table FactEmployeeWageHoursForAllocationNoWage
	lineageTag: f5c897b8-d3e4-492b-8433-6ec36197242a
	sourceLineageTag: [dbo].[FactEmployeeWageHoursForAllocationNoWageOutBound]

	measure 'AMT - Allocation Percentage Measure(NoWage)' = SUM(FactEmployeeWageHoursForAllocationNoWage[QNTY - Allocation Percentage])
		lineageTag: 07f703d9-9a4d-428d-89b9-2d6af9636165

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CNT - Count Distinct Employees(NoWage)' = DISTINCTCOUNT(FactEmployeeWageHoursForAllocationNoWage[HEXKeyEmployeeNoWage])
		formatString: 0
		lineageTag: 305d5e51-d45b-44d0-bc64-10238358b839

		changedProperty = Name

		changedProperty = IsHidden

	measure 'PM - PM Points Measure (NoWage)' = SUM(FactEmployeeWageHoursForAllocationNoWage[PM - PM Points])
		lineageTag: a99138a9-1e5c-4798-921f-575d78d47f0f

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'QNTY - Hours Measure (NoWage)' = SUM(FactEmployeeWageHoursForAllocationNoWage[QNTY - Hours])
		lineageTag: af18d087-8ac7-4386-b77a-07ee3ad81d09

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HEXKeyEmployeeNoWage
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: b495ecbf-933c-4a1d-9e77-f806770afa5d
		sourceLineageTag: HEXKeyEmployeeNoWage
		summarizeBy: none
		sourceColumn: HEXKeyEmployeeNoWage

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HEXKeyCalendarDateNoWage
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 56f1958e-8140-4175-b8d3-edfc7054f973
		sourceLineageTag: HEXKeyCalendarDateNoWage
		summarizeBy: none
		sourceColumn: HEXKeyCalendarDateNoWage

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HEXKeyLBCLocationNoWage
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 7749d0e6-310b-46f3-9e98-87c4c02e3157
		sourceLineageTag: HEXKeyLBCLocationNoWage
		summarizeBy: none
		sourceColumn: HEXKeyLBCLocationNoWage

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HEXKeyCombineCustomerNoWage
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 04247d2a-b22a-41f7-a7f8-fc5b900f521f
		sourceLineageTag: HEXKeyCombineCustomerNoWage
		summarizeBy: none
		sourceColumn: HEXKeyCombineCustomerNoWage

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HEXKeyEmployeeHistoryNoWage
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 35f14e07-d8b9-4c01-9b06-9279ac4d1cb4
		sourceLineageTag: HEXKeyEmployeeHistoryNoWage
		summarizeBy: none
		sourceColumn: HEXKeyEmployeeHistoryNoWage

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HEXKeySubService
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: e949b7ab-17d8-4453-ad22-87ade77cca9a
		sourceLineageTag: HEXKeySubService
		summarizeBy: none
		sourceColumn: HEXKeySubService

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HEXKeySubRegion
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 1b2c1e06-049a-40ad-8835-8b316a521dad
		sourceLineageTag: HEXKeySubRegion
		summarizeBy: none
		sourceColumn: HEXKeySubRegion

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HEXKeyAllocationMethodology
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: cc2c2219-896e-462b-be12-b1cbf45bcb87
		sourceLineageTag: HEXKeyAllocationMethodology
		summarizeBy: none
		sourceColumn: HEXKeyAllocationMethodology

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'QNTY - Hours'
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: 3c455ea7-5aba-4edc-82bf-bb8abc01e723
		sourceLineageTag: Hours
		summarizeBy: none
		sourceColumn: Hours

		changedProperty = Name

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'PM - PM Points'
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: fb15b54d-0684-410f-8a7c-143460e1a96c
		sourceLineageTag: PMPoints
		summarizeBy: none
		sourceColumn: PMPoints

		changedProperty = Name

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'DATE - PartitionMonth'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 7b335a28-2bea-46a8-92e9-16785672a464
		sourceLineageTag: PartitionMonth
		summarizeBy: none
		sourceColumn: PartitionMonth

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'IND - Allocation Methodolgy'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 5c2d8c0a-fc76-46f8-bccd-03155ad933af
		sourceLineageTag: AllocationMethodolgy
		summarizeBy: none
		sourceColumn: AllocationMethodolgy

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'QNTY - Allocation Percentage'
		dataType: double
		sourceProviderType: decimal(17, 8)
		lineageTag: 347a4792-b974-49ba-b841-03d17c0f22a5
		sourceLineageTag: AllocationPercentage
		summarizeBy: none
		sourceColumn: AllocationPercentage

		changedProperty = Name

		changedProperty = SummarizeBy

		changedProperty = IsHidden

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IND - Data Source'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: e5969c89-fad5-44ff-b9e7-17e78e1dbe71
		sourceLineageTag: DataSource
		summarizeBy: none
		sourceColumn: DataSource

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'IND - DepartmentI ndicator'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: d09ac889-ba46-4214-b03f-d3e894e1b693
		sourceLineageTag: DepartmentIndicator
		summarizeBy: none
		sourceColumn: DepartmentIndicator

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'IND - Allocation Percentage UN Allocated Ind'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 956c9e50-f1d1-4f29-910b-b13998c7a06c
		sourceLineageTag: AllocationPercentageUNAllocatedInd
		summarizeBy: none
		sourceColumn: AllocationPercentageUNAllocatedInd

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'AMT - Allocated Wage (USD)'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: cc7741c5-2266-471f-ba51-93e79d9603e2
		sourceLineageTag: AllocatedWageUSD
		summarizeBy: none
		sourceColumn: AllocatedWageUSD

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'IND - Indicator'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: e570f052-a756-4d09-a30a-c888059b0707
		sourceLineageTag: Indicator
		summarizeBy: none
		sourceColumn: Indicator

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'IND - GDPR Restricted'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 81ee7227-7978-49bd-adce-3550ed663ece
		sourceLineageTag: GDPRRestricted
		summarizeBy: none
		sourceColumn: GDPRRestricted

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column METADATA$ROW_ID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 759fe847-6cfd-47b9-87d2-50914b76fd3f
		sourceLineageTag: METADATA$ROW_ID
		summarizeBy: none
		sourceColumn: METADATA$ROW_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition FactEmployeeWageHoursForAllocationNoWage = entity
		mode: directLake
		source
			entityName: FactEmployeeWageHoursForAllocationNoWageOutBound
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = Name

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

