table FactSalesCostActual
	lineageTag: a9eaefd2-c596-4eb6-baab-205a3943a6ca
	sourceLineageTag: [dbo].[FactSalesCostActual]

	measure RevenueUSD =
			
			SUMX(
			    'FactSalesCostActual',
			    'FactSalesCostActual'[AMT - Exchange Rate To USD] * 'FactSalesCostActual'[AMT - Invoice Line Item Amount LC]
			)
		lineageTag: 0cbee338-1a05-4589-bcbb-f77e8c7f76f2

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - Allocation Percentage Measure(NoWage)' = ```
			SUM([QNTY - Employee Allocation Percentage])
			
			```
		lineageTag: 31a4b990-94c9-4f8b-a9eb-1a5cc9948c0e

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Overtime(Cost of Goods Sold)' =
			
			CALCULATE(
			    SUM(FactSalesCostActual[AMT - Exchange Rate To USD]),
			    FILTER(
			        DimGLAccountsDepartment,
			        DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" &&
			        DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" &&
			        DimGLAccountsDepartment[GL - GL Level 4] = "Overtime"
			    )
			) + 0
		lineageTag: b324be38-7b7a-4cc3-91b5-b30703c7faf4

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - % of Revenue(Cost of Goods Sold)' = ```
			
			DIVIDE(
			    [AMT - P&L Total Wages(Cost of Goods Sold)],
			    [AMT - P&L Net Sales],0
			)
			
			```
		lineageTag: fa31c086-e97a-4c80-985e-d4d0c4e0be17

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - Gross Margin %' = [AMT - P&L Net Sales] - [AMT - P&L Total COGS] + 0
		lineageTag: cfff4061-2bc9-48c5-b72e-8457c3513220

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - Mapped Cost Actual(USD)' = ```
			
			SUMX(
			    'FactSalesCostActual',
			    'FactSalesCostActual'[AMT - Mapped Cost Actual LC] *
			    IF(
			        ISBLANK('FactSalesCostActual'[AMT - Exchange Rate To USD]),
			        1,
			        'FactSalesCostActual'[AMT - Exchange Rate To USD]
			    )
			)
			
			```
		lineageTag: 504a83b2-d76b-40b3-83a7-a72590235cf1

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - Revenue (USD)' = ```
			
			SUMX(
			    'FactSalesCostActual',
			    'FactSalesCostActual'[AMT - Exchange Rate To USD] * 'FactSalesCostActual'[AMT - Invoice Line Item Amount LC]
			)
			
			```
		lineageTag: fbbcdfe0-515d-465f-8595-eb487f05e908

		changedProperty = IsHidden

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - Mapped Cost With Mapped Rate(USD)' =
			
			SUMX(
			    'FactSalesCostActual',
			    'FactSalesCostActual'[AMT - Mapped Cost LC] * 'FactSalesCostActual'[AMT - Exchange Rate To USD]
			)
		lineageTag: 85886c82-ba87-432e-acd1-49d7158f8337

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - Total Cost (USD)' =
			
			SUMX(
			    FactSalesCostActual,
			    FactSalesCostActual[AMT - Total Cost LC] * FactSalesCostActual[AMT - Exchange Rate To USD]
			)
		lineageTag: a6ad264a-db4d-41bb-8918-5adf8abbf8e6

		changedProperty = IsHidden

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - UnMapped Cost Actual(USD)' =
			SUMX(
			    FactSalesCostActual,'FactSalesCostActual'[AMT - UnMapped Cost Actual LC(W/O Hr)]* 'FactSalesCostActual' [AMT - Exchange Rate To USD])
		lineageTag: 6636525e-064c-4cfb-9baf-75c58ecb5300

		changedProperty = IsHidden

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - Unmapped Cost Actual(W/0 Hr+ W/o Cust)' =
			SUMX(
			    FactSalesCostActual,'FactSalesCostActual'[AMT - UnMapped Cost Actual LC(W/O Hr)]+'FactSalesCostActual'[AMT - Un Mapped Cost Actual LC(W/O Customer)])
		lineageTag: 24628691-a499-401b-bf43-aab646a542e9

		changedProperty = IsHidden

		changedProperty = Name

	measure 'AMT - Mapped Cost With Mapped Rate(USD) MA' = ```
			
			SUMX(
			    'FactSalesCostActual',
			    'FactSalesCostActual'[AMT - Mapped Cost LC] * 'FactSalesCostActual'[AMT - Exchange Rate To USD]
			)
			
			```
		lineageTag: d07151c5-420a-4a4b-b2b8-6f2b3ac81b5d

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L (Selling, General and Administrative)' = ```
			
			[AMT - P&L Total Selling Expence] + [AMT - P&L Total G&A]
			
			
			
			
			
			
			```
		lineageTag: c53da341-2e85-4bf3-b7cf-6ca1e19d6d0b

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L % of Revenue (Adjusted EBITA Pre-IC)' = ```
			DIVIDE([AMT - P&L Adjusted EBITA (Pre-IC)],[AMT - P&L Net Sales])+0  
			```
		lineageTag: 2066742e-2ec5-4358-b080-c947afcd586a

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L % of Revenue(Adjusted EBITDA)' = DIVIDE([AMT - P&L Adjusted EBITDA],[AMT - P&L Net Sales])+0
		lineageTag: c83c9db3-71c4-41fb-ac9f-aca97935e4b7

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L % of Revenue(SG&A)' = DIVIDE([AMT - Total P&L SG&A],[AMT - P&L Net Sales])+0
		lineageTag: fcf28cbe-7573-4d10-b2f2-5dcd9fed13ca

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Adjusted EBITA (Pre-IC)' = ( [AMT - P&L Gross Margin] - [AMT - Total P&L SG&A])
		lineageTag: 7865cb18-3698-4ae9-b810-1d249f7cff59

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Adjusted EBITDA' = [AMT - P&L Adjusted EBITA (Pre-IC)]-[AMT - P&L Incentive Compensation]
		lineageTag: ea630193-9185-4835-ac38-c6a69f9caf48

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Capitalization of IT Costs(Cost of Goods Sold)' =
			
			CALCULATE(
			    [AMT - Mapped Cost With Mapped Rate(USD)],
			    FILTER(
			        DimGLAccountsDepartment,
			        LEFT(DimGLAccountsDepartment[GL - GL Department Key], 11) = "69001499-71" ||
			        LEFT(DimGLAccountsDepartment[GL - GL Department Key], 11) = "69001499-76"
			    )
			) + 0
		lineageTag: 2d4df802-e2c8-4a05-bcdd-359c98656cac

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Capitalization of IT Costs(Selling Expence)' = ```
			
				   CALCULATE(
				   [AMT - Mapped Cost With Mapped Rate(USD)],
				   FILTER(
				   DimGLAccountsDepartment,
				   DimGLAccountsDepartment[GL - GL Department Key]= "69001499-80*")
				   )+0
			```
		lineageTag: fa220d98-a717-4eb2-81c9-aaed73b35f6e

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Cost of Goods Sold' =
			
			CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],
			FILTER(
			DimGLAccountsDepartment,
			DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold"))+0
		lineageTag: 4e167fe9-3aba-4a0e-b8a3-997cd9ed9b5f

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Net Sales'
		lineageTag: fe2f6517-2ecb-46bb-a96a-da59df36c55f

		changedProperty = Name

		changedProperty = IsHidden

		annotation 436ba87b-9c83-4389-a31b-ebd06a36be98 = {"Expression":null}

		annotation 277cc1b9-af89-4597-8e15-cacc25c0886b = To use special characters in a measure name, enclose the entire name in brackets ( [] ) and add a ] to any closing brackets in the name.

	measure 'AMT - P&L Freight(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3]= "Freight"))+0
		lineageTag: cbc89479-36e1-4b96-a169-0fdca0bfeeb6

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Freight(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Freight"))+0
		lineageTag: 99a738f5-6207-4ae0-8365-6387ac617e4c

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Freight(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Freight"))+0
		lineageTag: 594b76ae-03db-4937-8b31-b0a2abddb40c

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Freight(SG&A)' = [AMT - P&L Freight(G&A)]+[AMT - P&L Freight(Selling Expence)]
		formatString: 0
		lineageTag: 31b3ab4b-6615-4ae4-8ddd-3caaa78cf0af

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Gross Margin' = [AMT - P&L Net Sales] - [AMT - P&L Total COGS]+0
		lineageTag: b15cfaed-ce02-4baa-bafc-7207e9f4e18e

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Gross Sales' = ```
			
			CALCULATE(
			    [AMT - Revenue (USD)], 
			    FILTER(DimGLAccounts, DimGLAccounts[IND - Is Gross Sales] = "Yes")
			)
			
			```
		lineageTag: 3af70358-446d-4c0c-9d09-e0799494ff3d

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Health and Welfare(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Health and Welfare"))+0
		lineageTag: fa77a255-ed26-453f-b326-5d453a269a11

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Health and Welfare(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Health and Welfare"))+0
		lineageTag: ea65a437-c8d2-44e8-b6b7-f5d28346ad42

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Health and Welfare(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Health and Welfare"))+0
		lineageTag: 4fdc8fa9-f5cb-424d-95b7-ca50154dd751

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Health and Welfare(SG&A)' = [AMT - P&L Health and Welfare(G&A)]+[AMT - P&L Health and Welfare(Selling Expence)]
		formatString: 0
		lineageTag: 36983d69-9de3-4568-8fc6-85ba2561c6c3

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Incentive Compensation' =
			
			CALCULATE(
			    [AMT - Mapped Cost With Mapped Rate(USD)],
			    FILTER(
			        DimGLAccountsDepartment,
			        DimGLAccountsDepartment[GL - GL Level 2] = "Management Incentive Compensation"
			    )
			) + 0
		lineageTag: 74550f1a-ee60-495a-8c98-b8eecbd121eb

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Information System(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Information Systems"))+0
		lineageTag: 6df1f7ed-a0d7-4758-963c-997bda78e570

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Information Systems(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Information Systems"))+0
		lineageTag: f0e0ec8c-32b4-4866-b5b3-9e8187f5be8b

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - Variable Costs' = [AMT - P&L Total People Costs(Cost of Goods Sold)]  + [AMT - P&L Materials(Cost of Goods Sold)]+[AMT - P&L Total People Cost(Selling Expence)] + [AMT - P&L Freight(Cost of Goods Sold)]
		formatString: 0
		lineageTag: 3323ef40-8c2f-426b-9477-10b0e5d17816

		changedProperty = IsHidden

		changedProperty = Name

	measure 'AMT - P&L Information Systems(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Information Systems"))+0
		lineageTag: d89171fa-1136-44b4-a63b-999d565c566a

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Information Systems(SG&A)' = ```
			[AMT - P&L Information Systems(G&A)]+[AMT - P&L Information Systems(Selling Expence)]
			
			```
		formatString: 0
		lineageTag: 53f38aa9-208b-4db2-b1e1-ab19525ab820

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Management Incentive Taxes' = 0
		formatString: 0
		lineageTag: 1f06da08-7900-4c29-a6ed-172739bf6688

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Mapped Cost(2019)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimCalendarDate, DimCalendarDate[CAL - Year Number(YYYY)] = 2019))+0
		lineageTag: 1ece401b-846f-453a-bdee-982db9efaf36

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Mapped Cost(2020)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimCalendarDate, DimCalendarDate[CAL - Year Number(YYYY)] = 2020))+0
		lineageTag: 3b29bd28-5b72-4693-859b-50cc24a825f1

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Materials(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Materials"))+0
		lineageTag: 54518ff4-2b8f-490c-8d73-d9027f1cf292

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Materials(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Materials"))+0
		lineageTag: 3896b900-1a5c-4fce-9f90-3415c9b8f0d3

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Materials(SG&A)' = [AMT - P&L Materials(G&A)]+[AMT - P&L Materials(Selling Expence)]
		lineageTag: 1d9727c5-ca94-4fc0-a60d-d724c3269154

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Metrics' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Metrics"))+0
		lineageTag: 849a85b6-2ea7-4cf5-a116-da8e6776d5e0

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT – P&L Transfer People Costs (G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment, DimGLAccountsDepartment[GL - GL Department Key]= "69001498-81*" || DimGLAccountsDepartment[GL - GL Department Key]= "69001496-81*"))+0
		lineageTag: e809c640-26cc-49eb-a938-8453b1a4b313

		changedProperty = IsHidden

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Net Sales With No Gross Sales' =
			CALCULATE([AMT - Revenue (USD)]
			,FILTER(DimGLAccounts,DimGLAccounts[IND - Is Gross Sales]="No" && DimGLAccounts[IND - Is Net Sales] = "Yes"))
		lineageTag: 09f2794f-684e-4a30-a734-16ab23a6ec8d

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT – P&L Transfer People Costs (Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment, DimGLAccountsDepartment[GL - GL Department Key]= "69001498-80*" || DimGLAccountsDepartment[GL - GL Department Key]= "69001496-80*"))+0
		lineageTag: 3e52a969-2268-43e0-8863-4039cf4bff38

		changedProperty = IsHidden

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Non-People Costs(G&A)' = [AMT - P&L Outside Services(G&A)]+[AMT - P&L Materials(G&A)]+[AMT - P&L Freight(G&A)]+[AMT - P&L Rent(G&A)]+[AMT - P&L Utilities/Network/Phone(G&A)]+[AMT - P&L Information Systems(G&A)]+[AMT - P&L Repairs & Maintenance(G&A)]+[AMT - P&L Taxes and Duties(G&A)]+[AMT - P&L Other(G&A)]+[AMT - P&L Professional Fees(G&A)]
		lineageTag: b609a06c-05a1-4675-9d13-ceacacd3a7e6

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Non-People Costs(Selling Expence)' = [AMT - P&L Outside Services(Selling Expence)]+[AMT - P&L Materials(Selling Expence)]+[AMT - P&L Freight(Selling Expence)]+[AMT - P&L Rent(Selling Expence)]+[AMT - P&L Utilities/Network/Phone(Selling Expence)]+[AMT - P&L Information Systems(Selling Expence)]+[AMT - P&L Repairs & Maintenance(Selling Expence)]+[AMT - P&L Taxes and Duties(Selling Expence)]+[AMT - P&L Other(Selling Expence)]+[AMT - P&L Professional Fees(Selling Expence)]
		lineageTag: 1e8d008f-3a43-4a5c-98db-53a82ac2c40f

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Other Benefits(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Other Benefits"))+0
		lineageTag: 5a2cb474-fe11-483d-91f0-fa1f87d577d6

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Other Benefits(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Other Benefits"))+0
		lineageTag: 96db18a5-bcfc-475f-873f-b89b917016b4

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Other Benefits(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Other Benefits"))+0
		lineageTag: 23d468d9-4649-48d3-9ffb-524de14dd7c8

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Other Benefits(SG&A)' = [AMT - P&L Other Benefits(G&A)]+[AMT - P&L Other Benefits(Selling Expence)]
		formatString: 0
		lineageTag: 096916ed-fdee-45e9-8527-b62fc49ca8d1

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Other(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Other" ))+0
		lineageTag: b40b5d4f-14a2-4495-bc73-8aa391f1696a

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Other(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Other"))+0
		lineageTag: 5627d656-f82f-43ad-8bfb-683efe25f7c3

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Other(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Other"))+0
		lineageTag: 06963b57-8d30-4a4f-b1a3-0dc73a9ab7c7

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Other(SG&A)' = [AMT - P&L Other(G&A)]+[AMT - P&L Other(Selling Expence)]
		formatString: 0
		lineageTag: 19cfc375-a88d-4f0f-9b17-fc7c71474317

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Others(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Other" && DimGLAccountsDepartment[GL - GL Level 4] = "Other"))+0
		lineageTag: 5a7c40a1-35bc-453a-9962-2e1af2078208

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Others(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Other" && DimGLAccountsDepartment[GL - GL Level 4] = "Other"))+0
		lineageTag: eff0ceef-dadb-4a3f-857f-fc884c7e56a6

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Outside Services(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Outside Services"))+0
		lineageTag: fd8d7f10-b418-4690-b5a0-b88ebeda1a76

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Outside Services(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Outside Services"))+0
		lineageTag: cfe16ea0-fb5f-4a59-b622-bc2c3a8d830d

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Outside Services(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Outside Services"))+0
		lineageTag: 20a2091a-404e-4881-9a90-119cfeea922a

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Outside Services(SG&A)' = [AMT - P&L Outside Services(G&A)]+[AMT - P&L Outside Services(Selling Expence)]
		formatString: 0
		lineageTag: fbad3553-c89a-4b2d-996a-61d79928f3f9

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Overtime(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Overtime"))+0
		lineageTag: 071b4afe-1330-4ecd-9eba-5dd53e886a1f

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Overtime(SG&A)' = [AMT - P&L Overtime(G&A)] + [AMT - P&L Overtime(Selling Expence)]
		lineageTag: 7b2056d6-cfc4-4fe0-8680-fb71301fe6d9

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Payroll Taxes(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Payroll Taxes"))+0
		lineageTag: 25301df3-eafe-4dfb-a92a-e844557bf287

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Payroll Taxes(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Payroll Taxes"))+0
		lineageTag: 47aab86c-34c7-4095-a558-34d60c1cad8d

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Payroll Taxes(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Payroll Taxes"))+0
		lineageTag: 4507d0db-c4cb-497f-a0ed-0e2305b37c55

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Payroll Taxes(SG&A)' = [AMT - P&L Payroll Taxes(G&A)]+[AMT - P&L Payroll Taxes(Selling Expence)]
		formatString: 0
		lineageTag: 1d160225-02dc-4ee0-8380-8371094294a4

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Professional Fees(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Professional Fees"))+0
		lineageTag: e78fc2e1-cbf0-45de-b255-7303d7618c66

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Professional Fees(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Professional Fees"))+0
		lineageTag: 32fad3c4-8586-4a9d-99b1-5f4ed03e4694

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Rent(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Rent"))+0
		lineageTag: cc8083f9-cf8e-4091-987e-04f75d897231

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Rent(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Rent"))+0
		lineageTag: b5371d9f-254b-4a31-bbec-617734c4d233

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Rent(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Rent"))+0
		lineageTag: ba527f4c-e320-4788-a76d-dec88c295b92

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Rent(SG&A)' = [AMT - P&L Rent(G&A)]+[AMT - P&L Rent(Selling Expence)]
		formatString: 0
		lineageTag: 0704d068-3ade-4ac5-a411-8ca85d552f04

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Repairs & Maintenance(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Repairs & Maintenance"))+0
		lineageTag: 36af8a8a-7f12-46a2-86a5-76d4ab114bcf

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Repairs & Maintenance(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Repairs & Maintenance"))+0
		lineageTag: d1bebddc-2fcc-414a-8194-74cef388a623

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Repairs & Maintenance(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Repairs & Maintenance"))+0
		lineageTag: c9a37b7f-d8fc-4f32-92de-d62f74740a58

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Repairs & Maintenance(SG&A)' = [AMT - P&L Repairs & Maintenance(G&A)]+[AMT - P&L Repairs & Maintenance(Selling Expence)]
		formatString: 0
		lineageTag: 389a4cb7-6804-4f04-bdc1-e3c50fb74be2

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Sales Incentive(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Non-Management Incentive"))+0
		lineageTag: c906498b-af2d-4843-adff-73cfedebc08d

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Sales Incentive(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Non-Management Incentive"))+0
		lineageTag: ba05bfa0-b9f4-4848-bdd5-e0b3cf5934ac

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Sales Incentive(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Non-Management Incentive"))+0
		lineageTag: 6f404104-5d76-478a-86d2-c03e0ccb8694

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Utilities/Network/Phone(SG&A)' = [AMT - P&L Utilities/Network/Phone(G&A)]+[AMT - P&L Utilities/Network/Phone(Selling Expence)]
		formatString: 0
		lineageTag: d4fb0f32-19d4-4279-aa33-d859e067f84a

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Sales Incentive(SG&A)' = [AMT - P&L Sales Incentive(G&A)]+[AMT - P&L Sales Incentive(Selling Expence)]
		formatString: 0
		lineageTag: fe879e87-b2ba-43ba-8ba7-c2e043e1f0c6

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Severences(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Severences"))+0
		lineageTag: 732111fa-71ec-488e-a9ad-94949d43d48f

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Severences(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Severences"))+0
		lineageTag: 1dc9b1f8-c51a-4f4e-a1fc-c3593c6a3195

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Severences(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Severences"))+0
		lineageTag: fa48a975-afe4-45ff-8a47-e49d85a1bcdd

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Severences(SG&A)' = [AMT - P&L Severences(G&A)] + [AMT - P&L Severences(Selling Expence)]
		formatString: 0
		lineageTag: e248d7a7-3a47-4544-8b5a-e8d680a05aba

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L T&E(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "T&E"))+0
		lineageTag: 202baef4-1792-4bd9-aa36-c3b80ef0103b

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L T&E(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "T&E"))+0
		lineageTag: 39ceeaef-eab0-4ec1-82ab-6b6ca5133765

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L T&E(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "T&E"))+0
		lineageTag: c0b980c3-a489-43fd-affa-9d10ae521112

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L T&E(SG&A)' = [AMT - P&L T&E(G&A)]+[AMT - P&L T&E(Selling Expence)]
		formatString: 0
		lineageTag: af2b5af4-576e-43de-a6bd-ce7f1fde7b14

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Taxes & Duties(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Taxes and Duties"))+0
		lineageTag: 0fdd4f90-0e3f-4294-8655-c3ad1f275e7f

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Taxes and Duties(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Taxes and Duties"))+0
		lineageTag: 4e99a758-cb16-4764-896f-8d9294bb0c22

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Taxes and Duties(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Taxes and Duties"))+0
		lineageTag: 51b40095-27ec-4715-8afb-74fdebd61704

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Taxes and Duties(SG&A)' = [AMT - P&L Taxes and Duties(G&A)]+[AMT - P&L Taxes and Duties(Selling Expence)]
		formatString: 0
		lineageTag: 3aaa5750-83d4-400d-8874-5425f6e731c0

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Temp Labor/Freelancer(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Temp Labor/Freelancer"))+0
		lineageTag: d066506f-edd0-4b02-9808-a9157e0114e1

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Temp Labor/Freelancer(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Temp Labor/Freelancer"))+0
		lineageTag: f5ebefc8-6e02-4fdc-ba9a-91b1302222fb

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Temp Labor/Freelancer(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Temp Labor/Freelancer"))+0
		lineageTag: 1fdafd9a-b22c-4d67-9c1c-25458f4fa414

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Temp Labor/Freelancer(SG&A)' = [AMT - P&L Temp Labor/Freelancer(G&A)]+[AMT - P&L Temp Labor/Freelancer(Selling Expence)]
		formatString: 0
		lineageTag: 1189db2e-70ca-40e3-bcac-c155e4c1aaa2

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Total COGS' = ```
			
			CALCULATE(
			    [AMT - Mapped Cost With Mapped Rate(USD)],      
			    FILTER(
			        DimGLAccountsDepartment,
			        DimGLAccountsDepartment[GL - GL Level 2]= "Cost of Goods Sold"
			    )
			) + 0
			
			
			
			```
		lineageTag: 05c27230-4bc5-49d6-8277-c3fd705a7e0e

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Total G&A' =
			
			CALCULATE(
			   [AMT - Mapped Cost With Mapped Rate(USD)],
			   FILTER(
			   DimGLAccountsDepartment,
			   DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense"
			   )
			 )+0
		lineageTag: d9309695-4cd2-44bb-ab93-c81ea3de0423

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Total People Cost(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost"))+0
		lineageTag: 9749f6b8-ea98-4703-80ce-3a36addbe5b2

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Total People Cost(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost"))+0
		lineageTag: eb33e986-893e-4470-9a89-59c2dcfcc32d

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Total People Cost(SG&A)' = [AMT - P&L Total People Cost(Selling Expence)]+[AMT - P&L Total People Cost(G&A)]
		formatString: 0
		lineageTag: 1ad8b5c2-9ed9-4654-93df-605f82572fdc

		changedProperty = Name

		changedProperty = IsHidden

	measure 'AMT - P&L Total People Costs(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost"))+0
		lineageTag: 68e8009f-27cc-4549-b78f-987936657d97

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Total Selling Expence' = ```
			
			CALCULATE(
			    [AMT - Mapped Cost With Mapped Rate(USD)],
			    FILTER(
			        DimGLAccountsDepartment,
			        DimGLAccountsDepartment[GL - GL Level 2] = "Selling Expense"
			    )
			) + 0
			
			```
		lineageTag: 0fee7fa3-1896-4426-b57b-6fbbc52d46b7

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Total Wages(Cost of Goods Sold)' = ```
			
			CALCULATE(
			    [AMT - Mapped cost with Mapped Rate(USD)],
			    FILTER(
			        DimGLAccountsDepartment,
			        DimGLAccountsDepartment[GL - GL Level 2] = "Cost of Goods Sold" &&
			        DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" &&
			        DimGLAccountsDepartment[GL - GL Level 4] = "Wages"
			    )
			) + 0
			
			
			```
		lineageTag: 88b378ce-c782-4482-a2e0-fade6189a775

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Utilities/Network/Phone(Cost of Goods Sold)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Utilities/Network/Phone"))+0
		lineageTag: bf319661-5d6d-4abd-bd14-76940dcea308

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Utilities/Network/Phone(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Utilities/Network/Phone"))+0
		lineageTag: 60c17618-4bfa-4213-8dc6-520fec4f435f

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Utilities/Network/Phone(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Utilities/Network/Phone"))+0
		lineageTag: 59f1741e-fe74-48e6-b89d-bf4b7241216f

		changedProperty = Name

		changedProperty = IsHidden

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - Total P&L SG&A' = ```
			
			[AMT - P&L Total Selling Expence] + [AMT - P&L Total G&A]
			
			```
		formatString: 0
		lineageTag: 0bf37494-522d-41ae-a336-17e61dedc192

		changedProperty = IsHidden

		changedProperty = Name

	measure 'AMT – Revenue (USD) PY' = ```
			
			CALCULATE(
			    [AMT - Revenue (USD)],
			    FILTER(
			        DimCalendarDate,
			        YEAR(DimCalendarDate[DATE - Calendar Date]) = YEAR(TODAY()) - 1
			    )
			)
			
			```
		lineageTag: eac936b1-d837-4290-9ef0-2db523133fec

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT – Revenue (USD) PYTD' =
			
			CALCULATE(
			    [AMT - Revenue (USD)],
			    DATESBETWEEN(
			        DimCalendarDate[DATE - Calendar Date],
			        DATE(YEAR(TODAY()) - 1, 1, 1),
			        DATE(YEAR(TODAY()) - 1, MONTH(TODAY()), DAY(TODAY()))
			    )
			)
		lineageTag: 59310b92-c302-498b-b470-61de2f1e4590

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT – Revenue (USD) R12' = ```
			
			CALCULATE(
			    (FactSalesCostActual[AMT - Revenue (USD)]),
			    DATESINPERIOD(
			        DimCalendarDate[DATE - Calendar Date],
			        EOMONTH(TODAY(), -1),
			        -12,
			        MONTH
			    )
			)
			
			```
		lineageTag: 8b6d3f30-689d-48ac-911e-e01d821bf10a

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT – Revenue (USD) R6' = ```
			
			CALCULATE(
			    (FactSalesCostActual[AMT - Revenue (USD)]),
			    DATESINPERIOD(
			        DimCalendarDate[DATE - Calendar Date],
			        TODAY(),
			        -6,
			        MONTH
			    )
			)
			
			```
		lineageTag: 7a64deba-7299-48af-a459-966070a8b946

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - % of Revenue(Cost of Goods Sold)' = ```
			
			 DIVIDE(
			        [MAPPED AMT - P&L Total Wages(Cost of Goods Sold)],
			        [MAPPED AMT - P&L Net Sales]
			    ) + 0
			```
		lineageTag: ad0f6517-be30-4e23-9c80-cd88ae842a35

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L (Selling, General and Administrative)' = [MAPPED AMT - P&L Total Selling Expence] + [MAPPED AMT - P&L Total G&A]
		lineageTag: 112289a4-d86d-4d08-9b5c-17412f967827

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L % of Revenue (Adjusted EBITA Pre-IC)' = DIVIDE([MAPPED AMT - P&L Adjusted EBITA (Pre-IC)],[MAPPED AMT - P&L Net Sales])+0
		lineageTag: a904bfee-7924-43dd-a80d-715f3e09a3fa

		changedProperty = Name

	measure 'MAPPED AMT - P&L % of Revenue(Adjusted EBITDA)' = DIVIDE([MAPPED AMT - P&L Adjusted EBITDA],[MAPPED AMT - P&L Net Sales])+0
		lineageTag: c16eddf6-59fd-4f06-a7a5-889641a3a7ba

		changedProperty = Name

	measure 'MAPPED AMT - P&L % of Revenue(SG&A)' = DIVIDE([MAPPED AMT - Total P&L SG&A],[MAPPED AMT - P&L Net Sales])+0
		lineageTag: d24a7805-5768-4208-ae38-1b1c6b36c96e

		changedProperty = Name

	measure 'MAPPED AMT - P&L Adjusted EBITA (Pre-IC)' = [MAPPED AMT - P&L Gross Margin] - [MAPPED AMT - Total P&L SG&A]
		lineageTag: e0c6d19d-7f66-464d-a47f-3ebedabb71ae

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Adjusted EBITDA' = [MAPPED AMT - P&L Adjusted EBITA (Pre-IC)]-[MAPPED AMT - P&L Incentive Compensation]
		lineageTag: 001a68d7-4ab7-4b1d-8b68-ddb793395c38

		changedProperty = Name

	measure 'MAPPED AMT - P&L Cost of Goods Sold' =
			
			CALCULATE(
			    SUMX(
			        FactSalesCostActual,
			        FactSalesCostActual[AMT - Mapped Cost Actual LC] +
			        FactSalesCostActual[AMT - Unmapped Cost Actual(W/0 Hr+ W/o Cust)]
			    ),
			    FILTER(
			        DimGLAccountsDepartment,
			        DimGLAccountsDepartment[GL - GL Level 2] = "Cost of Goods Sold"
			    )
			) + 0
		lineageTag: 88244b0d-7fe4-4e38-be62-4bf430045a69

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Freight(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3]= "Freight"))+0
		lineageTag: ef812b01-72ae-475b-b5a9-a04ee34c7047

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Freight(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Freight"))+0
		lineageTag: 884935a9-da9d-4282-9079-7ef708c64cad

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Freight(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Freight"))+0
		lineageTag: a1f2eca1-604c-40ce-9836-4a900d25c219

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Gross Margin' = [MAPPED AMT - P&L Net Sales] - [MAPPED AMT - P&L Total COGS]+0
		lineageTag: 754f4e98-ff09-44f8-b919-12115d269ce2

		changedProperty = Name

	measure 'MAPPED AMT - P&L Health and Welfare(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Health and Welfare"))+0
		lineageTag: bb835afa-c3b5-4206-9b47-31dca31a2fba

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Health and Welfare(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Health and Welfare"))+0
		lineageTag: 19fc6a6e-d1c3-4f20-8a40-0da5a5810707

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Health and Welfare(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Health and Welfare"))+0
		lineageTag: d67c9948-d1bc-4b51-896c-52f5a991bfa7

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Health and Welfare(SG&A)' = [MAPPED AMT - P&L Health and Welfare(G&A)]+[MAPPED AMT - P&L Health and Welfare(Selling Expence)]
		lineageTag: 72802fd7-5de7-466e-a9aa-ea6f3f1b8671

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Incentive Compensation' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Management Incentive Compensation"))+0
		lineageTag: 5f40fd8d-a772-4cf2-822e-cf4267cca7e5

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Information System(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Information Systems"))+0
		lineageTag: 160767df-26d4-4dbe-95ec-9a0213424c79

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Information Systems(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Information Systems"))+0
		lineageTag: e0de2413-589e-47d8-bf5f-126f5a69e18b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Other Benefits(SG&A)' = [MAPPED AMT - P&L Other Benefits(G&A)]+[MAPPED AMT - P&L Other Benefits(Selling Expence)]
		lineageTag: d724c6e5-574f-4b48-883c-c0ce422a4117

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Information Systems(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Information Systems"))+0
		lineageTag: 915fefce-dcb9-415c-9e19-a6b00993da9e

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Information Systems(SG&A)' = [MAPPED AMT - P&L Information Systems(G&A)]+[MAPPED AMT - P&L Information Systems(Selling Expence)]
		lineageTag: 76d1f42e-0b66-4dea-bb92-7481b304ad14

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Management Incentive Taxes' = 0
		formatString: 0
		lineageTag: f7aa65ef-bfa7-40ff-b0b6-58229847efed

		changedProperty = Name

	measure 'MAPPED AMT - P&L Mapped Cost(2019)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimCalendarDate, DimCalendarDate[CAL - Year Number(YYYY)] = 2019))+0
		lineageTag: 6d58dd33-8bc8-4999-86d4-7638e7ebd247

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Mapped Cost(2020)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimCalendarDate, DimCalendarDate[CAL - Year Number(YYYY)] = 2020))+0
		lineageTag: 08bac70f-7e22-4f22-82c0-19537653106a

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Other(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Other" && DimGLAccountsDepartment[GL - GL Level 4] = "Other"))+0
		lineageTag: d55fe0e2-2429-432a-932e-2f56fe8f15b2

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Materials(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Materials"))+0
		lineageTag: 4df3e375-2184-4ae5-a99d-e1e357cff402

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Materials(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Materials"))+0
		lineageTag: a51ca5ce-1fe6-4771-bf65-0b40c7bdafff

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Materials(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Materials"))+0
		lineageTag: 55a397bb-69b3-4690-a0be-49c0a65bd76a

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Materials(SG&A)' = [MAPPED AMT - P&L Materials(G&A)]+[MAPPED AMT - P&L Materials(Selling Expence)]
		lineageTag: 2d76fee4-1125-424b-8397-dc1ed4c0e48c

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Metrics' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Metrics"))+0
		lineageTag: 50287588-ad9a-4f81-aaba-dc64d7a451d9

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Non-People Costs(G&A)' = [MAPPED AMT - P&L Outside Services(G&A)]+[MAPPED AMT - P&L Materials(G&A)]+[MAPPED AMT - P&L Freight(G&A)]+[MAPPED AMT - P&L Rent(G&A)]+[MAPPED AMT - P&L Utilities/Network/Phone(G&A)]+[MAPPED AMT - P&L Information Systems(G&A)]+[MAPPED AMT - P&L Repairs & Maintenance(G&A)]+[MAPPED AMT - P&L Taxes and Duties(G&A)]+[MAPPED AMT - P&L Other(G&A)]+[MAPPED AMT - P&L Professional Fees(G&A)]
		lineageTag: b3bdd9fa-8293-490e-b587-afdc6fa0e1c5

		changedProperty = Name

	measure 'MAPPED AMT - P&L Non-People Costs(Selling Expence)' = [MAPPED AMT - P&L Outside Services(Selling Expence)]+[MAPPED AMT - P&L Materials(Selling Expence)]+[MAPPED AMT - P&L Freight(Selling Expence)]+[MAPPED AMT - P&L Rent(Selling Expence)]+[MAPPED AMT - P&L Utilities/Network/Phone(Selling Expence)]+[MAPPED AMT - P&L Information Systems(Selling Expence)]+[MAPPED AMT - P&L Repairs & Maintenance(Selling Expence)]+[MAPPED AMT - P&L Taxes and Duties(Selling Expence)]+[MAPPED AMT - P&L Other(Selling Expence)]+[MAPPED AMT - P&L Professional Fees(Selling Expence)]
		lineageTag: 094fc4a4-86b4-4b56-a4fd-5a8dd14df3c4

		changedProperty = Name

	measure 'MAPPED AMT - P&L Non-People Costs(SG&A)' = [MAPPED AMT - P&L Non-People Costs(G&A)]+[MAPPED AMT - P&L Non-People Costs(Selling Expence)]
		formatString: 0
		lineageTag: b5439393-8efd-4c3d-aa1b-bbaaab370275

		changedProperty = Name

	measure 'MAPPED AMT - P&L Other Benefits(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Other Benefits"))+0
		lineageTag: ecab7d04-cec2-4326-a56e-c760d43a3959

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Other Benefits(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Other Benefits"))+0
		lineageTag: 025254a1-7dfe-4c94-9e1a-7bde96abc9d0

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Other Benefits(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Other Benefits"))+0
		lineageTag: 59f61bab-b28e-4f09-b815-2ba15f26028d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Other(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Other"))+0
		lineageTag: ea48d972-3114-4f4c-8e3e-72dfd57ab966

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Other(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Other"))+0
		lineageTag: f449a953-dad8-4290-9195-368af1f0f197

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Other(SG&A)' = [MAPPED AMT - P&L Other(G&A)]+[MAPPED AMT - P&L Other(Selling Expence)]
		lineageTag: 7870fd00-9da2-471c-b3ac-80aeb2190c81

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Others(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Other"))+0
		lineageTag: f2d7bdc9-9e2c-4b36-8886-16565c3f38f4

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Outside Services(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Outside Services"))+0
		lineageTag: 9ee7dd44-f1ad-40d6-b264-0bd2ed32bece

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Outside Services(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Outside Services"))+0
		lineageTag: 1622e473-668f-4838-a977-40425458f86c

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Outside Services(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Outside Services"))+0
		lineageTag: 50b1b051-5bc8-4fd5-95fd-160d8ac01935

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Overtime(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Overtime"))+0
		lineageTag: d57265b8-5dca-4081-8f76-15187e04f943

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Overtime(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Overtime"))+0
		lineageTag: 0a46a807-efc3-4f2e-bea9-1e8548b2037c

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Overtime(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Overtime"))+0
		lineageTag: 9b976943-ff12-470e-afb5-30b8b20c4f72

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Overtime(SG&A)' = [MAPPED AMT - P&L Overtime(G&A)] + [MAPPED AMT - P&L Overtime(Selling Expence)]
		lineageTag: 4a8b5a53-a79b-4580-82df-007809612325

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Payroll Taxes(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Payroll Taxes"))+0
		lineageTag: 47cc3a25-d746-4a58-bc10-3ed29be5d68b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Payroll Taxes(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Payroll Taxes"))+0
		lineageTag: 0f8e8389-eff4-4942-a539-d9e960eeea15

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Payroll Taxes(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Payroll Taxes"))+0
		lineageTag: d3fa7327-8c43-4a2d-b2b6-497ef633c7ec

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Payroll Taxes(SG&A)' = [MAPPED AMT - P&L Payroll Taxes(G&A)]+[MAPPED AMT - P&L Payroll Taxes(Selling Expence)]
		lineageTag: d770e0b9-d47b-489e-b7e1-fe7bde09ea18

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Professional Fees(Cost of Goods Sold)' =
			CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),
			FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3]= "Professional Fees"))+0
		lineageTag: e369ea4a-f8b9-45e5-9ea5-7d9886bcfc28

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Professional Fees(G&A)' =
			CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),
			FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Professional Fees"))+0
		lineageTag: e794a7b1-b3c2-4c27-bdd6-3a3db19311f4

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Professional Fees(Selling Expence)' =
			
			CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),
			FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Professional Fees"))+0
		lineageTag: 4c85ccc6-8197-417e-a0fa-40e64cce155d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Professional Fees(SG&A)' = [MAPPED AMT - P&L Professional Fees(G&A)]+[MAPPED AMT - P&L Professional Fees(Selling Expence)]
		lineageTag: e2175322-014d-4268-bf2b-142045f11de7

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Rent(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Rent"))+0
		lineageTag: 69d8407e-7ef6-4c0f-b6b7-4f405479e56b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Rent(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Rent"))+0
		lineageTag: 96cb9a91-cbc2-4b0a-a72a-d5d5bdddf84b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Rent(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Rent"))+0
		lineageTag: 474685a7-d127-4de4-88cf-25bf9ee781b7

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Rent(SG&A)' = [MAPPED AMT - P&L Rent(G&A)]+[MAPPED AMT - P&L Rent(Selling Expence)]
		lineageTag: 40cba609-0e68-4e21-80be-06d30bd6c33b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Repairs & Maintenance(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Repairs & Maintenance"))+0
		lineageTag: 66019f6e-f202-47c3-8400-1f7a2ece63a2

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Repairs & Maintenance(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Repairs & Maintenance"))+0
		lineageTag: b8f92c2a-2e4b-4e0d-8ced-4160aa1ccb5b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Repairs & Maintenance(SG&A)' = [MAPPED AMT - P&L Repairs & Maintenance(G&A)]+[MAPPED AMT - P&L Repairs & Maintenance(Selling Expence)]
		lineageTag: fd0d0e97-f669-4ac1-a373-362cf33c5a08

		changedProperty = Name

	measure 'MAPPED AMT - P&L Sales Incentive(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Non-Management Incentive"))+0
		lineageTag: a21aec0a-77c3-4267-93fe-19f964aef50d

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Sales Incentive(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Non-Management Incentive"))+0
		lineageTag: c6f023c0-feda-4656-b29c-4387222b0b98

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Sales Incentive(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Non-Management Incentive"))+0
		lineageTag: 6a1b0ba4-7745-4aeb-938e-ec4b0d51fd79

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Sales Incentive(SG&A)' = [MAPPED AMT - P&L Sales Incentive(G&A)]+[MAPPED AMT - P&L Sales Incentive(Selling Expence)]
		lineageTag: b2adb9e9-5bcb-4655-90a6-5d93a4ad6b72

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Severences(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Severences"))+0
		lineageTag: e71eac24-ee01-45f7-9211-ad887084bace

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Severences(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Severences"))+0
		lineageTag: 53529aca-9db2-4242-ba04-94c11c59a3bd

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Severences(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Severences"))+0
		lineageTag: d5b29faa-8c07-44cf-8e2f-740a73078408

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Severences(SG&A)' = [MAPPED AMT - P&L Severences(G&A)] + [MAPPED AMT - P&L Severences(Selling Expence)]
		lineageTag: 88f1055a-2946-457a-abd4-364ffafc7515

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L T&E(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "T&E"))+0
		lineageTag: 929c4ba7-fbff-4515-8eb5-01d53760f653

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L T&E(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "T&E"))+0
		lineageTag: 0d455058-b768-47e7-8e57-c7ce42bf2ce6

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L T&E(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "T&E"))+0
		lineageTag: 9befe230-c577-4eac-b228-61846c4f660c

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L T&E(SG&A)' = [MAPPED AMT - P&L T&E(G&A)]+[MAPPED AMT - P&L T&E(Selling Expence)]
		lineageTag: 7ac8ca63-e2f4-4fcc-bbd1-5366e5d92635

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Taxes & Duties(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Taxes and Duties"))+0
		lineageTag: d22b31a5-c4c6-44c9-908d-254313643f54

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Taxes and Duties(G&A)' = ```
			CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Taxes and Duties"))+0
			
			```
		lineageTag: 5d5cb121-63a7-40e4-bc4f-ca81afcf5809

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Taxes and Duties(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Taxes and Duties"))+0
		lineageTag: 1dd104a8-3da2-4070-b188-da455a43ca68

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Taxes and Duties(SG&A)' = [MAPPED AMT - P&L Taxes and Duties(G&A)]+[MAPPED AMT - P&L Taxes and Duties(Selling Expence)]
		lineageTag: 7768a460-7768-4931-b8ae-55504c88680c

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Temp Labor/Freelancer(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Temp Labor/Freelancer"))+0
		lineageTag: 49758431-1e5c-4770-85de-32d23cf3d5bf

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Temp Labor/Freelancer(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Temp Labor/Freelancer"))+0
		lineageTag: e11e936b-9846-4757-9e8d-4ccb16d40285

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Temp Labor/Freelancer(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3]= "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Temp Labor/Freelancer"))+0
		lineageTag: ac0d5da7-b1e5-4b21-a58d-d0fe702c1785

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Temp Labor/Freelancer(SG&A)' = [MAPPED AMT - P&L Temp Labor/Freelancer(G&A)]+[MAPPED AMT - P&L Temp Labor/Freelancer(Selling Expence)]
		lineageTag: 62aa71bd-7585-4ea1-b686-c173eda39abb

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Total COGS' =
			
			CALCULATE('FactSalesCostActual'[AMT - Mapped Cost Actual LC(M)] +
			        FactSalesCostActual[AMT - Unmapped Cost Actual(W/0 Hr+ W/o Cust)],
			    DimGLAccountsDepartment[GL - GL Level 2] = "Cost of Goods Sold"
			) + 0
		lineageTag: d883c6fd-10e7-44a8-ac79-766dab914a24

		changedProperty = Name

	measure 'MAPPED AMT - P&L Total G&A' =
			
			SUMX(
			    'FactSalesCostActual',
			    COALESCE('FactSalesCostActual'[AMT - Mapped Cost Actual LC], 0) +
			    COALESCE('FactSalesCostActual'[AMT - Unmapped Cost Actual(W/0 Hr+ W/o Cust)], 0)
			)
		lineageTag: c1db2fe4-702f-4a15-b699-6e1f3a428605

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Total Incentive Compensation' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Management Incentive Compensation"))+0
		lineageTag: d6b72b3b-cf13-42b3-a52c-6757de1a2b16

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Total People Cost(G&A)' =
			
			CALCULATE(
			    SUMX(
			        FactSalesCostActual,
			        FactSalesCostActual[AMT - Mapped Cost Actual LC] +
			        FactSalesCostActual[AMT - Unmapped Cost Actual(W/0 Hr+ W/o Cust)]
			    ),
			    FILTER(
			        DimGLAccountsDepartment,
			        DimGLAccountsDepartment[GL - GL Level 2] = "General and Administrative Expense" &&
			        DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost"
			    )
			) + 0
		lineageTag: 4297ef1f-e7d1-4e6f-9d13-10ba8a8f887c

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Total People Cost(Selling Expence)' = ```
			
			CALCULATE( 
			    SUMX(
			        FactSalesCostActual,
			        FactSalesCostActual[AMT - Mapped Cost Actual LC] + 
			        FactSalesCostActual[AMT - Unmapped Cost Actual(W/0 Hr+ W/o Cust)]
			    ),
			    FILTER(
			        DimGLAccountsDepartment,
			        DimGLAccountsDepartment[GL - GL Level 2] = "Selling Expense" &&
			        DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost"
			    )
			) + 0
			```
		lineageTag: 28249603-6263-4c3b-9a76-4b5d4a341a8a

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Total People Cost(SG&A)' = [MAPPED AMT - P&L Total People Cost(Selling Expence)]+[MAPPED AMT - P&L Total People Cost(G&A)]
		formatString: 0
		lineageTag: 6e91eed1-e89a-42f7-abd8-9f9645574545

		changedProperty = Name

	measure 'MAPPED AMT - P&L Total People Costs(Cost of Goods Sold)' =
			
			CALCULATE(
			    SUMX(
			        FactSalesCostActual,
			        FactSalesCostActual[AMT - Mapped Cost Actual LC] +
			        FactSalesCostActual[AMT - Unmapped Cost Actual(W/0 Hr+ W/o Cust)]
			    ),
			    FILTER(
			        DimGLAccountsDepartment,
			        DimGLAccountsDepartment[GL - GL Level 2] = "Cost of Goods Sold" &&
			        DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost"
			    )
			) + 0
		lineageTag: d1a66963-eeca-47b5-a3df-628a5308acfe

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Total Selling Expence' =
			
			CALCULATE(
			    [AMT - Mapped Cost Actual(USD)],
			    FILTER(
			        DimGLAccountsDepartment,
			        DimGLAccountsDepartment[GL - GL Level 2] = "Selling Expense"
			    )
			) +
			CALCULATE(
			    [AMT - Unmapped Cost Actual(W/0 Hr+ W/o Cust)],
			    FILTER(
			        DimGLAccountsDepartment,
			        DimGLAccountsDepartment[GL - GL Level 2] = "Selling Expense"
			    )
			) + 0
		lineageTag: d220dad0-853f-49c8-921d-570217c17651

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Total Third Party Labor(Cost of Goods Sold)' =
			
			CALCULATE(
			    SUMX(
			        FactSalesCostActual,
			        FactSalesCostActual[AMT - Mapped Cost Actual LC] +
			        FactSalesCostActual[AMT - Unmapped Cost Actual(W/0 Hr+ W/o Cust)]
			    ),
			    FILTER(
			        DimGLAccountsDepartment,
			        DimGLAccountsDepartment[GL - GL Level 2] = "Cost of Goods Sold" &&
			        DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" &&
			        DimGLAccountsDepartment[GL - GL Level 4] = "Third Party Labor"
			    )
			)
		lineageTag: a7db6b4d-508d-4c17-a3c5-5a407fd3d420

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Total Wages(Cost of Goods Sold)' =
			
			CALCULATE(
			    SUMX(
			        FactSalesCostActual,
			        FactSalesCostActual[AMT - Mapped Cost Actual LC] +
			        FactSalesCostActual[AMT - Unmapped Cost Actual(W/0 Hr+ W/o Cust)]
			    ),
			    FILTER(
			        DimGLAccountsDepartment,
			        DimGLAccountsDepartment[GL - GL Level 2] = "Cost of Goods Sold" &&
			        DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" &&
			        DimGLAccountsDepartment[GL - GL Level 4] = "Wages"
			    )
			)
		lineageTag: 312c08c7-5b3b-4418-a355-5f5431d701ba

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Total Wages(Selling Expence)' = ```
			
			CALCULATE(
			    SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]) + 
			    SUM([AMT - UnMapped Cost Actual LC(W/O Hr)]),
			    FILTER(
			        DimGLAccountsDepartment,
			        DimGLAccountsDepartment[GL - GL Level 2] = "Selling Expense" &&
			        DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" &&
			        DimGLAccountsDepartment[GL - GL Level 4] = "Wages"
			    )
			) + 0
			```
		lineageTag: 4d27d360-aed8-4aee-8252-1fd66467e7fc

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Total Wages(SG&A)' = [MAPPED AMT - P&L Total Wages(G&A)]+[MAPPED AMT - P&L Total Wages(Selling Expence)]
		lineageTag: 5131adb1-327d-4df2-ba6b-446809caeb7e

		changedProperty = Name

	measure 'MAPPED AMT - P&L Utilities/Network/Phone(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Cost of Goods Sold" && DimGLAccountsDepartment[GL - GL Level 3] = "Utilities/Network/Phone"))+0
		lineageTag: bc60a853-73bf-4cb9-8dce-9e85f94ee595

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Utilities/Network/Phone(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Utilities/Network/Phone"))+0
		lineageTag: 71d8d344-aef4-4232-a4d8-5ac94943da2e

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Utilities/Network/Phone(Selling Expence)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Utilities/Network/Phone"))+0
		lineageTag: c7d29167-d2cc-4e93-bcad-ae02d8d02287

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Utilities/Network/Phone(SG&A)' = [MAPPED AMT - P&L Utilities/Network/Phone(G&A)]+[MAPPED AMT - P&L Utilities/Network/Phone(Selling Expence)]
		lineageTag: 7f593ac7-a19c-42ac-b979-b63c6ea36cfc

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - Total P&L SG&A' = CALCULATE([MAPPED AMT - P&L Total Selling Expence]) + CALCULATE([MAPPED AMT - P&L Total G&A])
		formatString: 0
		lineageTag: d50d8ea7-fd2d-4462-bb4e-d0c99f114525

		changedProperty = Name

	measure 'MAPPED AMT – P&L Transfer People Costs (Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment, DimGLAccountsDepartment[GL - GL Department Key]= "69001498-71*" || DimGLAccountsDepartment[GL - GL Department Key]= "69001496-71*" || DimGLAccountsDepartment[GL - GL Department Key]= "69001496-76*" || DimGLAccountsDepartment[GL - GL Department Key]= "69001498-76*"))+0
		lineageTag: 2a9b2b90-1a3f-4fd0-9275-c3209799757d

		changedProperty = Name

	measure 'MAPPED Gross Margin %' = DIVIDE([MAPPED AMT - P&L Gross Margin],[MAPPED AMT - P&L Net Sales])
		lineageTag: ccf8c412-3c4c-482b-8255-c40df2642d5c

		changedProperty = Name

	measure 'MAPPED P&L Capitalization of IT Costs(Cost of Goods Sold)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Department Key]= "69001499-71*" || DimGLAccountsDepartment[GL - GL Department Key]= "69001499-76*"))+0
		lineageTag: b9a122a4-6970-4572-8cd5-66f8ad7eb36c

		changedProperty = Name

	measure 'MAPPED Variable Contribution Margin' = [MAPPED AMT - P&L Net Sales]-[MAPPED Variable Costs]
		lineageTag: 8ae34246-3bb4-47d3-8d49-9eb18a6460a1

		changedProperty = Name

	measure 'MAPPED Variable Contribution Margin %' =
			
			IF (
			    [MAPPED AMT - P&L Net Sales] < 0,
			    -1,
			    1
			) *
			DIVIDE(
			    [MAPPED Variable Contribution Margin],
			    [MAPPED AMT - P&L Net Sales]
			)
		lineageTag: 47d967b7-f03c-4520-b9cc-18bb3536436b

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED Variable Costs' =
			
			[MAPPED AMT - P&L Total People Costs(Cost of Goods Sold)] +
			[MAPPED AMT - P&L Materials(Cost of Goods Sold)] +
			[MAPPED AMT - P&L Total People Cost(Selling Expence)] +
			[MAPPED AMT - P&L Freight(Cost of Goods Sold)]
		lineageTag: 33bcbbfb-9485-4476-b4d4-e909154a3bae

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Variable Contribution Margin' = ([AMT - P&L Net Sales]-[AMT - Variable Costs])
		formatString: 0
		lineageTag: 1dc0af53-67c5-4ccb-8061-557781b1176a

		changedProperty = Name

	measure 'Variable Contribution Margin %' = IF ([MAPPED AMT - P&L Net Sales] < 0 , -1, 1) *DIVIDE([Variable Contribution Margin],[AMT - P&L Net Sales])
		lineageTag: 13b25f03-94a7-43df-9607-93fc3c900ec9

		changedProperty = Name

	measure 'MAPPED AMT - P&L Repairs & Maintenance(G&A)' = CALCULATE(SUM(FactSalesCostActual[AMT - Mapped Cost Actual LC]),FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Repairs & Maintenance"))+0
		lineageTag: 57900ae1-8d15-4174-a794-b7801b107eeb

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Net Sales' = ```
			
			[AMT - P&L Gross Sales] + [AMT - P&L Net Sales With No Gross Sales]
			
			```
		formatString: 0
		lineageTag: 2e44250d-e3b9-4a33-bcea-0d1804889b6c

		changedProperty = Name

	measure 'AMT - P&L Materials(G&A)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="General and Administrative Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Materials"))+0
		lineageTag: 96ff6507-ecde-4b56-96e9-3e9b464bb089

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - P&L Overtime(Selling Expence)' = CALCULATE([AMT - Mapped Cost With Mapped Rate(USD)],FILTER(DimGLAccountsDepartment,DimGLAccountsDepartment[GL - GL Level 2]="Selling Expense" && DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" && DimGLAccountsDepartment[GL - GL Level 4] = "Overtime"))+0
		lineageTag: ac1f769f-4c58-4dd9-8e30-339bf7581365

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'MAPPED AMT - P&L Total Wages(G&A)' =
			
			CALCULATE(
			    SUMX(
			        FactSalesCostActual,
			        FactSalesCostActual[AMT - Mapped Cost Actual LC] +
			        FactSalesCostActual[AMT - Unmapped Cost Actual(W/0 Hr+ W/o Cust)]
			    ),
			    FILTER(
			        DimGLAccountsDepartment,
			        DimGLAccountsDepartment[GL - GL Level 2] = "General and Administrative Expense" &&
			        DimGLAccountsDepartment[GL - GL Level 3] = "Total People Cost" &&
			        DimGLAccountsDepartment[GL - GL Level 4] = "Wages"
			    )
			) + 0
		lineageTag: 92343d9c-b4e6-4a2e-a2e4-89dd331d1958

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'AMT - Mapped Cost Actual LC(M)' = SUM('FactSalesCostActual'[AMT - Mapped Cost Actual LC])
		lineageTag: 736d7528-e389-433a-8182-e6d65e7bbae7

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HEXKeyCombineCustomer
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 8f0e78fd-e152-4e4e-8295-5d96e9f4578e
		sourceLineageTag: HEXKeyCombineCustomer
		summarizeBy: none
		sourceColumn: HEXKeyCombineCustomer

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey LBC Location'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 89674573-1efb-4b05-b026-bae7a73f68e9
		sourceLineageTag: HEXKeyLBCLocation
		summarizeBy: none
		sourceColumn: HEXKeyLBCLocation

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey GLAccounts'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c5853ce4-b0ad-4f1b-b752-b58fa5464220
		sourceLineageTag: HEXKeyGLAccounts
		summarizeBy: none
		sourceColumn: HEXKeyGLAccounts

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Product'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 4c3e891f-0a52-442d-9e7f-65f5834041c1
		sourceLineageTag: HEXKeyProduct
		summarizeBy: none
		sourceColumn: HEXKeyProduct

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Company'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: efae2410-d37e-4c38-abab-dbc06f3e2d90
		sourceLineageTag: HEXKeyCompany
		summarizeBy: none
		sourceColumn: HEXKeyCompany

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Price Code'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 52123dec-5a50-4843-b395-a7a799e457de
		sourceLineageTag: HEXKeyPriceCode
		summarizeBy: none
		sourceColumn: HEXKeyPriceCode

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Invoice Date'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: c1ef876f-2cc1-49d2-ab5c-2c631a98c422
		sourceLineageTag: HEXKeyInvoiceDate
		summarizeBy: none
		sourceColumn: HEXKeyInvoiceDate

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Job Version'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: be1c29fb-a75a-47db-8364-ba8d25501b6e
		sourceLineageTag: HEXKeyJobVersion
		summarizeBy: none
		sourceColumn: HEXKeyJobVersion

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Sales Person'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 19dceb28-be7a-4d5d-bd16-a3cacff777ba
		sourceLineageTag: HEXKeySalesPerson
		summarizeBy: none
		sourceColumn: HEXKeySalesPerson

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Sites'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: e1603de7-bcd8-4f30-82b8-5519c5c6569e
		sourceLineageTag: HEXKeySites
		summarizeBy: none
		sourceColumn: HEXKeySites

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Billto Customer'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 37f9dece-1c38-4d6a-a239-bf1d8b4058c9
		sourceLineageTag: HEXKeyBilltoCustomer
		summarizeBy: none
		sourceColumn: HEXKeyBilltoCustomer

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Shipto Customer'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 050259e1-f11c-423e-b89f-da8ea67d288d
		sourceLineageTag: HEXKeyShiptoCustomer
		summarizeBy: none
		sourceColumn: HEXKeyShiptoCustomer

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Soldto Customer'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 8d4fcd5c-e406-43d2-a8b9-f16cd68147e6
		sourceLineageTag: HEXKeySoldtoCustomer
		summarizeBy: none
		sourceColumn: HEXKeySoldtoCustomer

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Printer Customer'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: eb46aa39-ab32-4655-b620-060fe919ab85
		sourceLineageTag: HEXKeyPrinterCustomer
		summarizeBy: none
		sourceColumn: HEXKeyPrinterCustomer

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'COST - Sales Person Name'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: cdc0e644-725c-4ea9-a13d-7154bd1722db
		sourceLineageTag: SalespersonName
		summarizeBy: none
		sourceColumn: SalespersonName

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'INV - Invoice ID'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ba2444b6-0ada-43ce-b5d1-60e9e8fc1494
		sourceLineageTag: InvoiceID
		summarizeBy: none
		sourceColumn: InvoiceID

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'INV - Inter company Invoice Reference'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: e7cfcd95-f5a2-4de8-a957-484376834920
		sourceLineageTag: IntercompanyInvoiceReference
		summarizeBy: none
		sourceColumn: IntercompanyInvoiceReference

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'INV - Invoice Type'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: a7b03d7f-9a1a-4233-9d98-f4231b607c3c
		sourceLineageTag: InvoiceType
		summarizeBy: none
		sourceColumn: InvoiceType

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'REV - Purchase Order1'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: cc24111c-2df7-4b87-a9fe-e8ab7b3ddc7b
		sourceLineageTag: PurchaseOrder1
		summarizeBy: none
		sourceColumn: PurchaseOrder1

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'REV - Purchase Order2'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 447e3a30-18c8-4e14-ba23-8690c6232444
		sourceLineageTag: PurchaseOrder2
		summarizeBy: none
		sourceColumn: PurchaseOrder2

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'REV - Order Description'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 8c4e7cd0-f0b7-455f-a3ee-b9ec51c4df6a
		sourceLineageTag: OrderDescription
		summarizeBy: none
		sourceColumn: OrderDescription

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MySGSAdditionalInvoiceDescription
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 9df752fa-dfc0-498a-851d-73c9797f6067
		sourceLineageTag: MySGSAdditionalInvoiceDescription
		summarizeBy: none
		sourceColumn: MySGSAdditionalInvoiceDescription

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'COST - Order Contact Person Name'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: acd1b9b8-d3bb-4258-ad39-049c828364c1
		sourceLineageTag: OrderContactPersonName
		summarizeBy: none
		sourceColumn: OrderContactPersonName

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'DATE - Order Created Date'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 1422e48e-7fa4-4404-95d4-ea83853cb193
		sourceLineageTag: OrderCreatedDate
		summarizeBy: none
		sourceColumn: OrderCreatedDate

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'QNTY - Quantity'
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: 1182c5cc-9194-41da-ac6b-143ac2c5f5f3
		sourceLineageTag: Quantity
		summarizeBy: sum
		sourceColumn: Quantity

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PriceLC
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: fcca2338-0503-4d63-92d9-9c1bbc04a489
		sourceLineageTag: PriceLC
		summarizeBy: sum
		sourceColumn: PriceLC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ExtendedPriceLC
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: 720013b1-6a75-4f6c-acfb-7b68aa0ffd27
		sourceLineageTag: ExtendedPriceLC
		summarizeBy: sum
		sourceColumn: ExtendedPriceLC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AMT - Invoice Line Item Amount LC'
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 4aac3430-fc09-4564-a637-708942bb4f6d
		sourceLineageTag: InvoiceLineItemAmountLC
		summarizeBy: sum
		sourceColumn: InvoiceLineItemAmountLC

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'REV - Rollup Item ID'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 4c9bf34a-26f1-437b-8974-3434bcef7566
		sourceLineageTag: RollupItemID
		summarizeBy: none
		sourceColumn: RollupItemID

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column TaxAmountLC
		dataType: double
		sourceProviderType: decimal(19, 4)
		lineageTag: 5fae8fab-0dbc-4254-8fa8-f30babd2f374
		sourceLineageTag: TaxAmountLC
		summarizeBy: sum
		sourceColumn: TaxAmountLC

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'TAX - Tax Code Description'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 403a3627-79b3-4b21-ad64-d71dc4f7f0cf
		sourceLineageTag: TaxcodeDescription
		summarizeBy: none
		sourceColumn: TaxcodeDescription

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'COST - CSR Customer Service Representative'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: a4207111-235c-4e8f-b4cc-4e2bc6afd4ff
		sourceLineageTag: CSRCustomerServiceRepresentative
		summarizeBy: none
		sourceColumn: CSRCustomerServiceRepresentative

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'COST - Department'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 51881e6e-8405-401f-b994-94afb1fee3b4
		sourceLineageTag: Department
		summarizeBy: none
		sourceColumn: Department

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'REV - Order Type'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 0027edfd-d87a-4f80-836c-4959d7434749
		sourceLineageTag: OrderType
		summarizeBy: none
		sourceColumn: OrderType

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FinalProductType
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 82da4b98-4022-4c2a-89db-d3e4e10f06da
		sourceLineageTag: FinalProductType
		summarizeBy: none
		sourceColumn: FinalProductType

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'CUST - Customer Specific ID'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 9da38b1f-52cb-4280-8eb4-180fde3a2328
		sourceLineageTag: CustomerSpecificID
		summarizeBy: none
		sourceColumn: CustomerSpecificID

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'REV - Charge Type'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: b53c6a60-b584-40fa-8375-998220d8e88c
		sourceLineageTag: ChargeType
		summarizeBy: none
		sourceColumn: ChargeType

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'REV - Company Number'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: f6853e97-7eed-46b3-b96e-9b030329b357
		sourceLineageTag: CompanyNumber
		summarizeBy: none
		sourceColumn: CompanyNumber

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'SYST - Data Source'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 10c2d898-74dc-4da8-bea8-789b2d28f619
		sourceLineageTag: DataSource
		summarizeBy: none
		sourceColumn: DataSource

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'REV - Local Currency Code'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 38f40923-dd59-4f5c-8f17-d4bbba1320c8
		sourceLineageTag: LocalCurrencyCode
		summarizeBy: none
		sourceColumn: LocalCurrencyCode

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'AMT - Exchange Rate To USD'
		dataType: double
		sourceProviderType: decimal(17, 6)
		lineageTag: db551e8b-9322-4309-8180-f9842d0a32dc
		sourceLineageTag: ExchangeRateToUSD
		summarizeBy: sum
		sourceColumn: ExchangeRateToUSD

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'REV - Order Number'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ea35b017-2ec2-4f0d-890e-b9ce5bd7e5b1
		sourceLineageTag: OrderNumber
		summarizeBy: none
		sourceColumn: OrderNumber

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'REV - Originating Plant'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: e8e9170b-73fe-4d1c-bb05-e9403f34a138
		sourceLineageTag: OriginatingPlant
		summarizeBy: none
		sourceColumn: OriginatingPlant

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Project Manager'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 1f930dab-4d0c-49a7-81ce-15f07760ad09
		sourceLineageTag: HEXKeyProjectManager
		summarizeBy: none
		sourceColumn: HEXKeyProjectManager

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Job Primary Team'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 2dc2bc57-def8-4857-839f-22caa876d959
		sourceLineageTag: HEXKeyJobPrimaryTeam
		summarizeBy: none
		sourceColumn: HEXKeyJobPrimaryTeam

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column AllocationRate
		dataType: double
		sourceProviderType: decimal(17, 6)
		lineageTag: b0d067b8-81bd-4c8a-9cf1-a6143847eebc
		sourceLineageTag: AllocationRate
		summarizeBy: sum
		sourceColumn: AllocationRate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'zID - HEXKey Department'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 4b4e3e14-cfde-4b9e-b4d7-114b2e634093
		sourceLineageTag: HEXKeyDepartment
		summarizeBy: none
		sourceColumn: HEXKeyDepartment

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey GL Accounts Department'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: f7df6e3e-efbc-4e3d-9528-2ecec7b130fa
		sourceLineageTag: HEXKeyGLAccountsDepartment
		summarizeBy: none
		sourceColumn: HEXKeyGLAccountsDepartment

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'AMT - Total Cost LC'
		dataType: double
		sourceProviderType: decimal(17, 6)
		lineageTag: a1ed3d8c-c589-4034-9789-1f5091ed07ff
		sourceLineageTag: TotalCostLocCurrency
		summarizeBy: sum
		sourceColumn: TotalCostLocCurrency

		changedProperty = IsHidden

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AMT - Mapped Cost LC'
		dataType: double
		sourceProviderType: decimal(17, 6)
		lineageTag: 9e1ea27a-d910-4d6d-b597-01c1b42e4b92
		sourceLineageTag: MappedCostLocCurrency
		summarizeBy: sum
		sourceColumn: MappedCostLocCurrency

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IND - Allocation Methodolgy'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 5e3c4ad9-fb41-4904-b4fe-05eb6657c475
		sourceLineageTag: AllocationMethodolgy
		summarizeBy: none
		sourceColumn: AllocationMethodolgy

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'AMT - Mapped Cost Actual LC'
		dataType: double
		sourceProviderType: decimal(17, 6)
		lineageTag: 92e66fcf-fc73-4cd7-818b-c72486345dd0
		sourceLineageTag: MappedCostActualLocCurrency
		summarizeBy: sum
		sourceColumn: MappedCostActualLocCurrency

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AMT - UnMapped Cost Actual LC(W/O Hr)'
		dataType: double
		sourceProviderType: decimal(17, 6)
		lineageTag: f089e86a-7a4f-4004-b8bf-a60ea086747a
		sourceLineageTag: UnMappedCostActualLocCurrency
		summarizeBy: sum
		sourceColumn: UnMappedCostActualLocCurrency

		changedProperty = IsHidden

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'AMT - Un Mapped Cost Actual LC(W/O Customer)'
		dataType: double
		sourceProviderType: decimal(17, 6)
		lineageTag: 5b47c2dc-f543-4933-8c42-eb0950090099
		sourceLineageTag: UnMappedCostActualLCWithoutCustomer
		summarizeBy: sum
		sourceColumn: UnMappedCostActualLCWithoutCustomer

		changedProperty = IsHidden

		changedProperty = Name

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'zID - HEXKey Customer Summary'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 1280e91a-05dc-447f-813b-e56d74115558
		sourceLineageTag: HEXKeyCustomerSummary
		summarizeBy: none
		sourceColumn: HEXKeyCustomerSummary

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'DATE - Partition Month'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 3cd7803b-3459-4723-90c9-4b9e7598de76
		sourceLineageTag: PartitionMonth
		summarizeBy: none
		sourceColumn: PartitionMonth

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column MappedNegativeAndPositiveCostInUSD
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		sourceProviderType: decimal(17, 4)
		lineageTag: ad61d8ea-04ac-4ec4-8bdb-8421117bcd0d
		sourceLineageTag: MappedNegativeAndPositiveCostInUSD
		summarizeBy: sum
		sourceColumn: MappedNegativeAndPositiveCostInUSD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column MappedActualNegativeAndPositiveCostInUSD
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		sourceProviderType: decimal(17, 4)
		lineageTag: 0b11bd15-bfa1-4e7e-8de5-6ce58b682496
		sourceLineageTag: MappedActualNegativeAndPositiveCostInUSD
		summarizeBy: sum
		sourceColumn: MappedActualNegativeAndPositiveCostInUSD

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'zID - HEXKey Employee History'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 9ab0d1aa-a76c-4f4f-9080-ef81389f4035
		sourceLineageTag: HEXKeyEmployeeHistory
		summarizeBy: none
		sourceColumn: HEXKeyEmployeeHistory

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Employees'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 4f252e5b-1199-4239-853d-3fc0723bba22
		sourceLineageTag: HEXKeyEmployees
		summarizeBy: none
		sourceColumn: HEXKeyEmployees

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'QNTY - Employee Allocation Percentage'
		dataType: double
		sourceProviderType: decimal(17, 6)
		lineageTag: 68dd1b11-d451-425b-a907-749472a94a61
		sourceLineageTag: EmployeeAllocationPercentage
		summarizeBy: sum
		sourceColumn: EmployeeAllocationPercentage

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'IND - Employee Department Indicator'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ec9ef107-f4a4-477e-8e1b-9179a37ecc7e
		sourceLineageTag: EmployeeDepartmentIndicator
		summarizeBy: none
		sourceColumn: EmployeeDepartmentIndicator

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Reporting Customer'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 6be99992-ba7a-4d45-aa16-5a629ceb8638
		sourceLineageTag: HEXKeyReportingCustomer
		summarizeBy: none
		sourceColumn: HEXKeyReportingCustomer

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey End User Customer'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 966daecf-9c54-4161-86c4-b554805e5cce
		sourceLineageTag: HEXKeyEndUserCustomer
		summarizeBy: none
		sourceColumn: HEXKeyEndUserCustomer

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Ledger Category'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ef761968-8219-48b7-9d61-82120bc09927
		sourceLineageTag: HEXKeyLedgerCategory
		summarizeBy: none
		sourceColumn: HEXKeyLedgerCategory

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Budget Category'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 6bd9e15a-843b-425c-a42a-5b5584579b45
		sourceLineageTag: HEXKeyBudgetCategory
		summarizeBy: none
		sourceColumn: HEXKeyBudgetCategory

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BudgetRevenue
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: e29f0ee9-5752-41d6-b0ac-582275c46a1a
		sourceLineageTag: BudgetRevenue
		summarizeBy: sum
		sourceColumn: BudgetRevenue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ForecastedRevenue
		dataType: double
		sourceProviderType: decimal(38, 6)
		lineageTag: 29cbcd39-1467-479d-81c5-471b05307e9c
		sourceLineageTag: ForecastedRevenue
		summarizeBy: sum
		sourceColumn: ForecastedRevenue

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column RevenueIndicator
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 959f36fd-f087-401c-879c-4251122f4756
		sourceLineageTag: RevenueIndicator
		summarizeBy: none
		sourceColumn: RevenueIndicator

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PriceCode
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 77d34c27-0a09-420a-a8e2-2d9f1a15fab5
		sourceLineageTag: PriceCode
		summarizeBy: none
		sourceColumn: PriceCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PriceCodeDescription1
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 52b20a06-cbab-429f-bfa9-108caff69be0
		sourceLineageTag: PriceCodeDescription1
		summarizeBy: none
		sourceColumn: PriceCodeDescription1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column PriceCodeDescription2
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 7a0ec6ff-80b8-487d-ae95-50e1a930229b
		sourceLineageTag: PriceCodeDescription2
		summarizeBy: none
		sourceColumn: PriceCodeDescription2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BillToAttribute1
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 5f7f177b-02b6-479a-9d82-1c6378b68561
		sourceLineageTag: BillToAttribute1
		summarizeBy: none
		sourceColumn: BillToAttribute1

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BillToAttribute2
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: be68f80c-a2e2-4157-8261-b1b48c0561ac
		sourceLineageTag: BillToAttribute2
		summarizeBy: none
		sourceColumn: BillToAttribute2

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BillToAttribute3
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 3f8a6616-aabd-4a2e-ada7-685db3733ed2
		sourceLineageTag: BillToAttribute3
		summarizeBy: none
		sourceColumn: BillToAttribute3

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BillToAttribute4
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 2bea7703-229b-4327-bd33-bdd91056126a
		sourceLineageTag: BillToAttribute4
		summarizeBy: none
		sourceColumn: BillToAttribute4

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FacilityLBCHelper
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 41cc67c4-952e-41ce-af49-2f55db310691
		sourceLineageTag: FacilityLBCHelper
		summarizeBy: none
		sourceColumn: FacilityLBCHelper

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column InvoiceDate
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: fe7e6b21-6f92-4fa3-b5fd-e0e324e44fcd
		sourceLineageTag: InvoiceDate
		summarizeBy: none
		sourceColumn: InvoiceDate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ActualFXRateBudget
		dataType: double
		sourceProviderType: decimal(17, 6)
		lineageTag: b23dcc8f-0982-430b-ae81-af16b566aac9
		sourceLineageTag: ActualFXRateBudget
		summarizeBy: sum
		sourceColumn: ActualFXRateBudget

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BudgetReportingFxRate
		dataType: double
		sourceProviderType: decimal(17, 6)
		lineageTag: 4574a39d-1032-4899-9689-d5afe3fa55cd
		sourceLineageTag: BudgetReportingFxRate
		summarizeBy: sum
		sourceColumn: BudgetReportingFxRate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ActualFXRateForecast
		dataType: double
		sourceProviderType: decimal(17, 6)
		lineageTag: 3388b62a-6ded-4825-84eb-6dbf851b721b
		sourceLineageTag: ActualFXRateForecast
		summarizeBy: sum
		sourceColumn: ActualFXRateForecast

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ForecastReportingFxRate
		dataType: double
		sourceProviderType: decimal(17, 6)
		lineageTag: 07688a81-fa36-4fd7-b0b2-7160824b5452
		sourceLineageTag: ForecastReportingFxRate
		summarizeBy: sum
		sourceColumn: ForecastReportingFxRate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ForecastFXRateBudget
		dataType: double
		sourceProviderType: decimal(17, 6)
		lineageTag: 8c1161ba-9024-4df3-bdc2-a2575d5fbc10
		sourceLineageTag: ForecastFXRateBudget
		summarizeBy: sum
		sourceColumn: ForecastFXRateBudget

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column BudgetReportingCurrency
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: b6f81713-a135-4144-8374-331d62524b51
		sourceLineageTag: BudgetReportingCurrency
		summarizeBy: none
		sourceColumn: BudgetReportingCurrency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ForecastReportingCurrency
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ec26d278-21e0-4a4c-96fe-3fa85ac505ad
		sourceLineageTag: ForecastReportingCurrency
		summarizeBy: none
		sourceColumn: ForecastReportingCurrency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ReportingFxRate
		dataType: double
		sourceProviderType: decimal(17, 15)
		lineageTag: 68d23a18-a7ea-46b4-af1c-b60750a57bd6
		sourceLineageTag: ReportingFxRate
		summarizeBy: sum
		sourceColumn: ReportingFxRate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ReportingCurrency
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 8f309a2d-26aa-42ca-b705-f63cfad1c70f
		sourceLineageTag: ReportingCurrency
		summarizeBy: none
		sourceColumn: ReportingCurrency

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CurrentBudgetFXRateActuals
		dataType: double
		sourceProviderType: decimal(17, 15)
		lineageTag: 32149916-0c47-4d68-b2a8-519cb4098896
		sourceLineageTag: CurrentBudgetFXRateActuals
		summarizeBy: sum
		sourceColumn: CurrentBudgetFXRateActuals

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Region
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 7935bbd6-11ee-483d-b9a7-748490ba393b
		sourceLineageTag: Region
		summarizeBy: none
		sourceColumn: Region

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column LBCCurrencyCode
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 8414fe00-b98c-4413-928c-33837cabcddf
		sourceLineageTag: LBCCurrencyCode
		summarizeBy: none
		sourceColumn: LBCCurrencyCode

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column CYFxRate
		dataType: double
		sourceProviderType: decimal(17, 15)
		lineageTag: 236841af-5107-4ce3-8637-0ef61e8d44ac
		sourceLineageTag: CYFxRate
		summarizeBy: sum
		sourceColumn: CYFxRate

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ForecastFXRateActuals
		dataType: double
		sourceProviderType: decimal(17, 15)
		lineageTag: cc0d0993-9c76-4028-8268-21ee114069dd
		sourceLineageTag: ForecastFXRateActuals
		summarizeBy: sum
		sourceColumn: ForecastFXRateActuals

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ReportingCustomer2Subsidiary
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 43f42e56-238d-43f7-a664-448d3faff979
		sourceLineageTag: ReportingCustomer2Subsidiary
		summarizeBy: none
		sourceColumn: ReportingCustomer2Subsidiary

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BudgetVersion
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 7e507741-d22b-4813-9a28-a9bbce2b356a
		sourceLineageTag: BudgetVersion
		summarizeBy: none
		sourceColumn: BudgetVersion

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BudgetScenario
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 14d8d458-f0c3-4af5-ad90-04d2c79c36de
		sourceLineageTag: BudgetScenario
		summarizeBy: none
		sourceColumn: BudgetScenario

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column ForecastScenario
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 0737af69-8af0-410c-82b7-7a7f449556a1
		sourceLineageTag: ForecastScenario
		summarizeBy: none
		sourceColumn: ForecastScenario

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HexKey Year Month'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 378ed4aa-1feb-45c1-84dc-f9484d95d41a
		sourceLineageTag: HexKeyYearMonth
		summarizeBy: none
		sourceColumn: HexKeyYearMonth

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column BatchLoadMonth
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: e0bfdccb-9f2c-4ba0-b3df-7d8b6088f5b3
		sourceLineageTag: BatchLoadMonth
		summarizeBy: none
		sourceColumn: BatchLoadMonth

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'zID - HEXKey Commercial Assignments Grid'
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 6a84f0ac-e9eb-424c-8318-239c4d1bb3ed
		sourceLineageTag: HEXKeyCommercialAssignmentsGrid
		summarizeBy: none
		sourceColumn: HEXKeyCommercialAssignmentsGrid

		changedProperty = Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HEXKeyReportingCustomerNumber
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: fbc0f0c0-6e96-4992-8b47-632375893f36
		sourceLineageTag: HEXKeyReportingCustomerNumber
		summarizeBy: none
		sourceColumn: HEXKeyReportingCustomerNumber

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column HexKeyLBCRevenueStream
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 856ddb47-bf77-438b-8645-5a0900f7e439
		sourceLineageTag: HexKeyLBCRevenueStream
		summarizeBy: none
		sourceColumn: HexKeyLBCRevenueStream

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column FactSalesCostActualSeqId
		dataType: double
		sourceProviderType: decimal(38, 0)
		lineageTag: bbc9d228-07ce-41bb-949d-d1d13f6acd8d
		sourceLineageTag: FactSalesCostActualSeqId
		summarizeBy: count
		sourceColumn: FactSalesCostActualSeqId

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HEXKeyAllocationMethodology
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 450aef8b-0ee8-43da-89cf-9874b41fcc94
		sourceLineageTag: HEXKeyAllocationMethodology
		summarizeBy: none
		sourceColumn: HEXKeyAllocationMethodology

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column JobStatus
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: ba1a42a7-6115-40e5-a76e-2aab453ac68c
		sourceLineageTag: JobStatus
		summarizeBy: none
		sourceColumn: JobStatus

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column METADATA$ROW_ID
		dataType: string
		sourceProviderType: varchar(8000)
		lineageTag: 6161ab3c-0320-4e25-bdf0-0aca3ae93439
		sourceLineageTag: METADATA$ROW_ID
		summarizeBy: none
		sourceColumn: METADATA$ROW_ID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition FactSalesCostActual = entity
		mode: directLake
		source
			entityName: FactSalesCostActual
			schemaName: dbo
			expressionSource: DatabaseQuery

	changedProperty = IsHidden

