table 'Fact Cats DB 3'
	lineageTag: c4d1e4ea-c31f-4933-84e4-1490933d9bb2
	sourceLineageTag: 2e5734e1-b53c-4e4b-a3b6-d5017782b127

	measure 'CATS Amount 3' = EXTERNALMEASURE("CATS Amount", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: f9a83c16-4bbe-430b-9356-5a05a725e65b
		sourceLineageTag: cb8e05e7-16b9-4e1d-ac8f-d2887f62d8aa
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'CATS Quantity 3' = EXTERNALMEASURE("CATS Quantity", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: 940ccff1-3df1-4776-a3e0-d93b37a4e8ab
		sourceLineageTag: 3182eb36-9880-44b7-a959-29a3df95c6f9
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Hours 3' = EXTERNALMEASURE("Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: cad65d74-e281-43c3-a3c3-9bdda90a1710
		sourceLineageTag: 96b8b343-ad66-4cce-afee-24690411dddf
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Measure 3' = EXTERNALMEASURE("Measure", INTEGER, "DirectQuery to AS - TimeCards_CATSDB 2")
		formatString: 0
		lineageTag: e76e5249-659e-42c6-b0b5-20f02bac8506
		sourceLineageTag: fcbf280e-a69e-44aa-b94f-ab33043aa50f
		dataCategory: Uncategorized

	column PERSONEL_NUM_KEY
		dataType: int64
		formatString: 0
		lineageTag: 9c7c31e7-4cd7-4673-a1d6-424f6dd5dd96
		sourceLineageTag: dc947c59-adff-4452-af41-0ac956f7e6cc
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: PERSONEL_NUM_KEY

		annotation SummarizationSetBy = User

	column WRK_DATE_KEY
		dataType: int64
		formatString: 0
		lineageTag: 83e11f69-a383-4213-9534-eb6ee7639c1f
		sourceLineageTag: 474fd0be-ae0b-44fc-8b42-2c73971c67b9
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: WRK_DATE_KEY

		annotation SummarizationSetBy = User

	column Counter
		dataType: string
		isNullable: false
		lineageTag: f3236aab-0c13-4d88-aca7-caac435d4355
		sourceLineageTag: b828eb81-99c2-44f1-9cb6-63476b21c472
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Counter

		annotation SummarizationSetBy = User

	column COST_CNTR_KEY
		dataType: int64
		formatString: 0
		lineageTag: d2f0ed89-d727-4c1e-85eb-01515e268082
		sourceLineageTag: 20fd81a1-e1a8-41e8-b37f-dac49496f98d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: COST_CNTR_KEY

		annotation SummarizationSetBy = User

	column ACTIVITY_TYP_KEY
		dataType: int64
		formatString: 0
		lineageTag: 0e2ab4b9-3125-4370-ba4c-d05a190d4080
		sourceLineageTag: 1b54df47-0fe3-4be8-ad8d-959140656fbc
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ACTIVITY_TYP_KEY

		annotation SummarizationSetBy = User

	column SERVC_ORDER_KEY
		dataType: int64
		formatString: 0
		lineageTag: 584c1a6a-4de3-496e-a6a6-6c56571c15ab
		sourceLineageTag: 04260b1e-4fb5-4ec1-b3f8-4aaeada98f4a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SERVC_ORDER_KEY

		annotation SummarizationSetBy = User

	column 'Operation Task List'
		dataType: int64
		formatString: 0
		lineageTag: 25c09abd-8ecd-45e7-9f9b-168e74ccee48
		sourceLineageTag: eaf4cf4b-6152-456e-8e8d-7a3aa0e27dfa
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Operation Task List

		annotation SummarizationSetBy = User

	column 'Operation Counter'
		dataType: int64
		formatString: 0
		lineageTag: 8523829b-acd8-4204-b387-3e06f68a745e
		sourceLineageTag: f4e96bf4-4b8f-4a0e-a86b-80b558b8bbaa
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Operation Counter

		annotation SummarizationSetBy = User

	column RECVNG_FUNCTNL_AREA_KEY
		dataType: int64
		formatString: 0
		lineageTag: af71fac4-ad1f-4810-aaab-90e16203c384
		sourceLineageTag: 85a02782-01f2-4e4e-a92c-873775480d6c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: RECVNG_FUNCTNL_AREA_KEY

		annotation SummarizationSetBy = User

	column SENDING_FUNCTNL_AREA_KEY
		dataType: int64
		formatString: 0
		lineageTag: 4c92d4af-8169-468e-a24e-62e8c7000220
		sourceLineageTag: f4245e90-ab67-45c4-bd4f-b21075f1db4e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SENDING_FUNCTNL_AREA_KEY

		annotation SummarizationSetBy = User

	column 'Attendance Or Absence Type'
		dataType: string
		lineageTag: 6f93ccee-b129-446d-9603-e930cfd34047
		sourceLineageTag: abe349ce-252f-4335-b103-f0fa72024cd8
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Attendance Or Absence Type

		annotation SummarizationSetBy = User

	column 'Controlling Area'
		dataType: string
		lineageTag: f68c59a3-0a30-45c0-9cc8-8c1673920abd
		sourceLineageTag: 7c97a980-8492-443a-88f8-3197f26cc51e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Controlling Area

		annotation SummarizationSetBy = User

	column 'Display UOM'
		dataType: string
		lineageTag: 8a9dd4df-54d4-4042-bb50-657c1092a9e2
		sourceLineageTag: 821f46bf-c272-4d1a-8f0f-55767cc0847c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Display UOM

		annotation SummarizationSetBy = User

	column WRK_CNTR_KEY
		dataType: int64
		formatString: 0
		lineageTag: 9c3d1f89-91bf-4dd2-b52b-44c8d2ca76e5
		sourceLineageTag: e88cbf6e-baa6-44cf-adfe-14566a0b1708
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: WRK_CNTR_KEY

		annotation SummarizationSetBy = User

	column 'Order Category'
		dataType: int64
		formatString: 0
		lineageTag: d7c3b2d9-fa07-45fe-ac17-e5dec3224d42
		sourceLineageTag: fca9b346-2590-4277-8d69-d7752376ee67
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: Order Category

		annotation SummarizationSetBy = User

	column 'Processing Status'
		dataType: string
		lineageTag: 8cd8bae2-a72d-4d2f-abf6-012b7e0c750d
		sourceLineageTag: 0ce13916-ebd1-4076-8997-3951b961b409
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Processing Status

		annotation SummarizationSetBy = User

	column 'Document Number'
		dataType: string
		lineageTag: b74b5d5b-a60f-47b9-940d-c87fea88c6a3
		sourceLineageTag: 2530e2f1-50c5-4573-ad7d-d89460a5a8a2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Document Number

		annotation SummarizationSetBy = User

	column HRS
		dataType: double
		lineageTag: 4ea97335-c541-47b3-a812-8ee3cf4b1bb5
		sourceLineageTag: cdbc0b1a-981a-4624-9139-6bec73f47c64
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Start Time'
		dataType: string
		lineageTag: 2a5ca954-0274-4433-9302-9b0d53683d73
		sourceLineageTag: 02cbbc68-538d-496f-8744-965490f64b2d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Start Time

		annotation SummarizationSetBy = User

	column 'End Time'
		dataType: string
		lineageTag: 3a38d98b-082a-4554-a8b6-b7fb0a933651
		sourceLineageTag: 5b797f43-40c3-441a-bb9b-e95042fbdeaa
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: End Time

		annotation SummarizationSetBy = User

	column CATS_AMT
		dataType: double
		lineageTag: fcede4fb-e159-479d-bbc2-949a78d0be0f
		sourceLineageTag: 8c97c1ca-862c-476d-9b78-877db203a75e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: CATS_AMT

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CATS_QTY
		dataType: double
		lineageTag: 84e2a548-b0fe-4e17-96f7-8d6e3243b963
		sourceLineageTag: 3908aa15-3b16-4303-9821-701193a60fa0
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: CATS_QTY

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Change Text'
		dataType: string
		lineageTag: 6a33e403-3f53-42d6-a6f3-bd0c55713862
		sourceLineageTag: e55bbcad-c212-43a9-902d-f7342db442bc
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Change Text

		annotation SummarizationSetBy = User

	column 'Created Date'
		dataType: string
		lineageTag: 4ee8f0dc-1956-4d1c-8f56-ca49a95ef4f4
		sourceLineageTag: e9d8e8df-b5ec-4a6d-a2cd-895fc1485c3c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Created Date

		annotation SummarizationSetBy = User

	column 'Created Time'
		dataType: string
		lineageTag: 3e1cd4cd-f756-4535-9e77-a92670f56e7d
		sourceLineageTag: 48d2ae20-28d8-4437-a40f-1751b3f5296b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Created Time

		annotation SummarizationSetBy = User

	column 'Changed Date'
		dataType: string
		lineageTag: 3410477c-1439-40f8-b975-b656977ccfa3
		sourceLineageTag: b86cf487-2272-4357-bab6-1df231782f04
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Changed Date

		annotation SummarizationSetBy = User

	column 'Change Time'
		dataType: string
		lineageTag: d5d35855-41ad-4fb8-a277-e80da776200c
		sourceLineageTag: 2f33e4b8-80e7-4538-a913-767344e8b524
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Change Time

		annotation SummarizationSetBy = User

	column Comment
		dataType: string
		lineageTag: 48a68a49-6ecb-45b7-ba8c-fb36b7fbe175
		sourceLineageTag: d1eb80eb-0f00-4753-b4f5-f6772c8bb86b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Comment

		annotation SummarizationSetBy = User

	column 'Header Comment'
		dataType: string
		lineageTag: 7ca21c98-b8ed-46d8-b830-dae785a6d7f0
		sourceLineageTag: 262d0a44-9a97-41a3-a916-1e3cf3a6cd0a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Header Comment

		annotation SummarizationSetBy = User

	column 'Short Text'
		dataType: string
		lineageTag: b8f2686d-8f22-4954-969c-d3e941d6968a
		sourceLineageTag: bc83d030-bf8e-44fb-a3e0-e06e3b538639
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Short Text

		annotation SummarizationSetBy = User

	column 'Long Text'
		dataType: string
		lineageTag: 8d1adc51-349f-4f93-881c-4b0fd4924636
		sourceLineageTag: 43a3b967-99c3-43f1-b29b-c620162338a7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Long Text

		annotation SummarizationSetBy = User

	column ETL_SRC_SYS_CD
		dataType: string
		lineageTag: 45901830-c771-44fd-b451-4ba4e3f51456
		sourceLineageTag: 9b1b6cda-41a8-4314-8945-b6f9780cc2cb
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ETL_SRC_SYS_CD

		annotation SummarizationSetBy = User

	column ETL_CREATED_TS
		dataType: dateTime
		formatString: General Number
		lineageTag: 0288b2c4-1047-40db-822f-1fa6cea68778
		sourceLineageTag: e34b286c-2713-4416-8202-be1feeda9b75
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ETL_CREATED_TS

		annotation SummarizationSetBy = User

	column ETL_UPDTD_TS
		dataType: dateTime
		formatString: General Number
		lineageTag: b6ae3dca-e2a7-4a04-be03-e99eb267aac6
		sourceLineageTag: 52402064-5624-4534-acd9-a66949a30185
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ETL_UPDTD_TS

		annotation SummarizationSetBy = User

	column PLNT_KEY
		dataType: int64
		formatString: 0
		lineageTag: a0377930-b665-43c7-8d4f-222f57843597
		sourceLineageTag: 147e6b32-6047-4ee1-9e92-2e61ea93c0f2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: PLNT_KEY

		annotation SummarizationSetBy = User

	column 'Controlling Area Description'
		dataType: string
		lineageTag: 8a7e2494-d490-47e8-82e0-6bce83b7f056
		sourceLineageTag: 6088fe09-62d6-4a5f-a1dc-c9597cdf3202
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Controlling Area Description

		annotation SummarizationSetBy = User

	column 'Order Category Description'
		dataType: string
		lineageTag: c9f6a9f7-f2cb-4dcc-af25-6f48cb838130
		sourceLineageTag: 1d36f616-39fd-40bc-8c3b-8fc8da9c0c9c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Order Category Description

		annotation SummarizationSetBy = User

	column 'Processing Status Description'
		dataType: string
		lineageTag: e5f25a2a-98ca-4774-85dd-7c627b7ac24c
		sourceLineageTag: bdfc4f62-8529-4a4d-a1c1-21c2d5bc66ae
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Processing Status Description

		annotation SummarizationSetBy = User

	column 'Network Number'
		dataType: string
		lineageTag: 2408a1b9-89c0-4d8a-9eb5-6bcbbd3e98dd
		sourceLineageTag: 42cf0f00-b85c-4104-b6ab-f02405dd137a
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Network Number

		annotation SummarizationSetBy = User

	column UOM
		dataType: string
		lineageTag: c84be300-7a4b-4c3b-b0a6-f55b57ae6d27
		sourceLineageTag: 0d8610fd-ee63-49ac-ab28-7b4a50124b6b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: UOM

		annotation SummarizationSetBy = User

	column 'Created On'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d805e111-7484-476a-ae7c-db4c906f691f
		sourceLineageTag: 098614be-8a68-45ed-96ba-aa8e914dd709
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Created On

		annotation SummarizationSetBy = User

	column 'Time Of Entry'
		dataType: string
		lineageTag: cdc227d3-ad28-48b6-b3fd-8345999d2362
		sourceLineageTag: 51ac0c85-6a1b-4bcd-898d-c46746ea6813
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Time Of Entry

		annotation SummarizationSetBy = User

	column 'User Who Created Data Record'
		dataType: string
		lineageTag: 9c2753ec-b470-4514-91f5-cd2b6e428b9a
		sourceLineageTag: 0ce5def0-2624-4469-8f7f-f98f42293774
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: User Who Created Data Record

		annotation SummarizationSetBy = User

	column 'Date Of Last Change'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2fac501e-e691-41b8-b20f-ca595048a8d2
		sourceLineageTag: be3793cb-9331-4275-81a8-365b7a5bcf56
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Date Of Last Change

		annotation SummarizationSetBy = User

	column 'Time of Last Change'
		dataType: string
		lineageTag: 89ff069e-d20b-4d18-b78c-c5d04865e37d
		sourceLineageTag: db3e8165-9813-4b1b-beff-0e170b8e65d3
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Time of Last Change

		annotation SummarizationSetBy = User

	column 'Name Of Person Who Changed Object'
		dataType: string
		lineageTag: 782ab4f5-6b27-40ce-beda-6975369af94d
		sourceLineageTag: a39c52ad-55f7-4dec-b2fc-a0fef118219c
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Name Of Person Who Changed Object

		annotation SummarizationSetBy = User

	column 'Name Of Person Who Apprvd Data'
		dataType: string
		lineageTag: 6e857d2a-5f99-4e8e-91ff-24307ca2e72b
		sourceLineageTag: 8dbf2c50-1e1f-4887-9640-1787f02d141e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Name Of Person Who Apprvd Data

		annotation SummarizationSetBy = User

	column 'Date Of Approval'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6f677c5f-8cb2-4e7b-a762-c149049d3ae7
		sourceLineageTag: 0e38a387-0f02-49c4-8a58-c6a847206b4b
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Date Of Approval

		annotation SummarizationSetBy = User

	column 'Logical System'
		dataType: string
		lineageTag: 41475c12-200f-45cd-98ef-fddcc7490ef5
		sourceLineageTag: e269b1d8-013a-4579-a36f-0f3db5563758
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Logical System

		annotation SummarizationSetBy = User

	column 'Reference Counter for Record to be Changed'
		dataType: string
		lineageTag: 9438e21c-14b4-4554-bf21-c53e805322c9
		sourceLineageTag: 9de22a09-4fcf-4f5b-ac7f-ad33752c08bf
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Reference Counter for Record to be Changed

		annotation SummarizationSetBy = User

	column 'Partial Confirmation Indicator'
		dataType: string
		lineageTag: 8825f15c-7f40-4ab6-bab1-f84869ec60dc
		sourceLineageTag: 3852524f-49b0-4d6c-bdae-d141d4b77bf0
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Partial Confirmation Indicator

		annotation SummarizationSetBy = User

	column 'Receiver Order'
		dataType: string
		lineageTag: c7acf4eb-8902-4beb-be4d-2e777ae893fc
		sourceLineageTag: bc19f783-52cf-4fd4-b00f-ef28c51c470e
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Receiver Order

		annotation SummarizationSetBy = User

	column 'Project Description'
		dataType: string
		lineageTag: 08313054-70fa-4bc8-a9ad-2ca71bf57b51
		sourceLineageTag: d764f61f-cb22-46f8-9958-a5db967cb059
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Project Description

		annotation SummarizationSetBy = User

	column 'WBS Number'
		dataType: string
		lineageTag: b310bf9c-5ecd-425d-ad07-f47e3d398035
		sourceLineageTag: 2fd5baf0-8c9b-42b5-ac58-faee1275569d
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: WBS Number

		annotation SummarizationSetBy = User

	column 'WBS Description'
		dataType: string
		lineageTag: 1f66b3b7-9e7a-4177-8d29-72ae1f53f51e
		sourceLineageTag: 0b47e1c9-9851-4d9b-aea8-dc855e9c4890
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: WBS Description

		annotation SummarizationSetBy = User

	column WBS_ELEMNT_KEY
		dataType: int64
		formatString: 0
		lineageTag: d6dc1b29-0cb6-4146-a235-7dfc3386ffd3
		sourceLineageTag: 68baf870-f13e-4ac3-9215-dd899123034c
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: WBS_ELEMNT_KEY

		annotation SummarizationSetBy = User

	column SGK_OPERREG_PLANT
		dataType: string
		lineageTag: 5c6deac3-1b26-40be-96ab-886d56d157f5
		sourceLineageTag: dfc1ee7a-09d1-4e7e-9735-773c6fa06135
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SGK_OPERREG_PLANT

		annotation SummarizationSetBy = User

	partition 'Fact Cats DB 3' = entity
		mode: directQuery
		source
			entityName: Fact Cats DB
			expressionSource: 'DirectQuery to AS - TimeCards_CATSDB 2'

