table 'Fact Time Card 3'
	lineageTag: 7b0b4dcb-c097-407b-a604-9bfb6a270dde
	sourceLineageTag: 52014830-cbc5-4256-bef8-72c523e15088

	measure 'Absence Hours 3' = EXTERNALMEASURE("Absence Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: 500d58e5-6e20-4d35-8e6c-f8fd691279b8
		sourceLineageTag: 00179789-d31b-46eb-906d-5b1c707090f2
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual Leave Hours 3' = EXTERNALMEASURE("Annual Leave Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: f390d78f-3822-4c3b-9606-6f16b77f952e
		sourceLineageTag: 1adc5f88-1c59-4434-96ee-828ea4dfb7ae
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Approved Working Hours 3' = EXTERNALMEASURE("Approved Working Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: 8cd92bb9-5491-4f32-a113-5bb527fb2090
		sourceLineageTag: 1aef535b-d2cc-41e9-9fe6-4691a41a476d
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Flex Bal TS 3' = EXTERNALMEASURE("Flex Bal TS", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: 6626228c-dc32-4a6e-8e65-afaf116b3944
		sourceLineageTag: 4b55a515-a3b6-424a-b4f6-627953f6c9e8
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lunch Hours 3' = EXTERNALMEASURE("Lunch Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: bc695811-ac29-4b94-96a4-249ca57b605d
		sourceLineageTag: d51043c9-3bd9-4018-be3b-125ec58382e3
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Other Leave Hours 3' = EXTERNALMEASURE("Other Leave Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: 2c7a9a11-5f92-4473-bf6a-93fe77b872ac
		sourceLineageTag: 9c53175a-1efe-4006-a61e-ebdff114ea7c
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Overtime Hours 3' = EXTERNALMEASURE("Overtime Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: 021d7e36-3d36-4132-8d17-b36f9c19e18c
		sourceLineageTag: d135b990-beb7-4012-8e54-6890d8cc85fb
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Paid Break 3' = EXTERNALMEASURE("Paid Break", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: c720c068-bda3-406f-a765-b9f9de511ef7
		sourceLineageTag: 367347c3-791a-4c03-8696-b0a204030326
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Punch In Out Hours 3' = EXTERNALMEASURE("Punch In Out Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: a99ebd79-5a0c-4ecd-97a8-fc79d3b05716
		sourceLineageTag: 47a3dcb6-5048-4fa7-af7d-36f7a707ab43
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Regular Hours 3' = EXTERNALMEASURE("Regular Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: 220129b0-a47b-4ee9-acc3-ae3cf1bde6e9
		sourceLineageTag: 20344af4-efc0-4519-9e42-5ad4c6c0a2fe
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Shift End Time 2 3' = EXTERNALMEASURE("Shift End Time 2", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: 95b29f6e-96c0-4251-ae65-50db8799e16c
		sourceLineageTag: 7e46920f-a2fb-45ca-8161-576b0999b353
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Shift Start Time 2 3' = EXTERNALMEASURE("Shift Start Time 2", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: 2e0471f0-7b03-45b1-bd37-452177e65f7e
		sourceLineageTag: 5ac2349d-3784-4683-a648-dd28bd12020e
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sick Leave Hours 3' = EXTERNALMEASURE("Sick Leave Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: 121138a6-4b3e-4814-bfab-572fdcb14da6
		sourceLineageTag: e99b1878-db95-4687-9646-ab4316a4ac07
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Hours 3' = EXTERNALMEASURE("Total Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: 65ea9e0a-f353-449c-90bb-427d8f061846
		sourceLineageTag: a36ffb56-cbd7-4421-ae14-57091e4d5a0e
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unpaid Leave Hours 3' = EXTERNALMEASURE("Unpaid Leave Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: b15bddc3-5a25-40bc-9a04-dd120e9c049f
		sourceLineageTag: 635711cc-6520-4976-b4b3-4c72c7c29a07
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Work Hours 3' = EXTERNALMEASURE("Work Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB 2")
		lineageTag: 4a6d6d18-3865-47c2-9f15-c0c2a128d66c
		sourceLineageTag: 53503404-7c4e-4715-a4a7-a0d7f5f74f50
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERSONEL_NUM_KEY
		dataType: int64
		isNullable: false
		formatString: 0
		lineageTag: f60416e0-dd7b-47b1-adaf-204230bf78d7
		sourceLineageTag: 17c2bdf3-9726-455a-ab23-af61ccc5c518
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: PERSONEL_NUM_KEY

		annotation SummarizationSetBy = User

	column DATE_KEY
		dataType: int64
		isNullable: false
		formatString: 0
		lineageTag: 3e7985f2-030a-4633-b47f-e314ec16d446
		sourceLineageTag: 525b99c9-c791-41cc-a0a3-6fcafba57474
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: DATE_KEY

		annotation SummarizationSetBy = User

	column TOTAL_HRS
		dataType: double
		lineageTag: 0758c5c8-09f4-4739-ac18-9121f06637b9
		sourceLineageTag: 37a431dc-8930-4642-8fef-eab7d32941a5
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: TOTAL_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column WRK_HRS
		dataType: double
		lineageTag: 27e7c860-7e98-4744-a2e0-1106b9bbecdb
		sourceLineageTag: 175c3fe1-ac10-4430-97c9-5a7fc0962523
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: WRK_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ABSNE_HRS
		dataType: double
		lineageTag: c2ac4fa6-e7ab-4217-8484-e4823d92c312
		sourceLineageTag: 040df9fb-ad9c-45f2-baff-cde6fe2d3e06
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: ABSNE_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LUNCH_HRS
		dataType: double
		lineageTag: ee418706-f4ad-4239-94aa-3fe68b43d4fc
		sourceLineageTag: 352d17b2-569a-4431-930d-8b46e11b1813
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: LUNCH_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OVERTIME_HRS
		dataType: double
		lineageTag: c1c7b3bc-ca93-41ec-bda9-20d1140da0fc
		sourceLineageTag: 2f6c5134-cda9-4d9a-8612-f3a56f5e0615
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: OVERTIME_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Shift Start Time'
		dataType: string
		lineageTag: a1c34909-97c7-411a-9bca-3f95a8996fa9
		sourceLineageTag: f338d512-a036-4959-8444-555712fc70a7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Shift Start Time

		annotation SummarizationSetBy = User

	column SHIFT_START_TM_2
		dataType: double
		lineageTag: 453c6da3-c84a-4227-989f-10e65c9536ed
		sourceLineageTag: 2f6f68b8-10ee-4b76-b882-bcdb9005b2b0
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: SHIFT_START_TM_2

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Shift End Time'
		dataType: string
		lineageTag: ee76b1eb-3a06-4b2c-b5bc-5fe56b3f19af
		sourceLineageTag: 142c6e0d-2632-4eaf-a60c-0d565cd9fb54
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Shift End Time

		annotation SummarizationSetBy = User

	column SHIFT_END_TM_2
		dataType: double
		lineageTag: ee58add6-5721-4207-be3a-ff191096e5a3
		sourceLineageTag: 8c6c654e-dfed-4326-b40f-cad91ab9623c
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: SHIFT_END_TM_2

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column APPRVD_WORKING_HRS
		dataType: double
		lineageTag: e6e19cf0-24ae-4f0c-95c8-5c492257ec09
		sourceLineageTag: fc120b2a-ddfb-4c11-ab72-419928abcf73
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: APPRVD_WORKING_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Shift Scheduled Start Time'
		dataType: string
		lineageTag: 577f6a30-1cf8-4795-871e-9523283bffd7
		sourceLineageTag: 7a3eb1ef-baaa-40e9-946c-222bb2ff1d17
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Shift Scheduled Start Time

		annotation SummarizationSetBy = User

	column 'Shift Scheduled End Time'
		dataType: string
		lineageTag: 76b45222-5544-4737-9291-57cad38dd4bf
		sourceLineageTag: dc36c618-8168-4bce-9e25-e47b4fed3bce
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Shift Scheduled End Time

		annotation SummarizationSetBy = User

	column Comments
		dataType: string
		lineageTag: 466af6d1-0e26-4582-b3ee-19579da52d90
		sourceLineageTag: 6ec69d69-21d2-4f45-97f0-00ddf05cb8e2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = User

	column ETL_SRC_SYS_CD
		dataType: string
		lineageTag: caae49e5-490f-49e4-92d2-ebd9e136c1e5
		sourceLineageTag: e7ea2d31-60cc-4214-8790-a67ee67626a6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ETL_SRC_SYS_CD

		annotation SummarizationSetBy = User

	column ETL_CREATED_TS
		dataType: dateTime
		formatString: General Number
		lineageTag: 095d4f4c-3174-4010-853d-e7b3435a0b9d
		sourceLineageTag: c4f00d4e-ab0b-46f9-b79f-83e30e6aab49
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ETL_CREATED_TS

		annotation SummarizationSetBy = User

	column ETL_UPDTD_TS
		dataType: dateTime
		formatString: General Number
		lineageTag: e1eb6c13-0a0c-4953-80aa-36b41ea1902c
		sourceLineageTag: d473eb72-0a40-4161-a91d-da9bd61f2418
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ETL_UPDTD_TS

		annotation SummarizationSetBy = User

	column COST_CNTR_KEY
		dataType: int64
		formatString: 0
		lineageTag: 959a9ff5-c1fa-49ee-ac52-53448047e2d5
		sourceLineageTag: 0631fee5-98a2-4f83-af47-bd2c74ffa4f1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: COST_CNTR_KEY

		annotation SummarizationSetBy = User

	column CMPNY_KEY
		dataType: int64
		formatString: 0
		lineageTag: 4ab4c1dd-11a0-488c-92a6-f02f05d0c2e0
		sourceLineageTag: 1f4ea2cf-623d-4dcf-84d7-0b983ce0c520
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: CMPNY_KEY

		annotation SummarizationSetBy = User

	column PLNT_KEY
		dataType: int64
		formatString: 0
		lineageTag: 17f1873c-a3a3-4231-9d3b-b6f34e8ba0b7
		sourceLineageTag: 9bdc1fa9-45a9-47f1-a9be-2b33fa4db4ec
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: PLNT_KEY

		annotation SummarizationSetBy = User

	column PERSONEL_AREA_KEY
		dataType: int64
		formatString: 0
		lineageTag: 41a88132-8b8f-4ac6-8b6e-df9e7dc43364
		sourceLineageTag: 1df02135-5b24-48bc-a6e0-7b0ae46e4790
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: PERSONEL_AREA_KEY

		annotation SummarizationSetBy = User

	column FLEX_BAL_TS
		dataType: double
		lineageTag: 94d5525f-b6a2-4645-bc4f-14b23381ba0a
		sourceLineageTag: 4cfc7efd-62ce-4c5f-94c0-aa2ef015ff07
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: FLEX_BAL_TS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Approver User ID'
		dataType: string
		lineageTag: 3bb0838d-24c0-49bf-84e9-0b5f9edb447e
		sourceLineageTag: 58eba140-38fc-42d7-b8a8-6c944386fffb
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Approver User ID

		annotation SummarizationSetBy = User

	column PAID_BRK
		dataType: double
		lineageTag: 2da2646c-969c-4682-8b9f-a6da07a39a0b
		sourceLineageTag: 6700cc8b-f98d-4b7a-9366-9180c7108360
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: PAID_BRK

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ANNUAL_LEAVE_HRS
		dataType: double
		lineageTag: cea069da-e9dc-4e52-973e-39a2c38e491e
		sourceLineageTag: d67bf23a-f545-48bc-952a-228bc1169d0e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: ANNUAL_LEAVE_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OTHR_LEAVE_HRS
		dataType: double
		lineageTag: 7fd1cceb-9456-48c5-ba3a-b96314f023c9
		sourceLineageTag: 89ca64e3-cd5a-4f60-93f2-94412462e90b
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: OTHR_LEAVE_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SICK_LEAVE_HRS
		dataType: double
		lineageTag: 5cfcee26-e5f7-4200-bc6d-f10f37f9b6ba
		sourceLineageTag: aae0655b-c407-4392-9d65-86aa1335047f
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: SICK_LEAVE_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UNPAID_LEAVE_HRS
		dataType: double
		lineageTag: 826e5752-b62d-40e3-8259-0d53f1b21c18
		sourceLineageTag: 451dcd1b-6f05-4076-8f7f-6a415db32882
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: UNPAID_LEAVE_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PUNCH_IN_OUT_HRS
		dataType: double
		lineageTag: de68f68b-1b3b-426d-9068-1e94482ca181
		sourceLineageTag: 2de01d3f-50d5-4fd1-bc6d-66fd9c20db79
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: PUNCH_IN_OUT_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SGK_OPERREG_PLANT
		dataType: string
		lineageTag: f50b1b7e-967e-485d-8f12-8f15c100472f
		sourceLineageTag: 34e13f84-9843-4701-8962-a8e481c41a23
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SGK_OPERREG_PLANT

		annotation SummarizationSetBy = User

	partition 'Fact Time Card 3' = entity
		mode: directQuery
		source
			entityName: Fact Time Card
			expressionSource: 'DirectQuery to AS - TimeCards_CATSDB 2'

