table 'Fact Time Card 2'
	lineageTag: 3893b971-98dc-4487-9af7-29efd0350c7e
	sourceLineageTag: 52014830-cbc5-4256-bef8-72c523e15088

	measure 'Absence Hours 2' = EXTERNALMEASURE("Absence Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: dc87c48f-63db-424f-b549-440f971ffc56
		sourceLineageTag: 00179789-d31b-46eb-906d-5b1c707090f2
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Annual Leave Hours 2' = EXTERNALMEASURE("Annual Leave Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: 826806a1-d8a0-4ed8-b416-0c558e0b0db3
		sourceLineageTag: 1adc5f88-1c59-4434-96ee-828ea4dfb7ae
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Approved Working Hours 2' = EXTERNALMEASURE("Approved Working Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: ef6198d5-d298-47b2-b70d-0149e957c217
		sourceLineageTag: 1aef535b-d2cc-41e9-9fe6-4691a41a476d
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Flex Bal TS 2' = EXTERNALMEASURE("Flex Bal TS", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: 23f30651-3ba4-403d-bece-25e1eac5f2f8
		sourceLineageTag: 4b55a515-a3b6-424a-b4f6-627953f6c9e8
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Lunch Hours 2' = EXTERNALMEASURE("Lunch Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: 1f34ab71-edf4-4e8b-8cb9-3a6b5fba02be
		sourceLineageTag: d51043c9-3bd9-4018-be3b-125ec58382e3
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Other Leave Hours 2' = EXTERNALMEASURE("Other Leave Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: a6ff2e57-d2b7-4dff-b774-e4381a0c8e2c
		sourceLineageTag: 9c53175a-1efe-4006-a61e-ebdff114ea7c
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Overtime Hours 2' = EXTERNALMEASURE("Overtime Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: baa78098-279d-496b-9673-3d867ba83047
		sourceLineageTag: d135b990-beb7-4012-8e54-6890d8cc85fb
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Paid Break 2' = EXTERNALMEASURE("Paid Break", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: 95ee5f4e-0bff-4ce7-8c2e-929b576b1b57
		sourceLineageTag: 367347c3-791a-4c03-8696-b0a204030326
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Punch In Out Hours 2' = EXTERNALMEASURE("Punch In Out Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: fad89616-0c7e-4c66-9b69-c89880d2257a
		sourceLineageTag: 47a3dcb6-5048-4fa7-af7d-36f7a707ab43
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Regular Hours 2' = EXTERNALMEASURE("Regular Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: 845bd781-f89a-48f6-a6b3-f7de32a5e150
		sourceLineageTag: 20344af4-efc0-4519-9e42-5ad4c6c0a2fe
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Shift End Time 2 2' = EXTERNALMEASURE("Shift End Time 2", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: 5f121378-03b9-4ae5-b07e-547a734def16
		sourceLineageTag: 7e46920f-a2fb-45ca-8161-576b0999b353
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Shift Start Time 2 2' = EXTERNALMEASURE("Shift Start Time 2", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: 376226b2-11a9-4454-af7f-a18587c0f9c8
		sourceLineageTag: 5ac2349d-3784-4683-a648-dd28bd12020e
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Sick Leave Hours 2' = EXTERNALMEASURE("Sick Leave Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: cca6832c-455b-464f-815f-8d1eec8c327e
		sourceLineageTag: e99b1878-db95-4687-9646-ab4316a4ac07
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Total Hours 2' = EXTERNALMEASURE("Total Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: ead5fa11-783d-4c8f-983d-79018ae17935
		sourceLineageTag: a36ffb56-cbd7-4421-ae14-57091e4d5a0e
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Unpaid Leave Hours 2' = EXTERNALMEASURE("Unpaid Leave Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: d5739a59-4559-41d4-be7a-939bb184793e
		sourceLineageTag: 635711cc-6520-4976-b4b3-4c72c7c29a07
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Work Hours 2' = EXTERNALMEASURE("Work Hours", DOUBLE, "DirectQuery to AS - TimeCards_CATSDB")
		lineageTag: ef759527-f2af-48d0-b96c-e3cb6ec9541e
		sourceLineageTag: 53503404-7c4e-4715-a4a7-a0d7f5f74f50
		dataCategory: Uncategorized

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PERSONEL_NUM_KEY
		dataType: int64
		isNullable: false
		formatString: 0
		lineageTag: 600d3117-43e2-4b31-bdb1-f6b92b719d80
		sourceLineageTag: 17c2bdf3-9726-455a-ab23-af61ccc5c518
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: PERSONEL_NUM_KEY

		annotation SummarizationSetBy = User

	column DATE_KEY
		dataType: int64
		isNullable: false
		formatString: 0
		lineageTag: faaf8e16-766f-4bc8-ad13-2f3638266b36
		sourceLineageTag: 525b99c9-c791-41cc-a0a3-6fcafba57474
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: DATE_KEY

		annotation SummarizationSetBy = User

	column TOTAL_HRS
		dataType: double
		lineageTag: 7170e24e-6f85-45bf-b7ad-87251edbf85a
		sourceLineageTag: 37a431dc-8930-4642-8fef-eab7d32941a5
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: TOTAL_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column WRK_HRS
		dataType: double
		lineageTag: 4c824a17-06f8-4324-8a9c-35146fc3c450
		sourceLineageTag: 175c3fe1-ac10-4430-97c9-5a7fc0962523
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: WRK_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ABSNE_HRS
		dataType: double
		lineageTag: c9058004-1233-4ef1-b6a9-01c3aa1da019
		sourceLineageTag: 040df9fb-ad9c-45f2-baff-cde6fe2d3e06
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: ABSNE_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column LUNCH_HRS
		dataType: double
		lineageTag: f50e5373-62f6-4946-a542-f69f2f57719c
		sourceLineageTag: 352d17b2-569a-4431-930d-8b46e11b1813
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: LUNCH_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OVERTIME_HRS
		dataType: double
		lineageTag: c38311a0-5061-40ef-a3c1-ff8954a1e799
		sourceLineageTag: 2f6c5134-cda9-4d9a-8612-f3a56f5e0615
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: OVERTIME_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Shift Start Time'
		dataType: string
		lineageTag: 20899d55-6547-445d-959b-f3b74369f831
		sourceLineageTag: f338d512-a036-4959-8444-555712fc70a7
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Shift Start Time

		annotation SummarizationSetBy = User

	column SHIFT_START_TM_2
		dataType: double
		lineageTag: 041671a8-cb68-4e08-acf1-ed20c1c476a6
		sourceLineageTag: 2f6f68b8-10ee-4b76-b882-bcdb9005b2b0
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: SHIFT_START_TM_2

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Shift End Time'
		dataType: string
		lineageTag: b66123ad-5c2e-4e03-8f93-8ec829e57f70
		sourceLineageTag: 142c6e0d-2632-4eaf-a60c-0d565cd9fb54
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Shift End Time

		annotation SummarizationSetBy = User

	column SHIFT_END_TM_2
		dataType: double
		lineageTag: 221e39b8-f433-4d27-b5ae-2b98cd8a81e9
		sourceLineageTag: 8c6c654e-dfed-4326-b40f-cad91ab9623c
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: SHIFT_END_TM_2

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column APPRVD_WORKING_HRS
		dataType: double
		lineageTag: c477c273-6d69-4955-b750-72c697947697
		sourceLineageTag: fc120b2a-ddfb-4c11-ab72-419928abcf73
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: APPRVD_WORKING_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Shift Scheduled Start Time'
		dataType: string
		lineageTag: 2b6767aa-c334-46e2-802e-40c8a6bc37d6
		sourceLineageTag: 7a3eb1ef-baaa-40e9-946c-222bb2ff1d17
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Shift Scheduled Start Time

		annotation SummarizationSetBy = User

	column 'Shift Scheduled End Time'
		dataType: string
		lineageTag: 52f0efac-a404-452c-9acd-79f338707660
		sourceLineageTag: dc36c618-8168-4bce-9e25-e47b4fed3bce
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Shift Scheduled End Time

		annotation SummarizationSetBy = User

	column Comments
		dataType: string
		lineageTag: f47a64cb-37cf-44cd-a63d-3adb5c7a9262
		sourceLineageTag: 6ec69d69-21d2-4f45-97f0-00ddf05cb8e2
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Comments

		annotation SummarizationSetBy = User

	column ETL_SRC_SYS_CD
		dataType: string
		lineageTag: d3897ebc-19d3-4070-a80c-fc88ba957636
		sourceLineageTag: e7ea2d31-60cc-4214-8790-a67ee67626a6
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ETL_SRC_SYS_CD

		annotation SummarizationSetBy = User

	column ETL_CREATED_TS
		dataType: dateTime
		formatString: General Number
		lineageTag: 07e0fe54-97e9-431c-9f45-76853f3f516b
		sourceLineageTag: c4f00d4e-ab0b-46f9-b79f-83e30e6aab49
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ETL_CREATED_TS

		annotation SummarizationSetBy = User

	column ETL_UPDTD_TS
		dataType: dateTime
		formatString: General Number
		lineageTag: 7a096d09-3f9b-4b66-9a82-2d69581f460e
		sourceLineageTag: d473eb72-0a40-4161-a91d-da9bd61f2418
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: ETL_UPDTD_TS

		annotation SummarizationSetBy = User

	column COST_CNTR_KEY
		dataType: int64
		formatString: 0
		lineageTag: f65d8ea7-1ae3-4852-bede-257aa3313347
		sourceLineageTag: 0631fee5-98a2-4f83-af47-bd2c74ffa4f1
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: COST_CNTR_KEY

		annotation SummarizationSetBy = User

	column CMPNY_KEY
		dataType: int64
		formatString: 0
		lineageTag: cb7b33f8-1756-4fc7-951a-9b7149c3d220
		sourceLineageTag: 1f4ea2cf-623d-4dcf-84d7-0b983ce0c520
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: CMPNY_KEY

		annotation SummarizationSetBy = User

	column PLNT_KEY
		dataType: int64
		formatString: 0
		lineageTag: b5d3fd74-8208-414e-910a-7bce78b213a7
		sourceLineageTag: 9bdc1fa9-45a9-47f1-a9be-2b33fa4db4ec
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: PLNT_KEY

		annotation SummarizationSetBy = User

	column PERSONEL_AREA_KEY
		dataType: int64
		formatString: 0
		lineageTag: e115249e-1e8c-4262-8319-ed9afc0f741b
		sourceLineageTag: 1df02135-5b24-48bc-a6e0-7b0ae46e4790
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: PERSONEL_AREA_KEY

		annotation SummarizationSetBy = User

	column FLEX_BAL_TS
		dataType: double
		lineageTag: d3904611-90cd-42e9-ac88-159ad006a3c6
		sourceLineageTag: 4cfc7efd-62ce-4c5f-94c0-aa2ef015ff07
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: FLEX_BAL_TS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Approver User ID'
		dataType: string
		lineageTag: 6fac287e-f2d9-4628-ac3a-0411f2469ad0
		sourceLineageTag: 58eba140-38fc-42d7-b8a8-6c944386fffb
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: Approver User ID

		annotation SummarizationSetBy = User

	column PAID_BRK
		dataType: double
		lineageTag: cb403f40-9834-4b0e-9e98-1681c2ea62a0
		sourceLineageTag: 6700cc8b-f98d-4b7a-9366-9180c7108360
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: PAID_BRK

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ANNUAL_LEAVE_HRS
		dataType: double
		lineageTag: 9db516de-0114-40b3-afc4-8daf97363ee3
		sourceLineageTag: d67bf23a-f545-48bc-952a-228bc1169d0e
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: ANNUAL_LEAVE_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OTHR_LEAVE_HRS
		dataType: double
		lineageTag: a54de40c-d674-4756-910c-cd22f7dc9f54
		sourceLineageTag: 89ca64e3-cd5a-4f60-93f2-94412462e90b
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: OTHR_LEAVE_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SICK_LEAVE_HRS
		dataType: double
		lineageTag: 259135b5-0088-4e7b-983d-cee64d6f35a3
		sourceLineageTag: aae0655b-c407-4392-9d65-86aa1335047f
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: SICK_LEAVE_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UNPAID_LEAVE_HRS
		dataType: double
		lineageTag: ceb9512c-5dbf-4d27-9586-59939d067d09
		sourceLineageTag: 451dcd1b-6f05-4076-8f7f-6a415db32882
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: UNPAID_LEAVE_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PUNCH_IN_OUT_HRS
		dataType: double
		lineageTag: c246a26c-51cc-4de8-a554-7cf43138030c
		sourceLineageTag: 2de01d3f-50d5-4fd1-bc6d-66fd9c20db79
		dataCategory: Uncategorized
		summarizeBy: sum
		sourceColumn: PUNCH_IN_OUT_HRS

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SGK_OPERREG_PLANT
		dataType: string
		lineageTag: bd7a5239-9385-4fa6-b49c-b2a00b08e832
		sourceLineageTag: 34e13f84-9843-4701-8962-a8e481c41a23
		dataCategory: Uncategorized
		summarizeBy: none
		sourceColumn: SGK_OPERREG_PLANT

		annotation SummarizationSetBy = User

	partition 'Fact Time Card 2' = entity
		mode: directQuery
		source
			entityName: Fact Time Card
			expressionSource: 'DirectQuery to AS - TimeCards_CATSDB'

