table 'Fact Service Order Costs'
	lineageTag: c29baef8-c5c3-4536-bf36-ea74f492a02a

	measure 'Actual Costs Company Currency' =
			CALCULATE(
			    SUM('Fact Service Order Costs'[CMPNY_CRNCY_VAL]),
			    FILTER(
			        'Fact Service Order Costs',
			        'Fact Service Order Costs'[TRNSCTN_TYP] = "RKL"
			    )
			)
		lineageTag: cba007d6-9cb6-44e1-8ab4-425b7f7bdc91

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Actual Costs Document Currency' =
			CALCULATE(
			    SUM('Fact Service Order Costs'[DOCMT_CRNCY_VAL]),
			    FILTER(
			        'Fact Service Order Costs',
			        'Fact Service Order Costs'[TRNSCTN_TYP] = "RKL"
			    )
			)
		lineageTag: 15e73b6a-8c23-43d8-895b-387ead5be735

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Actual Costs Group Currency' =
			CALCULATE(
			    SUM('Fact Service Order Costs'[GROUP_CRNCY_VAL]),
			    FILTER(
			        'Fact Service Order Costs',
			        'Fact Service Order Costs'[TRNSCTN_TYP] = "RKL"
			    )
			)
		lineageTag: 6b96dcca-8309-4f30-ac3e-6079f6ef39c5

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Company Currency Value' = sum('Fact Service Order Costs'[CMPNY_CRNCY_VAL])
		lineageTag: dc241b14-480c-44c0-aaa8-ed323651b07b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Document Currency Value' = sum('Fact Service Order Costs'[DOCMT_CRNCY_VAL])
		lineageTag: ee047b9e-2687-44c9-92d0-2da3dd4ef21d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Group Currency Value' = sum('Fact Service Order Costs'[GROUP_CRNCY_VAL])
		lineageTag: 1febd6dc-a825-49a1-b170-37be94ede194

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Quantity Total' = sum('Fact Service Order Costs'[QTY_TOTAL])
		lineageTag: 8f685172-22fd-4150-99c7-b64cd2134621

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SERVC_ORDER_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 3c0373af-ac2d-4a08-9c27-87e1bacc2231
		summarizeBy: none
		sourceColumn: SERVC_ORDER_KEY

		annotation SummarizationSetBy = Automatic

	column PRODUCING_PLNT_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 0373349d-56be-44d5-9506-88c51a386929
		summarizeBy: none
		sourceColumn: PRODUCING_PLNT_KEY

		annotation SummarizationSetBy = Automatic

	column 'Document Number'
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		lineageTag: 82506b59-6593-4ae3-b2f5-b9f35e377741
		summarizeBy: sum
		sourceColumn: Document Number

		annotation SummarizationSetBy = Automatic

	column Period
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 85943125-edc4-4426-b9a9-1a25e049f5fb
		summarizeBy: sum
		sourceColumn: Period

		annotation SummarizationSetBy = Automatic

	column DOCMT_CRNCY_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ba242ec1-a160-4aa3-8851-be31b8d16eb9
		summarizeBy: none
		sourceColumn: DOCMT_CRNCY_KEY

		annotation SummarizationSetBy = Automatic

	column CMPNY_CRNCY_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: d2e4d403-5491-4561-949d-ce70716a8e9a
		summarizeBy: none
		sourceColumn: CMPNY_CRNCY_KEY

		annotation SummarizationSetBy = Automatic

	column GROUP_CRNCY_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ce7151b6-d106-40f1-9190-3642d7c1a49a
		summarizeBy: none
		sourceColumn: GROUP_CRNCY_KEY

		annotation SummarizationSetBy = Automatic

	column DOCMT_CRNCY_VAL
		dataType: double
		sourceProviderType: decimal(18, 3)
		lineageTag: f4c6e9cb-7782-43c9-8d81-9cdedbec5487
		summarizeBy: sum
		sourceColumn: DOCMT_CRNCY_VAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CMPNY_CRNCY_VAL
		dataType: double
		sourceProviderType: decimal(18, 3)
		lineageTag: 31fcb35b-c3ce-4d78-b463-c2730effd850
		summarizeBy: sum
		sourceColumn: CMPNY_CRNCY_VAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GROUP_CRNCY_VAL
		dataType: double
		sourceProviderType: decimal(18, 3)
		lineageTag: 773b892a-af96-4f71-b951-df2c1a17c3d9
		summarizeBy: sum
		sourceColumn: GROUP_CRNCY_VAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column QTY_TOTAL
		dataType: double
		sourceProviderType: decimal(18, 3)
		lineageTag: 16288c52-8754-45e4-a8e0-633787f158c1
		summarizeBy: sum
		sourceColumn: QTY_TOTAL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column UoM
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: bbd19a92-3b53-4c72-a079-03b771ae7d39
		summarizeBy: none
		sourceColumn: UoM

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: f9bd2a72-8409-4abe-9461-d4566574a9e3
		summarizeBy: sum
		sourceColumn: Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'Value Type'
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: 16e42f5f-feea-4231-8ef4-c91da323ceed
		summarizeBy: none
		sourceColumn: Value Type

		annotation SummarizationSetBy = Automatic

	column COST_ELEMNT_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: fcf26813-446e-4c80-a6fd-6395ce81546a
		summarizeBy: none
		sourceColumn: COST_ELEMNT_KEY

		annotation SummarizationSetBy = Automatic

	column TRNSCTN_TYP
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: f9cf0c51-4fed-4f15-beef-49975eb2b216
		summarizeBy: none
		sourceColumn: TRNSCTN_TYP

		annotation SummarizationSetBy = Automatic

	column 'Partner Object'
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: ce2c3042-4393-4c29-a18c-6fedcdd214c2
		summarizeBy: none
		sourceColumn: Partner Object

		annotation SummarizationSetBy = Automatic

	column MATRL_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: f91c4590-2ecd-4a1c-ae15-6a9f091e9b3b
		summarizeBy: none
		sourceColumn: MATRL_KEY

		annotation SummarizationSetBy = Automatic

	column CMPNY_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 8fc98f52-93d3-4324-8cbd-44fd1fad6e87
		summarizeBy: none
		sourceColumn: CMPNY_KEY

		annotation SummarizationSetBy = Automatic

	column PRTNR_CMPNY_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: fd04c6ba-8251-47ba-a913-ab95adb6b51d
		summarizeBy: none
		sourceColumn: PRTNR_CMPNY_KEY

		annotation SummarizationSetBy = Automatic

	column 'Order Type'
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: cf011f2e-57ee-4865-9eb0-5399114bd01d
		summarizeBy: none
		sourceColumn: Order Type

		annotation SummarizationSetBy = Automatic

	column 'Order Category'
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: c14efc81-1b3d-4680-a61b-f35755732a02
		summarizeBy: none
		sourceColumn: Order Category

		annotation SummarizationSetBy = Automatic

	column MAINTENANCE_WRK_CNTR_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: afc0e63f-2567-476b-bde1-46caefd1603f
		summarizeBy: none
		sourceColumn: MAINTENANCE_WRK_CNTR_KEY

		annotation SummarizationSetBy = Automatic

	column 'Object Class'
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: 3756b46e-ca22-4bde-a6b8-32630b7917e7
		summarizeBy: none
		sourceColumn: Object Class

		annotation SummarizationSetBy = Automatic

	column RESPNSBLE_COST_CNTR_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 5a8cada6-0297-42a1-b584-c234d09e4339
		summarizeBy: none
		sourceColumn: RESPNSBLE_COST_CNTR_KEY

		annotation SummarizationSetBy = Automatic

	column PROFT_CNTR_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: f0708996-6e7b-42f7-9a96-4240658ac5c3
		summarizeBy: none
		sourceColumn: PROFT_CNTR_KEY

		annotation SummarizationSetBy = Automatic

	column ETL_SRC_SYS_CD
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: a13a5498-7130-40a2-9821-93979ac0c378
		summarizeBy: none
		sourceColumn: ETL_SRC_SYS_CD

		annotation SummarizationSetBy = Automatic

	column ETL_CREATED_TS
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 1cd9c69c-55d8-4413-83da-0edf0bc0681a
		summarizeBy: none
		sourceColumn: ETL_CREATED_TS

		annotation SummarizationSetBy = Automatic

	column ETL_UPDTD_TS
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: c147d3ae-2399-46be-96be-9bc429c20316
		summarizeBy: none
		sourceColumn: ETL_UPDTD_TS

		annotation SummarizationSetBy = Automatic

	column LOC_PLNT_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 9575aae5-0f82-4f62-9666-7528213676c1
		summarizeBy: none
		sourceColumn: LOC_PLNT_KEY

		annotation SummarizationSetBy = Automatic

	column 'Type Of Cost'
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: d7f35d3a-a09c-45eb-be52-1fca421abd58
		summarizeBy: none
		sourceColumn: Type Of Cost

		annotation SummarizationSetBy = Automatic

	column PERSONEL_NUM_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: e398dc28-f034-4788-a93c-3fc9bf44e711
		summarizeBy: none
		sourceColumn: PERSONEL_NUM_KEY

		annotation SummarizationSetBy = Automatic

	column FUNCTNL_AREA_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: e4df2f81-260f-4ed3-adff-c6a5747d79d1
		summarizeBy: none
		sourceColumn: FUNCTNL_AREA_KEY

		annotation SummarizationSetBy = Automatic

	column 'Debit/Credit Indicator'
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: c5ba1ee2-813d-448a-bacb-43e5cb789da5
		summarizeBy: none
		sourceColumn: Debit/Credit Indicator

		annotation SummarizationSetBy = Automatic

	column 'Reference Document Number'
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: b9c2794f-7df0-41c9-8f3f-5c7657171325
		summarizeBy: none
		sourceColumn: Reference Document Number

		annotation SummarizationSetBy = Automatic

	column 'Controlling Area'
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: d75eedf0-2ae1-466b-9ec0-779222782920
		summarizeBy: none
		sourceColumn: Controlling Area

		annotation SummarizationSetBy = Automatic

	column PLNT_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 8a9dd9cc-e61a-4f5d-a335-8260f07aef0b
		summarizeBy: none
		sourceColumn: PLNT_KEY

		annotation SummarizationSetBy = Automatic

	column PSTNG_DATE_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: e6b9dce3-2113-4b24-8404-43de26320acd
		summarizeBy: none
		sourceColumn: PSTNG_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column 'Value Type Description'
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: 0103cece-79ed-4deb-a735-da056ca9c3d2
		summarizeBy: none
		sourceColumn: Value Type Description

		annotation SummarizationSetBy = Automatic

	column 'Transaction Type Description'
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: e0059400-c6bc-46f3-a9a3-d0964b3c0232
		summarizeBy: none
		sourceColumn: Transaction Type Description

		annotation SummarizationSetBy = Automatic

	column 'Controlling Area Description'
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: fa136229-b719-4a83-8d41-cbb563e7d9ee
		summarizeBy: none
		sourceColumn: Controlling Area Description

		annotation SummarizationSetBy = Automatic

	column 'Is Internal  Posting'
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: 8c98e545-e7f0-4b0d-9a82-1bb8132effcb
		summarizeBy: none
		sourceColumn: Is Internal  Posting

		annotation SummarizationSetBy = Automatic

	column ACTIVITY_TYP_KEY
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		lineageTag: 4f45e381-fad2-4650-ac91-d894d6addba0
		summarizeBy: none
		sourceColumn: ACTIVITY_TYP_KEY

		annotation SummarizationSetBy = Automatic

	column 'Posting Row'
		dataType: int64
		isNullable: false
		formatString: 0
		sourceProviderType: int
		lineageTag: e6aa0a96-d571-4642-8249-ac9f92fc0eca
		summarizeBy: sum
		sourceColumn: Posting Row

		annotation SummarizationSetBy = Automatic

	column 'Is INTER Company Posting'
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: d4253849-e4dc-4c4c-83fb-aafb289ad1c5
		summarizeBy: none
		sourceColumn: Is INTER Company Posting

		annotation SummarizationSetBy = Automatic

	column 'Is INTRA Company Posting'
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: fecad832-7fed-4ec3-b735-0d1da063f468
		summarizeBy: none
		sourceColumn: Is INTRA Company Posting

		annotation SummarizationSetBy = Automatic

	column PRTNR_COST_CNTR_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: a39981da-db2d-47cc-8ac3-a1e588f7c259
		summarizeBy: none
		sourceColumn: PRTNR_COST_CNTR_KEY

		annotation SummarizationSetBy = Automatic

	column TCHNCL_COMPLETION_DATE_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: e32a6db4-c18d-4133-b5dc-14127f160ff1
		summarizeBy: none
		sourceColumn: TCHNCL_COMPLETION_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column DOCMT_DATE_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 07c3a1ec-3f14-4f86-b4c2-ad058eefaa56
		summarizeBy: none
		sourceColumn: DOCMT_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column CREATION_DATE_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: bb3ddb31-79cb-41d5-8b0b-b8931a0cae8a
		summarizeBy: none
		sourceColumn: CREATION_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column 'Posting Creation Date Timestamp'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 9e48fc45-4bde-40c8-93b3-82ad0e539ca6
		summarizeBy: none
		sourceColumn: Posting Creation Date Timestamp

		annotation SummarizationSetBy = Automatic

	column PERSONNEL_PLANT_REGION_PLANT
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: 7bc42afc-ed90-4f6f-b578-587589a6ad7f
		summarizeBy: none
		sourceColumn: PERSONNEL_PLANT_REGION_PLANT

		annotation SummarizationSetBy = Automatic

	column PLANT_REGION_PLANT
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: fae119ea-ac92-4583-b00f-7c6f8eebb26f
		summarizeBy: none
		sourceColumn: PLANT_REGION_PLANT

		annotation SummarizationSetBy = Automatic

	column LOCATION_PLANT_REGION_PLANT
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: 8d12a656-4d57-4596-8855-acad5c5f5fdc
		summarizeBy: none
		sourceColumn: LOCATION_PLANT_REGION_PLANT

		annotation SummarizationSetBy = Automatic

	column PRODUCING_PLANT_REGION_PLANT
		dataType: string
		sourceProviderType: varchar(max)
		lineageTag: a713f680-ebde-43c2-b5cf-5cce3d69cef8
		summarizeBy: none
		sourceColumn: PRODUCING_PLANT_REGION_PLANT

		annotation SummarizationSetBy = Automatic

	partition 'Fact Service Order Costs' = m
		mode: directQuery
		source =
				let
				    Source = Sql.Database("c2rbjb2faruufollpwcl3w3nue-ozi5pscjxf7e7jsyxglgapwiym.datawarehouse.fabric.microsoft.com", "GLOBAL_EDW"),
				    Propelis_EDW_T_FACT_PRD_SERVCST_CUR_D = Source{[Schema="Propelis",Item="EDW_T_FACT_PRD_SERVCST_CUR_D"]}[Data]
				in
				    Propelis_EDW_T_FACT_PRD_SERVCST_CUR_D

	changedProperty = Name

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

