CREATE   PROCEDURE [dbo].[Proc_EDW_T_D_SAL_INVOICE_CUR_D]
AS
BEGIN
    ----------------------------------------------------------------------
    -- Update existing records in target table
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[Sales Order Invoice ID] = S.[SALES_ORDER_INVC_ID],
        T.[Invoice Company Code] = S.[CMPNY_CD],
        T.[Invoice Billing Type Code] = S.[BILLING_TYP_CD],
        T.[Invoice Billing Category] = S.[BILLING_CTGRY],
        T.[Invoice SD Document Category] = S.[SD_DOCMT_CTGRY],
        T.[Invoice Sales Organization] = S.[SALES_ORGZTN],
        T.[Invoice Distribution Channel] = S.[DISTRBN_CHNL],
        T.[Invoice Divison] = S.[DIVISON],
        T.[Invoice Invoice Pricing Procedure] = S.[PRICING_PROC],
        T.[Invoice Document Condition Number] = S.[DOCMT_COND_NUM],
        T.[Invoice Shipping Condition] = S.[SHIPG_COND],
        T.[Invoice Price Group] = S.[PRICE_GROUP],
        T.[Invoice Customer Group] = S.[CUST_GROUP],
        T.[Invoice Price List] = S.[PRICE_LIST],
        T.[Invoice Payment Reference] = S.[PYMT_REF],
        T.[Invoice Payment Terms] = S.[PYMT_TRMS],
        T.[Invoice Incoterms] = S.[INCOTERMS],
        T.[Invoice Incoterms 2] = S.[INCOTERMS2],
        T.[Invoice Exchange Rate] = S.[EXCHG_RT],
        T.[Invoice Net Value] = S.[NET_VAL],
        T.[Invoice Statistical Currency] = S.[STATISTICAL_CRNCY],
        T.[Invoice List Type] = S.[INVC_LIST_TYP],
        T.[Invoice Reference] = S.[REF],
        T.[Invoice Invoice Date] = S.[INVC_DATE],
        T.[Invoice Created Date] = S.[CREATED_DATE],
        T.[Invoice Created User ID] = S.[CREATED_USR_ID],
        T.[Invoice Updated Date] = S.[UPDTD_DATE],
        T.[Invoice Updated User ID] = S.[UPDTD_USR_ID],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE] = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE] = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND] = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Invoice Billing Document Cancelled Indicator] = S.[BILLING_DOCMT_CANCELLED_IND],
        T.[Invoice Creation Date] = S.[CREATION_DATE],
        T.[Invoice Changed On Date] = S.[CHANGED_ON_DATE],
        T.[Invoice Customer Purchase Order Number] = S.[CUST_PURCHS_ORDER_NUM],
        T.[Invoice Accounting Transfer Status] = S.[ACCTNG_TRSFR_STATUS],
        T.[Invoice Currency Key of Credit Control Area] = S.[CRNCY_KEY_OF_CREDIT_CTRL_AREA],
        T.[Invoice Accounting Document Number] = S.[ACCTNG_DOCMT_NUM],
        T.[Invoice SD Document Currency] = S.[SD_DOCMT_CRNCY_DESC],
        T.[Invoice Company Description] = S.[CMPNY_DESC],
        T.[Invoice Billing Type Description] = S.[BILLING_TYP_DESC],
        T.[Invoice Billing Category Description] = S.[BILLING_CTGRY_DESC],
        T.[Invoice SD Document Category Description] = S.[SD_DOCMT_CTGRY_DESC],
        T.[Invoice Sales Organization Description] = S.[SALES_ORGZTN_DESC],
        T.[Invoice Distribution Channel Description] = S.[DISTRBN_CHNL_DESC],
        T.[Invoice Division Description] = S.[DIVISION_DESC],
        T.[Invoice Shipping Condition Description] = S.[SHIPG_COND_DESC],
        T.[Invoice Price Group Description] = S.[PRICE_GROUP_DESC],
        T.[Invoice Customer Group Description] = S.[CUST_GROUP_DESC],
        T.[Invoice Price List Description] = S.[PRICE_LIST_DESC],
        T.[Invoice Payment Terms Description] = S.[PYMT_TRMS_DESC],
        T.[Invoice Inco Terms Description] = S.[INCO_TRMS_DESC],
        T.[Invoice Statistical Currency Description] = S.[STATISTICAL_CRNCY_DESC],
        T.[Invoice List Type Description] = S.[INVC_LIST_TYP_DESC],
        T.[Invoice Accounting Transfer Status Description] = S.[ACCTNG_TRSFR_STATUS_DESC],
        T.[CANCELLED_DOCMT_NUM] = S.[CANCELLED_DOCMT_NUM],
        T.[Invoice Terms Discount Percentage] = S.[TRMS_DISCNT_PRCNTG],
        T.[Invoice Customer Group 6] = S.[CUST_GROUP_6],
        T.[Invoice Customer Group 7] = S.[CUST_GROUP_7],
        T.[Invoice Customer Group 8] = S.[CUST_GROUP_8],
        T.[Invoice Customer Group 9] = S.[CUST_GROUP_9],
        T.[Invoice Customer Group 10] = S.[CUST_GROUP_10],
        T.[Invoice Customer Group 6 Description] = S.[CUST_GROUP_6_DESC],
        T.[Invoice Customer Group 7 Description] = S.[CUST_GROUP_7_DESC],
        T.[Invoice Customer Group 8 Description] = S.[CUST_GROUP_8_DESC],
        T.[Invoice Customer Group 9 Description] = S.[CUST_GROUP_9_DESC],
        T.[Invoice Customer Group 10 Description] = S.[CUST_GROUP_10_DESC]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_INVOICE_CUR_D] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_SAL_INVOICE_CUR_D] S
        ON T.[INVC_KEY] = S.[INVC_KEY];

    ----------------------------------------------------------------------
    -- Insert new records into target table
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_INVOICE_CUR_D] (
        [INVC_KEY],
        [Sales Order Invoice ID],
        [Invoice Company Code],
        [Invoice Billing Type Code],
        [Invoice Billing Category],
        [Invoice SD Document Category],
        [Invoice Sales Organization],
        [Invoice Distribution Channel],
        [Invoice Divison],
        [Invoice Invoice Pricing Procedure],
        [Invoice Document Condition Number],
        [Invoice Shipping Condition],
        [Invoice Price Group],
        [Invoice Customer Group],
        [Invoice Price List],
        [Invoice Payment Reference],
        [Invoice Payment Terms],
        [Invoice Incoterms],
        [Invoice Incoterms 2],
        [Invoice Exchange Rate],
        [Invoice Net Value],
        [Invoice Statistical Currency],
        [Invoice List Type],
        [Invoice Reference],
        [Invoice Invoice Date],
        [Invoice Created Date],
        [Invoice Created User ID],
        [Invoice Updated Date],
        [Invoice Updated User ID],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Invoice Billing Document Cancelled Indicator],
        [Invoice Creation Date],
        [Invoice Changed On Date],
        [Invoice Customer Purchase Order Number],
        [Invoice Accounting Transfer Status],
        [Invoice Currency Key of Credit Control Area],
        [Invoice Accounting Document Number],
        [Invoice SD Document Currency],
        [Invoice Company Description],
        [Invoice Billing Type Description],
        [Invoice Billing Category Description],
        [Invoice SD Document Category Description],
        [Invoice Sales Organization Description],
        [Invoice Distribution Channel Description],
        [Invoice Division Description],
        [Invoice Shipping Condition Description],
        [Invoice Price Group Description],
        [Invoice Customer Group Description],
        [Invoice Price List Description],
        [Invoice Payment Terms Description],
        [Invoice Inco Terms Description],
        [Invoice Statistical Currency Description],
        [Invoice List Type Description],
        [Invoice Accounting Transfer Status Description],
        [CANCELLED_DOCMT_NUM],
        [Invoice Terms Discount Percentage],
        [Invoice Customer Group 6],
        [Invoice Customer Group 7],
        [Invoice Customer Group 8],
        [Invoice Customer Group 9],
        [Invoice Customer Group 10],
        [Invoice Customer Group 6 Description],
        [Invoice Customer Group 7 Description],
        [Invoice Customer Group 8 Description],
        [Invoice Customer Group 9 Description],
        [Invoice Customer Group 10 Description]
    )
    SELECT
        S.[INVC_KEY],
        S.[SALES_ORDER_INVC_ID],
        S.[CMPNY_CD],
        S.[BILLING_TYP_CD],
        S.[BILLING_CTGRY],
        S.[SD_DOCMT_CTGRY],
        S.[SALES_ORGZTN],
        S.[DISTRBN_CHNL],
        S.[DIVISON],
        S.[PRICING_PROC],
        S.[DOCMT_COND_NUM],
        S.[SHIPG_COND],
        S.[PRICE_GROUP],
        S.[CUST_GROUP],
        S.[PRICE_LIST],
        S.[PYMT_REF],
        S.[PYMT_TRMS],
        S.[INCOTERMS],
        S.[INCOTERMS2],
        S.[EXCHG_RT],
        S.[NET_VAL],
        S.[STATISTICAL_CRNCY],
        S.[INVC_LIST_TYP],
        S.[REF],
        S.[INVC_DATE],
        S.[CREATED_DATE],
        S.[CREATED_USR_ID],
        S.[UPDTD_DATE],
        S.[UPDTD_USR_ID],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[BILLING_DOCMT_CANCELLED_IND],
        S.[CREATION_DATE],
        S.[CHANGED_ON_DATE],
        S.[CUST_PURCHS_ORDER_NUM],
        S.[ACCTNG_TRSFR_STATUS],
        S.[CRNCY_KEY_OF_CREDIT_CTRL_AREA],
        S.[ACCTNG_DOCMT_NUM],
        S.[SD_DOCMT_CRNCY_DESC],
        S.[CMPNY_DESC],
        S.[BILLING_TYP_DESC],
        S.[BILLING_CTGRY_DESC],
        S.[SD_DOCMT_CTGRY_DESC],
        S.[SALES_ORGZTN_DESC],
        S.[DISTRBN_CHNL_DESC],
        S.[DIVISION_DESC],
        S.[SHIPG_COND_DESC],
        S.[PRICE_GROUP_DESC],
        S.[CUST_GROUP_DESC],
        S.[PRICE_LIST_DESC],
        S.[PYMT_TRMS_DESC],
        S.[INCO_TRMS_DESC],
        S.[STATISTICAL_CRNCY_DESC],
        S.[INVC_LIST_TYP_DESC],
        S.[ACCTNG_TRSFR_STATUS_DESC],
        S.[CANCELLED_DOCMT_NUM],
        S.[TRMS_DISCNT_PRCNTG],
        S.[CUST_GROUP_6],
        S.[CUST_GROUP_7],
        S.[CUST_GROUP_8],
        S.[CUST_GROUP_9],
        S.[CUST_GROUP_10],
        S.[CUST_GROUP_6_DESC],
        S.[CUST_GROUP_7_DESC],
        S.[CUST_GROUP_8_DESC],
        S.[CUST_GROUP_9_DESC],
        S.[CUST_GROUP_10_DESC]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_SAL_INVOICE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_INVOICE_CUR_D] T
        ON T.[INVC_KEY] = S.[INVC_KEY]
    WHERE T.[INVC_KEY] IS NULL;
END