CREATE   PROCEDURE [dbo].[Proc_EDW_T_D_MST_NOTFICN_CUR_D]
AS
BEGIN
    ----------------------------------------------------------------------
    -- Step 1: Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[Notification]                          = S.[NOTIFICATION],
        T.[Notification Type]                     = S.[NOTIFICATION_TYP],
        T.[Notification Description]              = S.[NOTIFICATION_DESC],
        T.[Notification Priority]                 = S.[NOTIFICATION_PRIORITY],
        T.[Notification Date]                     = S.[NOTIFICATION_DATE],
        T.[Notification Required Start Date]      = S.[NOTIFICATION_REQUIRED_START_DAT],
        T.[Notification Required End Date]        = S.[NOTIFICATION_REQUIRED_END_DATE],
        T.[ETL_SRC_SYS_CD]                        = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE]                = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE]                  = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND]                      = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS]                        = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS]                          = S.[ETL_UPDTD_TS],
        T.[Notification Timestamp]                = S.[NOTIFICATION_TS],
        T.[Reported By]                           = S.[RPTD_BY],
        T.[Notification Required Start Timestamp] = S.[NOTIFICATION_REQUIRED_START_TS],
        T.[Notification Required End Timestamp]   = S.[NOTIFICATION_REQUIRED_END_TS],
        T.[Object Number]                         = S.[OBJ_NUM],
        T.[Completion By Date]                    = S.[COMPLETION_BY_DATE],
        T.[Completion Timestamp]                  = S.[COMPLETION_TS],
        T.[Reference Date]                        = S.[REF_DATE],
        T.[Reference Time]                        = S.[REF_TM],
        T.[Work Center]                           = S.[WRK_CNTR],
        T.[Plant For Work Center]                 = S.[PLNT_FOR_WRK_CNTR],
        T.[Object Type]                           = S.[OBJ_TYP],
        T.[Sales Office]                          = S.[SALES_OFFC],
        T.[Sales Group]                           = S.[SALES_GROUP],
        T.[Notification Type Description]         = S.[NOTIFICATION_TYP_DESC],
        T.[Notification Priority Description]     = S.[NOTIFICATION_PRIORITY_DESC],
        T.[Sales Office Description]              = S.[SALES_OFFC_DESC],
        T.[Sales Group Description]               = S.[SALES_GROUP_DESC],
        T.[Created By]                            = S.[CREATED_BY],
        T.[Catalog Type Coding]                   = S.[CATLG_TYP_CODING],
        T.[Catalog Type Coding Description]       = S.[CATLG_TYP_CODING_DESC],
        T.[CD Group Coding]                       = S.[CD_GROUP_CODING],
        T.[CD Group Coding Description]           = S.[CD_GROUP_CODING_DESC],
        T.[Coding]                                = S.[CODING],
        T.[Coding Description]                    = S.[CODING_DESC],
        T.[Partner Number]                        = S.[PRTNR_NUM],
        T.[Partner Name]                          = S.[PRTNR_NAME]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_NOTFICN_CUR_D] AS T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_NOTFICN_CUR_D] AS S
        ON T.[NOTIFICATION_KEY] = S.[NOTIFICATION_KEY];

    ----------------------------------------------------------------------
    -- Step 2: Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_MST_NOTFICN_CUR_D] (
        [NOTIFICATION_KEY],
        [Notification],
        [Notification Type],
        [Notification Description],
        [Notification Priority],
        [Notification Date],
        [Notification Required Start Date],
        [Notification Required End Date],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Notification Timestamp],
        [Reported By],
        [Notification Required Start Timestamp],
        [Notification Required End Timestamp],
        [Object Number],
        [Completion By Date],
        [Completion Timestamp],
        [Reference Date],
        [Reference Time],
        [Work Center],
        [Plant For Work Center],
        [Object Type],
        [Sales Office],
        [Sales Group],
        [Notification Type Description],
        [Notification Priority Description],
        [Sales Office Description],
        [Sales Group Description],
        [Created By],
        [Catalog Type Coding],
        [Catalog Type Coding Description],
        [CD Group Coding],
        [CD Group Coding Description],
        [Coding],
        [Coding Description],
        [Partner Number],
        [Partner Name]
    )
    SELECT
        S.[NOTIFICATION_KEY],
        S.[NOTIFICATION],
        S.[NOTIFICATION_TYP],
        S.[NOTIFICATION_DESC],
        S.[NOTIFICATION_PRIORITY],
        S.[NOTIFICATION_DATE],
        S.[NOTIFICATION_REQUIRED_START_DAT],
        S.[NOTIFICATION_REQUIRED_END_DATE],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[NOTIFICATION_TS],
        S.[RPTD_BY],
        S.[NOTIFICATION_REQUIRED_START_TS],
        S.[NOTIFICATION_REQUIRED_END_TS],
        S.[OBJ_NUM],
        S.[COMPLETION_BY_DATE],
        S.[COMPLETION_TS],
        S.[REF_DATE],
        S.[REF_TM],
        S.[WRK_CNTR],
        S.[PLNT_FOR_WRK_CNTR],
        S.[OBJ_TYP],
        S.[SALES_OFFC],
        S.[SALES_GROUP],
        S.[NOTIFICATION_TYP_DESC],
        S.[NOTIFICATION_PRIORITY_DESC],
        S.[SALES_OFFC_DESC],
        S.[SALES_GROUP_DESC],
        S.[CREATED_BY],
        S.[CATLG_TYP_CODING],
        S.[CATLG_TYP_CODING_DESC],
        S.[CD_GROUP_CODING],
        S.[CD_GROUP_CODING_DESC],
        S.[CODING],
        S.[CODING_DESC],
        S.[PRTNR_NUM],
        S.[PRTNR_NAME]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_NOTFICN_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_NOTFICN_CUR_D] AS T
        ON T.[NOTIFICATION_KEY] = S.[NOTIFICATION_KEY]
    WHERE T.[NOTIFICATION_KEY] IS NULL;
END;