CREATE   PROCEDURE [dbo].[Proc_EDW_T_D_MST_COSCNTR_CUR_D]
AS
BEGIN
	UPDATE T
	SET
		T.[COST_CNTR_KEY] = S.[COST_CNTR_KEY],
		T.[Cost Center ID] = S.[COST_CNTR_ID],
		T.[Cost Center Long Description] = S.[COST_CNTR_LONG_DESC],
		T.[Cost Center Controlling Area ID] = S.[CONTROLLING_AREA_ID],
		T.[Cost Center Language Type Code] = S.[LANG_TYP_CD],
		T.[Cost Center Category] = S.[COST_CNTR_CTGRY],
		T.[Cost Center Hierarchy Area] = S.[HIERCHY_AREA],
		T.[Cost Center Company Code] = S.[CMPNY_CD],
		T.[Cost Center Plant ID] = S.[PLNT_ID],
		T.[Cost Center Profit Center ID] = S.[PROFT_CNTR_ID],
		T.[Cost Center Currency Code] = S.[CRNCY_CD],
		T.[Cost Center Address Line 1] = S.[ADRESS_LINE_1],
		T.[Cost Center Address Line 2] = S.[ADRESS_LINE_2],
		T.[Cost Center Address Line 3] = S.[ADRESS_LINE_3],
		T.[Cost Center City Name] = S.[CITY_NAME],
		T.[Cost Center District Name] = S.[DISTR_NAME],
		T.[Cost Center Postal Code] = S.[POSTAL_CD],
		T.[Cost Center Country Code] = S.[CNTRY_CD],
		T.[Cost Center Region Code] = S.[REGN_CD],
		T.[Cost Center Person Responsible] = S.[PERSON_RESPNSBLE],
		T.[Cost Center Flag Actual Revenues] = S.[FLG_ACTUAL_REVENUES],
		T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
		T.[ETL_EFFECTV_BEGIN_DATE] = S.[ETL_EFFECTV_BEGIN_DATE],
		T.[ETL_EFFECTV_END_DATE] = S.[ETL_EFFECTV_END_DATE],
		T.[ETL_CURR_RCD_IND] = S.[ETL_CURR_RCD_IND],
		T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
		T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
		T.[Cost Center Actual Primary Postings Lock Indicator] = S.[ACTUAL_PRIMARY_POSTINGS_LOCK_IN],
		T.[Cost Center Plan Primary Costs Lock Indicator] = S.[PLAN_PRIMARY_COSTS_LOCK_IND],
		T.[Cost Center Business Area] = S.[BIZ_AREA],
		T.[Cost Center Planning Revenues Lock Indicator] = S.[PLNG_REVENUES_LOCK_IND],
		T.[Cost Center PO Box] = S.[PO_BOX],
		T.[Cost Center Street] = S.[STR],
		T.[Cost Center User Responsible] = S.[USR_RESPNSBLE],
		T.[COST_CNTR_NAME] = S.[COST_CNTR_NAME],
		T.[Cost Center Short Description] = S.[COST_CNTR_SHORT_DESC],
		T.[Cost Center Controlling Area Description] = S.[CONTROLLING_AREA_DESC],
		T.[Cost Center Category Description] = S.[COST_CNTR_CTGRY_DESC],
		T.[Cost Center Company Description] = S.[CMPNY_DESC],
		T.[Cost Center Currency Description] = S.[CRNCY_DESC],
		T.[Cost Center Country Description] = S.[CNTRY_DESC],
		T.[Cost Center Business Area Description] = S.[BIZ_AREA_DESC],
		T.[Cost Center Actual Secondary Cost Lock Indicator] = S.[ACTUAL_SECONDARY_COST_LOCK_IND],
		T.[Cost Center Plan Secondary Cost Lock Indicator] = S.[PLAN_SECONDARY_COST_LOCK_IND],
		T.[Cost Center Functional Area] = S.[FUNCTNL_AREA],
		T.[Cost Center Functional Area Description] = S.[FUNCTNL_AREA_DESC],
		T.[Cost Center Tax Jurisdiction] = S.[TAX_JRSDCTN],
		T.[FUNCTION_OF_COST_CNTR] = S.[FUNCTION_OF_COST_CNTR],
		T.[Cost Center Plant Description] = S.[PLNT_DESC],
		T.[Cost Center Created On] = S.[CREATED_ON],
		T.[Cost Center Valid To Date] = S.[VALID_TO_DATE],
		T.[Cost Center Valid From Date] = S.[VALID_FROM_DATE]

FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_COSCNTR_CUR_D] T
INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_COSCNTR_CUR_D] S
    ON T.[COST_CNTR_KEY] = S.[COST_CNTR_KEY];

-- Step 2: Insert new records from [GLOBAL_EDW_MIRROR] to [GLOBAL_EDW] where COST_CNTR_KEY does not exist

    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_MST_COSCNTR_CUR_D] 
	(
T.[COST_CNTR_KEY],
T.[Cost Center ID],
T.[Cost Center Long Description],
T.[Cost Center Controlling Area ID],
T.[Cost Center Language Type Code],
T.[Cost Center Category],
T.[Cost Center Hierarchy Area],
T.[Cost Center Company Code],
T.[Cost Center Plant ID],
T.[Cost Center Profit Center ID],
T.[Cost Center Currency Code],
T.[Cost Center Address Line 1],
T.[Cost Center Address Line 2],
T.[Cost Center Address Line 3],
T.[Cost Center City Name],
T.[Cost Center District Name],
T.[Cost Center Postal Code],
T.[Cost Center Country Code],
T.[Cost Center Region Code],
T.[Cost Center Person Responsible],
T.[Cost Center Flag Actual Revenues],
T.[ETL_SRC_SYS_CD],
T.[ETL_EFFECTV_BEGIN_DATE],
T.[ETL_EFFECTV_END_DATE],
T.[ETL_CURR_RCD_IND],
T.[ETL_CREATED_TS],
T.[ETL_UPDTD_TS],
T.[Cost Center Actual Primary Postings Lock Indicator],
T.[Cost Center Plan Primary Costs Lock Indicator],
T.[Cost Center Business Area],
T.[Cost Center Planning Revenues Lock Indicator],
T.[Cost Center PO Box],
T.[Cost Center Street],
T.[Cost Center User Responsible],
T.[COST_CNTR_NAME],
T.[Cost Center Short Description],
T.[Cost Center Controlling Area Description],
T.[Cost Center Category Description],
T.[Cost Center Company Description],
T.[Cost Center Currency Description],
T.[Cost Center Country Description],
T.[Cost Center Business Area Description],
T.[Cost Center Actual Secondary Cost Lock Indicator],
T.[Cost Center Plan Secondary Cost Lock Indicator],
T.[Cost Center Functional Area],
T.[Cost Center Functional Area Description],
T.[Cost Center Tax Jurisdiction],
T.[FUNCTION_OF_COST_CNTR],
T.[Cost Center Plant Description],
T.[Cost Center Created On],
T.[Cost Center Valid To Date],
T.[Cost Center Valid From Date]
)
SELECT 

S.[COST_CNTR_KEY],
S.[COST_CNTR_ID],
S.[COST_CNTR_LONG_DESC],
S.[CONTROLLING_AREA_ID],
S.[LANG_TYP_CD],
S.[COST_CNTR_CTGRY],
S.[HIERCHY_AREA],
S.[CMPNY_CD],
S.[PLNT_ID],
S.[PROFT_CNTR_ID],
S.[CRNCY_CD],
S.[ADRESS_LINE_1],
S.[ADRESS_LINE_2],
S.[ADRESS_LINE_3],
S.[CITY_NAME],
S.[DISTR_NAME],
S.[POSTAL_CD],
S.[CNTRY_CD],
S.[REGN_CD],
S.[PERSON_RESPNSBLE],
S.[FLG_ACTUAL_REVENUES],
S.[ETL_SRC_SYS_CD],
S.[ETL_EFFECTV_BEGIN_DATE],
S.[ETL_EFFECTV_END_DATE],
S.[ETL_CURR_RCD_IND],
S.[ETL_CREATED_TS],
S.[ETL_UPDTD_TS],
S.[ACTUAL_PRIMARY_POSTINGS_LOCK_IN],
S.[PLAN_PRIMARY_COSTS_LOCK_IND],
S.[BIZ_AREA],
S.[PLNG_REVENUES_LOCK_IND],
S.[PO_BOX],
S.[STR],
S.[USR_RESPNSBLE],
S.[COST_CNTR_NAME],
S.[COST_CNTR_SHORT_DESC],
S.[CONTROLLING_AREA_DESC],
S.[COST_CNTR_CTGRY_DESC],
S.[CMPNY_DESC],
S.[CRNCY_DESC],
S.[CNTRY_DESC],
S.[BIZ_AREA_DESC],
S.[ACTUAL_SECONDARY_COST_LOCK_IND],
S.[PLAN_SECONDARY_COST_LOCK_IND],
S.[FUNCTNL_AREA],
S.[FUNCTNL_AREA_DESC],
S.[TAX_JRSDCTN],
S.[FUNCTION_OF_COST_CNTR],
S.[PLNT_DESC],
S.[CREATED_ON],
S.[VALID_TO_DATE],
S.[VALID_FROM_DATE]


FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_COSCNTR_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_COSCNTR_CUR_D] T
        ON T.[COST_CNTR_KEY] = S.[COST_CNTR_KEY]
    WHERE T.[COST_CNTR_KEY] IS NULL;

END