CREATE     PROCEDURE [dbo].[Proc_EDW_T_D_MST_CUSTOMR_CUR_D]
AS
BEGIN  
    -- Update existing records
    UPDATE T SET
        T.[CUST_KEY] = S.[CUST_KEY],
        T.[Customer ID] = S.[CUST_ID],
        T.[Legacy Customer ID] = S.[LGCY_CUST_ID],
        T.[Customer Name] = S.[CUST_NAME],
        T.[Customer Line 2 Description] = S.[CUST_LINE_2_DESC],
        T.[Customer Country Code] = S.[CNTRY_CD],
        T.[Customer Plant ID] = S.[PLNT_ID],
        T.[Customer Segment ID] = S.[SEG_ID],
        T.[Customer Industry] = S.[INDUS],
        T.[Customer Vendor ID] = S.[VNDR_ID],
        T.[Customer Group Code] = S.[CUST_GROUP_CD],
        T.[Customer Account Group Code] = S.[CUST_ACCT_GROUP_CD],
        T.[Customer Title] = S.[TITLE],
        T.[Customer Search Term] = S.[SEARCH_TERM],
        T.[Customer Street] = S.[STR],
        T.[Customer City] = S.[CITY_NAME],
        T.[Customer Zip Code] = S.[ZIP_CD],
        T.[Customer State Code] = S.[ST_CD],
        T.[Customer Region Code] = S.[REGN_CD],
        T.[Customer Telephone Number 1] = S.[TEL_NUM_1_CD],
        T.[Customer Telephone Number 2] = S.[TEL_NUM_2_CD],
        T.[Customer Fax Number Code] = S.[FAX_NUM_CD],
        T.[Customer Tax Number 1 Code] = S.[TAX_NUM_1_CD],
        T.[Customer Tax Number 2 Code] = S.[TAX_NUM_2_CD],
        T.[Customer VAT Number Code] = S.[VAT_NUM_CD],
        T.[Customer Credit Limit] = S.[CREDIT_LMT],
        T.[Customer Bonus Rate] = S.[BONUS_RT],
        T.[Customer Express Station] = S.[EXPRESS_STATION],
        T.[Customer Transportation Zone] = S.[TRANSTN_ZONE],
        T.[Customer Printer Location Characteristics] = S.[PRINTER_LOC_CHARS],
        T.[Customer Printer Region Characteristics] = S.[PRINTER_REGN_CHARS],
        T.[Customer Printer Site Characteristics] = S.[PRINTER_SITE_CHARS],
        T.[Customer Created Date] = S.[CREATED_DATE],
        T.[Customer Created User ID] = S.[CREATED_USR_ID],
        T.[Customer Updated Date] = S.[UPDTD_DATE],
        T.[Customer Updated User ID] = S.[UPDTD_USR_ID],
        T.[Customer Payment Terms Code] = S.[PYMT_TRMS_CD],
        T.[Customer Sales Distribution] = S.[SALES_DISTR],
        T.[Customer Order Block For Sales Area] = S.[ORDER_BLK_FOR_SALES_AREA],
        T.[Customer Delivery Block For Sales Area] = S.[DLVRY_BLK_FOR_SALES_AREA],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE] = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE] = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND] = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Customer Corporate Group] = S.[CORPORATE_GROUP],
        T.[Customer Classification] = S.[CUST_CLSFTN],
        T.[Customer Classification Description] = S.[CUST_CLSFTN_DESC],
        T.[Customer Printer Location] = S.[PRINTER_LOC],
        T.[Customer Printer Site] = S.[PRINTER_SITE],
        T.[Customer Printer Region] = S.[PRINTER_REGN],
        T.[Customer Specific Field Label 01] = S.[CUST_SPECIFIC_FLD_LBL_01],
        T.[Customer Specific Field Label 02] = S.[CUST_SPECIFIC_FLD_LBL_02],
        T.[Customer Specific Field Label 03] = S.[CUST_SPECIFIC_FLD_LBL_03],
        T.[Customer Specific Field Label 04] = S.[CUST_SPECIFIC_FLD_LBL_04],
        T.[Customer Specific Field Label 05] = S.[CUST_SPECIFIC_FLD_LBL_05],
        T.[Customer Specific Field Label 06] = S.[CUST_SPECIFIC_FLD_LBL_06],
        T.[Customer Specific Field Label 07] = S.[CUST_SPECIFIC_FLD_LBL_07],
        T.[Customer Specific Field Label 08] = S.[CUST_SPECIFIC_FLD_LBL_08],
        T.[Customer Specific Field Label 09] = S.[CUST_SPECIFIC_FLD_LBL_09],
        T.[Customer Specific Field Label 10] = S.[CUST_SPECIFIC_FLD_LBL_10],
        T.[Customer Specific Field Label 11] = S.[CUST_SPECIFIC_FLD_LBL_11],
        T.[Customer Specific Field Label 12] = S.[CUST_SPECIFIC_FLD_LBL_12],
        T.[Customer Specific Field Label 13] = S.[CUST_SPECIFIC_FLD_LBL_13],
        T.[Customer Specific Field Label 14] = S.[CUST_SPECIFIC_FLD_LBL_14],
        T.[Customer Specific Field Label 15] = S.[CUST_SPECIFIC_FLD_LBL_15],
        T.[Customer Specific Field Label 16] = S.[CUST_SPECIFIC_FLD_LBL_16],
        T.[Customer Specific Field Label 17] = S.[CUST_SPECIFIC_FLD_LBL_17],
        T.[Customer Specific Field Label 18] = S.[CUST_SPECIFIC_FLD_LBL_18],
        T.[Customer Specific Field Label 19] = S.[CUST_SPECIFIC_FLD_LBL_19],
        T.[Customer Specific Field Label 20] = S.[CUST_SPECIFIC_FLD_LBL_20],
        T.[Customer Condition Group 1] = S.[CUST_COND_GROUP_1],
        T.[Customer Industry Code 1] = S.[INDUS_CD_1],
        T.[Customer Industry Code 2] = S.[INDUS_CD_2],
        T.[Customer Industry Description] = S.[INDUS_DESC],
        T.[Customer Industry Code 1 Description] = S.[INDUS_CD_1_DESC],
        T.[Customer Industry Code 2 Description] = S.[INDUS_CD_2_DESC],
        T.[Customer Assignment to Hierarchy] = S.[ASSIGN_TO_HIERCHY],
        T.[Customer Account Group Description] = S.[CUST_ACCT_GROUP_DESC],
        T.[Customer Region Description] = S.[REGN_DESC],
        T.[Customer Country Description] = S.[CNTRY_DESC],
        T.[Customer Transportation Zone Description] = S.[TRANSTN_ZONE_DESC],
        T.[Customer Plant Description] = S.[PLNT_DESC],
        T.[Customer Condition Group Description] = S.[CUST_COND_GROUP_DESC],
        T.[Customer Cental Billing Block] = S.[CENTRAL_BILLING_BLK],
        T.[Customer Cental Billing Block Description] = S.[CENTRAL_BILLING_BLK_DESC],
        T.[Customer Central Delivery Block] = S.[CENTRAL_DLVRY_BLK],
        T.[Customer Central Delivery Block Description] = S.[CENTRAL_DLVRY_BLK_DESC],
        T.[Customer Deletion Indicator] = S.[DELETION_IND],
        T.[Customer Central Posting Block] = S.[CENTRAL_PSTNG_BLK],
        T.[Customer Tax Jurisdiction] = S.[TAX_JRSDCTN],
        T.[Customer Central Sales Block] = S.[CENTRAL_SALES_BLK],
        T.[Customer Central Deletion Indicator] = S.[CENTRAL_DELETION_IND],
        T.[Customer Language Key] = S.[LANG_KEY],
        T.[Customer Trading Partner] = S.[TRADING_PRTNR],
        T.[Customer Trading Partner Description] = S.[TRADING_PRTNR_DESC],
        T.[Customer Annual Sales] = S.[ANNUAL_SALES],
        T.[Customer Annual Sales Year] = S.[ANNUAL_SALES_YR],
        T.[Customer Sales Currency] = S.[SALES_CRNCY],
        T.[Customer Sales Currency Description] = S.[SALES_CRNCY_DESC],
        T.[Customer One Time Account Group] = S.[ONE_TM_CUST_ACCT_GROUP],
        T.[Customer One Time Account Group Description] = S.[ONE_TM_CUST_ACCT_GROUP_DESC],
        T.[Customer One Time Indicator] = S.[ONE_TM_CUST_IND],
        T.[Customer Industry Type] = S.[INDUS_TYP],
        T.[Customer Business Type] = S.[BIZ_TYP],
        T.[Customer DUNS Number] = S.[DUNS_NUM],
        T.[Customer DUNS Plus 4] = S.[DUNS_PLUS_4],
        T.[Customer City Coordinates] = S.[CITY_COORDINATES],
        T.[Customer Tax Number 4 Code] = S.[TAX_NUM_4_CD],
        T.[Customer Attribute 3] = S.[ATTRIB_3],
        T.[Customer Attribute 3 Description] = S.[ATTRIB_3_DESC],
        T.[Customer E-Mail Address] = S.[E_MAIL_ADDR],
        T.[Customer Mobile Number] = S.[MOBILE_NUM],
        T.[Customer Search Term 2] = S.[SEARCH_TERM_2],
        T.[Customer Street 2] = S.[STR_2],
        T.[Customer Street 3] = S.[STR_3],
        T.[Customer Street 4] = S.[STR_4],
        T.[Customer Street 5] = S.[STR_5],
        T.[Customer PO Box] = S.[PO_BOX],
        T.[Customer PO Box Postal Code] = S.[PO_BOX_POSTAL_CD],
        T.[Customer PO Box City] = S.[PO_BOX_CITY],
        T.[Customer Region For PO Box] = S.[REGN_FOR_PO_BOX],
        T.[Customer PO Box Country] = S.[PO_BOX_CNTRY],
        T.[Customer Transport Zone] = S.[TRNSPRT_ZONE],
        T.[Customer Address Notes] = S.[ADDR_NOTES],
        T.[Customer Tax Number 3 Code] = S.[TAX_NUM_3],
        T.[Customer Tax Number 5 Code] = S.[TAX_NUM_5],
        T.[Customer Industry Code 3] = S.[INDUS_CD_3],
        T.[Customer Industry Code 3 Description] = S.[INDUS_CD_3_DESC],
        T.[Customer Industry Code 4] = S.[INDUS_CD_4],
        T.[Customer Industry Code 4 Description] = S.[INDUS_CD_4_DESC],
        T.[Customer Industry Code 5] = S.[INDUS_CD_5],
        T.[Customer Industry Code 5 Description] = S.[INDUS_CD_5_DESC],
        T.[Customer Central Order Block For Customer] = S.[CENTRAL_ORDER_BLK_FOR_CUST],
        T.[Customer Payment Block] = S.[PYMT_BLK]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CUSTOMR_CUR_D] S
        ON T.[CUST_KEY] = S.[CUST_KEY];
 
        -- Insert new records
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D] (
        [CUST_KEY],
        [Customer ID],
        [Legacy Customer ID],
        [Customer Name],
        [Customer Line 2 Description],
        [Customer Country Code],
        [Customer Plant ID],
        [Customer Segment ID],
        [Customer Industry],
        [Customer Vendor ID],
        [Customer Group Code],
        [Customer Account Group Code],
        [Customer Title],
        [Customer Search Term],
        [Customer Street],
        [Customer City],
        [Customer Zip Code],
        [Customer State Code],
        [Customer Region Code],
        [Customer Telephone Number 1],
        [Customer Telephone Number 2],
        [Customer Fax Number Code],
        [Customer Tax Number 1 Code],
        [Customer Tax Number 2 Code],
        [Customer VAT Number Code],
        [Customer Credit Limit],
        [Customer Bonus Rate],
        [Customer Express Station],
        [Customer Transportation Zone],
        [Customer Printer Location Characteristics],
        [Customer Printer Region Characteristics],
        [Customer Printer Site Characteristics],
        [Customer Created Date],
        [Customer Created User ID],
        [Customer Updated Date],
        [Customer Updated User ID],
        [Customer Payment Terms Code],
        [Customer Sales Distribution],
        [Customer Order Block For Sales Area],
        [Customer Delivery Block For Sales Area],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Customer Corporate Group],
        [Customer Classification],
        [Customer Classification Description],
        [Customer Printer Location],
        [Customer Printer Site],
        [Customer Printer Region],
        [Customer Specific Field Label 01],
        [Customer Specific Field Label 02],
        [Customer Specific Field Label 03],
        [Customer Specific Field Label 04],
        [Customer Specific Field Label 05],
        [Customer Specific Field Label 06],
        [Customer Specific Field Label 07],
        [Customer Specific Field Label 08],
        [Customer Specific Field Label 09],
        [Customer Specific Field Label 10],
        [Customer Specific Field Label 11],
        [Customer Specific Field Label 12],
        [Customer Specific Field Label 13],
        [Customer Specific Field Label 14],
        [Customer Specific Field Label 15],
        [Customer Specific Field Label 16],
        [Customer Specific Field Label 17],
        [Customer Specific Field Label 18],
        [Customer Specific Field Label 19],
        [Customer Specific Field Label 20],
        [Customer Condition Group 1],
        [Customer Industry Code 1],
        [Customer Industry Code 2],
        [Customer Industry Description],
        [Customer Industry Code 1 Description],
        [Customer Industry Code 2 Description],
        [Customer Assignment to Hierarchy],
        [Customer Account Group Description],
        [Customer Region Description],
        [Customer Country Description],
        [Customer Transportation Zone Description],
        [Customer Plant Description],
        [Customer Condition Group Description],
        [Customer Cental Billing Block],
        [Customer Cental Billing Block Description],
        [Customer Central Delivery Block],
        [Customer Central Delivery Block Description],
        [Customer Deletion Indicator],
        [Customer Central Posting Block],
        [Customer Tax Jurisdiction],
        [Customer Central Sales Block],
        [Customer Central Deletion Indicator],
        [Customer Language Key],
        [Customer Trading Partner],
        [Customer Trading Partner Description],
        [Customer Annual Sales],
        [Customer Annual Sales Year],
        [Customer Sales Currency],
        [Customer Sales Currency Description],
        [Customer One Time Account Group],
        [Customer One Time Account Group Description],
        [Customer One Time Indicator],
        [Customer Industry Type],
        [Customer Business Type],
        [Customer DUNS Number],
        [Customer DUNS Plus 4],
        [Customer City Coordinates],
        [Customer Tax Number 4 Code],
        [Customer Attribute 3],
        [Customer Attribute 3 Description],
        [Customer E-Mail Address],
        [Customer Mobile Number],
        [Customer Search Term 2],
        [Customer Street 2],
        [Customer Street 3],
        [Customer Street 4],
        [Customer Street 5],
        [Customer PO Box],
        [Customer PO Box Postal Code],
        [Customer PO Box City],
        [Customer Region For PO Box],
        [Customer PO Box Country],
        [Customer Transport Zone],
        [Customer Address Notes],
        [Customer Tax Number 3 Code],
        [Customer Tax Number 5 Code],
        [Customer Industry Code 3],
        [Customer Industry Code 3 Description],
        [Customer Industry Code 4],
        [Customer Industry Code 4 Description],
        [Customer Industry Code 5],
        [Customer Industry Code 5 Description],
        [Customer Central Order Block For Customer],
        [Customer Payment Block]
    )
    SELECT
        S.[CUST_KEY],
        S.[CUST_ID],
        S.[LGCY_CUST_ID],
        S.[CUST_NAME],
        S.[CUST_LINE_2_DESC],
        S.[CNTRY_CD],
        S.[PLNT_ID],
        S.[SEG_ID],
        S.[INDUS],
        S.[VNDR_ID],
        S.[CUST_GROUP_CD],
        S.[CUST_ACCT_GROUP_CD],
        S.[TITLE],
        S.[SEARCH_TERM],
        S.[STR],
        S.[CITY_NAME],
        S.[ZIP_CD],
        S.[ST_CD],
        S.[REGN_CD],
        S.[TEL_NUM_1_CD],
        S.[TEL_NUM_2_CD],
        S.[FAX_NUM_CD],
        S.[TAX_NUM_1_CD],
        S.[TAX_NUM_2_CD],
        S.[VAT_NUM_CD],
        S.[CREDIT_LMT],
        S.[BONUS_RT],
        S.[EXPRESS_STATION],
        S.[TRANSTN_ZONE],
        S.[PRINTER_LOC_CHARS],
        S.[PRINTER_REGN_CHARS],
        S.[PRINTER_SITE_CHARS],
        S.[CREATED_DATE],
        S.[CREATED_USR_ID],
        S.[UPDTD_DATE],
        S.[UPDTD_USR_ID],
        S.[PYMT_TRMS_CD],
        S.[SALES_DISTR],
        S.[ORDER_BLK_FOR_SALES_AREA],
        S.[DLVRY_BLK_FOR_SALES_AREA],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CORPORATE_GROUP],
        S.[CUST_CLSFTN],
        S.[CUST_CLSFTN_DESC],
        S.[PRINTER_LOC],
        S.[PRINTER_SITE],
        S.[PRINTER_REGN],
        S.[CUST_SPECIFIC_FLD_LBL_01],
        S.[CUST_SPECIFIC_FLD_LBL_02],
        S.[CUST_SPECIFIC_FLD_LBL_03],
        S.[CUST_SPECIFIC_FLD_LBL_04],
        S.[CUST_SPECIFIC_FLD_LBL_05],
        S.[CUST_SPECIFIC_FLD_LBL_06],
        S.[CUST_SPECIFIC_FLD_LBL_07],
        S.[CUST_SPECIFIC_FLD_LBL_08],
        S.[CUST_SPECIFIC_FLD_LBL_09],
        S.[CUST_SPECIFIC_FLD_LBL_10],
        S.[CUST_SPECIFIC_FLD_LBL_11],
        S.[CUST_SPECIFIC_FLD_LBL_12],
        S.[CUST_SPECIFIC_FLD_LBL_13],
        S.[CUST_SPECIFIC_FLD_LBL_14],
        S.[CUST_SPECIFIC_FLD_LBL_15],
        S.[CUST_SPECIFIC_FLD_LBL_16],
        S.[CUST_SPECIFIC_FLD_LBL_17],
        S.[CUST_SPECIFIC_FLD_LBL_18],
        S.[CUST_SPECIFIC_FLD_LBL_19],
        S.[CUST_SPECIFIC_FLD_LBL_20],
        S.[CUST_COND_GROUP_1],
        S.[INDUS_CD_1],
        S.[INDUS_CD_2],
        S.[INDUS_DESC],
        S.[INDUS_CD_1_DESC],
        S.[INDUS_CD_2_DESC],
        S.[ASSIGN_TO_HIERCHY],
        S.[CUST_ACCT_GROUP_DESC],
        S.[REGN_DESC],
        S.[CNTRY_DESC],
        S.[TRANSTN_ZONE_DESC],
        S.[PLNT_DESC],
        S.[CUST_COND_GROUP_DESC],
        S.[CENTRAL_BILLING_BLK],
        S.[CENTRAL_BILLING_BLK_DESC],
        S.[CENTRAL_DLVRY_BLK],
        S.[CENTRAL_DLVRY_BLK_DESC],
        S.[DELETION_IND],
        S.[CENTRAL_PSTNG_BLK],
        S.[TAX_JRSDCTN],
        S.[CENTRAL_SALES_BLK],
        S.[CENTRAL_DELETION_IND],
        S.[LANG_KEY],
        S.[TRADING_PRTNR],
        S.[TRADING_PRTNR_DESC],
        S.[ANNUAL_SALES],
        S.[ANNUAL_SALES_YR],
        S.[SALES_CRNCY],
        S.[SALES_CRNCY_DESC],
        S.[ONE_TM_CUST_ACCT_GROUP],
        S.[ONE_TM_CUST_ACCT_GROUP_DESC],
        S.[ONE_TM_CUST_IND],
        S.[INDUS_TYP],
        S.[BIZ_TYP],
        S.[DUNS_NUM],
        S.[DUNS_PLUS_4],
        S.[CITY_COORDINATES],
        S.[TAX_NUM_4_CD],
        S.[ATTRIB_3],
        S.[ATTRIB_3_DESC],
        S.[E_MAIL_ADDR],
        S.[MOBILE_NUM],
        S.[SEARCH_TERM_2],
        S.[STR_2],
        S.[STR_3],
        S.[STR_4],
        S.[STR_5],
        S.[PO_BOX],
        S.[PO_BOX_POSTAL_CD],
        S.[PO_BOX_CITY],
        S.[REGN_FOR_PO_BOX],
        S.[PO_BOX_CNTRY],
        S.[TRNSPRT_ZONE],
        S.[ADDR_NOTES],
        S.[TAX_NUM_3],
        S.[TAX_NUM_5],
        S.[INDUS_CD_3],
        S.[INDUS_CD_3_DESC],
        S.[INDUS_CD_4],
        S.[INDUS_CD_4_DESC],
        S.[INDUS_CD_5],
        S.[INDUS_CD_5_DESC],
        S.[CENTRAL_ORDER_BLK_FOR_CUST],
        S.[PYMT_BLK]
    
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CUSTOMR_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D] T
        ON T.[CUST_KEY] = S.[CUST_KEY]
    WHERE T.[CUST_KEY] IS NULL;
END