CREATE     PROCEDURE [dbo].[Proc_EDW_T_D_PRS_WBSELEM_CUR_D]
AS
BEGIN
    -- Update existing records
    UPDATE T
    SET
        T.[WBS Project Definition Internal]      = S.[PROJ_DEFINITION_INTERNL],
        T.[WBS Project Definition]               = S.[PROJ_DEFINITION],
        T.[WBS Project Object Number]            = S.[PROJ_OBJ_NUM],
        T.[WBS Element Internal]                 = S.[WBS_ELEMNT_INTERNL],
        T.[WBS Element]                          = S.[WBS_ELEMNT],
        T.[WBS Element Object Number]            = S.[WBS_ELEMNT_OBJ_NUM],
        T.[WBS Element Description]              = S.[WBS_ELEMNT_DESC],
        T.[WBS Project Type]                     = S.[WBS_PROJ_TYP],
        T.[WBS Project Priority]                 = S.[WBS_PROJ_PRIORITY],
        T.[WBS Project Short Description]        = S.[WBS_PROJ_SHORT_DESC],
        T.[WBS Project Personnel Responsible]    = S.[WBS_PROJ_PERSONEL_RESPNSBLE],
        T.[WBS Project Short ID]                 = S.[WBS_PROJ_SHORT_ID],
        T.[WBS Application Number]               = S.[WBS_APPL_NUM],
        T.[WBS Responsible Cost Center]          = S.[WBS_RESPNSBLE_COST_CNTR],
        T.[WBS Request Cost Center]              = S.[WBS_REQUEST_COST_CNTR],
        T.[WBS Request Company Code]             = S.[WBS_REQUEST_CMPNY_CD],
        T.[WBS Basic Start Date]                 = S.[WBS_BASIC_START_DATE],
        T.[WBS Basic Finish Date]                = S.[WBS_BASIC_FINISH_DATE],
        T.[WBS Forecast Start Date]              = S.[WBS_FORECAST_START_DATE],
        T.[WBS Forecast Finish Date]             = S.[WBS_FORECAST_FINISH_DATE],
        T.[WBS Actual Start Date]                = S.[WBS_ACTUAL_START_DATE],
        T.[WBS Actual Finish Date]               = S.[WBS_ACTUAL_FINISH_DATE],
        T.[WBS Basic Duration]                   = S.[WBS_BASIC_DUR],
        T.[WBS Basic UOM]                        = S.[WBS_BASIC_UOM],
        T.[WBS Forecast Duration]                = S.[WBS_FORECAST_DUR],
        T.[WBS Forecast UOM]                     = S.[WBS_FORECAST_UOM],
        T.[WBS Actual Duration]                  = S.[WBS_ACTUAL_DUR],
        T.[WBS Actual UOM]                       = S.[WBS_ACTUAL_UOM],
        T.[WBS Basic Earlist Start Date]         = S.[WBS_BASIC_EARLIST_START_DATE],
        T.[WBS Basic Earlist Finish Date]        = S.[WBS_BASIC_EARLIST_FINISH_DATE],
        T.[WBS Basic Latest Start Date]          = S.[WBS_BASIC_LATEST_START_DATE],
        T.[WBS Basic Latest Finish Date]         = S.[WBS_BASIC_LATEST_FINISH_DATE],
        T.[WBS Forecast Earliest Start Date]     = S.[WBS_FORECAST_EARLIST_START_DATE],
        T.[WBS Forecast Earliest Finish Date]    = S.[WBS_FORECAST_EARLIST_FINISH_DAT],
        T.[WBS Forecast Latest Start Date]       = S.[WBS_FORECAST_LATEST_START_DATE],
        T.[WBS Forecast Latest Finish Date]      = S.[WBS_FORECAST_LATEST_FINISH_DATE],
        T.[WBS Tentative Actual Start Date]      = S.[WBS_TENTATIVE_ACTUAL_START_DATE],
        T.[WBS Tentative Actual Finish Date]     = S.[WBS_TENTATIVE_ACTUAL_FINISH_DAT],
        T.[WBS Calendar]                         = S.[WBS_CLNDR],
        T.[WBS Controlling Area]                 = S.[WBS_CONTROLLING_AREA],
        T.[WBS Company Code]                     = S.[WBS_CMPNY_CD],
        T.[WBS Business Area]                    = S.[WBS_BIZ_AREA],
        T.[WBS Functional Area]                  = S.[WBS_FUNCTNL_AREA],
        T.[WBS Profit Center]                    = S.[WBS_PROFT_CNTR],
        T.[WBS Object Class]                     = S.[WBS_OBJ_CLASS],
        T.[WBS Currency]                         = S.[WBS_CRNCY],
        T.[WBS Tax Jurisdiction]                 = S.[WBS_TAX_JRSDCTN],
        T.[WBS Sub Project]                      = S.[WBS_SUB_PROJ],
        T.[WBS Plant]                            = S.[WBS_PLNT],
        T.[WBS Location]                         = S.[WBS_LOC],
        T.[WBS Equipment]                        = S.[WBS_EQUIP],
        T.[WBS Functional Location]              = S.[WBS_FUNCTNL_LOC],
        T.[WBS Change Number]                    = S.[WBS_CHG_NUM],
        T.[WBS Reference Element]                = S.[WBS_REF_ELEMNT],
        T.[WBS Element Created By]               = S.[CREATED_BY],
        T.[WBS Created On]                       = S.[CREATED_ON],
        T.[WBS Changed By]                       = S.[CHANGED_BY],
        T.[WBS Changed On]                       = S.[CHANGED_ON],
        T.[WBS Level in Project Hierarchy]       = S.[WBS_LVL_IN_PROJ_HIERCHY],
        T.[ETL_SRC_SYS_CD]                       = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE]               = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE]                 = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND]                     = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS]                       = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS]                         = S.[ETL_UPDTD_TS],
        T.[WBS Responsible Person Name]          = S.[WBS_RESPNSBLE_PERSON_NAME],
        T.[WBS Appropriate Project Number]       = S.[WBS_APPROPRIATE_PROJ_NUM],
        T.[WBS Language Key]                     = S.[WBS_LANG_KEY],
        T.[WBS Project Type Description]         = S.[WBS_PROJ_TYP_DESC],
        T.[WBS Project Priority Description]     = S.[WBS_PROJ_PRIORITY_DESC],
        T.[WBS Factory Calendar Description]     = S.[WBS_FACTORY_CLNDR_DESC],
        T.[WBS Controlling Area Description]     = S.[WBS_CONTROLLING_AREA_DESC],
        T.[WBS Company Description]              = S.[WBS_CMPNY_DESC],
        T.[WBS Business Area Description]        = S.[WBS_BIZ_AREA_DESC],
        T.[WBS Object Class Description]         = S.[WBS_OBJ_CLASS_DESC],
        T.[WBS Currency Description]             = S.[WBS_CRNCY_DESC],
        T.[WBS Plant Description]                = S.[WBS_PLNT_DESC],
        T.[WBS POC Weight]                       = S.[WBS_POC_WGHT],
        T.[WBS Progress Version]                 = S.[WBS_PROGRESS_VRSN],
        T.[WBS Plan Measurement Method]          = S.[WBS_PLAN_MSRMNT_MTHD],
        T.[WBS Plan Reference Object]            = S.[WBS_PLAN_REF_OBJ],
        T.[WBS Actual Measurement Method]        = S.[WBS_ACTUAL_MSRMNT_MTHD],
        T.[WBS Actual Reference Object]          = S.[WBS_ACTUAL_REF_OBJ],
        T.[WBS System Status]                    = S.[WBS_SYS_STATUS],
        T.[WBS User Status]                      = S.[WBS_USR_STATUS],
        T.[WBS Project Description]              = S.[PROJ_DESC],
        T.[WBS Project Responsible Person Number]= S.[PROJ_RESPNSBLE_PERSON_NUM],
        T.[WBS Project Responsible Person Name]  = S.[PROJ_RESPNSBLE_PERSON_NAME],
        T.[WBS Project Company Code]             = S.[PROJ_CMPNY_CD],
        T.[WBS Project Company Description]      = S.[PROJ_CMPNY_DESC],
        T.[WBS Project Profit Center]            = S.[PROJ_PROFT_CNTR],
        T.[WBS Project Plant ID]                 = S.[PROJ_PLNT_ID],
        T.[WBS Project Plant Description]        = S.[PROJ_PLNT_DESC],
        T.[WBS Project Functional Area]          = S.[PROJ_FUNCTNL_AREA],
        T.[WBS Project Customer Number]          = S.[PROJ_CUST_NUM],
        T.[WBS Project Customer Name]            = S.[PROJ_CUST_NAME],
        T.[WBS Project Controlling Area]         = S.[PROJ_CONTROLLING_AREA],
        T.[WBS Project Controlling Area Description] = S.[PROJ_CONTROLLING_AREA_DESC],
        T.[WBS Project Location]                 = S.[PROJ_LOC],
        T.[WBS Project Currency]                 = S.[PROJ_CRNCY],
        T.[WBS Project Business Area]            = S.[PROJ_BIZ_AREA],
        T.[WBS Project Business Area Description]= S.[PROJ_BIZ_AREA_DESC],
        T.[WBS Project Factory Calendar]         = S.[PROJ_FACTORY_CLNDR],
        T.[WBS Project Factory Calendar Description] = S.[PROJ_FACTORY_CLNDR_DESC],
        T.[WBS Project Time Unit]                = S.[PROJ_TM_UNIT],
        T.[WBS Project Forecast Start Date]      = S.[PROJ_FORECAST_START_DATE],
        T.[WBS Project Forecast Finish Date]     = S.[PROJ_FORECAST_FINISH_DATE],
        T.[WBS Project Created By]               = S.[PROJ_CREATED_BY],
        T.[WBS Project Created Date]             = S.[PROJ_CREATED_DATE],
        T.[WBS Project Changed By]               = S.[PROJ_CHANGED_BY],
        T.[WBS Project Changed On]               = S.[PROJ_CHANGED_ON],
        T.[WBS Project System Status]            = S.[PROJ_SYS_STATUS],
        T.[WBS Project User Status]              = S.[PROJ_USR_STATUS],
        T.[WBS Project Start Date]               = S.[PROJ_START_DATE],
        T.[WBS Project Finish Date]              = S.[PROJ_FINISH_DATE],
        T.[WBS Project Last Basic Scheduling Date]= S.[PROJ_LAST_BASIC_SCHLG_DATE],
        T.[WBS Last Forecast Scheduling Date]    = S.[PROJ_LAST_FORECAST_SCHLG_DATE]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_PRS_WBSELEM_CUR_D] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_PRS_WBSELEM_CUR_D] S
        ON T.[WBS_ELEMNT_KEY] = S.[WBS_ELEMNT_KEY];

    -- Insert new records
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_PRS_WBSELEM_CUR_D]
    (
	[WBS_ELEMNT_KEY],
    [WBS Project Definition Internal],
    [WBS Project Definition],
    [WBS Project Object Number],
    [WBS Element Internal],
    [WBS Element],
    [WBS Element Object Number],
    [WBS Element Description],
    [WBS Project Type],
    [WBS Project Priority],
    [WBS Project Short Description],
    [WBS Project Personnel Responsible],
    [WBS Project Short ID],
    [WBS Application Number],
    [WBS Responsible Cost Center],
    [WBS Request Cost Center],
    [WBS Request Company Code],
    [WBS Basic Start Date],
    [WBS Basic Finish Date],
    [WBS Forecast Start Date],
    [WBS Forecast Finish Date],
    [WBS Actual Start Date],
    [WBS Actual Finish Date],
    [WBS Basic Duration],
    [WBS Basic UOM],
    [WBS Forecast Duration],
    [WBS Forecast UOM],
    [WBS Actual Duration],
    [WBS Actual UOM],
    [WBS Basic Earlist Start Date],
    [WBS Basic Earlist Finish Date],
    [WBS Basic Latest Start Date],
    [WBS Basic Latest Finish Date],
    [WBS Forecast Earliest Start Date],
    [WBS Forecast Earliest Finish Date],
    [WBS Forecast Latest Start Date],
    [WBS Forecast Latest Finish Date],
    [WBS Tentative Actual Start Date],
    [WBS Tentative Actual Finish Date],
    [WBS Calendar],
    [WBS Controlling Area],
    [WBS Company Code],
    [WBS Business Area],
    [WBS Functional Area],
    [WBS Profit Center],
    [WBS Object Class],
    [WBS Currency],
    [WBS Tax Jurisdiction],
    [WBS Sub Project],
    [WBS Plant],
    [WBS Location],
    [WBS Equipment],
    [WBS Functional Location],
    [WBS Change Number],
    [WBS Reference Element],
    [WBS Element Created By],
    [WBS Created On],
    [WBS Changed By],
    [WBS Changed On],
    [WBS Level in Project Hierarchy],
    [ETL_SRC_SYS_CD],
    [ETL_EFFECTV_BEGIN_DATE],
    [ETL_EFFECTV_END_DATE],
    [ETL_CURR_RCD_IND],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [WBS Responsible Person Name],
    [WBS Appropriate Project Number],
    [WBS Language Key],
    [WBS Project Type Description],
    [WBS Project Priority Description],
    [WBS Factory Calendar Description],
    [WBS Controlling Area Description],
    [WBS Company Description],
    [WBS Business Area Description],
    [WBS Object Class Description],
    [WBS Currency Description],
    [WBS Plant Description],
    [WBS POC Weight],
    [WBS Progress Version],
    [WBS Plan Measurement Method],
    [WBS Plan Reference Object],
    [WBS Actual Measurement Method],
    [WBS Actual Reference Object],
    [WBS System Status],
    [WBS User Status],
    [WBS Project Description],
    [WBS Project Responsible Person Number],
    [WBS Project Responsible Person Name],
    [WBS Project Company Code],
    [WBS Project Company Description],
    [WBS Project Profit Center],
    [WBS Project Plant ID],
    [WBS Project Plant Description],
    [WBS Project Functional Area],
    [WBS Project Customer Number],
    [WBS Project Customer Name],
    [WBS Project Controlling Area],
    [WBS Project Controlling Area Description],
    [WBS Project Location],
    [WBS Project Currency],
    [WBS Project Business Area],
    [WBS Project Business Area Description],
    [WBS Project Factory Calendar],
    [WBS Project Factory Calendar Description],
    [WBS Project Time Unit],
    [WBS Project Forecast Start Date],
    [WBS Project Forecast Finish Date],
    [WBS Project Created By],
    [WBS Project Created Date],
    [WBS Project Changed By],
    [WBS Project Changed On],
    [WBS Project System Status],
    [WBS Project User Status],
    [WBS Project Start Date],
    [WBS Project Finish Date],
    [WBS Project Last Basic Scheduling Date],
    [WBS Last Forecast Scheduling Date]
    )
    SELECT
        S.[WBS_ELEMNT_KEY],
        S.[PROJ_DEFINITION_INTERNL],
        S.[PROJ_DEFINITION],
        S.[PROJ_OBJ_NUM],
        S.[WBS_ELEMNT_INTERNL],
        S.[WBS_ELEMNT],
        S.[WBS_ELEMNT_OBJ_NUM],
        S.[WBS_ELEMNT_DESC],
        S.[WBS_PROJ_TYP],
        S.[WBS_PROJ_PRIORITY],
        S.[WBS_PROJ_SHORT_DESC],
        S.[WBS_PROJ_PERSONEL_RESPNSBLE],
        S.[WBS_PROJ_SHORT_ID],
        S.[WBS_APPL_NUM],
        S.[WBS_RESPNSBLE_COST_CNTR],
        S.[WBS_REQUEST_COST_CNTR],
        S.[WBS_REQUEST_CMPNY_CD],
        S.[WBS_BASIC_START_DATE],
        S.[WBS_BASIC_FINISH_DATE],
        S.[WBS_FORECAST_START_DATE],
        S.[WBS_FORECAST_FINISH_DATE],
        S.[WBS_ACTUAL_START_DATE],
        S.[WBS_ACTUAL_FINISH_DATE],
        S.[WBS_BASIC_DUR],
        S.[WBS_BASIC_UOM],
        S.[WBS_FORECAST_DUR],
        S.[WBS_FORECAST_UOM],
        S.[WBS_ACTUAL_DUR],
        S.[WBS_ACTUAL_UOM],
        S.[WBS_BASIC_EARLIST_START_DATE],
        S.[WBS_BASIC_EARLIST_FINISH_DATE],
        S.[WBS_BASIC_LATEST_START_DATE],
        S.[WBS_BASIC_LATEST_FINISH_DATE],
        S.[WBS_FORECAST_EARLIST_START_DATE],
        S.[WBS_FORECAST_EARLIST_FINISH_DAT],
        S.[WBS_FORECAST_LATEST_START_DATE],
        S.[WBS_FORECAST_LATEST_FINISH_DATE],
        S.[WBS_TENTATIVE_ACTUAL_START_DATE],
        S.[WBS_TENTATIVE_ACTUAL_FINISH_DAT],
        S.[WBS_CLNDR],
        S.[WBS_CONTROLLING_AREA],
        S.[WBS_CMPNY_CD],
        S.[WBS_BIZ_AREA],
        S.[WBS_FUNCTNL_AREA],
        S.[WBS_PROFT_CNTR],
        S.[WBS_OBJ_CLASS],
        S.[WBS_CRNCY],
        S.[WBS_TAX_JRSDCTN],
        S.[WBS_SUB_PROJ],
        S.[WBS_PLNT],
        S.[WBS_LOC],
        S.[WBS_EQUIP],
        S.[WBS_FUNCTNL_LOC],
        S.[WBS_CHG_NUM],
        S.[WBS_REF_ELEMNT],
        S.[CREATED_BY],
        S.[CREATED_ON],
        S.[CHANGED_BY],
        S.[CHANGED_ON],
        S.[WBS_LVL_IN_PROJ_HIERCHY],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[WBS_RESPNSBLE_PERSON_NAME],
        S.[WBS_APPROPRIATE_PROJ_NUM],
        S.[WBS_LANG_KEY],
        S.[WBS_PROJ_TYP_DESC],
        S.[WBS_PROJ_PRIORITY_DESC],
        S.[WBS_FACTORY_CLNDR_DESC],
        S.[WBS_CONTROLLING_AREA_DESC],
        S.[WBS_CMPNY_DESC],
        S.[WBS_BIZ_AREA_DESC],
        S.[WBS_OBJ_CLASS_DESC],
        S.[WBS_CRNCY_DESC],
        S.[WBS_PLNT_DESC],
        S.[WBS_POC_WGHT],
        S.[WBS_PROGRESS_VRSN],
        S.[WBS_PLAN_MSRMNT_MTHD],
        S.[WBS_PLAN_REF_OBJ],
        S.[WBS_ACTUAL_MSRMNT_MTHD],
        S.[WBS_ACTUAL_REF_OBJ],
        S.[WBS_SYS_STATUS],
        S.[WBS_USR_STATUS],
        S.[PROJ_DESC],
        S.[PROJ_RESPNSBLE_PERSON_NUM],
        S.[PROJ_RESPNSBLE_PERSON_NAME],
        S.[PROJ_CMPNY_CD],
        S.[PROJ_CMPNY_DESC],
        S.[PROJ_PROFT_CNTR],
        S.[PROJ_PLNT_ID],
        S.[PROJ_PLNT_DESC],
        S.[PROJ_FUNCTNL_AREA],
        S.[PROJ_CUST_NUM],
        S.[PROJ_CUST_NAME],
        S.[PROJ_CONTROLLING_AREA],
        S.[PROJ_CONTROLLING_AREA_DESC],
        S.[PROJ_LOC],
        S.[PROJ_CRNCY],
        S.[PROJ_BIZ_AREA],
        S.[PROJ_BIZ_AREA_DESC],
        S.[PROJ_FACTORY_CLNDR],
        S.[PROJ_FACTORY_CLNDR_DESC],
        S.[PROJ_TM_UNIT],
        S.[PROJ_FORECAST_START_DATE],
        S.[PROJ_FORECAST_FINISH_DATE],
        S.[PROJ_CREATED_BY],
        S.[PROJ_CREATED_DATE],
        S.[PROJ_CHANGED_BY],
        S.[PROJ_CHANGED_ON],
        S.[PROJ_SYS_STATUS],
        S.[PROJ_USR_STATUS],
        S.[PROJ_START_DATE],
        S.[PROJ_FINISH_DATE],
        S.[PROJ_LAST_BASIC_SCHLG_DATE],
        S.[PROJ_LAST_FORECAST_SCHLG_DATE]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_PRS_WBSELEM_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_PRS_WBSELEM_CUR_D] T
        ON T.[WBS_ELEMNT_KEY] = S.[WBS_ELEMNT_KEY]
    WHERE T.[WBS_ELEMNT_KEY] IS NULL;
END