CREATE   PROCEDURE [dbo].[Proc_REQUIREMENT_DATE]
AS
BEGIN  
    -- Update existing records
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Requirement Date] = S.[THE_DATE],
        T.[Requirement Fiscal Year] = S.[FISCAL_YR],
        T.[Requirement Fiscal Period Number] = S.[FISCAL_PER_NUM],
        T.[Requirement Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Requirement Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Requirement Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Requirement Calendar Year] = S.[CLNDR_YR],
        T.[Requirement Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Requirement Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Requirement Calendar Month Description] = S.[CLNDR_MNTH_DESC],
        T.[Requirement Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[Requirement Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Requirement Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Requirement Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Requirement Calendar Day In Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Requirement Calendar Day In Year] = S.[CLNDR_DAY_IN_YR],
        T.[Requirement Calendar Week] = S.[CLNDR_WK],
        T.[Requirement Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Requirement Calendar Days In Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Requirement Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Requirement Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Requirement Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Requirement Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Requirement Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Requirement Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Requirement Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Requirement Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Requirement Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Requirement Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Requirement Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Requirement Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Requirement Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Requirement Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Requirement Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Requirement Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Requirement Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Requirement Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Requirement Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Requirement Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Requirement Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Requirement Fiscal Week] = S.[FISCAL_WK],
        T.[Requirement Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Requirement Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Requirement Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Requirement Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Requirement Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Requirement Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Requirement Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Requirement Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Requirement Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Requirement Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[REQUIREMENT_DATE] AS T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] AS S
        ON T.[DATE_KEY] = S.[DATE_KEY];

    -- =============================
    -- Step 2: Insert new records
    -- =============================
    INSERT INTO [GLOBAL_EDW].[Propelis].[REQUIREMENT_DATE] (
        [DATE_KEY],
        [Requirement Date],
        [Requirement Fiscal Year],
        [Requirement Fiscal Period Number],
        [Requirement Fiscal Period Code],
        [Requirement Fiscal Quarter Number],
        [Requirement Fiscal Quarter Code],
        [Requirement Calendar Year],
        [Requirement Calendar Month Number],
        [Requirement Calendar Month Code],
        [Requirement Calendar Month Description],
        [Requirement Calendar Quarter Number],
        [Requirement Calendar Quarter Code],
        [Requirement Calendar Weekday Number],
        [Requirement Calendar Weekday Name],
        [Requirement Calendar Day In Month],
        [Requirement Calendar Day In Year],
        [Requirement Calendar Week],
        [Requirement Calendar Month In Quarter Number],
        [Requirement Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Requirement Current Day Flag],
        [Requirement Current Day Minus 1 Flag],
        [Requirement Current Calendar Week Flag],
        [Requirement Current Calendar Week Minus 1 Flag],
        [Requirement Current Month Flag],
        [Requirement Current Month Minus 1 Flag],
        [Requirement Current Month Minus 2 Flag],
        [Requirement Current Month Minus 12 Flag],
        [Requirement Current Quarter Flag],
        [Requirement Current Quarter Minus 1 Flag],
        [Requirement Current Quarter Minus 4 Flag],
        [Requirement Current Calendar Year Flag],
        [Requirement Current Calendar Year Minus 1 Flag],
        [Requirement Current Calendar Year Minus 2 Flag],
        [Requirement Current Calendar Year Plus 1 Flag],
        [Requirement Current Fiscal Year Flag],
        [Requirement Current Fiscal Year Minus 1 Flag],
        [Requirement Current Fiscal Year Minus 2 Flag],
        [Requirement Current Fiscal Year Plus 1 Flag],
        [Requirement Day In Fiscal Year],
        [Requirement Date Is Weekday],
        [Requirement Fiscal Week],
        [Requirement Fiscal Weekday Number],
        [Requirement Fiscal Weekday Name],
        [Requirement Current Fiscal Week Flag],
        [Requirement Current Fiscal Week Minus 1 Flag],
        [Requirement Current Fiscal Week Minus 2 Flag],
        [Requirement Current Fiscal Week Minus 3 Flag],
        [Requirement Current Fiscal Week Minus 4 Flag],
        [Requirement Current Fiscal Week Minus 5 Flag],
        [Requirement Current Fiscal Week Minus 6 Flag],
        [Requirement Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[REQUIREMENT_DATE] AS T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
END;