CREATE     PROCEDURE [dbo].[Proc_EDW_T_D_MST_MATERIAL_CUR_D]
AS
BEGIN
    -- =============================
    -- UPDATE existing records
    -- =============================
    UPDATE T
    SET
        T.[Material ID]                               = S.[MATRL_ID],
        T.[Material Description]                      = S.[MATRL_DESC],
        T.[Legacy Material ID]                        = S.[LGCY_MATRL_ID],
        T.[Material Customer ID]                      = S.[CUST_ID],
        T.[Material Category]                         = S.[MATRL_CTGRY],
        T.[Material Type]                             = S.[MATRL_TYP],
        T.[Material Group]                            = S.[MATRL_GROUP],
        T.[Material Base Unit Of Measure]             = S.[BASE_UNIT_OF_MEASUR],
        T.[Material Industry Sector]                  = S.[INDUS_SECTOR],
        T.[Material General Item Category Group]      = S.[GENERAL_ITM_CTGRY_GROUP],
        T.[Material Unit]                             = S.[UNIT],
        T.[Material Gross Weight]                     = S.[GROSS_WGHT],
        T.[Material Net Weight]                       = S.[NET_WGHT],
        T.[Material Product Hierarchy]                = S.[PRDT_HIERCHY],
        T.[Category of Material]                      = S.[CTGRY],
        T.[Material Brand]                            = S.[BRAND],
        T.[Material Sub Brand]                        = S.[SUB_BRAND],
        T.[Material Variant Obsolete]                 = S.[VARIANT_OBSOLET],
        T.[Material Variant]                          = S.[VARIANT],
        T.[Material Name 1]                           = S.[NAME_1],
        T.[Material Pack Size]                        = S.[PACK_SIZE],
        T.[Material Pack Type]                        = S.[PACK_TYP],
        T.[Material Country Name]                     = S.[CNTRY_NAME],
        T.[Material Print Method]                     = S.[PRNT_MTHD],
        T.[Material Level 4 Product Category Code]    = S.[LEVEL4_PRDT_CTGRY_CD],
        T.[Material Level 4 Product Category Description] = S.[LEVEL4_PRDT_CTGRY_DESC],
        T.[Material Level 3 Sub Family Code]          = S.[LEVEL3_SUB_FAMILY_CD],
        T.[Material Level 3 Sub Family Description]   = S.[LEVEL3_SUB_FAMILY_DESC],
        T.[Material Level 2 Family Code]              = S.[LEVEL2_FAMILY_CD],
        T.[Material Level 2 Family Description]       = S.[LEVEL2_FAMILY_DESC],
        T.[Material Level 1 Class Code]               = S.[LEVEL1_CLASS_CD],
        T.[Material Level 1 Class Description]        = S.[LEVEL1_CLASS_DESC],
        T.[Material Created Date]                     = S.[CREATED_DATE],
        T.[Material Created User ID]                  = S.[CREATED_USR_ID],
        T.[Material Updated Date]                     = S.[UPDTD_DATE],
        T.[Material Updated User ID]                  = S.[UPDTD_USR_ID],
        T.[ETL_SRC_SYS_CD]                            = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE]                    = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE]                      = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND]                          = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS]                            = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS]                              = S.[ETL_UPDTD_TS],
        T.[Material Group Description]                = S.[MATRL_GROUP_DESC],
        T.[Material Group Description 2]              = S.[MATRL_GROUP_DESC_2],
        T.[Category of Material Description]          = S.[CTGRY_DESC],
        T.[Material Brand Description]                = S.[BRAND_DESC],
        T.[Material Sub Brand Description]            = S.[SUB_BRAND_DESC],
        T.[Material Print Method Description]         = S.[PRNT_MTHD_DESC],
        T.[Material Level 5 Product Category Code]    = S.[LEVEL5_PRDT_CTGRY_CD],
        T.[Material Level 5 Product Category Description] = S.[LEVEL5_PRDT_CTGRY_DESC],
        T.[Material Level 6 Product Category Code]    = S.[LEVEL6_PRDT_CTGRY_CD],
        T.[Material Level 6 Product Category Description] = S.[LEVEL6_PRDT_CTGRY_DESC],
        T.[Material Category Description]             = S.[MATRL_CTGRY_DESC],
        T.[Material Type Description]                 = S.[MATRL_TYP_DESC],
        T.[Material Product Hierarchy Description]    = S.[PRDT_HIERCHY_DESC],
        T.[Material Industry Sector Description]      = S.[INDUS_SECTOR_DESC],
        T.[Material General Item Category Group Description] = S.[GEN_ITM_CTGRY_GRP_DESC],
        T.[Material Client Level Deletion Indicator]  = S.[CLNT_LVL_DELETION_IND],
        T.[Material PO UoM]                           = S.[PO_UOM],
        T.[Material Basic]                            = S.[BASIC_MATRL],
        T.[Material Industry Standard Description]    = S.[INDUS_STD_DESC],
        T.[Material Laboratory/Design Office]         = S.[LABORATORY_DESIGN_OFFC],
        T.[Material Laboratory/Design Office Description] = S.[LABORATORY_DESIGN_OFFC_DESC],
        T.[Material Purchasing Value Key]             = S.[PURNG_VAL_KEY],
        T.[Material Storage Condition]                = S.[STOR_COND],
        T.[Material Storage Condition Description]    = S.[STOR_COND_DESC],
        T.[Material Temperature Conditions Indicator] = S.[TEMPERATURE_CONDITIONS_IND],
        T.[Material Temperature Conditions Indicator Description] = S.[TEMPERATURE_CONDITIONS_IND_DESC],
        T.[Material Transportation Group]             = S.[TRANSTN_GROUP],
        T.[Material Transportation Group Description] = S.[TRANSTN_GROUP_DESC],
        T.[Material Hazardous Number]                 = S.[HAZARDOUS_MATRL_NUM],
        T.[Material Source of Supply]                 = S.[SRC_OF_SUPLY],
        T.[Material Source of Supply Description]     = S.[SRC_OF_SUPLY_DESC],
        T.[Material EAN/UPC Number]                   = S.[EAN_UPC_NO],
        T.[Material EAN Category]                     = S.[EAN_CTGRY],
        T.[Material EAN Category Description]         = S.[EAN_CTGRY_DESC],
        T.[Material Length]                           = S.[LNGTH],
        T.[Material Width]                            = S.[WIDTH],
        T.[Material Height]                           = S.[HGHT],
        T.[Material UoD]                              = S.[UOD],
        T.[Material External Group]                   = S.[EXTNL_MATRL_GROUP],
        T.[Material External Group Description]       = S.[EXTNL_MATRL_GROUP_DESC],
        T.[Material Manufacturer Part Number]         = S.[MANUFACTURER_PART_NUM],
        T.[Material Dangerous Goods Indicator Profile] = S.[DANGEROUS_GOODS_IND_PROFILE],
        T.[Material Dangerous Goods Indicator Profile Desription] = S.[DANGEROUS_GOODS_IND_PROFILE_DES],
        T.[Material Country of Origin]                = S.[CNTRY_OF_ORIGIN],
        T.[Material Country of Origin Description]    = S.[CNTRY_OF_ORIGION_DESC],
        T.[Material Quality Inspection Group]         = S.[QUAL_INSPTN_GROUP],
        T.[Material Quality Inspection Group Description] = S.[QUAL_INSPTN_GROUP_DESC],
        T.[MATRL_SALES_TEXT]                          = S.[MATRL_SALES_TEXT],
        T.[Class Internl Num]                         = S.[CLASS_INTERNL_NUM],
        T.[Class Name]                                = S.[CLASS_NAME],
        T.[Class Typ]                                 = S.[CLASS_TYP],
        T.[Class Typ Desc]                            = S.[CLASS_TYP_DESC],
        T.[Class Status]                              = S.[CLASS_STATUS],
        T.[Class Status Desc]                         = S.[CLASS_STATUS_DESC],
        T.[Characteristic 1 Internl Num]              = S.[CHARACTERISTIC_1_INTERNL_NUM],
        T.[Characteristic 1 Name]                     = S.[CHARACTERISTIC_1_NAME],
        T.[Characteristic 1 Desc]                     = S.[CHARACTERISTIC_1_DESC],
        T.[Characteristic 1 Val]                      = S.[CHARACTERISTIC_1_VAL],
        T.[Characteristic 1 Val Desc]                 = S.[CHARACTERISTIC_1_VAL_DESC],
        T.[Characteristic 2 Internl Num]              = S.[CHARACTERISTIC_2_INTERNL_NUM],
        T.[Characteristic 2 Name]                     = S.[CHARACTERISTIC_2_NAME],
        T.[Characteristic 2 Desc]                     = S.[CHARACTERISTIC_2_DESC],
        T.[Characteristic 2 Val]                      = S.[CHARACTERISTIC_2_VAL],
        T.[Characteristic 2 Val Desc]                 = S.[CHARACTERISTIC_2_VAL_DESC],
        T.[Characteristic 3 Internl Num]              = S.[CHARACTERISTIC_3_INTERNL_NUM],
        T.[Characteristic 3 Name]                     = S.[CHARACTERISTIC_3_NAME],
        T.[Characteristic 3 Desc]                     = S.[CHARACTERISTIC_3_DESC],
        T.[Characteristic 3 Val]                      = S.[CHARACTERISTIC_3_VAL],
        T.[Characteristic 3 Val Desc]                 = S.[CHARACTERISTIC_3_VAL_DESC],
        T.[Characteristic 4 Internl Num]              = S.[CHARACTERISTIC_4_INTERNL_NUM],
        T.[Characteristic 4 Name]                     = S.[CHARACTERISTIC_4_NAME],
        T.[Characteristic 4 Desc]                     = S.[CHARACTERISTIC_4_DESC],
        T.[Characteristic 4 Val]                      = S.[CHARACTERISTIC_4_VAL],
        T.[Characteristic 4 Val Desc]                 = S.[CHARACTERISTIC_4_VAL_DESC],
        T.[Characteristic 5 Internl Num]              = S.[CHARACTERISTIC_5_INTERNL_NUM],
        T.[Characteristic 5 Name]                     = S.[CHARACTERISTIC_5_NAME],
        T.[Characteristic 5 Desc]                     = S.[CHARACTERISTIC_5_DESC],
        T.[Characteristic 5 Val]                      = S.[CHARACTERISTIC_5_VAL],
        T.[Characteristic 5 Val Desc]                 = S.[CHARACTERISTIC_5_VAL_DESC],
        T.[Characteristic 6 Internl Num]              = S.[CHARACTERISTIC_6_INTERNL_NUM],
        T.[Characteristic 6 Name]                     = S.[CHARACTERISTIC_6_NAME],
        T.[Characteristic 6 Desc]                     = S.[CHARACTERISTIC_6_DESC],
        T.[Characteristic 6 Val]                      = S.[CHARACTERISTIC_6_VAL],
        T.[Characteristic 6 Val Desc]                 = S.[CHARACTERISTIC_6_VAL_DESC],
        T.[Characteristic 7 Internl Num]              = S.[CHARACTERISTIC_7_INTERNL_NUM],
        T.[Characteristic 7 Name]                     = S.[CHARACTERISTIC_7_NAME],
        T.[Characteristic 7 Desc]                     = S.[CHARACTERISTIC_7_DESC],
        T.[Characteristic 7 Val]                      = S.[CHARACTERISTIC_7_VAL],
        T.[Characteristic 7 Val Desc]                 = S.[CHARACTERISTIC_7_VAL_DESC],
        T.[Characteristic 8 Internl Num]              = S.[CHARACTERISTIC_8_INTERNL_NUM],
        T.[Characteristic 8 Name]                     = S.[CHARACTERISTIC_8_NAME],
        T.[Characteristic 8 Desc]                     = S.[CHARACTERISTIC_8_DESC],
        T.[Characteristic 8 Val]                      = S.[CHARACTERISTIC_8_VAL],
        T.[Characteristic 8 Val Desc]                 = S.[CHARACTERISTIC_8_VAL_DESC],
        T.[Characteristic 9 Internl Num]              = S.[CHARACTERISTIC_9_INTERNL_NUM],
        T.[Characteristic 9 Name]                     = S.[CHARACTERISTIC_9_NAME],
        T.[Characteristic 9 Desc]                     = S.[CHARACTERISTIC_9_DESC],
        T.[Characteristic 9 Val]                      = S.[CHARACTERISTIC_9_VAL],
        T.[Characteristic 9 Val Desc]                 = S.[CHARACTERISTIC_9_VAL_DESC],
        T.[Characteristic 10 Internl Num]             = S.[CHARACTERISTIC_10_INTERNL_NUM],
        T.[Characteristic 10 Name]                    = S.[CHARACTERISTIC_10_NAME],
        T.[Characteristic 10 Desc]                    = S.[CHARACTERISTIC_10_DESC],
        T.[Characteristic 10 Val]                     = S.[CHARACTERISTIC_10_VAL],
        T.[Characteristic 10 Val Desc]                = S.[CHARACTERISTIC_10_VAL_DESC],
        T.[Characteristic 11 Internl Num]             = S.[CHARACTERISTIC_11_INTERNL_NUM],
        T.[Characteristic 11 Name]                    = S.[CHARACTERISTIC_11_NAME],
        T.[Characteristic 11 Desc]                    = S.[CHARACTERISTIC_11_DESC],
        T.[Characteristic 11 Val]                     = S.[CHARACTERISTIC_11_VAL],
        T.[Characteristic 11 Val Desc]                = S.[CHARACTERISTIC_11_VAL_DESC],
        T.[Characteristic 12 Internl Num]             = S.[CHARACTERISTIC_12_INTERNL_NUM],
        T.[Characteristic 12 Name]                    = S.[CHARACTERISTIC_12_NAME],
        T.[Characteristic 12 Desc]                    = S.[CHARACTERISTIC_12_DESC],
        T.[Characteristic 12 Val]                     = S.[CHARACTERISTIC_12_VAL],
        T.[Characteristic 12 Val Desc]                = S.[CHARACTERISTIC_12_VAL_DESC],
        T.[Characteristic 13 Internl Num]             = S.[CHARACTERISTIC_13_INTERNL_NUM],
        T.[Characteristic 13 Name]                    = S.[CHARACTERISTIC_13_NAME],
        T.[Characteristic 13 Desc]                    = S.[CHARACTERISTIC_13_DESC],
        T.[Characteristic 13 Val]                     = S.[CHARACTERISTIC_13_VAL],
        T.[Characteristic 13 Val Desc]                = S.[CHARACTERISTIC_13_VAL_DESC],
        T.[Characteristic 14 Internl Num]             = S.[CHARACTERISTIC_14_INTERNL_NUM],
        T.[Characteristic 14 Name]                    = S.[CHARACTERISTIC_14_NAME],
        T.[Characteristic 14 Desc]                    = S.[CHARACTERISTIC_14_DESC],
        T.[Characteristic 14 Val]                     = S.[CHARACTERISTIC_14_VAL],
        T.[Characteristic 14 Val Desc]                = S.[CHARACTERISTIC_14_VAL_DESC],
        T.[Characteristic 15 Internl Num]             = S.[CHARACTERISTIC_15_INTERNL_NUM],
        T.[Characteristic 15 Name]                    = S.[CHARACTERISTIC_15_NAME],
        T.[Characteristic 15 Desc]                    = S.[CHARACTERISTIC_15_DESC],
        T.[Characteristic 15 Val]                     = S.[CHARACTERISTIC_15_VAL],
        T.[Characteristic 15 Val Desc]                = S.[CHARACTERISTIC_15_VAL_DESC],
        T.[Characteristic 16 Internl Num]             = S.[CHARACTERISTIC_16_INTERNL_NUM],
        T.[Characteristic 16 Name]                    = S.[CHARACTERISTIC_16_NAME],
        T.[Characteristic 16 Desc]                    = S.[CHARACTERISTIC_16_DESC],
        T.[Characteristic 16 Val]                     = S.[CHARACTERISTIC_16_VAL],
        T.[Characteristic 16 Val Desc]                = S.[CHARACTERISTIC_16_VAL_DESC],
        T.[Characteristic 17 Internl Num]             = S.[CHARACTERISTIC_17_INTERNL_NUM],
        T.[Characteristic 17 Name]                    = S.[CHARACTERISTIC_17_NAME],
        T.[Characteristic 17 Desc]                    = S.[CHARACTERISTIC_17_DESC],
        T.[Characteristic 17 Val]                     = S.[CHARACTERISTIC_17_VAL],
        T.[Characteristic 17 Val Desc]                = S.[CHARACTERISTIC_17_VAL_DESC],
        T.[Characteristic 18 Internl Num]             = S.[CHARACTERISTIC_18_INTERNL_NUM],
        T.[Characteristic 18 Name]                    = S.[CHARACTERISTIC_18_NAME],
        T.[Characteristic 18 Desc]                    = S.[CHARACTERISTIC_18_DESC],
        T.[Characteristic 18 Val]                     = S.[CHARACTERISTIC_18_VAL],
        T.[Characteristic 18 Val Desc]                = S.[CHARACTERISTIC_18_VAL_DESC],
        T.[Characteristic 19 Internl Num]             = S.[CHARACTERISTIC_19_INTERNL_NUM],
        T.[Characteristic 19 Name]                    = S.[CHARACTERISTIC_19_NAME],
        T.[Characteristic 19 Desc]                    = S.[CHARACTERISTIC_19_DESC],
        T.[Characteristic 19 Val]                     = S.[CHARACTERISTIC_19_VAL],
        T.[Characteristic 19 Val Desc]                = S.[CHARACTERISTIC_19_VAL_DESC],
        T.[Characteristic 20 Internl Num]             = S.[CHARACTERISTIC_20_INTERNL_NUM],
        T.[Characteristic 20 Name]                    = S.[CHARACTERISTIC_20_NAME],
        T.[Characteristic 20 Desc]                    = S.[CHARACTERISTIC_20_DESC],
        T.[Characteristic 20 Val]                     = S.[CHARACTERISTIC_20_VAL],
        T.[Characteristic 20 Val Desc]                = S.[CHARACTERISTIC_20_VAL_DESC],
        T.[Characteristic 21 Internl Num]             = S.[CHARACTERISTIC_21_INTERNL_NUM],
        T.[Characteristic 21 Name]                    = S.[CHARACTERISTIC_21_NAME],
        T.[Characteristic 21 Desc]                    = S.[CHARACTERISTIC_21_DESC],
        T.[Characteristic 21 Val]                     = S.[CHARACTERISTIC_21_VAL],
        T.[Characteristic 21 Val Desc]                = S.[CHARACTERISTIC_21_VAL_DESC],
        T.[Characteristic 22 Internl Num]             = S.[CHARACTERISTIC_22_INTERNL_NUM],
        T.[Characteristic 22 Name]                    = S.[CHARACTERISTIC_22_NAME],
        T.[Characteristic 22 Desc]                    = S.[CHARACTERISTIC_22_DESC],
        T.[Characteristic 22 Val]                     = S.[CHARACTERISTIC_22_VAL],
        T.[Characteristic 22 Val Desc]                = S.[CHARACTERISTIC_22_VAL_DESC],
        T.[Characteristic 23 Internl Num]             = S.[CHARACTERISTIC_23_INTERNL_NUM],
        T.[Characteristic 23 Name]                    = S.[CHARACTERISTIC_23_NAME],
        T.[Characteristic 23 Desc]                    = S.[CHARACTERISTIC_23_DESC],
		T.[Characteristic 23 Val]                     = S.[CHARACTERISTIC_23_VAL],
        T.[Characteristic 23 Val Desc]                = S.[CHARACTERISTIC_23_VAL_DESC],
        T.[Material Description Italian]              = S.[MATRL_DESC_ITALIAN],
        T.[Material Cross Plant Status]               = S.[MATRL_X_PLNT_STATUS],
        T.[Material Cross Plant Description]          = S.[MATRL_X_PLNT_DESC],
        T.[DIVISION]                                  = S.[DIVISION],
        T.[DIVISION_DESC]                             = S.[DIVISION_DESC]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_MATERIAL_CUR_D] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_MATERIAL_CUR_D] S
        ON T.[MATRL_KEY] = S.[MATRL_KEY];

    -- =============================
    -- INSERT new records
    -- =============================
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_MST_MATERIAL_CUR_D] (
        [MATRL_KEY],
        [Material ID],
        [Material Description],
        [Legacy Material ID],
        [Material Customer ID],
        [Material Category],
        [Material Type],
        [Material Group],
        [Material Base Unit Of Measure],
        [Material Industry Sector],
        [Material General Item Category Group],
        [Material Unit],
        [Material Gross Weight],
        [Material Net Weight],
        [Material Product Hierarchy],
        [Category of Material],
        [Material Brand],
        [Material Sub Brand],
        [Material Variant Obsolete],
        [Material Variant],
        [Material Name 1],
        [Material Pack Size],
        [Material Pack Type],
        [Material Country Name],
        [Material Print Method],
        [Material Level 4 Product Category Code],
        [Material Level 4 Product Category Description],
        [Material Level 3 Sub Family Code],
        [Material Level 3 Sub Family Description],
        [Material Level 2 Family Code],
        [Material Level 2 Family Description],
        [Material Level 1 Class Code],
        [Material Level 1 Class Description],
        [Material Created Date],
        [Material Created User ID],
        [Material Updated Date],
        [Material Updated User ID],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Material Group Description],
        [Material Group Description 2],
        [Category of Material Description],
        [Material Brand Description],
        [Material Sub Brand Description],
        [Material Print Method Description],
        [Material Level 5 Product Category Code],
        [Material Level 5 Product Category Description],
        [Material Level 6 Product Category Code],
        [Material Level 6 Product Category Description],
        [Material Category Description],
        [Material Type Description],
        [Material Product Hierarchy Description],
        [Material Industry Sector Description],
        [Material General Item Category Group Description],
        [Material Client Level Deletion Indicator],
        [Material PO UoM],
        [Material Basic],
        [Material Industry Standard Description],
        [Material Laboratory/Design Office],
        [Material Laboratory/Design Office Description],
        [Material Purchasing Value Key],
        [Material Storage Condition],
        [Material Storage Condition Description],
        [Material Temperature Conditions Indicator],
        [Material Temperature Conditions Indicator Description],
        [Material Transportation Group],
        [Material Transportation Group Description],
        [Material Hazardous Number],
        [Material Source of Supply],
        [Material Source of Supply Description],
        [Material EAN/UPC Number],
        [Material EAN Category],
        [Material EAN Category Description],
        [Material Length],
        [Material Width],
        [Material Height],
        [Material UoD],
        [Material External Group],
        [Material External Group Description],
        [Material Manufacturer Part Number],
        [Material Dangerous Goods Indicator Profile],
        [Material Dangerous Goods Indicator Profile Desription],
        [Material Country of Origin],
        [Material Country of Origin Description],
        [Material Quality Inspection Group],
        [Material Quality Inspection Group Description],
        [MATRL_SALES_TEXT],
        [Class Internl Num],
        [Class Name],
        [Class Typ],
        [Class Typ Desc],
        [Class Status],
        [Class Status Desc],
        [Characteristic 1 Internl Num],    
        [Characteristic 1 Name],     
        [Characteristic 1 Desc],            
        [Characteristic 1 Val],           
        [Characteristic 1 Val Desc],         
        [Characteristic 2 Internl Num],      
        [Characteristic 2 Name],     
        [Characteristic 2 Desc],             
        [Characteristic 2 Val],              
        [Characteristic 2 Val Desc],         
        [Characteristic 3 Internl Num],      
        [Characteristic 3 Name],             
        [Characteristic 3 Desc],             
        [Characteristic 3 Val],              
        [Characteristic 3 Val Desc],         
        [Characteristic 4 Internl Num],      
        [Characteristic 4 Name],             
        [Characteristic 4 Desc],             
        [Characteristic 4 Val],              
        [Characteristic 4 Val Desc],         
        [Characteristic 5 Internl Num],      
        [Characteristic 5 Name],             
        [Characteristic 5 Desc],             
        [Characteristic 5 Val],              
        [Characteristic 5 Val Desc],         
        [Characteristic 6 Internl Num],      
        [Characteristic 6 Name],             
        [Characteristic 6 Desc],             
        [Characteristic 6 Val],              
        [Characteristic 6 Val Desc],         
        [Characteristic 7 Internl Num],      
        [Characteristic 7 Name],             
        [Characteristic 7 Desc],             
        [Characteristic 7 Val],              
        [Characteristic 7 Val Desc],         
        [Characteristic 8 Internl Num],      
        [Characteristic 8 Name],             
        [Characteristic 8 Desc],             
        [Characteristic 8 Val],              
        [Characteristic 8 Val Desc],         
        [Characteristic 9 Internl Num],      
        [Characteristic 9 Name],             
        [Characteristic 9 Desc],             
        [Characteristic 9 Val],              
        [Characteristic 9 Val Desc],         
        [Characteristic 10 Internl Num],     
        [Characteristic 10 Name],            
        [Characteristic 10 Desc],            
        [Characteristic 10 Val],             
        [Characteristic 10 Val Desc],        
        [Characteristic 11 Internl Num],     
        [Characteristic 11 Name],            
        [Characteristic 11 Desc],            
        [Characteristic 11 Val],             
        [Characteristic 11 Val Desc],        
        [Characteristic 12 Internl Num],     
        [Characteristic 12 Name],            
        [Characteristic 12 Desc],            
        [Characteristic 12 Val],             
        [Characteristic 12 Val Desc],        
        [Characteristic 13 Internl Num],     
        [Characteristic 13 Name],            
        [Characteristic 13 Desc],            
        [Characteristic 13 Val],             
        [Characteristic 13 Val Desc],        
        [Characteristic 14 Internl Num],     
        [Characteristic 14 Name],            
        [Characteristic 14 Desc],            
        [Characteristic 14 Val],             
        [Characteristic 14 Val Desc],        
        [Characteristic 15 Internl Num],     
        [Characteristic 15 Name],            
        [Characteristic 15 Desc],            
        [Characteristic 15 Val],             
        [Characteristic 15 Val Desc],        
        [Characteristic 16 Internl Num],     
        [Characteristic 16 Name],            
        [Characteristic 16 Desc],            
        [Characteristic 16 Val],             
        [Characteristic 16 Val Desc],        
        [Characteristic 17 Internl Num],     
        [Characteristic 17 Name],            
        [Characteristic 17 Desc],            
        [Characteristic 17 Val],             
        [Characteristic 17 Val Desc],        
        [Characteristic 18 Internl Num],     
        [Characteristic 18 Name],            
        [Characteristic 18 Desc],            
        [Characteristic 18 Val],             
        [Characteristic 18 Val Desc],        
        [Characteristic 19 Internl Num],     
        [Characteristic 19 Name],            
        [Characteristic 19 Desc],            
        [Characteristic 19 Val],             
        [Characteristic 19 Val Desc],        
        [Characteristic 20 Internl Num],     
        [Characteristic 20 Name],            
        [Characteristic 20 Desc],            
        [Characteristic 20 Val],             
        [Characteristic 20 Val Desc],        
        [Characteristic 21 Internl Num],     
        [Characteristic 21 Name],            
        [Characteristic 21 Desc],            
        [Characteristic 21 Val],             
        [Characteristic 21 Val Desc],        
        [Characteristic 22 Internl Num],     
        [Characteristic 22 Name],            
        [Characteristic 22 Desc],            
        [Characteristic 22 Val],             
        [Characteristic 22 Val Desc],        
        [Characteristic 23 Internl Num],     
        [Characteristic 23 Name],            
        [Characteristic 23 Desc], 
		[Characteristic 23 Val],             
        [Characteristic 23 Val Desc],
        [Material Description Italian],
        [Material Cross Plant Status],
        [Material Cross Plant Description],
        [DIVISION],
        [DIVISION_DESC]
   )
    SELECT
        S.[MATRL_KEY],
        S.[MATRL_ID],
        S.[MATRL_DESC],
        S.[LGCY_MATRL_ID],
        S.[CUST_ID],
        S.[MATRL_CTGRY],
        S.[MATRL_TYP],
        S.[MATRL_GROUP],
        S.[BASE_UNIT_OF_MEASUR],
        S.[INDUS_SECTOR],
        S.[GENERAL_ITM_CTGRY_GROUP],
        S.[UNIT],
        S.[GROSS_WGHT],
        S.[NET_WGHT],
        S.[PRDT_HIERCHY],
        S.[CTGRY],
        S.[BRAND],
        S.[SUB_BRAND],
        S.[VARIANT_OBSOLET],
        S.[VARIANT],
        S.[NAME_1],
        S.[PACK_SIZE],
        S.[PACK_TYP],
        S.[CNTRY_NAME],
        S.[PRNT_MTHD],
        S.[LEVEL4_PRDT_CTGRY_CD],
        S.[LEVEL4_PRDT_CTGRY_DESC],
        S.[LEVEL3_SUB_FAMILY_CD],
        S.[LEVEL3_SUB_FAMILY_DESC],
        S.[LEVEL2_FAMILY_CD],
        S.[LEVEL2_FAMILY_DESC],
        S.[LEVEL1_CLASS_CD],
        S.[LEVEL1_CLASS_DESC],
        S.[CREATED_DATE],
        S.[CREATED_USR_ID],
        S.[UPDTD_DATE],
        S.[UPDTD_USR_ID],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[MATRL_GROUP_DESC],
        S.[MATRL_GROUP_DESC_2],
        S.[CTGRY_DESC],
        S.[BRAND_DESC],
        S.[SUB_BRAND_DESC],
        S.[PRNT_MTHD_DESC],
        S.[LEVEL5_PRDT_CTGRY_CD],
        S.[LEVEL5_PRDT_CTGRY_DESC],
        S.[LEVEL6_PRDT_CTGRY_CD],
        S.[LEVEL6_PRDT_CTGRY_DESC],
        S.[MATRL_CTGRY_DESC],
        S.[MATRL_TYP_DESC],
        S.[PRDT_HIERCHY_DESC],
        S.[INDUS_SECTOR_DESC],
        S.[GEN_ITM_CTGRY_GRP_DESC],
        S.[CLNT_LVL_DELETION_IND],
        S.[PO_UOM],
        S.[BASIC_MATRL],
        S.[INDUS_STD_DESC],
        S.[LABORATORY_DESIGN_OFFC],
        S.[LABORATORY_DESIGN_OFFC_DESC],
        S.[PURNG_VAL_KEY],
        S.[STOR_COND],
        S.[STOR_COND_DESC],
        S.[TEMPERATURE_CONDITIONS_IND],
        S.[TEMPERATURE_CONDITIONS_IND_DESC],
        S.[TRANSTN_GROUP],
        S.[TRANSTN_GROUP_DESC],
        S.[HAZARDOUS_MATRL_NUM],
        S.[SRC_OF_SUPLY],
        S.[SRC_OF_SUPLY_DESC],
        S.[EAN_UPC_NO],
        S.[EAN_CTGRY],
        S.[EAN_CTGRY_DESC],
        S.[LNGTH],
        S.[WIDTH],
        S.[HGHT],
        S.[UOD],
        S.[EXTNL_MATRL_GROUP],
        S.[EXTNL_MATRL_GROUP_DESC],
        S.[MANUFACTURER_PART_NUM],
        S.[DANGEROUS_GOODS_IND_PROFILE],
        S.[DANGEROUS_GOODS_IND_PROFILE_DES],
        S.[CNTRY_OF_ORIGIN],
        S.[CNTRY_OF_ORIGION_DESC],
        S.[QUAL_INSPTN_GROUP],
        S.[QUAL_INSPTN_GROUP_DESC],
        S.[MATRL_SALES_TEXT],
        S.[CLASS_INTERNL_NUM],
        S.[CLASS_NAME],
        S.[CLASS_TYP],
        S.[CLASS_TYP_DESC],
        S.[CLASS_STATUS],
        S.[CLASS_STATUS_DESC],
        S.[CHARACTERISTIC_1_INTERNL_NUM],
	    S.[CHARACTERISTIC_1_NAME],
	    S.[CHARACTERISTIC_1_DESC],
	    S.[CHARACTERISTIC_1_VAL],
	    S.[CHARACTERISTIC_1_VAL_DESC],
	    S.[CHARACTERISTIC_2_INTERNL_NUM],
	    S.[CHARACTERISTIC_2_NAME],
	    S.[CHARACTERISTIC_2_DESC],
	    S.[CHARACTERISTIC_2_VAL],
	    S.[CHARACTERISTIC_2_VAL_DESC],
	    S.[CHARACTERISTIC_3_INTERNL_NUM],
	    S.[CHARACTERISTIC_3_NAME],
	    S.[CHARACTERISTIC_3_DESC],
	    S.[CHARACTERISTIC_3_VAL],
	    S.[CHARACTERISTIC_3_VAL_DESC],
	    S.[CHARACTERISTIC_4_INTERNL_NUM],
	    S.[CHARACTERISTIC_4_NAME],
	    S.[CHARACTERISTIC_4_DESC],
	    S.[CHARACTERISTIC_4_VAL],
	    S.[CHARACTERISTIC_4_VAL_DESC],
	    S.[CHARACTERISTIC_5_INTERNL_NUM],
	    S.[CHARACTERISTIC_5_NAME],
	    S.[CHARACTERISTIC_5_DESC],
	    S.[CHARACTERISTIC_5_VAL],
	    S.[CHARACTERISTIC_5_VAL_DESC],
	    S.[CHARACTERISTIC_6_INTERNL_NUM],
	    S.[CHARACTERISTIC_6_NAME],
	    S.[CHARACTERISTIC_6_DESC],
	    S.[CHARACTERISTIC_6_VAL],
	    S.[CHARACTERISTIC_6_VAL_DESC],
	    S.[CHARACTERISTIC_7_INTERNL_NUM],
	    S.[CHARACTERISTIC_7_NAME],
	    S.[CHARACTERISTIC_7_DESC],
	    S.[CHARACTERISTIC_7_VAL],
	    S.[CHARACTERISTIC_7_VAL_DESC],
	    S.[CHARACTERISTIC_8_INTERNL_NUM],
	    S.[CHARACTERISTIC_8_NAME],
	    S.[CHARACTERISTIC_8_DESC],
	    S.[CHARACTERISTIC_8_VAL],
	    S.[CHARACTERISTIC_8_VAL_DESC],
	    S.[CHARACTERISTIC_9_INTERNL_NUM],
	    S.[CHARACTERISTIC_9_NAME],
	    S.[CHARACTERISTIC_9_DESC],
	    S.[CHARACTERISTIC_9_VAL],
	    S.[CHARACTERISTIC_9_VAL_DESC],
	    S.[CHARACTERISTIC_10_INTERNL_NUM],
	    S.[CHARACTERISTIC_10_NAME],
	    S.[CHARACTERISTIC_10_DESC],
	    S.[CHARACTERISTIC_10_VAL],
	    S.[CHARACTERISTIC_10_VAL_DESC],
	    S.[CHARACTERISTIC_11_INTERNL_NUM],
	    S.[CHARACTERISTIC_11_NAME],
	    S.[CHARACTERISTIC_11_DESC],
	    S.[CHARACTERISTIC_11_VAL],
	    S.[CHARACTERISTIC_11_VAL_DESC],
	    S.[CHARACTERISTIC_12_INTERNL_NUM],
	    S.[CHARACTERISTIC_12_NAME],
	    S.[CHARACTERISTIC_12_DESC],
	    S.[CHARACTERISTIC_12_VAL],
	    S.[CHARACTERISTIC_12_VAL_DESC],
	    S.[CHARACTERISTIC_13_INTERNL_NUM],
	    S.[CHARACTERISTIC_13_NAME],
	    S.[CHARACTERISTIC_13_DESC],
	    S.[CHARACTERISTIC_13_VAL],
	    S.[CHARACTERISTIC_13_VAL_DESC],
	    S.[CHARACTERISTIC_14_INTERNL_NUM],
	    S.[CHARACTERISTIC_14_NAME],
	    S.[CHARACTERISTIC_14_DESC],
	    S.[CHARACTERISTIC_14_VAL],
	    S.[CHARACTERISTIC_14_VAL_DESC],
	    S.[CHARACTERISTIC_15_INTERNL_NUM],
	    S.[CHARACTERISTIC_15_NAME],
	    S.[CHARACTERISTIC_15_DESC],
	    S.[CHARACTERISTIC_15_VAL],
	    S.[CHARACTERISTIC_15_VAL_DESC],
	    S.[CHARACTERISTIC_16_INTERNL_NUM],
	    S.[CHARACTERISTIC_16_NAME],
	    S.[CHARACTERISTIC_16_DESC],
	    S.[CHARACTERISTIC_16_VAL],
	    S.[CHARACTERISTIC_16_VAL_DESC],
	    S.[CHARACTERISTIC_17_INTERNL_NUM],
	    S.[CHARACTERISTIC_17_NAME],
	    S.[CHARACTERISTIC_17_DESC],
	    S.[CHARACTERISTIC_17_VAL],
	    S.[CHARACTERISTIC_17_VAL_DESC],
	    S.[CHARACTERISTIC_18_INTERNL_NUM],
	    S.[CHARACTERISTIC_18_NAME],
	    S.[CHARACTERISTIC_18_DESC],
	    S.[CHARACTERISTIC_18_VAL],
	    S.[CHARACTERISTIC_18_VAL_DESC],
	    S.[CHARACTERISTIC_19_INTERNL_NUM],
	    S.[CHARACTERISTIC_19_NAME],
	    S.[CHARACTERISTIC_19_DESC],
	    S.[CHARACTERISTIC_19_VAL],
	    S.[CHARACTERISTIC_19_VAL_DESC],
	    S.[CHARACTERISTIC_20_INTERNL_NUM],
	    S.[CHARACTERISTIC_20_NAME],
	    S.[CHARACTERISTIC_20_DESC],
	    S.[CHARACTERISTIC_20_VAL],
	    S.[CHARACTERISTIC_20_VAL_DESC],
	    S.[CHARACTERISTIC_21_INTERNL_NUM],
	    S.[CHARACTERISTIC_21_NAME],
	    S.[CHARACTERISTIC_21_DESC],
	    S.[CHARACTERISTIC_21_VAL],
	    S.[CHARACTERISTIC_21_VAL_DESC],
	    S.[CHARACTERISTIC_22_INTERNL_NUM],
	    S.[CHARACTERISTIC_22_NAME],
	    S.[CHARACTERISTIC_22_DESC],
	    S.[CHARACTERISTIC_22_VAL],
	    S.[CHARACTERISTIC_22_VAL_DESC],
	    S.[CHARACTERISTIC_23_INTERNL_NUM],
	    S.[CHARACTERISTIC_23_NAME],
	    S.[CHARACTERISTIC_23_DESC],
        S.[CHARACTERISTIC_23_VAL],
	    S.[CHARACTERISTIC_23_VAL_DESC],		
        S.[MATRL_DESC_ITALIAN],
        S.[MATRL_X_PLNT_STATUS],
        S.[MATRL_X_PLNT_DESC],
        S.[DIVISION],
        S.[DIVISION_DESC]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_MATERIAL_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_MATERIAL_CUR_D] T
        ON T.[MATRL_KEY] = S.[MATRL_KEY]
    WHERE T.[MATRL_KEY] IS NULL;
END