CREATE   PROCEDURE [dbo].[Proc_EDW_T_D_PRD_SERVORD_CUR_D]
AS
BEGIN
    
    UPDATE T
    SET
		T.[SERVC_ORDER_KEY] = S.[SERVC_ORDER_KEY],
        T.[Service Order] = S.[SERVC_ORDER],
        T.[Service Order Operation Task List ID] = S.[OPERATION_TASK_LIST_ID],
        T.[Service Order Order Type] = S.[ORDER_TYP],
        T.[Service Order Category] = S.[ORDER_CTGRY],
        T.[Service Order Company Code] = S.[CMPNY_CD],
        T.[Service Order Plant] = S.[PLNT],
        T.[Service Order Location Plant] = S.[LOC_PLNT],
        T.[Service Order Maintenance Plant] = S.[MAINTENANCE_PLNT],
        T.[Service Order Document Currency] = S.[DOCMT_CRNCY],
        T.[Service Order Maintenance Work Center] = S.[MAINTENANCE_WRK_CNTR],
        T.[Service Order Functional Area] = S.[FUNCTNL_AREA],
        T.[Service Order Object Class] = S.[OBJ_CLASS],
        T.[Service Order Estimated Total Costs] = S.[ESTD_TOTAL_COSTS_OF_ORDER],
        T.[Service Order Description] = S.[DESC],
        T.[Service Order Is Created] = S.[IS_CREATED],
        T.[Service Order Is Released] = S.[IS_RELSD],
        T.[Service Order Is Completed] = S.[IS_COMPLETED],
        T.[Service Order Is Closed] = S.[IS_CLSD],
        T.[Service Order Release Date] = S.[RELS_DATE],
        T.[Service Order Tech Completion Date] = S.[TCHNCL_COMPLETION_DATE],
        T.[Service Order Close Date] = S.[CLS_DATE],
        T.[Service Order Deletion Flag] = S.[DELETION_FLG],
		T.[Service Order Object Number] = S.[OBJ_NUM],
        T.[Service Order Responsible Cost Center] = S.[RESPNSBLE_COST_CNTR],
        T.[Service Order Profit Center] = S.[PROFT_CNTR],
        T.[Service Order Basic Start Date] = S.[BASIC_START_DATE],
        T.[Service Order Basic Finish Date] = S.[BASIC_FINISH_DATE],
        T.[Service Order Scheduled Release Date] = S.[SCHLD_RELS_DATE],
        T.[Service Order Scheduled Finish Date] = S.[SCHLD_FINISH_DATE],
        T.[Service Order Scheduled Start Date] = S.[SCHLD_START_DATE],
        T.[Service Order Actual Start Date] = S.[ACTUAL_START_DATE],
        T.[Service Order Actual Finish Date] = S.[ACTUAL_FINISH_DATE],
        T.[Service Order Actual Release Date] = S.[ACTUAL_RELS_DATE],
        T.[Service Order Planned Release Date] = S.[PLND_RELS_DATE],
        T.[Service Order Reservation] = S.[RESRVTN],
        T.[Service Order Total Scrap] = S.[TOTAL_SCRAP],
        T.[Service Order Target Quantity] = S.[TRGT_QTY],
        T.[Service Order Task List Type] = S.[TASK_LIST_TYP],
        T.[Service Order Capacity Requirements ID] = S.[CAPACITY_REQMNTS_ID],
        T.[Service Order Equipment] = S.[EQUIP],
        T.[Service Order Location Account Assignment] = S.[LOC_ACCT_ASSIGN],
        T.[Service Order Planning Plant] = S.[PLNG_PLNT],
        T.[Service Order Work Center] = S.[WRK_CNTR],
        T.[Service Order Object List] = S.[OBJ_LIST],
        T.[Service Order Maintenance Activity Type] = S.[MAINTENANCE_ACTIVITY_TYP],
        T.[Service Order Notification] = S.[NOTIFICATION],
        T.[Service Order Cost Center] = S.[COST_CNTR],
        T.[Service Order Functional Location] = S.[FUNCTNL_LOC],
        T.[Service Order Sales Order] = S.[SALES_ORDER],
        T.[Service Order Sales Order Item Number] = S.[SALES_ORDER_ITM_NUM],
        T.[Service Order Count Of Rounds] = S.[CNT_OF_ROUNDS],
        T.[Service Order Count Of Rework Internal] = S.[CNT_OF_REWORK_INTERNL],
        T.[Service Order HUB Production Deadline Date] = S.[HUB_PROD_DEADLINE],
        T.[Service Order HUB Approval Loop Deadline Date] = S.[HUB_APPROVAL_LOOP_DEADLINE],
        T.[Service Order HUB Change Request Deadline Date] = S.[HUB_CHG_REQUEST_DEADLINE],
        T.[Service Order HUB Finish Date Deadline Date] = S.[HUB_FINISH_DATE_DEADLINE],
        T.[Service Order HUB Number Of Loops] = S.[HUB_NUM_OF_LOOPS],
        T.[Service Order HUB Webstatus] = S.[HUB_WEBSTATUS],
        T.[Service Order HUB First Time In Prep For Production] = S.[HUB_FIRST_TM_IN_PREP_FOR_PROD],
        T.[Service Order HUB Last Time In Prep For Production] = S.[HUB_LAST_TM_IN_PREP_FOR_PROD],
        T.[Service Order HUB First Time In Production] = S.[HUB_FIRST_TM_IN_PROD],
        T.[Service Order HUB Last Time In Production] = S.[HUB_LAST_TM_IN_PROD],
        T.[Service Order HUB First Time In Out For Approval] = S.[HUB_FIRST_TM_IN_OUT_FOR_APPROVA],
        T.[Service Order HUB Last Time In Out For Approval] = S.[HUB_LAST_TM_IN_OUT_FOR_APPROVAL],
        T.[Service Order HUB First Time In Approval Loop] = S.[HUB_FIRST_TM_IN_APPROVAL_LOOP],
        T.[Service Order HUB Last Time In Approval Loop] = S.[HUB_LAST_TM_IN_APPROVAL_LOOP],
        T.[Service Order HUB First Time In Change Request] = S.[HUB_FIRST_TM_IN_CHG_REQUEST],
        T.[Service Order HUB Last Time In Change Request] = S.[HUB_LAST_TM_IN_CHG_REQUEST],
        T.[Service Order HUB First Time In Approved] = S.[HUB_FIRST_TM_IN_APPRVD],
        T.[Service Order HUB Last Time In Approved] = S.[HUB_LAST_TM_IN_APPRVD],
        T.[Service Order HUB First Time In Final Production] = S.[HUB_FIRST_TM_IN_FINAL_PROD],
        T.[Service Order HUB Last Time In Final Production] = S.[HUB_LAST_TM_IN_FINAL_PROD],
        T.[Service Order HUB First Time In Production Completed] = S.[HUB_FIRST_TM_IN_PROD_COMPLETED],
        T.[Service Order HUB Last Time In Production Completed] = S.[HUB_LAST_TM_IN_PROD_COMPLETED],
        T.[Service Order HUB First Time In On Hold] = S.[HUB_FIRST_TM_IN_ON_HOLD],
        T.[Service Order HUB Last Time In On Hold] = S.[HUB_LAST_TM_IN_ON_HOLD],
        T.[Service Order HUB First Time In Archived] = S.[HUB_FIRST_TM_IN_ARCHIVED],
        T.[Service Order HUB Last Time In Archived] = S.[HUB_LAST_TM_IN_ARCHIVED],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE] = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE] = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND] = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Service Order HUB Webstatus Description] = S.[HUB_WEBSTATUS_DESC],
        T.[Service Order Done Date] = S.[SERVC_ORDER_DONE_DATE],
        T.[Service Order Invoice Create Date] = S.[INVC_CREATE_DATE],
		T.[Service Order Production Complete Date] = S.[PROD_COMPLETE_DATE],
        T.[Service Order Waiting on Client PO Date] = S.[WAITING_ON_CLNT_PO_DATE],
		T.[Service Order Billing In Progress Date] = S.[BILLING_IN_PROGRESS_DATE],
		T.[Service Order Released To Invoicing Date] = S.[RELSD_TO_INVOICING_DATE],
        T.[Service Order Last Changed By] = S.[LAST_CHANGED_BY],
        T.[Service Order Change Date] = S.[CHG_DATE],
        T.[Service Order Entered By] = S.[ENTERED_BY],
        T.[Service Order Additional Device Data] = S.[ADDITIONAL_DEVICE_DATA],
        T.[Service Order Assembly] = S.[ASSEMBLY],
        T.[Service Order ILOA Individual] = S.[ILOA_INDIVIDUAL],
        T.[Service Order Priority] = S.[PRIORITY],
        T.[Service Order Priority Type] = S.[PRIORITY_TYP],
        T.[Service Order Reason Code] = S.[RSN_CD],
        T.[Service Order Reason for Change] = S.[RSN_FOR_CHG],
        T.[Service Order Description of Change] = S.[DESC_OF_CHG],
        T.[Service Order Error Caught By] = S.[ERR_CAUGHT_BY],
        T.[Service Order Error Description] = S.[ERR_DESC],
        T.[Service Order Error Origin] = S.[ERR_ORIGIN],
        T.[Service Order Error Severity] = S.[ERR_SEVERITY],
        T.[Service Order Error Type] = S.[ERR_TYP],
        T.[Service Order Requested By] = S.[REQD_BY],
        T.[Service Order Controlling Area] = S.[CONTROLLING_AREA],
        T.[Service Order Equity Type] = S.[EQUITY_TYP],
        T.[Service Order WBS Element] = S.[WBS_ELEMNT],
		T.[Service Order Job Status] = S.[JOB_STATUS],
        T.[Service Order System Status] = S.[SYS_STATUS],
        T.[Service Order Type Description] = S.[ORDER_TYP_DESC],
        T.[Service Order Category Description] = S.[ORDER_CTGRY_DESC],
        T.[Service Order Company Description] = S.[CMPNY_DESC],
        T.[Service Order Plant Description] = S.[PLNT_DESC],
        T.[Service Order Location Plant Description] = S.[LOC_PLNT_DESC],
        T.[Service Order Maintenance Plant Description] = S.[MAINT_PLNT_DESC],
        T.[Service Order Document Currency Description] = S.[DOCMT_CRNCY_DESC],
        T.[Service Order Object Class Description] = S.[OBJ_CLASS_DESC],
        T.[Service Order Task List Type Description] = S.[TASK_LIST_TYP_DESC],
        T.[Service Order Planning Plant Description] = S.[PLNG_PLNT_DESC],
        T.[Service Order Work Center Description] = S.[WRK_CNTR_DESC],
        T.[Service Order Maintenance Activity Type Description] = S.[MAINTENANCE_ACTIVITY_TYP_DESC],
        T.[Service Order Active Date] = S.[ACTIVE_DATE],
        T.[Service Order On Hold Date] = S.[ON_HOLD_DATE],
        T.[Service Order Intercompany Date] = S.[INTERCOMPANY_DATE],
        T.[Service Order Out For Appproval Date] = S.[OUT_FOR_APPPROVAL_DATE],
        T.[Service Order Closed Date] = S.[CLSD_DATE],
        T.[Service Order Post Approval Production Date] = S.[POST_APPROVAL_PROD_DATE],
        T.[Service Order Active Artwork Date] = S.[ACTIVE_ARTWORK_DATE],
        T.[Service Order Active Prepress Date] = S.[ACTIVE_PREPRESS_DATE],
        T.[Service Order Priority Type Description]  = S.[PRIORITY_TYP_DESC],
        T.[Service Order Controlling Area Description] = S.[CONTROLLING_AREA_DESC],
        T.[Service Order Equity Type Description]  = S.[EQUITY_TYP_DESC],
        T.[Service Order Created On Date]  = S.[CREATED_ON_DATE],
        T.[Service Order Accountng Indicator Customer]  = S.[ACCTNG_IND],
        T.[Service Order Accountng Indicator Customer Description] = S.[ACCTNG_IND_DESC]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_PRD_SERVORD_CUR_D] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_PRD_SERVORD_CUR_D] S
        ON T.[SERVC_ORDER_KEY] = S.[SERVC_ORDER_KEY];
		
		
    -- Step 2: Insert new records from [GLOBAL_EDW_MIRROR] to [GLOBAL_EDW] where SERVC_ORDER_KEY does not exist
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_PRD_SERVORD_CUR_D] (
	[SERVC_ORDER_KEY],
	[Service Order],
	[Service Order Operation Task List ID],
	[Service Order Order Type],
	[Service Order Category],
	[Service Order Company Code], 
	[Service Order Plant], 
	[Service Order Location Plant], 
	[Service Order Maintenance Plant], 
	[Service Order Document Currency], 
	[Service Order Maintenance Work Center], 
	[Service Order Functional Area], 
	[Service Order Object Class], 
	[Service Order Estimated Total Costs], 
	[Service Order Description], 
	[Service Order Is Created], 
	[Service Order Is Released], 
	[Service Order Is Completed], 
	[Service Order Is Closed], 
	[Service Order Release Date], 
	[Service Order Tech Completion Date], 
	[Service Order Close Date], 
	[Service Order Deletion Flag], 
	[Service Order Object Number], 
	[Service Order Responsible Cost Center], 
	[Service Order Profit Center],
	[Service Order Basic Start Date],
	[Service Order Basic Finish Date], 
	[Service Order Scheduled Release Date], 
	[Service Order Scheduled Finish Date],
	[Service Order Scheduled Start Date], 
	[Service Order Actual Start Date], 
	[Service Order Actual Finish Date], 
	[Service Order Actual Release Date], 
	[Service Order Planned Release Date], 
	[Service Order Reservation], 
	[Service Order Total Scrap],
	[Service Order Target Quantity],
	[Service Order Task List Type], 
	[Service Order Capacity Requirements ID],
	[Service Order Equipment],
	[Service Order Location Account Assignment],
	[Service Order Planning Plant], 
	[Service Order Work Center], 
	[Service Order Object List], 
	[Service Order Maintenance Activity Type], 
	[Service Order Notification], 
	[Service Order Cost Center], 
	[Service Order Functional Location], 
	[Service Order Sales Order],
	[Service Order Sales Order Item Number],
	[Service Order Count Of Rounds], 
	[Service Order Count Of Rework Internal],
	[Service Order HUB Production Deadline Date], 
	[Service Order HUB Approval Loop Deadline Date], 
	[Service Order HUB Change Request Deadline Date], 
	[Service Order HUB Finish Date Deadline Date], 
	[Service Order HUB Number Of Loops], 
	[Service Order HUB Webstatus], 
	[Service Order HUB First Time In Prep For Production], 
	[Service Order HUB Last Time In Prep For Production],
	[Service Order HUB First Time In Production], 
	[Service Order HUB Last Time In Production], 
	[Service Order HUB First Time In Out For Approval], 
	[Service Order HUB Last Time In Out For Approval], 
	[Service Order HUB First Time In Approval Loop], 
	[Service Order HUB Last Time In Approval Loop],
	[Service Order HUB First Time In Change Request], 
	[Service Order HUB Last Time In Change Request], 
	[Service Order HUB First Time In Approved],
	[Service Order HUB Last Time In Approved], 
	[Service Order HUB First Time In Final Production],
	[Service Order HUB Last Time In Final Production], 
	[Service Order HUB First Time In Production Completed], 
	[Service Order HUB Last Time In Production Completed] ,
	[Service Order HUB First Time In On Hold]             ,
	[Service Order HUB Last Time In On Hold]              ,
	[Service Order HUB First Time In Archived]            ,
	[Service Order HUB Last Time In Archived]             ,
	[ETL_SRC_SYS_CD]                                      ,
	[ETL_EFFECTV_BEGIN_DATE]                              ,
	[ETL_EFFECTV_END_DATE]                                ,
	[ETL_CURR_RCD_IND]                                    ,
	[ETL_CREATED_TS]                                      ,
	[ETL_UPDTD_TS]                                        ,
	[Service Order HUB Webstatus Description]             ,
	[Service Order Done Date]                             ,
	[Service Order Invoice Create Date]                   ,
	[Service Order Production Complete Date]			  ,
	[Service Order Waiting on Client PO Date]			  ,
	[Service Order Billing In Progress Date]			  ,
	[Service Order Released To Invoicing Date]			  ,
	[Service Order Last Changed By]                       ,
	[Service Order Change Date]                           ,
	[Service Order Entered By]                            ,
	[Service Order Additional Device Data]                ,
	[Service Order Assembly]                              ,
	[Service Order ILOA Individual]                       ,
	[Service Order Priority]                              ,
	[Service Order Priority Type]                         ,
	[Service Order Reason Code]                           ,
	[Service Order Reason for Change]                     ,
	[Service Order Description of Change]                 ,
	[Service Order Error Caught By]                       ,
	[Service Order Error Description]                     ,
	[Service Order Error Origin]                          ,
	[Service Order Error Severity]                        ,
	[Service Order Error Type]                            ,
	[Service Order Requested By]                          ,
	[Service Order Controlling Area]                      ,
	[Service Order Equity Type]                           ,
	[Service Order WBS Element]                           ,
	[Service Order Job Status]                            ,
	[Service Order System Status]                         ,
	[Service Order Type Description]                      ,
	[Service Order Category Description]                  ,
	[Service Order Company Description]                   ,
	[Service Order Plant Description]                     ,
	[Service Order Location Plant Description]            ,
	[Service Order Maintenance Plant Description]         ,
	[Service Order Document Currency Description]         ,
	[Service Order Object Class Description]              ,
	[Service Order Task List Type Description]            ,
	[Service Order Planning Plant Description]            ,
	[Service Order Work Center Description]               ,
	[Service Order Maintenance Activity Type Description] ,
	[Service Order Active Date]                           ,
	[Service Order On Hold Date]                          ,
	[Service Order Intercompany Date]                     ,
	[Service Order Out For Appproval Date]                ,
	[Service Order Closed Date]                           ,
	[Service Order Post Approval Production Date]         ,
	[Service Order Active Artwork Date]                   ,
	[Service Order Active Prepress Date]                  ,
	[Service Order Priority Type Description]             ,
	[Service Order Controlling Area Description]          ,
	[Service Order Equity Type Description]               ,
	[Service Order Created On Date]                       ,
	[Service Order Accountng Indicator Customer]          ,
	[Service Order Accountng Indicator Customer Description]
    )
    SELECT
        S.[SERVC_ORDER_KEY],
        S.[SERVC_ORDER],
        S.[OPERATION_TASK_LIST_ID],
        S.[ORDER_TYP],
        S.[ORDER_CTGRY],
        S.[CMPNY_CD],
        S.[PLNT],
        S.[LOC_PLNT],
        S.[MAINTENANCE_PLNT],
        S.[DOCMT_CRNCY],
        S.[MAINTENANCE_WRK_CNTR],
        S.[FUNCTNL_AREA],
        S.[OBJ_CLASS],
        S.[ESTD_TOTAL_COSTS_OF_ORDER],
        S.[DESC],
        S.[IS_CREATED],
        S.[IS_RELSD],
        S.[IS_COMPLETED],
        S.[IS_CLSD],
        S.[RELS_DATE],
        S.[TCHNCL_COMPLETION_DATE],
        S.[CLS_DATE],
        S.[DELETION_FLG],
        S.[OBJ_NUM],
        S.[RESPNSBLE_COST_CNTR],
        S.[PROFT_CNTR],
        S.[BASIC_START_DATE],
        S.[BASIC_FINISH_DATE],
        S.[SCHLD_RELS_DATE],
        S.[SCHLD_FINISH_DATE],
        S.[SCHLD_START_DATE],
        S.[ACTUAL_START_DATE],
        S.[ACTUAL_FINISH_DATE],
        S.[ACTUAL_RELS_DATE],
        S.[PLND_RELS_DATE],
        S.[RESRVTN],
        S.[TOTAL_SCRAP],
        S.[TRGT_QTY],
        S.[TASK_LIST_TYP],
        S.[CAPACITY_REQMNTS_ID],
        S.[EQUIP],
        S.[LOC_ACCT_ASSIGN],
        S.[PLNG_PLNT],
        S.[WRK_CNTR],
        S.[OBJ_LIST],
        S.[MAINTENANCE_ACTIVITY_TYP],
        S.[NOTIFICATION],
        S.[COST_CNTR],
        S.[FUNCTNL_LOC],
        S.[SALES_ORDER],
        S.[SALES_ORDER_ITM_NUM],
        S.[CNT_OF_ROUNDS],
        S.[CNT_OF_REWORK_INTERNL],
        S.[HUB_PROD_DEADLINE],
        S.[HUB_APPROVAL_LOOP_DEADLINE],
        S.[HUB_CHG_REQUEST_DEADLINE],
        S.[HUB_FINISH_DATE_DEADLINE],
        S.[HUB_NUM_OF_LOOPS],
        S.[HUB_WEBSTATUS],
        S.[HUB_FIRST_TM_IN_PREP_FOR_PROD],
        S.[HUB_LAST_TM_IN_PREP_FOR_PROD],
        S.[HUB_FIRST_TM_IN_PROD],
        S.[HUB_LAST_TM_IN_PROD],
        S.[HUB_FIRST_TM_IN_OUT_FOR_APPROVA],
        S.[HUB_LAST_TM_IN_OUT_FOR_APPROVAL],
        S.[HUB_FIRST_TM_IN_APPROVAL_LOOP],
        S.[HUB_LAST_TM_IN_APPROVAL_LOOP],
        S.[HUB_FIRST_TM_IN_CHG_REQUEST],
        S.[HUB_LAST_TM_IN_CHG_REQUEST],
        S.[HUB_FIRST_TM_IN_APPRVD],
        S.[HUB_LAST_TM_IN_APPRVD],
        S.[HUB_FIRST_TM_IN_FINAL_PROD],
        S.[HUB_LAST_TM_IN_FINAL_PROD],
        S.[HUB_FIRST_TM_IN_PROD_COMPLETED],
        S.[HUB_LAST_TM_IN_PROD_COMPLETED],
        S.[HUB_FIRST_TM_IN_ON_HOLD],
        S.[HUB_LAST_TM_IN_ON_HOLD],
        S.[HUB_FIRST_TM_IN_ARCHIVED],
        S.[HUB_LAST_TM_IN_ARCHIVED],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[HUB_WEBSTATUS_DESC],
        S.[SERVC_ORDER_DONE_DATE],
        S.[INVC_CREATE_DATE],
        S.[PROD_COMPLETE_DATE],
        S.[WAITING_ON_CLNT_PO_DATE],
        S.[BILLING_IN_PROGRESS_DATE],
        S.[RELSD_TO_INVOICING_DATE],
        S.[LAST_CHANGED_BY],
        S.[CHG_DATE],
        S.[ENTERED_BY],
        S.[ADDITIONAL_DEVICE_DATA],
        S.[ASSEMBLY],
        S.[ILOA_INDIVIDUAL],
        S.[PRIORITY],
        S.[PRIORITY_TYP],
        S.[RSN_CD],
        S.[RSN_FOR_CHG],
        S.[DESC_OF_CHG],
        S.[ERR_CAUGHT_BY],
        S.[ERR_DESC],
        S.[ERR_ORIGIN],
        S.[ERR_SEVERITY],
        S.[ERR_TYP],
        S.[REQD_BY],
        S.[CONTROLLING_AREA],
        S.[EQUITY_TYP],
        S.[WBS_ELEMNT],
        S.[SYS_STATUS],
        S.[JOB_STATUS],
        S.[ORDER_TYP_DESC],
        S.[ORDER_CTGRY_DESC],
        S.[CMPNY_DESC],
        S.[PLNT_DESC],
        S.[LOC_PLNT_DESC],
        S.[MAINT_PLNT_DESC],
        S.[DOCMT_CRNCY_DESC],
        S.[OBJ_CLASS_DESC],
        S.[TASK_LIST_TYP_DESC],
        S.[PLNG_PLNT_DESC],
        S.[WRK_CNTR_DESC],
        S.[MAINTENANCE_ACTIVITY_TYP_DESC],
        S.[ACTIVE_DATE],
        S.[ON_HOLD_DATE],
        S.[INTERCOMPANY_DATE],
        S.[OUT_FOR_APPPROVAL_DATE],
        S.[CLSD_DATE],
        S.[POST_APPROVAL_PROD_DATE],
        S.[ACTIVE_ARTWORK_DATE],
        S.[ACTIVE_PREPRESS_DATE],
        S.[PRIORITY_TYP_DESC],
        S.[CONTROLLING_AREA_DESC],
        S.[EQUITY_TYP_DESC],
        S.[CREATED_ON_DATE],
        S.[ACCTNG_IND],
        S.[ACCTNG_IND_DESC]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_PRD_SERVORD_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_PRD_SERVORD_CUR_D] T
        ON T.[SERVC_ORDER_KEY] = S.[SERVC_ORDER_KEY]
    WHERE T.[SERVC_ORDER_KEY] IS NULL;

END