CREATE   PROCEDURE [dbo].[Proc_EDW_T_D_MST_VENDOR_CUR_D]
AS
BEGIN
    UPDATE T
    SET
        T.[Vendor ID]                        = S.[VNDR_ID],
        T.[Vendor Name]                      = S.[VNDR_NAME],
        T.[Vendor Description]               = S.[VNDR_DESC],
        T.[Vendor Account Group]             = S.[VNDR_ACCT_GROUP],
        T.[Vendor Title]                     = S.[TITLE],
        T.[Vendor Search Term]               = S.[SEARCH_TERM],
        T.[Vendor Street]                    = S.[STR],
        T.[Vendor City Name]                 = S.[CITY_NAME],
        T.[Vendor Zip Code]                  = S.[ZIP_CD],
        T.[Vendor Country Code]              = S.[CNTRY_CD],
        T.[Vendor State]                     = S.[ST],
        T.[Vendor Telephone Number 1 Code]   = S.[TEL_NUM_1_CD],
        T.[Vendor Fax Number Code]           = S.[FAX_NUM_CD],
        T.[Vendor Tax Number 1 Code]         = S.[TAX_NUM_1_CD],
        T.[Vendor Tax Number 2 Code]         = S.[TAX_NUM_2_CD],
        T.[Vendor VAT Number Code]           = S.[VAT_NUM_CD],
        T.[Vendor Express Station]           = S.[EXPRESS_STATION],
        T.[Vendor Transportation Zone]       = S.[TRANSTN_ZONE],
        T.[Vendor Industry]                  = S.[INDUS],
        T.[Vendor Created Date]              = S.[CREATED_DATE],
        T.[ETL_SRC_SYS_CD]                                    = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE]                            = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE]                              = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND]                                  = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS]                                    = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS]                                      = S.[ETL_UPDTD_TS],
        T.[Vendor Address Number]            = S.[ADDR_NUM],
        T.[Vendor Account Group Description] = S.[VNDR_ACCT_GROUP_DESC],
        T.[Vendor Country Description]       = S.[CNTRY_DESC],
        T.[Vendor Region Description]        = S.[REGN_DESC],
        T.[Vendor Transportation Zone Description] = S.[TRANSTN_ZONE_DESC],
        T.[Vendor Industry Description]      = S.[INDUS_DESC],
        T.[Vendor Created By]                = S.[CREATED_BY],
        T.[Vendor Central Deletion Indicator] = S.[CENTRAL_DELETION_IND],
        T.[Vendor Central Posting Block]     = S.[CENTRAL_PSTNG_BLK],
        T.[Vendor Central Purchasing Block]  = S.[CENTRAL_PURNG_BLK],
        T.[Vendor Language Key]              = S.[LANG_KEY],
        T.[Vendor Customer ID]               = S.[CUST_ID],
        T.[Vendor One Time Account Indicator]= S.[ONE_TM_ACCT_IND],
        T.[Vendor One Time Account Reference Group] = S.[ONE_TM_ACCT_REF_ACCT__GROUP],
        T.[Vendor One Time Account Reference Group Desc] = S.[ONE_TM_ACC_REF_ACCT_GROUP_DESC],
        T.[Vendor Trading Partner]           = S.[TRADING_PRTNR],
        T.[Vendor Trading Partner Description]= S.[TRADING_PRTNR_DESC],
        T.[Vendor VAT Indicator]             = S.[VAT_IND],
        T.[Vendor Industry Type]             = S.[INDUS_TYP],
        T.[Vendor Business Type]             = S.[BIZ_TYP],
        T.[Vendor Payment Block]             = S.[PYMT_BLK],
        T.[Vendor Tax Jurisdiction]          = S.[TAX_JRSDCTN],
        T.[Vendor Tax Number 3 Code]        = S.[TAX_NUM_3_CD],
        T.[Vendor Tax Number Type]          = S.[TAX_NUM_TYP],
        T.[Vendor Tax Type]                 = S.[TAX_TYP],
        T.[Vendor Level 1]                  = S.[LVL_1],
        T.[Vendor Level 2]                  = S.[LVL_2],
        T.[Vendor Level 3]                  = S.[LVL_3],
        T.[Vendor Level 4]                  = S.[LVL_4],
        T.[Vendor Addressable]              = S.[ADDRESSABLE],
        T.[Tail Vendor]                     = S.[TAIL_VNDR],
        T.[Vendor Normalized]               = S.[NORMALIZED_VNDR],
        T.[Vendor Corporate Group]          = S.[CORPORATE_GROUP],
        T.[Vendor Account No Alternate Payee]= S.[ACCT_NO_ALT_PYE],
        T.[Vendor Email Address]            = S.[E_MAIL_ADDR]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_VENDOR_CUR_D] AS T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_VENDOR_CUR_D] AS S
        ON T.[VNDR_KEY] = S.[VNDR_KEY];

    -- Step 2: Insert new records from mirror into target table
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_MST_VENDOR_CUR_D] (
        [VNDR_KEY],
        [Vendor ID],
        [Vendor Name],
        [Vendor Description],
        [Vendor Account Group],
        [Vendor Title],
        [Vendor Search Term],
        [Vendor Street],
        [Vendor City Name],
        [Vendor Zip Code],
        [Vendor Country Code],
        [Vendor State],
        [Vendor Telephone Number 1 Code],
        [Vendor Fax Number Code],
        [Vendor Tax Number 1 Code],
        [Vendor Tax Number 2 Code],
        [Vendor VAT Number Code],
        [Vendor Express Station],
        [Vendor Transportation Zone],
        [Vendor Industry],
        [Vendor Created Date],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Vendor Address Number],
        [Vendor Account Group Description],
        [Vendor Country Description],
        [Vendor Region Description],
        [Vendor Transportation Zone Description],
        [Vendor Industry Description],
        [Vendor Created By],
        [Vendor Central Deletion Indicator],
        [Vendor Central Posting Block],
        [Vendor Central Purchasing Block],
        [Vendor Language Key],
        [Vendor Customer ID],
        [Vendor One Time Account Indicator],
        [Vendor One Time Account Reference Group],
        [Vendor One Time Account Reference Group Desc],
        [Vendor Trading Partner],
        [Vendor Trading Partner Description],
        [Vendor VAT Indicator],
        [Vendor Industry Type],
        [Vendor Business Type],
        [Vendor Payment Block],
        [Vendor Tax Jurisdiction],
        [Vendor Tax Number 3 Code],
        [Vendor Tax Number Type],
        [Vendor Tax Type],
        [Vendor Level 1],
        [Vendor Level 2],
        [Vendor Level 3],
        [Vendor Level 4],
        [Vendor Addressable],
        [Tail Vendor],
        [Vendor Normalized],
        [Vendor Corporate Group],
        [Vendor Account No Alternate Payee],
        [Vendor Email Address]
    )
    SELECT
        S.[VNDR_KEY],
        S.[VNDR_ID],
        S.[VNDR_NAME],
        S.[VNDR_DESC],
        S.[VNDR_ACCT_GROUP],
        S.[TITLE],
        S.[SEARCH_TERM],
        S.[STR],
        S.[CITY_NAME],
        S.[ZIP_CD],
        S.[CNTRY_CD],
        S.[ST],
        S.[TEL_NUM_1_CD],
        S.[FAX_NUM_CD],
        S.[TAX_NUM_1_CD],
        S.[TAX_NUM_2_CD],
        S.[VAT_NUM_CD],
        S.[EXPRESS_STATION],
        S.[TRANSTN_ZONE],
        S.[INDUS],
        S.[CREATED_DATE],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[ADDR_NUM],
        S.[VNDR_ACCT_GROUP_DESC],
        S.[CNTRY_DESC],
        S.[REGN_DESC],
        S.[TRANSTN_ZONE_DESC],
        S.[INDUS_DESC],
        S.[CREATED_BY],
        S.[CENTRAL_DELETION_IND],
        S.[CENTRAL_PSTNG_BLK],
        S.[CENTRAL_PURNG_BLK],
        S.[LANG_KEY],
        S.[CUST_ID],
        S.[ONE_TM_ACCT_IND],
        S.[ONE_TM_ACCT_REF_ACCT__GROUP],
        S.[ONE_TM_ACC_REF_ACCT_GROUP_DESC],
        S.[TRADING_PRTNR],
        S.[TRADING_PRTNR_DESC],
        S.[VAT_IND],
        S.[INDUS_TYP],
        S.[BIZ_TYP],
        S.[PYMT_BLK],
        S.[TAX_JRSDCTN],
        S.[TAX_NUM_3_CD],
        S.[TAX_NUM_TYP],
        S.[TAX_TYP],
        S.[LVL_1],
        S.[LVL_2],
        S.[LVL_3],
        S.[LVL_4],
        S.[ADDRESSABLE],
        S.[TAIL_VNDR],
        S.[NORMALIZED_VNDR],
        S.[CORPORATE_GROUP],
        S.[ACCT_NO_ALT_PYE],
        S.[E_MAIL_ADDR]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_VENDOR_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_VENDOR_CUR_D] AS T
        ON T.[VNDR_KEY] = S.[VNDR_KEY]
    WHERE T.[VNDR_KEY] IS NULL;

END

EXEC [dbo].[Proc_EDW_T_D_MST_VENDOR_CUR_D];