CREATE       PROCEDURE [dbo].[Proc_EDW_T_D_MST_CUSTCMP_CUR_D]
AS
BEGIN
    UPDATE T
    SET
        T.[CUST_CMPNY_KEY]	= S.[CUST_CMPNY_KEY],
        T.[Customer ID]	= S.[CUST_ID],
        T.[Company Code]	= S.[CMPNY_CD],
        T.[Legacy Customer ID]	= S.[LGCY_CUST_ID],
        T.[Plant ID]	= S.[PLNT_ID],
        T.[Payment Terms Code]	= S.[PYMT_TRMS_CD],
        T.[Payment Block]	= S.[PYMT_BLK],
        T.[Accounting Clerk]	= S.[ACCTNG_CLERK],
        T.[Account At Customer]	= S.[ACCT_AT_CUST],
        T.[Posting Block For Company Code]	= S.[PSTNG_BLK_FOR_CMPNY_CD],
        T.[Deletion Flag For Company Code]	= S.[DELETION_FLG_FOR_CMPNY_CD],
        T.[Recon Account]	= S.[RECON_ACCT],
        T.[Periodic Account Statement Flag]	= S.[PER_ACCT_STMT_FLG],
        T.[Lockbox]	= S.[LOCKBOX],
        T.[Sort Key]	= S.[SRT_KEY],
        T.[Payment Method]	= S.[PYMT__MTHD],
        T.[ETL_SRC_SYS_CD]	= S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE]	= S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE]	= S.[ETL_EFFECTV_END_DATE],
        T.[Current Record Indicator of Customer Company]	= S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS]	= S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS]	= S.[ETL_UPDTD_TS],
        T.[Company Description]	= S.[CMPNY_DESC],
        T.[Payment Terms Description]	= S.[PYMT_TRMS_DESC],
        T.[Plant Description]	= S.[PLNT_DESC],
        T.[Accounting Clerk Description]	= S.[ACCTNG_CLERK_DESC],
        T.[Posting Block Description]	= S.[PSTNG_BLK_DESC],
        T.[Statement Description]	= S.[STMT_DESC],
        T.[Payment Block Description]	= S.[PYMT_BLK_DESC],
        T.[Sort Description]	= S.[SRT_DESC],
        T.[Head Office Account Number]	= S.[HEAD_OFFC_ACCT_NUM],
        T.[Alternative Payer Account Number]	= S.[ALTERNATIVE_PAYER_ACCT_NUM],
        T.[Clearing Between Cust & Vendor Indicator]	= S.[CLEARING_BW_CUST_AND_VNDR_IND],
        T.[Collective Invoice Variant]	= S.[COLLECTIVE_INVC_VARIANT],
        T.[Dunning Notice Grouping Key]	= S.[DUNNING_NOTICE_GROUPING_KEY],
        T.[Dunning Notice Grouping Description]	= S.[DUNNING_NOTICE_GROUPING_DESC],
        T.[Buying Group Account Number]	= S.[BUYING_GROUP_ACCT_NUM],
        T.[Payment Method Description]	= S.[PYMT_MTHD_DESC],
        T.[Created On]	= S.[CREATED_ON],
        T.[Created By]	= S.[CREATED_BY],
        T.[Deletion Block For Master Record]	= S.[DELETION_BOCK_FOR_MAST_RCD],
        T.[Personnel Number]	= S.[PERSONEL_NUM],
        T.[Lockbox Key]	= S.[LOCKBOX_KEY],
        T.[Short Key For A House Bank]	= S.[SHORT_KEY_FOR_A_HOUSE_BANK]

 FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTCMP_CUR_D] AS T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CUSTCMP_CUR_D] AS S
        ON T.[CUST_CMPNY_KEY] = S.[CUST_CMPNY_KEY];

    -- Step 2: Insert new records from mirror into target table
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTCMP_CUR_D] (
        [CUST_CMPNY_KEY],
        [Customer ID],
        [Company Code],
        [Legacy Customer ID],
        [Plant ID],
        [Payment Terms Code],
        [Payment Block],
        [Accounting Clerk],
        [Account At Customer],
        [Posting Block For Company Code],
        [Deletion Flag For Company Code],
        [Recon Account],
        [Periodic Account Statement Flag],
        [Lockbox],
        [Sort Key],
        [Payment Method],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [Current Record Indicator of Customer Company],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Company Description],
        [Payment Terms Description],
        [Plant Description],
        [Accounting Clerk Description],
        [Posting Block Description],
        [Statement Description],
        [Payment Block Description],
        [Sort Description],
        [Head Office Account Number],
        [Alternative Payer Account Number],
        [Clearing Between Cust & Vendor Indicator],
        [Collective Invoice Variant],
        [Dunning Notice Grouping Key],
        [Dunning Notice Grouping Description],
        [Buying Group Account Number],
        [Payment Method Description],
        [Created On],
        [Created By],
        [Deletion Block For Master Record],
        [Personnel Number],
        [Lockbox Key],
        [Short Key For A House Bank]

)
    SELECT
       S.[CUST_CMPNY_KEY],
       S.[CUST_ID],
       S.[CMPNY_CD],
       S.[LGCY_CUST_ID],
       S.[PLNT_ID],
       S.[PYMT_TRMS_CD],
       S.[PYMT_BLK],
       S.[ACCTNG_CLERK],
       S.[ACCT_AT_CUST],
       S.[PSTNG_BLK_FOR_CMPNY_CD],
       S.[DELETION_FLG_FOR_CMPNY_CD],
       S.[RECON_ACCT],
       S.[PER_ACCT_STMT_FLG],
       S.[LOCKBOX],
       S.[SRT_KEY],
       S.[PYMT__MTHD],
       S.[ETL_SRC_SYS_CD],
       S.[ETL_EFFECTV_BEGIN_DATE],
       S.[ETL_EFFECTV_END_DATE],
       S.[ETL_CURR_RCD_IND],
       S.[ETL_CREATED_TS],
       S.[ETL_UPDTD_TS],
       S.[CMPNY_DESC],
       S.[PYMT_TRMS_DESC],
       S.[PLNT_DESC],
       S.[ACCTNG_CLERK_DESC],
       S.[PSTNG_BLK_DESC],
       S.[STMT_DESC],
       S.[PYMT_BLK_DESC],
       S.[SRT_DESC],
       S.[HEAD_OFFC_ACCT_NUM],
       S.[ALTERNATIVE_PAYER_ACCT_NUM],
       S.[CLEARING_BW_CUST_AND_VNDR_IND],
       S.[COLLECTIVE_INVC_VARIANT],
       S.[DUNNING_NOTICE_GROUPING_KEY],
       S.[DUNNING_NOTICE_GROUPING_DESC],
       S.[BUYING_GROUP_ACCT_NUM],
       S.[PYMT_MTHD_DESC],
       S.[CREATED_ON],
       S.[CREATED_BY],
       S.[DELETION_BOCK_FOR_MAST_RCD],
       S.[PERSONEL_NUM],
       S.[LOCKBOX_KEY],
       S.[SHORT_KEY_FOR_A_HOUSE_BANK]

	FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CUSTCMP_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTCMP_CUR_D] AS T
        ON T.[CUST_CMPNY_KEY] = S.[CUST_CMPNY_KEY]
    WHERE T.[CUST_CMPNY_KEY] IS NULL;

END