CREATE       PROCEDURE [dbo].[Proc_EDW_T_D_SAL_PRDVCON_CUR_D]
AS
BEGIN
    
    UPDATE T
    SET
	
	T.[PRDT_VARIANT_CONFIG_KEY]  		 						=  S.[PRDT_VARIANT_CONFIG_KEY] 			,
	T.[SALES_ORDER_ID]                                          =  S.[SALES_ORDER_ID] 					,
	T.[SALES_ORDER_ITM_ID]                                      =  S.[SALES_ORDER_ITM_ID] 				,
	T.[ZLP BB Reference Job]                                    =  S.[ZLP_BB_REF_JOB] 					,
    T.[ZLP AV Reference Job Number]                             =  S.[ZLP_AV_REF_JOB_NR] 				    ,
	T.[ZLP BB Adapt From]                                       =  S.[ZLP_BB_ADAPT_FROM] 				    ,
    T.[ZLP CAD F Previous Job Number]                           =  S.[ZLP_CAD_F_PREV_JOB_NO] 			    ,
    T.[ZLP AG Reference Job]                                    =  S.[ZLP_AG_REF_JOB] 					,
    T.[ZLP BB Version]                                          =  S.[ZLP_BB_VRSN] 						,
    T.[ZLP AG Project]                                          =  S.[ZLP_AG_PROJ] 						,
    T.[G Separation ID]                                         =  S.[G_SEPARATION_ID] 					,
    T.[G Emboss Rework]                                         =  S.[G_EMBOSS_REWORK] 					,
    T.[G Chrome Thickness]                                      =  S.[G_CHROME_THICKNESS] 				,
    T.[G Emboss Double Height]                                  =  S.[G_EMBOSS_DOUBLE_HGHT] 				,
    T.[G SE Drawing Number]                                     =  S.[G_SE_DRAW_NUM] 					    ,
    T.[G Incoming Cylinder Number]                              =  S.[G_INCOMING_CYL_NR] 				    ,
    T.[G Leaving Cylinder Number]                               =  S.[G_LEAVING_CYL_NR] 					,
    T.[G Bombage]                                               =  S.[G_BOMBAGE] 						    ,
    T.[G Copper Diameter]                                       =  S.[G_COPPER_DIAMETER] 				    ,
    T.[G Copper Radius]                                         =  S.[G_COPPER_RADIUS] 					,
    T.[G Lower Tolerance]                                       =  S.[G_LOWER_TOLERANCE] 				    ,
    T.[G Upper Tolerance]                                       =  S.[G_UPPER_TOLERANCE] 				    ,
    T.[G Copper Thickness]                                      =  S.[G_COPPER_THICKNESS] 				,
    T.[G Extra Copper Work]                                     =  S.[G_EXTRA_COPPER_WRK] 				,
    T.[G Finishing]                                             =  S.[G_FINISHING] 						,
    T.[G Grinding Finishing]                                    =  S.[G_GRINDING_FINISHING] 				,
    T.[G Emboss Hardening]                                      =  S.[G_EMBOSS_HARDENING] 				,
    T.[G Coating]                                               =  S.[G_COATING] 						    ,
    T.[G Emboss Bearings]                                       =  S.[G_EMBOSS_BEARINGS] 				    ,
    T.[G Inbnd Cylinder]                                        =  S.[G_INBND_CYLINDER] 					,
    T.[G Finishing 2]                                           =  S.[G_FINISHING2] 						,
    T.[G Emboss Mat Thickness]                                  =  S.[G_EMBOSS_MAT_THICKNESS] 			,
    T.[G Emboss Dehydrathe]                                     =  S.[G_EMBOSS_DEHYDRATHE] 				,
    T.[G Grinding In Steel]                                     =  S.[G_GRINDING_IN_STEEL] 				,
    T.[G Ctrl Classtatu]                                        =  S.[G_CTRL_CLASSTATU] 					,
    T.[G Imaging Material]                                      =  S.[G_IMAGING_MATRL] 					,
    T.[G Engraving Width]                                       =  S.[G_ENGRAVING_WIDTH] 				    ,
    T.[GT Nickel Type]                                          =  S.[GT_NICKEL_TYP] 					    ,
    T.[G Emboss Blasting]                                       =  S.[G_EMBOSS_BLASTING] 				    ,
    T.[G DFF Work Guideline]                                    =  S.[G_DFF_WRK_GDLN] 					,
    T.[GT 3D Coating]                                           =  S.[GT_3D_COATING] 					    ,
    T.[Document Version]                                        =  S.[DOC_VRSN] 							,
    T.[Encoway Document Number]                                 =  S.[ENCO_DOC_NUM] 						,
    T.[Encoway Document Version]                                =  S.[ENCO_DOC_VRSN] 					    ,
    T.[Document Number]                                         =  S.[DOC_NUM] 							,
    T.[G Separation DESC]                                       =  S.[G_SEPARATION_DESC] 				    ,
    T.[G Repro Source]                                          =  S.[G_REPRO_SRC] 						,
    T.[G Repro Class]                                           =  S.[G_REPRO_CLASS] 					    ,
    T.[G Face Width]                                            =  S.[G_FACE_WIDTH] 						,
    T.[G Final Diameter]                                        =  S.[G_FINAL_DIAMETER] 					,
    T.[G Circumference Change]                                  =  S.[G_CIRCUM_CHG] 						,
    T.[G Number of Multiple Engravings]                         =  S.[G_NR_MULT_ENGRAVING] 				,
    T.[G Cylinder Conditions]                                   =  S.[G_CYLINDER_CONDITIONS] 			    ,
    T.[G Repro Rework]                                          =  S.[G_REPRO_REWORK] 					,
    T.[G Repro Team]                                            =  S.[G_REPRO_TEAM] 						,
    T.[G ROTO Technology]                                       =  S.[G_ROTO_TECHNOLOGY] 				    ,
    T.[G Repro Composition]                                     =  S.[G_REPRO_COMPOSITION] 				,
    T.[G Brandowner]                                            =  S.[G_BRANDOWNER] 						,
    T.[G Cylinder Type]                                         =  S.[G_CYLINDER_TYP] 					,
    T.[G Axial Width]                                           =  S.[G_AXIAL_WIDTH] 					    ,
    T.[G Business Unit]                                         =  S.[G_BIZ_UNIT] 						,
    T.[G Position Number]                                       =  S.[G_POSITION_NUM] 					,
    T.[Batch Class]                                             =  S.[BATCH_CLASS] 						,
    T.[G Original Diameter]                                     =  S.[G_ORIG_DIAMETER] 					,
    T.[G Original Wall Thickness]                               =  S.[G_ORIG_WALL_THICKNESS] 			    ,
    T.[G Original Copper Layer]                                 =  S.[G_ORIG_COPPER_LAYER] 				,
    T.[G Original Steelbase Order]                              =  S.[G_ORIG_STEELBASE_ORDER] 			,
    T.[G Original Engraving Surface]                            =  S.[G_ORIG_ENGR_SURFACE] 				,
    T.[G Original Cylinder Surface]                             =  S.[G_ORIG_CYL_SURFACE] 				,
    T.[G Original Threads]                                      =  S.[G_ORIG_THREADS] 					,
    T.[G Printing Circumference]                                =  S.[G_PRINTING_CIRCUM] 				    ,
    T.[G Engraving Type]                                        =  S.[G_ENGRAVING_TYP] 					,
    T.[ETL_SRC_SYS_CD]                                          =  S.[ETL_SRC_SYS_CD] 					,
    T.[ETL_EFFECTV_BEGIN_DATE]                                  =  S.[ETL_EFFECTV_BEGIN_DATE] 			,
    T.[ETL_EFFECTV_END_DATE]                                    =  S.[ETL_EFFECTV_END_DATE] 				,
    T.[ETL_CURR_RCD_IND]                                        =  S.[ETL_CURR_RCD_IND] 					,
    T.[ETL_CREATED_TS]                                          =  S.[ETL_CREATED_TS] 					,
    T.[ETL_UPDTD_TS]                                            =  S.[ETL_UPDTD_TS] 						,
    T.[ZLP BB Reference Job Description]                        =  S.[ZLP_BB_REF_JOB_DESC] 				,
    T.[ZLP AV Reference Job Number Description]                 =  S.[ZLP_AV_REF_JOB_NR_DESC] 			,
    T.[ZLP BB Adapt From Description]                           =  S.[ZLP_BB_ADAPT_FROM_DESC] 			,
    T.[ZLP CAD F Previous Job Number Description]               =  S.[ZLP_CAD_F_PREV_JOB_NO_DESC] 		,
    T.[ZLP AG Reference Job Description]                        =  S.[ZLP_AG_REF_JOB_DESC] 				,
    T.[ZLP BB Version Description]                              =  S.[ZLP_BB_VRSN_DESC] 					,
    T.[ZLP AG Project Description]                              =  S.[ZLP_AG_PROJ_DESC] 					,
    T.[G Separation ID Description]                             =  S.[G_SEPARATION_ID_DESC] 				,
    T.[G Emboss Rework Description]                             =  S.[G_EMBOSS_REWORK_DESC] 				,
    T.[G Chrome Thickness Description]                          =  S.[G_CHROME_THICKNESS_DESC] 			,
    T.[G Emboss Double Height Description]                      =  S.[G_EMBOSS_DOUBLE_HGHT_DESC] 		    ,
    T.[G SE Draw Number Description]                            =  S.[G_SE_DRAW_NUM_DESC] 				,
    T.[G Incoming Cylinder Number Description]                  =  S.[G_INCOMING_CYL_NR_DESC] 			,
    T.[G Leaving Cylinder Number Description]                   =  S.[G_LEAVING_CYL_NR_DESC] 			    ,
    T.[G Bombage Description]                                   =  S.[G_BOMBAGE_DESC] 					,
    T.[G Copper Diameter Description]                           =  S.[G_COPPER_DIAMETER_DESC] 			,
    T.[G Copper Radius Description]                             =  S.[G_COPPER_RADIUS_DESC] 				,
    T.[G Lower Tolerance Description]                           =  S.[G_LOWER_TOLERANCE_DESC] 			,
    T.[G Upper Tolerance Description]                           =  S.[G_UPPER_TOLERANCE_DESC] 			,
    T.[G Copper Thickness Description]                          =  S.[G_COPPER_THICKNESS_DESC] 			,
    T.[G Extra Copper Work Description]                         =  S.[G_EXTRA_COPPER_WRK_DESC] 			,
    T.[G Finishing Description]                                 =  S.[G_FINISHING_DESC] 					,
    T.[G Grinding Finishing Description]                        =  S.[G_GRINDING_FINISHING_DESC] 		    ,
    T.[G Emboss Hardening Description]                          =  S.[G_EMBOSS_HARDENING_DESC] 			,
    T.[G Coating Description]                                   =  S.[G_COATING_DESC] 					,
    T.[G Emboss Bearings Description]                           =  S.[G_EMBOSS_BEARINGS_DESC] 			,
    T.[G Inbnd Cylinder Description]                            =  S.[G_INBND_CYLINDER_DESC] 			    ,
    T.[G Finishing 2 Description]                               =  S.[G_FINISHING2_DESC] 				    ,
    T.[G Emboss Mat Thickness Description]                      =  S.[G_EMBOSS_MAT_THICKNESS_DESC] 		,
    T.[G Emboss Dehydrathe Description]                         =  S.[G_EMBOSS_DEHYDRATHE_DESC] 			,
    T.[G Grinding In Steel Description]                         =  S.[G_GRINDING_IN_STEEL_DESC] 			,
    T.[G Ctrl Classtatu Description]                            =  S.[G_CTRL_CLASSTATU_DESC] 			    ,
    T.[G Imaging Material Description]                          =  S.[G_IMAGING_MATRL_DESC] 				,
    T.[G Engraving Width Description]                           =  S.[G_ENGRAVING_WIDTH_DESC] 			,
    T.[GT Nickel Type Description]                              =  S.[GT_NICKEL_TYP_DESC] 				,
    T.[G Emboss Blasting Description]                           =  S.[G_EMBOSS_BLASTING_DESC] 			,
    T.[G DFF Work Guideline Description]                        =  S.[G_DFF_WRK_GDLN_DESC] 				,
    T.[GT 3D Coating Description]                               =  S.[GT_3D_COATING_DESC] 				,
    T.[Document Version Description]                            =  S.[DOC_VRSN_DESC] 					    ,
    T.[Encoway Document Number Description]                     =  S.[ENCO_DOC_NUM_DESC] 				    ,
    T.[Encoway Document Version Description]                    =  S.[ENCO_DOC_VRSN_DESC] 				,
    T.[Document Number Description]                             =  S.[DOC_NUM_DESC] 						,
    T.[G Separation DESC Description]                           =  S.[G_SEPARATION_DESC_DESC] 			,
    T.[G Repro Source Description]                              =  S.[G_REPRO_SRC_DESC] 					,
    T.[G Repro Class Description]                               =  S.[G_REPRO_CLASS_DESC] 				,
    T.[G Face Width Description]                                =  S.[G_FACE_WIDTH_DESC] 				    ,
    T.[G Final Diameter Description]                            =  S.[G_FINAL_DIAMETER_DESC] 			    ,
    T.[G Circumference Change Description]                      =  S.[G_CIRCUM_CHG_DESC] 				    ,
    T.[G Number of Multiple Engravings Description]             =  S.[G_NR_MULT_ENGRAVING_DESC] 			,
    T.[G Cylinder Conditions Description]                       =  S.[G_CYLINDER_CONDITIONS_DESC] 		,
    T.[G Repro Rework Description]                              =  S.[G_REPRO_REWORK_DESC] 				,
    T.[G Repro Team Description]                                =  S.[G_REPRO_TEAM_DESC] 				    ,
    T.[G ROTO Technology Description]                           =  S.[G_ROTO_TECHNOLOGY_DESC] 			,
	T.[G Repro Composition Description]                         =  S.[G_REPRO_COMPOSITION_DESC] 			,
	T.[G Brandowner Description]                                =  S.[G_BRANDOWNER_DESC] 				    ,
	T.[G Cylinder Type Description]                             =  S.[G_CYLINDER_TYP_DESC] 				,
	T.[G Axial Width Description]                               =  S.[G_AXIAL_WIDTH_DESC] 				,
	T.[G Business Unit Description]                             =  S.[G_BIZ_UNIT_DESC] 					,
	T.[G Position Number Description]                           =  S.[G_POSITION_NUM_DESC] 				,
	T.[Batch Class Description]                                 =  S.[BATCH_CLASS_DESC] 					,
	T.[G Original Diameter Description]                         =  S.[G_ORIG_DIAMETER_DESC] 				,
	T.[G Original Wall Thickness Description]                   =  S.[G_ORIG_WALL_THICKNESS_DESC] 		,
	T.[G Original Copper Layer Description]                     =  S.[G_ORIG_COPPER_LAYER_DESC] 			,
	T.[G Original Steelbase Order Description]                  =  S.[G_ORIG_STEELBASE_ORDER_DESC] 		,
	T.[G Original Engraving Surface Description]                =  S.[G_ORIG_ENGR_SURFACE_DESC] 			,
	T.[G Original Cylinder Surface Description]                 =  S.[G_ORIG_CYL_SURFACE_DESC] 			,
	T.[G Original Threads Description]                          =  S.[G_ORIG_THREADS_DESC] 				,
	T.[G Printing Circumference Description]                    =  S.[G_PRINTING_CIRCUM_DESC] 			,
	T.[G Engraving Type Description]                            =  S.[G_ENGRAVING_TYP_DESC] 				,
	T.[ZLP Customer Specific Field Label 01]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_01] 			,
	T.[ZLP Customer Specific Field Label 02]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_02] 			,
	T.[ZLP Customer Specific Field Label 03]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_03] 			,
	T.[ZLP Customer Specific Field Label 04]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_04] 			,
	T.[ZLP Customer Specific Field Label 05]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_05] 			,
	T.[ZLP Customer Specific Field Label 06]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_06] 			,
	T.[ZLP Customer Specific Field Label 07]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_07] 			,
	T.[ZLP Customer Specific Field Label 08]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_08] 			,
	T.[ZLP Customer Specific Field Label 09]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_09] 			,
	T.[ZLP Customer Specific Field Label 10]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_10] 			,
	T.[ZLP Customer Specific Field Label 11]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_11] 			,
	T.[ZLP Customer Specific Field Label 12]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_12] 			,
	T.[ZLP Customer Specific Field Label 13]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_13] 			,
	T.[ZLP Customer Specific Field Label 14]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_14] 			,
	T.[ZLP Customer Specific Field Label 15]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_15] 			,
	T.[ZLP Customer Specific Field Label 16]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_16] 			,
	T.[ZLP Customer Specific Field Label 17]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_17] 			,
	T.[ZLP Customer Specific Field Label 18]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_18] 			,
	T.[ZLP Customer Specific Field Label 19]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_19] 			,
	T.[ZLP Customer Specific Field Label 20]                    =  S.[ZLP_CUST_SPEC_FLD_LBL_20] 			,
	T.[ZLP Customer Specific Field Label 01 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_01_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 02 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_02_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 03 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_03_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 04 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_04_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 05 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_05_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 06 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_06_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 07 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_07_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 08 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_08_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 09 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_09_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 10 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_10_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 11 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_11_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 12 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_12_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 13 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_13_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 14 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_14_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 15 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_15_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 16 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_16_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 17 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_17_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 18 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_18_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 19 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_19_DESC] 	    ,
	T.[ZLP Customer Specific Field Label 20 Description]        =  S.[ZLP_CUST_SPEC_FLD_LBL_20_DESC] 	    ,
	T.[GT Screen Circumference]                                 =  S.[GT_SCREEN_CIRCUM] 					,
	T.[GT Screen Length]                                        =  S.[GT_SCREEN_LNGTH] 					,
	T.[G Plate Length]                                          =  S.[G_PLATE_LNGTH] 					    ,
	T.[G Plate Width]                                           =  S.[G_PLATE_WIDTH] 					    ,
	T.[G Emboss Depth]                                          =  S.[G_EMBOSS_DEPTH] 					,
	T.[GT C Nickel Plating]                                     =  S.[GT_C_NICKEL_PLATING] 				,
	T.[G Emboss Steps]                                          =  S.[G_EMBOSS_STEPS] 					,
	T.[GT Screen Circumference Description]                     =  S.[GT_SCREEN_CIRCUM_DESC] 			    ,
	T.[GT Screen Length Description]                            =  S.[GT_SCREEN_LNGTH_DESC] 				,
	T.[G Plate Length Description]                              =  S.[G_PLATE_LNGTH_DESC] 				,
	T.[G Plate Width Description]                               =  S.[G_PLATE_WIDTH_DESC] 				,
	T.[G Emboss Depth Description]                              =  S.[G_EMBOSS_DEPTH_DESC] 				,
	T.[GT C Nickel Plating Description]                         =  S.[GT_C_NICKEL_PLATING_DESC] 			,
	T.[GT Wall Thickness Description]                           =  S.[GT_WALL_THICKNESS_DESC] 			,
	T.[G Emboss Steps Description]                              =  S.[G_EMBOSS_STEPS_DESC] 				,
	T.[GT Wall Thickness]                                       =  S.[GT_WALL_THICKNESS] 				    ,
	T.[G Engraving Methode]                                     =  S.[G_ENGRAVING_METHODE] 				,
	T.[G Laser Type]                                            =  S.[G_LASER_TYP] 						,
	T.[G Engraving Methode Description]                         =  S.[G_ENGRAVING_METHODE_DESC] 			,
	T.[G Laser Type Description]                                =  S.[G_LASER_TYP_DESC] 					,
	T.[G Estimated Cylinder Conditions]                         =  S.[G_EST_CYLINDER_CONDITIONS] 		    ,
	T.[G Estimated Circumference Change]                        =  S.[G_EST_CIRCUM_CHG] 					,
	T.[G Emboss Method]                                         =  S.[G_EMBOSS_MTHD] 					    ,
	T.[G Emboss Material]                                       =  S.[G_EMBOSS_MATRL] 					,
	T.[GT Screen Type]                                          =  S.[GT_SCREEN_TYP] 					    ,
	T.[G Estimated Cylinder Conditions Description]             =  S.[G_EST_CYLINDER_CONDITIONS_DESC] 	,
	T.[G Estimated Circumference Change Description]            =  S.[G_EST_CIRCUM_CHG_DESC] 			    ,
	T.[G Emboss Method Description]                             =  S.[G_EMBOSS_MTHD_DESC] 				,
	T.[G Emboss Material Description]                           =  S.[G_EMBOSS_MATRL_DESC] 				,
	T.[GT Screen Type Description]                              =  S.[GT_SCREEN_TYP_DESC] 				,
	T.[ZLP ANZF VS]                                             =  S.[ZLP_ANZF_VS] 						,
	T.[ZLP ANZF VS Description]                                 =  S.[ZLP_ANZF_VS_DESC] 					,
	T.[G Copper Hardness HV]                                    =  S.[G_COPPER_HARDNESS_HV] 				,
	T.[G Copper Hardness HV Description]                        =  S.[G_COPPER_HARDNESS_HV_DESC] 		    ,
	T.[ZLP BB Color Profile]                                    =  S.[ZLP_BB_COL_PROFILE] 				,
	T.[ZLP BB Color Profile Description]                        =  S.[ZLP_BB_COL_PROFILE_DESC] 			,
	T.[ZLP AG F Color 01]                                       =  S.[ZLP_AG_F_COLR_01] 					,
	T.[ZLP AG F Color 02]                                       =  S.[ZLP_AG_F_COLR_02] 					,
	T.[ZLP AG F Color 03]                                       =  S.[ZLP_AG_F_COLR_03] 					,
	T.[ZLP AG F Color 04]                                       =  S.[ZLP_AG_F_COLR_04] 					,
	T.[ZLP AG F Color 05]                                       =  S.[ZLP_AG_F_COLR_05] 					,
	T.[ZLP AG F Color 06]                                       =  S.[ZLP_AG_F_COLR_06] 					,
	T.[ZLP AG F Color 07]                                       =  S.[ZLP_AG_F_COLR_07] 					,
	T.[ZLP AG F Color 08]                                       =  S.[ZLP_AG_F_COLR_08] 					,
	T.[ZLP AG F Color 09]                                       =  S.[ZLP_AG_F_COLR_09] 					,
	T.[ZLP AG F Color 10]                                       =  S.[ZLP_AG_F_COLR_10] 					,
	T.[ZLP AG F Color 11]                                       =  S.[ZLP_AG_F_COLR_11] 					,
	T.[ZLP AG F Color 12]                                       =  S.[ZLP_AG_F_COLR_12] 					,
	T.[ZLP AG F Color 13]                                       =  S.[ZLP_AG_F_COLR_13] 					,
	T.[ZLP AG F Color 14]                                       =  S.[ZLP_AG_F_COLR_14] 					,
	T.[ZLP AG F Color 15]                                       =  S.[ZLP_AG_F_COLR_15] 					,
	T.[ZLP AG F Color 16]                                       =  S.[ZLP_AG_F_COLR_16] 					,
	T.[ZLP AG F Color 17]                                       =  S.[ZLP_AG_F_COLR_17] 					,
	T.[ZLP AG F Color 18]                                       =  S.[ZLP_AG_F_COLR_18] 					,
	T.[ZLP AG F Color 19]                                       =  S.[ZLP_AG_F_COLR_19] 					,
	T.[ZLP AG F Color 20]                                       =  S.[ZLP_AG_F_COLR_20] 					,
	T.[ZLP AG C Customer Color 01]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_01] 		    ,
	T.[ZLP AG C Customer Color 02]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_02] 		    ,
	T.[ZLP AG C Customer Color 03]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_03] 		    ,
	T.[ZLP AG C Customer Color 04]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_04] 		    ,
	T.[ZLP AG C Customer Color 05]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_05] 		    ,
	T.[ZLP AG C Customer Color 06]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_06] 		    ,
	T.[ZLP AG C Customer Color 07]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_07] 		    ,
	T.[ZLP AG C Customer Color 08]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_08] 		    ,
	T.[ZLP AG C Customer Color 09]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_09] 		    ,
	T.[ZLP AG C Customer Color 10]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_10] 		    ,
	T.[ZLP AG C Customer Color 11]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_11] 		    ,
	T.[ZLP AG C Customer Color 12]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_12] 		    ,
	T.[ZLP AG C Customer Color 13]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_13] 		    ,
	T.[ZLP AG C Customer Color 14]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_14] 		    ,
	T.[ZLP AG C Customer Color 15]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_15] 		    ,
	T.[ZLP AG C Customer Color 16]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_16] 		    ,
	T.[ZLP AG C Customer Color 17]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_17] 		    ,
	T.[ZLP AG C Customer Color 18]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_18] 		    ,
	T.[ZLP AG C Customer Color 19]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_19] 		    ,
	T.[ZLP AG C Customer Color 20]                              =  S.[ZLP_AG_C_CUSTOMERCOLOR_20] 		    ,
	T.[ZLP AG F Color 01 Description]                           =  S.[ZLP_AG_F_COLR_01_DESC] 			    ,
	T.[ZLP AG F Color 02 Description]                           =  S.[ZLP_AG_F_COLR_02_DESC] 			    ,
	T.[ZLP AG F Color 03 Description]                           =  S.[ZLP_AG_F_COLR_03_DESC] 			    ,
	T.[ZLP AG F Color 04 Description]                           =  S.[ZLP_AG_F_COLR_04_DESC] 			    ,
	T.[ZLP AG F Color 05 Description]                           =  S.[ZLP_AG_F_COLR_05_DESC] 			    ,
	T.[ZLP AG F Color 06 Description]                           =  S.[ZLP_AG_F_COLR_06_DESC] 			    ,
	T.[ZLP AG F Color 07 Description]                           =  S.[ZLP_AG_F_COLR_07_DESC] 			    ,
	T.[ZLP AG F Color 08 Description]                           =  S.[ZLP_AG_F_COLR_08_DESC] 			    ,
	T.[ZLP AG F Color 09 Description]                           =  S.[ZLP_AG_F_COLR_09_DESC] 			    ,
	T.[ZLP AG F Color 10 Description]                           =  S.[ZLP_AG_F_COLR_10_DESC] 			    ,
	T.[ZLP AG F Color 11 Description]                           =  S.[ZLP_AG_F_COLR_11_DESC] 			    ,
	T.[ZLP AG F Color 12 Description]                           =  S.[ZLP_AG_F_COLR_12_DESC] 			    ,
	T.[ZLP AG F Color 13 Description]                           =  S.[ZLP_AG_F_COLR_13_DESC] 			    ,
	T.[ZLP AG F Color 14 Description]                           =  S.[ZLP_AG_F_COLR_14_DESC] 			    ,
	T.[ZLP AG F Color 15 Description]                           =  S.[ZLP_AG_F_COLR_15_DESC] 			    ,
	T.[ZLP AG F Color 16 Description]                           =  S.[ZLP_AG_F_COLR_16_DESC] 			    ,
	T.[ZLP AG F Color 17 Description]                           =  S.[ZLP_AG_F_COLR_17_DESC] 			    ,
	T.[ZLP AG F Color 18 Description]                           =  S.[ZLP_AG_F_COLR_18_DESC] 			    ,
	T.[ZLP AG F Color 19 Description]                           =  S.[ZLP_AG_F_COLR_19_DESC] 			    ,
	T.[ZLP AG F Color 20 Description]                           =  S.[ZLP_AG_F_COLR_20_DESC] 			    ,
	T.[ZLP AG C Customer Color 01 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_01_DESC] 	,
	T.[ZLP AG C Customer Color 02 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_02_DESC] 	,
	T.[ZLP AG C Customer Color 03 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_03_DESC] 	,
	T.[ZLP AG C Customer Color 04 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_04_DESC] 	,
	T.[ZLP AG C Customer Color 05 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_05_DESC] 	,
	T.[ZLP AG C Customer Color 06 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_06_DESC] 	,
	T.[ZLP AG C Customer Color 07 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_07_DESC] 	,
	T.[ZLP AG C Customer Color 08 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_08_DESC] 	,
	T.[ZLP AG C Customer Color 09 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_09_DESC] 	,
	T.[ZLP AG C Customer Color 10 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_10_DESC] 	,
	T.[ZLP AG C Customer Color 11 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_11_DESC] 	,
	T.[ZLP AG C Customer Color 12 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_12_DESC] 	,
	T.[ZLP AG C Customer Color 13 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_13_DESC] 	,
	T.[ZLP AG C Customer Color 14 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_14_DESC] 	,
	T.[ZLP AG C Customer Color 15 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_15_DESC] 	,
	T.[ZLP AG C Customer Color 16 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_16_DESC] 	,
	T.[ZLP AG C Customer Color 17 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_17_DESC] 	,
	T.[ZLP AG C Customer Color 18 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_18_DESC] 	,
	T.[ZLP AG C Customer Color 19 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_19_DESC] 	,
	T.[ZLP AG C Customer Color 20 Description]                  =  S.[ZLP_AG_C_CUSTOMERCOLOR_20_DESC] 	,
	T.[ZLP AG F Line Screen 1]                                  =  S.[ZLP_AG_F_LINE_SCREEN_1] 			,
	T.[ZLP AG F Line Screen 2]                                  =  S.[ZLP_AG_F_LINE_SCREEN_2] 			,
	T.[ZLP AG F Line Screen 3]                                  =  S.[ZLP_AG_F_LINE_SCREEN_3] 			,
	T.[ZLP AG F Line Screen 4]                                  =  S.[ZLP_AG_F_LINE_SCREEN_4] 			,
	T.[ZLP AG F Line Screen 5]                                  =  S.[ZLP_AG_F_LINE_SCREEN_5] 			,
	T.[ZLP AG F Line Screen 6]                                  =  S.[ZLP_AG_F_LINE_SCREEN_6] 			,
	T.[ZLP AG F Line Screen 7]                                  =  S.[ZLP_AG_F_LINE_SCREEN_7] 			,
	T.[ZLP AG F Line Screen 8]                                  =  S.[ZLP_AG_F_LINE_SCREEN_8] 			,
	T.[ZLP AG F Line Screen 9]                                  =  S.[ZLP_AG_F_LINE_SCREEN_9] 			,
	T.[ZLP AG F Line Screen 10]                                 =  S.[ZLP_AG_F_LINE_SCREEN_10] 			,
	T.[ZLP AG F Line Screen 11]                                 =  S.[ZLP_AG_F_LINE_SCREEN_11] 			,
	T.[ZLP AG F Line Screen 12]                                 =  S.[ZLP_AG_F_LINE_SCREEN_12] 			,
	T.[ZLP AG F Line Screen 13]                                 =  S.[ZLP_AG_F_LINE_SCREEN_13] 			,
	T.[ZLP AG F Line Screen 14]                                 =  S.[ZLP_AG_F_LINE_SCREEN_14] 			,
	T.[ZLP AG F Line Screen 15]                                 =  S.[ZLP_AG_F_LINE_SCREEN_15] 			,
	T.[ZLP AG F Line Screen 16]                                 =  S.[ZLP_AG_F_LINE_SCREEN_16] 			,
	T.[ZLP AG F Line Screen 17]                                 =  S.[ZLP_AG_F_LINE_SCREEN_17] 			,
	T.[ZLP AG F Line Screen 18]                                 =  S.[ZLP_AG_F_LINE_SCREEN_18] 			,
	T.[ZLP AG F Line Screen 19]                                 =  S.[ZLP_AG_F_LINE_SCREEN_19] 			,
	T.[ZLP AG F Line Screen 20]                                 =  S.[ZLP_AG_F_LINE_SCREEN_20] 			,
	T.[ZLP AG F Line Screen 1 Description]                      =  S.[ZLP_AG_F_LINE_SCREEN_1_DESC] 		,
	T.[ZLP AG F Line Screen 2 Description]                      =  S.[ZLP_AG_F_LINE_SCREEN_2_DESC] 		,
	T.[ZLP AG F Line Screen 3 Description]                      =  S.[ZLP_AG_F_LINE_SCREEN_3_DESC] 		,
	T.[ZLP AG F Line Screen 4 Description]                      =  S.[ZLP_AG_F_LINE_SCREEN_4_DESC] 		,
	T.[ZLP AG F Line Screen 5 Description]                      =  S.[ZLP_AG_F_LINE_SCREEN_5_DESC] 		,
	T.[ZLP AG F Line Screen 6 Description]                      =  S.[ZLP_AG_F_LINE_SCREEN_6_DESC] 		,
	T.[ZLP AG F Line Screen 7 Description]                      =  S.[ZLP_AG_F_LINE_SCREEN_7_DESC] 		,
	T.[ZLP AG F Line Screen 8 Description]                      =  S.[ZLP_AG_F_LINE_SCREEN_8_DESC] 		,
	T.[ZLP AG F Line Screen 9 Description]                      =  S.[ZLP_AG_F_LINE_SCREEN_9_DESC] 		,
	T.[ZLP AG F Line Screen 10 Description]                     =  S.[ZLP_AG_F_LINE_SCREEN_10_DESC] 		,
	T.[ZLP AG F Line Screen 11 Description]                     =  S.[ZLP_AG_F_LINE_SCREEN_11_DESC] 		,
	T.[ZLP AG F Line Screen 12 Description]                     =  S.[ZLP_AG_F_LINE_SCREEN_12_DESC] 		,
	T.[ZLP AG F Line Screen 13 Description]                     =  S.[ZLP_AG_F_LINE_SCREEN_13_DESC] 		,
	T.[ZLP AG F Line Screen 14 Description]                     =  S.[ZLP_AG_F_LINE_SCREEN_14_DESC] 		,
	T.[ZLP AG F Line Screen 15 Description]                     =  S.[ZLP_AG_F_LINE_SCREEN_15_DESC] 		,
	T.[ZLP AG F Line Screen 16 Description]                     =  S.[ZLP_AG_F_LINE_SCREEN_16_DESC] 		,
	T.[ZLP AG F Line Screen 17 Description]                     =  S.[ZLP_AG_F_LINE_SCREEN_17_DESC] 		,
	T.[ZLP AG F Line Screen 18 Description]                     =  S.[ZLP_AG_F_LINE_SCREEN_18_DESC] 		,
	T.[ZLP AG F Line Screen 19 Description]                     =  S.[ZLP_AG_F_LINE_SCREEN_19_DESC] 		,
	T.[ZLP AG F Line Screen 20 Description]                     =  S.[ZLP_AG_F_LINE_SCREEN_20_DESC] 		,
	T.[ZLP Order Type]	                                        =  S.[ZLP_ORDER_TYP] 					    ,
	T.[ZLP Order Type Description]                              =  S.[ZLP_ORDER_TYP_DESC] 				



FROM [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_PRDVCON_CUR_D] T
    INNER JOIN [GLOBAL_EDW].[dbo].[SAL_PRDVCON] S
        ON T.[PRDT_VARIANT_CONFIG_KEY] = S.[PRDT_VARIANT_CONFIG_KEY];

    -- Step 2: Insert new records from [GLOBAL_EDW_MIRROR] to [GLOBAL_EDW] where SEG_KEY does not exist
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_PRDVCON_CUR_D] (
[PRDT_VARIANT_CONFIG_KEY]  								  ,
[SALES_ORDER_ID]                                          ,
[SALES_ORDER_ITM_ID]                                      ,
[ZLP BB Reference Job]                                    ,
[ZLP AV Reference Job Number]                             ,
[ZLP BB Adapt From]                                       ,
[ZLP CAD F Previous Job Number]                           ,
[ZLP AG Reference Job]                                    ,
[ZLP BB Version]                                          ,
[ZLP AG Project]                                          ,
[G Separation ID]                                         ,
[G Emboss Rework]                                         ,
[G Chrome Thickness]                                      ,
[G Emboss Double Height]                                  ,
[G SE Drawing Number]                                     ,
[G Incoming Cylinder Number]                              ,
[G Leaving Cylinder Number]                               ,
[G Bombage]                                               ,
[G Copper Diameter]                                       ,
[G Copper Radius]                                         ,
[G Lower Tolerance]                                       ,
[G Upper Tolerance]                                       ,
[G Copper Thickness]                                      ,
[G Extra Copper Work]                                     ,
[G Finishing]                                             ,
[G Grinding Finishing]                                    ,
[G Emboss Hardening]                                      ,
[G Coating]                                               ,
[G Emboss Bearings]                                       ,
[G Inbnd Cylinder]                                        ,
[G Finishing 2]                                           ,
[G Emboss Mat Thickness]                                  ,
[G Emboss Dehydrathe]                                     ,
[G Grinding In Steel]                                     ,
[G Ctrl Classtatu]                                        ,
[G Imaging Material]                                      ,
[G Engraving Width]                                       ,
[GT Nickel Type]                                          ,
[G Emboss Blasting]                                       ,
[G DFF Work Guideline]                                    ,
[GT 3D Coating]                                           ,
[Document Version]                                        ,
[Encoway Document Number]                                 ,
[Encoway Document Version]                                ,
[Document Number]                                         ,
[G Separation DESC]                                       ,
[G Repro Source]                                          ,
[G Repro Class]                                           ,
[G Face Width]                                            ,
[G Final Diameter]                                        ,
[G Circumference Change]                                  ,
[G Number of Multiple Engravings]                         ,
[G Cylinder Conditions]                                   ,
[G Repro Rework]                                          ,
[G Repro Team]                                            ,
[G ROTO Technology]                                       ,
[G Repro Composition]                                     ,
[G Brandowner]                                            ,
[G Cylinder Type]                                         ,
[G Axial Width]                                           ,
[G Business Unit]                                         ,
[G Position Number]                                       ,
[Batch Class]                                             ,
[G Original Diameter]                                     ,
[G Original Wall Thickness]                               ,
[G Original Copper Layer]                                 ,
[G Original Steelbase Order]                              ,
[G Original Engraving Surface]                            ,
[G Original Cylinder Surface]                             ,
[G Original Threads]                                      ,
[G Printing Circumference]                                ,
[G Engraving Type]                                        ,
[ETL_SRC_SYS_CD]                                          ,
[ETL_EFFECTV_BEGIN_DATE]                                  ,
[ETL_EFFECTV_END_DATE]                                    ,
[ETL_CURR_RCD_IND]                                        ,
[ETL_CREATED_TS]                                          ,
[ETL_UPDTD_TS]                                            ,
[ZLP BB Reference Job Description]                        ,
[ZLP AV Reference Job Number Description]                 ,
[ZLP BB Adapt From Description]                           ,
[ZLP CAD F Previous Job Number Description]               ,
[ZLP AG Reference Job Description]                        ,
[ZLP BB Version Description]                              ,
[ZLP AG Project Description]                              ,
[G Separation ID Description]                             ,
[G Emboss Rework Description]                             ,
[G Chrome Thickness Description]                         ,
[G Emboss Double Height Description]                      ,
[G SE Draw Number Description]                            ,
[G Incoming Cylinder Number Description]                  ,
[G Leaving Cylinder Number Description]                  ,
[G Bombage Description]                                   ,
[G Copper Diameter Description]                           ,
[G Copper Radius Description]                             ,
[G Lower Tolerance Description]                           ,
[G Upper Tolerance Description]                           ,
[G Copper Thickness Description]                         ,
[G Extra Copper Work Description]                         ,
[G Finishing Description]                                 ,
[G Grinding Finishing Description]                       ,
[G Emboss Hardening Description]                          ,
[G Coating Description]                                   ,
[G Emboss Bearings Description]                           ,
[G Inbnd Cylinder Description]                            ,
[G Finishing 2 Description]                               ,
[G Emboss Mat Thickness Description]                      ,
[G Emboss Dehydrathe Description]                         ,
[G Grinding In Steel Description]                         ,
[G Ctrl Classtatu Description]                            ,
[G Imaging Material Description]                          ,
[G Engraving Width Description]                           ,
[GT Nickel Type Description]                              ,
[G Emboss Blasting Description]                           ,
[G DFF Work Guideline Description]                        ,
[GT 3D Coating Description]                               ,
[Document Version Description]                            ,
[Encoway Document Number Description]                     ,
[Encoway Document Version Description]                    ,
[Document Number Description]                             ,
[G Separation DESC Description]                           ,
[G Repro Source Description]                              ,
[G Repro Class Description]                               ,
[G Face Width Description]                                ,
[G Final Diameter Description]                            ,
[G Circumference Change Description]                      ,
[G Number of Multiple Engravings Description]             ,
[G Cylinder Conditions Description]                       ,
[G Repro Rework Description]                              ,
[G Repro Team Description]                                ,
[G ROTO Technology Description]                           ,
[G Repro Composition Description]                         ,
[G Brandowner Description]                                ,
[G Cylinder Type Description]                             ,
[G Axial Width Description]                               ,
[G Business Unit Description]                             ,
[G Position Number Description]                           ,
[Batch Class Description]                                 ,
[G Original Diameter Description]                         ,
[G Original Wall Thickness Description]                   ,
[G Original Copper Layer Description]                     ,
[G Original Steelbase Order Description]                  ,
[G Original Engraving Surface Description]                ,
[G Original Cylinder Surface Description]                 ,
[G Original Threads Description]                          ,
[G Printing Circumference Description]                    ,
[G Engraving Type Description]                            ,
[ZLP Customer Specific Field Label 01]                    ,
[ZLP Customer Specific Field Label 02]                    ,
[ZLP Customer Specific Field Label 03]                    ,
[ZLP Customer Specific Field Label 04]                    ,
[ZLP Customer Specific Field Label 05]                    ,
[ZLP Customer Specific Field Label 06]                    ,
[ZLP Customer Specific Field Label 07]                    ,
[ZLP Customer Specific Field Label 08]                    ,
[ZLP Customer Specific Field Label 09]                    ,
[ZLP Customer Specific Field Label 10]                    ,
[ZLP Customer Specific Field Label 11]                    ,
[ZLP Customer Specific Field Label 12]                    ,
[ZLP Customer Specific Field Label 13]                    ,
[ZLP Customer Specific Field Label 14]                    ,
[ZLP Customer Specific Field Label 15]                    ,
[ZLP Customer Specific Field Label 16]                    ,
[ZLP Customer Specific Field Label 17]                    ,
[ZLP Customer Specific Field Label 18]                    ,
[ZLP Customer Specific Field Label 19]                    ,
[ZLP Customer Specific Field Label 20]                    ,
[ZLP Customer Specific Field Label 01 Description]        ,
[ZLP Customer Specific Field Label 02 Description]        ,
[ZLP Customer Specific Field Label 03 Description]        ,
[ZLP Customer Specific Field Label 04 Description]        ,
[ZLP Customer Specific Field Label 05 Description]        ,
[ZLP Customer Specific Field Label 06 Description]        ,
[ZLP Customer Specific Field Label 07 Description]        ,
[ZLP Customer Specific Field Label 08 Description]        ,
[ZLP Customer Specific Field Label 09 Description]        ,
[ZLP Customer Specific Field Label 10 Description]        ,
[ZLP Customer Specific Field Label 11 Description]        ,
[ZLP Customer Specific Field Label 12 Description]        ,
[ZLP Customer Specific Field Label 13 Description]        ,
[ZLP Customer Specific Field Label 14 Description]        ,
[ZLP Customer Specific Field Label 15 Description]        ,
[ZLP Customer Specific Field Label 16 Description]        ,
[ZLP Customer Specific Field Label 17 Description]        ,
[ZLP Customer Specific Field Label 18 Description]        ,
[ZLP Customer Specific Field Label 19 Description]        ,
[ZLP Customer Specific Field Label 20 Description]        ,
[GT Screen Circumference]                                 ,
[GT Screen Length]                                       ,
[G Plate Length]                                         ,
[G Plate Width]                                           ,
[G Emboss Depth]                                          ,
[GT C Nickel Plating]                                     ,
[G Emboss Steps]                                          ,
[GT Screen Circumference Description]                    ,
[GT Screen Length Description]                           ,
[G Plate Length Description]                              ,
[G Plate Width Description]                               ,
[G Emboss Depth Description]                              ,
[GT C Nickel Plating Description]                         ,
[GT Wall Thickness Description]                           ,
[G Emboss Steps Description]                              ,
[GT Wall Thickness]                                       ,
[G Engraving Methode]                                     ,
[G Laser Type]                                            ,
[G Engraving Methode Description]                         ,
[G Laser Type Description]                                ,
[G Estimated Cylinder Conditions]                         ,
[G Estimated Circumference Change]                        ,
[G Emboss Method]                                         ,
[G Emboss Material]                                       ,
[GT Screen Type]                                          ,
[G Estimated Cylinder Conditions Description]             ,
[G Estimated Circumference Change Description]            ,
[G Emboss Method Description]                             ,
[G Emboss Material Description]                           ,
[GT Screen Type Description]                              ,
[ZLP ANZF VS]                                           ,
[ZLP ANZF VS Description]                                ,
[G Copper Hardness HV]                                   ,
[G Copper Hardness HV Description]                        ,
[ZLP BB Color Profile]                                    ,
[ZLP BB Color Profile Description]                        ,
[ZLP AG F Color 01]                                       ,
[ZLP AG F Color 02]                                       ,
[ZLP AG F Color 03]                                       ,
[ZLP AG F Color 04]                                       ,
[ZLP AG F Color 05]                                       ,
[ZLP AG F Color 06]                                       ,
[ZLP AG F Color 07]                                       ,
[ZLP AG F Color 08]                                       ,
[ZLP AG F Color 09]                                       ,
[ZLP AG F Color 10]                                       ,
[ZLP AG F Color 11]                                       ,
[ZLP AG F Color 12]                                       ,
[ZLP AG F Color 13]                                       ,
[ZLP AG F Color 14]                                       ,
[ZLP AG F Color 15]                                       ,
[ZLP AG F Color 16]                                       ,
[ZLP AG F Color 17]                                       ,
[ZLP AG F Color 18]                                       ,
[ZLP AG F Color 19]                                       ,
[ZLP AG F Color 20]                                       ,
[ZLP AG C Customer Color 01]                              ,
[ZLP AG C Customer Color 02]                              ,
[ZLP AG C Customer Color 03]                              ,
[ZLP AG C Customer Color 04]                              ,
[ZLP AG C Customer Color 05]                              ,
[ZLP AG C Customer Color 06]                              ,
[ZLP AG C Customer Color 07]                              ,
[ZLP AG C Customer Color 08]                              ,
[ZLP AG C Customer Color 09]                              ,
[ZLP AG C Customer Color 10]                              ,
[ZLP AG C Customer Color 11]                              ,
[ZLP AG C Customer Color 12]                              ,
[ZLP AG C Customer Color 13]                              ,
[ZLP AG C Customer Color 14]                              ,
[ZLP AG C Customer Color 15]                              ,
[ZLP AG C Customer Color 16]                              ,
[ZLP AG C Customer Color 17]                              ,
[ZLP AG C Customer Color 18]                              ,
[ZLP AG C Customer Color 19]                              ,
[ZLP AG C Customer Color 20]                              ,
[ZLP AG F Color 01 Description]                           ,
[ZLP AG F Color 02 Description]                           ,
[ZLP AG F Color 03 Description]                           ,
[ZLP AG F Color 04 Description]                           ,
[ZLP AG F Color 05 Description]                           ,
[ZLP AG F Color 06 Description]                           ,
[ZLP AG F Color 07 Description]                           ,
[ZLP AG F Color 08 Description]                           ,
[ZLP AG F Color 09 Description]                           ,
[ZLP AG F Color 10 Description]                           ,
[ZLP AG F Color 11 Description]                           ,
[ZLP AG F Color 12 Description]                           ,
[ZLP AG F Color 13 Description]                           ,
[ZLP AG F Color 14 Description]                           ,
[ZLP AG F Color 15 Description]                           ,
[ZLP AG F Color 16 Description]                           ,
[ZLP AG F Color 17 Description]                           ,
[ZLP AG F Color 18 Description]                           ,
[ZLP AG F Color 19 Description]                           ,
[ZLP AG F Color 20 Description]                           ,
[ZLP AG C Customer Color 01 Description]                  ,
[ZLP AG C Customer Color 02 Description]                  ,
[ZLP AG C Customer Color 03 Description]                  ,
[ZLP AG C Customer Color 04 Description]                  ,
[ZLP AG C Customer Color 05 Description]                  ,
[ZLP AG C Customer Color 06 Description]                  ,
[ZLP AG C Customer Color 07 Description]                  ,
[ZLP AG C Customer Color 08 Description]                  ,
[ZLP AG C Customer Color 09 Description]                  ,
[ZLP AG C Customer Color 10 Description]                  ,
[ZLP AG C Customer Color 11 Description]                  ,
[ZLP AG C Customer Color 12 Description]                  ,
[ZLP AG C Customer Color 13 Description]                  ,
[ZLP AG C Customer Color 14 Description]                  ,
[ZLP AG C Customer Color 15 Description]                  ,
[ZLP AG C Customer Color 16 Description]                  ,
[ZLP AG C Customer Color 17 Description]                  ,
[ZLP AG C Customer Color 18 Description]                  ,
[ZLP AG C Customer Color 19 Description]                  ,
[ZLP AG C Customer Color 20 Description]                  ,
[ZLP AG F Line Screen 1]                                  ,
[ZLP AG F Line Screen 2]                                  ,
[ZLP AG F Line Screen 3]                                  ,
[ZLP AG F Line Screen 4]                                  ,
[ZLP AG F Line Screen 5]                                  ,
[ZLP AG F Line Screen 6]                                  ,
[ZLP AG F Line Screen 7]                                  ,
[ZLP AG F Line Screen 8]                                  ,
[ZLP AG F Line Screen 9]                                  ,
[ZLP AG F Line Screen 10]                                 ,
[ZLP AG F Line Screen 11]                                 ,
[ZLP AG F Line Screen 12]                                 ,
[ZLP AG F Line Screen 13]                                 ,
[ZLP AG F Line Screen 14]                                 ,
[ZLP AG F Line Screen 15]                                 ,
[ZLP AG F Line Screen 16]                                 ,
[ZLP AG F Line Screen 17]                                 ,
[ZLP AG F Line Screen 18]                                 ,
[ZLP AG F Line Screen 19]                                 ,
[ZLP AG F Line Screen 20]                                 ,
[ZLP AG F Line Screen 1 Description]                      ,
[ZLP AG F Line Screen 2 Description]                      ,
[ZLP AG F Line Screen 3 Description]                      ,
[ZLP AG F Line Screen 4 Description]                      ,
[ZLP AG F Line Screen 5 Description]                      ,
[ZLP AG F Line Screen 6 Description]                      ,
[ZLP AG F Line Screen 7 Description]                      ,
[ZLP AG F Line Screen 8 Description]                      ,
[ZLP AG F Line Screen 9 Description]                      ,
[ZLP AG F Line Screen 10 Description]                     ,
[ZLP AG F Line Screen 11 Description]                     ,
[ZLP AG F Line Screen 12 Description]                     ,
[ZLP AG F Line Screen 13 Description]                     ,
[ZLP AG F Line Screen 14 Description]                     ,
[ZLP AG F Line Screen 15 Description]                     ,
[ZLP AG F Line Screen 16 Description]                     ,
[ZLP AG F Line Screen 17 Description]                     ,
[ZLP AG F Line Screen 18 Description]                     ,
[ZLP AG F Line Screen 19 Description]                     ,
[ZLP AG F Line Screen 20 Description]                     ,
[ZLP Order Type]	                                      ,
[ZLP Order Type Description]                              
)
SELECT

	S.[PRDT_VARIANT_CONFIG_KEY] 			,
	S.[SALES_ORDER_ID] 					,
	S.[SALES_ORDER_ITM_ID] 				,
	S.[ZLP_BB_REF_JOB] 					,
	S.[ZLP_AV_REF_JOB_NR] 				,
	S.[ZLP_BB_ADAPT_FROM] 				,
	S.[ZLP_CAD_F_PREV_JOB_NO] 			,
	S.[ZLP_AG_REF_JOB] 					,
	S.[ZLP_BB_VRSN] 						,
	S.[ZLP_AG_PROJ] 						,
	S.[G_SEPARATION_ID] 					,
	S.[G_EMBOSS_REWORK] 					,
	S.[G_CHROME_THICKNESS] 				,
	S.[G_EMBOSS_DOUBLE_HGHT] 				,
	S.[G_SE_DRAW_NUM] 					,
	S.[G_INCOMING_CYL_NR] 				,
	S.[G_LEAVING_CYL_NR] 					,
	S.[G_BOMBAGE] 						,
	S.[G_COPPER_DIAMETER] 				,
	S.[G_COPPER_RADIUS] 					,
	S.[G_LOWER_TOLERANCE] 				,
	S.[G_UPPER_TOLERANCE] 				,
	S.[G_COPPER_THICKNESS] 				,
	S.[G_EXTRA_COPPER_WRK] 				,
	S.[G_FINISHING] 						,
	S.[G_GRINDING_FINISHING] 				,
	S.[G_EMBOSS_HARDENING] 				,
	S.[G_COATING] 						,
	S.[G_EMBOSS_BEARINGS] 				,
	S.[G_INBND_CYLINDER] 					,
	S.[G_FINISHING2] 						,
	S.[G_EMBOSS_MAT_THICKNESS] 			,
	S.[G_EMBOSS_DEHYDRATHE] 				,
	S.[G_GRINDING_IN_STEEL] 				,
	S.[G_CTRL_CLASSTATU] 					,
	S.[G_IMAGING_MATRL] 					,
	S.[G_ENGRAVING_WIDTH] 				,
	S.[GT_NICKEL_TYP] 					,
	S.[G_EMBOSS_BLASTING] 				,
	S.[G_DFF_WRK_GDLN] 					,
	S.[GT_3D_COATING] 					,
	S.[DOC_VRSN] 							,
	S.[ENCO_DOC_NUM] 						,
	S.[ENCO_DOC_VRSN] 					,
	S.[DOC_NUM] 							,
	S.[G_SEPARATION_DESC] 				,
	S.[G_REPRO_SRC] 						,
	S.[G_REPRO_CLASS] 					,
	S.[G_FACE_WIDTH] 						,
	S.[G_FINAL_DIAMETER] 					,
	S.[G_CIRCUM_CHG] 						,
	S.[G_NR_MULT_ENGRAVING] 				,
	S.[G_CYLINDER_CONDITIONS] 			,
	S.[G_REPRO_REWORK] 					,
	S.[G_REPRO_TEAM] 						,
	S.[G_ROTO_TECHNOLOGY] 				,
	S.[G_REPRO_COMPOSITION] 				,
	S.[G_BRANDOWNER] 						,
	S.[G_CYLINDER_TYP] 					,
	S.[G_AXIAL_WIDTH] 					,
	S.[G_BIZ_UNIT] 						,
	S.[G_POSITION_NUM] 					,
	S.[BATCH_CLASS] 						,
	S.[G_ORIG_DIAMETER] 					,
	S.[G_ORIG_WALL_THICKNESS] 			,
	S.[G_ORIG_COPPER_LAYER] 				,
	S.[G_ORIG_STEELBASE_ORDER] 			,
	S.[G_ORIG_ENGR_SURFACE] 				,
	S.[G_ORIG_CYL_SURFACE] 				,
	S.[G_ORIG_THREADS] 					,
	S.[G_PRINTING_CIRCUM] 				,
	S.[G_ENGRAVING_TYP] 					,
	S.[ETL_SRC_SYS_CD] 					,
	S.[ETL_EFFECTV_BEGIN_DATE] 			,
	S.[ETL_EFFECTV_END_DATE] 				,
	S.[ETL_CURR_RCD_IND] 					,
	S.[ETL_CREATED_TS] 					,
	S.[ETL_UPDTD_TS] 						,
	S.[ZLP_BB_REF_JOB_DESC] 				,
	S.[ZLP_AV_REF_JOB_NR_DESC] 			,
	S.[ZLP_BB_ADAPT_FROM_DESC] 			,
	S.[ZLP_CAD_F_PREV_JOB_NO_DESC] 		,
	S.[ZLP_AG_REF_JOB_DESC] 				,
	S.[ZLP_BB_VRSN_DESC] 					,
	S.[ZLP_AG_PROJ_DESC] 					,
	S.[G_SEPARATION_ID_DESC] 				,
	S.[G_EMBOSS_REWORK_DESC] 				,
	S.[G_CHROME_THICKNESS_DESC] 			,
	S.[G_EMBOSS_DOUBLE_HGHT_DESC] 		,
	S.[G_SE_DRAW_NUM_DESC] 				,
	S.[G_INCOMING_CYL_NR_DESC] 			,
	S.[G_LEAVING_CYL_NR_DESC] 			,
	S.[G_BOMBAGE_DESC] 					,
	S.[G_COPPER_DIAMETER_DESC] 			,
	S.[G_COPPER_RADIUS_DESC] 				,
	S.[G_LOWER_TOLERANCE_DESC] 			,
	S.[G_UPPER_TOLERANCE_DESC] 			,
	S.[G_COPPER_THICKNESS_DESC] 			,
	S.[G_EXTRA_COPPER_WRK_DESC] 			,
	S.[G_FINISHING_DESC] 					,
	S.[G_GRINDING_FINISHING_DESC] 		,
	S.[G_EMBOSS_HARDENING_DESC] 			,
	S.[G_COATING_DESC] 					,
	S.[G_EMBOSS_BEARINGS_DESC] 			,
	S.[G_INBND_CYLINDER_DESC] 			,
	S.[G_FINISHING2_DESC] 				,
	S.[G_EMBOSS_MAT_THICKNESS_DESC] 		,
	S.[G_EMBOSS_DEHYDRATHE_DESC] 			,
	S.[G_GRINDING_IN_STEEL_DESC] 			,
	S.[G_CTRL_CLASSTATU_DESC] 			,
	S.[G_IMAGING_MATRL_DESC] 				,
	S.[G_ENGRAVING_WIDTH_DESC] 			,
	S.[GT_NICKEL_TYP_DESC] 				,
	S.[G_EMBOSS_BLASTING_DESC] 			,
	S.[G_DFF_WRK_GDLN_DESC] 				,
	S.[GT_3D_COATING_DESC] 				,
	S.[DOC_VRSN_DESC] 					,
	S.[ENCO_DOC_NUM_DESC] 				,
	S.[ENCO_DOC_VRSN_DESC] 				,
	S.[DOC_NUM_DESC] 						,
	S.[G_SEPARATION_DESC_DESC] 			,
	S.[G_REPRO_SRC_DESC] 					,
	S.[G_REPRO_CLASS_DESC] 				,
	S.[G_FACE_WIDTH_DESC] 				,
	S.[G_FINAL_DIAMETER_DESC] 			,
	S.[G_CIRCUM_CHG_DESC] 				,
	S.[G_NR_MULT_ENGRAVING_DESC] 			,
	S.[G_CYLINDER_CONDITIONS_DESC] 		,
	S.[G_REPRO_REWORK_DESC] 				,
	S.[G_REPRO_TEAM_DESC] 				,
	S.[G_ROTO_TECHNOLOGY_DESC] 			,
	S.[G_REPRO_COMPOSITION_DESC] 			,
	S.[G_BRANDOWNER_DESC] 				,
	S.[G_CYLINDER_TYP_DESC] 				,
	S.[G_AXIAL_WIDTH_DESC] 				,
	S.[G_BIZ_UNIT_DESC] 					,
	S.[G_POSITION_NUM_DESC] 				,
	S.[BATCH_CLASS_DESC] 					,
	S.[G_ORIG_DIAMETER_DESC] 				,
	S.[G_ORIG_WALL_THICKNESS_DESC] 		,
	S.[G_ORIG_COPPER_LAYER_DESC] 			,
	S.[G_ORIG_STEELBASE_ORDER_DESC] 		,
	S.[G_ORIG_ENGR_SURFACE_DESC] 			,
	S.[G_ORIG_CYL_SURFACE_DESC] 			,
	S.[G_ORIG_THREADS_DESC] 				,
	S.[G_PRINTING_CIRCUM_DESC] 			,
	S.[G_ENGRAVING_TYP_DESC] 				,
	S.[ZLP_CUST_SPEC_FLD_LBL_01] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_02] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_03] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_04] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_05] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_06] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_07] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_08] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_09] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_10] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_11] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_12] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_13] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_14] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_15] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_16] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_17] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_18] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_19] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_20] 			,
	S.[ZLP_CUST_SPEC_FLD_LBL_01_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_02_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_03_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_04_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_05_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_06_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_07_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_08_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_09_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_10_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_11_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_12_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_13_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_14_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_15_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_16_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_17_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_18_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_19_DESC] 	,
	S.[ZLP_CUST_SPEC_FLD_LBL_20_DESC] 	,
	S.[GT_SCREEN_CIRCUM] 					,
	S.[GT_SCREEN_LNGTH] 					,
	S.[G_PLATE_LNGTH] 					,
	S.[G_PLATE_WIDTH] 					,
	S.[G_EMBOSS_DEPTH] 					,
	S.[GT_C_NICKEL_PLATING] 				,
	S.[G_EMBOSS_STEPS] 					,
	S.[GT_SCREEN_CIRCUM_DESC] 			,
	S.[GT_SCREEN_LNGTH_DESC] 				,
	S.[G_PLATE_LNGTH_DESC] 				,
	S.[G_PLATE_WIDTH_DESC] 				,
	S.[G_EMBOSS_DEPTH_DESC] 				,
	S.[GT_C_NICKEL_PLATING_DESC] 			,
	S.[GT_WALL_THICKNESS_DESC] 			,
	S.[G_EMBOSS_STEPS_DESC] 				,
	S.[GT_WALL_THICKNESS] 				,
	S.[G_ENGRAVING_METHODE] 				,
	S.[G_LASER_TYP] 						,
	S.[G_ENGRAVING_METHODE_DESC] 			,
	S.[G_LASER_TYP_DESC] 					,
	S.[G_EST_CYLINDER_CONDITIONS] 		,
	S.[G_EST_CIRCUM_CHG] 					,
	S.[G_EMBOSS_MTHD] 					,
	S.[G_EMBOSS_MATRL] 					,
	S.[GT_SCREEN_TYP] 					,
	S.[G_EST_CYLINDER_CONDITIONS_DESC] 	,
	S.[G_EST_CIRCUM_CHG_DESC] 			,
	S.[G_EMBOSS_MTHD_DESC] 				,
	S.[G_EMBOSS_MATRL_DESC] 				,
	S.[GT_SCREEN_TYP_DESC] 				,
	S.[ZLP_ANZF_VS] 						,
	S.[ZLP_ANZF_VS_DESC] 					,
	S.[G_COPPER_HARDNESS_HV] 				,
	S.[G_COPPER_HARDNESS_HV_DESC] 		,
	S.[ZLP_BB_COL_PROFILE] 				,
	S.[ZLP_BB_COL_PROFILE_DESC] 			,
	S.[ZLP_AG_F_COLR_01] 					,
	S.[ZLP_AG_F_COLR_02] 					,
	S.[ZLP_AG_F_COLR_03] 					,
	S.[ZLP_AG_F_COLR_04] 					,
	S.[ZLP_AG_F_COLR_05] 					,
	S.[ZLP_AG_F_COLR_06] 					,
	S.[ZLP_AG_F_COLR_07] 					,
	S.[ZLP_AG_F_COLR_08] 					,
	S.[ZLP_AG_F_COLR_09] 					,
	S.[ZLP_AG_F_COLR_10] 					,
	S.[ZLP_AG_F_COLR_11] 					,
	S.[ZLP_AG_F_COLR_12] 					,
	S.[ZLP_AG_F_COLR_13] 					,
	S.[ZLP_AG_F_COLR_14] 					,
	S.[ZLP_AG_F_COLR_15] 					,
	S.[ZLP_AG_F_COLR_16] 					,
	S.[ZLP_AG_F_COLR_17] 					,
	S.[ZLP_AG_F_COLR_18] 					,
	S.[ZLP_AG_F_COLR_19] 					,
	S.[ZLP_AG_F_COLR_20] 					,
	S.[ZLP_AG_C_CUSTOMERCOLOR_01] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_02] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_03] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_04] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_05] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_06] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_07] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_08] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_09] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_10] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_11] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_12] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_13] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_14] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_15] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_16] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_17] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_18] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_19] 		,
	S.[ZLP_AG_C_CUSTOMERCOLOR_20] 		,
	S.[ZLP_AG_F_COLR_01_DESC] 			,
	S.[ZLP_AG_F_COLR_02_DESC] 			,
	S.[ZLP_AG_F_COLR_03_DESC] 			,
	S.[ZLP_AG_F_COLR_04_DESC] 			,
	S.[ZLP_AG_F_COLR_05_DESC] 			,
	S.[ZLP_AG_F_COLR_06_DESC] 			,
	S.[ZLP_AG_F_COLR_07_DESC] 			,
	S.[ZLP_AG_F_COLR_08_DESC] 			,
	S.[ZLP_AG_F_COLR_09_DESC] 			,
	S.[ZLP_AG_F_COLR_10_DESC] 			,
	S.[ZLP_AG_F_COLR_11_DESC] 			,
	S.[ZLP_AG_F_COLR_12_DESC] 			,
	S.[ZLP_AG_F_COLR_13_DESC] 			,
	S.[ZLP_AG_F_COLR_14_DESC] 			,
	S.[ZLP_AG_F_COLR_15_DESC] 			,
	S.[ZLP_AG_F_COLR_16_DESC] 			,
	S.[ZLP_AG_F_COLR_17_DESC] 			,
	S.[ZLP_AG_F_COLR_18_DESC] 			,
	S.[ZLP_AG_F_COLR_19_DESC] 			,
	S.[ZLP_AG_F_COLR_20_DESC] 			,
	S.[ZLP_AG_C_CUSTOMERCOLOR_01_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_02_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_03_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_04_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_05_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_06_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_07_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_08_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_09_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_10_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_11_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_12_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_13_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_14_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_15_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_16_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_17_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_18_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_19_DESC] 	,
	S.[ZLP_AG_C_CUSTOMERCOLOR_20_DESC] 	,
	S.[ZLP_AG_F_LINE_SCREEN_1] 			,
	S.[ZLP_AG_F_LINE_SCREEN_2] 			,
	S.[ZLP_AG_F_LINE_SCREEN_3] 			,
	S.[ZLP_AG_F_LINE_SCREEN_4] 			,
	S.[ZLP_AG_F_LINE_SCREEN_5] 			,
	S.[ZLP_AG_F_LINE_SCREEN_6] 			,
	S.[ZLP_AG_F_LINE_SCREEN_7] 			,
	S.[ZLP_AG_F_LINE_SCREEN_8] 			,
	S.[ZLP_AG_F_LINE_SCREEN_9] 			,
	S.[ZLP_AG_F_LINE_SCREEN_10] 			,
	S.[ZLP_AG_F_LINE_SCREEN_11] 			,
	S.[ZLP_AG_F_LINE_SCREEN_12] 			,
	S.[ZLP_AG_F_LINE_SCREEN_13] 			,
	S.[ZLP_AG_F_LINE_SCREEN_14] 			,
	S.[ZLP_AG_F_LINE_SCREEN_15] 			,
	S.[ZLP_AG_F_LINE_SCREEN_16] 			,
	S.[ZLP_AG_F_LINE_SCREEN_17] 			,
	S.[ZLP_AG_F_LINE_SCREEN_18] 			,
	S.[ZLP_AG_F_LINE_SCREEN_19] 			,
	S.[ZLP_AG_F_LINE_SCREEN_20] 			,
	S.[ZLP_AG_F_LINE_SCREEN_1_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_2_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_3_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_4_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_5_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_6_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_7_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_8_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_9_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_10_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_11_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_12_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_13_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_14_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_15_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_16_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_17_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_18_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_19_DESC] 		,
	S.[ZLP_AG_F_LINE_SCREEN_20_DESC] 		,
	S.[ZLP_ORDER_TYP] 					,
	S.[ZLP_ORDER_TYP_DESC] 				
FROM [GLOBAL_EDW].[dbo].[SAL_PRDVCON] S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_PRDVCON_CUR_D] T
        ON T.[PRDT_VARIANT_CONFIG_KEY] = S.[PRDT_VARIANT_CONFIG_KEY]
    WHERE T.[PRDT_VARIANT_CONFIG_KEY] IS NULL;

END