CREATE     PROCEDURE [dbo].[Proc_EDW_T_D_PP_PURORDL_CUR_D]
AS
BEGIN  
    ----------------------------------------------------------------------
    -- Update existing records in target table
    ----------------------------------------------------------------------
   
   UPDATE T
SET
    T.[Purchase Order ID] = S.[PURCHS_ORDER_ID],
    T.[Purchase Order Item ID] = S.[PURCHS_ORDER_ITM_ID],
    T.[PO Company Code] = S.[CMPNY_CD],
    T.[PO Purchasing Document Category] = S.[PURCHS_DOCMT_CTGRY],
    T.[PO Purchasing Document Type] = S.[PURCHS_DOCMT_TYP],
    T.[PO Status] = S.[STATUS],
    T.[PO Statistical Date] = S.[STATISTICAL_DATE],
    T.[PO Delivery Date] = S.[DLVRY_DATE],
    T.[PO Created On] = S.[CREATED_ON],
    T.[PO Created By] = S.[CREATED_BY],
    T.[PO Vendor] = S.[VNDR],
    T.[PO Purchasing Organization] = S.[PURCHS_ORGZTN],
    T.[PO Purchasing Group] = S.[PURCHS_GROUP],
    T.[PO Currency] = S.[CRNCY],
    T.[PO Exchange Rate] = S.[EXCHG_RT],
    T.[PO Invoicing Party] = S.[INVOICING_PARTY],
    T.[PO Document Date] = S.[DOCMT_DATE],
    T.[PO Terms Of Payment] = S.[TRMS_OF_PYMT],
    T.[PO Incoterms] = S.[INCOTERMS],
    T.[PO Deletion Indicator] = S.[DELETION_IND],
    T.[PO Short Text] = S.[SHORT_TEXT],
    T.[PO Material] = S.[MATRL],
    T.[PO Material 2] = S.[MATRL_2],
    T.[PO Material Group] = S.[MATRL_GROUP],
    T.[PO Plant] = S.[PLNT],
    T.[PO Storage Location] = S.[STOR_LOC],
    T.[PO Target Quantity] = S.[TRGT_QTY],
    T.[PO Quantity] = S.[ORDER_QTY],
    T.[PO Unit] = S.[ORDER_UNIT],
    T.[PO Net Order Price] = S.[NET_ORDER_PRICE],
    T.[PO Net Order Value] = S.[NET_ORDER_VAL],
    T.[PO Is PO Open] = S.[IS_PURCHS_ORDER_OPEN],
    T.[PO Quantity Open Goods Receipt Total] = S.[QTY_OPEN_GOODS_RCPT_TOTAL],
    T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
    T.[ETL_EFFECTV_BEGIN_DATE] = S.[ETL_EFFECTV_BEGIN_DATE],
    T.[ETL_EFFECTV_END_DATE] = S.[ETL_EFFECTV_END_DATE],
    T.[ETL_CURR_RCD_IND] = S.[ETL_CURR_RCD_IND],
    T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
    T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
    T.[PO Account Assignment Category] = S.[ACCT_ASSIGN_CTGRY],
    T.[PO Account Assignment Category Description] = S.[ACCT_ASSIGN_CTGRY_DESC],
    T.[PO Number of Principal Purchase Agreement] = S.[NUM_OF_PRINCIPAL_PURCHS_AGREEME],
    T.[PO Deletion Indicator in Purchasing Document] = S.[DELETION_IND_IN_PURNG_DOCMT],
    T.[PO Delivery Completed Indicator] = S.[DLVRY_COMPLETED_IND],
    T.[PO Final Invoice Indicator] = S.[FINAL_INVC_IND],
    T.[PO Goods Receipt Non Valuated] = S.[GOODS_RCPT_NON_VALTD],
    T.[PO Indicator GR Based Invoice Verification] = S.[IND_GR_BASED_INVC_VERFTN],
    T.[PO Incoterms Part 1] = S.[INCOTERMS_PART_1],
    T.[PO Incoterms Part 2] = S.[INCOTERMS_PART_2],
    T.[PO Indicator Update Info Record] = S.[IND_UPDT_INFO_RCD],
    T.[PO Period Indicator for Shelf Life Expiration Date] = S.[PER_IND_FOR_SHELF_LIFE_EXPIRATI],
    T.[PO Item Category in Purchasing Document] = S.[ITM_CTGRY_IN_PURNG_DOCMT],
    T.[PO Requisition Number] = S.[PURCHS_REQZ_NUM],
    T.[PO Revision Level] = S.[REVISION_LVL],
    T.[PO Shipping Instructions] = S.[SHIPG_INSTRUCTIONS],
    T.[PO Stock Type] = S.[STK_TYP],
    T.[PO Tax On Sales Purchases Code] = S.[TAX_ON_SALES_PURCHASES_CD],
    T.[PO Material Number Used by Vendor] = S.[MATRL_NUM_USED_BY_VNDR],
    T.[PO Goods Receipt Processing Time in Days] = S.[GOODS_RCPT_PRCSNG_TM_IN_DAYS],
    T.[PO Minimum Remaining Shelf Life] = S.[MIN_REMG_SHELF_LIFE],
    T.[PO Overdelivery Tolerance Limit] = S.[OVERDELIVERY_TOLERANCE_LMT],
    T.[PO Planned Delivery Time in Days] = S.[PLND_DLVRY_TM_IN_DAYS],
    T.[PO Underdelivery Tolerance Limit] = S.[UNDERDELIVERY_TOLERANCE_LMT],
    T.[PO Purchasing Document Processing State] = S.[PURNG_DOCMT_PRCSNG_ST],
    T.[PO International Article Number EAN UPC] = S.[INTERNATIONAL_ARTICLE_NUM_EAN_U],
    T.[PO Goods Receipt Indicator] = S.[GOODS_RCPT_IND],
    T.[PO Invoice Receipt Indicator] = S.[INVC_RCPT_IND],
    T.[PO Order Price Unit Purchasing] = S.[ORDER_PRICE_UNIT_PURNG],
    T.[PO Base Unit Of Measure] = S.[BASE_UNIT_OF_MEASUR],
    T.[PO Name Of Requisitioner Requester] = S.[NAME_OF_REQUISITIONER_REQUESTER],
    T.[PO Change Document Responsible Person] = S.[CHG_DOCMT_RESPNSBLE_PERSON],
    T.[PO Change Document Creation Date] = S.[CHG_DOCMT_CREATION_DATE],
    T.[PO Item Category Description] = S.[ITM_CTGRY_DESC],
    T.[PO Purchasing Document Category Description] = S.[PURNG_DOCMT_CTGRY_DESC],
    T.[PO Purchasing Document Type Description] = S.[PURNG_DOCMT_TYP_DESC],
    T.[PO Purchasing Organization Description] = S.[PURNG_ORGZTN_DESC],
    T.[PO Purchasing Group Description] = S.[PURNG_GROUP_DESC],
    T.[PO Currency Description] = S.[CRNCY_DESC],
    T.[PO Terms of Payment Description] = S.[TRMS_OF_PYMT_DESC],
    T.[PO Incoterms Description] = S.[INCOTERMS_DESC],
    T.[PO Material Group Description] = S.[MATRL_GROUP_DESC],
    T.[PO Plant Description] = S.[PLNT_DESC],
    T.[PO Storage Location Description] = S.[STOR_LOC_DESC],
    T.[PO Incoterms Part 1 Description] = S.[INCOTERMS_PART_1_DESC],
    T.[PO Indicator Update Info Record Description] = S.[IND_UPDT_INFO_RCD_DESC],
    T.[PO Shipping Instructions Description] = S.[SHIPG_INSTRUCTIONS_DESC],
    T.[PO Stock Type Description] = S.[STK_TYP_DESC],
    T.[PO Tax On Sales Purchases Code Description] = S.[TAX_ON_SALES_PURCHASES_CD_DESC],
    T.[PO First Name Of Requester] = S.[FIRST_NAME_OF_REQUESTER],
    T.[PO Last Name Of Requester] = S.[LAST_NAME_OF_REQUESTER],
    T.[PO First Name Of Change Document Responsible] = S.[FIRST_NAME_OF_CHG_DOCMT_RESPNSB],
    T.[PO Last Name Of Change Document Responsible] = S.[LAST_NAME_OF_CHG_DOCMT_RESPNSBL],
    T.[PO Item Category In Purchasing Order] = S.[ITM_CTGRY_IN_PURCHS_ORDER],
    T.[PO Incompletion Indicator] = S.[PO_INCOMPLETION_IND],
    T.[PO STO Supplying Plant] = S.[STO_SUPPLYING_PLNT],
    T.[PO Principle Purchase Agreement Item Number] = S.[PRIN_PURCHS_AGMT_ITM_NUM],
    T.[PO Price Unit] = S.[PRICE_UNIT],
    T.[PO Is ZARI Output Type] = S.[IS_ZARI_OTPUT_TYP],
    T.[PO ZARI Status] = S.[ZARI_STATUS],
    T.[PO ZARI Status Description] = S.[ZARI_STATUS_DESC],
    T.[PO Validity Period Start Date] = S.[VLDTY_PER_STRT_DATE],
    T.[PO Validity Period End Date] = S.[VLDTY_PER_END_DATE],
    T.[PO Delivery Address Name 1] = S.[DLVRY_ADDR_NAME_1],
    T.[PO Delivery Address Name 2] = S.[DLVRY_ADDR_NAME_2],
    T.[PO Delivery Address House Number] = S.[DLVRY_ADDR_HOUSE_NUM],
    T.[PO Delivery Address Street] = S.[DLVRY_ADDR_STR],
    T.[PO Delivery Address District] = S.[DLVRY_ADDR_DISTR],
    T.[PO Delivery Address Postal Code] = S.[DLVRY_ADDR_POSTAL_CD],
    T.[PO Delivery Address City] = S.[DLVRY_ADDR_CITY],
    T.[PO Delivery Address Country] = S.[DLVRY_ADDR_CNTRY],
    T.[PO Delivery Address Region] = S.[DLVRY_ADDR_REGN],
    T.[PO Order Acknowledgment Number] = S.[ORDER_ACKNOWLEDGMENT_NUM]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_PP_PURORDL_CUR_D] T
INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_PP_PURORDL_CUR_D] S
    ON T.[PURCHS_ORDER_ITM_KEY] = S.[PURCHS_ORDER_ITM_KEY];

    ----------------------------------------------------------------------
    -- Insert new records into target table
    ----------------------------------------------------------------------
   INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_PP_PURORDL_CUR_D] (
    [PURCHS_ORDER_ITM_KEY],
    [Purchase Order ID],
    [Purchase Order Item ID],
    [PO Company Code],
    [PO Purchasing Document Category],
    [PO Purchasing Document Type],
    [PO Status],
    [PO Statistical Date],
    [PO Delivery Date],
    [PO Created On],
    [PO Created By],
    [PO Vendor],
    [PO Purchasing Organization],
    [PO Purchasing Group],
    [PO Currency],
    [PO Exchange Rate],
    [PO Invoicing Party],
    [PO Document Date],
    [PO Terms Of Payment],
    [PO Incoterms],
    [PO Deletion Indicator],
    [PO Short Text],
    [PO Material],
    [PO Material 2],
    [PO Material Group],
    [PO Plant],
    [PO Storage Location],
    [PO Target Quantity],
    [PO Quantity],
    [PO Unit],
    [PO Net Order Price],
    [PO Net Order Value],
    [PO Is PO Open],
    [PO Quantity Open Goods Receipt Total],
    [ETL_SRC_SYS_CD],
    [ETL_EFFECTV_BEGIN_DATE],
    [ETL_EFFECTV_END_DATE],
    [ETL_CURR_RCD_IND],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [PO Account Assignment Category],
    [PO Account Assignment Category Description],
    [PO Number of Principal Purchase Agreement],
    [PO Deletion Indicator in Purchasing Document],
    [PO Delivery Completed Indicator],
    [PO Final Invoice Indicator],
    [PO Goods Receipt Non Valuated],
    [PO Indicator GR Based Invoice Verification],
    [PO Incoterms Part 1],
    [PO Incoterms Part 2],
    [PO Indicator Update Info Record],
    [PO Period Indicator for Shelf Life Expiration Date],
    [PO Item Category in Purchasing Document],
    [PO Requisition Number],
    [PO Revision Level],
    [PO Shipping Instructions],
    [PO Stock Type],
    [PO Tax On Sales Purchases Code],
    [PO Material Number Used by Vendor],
    [PO Goods Receipt Processing Time in Days],
    [PO Minimum Remaining Shelf Life],
    [PO Overdelivery Tolerance Limit],
    [PO Planned Delivery Time in Days],
    [PO Underdelivery Tolerance Limit],
    [PO Purchasing Document Processing State],
    [PO International Article Number EAN UPC],
    [PO Goods Receipt Indicator],
    [PO Invoice Receipt Indicator],
    [PO Order Price Unit Purchasing],
    [PO Base Unit Of Measure],
    [PO Name Of Requisitioner Requester],
    [PO Change Document Responsible Person],
    [PO Change Document Creation Date],
    [PO Item Category Description],
    [PO Purchasing Document Category Description],
    [PO Purchasing Document Type Description],
    [PO Purchasing Organization Description],
    [PO Purchasing Group Description],
    [PO Currency Description],
    [PO Terms of Payment Description],
    [PO Incoterms Description],
    [PO Material Group Description],
    [PO Plant Description],
    [PO Storage Location Description],
    [PO Incoterms Part 1 Description],
    [PO Indicator Update Info Record Description],
    [PO Shipping Instructions Description],
    [PO Stock Type Description],
    [PO Tax On Sales Purchases Code Description],
    [PO First Name Of Requester],
    [PO Last Name Of Requester],
    [PO First Name Of Change Document Responsible],
    [PO Last Name Of Change Document Responsible],
    [PO Item Category In Purchasing Order],
    [PO Incompletion Indicator],
    [PO STO Supplying Plant],
    [PO Principle Purchase Agreement Item Number],
    [PO Price Unit],
    [PO Is ZARI Output Type],
    [PO ZARI Status],
    [PO ZARI Status Description],
    [PO Validity Period Start Date],
    [PO Validity Period End Date],
    [PO Delivery Address Name 1],
    [PO Delivery Address Name 2],
    [PO Delivery Address House Number],
    [PO Delivery Address Street],
    [PO Delivery Address District],
    [PO Delivery Address Postal Code],
    [PO Delivery Address City],
    [PO Delivery Address Country],
    [PO Delivery Address Region],
    [PO Order Acknowledgment Number]
)
SELECT
    S.[PURCHS_ORDER_ITM_KEY],
    S.[PURCHS_ORDER_ID],
    S.[PURCHS_ORDER_ITM_ID],
    S.[CMPNY_CD],
    S.[PURCHS_DOCMT_CTGRY],
    S.[PURCHS_DOCMT_TYP],
    S.[STATUS],
    S.[STATISTICAL_DATE],
    S.[DLVRY_DATE],
    S.[CREATED_ON],
    S.[CREATED_BY],
    S.[VNDR],
    S.[PURCHS_ORGZTN],
    S.[PURCHS_GROUP],
    S.[CRNCY],
    S.[EXCHG_RT],
    S.[INVOICING_PARTY],
    S.[DOCMT_DATE],
    S.[TRMS_OF_PYMT],
    S.[INCOTERMS],
    S.[DELETION_IND],
    S.[SHORT_TEXT],
    S.[MATRL],
    S.[MATRL_2],
    S.[MATRL_GROUP],
    S.[PLNT],
    S.[STOR_LOC],
    S.[TRGT_QTY],
    S.[ORDER_QTY],
    S.[ORDER_UNIT],
    S.[NET_ORDER_PRICE],
    S.[NET_ORDER_VAL],
    S.[IS_PURCHS_ORDER_OPEN],
    S.[QTY_OPEN_GOODS_RCPT_TOTAL],
    S.[ETL_SRC_SYS_CD],
    S.[ETL_EFFECTV_BEGIN_DATE],
    S.[ETL_EFFECTV_END_DATE],
    S.[ETL_CURR_RCD_IND],
    S.[ETL_CREATED_TS],
    S.[ETL_UPDTD_TS],
    S.[ACCT_ASSIGN_CTGRY],
    S.[ACCT_ASSIGN_CTGRY_DESC],
    S.[NUM_OF_PRINCIPAL_PURCHS_AGREEME],
    S.[DELETION_IND_IN_PURNG_DOCMT],
    S.[DLVRY_COMPLETED_IND],
    S.[FINAL_INVC_IND],
    S.[GOODS_RCPT_NON_VALTD],
    S.[IND_GR_BASED_INVC_VERFTN],
    S.[INCOTERMS_PART_1],
    S.[INCOTERMS_PART_2],
    S.[IND_UPDT_INFO_RCD],
    S.[PER_IND_FOR_SHELF_LIFE_EXPIRATI],
    S.[ITM_CTGRY_IN_PURNG_DOCMT],
    S.[PURCHS_REQZ_NUM],
    S.[REVISION_LVL],
    S.[SHIPG_INSTRUCTIONS],
    S.[STK_TYP],
    S.[TAX_ON_SALES_PURCHASES_CD],
    S.[MATRL_NUM_USED_BY_VNDR],
    S.[GOODS_RCPT_PRCSNG_TM_IN_DAYS],
    S.[MIN_REMG_SHELF_LIFE],
    S.[OVERDELIVERY_TOLERANCE_LMT],
    S.[PLND_DLVRY_TM_IN_DAYS],
    S.[UNDERDELIVERY_TOLERANCE_LMT],
    S.[PURNG_DOCMT_PRCSNG_ST],
    S.[INTERNATIONAL_ARTICLE_NUM_EAN_U],
    S.[GOODS_RCPT_IND],
    S.[INVC_RCPT_IND],
    S.[ORDER_PRICE_UNIT_PURNG],
    S.[BASE_UNIT_OF_MEASUR],
    S.[NAME_OF_REQUISITIONER_REQUESTER],
    S.[CHG_DOCMT_RESPNSBLE_PERSON],
    S.[CHG_DOCMT_CREATION_DATE],
    S.[ITM_CTGRY_DESC],
    S.[PURNG_DOCMT_CTGRY_DESC],
    S.[PURNG_DOCMT_TYP_DESC],
    S.[PURNG_ORGZTN_DESC],
    S.[PURNG_GROUP_DESC],
    S.[CRNCY_DESC],
    S.[TRMS_OF_PYMT_DESC],
    S.[INCOTERMS_DESC],
    S.[MATRL_GROUP_DESC],
    S.[PLNT_DESC],
    S.[STOR_LOC_DESC],
    S.[INCOTERMS_PART_1_DESC],
    S.[IND_UPDT_INFO_RCD_DESC],
    S.[SHIPG_INSTRUCTIONS_DESC],
    S.[STK_TYP_DESC],
    S.[TAX_ON_SALES_PURCHASES_CD_DESC],
    S.[FIRST_NAME_OF_REQUESTER],
    S.[LAST_NAME_OF_REQUESTER],
    S.[FIRST_NAME_OF_CHG_DOCMT_RESPNSB],
    S.[LAST_NAME_OF_CHG_DOCMT_RESPNSBL],
    S.[ITM_CTGRY_IN_PURCHS_ORDER],
    S.[PO_INCOMPLETION_IND],
    S.[STO_SUPPLYING_PLNT],
    S.[PRIN_PURCHS_AGMT_ITM_NUM],
    S.[PRICE_UNIT],
    S.[IS_ZARI_OTPUT_TYP],
    S.[ZARI_STATUS],
    S.[ZARI_STATUS_DESC],
    S.[VLDTY_PER_STRT_DATE],
    S.[VLDTY_PER_END_DATE],
    S.[DLVRY_ADDR_NAME_1],
    S.[DLVRY_ADDR_NAME_2],
    S.[DLVRY_ADDR_HOUSE_NUM],
    S.[DLVRY_ADDR_STR],
    S.[DLVRY_ADDR_DISTR],
    S.[DLVRY_ADDR_POSTAL_CD],
    S.[DLVRY_ADDR_CITY],
    S.[DLVRY_ADDR_CNTRY],
    S.[DLVRY_ADDR_REGN],
    S.[ORDER_ACKNOWLEDGMENT_NUM]
FROM[GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_PP_PURORDL_CUR_D] S
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_PP_PURORDL_CUR_D] T
    ON T.[PURCHS_ORDER_ITM_KEY] = S.[PURCHS_ORDER_ITM_KEY]
WHERE T.[PURCHS_ORDER_ITM_KEY] IS NULL;
END