CREATE     PROCEDURE [dbo].[Proc_EDW_T_D_MST_WORKCTR_CUR_D]
AS
BEGIN
    UPDATE T
    SET
        [Work Center ID] = S.[WRK_CNTR_ID],
        [Work Center Plant ID] = S.[PLNT_ID],
        [Work Center Object ID] = S.[OBJ_ID],
        [Work Center Object Type] = S.[OBJ_TYP],
        [Work Center Category] = S.[WRK_CNTR_CTGRY],
        [Work Center Location] = S.[WRK_CNTR_LOC],
        [Work Center Person Responsible] = S.[PERSON_RESPNSBLE],
        [STD_VAL_KEY] = S.[STD_VAL_KEY],
        [Work Center Usage Code] = S.[USAGE_CD],
        [Work Center Capacity ID] = S.[CAPACITY_ID],
        [Work Center Supply Area] = S.[SUPLY_AREA],
        [Work Center Deletion Flag] = S.[DELETION_FLG],
        [Work Center Locked Status] = S.[LOCKED_STATUS],
        [ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE] = S.[ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE] = S.[ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND] = S.[ETL_CURR_RCD_IND],
        [ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        [ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        [Work Center Description] = S.[WRK_CNTR_DESC],
        [Work Center Category Description] = S.[WRK_CNTR_CTGRY_DESC],
        [Work Center Person Responsible Name] = S.[PERSON_RESPNSBLE_NAME],
        [Work Center Control Key] = S.[CTRL_KEY],
        [Work Center Storage Location Storage Resource] = S.[STOR_LOC_STOR_RESOURCE],
        [Work Center User Name Term] = S.[USR_NAME_TERM],
        [Work Center User Name GRND] = S.[USR_NAME_GRND],
        [Work Center Changed On Date Term] = S.[CHANGED_ON_DATE_TERM],
        [Work Center Changed On Date GRND] = S.[CHANGED_ON_DATE_GRND],
        [Work Center Changed On Date] = S.[CHANGED_ON_DATE],
        [Work Center Plant Description] = S.[PLNT_DESC],
        [Work Center Object Type Description] = S.[OBJ_TYP_DESC],
        [Work Center Location Description] = S.[WRK_CNTR_LOC_DESC],
        [Work Center Standard Value Description] = S.[STD_VAL_DESC],
        [Work Center Usage Description] = S.[USAGE_DESC],
        [Work Center Supply Area Description] = S.[SUPLY_AREA_DESC],
        [Work Center Control Description] = S.[CTRL_DESC],
        [Work Center Storage Location Description] = S.[STOR_LOC_DESC]
    FROM [EDW_T_D_MST_WORKCTR_CUR_D] AS T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_WORKCTR_CUR_D] AS S
        ON T.[WRK_CNTR_KEY] = S.[WRK_CNTR_KEY];

    INSERT INTO [EDW_T_D_MST_WORKCTR_CUR_D] (
        [WRK_CNTR_KEY],
        [Work Center ID],
        [Work Center Plant ID],
        [Work Center Object ID],
        [Work Center Object Type],
        [Work Center Category],
        [Work Center Location],
        [Work Center Person Responsible],
        [STD_VAL_KEY],
        [Work Center Usage Code],
        [Work Center Capacity ID],
        [Work Center Supply Area],
        [Work Center Deletion Flag],
        [Work Center Locked Status],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Work Center Description],
        [Work Center Category Description],
        [Work Center Person Responsible Name],
        [Work Center Control Key],
        [Work Center Storage Location Storage Resource],
        [Work Center User Name Term],
        [Work Center User Name GRND],
        [Work Center Changed On Date Term],
        [Work Center Changed On Date GRND],
        [Work Center Changed On Date],
        [Work Center Plant Description],
        [Work Center Object Type Description],
        [Work Center Location Description],
        [Work Center Standard Value Description],
        [Work Center Usage Description],
        [Work Center Supply Area Description],
        [Work Center Control Description],
        [Work Center Storage Location Description]
    )
    SELECT
        S.[WRK_CNTR_KEY],
        S.[WRK_CNTR_ID],
        S.[PLNT_ID],
        S.[OBJ_ID],
        S.[OBJ_TYP],
        S.[WRK_CNTR_CTGRY],
        S.[WRK_CNTR_LOC],
        S.[PERSON_RESPNSBLE],
        S.[STD_VAL_KEY],
        S.[USAGE_CD],
        S.[CAPACITY_ID],
        S.[SUPLY_AREA],
        S.[DELETION_FLG],
        S.[LOCKED_STATUS],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[WRK_CNTR_DESC],
        S.[WRK_CNTR_CTGRY_DESC],
        S.[PERSON_RESPNSBLE_NAME],
        S.[CTRL_KEY],
        S.[STOR_LOC_STOR_RESOURCE],
        S.[USR_NAME_TERM],
        S.[USR_NAME_GRND],
        S.[CHANGED_ON_DATE_TERM],
        S.[CHANGED_ON_DATE_GRND],
        S.[CHANGED_ON_DATE],
        S.[PLNT_DESC],
        S.[OBJ_TYP_DESC],
        S.[WRK_CNTR_LOC_DESC],
        S.[STD_VAL_DESC],
        S.[USAGE_DESC],
        S.[SUPLY_AREA_DESC],
        S.[CTRL_DESC],
        S.[STOR_LOC_DESC]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_WORKCTR_CUR_D] AS S
    LEFT JOIN [EDW_T_D_MST_WORKCTR_CUR_D] AS T
        ON T.[WRK_CNTR_KEY] = S.[WRK_CNTR_KEY]
    WHERE T.[WRK_CNTR_KEY] IS NULL;
END;