CREATE     PROCEDURE [dbo].[Proc_EDW_T_D_MST_CMPNYDT_CUR_D]
AS
BEGIN
    ----------------------------------------------------------------------
    -- Update existing records in target table
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[Company Factory Calendar ID] = S.[FACTORY_CLNDR_ID],
        T.[Company Holiday Calendar ID] = S.[HOLIDAY_CLNDR_ID],
        T.[Company Date] = S.[THE_DATE],
        T.[Company Fiscal Year] = S.[FISCAL_YR],
        T.[Company Fiscal Period Number] = S.[FISCAL_PER_NUM],
        T.[Company Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Company Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Company Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Company Calendar Year] = S.[CLNDR_YR],
        T.[Company Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Company Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Company Calendar Month Description] = S.[CLNDR_MNTH_DESC],
        T.[Company Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[Company Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Company Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Company Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Company Calendar Day In Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Company Calendar Day In Year] = S.[CLNDR_DAY_IN_YR],
        T.[Company Calendar Week] = S.[CLNDR_WK],
        T.[Company Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Company Calendar Days in Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[Company Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Company Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Company Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Company Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Company Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Company Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Company Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Company Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Company Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Company Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Company Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Company Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Company Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Company Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Company Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Company Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Company Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Company Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Company Day in Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Company Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Company Fiscal Week] = S.[FISCAL_WK],
        T.[Company Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Company Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Company Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Company Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[CURR_MNTH_MINUS_2_FLG] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Company Is Factory Working Day] = S.[IS_FACTORY_WORKING_DAY],
        T.[Company Is Factory Public Holiday] = S.[IS_FACTORY_PUBLIC_HOLIDAY],
        T.[Company Is Working Day] = S.[IS_WORKING_DAY],
        T.[Company Business Day Number] = S.[BIZ_DAY_NUM],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CMPNYDT_CUR_D] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CMPNYDT_CUR_D] S
        ON T.[CMPNY_CD] = S.[CMPNY_CD]
        AND T.[DATE_KEY] = S.[DATE_KEY];

    ----------------------------------------------------------------------
    -- Insert new records into target table
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CMPNYDT_CUR_D] (
        [CMPNY_CD],
        [Company Factory Calendar ID],
        [DATE_KEY],
        [Company Holiday Calendar ID],
        [Company Date],
        [Company Fiscal Year],
        [Company Fiscal Period Number],
        [Company Fiscal Period Code],
        [Company Fiscal Quarter Number],
        [Company Fiscal Quarter Code],
        [Company Calendar Year],
        [Company Calendar Month Number],
        [Company Calendar Month Code],
        [Company Calendar Month Description],
        [Company Calendar Quarter Number],
        [Company Calendar Quarter Code],
        [Company Calendar Weekday Number],
        [Company Calendar Weekday Name],
        [Company Calendar Day In Month],
        [Company Calendar Day In Year],
        [Company Calendar Week],
        [Company Calendar Month In Quarter Number],
        [Company Calendar Days in Month],
        [Company Current Day Flag],
        [Company Current Day Minus 1 Flag],
        [Company Current Calendar Week Flag],
        [Company Current Calendar Week Minus 1 Flag],
        [Company Current Month Flag],
        [Company Current Month Minus 1 Flag],
        [Company Current Month Minus 12 Flag],
        [Company Current Quarter Flag],
        [Company Current Quarter Minus 1 Flag],
        [Company Current Quarter Minus 4 Flag],
        [Company Current Calendar Year Flag],
        [Company Current Calendar Year Minus 1 Flag],
        [Company Current Calendar Year Minus 2 Flag],
        [Company Current Fiscal Year Flag],
        [Company Current Fiscal Year Minus 1 Flag],
        [Company Current Fiscal Year Minus 2 Flag],
        [Company Current Calendar Year Plus 1 Flag],
        [Company Current Fiscal Year Plus 1 Flag],
        [Company Day in Fiscal Year],
        [Company Date Is Weekday],
        [Company Fiscal Week],
        [Company Current Fiscal Week Flag],
        [Company Current Fiscal Week Minus 1 Flag],
        [Company Fiscal Weekday Number],
        [Company Fiscal Weekday Name],
        [CURR_MNTH_MINUS_2_FLG],
        [Company Is Factory Working Day],
        [Company Is Factory Public Holiday],
        [Company Is Working Day],
        [Company Business Day Number],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS]
    )
    SELECT
        S.[CMPNY_CD],
        S.[FACTORY_CLNDR_ID],
        S.[DATE_KEY],
        S.[HOLIDAY_CLNDR_ID],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[IS_FACTORY_WORKING_DAY],
        S.[IS_FACTORY_PUBLIC_HOLIDAY],
        S.[IS_WORKING_DAY],
        S.[BIZ_DAY_NUM],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CMPNYDT_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CMPNYDT_CUR_D] T
        ON T.[CMPNY_CD] = S.[CMPNY_CD]
        AND T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[CMPNY_CD] IS NULL;
END