CREATE     PROCEDURE [dbo].[Proc_EDW_T_D_MST_CUSTSAL_CUR_D]
AS
BEGIN
    UPDATE T
    SET
        T.[CUST_SALES_AREA_KEY]	= S.[CUST_SALES_AREA_KEY],
        T.[Customer Sales ID]	= S.[CUST_ID],
        T.[Customer Sales Segment ID]	= S.[SEG_ID],
        T.[Customer Sales Organization]	= S.[SALES_ORGZTN],
        T.[Customer Sales Distribution Channel]	= S.[DISTRBN_CHNL],
        T.[Division]	= S.[DIVISION],
        T.[Order Block]	= S.[ORDER_BLK_FOR_SALES_AREA],
        T.[Delivery Block]	= S.[DLVRY_BLK_FOR_SALES_AREA],
        T.[Customer Group]	= S.[CUST_GROUP],
        T.[Customer Price Procedure]	= S.[CUST_PRICE_PROC],
        T.[Sales District]	= S.[SALES_DISTR],
        T.[Price Group]	= S.[PRICE_GROUP],
        T.[Price List]	= S.[PRICE_LIST],
        T.[Order Probability]	= S.[ORDER_PRBLTY],
        T.[Incoterms]	= S.[INCOTERMS],
        T.[Incoterms 2]	= S.[INCOTERMS2],
        T.[Account At Customer]	= S.[ACCT_AT_CUST],
        T.[Shipping Conditions]	= S.[SHIPG_CONDITIONS],
        T.[Payment Terms Code]	= S.[PYMT_TRMS_CD],
        T.[Account Clerk]	= S.[ACCT_CLERK],
        T.[ETL_SRC_SYS_CD]	= S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE]	= S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE]	= S.[ETL_EFFECTV_END_DATE],
        T.[Current Record Indicator of Customer Sales]	= S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS]	= S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS]	= S.[ETL_UPDTD_TS],
        T.[Market Code]	= S.[MRKT_CD],
        T.[Customer Group 2]	= S.[CUST_GROUP_2],
        T.[Sales Group]	= S.[SALES_GROUP],
        T.[Sales Office]	= S.[SALES_OFFC],
        T.[Created Date]	= S.[CREATED_DATE],
        T.[Aurora Rebate Program]	= S.[AURORA_RBTE_PGM],
        T.[Customer Group 3]	= S.[CUST_GROUP_3],
        T.[Periodic Account Statements Indicator]	= S.[PER_ACCT_STATEMENTS_IND],
        T.[Parent Customer ID]	= S.[PARNT_CUST_ID],
        T.[Parent Customer Name 1]	= S.[PARNT_CUST_NAME_1],
        T.[Parent Customer Name 2]	= S.[PARNT_CUST_NAME_2],
        T.[Customer Group 4]	= S.[CUST_GROUP_4],
        T.[Customer Group 5]	= S.[CUST_GROUP_5],
        T.[Customer Sales Organization Description]	= S.[SALES_ORG_DESC],
        T.[Distribution Channel Description]	= S.[DISTRBN_CHNL_DESC],
        T.[Division Description]	= S.[DIVISION_DESC],
        T.[Order Block Description]	= S.[ORDER_BLK_DESC],
        T.[Delivery Block Description]	= S.[DLVRY_BLK_DESC],
        T.[Customer Group Description]	= S.[CUST_GROUP_DESC],
        T.[Customer Price Procedure Description]	= S.[CUST_PRICE_PROC_DESC],
        T.[Sales District Description]	= S.[SALES_DISTR_DESC],
        T.[Price Group Description]	= S.[PRICE_GROUP_DESC],
        T.[Price List Description]	= S.[PRICE_LIST_DESC],
        T.[Incoterms Description]	= S.[INCOTERMS_DESC],
        T.[Shipping Conditions Description]	= S.[SHIPG_CONDITIONS_DESC],
        T.[Payment Terms Description]	= S.[TRMS_OF_PYMT_DESC],
        T.[Account Clerk Description]	= S.[ACCT_CLERK_DESC],
        T.[Aurora Rebate Program Description]	= S.[AURORA_RBTE_PGM_DESC],
        T.[Customer Group 2 Description]	= S.[CUST_GROUP_2_DESC],
        T.[Sales Group Description]	= S.[SALES_GROUP_DESC],
        T.[Sales Office Description]	= S.[SALES_OFFC_DESC],
        T.[Customer Group 3 Description]	= S.[CUST_GROUP_3_DESC],
        T.[Statement Description]	= S.[STMT_DESC],
        T.[Customer Group 4 Description]	= S.[CUST_GROUP_4_DESC],
        T.[Customer Group 5 Description]	= S.[CUST_GROUP_5_DESC],
        T.[Created By]	= S.[CREATED_BY],
        T.[Account Assignment Group]	= S.[CUST_ACCT_ASSIGN_GROUP],
        T.[Account Assignment Group Description]	= S.[CUST_ACCT_ASSIGN_GROUP_DESC],
        T.[ABC Classification]	= S.[CUST_ABC_CLSFTN],
        T.[Currency]	= S.[CRNCY],
        T.[Currency Description]	= S.[CRNCY_DESC],
        T.[Credit Control Area]	= S.[CREDIT_CTRL_AREA],
        T.[Credit Control Area Description]	= S.[CREDIT_CTRL_AREA_DESC],
        T.[Sales Block]	= S.[SALES_AREA_SALES_BLK],
        T.[Customer Group 1]	= S.[CUST_GROUP_1],
        T.[Customer Group 1 Description]	= S.[CUST_GROUP_1_DESC],
        T.[No Of Days Payment Terms]	= S.[NO_OF_DAYS_PYMT_TRMS],
        T.[End Of The Month Ind]	= S.[END_OF_THE_MNTH_IND],
        T.[Terms Discount Percentage]	= S.[TRMS_DISCNT_PRCNTG],
        T.[Customer Group 6]	= S.[CUST_GROUP_6],
        T.[Customer Group 7]	= S.[CUST_GROUP_7],
        T.[Customer Group 8]	= S.[CUST_GROUP_8],
        T.[Customer Group 9]	= S.[CUST_GROUP_9],
        T.[Customer Group 10]	= S.[CUST_GROUP_10],
        T.[Customer Group 6 Description]	= S.[CUST_GROUP_6_DESC],
        T.[Customer Group 7 Description]	= S.[CUST_GROUP_7_DESC],
        T.[Customer Group 8 Description]	= S.[CUST_GROUP_8_DESC],
        T.[Customer Group 9 Description]	= S.[CUST_GROUP_9_DESC],
        T.[Customer Group 10 Description]	= S.[CUST_GROUP_10_DESC],
        T.[Brand Owner ID]	= S.[BRAND_OWNER_ID],
        T.[Brand Owner Name 1]	= S.[BRAND_OWNER_NAME_1],
        T.[Brand Owner Name 2]	= S.[BRAND_OWNER_NAME_2],
        T.[Delivery Priority]	= S.[DLVRY_PRIORITY],
        T.[Delivery Priority Description]	= S.[DLVRY_PRIORITY_DESC],
        T.[Invoice Dates Calendar Identification]	= S.[INVC_DATES_CLNDR_ID],
        T.[Invoice Dates Calendar Identification Description]	= S.[INVC_DATES_CLNDR_ID_DESC],
        T.[Order Combination Indicator]	= S.[ORDER_COMBINATION_IND],
        T.[Complete Delivery Defined For Each Sales Order]	= S.[COMPLETE_DLVRY_DEFINED_FOR_EACH],
        T.[Max Number Of Partial Deliveries Allowed Per Item]	= S.[MAX_NUM_OF_PARTIAL_DELIVERIES_A],
        T.[Delivering Plant ID]	= S.[DELIVERING_PLNT_ID],
        T.[Delivering Plant Description]	= S.[DELIVERING_PLNT_DESC],
        T.[Deletion Indicator]	= S.[DELETION_IND],
        T.[Sales Area Billing Block]	= S.[SALES_AREA_BILLING_BLK],
        T.[Customer Procedure for Product Proposal]	= S.[CUST_PROC_FOR_PRDT_PROPOSAL],
        T.[Customer Procedure for Product Proposal Description]	= S.[CUST_PROC_FOR_PRDT_PROPOSAL_DES],
        T.[Customer Statistics Group]	= S.[CUST_STATISTICS_GROUP],
        T.[Customer Statistics Group Description]	= S.[CUST_STATISTICS_GROUP_DESC],
        T.[Partial Delivery At Item Level]	= S.[PARTIAL_DLVRY_AT_ITM_LVL],
        T.[Customer Is Rebate-Relevant Indicator]	= S.[CUST_IS_RBTE_RELEVANT_IND],
        T.[Relevant For Price Determination ID]	= S.[RELEVANT_FOR_PRICE_DETERMINATIO],
        T.[Invoice List Schedule]	= S.[INVC_LIST_SCHL],
        T.[Rating Customer]	= S.[RTG_CUST],
        T.[CFSA Code]	= S.[CFSA_CD],
        T.[Pre Need]	= S.[PRE_NEED],
        T.[PN Contact]	= S.[PN_CONTACT],
        T.[PN Pending]	= S.[PN_PEND],
        T.[Separate Invoice]	= S.[SEPARATE_INVC],
        T.[Miles From WHSE]	= S.[MILES_FROM_WHSE],
        T.[NSM Member]	= S.[NSM_MEMBR],
        T.[Consignment Code]	= S.[CONSIGNMENT_CD],
        T.[Saturday WHSE]	= S.[SATURDAY_WHSE],
        T.[PO Mandatory]	= S.[PO_MNDTRY],
        T.[Deceased Name Mandatory]	= S.[DECEASED_NAME_MNDTRY],
        T.[Company]	= S.[CMPNY],
        T.[CFSA Rating]	= S.[CFSA_RTG],
        T.[Transfer Fee]	= S.[TRSFR_FEE],
        T.[Customer Origin]	= S.[CUST_ORIGIN],
        T.[Sales Volume Commitment Percentage]	= S.[SALES_VOLUME_COMMITMENT_PRCNTG],
        T.[Case Volume Percentage]	= S.[CASE_VOLUME_PRCNTG],
        T.[Casket Volume Percentage]	= S.[CASKET_VOLUME_PRCNTG],
        T.[12 Unit Challenge]	= S.[UNIT_12_CHALLENGE],
        T.[PN % Commission]	= S.[PN_PRCNTG_COMM],
        T.[Plant]	= S.[PLNT],
        T.[Sign Up Date]	= S.[SIGN_UP_DATE]

    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTSAL_CUR_D] AS T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_CUSTSAL_CUR_D] AS S
        ON T.[CUST_SALES_AREA_KEY] = S.[CUST_SALES_AREA_KEY];

    -- Step 2: Insert new records from mirror into target table
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTSAL_CUR_D] (
        [CUST_SALES_AREA_KEY],
        [Customer Sales ID],
        [Customer Sales Segment ID],
        [Customer Sales Organization],
        [Customer Sales Distribution Channel],
        [Division],
        [Order Block],
        [Delivery Block],
        [Customer Group],
        [Customer Price Procedure],
        [Sales District],
        [Price Group],
        [Price List],
        [Order Probability],
        [Incoterms],
        [Incoterms 2],
        [Account At Customer],
        [Shipping Conditions],
        [Payment Terms Code],
        [Account Clerk],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [Current Record Indicator of Customer Sales],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Market Code],
        [Customer Group 2],
        [Sales Group],
        [Sales Office],
        [Created Date],
        [Aurora Rebate Program],
        [Customer Group 3],
        [Periodic Account Statements Indicator],
        [Parent Customer ID],
        [Parent Customer Name 1],
        [Parent Customer Name 2],
        [Customer Group 4],
        [Customer Group 5],
        [Customer Sales Organization Description],
        [Distribution Channel Description],
        [Division Description],
        [Order Block Description],
        [Delivery Block Description],
        [Customer Group Description],
        [Customer Price Procedure Description],
        [Sales District Description],
        [Price Group Description],
        [Price List Description],
        [Incoterms Description],
        [Shipping Conditions Description],
        [Payment Terms Description],
        [Account Clerk Description],
        [Aurora Rebate Program Description],
        [Customer Group 2 Description],
        [Sales Group Description],
        [Sales Office Description],
        [Customer Group 3 Description],
        [Statement Description],
        [Customer Group 4 Description],
        [Customer Group 5 Description],
        [Created By],
        [Account Assignment Group],
        [Account Assignment Group Description],
        [ABC Classification],
        [Currency],
        [Currency Description],
        [Credit Control Area],
        [Credit Control Area Description],
        [Sales Block],
        [Customer Group 1],
        [Customer Group 1 Description],
        [No Of Days Payment Terms],
        [End Of The Month Ind],
        [Terms Discount Percentage],
        [Customer Group 6],
        [Customer Group 7],
        [Customer Group 8],
        [Customer Group 9],
        [Customer Group 10],
        [Customer Group 6 Description],
        [Customer Group 7 Description],
        [Customer Group 8 Description],
        [Customer Group 9 Description],
        [Customer Group 10 Description],
        [Brand Owner ID],
        [Brand Owner Name 1],
        [Brand Owner Name 2],
        [Delivery Priority],
        [Delivery Priority Description],
        [Invoice Dates Calendar Identification],
        [Invoice Dates Calendar Identification Description],
        [Order Combination Indicator],
        [Complete Delivery Defined For Each Sales Order],
        [Max Number Of Partial Deliveries Allowed Per Item],
        [Delivering Plant ID],
        [Delivering Plant Description],
        [Deletion Indicator],
        [Sales Area Billing Block],
        [Customer Procedure for Product Proposal],
        [Customer Procedure for Product Proposal Description],
        [Customer Statistics Group],
        [Customer Statistics Group Description],
        [Partial Delivery At Item Level],
        [Customer Is Rebate-Relevant Indicator],
        [Relevant For Price Determination ID],
        [Invoice List Schedule],
        [Rating Customer],
        [CFSA Code],
        [Pre Need],
        [PN Contact],
        [PN Pending],
        [Separate Invoice],
        [Miles From WHSE],
        [NSM Member],
        [Consignment Code],
        [Saturday WHSE],
        [PO Mandatory],
        [Deceased Name Mandatory],
        [Company],
        [CFSA Rating],
        [Transfer Fee],
        [Customer Origin],
        [Sales Volume Commitment Percentage],
        [Case Volume Percentage],
        [Casket Volume Percentage],
        [12 Unit Challenge],
        [PN % Commission],
        [Plant],
        [Sign Up Date]

    )
    SELECT
       S.[CUST_SALES_AREA_KEY],
       S.[CUST_ID],
       S.[SEG_ID],
       S.[SALES_ORGZTN],
       S.[DISTRBN_CHNL],
       S.[DIVISION],
       S.[ORDER_BLK_FOR_SALES_AREA],
       S.[DLVRY_BLK_FOR_SALES_AREA],
       S.[CUST_GROUP],
       S.[CUST_PRICE_PROC],
       S.[SALES_DISTR],
       S.[PRICE_GROUP],
       S.[PRICE_LIST],
       S.[ORDER_PRBLTY],
       S.[INCOTERMS],
       S.[INCOTERMS2],
       S.[ACCT_AT_CUST],
       S.[SHIPG_CONDITIONS],
       S.[PYMT_TRMS_CD],
       S.[ACCT_CLERK],
       S.[ETL_SRC_SYS_CD],
       S.[ETL_EFFECTV_BEGIN_DATE],
       S.[ETL_EFFECTV_END_DATE],
       S.[ETL_CURR_RCD_IND],
       S.[ETL_CREATED_TS],
       S.[ETL_UPDTD_TS],
       S.[MRKT_CD],
       S.[CUST_GROUP_2],
       S.[SALES_GROUP],
       S.[SALES_OFFC],
       S.[CREATED_DATE],
       S.[AURORA_RBTE_PGM],
       S.[CUST_GROUP_3],
       S.[PER_ACCT_STATEMENTS_IND],
       S.[PARNT_CUST_ID],
       S.[PARNT_CUST_NAME_1],
       S.[PARNT_CUST_NAME_2],
       S.[CUST_GROUP_4],
       S.[CUST_GROUP_5],
       S.[SALES_ORG_DESC],
       S.[DISTRBN_CHNL_DESC],
       S.[DIVISION_DESC],
       S.[ORDER_BLK_DESC],
       S.[DLVRY_BLK_DESC],
       S.[CUST_GROUP_DESC],
       S.[CUST_PRICE_PROC_DESC],
       S.[SALES_DISTR_DESC],
       S.[PRICE_GROUP_DESC],
       S.[PRICE_LIST_DESC],
       S.[INCOTERMS_DESC],
       S.[SHIPG_CONDITIONS_DESC],
       S.[TRMS_OF_PYMT_DESC],
       S.[ACCT_CLERK_DESC],
       S.[AURORA_RBTE_PGM_DESC],
       S.[CUST_GROUP_2_DESC],
       S.[SALES_GROUP_DESC],
       S.[SALES_OFFC_DESC],
       S.[CUST_GROUP_3_DESC],
       S.[STMT_DESC],
       S.[CUST_GROUP_4_DESC],
       S.[CUST_GROUP_5_DESC],
       S.[CREATED_BY],
       S.[CUST_ACCT_ASSIGN_GROUP],
       S.[CUST_ACCT_ASSIGN_GROUP_DESC],
       S.[CUST_ABC_CLSFTN],
       S.[CRNCY],
       S.[CRNCY_DESC],
       S.[CREDIT_CTRL_AREA],
       S.[CREDIT_CTRL_AREA_DESC],
       S.[SALES_AREA_SALES_BLK],
       S.[CUST_GROUP_1],
       S.[CUST_GROUP_1_DESC],
       S.[NO_OF_DAYS_PYMT_TRMS],
       S.[END_OF_THE_MNTH_IND],
       S.[TRMS_DISCNT_PRCNTG],
       S.[CUST_GROUP_6],
       S.[CUST_GROUP_7],
       S.[CUST_GROUP_8],
       S.[CUST_GROUP_9],
       S.[CUST_GROUP_10],
       S.[CUST_GROUP_6_DESC],
       S.[CUST_GROUP_7_DESC],
       S.[CUST_GROUP_8_DESC],
       S.[CUST_GROUP_9_DESC],
       S.[CUST_GROUP_10_DESC],
       S.[BRAND_OWNER_ID],
       S.[BRAND_OWNER_NAME_1],
       S.[BRAND_OWNER_NAME_2],
       S.[DLVRY_PRIORITY],
       S.[DLVRY_PRIORITY_DESC],
       S.[INVC_DATES_CLNDR_ID],
       S.[INVC_DATES_CLNDR_ID_DESC],
       S.[ORDER_COMBINATION_IND],
       S.[COMPLETE_DLVRY_DEFINED_FOR_EACH],
       S.[MAX_NUM_OF_PARTIAL_DELIVERIES_A],
       S.[DELIVERING_PLNT_ID],
       S.[DELIVERING_PLNT_DESC],
       S.[DELETION_IND],
       S.[SALES_AREA_BILLING_BLK],
       S.[CUST_PROC_FOR_PRDT_PROPOSAL],
       S.[CUST_PROC_FOR_PRDT_PROPOSAL_DES],
       S.[CUST_STATISTICS_GROUP],
       S.[CUST_STATISTICS_GROUP_DESC],
       S.[PARTIAL_DLVRY_AT_ITM_LVL],
       S.[CUST_IS_RBTE_RELEVANT_IND],
       S.[RELEVANT_FOR_PRICE_DETERMINATIO],
       S.[INVC_LIST_SCHL],
       S.[RTG_CUST],
       S.[CFSA_CD],
       S.[PRE_NEED],
       S.[PN_CONTACT],
       S.[PN_PEND],
       S.[SEPARATE_INVC],
       S.[MILES_FROM_WHSE],
       S.[NSM_MEMBR],
       S.[CONSIGNMENT_CD],
       S.[SATURDAY_WHSE],
       S.[PO_MNDTRY],
       S.[DECEASED_NAME_MNDTRY],
       S.[CMPNY],
       S.[CFSA_RTG],
       S.[TRSFR_FEE],
       S.[CUST_ORIGIN],
       S.[SALES_VOLUME_COMMITMENT_PRCNTG],
       S.[CASE_VOLUME_PRCNTG],
       S.[CASKET_VOLUME_PRCNTG],
       S.[UNIT_12_CHALLENGE],
       S.[PN_PRCNTG_COMM],
       S.[PLNT],
       S.[SIGN_UP_DATE]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_CUSTSAL_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTSAL_CUR_D] AS T
        ON T.[CUST_SALES_AREA_KEY] = S.[CUST_SALES_AREA_KEY]
    WHERE T.[CUST_SALES_AREA_KEY] IS NULL;

END