CREATE   PROCEDURE [dbo].[Proc_EDW_T_D_MST_PLNTMAT_CUR_D]
AS
BEGIN
    ----------------------------------------------------------------------
    -- Update existing records in target table
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[Plant Material Material ID] = S.[MATRL_ID],
        T.[Plant Material Plant ID] = S.[PLNT_ID],
        T.[Plant Material Maintenance Status] = S.[MAINTENANCE_STATUS],
        T.[Plant Material Purchasing Group] = S.[PURNG_GROUP],
        T.[Plant Material MRP Type] = S.[MRP_TYP],
        T.[Plant Material MRP Controller] = S.[MRP_CNTRLR],
        T.[Plant Material Procurement Type] = S.[PRCRMNT_TYP],
        T.[Plant Material Export Import Group] = S.[EXPORT_IMPORT_GROUP],
        T.[Plant Material Profit Center ID] = S.[PROFT_CNTR_ID],
        T.[Plant Material Production Storage Location] = S.[PROD_STOR_LOC],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE] = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE] = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND] = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Plant Material Planned Delivery Time in Days] = S.[PLND_DLVRY_TM_IN_DAYS],
        T.[Plant Material Goods Receipt Processing Time in Days] = S.[GOODS_RCPT_PRCSNG_TM_IN_DAYS],
        T.[Plant Material Lot Size] = S.[LOT_SIZE],
        T.[Plant Material Production Supervisor] = S.[PROD_SUPVSR],
        T.[Plant Material Commodity Code] = S.[COMMODITY_CD],
        T.[Plant Material Storage Location for External Procurement] = S.[STOR_LOC_FOR_EXTNL_PRCRMNT],
        T.[Plant Material Production Scheduling Profile] = S.[PROD_SCHLG_PROFILE],
        T.[Plant Material Maximum Storage Period] = S.[MAX_STOR_PER],
        T.[Plant Material Time Unit] = S.[TM_UNIT],
        T.[Plant Material Availability Check] = S.[AVAILABILITY_CHK],
        T.[Plant Material Costing Lot Size] = S.[COSTING_LOT_SIZE],
        T.[Plant Material Planning Strategy Group] = S.[PLNG_STRATEGY_GROUP],
        T.[Plant Material Special Procurement Type] = S.[SPCL_PRCRMNT_TYP],
        T.[Plant Material Plant Description] = S.[PLNT_DESC],
        T.[Plant Material Purchasing Group Description] = S.[PURNG_GROUP_DESC],
        T.[Plant Material MRP Type Description] = S.[MRP_TYP_DESC],
        T.[Plant Material MRP Controller Description] = S.[MRP_CNTRLR_DESC],
        T.[Plant Material Procurement Type Description] = S.[PRCRMNT_TYP_DESC],
        T.[Plant Material Export Import Group Description] = S.[EXPORT_IMPORT_GROUP_DESC],
        T.[Plant Material Production Storage Location Description] = S.[PROD_STOR_LOC_DESC],
        T.[Plant Material Lot Size Description] = S.[LOT_SIZE_DESC],
        T.[Plant Material Production Supervisor Description] = S.[PROD_SUPVSR_DESC],
        T.[Plant Material Commodity Description] = S.[COMMODITY_DESC],
        T.[Plant Material Storage Location for External Procurement Description] = S.[STOR_LOC_FOR_EXTNL_PRCRMNT_DESC],
        T.[Plant Material Production Scheduling Profile Description] = S.[PROD_SCHLG_PROFILE_DESC],
        T.[Plant Material Availability Check Description] = S.[AVAILABILITY_CHK_DESC],
        T.[Plant Material Planning Strategy Group Description] = S.[PLNG_STRATEGY_GROUP_DESC],
        T.[Plant Material Special Procurement Type Description] = S.[SPCL_PRCRMNT_TYP_DESC],
        T.[Plant Material Re Order Point] = S.[RE_ORDER_PNT],
        T.[Plant Material In House Production Time] = S.[IN_HOUSE_PROD_TM],
        T.[SCHLG_MRGN_KEY] = S.[SCHLG_MRGN_KEY],
        T.[Plant Material PPC Planning Calendar] = S.[PPC_PLNG_CLNDR],
        T.[Plant Material Valuation Category] = S.[VALTN_CTGRY],
        T.[Plant Material Valuation Category Description] = S.[VALTN_CTGRY_DESC],
        T.[Plant Specific Material Status] = S.[PLNT_SPECIFIC_MATRL_STATUS],
        T.[Plant Specific Material Status Description] = S.[MATRL_STATUS_DESC],
        T.[Plant Material ABC Indicator] = S.[ABC_IND],
        T.[Plant Material ABC Indicator Description] = S.[ABC_IND_DESC],
        T.[Plant Material Critical Part Indicator] = S.[CRITICAL_PART_IND],
        T.[Plant Material UOI] = S.[UOI],
        T.[Plant Material Assembly Scrap In Pct] = S.[ASSEMBLY_SCRAP_IN_PCT],
        T.[Plant Material Safety Stock] = S.[SAFETY_STK],
        T.[Plant Material Max Stock Level] = S.[MAX_STK_LVL],
        T.[Plant Material PO Qty Rounding] = S.[PO_QTY_ROUNDING],
        T.[Plant Material Individual Collective Req Indicator] = S.[INDIVIDUAL_COLLECTIVE_REQ_IND],
        T.[Plant Material Overdelivery Tolerance Limit] = S.[OVERDELIVERY_TOLERANCE_LMT],
        T.[Plant Material Underdelivery Tolerance Limit] = S.[UNDERDELIVERY_TOLERANCE_LMT],
        T.[Plant Material Replenishment Lead Time In Days] = S.[REPLENISHMENT_LEAD_TM_IN_DAYS],
        T.[Plant Material Country Of Origin] = S.[CNTRY_OF_ORIGIN],
        T.[Plant Material Country Of Origin Description] = S.[CNTRY_OF_ORIGION_DESC],
        T.[Plant Material Individual Collective Requirement Description] = S.[INDIVIDUAL_COLLECTIVE_REQ_DESC],
        T.[Plant Material Costing Special Procurement Type] = S.[COSTING_SPCL_PRCRMNT_TYP],
        T.[Plant Material Costing Special Procurement Type Description] = S.[COSTING_SPCL_PRCRMNT_TYP_DESC],
        T.[Plant Material Do Not Cost] = S.[DO_NOT_COST],
        T.[Plant Material Level Deletion Flag] = S.[PLNT_LVL_MATRL_DELETION_FLG],
        T.[Plant Material Replacement Part] = S.[REPLACEMENT_PART],
        T.[Plant Material Replacement Part Description] = S.[REPLACEMENT_PART_DESC],
        T.[Plant Material Freight Group] = S.[MATRL_FREIGHT_GROUP],
        T.[Plant Material Freight Group Description] = S.[MATRL_FREIGHT_GROUP_DESC],
        T.[Plant Material Serial Number Profile] = S.[SERIAL_NUM_PROFILE],
        T.[Plant Material Serial Number Profile Description] = S.[SERIAL_NUM_PROFILE_DESC],
        T.[Plant Material Distribution Profile Of Material In Plant] = S.[DISTR_PROFILE_OF_MATRL_IN_PLNT],
        T.[Plant Material Distribution Profile Of Material In Plant Description] = S.[DISTRBN_PROFILE_OF_MATRL_IN_PLN]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PLNTMAT_CUR_D] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_PLNTMAT_CUR_D] S
        ON T.[PLNT_MATRL_KEY] = S.[PLNT_MATRL_KEY];

    ----------------------------------------------------------------------
    -- Insert new records into target table
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PLNTMAT_CUR_D] (
        [PLNT_MATRL_KEY],
        [Plant Material Material ID],
        [Plant Material Plant ID],
        [Plant Material Maintenance Status],
        [Plant Material Purchasing Group],
        [Plant Material MRP Type],
        [Plant Material MRP Controller],
        [Plant Material Procurement Type],
        [Plant Material Export Import Group],
        [Plant Material Profit Center ID],
        [Plant Material Production Storage Location],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Plant Material Planned Delivery Time in Days],
        [Plant Material Goods Receipt Processing Time in Days],
        [Plant Material Lot Size],
        [Plant Material Production Supervisor],
        [Plant Material Commodity Code],
        [Plant Material Storage Location for External Procurement],
        [Plant Material Production Scheduling Profile],
        [Plant Material Maximum Storage Period],
        [Plant Material Time Unit],
        [Plant Material Availability Check],
        [Plant Material Costing Lot Size],
        [Plant Material Planning Strategy Group],
        [Plant Material Special Procurement Type],
        [Plant Material Plant Description],
        [Plant Material Purchasing Group Description],
        [Plant Material MRP Type Description],
        [Plant Material MRP Controller Description],
        [Plant Material Procurement Type Description],
        [Plant Material Export Import Group Description],
        [Plant Material Production Storage Location Description],
        [Plant Material Lot Size Description],
        [Plant Material Production Supervisor Description],
        [Plant Material Commodity Description],
        [Plant Material Storage Location for External Procurement Description],
        [Plant Material Production Scheduling Profile Description],
        [Plant Material Availability Check Description],
        [Plant Material Planning Strategy Group Description],
        [Plant Material Special Procurement Type Description],
        [Plant Material Re Order Point],
        [Plant Material In House Production Time],
        [SCHLG_MRGN_KEY],
        [Plant Material PPC Planning Calendar],
        [Plant Material Valuation Category],
        [Plant Material Valuation Category Description],
        [Plant Specific Material Status],
        [Plant Specific Material Status Description],
        [Plant Material ABC Indicator],
        [Plant Material ABC Indicator Description],
        [Plant Material Critical Part Indicator],
        [Plant Material UOI],
        [Plant Material Assembly Scrap In Pct],
        [Plant Material Safety Stock],
        [Plant Material Max Stock Level],
        [Plant Material PO Qty Rounding],
        [Plant Material Individual Collective Req Indicator],
        [Plant Material Overdelivery Tolerance Limit],
        [Plant Material Underdelivery Tolerance Limit],
        [Plant Material Replenishment Lead Time In Days],
        [Plant Material Country Of Origin],
        [Plant Material Country Of Origin Description],
        [Plant Material Individual Collective Requirement Description],
        [Plant Material Costing Special Procurement Type],
        [Plant Material Costing Special Procurement Type Description],
        [Plant Material Do Not Cost],
        [Plant Material Level Deletion Flag],
        [Plant Material Replacement Part],
        [Plant Material Replacement Part Description],
        [Plant Material Freight Group],
        [Plant Material Freight Group Description],
        [Plant Material Serial Number Profile],
        [Plant Material Serial Number Profile Description],
        [Plant Material Distribution Profile Of Material In Plant],
        [Plant Material Distribution Profile Of Material In Plant Description]
    )
    SELECT
        S.[PLNT_MATRL_KEY],
        S.[MATRL_ID],
        S.[PLNT_ID],
        S.[MAINTENANCE_STATUS],
        S.[PURNG_GROUP],
        S.[MRP_TYP],
        S.[MRP_CNTRLR],
        S.[PRCRMNT_TYP],
        S.[EXPORT_IMPORT_GROUP],
        S.[PROFT_CNTR_ID],
        S.[PROD_STOR_LOC],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[PLND_DLVRY_TM_IN_DAYS],
        S.[GOODS_RCPT_PRCSNG_TM_IN_DAYS],
        S.[LOT_SIZE],
        S.[PROD_SUPVSR],
        S.[COMMODITY_CD],
        S.[STOR_LOC_FOR_EXTNL_PRCRMNT],
        S.[PROD_SCHLG_PROFILE],
        S.[MAX_STOR_PER],
        S.[TM_UNIT],
        S.[AVAILABILITY_CHK],
        S.[COSTING_LOT_SIZE],
        S.[PLNG_STRATEGY_GROUP],
        S.[SPCL_PRCRMNT_TYP],
        S.[PLNT_DESC],
        S.[PURNG_GROUP_DESC],
        S.[MRP_TYP_DESC],
        S.[MRP_CNTRLR_DESC],
        S.[PRCRMNT_TYP_DESC],
        S.[EXPORT_IMPORT_GROUP_DESC],
        S.[PROD_STOR_LOC_DESC],
        S.[LOT_SIZE_DESC],
        S.[PROD_SUPVSR_DESC],
        S.[COMMODITY_DESC],
        S.[STOR_LOC_FOR_EXTNL_PRCRMNT_DESC],
        S.[PROD_SCHLG_PROFILE_DESC],
        S.[AVAILABILITY_CHK_DESC],
        S.[PLNG_STRATEGY_GROUP_DESC],
        S.[SPCL_PRCRMNT_TYP_DESC],
        S.[RE_ORDER_PNT],
        S.[IN_HOUSE_PROD_TM],
        S.[SCHLG_MRGN_KEY],
        S.[PPC_PLNG_CLNDR],
        S.[VALTN_CTGRY],
        S.[VALTN_CTGRY_DESC],
        S.[PLNT_SPECIFIC_MATRL_STATUS],
        S.[MATRL_STATUS_DESC],
        S.[ABC_IND],
        S.[ABC_IND_DESC],
        S.[CRITICAL_PART_IND],
        S.[UOI],
        S.[ASSEMBLY_SCRAP_IN_PCT],
        S.[SAFETY_STK],
        S.[MAX_STK_LVL],
        S.[PO_QTY_ROUNDING],
        S.[INDIVIDUAL_COLLECTIVE_REQ_IND],
        S.[OVERDELIVERY_TOLERANCE_LMT],
        S.[UNDERDELIVERY_TOLERANCE_LMT],
        S.[REPLENISHMENT_LEAD_TM_IN_DAYS],
        S.[CNTRY_OF_ORIGIN],
        S.[CNTRY_OF_ORIGION_DESC],
        S.[INDIVIDUAL_COLLECTIVE_REQ_DESC],
        S.[COSTING_SPCL_PRCRMNT_TYP],
        S.[COSTING_SPCL_PRCRMNT_TYP_DESC],
        S.[DO_NOT_COST],
        S.[PLNT_LVL_MATRL_DELETION_FLG],
        S.[REPLACEMENT_PART],
        S.[REPLACEMENT_PART_DESC],
        S.[MATRL_FREIGHT_GROUP],
        S.[MATRL_FREIGHT_GROUP_DESC],
        S.[SERIAL_NUM_PROFILE],
        S.[SERIAL_NUM_PROFILE_DESC],
        S.[DISTR_PROFILE_OF_MATRL_IN_PLNT],
        S.[DISTRBN_PROFILE_OF_MATRL_IN_PLN]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_PLNTMAT_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PLNTMAT_CUR_D] T
        ON T.[PLNT_MATRL_KEY] = S.[PLNT_MATRL_KEY]
    WHERE T.[PLNT_MATRL_KEY] IS NULL;
END