CREATE     PROCEDURE [dbo].[Proc_EDW_T_D_SAL_SALORDH_CUR_D]
AS
BEGIN  
    -- Update existing records
    UPDATE T
    SET
        T.[SALES_ORDER_KEY] = S.[SALES_ORDER_KEY],
        T.[Sales Order ID] = S.[SALES_ORDER_ID],
        T.[Sales Order Company Code] = S.[CMPNY_CD],
        T.[Sales Order Segment ID] = S.[SEG_ID],
        T.[Sales Order Type ID] = S.[SALES_ORDER_TYP_ID],
        T.[Sales Order Requested Delivery Date] = S.[REQESTED_DLVRY_DATE],
        T.[Sales Order Category Code] = S.[CTGRY_CD],
        T.[Sales Order Document Number] = S.[DOCMT_NUM],
        T.[Sales Order Document Version] = S.[DOCMT_VRSN],
        T.[Sales Order Document Date] = S.[DOCMT_DATE],
        T.[Sales Order Purchase Order Type] = S.[PURCHS_ORDER_TYP],
        T.[Sales Order Note Description] = S.[SALES_ORDER_NOTE_DESC],
        T.[Sales Order Receive Date] = S.[SALES_ORDER_RECV_DATE],
        T.[Sales Order Currency] = S.[SALES_ORDER_CRNCY],
        T.[Sales Order Delivery Block] = S.[DLVRY_BLK],
        T.[Sales Order Sales Organization] = S.[SALES_ORGZTN],
        T.[Sales Order Pricing Procedure In Pricing] = S.[PRICING_PROC],
        T.[Sales Order Distribution Channel] = S.[DISTRBN_CHNL],
        T.[Sales Order Division] = S.[DIVISION],
        T.[Sales Order Sales Group] = S.[SALES_GROUP],
        T.[Sales Order Sales Office] = S.[SALES_OFFC],
        T.[Sales Order Internal Customer Reference Number] = S.[INTERNL_CUST_REF_NUM],
        T.[Sales Order Name Of Order] = S.[NAME_OF_ORDER],
        T.[Sales Order Document Overall Processing Status] = S.[DOCMT_OVERLL_PROCESSING_STATUS],
        T.[Sales Order Document Overall Rejection Status] = S.[DOCMT_OVERLL_REJN_STATUS],
        T.[Sales Order Delivery Status] = S.[DLVRY_STATUS],
        T.[Sales Order Credit Status] = S.[CREDIT_STATUS],
        T.[Sales Order Billing Status] = S.[BILLING_STATUS],
        T.[Sales Order Posting Status] = S.[PSTNG_STATUS],
        T.[Sales Order Rejection Status] = S.[REJN_STATUS],
        T.[Sales Order Total Goods Movement Status] = S.[TOTAL_GOODS_MOVEMNT_STATUS],
        T.[Sales Order Reason] = S.[ORDER_RSN],
        T.[Sales Order Reference Document] = S.[REF_DOCMT],
        T.[Sales Order Contract Number] = S.[CNTRCT_NUM],
        T.[Sales Order Lot Location] = S.[LOT_LOC],
        T.[Sales Order Counselor] = S.[COUNSELOR],
        T.[Sales Order Websphere Order Number] = S.[WEBSPHERE_ORDER_NUM],
        T.[Sales Order Processed Flag] = S.[PROCESSED_FLG],
        T.[Sales Order Websphere Create Name] = S.[WEBSPHERE_CREATE_NAME],
        T.[Sales Order Delivery Days] = S.[DLVRY_DAYS],
        T.[Sales Order Previous Sales Order Number] = S.[PREV_SALES_ORDER_NUM],
        T.[Sales Order Remake Number] = S.[REMAKE_NUM],
        T.[Sales Order Created Date] = S.[CREATED_DATE],
        T.[Sales Order Created User ID] = S.[CREATED_USR_ID],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE] = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE] = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND] = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Sales Order Reference Number] = S.[REF_SALES_ORDER_NUM],
        T.[Sales Order Type Description] = S.[SALES_ORDER_TYP_DESC],
        T.[Sales Order Purchase Order Number] = S.[PURCHS_ORDER_NUM],
        T.[Sales Order Bill Stat Order Status] = S.[BILL_STAT_ORDER_STATUS],
        T.[Sales Order Document Overall Processing Status Description] = S.[DOCMT_OVERLL_PROCESSING_STATUS_DESC],
        T.[Sales Order Document Overall Rejection Status Description] = S.[DOCMT_OVERLL_REJN_STATUS_DESC],
        T.[Sales Order Delivery Status Description] = S.[DLVRY_STATUS_DESC],
        T.[Sales Order Credit Status Description] = S.[CREDIT_STATUS_DESC],
        T.[Sales Order Billing Status Description] = S.[BILLING_STATUS_DESC],
        T.[Sales Order Posting Status Description] = S.[PSTNG_STATUS_DESC],
        T.[Sales Order Rejection Status Description] = S.[REJN_STATUS_DESC],
        T.[Sales Order Total Goods Movement Status Description] = S.[TOTAL_GOODS_MOVEMNT_STATUS_DESC],
        T.[Sales Order Reason Description] = S.[ORDER_RSN_DESC],
        T.[Sales Order Bill Stat Order Status Description] = S.[BILL_STAT_ORDER_STATUS_DESC],
        T.[Sales Order Payment Terms] = S.[PYMT_TRMS],
        T.[Sales Order Payment Terms Description] = S.[PYMT_TRMS_DESC],
        T.[Sales Order Quotation Valid From Date] = S.[QUOTATION_VALID_FROM_DATE],
        T.[Sales Order Quotation Valid To Date] = S.[QUOTATION_VALID_TO_DATE],
        T.[Sales Order Warranty Date] = S.[WARRANTY_DATE],
        T.[Sales Order Preceding Document Category] = S.[PRECEDING_DOCMT_CTGRY],
        T.[Sales Order Version] = S.[VRSN],
        T.[Sales Order Reference Status] = S.[REF_STATUS],
        T.[Sales Order Total Reference Status] = S.[TOTAL_REF_STATUS],
        T.[Sales Order Billing Block] = S.[BILLING_BLK],
        T.[Sales Order Is Arrangement] = S.[IS_ARRANGEMENT],
        T.[Sales Order Is Approval] = S.[IS_APPROVAL],
        T.[Sales Order Is Delivery] = S.[IS_DLVRY],
        T.[Sales Order Is Fixed Det] = S.[IS_FIXED_DET],
        T.[Sales Order Invoice Create Date] = S.[INVC_CREATE_DATE],
        T.[Sales Order Sold To Customer] = S.[SOLDTO_CUST],
        T.[Sales Order Bill To Customer] = S.[BILLTO_CUST],
        T.[Sales Order Ship To Customer] = S.[SHIPTO_CUST],
        T.[Sales Order Changed On Date] = S.[CHANGED_ON_DATE],
        T.[Sales Order Document Currency Net Value] = S.[DOCMT_CRNCY_NET_VAL],
        T.[Sales Order Customer Group 2] = S.[CUST_GROUP_2],
        T.[Sales Order Billing Date] = S.[BILLING_DATE],
        T.[Sales Order Entry Time] = S.[ENTRY_TM],
        T.[Sales Order Usage Indicator] = S.[USAGE_IND],
        T.[SO Status of Static Credit Limit Check] = S.[STATUS_OF_STTIC_CREDIT_LMT_CHK],
        T.[Sales Order Company Code To Be Billed] = S.[CMPNY_CD_TO_BE_BILLD],
        T.[Sales Order Long Description] = S.[SALES_ORDER_LONG_DESC],
        T.[Sales Order Company Description] = S.[CMPNY_DESC],
        T.[Sales Order Category Code Description] = S.[CTGRY_CD_DESC],
        T.[Sales Order Purchase Order Type Description] = S.[PURCHS_ORDER_TYP_DESC],
        T.[Sales Order Currency Description] = S.[SALES_ORDER_CRNCY_DESC],
        T.[Sales Order Delivery Block Description] = S.[DLVRY_BLK_DESC],
        T.[Sales Order Sales Organization Description] = S.[SALES_ORGZTN_DESC],
        T.[Sales Order Distribution Channel Description] = S.[DISTRBN_CHNL_DESC],
        T.[Sales Order Division Description] = S.[DIVISION_DESC],
        T.[Sales Order Sales Group Description] = S.[SALES_GROUP_DESC],
        T.[Sales Order Sales Office Description] = S.[SALES_OFFC_DESC],
        T.[Sales Order Preceding Document Category Description] = S.[PRECEDING_DOCMT_CTGRY_DESC],
        T.[Sales Order Reference Status Description] = S.[REF_STATUS_DESC],
        T.[Sales Order Total Reference Status Description] = S.[TOTAL_REF_STATUS_DESC],
        T.[Sales Order Billing Block Description] = S.[BILLING_BLK_DESC],
        T.[Sales Order Customer Group 2 Description] = S.[CUST_GROUP2_DESC],
        T.[Sales Order Usage Indicator Description] = S.[USAGE_IND_DESC],
        T.[Sales Order Static Credit Limit Check Description] = S.[STTIC_CREDIT_LMT_CHK_DESC],
        T.[Sales Order Company To Be Billed Description] = S.[CMPNY_TO_BE_BILLD_DESC],
        T.[Sales Order Sold To Purchase Order Number] = S.[SOLDTO_PURCHS_ORDER_NUM],
        T.[Sales Order Sold To Purchase Order Date] = S.[SOLDTO_PURCHS_ORDER_DATE],
        T.[Sales Order Ship To Purchase Order Number] = S.[SHIPTO_PURCHS_ORDER_NUM],
        T.[Sales Order Ship To Purchase Order Date] = S.[SHIPTO_PURCHS_ORDER_DATE],
        T.[Sales Order Customer Condition Group 1] = S.[CUST_COND_GROUP_1],
        T.[Sales Order Customer Condition Group 1 Description] = S.[CUST_COND_GROUP_1_DESC],
        T.[Sales Order Last Customer Contact Date] = S.[LAST_CUST_CONTACT_DATE],
        T.[Sales Order User Status] = S.[USR_STATUS],
        T.[Sales Order Encoway ID] = S.[ENCOWAY_ID],
        T.[Sales Order Encoway Version] = S.[ENCOWAY_VRSN],
        T.[Sales Order Encoway Description] = S.[ENCOWAY_DESC],
        T.[Sales Order Overall Blocked Status] = S.[OVERLL_BLCKD_STATUS],
        T.[Sales Order Overall Blocked Status Description] = S.[OVERLL_BLCKD_STATUS_DESC],
        T.[ADB Field 1 - Addl Field 1] = S.[ADDITIONAL_FLD_1],
        T.[ADB Field 2 - Addl Field 2] = S.[ADDITIONAL_FLD_2],
        T.[ADB Field 3 - Addl Field 3] = S.[ADDITIONAL_FLD_3],
        T.[ADB Field 4 - Addl Field 4] = S.[ADDITIONAL_FLD_4],
        T.[ADB Field 5 - Addl Field 5] = S.[ADDITIONAL_FLD_5],
        T.[ADB Field 6 - Addl Field 6] = S.[ADDITIONAL_FLD_6],
        T.[ADB Field 7 - Addl Field 7] = S.[ADDITIONAL_FLD_7],
        T.[ADB Field 8 - Addl Field 8] = S.[ADDITIONAL_FLD_8],
        T.[ADB Field 9 - Addl Field 9] = S.[ADDITIONAL_FLD_9],
        T.[Sales Order Number] = S.[ORDER_NUM],
        T.[Sales Order Delay Status] = S.[DELAY_STATUS],
        T.[Sales Order Delay Status Description] = S.[DELAY_STATUS_DESC],
        T.[Sales Order Payment Method] = S.[PYMT_MTHD],
        T.[Sales Order Payment Method Description] = S.[PYMT_MTHD_DESC],
        T.[VALID_FROM_DATE] = S.[VALID_FROM_DATE],
        T.[VALID_TO_DATE] = S.[VALID_TO_DATE],
        T.[Sales Order Collective Number] = S.[COLLECTIVE_NUM],
        T.[Sales Order Sales Employee ID] = S.[SALES_EMPL_ID],
        T.[Sales Order Terms Discount Percentage] = S.[TRMS_DISCNT_PRCNTG],
        T.[Sales Order Customer Group 6] = S.[CUST_GROUP_6],
        T.[Sales Order Customer Group 7] = S.[CUST_GROUP_7],
        T.[Sales Order Customer Group 8] = S.[CUST_GROUP_8],
        T.[Sales Order Customer Group 9] = S.[CUST_GROUP_9],
        T.[Sales Order Customer Group 10] = S.[CUST_GROUP_10],
        T.[Sales Order Transaction Group] = S.[TRNSCTN_GROUP],
        T.[Sales Order Transaction Group Description] = S.[TRNSCTN_GROUP_DESC],
        T.[Sales Order Customer Group 6 Description] = S.[CUST_GROUP_6_DESC],
        T.[Sales Order Customer Group 7 Description] = S.[CUST_GROUP_7_DESC],
        T.[Sales Order Customer Group 8 Description] = S.[CUST_GROUP_8_DESC],
        T.[Sales Order Customer Group 9 Description] = S.[CUST_GROUP_9_DESC],
        T.[Sales Order Customer Group 10 Description] = S.[CUST_GROUP_10_DESC]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_SALORDH_CUR_D] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_SAL_SALORDH_CUR_D] S
        ON T.[SALES_ORDER_KEY] = S.[SALES_ORDER_KEY];

    -- Insert new records
INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_SALORDH_CUR_D] (
    [SALES_ORDER_KEY],
    [Sales Order ID],
    [Sales Order Company Code],
    [Sales Order Segment ID],
    [Sales Order Type ID],
    [Sales Order Requested Delivery Date],
    [Sales Order Category Code],
    [Sales Order Document Number],
    [Sales Order Document Version],
    [Sales Order Document Date],
    [Sales Order Purchase Order Type],
    [Sales Order Note Description],
    [Sales Order Receive Date],
    [Sales Order Currency],
    [Sales Order Delivery Block],
    [Sales Order Sales Organization],
    [Sales Order Pricing Procedure In Pricing],
    [Sales Order Distribution Channel],
    [Sales Order Division],
    [Sales Order Sales Group],
    [Sales Order Sales Office],
    [Sales Order Internal Customer Reference Number],
    [Sales Order Name Of Order],
    [Sales Order Document Overall Processing Status],
    [Sales Order Document Overall Rejection Status],
    [Sales Order Delivery Status],
    [Sales Order Credit Status],
    [Sales Order Billing Status],
    [Sales Order Posting Status],
    [Sales Order Rejection Status],
    [Sales Order Total Goods Movement Status],
    [Sales Order Reason],
    [Sales Order Reference Document],
    [Sales Order Contract Number],
    [Sales Order Lot Location],
    [Sales Order Counselor],
    [Sales Order Websphere Order Number],
    [Sales Order Processed Flag],
    [Sales Order Websphere Create Name],
    [Sales Order Delivery Days],
    [Sales Order Previous Sales Order Number],
    [Sales Order Remake Number],
    [Sales Order Created Date],
    [Sales Order Created User ID],
    [ETL_SRC_SYS_CD],
    [ETL_EFFECTV_BEGIN_DATE],
    [ETL_EFFECTV_END_DATE],
    [ETL_CURR_RCD_IND],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Sales Order Reference Number],
    [Sales Order Type Description],
    [Sales Order Purchase Order Number],
    [Sales Order Bill Stat Order Status],
    [Sales Order Document Overall Processing Status Description],
    [Sales Order Document Overall Rejection Status Description],
    [Sales Order Delivery Status Description],
    [Sales Order Credit Status Description],
    [Sales Order Billing Status Description],
    [Sales Order Posting Status Description],
    [Sales Order Rejection Status Description],
    [Sales Order Total Goods Movement Status Description],
    [Sales Order Reason Description],
    [Sales Order Bill Stat Order Status Description],
    [Sales Order Payment Terms],
    [Sales Order Payment Terms Description],
    [Sales Order Quotation Valid From Date],
    [Sales Order Quotation Valid To Date],
    [Sales Order Warranty Date],
    [Sales Order Preceding Document Category],
    [Sales Order Version],
    [Sales Order Reference Status],
    [Sales Order Total Reference Status],
    [Sales Order Billing Block],
    [Sales Order Is Arrangement],
    [Sales Order Is Approval],
    [Sales Order Is Delivery],
    [Sales Order Is Fixed Det],
    [Sales Order Invoice Create Date],
    [Sales Order Sold To Customer],
    [Sales Order Bill To Customer],
    [Sales Order Ship To Customer],
    [Sales Order Changed On Date],
    [Sales Order Document Currency Net Value],
    [Sales Order Customer Group 2],
    [Sales Order Billing Date],
    [Sales Order Entry Time],
    [Sales Order Usage Indicator],
    [SO Status of Static Credit Limit Check],
    [Sales Order Company Code To Be Billed],
    [Sales Order Long Description],
    [Sales Order Company Description],
    [Sales Order Category Code Description],
    [Sales Order Purchase Order Type Description],
    [Sales Order Currency Description],
    [Sales Order Delivery Block Description],
    [Sales Order Sales Organization Description],
    [Sales Order Distribution Channel Description],
    [Sales Order Division Description],
    [Sales Order Sales Group Description],
    [Sales Order Sales Office Description],
    [Sales Order Preceding Document Category Description],
    [Sales Order Reference Status Description],
    [Sales Order Total Reference Status Description],
    [Sales Order Billing Block Description],
    [Sales Order Customer Group 2 Description],
    [Sales Order Usage Indicator Description],
    [Sales Order Static Credit Limit Check Description],
    [Sales Order Company To Be Billed Description],
    [Sales Order Sold To Purchase Order Number],
    [Sales Order Sold To Purchase Order Date],
    [Sales Order Ship To Purchase Order Number],
    [Sales Order Ship To Purchase Order Date],
    [Sales Order Customer Condition Group 1],
    [Sales Order Customer Condition Group 1 Description],
    [Sales Order Last Customer Contact Date],
    [Sales Order User Status],
    [Sales Order Encoway ID],
    [Sales Order Encoway Version],
    [Sales Order Encoway Description],
    [Sales Order Overall Blocked Status],
    [Sales Order Overall Blocked Status Description],
    [ADB Field 1 - Addl Field 1],
    [ADB Field 2 - Addl Field 2],
    [ADB Field 3 - Addl Field 3],
    [ADB Field 4 - Addl Field 4],
    [ADB Field 5 - Addl Field 5],
    [ADB Field 6 - Addl Field 6],
    [ADB Field 7 - Addl Field 7],
    [ADB Field 8 - Addl Field 8],
    [ADB Field 9 - Addl Field 9],
    [Sales Order Number],
    [Sales Order Delay Status],
    [Sales Order Delay Status Description],
    [Sales Order Payment Method],
    [Sales Order Payment Method Description],
    [VALID_FROM_DATE],
    [VALID_TO_DATE],
    [Sales Order Collective Number],
    [Sales Order Sales Employee ID],
    [Sales Order Terms Discount Percentage],
    [Sales Order Customer Group 6],
    [Sales Order Customer Group 7],
    [Sales Order Customer Group 8],
    [Sales Order Customer Group 9],
    [Sales Order Customer Group 10],
    [Sales Order Transaction Group],
    [Sales Order Transaction Group Description],
    [Sales Order Customer Group 6 Description],
    [Sales Order Customer Group 7 Description],
    [Sales Order Customer Group 8 Description],
    [Sales Order Customer Group 9 Description],
    [Sales Order Customer Group 10 Description]
)
SELECT
    S.[SALES_ORDER_KEY],
    S.[SALES_ORDER_ID],
    S.[CMPNY_CD],
    S.[SEG_ID],
    S.[SALES_ORDER_TYP_ID],
    S.[REQESTED_DLVRY_DATE],
    S.[CTGRY_CD],
    S.[DOCMT_NUM],
    S.[DOCMT_VRSN],
    S.[DOCMT_DATE],
    S.[PURCHS_ORDER_TYP],
    S.[SALES_ORDER_NOTE_DESC],
    S.[SALES_ORDER_RECV_DATE],
    S.[SALES_ORDER_CRNCY],
    S.[DLVRY_BLK],
    S.[SALES_ORGZTN],
    S.[PRICING_PROC],
    S.[DISTRBN_CHNL],
    S.[DIVISION],
    S.[SALES_GROUP],
    S.[SALES_OFFC],
    S.[INTERNL_CUST_REF_NUM],
    S.[NAME_OF_ORDER],
    S.[DOCMT_OVERLL_PROCESSING_STATUS],
    S.[DOCMT_OVERLL_REJN_STATUS],
    S.[DLVRY_STATUS],
    S.[CREDIT_STATUS],
    S.[BILLING_STATUS],
    S.[PSTNG_STATUS],
    S.[REJN_STATUS],
    S.[TOTAL_GOODS_MOVEMNT_STATUS],
    S.[ORDER_RSN],
    S.[REF_DOCMT],
    S.[CNTRCT_NUM],
    S.[LOT_LOC],
    S.[COUNSELOR],
    S.[WEBSPHERE_ORDER_NUM],
    S.[PROCESSED_FLG],
    S.[WEBSPHERE_CREATE_NAME],
    S.[DLVRY_DAYS],
    S.[PREV_SALES_ORDER_NUM],
    S.[REMAKE_NUM],
    S.[CREATED_DATE],
    S.[CREATED_USR_ID],
    S.[ETL_SRC_SYS_CD],
    S.[ETL_EFFECTV_BEGIN_DATE],
    S.[ETL_EFFECTV_END_DATE],
    S.[ETL_CURR_RCD_IND],
    S.[ETL_CREATED_TS],
    S.[ETL_UPDTD_TS],
    S.[REF_SALES_ORDER_NUM],
    S.[SALES_ORDER_TYP_DESC],
    S.[PURCHS_ORDER_NUM],
    S.[BILL_STAT_ORDER_STATUS],
    S.[DOCMT_OVERLL_PROCESSING_STATUS_DESC],
    S.[DOCMT_OVERLL_REJN_STATUS_DESC],
    S.[DLVRY_STATUS_DESC],
    S.[CREDIT_STATUS_DESC],
    S.[BILLING_STATUS_DESC],
    S.[PSTNG_STATUS_DESC],
    S.[REJN_STATUS_DESC],
    S.[TOTAL_GOODS_MOVEMNT_STATUS_DESC],
    S.[ORDER_RSN_DESC],
    S.[BILL_STAT_ORDER_STATUS_DESC],
    S.[PYMT_TRMS],
    S.[PYMT_TRMS_DESC],
    S.[QUOTATION_VALID_FROM_DATE],
    S.[QUOTATION_VALID_TO_DATE],
    S.[WARRANTY_DATE],
    S.[PRECEDING_DOCMT_CTGRY],
    S.[VRSN],
    S.[REF_STATUS],
    S.[TOTAL_REF_STATUS],
    S.[BILLING_BLK],
    S.[IS_ARRANGEMENT],
    S.[IS_APPROVAL],
    S.[IS_DLVRY],
    S.[IS_FIXED_DET],
    S.[INVC_CREATE_DATE],
    S.[SOLDTO_CUST],
    S.[BILLTO_CUST],
    S.[SHIPTO_CUST],
    S.[CHANGED_ON_DATE],
    S.[DOCMT_CRNCY_NET_VAL],
    S.[CUST_GROUP_2],
    S.[BILLING_DATE],
    S.[ENTRY_TM],
    S.[USAGE_IND],
    S.[STATUS_OF_STTIC_CREDIT_LMT_CHK],
    S.[CMPNY_CD_TO_BE_BILLD],
    S.[SALES_ORDER_LONG_DESC],
    S.[CMPNY_DESC],
    S.[CTGRY_CD_DESC],
    S.[PURCHS_ORDER_TYP_DESC],
    S.[SALES_ORDER_CRNCY_DESC],
    S.[DLVRY_BLK_DESC],
    S.[SALES_ORGZTN_DESC],
    S.[DISTRBN_CHNL_DESC],
    S.[DIVISION_DESC],
    S.[SALES_GROUP_DESC],
    S.[SALES_OFFC_DESC],
    S.[PRECEDING_DOCMT_CTGRY_DESC],
    S.[REF_STATUS_DESC],
    S.[TOTAL_REF_STATUS_DESC],
    S.[BILLING_BLK_DESC],
    S.[CUST_GROUP2_DESC],
    S.[USAGE_IND_DESC],
    S.[STTIC_CREDIT_LMT_CHK_DESC],
    S.[CMPNY_TO_BE_BILLD_DESC],
    S.[SOLDTO_PURCHS_ORDER_NUM],
    S.[SOLDTO_PURCHS_ORDER_DATE],
    S.[SHIPTO_PURCHS_ORDER_NUM],
    S.[SHIPTO_PURCHS_ORDER_DATE],
    S.[CUST_COND_GROUP_1],
    S.[CUST_COND_GROUP_1_DESC],
    S.[LAST_CUST_CONTACT_DATE],
    S.[USR_STATUS],
    S.[ENCOWAY_ID],
    S.[ENCOWAY_VRSN],
    S.[ENCOWAY_DESC],
    S.[OVERLL_BLCKD_STATUS],
    S.[OVERLL_BLCKD_STATUS_DESC],
    S.[ADDITIONAL_FLD_1],
    S.[ADDITIONAL_FLD_2],
    S.[ADDITIONAL_FLD_3],
    S.[ADDITIONAL_FLD_4],
    S.[ADDITIONAL_FLD_5],
    S.[ADDITIONAL_FLD_6],
    S.[ADDITIONAL_FLD_7],
    S.[ADDITIONAL_FLD_8],
    S.[ADDITIONAL_FLD_9],
    S.[ORDER_NUM],
    S.[DELAY_STATUS],
    S.[DELAY_STATUS_DESC],
    S.[PYMT_MTHD],
    S.[PYMT_MTHD_DESC],
    S.[VALID_FROM_DATE],
    S.[VALID_TO_DATE],
    S.[COLLECTIVE_NUM],
    S.[SALES_EMPL_ID],
    S.[TRMS_DISCNT_PRCNTG],
    S.[CUST_GROUP_6],
    S.[CUST_GROUP_7],
    S.[CUST_GROUP_8],
    S.[CUST_GROUP_9],
    S.[CUST_GROUP_10],
    S.[TRNSCTN_GROUP],
    S.[TRNSCTN_GROUP_DESC],
    S.[CUST_GROUP_6_DESC],
    S.[CUST_GROUP_7_DESC],
    S.[CUST_GROUP_8_DESC],
    S.[CUST_GROUP_9_DESC],
    S.[CUST_GROUP_10_DESC]
FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_SAL_SALORDH_CUR_D] S
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_SALORDH_CUR_D] T
    ON T.[SALES_ORDER_KEY] = S.[SALES_ORDER_KEY]
WHERE T.[SALES_ORDER_KEY] IS NULL;
END