table EDW_T_FACT_PRD_TMCONFS_CUR_D
	lineageTag: dd241c16-89b6-4595-b751-b5f68aba0206
	sourceLineageTag: [Propelis].[EDW_T_Fact_PRD_TMCONFS_CUR_D]

	measure ACTUAL_WRK_YTD = ```
			
			TOTALYTD(
			    SUM('EDW_T_FACT_PRD_TMCONFS_CUR_D'[ACTUAL_WRK_IN_HRS]), 
			    'EDW_T_D_MST_DATE_CUR_D'[THE_DATE]
			)
			```
		formatString: #,0.00
		lineageTag: 741bd641-3920-449c-9f9f-8984953a12e8

		changedProperty = Name

		changedProperty = FormatString

	measure ACTUAL_WRK_MTD = ```
			
			TOTALMTD(
			    SUM('EDW_T_FACT_PRD_TMCONFS_CUR_D'[ACTUAL_WRK_IN_HRS]), 
			    'EDW_T_D_MST_DATE_CUR_D'[THE_DATE]
			)
			```
		formatString: #,0.00
		lineageTag: 91f6cc49-9662-447c-be25-478edeac9d41

		changedProperty = Name

		changedProperty = FormatString

	measure 'Remaining Work in Hours' = SUM(EDW_T_FACT_PRD_TMCONFS_CUR_D[REMG_WRK_IN_HRS])
		formatString: #,0.00
		lineageTag: 8c7aa4f7-bd97-43dc-9bac-dfa4eb6f28a0

		changedProperty = Name

		changedProperty = FormatString

	measure 'Remaining Work' = SUM(EDW_T_FACT_PRD_TMCONFS_CUR_D[REMG_WRK])
		formatString: #,0.00
		lineageTag: ff40a136-5cb0-405a-974b-5c39f1c15c9f

		changedProperty = Name

		changedProperty = FormatString

	measure 'Actual Work in Hours' = SUM(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACTUAL_WRK_IN_HRS])
		formatString: #,0
		lineageTag: 22d40bf0-c8db-4907-8eb4-6cfbc2c7133b

		changedProperty = Name

		changedProperty = FormatString

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Actual Work' = SUM(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACTUAL_WRK])
		formatString: #,0.00
		lineageTag: 4176294f-6c72-41ba-8831-f70a56405300

		changedProperty = Name

		changedProperty = FormatString

	measure ACTUAL_WRK_QTD = ```
			
			TOTALQTD(
			    SUM('EDW_T_FACT_PRD_TMCONFS_CUR_D'[ACTUAL_WRK_IN_HRS]), 
			    'EDW_T_D_MST_DATE_CUR_D'[THE_DATE]
			)
			```
		formatString: #,0.00
		lineageTag: 6d1ce54e-d820-498f-bc22-26f943aa7b46

		changedProperty = Name

		changedProperty = FormatString

	measure 'Hours of Original' =
			
			CALCULATE(
			    SUM(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACTUAL_WRK_IN_HRS]),
			    FILTER(
			        EDW_T_FACT_PRD_TMCONFS_CUR_D,
			        VALUE(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACCT_IND]) = 0 ||
			        (VALUE(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACCT_IND]) >= 41 &&
			         VALUE(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACCT_IND]) <= 50)
			    )
			)
		formatString: #,0.00
		lineageTag: ae7bf6ce-d68d-47d7-84ae-0e8e2fe095b6

		changedProperty = Name

		changedProperty = FormatString

	measure 'Hours of Change' =
			
			CALCULATE(
			    SUM(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACTUAL_WRK_IN_HRS]),
			    FILTER(
			        EDW_T_FACT_PRD_TMCONFS_CUR_D,
			        VALUE(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACCT_IND]) >= 1 &&
			        VALUE(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACCT_IND]) <= 40
			    )
			)
		formatString: #,0.00
		lineageTag: dab7b044-12a5-4f0f-8f82-e5ff27027796

		changedProperty = Name

		changedProperty = FormatString

	measure 'Hours of Rework Internal' =
			CALCULATE(
			    SUM(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACTUAL_WRK_IN_HRS]),
			    FILTER(
			        EDW_T_FACT_PRD_TMCONFS_CUR_D,
			        VALUE(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACCT_IND]) >= 51 &&
			        VALUE(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACCT_IND]) <= 65
			    )
			)
		formatString: #,0.00
		lineageTag: 3ac0eadd-3c80-4947-acc6-8b8572b84d97

		changedProperty = Name

		changedProperty = FormatString

	measure 'Hours of Rework External' =
			CALCULATE(
			    SUM(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACTUAL_WRK_IN_HRS]),
			    FILTER(
			        EDW_T_FACT_PRD_TMCONFS_CUR_D,
			        VALUE(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACCT_IND]) >= 76 &&
			        VALUE(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACCT_IND]) <= 90
			    )
			)
		formatString: #,0.00
		lineageTag: 72892d10-522f-438d-a399-ffac679da2c8

		changedProperty = Name

		changedProperty = FormatString

	measure 'Hours of Rework Ext w/Change' =
			CALCULATE(
			    SUM(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACTUAL_WRK_IN_HRS]),
			    FILTER(
			        EDW_T_FACT_PRD_TMCONFS_CUR_D,
			        VALUE(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACCT_IND]) >= 66 &&
			        VALUE(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACCT_IND]) <= 75
			    )
			)
		formatString: #,0.00
		lineageTag: b5461937-c9f5-4115-be17-54c0d2a26c00

		changedProperty = Name

		changedProperty = FormatString

	measure 'Hours of Approval' =
			CALCULATE(
			    SUM(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACTUAL_WRK_IN_HRS]),
			    FILTER(
			        EDW_T_FACT_PRD_TMCONFS_CUR_D,
			        VALUE(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACCT_IND]) >= 91 &&
			        VALUE(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACCT_IND]) <= 99
			    )
			)
		formatString: #,0.00
		lineageTag: 1f1ec3a2-e457-41de-b438-53d1386e08c3

		changedProperty = Name

		changedProperty = FormatString

	measure 'Flex Force Hours' =
			CALCULATE(
			    SUM(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACTUAL_WRK_IN_HRS]),'OPERATING_PLANT'[PLNT_ID]= "5064"
			    )
		formatString: #,0.00
		lineageTag: 7a6daffe-1218-4ede-b364-06dae3f7426e

		changedProperty = Name

		changedProperty = FormatString

	measure 'Smart Sourced Hours Low Cost' =
			CALCULATE(
			    SUM(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACTUAL_WRK_IN_HRS]), 'OPERATING_PLANT'[PLNT_ID] IN { "5049", "5054", "5151", "5150", "5154", "5053", "5126", "5058", "5903", "4639" }
			) + 0
		formatString: #,0.00
		lineageTag: fd0fb446-fc70-4371-911e-05ff649ae1b4

		changedProperty = Name

		changedProperty = FormatString

	measure 'Planning Plant Hours' =
			
			CALCULATE(
			    SUM(EDW_T_FACT_PRD_TMCONFS_CUR_D[ACTUAL_WRK_IN_HRS]),
			    FILTER(
			        EDW_T_FACT_PRD_TMCONFS_CUR_D,
			        RELATED(OPERATING_PLANT[PLNT_ID]) = RELATED(PLANNING_PLANT[PLNT_ID])
			    )
			) + 0
		formatString: #,0.00
		lineageTag: 964b77f3-8d8d-496a-b5e3-2940a81f4c11

		changedProperty = Name

		changedProperty = FormatString

	measure 'Smart Sourced Hours Other' = [Actual Work in Hours] -([Flex Force Hours]+[Planning Plant Hours]+[Smart Sourced Hours Low Cost])
		formatString: #,0.00
		lineageTag: 4f606f19-7ffc-43c9-9216-bbaf04f59489

		changedProperty = Name

		changedProperty = FormatString

	measure 'Percentage Smart Sourced' =
			DIVIDE(
			    [Smart Sourced Hours Low Cost],
			    [Actual Work in Hours]
			    ) +0
		formatString: 0.00
		lineageTag: a3c87b96-fc49-4302-bddf-746a2057079d

		changedProperty = Name

		changedProperty = FormatString

	measure %SmartSourced =
			DIVIDE(
			    [Smart Sourced Hours Low Cost],
			    [Actual Work in Hours]
			    ) +0
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: dbcbfa30-66a4-43a7-9b65-4a89e965bde4

		changedProperty = Name

		changedProperty = FormatString

	column SEG_CD_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: a4c4c757-e370-4837-bf17-42831226a611
		sourceLineageTag: SEG_CD_KEY
		summarizeBy: none
		sourceColumn: SEG_CD_KEY

		annotation SummarizationSetBy = Automatic

	column OPERATION_TASK_LIST_ID
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 3763892b-5fc8-4d1e-96c0-3e6fed25fa79
		sourceLineageTag: OPERATION_TASK_LIST_ID
		summarizeBy: count
		sourceColumn: OPERATION_TASK_LIST_ID

		annotation SummarizationSetBy = Automatic

	column OPERATION_COUNTER_ID
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: b0ef9f16-a6e7-4bf1-941a-bd4016b32213
		sourceLineageTag: OPERATION_COUNTER_ID
		summarizeBy: count
		sourceColumn: OPERATION_COUNTER_ID

		annotation SummarizationSetBy = Automatic

	column OPERATION_ACTIVITY_ID
		dataType: string
		sourceProviderType: varchar(8)
		lineageTag: 6f301a6f-a8cf-44f9-bfa8-ad4820e04887
		sourceLineageTag: OPERATION_ACTIVITY_ID
		summarizeBy: none
		sourceColumn: OPERATION_ACTIVITY_ID

		annotation SummarizationSetBy = Automatic

	column OPERATION_CONFIRM_ID
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 8bd0d12e-f6f4-427b-ae6b-5ec4f1d3cf5c
		sourceLineageTag: OPERATION_CONFIRM_ID
		summarizeBy: count
		sourceColumn: OPERATION_CONFIRM_ID

		annotation SummarizationSetBy = Automatic

	column OPERATION_SEQ_ID
		dataType: string
		sourceProviderType: varchar(6)
		lineageTag: d972146e-cde1-4283-adaf-7818c5476486
		sourceLineageTag: OPERATION_SEQ_ID
		summarizeBy: none
		sourceColumn: OPERATION_SEQ_ID

		annotation SummarizationSetBy = Automatic

	column PROFT_CNTR_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 645c6f09-e608-4143-9121-c865f7048364
		sourceLineageTag: PROFT_CNTR_KEY
		summarizeBy: none
		sourceColumn: PROFT_CNTR_KEY

		annotation SummarizationSetBy = Automatic

	column SALES_ORDER_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 2725c985-abd3-435b-84ea-f00e7f7f7048
		sourceLineageTag: SALES_ORDER_KEY
		summarizeBy: none
		sourceColumn: SALES_ORDER_KEY

		annotation SummarizationSetBy = Automatic

	column SALES_ORDER_ITM_NBR
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 78c9a944-45d4-42b6-8f67-354bde05a768
		sourceLineageTag: SALES_ORDER_ITM_NBR
		summarizeBy: none
		sourceColumn: SALES_ORDER_ITM_NBR

		annotation SummarizationSetBy = Automatic

	column CMPNY_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: f605c17f-adb0-4590-bb17-12edce3ef53a
		sourceLineageTag: CMPNY_KEY
		summarizeBy: none
		sourceColumn: CMPNY_KEY

		annotation SummarizationSetBy = Automatic

	column WRK_CNTR_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 21eda9b4-c6f3-483f-8930-2a75c7eda067
		sourceLineageTag: WRK_CNTR_KEY
		summarizeBy: none
		sourceColumn: WRK_CNTR_KEY

		annotation SummarizationSetBy = Automatic

	column COST_CNTR_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: c674101d-aaca-4968-9ea7-bd1b94bcf5ff
		sourceLineageTag: COST_CNTR_KEY
		summarizeBy: none
		sourceColumn: COST_CNTR_KEY

		annotation SummarizationSetBy = Automatic

	column OPERATION_STD_TEXT
		dataType: string
		sourceProviderType: varchar(14)
		lineageTag: c265599a-4ccb-4f2d-9aab-b801cbc77eca
		sourceLineageTag: OPERATION_STD_TEXT
		summarizeBy: none
		sourceColumn: OPERATION_STD_TEXT

		annotation SummarizationSetBy = Automatic

	column OPERATION_SHORT_TEXT
		dataType: string
		sourceProviderType: varchar(80)
		lineageTag: 761278cc-241d-4fee-b4ab-f5f5c1b505ee
		sourceLineageTag: OPERATION_SHORT_TEXT
		summarizeBy: none
		sourceColumn: OPERATION_SHORT_TEXT

		annotation SummarizationSetBy = Automatic

	column PSTNG_DATE_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 28bb2685-2331-465c-9fa2-17f577fcde29
		sourceLineageTag: PSTNG_DATE_KEY
		summarizeBy: none
		sourceColumn: PSTNG_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column PLNG_PLNT_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: f2c1c217-2502-416c-b0e7-95ee04f13dde
		sourceLineageTag: PLNG_PLNT_KEY
		summarizeBy: none
		sourceColumn: PLNG_PLNT_KEY

		annotation SummarizationSetBy = Automatic

	column ENTRY_CREATE_DATE
		dataType: dateTime
		formatString: General Date
		sourceProviderType: date
		lineageTag: fd664f58-013e-40a7-879c-b96ce47cae03
		sourceLineageTag: ENTRY_CREATE_DATE
		summarizeBy: none
		sourceColumn: ENTRY_CREATE_DATE

		annotation SummarizationSetBy = Automatic

	column PERSON_WHO_ENTERERD
		dataType: string
		sourceProviderType: varchar(12)
		lineageTag: e68829f8-9b70-4b7b-b96c-efd29076d377
		sourceLineageTag: PERSON_WHO_ENTERERD
		summarizeBy: none
		sourceColumn: PERSON_WHO_ENTERERD

		annotation SummarizationSetBy = Automatic

	column OPERATION_CONFIRM_COUNTER
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 2445259e-ba55-4654-909b-00d527b2ea12
		sourceLineageTag: OPERATION_CONFIRM_COUNTER
		summarizeBy: sum
		sourceColumn: OPERATION_CONFIRM_COUNTER

		annotation SummarizationSetBy = Automatic

	column ACTUAL_WRK
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		sourceProviderType: decimal(8, 2)
		lineageTag: c18c56f3-463e-4bf0-94ee-d668ecd130b2
		sourceLineageTag: ACTUAL_WRK
		summarizeBy: sum
		sourceColumn: ACTUAL_WRK

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column ACTUAL_WRK_UOM
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 363ebeb0-ca7e-4b3a-b3b9-c24354966655
		sourceLineageTag: ACTUAL_WRK_UOM
		summarizeBy: none
		sourceColumn: ACTUAL_WRK_UOM

		annotation SummarizationSetBy = Automatic

	column ACCTNG_IND
		dataType: string
		sourceProviderType: varchar(2)
		lineageTag: 99bf8b40-ad5a-4b8e-853b-819ace011ded
		sourceLineageTag: ACCTNG_IND
		summarizeBy: none
		sourceColumn: ACCTNG_IND

		annotation SummarizationSetBy = Automatic

	column REMG_WRK
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		sourceProviderType: decimal(8, 2)
		lineageTag: 1bb77bb2-f726-481e-a017-a0820b9ec729
		sourceLineageTag: REMG_WRK
		summarizeBy: sum
		sourceColumn: REMG_WRK

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column REMG_WRK_UOM
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: 920dca28-af1f-4ea8-a1b9-6c8f7298e020
		sourceLineageTag: REMG_WRK_UOM
		summarizeBy: none
		sourceColumn: REMG_WRK_UOM

		annotation SummarizationSetBy = Automatic

	column ACTUAL_WRK_IN_HRS
		dataType: decimal
		sourceProviderType: decimal(8, 2)
		lineageTag: 9e0152a5-37a8-4d7a-836e-6e5606dd5a32
		sourceLineageTag: ACTUAL_WRK_IN_HRS
		summarizeBy: sum
		sourceColumn: ACTUAL_WRK_IN_HRS

		changedProperty = FormatString

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column REMG_WRK_IN_HRS
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		sourceProviderType: decimal(8, 2)
		lineageTag: e8714af7-ccb8-43fd-b0f1-3443fcfdfc34
		sourceLineageTag: REMG_WRK_IN_HRS
		summarizeBy: sum
		sourceColumn: REMG_WRK_IN_HRS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column WRK_IN_HRS_UOM
		dataType: string
		sourceProviderType: varchar(3)
		lineageTag: e32a6071-1df7-432f-a4f9-6a068e46a824
		sourceLineageTag: WRK_IN_HRS_UOM
		summarizeBy: none
		sourceColumn: WRK_IN_HRS_UOM

		annotation SummarizationSetBy = Automatic

	column ACTIVITY_TYP_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 3349925f-363f-44a8-b1f0-d3d8ba423c9b
		sourceLineageTag: ACTIVITY_TYP_KEY
		summarizeBy: none
		sourceColumn: ACTIVITY_TYP_KEY

		annotation SummarizationSetBy = Automatic

	column OPERATION_CONFIRM_TEXT
		dataType: string
		sourceProviderType: varchar(40)
		lineageTag: 4236701c-524b-4c36-a8b8-9393b0d79e29
		sourceLineageTag: OPERATION_CONFIRM_TEXT
		summarizeBy: none
		sourceColumn: OPERATION_CONFIRM_TEXT

		annotation SummarizationSetBy = Automatic

	column RSN_FOR_VRNC
		dataType: string
		sourceProviderType: varchar(4)
		lineageTag: e4cb0e70-ac2b-4f5c-8a12-18ca0f669a97
		sourceLineageTag: RSN_FOR_VRNC
		summarizeBy: none
		sourceColumn: RSN_FOR_VRNC

		annotation SummarizationSetBy = Automatic

	column CONFIRM_COUNTER_OF_CANCELLED_CO
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 9c25af7f-7768-4a7c-abbf-d86349731df1
		sourceLineageTag: CONFIRM_COUNTER_OF_CANCELLED_CO
		summarizeBy: sum
		sourceColumn: CONFIRM_COUNTER_OF_CANCELLED_CO

		annotation SummarizationSetBy = Automatic

	column SOLD_TO_CUST_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 796ddafe-9a1c-42b3-965d-4de2d90798be
		sourceLineageTag: SOLD_TO_CUST_KEY
		summarizeBy: none
		sourceColumn: SOLD_TO_CUST_KEY

		annotation SummarizationSetBy = Automatic

	column PERSONEL_NUM_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: ff5eed62-2b7d-4ab7-b52c-0131687d4c73
		sourceLineageTag: PERSONEL_NUM_KEY
		summarizeBy: none
		sourceColumn: PERSONEL_NUM_KEY

		annotation SummarizationSetBy = Automatic

	column ETL_SRC_SYS_CD
		dataType: string
		sourceProviderType: varchar(10)
		lineageTag: 51bd7840-d7a9-4303-9ee4-1e7ede8072c2
		sourceLineageTag: ETL_SRC_SYS_CD
		summarizeBy: none
		sourceColumn: ETL_SRC_SYS_CD

		annotation SummarizationSetBy = Automatic

	column ETL_CREATED_TS
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 158b4afa-e220-4025-b8c1-88e96c6abf0a
		sourceLineageTag: ETL_CREATED_TS
		summarizeBy: none
		sourceColumn: ETL_CREATED_TS

		annotation SummarizationSetBy = Automatic

	column ETL_UPDTD_TS
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: b4e1a692-8e3e-4669-952d-512b3f4210b8
		sourceLineageTag: ETL_UPDTD_TS
		summarizeBy: none
		sourceColumn: ETL_UPDTD_TS

		annotation SummarizationSetBy = Automatic

	column SERVC_ORDER_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: aba2c744-92bc-4339-8445-5236957ddc59
		sourceLineageTag: SERVC_ORDER_KEY
		summarizeBy: none
		sourceColumn: SERVC_ORDER_KEY

		annotation SummarizationSetBy = Automatic

	column SALES_AREA_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 52ea8101-6c1c-4886-b8cf-c5ed81a27f0c
		sourceLineageTag: SALES_AREA_KEY
		summarizeBy: none
		sourceColumn: SALES_AREA_KEY

		annotation SummarizationSetBy = Automatic

	column OPERATING_PLNT_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 63dd1378-0627-4616-b8a6-6efa374cff4c
		sourceLineageTag: OPERATING_PLNT_KEY
		summarizeBy: none
		sourceColumn: OPERATING_PLNT_KEY

		annotation SummarizationSetBy = Automatic

	column SERVC_ORDER_CREATE_DATE_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 1365db6b-0a93-4685-87d3-5cf20e945b94
		sourceLineageTag: SERVC_ORDER_CREATE_DATE_KEY
		summarizeBy: none
		sourceColumn: SERVC_ORDER_CREATE_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column ACCT_IND
		dataType: string
		sourceProviderType: varchar(18)
		lineageTag: b0a741cb-78ad-48ef-a4a3-ef2b7f81d23c
		sourceLineageTag: ACCT_IND
		summarizeBy: none
		sourceColumn: ACCT_IND

		annotation SummarizationSetBy = Automatic

	column PARNT_CUST_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 1772331e-e259-48fb-87be-13c61db2034a
		sourceLineageTag: PARNT_CUST_KEY
		summarizeBy: none
		sourceColumn: PARNT_CUST_KEY

		annotation SummarizationSetBy = Automatic

	column RSN_FOR_VRNC_DESC
		dataType: string
		sourceProviderType: varchar(30)
		lineageTag: 6257db9c-8dff-460e-be4c-78c60ffdd9d8
		sourceLineageTag: RSN_FOR_VRNC_DESC
		summarizeBy: none
		sourceColumn: RSN_FOR_VRNC_DESC

		annotation SummarizationSetBy = Automatic

	column PARTIAL_FINAL_CONFIRM
		dataType: string
		sourceProviderType: varchar(1)
		lineageTag: 9aa5bb9b-9c07-4837-bd40-a00e9068a333
		sourceLineageTag: PARTIAL_FINAL_CONFIRM
		summarizeBy: none
		sourceColumn: PARTIAL_FINAL_CONFIRM

		annotation SummarizationSetBy = Automatic

	column TCHNCL_COMPLETION_DATE_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: cdda81d9-dbb3-4b60-a93d-0ee040369298
		sourceLineageTag: TCHNCL_COMPLETION_DATE_KEY
		summarizeBy: none
		sourceColumn: TCHNCL_COMPLETION_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column SALES_ORDER_ID
		dataType: string
		sourceProviderType: varchar(10)
		lineageTag: dd14b810-ed54-4335-a4b7-a0c5fea5e4d1
		sourceLineageTag: SALES_ORDER_ID
		summarizeBy: none
		sourceColumn: SALES_ORDER_ID

		annotation SummarizationSetBy = Automatic

	column ACCTNG_IND_DESC
		dataType: string
		sourceProviderType: varchar(25)
		lineageTag: 47c886cb-be74-4233-83c6-b65ff01b5c85
		sourceLineageTag: ACCTNG_IND_DESC
		summarizeBy: none
		sourceColumn: ACCTNG_IND_DESC

		annotation SummarizationSetBy = Automatic

	column SERV_ORDER_INVOICE_CREATED_DATE_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 07caa0af-c331-4010-a2ee-a89bff0aaa49
		sourceLineageTag: SERV_ORDER_INVOICE_CREATED_DATE_KEY
		summarizeBy: none
		sourceColumn: SERV_ORDER_INVOICE_CREATED_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column OPERATING_PLANT_REGION_PLANT
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: 85581743-364c-46dd-977e-acd29b218c94
		sourceLineageTag: OPERATING_PLANT_REGION_PLANT
		summarizeBy: none
		sourceColumn: OPERATING_PLANT_REGION_PLANT

		annotation SummarizationSetBy = Automatic

	column PLANNING_PLANT_REGION_PLANT
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: e2767e15-7125-43ce-a291-bf62f895a433
		sourceLineageTag: PLANNING_PLANT_REGION_PLANT
		summarizeBy: none
		sourceColumn: PLANNING_PLANT_REGION_PLANT

		annotation SummarizationSetBy = Automatic

	column PERSONNEL_PLANT_REGION_PLANT
		dataType: string
		sourceProviderType: varchar(255)
		lineageTag: 7f8a7648-24eb-497b-b785-150e24a66607
		sourceLineageTag: PERSONNEL_PLANT_REGION_PLANT
		summarizeBy: none
		sourceColumn: PERSONNEL_PLANT_REGION_PLANT

		annotation SummarizationSetBy = Automatic

	column PARENT_CUST_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: b96aaf6a-dc20-45de-9e90-cf78d1896e0c
		sourceLineageTag: PARENT_CUST_KEY
		summarizeBy: none
		sourceColumn: PARENT_CUST_KEY

		annotation SummarizationSetBy = Automatic

	column PAYER_CUST_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: f1f5190b-1b49-4fab-b1de-8936a2f96842
		sourceLineageTag: PAYER_CUST_KEY
		summarizeBy: none
		sourceColumn: PAYER_CUST_KEY

		annotation SummarizationSetBy = Automatic

	column SHIP_TO_CUST_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 34607ffd-fb37-4855-98cb-d901b5a8469c
		sourceLineageTag: SHIP_TO_CUST_KEY
		summarizeBy: none
		sourceColumn: SHIP_TO_CUST_KEY

		annotation SummarizationSetBy = Automatic

	column BRAND_OWNER_CUST_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: e4f2fe9e-2a81-43bf-a2dd-42f57695bdfb
		sourceLineageTag: BRAND_OWNER_CUST_KEY
		summarizeBy: none
		sourceColumn: BRAND_OWNER_CUST_KEY

		annotation SummarizationSetBy = Automatic

	column CUST_CONTACT_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 39f06c71-de7d-4dda-96db-6c6b1ca5837d
		sourceLineageTag: CUST_CONTACT_KEY
		summarizeBy: none
		sourceColumn: CUST_CONTACT_KEY

		annotation SummarizationSetBy = Automatic

	column PERSON_RESP_PERSONNEL_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: f4afa034-821d-4eac-bfb9-1208ef9bf1a5
		sourceLineageTag: PERSON_RESP_PERSONNEL_KEY
		summarizeBy: none
		sourceColumn: PERSON_RESP_PERSONNEL_KEY

		annotation SummarizationSetBy = Automatic

	column CYLINDER_OWNER_CUST_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: e10c4564-9fe9-40da-911d-0e013ece7cb6
		sourceLineageTag: CYLINDER_OWNER_CUST_KEY
		summarizeBy: none
		sourceColumn: CYLINDER_OWNER_CUST_KEY

		annotation SummarizationSetBy = Automatic

	column AGENCY_CUST_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 9da9ef79-3174-4d8a-aff8-89e0032dc4c9
		sourceLineageTag: AGENCY_CUST_KEY
		summarizeBy: none
		sourceColumn: AGENCY_CUST_KEY

		annotation SummarizationSetBy = Automatic

	column PRINTER_CUST_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 9613dc5d-e7b6-4e5d-ad73-da3e2e0a64bb
		sourceLineageTag: PRINTER_CUST_KEY
		summarizeBy: none
		sourceColumn: PRINTER_CUST_KEY

		annotation SummarizationSetBy = Automatic

	column SUPPLIER_CUST_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 5d0ecfb6-799e-42d9-bf7d-2e946b2ddf3a
		sourceLineageTag: SUPPLIER_CUST_KEY
		summarizeBy: none
		sourceColumn: SUPPLIER_CUST_KEY

		annotation SummarizationSetBy = Automatic

	column EMPLOYEE_RESP_PERSONEL_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: a38d513a-5b09-4e06-9041-74d34404d42e
		sourceLineageTag: EMPLOYEE_RESP_PERSONEL_KEY
		summarizeBy: none
		sourceColumn: EMPLOYEE_RESP_PERSONEL_KEY

		annotation SummarizationSetBy = Automatic

	column EMPLOYEE_RESP_2_PERSONEL_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 6a9dae08-e6bf-4c82-83c2-57d9463c03b9
		sourceLineageTag: EMPLOYEE_RESP_2_PERSONEL_KEY
		summarizeBy: none
		sourceColumn: EMPLOYEE_RESP_2_PERSONEL_KEY

		annotation SummarizationSetBy = Automatic

	column FORWARDING_AGENT_VENDOR_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: cd63cdf5-40af-47de-a386-9448dcae49f1
		sourceLineageTag: FORWARDING_AGENT_VENDOR_KEY
		summarizeBy: none
		sourceColumn: FORWARDING_AGENT_VENDOR_KEY

		annotation SummarizationSetBy = Automatic

	column UNITIZATION_AGENT_VENDOR_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: f98dfe8a-0f6d-4cb3-b453-f0b11b6741e5
		sourceLineageTag: UNITIZATION_AGENT_VENDOR_KEY
		summarizeBy: none
		sourceColumn: UNITIZATION_AGENT_VENDOR_KEY

		annotation SummarizationSetBy = Automatic

	column ORDER_FOR_CUSTOMER_ADDR_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: f750a5f9-19f5-4e9a-bf2e-8685070b0252
		sourceLineageTag: ORDER_FOR_CUSTOMER_ADDR_KEY
		summarizeBy: none
		sourceColumn: ORDER_FOR_CUSTOMER_ADDR_KEY

		annotation SummarizationSetBy = Automatic

	column SO_PARENT_CUST_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 6e09c093-6133-4589-9a9c-0b587c4a6a2b
		sourceLineageTag: SO_PARENT_CUST_KEY
		summarizeBy: none
		sourceColumn: SO_PARENT_CUST_KEY

		annotation SummarizationSetBy = Automatic

	column BILL_TO_CUST_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 13acd75e-9ea8-45db-846a-6fe8751cc676
		sourceLineageTag: BILL_TO_CUST_KEY
		summarizeBy: none
		sourceColumn: BILL_TO_CUST_KEY

		annotation SummarizationSetBy = Automatic

	column CUSTOMER_PROJECT_MANAGER_CUST_CONTACT_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 914d5a40-5226-4165-9dce-8b9e2ecf8c7d
		sourceLineageTag: CUSTOMER_PROJECT_MANAGER_CUST_CONTACT_KEY
		summarizeBy: none
		sourceColumn: CUSTOMER_PROJECT_MANAGER_CUST_CONTACT_KEY

		annotation SummarizationSetBy = Automatic

	column SALES_PERSON_PERSONEL_KEY
		dataType: int64
		formatString: 0
		sourceProviderType: int
		lineageTag: 124fb828-82a5-4a39-892c-45164929a42b
		sourceLineageTag: SALES_PERSON_PERSONEL_KEY
		summarizeBy: none
		sourceColumn: SALES_PERSON_PERSONEL_KEY

		annotation SummarizationSetBy = Automatic

	partition EDW_T_FACT_PRD_TMCONFS_CUR_D = entity
		mode: directLake
		source
			entityName: EDW_T_Fact_PRD_TMCONFS_CUR_D
			schemaName: Propelis
			expressionSource: DatabaseQuery

	changedProperty = Name

	annotation PBI_ResultType = Table

