CREATE TABLE [Propelis].[ACTUAL_RELEASE_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Actual Release Date] date NULL, 
	[Actual Release Fiscal Year] int NULL, 
	[Actual Release Fiscal Period Number] int NULL, 
	[Actual Release Fiscal Period Code] varchar(max) NULL, 
	[Actual Release Fiscal Quarter Number] int NULL, 
	[Actual Release Fiscal Quarter Code] varchar(max) NULL, 
	[Actual Release Calendar Year] int NULL, 
	[Actual Release Calendar Month Number] int NULL, 
	[Actual Release Calendar Month Code] varchar(max) NULL, 
	[Actual Release Calendar Month Description] varchar(max) NULL, 
	[Actual Release Calendar Quarter Number] int NULL, 
	[Actual Release Calendar Quarter Code] varchar(max) NULL, 
	[Actual Release Calendar Weekday Number] int NULL, 
	[Actual Release Calendar Weekday Name] varchar(max) NULL, 
	[Actual Release Calendar Day In Month] int NULL, 
	[Actual Release Calendar Day In Year] int NULL, 
	[Actual Release Calendar Week] int NULL, 
	[Actual Release Calendar Month In Quarter Number] int NULL, 
	[Actual Release Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Actual Release Current Day Flag] int NULL, 
	[Actual Release Current Day Minus 1 Flag] int NULL, 
	[Actual Release Current Calendar Week Flag] int NULL, 
	[Actual Release Current Calendar Week Minus 1 Flag] int NULL, 
	[Actual Release Current Month Flag] int NULL, 
	[Actual Release Current Month Minus 1 Flag] int NULL, 
	[Actual Release Current Month Minus 12 Flag] int NULL, 
	[Actual Release Current Quarter Flag] int NULL, 
	[Actual Release Current Quarter Minus 1 Flag] int NULL, 
	[Actual Release Current Quarter Minus 4 Flag] int NULL, 
	[Actual Release Current Calendar Year Flag] int NULL, 
	[Actual Release Current Calendar Year Minus 1 Flag] int NULL, 
	[Actual Release Current Calendar Year Minus 2 Flag] int NULL, 
	[Actual Release Current Fiscal Year Flag] int NULL, 
	[Actual Release Current Fiscal Year Minus 1 Flag] int NULL, 
	[Actual Release Current Fiscal Year Minus 2 Flag] int NULL, 
	[Actual Release Current Calendar Year Plus 1 Flag] int NULL, 
	[CURR_FISCAL_YR_PLUS_1_FLG] int NULL, 
	[Actual Release Day In Fiscal Year] int NULL, 
	[Actual Release Date Is Weekday] int NULL, 
	[Actual Release Fiscal Week] int NULL, 
	[Actual Release Current Fiscal Week Flag] int NULL, 
	[Actual Release Current Fiscal Week Minus 1 Flag] int NULL, 
	[Actual Release Fiscal Weekday Number] int NULL, 
	[Actual Release Fiscal Weekday Name] varchar(max) NULL, 
	[Actual Release Current Month Minus 2 Flag] int NULL, 
	[Actual Release Current Fiscal Week Minus 2 Flag] int NULL, 
	[Actual Release Current Fiscal Week Minus 6 Flag] int NULL, 
	[Actual Release Current Fiscal Week Minus 3 Flag] int NULL, 
	[Actual Release Current Fiscal Week Minus 4 Flag] int NULL, 
	[Actual Release Current Fiscal Week Minus 5 Flag] int NULL, 
	[Actual Release Current Fiscal Week Minus 7 Flag] int NULL
);