CREATE TABLE [Propelis].[ACTUAL_FINISH_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Actual Finish Date] date NULL, 
	[Actual Finish Fiscal Year] int NULL, 
	[Actual Finish Fiscal Period Number] int NULL, 
	[Actual Finish Fiscal Period Code] varchar(max) NULL, 
	[Actual Finish Fiscal Quarter Number] int NULL, 
	[Actual Finish Fiscal Quarter Code] varchar(max) NULL, 
	[Actual Finish Calendar Year] int NULL, 
	[Actual Finish Calendar Month Number] int NULL, 
	[Actual Finish Calendar Month Code] varchar(max) NULL, 
	[Actual Finish Calendar Month Description] varchar(max) NULL, 
	[Actual Finish Calendar Quarter Number] int NULL, 
	[Actual Finish Calendar Quarter Code] varchar(max) NULL, 
	[Actual Finish Calendar Weekday Number] int NULL, 
	[Actual Finish Calendar Weekday Name] varchar(max) NULL, 
	[Actual Finish Calendar Day In Month] int NULL, 
	[Actual Finish Calendar Day In Year] int NULL, 
	[Actual Finish Calendar Week] int NULL, 
	[Actual Finish Calendar Month In Quarter Number] int NULL, 
	[Actual Finish Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Actual Finish Current Day Flag] int NULL, 
	[Actual Finish Current Day Minus 1 Flag] int NULL, 
	[Actual Finish Current Calendar Week Flag] int NULL, 
	[Actual Finish Current Calendar Week Minus 1 Flag] int NULL, 
	[Actual Finish Current Month Flag] int NULL, 
	[Actual Finish Current Month Minus 1 Flag] int NULL, 
	[Actual Finish Current Month Minus 12 Flag] int NULL, 
	[Actual Finish Current Quarter Flag] int NULL, 
	[Actual Finish Current Quarter Minus 1 Flag] int NULL, 
	[Actual Finish Current Quarter Minus 4 Flag] int NULL, 
	[Actual Finish Current Calendar Year Flag] int NULL, 
	[Actual Finish Current Calendar Year Minus 1 Flag] int NULL, 
	[Actual Finish Current Calendar Year Minus 2 Flag] int NULL, 
	[Actual Finish Current Fiscal Year Flag] int NULL, 
	[Actual Finish Current Fiscal Year Minus 1 Flag] int NULL, 
	[Actual Finish Current Fiscal Year Minus 2 Flag] int NULL, 
	[Actual Finish Current Calendar Year Plus 1 Flag] int NULL, 
	[CURR_FISCAL_YR_PLUS_1_FLG] int NULL, 
	[Actual Finish Day In Fiscal Year] int NULL, 
	[Actual Finish Date Is Weekday] int NULL, 
	[Actual Finish Fiscal Week] int NULL, 
	[Actual Finish Current Fiscal Week Flag] int NULL, 
	[Actual Finish Current Fiscal Week Minus 1 Flag] int NULL, 
	[Actual Finish Fiscal Weekday Number] int NULL, 
	[Actual Finish Fiscal Weekday Name] varchar(max) NULL, 
	[Actual Finish Current Month Minus 2 Flag] int NULL, 
	[Actual Finish Current Fiscal Week Minus 2 Flag] int NULL, 
	[Actual Finish Current Fiscal Week Minus 6 Flag] int NULL, 
	[Actual Finish Current Fiscal Week Minus 3 Flag] int NULL, 
	[Actual Finish Current Fiscal Week Minus 4 Flag] int NULL, 
	[Actual Finish Current Fiscal Week Minus 5 Flag] int NULL, 
	[Actual Finish Current Fiscal Week Minus 7 Flag] int NULL
);