CREATE TABLE [Propelis].[ACTUAL_START_EXEC_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Actual Start Exec Date] date NULL, 
	[Actual Start Exec Fiscal Year] int NULL, 
	[Actual Start Exec Fiscal Period Number] int NULL, 
	[Actual Start Exec Fiscal Period Code] varchar(max) NULL, 
	[Actual Start Exec Fiscal Quarter Number] int NULL, 
	[Actual Start Exec Fiscal Quarter Code] varchar(max) NULL, 
	[Actual Start Exec Calendar Year] int NULL, 
	[Actual Start Exec Calendar Month Number] int NULL, 
	[Actual Start Exec Calendar Month Code] varchar(max) NULL, 
	[Actual Start Exec Calendar Month Description] varchar(max) NULL, 
	[Actual Start Exec Calendar Quarter Number] int NULL, 
	[Actual Start Exec Calendar Quarter Code] varchar(max) NULL, 
	[Actual Start Exec Calendar Weekday Number] int NULL, 
	[Actual Start Exec Calendar Weekday Name] varchar(max) NULL, 
	[Actual Start Exec Calendar Day In Month] int NULL, 
	[Actual Start Exec Calendar Day In Year] int NULL, 
	[Actual Start Exec Calendar Week] int NULL, 
	[Actual Start Exec Calendar Month In Quarter Number] int NULL, 
	[Actual Start Exec Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Actual Start Exec Current Day Flag] int NULL, 
	[Actual Start Exec Current Day Minus 1 Flag] int NULL, 
	[Actual Start Exec Current Calendar Week Flag] int NULL, 
	[Actual Start Exec Current Calendar Week Minus 1 Flag] int NULL, 
	[Actual Start Exec Current Month Flag] int NULL, 
	[Actual Start Exec Current Month Minus 1 Flag] int NULL, 
	[Actual Start Exec Current Month Minus 12 Flag] int NULL, 
	[Actual Start Exec Current Quarter Flag] int NULL, 
	[Actual Start Exec Current Quarter Minus 1 Flag] int NULL, 
	[Actual Start Exec Current Quarter Minus 4 Flag] int NULL, 
	[Actual Start Exec Current Calendar Year Flag] int NULL, 
	[Actual Start Exec Current Calendar Year Minus 1 Flag] int NULL, 
	[Actual Start Exec Current Calendar Year Minus 2 Flag] int NULL, 
	[Actual Start Exec Current Fiscal Year Flag] int NULL, 
	[Actual Start Exec Current Fiscal Year Minus 1 Flag] int NULL, 
	[Actual Start Exec Current Fiscal Year Minus 2 Flag] int NULL, 
	[Actual Start Exec Current Calendar Year Plus 1 Flag] int NULL, 
	[Actual Start Exec Current Calendar Year Plus 2 Flag] int NULL, 
	[Actual Start Exec Day In Fiscal Year] int NULL, 
	[Actual Start Exec Date Is Weekday] int NULL, 
	[Actual Start Exec Fiscal Week] int NULL, 
	[Actual Start Exec Current Fiscal Week Flag] int NULL, 
	[Actual Start Exec Current Fiscal Week Minus 1 Flag] int NULL, 
	[Actual Start Exec Fiscal Weekday Number] int NULL, 
	[Actual Start Exec Fiscal Weekday Name] varchar(max) NULL, 
	[Actual Start Exec Current Month Minus 2 Flag] int NULL, 
	[Actual Start Exec Current Fiscal Week Minus 2 Flag] int NULL, 
	[Actual Start Exec Current Fiscal Week Minus 6 Flag] int NULL, 
	[Actual Start Exec Current Fiscal Week Minus 3 Flag] int NULL, 
	[Actual Start Exec Current Fiscal Week Minus 4 Flag] int NULL, 
	[Actual Start Exec Current Fiscal Week Minus 5 Flag] int NULL, 
	[Actual Start Exec Current Fiscal Week Minus 7 Flag] int NULL
);