CREATE TABLE [Propelis].[ACTUAL_START_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Actual Start Date] date NULL, 
	[Actual Start Fiscal Year] int NULL, 
	[Actual Start Fiscal Period Number] int NULL, 
	[Actual Start Fiscal Period Code] varchar(max) NULL, 
	[Actual Start Fiscal Quarter Number] int NULL, 
	[Actual Start Fiscal Quarter Code] varchar(max) NULL, 
	[Actual Start Calendar Year] int NULL, 
	[Actual Start Calendar Month Number] int NULL, 
	[Actual Start Calendar Month Code] varchar(max) NULL, 
	[Actual Start Calendar Month Description] varchar(max) NULL, 
	[Actual Start Calendar Quarter Number] int NULL, 
	[Actual Start Calendar Quarter Code] varchar(max) NULL, 
	[Actual Start Calendar Weekday Number] int NULL, 
	[Actual Start Calendar Weekday Name] varchar(max) NULL, 
	[Actual Start Calendar Day In Month] int NULL, 
	[Actual Start Calendar Day In Year] int NULL, 
	[Actual Start Calendar Week] int NULL, 
	[Actual Start Calendar Month In Quarter Number] int NULL, 
	[Actual Start Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Actual Start Current Day Flag] int NULL, 
	[Actual Start Current Day Minus 1 Flag] int NULL, 
	[Actual Start Current Calendar Week Flag] int NULL, 
	[Actual Start Current Calendar Week Minus 1 Flag] int NULL, 
	[Actual Start Current Month Flag] int NULL, 
	[Actual Start Current Month Minus 1 Flag] int NULL, 
	[Actual Start Current Month Minus 12 Flag] int NULL, 
	[Actual Start Current Quarter Flag] int NULL, 
	[Actual Start Current Quarter Minus 1 Flag] int NULL, 
	[Actual Start Current Quarter Minus 4 Flag] int NULL, 
	[Actual Start Current Calendar Year Flag] int NULL, 
	[Actual Start Current Calendar Year Minus 1 Flag] int NULL, 
	[Actual Start Current Calendar Year Minus 2 Flag] int NULL, 
	[Actual Start Current Fiscal Year Flag] int NULL, 
	[Actual Start Current Fiscal Year Minus 1 Flag] int NULL, 
	[Actual Start Current Fiscal Year Minus 2 Flag] int NULL, 
	[Actual Start Current Calendar Year Plus 1 Flag] int NULL, 
	[CURR_FISCAL_YR_PLUS_1_FLG] int NULL, 
	[Actual Start Day In Fiscal Year] int NULL, 
	[Actual Start Date Is Weekday] int NULL, 
	[Actual Start Fiscal Week] int NULL, 
	[Actual Start Current Fiscal Week Flag] int NULL, 
	[Actual Start Current Fiscal Week Minus 1 Flag] int NULL, 
	[Actual Start Fiscal Weekday Number] int NULL, 
	[Actual Start Fiscal Weekday Name] varchar(max) NULL, 
	[Actual Start Current Month Minus 2 Flag] int NULL, 
	[Actual Start Current Fiscal Week Minus 2 Flag] int NULL, 
	[Actual Start Current Fiscal Week Minus 6 Flag] int NULL, 
	[Actual Start Current Fiscal Week Minus 3 Flag] int NULL, 
	[Actual Start Current Fiscal Week Minus 4 Flag] int NULL, 
	[Actual Start Current Fiscal Week Minus 5 Flag] int NULL, 
	[Actual Start Current Fiscal Week Minus 7 Flag] int NULL
);