CREATE TABLE [Propelis].[BASELINE_DUE_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Baseline Due Date] date NULL, 
	[Baseline Due Fiscal Year] int NULL, 
	[Baseline Due Fiscal Period Number] int NULL, 
	[Baseline Due Fiscal Period] varchar(max) NULL, 
	[Baseline Due Fiscal Quarter Number] int NULL, 
	[Baseline Due Fiscal Quarter Code] varchar(max) NULL, 
	[Baseline Due Calendar Year] int NULL, 
	[Baseline Due Calendar Month Number] int NULL, 
	[Baseline Due Calendar Month] varchar(max) NULL, 
	[Baseline Due Calendar Month Description] varchar(max) NULL, 
	[Baseline Due Calendar Quarter Number] int NULL, 
	[Baseline Due Calendar Quarter Code] varchar(max) NULL, 
	[Baseline Due Calendar Weekday Number] int NULL, 
	[Baseline Due Calendar Weekday Name] varchar(max) NULL, 
	[Baseline Due Calendar Day In Month] int NULL, 
	[Baseline Due Calendar Day In Year] int NULL, 
	[Baseline Due Calendar Week] int NULL, 
	[Baseline Due Calendar Month In Quarter Number] int NULL, 
	[Baseline Due Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Baseline Due Current Day Flag] int NULL, 
	[Baseline Due Current Day Minus 1 Flag] int NULL, 
	[Baseline Due Current Calendar Week Flag] int NULL, 
	[Baseline Due Current Calendar Week Minus 1 Flag] int NULL, 
	[Baseline Due Current Month Flag] int NULL, 
	[Baseline Due Current Month Minus 1 Flag] int NULL, 
	[Baseline Due Current Month Minus 2 Flag] int NULL, 
	[Baseline Due Current Month Minus 12 Flag] int NULL, 
	[Baseline Due Current Quarter Flag] int NULL, 
	[Baseline Due Current Quarter Minus 1 Flag] int NULL, 
	[Baseline Due Current Quarter Minus 4 Flag] int NULL, 
	[Baseline Due Current Calendar Year Flag] int NULL, 
	[Baseline Due Current Calendar Year Minus 1 Flag] int NULL, 
	[Baseline Due Current Calendar Year Minus 2 Flag] int NULL, 
	[Baseline Due Current Calendar Year Plus 1 Flag] int NULL, 
	[Baseline Due Current Fiscal Year Flag] int NULL, 
	[Baseline Due Current Fiscal Year Minus 1 Flag] int NULL, 
	[Baseline Due Current Fiscal Year Minus 2 Flag] int NULL, 
	[Baseline Due Current Fiscal Year Plus 1 Flag] int NULL, 
	[Baseline Due Day in Fiscal Year] int NULL, 
	[Baseline Due Date Is Weekday] int NULL, 
	[Clearing Fiscal Week] int NULL, 
	[Baseline Due Current Fiscal Week Flag] int NULL, 
	[Baseline Due Current Fiscal Week Minus 1 Flag] int NULL, 
	[Baseline Due Current Fiscal Week Minus 2 Flag] int NULL, 
	[Baseline Due Current Fiscal Week Minus 3 Flag] int NULL, 
	[Baseline Due Current Fiscal Week Minus 4 Flag] int NULL, 
	[Baseline Due Current Fiscal Week Minus 5 Flag] int NULL, 
	[Baseline Due Current Fiscal Week Minus 6 Flag] int NULL, 
	[Baseline Due Current Fiscal Week Minus 7 Flag] int NULL, 
	[Baseline Due Fiscal Weekday Number] int NULL, 
	[Baseline Due Fiscal Weekday Name] varchar(max) NULL
);