CREATE TABLE [Propelis].[BASIC_START_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Basic Start Date] date NULL, 
	[Basic Start Fiscal Year] int NULL, 
	[Basic Start Fiscal Period Number] int NULL, 
	[Basic Start Fiscal Period Code] varchar(max) NULL, 
	[Basic Start Fiscal Quarter Number] int NULL, 
	[Basic Start Fiscal Quarter Code] varchar(max) NULL, 
	[Basic Start Calendar Year] int NULL, 
	[Basic Start Calendar Month Number] int NULL, 
	[Basic Start Calendar Month Code] varchar(max) NULL, 
	[Basic Start Calendar Month Description] varchar(max) NULL, 
	[Basic Start Calendar Quarter Number] int NULL, 
	[Basic Start Calendar Quarter Code] varchar(max) NULL, 
	[Basic Start Calendar Weekday Number] int NULL, 
	[Basic Start Calendar Weekday Name] varchar(max) NULL, 
	[Basic Start Calendar Day In Month] int NULL, 
	[Basic Start Calendar Day In Year] int NULL, 
	[Basic Start Calendar Week] int NULL, 
	[Basic Start Calendar Month In Quarter Number] int NULL, 
	[Basic Start Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Basic Start Current Day Flag] int NULL, 
	[Basic Start Current Day Minus 1 Flag] int NULL, 
	[Basic Start Current Calendar Week Flag] int NULL, 
	[Basic Start Current Calendar Week Minus 1 Flag] int NULL, 
	[Basic Start Current Month Flag] int NULL, 
	[Basic Start Current Month Minus 1 Flag] int NULL, 
	[Basic Start Current Month Minus 12 Flag] int NULL, 
	[Basic Start Current Quarter Flag] int NULL, 
	[Basic Start Current Quarter Minus 1 Flag] int NULL, 
	[Basic Start Current Quarter Minus 4 Flag] int NULL, 
	[Basic Start Current Calendar Year Flag] int NULL, 
	[Basic Start Current Calendar Year Minus 1 Flag] int NULL, 
	[Basic Start Current Calendar Year Minus 2 Flag] int NULL, 
	[Basic Start Current Fiscal Year Flag] int NULL, 
	[Basic Start Current Fiscal Year Minus 1 Flag] int NULL, 
	[Basic Start Current Fiscal Year Minus 2 Flag] int NULL, 
	[Basic Start Current Calendar Year Plus 1 Flag] int NULL, 
	[CURR_FISCAL_YR_PLUS_1_FLG] int NULL, 
	[Basic Start Day In Fiscal Year] int NULL, 
	[Basic Start Date Is Weekday] int NULL, 
	[Basic Start Fiscal Week] int NULL, 
	[Basic Start Current Fiscal Week Flag] int NULL, 
	[Basic Start Current Fiscal Week Minus 1 Flag] int NULL, 
	[Basic Start Fiscal Weekday Number] int NULL, 
	[Basic Start Fiscal Weekday Name] varchar(max) NULL, 
	[Basic Start Current Month Minus 2 Flag] int NULL, 
	[Basic Start Current Fiscal Week Minus 2 Flag] int NULL, 
	[Basic Start Current Fiscal Week Minus 6 Flag] int NULL, 
	[Basic Start Current Fiscal Week Minus 3 Flag] int NULL, 
	[Basic Start Current Fiscal Week Minus 4 Flag] int NULL, 
	[Basic Start Current Fiscal Week Minus 5 Flag] int NULL, 
	[Basic Start Current Fiscal Week Minus 7 Flag] int NULL
);