CREATE TABLE [Propelis].[BILL_TO_CUST] (

	[CUST_KEY] int NOT NULL, 
	[Bill To Customer ID] varchar(max) NULL, 
	[Bill To Customer Legacy ID] varchar(max) NULL, 
	[Bill To Customer Name] varchar(max) NULL, 
	[Bill To Cust Line 2 Description] varchar(max) NULL, 
	[Bill To Cust Country Code] varchar(max) NULL, 
	[Bill To Cust Plant ID] varchar(max) NULL, 
	[Bill To Cust Segment ID] varchar(max) NULL, 
	[Bill To Cust Industry] varchar(max) NULL, 
	[Bill To Cust Vendor ID] varchar(max) NULL, 
	[Bill To Cust Group Code] varchar(max) NULL, 
	[Bill To Cust Account Group Code] varchar(max) NULL, 
	[Bill To Cust Title] varchar(max) NULL, 
	[Bill To Cust Search Term] varchar(max) NULL, 
	[Bill To Cust Street] varchar(max) NULL, 
	[Bill To Cust City] varchar(max) NULL, 
	[Bill To Cust Zip Code] varchar(max) NULL, 
	[Bill To Cust State Code] varchar(max) NULL, 
	[Bill To Cust Region Code] varchar(max) NULL, 
	[Bill To Cust Telephone Number 1] varchar(max) NULL, 
	[Bill To Cust Telephone Number 2] varchar(max) NULL, 
	[Bill To Cust Fax Number Code] varchar(max) NULL, 
	[Bill To Cust Tax Number 1 Code] varchar(max) NULL, 
	[Bill To Cust Tax Number 2 Code] varchar(max) NULL, 
	[Bill To Cust VAT Number Code] varchar(max) NULL, 
	[Bill To Cust Credit Limit] decimal(15,3) NULL, 
	[Bill To Cust Bonus Rate] decimal(9,3) NULL, 
	[Bill To Cust Express Station] varchar(max) NULL, 
	[Bill To Cust Transport Zone] varchar(max) NULL, 
	[Bill To Cust Printer Location Characteristics] varchar(max) NULL, 
	[Bill To Cust Printer Region Characteristics] varchar(max) NULL, 
	[Bill To Cust Printer Site Characteristics] varchar(max) NULL, 
	[Bill To Cust Created Date] date NULL, 
	[Bill To Cust Created User ID] varchar(max) NULL, 
	[Bill To Cust Updated Date] date NULL, 
	[Bill To Cust Updated User ID] varchar(max) NULL, 
	[Bill To Cust Payment Terms Code] varchar(max) NULL, 
	[Bill To Cust Sales Distribution] varchar(max) NULL, 
	[Bill To Cust Order Block For Sales Area] varchar(max) NULL, 
	[Bill To Cust Delivery Block For Sales Area] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Bill To Cust Corporate Group] varchar(max) NULL, 
	[Bill To Cust Customer Classification] varchar(max) NULL, 
	[Bill To Cust Classification Description] varchar(max) NULL, 
	[Bill To Cust Printer Location] varchar(max) NULL, 
	[Bill To Cust Printer Site] varchar(max) NULL, 
	[Bill To Cust Printer Region] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 01] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 02] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 03] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 04] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 05] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 06] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 07] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 08] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 09] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 10] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 11] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 12] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 13] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 14] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 15] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 16] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 17] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 18] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 19] varchar(max) NULL, 
	[Bill To Cust Specific Field Label 20] varchar(max) NULL, 
	[Bill To Cust Condition Group 1] varchar(max) NULL, 
	[Bill To Cust Industry Code 1] varchar(max) NULL, 
	[Bill To Cust Industry Code 2] varchar(max) NULL, 
	[Bill To Cust Industry Description] varchar(max) NULL, 
	[Bill To Cust Industry Code 1 Description] varchar(max) NULL, 
	[Bill To Cust Industry Code 2 Description] varchar(max) NULL, 
	[Bill To Cust Assignment to Hierarchy] int NULL, 
	[Bill To Cust Account Group Description] varchar(max) NULL, 
	[Bill To Cust Region Description] varchar(max) NULL, 
	[Bill To Cust Country Description] varchar(max) NULL, 
	[Bill To Cust Transportation Zone Description] varchar(max) NULL, 
	[Bill To Cust Plant Description] varchar(max) NULL, 
	[Bill To Cust Condition Group Description] varchar(max) NULL, 
	[Bill To Cust Cental Billing Block] varchar(max) NULL, 
	[Bill To Cust Cental Billing Block Description] varchar(max) NULL, 
	[Bill To Cust Central Delivery Block] varchar(max) NULL, 
	[Bill To Cust Central Delivery Block Description] varchar(max) NULL, 
	[Bill To Cust Deletion Indicator] varchar(max) NULL, 
	[Bill To Cust Central Posting Block] varchar(max) NULL, 
	[Bill To Cust Tax Jurisdiction] varchar(max) NULL, 
	[Bill To Cust Central Sales Block] varchar(max) NULL, 
	[Bill To Cust Central Deletion Indicator] varchar(max) NULL, 
	[Bill To Cust Language Key] varchar(max) NULL, 
	[Bill To Cust Trading Partner] varchar(max) NULL, 
	[Bill To Cust Trading Partner Description] varchar(max) NULL, 
	[Bill To Cust Annual Sales] decimal(8,2) NULL, 
	[Bill To Cust Annual Sales Year] int NULL, 
	[Bill To Cust Sales Currency] varchar(max) NULL, 
	[Bill To Cust Sales Currency Description] varchar(max) NULL, 
	[Bill To Cust One Time Account Group] varchar(max) NULL, 
	[Bill To Cust One Time Account Group Description] varchar(max) NULL, 
	[Bill To Cust One Time Indicator] varchar(max) NULL, 
	[Bill To Cust Industry Type] varchar(max) NULL, 
	[Bill To Cust Business Type] varchar(max) NULL, 
	[Bill To Cust DUNS Number] varchar(max) NULL, 
	[Bill To Cust DUNS Plus 4] varchar(max) NULL, 
	[Bill To City Coordinates] varchar(max) NULL, 
	[Bill To Cust Tax Number 4 Code] varchar(max) NULL, 
	[Bill To Cust Attribute 3] varchar(max) NULL, 
	[Bill To Cust Attribute 3 Description] varchar(max) NULL, 
	[Bill To Cust E-Mail Address] varchar(max) NULL, 
	[Bill To Cust Mobile Number] varchar(max) NULL, 
	[Bill To Cust Search Term 2] varchar(max) NULL, 
	[Bill To Cust Street 2] varchar(max) NULL, 
	[Bill To Cust Street 3] varchar(max) NULL, 
	[Bill To Cust Street 4] varchar(max) NULL, 
	[Bill To Cust Street 5] varchar(max) NULL, 
	[Bill To Cust PO Box] varchar(max) NULL, 
	[Bill To Cust PO Box Postal Code] varchar(max) NULL, 
	[Bill To Cust PO Box City] varchar(max) NULL, 
	[Bill To Cust Region For PO Box] varchar(max) NULL, 
	[Bill To Cust PO Box Country] varchar(max) NULL, 
	[Bill To Cust Transportation Zone] varchar(max) NULL, 
	[Bill To Cust Address Notes] varchar(max) NULL, 
	[Bill To Cust Tax Number 3 Code] varchar(max) NULL, 
	[Bill To Cust Tax Number 5 Code] varchar(max) NULL, 
	[Bill To Cust Industry Code 3] varchar(max) NULL, 
	[Bill To Cust Industry Code 3 Description] varchar(max) NULL, 
	[Bill To Cust Industry Code 4] varchar(max) NULL, 
	[Bill To Cust Industry Code 4 Description] varchar(max) NULL, 
	[Bill To Cust Industry Code 5] varchar(max) NULL, 
	[Bill To Cust Industry Code 5 Description] varchar(max) NULL, 
	[Bill To Cust Central Order Block For Customer] varchar(max) NULL, 
	[Bill To Cust Payment Block] varchar(max) NULL
);