CREATE TABLE [Propelis].[CLEARING_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Clearing Date] date NULL, 
	[Clearing Fiscal Year] varchar(max) NULL, 
	[Clearing Fiscal Period Number] int NULL, 
	[Clearing Fiscal Period] varchar(max) NULL, 
	[Clearing Fiscal Quarter Number] int NULL, 
	[Clearing Fiscal Quarter Code] varchar(max) NULL, 
	[Clearing Calendar Year] int NULL, 
	[Clearing Calendar Month Number] int NULL, 
	[Clearing Calendar Month] varchar(max) NULL, 
	[Clearing Calendar Month Description] varchar(max) NULL, 
	[Clearing Calendar Quarter Number] int NULL, 
	[Clearing Calendar Quarter Code] varchar(max) NULL, 
	[Clearing Calendar Weekday Number] int NULL, 
	[Clearing Calendar Weekday Name] varchar(max) NULL, 
	[Clearing Calendar Day In Month] int NULL, 
	[Clearing Calendar Day In Year] int NULL, 
	[Clearing Calendar Week] int NULL, 
	[Clearing Calendar Month In Quarter Number] int NULL, 
	[Clearing Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Clearing Current Day Flag] varchar(1) NULL, 
	[Clearing Current Day Minus 1 Flag] varchar(1) NULL, 
	[Clearing Current Calendar Week Flag] varchar(1) NULL, 
	[Clearing Current Calendar Week Minus 1 Flag] varchar(1) NULL, 
	[Clearing Current Month Flag] varchar(1) NULL, 
	[Clearing Current Month Minus 1 Flag] varchar(1) NULL, 
	[Clearing Current Month Minus 12 Flag] varchar(1) NULL, 
	[Clearing Current Quarter Flag] varchar(1) NULL, 
	[Clearing Current Quarter Minus 1 Flag] varchar(1) NULL, 
	[Clearing Current Quarter Minus 4 Flag] varchar(1) NULL, 
	[Clearing Current Calendar Year Flag] varchar(1) NULL, 
	[Clearing Current Calendar Year Minus 1 Flag] varchar(1) NULL, 
	[Clearing Current Calendar Year Minus 2 Flag] varchar(1) NULL, 
	[Clearing Current Fiscal Year Flag] varchar(1) NULL, 
	[Clearing Current Fiscal Year Minus 1 Flag] varchar(1) NULL, 
	[Clearing Current Fiscal Year Minus 2 Flag] varchar(1) NULL, 
	[Clearing Current Calendar Year Plus 1 Flag] varchar(1) NULL, 
	[Clearing Current Fiscal Year Plus 1 Flag] varchar(1) NULL, 
	[Clearing Day in Fiscal Year] int NULL, 
	[Clearing Date Is Weekday] varchar(1) NULL, 
	[Clearing Fiscal Week] int NULL, 
	[Clearing Current Fiscal Week Flag] varchar(1) NULL, 
	[Clearing Current Fiscal Week Minus 1 Flag] varchar(1) NULL, 
	[Clearing Fiscal Weekday Number] int NULL, 
	[Clearing Fiscal Weekday Name] varchar(max) NULL, 
	[Clearing Current Month Minus 2 Flag] varchar(1) NULL, 
	[Clearing Current Fiscal Week Minus 2 Flag] varchar(1) NULL, 
	[Clearing Current Fiscal Week Minus 6 Flag] varchar(1) NULL, 
	[Clearing Current Fiscal Week Minus 3 Flag] varchar(1) NULL, 
	[Clearing Current Fiscal Week Minus 4 Flag] varchar(1) NULL, 
	[Clearing Current Fiscal Week Minus 5 Flag] varchar(1) NULL, 
	[Clearing Current Fiscal Week Minus 7 Flag] varchar(1) NULL
);