CREATE TABLE [Propelis].[CLOSE_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Close Date] date NULL, 
	[Close Fiscal Year] int NULL, 
	[Close Fiscal Period Number] int NULL, 
	[Close Fiscal Period Code] varchar(max) NULL, 
	[Close Fiscal Quarter Number] int NULL, 
	[Close Fiscal Quarter Code] varchar(max) NULL, 
	[Close Calendar Year] int NULL, 
	[Close Calendar Month Number] int NULL, 
	[Close Calendar Month Code] varchar(max) NULL, 
	[Close Calendar Month Description] varchar(max) NULL, 
	[Close Calendar Quarter Number] int NULL, 
	[Close Calendar Quarter Code] varchar(max) NULL, 
	[Close Calendar Weekday Number] int NULL, 
	[Close Calendar Weekday Name] varchar(max) NULL, 
	[Close Calendar Day In Month] int NULL, 
	[Close Calendar Day In Year] int NULL, 
	[Close Calendar Week] int NULL, 
	[Close Calendar Month In Quarter Number] int NULL, 
	[Close Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Close Current Day Flag] int NULL, 
	[Close Current Day Minus 1 Flag] int NULL, 
	[Close Current Calendar Week Flag] int NULL, 
	[Close Current Calendar Week Minus 1 Flag] int NULL, 
	[Close Current Month Flag] int NULL, 
	[Close Current Month Minus 1 Flag] int NULL, 
	[Close Current Month Minus 12 Flag] int NULL, 
	[Close Current Quarter Flag] int NULL, 
	[Close Current Quarter Minus 1 Flag] int NULL, 
	[Close Current Quarter Minus 4 Flag] int NULL, 
	[Close Current Calendar Year Flag] int NULL, 
	[Close Current Calendar Year Minus 1 Flag] int NULL, 
	[Close Current Calendar Year Minus 2 Flag] int NULL, 
	[Close Current Fiscal Year Flag] int NULL, 
	[Close Current Fiscal Year Minus 1 Flag] int NULL, 
	[Close Current Fiscal Year Minus 2 Flag] int NULL, 
	[Close Current Calendar Year Plus 1 Flag] int NULL, 
	[Close Current Calendar Year Plus 2 Flag] int NULL, 
	[Close Day In Fiscal Year] int NULL, 
	[Close Date Is Weekday] int NULL, 
	[Close Fiscal Week] int NULL, 
	[Close Current Fiscal Week Flag] int NULL, 
	[Close Current Fiscal Week Minus 1 Flag] int NULL, 
	[Close Fiscal Weekday Number] int NULL, 
	[Close Fiscal Weekday Name] varchar(max) NULL, 
	[Close Current Month Minus 2 Flag] int NULL, 
	[Close Current Fiscal Week Minus 2 Flag] int NULL, 
	[Close Current Fiscal Week Minus 6 Flag] int NULL, 
	[Close Current Fiscal Week Minus 3 Flag] int NULL, 
	[Close Current Fiscal Week Minus 4 Flag] int NULL, 
	[Close Current Fiscal Week Minus 5 Flag] int NULL, 
	[Close Current Fiscal Week Minus 7 Flag] int NULL
);