CREATE TABLE [Propelis].[COMPANY_INFO] (

	[CMPNY_KEY] int NOT NULL, 
	[Company Code] varchar(max) NULL, 
	[Legacy Company Code] varchar(max) NULL, 
	[Company Name] varchar(max) NULL, 
	[Line Of Business] varchar(max) NULL, 
	[Line Of Business Description] varchar(max) NULL, 
	[Currency Code] varchar(max) NULL, 
	[Language Type Code] varchar(max) NULL, 
	[Chart Of Accounts ID] varchar(max) NULL, 
	[Entity Address Line 1] varchar(max) NULL, 
	[Entity Address Line 2] varchar(max) NULL, 
	[Entity City Name] varchar(max) NULL, 
	[Entity Zip Code] varchar(max) NULL, 
	[Entity Country Code] varchar(max) NULL, 
	[Entity Telephone1] varchar(max) NULL, 
	[Entity Telephone 2] varchar(max) NULL, 
	[Fax Number] varchar(max) NULL, 
	[Tax Jurisdiction] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Fiscal Year Variant] varchar(max) NULL, 
	[Credit Control Area] varchar(max) NULL, 
	[Input Tax Code] varchar(max) NULL, 
	[Output Tax Code] varchar(max) NULL, 
	[Currency Description] varchar(max) NULL, 
	[Chart Of Accounts Description] varchar(max) NULL, 
	[Country Description] varchar(max) NULL, 
	[Fiscal Year Variant Description] varchar(max) NULL, 
	[Credit Control Area Description] varchar(max) NULL
);