CREATE TABLE [Propelis].[COMPANY] (

	[CMPNY_KEY] int NOT NULL, 
	[Company] varchar(max) NULL, 
	[Company Legacy Code] varchar(max) NULL, 
	[Company Name] varchar(max) NULL, 
	[Company Line Of Business Code] varchar(max) NULL, 
	[Company Line Of Business Code Description] varchar(max) NULL, 
	[Company Currency Code] varchar(max) NULL, 
	[Company Language Type Code] varchar(max) NULL, 
	[Company Chart Of Accounts ID] varchar(max) NULL, 
	[Company Address Line 1] varchar(max) NULL, 
	[Company Address Line 2] varchar(max) NULL, 
	[Company City Name] varchar(max) NULL, 
	[Company Zip Code] varchar(max) NULL, 
	[Company Country Code] varchar(max) NULL, 
	[Company Telephone 1] varchar(max) NULL, 
	[Company Telephone 2] varchar(max) NULL, 
	[Company Fax Number] varchar(max) NULL, 
	[Company Tax Jurisdiction] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Company Fiscal Year Variant] varchar(max) NULL, 
	[Company Credit Control Area] varchar(max) NULL, 
	[Company Input Tax Cd] varchar(max) NULL, 
	[Company Output Tax Code] varchar(max) NULL, 
	[Company Currency Description] varchar(max) NULL, 
	[Company Chart Of Accounts Description] varchar(max) NULL, 
	[Company Country Description] varchar(max) NULL, 
	[Company Fiscal Year Variant Description] varchar(max) NULL, 
	[Company Credit Control Area Description] varchar(max) NULL
);