CREATE TABLE [Propelis].[CREATE_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Create Date] date NULL, 
	[Create Fiscal Year] int NULL, 
	[Create Fiscal Period Number] int NULL, 
	[Create Fiscal Period Code] varchar(max) NULL, 
	[Create Fiscal Quarter Number] int NULL, 
	[Create Fiscal Quarter Code] varchar(max) NULL, 
	[Create Calendar Year] int NULL, 
	[Create Calendar Month Number] int NULL, 
	[Create Calendar Month Code] varchar(max) NULL, 
	[Create Calendar Month Description] varchar(max) NULL, 
	[Create Calendar Quarter Number] int NULL, 
	[Create Calendar Quarter Code] varchar(max) NULL, 
	[Create Calendar Weekday Number] int NULL, 
	[Create Calendar Weekday Name] varchar(max) NULL, 
	[Create Calendar Day In Month] int NULL, 
	[Create Calendar Day In Year] int NULL, 
	[Create Calendar Week] int NULL, 
	[Create Calendar Month In Quarter Number] int NULL, 
	[Create Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Create Current Day Flag] int NULL, 
	[Create Current Day Minus 1 Flag] int NULL, 
	[Create Current Calendar Week Flag] int NULL, 
	[Create Current Calendar Week Minus 1 Flag] int NULL, 
	[Create Current Month Flag] int NULL, 
	[Create Current Month Minus 1 Flag] int NULL, 
	[Create Current Month Minus 12 Flag] int NULL, 
	[Create Current Quarter Flag] int NULL, 
	[Create Current Quarter Minus 1 Flag] int NULL, 
	[Create Current Quarter Minus 4 Flag] int NULL, 
	[Create Current Calendar Year Flag] int NULL, 
	[Create Current Calendar Year Minus 1 Flag] int NULL, 
	[Create Current Calendar Year Minus 2 Flag] int NULL, 
	[Create Current Fiscal Year Flag] int NULL, 
	[Create Current Fiscal Year Minus 1 Flag] int NULL, 
	[Create Current Fiscal Year Minus 2 Flag] int NULL, 
	[Create Current Calendar Year Plus 1 Flag] int NULL, 
	[Create Current Fiscal Year Plus 1 Flag] int NULL, 
	[Create Day In Fiscal Year] int NULL, 
	[Create Is Weekday] int NULL, 
	[Create Fiscal Week] int NULL, 
	[Create Current Fiscal Week Flag] int NULL, 
	[Create Current Fiscal Week Minus 1 Flag] int NULL, 
	[Create Fiscal Weekday Number] int NULL, 
	[Create Fiscal Weekday Name] varchar(max) NULL, 
	[Create Current Month Minus 2 Flag] int NULL, 
	[Create Current Fiscal Week Minus 2 Flag] int NULL, 
	[Create Current Fiscal Week Minus 6 Flag] int NULL, 
	[Create Current Fiscal Week Minus 3 Flag] int NULL, 
	[Create Current Fiscal Week Minus 4 Flag] int NULL, 
	[Create Current Fiscal Week Minus 5 Flag] int NULL, 
	[Create Current Fiscal Week Minus 7 Flag] int NULL
);