CREATE TABLE [Propelis].[CREATED_ON_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Created On Date] date NULL, 
	[Created On Fiscal Year] int NULL, 
	[Created On Fiscal Period Number] int NULL, 
	[Created On Fiscal Period Code] varchar(max) NULL, 
	[Created On Fiscal Quarter Number] int NULL, 
	[Created On Fiscal Quarter Code] varchar(max) NULL, 
	[Created On Calendar Year] int NULL, 
	[Created On Calendar Month Number] int NULL, 
	[Created On Calendar Month Code] varchar(max) NULL, 
	[Created On Calendar Month Description] varchar(max) NULL, 
	[Created On Calendar Quarter Number] int NULL, 
	[Created On Calendar Quarter Code] varchar(max) NULL, 
	[Created On Calendar Weekday Number] int NULL, 
	[Created On Calendar Weekday Name] varchar(max) NULL, 
	[Created On Calendar Day In Month] int NULL, 
	[Created On Calendar Day In Year] int NULL, 
	[Created On Calendar Week] int NULL, 
	[Created On Calendar Month In Quarter Number] int NULL, 
	[Created On Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Created On Current Day Flag] int NULL, 
	[Created On Current Day Minus 1 Flag] int NULL, 
	[Created On Current Calendar Week Flag] int NULL, 
	[Created On Current Calendar Week Minus 1 Flag] int NULL, 
	[Created On Current Month Flag] int NULL, 
	[Created On Current Month Minus 1 Flag] int NULL, 
	[Created On Current Month Minus 12 Flag] int NULL, 
	[Created On Current Quarter Flag] int NULL, 
	[Created On Current Quarter Minus 1 Flag] int NULL, 
	[Created On Current Quarter Minus 4 Flag] int NULL, 
	[Created On Current Calendar Year Flag] int NULL, 
	[Created On Current Calendar Year Minus 1 Flag] int NULL, 
	[Created On Current Calendar Year Minus 2 Flag] int NULL, 
	[Created On Current Fiscal Year Flag] int NULL, 
	[Created On Current Fiscal Year Minus 1 Flag] int NULL, 
	[Created On Current Fiscal Year Minus 2 Flag] int NULL, 
	[Created On Current Calendar Year Plus 1 Flag] int NULL, 
	[CURR_FISCAL_YR_PLUS_1_FLG] int NULL, 
	[Created On Day In Fiscal Year] int NULL, 
	[Created On Date Is Weekday] int NULL, 
	[Created On Fiscal Week] int NULL, 
	[Created On Current Fiscal Week Flag] int NULL, 
	[Created On Current Fiscal Week Minus 1 Flag] int NULL, 
	[Created On Fiscal Weekday Number] int NULL, 
	[Created On Fiscal Weekday Name] varchar(max) NULL, 
	[Created On Current Month Minus 2 Flag] int NULL, 
	[Created On Current Fiscal Week Minus 2 Flag] int NULL, 
	[Created On Current Fiscal Week Minus 6 Flag] int NULL, 
	[Created On Current Fiscal Week Minus 3 Flag] int NULL, 
	[Created On Current Fiscal Week Minus 4 Flag] int NULL, 
	[Created On Current Fiscal Week Minus 5 Flag] int NULL, 
	[Created On Current Fiscal Week Minus 7 Flag] int NULL
);