CREATE TABLE [Propelis].[CUST_HIERARCHY1] (

	[CUST_KEY] int NOT NULL, 
	[Customer Hierarchy1 ID] varchar(max) NULL, 
	[Customer Hierarchy1 Legacy Customer ID] varchar(max) NULL, 
	[Customer Hierarchy1 Name] varchar(max) NULL, 
	[Customer Hierarchy1 Line 2 Description] varchar(max) NULL, 
	[Customer Hierarchy1 Country Code] varchar(max) NULL, 
	[Customer Hierarchy1 Plant ID] varchar(max) NULL, 
	[Customer Hierarchy1 Segment ID] varchar(max) NULL, 
	[Customer Hierarchy1 Industry] varchar(max) NULL, 
	[Customer Hierarchy1 Vendor ID] varchar(max) NULL, 
	[Customer Hierarchy1 Customer Group Code] varchar(max) NULL, 
	[Customer Hierarchy1 Account Group Code] varchar(max) NULL, 
	[Customer Hierarchy1 Title] varchar(max) NULL, 
	[Customer Hierarchy1 Search Term] varchar(max) NULL, 
	[Customer Hierarchy1 Street] varchar(max) NULL, 
	[Customer Hierarchy1 City] varchar(max) NULL, 
	[Customer Hierarchy1 Zip Code] varchar(max) NULL, 
	[Customer Hierarchy1 State Code] varchar(max) NULL, 
	[Customer Hierarchy1 Region Code] varchar(max) NULL, 
	[Customer Hierarchy1 Telephone Number 1] varchar(max) NULL, 
	[Customer Hierarchy1 Telephone Number 2] varchar(max) NULL, 
	[Customer Hierarchy1 Fax Number Code] varchar(max) NULL, 
	[Customer Hierarchy1 Tax Number 1 Code] varchar(max) NULL, 
	[Customer Hierarchy1 Tax Number 2 Code] varchar(max) NULL, 
	[Customer Hierarchy1 VAT Number Code] varchar(max) NULL, 
	[Customer Hierarchy1 Credit Limit] decimal(15,3) NULL, 
	[Customer Hierarchy1 Bonus Rate] decimal(9,3) NULL, 
	[Customer Hierarchy1 Express Station] varchar(max) NULL, 
	[Customer Hierarchy1 Transportation Zone] varchar(max) NULL, 
	[Customer Hierarchy1 Printer Location Characteristics] varchar(max) NULL, 
	[Customer Hierarchy1 Printer Region Characteristics] varchar(max) NULL, 
	[Customer Hierarchy1 Printer Site Characteristics] varchar(max) NULL, 
	[Customer Hierarchy1 Customer Created Date] date NULL, 
	[Customer Hierarchy1 Created User ID] varchar(max) NULL, 
	[Customer Hierarchy1 Customer Updated Date] date NULL, 
	[Customer Hierarchy1 Updated User ID] varchar(max) NULL, 
	[Customer Hierarchy1 Payment Terms Code] varchar(max) NULL, 
	[Customer Hierarchy1 Sales Distribution] varchar(max) NULL, 
	[Customer Hierarchy1 Order Block For Sales Area] varchar(max) NULL, 
	[Customer Hierarchy1 Delivery Block For Sales Area] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Customer Hierarchy1 Corporate Group] varchar(max) NULL, 
	[Customer Hierarchy1 Classification] varchar(max) NULL, 
	[Customer Hierarchy1 Classification Description] varchar(max) NULL, 
	[Customer Hierarchy1 Printer Location] varchar(max) NULL, 
	[Customer Hierarchy1 Printer Site] varchar(max) NULL, 
	[Customer Hierarchy1 Printer Region] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 01] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 02] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 03] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 04] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 05] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 06] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 07] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 08] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 09] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 10] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 11] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 12] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 13] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 14] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 15] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 16] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 17] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 18] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 19] varchar(max) NULL, 
	[Customer Hierarchy1 Specific Field Label 20] varchar(max) NULL, 
	[Customer Hierarchy1 Condition Group 1] varchar(max) NULL, 
	[Customer Hierarchy1 Industry Code 1] varchar(max) NULL, 
	[Customer Hierarchy1 Industry Code 2] varchar(max) NULL, 
	[Customer Hierarchy1 Industry Description] varchar(max) NULL, 
	[Customer Hierarchy1 Industry Code 1 Description] varchar(max) NULL, 
	[Customer Hierarchy1 Industry Code 2 Description] varchar(max) NULL, 
	[Customer Hierarchy1 Assignment to Hierarchy] int NULL, 
	[Customer Hierarchy1 Account Group Description] varchar(max) NULL, 
	[Customer Hierarchy1 Region Description] varchar(max) NULL, 
	[Customer Hierarchy1 Country Description] varchar(max) NULL, 
	[Customer Hierarchy1 Transportation Zone Description] varchar(max) NULL, 
	[Customer Hierarchy1 Plant Description] varchar(max) NULL, 
	[Customer Hierarchy1 Condition Group Description] varchar(max) NULL, 
	[Customer Hierarchy1 Cental Billing Block] varchar(max) NULL, 
	[Customer Hierarchy1 Cental Billing Block Description] varchar(max) NULL, 
	[Customer Hierarchy1 Central Delivery Block] varchar(max) NULL, 
	[Customer Hierarchy1 Central Delivery Block Description] varchar(max) NULL, 
	[Customer Hierarchy1 Deletion Indicator] varchar(max) NULL, 
	[Customer Hierarchy1 Central Posting Block] varchar(max) NULL, 
	[Customer Hierarchy1 Tax Jurisdiction] varchar(max) NULL, 
	[Customer Hierarchy1 Central Sales Block] varchar(max) NULL, 
	[Customer Hierarchy1 Central Deletion Indicator] varchar(max) NULL, 
	[Customer Hierarchy1 Language Key] varchar(max) NULL, 
	[Customer Hierarchy1 Trading Partner] varchar(max) NULL, 
	[Customer Hierarchy1 Trading Partner Description] varchar(max) NULL, 
	[Customer Hierarchy1 Annual Sales] decimal(8,2) NULL, 
	[Customer Hierarchy1 Annual Sales Year] int NULL, 
	[Customer Hierarchy1 Sales Currency] varchar(max) NULL, 
	[Customer Hierarchy1 Sales Currency Description] varchar(max) NULL, 
	[Customer Hierarchy1 One Time Account Group] varchar(max) NULL, 
	[Customer Hierarchy1 One Time Account Group Description] varchar(max) NULL, 
	[Customer Hierarchy1 One Time Indicator] varchar(max) NULL, 
	[Customer Hierarchy1 Industry Type] varchar(max) NULL, 
	[Customer Hierarchy1 Business Type] varchar(max) NULL, 
	[Customer Hierarchy1 DUNS Number] varchar(max) NULL, 
	[Customer Hierarchy1 DUNS Plus 4] varchar(max) NULL, 
	[CITY_COORDINATES] varchar(max) NULL, 
	[TAX_NUM_4_CD] varchar(max) NULL, 
	[ATTRIB_3] varchar(max) NULL, 
	[ATTRIB_3_DESC] varchar(max) NULL, 
	[E_MAIL_ADDR] varchar(max) NULL, 
	[MOBILE_NUM] varchar(max) NULL, 
	[SEARCH_TERM_2] varchar(max) NULL, 
	[STR_2] varchar(max) NULL, 
	[STR_3] varchar(max) NULL, 
	[STR_4] varchar(max) NULL, 
	[STR_5] varchar(max) NULL, 
	[PO_BOX] varchar(max) NULL, 
	[PO_BOX_POSTAL_CD] varchar(max) NULL, 
	[PO_BOX_CITY] varchar(max) NULL, 
	[REGN_FOR_PO_BOX] varchar(max) NULL, 
	[PO_BOX_CNTRY] varchar(max) NULL, 
	[TRNSPRT_ZONE] varchar(max) NULL, 
	[ADDR_NOTES] varchar(max) NULL, 
	[TAX_NUM_3] varchar(max) NULL, 
	[TAX_NUM_5] varchar(max) NULL, 
	[INDUS_CD_3] varchar(max) NULL, 
	[INDUS_CD_3_DESC] varchar(max) NULL, 
	[INDUS_CD_4] varchar(max) NULL, 
	[INDUS_CD_4_DESC] varchar(max) NULL, 
	[INDUS_CD_5] varchar(max) NULL, 
	[INDUS_CD_5_DESC] varchar(max) NULL, 
	[CENTRAL_ORDER_BLK_FOR_CUST] varchar(max) NULL, 
	[PYMT_BLK] varchar(max) NULL
);