CREATE TABLE [Propelis].[CUSTOMER_SERVICE_REP] (

	[PERSONEL_KEY] int NOT NULL, 
	[CSR Personnel Number] varchar(max) NULL, 
	[CSR Company Code] varchar(max) NULL, 
	[CSR Plant ID] varchar(max) NULL, 
	[CSR Cost Center ID] varchar(max) NULL, 
	[CSR Success Factors ID] varchar(max) NULL, 
	[CSR Employee First Name] varchar(max) NULL, 
	[CSR Employee Last Name] varchar(max) NULL, 
	[CSR Employee Full Name] varchar(max) NULL, 
	[CSR Employee Status Indicator] varchar(max) NULL, 
	[CSR Employment Start Date] date NULL, 
	[CSR Employment End Date] date NULL, 
	[CSR Employee Group ID] varchar(max) NULL, 
	[CSR Employee Group Description] varchar(max) NULL, 
	[CSR Employee Subgroup ID] varchar(max) NULL, 
	[CSR Employee Subgroup Description] varchar(max) NULL, 
	[CSR Employee Telephone 1] varchar(max) NULL, 
	[CSR Employee Telephone 2] varchar(max) NULL, 
	[CSR Email Address] varchar(max) NULL, 
	[CSR Created Date] date NULL, 
	[CSR Created User ID] varchar(max) NULL, 
	[CSR Updated Date] date NULL, 
	[CSR Updated User ID] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[CSR Company Description] varchar(max) NULL, 
	[CSR Plant Description] varchar(max) NULL
);