CREATE TABLE [Propelis].[CUSTOMER_PROJECT_MANAGER] (

	[CUST_CONTACT_KEY] int NOT NULL, 
	[CONTACT_PERSON_ID] varchar(10) NULL, 
	[CUST_ID] varchar(10) NULL, 
	[FIRST_NAME] varchar(35) NULL, 
	[NAME] varchar(35) NULL, 
	[CONTACT_PERSON_DEPT] varchar(4) NULL, 
	[CONTACT_PERSON_DEPT_NAME] varchar(35) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);