CREATE TABLE [Propelis].[DISCOVERY_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Discovery Date] date NULL, 
	[Discovery Fiscal Year] int NULL, 
	[Discovery Fiscal Period Number] int NULL, 
	[Discovery Fiscal Period Code] varchar(max) NULL, 
	[Discovery Fiscal Quarter Number] int NULL, 
	[Discovery Fiscal Quarter Code] varchar(max) NULL, 
	[Discovery Calendar Year] int NULL, 
	[Discovery Calendar Month Number] int NULL, 
	[Discovery Calendar Month Code] varchar(max) NULL, 
	[Discovery Calendar Month Description] varchar(max) NULL, 
	[Discovery Calendar Quarter Number] int NULL, 
	[Discovery Calendar Quarter Code] varchar(max) NULL, 
	[Discovery Calendar Weekday Number] int NULL, 
	[Discovery Calendar Weekday Name] varchar(max) NULL, 
	[Discovery Calendar Day In Month] int NULL, 
	[Discovery Calendar Day In Year] int NULL, 
	[Discovery Calendar Week] int NULL, 
	[Discovery Calendar Month In Quarter Number] int NULL, 
	[Discovery Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Discovery Current Day Flag] int NULL, 
	[Discovery Current Day Minus 1 Flag] int NULL, 
	[Discovery Current Calendar Week Flag] int NULL, 
	[Discovery Current Calendar Week Minus 1 Flag] int NULL, 
	[Discovery Current Month Flag] int NULL, 
	[Discovery Current Month Minus 1 Flag] int NULL, 
	[Discovery Current Month Minus 12 Flag] int NULL, 
	[Discovery Current Quarter Flag] int NULL, 
	[Discovery Current Quarter Minus 1 Flag] int NULL, 
	[Discovery Current Quarter Minus 4 Flag] int NULL, 
	[Discovery Current Calendar Year Flag] int NULL, 
	[Discovery Current Calendar Year Minus 1 Flag] int NULL, 
	[Discovery Current Calendar Year Minus 2 Flag] int NULL, 
	[Discovery Current Fiscal Year Flag] int NULL, 
	[Discovery Current Fiscal Year Minus 1 Flag] int NULL, 
	[Discovery Current Fiscal Year Minus 2 Flag] int NULL, 
	[Discovery Current Calendar Year Plus 1 Flag] int NULL, 
	[Discovery Current Fiscal Year Plus 1 Flag] int NULL, 
	[Discovery Day In Fiscal Year] int NULL, 
	[Discovery Is Weekday] int NULL, 
	[Discovery Fiscal Week] int NULL, 
	[Discovery Current Fiscal Week Flag] int NULL, 
	[Discovery Current Fiscal Week Minus 1 Flag] int NULL, 
	[Discovery Fiscal Weekday Number] int NULL, 
	[Discovery Fiscal Weekday Name] varchar(max) NULL, 
	[Discovery Current Month Minus 2 Flag] int NULL, 
	[Discovery Current Fiscal Week Minus 2 Flag] int NULL, 
	[Discovery Current Fiscal Week Minus 6 Flag] int NULL, 
	[Discovery Current Fiscal Week Minus 3 Flag] int NULL, 
	[Discovery Current Fiscal Week Minus 4 Flag] int NULL, 
	[Discovery Current Fiscal Week Minus 5 Flag] int NULL, 
	[Discovery Current Fiscal Week Minus 7 Flag] int NULL
);