CREATE TABLE [Propelis].[DOCUMENT_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Entry Create Date] date NULL, 
	[Entry Create Fiscal Year] int NULL, 
	[Entry Create Fiscal Period] int NULL, 
	[Entry Create Fiscal Period Code] varchar(max) NULL, 
	[Entry Create Fiscal Quarter Number] int NULL, 
	[Entry Create Fiscal Quarter Code] varchar(max) NULL, 
	[Entry Create Calendar Year] int NULL, 
	[Entry Create Calendar Month Number] int NULL, 
	[Entry Create Calendar Month Code] varchar(max) NULL, 
	[Entry Create Calendar Month Description] varchar(max) NULL, 
	[Entry Create Calendar Quarter] int NULL, 
	[Entry Create Calendar Quarter Code] varchar(max) NULL, 
	[Entry Create Calendar Weekday Number] int NULL, 
	[Entry Create Calendar Weekday Name] varchar(max) NULL, 
	[Entry Create Calendar Day in Month] int NULL, 
	[Entry Create Calendar Day in Year] int NULL, 
	[Entry Create Calendar Week] int NULL, 
	[Entry Create Calendar Month in Quarter Number] int NULL, 
	[Entry Create Calendar Days in Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Entry Create Current Day Flag] int NULL, 
	[Entry Create Current Day Minus 1 Flag] int NULL, 
	[Entry Create Current Calendar Week Flag] int NULL, 
	[Entry Create Current Calendar Week Minus 1 Flag] int NULL, 
	[Entry Create Current Month Flag] int NULL, 
	[Entry Create Current Month Minus 1 Flag] int NULL, 
	[Entry Create Current Month Minus 12 Flag] int NULL, 
	[Entry Create Current Quarter Flag] int NULL, 
	[Entry Create Current Quarter Minus 1 Flag] int NULL, 
	[Entry Create Current Quarter Minus 4 Flag] int NULL, 
	[Entry Create Current Calendar Year Flag] int NULL, 
	[Entry Create Current Calendar Year Minus 1 Flag] int NULL, 
	[Entry Create Current Calendar Year Minus 2 Flag] int NULL, 
	[Entry Create Current Fiscal Year Flag] int NULL, 
	[Entry Create Current Fiscal Year Minus 1 Flag] int NULL, 
	[Entry Create Current Fiscal Year Minus 2 Flag] int NULL, 
	[Entry Create Current Calendar Year Plus 1 Flag] int NULL, 
	[Entry Create Current Fiscal Year Plus 1 Flag] int NULL, 
	[Entry Create Day in Fiscal Year] int NULL, 
	[IS_WEEKDAY] int NULL, 
	[Entry Create Fiscal Week] int NULL, 
	[Entry Create Current Fiscal Week Flag] int NULL, 
	[Entry Create Current Fiscal Week Minus 1 Flag] int NULL, 
	[Entry Create Fiscal Weekday Number] int NULL, 
	[Entry Create Fiscal Weekday Name] varchar(max) NULL, 
	[Entry Create Current Month Minus 2 Flag] int NULL, 
	[Entry Create Current Fiscal Week Minus 2 Flag] int NULL, 
	[Entry Create Current Fiscal Week Minus 6 Flag] int NULL, 
	[Entry Create Current Fiscal Week Minus 3 Flag] int NULL, 
	[Entry Create Current Fiscal Week Minus 4 Flag] int NULL, 
	[Entry Create Current Fiscal Week Minus 5 Flag] int NULL, 
	[Entry Create Current Fiscal Week Minus 7 Flag] int NULL
);