CREATE TABLE [Propelis].[EDW_T_FACT_CO_COPA3_CUR_D] (

	[COPA Currency Type] varchar(max) NULL, 
	[COPA Record Type] varchar(max) NULL, 
	[COPA Version] varchar(max) NULL, 
	[COPA Period Year] varchar(max) NULL, 
	[COPA Profit Segment] varchar(max) NULL, 
	[COPA Subnumber] varchar(max) NULL, 
	[COPA Accounting Clerk Description] varchar(max) NULL, 
	[COPA Sub Brand] varchar(max) NULL, 
	[COPA Brand] varchar(max) NULL, 
	[COPA Product Hierarchy Code] varchar(max) NULL, 
	[COPA Base UoM Description] varchar(max) NULL, 
	[COPA Region] varchar(max) NULL, 
	[COPA Industry Code 1] varchar(max) NULL, 
	[COPA Industry Code 1 Description] varchar(max) NULL, 
	[COPA Industry Code 2] varchar(max) NULL, 
	[COPA Industry Code 2 Description] varchar(max) NULL, 
	[COPA Accounting Clerk] varchar(max) NULL, 
	[COPA Customer Group Description] varchar(max) NULL, 
	[COPA Customer Group 2] varchar(max) NULL, 
	[COPA Customer Group 2 Description] varchar(max) NULL, 
	[COPA Material Group] varchar(max) NULL, 
	[COPA Material Group Description] varchar(max) NULL, 
	[COPA Distribution Channel Description] varchar(max) NULL, 
	[COPA Division] varchar(max) NULL, 
	[COPA Division Description] varchar(max) NULL, 
	[COPA Industry Description] varchar(max) NULL, 
	[COPA Customer Group] varchar(max) NULL, 
	[COPA Customer Account Assignment Group Description] varchar(max) NULL, 
	[MATRL_SALES_KEY] int NULL, 
	[BRAND_OWNER_CUST_KEY] int NULL, 
	[COPA Sales Organization] varchar(max) NULL, 
	[COPA Sales Organization Description] varchar(max) NULL, 
	[COPA Distribution Channel] varchar(max) NULL, 
	[Customer PO Box Postal Code] varchar(max) NULL, 
	[COPA Sales Office] varchar(max) NULL, 
	[COPA Sales Office Description] varchar(max) NULL, 
	[COPA Sales Group] varchar(max) NULL, 
	[COPA Sales Group Description] varchar(max) NULL, 
	[COPA Customer Account Assignment Group] varchar(max) NULL, 
	[CUST_KEY] int NULL, 
	[COPA Commission Group Description] varchar(max) NULL, 
	[COPA Order Reason] varchar(max) NULL, 
	[COPA Order Reason Description] varchar(max) NULL, 
	[COPA Sales District] varchar(max) NULL, 
	[COPA Sales District Description] varchar(max) NULL, 
	[COPA Invoice Type Description] varchar(max) NULL, 
	[COPA Order Number] varchar(max) NULL, 
	[INCOMING_FREIGHT_AMT] decimal(18,2) NULL, 
	[OUTGOING_TRNSPRT_AMT] decimal(18,2) NULL, 
	[SUBCONTRACTING_SERVC_AMT] decimal(18,2) NULL, 
	[COPA Sales Document Description] varchar(max) NULL, 
	[COPA Ship To Zip Code] varchar(max) NULL, 
	[COPA Plan Actual Indicator] varchar(max) NULL, 
	[COPA Plan Actual Indicator Description] varchar(max) NULL, 
	[WBS_ELEMNT_KEY] int NULL, 
	[COPA Cancelled Document] varchar(max) NULL, 
	[COPA Cancelled Document Item] varchar(max) NULL, 
	[COPA Ship To Telephone] varchar(max) NULL, 
	[COPA Terms of Payment Description] varchar(max) NULL, 
	[COPA Ship To Address] varchar(max) NULL, 
	[COPA Ship To Country] varchar(max) NULL, 
	[COPA Ship To Region] varchar(max) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[COPA Currency Type Description] varchar(max) NULL, 
	[COPA Created By] varchar(max) NULL, 
	[COPA Controlling Area] varchar(max) NULL, 
	[COPA Controlling Area Description] varchar(max) NULL, 
	[COPA Ship To City] varchar(max) NULL, 
	[BILLTO_CUST_KEY] int NULL, 
	[CUST_SERVC_REPRESENTATIVE_KEY] int NULL, 
	[GOODS_ISSUE_DATE_KEY] int NULL, 
	[COPA Created On Date] date NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[FRIEGHT_REVNU_AMT] decimal(18,2) NULL, 
	[OVERHEAD_VARIANCES_AMT] decimal(18,2) NULL, 
	[COPA Order Quantity UoM] varchar(max) NULL, 
	[COPA Commission Group] varchar(max) NULL, 
	[CUST_SALES_AREA_KEY] int NULL, 
	[SALES_REP_REPRESENTATIVE_KEY] int NULL, 
	[CASHDISC_WO_TAX_AMT] decimal(18,2) NULL, 
	[DISTRBN_EXPENSE_AMT] decimal(18,2) NULL, 
	[INTERCO_MAT_COST_AMT] decimal(18,2) NULL, 
	[OUTSIDE_PURCHASES_AMT] decimal(18,2) NULL, 
	[MCHINE_COSTS_AMT] decimal(18,2) NULL, 
	[COPA Sales Document Type] varchar(max) NULL, 
	[CLOSEOUT_REVNU_AMT] decimal(18,2) NULL, 
	[DAMAGED_REVNU_AMT] decimal(18,2) NULL, 
	[SUBSTITUTION_REVNU_AMT] decimal(18,2) NULL, 
	[PROMOTION_REVNU_AMT] decimal(18,2) NULL, 
	[EXCEPTION_REVNU_AMT] decimal(18,2) NULL, 
	[PRENEED_REVNU_AMT] decimal(18,2) NULL, 
	[SELLING_EXPENSE_AMT] decimal(18,2) NULL, 
	[GENERAL_ADMIN_AMT] decimal(18,2) NULL, 
	[PROFT_DISTRBN_AMT] decimal(18,2) NULL, 
	[DIVISION_SERVICES_AMT] decimal(18,2) NULL, 
	[CASHDISCOUNT_ON_INVC_AMT] decimal(18,2) NULL, 
	[SELLING_PRICE_AMT] decimal(18,2) NULL, 
	[CORPORATE_SERVICES_AMT] decimal(18,2) NULL, 
	[REBATES_ON_INVC_AMT] decimal(18,2) NULL, 
	[FREIGHT_COST_AMT] decimal(18,2) NULL, 
	[REALIZED_FX_AP_AR_AMT] decimal(18,2) NULL, 
	[LABOR_SPEND_VRNC_AMT] decimal(18,2) NULL, 
	[OVERHEAD_SPEND_VRNC_AMT] decimal(18,2) NULL, 
	[Direct Material Amount] decimal(18,2) NULL, 
	[OVERHEAD_AMT] decimal(18,2) NULL, 
	[REBATES_AMT] decimal(18,2) NULL, 
	[PROD_LABOUR_VRNC_AMT] decimal(18,2) NULL, 
	[PROD_MAT_VRNC_AMT] decimal(18,2) NULL, 
	[OTHR_MAT_VRNC_AMT] decimal(18,2) NULL, 
	[MATRL_COST_AMT] decimal(18,2) NULL, 
	[OVERHEAD_COST_AMT] decimal(18,2) NULL, 
	[DISCNT_ON_INVC_AMT] decimal(18,2) NULL, 
	[IC_MARKUP_AMT] decimal(18,2) NULL, 
	[DIR_LABOR_AMT] decimal(18,2) NULL, 
	[LIST_PRICE_AMT] decimal(18,2) NULL, 
	[PRICE_VARIANCES_AMT] decimal(18,2) NULL, 
	[OTHR_VARIANCES_AMT] decimal(18,2) NULL, 
	[RESOURCE_USAGE_VARIANCES_AMT] decimal(18,2) NULL, 
	[CASH_DISCNT_AMT] decimal(18,2) NULL, 
	[STK_VAL_AMT] decimal(18,2) NULL, 
	[LABOR_COST_AMT] decimal(18,2) NULL, 
	[COPA Sales Order Line Item] varchar(max) NULL, 
	[SO_QTY] decimal(18,2) NULL, 
	[REVNU_AMT] decimal(18,2) NULL, 
	[LOTSIZE_VRNC_AMT] decimal(18,2) NULL, 
	[PROD_COSTS_VRNC_AMT] decimal(18,2) NULL, 
	[QTY_VARIANCES_AMT] decimal(18,2) NULL, 
	[COPA Invoice Header Number] varchar(max) NULL, 
	[COPA Invoice Item Number] varchar(max) NULL, 
	[COPA Year] varchar(max) NULL, 
	[COPA Period] varchar(max) NULL, 
	[COPA Invoice Type] varchar(max) NULL, 
	[SALES_ORDER_KEY] int NULL, 
	[COST_ELEMNT_KEY] int NULL, 
	[MATRL_KEY] int NULL, 
	[PLNT_KEY] int NULL, 
	[SALES_AREA_KEY] int NULL, 
	[SEG_KEY] int NULL, 
	[CRNCY_KEY] int NULL, 
	[PARNT_CUST_KEY] int NULL, 
	[RCD_TYP_DESC] varchar(max) NULL, 
	[SHIPTO_CUST_KEY] int NULL, 
	[CUST_CMPNY_KEY] int NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[PRTNR_PROFT_CNTR_KEY] int NULL, 
	[COPA Document Number] varchar(max) NULL, 
	[COPA Document Item Number] varchar(max) NULL, 
	[BILLING_DATE_KEY] int NULL, 
	[PSTNG_DATE_KEY] int NULL, 
	[CMPNY_KEY] int NULL, 
	[SOLDTO_CUST_KEY] int NULL, 
	[COSTEHZ_COST_ELEMNT_KEY ] int NULL, 
	[COSTEVZ_COST_ELEMNT_KEY ] int NULL, 
	[Partner_Profit_Center_Vertical_PROFT_CNTR_KEY] int NULL, 
	[Partner_Profit_Center_Horizontal_PROFT_CNTR_KEY] int NULL, 
	[PROFCVZ_PROFT_CNTR_KEY] int NULL, 
	[PROFCHZ_PROFT_CNTR_KEY] int NULL, 
	[CNTRY_KEY] varchar(max) NULL, 
	[INDUS_KEY] varchar(max) NULL, 
	[TRMS_OF_PYMT_KEY] varchar(max) NULL
);