CREATE TABLE [Propelis].[EDW_T_FACT_HR_CATSDB_CUR_D] (

	[PERSONEL_NUM_KEY] int NULL, 
	[WRK_DATE_KEY] int NULL, 
	[Counter] varchar(max) NOT NULL, 
	[COST_CNTR_KEY] int NULL, 
	[ACTIVITY_TYP_KEY] int NULL, 
	[SERVC_ORDER_KEY] int NULL, 
	[Operation Task List] int NULL, 
	[Operation Counter] int NULL, 
	[RECVNG_FUNCTNL_AREA_KEY] int NULL, 
	[SENDING_FUNCTNL_AREA_KEY] int NULL, 
	[Attendance Or Absence Type] varchar(max) NULL, 
	[Controlling Area] varchar(max) NULL, 
	[Display UOM] varchar(max) NULL, 
	[WRK_CNTR_KEY] int NULL, 
	[Order Category] int NULL, 
	[Processing Status] varchar(max) NULL, 
	[Document Number] varchar(max) NULL, 
	[HRS] decimal(4,2) NULL, 
	[Start Time] varchar(max) NULL, 
	[End Time] varchar(max) NULL, 
	[CATS_AMT] decimal(13,2) NULL, 
	[CATS_QTY] decimal(15,3) NULL, 
	[Change Text] varchar(max) NULL, 
	[Created Date] varchar(max) NULL, 
	[Created Time] varchar(max) NULL, 
	[Changed Date] varchar(max) NULL, 
	[Change Time] varchar(max) NULL, 
	[Comment] varchar(max) NULL, 
	[Header Comment] varchar(max) NULL, 
	[Short Text] varchar(max) NULL, 
	[Long Text] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[PLNT_KEY] int NULL, 
	[Controlling Area Description] varchar(max) NULL, 
	[Order Category Description] varchar(max) NULL, 
	[Processing Status Description] varchar(max) NULL, 
	[Network Number] varchar(max) NULL, 
	[UOM] varchar(max) NULL, 
	[Created On] date NULL, 
	[Time Of Entry] varchar(max) NULL, 
	[User Who Created Data Record] varchar(max) NULL, 
	[Date Of Last Change] date NULL, 
	[Time of Last Change] varchar(max) NULL, 
	[Name Of Person Who Changed Object] varchar(max) NULL, 
	[Name Of Person Who Apprvd Data] varchar(max) NULL, 
	[Date Of Approval] date NULL, 
	[Logical System] varchar(max) NULL, 
	[Reference Counter for Record to be Changed] varchar(max) NULL, 
	[Partial Confirmation Indicator] varchar(max) NULL, 
	[Receiver Order] varchar(max) NULL, 
	[Project Description] varchar(max) NULL, 
	[WBS Number] varchar(max) NULL, 
	[WBS Description] varchar(max) NULL, 
	[WBS_ELEMNT_KEY] int NULL, 
	[SGK_OPERREG_PLANT] varchar(max) NULL, 
	[COSTCVZ_COST_CNTR_KEY] int NULL, 
	[COSTCHZ_COST_CNTR_KEY] int NULL, 
	[WORKCHZ_WRK_CNTR_KEY] int NULL, 
	[WORKCVZ_WRK_CNTR_KEY] int NULL
);