CREATE TABLE [Propelis].[EDW_T_FACT_SAL_SALSCHL_CUR_D] (

	[SALES_ORDER_KEY] int NOT NULL, 
	[Sales Order Item ID] varchar(max) NOT NULL, 
	[Schedule Item ID] varchar(max) NOT NULL, 
	[CMPNY_KEY] int NOT NULL, 
	[PLNT_KEY] int NOT NULL, 
	[SEG_KEY] int NOT NULL, 
	[SALES_AREA_KEY] int NOT NULL, 
	[MATRL_KEY] int NOT NULL, 
	[SCHL_ITM_DATE_KEY] int NOT NULL, 
	[MATRL_AVAILABILITY_DATE_KEY] int NOT NULL, 
	[LOADING_DATE_KEY] int NOT NULL, 
	[GOODS_ISSUE_DATE_KEY] int NOT NULL, 
	[Schedule Line Category Code] varchar(max) NULL, 
	[QTY_ORDERED] decimal(13,3) NULL, 
	[QTY_CONFIRMED] decimal(13,3) NULL, 
	[QTY_REQUIRED] decimal(13,3) NULL, 
	[Quantity Uom] varchar(max) NULL, 
	[Release for Planning Timestamp] datetime2(0) NULL, 
	[Delivery Block] varchar(max) NULL, 
	[QTY_COMMITED] decimal(13,3) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Reason for Rejection] varchar(max) NULL, 
	[Delivery Block Description] varchar(max) NULL, 
	[Schedule Line Category Description] varchar(max) NULL, 
	[Technical Release Timestamp] datetime2(0) NULL, 
	[Sales Order ID] varchar(max) NOT NULL
);