CREATE TABLE [Propelis].[EDW_T_FACT_CO_CCCSTRN_CUR_D] (

	[Transaction Ledger] varchar(max) NULL, 
	[Transaction Object Number] varchar(max) NULL, 
	[Transaction Year] int NULL, 
	[Transaction Value Type] varchar(max) NULL, 
	[Transaction Version] varchar(max) NULL, 
	[COST_CNTR_KEY] int NOT NULL, 
	[Transaction CO Subkey] varchar(max) NULL, 
	[Transaction Business] varchar(max) NULL, 
	[Transaction Trading Partner] varchar(max) NULL, 
	[Transaction Trading Partner Business Area] varchar(max) NULL, 
	[Transaction Debit Credit Indicator] varchar(max) NULL, 
	[DOCMT_CRNCY_KEY] int NOT NULL, 
	[CMPNY_KEY] int NOT NULL, 
	[SEG_KEY] int NULL, 
	[COST_ELEMNT_KEY] int NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[CMPNY_CRNCY_KEY] int NULL, 
	[GROUP_CRNCY_KEY] int NULL, 
	[DOCMT_CRNCY_AMT] decimal(15,2) NULL, 
	[CMPNY_CRNCY_AMT] decimal(15,2) NULL, 
	[GROUP_CRNCY_AMT] decimal(15,2) NULL, 
	[Transaction Period] int NULL, 
	[Transaction Partner Object Type] varchar(max) NULL, 
	[Transaction Partner Object Type Description] varchar(max) NULL, 
	[TOTAL_QTY] decimal(15,3) NULL, 
	[FIXED_QTY] decimal(15,3) NULL, 
	[Transaction Value Type Description] varchar(max) NULL, 
	[Transaction Source System Code] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[FUNCTNL_AREA_KEY] int NULL, 
	[Transaction Controlling Area] varchar(max) NOT NULL, 
	[Transaction Document Number] varchar(max) NOT NULL, 
	[Transaction Posting Row] varchar(max) NOT NULL, 
	[PLNT_KEY] int NULL, 
	[Transaction Controlling Area Description] varchar(max) NULL, 
	[Transaction Ledger Description] varchar(max) NULL, 
	[Transaction Business Description] varchar(max) NULL, 
	[Transaction Trading Partner Description] varchar(max) NULL, 
	[Transaction Trading Partner Business Area Desc] varchar(max) NULL, 
	[Transaction Partner Object] varchar(max) NULL, 
	[Transaction Source Object] varchar(max) NULL, 
	[PSTNG_DATE_KEY] int NULL, 
	[Transaction Document Item Number] int NULL, 
	[TOTAL_QTY_ENTERED] decimal(15,3) NULL, 
	[Transaction UOM] varchar(max) NULL, 
	[Transaction Posted UOM] varchar(max) NULL, 
	[CONTROLLING_AREA_COST_ELEMNT_KE] int NULL, 
	[MATRL_KEY] int NULL, 
	[COSTEHZ_COST_ELEMNT_KEY] int NULL, 
	[COSTEVZ_COST_ELEMNT_KEY] int NULL, 
	[PROFCHZ_PROFT_CNTR_KEY] int NULL, 
	[PROFCVZ_PROFT_CNTR_KEY] int NULL, 
	[COSTCHZ_COST_CNTR_KEY] int NULL, 
	[COSTCVZ_COST_CNTR_KEY] int NULL
);