CREATE TABLE [Propelis].[EDW_T_FACT_HR_TIMECRD_CUR_D] (

	[PERSONEL_NUM_KEY] int NOT NULL, 
	[DATE_KEY] int NOT NULL, 
	[TOTAL_HRS] decimal(4,2) NULL, 
	[WRK_HRS] decimal(4,2) NULL, 
	[ABSNE_HRS] decimal(4,2) NULL, 
	[LUNCH_HRS] decimal(4,2) NULL, 
	[OVERTIME_HRS] decimal(4,2) NULL, 
	[Shift Start Time] varchar(max) NULL, 
	[SHIFT_START_TM_2] decimal(4,2) NULL, 
	[Shift End Time] varchar(max) NULL, 
	[SHIFT_END_TM_2] decimal(4,2) NULL, 
	[APPRVD_WORKING_HRS] decimal(4,2) NULL, 
	[Shift Scheduled Start Time] varchar(max) NULL, 
	[Shift Scheduled End Time] varchar(max) NULL, 
	[Comments] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[COST_CNTR_KEY] int NULL, 
	[CMPNY_KEY] int NULL, 
	[PLNT_KEY] int NULL, 
	[PERSONEL_AREA_KEY] int NULL, 
	[FLEX_BAL_TS] decimal(4,2) NULL, 
	[Approver User ID] varchar(max) NULL, 
	[PAID_BRK] decimal(4,2) NULL, 
	[ANNUAL_LEAVE_HRS] decimal(4,2) NULL, 
	[OTHR_LEAVE_HRS] decimal(4,2) NULL, 
	[SICK_LEAVE_HRS] decimal(4,2) NULL, 
	[UNPAID_LEAVE_HRS] decimal(4,2) NULL, 
	[PUNCH_IN_OUT_HRS] decimal(4,2) NULL, 
	[SGK_OPERREG_PLANT] varchar(max) NULL
);