CREATE TABLE [Propelis].[EDW_T_FACT_PRD_ENCPDAT_CUR_D] (

	[ENCP Job ID] int NOT NULL, 
	[ENCP Investigation Level] varchar(255) NULL, 
	[ENCP Brand] varchar(255) NULL, 
	[ENCP Category] varchar(255) NULL, 
	[ENCP Client] varchar(255) NULL, 
	[DISCOVERY_DATE_KEY] int NULL, 
	[ENCP Notification Number] varchar(255) NULL, 
	[ENCP Estimated Cost of Poor Quality] varchar(255) NULL, 
	[INVESTIGATION_START_DATE_KEY] int NULL, 
	[OCCURRENCE_DATE_KEY] int NULL, 
	[ENCP Other Impacted Service Orders] varchar(255) NULL, 
	[ENCP Primary Error Category] varchar(255) NULL, 
	[ENCP Primary Root Cause] varchar(255) NULL, 
	[ENCP Repeat Incident] varchar(255) NULL, 
	[ENCP Responsible Department] varchar(255) NULL, 
	[ENCP Secondary Error Category] varchar(255) NULL, 
	[ENCP Secondary Root Cause] varchar(255) NULL, 
	[ENCP SGK Error] varchar(255) NULL, 
	[ENCP SKU Description] varchar(255) NULL, 
	[ENCP Sold To Party Name] varchar(255) NULL, 
	[START_DATE_KEY] int NULL, 
	[ENCP Status] int NULL, 
	[SERVC_ORDER_KEY] int NULL, 
	[SALES_ORDER_KEY] int NULL, 
	[SOLD_TO_PARTY_KEY] int NULL, 
	[CUST_BRAND_HIERCHY_KEY] int NULL, 
	[SKU_MATRL_KEY] int NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[ENCP Potential Value of Claim $] varchar(255) NULL, 
	[ENCP Settled Value of Claim $] varchar(255) NULL, 
	[ENCP Describe Potential Impact Of The Error] varchar(5000) NULL, 
	[ENCP On Hold Reason] varchar(75) NULL
);