CREATE TABLE [Propelis].[EDW_T_FACT_SAL_INVITEM_CUR_D] (

	[INVC_KEY] int NOT NULL, 
	[Invoice ID] varchar(max) NOT NULL, 
	[Invoice Item ID] varchar(max) NOT NULL, 
	[CMPNY_KEY] int NOT NULL, 
	[INVC_DATE_KEY] int NOT NULL, 
	[PLNT_KEY] int NOT NULL, 
	[SOLDTO_CUST_KEY] int NOT NULL, 
	[BILLTO_CUST_KEY] int NOT NULL, 
	[PAYER_CUST_KEY] int NOT NULL, 
	[SHIPTO_CUST_KEY] int NOT NULL, 
	[BRANDOWNER_CUST_KEY] int NOT NULL, 
	[CUST_CONTACT_KEY] int NOT NULL, 
	[SALES_PERSON_PERSONEL_KEY] int NOT NULL, 
	[PERSON_RESPNSBLE_PERSONEL_KEY] int NOT NULL, 
	[MATRL_KEY] int NOT NULL, 
	[SEG_KEY] int NOT NULL, 
	[CUST_CMPNY_KEY] int NOT NULL, 
	[CUST_SALES_AREA_KEY] int NOT NULL, 
	[SALES_ORDER_KEY] int NOT NULL, 
	[SALES_ORDER_ID] varchar(max) NOT NULL, 
	[SALES_ORDER_ITM_ID] varchar(max) NULL, 
	[DOCMT_CRNCY_KEY] int NOT NULL, 
	[CMPNY_CRNCY_KEY] int NOT NULL, 
	[GROUP_CRNCY_KEY] int NOT NULL, 
	[Invoice Payment Required Date] date NULL, 
	[DOCMT_CRNCY_INVC_AMT] decimal(18,3) NULL, 
	[CMPNY_CRNCY_INVC_AMT] decimal(18,3) NULL, 
	[GROUP_CRNCY_INVC_AMT] decimal(18,3) NULL, 
	[INVOICED_QTY] decimal(15,3) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[PRDT_VARIANT_CONFIG_KEY] int NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[CYLINDER_OWNER_CUST_KEY] int NULL, 
	[PARNT_CUST_KEY] int NULL, 
	[Sales UoM] varchar(max) NULL, 
	[Short Text For Sales Order Item] varchar(max) NULL, 
	[SUBTOTAL_4_PRICING_COND] decimal(13,2) NULL, 
	[DOCMT_CRNCY_TAX_AMT] decimal(13,2) NULL, 
	[AGENCY_CUST_KEY] int NULL, 
	[PRINTER_CUST_KEY] int NULL, 
	[SUPLR_CUST_KEY] int NULL, 
	[Sales Document Item Category] varchar(max) NULL, 
	[Usage Indicator] varchar(max) NULL, 
	[SUBTOTAL_2_PRICING_COND] decimal(13,2) NULL, 
	[SUBTOTAL_5_PRICING_COND] decimal(13,2) NULL, 
	[Reference Document] varchar(max) NULL, 
	[Reference Document Item] int NULL, 
	[Usage Indicator Description] varchar(max) NULL, 
	[SPCL_STK_PRTNR_KEY] int NULL, 
	[CUST_HIERCHY_1_KEY] int NULL, 
	[Originating Document] varchar(max) NULL, 
	[Originating Item] int NULL, 
	[PARNT_INVC_KEY] int NULL, 
	[Parent Invoice Item ID] int NULL, 
	[CREATED_DATE_KEY] int NULL, 
	[SUBTOTAL_1_PRICING_COND] decimal(13,2) NULL, 
	[SUBTOTAL_3_PRICING_COND] decimal(13,2) NULL, 
	[SUBTOTAL_6_PRICING_COND] decimal(13,2) NULL, 
	[RBTE_BASIS_1] decimal(13,2) NULL, 
	[ITM_CREDIT_PRICE] decimal(11,2) NULL, 
	[OPERATING_PLANT_REGION_PLANT] varchar(max) NULL, 
	[SALES_ORDER_CREATION_DATE_DATE_KEY] date NULL, 
	[CUSTOMR_CUST_ID] varchar(max) NULL, 
	[PROFCHZ_PROFT_CNTR_KEY] int NULL, 
	[PROFCVZ_PROFT_CNTR_KEY] int NULL, 
	[PRDVCON_KEY] varchar(max) NULL
);