CREATE TABLE [Propelis].[EDW_T_FACT_PRD_TMCONFS_CUR_D_GK] (

	[SEG_CD_KEY] int NULL, 
	[Operation Task List ID] int NULL, 
	[Operation Counter ID] int NULL, 
	[Operation Activity ID] int NULL, 
	[Operation Confirmation ID] int NULL, 
	[Operation Sequence ID] int NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[SALES_ORDER_KEY] int NULL, 
	[Sales Order Item Number] int NULL, 
	[CMPNY_KEY] int NULL, 
	[WRK_CNTR_KEY] int NULL, 
	[COST_CNTR_KEY] int NULL, 
	[OPERATION_STD_TEXT] varchar(max) NULL, 
	[Operation Short Text] varchar(max) NULL, 
	[PSTNG_DATE_KEY] int NULL, 
	[PLNG_PLNT_KEY] int NULL, 
	[Entry Create Date] date NULL, 
	[Person Who Entererd] varchar(max) NULL, 
	[Operation Confirm Counter] int NULL, 
	[Actual Work] decimal(18,2) NULL, 
	[Actual Work UOM] varchar(max) NULL, 
	[Accounting Indicator] varchar(max) NULL, 
	[Remaining Work] decimal(18,2) NULL, 
	[Remaining Work UOM] varchar(max) NULL, 
	[Actual Work in Hours] decimal(18,2) NULL, 
	[Remaining Work in Hours] decimal(18,2) NULL, 
	[Work In Hours UOM] varchar(max) NULL, 
	[ACTIVITY_TYP_KEY] int NULL, 
	[Operation Confirm Text] varchar(max) NULL, 
	[Reason for Variance] varchar(max) NULL, 
	[Confirm  Counter  Of  Cancelled  Confirmation] int NULL, 
	[SOLD_TO_CUST_KEY] int NULL, 
	[PERSONEL_NUM_KEY] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[SERVC_ORDER_KEY] int NULL, 
	[SALES_AREA_KEY] int NULL, 
	[OPERATING_PLNT_KEY] int NULL, 
	[SERVC_ORDER_CREATE_DATE_KEY] int NULL, 
	[Account Indicator] varchar(max) NULL, 
	[PARNT_CUST_KEY] int NULL, 
	[Reason for Variance Description] varchar(max) NULL, 
	[Partial Final Confirm] varchar(max) NULL, 
	[TCHNCL_COMPLETION_DATE_KEY] int NULL, 
	[SALES_ORDER_ID] varchar(max) NULL, 
	[Accounting Indicator Description] varchar(max) NULL, 
	[SERV_ORDER_INVOICE_CREATED_DATE_KEY] int NULL, 
	[OPERATING_PLANT_REGION_PLANT] varchar(max) NULL, 
	[PLANNING_PLANT_REGION_PLANT] varchar(max) NULL, 
	[PERSONNEL_PLANT_REGION_PLANT] varchar(max) NULL, 
	[PARENT_CUST_KEY] int NULL, 
	[PAYER_CUST_KEY] int NULL, 
	[SHIP_TO_CUST_KEY] int NULL, 
	[BRAND_OWNER_CUST_KEY] int NULL, 
	[CUST_CONTACT_KEY] int NULL, 
	[PERSON_RESP_PERSONNEL_KEY] int NULL, 
	[CYLINDER_OWNER_CUST_KEY] int NULL, 
	[AGENCY_CUST_KEY] int NULL, 
	[PRINTER_CUST_KEY] int NULL, 
	[SUPPLIER_CUST_KEY] int NULL, 
	[EMPLOYEE_RESP_PERSONEL_KEY] int NULL, 
	[EMPLOYEE_RESP_2_PERSONEL_KEY] int NULL, 
	[FORWARDING_AGENT_VENDOR_KEY] int NULL, 
	[UNITIZATION_AGENT_VENDOR_KEY] int NULL, 
	[ORDER_FOR_CUSTOMER_ADDR_KEY] int NULL, 
	[SO_PARENT_CUST_KEY] int NULL, 
	[BILL_TO_CUST_KEY] int NULL, 
	[CUSTOMER_PROJECT_MANAGER_CUST_CONTACT_KEY] int NULL, 
	[SALES_PERSON_PERSONEL_KEY] int NULL, 
	[PRDT_VARIANT_CONFIG_KEY] int NULL, 
	[SOIPTNR_KEY] varchar(250) NULL
);