CREATE TABLE [Propelis].[EDW_V_FACT_FI_GENLDGR_CUR_D] (

	[CMPNY_KEY] int NULL, 
	[GL Fiscal Year] int NULL, 
	[GL Document Number] varchar(max) NULL, 
	[GL Ledger] varchar(max) NULL, 
	[GL Document Line Item] int NULL, 
	[GL Controlling Area] varchar(max) NULL, 
	[TRNSCTN_CRNCY_AMT] decimal(23,2) NULL, 
	[CMPNY_CRNCY_AMT] decimal(23,2) NULL, 
	[GROUP_CRNCY_AMT] decimal(23,2) NULL, 
	[TRNSCTN_CRNCY_KEY] int NULL, 
	[CMPNY_CRNCY_KEY] int NULL, 
	[GROUP_CRNCY_KEY] int NULL, 
	[GL Item Category] varchar(max) NULL, 
	[GL Fiscal Period] int NULL, 
	[GL Document Line Item ID] varchar(max) NULL, 
	[GL Clearing Fiscal Year] int NULL, 
	[GL Clearing Item] int NULL, 
	[CUST_KEY] int NULL, 
	[VNDR_KEY] int NULL, 
	[GL Reason Code for Payments] varchar(max) NULL, 
	[GL Reference Date for Settlement] date NULL, 
	[GL Business Partner Reference Key] varchar(max) NULL, 
	[GL Business Partner Reference Key 2] varchar(max) NULL, 
	[GL Special GL Transaction Type] varchar(max) NULL, 
	[GL Special GL Indicator] varchar(max) NULL, 
	[GL Transaction Type] varchar(max) NULL, 
	[GL Value Date] date NULL, 
	[GL Assignment Number] varchar(max) NULL, 
	[GL Item Text] varchar(max) NULL, 
	[QTY] decimal(13,3) NULL, 
	[GL Quantity UOM] varchar(max) NULL, 
	[FUNCTNL_AREA_KEY] int NULL, 
	[AMT_FOR_UPDATING_IN_GL] decimal(13,2) NULL, 
	[GL Update Currency] varchar(max) NULL, 
	[GL Is Open Item Management] varchar(max) NULL, 
	[GL Tax Jurisdiction] varchar(max) NULL, 
	[GL Tax On Sales Or Purchases] varchar(max) NULL, 
	[GL Tax Type] varchar(max) NULL, 
	[TRADING_PRTNR_CMPNY_KEY] int NULL, 
	[WBS_ELEMNT_KEY] int NULL, 
	[GL Account Type] varchar(max) NULL, 
	[PRTNR_FUNCTNL_AREA_KEY] int NULL, 
	[COST_CNTR_KEY] int NULL, 
	[COST_ELEMNT_KEY] int NULL, 
	[GL Reference Key for Line Item] varchar(max) NULL, 
	[GL Payment Reference] varchar(max) NULL, 
	[PLNT_KEY] int NULL, 
	[CLEARING_DATE_KEY] int NULL, 
	[GL Clearing Document Number] varchar(max) NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[SEG_KEY] int NULL, 
	[GL Debit/Credit Indicator] varchar(max) NULL, 
	[GL Posting Key] varchar(max) NULL, 
	[GL Invoice Document Number] varchar(max) NULL, 
	[GL_KEY] int NULL, 
	[MATRL_KEY] int NULL, 
	[PRTNR_PROFT_CNTR_KEY] int NULL, 
	[PRTNR_SEG_KEY] int NULL, 
	[GL Document Type] varchar(max) NULL, 
	[GL Ledger in GL Accounting] varchar(max) NULL, 
	[DOCMT_DATE_KEY] int NULL, 
	[GL Document Creation Date] date NULL, 
	[GL Document Creation Time] int NULL, 
	[GL Document Creation User Name] varchar(max) NULL, 
	[PSTNG_DATE_KEY] int NULL, 
	[GL Business Transaction] varchar(max) NULL, 
	[GL Document Status] varchar(max) NULL, 
	[GL Reference Document Number] varchar(max) NULL, 
	[GL Reference Key] varchar(max) NULL, 
	[GL Reference Transaction] varchar(max) NULL, 
	[BILLING_DOCMT_KEY] int NULL, 
	[GL Order Number] varchar(max) NULL, 
	[GL Purchase Order Item ID] int NULL, 
	[PURCHS_ORDER_ITM_KEY] int NULL, 
	[GL Sales Order Item ID] int NULL, 
	[SALES_ORDER_KEY] int NULL, 
	[LCL_CRNCY_3_KEY] int NULL, 
	[GL Parked Document User Name] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[GL Assignment Number for Special Accounts] varchar(max) NULL, 
	[CMPNY_CRNCY_TAX_AMT] decimal(13,2) NULL, 
	[DOCMT_CRNCY_TAX_AMT] decimal(13,2) NULL, 
	[GL Ledger Description] varchar(max) NULL, 
	[GL Controlling Area Description] varchar(max) NULL, 
	[GL Item Category Description] varchar(max) NULL, 
	[GL Reason Code Description] varchar(max) NULL, 
	[GL Special GI Indicator Description] varchar(max) NULL, 
	[GL Transaction Type Description] varchar(max) NULL, 
	[GL Tax Type Description] varchar(max) NULL, 
	[GL Account Type Description] varchar(max) NULL, 
	[GL Posting Key Description] varchar(max) NULL, 
	[GL Document Type Description] varchar(max) NULL, 
	[GL Document Status Description] varchar(max) NULL, 
	[GL Timestamp] decimal(15,0) NULL, 
	[GL Base UoM Description] varchar(max) NULL, 
	[DOCMT_CRNCY_KEY] int NULL, 
	[DOCMT_CRNCY_AMT] decimal(23,2) NULL, 
	[GL_CMPNY_KEY] int NULL, 
	[GL Transaction Code] varchar(max) NULL, 
	[ASSET_KEY] int NULL, 
	[GL Asset Transaction Type] varchar(max) NULL, 
	[GL Asset Transaction Type Description] varchar(max) NULL, 
	[GL Document Line Item In BSEG] int NULL, 
	[PRFT_CNTR_TRD_PRTNR_GRP_ID] varchar(max) NULL, 
	[PRTNR_PRFT_CNTR_TRD_PRTNR_GRP_ID] varchar(max) NULL, 
	[PRTNR_PRFT_CNTR_V_HIER_KEY] int NULL, 
	[PRTNR_PRFT_CNTR_H_HIER_KEY] int NULL, 
	[COSTCHZ_COST_CNTR_KEY] int NULL, 
	[COSTCVZ_COST_CNTR_KEY] int NULL, 
	[PROFCHZ_PROFT_CNTR_KEY] int NULL, 
	[PROFCVZ_PROFT_CNTR_KEY] int NULL, 
	[COSTEHZ_COST_ELEMNT_KEY] int NULL, 
	[COSTEVZ_COST_ELEMNT_KEY] int NULL, 
	[ICGLGRP_GL_CD] int NULL, 
	[CMPNYDT_KEY] varchar(max) NULL
);