CREATE TABLE [Propelis].[EDW_T_FACT_CO_CCCSUMM_CUR_D] (

	[Summary Ledger] varchar(max) NOT NULL, 
	[Summary Object Number] varchar(max) NOT NULL, 
	[Summary Year] int NOT NULL, 
	[Summary Value Type] varchar(max) NOT NULL, 
	[Summary Version] varchar(max) NOT NULL, 
	[COST_CNTR_KEY] int NOT NULL, 
	[Summary CO Subkey] varchar(max) NOT NULL, 
	[Summary Business Transaction] varchar(max) NOT NULL, 
	[Summary Trading Partner] varchar(max) NOT NULL, 
	[Summary Trading Partner Business Area] varchar(max) NOT NULL, 
	[Summary Debit Credit Indicator] varchar(max) NOT NULL, 
	[DOCMT_CRNCY_KEY] int NOT NULL, 
	[Summary Period Block] int NOT NULL, 
	[CMPNY_KEY] int NULL, 
	[FUNCTNL_AREA_KEY] int NULL, 
	[SEG_KEY] int NULL, 
	[COST_ELEMNT_KEY] int NOT NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[CMPNY_CRNCY_KEY] int NULL, 
	[GROUP_CRNCY_KEY] int NULL, 
	[DOCMT_CRNCY_AMT] decimal(15,2) NULL, 
	[CMPNY_CRNCY_AMT] decimal(15,2) NULL, 
	[GROUP_CRNCY_AMT] decimal(15,2) NULL, 
	[Summary Period] int NOT NULL, 
	[Summary Partner Object Type] varchar(max) NULL, 
	[Summary Partner Object Type Description] varchar(max) NULL, 
	[Summary Value Type Description] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Summary Partner Object] varchar(max) NOT NULL, 
	[Summary Source Object] varchar(max) NOT NULL, 
	[Summary Ledger Description] varchar(max) NULL, 
	[Summary Trading Partner Description] varchar(max) NULL, 
	[Summary Trading Partner Business Area Desc] varchar(max) NULL, 
	[CONTROLLING_AREA_COST_ELEMNT_KE] int NULL, 
	[COSTEHZ_COST_ELEMNT_KEY] int NULL, 
	[COSTEVZ_COST_ELEMNT_KEY] int NULL, 
	[PROFCHZ_PROFT_CNTR_KEY] int NULL, 
	[PROFCVZ_PROFT_CNTR_KEY] int NULL, 
	[COSTCHZ_COST_CNTR_KEY] int NULL, 
	[COSTCVZ_COST_CNTR_KEY] int NULL, 
	[Cost Element Grouping] varchar(100) NULL, 
	[Cost Element Type] varchar(50) NULL
);