CREATE TABLE [Propelis].[EDW_T_FACT_FI_BPCDTAU_CUR_D] (

	[ACCT_KEY] int NOT NULL, 
	[Audit Trail] varchar(max) NULL, 
	[Currency] varchar(max) NULL, 
	[Custom1] varchar(max) NULL, 
	[ENTITY_KEY] int NOT NULL, 
	[Flow] varchar(max) NULL, 
	[FUNCTNL_AREA_KEY] int NOT NULL, 
	[INTER_CMPNY_PROFT_CNTR_KEY] int NOT NULL, 
	[INTER_CMPNY_KEY] int NOT NULL, 
	[PROFT_CNTR_KEY] int NOT NULL, 
	[Project] varchar(max) NULL, 
	[Scope] varchar(max) NULL, 
	[Version] varchar(max) NULL, 
	[Fiscal Year] int NOT NULL, 
	[FYP] decimal(15,3) NULL, 
	[Signdata Amount] decimal(15,3) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(6) NULL, 
	[ETL_UPDTD_TS] datetime2(6) NULL, 
	[ACCT ID] varchar(max) NOT NULL, 
	[ENTITY ID] varchar(max) NOT NULL, 
	[Functional Area ID] varchar(max) NULL, 
	[Inter Company Profit Center ID] varchar(max) NULL, 
	[Profit Center ID] varchar(max) NULL, 
	[Inter Company ID] varchar(max) NULL, 
	[Signdata Amt - Current] decimal(15,3) NULL, 
	[PROFCHZ_PROFT_CNTR_KEY] int NULL, 
	[PROFCVZ_PROFT_CNTR_KEY] int NULL, 
	[INTER_COMPANY_PC_HH_PROFT_CNTR_KEY] int NULL, 
	[INTER_COMP_PC_VH_PROFT_CNTR_KEY] int NULL, 
	[FYQ] varchar(25) NULL, 
	[MST_DATE_KEY] varchar(max) NULL, 
	[Functional_GL_Key] varchar(max) NULL, 
	[Period] int NULL, 
	[Last Month of Quarter] int NULL
);