CREATE TABLE [Propelis].[EDW_T_FACT_FI_ACCTPAY2_CUR_D] (

	[CMPNY_KEY] int NOT NULL, 
	[AP Fiscal Year] int NOT NULL, 
	[AP Document Header Number] varchar(max) NOT NULL, 
	[AP Ledger Posting Item Number] varchar(max) NOT NULL, 
	[AP Ledger Code] varchar(max) NOT NULL, 
	[VNDR_KEY] int NULL, 
	[AP Document Line Item Number] int NULL, 
	[AP Clearing Document Number] varchar(max) NULL, 
	[CLEARING_DATE_KEY] int NULL, 
	[AP Assignment Number] varchar(max) NULL, 
	[AP Special GL Transaction Type] varchar(max) NULL, 
	[AP Special GL Indicator] varchar(max) NULL, 
	[DOCMT_DATE_KEY] int NULL, 
	[PSTNG_DATE_KEY] int NULL, 
	[DOCMT_CRNCY_KEY] int NULL, 
	[CMPNY_CRNCY_KEY] int NULL, 
	[GROUP_CRNCY_KEY] int NULL, 
	[AP Posting Period] int NULL, 
	[AP Document Type] varchar(max) NULL, 
	[AP Reference Number] varchar(max) NULL, 
	[AP Invoice Reference Number] varchar(max) NULL, 
	[AP Reason Code] varchar(max) NULL, 
	[AP Reason Code Description] varchar(max) NULL, 
	[CMPNY_CRNCY_AMT] decimal(23,2) NULL, 
	[DOCMT_CRNCY_AMT] decimal(23,2) NULL, 
	[GROUP_CRNCY_AMT] decimal(23,2) NULL, 
	[PSTNG_KEY] varchar(max) NULL, 
	[AP Debit Credit Indicator] varchar(max) NULL, 
	[GL_KEY] int NULL, 
	[BSLINE_DUE_DATE_KEY] int NULL, 
	[AP Payment Terms] varchar(max) NULL, 
	[CASH_DISCOUNTS_DAY_1] decimal(3,0) NULL, 
	[CASH_DISCOUNTS_DAY_2] decimal(3,0) NULL, 
	[AP Net Payments Term Period] decimal(3,0) NULL, 
	[AP Reference Key Line Item] varchar(max) NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[SEG_KEY] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[AP Special GL Indicator Description] varchar(max) NULL, 
	[AP Ledger Code Description] varchar(max) NULL, 
	[AP Document Type Description] varchar(max) NULL, 
	[AP Posting Description] varchar(max) NULL, 
	[AP Payment Terms Description] varchar(max) NULL, 
	[AP Tax Code On Purchases] varchar(max) NULL, 
	[AP Special GL Accounts Assignment Number] varchar(max) NULL, 
	[AP Entered By] varchar(max) NULL, 
	[AP Payment Method] varchar(max) NULL, 
	[AP Payment Method Description] varchar(max) NULL, 
	[PROFCHZ_PROFT_CNTR_KEY] int NULL, 
	[PROFCVZ_PROFT_CNTR_KEY ] int NULL
);