CREATE TABLE [Propelis].[EDW_T_FACT_PRD_QCDBDAT_CUR_D] (

	[QC Service Order ID] varchar(max) NOT NULL, 
	[QC Job Category] varchar(max) NOT NULL, 
	[QC Revision ID] varchar(max) NOT NULL, 
	[QC Revision No] varchar(max) NOT NULL, 
	[QC Job ID] varchar(max) NOT NULL, 
	[QC Unique Identifier] varchar(max) NOT NULL, 
	[QC Task] varchar(max) NOT NULL, 
	[SERVC_ORDER_KEY] int NULL, 
	[SOLDTO_PARTY_KEY] int NULL, 
	[QC Checklist Activity Type] varchar(max) NULL, 
	[QC PA User] varchar(max) NULL, 
	[QC User ID] varchar(max) NULL, 
	[QC Does Stage Have Error] varchar(max) NULL, 
	[QC Error Comment] varchar(max) NULL, 
	[CUST_BRAND_HIERCHY_KEY] int NULL, 
	[SCHAWK_PLNT_KEY] int NULL, 
	[PA_PLNT_KEY] int NULL, 
	[QC_PLNT_KEY] int NULL, 
	[DATE_COMPLETION_PA_KEY] int NULL, 
	[DATE_COMPLETION_QC_KEY] int NULL, 
	[PARNT_KEY] int NULL, 
	[CREATED_ON_TS] datetime2(0) NULL, 
	[CREATED_ON_DATE_KEY] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[QC Instructions] varchar(max) NULL, 
	[OPERREG_PLANT] varchar(max) NULL
);