CREATE TABLE [Propelis].[EDW_T_FACT_SAL_SALORDD_CUR_D] (

	[SALES_ORDER_KEY] int NOT NULL, 
	[Sales Order ID] varchar(max) NOT NULL, 
	[Sales Order Item ID] varchar(max) NOT NULL, 
	[DOCMT_DATE_KEY] int NOT NULL, 
	[REQD_DLVRY_DATE_KEY] int NOT NULL, 
	[CMPNY_KEY] int NOT NULL, 
	[PLNT_KEY] int NOT NULL, 
	[SOLDTO_CUST_KEY] int NOT NULL, 
	[BILLTO_CUST_KEY] int NOT NULL, 
	[PAYER_CUST_KEY] int NOT NULL, 
	[SHIPTO_CUST_KEY] int NOT NULL, 
	[BRAND_OWNER_CUST_KEY] int NOT NULL, 
	[CUST_CONTACT_KEY] int NOT NULL, 
	[SALES_PERSON_PERSONEL_KEY] int NOT NULL, 
	[PERSON_RESPNSBLE_PERSONEL_KEY] int NOT NULL, 
	[MATRL_KEY] int NOT NULL, 
	[PROFT_CNTR_KEY] int NOT NULL, 
	[CUST_CMPNY_KEY] int NOT NULL, 
	[CUST_SALES_AREA_KEY] int NOT NULL, 
	[SEG_KEY] int NOT NULL, 
	[SALES_AREA_KEY] int NOT NULL, 
	[DOCMT_CRNCY_KEY] int NOT NULL, 
	[CMPNY_CRNCY_KEY] int NOT NULL, 
	[GROUP_CRNCY_KEY] int NOT NULL, 
	[SALES_ORDER_QTY] decimal(15,3) NULL, 
	[SO Unit Of Measure] varchar(max) NULL, 
	[DOCMT_CRNCY_NET_PRICE] decimal(15,3) NULL, 
	[DOCMT_CRNCY_NET_VAL_AMT] decimal(15,3) NULL, 
	[DOCMT_CRNCY_TAX_AMT] decimal(15,3) NULL, 
	[CMPNY_CRNCY_NET_VAL_AMT] decimal(15,3) NULL, 
	[GROUP_CRNCY_NET_VAL_AMT] decimal(15,3) NULL, 
	[SO Shipping Point] varchar(max) NULL, 
	[SO Reason For Rejection] varchar(max) NULL, 
	[SO Overall Status] varchar(max) NULL, 
	[SO Delivery Status] varchar(max) NULL, 
	[SO Order Related Bill Status] varchar(max) NULL, 
	[Sales Order Header Encoway Id] varchar(max) NULL, 
	[SO Encoway Version] varchar(max) NULL, 
	[SO Encoway Part] varchar(max) NULL, 
	[SO Encoway Description] varchar(max) NULL, 
	[SO Encoway Number] varchar(max) NULL, 
	[SO Material Description] varchar(max) NULL, 
	[SO Delivery Group] varchar(max) NULL, 
	[QTY_NETTED] decimal(15,3) NULL, 
	[SO Reason For Rejection Description] varchar(max) NULL, 
	[SO Shipping Condition] varchar(max) NULL, 
	[SO Inco Terms] varchar(max) NULL, 
	[SO Inco Terms Description] varchar(max) NULL, 
	[SO Inco Terms 2] varchar(max) NULL, 
	[SO Billing Date] date NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NOT NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[CYLINDER_OWNER_CUST_KEY] int NULL, 
	[SO Usage] varchar(max) NULL, 
	[SO Higher-Level Item] int NULL, 
	[SO Alternative to Item] int NULL, 
	[MATRL_ENTERED_KEY] int NULL, 
	[SO Reference Document] varchar(max) NULL, 
	[SO Reference Item] int NULL, 
	[SO Reference Status] varchar(max) NULL, 
	[SO Total Reference Status] varchar(max) NULL, 
	[SO Billing Block] varchar(max) NULL, 
	[PERSON_RESPNSBLE_COST_CNTR_KEY] int NULL, 
	[PARNT_CUST_KEY] int NULL, 
	[CREATION_DATE_KEY] int NULL, 
	[SO Creation Timestamp] datetime2(0) NULL, 
	[SO Delivery Status Indicator] varchar(max) NULL, 
	[SO Sales UoM] varchar(max) NULL, 
	[SALES_TRGT_QTY] decimal(15,3) NULL, 
	[SO Target Quantity UoM] varchar(max) NULL, 
	[DLVRD_QTY] decimal(15,3) NULL, 
	[SO Is Sales Schedule Line Created] varchar(max) NULL, 
	[DOCMT_CHARS_ENCOWAY_JS_HDR_KEY] int NULL, 
	[EMPL_RESPNSBLE_2_KEY] int NULL, 
	[SO BOM Item Number] varchar(max) NULL, 
	[CUST_MATRL_INFO_RCD_KEY] int NULL, 
	[SO Changed On Date] date NULL, 
	[SO Relevant For Billing] varchar(max) NULL, 
	[SO Item Is Relevant For Delivery] varchar(max) NULL, 
	[WBS_ELEMNT_KEY] int NULL, 
	[AGENCY_CUST_KEY] int NULL, 
	[PRINTER_CUST_KEY] int NULL, 
	[SUPLR_CUST_KEY] int NULL, 
	[SO Billing Status Of Delivery] varchar(max) NULL, 
	[SO Approval] varchar(max) NULL, 
	[SO Arrangement] varchar(max) NULL, 
	[SO Delivery] varchar(max) NULL, 
	[SO Fixed DET] varchar(max) NULL, 
	[RSLTS_ANALYSIS_KEY] varchar(max) NULL, 
	[SO Purchase Order Item Number] varchar(max) NULL, 
	[SO Line Item System Status] varchar(max) NULL, 
	[SO Overall Status Description] varchar(max) NULL, 
	[Delivery Status Description] varchar(max) NULL, 
	[SO Order Related Bill Status Description] varchar(max) NULL, 
	[SO Shipping Condition Description] varchar(max) NULL, 
	[SO Usage Description] varchar(max) NULL, 
	[SO Reference Status Description] varchar(max) NULL, 
	[SO Total Reference Status Description] varchar(max) NULL, 
	[SO Billing Block Description] varchar(max) NULL, 
	[SO Delivery Status Indicator Description] varchar(max) NULL, 
	[SO Relevant For Billing Description] varchar(max) NULL, 
	[SO Billing Status Of Delivery Description] varchar(max) NULL, 
	[SO Results Analysis Description] varchar(max) NULL, 
	[SO Internal Customer Reference Number] varchar(max) NULL, 
	[Product Hierarchy] varchar(max) NULL, 
	[SO Sold To Purchase Order Number] varchar(max) NULL, 
	[SO Sold To Purchase Order Date] date NULL, 
	[SO Ship To Purchase Order Number] varchar(max) NULL, 
	[SO Ship To Purchase Order Date] date NULL, 
	[SO Customer Condition Group 1] varchar(max) NULL, 
	[SO Customer Condition Group 1 Description] varchar(max) NULL, 
	[SO Customer Material Number] varchar(max) NULL, 
	[EMPL_RESPNSBLE_KEY] int NULL, 
	[CUST_POJECT_MGR_KEY] int NULL, 
	[SO Item Category] varchar(max) NULL, 
	[SO Item Category Description] varchar(max) NULL, 
	[SHIP_TO_ADDR_KEY] int NULL, 
	[SO Delivery Priority Code] varchar(max) NULL, 
	[SO Delivery Priority Description] varchar(max) NULL, 
	[CREATED_BY] varchar(max) NULL, 
	[UNITIZATION_AGENT_VNDR_KEY] int NULL, 
	[SO Designable E Services Flag] varchar(max) NULL, 
	[SO Agreed Delivery Time] varchar(max) NULL, 
	[SO Deceased Name] varchar(max) NULL, 
	[SO Customer Purchase Order Type] varchar(max) NULL, 
	[SO Customer Purchase Order Type Description] varchar(max) NULL, 
	[ORDER_KEY] int NULL, 
	[SO Price Group] varchar(max) NULL, 
	[SO Price Group Description] varchar(max) NULL, 
	[CMLT_CONFIRMED_QTY_IN_BASE_UNIT] decimal(15,3) NULL, 
	[SO Base Unit Of Measure] varchar(max) NULL, 
	[COMPANY_INFO_CMPNY_CD_KEY] int NULL, 
	[SAL_SALORDH_INVOICE_CREATION_DATE_KEY] int NULL, 
	[SAL_SALORDH_CREATED_DATE_KEY] int NULL, 
	[PLANT_REGION_PLANT_ID] varchar(max) NULL, 
	[RESPNSBLE_COST_CNTR_V_HEIR_COST_CNTR_KEY] int NULL, 
	[PERSON_RESPNSBLE_COST_CNTR_H_HEIR_KEY] int NULL, 
	[FORWARDING_AGENT_VENDOR_KEY] int NULL, 
	[ORDER_FOR_CUSTOMER_ADDR_KEY] int NULL, 
	[SO_PARENT_CUST_KEY] int NULL, 
	[MST_PRTHRCY_PRDT_HIERCHY_CD] varchar(max) NULL, 
	[SOIPTNR_KEY] varchar(max) NULL, 
	[V_D_SAL_PRDVCON_KEY] varchar(max) NULL, 
	[PROFCHZ_PROFT_CNTR_KEY] int NULL, 
	[PROFCVZ_PROFT_CNTR_KEY] int NULL, 
	[CUSTCNT_CUST_CONTACT_KEY] int NULL, 
	[PERSON_RESPNSBLE_COST_CNTR_V_KEY] int NULL
);