CREATE TABLE [Propelis].[EDW_T_FACT_PRD_ENCPDAT_CUR_D] (

	[ENCP Job ID] bigint NOT NULL, 
	[ENCP Investigation Level] varchar(max) NULL, 
	[ENCP Brand] varchar(max) NULL, 
	[ENCP Category] varchar(max) NULL, 
	[ENCP Client] varchar(max) NULL, 
	[DISCOVERY_DATE_KEY] int NULL, 
	[ENCP Notification Number] varchar(max) NULL, 
	[ENCP Estimated Cost of Poor Quality] varchar(max) NULL, 
	[INVESTIGATION_START_DATE_KEY] int NULL, 
	[OCCURRENCE_DATE_KEY] int NULL, 
	[ENCP Other Impacted Service Orders] varchar(max) NULL, 
	[ENCP Primary Error Category] varchar(max) NULL, 
	[ENCP Primary Root Cause] varchar(max) NULL, 
	[ENCP Repeat Incident] varchar(max) NULL, 
	[ENCP Responsible Department] varchar(max) NULL, 
	[ENCP Secondary Error Category] varchar(max) NULL, 
	[ENCP Secondary Root Cause] varchar(max) NULL, 
	[ENCP SGK Error] varchar(max) NULL, 
	[ENCP SKU Description] varchar(max) NULL, 
	[ENCP Sold To Party Name] varchar(max) NULL, 
	[START_DATE_KEY] int NULL, 
	[ENCP Status] bigint NULL, 
	[SERVC_ORDER_KEY] int NULL, 
	[SALES_ORDER_KEY] int NULL, 
	[SOLD_TO_PARTY_KEY] int NULL, 
	[CUST_BRAND_HIERCHY_KEY] int NULL, 
	[SKU_MATRL_KEY] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[ENCP Potential Value of Claim $] varchar(max) NULL, 
	[ENCP Settled Value of Claim $] varchar(max) NULL, 
	[ENCP Describe Potential Impact Of The Error] varchar(max) NULL, 
	[ENCP On Hold Reason] varchar(max) NULL
);