CREATE TABLE [Propelis].[EDW_T_FACT_FI_ACCTRCV2_CUR_D] (

	[CMPNY_KEY] int NOT NULL, 
	[AR Document Header Number] varchar(max) NOT NULL, 
	[Baseline Due Fiscal Year] int NOT NULL, 
	[AR Ledger Code] varchar(max) NOT NULL, 
	[AR Ledger Posting Item Number] varchar(max) NOT NULL, 
	[PAYER_CUST_KEY] int NULL, 
	[AR Document Line Item Number] int NULL, 
	[AR Clearing Document Number] varchar(max) NULL, 
	[CLEARING_DATE_KEY] int NULL, 
	[AR Assignment Number] varchar(max) NULL, 
	[AR Special GL Transaction Type] varchar(max) NULL, 
	[AR Special GL Indicator] varchar(max) NULL, 
	[DOCMT_DATE_KEY] int NULL, 
	[PSTNG_DATE_KEY] int NULL, 
	[DOCMT_CRNCY_KEY] int NULL, 
	[CMPNY_CRNCY_KEY] int NULL, 
	[GROUP_CRNCY_KEY] int NULL, 
	[AR Posting Period] int NULL, 
	[AR Document Type] varchar(max) NULL, 
	[AR Reference Number] varchar(max) NULL, 
	[AR Invoice Reference Number] varchar(max) NULL, 
	[AR Reason Code] varchar(max) NULL, 
	[AR Reason Code Description] varchar(max) NULL, 
	[CMPNY_CRNCY_AMT] decimal(23,2) NULL, 
	[DOCMT_CRNCY_AMT] decimal(23,2) NULL, 
	[GROUP_CRNCY_AMT] decimal(23,2) NULL, 
	[PSTNG_KEY] varchar(max) NULL, 
	[DEBIT_CREDIT_IND] varchar(max) NULL, 
	[GL_KEY] int NULL, 
	[BSLINE_DUE_DATE_KEY] int NULL, 
	[AR Payment Terms] varchar(max) NULL, 
	[AR Days 1] decimal(3,0) NULL, 
	[AR Days 2] decimal(3,0) NULL, 
	[AR Days Net] decimal(3,0) NULL, 
	[AR Reference Key for Line Item] varchar(max) NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[SEG_KEY] int NULL, 
	[BILLING_DOCMT_KEY] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[AR Controlling Area] varchar(max) NULL, 
	[WBS_ELEMNT_KEY] int NULL, 
	[SALES_AREA_KEY] int NULL, 
	[CUST_SALES_AREA_KEY] int NULL, 
	[CUST_CREDIT_KEY] int NULL, 
	[AR Document Type Description] varchar(max) NULL, 
	[AR Special GL Indicator Description] varchar(max) NULL, 
	[AR Posting Key Description] varchar(max) NULL, 
	[AR Payment Terms Description] varchar(max) NULL, 
	[AR Controlling Area Description] varchar(max) NULL, 
	[AR Ledger Code Description] varchar(max) NULL, 
	[AR Item Text] varchar(max) NULL, 
	[AR Deletion Flag] varchar(max) NULL, 
	[AR Debit Credit Indicator] varchar(max) NULL, 
	[AR Expected Customer Sales Organization] varchar(max) NULL, 
	[AR Expected Customer Sales Organization Description] varchar(max) NULL, 
	[AR Expected Sales Organization] varchar(max) NULL, 
	[AR Expected Sales Organization Description] varchar(max) NULL, 
	[AR Dunning Block] varchar(max) NULL, 
	[AR Dunning Block Description] varchar(max) NULL, 
	[LAST_DUNNING_NOTICE_DATE_KEY] int NULL, 
	[AR Dunning Level] varchar(max) NULL, 
	[DUNNING_KEY] int NULL, 
	[AR Dunning Key Description] varchar(max) NULL, 
	[PROFCHZ_PROFT_CNTR_KEY] int NULL, 
	[PROFCVZ_PROFT_CNTR_KEY] int NULL
);