CREATE TABLE [Propelis].[EDW_T_FACT_PRD_FFUDATA_CUR_D] (

	[FFU Job ID] int NOT NULL, 
	[FFU Account Indicator] varchar(max) NULL, 
	[FFU Author] varchar(max) NULL, 
	[FFU Auto Status] varchar(max) NULL, 
	[FFU Brand] varchar(max) NULL, 
	[FFU Category] varchar(max) NULL, 
	[FFU Issue Category] varchar(max) NULL, 
	[FFU Issue Sub Category] varchar(max) NULL, 
	[FFU Query Type] varchar(max) NULL, 
	[FFU Sales Employee Name] varchar(max) NULL, 
	[FFU Site] varchar(max) NULL, 
	[FFU SKU Description] varchar(max) NULL, 
	[FFU Sold To Party Name] varchar(max) NULL, 
	[FFU Status] int NULL, 
	[SERVC_ORDER_KEY] int NULL, 
	[SALES_ORDER_KEY] int NULL, 
	[SOLD_TO_PARTY_KEY] int NULL, 
	[CUST_BRAND_HIERCHY_KEY] int NULL, 
	[SKU_MATRL_KEY] int NULL, 
	[SITE_KEY] int NULL, 
	[SALES_EMPL_KEY] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[CREATE_DATE_KEY] int NULL, 
	[FFU Create Date Timestamp] datetime2(0) NULL, 
	[FFU Status Name] varchar(max) NULL, 
	[FFU Additional Affected Service Orders] varchar(max) NULL, 
	[FFU Issue Category 2] varchar(max) NULL, 
	[FFU Issue Category 3] varchar(max) NULL, 
	[FFU Issue Category 4] varchar(max) NULL, 
	[FFU Issue Category 5] varchar(max) NULL, 
	[FFU Issue Category 6] varchar(max) NULL, 
	[FFU Issue Subcategory 2] varchar(max) NULL, 
	[FFU Issue Subcategory 3] varchar(max) NULL, 
	[FFU Issue Subcategory 4] varchar(max) NULL, 
	[FFU Issue Subcategory 5] varchar(max) NULL, 
	[FFU Issue Subcategory 6] varchar(max) NULL, 
	[FFU CSR2] varchar(max) NULL, 
	[FFU CSR] varchar(max) NULL, 
	[FFU Variant] varchar(max) NULL, 
	[FFU Proj Description] varchar(max) NULL, 
	[FFU Project Name] varchar(max) NULL, 
	[FFU Project Number] varchar(max) NULL, 
	[FFU Last Status Change] datetime2(0) NULL, 
	[FFU Error Description] varchar(max) NULL, 
	[FFU Resolution] varchar(max) NULL
);