CREATE TABLE [Propelis].[EDW_T_FACT_CO_COPABGT_CUR_D] (

	[COPA Currency Type] varchar(max) NOT NULL, 
	[COPA Currency Type Description] varchar(max) NULL, 
	[COPA Record Type] varchar(max) NOT NULL, 
	[COPA Version] varchar(max) NOT NULL, 
	[COPA Profit Segment] bigint NOT NULL, 
	[COPA Subnumber] int NOT NULL, 
	[COPA Document Number] varchar(max) NOT NULL, 
	[COPA Fiscal Year/Period Block] int NOT NULL, 
	[COPA Created On Date] date NULL, 
	[COPA Created By] varchar(max) NULL, 
	[COPA Fiscal Year] int NULL, 
	[SOLDTO_CUST_KEY] int NULL, 
	[MATRL_KEY] int NULL, 
	[FOREIGN_CRNCY_KEY] int NULL, 
	[CRNCY_KEY] int NULL, 
	[CUST_CMPNY_KEY] int NULL, 
	[COPA Controlling Area] varchar(max) NULL, 
	[COPA Controlling Area Description] varchar(max) NULL, 
	[PLNT_KEY] int NULL, 
	[SALES_AREA_KEY] int NULL, 
	[CUST_SALES_AREA_KEY] int NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[COPA Time Created] decimal(16,0) NULL, 
	[INDUS_KEY] varchar(max) NULL, 
	[COPA Industry Description] varchar(max) NULL, 
	[COPA Sales District] varchar(max) NULL, 
	[COPA Sales District Description] varchar(max) NULL, 
	[COPA Customer Group] varchar(max) NULL, 
	[COPA Customer Group Description] varchar(max) NULL, 
	[COPA Country Key] varchar(max) NULL, 
	[COPA Customer Group 2] varchar(max) NULL, 
	[COPA Customer Group 2 Description] varchar(max) NULL, 
	[COPA Material Group] varchar(max) NULL, 
	[COPA Material Group Description] varchar(max) NULL, 
	[COPA Postal Code] varchar(max) NULL, 
	[COPA Region] varchar(max) NULL, 
	[COPA Sales Office] varchar(max) NULL, 
	[COPA Sales Office Description] varchar(max) NULL, 
	[COPA Sales Group] varchar(max) NULL, 
	[COPA Sales Group Description] varchar(max) NULL, 
	[COPA Customer Group Assignment Group] varchar(max) NULL, 
	[COPA Cust Group Assignment Group Description] varchar(max) NULL, 
	[COPA City Coordinates] varchar(max) NULL, 
	[COPA Commission Group] varchar(max) NULL, 
	[COPA Commission Group Description] varchar(max) NULL, 
	[COPA Product Hierarchy Code] varchar(max) NULL, 
	[COPA Industry Code 1] varchar(max) NULL, 
	[COPA Industry Code 1 Description] varchar(max) NULL, 
	[COPA Industry Code 2] varchar(max) NULL, 
	[COPA Industry Code 2 Description] varchar(max) NULL, 
	[COPA Accounting Clerk] varchar(max) NULL, 
	[COPA Acctounting Clerk Description] varchar(max) NULL, 
	[COPA Sub Brand] int NULL, 
	[COPA Base UoM] varchar(max) NULL, 
	[SALES_QTY] decimal(15,3) NULL, 
	[REVNU_AMT] decimal(18,2) NULL, 
	[LABOR_COST_AMT] decimal(18,2) NULL, 
	[MATRL_COST_AMT] decimal(18,2) NULL, 
	[OVERHEAD_COST_AMT] decimal(18,2) NULL, 
	[OUTSIDE_PURCHASES_AMT] decimal(18,2) NULL, 
	[MATRL_SALES_KEY] int NULL, 
	[CMPNY_KEY] int NULL, 
	[COPA Sales Organization] varchar(max) NULL, 
	[COPA Sales Organization Description] varchar(max) NULL, 
	[COPA Distribution Channel] varchar(max) NULL, 
	[COPA Distribution Channel Description] varchar(max) NULL, 
	[COPA Division] varchar(max) NULL, 
	[COPA Division Description] varchar(max) NULL, 
	[COPA Brand] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[COPA Base UoM Description] varchar(max) NULL, 
	[GENERAL_AND_ADMIN_AMT] decimal(18,2) NULL, 
	[SELLING_EXPENSE_AMT] decimal(18,2) NULL, 
	[MCHINE_COSTS_AMT] decimal(18,2) NULL, 
	[SEG_KEY] int NULL, 
	[PROFCHZ_PROFT_CNTR_KEY ] int NULL, 
	[PROFCVZ_PROFT_CNTR_KEY ] int NULL
);