CREATE TABLE [Propelis].[EDW_T_FACT_IM_MATMVMT_CUR_D] (

	[Material Movement Document Number] varchar(max) NOT NULL, 
	[Material Movement Document Item Number] varchar(max) NOT NULL, 
	[Material Movement Document Year] int NOT NULL, 
	[SALES_ORDER_KEY] int NOT NULL, 
	[DOCMT_DATE_KEY] int NOT NULL, 
	[PSTNG_DATE_KEY] int NOT NULL, 
	[MATRL_KEY] int NOT NULL, 
	[CMPNY_KEY] int NOT NULL, 
	[PROFT_CNTR_KEY] int NOT NULL, 
	[PLNT_KEY] int NOT NULL, 
	[STOR_LOC_KEY] int NOT NULL, 
	[CUST_KEY] int NOT NULL, 
	[VNDR_KEY] int NOT NULL, 
	[CMPNY_CRNCY_KEY] int NOT NULL, 
	[GROUP_CRNCY_KEY] int NOT NULL, 
	[COST_CNTR_KEY] int NOT NULL, 
	[SALES_ORDER_ITM_ID] varchar(max) NULL, 
	[Material Movement Type Code] varchar(max) NULL, 
	[Material Movement Document Type] varchar(max) NULL, 
	[Material Movement Transaction Type] varchar(max) NULL, 
	[Material Movement Batch Number] varchar(max) NULL, 
	[Material Movement Order ID] varchar(max) NULL, 
	[Material Movement Purchase Order ID] varchar(max) NULL, 
	[Material Movement Reference Document Number] varchar(max) NULL, 
	[Material Movement Debit Credit Indicator] varchar(max) NULL, 
	[CMPNY_CRNCY_AMT] decimal(15,3) NULL, 
	[GROUP_CRNCY_AMT] decimal(15,3) NULL, 
	[QTY] decimal(13,3) NULL, 
	[Material Movement Quantity Unit of Measure] varchar(max) NULL, 
	[QTY_ENTRY_UNIT] decimal(13,3) NULL, 
	[Material Movement Quantity Entry Unit UOM] varchar(max) NULL, 
	[QTY_ORDER_UNIT] decimal(13,3) NULL, 
	[Material Movement Quantity Order Unit UOM] varchar(max) NULL, 
	[Material Movement Special Stock Indicator] varchar(max) NULL, 
	[Material Movement Special Stock Description] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[CREATION_DATE_KEY] int NULL, 
	[Material Movement Creation Timestamp] datetime2(0) NULL, 
	[Material Movement Purchase Order Item ID] varchar(max) NULL, 
	[RECVNG_PLNT_KEY] int NULL, 
	[PURCHS_ORDER_ITM_KEY] int NULL, 
	[Material Movement Line Item Text] varchar(max) NULL, 
	[PLNT_MATRL_KEY] int NULL, 
	[Material Movement Serial Number] varchar(max) NULL, 
	[Material Movement Stock Type] varchar(max) NULL, 
	[Material Movement Stock Type Description] varchar(max) NULL, 
	[COSTCHZ_COST_CNTR_KEY] int NULL, 
	[COSTCVZ_COST_CNTR_KEY] int NULL, 
	[PROFCHZ_PROFT_CNTR_KEY] int NULL, 
	[PROFCVZ_PROFT_CNTR_KEY] int NULL
);