CREATE TABLE [Propelis].[EDW_T_FACT_FI_GENLDGT2_CUR_D] (

	[Fiscal Year] int NULL, 
	[Table Group Object Number 00] int NULL, 
	[Table Group Object Number 01] int NULL, 
	[Table Group Object Number 03] int NULL, 
	[Table Group Object Number 04] int NULL, 
	[Table Group Object Number 02] int NULL, 
	[Table Group Object Number 05] int NULL, 
	[Table Group Object Number 06] int NULL, 
	[Table Group Object Number 07] int NULL, 
	[Table Group Object Number 08] int NULL, 
	[Max Period] int NULL, 
	[Debit Credit Indicator] varchar(8000) NOT NULL, 
	[Version] varchar(8000) NULL, 
	[Version Description] varchar(8000) NULL, 
	[Controlling Area] varchar(8000) NULL, 
	[Controlling Area Description] varchar(8000) NULL, 
	[Ledger] varchar(8000) NULL, 
	[Ledger Description] varchar(8000) NULL, 
	[DOCMT_CRNCY_KEY] int NULL, 
	[CMPNY_CRNCY_KEY] int NULL, 
	[GROUP_CRNCY_KEY] int NULL, 
	[Record Type] varchar(8000) NULL, 
	[Record Type Description] varchar(8000) NULL, 
	[CMPNY_KEY] int NULL, 
	[PRTNR_PROFT_CNTR_KEY] int NULL, 
	[FUNCTNL_AREA_KEY] int NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[GL_KEY] int NULL, 
	[TRNSCTN_CRNCY_AMT] decimal(18,2) NULL, 
	[CMPNY_CRNCY_AMT] decimal(18,2) NULL, 
	[GROUP_CRNCY_AMT] decimal(18,2) NULL, 
	[Posting Period] int NULL, 
	[SEG_KEY] int NULL, 
	[TRADING_PRTNR_CMPNY_KEY] int NULL, 
	[ETL_SRC_SYS_CD] varchar(8000) NULL, 
	[ETL_CREATED_TS] datetime2(6) NULL, 
	[ETL_UPDTD_TS] datetime2(6) NULL, 
	[Functional Area ID] varchar(8000) NULL, 
	[General Ledger Code] varchar(8000) NULL, 
	[PRTNR_PRFT_CNTR_V_HIER_KEY] int NULL, 
	[PRTNR_PRFT_CNTR_H_HIER_KEY] int NULL, 
	[Functional_GL_Key] varchar(8000) NULL, 
	[PROFCHZ_PROFT_CNTR_KEY] int NULL, 
	[PROFCVZ_PROFT_CNTR_KEY] int NULL
);