CREATE TABLE [Propelis].[EDW_T_FACT_PRD_SERVOPR_CUR_D] (

	[Service Order Execution Factor] decimal(3,0) NULL, 
	[Service Order Group Counter] varchar(max) NULL, 
	[Service Order Operation System Status] varchar(max) NULL, 
	[EMPL_RESPNSBLE_KEY] int NULL, 
	[Is Deletion Set] varchar(max) NULL, 
	[Sales Order Item] varchar(max) NULL, 
	[Sales Order ID] varchar(max) NULL, 
	[GROUP_CRNCY_ACTUAL_WRK_AMT] decimal(18,3) NULL, 
	[CMPNY_CRNCY_ACTUAL_WRK_AMT] decimal(18,3) NULL, 
	[GROUP_CRNCY_NORMAL_DUR_AMT] decimal(18,3) NULL, 
	[CMPNY_CRNCY_NORMAL_DUR_AMT] decimal(18,3) NULL, 
	[GROUP_CRNCY_WRK_INV_ACTIVITY_AM] decimal(18,3) NULL, 
	[CMPNY_CRNCY_WRK_INV_ACTIVITY_AM] decimal(18,3) NULL, 
	[OPERATION_LVL_WRK_CNTR_KEY] int NULL, 
	[Printer Specification Document Number] varchar(max) NULL, 
	[CUST_MATRL_INFO_RCD_KEY] int NULL, 
	[BRAND_OWNER_CUST_KEY] int NULL, 
	[Press Name] varchar(max) NULL, 
	[Service Order Task List Type Description] varchar(max) NULL, 
	[Activity Typ 06 PP Description] varchar(max) NULL, 
	[Activity Typ 04 PP Description] varchar(max) NULL, 
	[Activity Typ 03 PP Description] varchar(max) NULL, 
	[Activity Typ 02 PP Description] varchar(max) NULL, 
	[Activity Typ 01 PP Description] varchar(max) NULL, 
	[PARNT_CUST_KEY] int NULL, 
	[Operation User Status] varchar(max) NULL, 
	[Operations User Status Profile] varchar(max) NULL, 
	[Header User Status Profile] varchar(max) NULL, 
	[User Field 7 Unit] varchar(max) NULL, 
	[User Field 6 Unit] varchar(max) NULL, 
	[User Field 5 Unit] varchar(max) NULL, 
	[User Field 4 Unit] varchar(max) NULL, 
	[Regulatory Indicator] varchar(max) NULL, 
	[Recovery Indicator] varchar(max) NULL, 
	[General Counter For Order] int NULL, 
	[Created On] date NULL, 
	[User Field 08] date NULL, 
	[Order Complexity] int NULL, 
	[Created By] varchar(max) NULL, 
	[User Field 02] varchar(max) NULL, 
	[User Field 01] varchar(max) NULL, 
	[User Field 00] varchar(max) NULL, 
	[Service Order Task List Type] varchar(max) NULL, 
	[Second Line Description] varchar(max) NULL, 
	[Material Base Unit Of Measure] varchar(max) NULL, 
	[Actual Finish Date] date NULL, 
	[Activity Type PP 6] varchar(max) NULL, 
	[Activity Type PP 4] varchar(max) NULL, 
	[Activity Type PP 3] varchar(max) NULL, 
	[Activity Type PP 2] varchar(max) NULL, 
	[Activity Type PP 1] varchar(max) NULL, 
	[CREATED_ON_DATE_KEY] int NULL, 
	[Standard Text Key] varchar(max) NULL, 
	[FUNCTNL_AREA_KEY] int NULL, 
	[PERSONEL_NUM_KEY] int NULL, 
	[ACTIVITY_TYP_KEY] int NULL, 
	[SERVC_MATRL_KEY] int NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[Finish Constraint Timestamp] datetime2(0) NULL, 
	[FINISH_CNSTRNT_DATE_KEY] int NULL, 
	[Is Finish Constraint] varchar(max) NULL, 
	[Start Constraint Timestamp] datetime2(0) NULL, 
	[START_CNSTRNT_DATE_KEY] int NULL, 
	[Is Start Constraint] varchar(max) NULL, 
	[Is Correction Approval Rework Description] varchar(max) NULL, 
	[Is Correction Approval Rework] varchar(max) NULL, 
	[Sort Term] varchar(max) NULL, 
	[Is On Time Delivery Production Center] varchar(max) NULL, 
	[Is On Time Delivery Business Center] varchar(max) NULL, 
	[Is Right First Time Production Center] varchar(max) NULL, 
	[Is Right First Time Business Center] varchar(max) NULL, 
	[Account Indicator] decimal(13,3) NULL, 
	[PRINTER_CUST_KEY] int NULL, 
	[SOLD_TO_CUST_KEY] int NULL, 
	[SHIP_TO_CUST_KEY] int NULL, 
	[BILL_TO_CUST_KEY] int NULL, 
	[SALES_ORDER_KEY] int NULL, 
	[FUNCTNL_LOC_KEY] int NULL, 
	[SERVC_ORDER_KEY] int NULL, 
	[Latest Scheduled Start Execution Timestamp] datetime2(0) NULL, 
	[WRK_CNTR_KEY] int NULL, 
	[Control Key Description] varchar(max) NULL, 
	[Actual Finish Execution Timestamp] datetime2(0) NULL, 
	[ACTUAL_FINISH_EXCT_DATE_KEY] int NULL, 
	[Latest Scheduled Finish Execution Timestamp] datetime2(0) NULL, 
	[LATEST_SCHLD_FINISH_EXCT_DATE_KEY] int NULL, 
	[Earliest Scheduled Finish Execution Timestamp] datetime2(0) NULL, 
	[ERLST_SCHED_FINISH_EXCT_DATE_KEY] int NULL, 
	[Actual Start Execution Setup Timestamp] datetime2(0) NULL, 
	[ACTUAL_START_EXCT_DATE_KEY] int NULL, 
	[LATEST_SCHLD_START_EXCT_DATE_KEY] int NULL, 
	[Earliest Scheduled Start Execution Timestamp] datetime2(0) NULL, 
	[ERLST_SCHLD_START_EXCT_DATE_KEY] int NULL, 
	[FORECASTED_WRK_ACTUAL_REMG] decimal(8,1) NULL, 
	[ACTUAL_WRK] decimal(16,3) NULL, 
	[Normal Duration UOM] varchar(max) NULL, 
	[NORMAL_DUR_OF_THE_ACTIVITY] decimal(6,1) NULL, 
	[WRK_UOM] varchar(max) NULL, 
	[WRK_INVOLVED_IN_THE_ACTIVITY] decimal(7,1) NULL, 
	[PRICE] decimal(12,2) NULL, 
	[Work Percentage] int NULL, 
	[Operation Short Text] varchar(max) NULL, 
	[Object Number] varchar(max) NULL, 
	[Object ID] int NULL, 
	[CTRL_KEY] varchar(max) NULL, 
	[Breakdown Duration] decimal(32,16) NULL, 
	[Breakdown Duration UOM] varchar(max) NULL, 
	[End Of Malfunction Timestamp] datetime2(0) NULL, 
	[END_OF_MALFUNCTION_DATE_KEY] int NULL, 
	[Start Of Malfunction Timestamp] datetime2(0) NULL, 
	[START_OF_MALFUNCTION_DATE_KEY] int NULL, 
	[COST_CNTR_KEY] int NULL, 
	[NOTIFICATION_KEY] int NULL, 
	[PLNG_PLNT_KEY] int NULL, 
	[EQUIP_KEY] int NULL, 
	[Service Order Capacity Requirements ID] int NULL, 
	[TRGT_QTY] decimal(13,3) NULL, 
	[TOTAL_SCRAP_AMT] decimal(13,3) NULL, 
	[PLND_RELS_DATE_KEY] int NULL, 
	[ACTUAL_RELS_DATE_KEY] int NULL, 
	[ACTUAL_FINISH_DATE_KEY] int NULL, 
	[ACTUAL_START_DATE_KEY] int NULL, 
	[SCHLD_START_DATE_KEY] int NULL, 
	[SCHLD_FINISH_DATE_KEY] int NULL, 
	[SCHLD_RELS_DATE_KEY] int NULL, 
	[BASIC_FINISH_DATE_KEY] int NULL, 
	[BASIC_START_DATE_KEY] int NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[RESPNSBLE_COST_CNTR_KEY] int NULL, 
	[MAINTENANCE_PLNT_KEY] int NULL, 
	[LOC_PLNT_KEY] int NULL, 
	[CLS_DATE_KEY] int NULL, 
	[TCHNCL_COMPLETION_DATE_KEY] int NULL, 
	[RELS_DATE_KEY] int NULL, 
	[DOCMT_CRNCY_KEY] int NULL, 
	[PLNT_KEY] int NULL, 
	[CMPNY_CD_KEY] int NULL, 
	[Order Category] int NULL, 
	[Service Order Order Type] varchar(max) NULL, 
	[Operation Counter] int NULL, 
	[Operation Sequence ID] varchar(max) NULL, 
	[Operation Activity ID] varchar(max) NULL, 
	[Operation Confirmation ID] int NULL, 
	[Operation Counter ID] int NULL, 
	[Operation Task List ID] int NULL, 
	[Service Order] varchar(max) NULL, 
	[PRDVCON_KEY] varchar(max) NULL, 
	[SOIPTNR_KEY] varchar(max) NULL, 
	[PLANT_REGION_PLANT] int NULL, 
	[LOCATION_PLANT_REGION_PLANT] int NULL, 
	[PLANNING_PLANT_REGION_PLANT] int NULL, 
	[OPERATING_PLANT_REGION_PLANT] int NULL, 
	[MAINTENANCE_PLANT_REGION_PLANT] int NULL, 
	[PERSONNEL_PLANT_REGION_PLANT] int NULL, 
	[SALES_EMPLOYEE_PERSONEL_KEY] varchar(max) NULL, 
	[SO_PARENT_CUST_KEY] varchar(max) NULL, 
	[PROFCHZ_PROFT_CNTR_KEY] int NULL, 
	[PROFCVZ_PROFT_CNTR_KEY] int NULL, 
	[WORKCHZ_WRK_CNTR_KEY] int NULL, 
	[WORKCVZ_WRK_CNTR_KEY] int NULL, 
	[OPER_PLANT_KEY] int NULL
);