CREATE TABLE [Propelis].[EDW_T_FACT_PRD_SERVRES_CUR_D] (

	[Service Order] varchar(max) NOT NULL, 
	[Operation Activity ID] varchar(max) NOT NULL, 
	[DOCMT_CRNCY_KEY] int NOT NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Quantity Withdrawn] decimal(15,3) NULL, 
	[Price in Document Currency] decimal(15,3) NULL, 
	[Quantity In Unit Of Entry] decimal(15,3) NULL, 
	[Requirement Quantity] decimal(15,3) NULL, 
	[Value Withdrawn Amount] decimal(15,3) NULL, 
	[PLNT_KEY] int NOT NULL, 
	[Debit Credit Indicator] varchar(max) NULL, 
	[MOVEMNT_TYP] varchar(max) NULL, 
	[Requirement Type] varchar(max) NULL, 
	[Base UoM] varchar(max) NULL, 
	[Unit Of Entry] varchar(max) NULL, 
	[Record Type] varchar(max) NULL, 
	[REQ_DATE_KEY] int NOT NULL, 
	[GL_KEY] int NOT NULL, 
	[MATRL_KEY] int NOT NULL, 
	[BOM Item Number] varchar(max) NULL, 
	[SERVC_ORDER_KEY] int NULL, 
	[PLANT_REGION_PLANT] varchar(max) NULL, 
	[Operation Task List ID] int NULL, 
	[Operation Counter ID] int NULL, 
	[Number of Reservation] int NULL, 
	[Item Number of Reservation] int NULL, 
	[Price Unit] decimal(15,3) NULL, 
	[Fixed Quantity] varchar(max) NULL
);