CREATE TABLE [Propelis].[EMPLOYEE_RESP] (

	[PERSONEL_KEY] int NOT NULL, 
	[Personnel Number] varchar(8) NULL, 
	[Company Code] varchar(4) NULL, 
	[Plant ID] varchar(4) NULL, 
	[Cost Center ID] varchar(10) NULL, 
	[Success Factors ID] varchar(8) NULL, 
	[Employee First Name] varchar(40) NULL, 
	[Employee Last Name] varchar(40) NULL, 
	[Employee Full Name] varchar(80) NULL, 
	[Employee Status Indicator] varchar(1) NULL, 
	[Employment Start Date] date NULL, 
	[Employment End Date] date NULL, 
	[Employee Group ID] varchar(1) NULL, 
	[Employee Group Description] varchar(40) NULL, 
	[Employee Subgroup ID] varchar(2) NULL, 
	[Employee Subgroup Description] varchar(40) NULL, 
	[Employee Telephone 1] varchar(16) NULL, 
	[Employee Telephone 2] varchar(16) NULL, 
	[Email Address] varchar(500) NULL, 
	[Created Date] date NULL, 
	[Created User ID] varchar(12) NULL, 
	[Updated Date] date NULL, 
	[Updated User ID] varchar(12) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Company Description] varchar(25) NULL, 
	[Plant Description] varchar(30) NULL
);