CREATE TABLE [Propelis].[EMPLOYEE_RESPONSIBLE] (

	[PERSONEL_KEY] int NOT NULL, 
	[PERSONEL_NUM] varchar(8) NULL, 
	[CMPNY_CD] varchar(4) NULL, 
	[PLNT_ID] varchar(4) NULL, 
	[COST_CNTR_ID] varchar(10) NULL, 
	[SUCCESS_FACTORS_ID] varchar(8) NULL, 
	[EMPL_FIRST_NAME] varchar(40) NULL, 
	[EMPL_LAST_NAME] varchar(40) NULL, 
	[EMPL_FULL_NAME] varchar(80) NULL, 
	[EMPL_STATUS_IND] varchar(1) NULL, 
	[EMPLNT_START_DATE] date NULL, 
	[EMPLNT_END_DATE] date NULL, 
	[EMPL_GROUP_ID] varchar(1) NULL, 
	[EMPL_GROUP_DESC] varchar(40) NULL, 
	[EMPL_SUBGRP_ID] varchar(2) NULL, 
	[EMPL_SUBGRP_DESC] varchar(40) NULL, 
	[EMPL_TEL_1] varchar(16) NULL, 
	[EMPL_TEL_2] varchar(16) NULL, 
	[EMAIL_ADDR] varchar(500) NULL, 
	[CREATED_DATE] date NULL, 
	[CREATED_USR_ID] varchar(12) NULL, 
	[UPDTD_DATE] date NULL, 
	[UPDTD_USR_ID] varchar(12) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[CMPNY_DESC] varchar(25) NULL, 
	[PLNT_DESC] varchar(30) NULL
);