CREATE TABLE [Propelis].[END_OF_MALFUNCTION_DATE] (

	[DATE_KEY] int NOT NULL, 
	[End Of Malfunction Date] date NULL, 
	[End Of Malfunction Fiscal Year] int NULL, 
	[End Of Malfunction Fiscal Period Number] int NULL, 
	[End Of Malfunction Fiscal Period Code] varchar(max) NULL, 
	[End Of Malfunction Fiscal Quarter Number] int NULL, 
	[End Of Malfunction Fiscal Quarter Code] varchar(max) NULL, 
	[End Of Malfunction Calendar Year] int NULL, 
	[End Of Malfunction Calendar Month Number] int NULL, 
	[End Of Malfunction Calendar Month Code] varchar(max) NULL, 
	[End Of Malfunction Calendar Month Description] varchar(max) NULL, 
	[End Of Malfunction Calendar Quarter Number] int NULL, 
	[End Of Malfunction Calendar Quarter Code] varchar(max) NULL, 
	[End Of Malfunction Calendar Weekday Number] int NULL, 
	[End Of Malfunction Calendar Weekday Name] varchar(max) NULL, 
	[End Of Malfunction Calendar Day In Month] int NULL, 
	[End Of Malfunction Calendar Day In Year] int NULL, 
	[End Of Malfunction Calendar Week] int NULL, 
	[End Of Malfunction Calendar Month In Quarter Number] int NULL, 
	[End Of Malfunction Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[End Of Malfunction Current Day Flag] int NULL, 
	[End Of Malfunction Current Day Minus 1 Flag] int NULL, 
	[End Of Malfunction Current Calendar Week Flag] int NULL, 
	[End Of Malfunction Current Calendar Week Minus 1 Flag] int NULL, 
	[End Of Malfunction Current Month Flag] int NULL, 
	[End Of Malfunction Current Month Minus 1 Flag] int NULL, 
	[End Of Malfunction Current Month Minus 12 Flag] int NULL, 
	[End Of Malfunction Current Quarter Flag] int NULL, 
	[End Of Malfunction Current Quarter Minus 1 Flag] int NULL, 
	[End Of Malfunction Current Quarter Minus 4 Flag] int NULL, 
	[End Of Malfunction Current Calendar Year Flag] int NULL, 
	[End Of Malfunction Current Calendar Year Minus 1 Flag] int NULL, 
	[End Of Malfunction Current Calendar Year Minus 2 Flag] int NULL, 
	[End Of Malfunction Current Fiscal Year Flag] int NULL, 
	[End Of Malfunction Current Fiscal Year Minus 1 Flag] int NULL, 
	[End Of Malfunction Current Fiscal Year Minus 2 Flag] int NULL, 
	[End Of Malfunction Current Calendar Year Plus 1 Flag] int NULL, 
	[CURR_FISCAL_YR_PLUS_1_FLG] int NULL, 
	[End Of Malfunction Day In Fiscal Year] int NULL, 
	[End Of Malfunction Date Is Weekday] int NULL, 
	[End Of Malfunction Fiscal Week] int NULL, 
	[End Of Malfunction Current Fiscal Week Flag] int NULL, 
	[End Of Malfunction Current Fiscal Week Minus 1 Flag] int NULL, 
	[End Of Malfunction Fiscal Weekday Number] int NULL, 
	[End Of Malfunction Fiscal Weekday Name] varchar(max) NULL, 
	[End Of Malfunction Current Month Minus 2 Flag] int NULL, 
	[End Of Malfunction Current Fiscal Week Minus 2 Flag] int NULL, 
	[End Of Malfunction Current Fiscal Week Minus 6 Flag] int NULL, 
	[End Of Malfunction Current Fiscal Week Minus 3 Flag] int NULL, 
	[End Of Malfunction Current Fiscal Week Minus 4 Flag] int NULL, 
	[End Of Malfunction Current Fiscal Week Minus 5 Flag] int NULL, 
	[End Of Malfunction Current Fiscal Week Minus 7 Flag] int NULL
);