CREATE TABLE [Propelis].[Entity_Company] (

	[CMPNY_KEY] int NOT NULL, 
	[Entity Company Code] varchar(4) NULL, 
	[Entity Legacy Company Code] varchar(10) NULL, 
	[Entity Company Name] varchar(60) NULL, 
	[Entity Company Line Of Business Code] varchar(20) NULL, 
	[Entity Company Line Of Business Code Description] varchar(255) NULL, 
	[Entity Company Currency Code] varchar(5) NULL, 
	[Entity Company Language Type Code] varchar(1) NULL, 
	[Entity Company Chart Of Accounts ID] varchar(4) NULL, 
	[Entity Company Entity Address Line 1] varchar(60) NULL, 
	[Entity Company Entity Address Line 2] varchar(60) NULL, 
	[Entity Company Entity City Name] varchar(40) NULL, 
	[Entity Company Entity Zip Code] varchar(10) NULL, 
	[Entity Company Entity Country Code] varchar(3) NULL, 
	[Entity Company Entity Telephone 1] varchar(30) NULL, 
	[Entity Company Entity Telephone 2] varchar(30) NULL, 
	[Entity Company Fax Number] varchar(30) NULL, 
	[Entity Company Tax Jurisdiction] varchar(15) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Entity Company Fiscal Year Variant] varchar(2) NULL, 
	[Entity Company Credit Control Area] varchar(4) NULL, 
	[Entity Company Input Tax Code] varchar(2) NULL, 
	[Entity Company Output Tax Code] varchar(2) NULL, 
	[Entity Company Currency Description] varchar(15) NULL, 
	[Entity Company Chart Of Accounts Description] varchar(50) NULL, 
	[Entity Company Country Description] varchar(15) NULL, 
	[Entity Company Fiscal Year Variant Description] varchar(30) NULL, 
	[Entity Company Credit Control Area Description] varchar(35) NULL
);