CREATE TABLE [Propelis].[FINISH_CONSTRAINT_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Finish Constraint Date] date NULL, 
	[Finish Constraint Fiscal Year] int NULL, 
	[Finish Constraint Fiscal Period Number] int NULL, 
	[Finish Constraint Fiscal Period Code] varchar(max) NULL, 
	[Finish Constraint Fiscal Quarter Number] int NULL, 
	[Finish Constraint Fiscal Quarter Code] varchar(max) NULL, 
	[Finish Constraint Calendar Year] int NULL, 
	[Finish Constraint Calendar Month Number] int NULL, 
	[Finish Constraint Calendar Month Code] varchar(max) NULL, 
	[Finish Constraint Calendar Month Description] varchar(max) NULL, 
	[Finish Constraint Calendar Quarter Number] int NULL, 
	[Finish Constraint Calendar Quarter Code] varchar(max) NULL, 
	[Finish Constraint Calendar Weekday Number] int NULL, 
	[Finish Constraint Calendar Weekday Name] varchar(max) NULL, 
	[Finish Constraint Calendar Day In Month] int NULL, 
	[Finish Constraint Calendar Day In Year] int NULL, 
	[Finish Constraint Calendar Week] int NULL, 
	[Finish Constraint Calendar Month In Quarter Number] int NULL, 
	[Finish Constraint Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Finish Constraint Current Day Flag] int NULL, 
	[Finish Constraint Current Day Minus 1 Flag] int NULL, 
	[Finish Constraint Current Calendar Week Flag] int NULL, 
	[Finish Constraint Current Calendar Week Minus 1 Flag] int NULL, 
	[Finish Constraint Current Month Flag] int NULL, 
	[Finish Constraint Current Month Minus 1 Flag] int NULL, 
	[Finish Constraint Current Month Minus 12 Flag] int NULL, 
	[Finish Constraint Current Quarter Flag] int NULL, 
	[Finish Constraint Current Quarter Minus 1 Flag] int NULL, 
	[Finish Constraint Current Quarter Minus 4 Flag] int NULL, 
	[Finish Constraint Current Calendar Year Flag] int NULL, 
	[Finish Constraint Current Calendar Year Minus 1 Flag] int NULL, 
	[Finish Constraint Current Calendar Year Minus 2 Flag] int NULL, 
	[Finish Constraint Current Fiscal Year Flag] int NULL, 
	[Finish Constraint Current Fiscal Year Minus 1 Flag] int NULL, 
	[Finish Constraint Current Fiscal Year Minus 2 Flag] int NULL, 
	[Finish Constraint Current Calendar Year Plus 1 Flag] int NULL, 
	[Finish Constraint Current Calendar Year Plus 2 Flag] int NULL, 
	[Finish Constraint Day In Fiscal Year] int NULL, 
	[Finish Constraint Date Is Weekday] int NULL, 
	[Finish Constraint Fiscal Week] int NULL, 
	[Finish Constraint Current Fiscal Week Flag] int NULL, 
	[Finish Constraint Current Fiscal Week Minus 1 Flag] int NULL, 
	[Finish Constraint Fiscal Weekday Number] int NULL, 
	[Finish Constraint Fiscal Weekday Name] varchar(max) NULL, 
	[Finish Constraint Current Month Minus 2 Flag] int NULL, 
	[Finish Constraint Current Fiscal Week Minus 2 Flag] int NULL, 
	[Finish Constraint Current Fiscal Week Minus 6 Flag] int NULL, 
	[Finish Constraint Current Fiscal Week Minus 3 Flag] int NULL, 
	[Finish Constraint Current Fiscal Week Minus 4 Flag] int NULL, 
	[Finish Constraint Current Fiscal Week Minus 5 Flag] int NULL, 
	[Finish Constraint Current Fiscal Week Minus 7 Flag] int NULL
);