CREATE TABLE [Propelis].[FORWARDING_AGENT_VENDOR] (

	[VNDR_KEY] int NOT NULL, 
	[Forwarding Agent Vendor ID] varchar(max) NULL, 
	[Forwarding Agent Vendor Name] varchar(max) NULL, 
	[Forwarding Agent Vendor Description] varchar(max) NULL, 
	[Forwarding Agent Vendor Account Group] varchar(max) NULL, 
	[Forwarding Agent Vendor Title] varchar(max) NULL, 
	[Forwarding Agent Vendor Search Term] varchar(max) NULL, 
	[Forwarding Agent Vendor Street] varchar(max) NULL, 
	[Forwarding Agent Vendor City Name] varchar(max) NULL, 
	[Forwarding Agent Vendor Zip Code] varchar(max) NULL, 
	[Forwarding Agent Vendor Country Code] varchar(max) NULL, 
	[Forwarding Agent Vendor State] varchar(max) NULL, 
	[Forwarding Agent Vendor Telephone Number 1 Code] varchar(max) NULL, 
	[Forwarding Agent Vendor Fax Number Code] varchar(max) NULL, 
	[Forwarding Agent Vendor Tax Number 1 Code] varchar(max) NULL, 
	[Forwarding Agent Vendor Tax Number 2 Code] varchar(max) NULL, 
	[Forwarding Agent Vendor VAT Number Code] varchar(max) NULL, 
	[Forwarding Agent Vendor Express Station] varchar(max) NULL, 
	[Forwarding Agent Vendor Transportation Zone] varchar(max) NULL, 
	[Forwarding Agent Vendor Industry] varchar(max) NULL, 
	[Forwarding Agent Vendor Created Date] date NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Forwarding Agent Vendor Address Number] varchar(max) NULL, 
	[Forwarding Agent Vendor Account Group Description] varchar(max) NULL, 
	[Forwarding Agent Vendor Country Description] varchar(max) NULL, 
	[Forwarding Agent Vendor Region Description] varchar(max) NULL, 
	[Forwarding Agent Vendor Transportation Zone Description] varchar(max) NULL, 
	[Forwarding Agent Vendor Industry Description] varchar(max) NULL, 
	[Forwarding Agent Vendor Created By] varchar(max) NULL, 
	[Forwarding Agent Vendor Central Deletion Indicator] varchar(max) NULL, 
	[Forwarding Agent Vendor Central Posting Block] varchar(max) NULL, 
	[Forwarding Agent Vendor Central Purchasing Block] varchar(max) NULL, 
	[Forwarding Agent Vendor Language Key] varchar(max) NULL, 
	[Forwarding Agent Vendor Customer ID] varchar(max) NULL, 
	[Forwarding Agent Vendor One Time Account Indicator] varchar(max) NULL, 
	[Forwarding Agent Vendor One Time Account Reference Group] varchar(max) NULL, 
	[Forwarding Agent Vendor One Time Account Reference Group Desc] varchar(max) NULL, 
	[Forwarding Agent Vendor Trading Partner] varchar(max) NULL, 
	[Forwarding Agent Vendor Trading Partner Description] varchar(max) NULL, 
	[Forwarding Agent Vendor VAT Indicator] varchar(max) NULL, 
	[Forwarding Agent Vendor Industry Type] varchar(max) NULL, 
	[Forwarding Agent Vendor Business Type] varchar(max) NULL, 
	[Forwarding Agent Vendor Payment Block] varchar(max) NULL, 
	[Forwarding Agent Vendor Tax Jurisdiction] varchar(max) NULL, 
	[Forwarding Agent Vendor Tax Number 3 Code] varchar(max) NULL, 
	[Forwarding Agent Vendor Tax Number Type] varchar(max) NULL, 
	[Forwarding Agent Vendor Tax Type] varchar(max) NULL, 
	[Forwarding Agent Vendor Level 1] varchar(max) NULL, 
	[Forwarding Agent Vendor Level 2] varchar(max) NULL, 
	[Forwarding Agent Vendor Level 3] varchar(max) NULL, 
	[Forwarding Agent Vendor Level 4] varchar(max) NULL, 
	[Forwarding Agent Vendor Addressable] varchar(max) NULL, 
	[Forwarding Agent Tail Vendor] varchar(max) NULL, 
	[Forwarding Agent Vendor Normalized] varchar(max) NULL, 
	[Forwarding Agent Vendor Corporate Group] varchar(max) NULL, 
	[Forwarding Agent Vendor Account No Alternate Payee] varchar(max) NULL, 
	[Forwarding Agent Vendor Email Address] varchar(max) NULL
);