CREATE TABLE [Propelis].[GOODS_ISSUE_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Goods Issue Date] date NULL, 
	[Goods Issue Fiscal Year] int NULL, 
	[Goods Issue Fiscal Period] int NULL, 
	[Goods Issue Fiscal Period Code] varchar(max) NULL, 
	[Goods Issue Fiscal Quarter Number] int NULL, 
	[Goods Issue Fiscal Quarter Code] varchar(max) NULL, 
	[Goods Issue Calendar Year] int NULL, 
	[Goods Issue Calendar Month Number] int NULL, 
	[Goods Issue Calendar Month Code] varchar(max) NULL, 
	[Goods Issue Calendar Month Desc] varchar(max) NULL, 
	[Goods Issue Calendar Quarter] int NULL, 
	[Goods Issue Calendar Quarter Code] varchar(max) NULL, 
	[Goods Issue Calendar Weekday Number] int NULL, 
	[Goods Issue Calendar Weekday Name] varchar(max) NULL, 
	[Goods Issue Calendar Day in Month] int NULL, 
	[Goods Issue Calendar Day in Year] int NULL, 
	[Goods Issue Calendar Week] int NULL, 
	[Goods Issue Calendar Month in Quarter Number] int NULL, 
	[Goods Issue Calendar Days in Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Goods Issue Current Day Flag] int NULL, 
	[Goods Issue Current Day Minus 1 Flag] int NULL, 
	[Goods Issue Current Calendar Week Flag] int NULL, 
	[Goods Issue Current Calendar Week Minus 1 Flag] int NULL, 
	[Goods Issue Current Month Flag] int NULL, 
	[Goods Issue Current Month Minus 1 Flag] int NULL, 
	[Goods Issue Current Month Minus 12 Flag] int NULL, 
	[Goods Issue Current Quarter Flag] int NULL, 
	[Goods Issue Current Quarter Minus 1 Flag] int NULL, 
	[Goods Issue Current Quarter Minus 4 Flag] int NULL, 
	[Goods Issue Current Calendar Year Flag] int NULL, 
	[Goods Issue Current Calendar Year Minus 1 Flag] int NULL, 
	[Goods Issue Current Calendar Year Minus 2 Flag] int NULL, 
	[Goods Issue Current Fiscal Year Flag] int NULL, 
	[Goods Issue Current Fiscal Year Minus 1 Flag] int NULL, 
	[Goods Issue Current Fiscal Year Minus 2 Flag] int NULL, 
	[Goods Issue Current Calendar Year Plus 1 Flag] int NULL, 
	[Goods Issue Current Fiscal Year Plus 1 Flag] int NULL, 
	[Goods Issue Day In Fiscal Year] int NULL, 
	[Goods Issue Date Is Weekday] int NULL, 
	[Goods Issue Fiscal Week] int NULL, 
	[Goods Issue Current Fiscal Week Flag] int NULL, 
	[Goods Issue Current Fiscal Week Minus 1 Flag] int NULL, 
	[Goods Issue Fiscal Weekday Number] int NULL, 
	[Goods Issue Fiscal Weekday Name] varchar(max) NULL, 
	[Goods Issue Current Month Minus 2 Flag] int NULL, 
	[Goods Issue Current Fiscal Week Minus 2 Flag] int NULL, 
	[Goods Issue Current Fiscal Week Minus 6 Flag] int NULL, 
	[Goods Issue Current Fiscal Week Minus 3 Flag] int NULL, 
	[Goods Issue Current Fiscal Week Minus 4 Flag] int NULL, 
	[Goods Issue Current Fiscal Week Minus 5 Flag] int NULL, 
	[Goods Issue Current Fiscal Week Minus 7 Flag] int NULL
);