CREATE TABLE [Propelis].[GOODS_ISSUED_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Goods Issued Date] date NULL, 
	[Goods Issued Fiscal Year] int NULL, 
	[Goods Issued Fiscal Period] int NULL, 
	[Goods Issued Fiscal Period Code] varchar(max) NULL, 
	[Goods Issued Fiscal Quarter Number] int NULL, 
	[Goods Issued Fiscal Quarter Code] varchar(max) NULL, 
	[Goods Issued Calendar Year] int NULL, 
	[Goods Issued Calendar Month Number] int NULL, 
	[Goods Issued Calendar Month Code] varchar(max) NULL, 
	[Goods Issued Calendar Month Desc] varchar(max) NULL, 
	[Goods Issued Calendar Quarter Number] int NULL, 
	[Goods Issued Calendar Quarter Code] varchar(max) NULL, 
	[Goods Issued Calendar Weekday Number] int NULL, 
	[Goods Issued Calendar Weekday Name] varchar(max) NULL, 
	[Goods Issued Calendar Day in Month] int NULL, 
	[Goods Issued Calendar Day in Year] int NULL, 
	[Goods Issued Calendar Week] int NULL, 
	[Goods Issued Calendar Month in Quarter Number] int NULL, 
	[Goods Issued Calendar Days in Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Goods Issued Current Day Flag] int NULL, 
	[Goods Issued Current Day Minus 1 Flag] int NULL, 
	[Goods Issued Current Calendar Week Flag] int NULL, 
	[Goods Issued Current Calendar Week Minus 1 Flag] int NULL, 
	[Goods Issued Current Month Flag] int NULL, 
	[Goods Issued Current Month Minus 1 Flag] int NULL, 
	[Goods Issued Current Month Minus 12 Flag] int NULL, 
	[Goods Issued Current Quarter Flag] int NULL, 
	[Goods Issued Current Quarter Minus 1 Flag] int NULL, 
	[Goods Issued Current Quarter Minus 4 Flag] int NULL, 
	[Goods Issued Current Calendar Year Flag] int NULL, 
	[Goods Issued Current Calendar Year Minus 1 Flag] int NULL, 
	[Goods Issued Current Calendar Year Minus 2 Flag] int NULL, 
	[Goods Issued Current Fiscal Year Flag] int NULL, 
	[Goods Issued Current Fiscal Year Minus 1 Flag] int NULL, 
	[Goods Issued Current Fiscal Year Minus 2 Flag] int NULL, 
	[Goods Issued Current Calendar Year Plus 1 Flag] int NULL, 
	[Goods Issued Current Fiscal Year Plus 1 Flag] int NULL, 
	[Goods Issued Day in Fiscal Year] int NULL, 
	[Goods Issued Date Is Weekday] int NULL, 
	[Goods Issued Fiscal Week] int NULL, 
	[Goods Issued Current Fiscal Week Flag] int NULL, 
	[Goods Issued Current Fiscal Week Minus 1 Flag] int NULL, 
	[Goods Issued Fiscal Weekday Number] int NULL, 
	[Goods Issued Fiscal Weekday Name] varchar(max) NULL, 
	[Goods Issued Current Month Minus 2 Flag] int NULL, 
	[Goods Issued Current Fiscal Week Minus 2 Flag] int NULL, 
	[Goods Issued Current Fiscal Week Minus 6 Flag] int NULL, 
	[Goods Issued Current Fiscal Week Minus 3 Flag] int NULL, 
	[Goods Issued Current Fiscal Week Minus 4 Flag] int NULL, 
	[Goods Issued Current Fiscal Week Minus 5 Flag] int NULL, 
	[Goods Issued Current Fiscal Week Minus 7 Flag] int NULL
);