CREATE TABLE [Propelis].[INTER_COMPANY] (

	[CMPNY_KEY] int NOT NULL, 
	[Inter Company Code] varchar(4) NULL, 
	[Inter Company Legacy Code] varchar(10) NULL, 
	[Inter Company Name] varchar(60) NULL, 
	[Inter Company Line Of Business Code] varchar(20) NULL, 
	[Inter Company Line Of Business Description] varchar(255) NULL, 
	[Inter Company Currency Code] varchar(5) NULL, 
	[Inter Company Language Type Code] varchar(1) NULL, 
	[Inter Company Chart Of Accounts ID] varchar(4) NULL, 
	[Inter Company Address Line 1] varchar(60) NULL, 
	[Inter Company Address Line 2] varchar(60) NULL, 
	[Inter Company City Name] varchar(40) NULL, 
	[Inter Company Zip Code] varchar(10) NULL, 
	[Inter Company Country Code] varchar(3) NULL, 
	[Company Telephone 1] varchar(30) NULL, 
	[Company Telephone 2] varchar(30) NULL, 
	[Inter Company Fax Number] varchar(30) NULL, 
	[Inter Company Tax Jurisdiction] varchar(15) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Inter Company Fiscal Year Variant] varchar(2) NULL, 
	[Inter Company Credit Control Area] varchar(4) NULL, 
	[Inter Company Input Tax Code] varchar(2) NULL, 
	[Inter Company Output Tax Code] varchar(2) NULL, 
	[Inter Company Currency Description] varchar(15) NULL, 
	[Inter Company Chart Of Accounts Description] varchar(50) NULL, 
	[Inter Company Country Description] varchar(15) NULL, 
	[Inter Company Fiscal Year Variant Description] varchar(30) NULL, 
	[Inter Company Credit Control Area Description] varchar(35) NULL
);