CREATE TABLE [Propelis].[INTER_COMP_PROFIT_CNTR] (

	[PROFT_CNTR_KEY] int NOT NULL, 
	[Inter Comp Profit Center ID] varchar(max) NULL, 
	[Inter Comp Profit Center Tax Jurisdiction] varchar(max) NULL, 
	[Inter Comp Profit Center Valid To Date] date NULL, 
	[Inter Comp Profit Center Valid From Date] date NULL, 
	[Inter Comp Profit Center Area] varchar(max) NULL, 
	[Inter Comp Profit Center Generic Mastdf Record Status] varchar(max) NULL, 
	[Inter Comp Profit Center Status Description] varchar(max) NULL, 
	[Inter Comp Profit Center Controlling Area Description] varchar(max) NULL, 
	[Inter Comp Profit Center Country Description] varchar(max) NULL, 
	[Inter Comp Profit Center Company Description] varchar(max) NULL, 
	[ETL_UPDTD_TS] varchar(max) NULL, 
	[Inter Comp Profit Center Company Code] varchar(max) NULL, 
	[Inter Comp Profit Center Long Description] varchar(max) NULL, 
	[Inter Comp Profit Center Short Description] varchar(max) NULL, 
	[Inter Comp Profit Center Lock Indicator] varchar(max) NULL, 
	[Inter Comp Profit Center Name 1] varchar(max) NULL, 
	[Inter Comp Profit Center Updated User ID] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] varchar(max) NULL, 
	[Inter Comp Profit Center Postal Code] varchar(max) NULL, 
	[Inter Comp Profit Center Country Code] varchar(max) NULL, 
	[Inter Comp Profit Center Region Code] varchar(max) NULL, 
	[Inter Comp Profit Center Created Date] date NULL, 
	[Inter Comp Profit Center Created User ID] varchar(max) NULL, 
	[Inter Comp Profit Center Updated Date] date NULL, 
	[Inter Comp Profit Center Language Type Code] varchar(max) NULL, 
	[Inter Comp Profit Center Segment ID] varchar(max) NULL, 
	[Inter Comp Profit Center Address Line 1] varchar(max) NULL, 
	[Inter Comp Profit Center Address Line 2] varchar(max) NULL, 
	[Inter Comp Profit Center City Name] varchar(max) NULL, 
	[Inter Comp Profit Center Distrtict Name] varchar(max) NULL, 
	[Inter Comp Profit Center Description] varchar(max) NULL, 
	[Legacy Profit Center Code] varchar(max) NULL, 
	[Legacy Profit Center Description] varchar(max) NULL, 
	[Inter Comp Profit Center Controlling Area ID] varchar(max) NULL, 
	[Inter Comp Profit Center User Responsible ID] varchar(max) NULL, 
	[Inter Comp Profit Center Person Responsible] varchar(max) NULL
);