CREATE TABLE [Propelis].[Investigation_Start_Date] (

	[DATE_KEY] int NOT NULL, 
	[Investigation Start Date] date NULL, 
	[Investigation Start Fiscal Year] int NULL, 
	[Investigation Start Fiscal Period Number] int NULL, 
	[Investigation Start Fiscal Period Code] varchar(255) NULL, 
	[Investigation Start Fiscal Quarter Number] int NULL, 
	[Investigation Start Fiscal Quarter Code] varchar(255) NULL, 
	[Investigation Start Calendar Year] int NULL, 
	[Investigation Start Calendar Month Number] int NULL, 
	[Investigation Start Calendar Month Code] varchar(255) NULL, 
	[Investigation Start Calendar Month Description] varchar(255) NULL, 
	[Investigation Start Calendar Quarter Number] int NULL, 
	[Investigation Start Calendar Quarter Code] varchar(255) NULL, 
	[Investigation Start Calendar Weekday Number] int NULL, 
	[Investigation Start Calendar Weekday Name] varchar(255) NULL, 
	[Investigation Start Calendar Day In Month] int NULL, 
	[Investigation Start Calendar Day In Year] int NULL, 
	[Investigation Start Calendar Week] int NULL, 
	[Investigation Start Calendar Month In Quarter Number] int NULL, 
	[Investigation Start Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(255) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Investigation Start Current Day Flag] bit NULL, 
	[Investigation Start Current Day Minus 1 Flag] bit NULL, 
	[Investigation Start Current Calendar Week Flag] bit NULL, 
	[Investigation Start Current Calendar Week Minus 1 Flag] bit NULL, 
	[Investigation Start Current Month Flag] bit NULL, 
	[Investigation Start Current Month Minus 1 Flag] bit NULL, 
	[Investigation Start Current Month Minus 12 Flag] bit NULL, 
	[Investigation Start Current Quarter Flag] bit NULL, 
	[Investigation Start Current Quarter Minus 1 Flag] bit NULL, 
	[Investigation Start Current Quarter Minus 4 Flag] bit NULL, 
	[Investigation Start Current Calendar Year Flag] bit NULL, 
	[Investigation Start Current Calendar Year Minus 1 Flag] bit NULL, 
	[Investigation Start Current Calendar Year Minus 2 Flag] bit NULL, 
	[Investigation Start Current Fiscal Year Flag] bit NULL, 
	[Investigation Start Current Fiscal Year Minus 1 Flag] bit NULL, 
	[Investigation Start Current Fiscal Year Minus 2 Flag] bit NULL, 
	[Investigation Start Current Calendar Year Plus 1 Flag] bit NULL, 
	[Investigation Start Current Fiscal Year Plus 1 Flag] bit NULL, 
	[Investigation Start Day In Fiscal Year] int NULL, 
	[Investigation Start Is Weekday] int NULL, 
	[Investigation Start Fiscal Week] int NULL, 
	[Investigation Start Current Fiscal Week Flag] bit NULL, 
	[Investigation Start Current Fiscal Week Minus 1 Flag] bit NULL, 
	[Investigation Start Fiscal Weekday Number] int NULL, 
	[Investigation Start Fiscal Weekday Name] varchar(255) NULL, 
	[Investigation Start Current Month Minus 2 Flag] bit NULL, 
	[Investigation Start Current Fiscal Week Minus 2 Flag] bit NULL, 
	[Investigation Start Current Fiscal Week Minus 6 Flag] bit NULL, 
	[Investigation Start Current Fiscal Week Minus 3 Flag] bit NULL, 
	[Investigation Start Current Fiscal Week Minus 4 Flag] bit NULL, 
	[Investigation Start Current Fiscal Week Minus 5 Flag] bit NULL, 
	[Investigation Start Current Fiscal Week Minus 7 Flag] bit NULL
);