CREATE TABLE [Propelis].[INVOICE_CREATION_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Invoice Creation Date] date NULL, 
	[Invoice Creation Fiscal Year] int NULL, 
	[Invoice Creation Fiscal Period] int NULL, 
	[Invoice Creation Fiscal Period Code] varchar(max) NULL, 
	[Invoice Creation Fiscal Quarter] int NULL, 
	[Invoice Creation Fiscal Quarter Code] varchar(max) NULL, 
	[Invoice Creation Calendar Year] int NULL, 
	[Invoice Creation Calendar Month Number] int NULL, 
	[Invoice Creation Calendar Month Code] varchar(max) NULL, 
	[Invoice Creation Calendar Month Desc] varchar(max) NULL, 
	[Invoice Creation Calendar Quarter] int NULL, 
	[Invoice Creation Calendar Quarter Code] varchar(max) NULL, 
	[Invoice Creation Calendar Weekday Number] int NULL, 
	[Invoice Creation Calendar Weekday Name] varchar(max) NULL, 
	[Invoice Creation Calendar Day in Month] int NULL, 
	[Invoice Creation Calendar Day in Year] int NULL, 
	[Invoice Creation Calendar Week] int NULL, 
	[Invoice Creation Calendar Month in Quarter Number] int NULL, 
	[Invoice Creation Calendar Days in Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Invoice Creation Current Day Flag] int NULL, 
	[Invoice Creation Current Day Minus 1 Flag] int NULL, 
	[Invoice Creation Current Calendar Week Flag] int NULL, 
	[Invoice Creation Current Calendar Week Minus 1 Flag] int NULL, 
	[Invoice Creation Current Month Flag] int NULL, 
	[Invoice Creation Current Month Minus 1 Flag] int NULL, 
	[Invoice Creation Current Month Minus 12 Flag] int NULL, 
	[Invoice Creation Current Quarter Flag] int NULL, 
	[Invoice Creation Current Quarter Minus 1 Flag] int NULL, 
	[Invoice Creation Current Quarter Minus 4 Flag] int NULL, 
	[Invoice Creation Current Calendar Year Flag] int NULL, 
	[Invoice Creation Current Calendar Year Minus 1 Flag] int NULL, 
	[Invoice Creation Current Calendar Year Minus 2 Flag] int NULL, 
	[Invoice Creation Current Fiscal Year Flag] int NULL, 
	[Invoice Creation Current Fiscal Year Minus 1 Flag] int NULL, 
	[Invoice Creation Current Fiscal Year Minus 2 Flag] int NULL, 
	[Invoice Creation Current Calendar Year Plus 1 Flag] int NULL, 
	[Invoice Creation Current Fiscal Year Plus 1 Flag] int NULL, 
	[Invoice Creation Day In Fiscal Year] int NULL, 
	[IS_WEEKDAY] int NULL, 
	[Invoice Creation Fiscal Week] int NULL, 
	[Invoice Creation Current Fiscal Week Flag] int NULL, 
	[Invoice Creation Current Fiscal Week Minus 1 Flag] int NULL, 
	[Invoice Creation Fiscal Weekday Number] int NULL, 
	[Invoice Creation Fiscal Weekday Name] varchar(max) NULL, 
	[CURR_MNTH_MINUS_2_FLG] int NULL, 
	[Invoice Creation Current Fiscal Week Minus 2 Flag] int NULL, 
	[Invoice Creation Current Fiscal Week Minus 6 Flag] int NULL, 
	[Invoice Creation Current Fiscal Week Minus 3 Flag] int NULL, 
	[Invoice Creation Current Fiscal Week Minus 4 Flag] int NULL, 
	[Invoice Creation Current Fiscal Week Minus 5 Flag] int NULL, 
	[Invoice Creation Current Fiscal Week Minus 7 Flag] int NULL
);