CREATE TABLE [Propelis].[INVOICE] (

	[INVC_KEY] int NOT NULL, 
	[Sales Order Invoice ID] varchar(max) NULL, 
	[Invoice Company Code] varchar(max) NULL, 
	[Invoice Billing Type Code] varchar(max) NULL, 
	[Invoice Billing Category] varchar(max) NULL, 
	[Invoice SD Document Category] varchar(max) NULL, 
	[Invoice Sales Organization] varchar(max) NULL, 
	[Invoice Distribution Channel] varchar(max) NULL, 
	[Invoice Divison] varchar(max) NULL, 
	[Invoice Invoice Pricing Procedure in Pricing] varchar(max) NULL, 
	[Invoice Document Condition Number] varchar(max) NULL, 
	[Invoice Shipping Condition] varchar(max) NULL, 
	[Invoice Price Group] varchar(max) NULL, 
	[Invoice Customer Group] varchar(max) NULL, 
	[Invoice Price List] varchar(max) NULL, 
	[Invoice Payment Reference] varchar(max) NULL, 
	[Invoice Payment Terms] varchar(max) NULL, 
	[Invoice Incoterms] varchar(max) NULL, 
	[Invoice Incoterms 2] varchar(max) NULL, 
	[Invoice Exchange Rate] decimal(9,5) NULL, 
	[Invoice Net Value] decimal(15,3) NULL, 
	[Invoice Statistical Currency] varchar(max) NULL, 
	[Invoice List Type] varchar(max) NULL, 
	[Invoice Reference] varchar(max) NULL, 
	[Invoice Invoice Date] date NULL, 
	[Invoice Created Date] date NULL, 
	[Invoice Created User ID] varchar(max) NULL, 
	[Invoice Updated Date] date NULL, 
	[Invoice Updated User ID] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Invoice Billing Document Cancelled Indicator] varchar(max) NULL, 
	[Invoice Creation Date] date NULL, 
	[Invoice Changed On Date] date NULL, 
	[Invoice Customer Purchase Order Number] varchar(max) NULL, 
	[Invoice Accounting Transfer Status] varchar(max) NULL, 
	[Invoice Currency Key of Credit Control Area] varchar(max) NULL, 
	[Invoice Accounting Document Number] varchar(max) NULL, 
	[Invoice SD Document Currency] varchar(max) NULL, 
	[Invoice Company Description] varchar(max) NULL, 
	[Invoice Billing Type Description] varchar(max) NULL, 
	[Invoice Billing Category Description] varchar(max) NULL, 
	[Invoice SD Document Category Description] varchar(max) NULL, 
	[Invoice Sales Organization Description] varchar(max) NULL, 
	[Invoice Distribution Channel Description] varchar(max) NULL, 
	[Invoice Division Description] varchar(max) NULL, 
	[Invoice Shipping Condition Description] varchar(max) NULL, 
	[Invoice Price Group Description] varchar(max) NULL, 
	[Invoice Customer Group Description] varchar(max) NULL, 
	[Invoice Price List Description] varchar(max) NULL, 
	[Invoice Payment Terms Description] varchar(max) NULL, 
	[Invoice Incoterms Description] varchar(max) NULL, 
	[Invoice Statistical Currency Description] varchar(max) NULL, 
	[Invoice List Type Description] varchar(max) NULL, 
	[Invoice Accounting Transfer Status Description] varchar(max) NULL, 
	[Invoice SD Document Currency Description] varchar(max) NULL, 
	[Invoice Cancelled Document Number] varchar(max) NULL, 
	[Invoice Terms Discount Percentage] varchar(max) NULL, 
	[Invoice Customer Group 6] varchar(max) NULL, 
	[Invoice Customer Group 7] varchar(max) NULL, 
	[Invoice Customer Group 8] varchar(max) NULL, 
	[Invoice Customer Group 9] varchar(max) NULL, 
	[Invoice Customer Group 10] varchar(max) NULL, 
	[Invoice Customer Group 6 Description] varchar(max) NULL, 
	[Invoice Customer Group 7 Description] varchar(max) NULL, 
	[Invoice Customer Group 8 Description] varchar(max) NULL, 
	[Invoice Customer Group 9 Description] varchar(max) NULL, 
	[Invoice Customer Group 10 Description] varchar(max) NULL
);