CREATE TABLE [Propelis].[INVOICE_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Invoice Posting Date] date NULL, 
	[Invoice Posting Fiscal Year] int NULL, 
	[Invoice Posting Fiscal Period] int NULL, 
	[Invoice Posting Fiscal Period Code] varchar(max) NULL, 
	[Invoice Posting Fiscal Quarter] int NULL, 
	[Invoice Posting Fiscal Quarter Code] varchar(max) NULL, 
	[Invoice Posting Calendar Year] int NULL, 
	[Invoice Posting Calendar Month Number] int NULL, 
	[Invoice Posting Calendar Month Code] varchar(max) NULL, 
	[Invoice Posting Calendar Month Desc] varchar(max) NULL, 
	[Invoice Posting Calendar Quarter] int NULL, 
	[Invoice Posting Calendar Quarter Code] varchar(max) NULL, 
	[Invoice Posting Calendar Weekday Number] int NULL, 
	[Invoice Posting Calendar Weekday Name] varchar(max) NULL, 
	[Invoice Posting Calendar Day] int NULL, 
	[Invoice Posting Calendar Day in Year] int NULL, 
	[Invoice Posting Calendar Week] int NULL, 
	[Invoice Posting Calendar Month in Quarter Number] int NULL, 
	[Invoice Posting Calendar Days in Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Invoice Posting Current Day Flag] int NULL, 
	[Invoice Posting Current Day Minus 1 Flag] int NULL, 
	[Invoice Posting Current Calendar Week Flag] int NULL, 
	[Invoice Posting Current Calendar Week Minus 1 Flag] int NULL, 
	[Invoice Posting Current Month Flag] int NULL, 
	[Invoice Posting Current Month Minus 1 Flag] int NULL, 
	[Invoice Posting Current Month Minus 12 Flag] int NULL, 
	[Invoice Posting Current Quarter Flag] int NULL, 
	[Invoice Posting Current Quarter Minus 1 Flag] int NULL, 
	[Invoice Posting Current Quarter Minus 4 Flag] int NULL, 
	[Invoice Posting Current Calendar Year Flag] int NULL, 
	[Invoice Posting Current Calendar Year Minus 1 Flag] int NULL, 
	[Invoice Posting Current Calendar Year Minus 2 Flag] int NULL, 
	[Invoice Posting Current Fiscal Year Flag] int NULL, 
	[Invoice Posting Current Fiscal Year Minus 1 Flag] int NULL, 
	[Invoice Posting Current Fiscal Year Minus 2 Flag] int NULL, 
	[Invoice Posting Current Calendar Year Plus 1 Flag] int NULL, 
	[Invoice Posting Current Fiscal Year Plus 1 Flag] int NULL, 
	[Invoice Posting Day In Fiscal Year] int NULL, 
	[Invoice Posting Date Is Weekday] int NULL, 
	[Invoice Posting Fiscal Week] int NULL, 
	[Invoice Posting Current Fiscal Week Flag] int NULL, 
	[Invoice Posting Current Fiscal Week Minus 1 Flag] int NULL, 
	[Invoice Posting Fiscal Weekday Number] int NULL, 
	[Invoice Posting Fiscal Weekday Name] varchar(max) NULL, 
	[Invoice Posting Current Month Minus 2 Flag] int NULL, 
	[Invoice Posting Current Fiscal Week Minus 2 Flag] int NULL, 
	[Invoice Posting Current Fiscal Week Minus 6 Flag] int NULL, 
	[Invoice Posting Current Fiscal Week Minus 3 Flag] int NULL, 
	[Invoice Posting Current Fiscal Week Minus 4 Flag] int NULL, 
	[Invoice Posting Current Fiscal Week Minus 5 Flag] int NULL, 
	[Invoice Posting Current Fiscal Week Minus 7 Flag] int NULL
);