CREATE TABLE [Propelis].[LAST_DUNNING_NOTICE_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Last Dunning Notice Date] date NULL, 
	[Last Dunning Notice Fiscal Year] int NULL, 
	[Last Dunning Notice Fiscal Period Number] int NULL, 
	[Last Dunning Notice Fiscal Period Code] varchar(max) NULL, 
	[Last Dunning Notice Fiscal Quarter Number] int NULL, 
	[Last Dunning Notice Current Fiscal Week Minus 7 Flag] int NULL, 
	[Last Dunning Notice Current Month Minus 2 Flag] int NULL, 
	[Last Dunning Notice Current Fiscal Week Minus 2 Flag] int NULL, 
	[Last Dunning Notice Current Fiscal Week Minus 6 Flag] int NULL, 
	[Last Dunning Notice Current Fiscal Week Minus 3 Flag] int NULL, 
	[Last Dunning Notice Current Fiscal Week Minus 4 Flag] int NULL, 
	[Last Dunning Notice Current Fiscal Week Minus 5 Flag] int NULL, 
	[Last Dunning Notice Date Is Weekday] int NULL, 
	[Last Dunning Notice Fiscal Week] int NULL, 
	[Last Dunning Notice Current Fiscal Week Flag] int NULL, 
	[Last Dunning Notice Current Fiscal Week Minus 1 Flag] int NULL, 
	[Last Dunning Notice Fiscal Weekday Number] int NULL, 
	[Last Dunning Notice Fiscal Weekday Name] varchar(max) NULL, 
	[Last Dunning Notice Current Fiscal Year Flag] int NULL, 
	[Last Dunning Notice Current Fiscal Year Minus 1 Flag] int NULL, 
	[Last Dunning Notice Current Fiscal Year Minus 2 Flag] int NULL, 
	[Last Dunning Notice Current Calendar Year Plus 1 Flag] int NULL, 
	[Last Dunning Notice Current Fiscal Year Plus 1 Flag] int NULL, 
	[Last Dunning Notice Day In Fiscal Year] int NULL, 
	[Last Dunning Notice Current Quarter Flag] int NULL, 
	[Last Dunning Notice Current Quarter Minus 1 Flag] int NULL, 
	[Last Dunning Notice Current Quarter Minus 4 Flag] int NULL, 
	[Last Dunning Notice Current Calendar Year Flag] int NULL, 
	[Last Dunning Notice Current Calendar Year Minus 1 Flag] int NULL, 
	[Last Dunning Notice Current Calendar Year Minus 2 Flag] int NULL, 
	[Last Dunning Notice Current Day Minus 1 Flag] int NULL, 
	[Last Dunning Notice Current Calendar Week Flag] int NULL, 
	[Last Dunning Notice Current Calendar Week Minus 1 Flag] int NULL, 
	[Last Dunning Notice Current Month Flag] int NULL, 
	[Last Dunning Notice Current Month Minus 1 Flag] int NULL, 
	[Last Dunning Notice Current Month Minus 12 Flag] int NULL, 
	[Last Dunning Notice Calendar Month In Quarter Number] int NULL, 
	[Last Dunning Notice Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Last Dunning Notice Current Day Flag] int NULL, 
	[Last Dunning Notice Calendar Quarter Code] varchar(max) NULL, 
	[Last Dunning Notice Calendar Weekday Number] int NULL, 
	[Last Dunning Notice Calendar Weekday Name] varchar(max) NULL, 
	[Last Dunning Notice Calendar Day In Month] int NULL, 
	[Last Dunning Notice Calendar Day In Year] int NULL, 
	[Last Dunning Notice Calendar Week] int NULL, 
	[Last Dunning Notice Fiscal Quarter Code] varchar(max) NULL, 
	[Last Dunning Notice Calendar Year] int NULL, 
	[Last Dunning Notice Calendar Month Number] int NULL, 
	[Last Dunning Notice Calendar Month Code] varchar(max) NULL, 
	[Last Dunning Notice Calendar Month Description] varchar(max) NULL, 
	[Last Dunning Notice Calendar Quarter Number] int NULL
);