CREATE TABLE [Propelis].[LATEST_SCHLD_FINISH_EXEC_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Latest Schld Finish Exec Date] date NULL, 
	[Latest Schld Finish Exec Fiscal Year] int NULL, 
	[Latest Schld Finish Exec Fiscal Period Number] int NULL, 
	[Latest Schld Finish Exec Fiscal Period Code] varchar(max) NULL, 
	[Latest Schld Finish Exec Fiscal Quarter Number] int NULL, 
	[Latest Schld Finish Exec Fiscal Quarter Code] varchar(max) NULL, 
	[Latest Schld Finish Exec Calendar Year] int NULL, 
	[Latest Schld Finish Exec Calendar Month Number] int NULL, 
	[Latest Schld Finish Exec Calendar Month Code] varchar(max) NULL, 
	[Latest Schld Finish Exec Calendar Month Description] varchar(max) NULL, 
	[Latest Schld Finish Exec Calendar Quarter Number] int NULL, 
	[Latest Schld Finish Exec Calendar Quarter Code] varchar(max) NULL, 
	[Latest Schld Finish Exec Calendar Weekday Number] int NULL, 
	[Latest Schld Finish Exec Calendar Weekday Name] varchar(max) NULL, 
	[Latest Schld Finish Exec Calendar Day In Month] int NULL, 
	[Latest Schld Finish Exec Calendar Day In Year] int NULL, 
	[Latest Schld Finish Exec Calendar Week] int NULL, 
	[Latest Schld Finish Exec Calendar Month In Quarter Number] int NULL, 
	[Latest Schld Finish Exec Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Latest Schld Finish Exec Current Day Flag] int NULL, 
	[Latest Schld Finish Exec Current Day Minus 1 Flag] int NULL, 
	[Latest Schld Finish Exec Current Calendar Week Flag] int NULL, 
	[Latest Schld Finish Exec Current Calendar Week Minus 1 Flag] int NULL, 
	[Latest Schld Finish Exec Current Month Flag] int NULL, 
	[Latest Schld Finish Exec Current Month Minus 1 Flag] int NULL, 
	[Latest Schld Finish Exec Current Month Minus 12 Flag] int NULL, 
	[Latest Schld Finish Exec Current Quarter Flag] int NULL, 
	[Latest Schld Finish Exec Current Quarter Minus 1 Flag] int NULL, 
	[Latest Schld Finish Exec Current Quarter Minus 4 Flag] int NULL, 
	[Latest Schld Finish Exec Current Calendar Year Flag] int NULL, 
	[Latest Schld Finish Exec Current Calendar Year Minus 1 Flag] int NULL, 
	[Latest Schld Finish Exec Current Calendar Year Minus 2 Flag] int NULL, 
	[Latest Schld Finish Exec Current Fiscal Year Flag] int NULL, 
	[Latest Schld Finish Exec Current Fiscal Year Minus 1 Flag] int NULL, 
	[Latest Schld Finish Exec Current Fiscal Year Minus 2 Flag] int NULL, 
	[Latest Schld Finish Exec Current Calendar Year Plus 1 Flag] int NULL, 
	[Latest Schld Finish Exec Current Calendar Year Plus 2 Flag] int NULL, 
	[Latest Schld Finish Exec Day In Fiscal Year] int NULL, 
	[Latest Schld Finish Exec Date Is Weekday] int NULL, 
	[Latest Schld Finish Exec Fiscal Week] int NULL, 
	[Latest Schld Finish Exec Current Fiscal Week Flag] int NULL, 
	[Latest Schld Finish Exec Current Fiscal Week Minus 1 Flag] int NULL, 
	[Latest Schld Finish Exec Fiscal Weekday Number] int NULL, 
	[Latest Schld Finish Exec Fiscal Weekday Name] varchar(max) NULL, 
	[Latest Schld Finish Exec Current Month Minus 2 Flag] int NULL, 
	[Latest Schld Finish Exec Current Fiscal Week Minus 2 Flag] int NULL, 
	[Latest Schld Finish Exec Current Fiscal Week Minus 6 Flag] int NULL, 
	[Latest Schld Finish Exec Current Fiscal Week Minus 3 Flag] int NULL, 
	[Latest Schld Finish Exec Current Fiscal Week Minus 4 Flag] int NULL, 
	[Latest Schld Finish Exec Current Fiscal Week Minus 5 Flag] int NULL, 
	[Latest Schld Finish Exec Current Fiscal Week Minus 7 Flag] int NULL
);