CREATE TABLE [Propelis].[LOADING_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Loading Date] date NULL, 
	[Loading Fiscal Year] int NULL, 
	[Loading Fiscal Period] int NULL, 
	[Loading Fiscal Period Code] varchar(max) NULL, 
	[Loading Fiscal Quarter] int NULL, 
	[Loading Fiscal Quarter Code] varchar(max) NULL, 
	[Loading Calendar Year] int NULL, 
	[Loading Calendar Month Number] int NULL, 
	[Loading Calendar Month Code] varchar(max) NULL, 
	[Loading Calendar Month Desc] varchar(max) NULL, 
	[Loading Calendar Quarter] int NULL, 
	[Loading Calendar Quarter Code] varchar(max) NULL, 
	[Loading Calendar Weekday Number] int NULL, 
	[Loading Calendar Weekday Name] varchar(max) NULL, 
	[Loading Calendar Day in Month] int NULL, 
	[Loading Calendar Day in Year] int NULL, 
	[Loading Calendar Week] int NULL, 
	[Loading Calendar Month in Quarter Number] int NULL, 
	[Loading Calendar Days in Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Loading Current Day Flag] int NULL, 
	[Loading Current Day Minus 1 Flag] int NULL, 
	[Loading Current Calendar Week Flag] int NULL, 
	[Loading Current Calendar Week Minus 1 Flag] int NULL, 
	[Loading Current Month Flag] int NULL, 
	[Loading Current Month Minus 1 Flag] int NULL, 
	[Loading Current Month Minus 12 Flag] int NULL, 
	[Loading Current Quarter Flag] int NULL, 
	[Loading Current Quarter Minus 1 Flag] int NULL, 
	[Loading Current Quarter Minus 4 Flag] int NULL, 
	[Loading Current Calendar Year Flag] int NULL, 
	[Loading Current Calendar Year Minus 1 Flag] int NULL, 
	[Loading Current Calendar Year Minus 2 Flag] int NULL, 
	[Loading Current Fiscal Year Flag] int NULL, 
	[Loading Current Fiscal Year Minus 1 Flag] int NULL, 
	[Loading Current Fiscal Year Minus 2 Flag] int NULL, 
	[Loading Current Calendar Year Plus 1 Flag] int NULL, 
	[Loading Current Fiscal Year Plus 1 Flag] int NULL, 
	[Loading Day In Fiscal Year] int NULL, 
	[Loading Date Is Weekday] int NULL, 
	[Loading Day Fiscal Week] int NULL, 
	[Loading Current Fiscal Week Flag] int NULL, 
	[Loading Current Fiscal Week Minus 1 Flag] int NULL, 
	[Loading Day Fiscal Weekday Number] int NULL, 
	[Loading Day Fiscal Weekday Name] varchar(max) NULL, 
	[Loading Current Month Minus 2 Flag] int NULL, 
	[Loading Current Fiscal Week Minus 2 Flag] int NULL, 
	[Loading Current Fiscal Week Minus 6 Flag] int NULL, 
	[Loading Current Fiscal Week Minus 3 Flag] int NULL, 
	[Loading Current Fiscal Week Minus 4 Flag] int NULL, 
	[Loading Current Fiscal Week Minus 5 Flag] int NULL, 
	[Loading Current Fiscal Week Minus 7 Flag] int NULL
);