CREATE TABLE [Propelis].[LOCATION_PLANT] (

	[PLNT_KEY] int NOT NULL, 
	[Location Plant ID] varchar(max) NULL, 
	[Location Legacy Plant ID] varchar(max) NULL, 
	[Location Plant Name] varchar(max) NULL, 
	[Location Plant Company Code] varchar(max) NULL, 
	[Location Plant Sales Organization] varchar(max) NULL, 
	[Location Plant Purchasing Organization] varchar(max) NULL, 
	[Location Plant Valuation Area] varchar(max) NULL, 
	[Location Plant Customer Number] varchar(max) NULL, 
	[Location Plant Vendor Number] varchar(max) NULL, 
	[Location Plant Factory Calendar Key] varchar(max) NULL, 
	[Location Plant Line 1 Description] varchar(max) NULL, 
	[Location Plant Line 2 Description] varchar(max) NULL, 
	[Location Plant City Name] varchar(max) NULL, 
	[Location Plant Zip Code] varchar(max) NULL, 
	[Location Plant Country Code] varchar(max) NULL, 
	[Location Plant Country Name] varchar(max) NULL, 
	[Location Plant Tax Jurisdiction] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Location Plant Is P001] varchar(max) NULL, 
	[Location Plant Is P002] varchar(max) NULL, 
	[Location Plant Company Description] varchar(max) NULL, 
	[Location Plant Sales Organization Description] varchar(max) NULL, 
	[Location Plant Factory Calendar Description] varchar(max) NULL, 
	[Location Plant Purchasing Organization Description] varchar(max) NULL, 
	[Location Plant Tax Indicator] varchar(max) NULL, 
	[Location Plant Tax Indicator Description] varchar(max) NULL, 
	[Location Plant Shipping/Receiving Point] varchar(max) NULL, 
	[Location Plant Shipping/Receiving Point Description] varchar(max) NULL
);