CREATE TABLE [Propelis].[MAINTENANCE_PLANT] (

	[PLNT_KEY] int NOT NULL, 
	[Maintenance Plant ID] varchar(max) NULL, 
	[Maintenance Plant Legacy Plant ID] varchar(max) NULL, 
	[Maintenance Plant Name] varchar(max) NULL, 
	[Maintenance Plant Company Code] varchar(max) NULL, 
	[Maintenance Plant Sales Organization] varchar(max) NULL, 
	[Maintenance Plant Purcahsing Organization] varchar(max) NULL, 
	[Maintenance Plant Valuation Area] varchar(max) NULL, 
	[Maintenance Plant Customer Numer of Plant] varchar(max) NULL, 
	[Maintenance Plant Vendor Number of Plant] varchar(max) NULL, 
	[Maintenance Plant Factory Calendar Key] varchar(max) NULL, 
	[Maintenance Plant Line 1 Description] varchar(max) NULL, 
	[Maintenance Plant Line 2 Description] varchar(max) NULL, 
	[Maintenance Plant City Name] varchar(max) NULL, 
	[Maintenance Plant Zip Code] varchar(max) NULL, 
	[Maintenance Plant Country Code] varchar(max) NULL, 
	[Maintenance Plant Country Name] varchar(max) NULL, 
	[Maintenance Plant Tax Jurisdiction] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Maintenance Plant Is P001] varchar(max) NULL, 
	[Maintenance Plant Is P002] varchar(max) NULL, 
	[Maintenance Plant Company Description] varchar(max) NULL, 
	[Maintenance Plant Sales Organization Description] varchar(max) NULL, 
	[Maintenance Plant Factory Calendar Description] varchar(max) NULL, 
	[Maintenance Plant Purchasing Organization Description] varchar(max) NULL, 
	[Maintenance Plant Tax Indicator] varchar(max) NULL, 
	[Maintenance Plant Tax Indicator Description] varchar(max) NULL, 
	[Maintenance Plant Shipping/Receiving Point] varchar(max) NULL, 
	[Maintenance Plant Shipping/Receiving Point Description] varchar(max) NULL
);