CREATE TABLE [Propelis].[MATRL_AVAILABILITY_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Matrl Avail Date] date NULL, 
	[Matrl Avail Fiscal Year] int NULL, 
	[Matrl Avail Fiscal Period] int NULL, 
	[Matrl Avail Fiscal Period Code] varchar(max) NULL, 
	[Matrl Avail Fiscal Quarter Number] int NULL, 
	[Matrl Avail Fiscal Quarter Code] varchar(max) NULL, 
	[Matrl Avail Calendar Year] int NULL, 
	[Matrl Avail Calendar Month Number] int NULL, 
	[Matrl Avail Calendar Month Code] varchar(max) NULL, 
	[Matrl Avail Calendar Month Desc] varchar(max) NULL, 
	[Matrl Avail Calendar Quarter] int NULL, 
	[Matrl Avail Calendar Quarter Code] varchar(max) NULL, 
	[Matrl Avail Calendar Weekday Number] int NULL, 
	[Matrl Avail Calendar Weekday Name] varchar(max) NULL, 
	[Matrl Avail Calendar Day in Month] int NULL, 
	[Matrl Avail Calendar Day in Year] int NULL, 
	[Matrl Avail Calendar Week] int NULL, 
	[Matrl Avail Calendar Month in Quarter Number] int NULL, 
	[Matrl Avail Calendar Days in Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Matrl Avail Current Day Flag] int NULL, 
	[Matrl Avail Current Day Minus 1 Flag] int NULL, 
	[Matrl Avail Current Calendar Week Flag] int NULL, 
	[Matrl Avail Current Calendar Week Minus 1 Flag] int NULL, 
	[Matrl Avail Current Month Flag] int NULL, 
	[Matrl Avail Current Month Minus 1 Flag] int NULL, 
	[Matrl Avail Current Month Minus 12 Flag] int NULL, 
	[Matrl Avail Current Quarter Flag] int NULL, 
	[Matrl Avail Current Quarter Minus 1 Flag] int NULL, 
	[Matrl Avail Current Quarter Minus 4 Flag] int NULL, 
	[Matrl Avail Current Calendar Year Flag] int NULL, 
	[Matrl Avail Current Calendar Year Minus 1 Flag] int NULL, 
	[Matrl Avail Current Calendar Year Minus 2 Flag] int NULL, 
	[Matrl Avail Current Fiscal Year Flag] int NULL, 
	[Matrl Avail Current Fiscal Year Minus 1 Flag] int NULL, 
	[Matrl Avail Current Fiscal Year Minus 2 Flag] int NULL, 
	[Matrl Avail Current Calendar Year Plus 1 Flag] int NULL, 
	[Matrl Avail Current Fiscal Year Plus 1 Flag] int NULL, 
	[Matrl Avail Day In Fiscal Year] int NULL, 
	[Matrl Avail Date Is Weekday] int NULL, 
	[Matrl Avail Fiscal Week] int NULL, 
	[Matrl Avail Current Fiscal Week Flag] int NULL, 
	[Matrl Avail Current Fiscal Week Minus 1 Flag] int NULL, 
	[Matrl Avail Fiscal Weekday Number] int NULL, 
	[Matrl Avail Fiscal Weekday Name] varchar(max) NULL, 
	[Matrl Avail Current Month Minus 2 Flag] int NULL, 
	[Matrl Avail Current Fiscal Week Minus 2 Flag] int NULL, 
	[Matrl Avail Current Fiscal Week Minus 6 Flag] int NULL, 
	[Matrl Avail Current Fiscal Week Minus 3 Flag] int NULL, 
	[Matrl Avail Current Fiscal Week Minus 4 Flag] int NULL, 
	[Matrl Avail Current Fiscal Week Minus 5 Flag] int NULL, 
	[Matrl Avail Current Fiscal Week Minus 7 Flag] int NULL
);