CREATE TABLE [Propelis].[OPERATION_LEVEL_WORK_CENTER] (

	[WRK_CNTR_KEY] int NOT NULL, 
	[Operation Work Center ID] varchar(8) NULL, 
	[Operation Work Center Plant ID] varchar(4) NULL, 
	[Operation Work Center Object ID] int NULL, 
	[Operation Work Center Object Type] varchar(2) NULL, 
	[Operation Work Center Category] varchar(4) NULL, 
	[Operation Work Center Location] varchar(10) NULL, 
	[Operation Work Center Person Responsible] varchar(3) NULL, 
	[Operation Work Center Standard Value Key] varchar(4) NULL, 
	[Operation Work Center Usage Code] varchar(3) NULL, 
	[Operation Work Center Capacity ID] int NULL, 
	[Operation Work Center Supply Area] varchar(10) NULL, 
	[Operation Work Center Deletion Flag] varchar(1) NULL, 
	[Operation Work Center Locked Status] varchar(1) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Operation Work Center Description] varchar(40) NULL, 
	[Operation Work Center Category Description] varchar(20) NULL, 
	[Operation Work Center Person Responsible Name] varchar(40) NULL, 
	[Operation Work Center Control Key] varchar(4) NULL, 
	[Operation Work Center Storage Location Storage Resource] varchar(4) NULL, 
	[Operation Work Center User Name Term] varchar(12) NULL, 
	[Operation Work Center User Name GRND] varchar(12) NULL, 
	[Operation Work Center Changed On Date Term] date NULL, 
	[Operation Work Center Changed On Date GRND] date NULL, 
	[Operation Work Center Plant Description] varchar(30) NULL, 
	[Operation Work Center Object Type Description] varchar(60) NULL, 
	[Operation Work Center Location Description] varchar(40) NULL, 
	[Operation Work Center Standard Value Description] varchar(30) NULL, 
	[Operation Work Center Usage Description] varchar(30) NULL, 
	[Operation Work Center Supply Area Description] varchar(40) NULL, 
	[Operation Work Center Control Description] varchar(40) NULL, 
	[Operation Work Center Storage Location Description] varchar(40) NULL, 
	[Operation Work Center Changed On Date] date NULL
);