CREATE TABLE [Propelis].[OPERATING_PLANT] (

	[PLNT_KEY] int NOT NULL, 
	[Operating Plant ID] varchar(max) NULL, 
	[Legacy Operating Plant ID] varchar(max) NULL, 
	[Operating Plant Name] varchar(max) NULL, 
	[Operating Plant Company Code] varchar(max) NULL, 
	[Operating Plant Sales Organization] varchar(max) NULL, 
	[Operating Plant Purchasing Organization] varchar(max) NULL, 
	[Operating Plant Valuation Area] varchar(max) NULL, 
	[Operating Plant Customer Number] varchar(max) NULL, 
	[Operating Plant Vendor Number] varchar(max) NULL, 
	[Operating Plant Factory Calendar Key] varchar(2) NULL, 
	[Operating Plant Line 1 Description] varchar(max) NULL, 
	[Operating Plant Line 2 Description] varchar(max) NULL, 
	[Operating Plant City Name] varchar(max) NULL, 
	[Operating Plant Zip Code] varchar(max) NULL, 
	[Operating Plant Country Code] varchar(max) NULL, 
	[Operating Plant Country Name] varchar(max) NULL, 
	[Operating Plant Tax Jurisdiction] varchar(max) NULL, 
	[ETL SRC SYS CD] varchar(max) NULL, 
	[ETL EFFECTV BEGIN DATE] date NULL, 
	[ETL EFFECTV END DATE] date NULL, 
	[ETL CURR RCD IND] varchar(max) NULL, 
	[ETL CREATED TS] datetime2(0) NULL, 
	[ETL UPDTD TS] datetime2(0) NULL, 
	[Operating Plant IS P001] varchar(max) NULL, 
	[Operating Plant IS P002] varchar(max) NULL, 
	[Operating Plant Company Description] varchar(max) NULL, 
	[Operating Plant Sales Organization Description] varchar(max) NULL, 
	[Operating Plant Factory Calendar Description] varchar(max) NULL, 
	[Operating Plant Purchasing Organization Description] varchar(max) NULL, 
	[Operating Plant Tax Indicator] varchar(max) NULL, 
	[Operating Plant Tax Indicator Description] varchar(max) NULL, 
	[Operating Plant Shipping Receiving Point] varchar(max) NULL, 
	[Operating Plant Shipping Receiving Point Description] varchar(max) NULL
);