CREATE TABLE [Propelis].[PA_COMPLETION_DATE] (

	[DATE_KEY] int NOT NULL, 
	[PA Completion Date] date NULL, 
	[PA Completion Fiscal Year] int NULL, 
	[PA Completion Fiscal Period Number] int NULL, 
	[PA Completion Fiscal Period Code] varchar(max) NULL, 
	[PA Completion Fiscal Quarter Number] int NULL, 
	[PA Completion Fiscal Quarter Code] varchar(max) NULL, 
	[PA Completion Calendar Year] int NULL, 
	[PA Completion Calendar Month Number] int NULL, 
	[PA Completion Calendar Month Code] varchar(max) NULL, 
	[PA Completion Calendar Month Description] varchar(max) NULL, 
	[PA Completion Calendar Quarter Number] int NULL, 
	[PA Completion Calendar Quarter Code] varchar(max) NULL, 
	[PA Completion Calendar Weekday Number] int NULL, 
	[PA Completion Calendar Weekday Name] varchar(max) NULL, 
	[PA Completion Calendar Day In Month] int NULL, 
	[PA Completion Calendar Day In Year] int NULL, 
	[PA Completion Calendar Week] int NULL, 
	[PA Completion Calendar Month In Quarter Number] int NULL, 
	[PA Completion Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[PA Completion Current Day Flag] int NULL, 
	[PA Completion Current Day Minus 1 Flag] int NULL, 
	[PA Completion Current Calendar Week Flag] int NULL, 
	[PA Completion Current Calendar Week Minus 1 Flag] int NULL, 
	[PA Completion Current Month Flag] int NULL, 
	[PA Completion Current Month Minus 1 Flag] int NULL, 
	[PA Completion Current Month Minus 12 Flag] int NULL, 
	[PA Completion Current Quarter Flag] int NULL, 
	[PA Completion Current Quarter Minus 1 Flag] int NULL, 
	[PA Completion Current Quarter Minus 4 Flag] int NULL, 
	[PA Completion Current Calendar Year Flag] int NULL, 
	[PA Completion Current Calendar Year Minus 1 Flag] int NULL, 
	[PA Completion Current Calendar Year Minus 2 Flag] int NULL, 
	[PA Completion Current Fiscal Yr Flag] int NULL, 
	[PA Completion Current Fiscal Year Minus 1 Flag] int NULL, 
	[PA Completion Current Fiscal Year Minus 2 Flag] int NULL, 
	[PA Completion Current Calendar Year Plus 1 Flag] int NULL, 
	[PA Completion Current Fiscal Year Plus 1 Flag] int NULL, 
	[PA Completion Day In Fiscal Year] int NULL, 
	[PA Completion Is Weekday] int NULL, 
	[PA Completion Fiscal Week] int NULL, 
	[PA Completion Current Fiscal Week Flag] int NULL, 
	[PA Completion Current Fiscal Week Minus 1 Flag] int NULL, 
	[PA Completion Fiscal Weekday Number] int NULL, 
	[PA Completion Fiscal Weekday Name] varchar(max) NULL, 
	[PA Completion Current Month Minus 2 Flag] int NULL, 
	[PA Completion Current Fiscal Week Minus 2 Flag] int NULL, 
	[PA Completion Current Fiscal Week Minus 6 Flag] int NULL, 
	[PA Completion Current Fiscal Week Minus 3 Flag] int NULL, 
	[PA Completion Current Fiscal Week Minus 4 Flag] int NULL, 
	[PA Completion Current Fiscal Week Minus 5 Flag] int NULL, 
	[PA Completion Current Fiscal Week Minus 7 Flag] int NULL
);