CREATE TABLE [Propelis].[PARENT_INVOICE] (

	[INVC_KEY] int NOT NULL, 
	[Parent Invoice Sales Order Invoice ID] varchar(max) NULL, 
	[Parent Invoice Company Code] varchar(max) NULL, 
	[Parent Invoice Billing Type Code] varchar(max) NULL, 
	[Parent Invoice Billing Category] varchar(max) NULL, 
	[Parent Invoice SD Document Category] varchar(max) NULL, 
	[Parent Invoice Sales Organization] varchar(max) NULL, 
	[Parent Invoice Distribution Channel] varchar(max) NULL, 
	[Parent Invoice Divison] varchar(max) NULL, 
	[Parent Invoice Parent Invoice Pricing Procedure in Pricing] varchar(max) NULL, 
	[Parent Invoice Document Condition Number] varchar(max) NULL, 
	[Parent Invoice Shipping Condition] varchar(max) NULL, 
	[Parent Invoice Price Group] varchar(max) NULL, 
	[Parent Invoice Customer Group] varchar(max) NULL, 
	[Parent Invoice Price List] varchar(max) NULL, 
	[Parent Invoice Payment Reference] varchar(max) NULL, 
	[Parent Invoice Payment Terms] varchar(max) NULL, 
	[Parent Invoice Incoterms] varchar(max) NULL, 
	[Parent Invoice Incoterms 2] varchar(max) NULL, 
	[Parent Invoice Exchange Rate] decimal(9,5) NULL, 
	[Parent Invoice Net Value] decimal(15,3) NULL, 
	[Parent Invoice Statistical Currency] varchar(max) NULL, 
	[Parent Invoice List Type] varchar(max) NULL, 
	[Parent Invoice Reference] varchar(max) NULL, 
	[Parent Invoice Parent Invoice Date] date NULL, 
	[Parent Invoice Created Date] date NULL, 
	[Parent Invoice Created User ID] varchar(max) NULL, 
	[Parent Invoice Updated Date] date NULL, 
	[Parent Invoice Updated User ID] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Parent Invoice Billing Document Cancelled Indicator] varchar(max) NULL, 
	[Parent Invoice Creation Date] date NULL, 
	[Parent Invoice Changed On Date] date NULL, 
	[Parent Invoice Customer Purchase Order Number] varchar(max) NULL, 
	[Parent Invoice Accounting Transfer Status] varchar(max) NULL, 
	[Parent Invoice Currency Key of Credit Control Area] varchar(max) NULL, 
	[Parent Invoice Accounting Document Number] varchar(max) NULL, 
	[Parent Invoice SD Document Currency] varchar(max) NULL, 
	[Parent Invoice Company Description] varchar(max) NULL, 
	[Parent Invoice Billing Type Description] varchar(max) NULL, 
	[Parent Invoice Billing Category Description] varchar(max) NULL, 
	[Parent Invoice SD Document Category Description] varchar(max) NULL, 
	[Parent Invoice Sales Organization Description] varchar(max) NULL, 
	[Parent Invoice Distribution Channel Description] varchar(max) NULL, 
	[Parent Invoice Division Description] varchar(max) NULL, 
	[Parent Invoice Shipping Condition Description] varchar(max) NULL, 
	[Parent Invoice Price Group Description] varchar(max) NULL, 
	[Parent Invoice Customer Group Description] varchar(max) NULL, 
	[Parent Invoice Price List Description] varchar(max) NULL, 
	[Parent Invoice Payment Terms Description] varchar(max) NULL, 
	[Parent Invoice Incoterms Description] varchar(max) NULL, 
	[Parent Invoice Statistical Currency Description] varchar(max) NULL, 
	[Parent Invoice List Type Description] varchar(max) NULL, 
	[Parent Invoice Accounting Transfer Status Description] varchar(max) NULL, 
	[Parent Invoice SD Document Currency Description] varchar(max) NULL, 
	[Parent Invoice Cancelled Document Number] varchar(max) NULL, 
	[Parent Invoice Terms Discount Percentage] varchar(max) NULL, 
	[Parent Invoice Customer Group 6] varchar(max) NULL, 
	[Parent Invoice Customer Group 7] varchar(max) NULL, 
	[Parent Invoice Customer Group 8] varchar(max) NULL, 
	[Parent Invoice Customer Group 9] varchar(max) NULL, 
	[Parent Invoice Customer Group 10] varchar(max) NULL, 
	[Parent Invoice Customer Group 6 Description] varchar(max) NULL, 
	[Parent Invoice Customer Group 7 Description] varchar(max) NULL, 
	[Parent Invoice Customer Group 8 Description] varchar(max) NULL, 
	[Parent Invoice Customer Group 9 Description] varchar(max) NULL, 
	[Parent Invoice Customer Group 10 Description] varchar(max) NULL
);