CREATE TABLE [Propelis].[PARTNER_PROFIT_CENTER] (

	[PROFT_CNTR_KEY] int NOT NULL, 
	[Partner Profit Center ID] varchar(max) NULL, 
	[Partner Profit Center Description] varchar(max) NULL, 
	[Legacy Partner Profit Center Code] varchar(max) NULL, 
	[Legacy Partner Profit Center Description] varchar(max) NULL, 
	[Partner Profit Center Controlling Area ID] varchar(max) NULL, 
	[Partner Profit Center User Responsible ID] varchar(max) NULL, 
	[Partner Profit Center Person Responsible] varchar(max) NULL, 
	[Partner Profit Center Language Type Code] varchar(max) NULL, 
	[Partner Profit Center Segment ID] varchar(max) NULL, 
	[Partner Profit Center Adress Line 1] varchar(max) NULL, 
	[Partner Profit Center Address Line 2] varchar(max) NULL, 
	[Partner Profit Center City Name] varchar(max) NULL, 
	[Partner Profit Center District Name] varchar(max) NULL, 
	[Partner Profit Center Postal Code] varchar(max) NULL, 
	[Partner Profit Center Country Code] varchar(max) NULL, 
	[Partner Profit Center Region Code] varchar(max) NULL, 
	[Partner Profit Center Created Date] date NULL, 
	[Partner Profit Center Created User ID] varchar(max) NULL, 
	[Partner Profit Center Updated Date] date NULL, 
	[Partner Profit Center Updated User ID] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] datetime2(0) NULL, 
	[ETL_EFFECTV_END_DATE] datetime2(0) NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Partner Profit Center Company Code] varchar(max) NULL, 
	[Partner Profit Center Long Description] varchar(max) NULL, 
	[Partner Profit Center Short Description] varchar(max) NULL, 
	[Partner Profit Center Lock Indicator] varchar(max) NULL, 
	[Profit Center Name 1] varchar(max) NULL, 
	[Partner Profit Center Area] varchar(max) NULL, 
	[Partner Profit Center General Master Record Status] varchar(max) NULL, 
	[Partner Profit Center Status Description] varchar(max) NULL, 
	[Partner Profit Center Controlling Area Desc] varchar(max) NULL, 
	[Partner Profit Center Country Description] varchar(max) NULL, 
	[Partner Profit Center Company Description] varchar(max) NULL, 
	[Partner Profit Center Tax Jurisdiction] varchar(max) NULL, 
	[Partner Profit Center Valid To Date] date NULL, 
	[Partner Profit Center Valid From Date] date NULL
);