CREATE TABLE [Propelis].[PARTNER_COST_CENTER] (

	[COST_CNTR_KEY] int NOT NULL, 
	[Partner Cost Center ID] varchar(max) NULL, 
	[Partner Cost Center Long Description] varchar(max) NULL, 
	[Partner Cost Center Controlling Area ID] varchar(max) NULL, 
	[Partner Cost Center Language Type Code] varchar(max) NULL, 
	[Partner Cost Center Category] varchar(max) NULL, 
	[Partner Cost Center Hierarchy Area] varchar(max) NULL, 
	[Partner Cost Center Company Code] varchar(max) NULL, 
	[Partner Cost Center Plant] varchar(max) NULL, 
	[Partner Cost Center Proft Center ID] varchar(max) NULL, 
	[Partner Cost Center Currency Code] varchar(max) NULL, 
	[Partner Cost Center Address Line 1] varchar(max) NULL, 
	[Partner Cost Center Address Line 2] varchar(max) NULL, 
	[Partner Cost Center Address Line 3] varchar(max) NULL, 
	[Partner Cost Center City Name] varchar(max) NULL, 
	[Partner Cost Center District Name] varchar(max) NULL, 
	[Partner Cost Center Postal Code] varchar(max) NULL, 
	[Partner Cost Center Country Code] varchar(max) NULL, 
	[Partner Cost Center Region Code] varchar(max) NULL, 
	[Partner Cost Center Person Responsible] varchar(max) NULL, 
	[Partner Cost Center Flag Actual Revenues] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Partner CC Actual Primary Postings Lock Indicator] varchar(max) NULL, 
	[Partner CC Plan Primary Costs Lock Indicator] varchar(max) NULL, 
	[Partner Cost Center Business Area] varchar(max) NULL, 
	[Partner CC Planning Revenues Lock Indicator] varchar(max) NULL, 
	[Partner Cost Center PO Box] varchar(max) NULL, 
	[Partner Cost Center Street] varchar(max) NULL, 
	[Partner Cost Center User Responsible] varchar(max) NULL, 
	[Partner Cost Center Description] varchar(max) NULL, 
	[Partner Cost Center Short Description] varchar(max) NULL, 
	[Partner Cost Center Controlling Area Description] varchar(max) NULL, 
	[Partner Cost Center Category Description] varchar(max) NULL, 
	[Partner Cost Center Company Description] varchar(max) NULL, 
	[Partner Cost Center Currency Description] varchar(max) NULL, 
	[Partner Cost Center Country Description] varchar(max) NULL, 
	[Partner Cost Center Business Area Description] varchar(max) NULL, 
	[Partner CC Actual Secondary Cost Lock Indicator] varchar(max) NULL, 
	[Partner CC Plan Secondary Cost Lock Indicator] varchar(max) NULL, 
	[Partner Cost Center Functional Area] varchar(max) NULL, 
	[Partner Cost Center Functional Area Description] varchar(max) NULL, 
	[Partner Cost Center Tax Jurisdiction] varchar(max) NULL, 
	[Partner Cost Center Function] varchar(max) NULL, 
	[Partner Cost Center Plant Description] varchar(max) NULL, 
	[Partner Cost Center Created On] date NULL, 
	[Partner Cost Center Valid To Date] date NULL, 
	[Partner Cost Center Valid From Date] date NULL
);