CREATE TABLE [Propelis].[PLANNED_RELEASE_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Planned Release Date] date NULL, 
	[Planned Release Fiscal Year] int NULL, 
	[Planned Release Fiscal Period Number] int NULL, 
	[Planned Release Fiscal Period Code] varchar(max) NULL, 
	[Planned Release Fiscal Quarter Number] int NULL, 
	[Planned Release Fiscal Quarter Code] varchar(max) NULL, 
	[Planned Release Calendar Year] int NULL, 
	[Planned Release Calendar Month Number] int NULL, 
	[Planned Release Calendar Month Code] varchar(max) NULL, 
	[Planned Release Calendar Month Description] varchar(max) NULL, 
	[Planned Release Calendar Quarter Number] int NULL, 
	[Planned Release Calendar Quarter Code] varchar(max) NULL, 
	[Planned Release Calendar Weekday Number] int NULL, 
	[Planned Release Calendar Weekday Name] varchar(max) NULL, 
	[Planned Release Calendar Day In Month] int NULL, 
	[Planned Release Calendar Day In Year] int NULL, 
	[Planned Release Calendar Week] int NULL, 
	[Planned Release Calendar Month In Quarter Number] int NULL, 
	[Planned Release Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Planned Release Current Day Flag] int NULL, 
	[Planned Release Current Day Minus 1 Flag] int NULL, 
	[Planned Release Current Calendar Week Flag] int NULL, 
	[Planned Release Current Calendar Week Minus 1 Flag] int NULL, 
	[Planned Release Current Month Flag] int NULL, 
	[Planned Release Current Month Minus 1 Flag] int NULL, 
	[Planned Release Current Month Minus 12 Flag] int NULL, 
	[Planned Release Current Quarter Flag] int NULL, 
	[Planned Release Current Quarter Minus 1 Flag] int NULL, 
	[Planned Release Current Quarter Minus 4 Flag] int NULL, 
	[Planned Release Current Calendar Year Flag] int NULL, 
	[Planned Release Current Calendar Year Minus 1 Flag] int NULL, 
	[Planned Release Current Calendar Year Minus 2 Flag] int NULL, 
	[Planned Release Current Fiscal Year Flag] int NULL, 
	[Planned Release Current Fiscal Year Minus 1 Flag] int NULL, 
	[Planned Release Current Fiscal Year Minus 2 Flag] int NULL, 
	[Planned Release Current Calendar Year Plus 1 Flag] int NULL, 
	[CURR_FISCAL_YR_PLUS_1_FLG] int NULL, 
	[Planned Release Day In Fiscal Year] int NULL, 
	[Planned Release Date Is Weekday] int NULL, 
	[Planned Release Fiscal Week] int NULL, 
	[Planned Release Current Fiscal Week Flag] int NULL, 
	[Planned Release Current Fiscal Week Minus 1 Flag] int NULL, 
	[Planned Release Fiscal Weekday Number] int NULL, 
	[Planned Release Fiscal Weekday Name] varchar(max) NULL, 
	[Planned Release Current Month Minus 2 Flag] int NULL, 
	[Planned Release Current Fiscal Week Minus 2 Flag] int NULL, 
	[Planned Release Current Fiscal Week Minus 6 Flag] int NULL, 
	[Planned Release Current Fiscal Week Minus 3 Flag] int NULL, 
	[Planned Release Current Fiscal Week Minus 4 Flag] int NULL, 
	[Planned Release Current Fiscal Week Minus 5 Flag] int NULL, 
	[Planned Release Current Fiscal Week Minus 7 Flag] int NULL
);