CREATE TABLE [Propelis].[POSTING_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Posting Date] date NULL, 
	[Posting Fiscal Year] int NULL, 
	[FISCAL PER NUM] int NULL, 
	[Posting Fiscal Period Code] varchar(max) NULL, 
	[Posting Fiscal Quarter Number] int NULL, 
	[Posting Fiscal Quarter Code] varchar(max) NULL, 
	[Posting Calendar Year] int NULL, 
	[Posting Calendar Month Number] int NULL, 
	[Posting Calendar Month Code] varchar(max) NULL, 
	[Posting Calendar Month Desc] varchar(max) NULL, 
	[CLNDR QTR NUM] int NULL, 
	[Posting Calendar Quarter Code] varchar(max) NULL, 
	[Posting Calendar Weekday Number] int NULL, 
	[Posting Calendar Weekday Name] varchar(max) NULL, 
	[Posting Calendar Day in Month] int NULL, 
	[Posting Calendar Day in Year] int NULL, 
	[Posting Calendar Week] int NULL, 
	[Posting Calendar Month in Quarter Number] int NULL, 
	[Posting Calendar Days in Month] int NULL, 
	[ETL SRC SYS CD] varchar(max) NULL, 
	[ETL CREATED TS] datetime2(0) NULL, 
	[ETL UPDTD TS] datetime2(0) NULL, 
	[Posting Current Day Flag] int NULL, 
	[Posting Current Day Minus 1 Flag] int NULL, 
	[Posting Current Calendar Week Flag] int NULL, 
	[Posting Current Calendar Week Minus 1 Flag] int NULL, 
	[Posting Current Month Flag] int NULL, 
	[Posting Current Month Minus 1 Flag] int NULL, 
	[Posting Current Month Minus 12 Flag] int NULL, 
	[Posting Current Quarter Flag] int NULL, 
	[Posting Current Quarter Minus 1 Flag] int NULL, 
	[Posting Current Quarter Minus 4 Flag] int NULL, 
	[Posting Current Calendar Year Flag] int NULL, 
	[Posting Current Calendar Year Minus 1 Flag] int NULL, 
	[Posting Current Calendar Year Minus 2 Flag] int NULL, 
	[Posting Current Fiscal Year Flag] int NULL, 
	[Posting Current Fiscal Year Minus 1 Flag] int NULL, 
	[Posting Current Fiscal Year Minus 2 Flag] int NULL, 
	[Posting Current Calendar Year Plus 1 Flag] int NULL, 
	[Posting Current Fiscal Year Plus 1 Flag] int NULL, 
	[Posting Day in Fiscal Year] int NULL, 
	[Posting Date Is Weekday] int NULL, 
	[Posting Fiscal Week] int NULL, 
	[Posting Current Fiscal Week Flag] int NULL, 
	[Posting Current Fiscal Week Minus 1 Flag] int NULL, 
	[Posting Fiscal Weekday Number] int NULL, 
	[Posting Fiscal Weekday Name] varchar(max) NULL, 
	[Posting Current Month Minus 2 Flag] int NULL, 
	[Posting Current Fiscal Week Minus 2 Flag] int NULL, 
	[Posting Current Fiscal Week Minus 6 Flag] int NULL, 
	[Posting Current Fiscal Week Minus 3 Flag] int NULL, 
	[Posting Current Fiscal Week Minus 4 Flag] int NULL, 
	[Posting Current Fiscal Week Minus 5 Flag] int NULL, 
	[Posting Current Fiscal Week Minus 7 Flag] int NULL
);