CREATE TABLE [Propelis].[PRINTER_CUST] (

	[CUST_KEY] int NOT NULL, 
	[Printer Customer ID] varchar(max) NULL, 
	[Printer Legacy Customer ID] varchar(max) NULL, 
	[Printer Customer Name] varchar(max) NULL, 
	[Printer Cust Line 2 Description] varchar(max) NULL, 
	[Printer Cust Country Code] varchar(max) NULL, 
	[Printer Cust Plant ID] varchar(max) NULL, 
	[Printer Cust Segment ID] varchar(max) NULL, 
	[Printer Cust Industry] varchar(max) NULL, 
	[Printer Cust Vendor ID] varchar(max) NULL, 
	[Printer Cust Customer Group Code] varchar(max) NULL, 
	[Printer Cust Account Group Code] varchar(max) NULL, 
	[Printer Cust Title] varchar(max) NULL, 
	[Printer Cust Search Term] varchar(max) NULL, 
	[Printer Cust Street] varchar(max) NULL, 
	[Printer Cust City] varchar(max) NULL, 
	[Printer Cust Zip Code] varchar(max) NULL, 
	[Printer Cust State Code] varchar(max) NULL, 
	[Printer Cust Region Code] varchar(max) NULL, 
	[Printer Cust Telephone Number 1] varchar(max) NULL, 
	[Printer Cust Telephone Number 2] varchar(max) NULL, 
	[Printer Cust Fax Number Code] varchar(max) NULL, 
	[Printer Cust Tax Number 1 Code] varchar(max) NULL, 
	[Printer Cust Tax Number 2 Code] varchar(max) NULL, 
	[Printer Cust VAT Number Code] varchar(max) NULL, 
	[Printer Cust Credit Limit] decimal(15,3) NULL, 
	[Printer Cust Bonus Rate] decimal(9,3) NULL, 
	[Printer Cust Express Station] varchar(max) NULL, 
	[Printer Cust Transportation Zone] varchar(max) NULL, 
	[Printer Cust Printer Location Characteristics] varchar(max) NULL, 
	[Printer Cust Printer Region Characteristics] varchar(max) NULL, 
	[Printer Cust Printer Site Characteristics] varchar(max) NULL, 
	[Printer Cust Customer Created Date] date NULL, 
	[Printer Cust Created User ID] varchar(max) NULL, 
	[Printer Cust Customer Updated Date] date NULL, 
	[Printer Cust Updated User ID] varchar(max) NULL, 
	[Printer Cust Payment Terms Code] varchar(max) NULL, 
	[Printer Cust Sales Distribution] varchar(max) NULL, 
	[Printer Cust Order Block For Sales Area] varchar(max) NULL, 
	[Printer Cust Delivery Block For Sales Area] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Printer Cust Corporate Group] varchar(max) NULL, 
	[Printer Cust Classification] varchar(max) NULL, 
	[Printer Cust Classification Description] varchar(max) NULL, 
	[Printer Cust Printer Location] varchar(max) NULL, 
	[Printer Cust Printer Site] varchar(max) NULL, 
	[Printer Cust Printer Region] varchar(max) NULL, 
	[Printer Cust Specific Field Label 01] varchar(max) NULL, 
	[Printer Cust Specific Field Label 02] varchar(max) NULL, 
	[Printer Cust Specific Field Label 03] varchar(max) NULL, 
	[Printer Cust Specific Field Label 04] varchar(max) NULL, 
	[Printer Cust Specific Field Label 05] varchar(max) NULL, 
	[Printer Cust Specific Field Label 06] varchar(max) NULL, 
	[Printer Cust Specific Field Label 07] varchar(max) NULL, 
	[Printer Cust Specific Field Label 08] varchar(max) NULL, 
	[Printer Cust Specific Field Label 09] varchar(max) NULL, 
	[Printer Cust Specific Field Label 10] varchar(max) NULL, 
	[Printer Cust Specific Field Label 11] varchar(max) NULL, 
	[Printer Cust Specific Field Label 12] varchar(max) NULL, 
	[Printer Cust Specific Field Label 13] varchar(max) NULL, 
	[Printer Cust Specific Field Label 14] varchar(max) NULL, 
	[Printer Cust Specific Field Label 15] varchar(max) NULL, 
	[Printer Cust Specific Field Label 16] varchar(max) NULL, 
	[Printer Cust Specific Field Label 17] varchar(max) NULL, 
	[Printer Cust Specific Field Label 18] varchar(max) NULL, 
	[Printer Cust Specific Field Label 19] varchar(max) NULL, 
	[Printer Cust Specific Field Label 20] varchar(max) NULL, 
	[Printer Cust Condition Group 1] varchar(max) NULL, 
	[Printer Cust Industry Code 1] varchar(max) NULL, 
	[Printer Cust Industry Code 2] varchar(max) NULL, 
	[Printer Cust Industry Description] varchar(max) NULL, 
	[Printer Cust Industry Code 1 Description] varchar(max) NULL, 
	[Printer Cust Industry Code 2 Description] varchar(max) NULL, 
	[Printer Cust Assignment to Hierarchy] int NULL, 
	[Printer Cust Account Group Description] varchar(max) NULL, 
	[Printer Cust Region Description] varchar(max) NULL, 
	[Printer Cust Country Description] varchar(max) NULL, 
	[Printer Cust Transportation Zone Description] varchar(max) NULL, 
	[Printer Cust Plant Description] varchar(max) NULL, 
	[Printer Cust Condition Group Description] varchar(max) NULL, 
	[Printer Cust Cental Billing Block] varchar(max) NULL, 
	[Printer Cust Cental Billing Block Description] varchar(max) NULL, 
	[Printer Cust Central Delivery Block] varchar(max) NULL, 
	[Printer Cust Central Delivery Block Description] varchar(max) NULL, 
	[Printer Cust Deletion Indicator] varchar(max) NULL, 
	[Printer Cust Central Posting Block] varchar(max) NULL, 
	[Printer Cust Tax Jurisdiction] varchar(max) NULL, 
	[Printer Cust Central Sales Block] varchar(max) NULL, 
	[Printer Cust Central Deletion Indicator] varchar(max) NULL, 
	[Printer Cust Language Key] varchar(max) NULL, 
	[Printer Cust Trading Partner] varchar(max) NULL, 
	[Printer Cust Trading Partner Description] varchar(max) NULL, 
	[Printer Cust Annual Sales] decimal(8,2) NULL, 
	[Printer Cust Annual Sales Year] int NULL, 
	[Printer Cust Sales Currency] varchar(max) NULL, 
	[Printer Cust Sales Currency Description] varchar(max) NULL, 
	[Printer Cust One Time Account Group] varchar(max) NULL, 
	[Printer Cust One Time Account Group Description] varchar(max) NULL, 
	[Printer Cust One Time Indicator] varchar(max) NULL, 
	[Printer Cust Industry Type] varchar(max) NULL, 
	[Printer Cust Business Type] varchar(max) NULL, 
	[Printer Cust DUNS Number] varchar(max) NULL, 
	[Printer Cust DUNS Plus 4] varchar(max) NULL, 
	[Printer Cust City Coordinates] varchar(max) NULL, 
	[Printer Cust Tax Number 4 Code] varchar(max) NULL, 
	[Printer Cust Attribute 3] varchar(max) NULL, 
	[Printer Cust Attribute 3 Description] varchar(max) NULL, 
	[Printer Cust E-Mail Address] varchar(max) NULL, 
	[Printer Cust Mobile Number] varchar(max) NULL, 
	[Printer Cust Search Term 2] varchar(max) NULL, 
	[Printer Cust Street 2] varchar(max) NULL, 
	[Printer Cust Street 3] varchar(max) NULL, 
	[Printer Cust Street 4] varchar(max) NULL, 
	[Printer Cust Street 5] varchar(max) NULL, 
	[Printer Cust PO Box] varchar(max) NULL, 
	[Printer Cust PO Box Postal Code] varchar(max) NULL, 
	[Printer Cust PO Box City] varchar(max) NULL, 
	[Printer Cust Region For PO Box] varchar(max) NULL, 
	[Printer Cust PO Box Country] varchar(max) NULL, 
	[Printer Cust Transport Zone] varchar(max) NULL, 
	[Printer Cust Address Notes] varchar(max) NULL, 
	[Printer Cust Tax Number 3 Code] varchar(max) NULL, 
	[Printer Cust Tax Number 5 Code] varchar(max) NULL, 
	[Printer Cust Industry Code 3] varchar(max) NULL, 
	[Printer Cust Industry Code 3 Description] varchar(max) NULL, 
	[Printer Cust Industry Code 4] varchar(max) NULL, 
	[Printer Cust Industry Code 4 Description] varchar(max) NULL, 
	[Printer Cust Industry Code 5] varchar(max) NULL, 
	[Printer Cust Industry Code 5 Description] varchar(max) NULL, 
	[Printer Cust Central Order Block For Customer] varchar(max) NULL, 
	[Printer Cust Payment Block] varchar(max) NULL
);