CREATE TABLE [Propelis].[PRODUCING_PLANT] (

	[PLNT_KEY] int NOT NULL, 
	[Producing Plant ID] varchar(max) NULL, 
	[Producing Legacy Plant ID] varchar(max) NULL, 
	[Producing Plant Name] varchar(max) NULL, 
	[Producing Plant Company Code] varchar(max) NULL, 
	[Producing Plant Sales Organization] varchar(max) NULL, 
	[Producing Plant Purchasing Organization] varchar(max) NULL, 
	[Producing Plant Valuation Area] varchar(max) NULL, 
	[Producing Plant Customer Number] varchar(max) NULL, 
	[Producing Plant Vendor Number] varchar(max) NULL, 
	[Producing Plant Factory Calendar Key] varchar(max) NULL, 
	[Producing Plant Line 1 Description] varchar(max) NULL, 
	[Producing Plant Line 2 Description] varchar(max) NULL, 
	[Producing Plant City Name] varchar(max) NULL, 
	[Producing Plant Zip Code] varchar(max) NULL, 
	[Producing Plant Country Code] varchar(max) NULL, 
	[Producing Plant Country Name] varchar(max) NULL, 
	[Producing Plant Tax Jurisdiction] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Producing Plant Is P001] varchar(max) NULL, 
	[Producing Plant Is P002] varchar(max) NULL, 
	[Producing Plant Company Description] varchar(max) NULL, 
	[Producing Plant Sales Organization Description] varchar(max) NULL, 
	[Producing Plant Factory Calendar Description] varchar(max) NULL, 
	[Producing Plant Purchasing Organization Description] varchar(max) NULL, 
	[Producing Plant Tax Indicator] varchar(max) NULL, 
	[Producing Plant Tax Indicator Description] varchar(max) NULL, 
	[Producing Plant Shipping/Receiving Point] varchar(max) NULL, 
	[Producing Plant Shipping/Receiving Point Description] varchar(max) NULL
);