CREATE TABLE [Propelis].[PROFIT_CENTER] (

	[PROFT_CNTR_KEY] int NOT NULL, 
	[Profit Center ID] varchar(max) NULL, 
	[Profit Center Description] varchar(max) NULL, 
	[Legacy Profit Center Code] varchar(max) NULL, 
	[Legacy Profit Center Description] varchar(max) NULL, 
	[Profit Center Controlling Area ID] varchar(max) NULL, 
	[Profit Center User Responsible ID] varchar(max) NULL, 
	[Profit Center Person Responsible] varchar(max) NULL, 
	[Profit Center Language Type Code] varchar(max) NULL, 
	[Profit Center Segment ID] varchar(max) NULL, 
	[Profit Center Address Line 1] varchar(max) NULL, 
	[Profit Center Address Line 2] varchar(max) NULL, 
	[Profit Center City Name] varchar(max) NULL, 
	[Profit Center District Name] varchar(max) NULL, 
	[Profit Center Postal Code] varchar(max) NULL, 
	[Profit Center Country Code] varchar(max) NULL, 
	[Profit Center Region Code] varchar(max) NULL, 
	[Profit Center Created Date] date NULL, 
	[Profit Center Created User ID] varchar(max) NULL, 
	[Profit Center Updated Date] date NULL, 
	[Profit Center Updated User ID] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Profit Center Company Code] varchar(max) NULL, 
	[Profit Center Long Description] varchar(max) NULL, 
	[Profit Center Short Description] varchar(max) NULL, 
	[Profit Center Lock Indicator] varchar(max) NULL, 
	[Profit Center Name 1] varchar(max) NULL, 
	[Profit Center Area] varchar(max) NULL, 
	[Profit Center General Master Record Status] varchar(max) NULL, 
	[Profit Center Status Description] varchar(max) NULL, 
	[Profit Center Controlling Area Desc] varchar(max) NULL, 
	[Profit Center Country Description] varchar(max) NULL, 
	[Profit Center Company Description] varchar(max) NULL, 
	[Profit Center Tax Jurisdiction] varchar(max) NULL, 
	[Profit Center Valid To Date] date NULL, 
	[Profit Center Valid From Date] date NULL
);