CREATE TABLE [Propelis].[QC_COMPLETION_DATE] (

	[DATE_KEY] int NOT NULL, 
	[QC Completion Date] date NULL, 
	[QC Completion Fiscal Year] int NULL, 
	[QC Completion Fiscal Period Number] int NULL, 
	[QC Completion Fiscal Period Code] varchar(max) NULL, 
	[QC Completion Fiscal Quarter Number] int NULL, 
	[QC Completion Fiscal Quarter Code] varchar(max) NULL, 
	[QC Completion Calendar Year] int NULL, 
	[QC Completion Calendar Month Number] int NULL, 
	[QC Completion Calendar Month Code] varchar(max) NULL, 
	[QC Completion Calendar Month Description] varchar(max) NULL, 
	[QC Completion Calendar Quarter Number] int NULL, 
	[QC Completion Calendar Quarter Code] varchar(max) NULL, 
	[QC Completion Calendar Weekday Number] int NULL, 
	[QC Completion Calendar Weekday Name] varchar(max) NULL, 
	[QC Completion Calendar Day In Month] int NULL, 
	[QC Completion Calendar Day In Year] int NULL, 
	[QC Completion Calendar Week] int NULL, 
	[QC Completion Calendar Month In Quarter Number] int NULL, 
	[QC Completion Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[QC Completion Current Day Flag] int NULL, 
	[QC Completion Current Day Minus 1 Flag] int NULL, 
	[QC Completion Current Calendar Week Flag] int NULL, 
	[QC Completion Current Calendar Week Minus 1 Flag] int NULL, 
	[QC Completion Current Month Flag] int NULL, 
	[QC Completion Current Month Minus 1 Flag] int NULL, 
	[QC Completion Current Month Minus 12 Flag] int NULL, 
	[QC Completion Current Quarter Flag] int NULL, 
	[QC Completion Current Quarter Minus 1 Flag] int NULL, 
	[QC Completion Current Quarter Minus 4 Flag] int NULL, 
	[QC Completion Current Calendar Year Flag] int NULL, 
	[QC Completion Current Calendar Year Minus 1 Flag] int NULL, 
	[QC Completion Current Calendar Year Minus 2 Flag] int NULL, 
	[QC Completion Current Fiscal Year Flag] int NULL, 
	[QC Completion Current Fiscal Year Minus 1 Flag] int NULL, 
	[QC Completion Current Fiscal Year Minus 2 Flag] int NULL, 
	[QC Completion Current Calendar Year Plus 1 Flag] int NULL, 
	[QC Completion_FISCAL_YR_PLUS_1_FLG] int NULL, 
	[QC Completion Day In Fiscal Year] int NULL, 
	[QC Completion Date Is Weekday] int NULL, 
	[QC Completion Fiscal Week] int NULL, 
	[QC Completion Current Fiscal Week Flag] int NULL, 
	[QC Completion Current Fiscal Week Minus 1 Flag] int NULL, 
	[QC Completion Fiscal Weekday Number] int NULL, 
	[QC Completion Fiscal Weekday Name] varchar(max) NULL, 
	[QC Completion Current Month Minus 2 Flag] int NULL, 
	[QC Completion Current Fiscal Week Minus 2 Flag] int NULL, 
	[QC Completion Current Fiscal Week Minus 6 Flag] int NULL, 
	[QC Completion Current Fiscal Week Minus 3 Flag] int NULL, 
	[QC Completion Current Fiscal Week Minus 4 Flag] int NULL, 
	[QC Completion Current Fiscal Week Minus 5 Flag] int NULL, 
	[QC Completion Current Fiscal Week Minus 7 Flag] int NULL
);