CREATE TABLE [Propelis].[QC_PLANT] (

	[PLNT_KEY] int NOT NULL, 
	[QC Plant ID] varchar(max) NULL, 
	[QC Legacy Plant ID] varchar(max) NULL, 
	[QC Plant Name] varchar(max) NULL, 
	[QC Company Code] varchar(max) NULL, 
	[QC Sales Organization] varchar(max) NULL, 
	[QC Purchasing Organization] varchar(max) NULL, 
	[QC Valuation Area] varchar(max) NULL, 
	[QC Customer Number Of Plant] varchar(max) NULL, 
	[QC Vendor Number Of Plant] varchar(max) NULL, 
	[Plant Factory Calendar Key] varchar(max) NULL, 
	[QC Plant Line 1 Description] varchar(max) NULL, 
	[QC Plant Line 2 Description] varchar(max) NULL, 
	[QC Plant City Name] varchar(max) NULL, 
	[QC Plant Zip Code] varchar(max) NULL, 
	[QC Plant Country Code] varchar(max) NULL, 
	[QC Plant Country Name] varchar(max) NULL, 
	[QC Tax Jurisdiction] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] datetime2(0) NULL, 
	[ETL_EFFECTV_END_DATE] datetime2(0) NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[QC Is P001] varchar(max) NULL, 
	[QC Is P002] varchar(max) NULL, 
	[QC Company Description] varchar(max) NULL, 
	[QC Sales Organization Description] varchar(max) NULL, 
	[QC Factory Calendar Description] varchar(max) NULL, 
	[QC Purchasing Organization Description] varchar(max) NULL, 
	[QC Plant Tax Indicator] varchar(max) NULL, 
	[QC Plant Tax Indicator Description] varchar(max) NULL, 
	[QC Shipping Receiving Point] varchar(max) NULL, 
	[QC Shipping Receiving Point Description] varchar(max) NULL
);