CREATE TABLE [Propelis].[RECEIVING_PLANT] (

	[PLNT_KEY] int NOT NULL, 
	[Receiving Plant ID] varchar(max) NULL, 
	[Receiving Legacy Plant ID] varchar(max) NULL, 
	[Receiving Plant Name] varchar(max) NULL, 
	[Receiving Plant Company Code] varchar(max) NULL, 
	[Receiving Plant Sales Organization] varchar(max) NULL, 
	[Receiving Plant Purchasing Organization] varchar(max) NULL, 
	[Receiving Plant Valuation Area] varchar(max) NULL, 
	[Receiving Customer Number Of Plant] varchar(max) NULL, 
	[Receiving Vendor Number Of Plant] varchar(max) NULL, 
	[FACTORY_CLNDR_KEY] varchar(max) NULL, 
	[Receiving Plant Line 1 Description] varchar(max) NULL, 
	[Receiving Plant Line 2 Description] varchar(max) NULL, 
	[Receiving Plant City Name] varchar(max) NULL, 
	[Receiving Plant Zip Code] varchar(max) NULL, 
	[Receiving Plant Country Code] varchar(max) NULL, 
	[Receiving Plant Country Name] varchar(max) NULL, 
	[Receiving Plant Tax Jurisdiction] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Receiving Plant Is P001] varchar(max) NULL, 
	[Receiving Plant Is P002] varchar(max) NULL, 
	[Receiving Plant Company Description] varchar(max) NULL, 
	[Receiving Plant Sales Organiztion Description] varchar(max) NULL, 
	[Receiving Plant Factory Calendar Description] varchar(max) NULL, 
	[Receiving Plant Purchasing Organization Description] varchar(max) NULL, 
	[Receiving Plant Tax Indicator] varchar(max) NULL, 
	[Receiving Plant Tax Indicator Description] varchar(max) NULL, 
	[Receiving Plant Shipping Recvng Point] varchar(max) NULL, 
	[Receiving Plant Shipping Recvng Point Description] varchar(max) NULL
);