CREATE TABLE [Propelis].[RELEASE_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Release Date] date NULL, 
	[Release Fiscal Year] int NULL, 
	[Release Fiscal Period Number] int NULL, 
	[Release Fiscal Period Code] varchar(max) NULL, 
	[Release Fiscal Quarter Number] int NULL, 
	[Release Fiscal Quarter Code] varchar(max) NULL, 
	[Release Calendar Year] int NULL, 
	[Release Calendar Month Number] int NULL, 
	[Release Calendar Month Code] varchar(max) NULL, 
	[Release Calendar Month Description] varchar(max) NULL, 
	[Release Calendar Quarter Number] int NULL, 
	[Release Calendar Quarter Code] varchar(max) NULL, 
	[Release Calendar Weekday Number] int NULL, 
	[Release Calendar Weekday Name] varchar(max) NULL, 
	[Release Calendar Day In Month] int NULL, 
	[Release Calendar Day In Year] int NULL, 
	[Release Calendar Week] int NULL, 
	[Release Calendar Month In Quarter Number] int NULL, 
	[Release Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Release Current Day Flag] int NULL, 
	[Release Current Day Minus 1 Flag] int NULL, 
	[Release Current Calendar Week Flag] int NULL, 
	[Release Current Calendar Week Minus 1 Flag] int NULL, 
	[Release Current Month Flag] int NULL, 
	[Release Current Month Minus 1 Flag] int NULL, 
	[Release Current Month Minus 12 Flag] int NULL, 
	[Release Current Quarter Flag] int NULL, 
	[Release Current Quarter Minus 1 Flag] int NULL, 
	[Release Current Quarter Minus 4 Flag] int NULL, 
	[Release Current Calendar Year Flag] int NULL, 
	[Release Current Calendar Year Minus 1 Flag] int NULL, 
	[Release Current Calendar Year Minus 2 Flag] int NULL, 
	[Release Current Fiscal Year Flag] int NULL, 
	[Release Current Fiscal Year Minus 1 Flag] int NULL, 
	[Release Current Fiscal Year Minus 2 Flag] int NULL, 
	[Release Current Calendar Year Plus 1 Flag] int NULL, 
	[CURR_FISCAL_YR_PLUS_1_FLG] int NULL, 
	[Release Day In Fiscal Year] int NULL, 
	[Release Date Is Weekday] int NULL, 
	[Release Fiscal Week] int NULL, 
	[Release Current Fiscal Week Flag] int NULL, 
	[Release Current Fiscal Week Minus 1 Flag] int NULL, 
	[Release Fiscal Weekday Number] int NULL, 
	[Release Fiscal Weekday Name] varchar(max) NULL, 
	[Release Current Month Minus 2 Flag] int NULL, 
	[Release Current Fiscal Week Minus 2 Flag] int NULL, 
	[Release Current Fiscal Week Minus 6 Flag] int NULL, 
	[Release Current Fiscal Week Minus 3 Flag] int NULL, 
	[Release Current Fiscal Week Minus 4 Flag] int NULL, 
	[Release Current Fiscal Week Minus 5 Flag] int NULL, 
	[Release Current Fiscal Week Minus 7 Flag] int NULL
);