CREATE TABLE [Propelis].[REQD_DELVRY_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Required Delivery Date] date NULL, 
	[Required Delivery Fiscal Year] int NULL, 
	[Required Delivery Fiscal Period] int NULL, 
	[Required Fiscal Period Code] varchar(max) NULL, 
	[Required Fiscal Quarter] int NULL, 
	[Required Fiscal Quarter Code] varchar(max) NULL, 
	[Required Calendar Year] int NULL, 
	[Required Calendar Month Number] int NULL, 
	[Required Calendar Month Code] varchar(max) NULL, 
	[Required Calendar Month Desc] varchar(max) NULL, 
	[Required Calendar Quarter] int NULL, 
	[Required Calendar Quarter Code] varchar(max) NULL, 
	[Required Calendar Weekday Number] int NULL, 
	[Required Calendar Weekday Name] varchar(max) NULL, 
	[Required Calendar Day] int NULL, 
	[Required Calendar Day in Year] int NULL, 
	[Required Calendar Week] int NULL, 
	[Required Calendar Month in Quarter Number] int NULL, 
	[Required Calendar Days in Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[CURR_DAY_FLG] int NULL, 
	[Required Current Day Minus 1 Flag] int NULL, 
	[Required Current Calendar Week Flag] int NULL, 
	[Required Current Calendar Week Minus 1 Flag] int NULL, 
	[Required Current Month Flag] int NULL, 
	[Required Current Month Minus 1 Flag] int NULL, 
	[Required Current Month Minus 12 Flag] int NULL, 
	[Required Current Quarter Flag] int NULL, 
	[Required Current Quarter Minus 1 Flag] int NULL, 
	[Required Current Quarter Minus 4 Flag] int NULL, 
	[Required Current Calendar Year Flag] int NULL, 
	[Required Current Calendar Year Minus 1 Flag] int NULL, 
	[Required Current Calendar Year Minus 2 Flag] int NULL, 
	[Required Current Fiscal Year Flag] int NULL, 
	[Required Current Fiscal Year Minus 1 Flag] int NULL, 
	[Required Current Fiscal Year Minus 2 Flag] int NULL, 
	[Required Current Calendar Year Plus 1 Flag] int NULL, 
	[Required Current Fiscal Year Plus 1 Flag] int NULL, 
	[Required Day In Fiscal Year] int NULL, 
	[Required Date Is Weekday] int NULL, 
	[Required Fiscal Week] int NULL, 
	[Required Current Fiscal Week Flag] int NULL, 
	[Required Current Fiscal Week Minus 1 Flag] int NULL, 
	[Required Fiscal Weekday Number] int NULL, 
	[Required Fiscal Weekday Name] varchar(max) NULL, 
	[Required Current Month Minus 2 Flag] int NULL, 
	[Required Current Fiscal Week Minus 2 Flag] int NULL, 
	[Required Current Fiscal Week Minus 6 Flag] int NULL, 
	[Required Current Fiscal Week Minus 3 Flag] int NULL, 
	[Required Current Fiscal Week Minus 4 Flag] int NULL, 
	[Required Current Fiscal Week Minus 5 Flag] int NULL, 
	[Required Current Fiscal Week Minus 7 Flag] int NULL
);