CREATE TABLE [Propelis].[REQUIREMENT_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Requirement Date] date NULL, 
	[Requirement Fiscal Year] int NULL, 
	[Requirement Fiscal Period Number] int NULL, 
	[Requirement Fiscal Period Code] varchar(max) NULL, 
	[Requirement Fiscal Quarter Number] int NULL, 
	[Requirement Current Fiscal Week Minus 7 Flag] int NULL, 
	[Requirement Current Month Minus 2 Flag] int NULL, 
	[Requirement Current Fiscal Week Minus 2 Flag] int NULL, 
	[Requirement Current Fiscal Week Minus 6 Flag] int NULL, 
	[Requirement Current Fiscal Week Minus 3 Flag] int NULL, 
	[Requirement Current Fiscal Week Minus 4 Flag] int NULL, 
	[Requirement Current Fiscal Week Minus 5 Flag] int NULL, 
	[Requirement Date Is Weekday] int NULL, 
	[Requirement Fiscal Week] int NULL, 
	[Requirement Current Fiscal Week Flag] int NULL, 
	[Requirement Current Fiscal Week Minus 1 Flag] int NULL, 
	[Requirement Fiscal Weekday Number] int NULL, 
	[Requirement Fiscal Weekday Name] varchar(max) NULL, 
	[Requirement Current Fiscal Year Flag] int NULL, 
	[Requirement Current Fiscal Year Minus 1 Flag] int NULL, 
	[Requirement Current Fiscal Year Minus 2 Flag] int NULL, 
	[Requirement Current Calendar Year Plus 1 Flag] int NULL, 
	[Requirement Current Fiscal Year Plus 1 Flag] int NULL, 
	[Requirement Day In Fiscal Year] int NULL, 
	[Requirement Current Quarter Flag] int NULL, 
	[Requirement Current Quarter Minus 1 Flag] int NULL, 
	[Requirement Current Quarter Minus 4 Flag] int NULL, 
	[Requirement Current Calendar Year Flag] int NULL, 
	[Requirement Current Calendar Year Minus 1 Flag] int NULL, 
	[Requirement Current Calendar Year Minus 2 Flag] int NULL, 
	[Requirement Current Day Minus 1 Flag] int NULL, 
	[Requirement Current Calendar Week Flag] int NULL, 
	[Requirement Current Calendar Week Minus 1 Flag] int NULL, 
	[Requirement Current Month Flag] int NULL, 
	[Requirement Current Month Minus 1 Flag] int NULL, 
	[Requirement Current Month Minus 12 Flag] int NULL, 
	[Requirement Calendar Month In Quarter Number] int NULL, 
	[Requirement Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Requirement Current Day Flag] int NULL, 
	[Requirement Calendar Quarter Code] varchar(max) NULL, 
	[Requirement Calendar Weekday Number] int NULL, 
	[Requirement Calendar Weekday Name] varchar(max) NULL, 
	[Requirement Calendar Day In Month] int NULL, 
	[Requirement Calendar Day In Year] int NULL, 
	[Requirement Calendar Week] int NULL, 
	[Requirement Fiscal Quarter Code] varchar(max) NULL, 
	[Requirement Calendar Year] int NULL, 
	[Requirement Calendar Month Number] int NULL, 
	[Requirement Calendar Month Code] varchar(max) NULL, 
	[Requirement Calendar Month Description] varchar(max) NULL, 
	[Requirement Calendar Quarter Number] int NULL
);