CREATE TABLE [Propelis].[SALES_ORDER_HEADER_CREATE_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Sales Order Header Creation Date] date NULL, 
	[Sales Order Header Creation Fiscal Year] int NULL, 
	[Sales Order Header Creation Fiscal Period] int NULL, 
	[Sales Order Header Creation Fiscal Period Code] varchar(max) NULL, 
	[Sales Order Header Creation Calendar Quarter] int NULL, 
	[Sales Order Header Creation Fiscal Quarter Code] varchar(max) NULL, 
	[Sales Order Header Creation Calendar Year] int NULL, 
	[Sales Order Header Creation Calendar Month Number] int NULL, 
	[Sales Order Header Creation Calendar Month Code] varchar(max) NULL, 
	[Sales Order Header Creation Calendar Month Desc] varchar(max) NULL, 
	[CLNDR_QTR_NUM] int NULL, 
	[Sales Order Header Creation Calendar Quarter Code] varchar(max) NULL, 
	[Sales Order Header Creation Calendar Weekday Number] int NULL, 
	[Sales Order Header Creation Calendar Weekday Name] varchar(max) NULL, 
	[Sales Order Header Creation Calendar Day in Month] int NULL, 
	[Sales Order Header Creation Calendar Day in Year] int NULL, 
	[Sales Order Header Creation Calendar Week] int NULL, 
	[Sales Order Header Creation Calendar Month in Quarter Number] int NULL, 
	[Sales Order Header Creation Calendar Days in Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Sales Order Header Creation Current Day Flag] int NULL, 
	[Sales Order Header Creation Current Day Minus 1 Flag] int NULL, 
	[Sales Order Header Creation Current Calendar Week Flag] int NULL, 
	[Sales Order Header Creation Current Calendar Week Minus 1 Flag] int NULL, 
	[Sales Order Header Creation Current Month Flag] int NULL, 
	[Sales Order Header Creation Current Month Minus 1 Flag] int NULL, 
	[Sales Order Header Creation Current Month Minus 12 Flag] int NULL, 
	[Sales Order Header Creation Current Quarter Flag] int NULL, 
	[Sales Order Header Creation Current Quarter Minus 1 Flag] int NULL, 
	[Sales Order Header Creation Current Quarter Minus 4 Flag] int NULL, 
	[Sales Order Header Creation Current Calendar Year Flag] int NULL, 
	[Sales Order Header Creation Current Calendar Year Minus 1 Flag] int NULL, 
	[Sales Order Header Creation Current Calendar Year Minus 2 Flag] int NULL, 
	[Sales Order Header Creation Current Fiscal Year Flag] int NULL, 
	[Sales Order Header Creation Current Fiscal Year Minus 1 Flag] int NULL, 
	[Sales Order Header Creation Current Fiscal Year Minus 2 Flag] int NULL, 
	[Sales Order Header Creation Current Calendar Year Plus 1 Flag] int NULL, 
	[Sales Order Header Creation Current Fiscal Year Plus 1 Flag] int NULL, 
	[Sales Order Header Creation Day In Fiscal Year] int NULL, 
	[IS_WEEKDAY] int NULL, 
	[FISCAL_WK] int NULL, 
	[Sales Order Header Creation Current Fiscal Week Flag] int NULL, 
	[Sales Order Header Creation Current Fiscal Week Minus 1 Flag] int NULL, 
	[Sales Order Header Creation Fiscal Weekday Number] int NULL, 
	[Sales Order Header Creation Fiscal Weekday Name] varchar(max) NULL, 
	[CURR_MNTH_MINUS_2_FLG] int NULL, 
	[Sales Order Header Creation Current Fiscal Week Minus 2 Flag] int NULL, 
	[Sales Order Header Creation Current Fiscal Week Minus 6 Flag] int NULL, 
	[Sales Order Header Creation Current Fiscal Week Minus 3 Flag] int NULL, 
	[Sales Order Header Creation Current Fiscal Week Minus 4 Flag] int NULL, 
	[Sales Order Header Creation Current Fiscal Week Minus 5 Flag] int NULL, 
	[Sales Order Header Creation Current Fiscal Week Minus 7 Flag] int NULL
);