CREATE TABLE [Propelis].[SALES_PERSON_PERSONEL] (

	[PERSONEL_KEY] int NOT NULL, 
	[Personnel Number] varchar(max) NULL, 
	[Company Code] varchar(max) NULL, 
	[Plant ID] varchar(max) NULL, 
	[Cost Center ID] varchar(max) NULL, 
	[Success Factors ID] varchar(max) NULL, 
	[Employee First Name] varchar(max) NULL, 
	[Employee Last Name] varchar(max) NULL, 
	[Employee Full Name] varchar(max) NULL, 
	[Employee Status lndicator] varchar(max) NULL, 
	[Employment Start Date] date NULL, 
	[Employment End Date] date NULL, 
	[Employee Group Id] varchar(max) NULL, 
	[Employee Group Description] varchar(max) NULL, 
	[Employee Subgroup ID] varchar(max) NULL, 
	[Employee Subgroup Description] varchar(max) NULL, 
	[Employee Telephone 1] varchar(max) NULL, 
	[Employee Telephone 2] varchar(max) NULL, 
	[Email Address] varchar(max) NULL, 
	[Created Date] date NULL, 
	[Created User ID] varchar(max) NULL, 
	[Updated Date] date NULL, 
	[Updated User ID] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Company Description] varchar(max) NULL, 
	[Plant Description] varchar(max) NULL
);