CREATE TABLE [Propelis].[SALES_REP] (

	[PERSONEL_KEY] int NOT NULL, 
	[Sales Rep Personnel Number] varchar(max) NULL, 
	[Sales Rep Company Code] varchar(max) NULL, 
	[Sales Rep Plant ID] varchar(max) NULL, 
	[Sales Rep Cost Center ID] varchar(max) NULL, 
	[Sales Rep Success Factors ID] varchar(max) NULL, 
	[Sales Rep Employee First Name] varchar(max) NULL, 
	[Sales Rep Employee Last Name] varchar(max) NULL, 
	[Sales Rep Employee Full Name] varchar(max) NULL, 
	[Sales Rep Employee Status Indicator] varchar(max) NULL, 
	[Sales Rep Employment Start Date] date NULL, 
	[Sales Rep Employment End Date] date NULL, 
	[Sales Rep Employee Group ID] varchar(max) NULL, 
	[Sales Rep Employee Group Description] varchar(max) NULL, 
	[Sales Rep Employee Subgroup ID] varchar(max) NULL, 
	[Sales Rep Employee Subgroup Description] varchar(max) NULL, 
	[Sales Rep Employee Telephone 1] varchar(max) NULL, 
	[Sales Rep Employee Telephone 2] varchar(max) NULL, 
	[Sales Rep Email Address] varchar(max) NULL, 
	[Sales Rep Created Date] date NULL, 
	[Sales Rep Created User ID] varchar(max) NULL, 
	[Sales Rep Updated Date] date NULL, 
	[Sales Rep Updated User ID] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Sales Rep Company Description] varchar(max) NULL, 
	[Sales Rep Plant Description] varchar(max) NULL
);