CREATE TABLE [Propelis].[Schawk_PLANT] (

	[PLNT_KEY] int NOT NULL, 
	[Schawk Plant ID] varchar(max) NULL, 
	[Schawk Legacy Plant ID] varchar(max) NULL, 
	[Schawk Plant Name] varchar(max) NULL, 
	[Schawk Plant Company Code] varchar(max) NULL, 
	[Schawk Plant Sales Organization] varchar(max) NULL, 
	[Schawk Plant Purchasing Organization] varchar(max) NULL, 
	[Schawk Plant Valuation Area] varchar(max) NULL, 
	[Schawk Plant Customer Number Of Plant] varchar(max) NULL, 
	[Schawk Plant Vendor Number Of Plant] varchar(max) NULL, 
	[Plant Factory Calendar Key] varchar(max) NULL, 
	[Schawk Plant Line 1 Description] varchar(max) NULL, 
	[Schawk Plant Line 2 Description] varchar(max) NULL, 
	[Schawk Plant City Name] varchar(max) NULL, 
	[Schawk Plant Zip Code] varchar(max) NULL, 
	[Schawk Plant Country Code] varchar(max) NULL, 
	[Schawk Plant Country Name] varchar(max) NULL, 
	[Schawk Plant Tax Jurisdiction] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Schawk Plant Is P001] varchar(max) NULL, 
	[Schawk Plant Is P002] varchar(max) NULL, 
	[Schawk Plant Company Description] varchar(max) NULL, 
	[Schawk Plant Sales Organization Description] varchar(max) NULL, 
	[Schawk Plant Factory Calendar Description] varchar(max) NULL, 
	[Schawk Plant Purchasing Organization Description] varchar(max) NULL, 
	[Schawk Plant Tax Indicator] varchar(max) NULL, 
	[Schawk Plant Tax Indicator Description] varchar(max) NULL, 
	[Schawk Plant Shipping Receiving Point] varchar(max) NULL, 
	[Schawk Plant Shipping Receiving Point Description] varchar(max) NULL
);