CREATE TABLE [Propelis].[SCHLD_RELEASE_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Schld Release Date] date NULL, 
	[Schld Release Fiscal Year] int NULL, 
	[Schld Release Fiscal Period Number] int NULL, 
	[Schld Release Fiscal Period Code] varchar(max) NULL, 
	[Schld Release Fiscal Quarter Number] int NULL, 
	[Schld Release Fiscal Quarter Code] varchar(max) NULL, 
	[Schld Release Calendar Year] int NULL, 
	[Schld Release Calendar Month Number] int NULL, 
	[Schld Release Calendar Month Code] varchar(max) NULL, 
	[Schld Release Calendar Month Description] varchar(max) NULL, 
	[Schld Release Calendar Quarter Number] int NULL, 
	[Schld Release Calendar Quarter Code] varchar(max) NULL, 
	[Schld Release Calendar Weekday Number] int NULL, 
	[Schld Release Calendar Weekday Name] varchar(max) NULL, 
	[Schld Release Calendar Day In Month] int NULL, 
	[Schld Release Calendar Day In Year] int NULL, 
	[Schld Release Calendar Week] int NULL, 
	[Schld Release Calendar Month In Quarter Number] int NULL, 
	[Schld Release Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Schld Release Current Day Flag] int NULL, 
	[Schld Release Current Day Minus 1 Flag] int NULL, 
	[Schld Release Current Calendar Week Flag] int NULL, 
	[Schld Release Current Calendar Week Minus 1 Flag] int NULL, 
	[Schld Release Current Month Flag] int NULL, 
	[Schld Release Current Month Minus 1 Flag] int NULL, 
	[Schld Release Current Month Minus 12 Flag] int NULL, 
	[Schld Release Current Quarter Flag] int NULL, 
	[Schld Release Current Quarter Minus 1 Flag] int NULL, 
	[Schld Release Current Quarter Minus 4 Flag] int NULL, 
	[Schld Release Current Calendar Year Flag] int NULL, 
	[Schld Release Current Calendar Year Minus 1 Flag] int NULL, 
	[Schld Release Current Calendar Year Minus 2 Flag] int NULL, 
	[Schld Release Current Fiscal Year Flag] int NULL, 
	[Schld Release Current Fiscal Year Minus 1 Flag] int NULL, 
	[Schld Release Current Fiscal Year Minus 2 Flag] int NULL, 
	[Schld Release Current Calendar Year Plus 1 Flag] int NULL, 
	[CURR_FISCAL_YR_PLUS_1_FLG] int NULL, 
	[Schld Release Day In Fiscal Year] int NULL, 
	[Schld Release Date Is Weekday] int NULL, 
	[Schld Release Fiscal Week] int NULL, 
	[Schld Release Current Fiscal Week Flag] int NULL, 
	[Schld Release Current Fiscal Week Minus 1 Flag] int NULL, 
	[Schld Release Fiscal Weekday Number] int NULL, 
	[Schld Release Fiscal Weekday Name] varchar(max) NULL, 
	[Schld Release Current Month Minus 2 Flag] int NULL, 
	[Schld Release Current Fiscal Week Minus 2 Flag] int NULL, 
	[Schld Release Current Fiscal Week Minus 6 Flag] int NULL, 
	[Schld Release Current Fiscal Week Minus 3 Flag] int NULL, 
	[Schld Release Current Fiscal Week Minus 4 Flag] int NULL, 
	[Schld Release Current Fiscal Week Minus 5 Flag] int NULL, 
	[Schld Release Current Fiscal Week Minus 7 Flag] int NULL
);