CREATE TABLE [Propelis].[SCHL_ITM_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Schedule Item Date] date NULL, 
	[Schedule Item Fiscal Year] int NULL, 
	[Schedule Item Fiscal Period] int NULL, 
	[Schedule Item Fiscal Period Code] varchar(max) NULL, 
	[Schedule Item Fiscal Quarter Number] int NULL, 
	[Schedule Item Fiscal Quarter Code] varchar(max) NULL, 
	[Schedule Item Calendar Year] int NULL, 
	[Schedule Item Calendar Month Number] int NULL, 
	[Schedule Item Calendar Month Code] varchar(max) NULL, 
	[Schedule Item Calendar Month Desc] varchar(max) NULL, 
	[Schedule Item Calendar Quarter] int NULL, 
	[Schedule Item Calendar Quarter Code] varchar(max) NULL, 
	[Schedule Item Calendar Weekday Number] int NULL, 
	[Schedule Item Calendar Weekday Name] varchar(max) NULL, 
	[Schdl Item Calendar Day in Month] int NULL, 
	[Schedule Item Calendar Day in Year] int NULL, 
	[Schedule Item Calendar Week] int NULL, 
	[Schedule Item Calendar Month in Quarter Number] int NULL, 
	[Schedule Item Calendar Days in Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Schld Item Current Day Flag] int NULL, 
	[Schld Item Current Day Minus 1 Flag] int NULL, 
	[Schld Item Current Calendar Week Flag] int NULL, 
	[Schld Item Current Calendar Week Minus 1 Flag] int NULL, 
	[Schld Item Current Month Flag] int NULL, 
	[Schld Item Current Month Minus 1 Flag] int NULL, 
	[Schld Item Current Month Minus 12 Flag] int NULL, 
	[Schld Item Current Quarter Flag] int NULL, 
	[Schld Item Current Quarter Minus 1 Flag] int NULL, 
	[Schld Item Current Quarter Minus 4 Flag] int NULL, 
	[Schld Item Current Calendar Year Flag] int NULL, 
	[Schld Item Current Calendar Year Minus 1 Flag] int NULL, 
	[Schld Item Current Calendar Year Minus 2 Flag] int NULL, 
	[Schld Item Current Fiscal Year Flag] int NULL, 
	[Schld Item Current Fiscal Year Minus 1 Flag] int NULL, 
	[Schld Item Current Fiscal Year Minus 2 Flag] int NULL, 
	[Schld Item Current Calendar Year Plus 1 Flag] int NULL, 
	[Schld Item Current Fiscal Year Plus 1 Flag] int NULL, 
	[Schedule Item Day In Fiscal Year] int NULL, 
	[Schld Item Date Is Weekday] int NULL, 
	[Schedule Item Fiscal Week] int NULL, 
	[Schld Item Current Fiscal Week Flag] int NULL, 
	[Schld Item Current Fiscal Week Minus 1 Flag] int NULL, 
	[Schedule Item Fiscal Weekday Number] int NULL, 
	[Schedule Item Fiscal Weekday Name] varchar(max) NULL, 
	[Schld Item Current Month Minus 2 Flag] int NULL, 
	[Schld Item Current Fiscal Week Minus 2 Flag] int NULL, 
	[Schld Item Current Fiscal Week Minus 6 Flag] int NULL, 
	[Schld Item Current Fiscal Week Minus 3 Flag] int NULL, 
	[Schld Item Current Fiscal Week Minus 4 Flag] int NULL, 
	[Schld Item Current Fiscal Week Minus 5 Flag] int NULL, 
	[Schld Item Current Fiscal Week Minus 7 Flag] int NULL
);