CREATE TABLE [Propelis].[SERV_ORDER_INVOICE_CREATED_DATE] (

	[DATE_KEY] int NOT NULL, 
	[THE_DATE] date NULL, 
	[Service Order Created Fiscal Year] int NULL, 
	[FISCAL_PER_NUM] int NULL, 
	[Service Order Created Fiscal Period Code] varchar(max) NULL, 
	[Service Order Created Fiscal Quarter Number] int NULL, 
	[Service Order Created Fiscal Quarter Code] varchar(max) NULL, 
	[Service Order Created Calendar Year] int NULL, 
	[Service Order Created Calendar Month Number] int NULL, 
	[Service Order Created Calendar Month Code] varchar(max) NULL, 
	[Service Order Created Calendar Month Desc] varchar(max) NULL, 
	[CLNDR_QTR_NUM] int NULL, 
	[Service Order Created Calendar Quarter Code] varchar(max) NULL, 
	[Service Order Created Calendar Weekday Number] int NULL, 
	[Service Order Created Calendar Weekday Name] varchar(max) NULL, 
	[Service Order Created Calendar Day in Month] int NULL, 
	[Service Order Created Calendar Day in Year] int NULL, 
	[Service Order Created Calendar Week] int NULL, 
	[Service Order Created Calendar Month in Quarter Number] int NULL, 
	[Service Order Created Calendar Days in Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Service Order Created Current Day Flag] int NULL, 
	[Service Order Created Current Day Minus 1 Flag] int NULL, 
	[Service Order Created Current Calendar Week Flag] int NULL, 
	[Service Order Created Current Calendar Week Minus 1 Flag] int NULL, 
	[Service Order Created Current Month Flag] int NULL, 
	[Service Order Created Current Month Minus 1 Flag] int NULL, 
	[Service Order Created Current Month Minus 12 Flag] int NULL, 
	[Service Order Created Current Quarter Flag] int NULL, 
	[Service Order Created Current Quarter Minus 1 Flag] int NULL, 
	[Service Order Created Current Quarter Minus 4 Flag] int NULL, 
	[Service Order Created Current Calendar Year Flag] int NULL, 
	[Service Order Created Current Calendar Year Minus 1 Flag] int NULL, 
	[Service Order Created Current Calendar Year Minus 2 Flag] int NULL, 
	[Service Order Created Current Fiscal Year Flag] int NULL, 
	[Service Order Created Current Fiscal Year Minus 1 Flag] int NULL, 
	[Service Order Created Current Fiscal Year Minus 2 Flag] int NULL, 
	[Service Order Created Current Calendar Year Plus 1 Flag] int NULL, 
	[Service Order Created Current Fiscal Year Plus 1 Flag] int NULL, 
	[Service Order Created Day in Fiscal Year] int NULL, 
	[Service Order Created Date Is Weekday] int NULL, 
	[Service Order Fiscal Week] int NULL, 
	[Service Order Current Fiscal Week Flag] int NULL, 
	[Service Order Current Fiscal Week Minus 1 Flag] int NULL, 
	[Service Order Fiscal Weekday Number] int NULL, 
	[Service Order Fiscal Weekday Name] varchar(max) NULL, 
	[CURR_MNTH_MINUS_2_FLG] int NULL, 
	[Service Order Current Fiscal Week Minus 2 Flag] int NULL, 
	[Service Order Current Fiscal Week Minus 6 Flag] int NULL, 
	[Service Order Current Fiscal Week Minus 3 Flag] int NULL, 
	[Service Order Current Fiscal Week Minus 4 Flag] int NULL, 
	[Service Order Current Fiscal Week Minus 5 Flag] int NULL, 
	[Service Order Current Fiscal Week Minus 7 Flag] int NULL
);