CREATE TABLE [Propelis].[SITE] (

	[PLNT_KEY] int NOT NULL, 
	[Site ID] varchar(max) NULL, 
	[Site Legacy Plant ID] varchar(max) NULL, 
	[Site Name] varchar(max) NULL, 
	[Site Company Code] varchar(max) NULL, 
	[Site Sales Organization] varchar(max) NULL, 
	[Site Purchasing Organization] varchar(max) NULL, 
	[Site Valuation Area] varchar(max) NULL, 
	[Site Customer Number Of Plant] varchar(max) NULL, 
	[Site Vendor Number Of Plant] varchar(max) NULL, 
	[Site Factory Calendar Key] varchar(max) NULL, 
	[Site Line 1 Description] varchar(max) NULL, 
	[Site Line 2 Description] varchar(max) NULL, 
	[Site City Name] varchar(max) NULL, 
	[Site Zip Code] varchar(max) NULL, 
	[Site Country Code] varchar(max) NULL, 
	[Site Country Name] varchar(max) NULL, 
	[Site Tax Jurisdiction] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Site Is P001] varchar(max) NULL, 
	[Site Is P002] varchar(max) NULL, 
	[Site Company Description] varchar(max) NULL, 
	[Site Sales Organization Description] varchar(max) NULL, 
	[Site Factory Calendar Description] varchar(max) NULL, 
	[Site Purchasing Organization Description] varchar(max) NULL, 
	[Site Tax Indicator] varchar(max) NULL, 
	[Site Tax Indicator Description] varchar(max) NULL, 
	[Site Shipping Receiving Point] varchar(max) NULL, 
	[Site Shipping Receiving Point Description] varchar(max) NULL
);