CREATE TABLE [Propelis].[SO_PARENT_CUST] (

	[CUST_KEY] int NOT NULL, 
	[SO Parent Customer ID] varchar(max) NOT NULL, 
	[SO Parent Legacy Customer ID] varchar(max) NULL, 
	[SO Parent Customer Name] varchar(max) NULL, 
	[SO Parent Cust Line 2 Description] varchar(max) NULL, 
	[SO Parent Cust Country Code] varchar(max) NULL, 
	[SO Parent Cust Plant ID] varchar(max) NULL, 
	[SO Parent Cust Segment ID] varchar(max) NULL, 
	[SO Parent Cust Industry] varchar(max) NULL, 
	[SO Parent Cust Vendor ID] varchar(max) NULL, 
	[SO Parent Cust Group Code] varchar(max) NULL, 
	[SO Parent Cust Account Group Code] varchar(max) NULL, 
	[SO Parent Cust Title] varchar(max) NULL, 
	[SO Parent Cust Search Term] varchar(max) NULL, 
	[SO Parent Cust Street] varchar(max) NULL, 
	[SO Parent Cust City] varchar(max) NULL, 
	[SO Parent Cust Zip Code] varchar(max) NULL, 
	[SO Parent Cust State Code] varchar(max) NULL, 
	[SO Parent Cust Region Code] varchar(max) NULL, 
	[SO Parent Cust Telephone Number 1] varchar(max) NULL, 
	[SO Parent Cust Telephone Number 2] varchar(max) NULL, 
	[SO Parent Cust Fax Number Code] varchar(max) NULL, 
	[SO Parent Cust Tax Number 1 Code] varchar(max) NULL, 
	[SO Parent Cust Tax Number 2 Code] varchar(max) NULL, 
	[SO Parent Cust VAT Number Code] varchar(max) NULL, 
	[SO Parent Cust Credit Limit] decimal(15,3) NULL, 
	[SO Parent Cust Bonus Rate] decimal(9,3) NULL, 
	[SO Parent Cust Express Station] varchar(max) NULL, 
	[SO Parent Cust Transportation Zone] varchar(max) NULL, 
	[SO Parent Cust Printer Location Characteristics] varchar(max) NULL, 
	[SO Parent Cust Printer Region Characteristics] varchar(max) NULL, 
	[SO Parent Cust Printer Site Characteristics] varchar(max) NULL, 
	[SO Parent Cust Created Date] date NULL, 
	[SO Parent Cust Created User ID] varchar(max) NULL, 
	[SO Parent Cust Updated Date] date NULL, 
	[SO Parent Cust Updated User ID] varchar(max) NULL, 
	[SO Parent Cust Payment Terms Code] varchar(max) NULL, 
	[SO Parent Cust Sales Distribution] varchar(max) NULL, 
	[SO Parent Cust Order Block For Sales Area] varchar(max) NULL, 
	[SO Parent Cust Delivery Block For Sales Area] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[SO Parent Cust Corporate Group] varchar(max) NULL, 
	[SO Parent Cust Customer Classification] varchar(max) NULL, 
	[SO Parent Cust Classification Description] varchar(max) NULL, 
	[SO Parent Cust Printer Location] varchar(max) NULL, 
	[SO Parent Cust Printer Site] varchar(max) NULL, 
	[SO Parent Cust Printer Region] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 01] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 02] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 03] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 04] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 05] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 06] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 07] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 08] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 09] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 10] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 11] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 12] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 13] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 14] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 15] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 16] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 17] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 18] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 19] varchar(max) NULL, 
	[SO Parent Cust Specific Field Label 20] varchar(max) NULL, 
	[SO Parent Cust Condition Group 1] varchar(max) NULL, 
	[SO Parent Cust Industry Code 1] varchar(max) NULL, 
	[SO Parent Cust Industry Code 2] varchar(max) NULL, 
	[SO Parent Cust Industry Description] varchar(max) NULL, 
	[SO Parent Cust Industry Code 1 Description] varchar(max) NULL, 
	[SO Parent Cust Industry Code 2 Description] varchar(max) NULL, 
	[SO Parent Cust Assignment to Hierarchy] int NULL, 
	[SO Parent Cust Account Group Description] varchar(max) NULL, 
	[SO Parent Cust Region Description] varchar(max) NULL, 
	[SO Parent Cust Country Description] varchar(max) NULL, 
	[SO Parent Cust Transportation Zone Description] varchar(max) NULL, 
	[SO Parent Cust Plant Description] varchar(max) NULL, 
	[SO Parent Cust Condition Group Description] varchar(max) NULL, 
	[SO Parent Cust Cental Billing Block] varchar(max) NULL, 
	[SO Parent Cust Cental Billing Block Description] varchar(max) NULL, 
	[SO Parent Cust Central Delivery Block] varchar(max) NULL, 
	[SO Parent Cust Central Delivery Block Description] varchar(max) NULL, 
	[SO Parent Cust Deletion Indicator] varchar(max) NULL, 
	[SO Parent Cust Central Posting Block] varchar(max) NULL, 
	[SO Parent Cust Tax Jurisdiction] varchar(max) NULL, 
	[SO Parent Cust Central Sales Block] varchar(max) NULL, 
	[SO Parent Cust Central Deletion Indicator] varchar(max) NULL, 
	[SO Parent Cust Language Key] varchar(max) NULL, 
	[SO Parent Cust Trading Partner] varchar(max) NULL, 
	[SO Parent Cust Trading Partner Description] varchar(max) NULL, 
	[SO Parent Cust Annual Sales] decimal(8,2) NULL, 
	[SO Parent Cust Annual Sales Year] int NULL, 
	[SO Parent Cust Sales Currency] varchar(max) NULL, 
	[SO Parent Cust Sales Currency Description] varchar(max) NULL, 
	[SO Parent Cust One Time Account Group] varchar(max) NULL, 
	[SO Parent Cust One Time Account Group Description] varchar(max) NULL, 
	[SO Parent Cust One Time Indicator] varchar(max) NULL, 
	[SO Parent Cust Industry Type] varchar(max) NULL, 
	[SO Parent Cust Business Type] varchar(max) NULL, 
	[SO Parent Cust DUNS Number] varchar(max) NULL, 
	[SO Parent Cust DUNS Plus 4] varchar(max) NULL, 
	[SO Parent Cust City Coordinates] varchar(max) NULL, 
	[SO Parent Cust Tax Number 4 Code] varchar(max) NULL, 
	[SO Parent Cust Attribute 3] varchar(max) NULL, 
	[SO Parent Cust Attribute 3 Description] varchar(max) NULL, 
	[SO Parent Cust E-Mail Address] varchar(max) NULL, 
	[SO Parent Cust Mobile Number] varchar(max) NULL, 
	[SO Parent Cust Search Term 2] varchar(max) NULL, 
	[SO Parent Cust Street 2] varchar(max) NULL, 
	[SO Parent Cust Street 3] varchar(max) NULL, 
	[SO Parent Cust Street 4] varchar(max) NULL, 
	[SO Parent Cust Street 5] varchar(max) NULL, 
	[SO Parent Cust PO Box] varchar(max) NULL, 
	[SO Parent Cust PO Box Postal Code] varchar(max) NULL, 
	[SO Parent Cust PO Box City] varchar(max) NULL, 
	[SO Parent Cust Region For PO Box] varchar(max) NULL, 
	[SO Parent Cust PO Box Country] varchar(max) NULL, 
	[SO Parent Cust Transport Zone] varchar(max) NULL, 
	[SO Parent Cust Address Notes] varchar(max) NULL, 
	[SO Parent Cust Tax Number 3 Code] varchar(max) NULL, 
	[SO Parent Cust Tax Number 5 Code] varchar(max) NULL, 
	[SO Parent Cust Industry Code 3] varchar(max) NULL, 
	[SO Parent Cust Industry Code 3 Description] varchar(max) NULL, 
	[SO Parent Cust Industry Code 4] varchar(max) NULL, 
	[SO Parent Cust Industry Code 4 Description] varchar(max) NULL, 
	[SO Parent Cust Industry Code 5] varchar(max) NULL, 
	[SO Parent Cust Industry Code 5 Description] varchar(max) NULL, 
	[SO Parent Cust Central Order Block For Customer] varchar(max) NULL, 
	[SO Parent Cust Payment Block] varchar(max) NULL
);