CREATE TABLE [Propelis].[SOLD_TO_PARTY] (

	[CUST_KEY] int NOT NULL, 
	[Sold To Party ID] varchar(max) NULL, 
	[Sold To Party Legacy Customer ID] varchar(max) NULL, 
	[Sold To Party Name] varchar(max) NULL, 
	[Sold To Party Customer Line 2 Description] varchar(max) NULL, 
	[Sold To Party Country Code] varchar(max) NULL, 
	[Sold To Party Plant ID] varchar(max) NULL, 
	[Sold To Party Segment ID] varchar(max) NULL, 
	[Sold To Party Industry] varchar(max) NULL, 
	[Sold To Party Vendor ID] varchar(max) NULL, 
	[Sold To Party Group Code] varchar(max) NULL, 
	[Sold To Party Account Group Code] varchar(max) NULL, 
	[Sold To Party Title] varchar(max) NULL, 
	[Sold To Party Search Term] varchar(max) NULL, 
	[Sold To Party Street] varchar(max) NULL, 
	[Sold To Party City Name] varchar(max) NULL, 
	[Sold To Party Zip Code] varchar(max) NULL, 
	[Sold To Party Street Code] varchar(max) NULL, 
	[Sold To Party Region Code] varchar(max) NULL, 
	[Sold To Party Telephone Number 1 Code] varchar(max) NULL, 
	[Sold To Party Telephone Number 2 Code] varchar(max) NULL, 
	[Sold To Party Fax Number Code] varchar(max) NULL, 
	[Sold To Party Tax Number 1 Code] varchar(max) NULL, 
	[Sold To Party Tax Number 2 Code] varchar(max) NULL, 
	[Sold To Party VAT Number Code] varchar(max) NULL, 
	[Sold To Party Credit Limit] decimal(15,3) NULL, 
	[Sold To Party Bonus Rate] decimal(9,3) NULL, 
	[Sold To Party Express Station] varchar(max) NULL, 
	[Sold To Party Transportation Zone] varchar(max) NULL, 
	[Sold To Party Printer Location Chars] varchar(max) NULL, 
	[Sold To Party Printer Region Chars] varchar(max) NULL, 
	[Sold To Party Printer Site Chars] varchar(max) NULL, 
	[Sold To Party Created Date] date NULL, 
	[Sold To Party Created User ID] varchar(max) NULL, 
	[Sold To Party Updated Date] date NULL, 
	[Sold To Party Updated User ID] varchar(max) NULL, 
	[Sold To Party Payment Terms Code] varchar(max) NULL, 
	[Sold To Party Sales District] varchar(max) NULL, 
	[Sold To Party Order Block For Sales Area] varchar(max) NULL, 
	[Sold To Party Delivery Block For Sales Area] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Sold To Party Corporate Group] varchar(max) NULL, 
	[Sold To Party Customer Classification] varchar(max) NULL, 
	[Sold To Party Customer Classification Description] varchar(max) NULL, 
	[Sold To Party Printer Location] varchar(max) NULL, 
	[Sold To Party Printer Site] varchar(max) NULL, 
	[Sold To Party Printer Region] varchar(max) NULL, 
	[Sold To Party Specific Field Label 01] varchar(max) NULL, 
	[Sold To Party Specific Field Label 02] varchar(max) NULL, 
	[Sold To Party Specific Field Label 03] varchar(max) NULL, 
	[Sold To Party Specific Field Label 04] varchar(max) NULL, 
	[Sold To Party Specific Field Label 05] varchar(max) NULL, 
	[Sold To Party Specific Field Label 06] varchar(max) NULL, 
	[Sold To Party Specific Field Label 07] varchar(max) NULL, 
	[Sold To Party Specific Field Label 08] varchar(max) NULL, 
	[Sold To Party Specific Field Label 09] varchar(max) NULL, 
	[Sold To Party Specific Field Label 10] varchar(max) NULL, 
	[Sold To Party Specific Field Label 11] varchar(max) NULL, 
	[Sold To Party Specific Field Label 12] varchar(max) NULL, 
	[Sold To Party Specific Field Label 13] varchar(max) NULL, 
	[Sold To Party Specific Field Label 14] varchar(max) NULL, 
	[Sold To Party Specific Field Label 15] varchar(max) NULL, 
	[Sold To Party Specific Field Label 16] varchar(max) NULL, 
	[Sold To Party Specific Field Label 17] varchar(max) NULL, 
	[Sold To Party Specific Field Label 18] varchar(max) NULL, 
	[Sold To Party Specific Field Label 19] varchar(max) NULL, 
	[Sold To Party Specific Field Label 20] varchar(max) NULL, 
	[Sold To Party Customer Condition Group 1] varchar(max) NULL, 
	[Sold To Party Industry Code 1] varchar(max) NULL, 
	[Sold To Party Industry Code 2] varchar(max) NULL, 
	[Sold To Party Industry Description] varchar(max) NULL, 
	[Sold To Party Industry Code 1 Description] varchar(max) NULL, 
	[Sold To Party Industry Code 2 Description] varchar(max) NULL, 
	[Sold To Party Assign To Hiercarhy] int NULL, 
	[Sold To Party Account Group Description] varchar(max) NULL, 
	[Sold To Party Region Description] varchar(max) NULL, 
	[Sold To Party Country Description] varchar(max) NULL, 
	[Sold To Party Transportation Zone Description] varchar(max) NULL, 
	[Sold To Party Plant Description] varchar(max) NULL, 
	[Sold To Party Customer Condition Group Description] varchar(max) NULL, 
	[Sold To Party Central Billing Block] varchar(max) NULL, 
	[Sold To Party Central Billing Block Description] varchar(max) NULL, 
	[Sold To Party Central Delivery Block] varchar(max) NULL, 
	[Sold To Party Central Delivery Block Description] varchar(max) NULL, 
	[Sold To Party Deletion Indicator] varchar(max) NULL, 
	[Sold To Party Central Posting Block] varchar(max) NULL, 
	[Sold To Party Tax Jurisdiction] varchar(max) NULL, 
	[Sold To Party Central Sales Block] varchar(max) NULL, 
	[Sold To Party Central Deletion Indicator] varchar(max) NULL, 
	[LANG_KEY] varchar(max) NULL, 
	[Sold To Party Trading Partner] varchar(max) NULL, 
	[Sold To Party Trading Partner Description] varchar(max) NULL, 
	[Sold To Party Annual Sales] decimal(8,2) NULL, 
	[Sold To Party Annual Sales Year] int NULL, 
	[Sold To Party Sales Currency] varchar(max) NULL, 
	[Sold To Party Sales Currency Description] varchar(max) NULL, 
	[Sold To Party One Time Customer Acct Group] varchar(max) NULL, 
	[Sold To Party One Time Customer Acct Group Description] varchar(max) NULL, 
	[Sold To Party One Time Customer Indicator] varchar(max) NULL, 
	[Sold To Party Industry Type] varchar(max) NULL, 
	[Sold To Party Business Type] varchar(max) NULL, 
	[Sold To Party DUNS Number] varchar(max) NULL, 
	[Sold To Party DUNS Plus 4] varchar(max) NULL, 
	[Sold To Party City Coordinates] varchar(max) NULL, 
	[Sold To Party Tax Number 4 Code] varchar(max) NULL, 
	[Sold To Party Attribute 3] varchar(max) NULL, 
	[Sold To Party Attribute 3 Description] varchar(max) NULL, 
	[Sold To Party E-Mail Address] varchar(max) NULL, 
	[Sold To Party Mobile Number] varchar(max) NULL, 
	[Sold To Party Search Term 2] varchar(max) NULL, 
	[Sold To Party Street 2] varchar(max) NULL, 
	[Sold To Party Street 3] varchar(max) NULL, 
	[Sold To Party Street 4] varchar(max) NULL, 
	[Sold To Party Street 5] varchar(max) NULL, 
	[Sold To Party PO Box] varchar(max) NULL, 
	[Sold To Party PO Box Postal Code] varchar(max) NULL, 
	[Sold To Party PO Box City] varchar(max) NULL, 
	[Sold To Party Region For PO Box] varchar(max) NULL, 
	[Sold To Party PO Box Country] varchar(max) NULL, 
	[Sold To Party Transport Zone] varchar(max) NULL, 
	[Sold To Party Tax Number 3 Code] varchar(max) NULL, 
	[Sold To Party Tax Number 5 Code] varchar(max) NULL, 
	[Sold To Party Industry Code 3] varchar(max) NULL, 
	[Sold To Party Industry Code 3 Description] varchar(max) NULL, 
	[Sold To Party Industry Code 4] varchar(max) NULL, 
	[Sold To Party Industry Code 4 Description] varchar(max) NULL, 
	[Sold To Party Industry Code 5] varchar(max) NULL, 
	[Sold To Party Industry Code 5 Description] varchar(max) NULL, 
	[Sold To Party Central Order Block For Customer] varchar(max) NULL, 
	[Sold To Party Payment Block] varchar(max) NULL, 
	[Sold To Party Address Notes] varchar(max) NULL
);