CREATE TABLE [Propelis].[SPECIAL_STOCK_PARTNER] (

	[CUST_KEY] int NOT NULL, 
	[Special Stock Partner ID] varchar(max) NULL, 
	[Special Stock Partner Legacy Customer ID] varchar(max) NULL, 
	[Special Stock Partner Name] varchar(max) NULL, 
	[Special Stock Partner Line 2 Description] varchar(max) NULL, 
	[Special Stock Partner Country Code] varchar(max) NULL, 
	[Special Stock Partner Plant ID] varchar(max) NULL, 
	[Special Stock Partner Segment ID] varchar(max) NULL, 
	[Special Stock Partner Industry] varchar(max) NULL, 
	[Special Stock Partner Vendor ID] varchar(max) NULL, 
	[Special Stock Partner Customer Group Code] varchar(max) NULL, 
	[Special Stock Partner Account Group Code] varchar(max) NULL, 
	[Special Stock Partner Title] varchar(max) NULL, 
	[Special Stock Partner Search Term] varchar(max) NULL, 
	[Special Stock Partner Street] varchar(max) NULL, 
	[Special Stock Partner City] varchar(max) NULL, 
	[Special Stock Partner Zip Code] varchar(max) NULL, 
	[Special Stock Partner State Code] varchar(max) NULL, 
	[Special Stock Partner Region Code] varchar(max) NULL, 
	[Special Stock Partner Telephone Number 1] varchar(max) NULL, 
	[Special Stock Partner Telephone Number 2] varchar(max) NULL, 
	[Special Stock Partner Fax Number Code] varchar(max) NULL, 
	[Special Stock Partner Tax Number 1 Code] varchar(max) NULL, 
	[Special Stock Partner Tax Number 2 Code] varchar(max) NULL, 
	[Special Stock Partner VAT Number Code] varchar(max) NULL, 
	[Special Stock Partner Credit Limit] decimal(15,3) NULL, 
	[Special Stock Partner Bonus Rate] decimal(9,3) NULL, 
	[Special Stock Partner Express Station] varchar(max) NULL, 
	[Special Stock Partner Transportation Zone] varchar(max) NULL, 
	[Special Stock Partner Printer Location Characteristics] varchar(max) NULL, 
	[Special Stock Partner Printer Region Characteristics] varchar(max) NULL, 
	[Special Stock Partner Printer Site Characteristics] varchar(max) NULL, 
	[Special Stock Partner Customer Created Date] date NULL, 
	[Special Stock Partner Created User ID] varchar(max) NULL, 
	[Special Stock Partner Customer Updated Date] date NULL, 
	[Special Stock Partner Updated User ID] varchar(max) NULL, 
	[Special Stock Partner Payment Terms Code] varchar(max) NULL, 
	[Special Stock Partner Sales Distribution] varchar(max) NULL, 
	[Special Stock Partner Order Block For Sales Area] varchar(max) NULL, 
	[Special Stock Partner Delivery Block For Sales Area] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Special Stock Partner Corporate Group] varchar(max) NULL, 
	[Special Stock Partner Classification] varchar(max) NULL, 
	[Special Stock Partner Classification Description] varchar(max) NULL, 
	[Special Stock Partner Printer Location] varchar(max) NULL, 
	[Special Stock Partner Printer Site] varchar(max) NULL, 
	[Special Stock Partner Printer Region] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 01] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 02] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 03] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 04] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 05] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 06] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 07] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 08] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 09] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 10] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 11] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 12] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 13] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 14] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 15] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 16] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 17] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 18] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 19] varchar(max) NULL, 
	[Special Stock Partner Specific Field Label 20] varchar(max) NULL, 
	[Special Stock Partner Condition Group 1] varchar(max) NULL, 
	[Special Stock Partner Industry Code 1] varchar(max) NULL, 
	[Special Stock Partner Industry Code 2] varchar(max) NULL, 
	[Special Stock Partner Industry Description] varchar(max) NULL, 
	[Special Stock Partner Industry Code 1 Description] varchar(max) NULL, 
	[Special Stock Partner Industry Code 2 Description] varchar(max) NULL, 
	[Special Stock Partner Assignment to Hierarchy] int NULL, 
	[Special Stock Partner Account Group Description] varchar(max) NULL, 
	[Special Stock Partner Region Description] varchar(max) NULL, 
	[Special Stock Partner Country Description] varchar(max) NULL, 
	[Special Stock Partner Transportation Zone Description] varchar(max) NULL, 
	[Special Stock Partner Plant Description] varchar(max) NULL, 
	[Special Stock Partner Condition Group Description] varchar(max) NULL, 
	[Special Stock Partner Cental Billing Block] varchar(max) NULL, 
	[Special Stock Partner Cental Billing Block Description] varchar(max) NULL, 
	[Special Stock Partner Central Delivery Block] varchar(max) NULL, 
	[Special Stock Partner Central Delivery Block Description] varchar(max) NULL, 
	[Special Stock Partner Deletion Indicator] varchar(max) NULL, 
	[Special Stock Partner Central Posting Block] varchar(max) NULL, 
	[Special Stock Partner Tax Jurisdiction] varchar(max) NULL, 
	[Special Stock Partner Central Sales Block] varchar(max) NULL, 
	[Special Stock Partner Central Deletion Indicator] varchar(max) NULL, 
	[Special Stock Partner Language Key] varchar(max) NULL, 
	[Special Stock Partner Trading Partner] varchar(max) NULL, 
	[Special Stock Partner Trading Partner Description] varchar(max) NULL, 
	[Special Stock Partner Annual Sales] decimal(8,2) NULL, 
	[Special Stock Partner Annual Sales Year] int NULL, 
	[Special Stock Partner Sales Currency] varchar(max) NULL, 
	[Special Stock Partner Sales Currency Description] varchar(max) NULL, 
	[Special Stock Partner One Time Account Group] varchar(max) NULL, 
	[Special Stock Partner One Time Account Group Description] varchar(max) NULL, 
	[Special Stock Partner One Time Indicator] varchar(max) NULL, 
	[Special Stock Partner Industry Type] varchar(max) NULL, 
	[Special Stock Partner Business Type] varchar(max) NULL, 
	[Special Stock Partner DUNS Number] varchar(max) NULL, 
	[Special Stock Partner DUNS Plus 4] varchar(max) NULL, 
	[CITY_COORDINATES] varchar(max) NULL, 
	[TAX_NUM_4_CD] varchar(max) NULL, 
	[ATTRIB_3] varchar(max) NULL, 
	[ATTRIB_3_DESC] varchar(max) NULL, 
	[E_MAIL_ADDR] varchar(max) NULL, 
	[MOBILE_NUM] varchar(max) NULL, 
	[SEARCH_TERM_2] varchar(max) NULL, 
	[STR_2] varchar(max) NULL, 
	[STR_3] varchar(max) NULL, 
	[STR_4] varchar(max) NULL, 
	[STR_5] varchar(max) NULL, 
	[PO_BOX] varchar(max) NULL, 
	[PO_BOX_POSTAL_CD] varchar(max) NULL, 
	[PO_BOX_CITY] varchar(max) NULL, 
	[REGN_FOR_PO_BOX] varchar(max) NULL, 
	[PO_BOX_CNTRY] varchar(max) NULL, 
	[TRNSPRT_ZONE] varchar(max) NULL, 
	[ADDR_NOTES] varchar(max) NULL, 
	[TAX_NUM_3] varchar(max) NULL, 
	[TAX_NUM_5] varchar(max) NULL, 
	[INDUS_CD_3] varchar(max) NULL, 
	[INDUS_CD_3_DESC] varchar(max) NULL, 
	[INDUS_CD_4] varchar(max) NULL, 
	[INDUS_CD_4_DESC] varchar(max) NULL, 
	[INDUS_CD_5] varchar(max) NULL, 
	[INDUS_CD_5_DESC] varchar(max) NULL, 
	[CENTRAL_ORDER_BLK_FOR_CUST] varchar(max) NULL, 
	[PYMT_BLK] varchar(max) NULL
);