CREATE TABLE [Propelis].[Trading_Partner_Company] (

	[CMPNY_KEY] int NOT NULL, 
	[Trading Partner Company Code] varchar(max) NULL, 
	[Legacy Trading Partner Company Code] varchar(max) NULL, 
	[Trading Partner Company Name] varchar(max) NULL, 
	[Trading Partner Company Line Of Business Code] varchar(max) NULL, 
	[Trading Partner Company Line Of Business Description] varchar(max) NULL, 
	[Trading Partner Company Currency Code] varchar(max) NULL, 
	[Trading Partner Company Language Type Code] varchar(max) NULL, 
	[Trading Partner Company Chart Of Accounts ID] varchar(max) NULL, 
	[Trading Partner Company Address Line 1] varchar(max) NULL, 
	[Trading Partner Company Address Line 2] varchar(max) NULL, 
	[Trading Partner Company City Name] varchar(max) NULL, 
	[Trading Partner Company Zip Code] varchar(max) NULL, 
	[Trading Partner Company Country Code] varchar(max) NULL, 
	[Trading Partner Company Telephone 1] varchar(max) NULL, 
	[Trading Partner Company Telephone 2] varchar(max) NULL, 
	[Trading Partner Company Fax Number] varchar(max) NULL, 
	[Trading Partner Company Tax Jurisdiction] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Trading Partner Company Fiscal Year Variant] varchar(max) NULL, 
	[Trading Partner Company Credit Control Area] varchar(max) NULL, 
	[Trading Partner Company Input Tax Code] varchar(max) NULL, 
	[Trading Partner Company Output Tax Code] varchar(max) NULL, 
	[Trading Partner Company Currency Description] varchar(max) NULL, 
	[Trading Partner Company Chart Of Accounts Description] varchar(max) NULL, 
	[Trading Partner Company Country Description] varchar(max) NULL, 
	[Trading Partner Company Fiscal Year Variant Description] varchar(max) NULL, 
	[Trading Partner Company Credit Control Area Description] varchar(max) NULL
);