CREATE TABLE [dbo].[EDW_T_D_MST_MATERIAL_CUR_D] (

	[MATRL_KEY] int NOT NULL, 
	[Material ID] varchar(max) NULL, 
	[Material Description] varchar(max) NULL, 
	[Legacy Material ID] varchar(max) NULL, 
	[Material Customer ID] varchar(max) NULL, 
	[Material Category] varchar(max) NULL, 
	[Material Type] varchar(max) NULL, 
	[Material Group] varchar(max) NULL, 
	[Material Base Unit Of Measure] varchar(max) NULL, 
	[Material Industry Sector] varchar(max) NULL, 
	[Material General Item Category Group] varchar(max) NULL, 
	[Material Unit] varchar(max) NULL, 
	[Material Gross Weight] decimal(13,3) NULL, 
	[Material Net Weight] decimal(13,3) NULL, 
	[Material Product Hierarchy] varchar(max) NULL, 
	[Category of Material] varchar(max) NULL, 
	[Material Brand] varchar(max) NULL, 
	[Material Sub Brand] varchar(max) NULL, 
	[Material Variant Obsolete] varchar(max) NULL, 
	[Material Variant] varchar(max) NULL, 
	[Material Name 1] varchar(max) NULL, 
	[Material Pack Size] varchar(max) NULL, 
	[Material Pack Type] varchar(max) NULL, 
	[Material Country Name] varchar(max) NULL, 
	[Material Print Method] varchar(max) NULL, 
	[Material Level 4 Product Category Code] varchar(max) NULL, 
	[Material Level 4 Product Category Description] varchar(max) NULL, 
	[Material Level 3 Sub Family Code] varchar(max) NULL, 
	[Material Level 3 Sub Family Description] varchar(max) NULL, 
	[Material Level 2 Family Code] varchar(max) NULL, 
	[Material Level 2 Family Description] varchar(max) NULL, 
	[Material Level 1 Class Code] varchar(max) NULL, 
	[Material Level 1 Class Description] varchar(max) NULL, 
	[Material Created Date] date NULL, 
	[Material Created User ID] varchar(max) NULL, 
	[Material Updated Date] date NULL, 
	[Material Updated User ID] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Material Group Description] varchar(max) NULL, 
	[Material Group Description 2] varchar(max) NULL, 
	[Category of Material Description] varchar(max) NULL, 
	[Material Brand Description] varchar(max) NULL, 
	[Material Sub Brand Description] varchar(max) NULL, 
	[Material Print Method Description] varchar(max) NULL, 
	[Material Level 5 Product Category Code] varchar(max) NULL, 
	[Material Level 5 Product Category Description] varchar(max) NULL, 
	[Material Level 6 Product Category Code] varchar(max) NULL, 
	[Material Level 6 Product Category Description] varchar(max) NULL, 
	[Material Category Description] varchar(max) NULL, 
	[Material Type Description] varchar(max) NULL, 
	[Material Product Hierarchy Description] varchar(max) NULL, 
	[Material Industry Sector Description] varchar(max) NULL, 
	[Material General Item Category Group Description] varchar(max) NULL, 
	[Material Client Level Deletion Indicator] varchar(max) NULL, 
	[Material PO UoM] varchar(max) NULL, 
	[Material Basic] varchar(max) NULL, 
	[Material Industry Standard Description] varchar(max) NULL, 
	[Material Laboratory/Design Office] varchar(max) NULL, 
	[Material Laboratory/Design Office Description] varchar(max) NULL, 
	[Material Purchasing Value Key] varchar(max) NULL, 
	[Material Storage Condition] varchar(max) NULL, 
	[Material Storage Condition Description] varchar(max) NULL, 
	[Material Temperature Conditions Indicator] varchar(max) NULL, 
	[Material Temperature Conditions Indicator Description] varchar(max) NULL, 
	[Material Transportation Group] varchar(max) NULL, 
	[Material Transportation Group Description] varchar(max) NULL, 
	[Material Hazardous Number] varchar(max) NULL, 
	[Material Source of Supply] varchar(max) NULL, 
	[Material Source of Supply Description] varchar(max) NULL, 
	[Material EAN/UPC Number] varchar(max) NULL, 
	[Material EAN Category] varchar(max) NULL, 
	[Material EAN Category Description] varchar(max) NULL, 
	[Material Length] decimal(13,3) NULL, 
	[Material Width] decimal(13,3) NULL, 
	[Material Height] decimal(13,3) NULL, 
	[Material UoD] varchar(max) NULL, 
	[Material External Group] varchar(max) NULL, 
	[Material External Group Description] varchar(max) NULL, 
	[Material Manufacturer Part Number] varchar(max) NULL, 
	[Material Dangerous Goods Indicator Profile] varchar(max) NULL, 
	[Material Dangerous Goods Indicator Profile Desription] varchar(max) NULL, 
	[Material Country of Origin] varchar(max) NULL, 
	[Material Country of Origin Description] varchar(max) NULL, 
	[Material Quality Inspection Group] varchar(max) NULL, 
	[Material Quality Inspection Group Description] varchar(max) NULL, 
	[MATRL_SALES_TEXT] varchar(max) NULL, 
	[Class Internl Num] int NULL, 
	[Class Name] varchar(max) NULL, 
	[Class Typ] varchar(max) NULL, 
	[Class Typ Desc] varchar(max) NULL, 
	[Class Status] varchar(max) NULL, 
	[Class Status Desc] varchar(max) NULL, 
	[Characteristic 1 Internl Num] int NULL, 
	[Characteristic 1 Name] varchar(max) NULL, 
	[Characteristic 1 Desc] varchar(max) NULL, 
	[Characteristic 1 Val] varchar(max) NULL, 
	[Characteristic 1 Val Desc] varchar(max) NULL, 
	[Characteristic 2 Internl Num] int NULL, 
	[Characteristic 2 Name] varchar(max) NULL, 
	[Characteristic 2 Desc] varchar(max) NULL, 
	[Characteristic 2 Val] varchar(max) NULL, 
	[Characteristic 2 Val Desc] varchar(max) NULL, 
	[Characteristic 3 Internl Num] int NULL, 
	[Characteristic 3 Name] varchar(max) NULL, 
	[Characteristic 3 Desc] varchar(max) NULL, 
	[Characteristic 3 Val] varchar(max) NULL, 
	[Characteristic 3 Val Desc] varchar(max) NULL, 
	[Characteristic 4 Internl Num] int NULL, 
	[Characteristic 4 Name] varchar(max) NULL, 
	[Characteristic 4 Desc] varchar(max) NULL, 
	[Characteristic 4 Val] varchar(max) NULL, 
	[Characteristic 4 Val Desc] varchar(max) NULL, 
	[Characteristic 5 Internl Num] int NULL, 
	[Characteristic 5 Name] varchar(max) NULL, 
	[Characteristic 5 Desc] varchar(max) NULL, 
	[Characteristic 5 Val] varchar(max) NULL, 
	[Characteristic 5 Val Desc] varchar(max) NULL, 
	[Characteristic 6 Internl Num] int NULL, 
	[Characteristic 6 Name] varchar(max) NULL, 
	[Characteristic 6 Desc] varchar(max) NULL, 
	[Characteristic 6 Val] varchar(max) NULL, 
	[Characteristic 6 Val Desc] varchar(max) NULL, 
	[Characteristic 7 Internl Num] int NULL, 
	[Characteristic 7 Name] varchar(max) NULL, 
	[Characteristic 7 Desc] varchar(max) NULL, 
	[Characteristic 7 Val] varchar(max) NULL, 
	[Characteristic 7 Val Desc] varchar(max) NULL, 
	[Characteristic 8 Internl Num] int NULL, 
	[Characteristic 8 Name] varchar(max) NULL, 
	[Characteristic 8 Desc] varchar(max) NULL, 
	[Characteristic 8 Val] varchar(max) NULL, 
	[Characteristic 8 Val Desc] varchar(max) NULL, 
	[Characteristic 9 Internl Num] int NULL, 
	[Characteristic 9 Name] varchar(max) NULL, 
	[Characteristic 9 Desc] varchar(max) NULL, 
	[Characteristic 9 Val] varchar(max) NULL, 
	[Characteristic 9 Val Desc] varchar(max) NULL, 
	[Characteristic 10 Internl Num] int NULL, 
	[Characteristic 10 Name] varchar(max) NULL, 
	[Characteristic 10 Desc] varchar(max) NULL, 
	[Characteristic 10 Val] varchar(max) NULL, 
	[Characteristic 10 Val Desc] varchar(max) NULL, 
	[Characteristic 11 Internl Num] int NULL, 
	[Characteristic 11 Name] varchar(max) NULL, 
	[Characteristic 11 Desc] varchar(max) NULL, 
	[Characteristic 11 Val] varchar(max) NULL, 
	[Characteristic 11 Val Desc] varchar(max) NULL, 
	[Characteristic 12 Internl Num] int NULL, 
	[Characteristic 12 Name] varchar(max) NULL, 
	[Characteristic 12 Desc] varchar(max) NULL, 
	[Characteristic 12 Val] varchar(max) NULL, 
	[Characteristic 12 Val Desc] varchar(max) NULL, 
	[Characteristic 13 Internl Num] int NULL, 
	[Characteristic 13 Name] varchar(max) NULL, 
	[Characteristic 13 Desc] varchar(max) NULL, 
	[Characteristic 13 Val] varchar(max) NULL, 
	[Characteristic 13 Val Desc] varchar(max) NULL, 
	[Characteristic 14 Internl Num] int NULL, 
	[Characteristic 14 Name] varchar(max) NULL, 
	[Characteristic 14 Desc] varchar(max) NULL, 
	[Characteristic 14 Val] varchar(max) NULL, 
	[Characteristic 14 Val Desc] varchar(max) NULL, 
	[Characteristic 15 Internl Num] int NULL, 
	[Characteristic 15 Name] varchar(max) NULL, 
	[Characteristic 15 Desc] varchar(max) NULL, 
	[Characteristic 15 Val] varchar(max) NULL, 
	[Characteristic 15 Val Desc] varchar(max) NULL, 
	[Characteristic 16 Internl Num] int NULL, 
	[Characteristic 16 Name] varchar(max) NULL, 
	[Characteristic 16 Desc] varchar(max) NULL, 
	[Characteristic 16 Val] varchar(max) NULL, 
	[Characteristic 16 Val Desc] varchar(max) NULL, 
	[Characteristic 17 Internl Num] int NULL, 
	[Characteristic 17 Name] varchar(max) NULL, 
	[Characteristic 17 Desc] varchar(max) NULL, 
	[Characteristic 17 Val] varchar(max) NULL, 
	[Characteristic 17 Val Desc] varchar(max) NULL, 
	[Characteristic 18 Internl Num] int NULL, 
	[Characteristic 18 Name] varchar(max) NULL, 
	[Characteristic 18 Desc] varchar(max) NULL, 
	[Characteristic 18 Val] varchar(max) NULL, 
	[Characteristic 18 Val Desc] varchar(max) NULL, 
	[Characteristic 19 Internl Num] int NULL, 
	[Characteristic 19 Name] varchar(max) NULL, 
	[Characteristic 19 Desc] varchar(max) NULL, 
	[Characteristic 19 Val] varchar(max) NULL, 
	[Characteristic 19 Val Desc] varchar(max) NULL, 
	[Characteristic 20 Internl Num] int NULL, 
	[Characteristic 20 Name] varchar(max) NULL, 
	[Characteristic 20 Desc] varchar(max) NULL, 
	[Characteristic 20 Val] varchar(max) NULL, 
	[Characteristic 20 Val Desc] varchar(max) NULL, 
	[Characteristic 21 Internl Num] int NULL, 
	[Characteristic 21 Name] varchar(max) NULL, 
	[Characteristic 21 Desc] varchar(max) NULL, 
	[Characteristic 21 Val] varchar(max) NULL, 
	[Characteristic 21 Val Desc] varchar(max) NULL, 
	[Characteristic 22 Internl Num] int NULL, 
	[Characteristic 22 Name] varchar(max) NULL, 
	[Characteristic 22 Desc] varchar(max) NULL, 
	[Characteristic 22 Val] varchar(max) NULL, 
	[Characteristic 22 Val Desc] varchar(max) NULL, 
	[Characteristic 23 Internl Num] varchar(max) NULL, 
	[Characteristic 23 Name] varchar(max) NULL, 
	[Characteristic 23 Desc] varchar(max) NULL, 
	[Characteristic 23 Val] varchar(max) NULL, 
	[Characteristic 23 Val Desc] varchar(max) NULL, 
	[Material Description Italian] varchar(max) NULL, 
	[Material Cross Plant Status] varchar(max) NULL, 
	[Material Cross Plant Description] varchar(max) NULL, 
	[DIVISION] varchar(max) NULL, 
	[DIVISION_DESC] varchar(max) NULL
);