CREATE TABLE [dbo].[EDW_T_D_SAL_PRDVCON_CUR_D] (

	[PRDT_VARIANT_CONFIG_KEY] int NOT NULL, 
	[SALES_ORDER_ID] varchar(max) NULL, 
	[SALES_ORDER_ITM_ID] varchar(max) NULL, 
	[ZLP BB Reference Job] varchar(max) NULL, 
	[ZLP AV Reference Job Number] varchar(max) NULL, 
	[ZLP BB Adapt From] varchar(max) NULL, 
	[ZLP CAD F Previous Job Number] varchar(max) NULL, 
	[ZLP AG Reference Job] varchar(max) NULL, 
	[ZLP BB Version] varchar(max) NULL, 
	[ZLP AG Project] varchar(max) NULL, 
	[G Separation ID] varchar(max) NULL, 
	[G Emboss Rework] varchar(max) NULL, 
	[G Chrome Thickness] varchar(max) NULL, 
	[G Emboss Double Height] varchar(max) NULL, 
	[G SE Drawing Number] varchar(max) NULL, 
	[G Incoming Cylinder Number] varchar(max) NULL, 
	[G Leaving Cylinder Number] varchar(max) NULL, 
	[G Bombage] varchar(max) NULL, 
	[G Copper Diameter] varchar(max) NULL, 
	[G Copper Radius] varchar(max) NULL, 
	[G Lower Tolerance] varchar(max) NULL, 
	[G Upper Tolerance] varchar(max) NULL, 
	[G Copper Thickness] varchar(max) NULL, 
	[G Extra Copper Work] varchar(max) NULL, 
	[G Finishing] varchar(max) NULL, 
	[G Grinding Finishing] varchar(max) NULL, 
	[G Emboss Hardening] varchar(max) NULL, 
	[G Coating] varchar(max) NULL, 
	[G Emboss Bearings] varchar(max) NULL, 
	[G Inbnd Cylinder] varchar(max) NULL, 
	[G Finishing 2] varchar(max) NULL, 
	[G Emboss Mat Thickness] varchar(max) NULL, 
	[G Emboss Dehydrathe] varchar(max) NULL, 
	[G Grinding In Steel] varchar(max) NULL, 
	[G Ctrl Classtatu] varchar(max) NULL, 
	[G Imaging Material] varchar(max) NULL, 
	[G Engraving Width] varchar(max) NULL, 
	[GT Nickel Type] varchar(max) NULL, 
	[G Emboss Blasting] varchar(max) NULL, 
	[G DFF Work Guideline] varchar(max) NULL, 
	[GT 3D Coating] varchar(max) NULL, 
	[Document Version] varchar(max) NULL, 
	[Encoway Document Number] varchar(max) NULL, 
	[Encoway Document Version] varchar(max) NULL, 
	[Document Number] varchar(max) NULL, 
	[G Separation DESC] varchar(max) NULL, 
	[G Repro Source] varchar(max) NULL, 
	[G Repro Class] varchar(max) NULL, 
	[G Face Width] varchar(max) NULL, 
	[G Final Diameter] varchar(max) NULL, 
	[G Circumference Change] varchar(max) NULL, 
	[G Number of Multiple Engravings] varchar(max) NULL, 
	[G Cylinder Conditions] varchar(max) NULL, 
	[G Repro Rework] varchar(max) NULL, 
	[G Repro Team] varchar(max) NULL, 
	[G ROTO Technology] varchar(max) NULL, 
	[G Repro Composition] varchar(max) NULL, 
	[G Brandowner] varchar(max) NULL, 
	[G Cylinder Type] varchar(max) NULL, 
	[G Axial Width] varchar(max) NULL, 
	[G Business Unit] varchar(max) NULL, 
	[G Position Number] varchar(max) NULL, 
	[Batch Class] varchar(max) NULL, 
	[G Original Diameter] varchar(max) NULL, 
	[G Original Wall Thickness] varchar(max) NULL, 
	[G Original Copper Layer] varchar(max) NULL, 
	[G Original Steelbase Order] varchar(max) NULL, 
	[G Original Engraving Surface] varchar(max) NULL, 
	[G Original Cylinder Surface] varchar(max) NULL, 
	[G Original Threads] varchar(max) NULL, 
	[G Printing Circumference] varchar(max) NULL, 
	[G Engraving Type] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[ZLP BB Reference Job Description] varchar(max) NULL, 
	[ZLP AV Reference Job Number Description] varchar(max) NULL, 
	[ZLP BB Adapt From Description] varchar(max) NULL, 
	[ZLP CAD F Previous Job Number Description] varchar(max) NULL, 
	[ZLP AG Reference Job Description] varchar(max) NULL, 
	[ZLP BB Version Description] varchar(max) NULL, 
	[ZLP AG Project Description] varchar(max) NULL, 
	[G Separation ID Description] varchar(max) NULL, 
	[G Emboss Rework Description] varchar(max) NULL, 
	[G Chrome Thickness Description] varchar(max) NULL, 
	[G Emboss Double Height Description] varchar(max) NULL, 
	[G SE Draw Number Description] varchar(max) NULL, 
	[G Incoming Cylinder Number Description] varchar(max) NULL, 
	[G Leaving Cylinder Number Description] varchar(max) NULL, 
	[G Bombage Description] varchar(max) NULL, 
	[G Copper Diameter Description] varchar(max) NULL, 
	[G Copper Radius Description] varchar(max) NULL, 
	[G Lower Tolerance Description] varchar(max) NULL, 
	[G Upper Tolerance Description] varchar(max) NULL, 
	[G Copper Thickness Description] varchar(max) NULL, 
	[G Extra Copper Work Description] varchar(max) NULL, 
	[G Finishing Description] varchar(max) NULL, 
	[G Grinding Finishing Description] varchar(max) NULL, 
	[G Emboss Hardening Description] varchar(max) NULL, 
	[G Coating Description] varchar(max) NULL, 
	[G Emboss Bearings Description] varchar(max) NULL, 
	[G Inbnd Cylinder Description] varchar(max) NULL, 
	[G Finishing 2 Description] varchar(max) NULL, 
	[G Emboss Mat Thickness Description] varchar(max) NULL, 
	[G Emboss Dehydrathe Description] varchar(max) NULL, 
	[G Grinding In Steel Description] varchar(max) NULL, 
	[G Ctrl Classtatu Description] varchar(max) NULL, 
	[G Imaging Material Description] varchar(max) NULL, 
	[G Engraving Width Description] varchar(max) NULL, 
	[GT Nickel Type Description] varchar(max) NULL, 
	[G Emboss Blasting Description] varchar(max) NULL, 
	[G DFF Work Guideline Description] varchar(max) NULL, 
	[GT 3D Coating Description] varchar(max) NULL, 
	[Document Version Description] varchar(max) NULL, 
	[Encoway Document Number Description] varchar(max) NULL, 
	[Encoway Document Version Description] varchar(max) NULL, 
	[Document Number Description] varchar(max) NULL, 
	[G Separation DESC Description] varchar(max) NULL, 
	[G Repro Source Description] varchar(max) NULL, 
	[G Repro Class Description] varchar(max) NULL, 
	[G Face Width Description] varchar(max) NULL, 
	[G Final Diameter Description] varchar(max) NULL, 
	[G Circumference Change Description] varchar(max) NULL, 
	[G Number of Multiple Engravings Description] varchar(max) NULL, 
	[G Cylinder Conditions Description] varchar(max) NULL, 
	[G Repro Rework Description] varchar(max) NULL, 
	[G Repro Team Description] varchar(max) NULL, 
	[G ROTO Technology Description] varchar(max) NULL, 
	[G Repro Composition Description] varchar(max) NULL, 
	[G Brandowner Description] varchar(max) NULL, 
	[G Cylinder Type Description] varchar(max) NULL, 
	[G Axial Width Description] varchar(max) NULL, 
	[G Business Unit Description] varchar(max) NULL, 
	[G Position Number Description] varchar(max) NULL, 
	[Batch Class Description] varchar(max) NULL, 
	[G Original Diameter Description] varchar(max) NULL, 
	[G Original Wall Thickness Description] varchar(max) NULL, 
	[G Original Copper Layer Description] varchar(max) NULL, 
	[G Original Steelbase Order Description] varchar(max) NULL, 
	[G Original Engraving Surface Description] varchar(max) NULL, 
	[G Original Cylinder Surface Description] varchar(max) NULL, 
	[G Original Threads Description] varchar(max) NULL, 
	[G Printing Circumference Description] varchar(max) NULL, 
	[G Engraving Type Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 01] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 02] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 03] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 04] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 05] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 06] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 07] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 08] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 09] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 10] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 11] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 12] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 13] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 14] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 15] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 16] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 17] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 18] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 19] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 20] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 01 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 02 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 03 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 04 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 05 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 06 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 07 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 08 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 09 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 10 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 11 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 12 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 13 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 14 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 15 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 16 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 17 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 18 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 19 Description] varchar(max) NULL, 
	[ZLP Customer Specific Field Label 20 Description] varchar(max) NULL, 
	[GT Screen Circumference] varchar(max) NULL, 
	[GT Screen Length] varchar(max) NULL, 
	[G Plate Length] varchar(max) NULL, 
	[G Plate Width] varchar(max) NULL, 
	[G Emboss Depth] varchar(max) NULL, 
	[GT C Nickel Plating] varchar(max) NULL, 
	[G Emboss Steps] varchar(max) NULL, 
	[GT Screen Circumference Description] varchar(max) NULL, 
	[GT Screen Length Description] varchar(max) NULL, 
	[G Plate Length Description] varchar(max) NULL, 
	[G Plate Width Description] varchar(max) NULL, 
	[G Emboss Depth Description] varchar(max) NULL, 
	[GT C Nickel Plating Description] varchar(max) NULL, 
	[GT Wall Thickness Description] varchar(max) NULL, 
	[G Emboss Steps Description] varchar(max) NULL, 
	[GT Wall Thickness] varchar(max) NULL, 
	[G Engraving Methode] varchar(max) NULL, 
	[G Laser Type] varchar(max) NULL, 
	[G Engraving Methode Description] varchar(max) NULL, 
	[G Laser Type Description] varchar(max) NULL, 
	[G Estimated Cylinder Conditions] varchar(max) NULL, 
	[G Estimated Circumference Change] varchar(max) NULL, 
	[G Emboss Method] varchar(max) NULL, 
	[G Emboss Material] varchar(max) NULL, 
	[GT Screen Type] varchar(max) NULL, 
	[G Estimated Cylinder Conditions Description] varchar(max) NULL, 
	[G Estimated Circumference Change Description] varchar(max) NULL, 
	[G Emboss Method Description] varchar(max) NULL, 
	[G Emboss Material Description] varchar(max) NULL, 
	[GT Screen Type Description] varchar(max) NULL, 
	[ZLP ANZF VS] varchar(max) NULL, 
	[ZLP ANZF VS Description] varchar(max) NULL, 
	[G Copper Hardness HV] varchar(max) NULL, 
	[G Copper Hardness HV Description] varchar(max) NULL, 
	[ZLP BB Color Profile] varchar(max) NULL, 
	[ZLP BB Color Profile Description] varchar(max) NULL, 
	[ZLP AG F Color 01] varchar(max) NULL, 
	[ZLP AG F Color 02] varchar(max) NULL, 
	[ZLP AG F Color 03] varchar(max) NULL, 
	[ZLP AG F Color 04] varchar(max) NULL, 
	[ZLP AG F Color 05] varchar(max) NULL, 
	[ZLP AG F Color 06] varchar(max) NULL, 
	[ZLP AG F Color 07] varchar(max) NULL, 
	[ZLP AG F Color 08] varchar(max) NULL, 
	[ZLP AG F Color 09] varchar(max) NULL, 
	[ZLP AG F Color 10] varchar(max) NULL, 
	[ZLP AG F Color 11] varchar(max) NULL, 
	[ZLP AG F Color 12] varchar(max) NULL, 
	[ZLP AG F Color 13] varchar(max) NULL, 
	[ZLP AG F Color 14] varchar(max) NULL, 
	[ZLP AG F Color 15] varchar(max) NULL, 
	[ZLP AG F Color 16] varchar(max) NULL, 
	[ZLP AG F Color 17] varchar(max) NULL, 
	[ZLP AG F Color 18] varchar(max) NULL, 
	[ZLP AG F Color 19] varchar(max) NULL, 
	[ZLP AG F Color 20] varchar(max) NULL, 
	[ZLP AG C Customer Color 01] varchar(max) NULL, 
	[ZLP AG C Customer Color 02] varchar(max) NULL, 
	[ZLP AG C Customer Color 03] varchar(max) NULL, 
	[ZLP AG C Customer Color 04] varchar(max) NULL, 
	[ZLP AG C Customer Color 05] varchar(max) NULL, 
	[ZLP AG C Customer Color 06] varchar(max) NULL, 
	[ZLP AG C Customer Color 07] varchar(max) NULL, 
	[ZLP AG C Customer Color 08] varchar(max) NULL, 
	[ZLP AG C Customer Color 09] varchar(max) NULL, 
	[ZLP AG C Customer Color 10] varchar(max) NULL, 
	[ZLP AG C Customer Color 11] varchar(max) NULL, 
	[ZLP AG C Customer Color 12] varchar(max) NULL, 
	[ZLP AG C Customer Color 13] varchar(max) NULL, 
	[ZLP AG C Customer Color 14] varchar(max) NULL, 
	[ZLP AG C Customer Color 15] varchar(max) NULL, 
	[ZLP AG C Customer Color 16] varchar(max) NULL, 
	[ZLP AG C Customer Color 17] varchar(max) NULL, 
	[ZLP AG C Customer Color 18] varchar(max) NULL, 
	[ZLP AG C Customer Color 19] varchar(max) NULL, 
	[ZLP AG C Customer Color 20] varchar(max) NULL, 
	[ZLP AG F Color 01 Description] varchar(max) NULL, 
	[ZLP AG F Color 02 Description] varchar(max) NULL, 
	[ZLP AG F Color 03 Description] varchar(max) NULL, 
	[ZLP AG F Color 04 Description] varchar(max) NULL, 
	[ZLP AG F Color 05 Description] varchar(max) NULL, 
	[ZLP AG F Color 06 Description] varchar(max) NULL, 
	[ZLP AG F Color 07 Description] varchar(max) NULL, 
	[ZLP AG F Color 08 Description] varchar(max) NULL, 
	[ZLP AG F Color 09 Description] varchar(max) NULL, 
	[ZLP AG F Color 10 Description] varchar(max) NULL, 
	[ZLP AG F Color 11 Description] varchar(max) NULL, 
	[ZLP AG F Color 12 Description] varchar(max) NULL, 
	[ZLP AG F Color 13 Description] varchar(max) NULL, 
	[ZLP AG F Color 14 Description] varchar(max) NULL, 
	[ZLP AG F Color 15 Description] varchar(max) NULL, 
	[ZLP AG F Color 16 Description] varchar(max) NULL, 
	[ZLP AG F Color 17 Description] varchar(max) NULL, 
	[ZLP AG F Color 18 Description] varchar(max) NULL, 
	[ZLP AG F Color 19 Description] varchar(max) NULL, 
	[ZLP AG F Color 20 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 01 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 02 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 03 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 04 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 05 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 06 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 07 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 08 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 09 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 10 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 11 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 12 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 13 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 14 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 15 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 16 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 17 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 18 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 19 Description] varchar(max) NULL, 
	[ZLP AG C Customer Color 20 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 1] varchar(max) NULL, 
	[ZLP AG F Line Screen 2] varchar(max) NULL, 
	[ZLP AG F Line Screen 3] varchar(max) NULL, 
	[ZLP AG F Line Screen 4] varchar(max) NULL, 
	[ZLP AG F Line Screen 5] varchar(max) NULL, 
	[ZLP AG F Line Screen 6] varchar(max) NULL, 
	[ZLP AG F Line Screen 7] varchar(max) NULL, 
	[ZLP AG F Line Screen 8] varchar(max) NULL, 
	[ZLP AG F Line Screen 9] varchar(max) NULL, 
	[ZLP AG F Line Screen 10] varchar(max) NULL, 
	[ZLP AG F Line Screen 11] varchar(max) NULL, 
	[ZLP AG F Line Screen 12] varchar(max) NULL, 
	[ZLP AG F Line Screen 13] varchar(max) NULL, 
	[ZLP AG F Line Screen 14] varchar(max) NULL, 
	[ZLP AG F Line Screen 15] varchar(max) NULL, 
	[ZLP AG F Line Screen 16] varchar(max) NULL, 
	[ZLP AG F Line Screen 17] varchar(max) NULL, 
	[ZLP AG F Line Screen 18] varchar(max) NULL, 
	[ZLP AG F Line Screen 19] varchar(max) NULL, 
	[ZLP AG F Line Screen 20] varchar(max) NULL, 
	[ZLP AG F Line Screen 1 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 2 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 3 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 4 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 5 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 6 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 7 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 8 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 9 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 10 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 11 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 12 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 13 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 14 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 15 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 16 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 17 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 18 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 19 Description] varchar(max) NULL, 
	[ZLP AG F Line Screen 20 Description] varchar(max) NULL, 
	[ZLP Order Type] varchar(max) NULL, 
	[ZLP Order Type Description] varchar(max) NULL
);