CREATE TABLE [dbo].[EDW_T_D_MST_CUSTCMP_CUR_D] (

	[CUST_CMPNY_KEY] int NOT NULL, 
	[Customer ID] varchar(max) NULL, 
	[Company Code] varchar(max) NULL, 
	[Legacy Customer ID] varchar(max) NULL, 
	[Plant ID] varchar(max) NULL, 
	[Payment Terms Code] varchar(max) NULL, 
	[Payment Block] varchar(max) NULL, 
	[Accounting Clerk] varchar(max) NULL, 
	[Account At Customer] varchar(max) NULL, 
	[Posting Block For Company Code] varchar(max) NULL, 
	[Deletion Flag For Company Code] varchar(max) NULL, 
	[Recon Account] varchar(max) NULL, 
	[Periodic Account Statement Flag] varchar(max) NULL, 
	[Lockbox] varchar(max) NULL, 
	[Sort Key] varchar(max) NULL, 
	[Payment Method] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[Current Record Indicator of Customer Company] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Company Description] varchar(max) NULL, 
	[Payment Terms Description] varchar(max) NULL, 
	[Plant Description] varchar(max) NULL, 
	[Accounting Clerk Description] varchar(max) NULL, 
	[Posting Block Description] varchar(max) NULL, 
	[Statement Description] varchar(max) NULL, 
	[Payment Block Description] varchar(max) NULL, 
	[Sort Description] varchar(max) NULL, 
	[Head Office Account Number] varchar(max) NULL, 
	[Alternative Payer Account Number] varchar(max) NULL, 
	[Clearing Between Cust & Vendor Indicator] varchar(max) NULL, 
	[Collective Invoice Variant] varchar(max) NULL, 
	[Dunning Notice Grouping Key] varchar(max) NULL, 
	[Dunning Notice Grouping Description] varchar(max) NULL, 
	[Buying Group Account Number] varchar(max) NULL, 
	[Payment Method Description] varchar(max) NULL, 
	[Created On] date NULL, 
	[Created By] varchar(max) NULL, 
	[Deletion Block For Master Record] varchar(max) NULL, 
	[Personnel Number] varchar(max) NULL, 
	[Lockbox Key] varchar(max) NULL, 
	[Short Key For A House Bank] varchar(max) NULL
);