CREATE TABLE [dbo].[EDW_T_D_MST_NOTFICN_CUR_D] (

	[NOTIFICATION_KEY] int NOT NULL, 
	[Notification] varchar(max) NULL, 
	[Notification Type] varchar(max) NULL, 
	[Notification Description] varchar(max) NULL, 
	[Notification Priority] varchar(max) NULL, 
	[Notification Date] date NULL, 
	[Notification Required Start Date] date NULL, 
	[Notification Required End Date] date NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Notification Timestamp] datetime2(0) NULL, 
	[Reported By] varchar(max) NULL, 
	[Notification Required Start Timestamp] datetime2(0) NULL, 
	[Notification Required End Timestamp] datetime2(0) NULL, 
	[Object Number] varchar(max) NULL, 
	[Completion By Date] date NULL, 
	[Completion Timestamp] datetime2(0) NULL, 
	[Reference Date] date NULL, 
	[Reference Time] datetime2(0) NULL, 
	[Work Center] varchar(max) NULL, 
	[Plant For Work Center] varchar(max) NULL, 
	[Object Type] varchar(max) NULL, 
	[Sales Office] varchar(max) NULL, 
	[Sales Group] varchar(max) NULL, 
	[Notification Type Description] varchar(max) NULL, 
	[Notification Priority Description] varchar(max) NULL, 
	[Sales Office Description] varchar(max) NULL, 
	[Sales Group Description] varchar(max) NULL, 
	[Created By] varchar(max) NULL, 
	[Catalog Type Coding] varchar(max) NULL, 
	[Catalog Type Coding Description] varchar(max) NULL, 
	[CD Group Coding] varchar(max) NULL, 
	[CD Group Coding Description] varchar(max) NULL, 
	[Coding] varchar(max) NULL, 
	[Coding Description] varchar(max) NULL, 
	[Partner Number] varchar(max) NULL, 
	[Partner Name] varchar(max) NULL
);