CREATE TABLE [dbo].[EDW_T_D_MST_COSCNTR_CUR_D] (

	[COST_CNTR_KEY] int NOT NULL, 
	[Cost Center ID] varchar(max) NULL, 
	[Cost Center Long Description] varchar(max) NULL, 
	[Cost Center Controlling Area ID] varchar(max) NULL, 
	[Cost Center Language Type Code] varchar(max) NULL, 
	[Cost Center Category] varchar(max) NULL, 
	[Cost Center Hierarchy Area] varchar(max) NULL, 
	[Cost Center Company Code] varchar(max) NULL, 
	[Cost Center Plant ID] varchar(max) NULL, 
	[Cost Center Profit Center ID] varchar(max) NULL, 
	[Cost Center Currency Code] varchar(max) NULL, 
	[Cost Center Address Line 1] varchar(max) NULL, 
	[Cost Center Address Line 2] varchar(max) NULL, 
	[Cost Center Address Line 3] varchar(max) NULL, 
	[Cost Center City Name] varchar(max) NULL, 
	[Cost Center District Name] varchar(max) NULL, 
	[Cost Center Postal Code] varchar(max) NULL, 
	[Cost Center Country Code] varchar(max) NULL, 
	[Cost Center Region Code] varchar(max) NULL, 
	[Cost Center Person Responsible] varchar(max) NULL, 
	[Cost Center Flag Actual Revenues] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Cost Center Actual Primary Postings Lock Indicator] varchar(max) NULL, 
	[Cost Center Plan Primary Costs Lock Indicator] varchar(max) NULL, 
	[Cost Center Business Area] varchar(max) NULL, 
	[Cost Center Planning Revenues Lock Indicator] varchar(max) NULL, 
	[Cost Center PO Box] varchar(max) NULL, 
	[Cost Center Street] varchar(max) NULL, 
	[Cost Center User Responsible] varchar(max) NULL, 
	[COST_CNTR_NAME] varchar(max) NULL, 
	[Cost Center Short Description] varchar(max) NULL, 
	[Cost Center Controlling Area Description] varchar(max) NULL, 
	[Cost Center Category Description] varchar(max) NULL, 
	[Cost Center Company Description] varchar(max) NULL, 
	[Cost Center Currency Description] varchar(max) NULL, 
	[Cost Center Country Description] varchar(max) NULL, 
	[Cost Center Business Area Description] varchar(max) NULL, 
	[Cost Center Actual Secondary Cost Lock Indicator] varchar(max) NULL, 
	[Cost Center Plan Secondary Cost Lock Indicator] varchar(max) NULL, 
	[Cost Center Functional Area] varchar(max) NULL, 
	[Cost Center Functional Area Description] varchar(max) NULL, 
	[Cost Center Tax Jurisdiction] varchar(max) NULL, 
	[FUNCTION_OF_COST_CNTR] varchar(max) NULL, 
	[Cost Center Plant Description] varchar(max) NULL, 
	[Cost Center Created On] date NULL, 
	[Cost Center Valid To Date] date NULL, 
	[Cost Center Valid From Date] date NULL
);