CREATE TABLE [dbo].[EDW_T_D_MST_CUSTSAL_CUR_D] (

	[CUST_SALES_AREA_KEY] int NOT NULL, 
	[Customer Sales ID] varchar(max) NULL, 
	[Customer Sales Segment ID] varchar(max) NULL, 
	[Customer Sales Organization] varchar(max) NULL, 
	[Customer Sales Distribution Channel] varchar(max) NULL, 
	[Division] varchar(max) NULL, 
	[Order Block] varchar(max) NULL, 
	[Delivery Block] varchar(max) NULL, 
	[Customer Group] varchar(max) NULL, 
	[Customer Price Procedure] varchar(max) NULL, 
	[Sales District] varchar(max) NULL, 
	[Price Group] varchar(max) NULL, 
	[Price List] varchar(max) NULL, 
	[Order Probability] varchar(max) NULL, 
	[Incoterms] varchar(max) NULL, 
	[Incoterms 2] varchar(max) NULL, 
	[Account At Customer] varchar(max) NULL, 
	[Shipping Conditions] varchar(max) NULL, 
	[Payment Terms Code] varchar(max) NULL, 
	[Account Clerk] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[Current Record Indicator of Customer Sales] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Market Code] varchar(max) NULL, 
	[Customer Group 2] varchar(max) NULL, 
	[Sales Group] varchar(max) NULL, 
	[Sales Office] varchar(max) NULL, 
	[Created Date] date NULL, 
	[Aurora Rebate Program] varchar(max) NULL, 
	[Customer Group 3] varchar(max) NULL, 
	[Periodic Account Statements Indicator] varchar(max) NULL, 
	[Parent Customer ID] varchar(max) NULL, 
	[Parent Customer Name 1] varchar(max) NULL, 
	[Parent Customer Name 2] varchar(max) NULL, 
	[Customer Group 4] varchar(max) NULL, 
	[Customer Group 5] varchar(max) NULL, 
	[Customer Sales Organization Description] varchar(max) NULL, 
	[Distribution Channel Description] varchar(max) NULL, 
	[Division Description] varchar(max) NULL, 
	[Order Block Description] varchar(max) NULL, 
	[Delivery Block Description] varchar(max) NULL, 
	[Customer Group Description] varchar(max) NULL, 
	[Customer Price Procedure Description] varchar(max) NULL, 
	[Sales District Description] varchar(max) NULL, 
	[Price Group Description] varchar(max) NULL, 
	[Price List Description] varchar(max) NULL, 
	[Incoterms Description] varchar(max) NULL, 
	[Shipping Conditions Description] varchar(max) NULL, 
	[Payment Terms Description] varchar(max) NULL, 
	[Account Clerk Description] varchar(max) NULL, 
	[Aurora Rebate Program Description] varchar(max) NULL, 
	[Customer Group 2 Description] varchar(max) NULL, 
	[Sales Group Description] varchar(max) NULL, 
	[Sales Office Description] varchar(max) NULL, 
	[Customer Group 3 Description] varchar(max) NULL, 
	[Statement Description] varchar(max) NULL, 
	[Customer Group 4 Description] varchar(max) NULL, 
	[Customer Group 5 Description] varchar(max) NULL, 
	[Created By] varchar(max) NULL, 
	[Account Assignment Group] varchar(max) NULL, 
	[Account Assignment Group Description] varchar(max) NULL, 
	[ABC Classification] varchar(max) NULL, 
	[Currency] varchar(max) NULL, 
	[Currency Description] varchar(max) NULL, 
	[Credit Control Area] varchar(max) NULL, 
	[Credit Control Area Description] varchar(max) NULL, 
	[Sales Block] varchar(max) NULL, 
	[Customer Group 1] varchar(max) NULL, 
	[Customer Group 1 Description] varchar(max) NULL, 
	[No Of Days Payment Terms] int NULL, 
	[End Of The Month Ind] varchar(max) NULL, 
	[Terms Discount Percentage] varchar(max) NULL, 
	[Customer Group 6] varchar(max) NULL, 
	[Customer Group 7] varchar(max) NULL, 
	[Customer Group 8] varchar(max) NULL, 
	[Customer Group 9] varchar(max) NULL, 
	[Customer Group 10] varchar(max) NULL, 
	[Customer Group 6 Description] varchar(max) NULL, 
	[Customer Group 7 Description] varchar(max) NULL, 
	[Customer Group 8 Description] varchar(max) NULL, 
	[Customer Group 9 Description] varchar(max) NULL, 
	[Customer Group 10 Description] varchar(max) NULL, 
	[Brand Owner ID] varchar(max) NULL, 
	[Brand Owner Name 1] varchar(max) NULL, 
	[Brand Owner Name 2] varchar(max) NULL, 
	[Delivery Priority] int NULL, 
	[Delivery Priority Description] varchar(max) NULL, 
	[Invoice Dates Calendar Identification] varchar(max) NULL, 
	[Invoice Dates Calendar Identification Description] varchar(max) NULL, 
	[Order Combination Indicator] varchar(max) NULL, 
	[Complete Delivery Defined For Each Sales Order] varchar(max) NULL, 
	[Max Number Of Partial Deliveries Allowed Per Item] int NULL, 
	[Delivering Plant ID] varchar(max) NULL, 
	[Delivering Plant Description] varchar(max) NULL, 
	[Deletion Indicator] varchar(max) NULL, 
	[Sales Area Billing Block] varchar(max) NULL, 
	[Customer Procedure for Product Proposal] varchar(max) NULL, 
	[Customer Procedure for Product Proposal Description] varchar(max) NULL, 
	[Customer Statistics Group] varchar(max) NULL, 
	[Customer Statistics Group Description] varchar(max) NULL, 
	[Partial Delivery At Item Level] varchar(max) NULL, 
	[Customer Is Rebate-Relevant Indicator] varchar(max) NULL, 
	[Relevant For Price Determination ID] varchar(max) NULL, 
	[Invoice List Schedule] varchar(max) NULL, 
	[Rating Customer] varchar(max) NULL, 
	[CFSA Code] varchar(max) NULL, 
	[Pre Need] varchar(max) NULL, 
	[PN Contact] varchar(max) NULL, 
	[PN Pending] varchar(max) NULL, 
	[Separate Invoice] varchar(max) NULL, 
	[Miles From WHSE] int NULL, 
	[NSM Member] varchar(max) NULL, 
	[Consignment Code] varchar(max) NULL, 
	[Saturday WHSE] varchar(max) NULL, 
	[PO Mandatory] varchar(max) NULL, 
	[Deceased Name Mandatory] varchar(max) NULL, 
	[Company] varchar(max) NULL, 
	[CFSA Rating] varchar(max) NULL, 
	[Transfer Fee] varchar(max) NULL, 
	[Customer Origin] varchar(max) NULL, 
	[Sales Volume Commitment Percentage] int NULL, 
	[Case Volume Percentage] int NULL, 
	[Casket Volume Percentage] int NULL, 
	[12 Unit Challenge] varchar(max) NULL, 
	[PN % Commission] int NULL, 
	[Plant] varchar(max) NULL, 
	[Sign Up Date] date NULL
);