CREATE TABLE [dbo].[EDW_T_D_MST_EQUIPMT_CUR_D] (

	[EQUIP_KEY] int NOT NULL, 
	[Equipment] varchar(max) NULL, 
	[Equipment Description] varchar(max) NULL, 
	[Equipment Category] varchar(max) NULL, 
	[Equipment Weight Of Object] decimal(13,3) NULL, 
	[Equipment Unit Of Weight] varchar(max) NULL, 
	[Equipment Warranty End Date] date NULL, 
	[Equipment Note] varchar(max) NULL, 
	[Equipment Object Number] varchar(max) NULL, 
	[Equipment Material] varchar(max) NULL, 
	[Equipment Serial Number] varchar(max) NULL, 
	[Equipment Size] varchar(max) NULL, 
	[Equipment Date Last Goods Movement] date NULL, 
	[Equipment Authorization Group Origin] varchar(max) NULL, 
	[Equipment Data Exists] varchar(max) NULL, 
	[Equipment Serialization Data] varchar(max) NULL, 
	[Equipment EQSI Exists] varchar(max) NULL, 
	[Equipment Stock Check] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Equipment Stock Type Of Goods Movement] varchar(max) NULL, 
	[Equipment Plant] varchar(max) NULL, 
	[Equipment Storage Location] varchar(max) NULL, 
	[Equipment Special Stock Indicator] varchar(max) NULL, 
	[Equipment System Status] varchar(max) NULL
);