CREATE TABLE [dbo].[EDW_T_D_PM_ORDER_CUR_D] (

	[ORDER_KEY] int NOT NULL, 
	[Order Type] varchar(max) NULL, 
	[Order Category] varchar(max) NULL, 
	[Order Company Code] varchar(max) NULL, 
	[Production Plant ID] varchar(max) NULL, 
	[Planning Plant ID] varchar(max) NULL, 
	[Material ID] varchar(max) NULL, 
	[Order Profit Center ID] varchar(max) NULL, 
	[Sales Order ID] varchar(max) NULL, 
	[Sales Order Item Number] int NULL, 
	[Task List Type] varchar(max) NULL, 
	[Order Create Date] date NULL, 
	[Order Close Date] date NULL, 
	[Project ID] int NULL, 
	[MRP Controller Code] varchar(max) NULL, 
	[Reservation Number] int NULL, 
	[Scheduled Start Date] date NULL, 
	[Scheduled Finish Date] date NULL, 
	[Actual Start Date] date NULL, 
	[Actual Finish Date] date NULL, 
	[Planned Release Date] date NULL, 
	[Actual Release Date] date NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Order Number] varchar(max) NULL, 
	[Entered By] varchar(max) NULL, 
	[Order Description] varchar(max) NULL, 
	[WBS Element Internal] bigint NULL, 
	[Controlling Area] varchar(max) NULL, 
	[Responsible Cost Center] varchar(max) NULL, 
	[Order Currency Code] varchar(max) NULL, 
	[Release Date] date NULL, 
	[Technical Completion Date] date NULL, 
	[Object Number] varchar(max) NULL, 
	[Requested By] varchar(max) NULL, 
	[Reason Code] varchar(max) NULL, 
	[Error Severity] varchar(max) NULL, 
	[Error Caught By] varchar(max) NULL, 
	[Error Origin] varchar(max) NULL, 
	[Error Type] varchar(max) NULL, 
	[Error Description] varchar(max) NULL, 
	[Reason For Change] varchar(max) NULL, 
	[Description Of Change] varchar(max) NULL, 
	[Main Work Center ID] varchar(max) NULL, 
	[Costing Sheet] varchar(max) NULL, 
	[Order Changed By] varchar(max) NULL, 
	[Order Changed On] date NULL, 
	[Business Area] varchar(max) NULL, 
	[Functional Area] varchar(max) NULL, 
	[Object Class] varchar(max) NULL, 
	[Tax Jurisdiction] varchar(max) NULL, 
	[Overhead Key] varchar(max) NULL, 
	[Basic End Date] date NULL, 
	[Basic Start Date] date NULL, 
	[Scheduled Release Date] date NULL, 
	[Plan Number Of Operation] int NULL, 
	[Exact Break Times] varchar(max) NULL, 
	[Network Profile] varchar(max) NULL, 
	[Order Priority] varchar(max) NULL, 
	[Costing Variant Plan] varchar(max) NULL, 
	[Costing Variant Actual] varchar(max) NULL, 
	[Superior Network Number] varchar(max) NULL, 
	[Superior Activity] varchar(max) NULL, 
	[Responsible Planner Group] varchar(max) NULL, 
	[Change Number] varchar(max) NULL, 
	[Order Type Description] varchar(max) NULL, 
	[Order Category Description] varchar(max) NULL, 
	[Task List Type Description] varchar(max) NULL, 
	[MRP Controller Code Description] varchar(max) NULL, 
	[Controlling Area Description] varchar(max) NULL, 
	[Business Area Description] varchar(max) NULL, 
	[Functional Area Description] varchar(max) NULL, 
	[Object Class Description] varchar(max) NULL, 
	[External Order Number] varchar(max) NULL, 
	[Person Responsible] varchar(max) NULL, 
	[End Of Work Date] date NULL, 
	[Date Of Last Status Change] date NULL, 
	[Status Reached So Far] int NULL, 
	[Is Created] varchar(max) NULL, 
	[Is Released] varchar(max) NULL, 
	[Is Completed] varchar(max) NULL, 
	[Is Closed] varchar(max) NULL, 
	[Deletion Indicator] varchar(max) NULL
);