CREATE TABLE [dbo].[EDW_T_D_MST_CUSTOMR_CUR_D] (

	[CUST_KEY] int NOT NULL, 
	[Customer ID] varchar(max) NULL, 
	[Legacy Customer ID] varchar(max) NULL, 
	[Customer Name] varchar(max) NULL, 
	[Customer Line 2 Description] varchar(max) NULL, 
	[Customer Country Code] varchar(max) NULL, 
	[Customer Plant ID] varchar(max) NULL, 
	[Customer Segment ID] varchar(max) NULL, 
	[Customer Industry] varchar(max) NULL, 
	[Customer Vendor ID] varchar(max) NULL, 
	[Customer Group Code] varchar(max) NULL, 
	[Customer Account Group Code] varchar(max) NULL, 
	[Customer Title] varchar(max) NULL, 
	[Customer Search Term] varchar(max) NULL, 
	[Customer Street] varchar(max) NULL, 
	[Customer City] varchar(max) NULL, 
	[Customer Zip Code] varchar(max) NULL, 
	[Customer State Code] varchar(max) NULL, 
	[Customer Region Code] varchar(max) NULL, 
	[Customer Telephone Number 1] varchar(max) NULL, 
	[Customer Telephone Number 2] varchar(max) NULL, 
	[Customer Fax Number Code] varchar(max) NULL, 
	[Customer Tax Number 1 Code] varchar(max) NULL, 
	[Customer Tax Number 2 Code] varchar(max) NULL, 
	[Customer VAT Number Code] varchar(max) NULL, 
	[Customer Credit Limit] decimal(15,3) NULL, 
	[Customer Bonus Rate] decimal(9,3) NULL, 
	[Customer Express Station] varchar(max) NULL, 
	[Customer Transportation Zone] varchar(max) NULL, 
	[Customer Printer Location Characteristics] varchar(max) NULL, 
	[Customer Printer Region Characteristics] varchar(max) NULL, 
	[Customer Printer Site Characteristics] varchar(max) NULL, 
	[Customer Created Date] date NULL, 
	[Customer Created User ID] varchar(max) NULL, 
	[Customer Updated Date] date NULL, 
	[Customer Updated User ID] varchar(max) NULL, 
	[Customer Payment Terms Code] varchar(max) NULL, 
	[Customer Sales Distribution] varchar(max) NULL, 
	[Customer Order Block For Sales Area] varchar(max) NULL, 
	[Customer Delivery Block For Sales Area] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Customer Corporate Group] varchar(max) NULL, 
	[Customer Classification] varchar(max) NULL, 
	[Customer Classification Description] varchar(max) NULL, 
	[Customer Printer Location] varchar(max) NULL, 
	[Customer Printer Site] varchar(max) NULL, 
	[Customer Printer Region] varchar(max) NULL, 
	[Customer Specific Field Label 01] varchar(max) NULL, 
	[Customer Specific Field Label 02] varchar(max) NULL, 
	[Customer Specific Field Label 03] varchar(max) NULL, 
	[Customer Specific Field Label 04] varchar(max) NULL, 
	[Customer Specific Field Label 05] varchar(max) NULL, 
	[Customer Specific Field Label 06] varchar(max) NULL, 
	[Customer Specific Field Label 07] varchar(max) NULL, 
	[Customer Specific Field Label 08] varchar(max) NULL, 
	[Customer Specific Field Label 09] varchar(max) NULL, 
	[Customer Specific Field Label 10] varchar(max) NULL, 
	[Customer Specific Field Label 11] varchar(max) NULL, 
	[Customer Specific Field Label 12] varchar(max) NULL, 
	[Customer Specific Field Label 13] varchar(max) NULL, 
	[Customer Specific Field Label 14] varchar(max) NULL, 
	[Customer Specific Field Label 15] varchar(max) NULL, 
	[Customer Specific Field Label 16] varchar(max) NULL, 
	[Customer Specific Field Label 17] varchar(max) NULL, 
	[Customer Specific Field Label 18] varchar(max) NULL, 
	[Customer Specific Field Label 19] varchar(max) NULL, 
	[Customer Specific Field Label 20] varchar(max) NULL, 
	[Customer Condition Group 1] varchar(max) NULL, 
	[Customer Industry Code 1] varchar(max) NULL, 
	[Customer Industry Code 2] varchar(max) NULL, 
	[Customer Industry Description] varchar(max) NULL, 
	[Customer Industry Code 1 Description] varchar(max) NULL, 
	[Customer Industry Code 2 Description] varchar(max) NULL, 
	[Customer Assignment to Hierarchy] int NULL, 
	[Customer Account Group Description] varchar(max) NULL, 
	[Customer Region Description] varchar(max) NULL, 
	[Customer Country Description] varchar(max) NULL, 
	[Customer Transportation Zone Description] varchar(max) NULL, 
	[Customer Plant Description] varchar(max) NULL, 
	[Customer Condition Group Description] varchar(max) NULL, 
	[Customer Cental Billing Block] varchar(max) NULL, 
	[Customer Cental Billing Block Description] varchar(max) NULL, 
	[Customer Central Delivery Block] varchar(max) NULL, 
	[Customer Central Delivery Block Description] varchar(max) NULL, 
	[Customer Deletion Indicator] varchar(max) NULL, 
	[Customer Central Posting Block] varchar(max) NULL, 
	[Customer Tax Jurisdiction] varchar(max) NULL, 
	[Customer Central Sales Block] varchar(max) NULL, 
	[Customer Central Deletion Indicator] varchar(max) NULL, 
	[Customer Language Key] varchar(max) NULL, 
	[Customer Trading Partner] varchar(max) NULL, 
	[Customer Trading Partner Description] varchar(max) NULL, 
	[Customer Annual Sales] decimal(8,2) NULL, 
	[Customer Annual Sales Year] int NULL, 
	[Customer Sales Currency] varchar(max) NULL, 
	[Customer Sales Currency Description] varchar(max) NULL, 
	[Customer One Time Account Group] varchar(max) NULL, 
	[Customer One Time Account Group Description] varchar(max) NULL, 
	[Customer One Time Indicator] varchar(max) NULL, 
	[Customer Industry Type] varchar(max) NULL, 
	[Customer Business Type] varchar(max) NULL, 
	[Customer DUNS Number] varchar(max) NULL, 
	[Customer DUNS Plus 4] varchar(max) NULL, 
	[Customer City Coordinates] varchar(max) NULL, 
	[Customer Tax Number 4 Code] varchar(max) NULL, 
	[Customer Attribute 3] varchar(max) NULL, 
	[Customer Attribute 3 Description] varchar(max) NULL, 
	[Customer E-Mail Address] varchar(max) NULL, 
	[Customer Mobile Number] varchar(max) NULL, 
	[Customer Search Term 2] varchar(max) NULL, 
	[Customer Street 2] varchar(max) NULL, 
	[Customer Street 3] varchar(max) NULL, 
	[Customer Street 4] varchar(max) NULL, 
	[Customer Street 5] varchar(max) NULL, 
	[Customer PO Box] varchar(max) NULL, 
	[Customer PO Box Postal Code] varchar(max) NULL, 
	[Customer PO Box City] varchar(max) NULL, 
	[Customer Region For PO Box] varchar(max) NULL, 
	[Customer PO Box Country] varchar(max) NULL, 
	[Customer Transport Zone] varchar(max) NULL, 
	[Customer Address Notes] varchar(max) NULL, 
	[Customer Tax Number 3 Code] varchar(max) NULL, 
	[Customer Tax Number 5 Code] varchar(max) NULL, 
	[Customer Industry Code 3] varchar(max) NULL, 
	[Customer Industry Code 3 Description] varchar(max) NULL, 
	[Customer Industry Code 4] varchar(max) NULL, 
	[Customer Industry Code 4 Description] varchar(max) NULL, 
	[Customer Industry Code 5] varchar(max) NULL, 
	[Customer Industry Code 5 Description] varchar(max) NULL, 
	[Customer Central Order Block For Customer] varchar(max) NULL, 
	[Customer Payment Block] varchar(max) NULL
);