CREATE   PROCEDURE [Propelis].[Proc_SUPPLIER_CUST]
AS
BEGIN
    -- Step 1: Update existing records in target table
    UPDATE T
    SET
               T.[CUST_KEY]	         = S.[CUST_KEY],
               T.[Supplier Customer ID]	         = S.[CUST_ID],
               T.[Supplier Legacy Customer ID]	         = S.[LGCY_CUST_ID],
               T.[Supplier Customer Name]	         = S.[CUST_NAME],
               T.[Supplier Cust Line 2 Description]	         = S.[CUST_LINE_2_DESC],
               T.[Supplier Cust Country Code]	         = S.[CNTRY_CD],
               T.[Supplier Cust Plant ID]	         = S.[PLNT_ID],
               T.[Supplier Cust Segment ID]	         = S.[SEG_ID],
               T.[Supplier Cust Industry]	         = S.[INDUS],
               T.[Supplier Cust Vendor ID]	         = S.[VNDR_ID],
               T.[Supplier Cust Customer Group Code]	         = S.[CUST_GROUP_CD],
               T.[Supplier Cust Account Group Code]	         = S.[CUST_ACCT_GROUP_CD],
               T.[Supplier Cust Title]	         = S.[TITLE],
               T.[Supplier Cust Search Term]	         = S.[SEARCH_TERM],
               T.[Supplier Cust Street]	         = S.[STR],
               T.[Supplier Cust City]	         = S.[CITY_NAME],
               T.[Supplier Cust Zip Code]	         = S.[ZIP_CD],
               T.[Supplier Cust State Code]	         = S.[ST_CD],
               T.[Supplier Cust Region Code]	         = S.[REGN_CD],
               T.[Supplier Cust Telephone Number 1]	         = S.[TEL_NUM_1_CD],
               T.[Supplier Cust Telephone Number 2]	         = S.[TEL_NUM_2_CD],
               T.[Supplier Cust Fax Number Code]	         = S.[FAX_NUM_CD],
               T.[Supplier Cust Tax Number 1 Code]	         = S.[TAX_NUM_1_CD],
               T.[Supplier Cust Tax Number 2 Code]	         = S.[TAX_NUM_2_CD],
               T.[Supplier Cust VAT Number Code]	         = S.[VAT_NUM_CD],
               T.[Supplier Cust Credit Limit]	         = S.[CREDIT_LMT],
               T.[Supplier Cust Bonus Rate]	         = S.[BONUS_RT],
               T.[Supplier Cust Express Station]	         = S.[EXPRESS_STATION],
               T.[Supplier Cust Transportation Zone]	         = S.[TRANSTN_ZONE],
               T.[Supplier Cust Printer Location Characteristics]	         = S.[PRINTER_LOC_CHARS],
               T.[Supplier Cust Printer Region Characteristics]	         = S.[PRINTER_REGN_CHARS],
               T.[Supplier Cust Printer Site Characteristics]	         = S.[PRINTER_SITE_CHARS],
               T.[Supplier Cust Customer Created Date]	         = S.[CREATED_DATE],
               T.[Supplier Cust Created User ID]	         = S.[CREATED_USR_ID],
               T.[Supplier Cust Customer Updated Date]	         = S.[UPDTD_DATE],
               T.[Supplier Cust Updated User ID]	         = S.[UPDTD_USR_ID],
               T.[Supplier Cust Payment Terms Code]	         = S.[PYMT_TRMS_CD],
               T.[Supplier Cust Sales Distribution]	         = S.[SALES_DISTR],
               T.[Supplier Cust Order Block For Sales Area]	         = S.[ORDER_BLK_FOR_SALES_AREA],
               T.[Supplier Cust Delivery Block For Sales Area]	         = S.[DLVRY_BLK_FOR_SALES_AREA],
               T.[ETL_SRC_SYS_CD]	         = S.[ETL_SRC_SYS_CD],
               T.[ETL_EFFECTV_BEGIN_DATE]	         = S.[ETL_EFFECTV_BEGIN_DATE],
               T.[ETL_EFFECTV_END_DATE]	         = S.[ETL_EFFECTV_END_DATE],
               T.[ETL_CURR_RCD_IND]	         = S.[ETL_CURR_RCD_IND],
               T.[ETL_CREATED_TS]	         = S.[ETL_CREATED_TS],
               T.[ETL_UPDTD_TS]	         = S.[ETL_UPDTD_TS],
               T.[Supplier Cust Corporate Group]	         = S.[CORPORATE_GROUP],
               T.[Supplier Cust Classification]	         = S.[CUST_CLSFTN],
               T.[Supplier Cust Classification Description]	         = S.[CUST_CLSFTN_DESC],
               T.[Supplier Cust Printer Location]	         = S.[PRINTER_LOC],
               T.[Supplier Cust Printer Site]	         = S.[PRINTER_SITE],
               T.[Supplier Cust Printer Region]	         = S.[PRINTER_REGN],
               T.[Supplier Cust Specific Field Label 01]	         = S.[CUST_SPECIFIC_FLD_LBL_01],
               T.[Supplier Cust Specific Field Label 02]	         = S.[CUST_SPECIFIC_FLD_LBL_02],
               T.[Supplier Cust Specific Field Label 03]	         = S.[CUST_SPECIFIC_FLD_LBL_03],
               T.[Supplier Cust Specific Field Label 04]	         = S.[CUST_SPECIFIC_FLD_LBL_04],
               T.[Supplier Cust Specific Field Label 05]	         = S.[CUST_SPECIFIC_FLD_LBL_05],
               T.[Supplier Cust Specific Field Label 06]	         = S.[CUST_SPECIFIC_FLD_LBL_06],
               T.[Supplier Cust Specific Field Label 07]	         = S.[CUST_SPECIFIC_FLD_LBL_07],
               T.[Supplier Cust Specific Field Label 08]	         = S.[CUST_SPECIFIC_FLD_LBL_08],
               T.[Supplier Cust Specific Field Label 09]	         = S.[CUST_SPECIFIC_FLD_LBL_09],
               T.[Supplier Cust Specific Field Label 10]	         = S.[CUST_SPECIFIC_FLD_LBL_10],
               T.[Supplier Cust Specific Field Label 11]	         = S.[CUST_SPECIFIC_FLD_LBL_11],
               T.[Supplier Cust Specific Field Label 12]	         = S.[CUST_SPECIFIC_FLD_LBL_12],
               T.[Supplier Cust Specific Field Label 13]	         = S.[CUST_SPECIFIC_FLD_LBL_13],
               T.[Supplier Cust Specific Field Label 14]	         = S.[CUST_SPECIFIC_FLD_LBL_14],
               T.[Supplier Cust Specific Field Label 15]	         = S.[CUST_SPECIFIC_FLD_LBL_15],
               T.[Supplier Cust Specific Field Label 16]	         = S.[CUST_SPECIFIC_FLD_LBL_16],
               T.[Supplier Cust Specific Field Label 17]	         = S.[CUST_SPECIFIC_FLD_LBL_17],
               T.[Supplier Cust Specific Field Label 18]	         = S.[CUST_SPECIFIC_FLD_LBL_18],
               T.[Supplier Cust Specific Field Label 19]	         = S.[CUST_SPECIFIC_FLD_LBL_19],
               T.[Supplier Cust Specific Field Label 20]	         = S.[CUST_SPECIFIC_FLD_LBL_20],
               T.[Supplier Cust Condition Group 1]	         = S.[CUST_COND_GROUP_1],
               T.[Supplier Cust Industry Code 1]	         = S.[INDUS_CD_1],
               T.[Supplier Cust Industry Code 2]	         = S.[INDUS_CD_2],
               T.[Supplier Cust Industry Description]	         = S.[INDUS_DESC],
               T.[Supplier Cust Industry Code 1 Description]	         = S.[INDUS_CD_1_DESC],
               T.[Supplier Cust Industry Code 2 Description]	         = S.[INDUS_CD_2_DESC],
               T.[Supplier Cust Assignment to Hierarchy]	         = S.[ASSIGN_TO_HIERCHY],
               T.[Supplier Cust Account Group Description]	         = S.[CUST_ACCT_GROUP_DESC],
               T.[Supplier Cust Region Description]	         = S.[REGN_DESC],
               T.[Supplier Cust Country Description]	         = S.[CNTRY_DESC],
               T.[Supplier Cust Transportation Zone Description]	         = S.[TRANSTN_ZONE_DESC],
               T.[Supplier Cust Plant Description]	         = S.[PLNT_DESC],
               T.[Supplier Cust Condition Group Description]	         = S.[CUST_COND_GROUP_DESC],
               T.[Supplier Cust Cental Billing Block]	         = S.[CENTRAL_BILLING_BLK],
               T.[Supplier Cust Cental Billing Block Description]	         = S.[CENTRAL_BILLING_BLK_DESC],
               T.[Supplier Cust Central Delivery Block]	         = S.[CENTRAL_DLVRY_BLK],
               T.[Supplier Cust Central Delivery Block Description]	         = S.[CENTRAL_DLVRY_BLK_DESC],
               T.[Supplier Cust Deletion Indicator]	         = S.[DELETION_IND],
               T.[Supplier Cust Central Posting Block]	         = S.[CENTRAL_PSTNG_BLK],
               T.[Supplier Cust Tax Jurisdiction]	         = S.[TAX_JRSDCTN],
               T.[Supplier Cust Central Sales Block]	         = S.[CENTRAL_SALES_BLK],
               T.[Supplier Cust Central Deletion Indicator]	         = S.[CENTRAL_DELETION_IND],
               T.[Supplier Cust Language Key]	         = S.[LANG_KEY],
               T.[Supplier Cust Trading Partner]	         = S.[TRADING_PRTNR],
               T.[Supplier Cust Trading Partner Description]	         = S.[TRADING_PRTNR_DESC],
               T.[Supplier Cust Annual Sales]	         = S.[ANNUAL_SALES],
               T.[Supplier Cust Annual Sales Year]	         = S.[ANNUAL_SALES_YR],
               T.[Supplier Cust Sales Currency]	         = S.[SALES_CRNCY],
               T.[Supplier Cust Sales Currency Description]	         = S.[SALES_CRNCY_DESC],
               T.[Supplier Cust One Time Account Group]	         = S.[ONE_TM_CUST_ACCT_GROUP],
               T.[Supplier Cust One Time Account Group Description]	         = S.[ONE_TM_CUST_ACCT_GROUP_DESC],
               T.[Supplier Cust One Time Indicator]	         = S.[ONE_TM_CUST_IND],
               T.[Supplier Cust Industry Type]	         = S.[INDUS_TYP],
               T.[Supplier Cust Business Type]	         = S.[BIZ_TYP],
               T.[Supplier Cust DUNS Number]	         = S.[DUNS_NUM],
               T.[Supplier Cust DUNS Plus 4]	         = S.[DUNS_PLUS_4],
               T.[Supplier Cust City Coordinates]	         = S.[CITY_COORDINATES],
               T.[Supplier Cust Tax Number 4 Code]	         = S.[TAX_NUM_4_CD],
               T.[Supplier Cust Attribute 3]	         = S.[ATTRIB_3],
               T.[Supplier Cust Attribute 3 Description]	         = S.[ATTRIB_3_DESC],
               T.[Supplier Cust E-Mail Address]	         = S.[E_MAIL_ADDR],
               T.[Supplier Cust Mobile Number]	         = S.[MOBILE_NUM],
               T.[Supplier Cust Search Term 2]	         = S.[SEARCH_TERM_2],
               T.[Supplier Cust Street 2]	         = S.[STR_2],
               T.[Supplier Cust Street 3]	         = S.[STR_3],
               T.[Supplier Cust Street 4]	         = S.[STR_4],
               T.[Supplier Cust Street 5]	         = S.[STR_5],
               T.[Supplier Cust PO Box]	         = S.[PO_BOX],
               T.[Supplier Cust PO Box Postal Code]	         = S.[PO_BOX_POSTAL_CD],
               T.[Supplier Cust PO Box City]	         = S.[PO_BOX_CITY],
               T.[Supplier Cust Region For PO Box]	         = S.[REGN_FOR_PO_BOX],
               T.[Supplier Cust PO Box Country]	         = S.[PO_BOX_CNTRY],
               T.[Supplier Cust Transport Zone]	         = S.[TRNSPRT_ZONE],
               T.[Supplier Cust Address Notes]	         = S.[ADDR_NOTES],
               T.[Supplier Cust Tax Number 3 Code]	         = S.[TAX_NUM_3],
               T.[Supplier Cust Tax Number 5 Code]	         = S.[TAX_NUM_5],
               T.[Supplier Cust Industry Code 3]	         = S.[INDUS_CD_3],
               T.[Supplier Cust Industry Code 3 Description]	         = S.[INDUS_CD_3_DESC],
               T.[Supplier Cust Industry Code 4]	         = S.[INDUS_CD_4],
               T.[Supplier Cust Industry Code 4 Description]	         = S.[INDUS_CD_4_DESC],
               T.[Supplier Cust Industry Code 5]	         = S.[INDUS_CD_5],
               T.[Supplier Cust Industry Code 5 Description]	         = S.[INDUS_CD_5_DESC],
               T.[Supplier Cust Central Order Block For Customer]	         = S.[CENTRAL_ORDER_BLK_FOR_CUST],
               T.[Supplier Cust Payment Block]	         = S.[PYMT_BLK]


    FROM [GLOBAL_EDW].[Propelis].[SUPPLIER_CUST] AS T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D] AS S
        ON T.[CUST_KEY] = S.[CUST_KEY];

    -- Step 2: Insert new records from mirror to target table
    INSERT INTO [GLOBAL_EDW].[Propelis].[SUPPLIER_CUST] (
                 [CUST_KEY],
                 [Supplier Customer ID],
                 [Supplier Legacy Customer ID],
                 [Supplier Customer Name],
                 [Supplier Cust Line 2 Description],
                 [Supplier Cust Country Code],
                 [Supplier Cust Plant ID],
                 [Supplier Cust Segment ID],
                 [Supplier Cust Industry],
                 [Supplier Cust Vendor ID],
                 [Supplier Cust Customer Group Code],
                 [Supplier Cust Account Group Code],
                 [Supplier Cust Title],
                 [Supplier Cust Search Term],
                 [Supplier Cust Street],
                 [Supplier Cust City],
                 [Supplier Cust Zip Code],
                 [Supplier Cust State Code],
                 [Supplier Cust Region Code],
                 [Supplier Cust Telephone Number 1],
                 [Supplier Cust Telephone Number 2],
                 [Supplier Cust Fax Number Code],
                 [Supplier Cust Tax Number 1 Code],
                 [Supplier Cust Tax Number 2 Code],
                 [Supplier Cust VAT Number Code],
                 [Supplier Cust Credit Limit],
                 [Supplier Cust Bonus Rate],
                 [Supplier Cust Express Station],
                 [Supplier Cust Transportation Zone],
                 [Supplier Cust Printer Location Characteristics],
                 [Supplier Cust Printer Region Characteristics],
                 [Supplier Cust Printer Site Characteristics],
                 [Supplier Cust Customer Created Date],
                 [Supplier Cust Created User ID],
                 [Supplier Cust Customer Updated Date],
                 [Supplier Cust Updated User ID],
                 [Supplier Cust Payment Terms Code],
                 [Supplier Cust Sales Distribution],
                 [Supplier Cust Order Block For Sales Area],
                 [Supplier Cust Delivery Block For Sales Area],
                 [ETL_SRC_SYS_CD],
                 [ETL_EFFECTV_BEGIN_DATE],
                 [ETL_EFFECTV_END_DATE],
                 [ETL_CURR_RCD_IND],
                 [ETL_CREATED_TS],
                 [ETL_UPDTD_TS],
                 [Supplier Cust Corporate Group],
                 [Supplier Cust Classification],
                 [Supplier Cust Classification Description],
                 [Supplier Cust Printer Location],
                 [Supplier Cust Printer Site],
                 [Supplier Cust Printer Region],
                 [Supplier Cust Specific Field Label 01],
                 [Supplier Cust Specific Field Label 02],
                 [Supplier Cust Specific Field Label 03],
                 [Supplier Cust Specific Field Label 04],
                 [Supplier Cust Specific Field Label 05],
                 [Supplier Cust Specific Field Label 06],
                 [Supplier Cust Specific Field Label 07],
                 [Supplier Cust Specific Field Label 08],
                 [Supplier Cust Specific Field Label 09],
                 [Supplier Cust Specific Field Label 10],
                 [Supplier Cust Specific Field Label 11],
                 [Supplier Cust Specific Field Label 12],
                 [Supplier Cust Specific Field Label 13],
                 [Supplier Cust Specific Field Label 14],
                 [Supplier Cust Specific Field Label 15],
                 [Supplier Cust Specific Field Label 16],
                 [Supplier Cust Specific Field Label 17],
                 [Supplier Cust Specific Field Label 18],
                 [Supplier Cust Specific Field Label 19],
                 [Supplier Cust Specific Field Label 20],
                 [Supplier Cust Condition Group 1],
                 [Supplier Cust Industry Code 1],
                 [Supplier Cust Industry Code 2],
                 [Supplier Cust Industry Description],
                 [Supplier Cust Industry Code 1 Description],
                 [Supplier Cust Industry Code 2 Description],
                 [Supplier Cust Assignment to Hierarchy],
                 [Supplier Cust Account Group Description],
                 [Supplier Cust Region Description],
                 [Supplier Cust Country Description],
                 [Supplier Cust Transportation Zone Description],
                 [Supplier Cust Plant Description],
                 [Supplier Cust Condition Group Description],
                 [Supplier Cust Cental Billing Block],
                 [Supplier Cust Cental Billing Block Description],
                 [Supplier Cust Central Delivery Block],
                 [Supplier Cust Central Delivery Block Description],
                 [Supplier Cust Deletion Indicator],
                 [Supplier Cust Central Posting Block],
                 [Supplier Cust Tax Jurisdiction],
                 [Supplier Cust Central Sales Block],
                 [Supplier Cust Central Deletion Indicator],
                 [Supplier Cust Language Key],
                 [Supplier Cust Trading Partner],
                 [Supplier Cust Trading Partner Description],
                 [Supplier Cust Annual Sales],
                 [Supplier Cust Annual Sales Year],
                 [Supplier Cust Sales Currency],
                 [Supplier Cust Sales Currency Description],
                 [Supplier Cust One Time Account Group],
                 [Supplier Cust One Time Account Group Description],
                 [Supplier Cust One Time Indicator],
                 [Supplier Cust Industry Type],
                 [Supplier Cust Business Type],
                 [Supplier Cust DUNS Number],
                 [Supplier Cust DUNS Plus 4],
                 [Supplier Cust City Coordinates],
                 [Supplier Cust Tax Number 4 Code],
                 [Supplier Cust Attribute 3],
                 [Supplier Cust Attribute 3 Description],
                 [Supplier Cust E-Mail Address],
                 [Supplier Cust Mobile Number],
                 [Supplier Cust Search Term 2],
                 [Supplier Cust Street 2],
                 [Supplier Cust Street 3],
                 [Supplier Cust Street 4],
                 [Supplier Cust Street 5],
                 [Supplier Cust PO Box],
                 [Supplier Cust PO Box Postal Code],
                 [Supplier Cust PO Box City],
                 [Supplier Cust Region For PO Box],
                 [Supplier Cust PO Box Country],
                 [Supplier Cust Transport Zone],
                 [Supplier Cust Address Notes],
                 [Supplier Cust Tax Number 3 Code],
                 [Supplier Cust Tax Number 5 Code],
                 [Supplier Cust Industry Code 3],
                 [Supplier Cust Industry Code 3 Description],
                 [Supplier Cust Industry Code 4],
                 [Supplier Cust Industry Code 4 Description],
                 [Supplier Cust Industry Code 5],
                 [Supplier Cust Industry Code 5 Description],
                 [Supplier Cust Central Order Block For Customer],
                 [Supplier Cust Payment Block]


    )
    SELECT
         S.[CUST_KEY],
         S.[CUST_ID],
         S.[LGCY_CUST_ID],
         S.[CUST_NAME],
         S.[CUST_LINE_2_DESC],
         S.[CNTRY_CD],
         S.[PLNT_ID],
         S.[SEG_ID],
         S.[INDUS],
         S.[VNDR_ID],
         S.[CUST_GROUP_CD],
         S.[CUST_ACCT_GROUP_CD],
         S.[TITLE],
         S.[SEARCH_TERM],
         S.[STR],
         S.[CITY_NAME],
         S.[ZIP_CD],
         S.[ST_CD],
         S.[REGN_CD],
         S.[TEL_NUM_1_CD],
         S.[TEL_NUM_2_CD],
         S.[FAX_NUM_CD],
         S.[TAX_NUM_1_CD],
         S.[TAX_NUM_2_CD],
         S.[VAT_NUM_CD],
         S.[CREDIT_LMT],
         S.[BONUS_RT],
         S.[EXPRESS_STATION],
         S.[TRANSTN_ZONE],
         S.[PRINTER_LOC_CHARS],
         S.[PRINTER_REGN_CHARS],
         S.[PRINTER_SITE_CHARS],
         S.[CREATED_DATE],
         S.[CREATED_USR_ID],
         S.[UPDTD_DATE],
         S.[UPDTD_USR_ID],
         S.[PYMT_TRMS_CD],
         S.[SALES_DISTR],
         S.[ORDER_BLK_FOR_SALES_AREA],
         S.[DLVRY_BLK_FOR_SALES_AREA],
         S.[ETL_SRC_SYS_CD],
         S.[ETL_EFFECTV_BEGIN_DATE],
         S.[ETL_EFFECTV_END_DATE],
         S.[ETL_CURR_RCD_IND],
         S.[ETL_CREATED_TS],
         S.[ETL_UPDTD_TS],
         S.[CORPORATE_GROUP],
         S.[CUST_CLSFTN],
         S.[CUST_CLSFTN_DESC],
         S.[PRINTER_LOC],
         S.[PRINTER_SITE],
         S.[PRINTER_REGN],
         S.[CUST_SPECIFIC_FLD_LBL_01],
         S.[CUST_SPECIFIC_FLD_LBL_02],
         S.[CUST_SPECIFIC_FLD_LBL_03],
         S.[CUST_SPECIFIC_FLD_LBL_04],
         S.[CUST_SPECIFIC_FLD_LBL_05],
         S.[CUST_SPECIFIC_FLD_LBL_06],
         S.[CUST_SPECIFIC_FLD_LBL_07],
         S.[CUST_SPECIFIC_FLD_LBL_08],
         S.[CUST_SPECIFIC_FLD_LBL_09],
         S.[CUST_SPECIFIC_FLD_LBL_10],
         S.[CUST_SPECIFIC_FLD_LBL_11],
         S.[CUST_SPECIFIC_FLD_LBL_12],
         S.[CUST_SPECIFIC_FLD_LBL_13],
         S.[CUST_SPECIFIC_FLD_LBL_14],
         S.[CUST_SPECIFIC_FLD_LBL_15],
         S.[CUST_SPECIFIC_FLD_LBL_16],
         S.[CUST_SPECIFIC_FLD_LBL_17],
         S.[CUST_SPECIFIC_FLD_LBL_18],
         S.[CUST_SPECIFIC_FLD_LBL_19],
         S.[CUST_SPECIFIC_FLD_LBL_20],
         S.[CUST_COND_GROUP_1],
         S.[INDUS_CD_1],
         S.[INDUS_CD_2],
         S.[INDUS_DESC],
         S.[INDUS_CD_1_DESC],
         S.[INDUS_CD_2_DESC],
         S.[ASSIGN_TO_HIERCHY],
         S.[CUST_ACCT_GROUP_DESC],
         S.[REGN_DESC],
         S.[CNTRY_DESC],
         S.[TRANSTN_ZONE_DESC],
         S.[PLNT_DESC],
         S.[CUST_COND_GROUP_DESC],
         S.[CENTRAL_BILLING_BLK],
         S.[CENTRAL_BILLING_BLK_DESC],
         S.[CENTRAL_DLVRY_BLK],
         S.[CENTRAL_DLVRY_BLK_DESC],
         S.[DELETION_IND],
         S.[CENTRAL_PSTNG_BLK],
         S.[TAX_JRSDCTN],
         S.[CENTRAL_SALES_BLK],
         S.[CENTRAL_DELETION_IND],
         S.[LANG_KEY],
         S.[TRADING_PRTNR],
         S.[TRADING_PRTNR_DESC],
         S.[ANNUAL_SALES],
         S.[ANNUAL_SALES_YR],
         S.[SALES_CRNCY],
         S.[SALES_CRNCY_DESC],
         S.[ONE_TM_CUST_ACCT_GROUP],
         S.[ONE_TM_CUST_ACCT_GROUP_DESC],
         S.[ONE_TM_CUST_IND],
         S.[INDUS_TYP],
         S.[BIZ_TYP],
         S.[DUNS_NUM],
         S.[DUNS_PLUS_4],
         S.[CITY_COORDINATES],
         S.[TAX_NUM_4_CD],
         S.[ATTRIB_3],
         S.[ATTRIB_3_DESC],
         S.[E_MAIL_ADDR],
         S.[MOBILE_NUM],
         S.[SEARCH_TERM_2],
         S.[STR_2],
         S.[STR_3],
         S.[STR_4],
         S.[STR_5],
         S.[PO_BOX],
         S.[PO_BOX_POSTAL_CD],
         S.[PO_BOX_CITY],
         S.[REGN_FOR_PO_BOX],
         S.[PO_BOX_CNTRY],
         S.[TRNSPRT_ZONE],
         S.[ADDR_NOTES],
         S.[TAX_NUM_3],
         S.[TAX_NUM_5],
         S.[INDUS_CD_3],
         S.[INDUS_CD_3_DESC],
         S.[INDUS_CD_4],
         S.[INDUS_CD_4_DESC],
         S.[INDUS_CD_5],
         S.[INDUS_CD_5_DESC],
         S.[CENTRAL_ORDER_BLK_FOR_CUST],
         S.[PYMT_BLK]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[SUPPLIER_CUST] AS T
        ON T.[CUST_KEY] = S.[CUST_KEY]
    WHERE T.[CUST_KEY] IS NULL;

END