CREATE   PROCEDURE [Propelis].[Proc_DOCUMENT_DATE]
AS
BEGIN
    ------------------------------------------------------------------
    -- Step 1: Load source data into a temp table with a hash key
    ------------------------------------------------------------------
    IF OBJECT_ID('tempdb..#SourceData') IS NOT NULL
        DROP TABLE #SourceData;

    SELECT 
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG],
        HASHBYTES('SHA2_256',
    CONCAT(
        ISNULL(CONVERT(varchar(50), S.[DATE_KEY]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[THE_DATE], 121), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[FISCAL_YR]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[FISCAL_PER_NUM]), ''), '|',
        ISNULL(S.[FISCAL_PER_CD], ''), '|',
        ISNULL(CONVERT(varchar(50), S.[FISCAL_QTR_NUM]), ''), '|',
        ISNULL(S.[FISCAL_QTR_CD], ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CLNDR_YR]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CLNDR_MNTH_NUM]), ''), '|',
        ISNULL(S.[CLNDR_MNTH_CD], ''), '|',
        ISNULL(S.[CLNDR_MNTH_DESC], ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CLNDR_QTR_NUM]), ''), '|',
        ISNULL(S.[CLNDR_QTR_CD], ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CLNDR_WEEKDAY_NUM]), ''), '|',
        ISNULL(S.[CLNDR_WEEKDAY_NAME], ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CLNDR_DAY_IN_MNTH]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CLNDR_DAY_IN_YR]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CLNDR_WK]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CLNDR_MNTH_IN_QTR_NUM]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CLNDR_DAYS_IN_MNTH]), ''), '|',
        ISNULL(S.[ETL_SRC_SYS_CD], ''), '|',
        ISNULL(CONVERT(varchar(50), S.[ETL_CREATED_TS], 121), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[ETL_UPDTD_TS], 121), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_DAY_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_DAY_MINUS_1_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_CLNDR_WK_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_CLNDR_WK_MINUS_1_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_MNTH_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_MNTH_MINUS_1_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_MNTH_MINUS_12_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_QTR_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_QTR_MINUS_1_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_QTR_MINUS_4_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_CLNDR_YR_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_CLNDR_YR_MINUS_1_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_CLNDR_YR_MINUS_2_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_YR_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_YR_MINUS_1_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_YR_MINUS_2_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_CLNDR_YR_PLUS_1_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_YR_PLUS_1_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[DAY_IN_FISCAL_YR]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[IS_WEEKDAY]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[FISCAL_WK]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_MINUS_1_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[FISCAL_WEEKDAY_NUM]), ''), '|',
        ISNULL(S.[FISCAL_WEEKDAY_NAME], ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_MNTH_MINUS_2_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_MINUS_2_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_MINUS_6_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_MINUS_3_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_MINUS_4_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_MINUS_5_FLG]), ''), '|',
        ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_MINUS_7_FLG]), '')
    )
   )AS HashKey
    INTO #SourceData
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] AS S;

    ------------------------------------------------------------------
    -- Step 2: Update changed rows in target (hash mismatch)
    ------------------------------------------------------------------
    UPDATE T
    SET 
        [Entry Create Date]                     = S.[THE_DATE],
        [Entry Create Fiscal Year]              = S.[FISCAL_YR],
        [Entry Create Fiscal Period]            = S.[FISCAL_PER_NUM],
        [Entry Create Fiscal Period Code]       = S.[FISCAL_PER_CD],
        [Entry Create Fiscal Quarter Number]    = S.[FISCAL_QTR_NUM],
        [Entry Create Fiscal Quarter Code]      = S.[FISCAL_QTR_CD],
        [Entry Create Calendar Year]            = S.[CLNDR_YR],
        [Entry Create Calendar Month Number]    = S.[CLNDR_MNTH_NUM],
        [Entry Create Calendar Month Code]      = S.[CLNDR_MNTH_CD],
        [Entry Create Calendar Month Description]= S.[CLNDR_MNTH_DESC],
        [Entry Create Calendar Quarter]         = S.[CLNDR_QTR_NUM],
        [Entry Create Calendar Quarter Code]    = S.[CLNDR_QTR_CD],
        [Entry Create Calendar Weekday Number]  = S.[CLNDR_WEEKDAY_NUM],
        [Entry Create Calendar Weekday Name]    = S.[CLNDR_WEEKDAY_NAME],
        [Entry Create Calendar Day in Month]    = S.[CLNDR_DAY_IN_MNTH],
        [Entry Create Calendar Day in Year]     = S.[CLNDR_DAY_IN_YR],
        [Entry Create Calendar Week]            = S.[CLNDR_WK],
        [Entry Create Calendar Month in Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        [Entry Create Calendar Days in Month]   = S.[CLNDR_DAYS_IN_MNTH],
        [ETL_SRC_SYS_CD]                        = S.[ETL_SRC_SYS_CD],
        [ETL_CREATED_TS]                        = S.[ETL_CREATED_TS],
        [ETL_UPDTD_TS]                          = S.[ETL_UPDTD_TS],
        [Entry Create Current Day Flag]         = S.[CURR_DAY_FLG],
        [Entry Create Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        [Entry Create Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        [Entry Create Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        [Entry Create Current Month Flag]       = S.[CURR_MNTH_FLG],
        [Entry Create Current Month Minus 1 Flag]= S.[CURR_MNTH_MINUS_1_FLG],
        [Entry Create Current Month Minus 12 Flag]= S.[CURR_MNTH_MINUS_12_FLG],
        [Entry Create Current Quarter Flag]     = S.[CURR_QTR_FLG],
        [Entry Create Current Quarter Minus 1 Flag]= S.[CURR_QTR_MINUS_1_FLG],
        [Entry Create Current Quarter Minus 4 Flag]= S.[CURR_QTR_MINUS_4_FLG],
        [Entry Create Current Calendar Year Flag]= S.[CURR_CLNDR_YR_FLG],
        [Entry Create Current Calendar Year Minus 1 Flag]= S.[CURR_CLNDR_YR_MINUS_1_FLG],
        [Entry Create Current Calendar Year Minus 2 Flag]= S.[CURR_CLNDR_YR_MINUS_2_FLG],
        [Entry Create Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        [Entry Create Current Fiscal Year Minus 1 Flag]= S.[CURR_FISCAL_YR_MINUS_1_FLG],
        [Entry Create Current Fiscal Year Minus 2 Flag]= S.[CURR_FISCAL_YR_MINUS_2_FLG],
        [Entry Create Current Calendar Year Plus 1 Flag]= S.[CURR_CLNDR_YR_PLUS_1_FLG],
        [Entry Create Current Fiscal Year Plus 1 Flag]= S.[CURR_FISCAL_YR_PLUS_1_FLG],
        [Entry Create Day in Fiscal Year]       = S.[DAY_IN_FISCAL_YR],
        [IS_WEEKDAY]                            = S.[IS_WEEKDAY],
        [Entry Create Fiscal Week]              = S.[FISCAL_WK],
        [Entry Create Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        [Entry Create Current Fiscal Week Minus 1 Flag]= S.[CURR_FISCAL_WK_MINUS_1_FLG],
        [Entry Create Fiscal Weekday Number]    = S.[FISCAL_WEEKDAY_NUM],
        [Entry Create Fiscal Weekday Name]      = S.[FISCAL_WEEKDAY_NAME],
        [Entry Create Current Month Minus 2 Flag]= S.[CURR_MNTH_MINUS_2_FLG],
        [Entry Create Current Fiscal Week Minus 2 Flag]= S.[CURR_FISCAL_WK_MINUS_2_FLG],
        [Entry Create Current Fiscal Week Minus 6 Flag]= S.[CURR_FISCAL_WK_MINUS_6_FLG],
        [Entry Create Current Fiscal Week Minus 3 Flag]= S.[CURR_FISCAL_WK_MINUS_3_FLG],
        [Entry Create Current Fiscal Week Minus 4 Flag]= S.[CURR_FISCAL_WK_MINUS_4_FLG],
        [Entry Create Current Fiscal Week Minus 5 Flag]= S.[CURR_FISCAL_WK_MINUS_5_FLG],
        [Entry Create Current Fiscal Week Minus 7 Flag]= S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[DOCUMENT_DATE] AS T
    INNER JOIN #SourceData AS S
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE HASHBYTES('SHA2_256',
    CONCAT(
        ISNULL(CONVERT(varchar(50), T.[DATE_KEY]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Date], 121), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Fiscal Year]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Fiscal Period]), ''), '|',
        ISNULL(T.[Entry Create Fiscal Period Code], ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Fiscal Quarter Number]), ''), '|',
        ISNULL(T.[Entry Create Fiscal Quarter Code], ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Calendar Year]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Calendar Month Number]), ''), '|',
        ISNULL(T.[Entry Create Calendar Month Code], ''), '|',
        ISNULL(T.[Entry Create Calendar Month Description], ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Calendar Quarter]), ''), '|',
        ISNULL(T.[Entry Create Calendar Quarter Code], ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Calendar Weekday Number]), ''), '|',
        ISNULL(T.[Entry Create Calendar Weekday Name], ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Calendar Day in Month]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Calendar Day in Year]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Calendar Week]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Calendar Month in Quarter Number]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Calendar Days in Month]), ''), '|',
        ISNULL(T.[ETL_SRC_SYS_CD], ''), '|',
        ISNULL(CONVERT(varchar(50), T.[ETL_CREATED_TS], 121), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[ETL_UPDTD_TS], 121), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Day Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Day Minus 1 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Calendar Week Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Calendar Week Minus 1 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Month Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Month Minus 1 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Month Minus 12 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Quarter Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Quarter Minus 1 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Quarter Minus 4 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Calendar Year Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Calendar Year Minus 1 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Calendar Year Minus 2 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Fiscal Year Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Fiscal Year Minus 1 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Fiscal Year Minus 2 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Calendar Year Plus 1 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Fiscal Year Plus 1 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Day in Fiscal Year]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[IS_WEEKDAY]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Fiscal Week]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Fiscal Week Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Fiscal Week Minus 1 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Fiscal Weekday Number]), ''), '|',
        ISNULL(T.[Entry Create Fiscal Weekday Name], ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Month Minus 2 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Fiscal Week Minus 2 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Fiscal Week Minus 6 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Fiscal Week Minus 3 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Fiscal Week Minus 4 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Fiscal Week Minus 5 Flag]), ''), '|',
        ISNULL(CONVERT(varchar(50), T.[Entry Create Current Fiscal Week Minus 7 Flag]), '')
    )
 )<> S.HashKey;

    ------------------------------------------------------------------
    -- Step 3: Insert only new rows not already in target
    ------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[DOCUMENT_DATE]
    (
        [DATE_KEY],
        [Entry Create Date],
        [Entry Create Fiscal Year],
        [Entry Create Fiscal Period],
        [Entry Create Fiscal Period Code],
        [Entry Create Fiscal Quarter Number],
        [Entry Create Fiscal Quarter Code],
        [Entry Create Calendar Year],
        [Entry Create Calendar Month Number],
        [Entry Create Calendar Month Code],
        [Entry Create Calendar Month Description],
        [Entry Create Calendar Quarter],
        [Entry Create Calendar Quarter Code],
        [Entry Create Calendar Weekday Number],
        [Entry Create Calendar Weekday Name],
        [Entry Create Calendar Day in Month],
        [Entry Create Calendar Day in Year],
        [Entry Create Calendar Week],
        [Entry Create Calendar Month in Quarter Number],
        [Entry Create Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Entry Create Current Day Flag],
        [Entry Create Current Day Minus 1 Flag],
        [Entry Create Current Calendar Week Flag],
        [Entry Create Current Calendar Week Minus 1 Flag],
        [Entry Create Current Month Flag],
        [Entry Create Current Month Minus 1 Flag],
        [Entry Create Current Month Minus 12 Flag],
        [Entry Create Current Quarter Flag],
        [Entry Create Current Quarter Minus 1 Flag],
        [Entry Create Current Quarter Minus 4 Flag],
        [Entry Create Current Calendar Year Flag],
        [Entry Create Current Calendar Year Minus 1 Flag],
        [Entry Create Current Calendar Year Minus 2 Flag],
        [Entry Create Current Fiscal Year Flag],
        [Entry Create Current Fiscal Year Minus 1 Flag],
        [Entry Create Current Fiscal Year Minus 2 Flag],
        [Entry Create Current Calendar Year Plus 1 Flag],
        [Entry Create Current Fiscal Year Plus 1 Flag],
        [Entry Create Day in Fiscal Year],
        [IS_WEEKDAY],
        [Entry Create Fiscal Week],
        [Entry Create Current Fiscal Week Flag],
        [Entry Create Current Fiscal Week Minus 1 Flag],
        [Entry Create Fiscal Weekday Number],
        [Entry Create Fiscal Weekday Name],
        [Entry Create Current Month Minus 2 Flag],
        [Entry Create Current Fiscal Week Minus 2 Flag],
        [Entry Create Current Fiscal Week Minus 6 Flag],
        [Entry Create Current Fiscal Week Minus 3 Flag],
        [Entry Create Current Fiscal Week Minus 4 Flag],
        [Entry Create Current Fiscal Week Minus 5 Flag],
        [Entry Create Current Fiscal Week Minus 7 Flag]
    )
    SELECT 
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM #SourceData AS S
    WHERE NOT EXISTS (
        SELECT 1
        FROM [GLOBAL_EDW].[Propelis].[DOCUMENT_DATE] AS T
        WHERE T.[DATE_KEY] = S.[DATE_KEY]
    );

    ------------------------------------------------------------------
    -- Step 4: Confirmation
    ------------------------------------------------------------------
    PRINT 'Incremental load completed – updated changed rows and inserted new rows.';

END;