CREATE   PROCEDURE [Propelis].[Proc_TECH_COMPLETION_DATE]
AS
BEGIN  
    -------------------------------------------------------------------
    -- Step 1: Update existing records
    -------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Tech Completion Date] = S.[THE_DATE],
        T.[Tech Completion Fiscal Year] = S.[FISCAL_YR],
        T.[Tech Completion Fiscal Period Number] = S.[FISCAL_PER_NUM],
        T.[Tech Completion Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Tech Completion Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Tech Completion Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Tech Completion Calendar Year] = S.[CLNDR_YR],
        T.[Tech Completion Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Tech Completion Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Tech Completion Calendar Month Description] = S.[CLNDR_MNTH_DESC],
        T.[Tech Completion Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[Tech Completion Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Tech Completion Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Tech Completion Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Tech Completion Calendar Day In Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Tech Completion Calendar Day In Year] = S.[CLNDR_DAY_IN_YR],
        T.[Tech Completion Calendar Week] = S.[CLNDR_WK],
        T.[Tech Completion Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Tech Completion Calendar Days In Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Tech Completion Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Tech Completion Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Tech Completion Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Tech Completion Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Tech Completion Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Tech Completion Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Tech Completion Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Tech Completion Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Tech Completion Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Tech Completion Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Tech Completion Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Tech Completion Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Tech Completion Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Tech Completion Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Tech Completion Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Tech Completion Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Tech Completion Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Tech Completion Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG], 
        T.[Tech Completion Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Tech Completion Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Tech Completion Fiscal Week] = S.[FISCAL_WK],
        T.[Tech Completion Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Tech Completion Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Tech Completion Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Tech Completion Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Tech Completion Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Tech Completion Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Tech Completion Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Tech Completion Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Tech Completion Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Tech Completion Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Tech Completion Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[TECH_COMPLETION_DATE] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];
 
    -------------------------------------------------------------------
    -- Step 2: Insert new records
    -------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[TECH_COMPLETION_DATE] (
        [DATE_KEY],
        [Tech Completion Date],
        [Tech Completion Fiscal Year],
        [Tech Completion Fiscal Period Number],
        [Tech Completion Fiscal Period Code],
        [Tech Completion Fiscal Quarter Number],
        [Tech Completion Fiscal Quarter Code],
        [Tech Completion Calendar Year],
        [Tech Completion Calendar Month Number],
        [Tech Completion Calendar Month Code],
        [Tech Completion Calendar Month Description],
        [Tech Completion Calendar Quarter Number],
        [Tech Completion Calendar Quarter Code],
        [Tech Completion Calendar Weekday Number],
        [Tech Completion Calendar Weekday Name],
        [Tech Completion Calendar Day In Month],
        [Tech Completion Calendar Day In Year],
        [Tech Completion Calendar Week],
        [Tech Completion Calendar Month In Quarter Number],
        [Tech Completion Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Tech Completion Current Day Flag],
        [Tech Completion Current Day Minus 1 Flag],
        [Tech Completion Current Calendar Week Flag],
        [Tech Completion Current Calendar Week Minus 1 Flag],
        [Tech Completion Current Month Flag],
        [Tech Completion Current Month Minus 1 Flag],
        [Tech Completion Current Month Minus 12 Flag],
        [Tech Completion Current Quarter Flag],
        [Tech Completion Current Quarter Minus 1 Flag],
        [Tech Completion Current Quarter Minus 4 Flag],
        [Tech Completion Current Calendar Year Flag],
        [Tech Completion Current Calendar Year Minus 1 Flag],
        [Tech Completion Current Calendar Year Minus 2 Flag],
        [Tech Completion Current Fiscal Year Flag],
        [Tech Completion Current Fiscal Year Minus 1 Flag],
        [Tech Completion Current Fiscal Year Minus 2 Flag],
        [Tech Completion Current Calendar Year Plus 1 Flag],
        [Tech Completion Current Fiscal Year Plus 1 Flag],
        [Tech Completion Day In Fiscal Year],
        [Tech Completion Date Is Weekday],
        [Tech Completion Fiscal Week],
        [Tech Completion Current Fiscal Week Flag],
        [Tech Completion Current Fiscal Week Minus 1 Flag],
        [Tech Completion Fiscal Weekday Number],
        [Tech Completion Fiscal Weekday Name],
        [Tech Completion Current Month Minus 2 Flag],
        [Tech Completion Current Fiscal Week Minus 2 Flag],
        [Tech Completion Current Fiscal Week Minus 6 Flag],
        [Tech Completion Current Fiscal Week Minus 3 Flag],
        [Tech Completion Current Fiscal Week Minus 4 Flag],
        [Tech Completion Current Fiscal Week Minus 5 Flag],
        [Tech Completion Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[TECH_COMPLETION_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
END