CREATE   PROCEDURE [Propelis].[Proc_REQD_DELVRY_DATE]
AS
BEGIN
    ------------------------------------------------------------------
    -- Step 1: Load source data into a temp table with a hash key
    ------------------------------------------------------------------
    IF OBJECT_ID('tempdb..#SourceData') IS NOT NULL
        DROP TABLE #SourceData;

    SELECT 
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG],
        HASHBYTES('SHA2_256',
            CONCAT(
                ISNULL(CONVERT(varchar(50), S.[DATE_KEY]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[THE_DATE], 121), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[FISCAL_YR]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[FISCAL_PER_NUM]), ''), '|',
                ISNULL(S.[FISCAL_PER_CD], ''), '|',
                ISNULL(CONVERT(varchar(50), S.[FISCAL_QTR_NUM]), ''), '|',
                ISNULL(S.[FISCAL_QTR_CD], ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CLNDR_YR]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CLNDR_MNTH_NUM]), ''), '|',
                ISNULL(S.[CLNDR_MNTH_CD], ''), '|',
                ISNULL(S.[CLNDR_MNTH_DESC], ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CLNDR_QTR_NUM]), ''), '|',
                ISNULL(S.[CLNDR_QTR_CD], ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CLNDR_WEEKDAY_NUM]), ''), '|',
                ISNULL(S.[CLNDR_WEEKDAY_NAME], ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CLNDR_DAY_IN_MNTH]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CLNDR_DAY_IN_YR]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CLNDR_WK]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CLNDR_MNTH_IN_QTR_NUM]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CLNDR_DAYS_IN_MNTH]), ''), '|',
                ISNULL(S.[ETL_SRC_SYS_CD], ''), '|',
                ISNULL(CONVERT(varchar(50), S.[ETL_CREATED_TS], 121), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[ETL_UPDTD_TS], 121), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_DAY_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_DAY_MINUS_1_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_CLNDR_WK_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_CLNDR_WK_MINUS_1_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_MNTH_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_MNTH_MINUS_1_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_MNTH_MINUS_12_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_QTR_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_QTR_MINUS_1_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_QTR_MINUS_4_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_CLNDR_YR_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_CLNDR_YR_MINUS_1_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_CLNDR_YR_MINUS_2_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_YR_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_YR_MINUS_1_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_YR_MINUS_2_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_CLNDR_YR_PLUS_1_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_YR_PLUS_1_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[DAY_IN_FISCAL_YR]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[IS_WEEKDAY]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[FISCAL_WK]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_MINUS_1_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[FISCAL_WEEKDAY_NUM]), ''), '|',
                ISNULL(S.[FISCAL_WEEKDAY_NAME], ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_MNTH_MINUS_2_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_MINUS_2_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_MINUS_6_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_MINUS_3_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_MINUS_4_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_MINUS_5_FLG]), ''), '|',
                ISNULL(CONVERT(varchar(50), S.[CURR_FISCAL_WK_MINUS_7_FLG]), '')
            )
        ) AS HashKey
    INTO #SourceData
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] AS S;

    ------------------------------------------------------------------
    -- Step 2: Update changed rows in target (hash mismatch)
    ------------------------------------------------------------------
    UPDATE T
    SET 
        [Required Delivery Date]                        = S.[THE_DATE],
        [Required Delivery Fiscal Year]                 = S.[FISCAL_YR],
        [Required Delivery Fiscal Period]               = S.[FISCAL_PER_NUM],
        [Required Fiscal Period Code]                   = S.[FISCAL_PER_CD],
        [Required Fiscal Quarter]                       = S.[FISCAL_QTR_NUM],
        [Required Fiscal Quarter Code]                  = S.[FISCAL_QTR_CD],
        [Required Calendar Year]                        = S.[CLNDR_YR],
        [Required Calendar Month Number]                = S.[CLNDR_MNTH_NUM],
        [Required Calendar Month Code]                  = S.[CLNDR_MNTH_CD],
        [Required Calendar Month Desc]                  = S.[CLNDR_MNTH_DESC],
        [Required Calendar Quarter]                     = S.[CLNDR_QTR_NUM],
        [Required Calendar Quarter Code]                = S.[CLNDR_QTR_CD],
        [Required Calendar Weekday Number]              = S.[CLNDR_WEEKDAY_NUM],
        [Required Calendar Weekday Name]                = S.[CLNDR_WEEKDAY_NAME],
        [Required Calendar Day]                         = S.[CLNDR_DAY_IN_MNTH],
        [Required Calendar Day in Year]                 = S.[CLNDR_DAY_IN_YR],
        [Required Calendar Week]                        = S.[CLNDR_WK],
        [Required Calendar Month in Quarter Number]     = S.[CLNDR_MNTH_IN_QTR_NUM],
        [Required Calendar Days in Month]               = S.[CLNDR_DAYS_IN_MNTH],
        [ETL_SRC_SYS_CD]                                = S.[ETL_SRC_SYS_CD],
        [ETL_CREATED_TS]                                = S.[ETL_CREATED_TS],
        [ETL_UPDTD_TS]                                  = S.[ETL_UPDTD_TS],
        [CURR_DAY_FLG]                                  = S.[CURR_DAY_FLG],
        [Required Current Day Minus 1 Flag]             = S.[CURR_DAY_MINUS_1_FLG],
        [Required Current Calendar Week Flag]           = S.[CURR_CLNDR_WK_FLG],
        [Required Current Calendar Week Minus 1 Flag]   = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        [Required Current Month Flag]                   = S.[CURR_MNTH_FLG],
        [Required Current Month Minus 1 Flag]           = S.[CURR_MNTH_MINUS_1_FLG],
        [Required Current Month Minus 12 Flag]          = S.[CURR_MNTH_MINUS_12_FLG],
        [Required Current Quarter Flag]                 = S.[CURR_QTR_FLG],
        [Required Current Quarter Minus 1 Flag]         = S.[CURR_QTR_MINUS_1_FLG],
        [Required Current Quarter Minus 4 Flag]         = S.[CURR_QTR_MINUS_4_FLG],
        [Required Current Calendar Year Flag]           = S.[CURR_CLNDR_YR_FLG],
        [Required Current Calendar Year Minus 1 Flag]   = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        [Required Current Calendar Year Minus 2 Flag]   = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        [Required Current Fiscal Year Flag]             = S.[CURR_FISCAL_YR_FLG],
        [Required Current Fiscal Year Minus 1 Flag]     = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        [Required Current Fiscal Year Minus 2 Flag]     = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        [Required Current Calendar Year Plus 1 Flag]    = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        [Required Current Fiscal Year Plus 1 Flag]      = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        [Required Day In Fiscal Year]                   = S.[DAY_IN_FISCAL_YR],
        [Required Date Is Weekday]                      = S.[IS_WEEKDAY],
        [Required Fiscal Week]                          = S.[FISCAL_WK],
        [Required Current Fiscal Week Flag]             = S.[CURR_FISCAL_WK_FLG],
        [Required Current Fiscal Week Minus 1 Flag]     = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        [Required Fiscal Weekday Number]                = S.[FISCAL_WEEKDAY_NUM],
        [Required Fiscal Weekday Name]                  = S.[FISCAL_WEEKDAY_NAME],
        [Required Current Month Minus 2 Flag]           = S.[CURR_MNTH_MINUS_2_FLG],
        [Required Current Fiscal Week Minus 2 Flag]     = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        [Required Current Fiscal Week Minus 6 Flag]     = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        [Required Current Fiscal Week Minus 3 Flag]     = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        [Required Current Fiscal Week Minus 4 Flag]     = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        [Required Current Fiscal Week Minus 5 Flag]     = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        [Required Current Fiscal Week Minus 7 Flag]     = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[REQD_DELVRY_DATE] AS T
    INNER JOIN #SourceData AS S
        ON T.[DATE_KEY] = S.[DATE_KEY]
   WHERE HASHBYTES('SHA2_256',
        CONCAT(
            ISNULL(CONVERT(varchar(50), T.[DATE_KEY]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Delivery Date], 121), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Delivery Fiscal Year]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Delivery Fiscal Period]), ''), '|',
            ISNULL(T.[Required Fiscal Period Code], ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Fiscal Quarter]), ''), '|',
            ISNULL(T.[Required Fiscal Quarter Code], ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Calendar Year]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Calendar Month Number]), ''), '|',
            ISNULL(T.[Required Calendar Month Code], ''), '|',
            ISNULL(T.[Required Calendar Month Desc], ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Calendar Quarter]), ''), '|',
            ISNULL(T.[Required Calendar Quarter Code], ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Calendar Weekday Number]), ''), '|',
            ISNULL(T.[Required Calendar Weekday Name], ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Calendar Day]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Calendar Day in Year]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Calendar Week]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Calendar Month in Quarter Number]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Calendar Days in Month]), ''), '|',
            ISNULL(T.[ETL_SRC_SYS_CD], ''), '|',
            ISNULL(CONVERT(varchar(50), T.[ETL_CREATED_TS], 121), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[ETL_UPDTD_TS], 121), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[CURR_DAY_FLG]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Day Minus 1 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Calendar Week Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Calendar Week Minus 1 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Month Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Month Minus 1 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Month Minus 12 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Quarter Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Quarter Minus 1 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Quarter Minus 4 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Calendar Year Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Calendar Year Minus 1 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Calendar Year Minus 2 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Fiscal Year Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Fiscal Year Minus 1 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Fiscal Year Minus 2 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Calendar Year Plus 1 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Fiscal Year Plus 1 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Day In Fiscal Year]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Date Is Weekday]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Fiscal Week]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Fiscal Week Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Fiscal Week Minus 1 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Fiscal Weekday Number]), ''), '|',
            ISNULL(T.[Required Fiscal Weekday Name], ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Month Minus 2 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Fiscal Week Minus 2 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Fiscal Week Minus 6 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Fiscal Week Minus 3 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Fiscal Week Minus 4 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Fiscal Week Minus 5 Flag]), ''), '|',
            ISNULL(CONVERT(varchar(50), T.[Required Current Fiscal Week Minus 7 Flag]), '')
        )
    ) <> S.HashKey

INSERT INTO [GLOBAL_EDW].[Propelis].[REQD_DELVRY_DATE]
(
    [DATE_KEY],
    [Required Delivery Date],
    [Required Delivery Fiscal Year],
    [Required Delivery Fiscal Period],
    [Required Fiscal Period Code],
    [Required Fiscal Quarter],
    [Required Fiscal Quarter Code],
    [Required Calendar Year],
    [Required Calendar Month Number],
    [Required Calendar Month Code],
    [Required Calendar Month Desc],
    [Required Calendar Quarter],
    [Required Calendar Quarter Code],
    [Required Calendar Weekday Number],
    [Required Calendar Weekday Name],
    [Required Calendar Day],
    [Required Calendar Day in Year],
    [Required Calendar Week],
    [Required Calendar Month in Quarter Number],
    [Required Calendar Days in Month],
    [ETL_SRC_SYS_CD],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [CURR_DAY_FLG],
    [Required Current Day Minus 1 Flag],
    [Required Current Calendar Week Flag],
    [Required Current Calendar Week Minus 1 Flag],
    [Required Current Month Flag],
    [Required Current Month Minus 1 Flag],
    [Required Current Month Minus 12 Flag],
    [Required Current Quarter Flag],
    [Required Current Quarter Minus 1 Flag],
    [Required Current Quarter Minus 4 Flag],
    [Required Current Calendar Year Flag],
    [Required Current Calendar Year Minus 1 Flag],
    [Required Current Calendar Year Minus 2 Flag],
    [Required Current Fiscal Year Flag],
    [Required Current Fiscal Year Minus 1 Flag],
    [Required Current Fiscal Year Minus 2 Flag],
    [Required Current Calendar Year Plus 1 Flag],
    [Required Current Fiscal Year Plus 1 Flag],
    [Required Day In Fiscal Year],
    [Required Date Is Weekday],
    [Required Fiscal Week],
    [Required Current Fiscal Week Flag],
    [Required Current Fiscal Week Minus 1 Flag],
    [Required Fiscal Weekday Number],
    [Required Fiscal Weekday Name],
    [Required Current Month Minus 2 Flag],
    [Required Current Fiscal Week Minus 2 Flag],
    [Required Current Fiscal Week Minus 6 Flag],
    [Required Current Fiscal Week Minus 3 Flag],
    [Required Current Fiscal Week Minus 4 Flag],
    [Required Current Fiscal Week Minus 5 Flag],
    [Required Current Fiscal Week Minus 7 Flag]
)
SELECT 
    S.[DATE_KEY],
    S.[THE_DATE],
    S.[FISCAL_YR],
    S.[FISCAL_PER_NUM],
    S.[FISCAL_PER_CD],
    S.[FISCAL_QTR_NUM],
    S.[FISCAL_QTR_CD],
    S.[CLNDR_YR],
    S.[CLNDR_MNTH_NUM],
    S.[CLNDR_MNTH_CD],
    S.[CLNDR_MNTH_DESC],
    S.[CLNDR_QTR_NUM],
    S.[CLNDR_QTR_CD],
    S.[CLNDR_WEEKDAY_NUM],
    S.[CLNDR_WEEKDAY_NAME],
    S.[CLNDR_DAY_IN_MNTH],
    S.[CLNDR_DAY_IN_YR],
    S.[CLNDR_WK],
    S.[CLNDR_MNTH_IN_QTR_NUM],
    S.[CLNDR_DAYS_IN_MNTH],
    S.[ETL_SRC_SYS_CD],
    S.[ETL_CREATED_TS],
    S.[ETL_UPDTD_TS],
    S.[CURR_DAY_FLG],
    S.[CURR_DAY_MINUS_1_FLG],
    S.[CURR_CLNDR_WK_FLG],
    S.[CURR_CLNDR_WK_MINUS_1_FLG],
    S.[CURR_MNTH_FLG],
    S.[CURR_MNTH_MINUS_1_FLG],
    S.[CURR_MNTH_MINUS_12_FLG],
    S.[CURR_QTR_FLG],
    S.[CURR_QTR_MINUS_1_FLG],
    S.[CURR_QTR_MINUS_4_FLG],
    S.[CURR_CLNDR_YR_FLG],
    S.[CURR_CLNDR_YR_MINUS_1_FLG],
    S.[CURR_CLNDR_YR_MINUS_2_FLG],
    S.[CURR_FISCAL_YR_FLG],
    S.[CURR_FISCAL_YR_MINUS_1_FLG],
    S.[CURR_FISCAL_YR_MINUS_2_FLG],
    S.[CURR_CLNDR_YR_PLUS_1_FLG],
    S.[CURR_FISCAL_YR_PLUS_1_FLG],
    S.[DAY_IN_FISCAL_YR],
    S.[IS_WEEKDAY],
    S.[FISCAL_WK],
    S.[CURR_FISCAL_WK_FLG],
    S.[CURR_FISCAL_WK_MINUS_1_FLG],
    S.[FISCAL_WEEKDAY_NUM],
    S.[FISCAL_WEEKDAY_NAME],
    S.[CURR_MNTH_MINUS_2_FLG],
    S.[CURR_FISCAL_WK_MINUS_2_FLG],
    S.[CURR_FISCAL_WK_MINUS_6_FLG],
    S.[CURR_FISCAL_WK_MINUS_3_FLG],
    S.[CURR_FISCAL_WK_MINUS_4_FLG],
    S.[CURR_FISCAL_WK_MINUS_5_FLG],
    S.[CURR_FISCAL_WK_MINUS_7_FLG]
FROM #SourceData AS S
WHERE NOT EXISTS (
    SELECT 1
    FROM [GLOBAL_EDW].[Propelis].[REQD_DELVRY_DATE] AS T
    WHERE T.[DATE_KEY] = S.[DATE_KEY]
);

 ------------------------------------------------------------------
    -- Step 4: Confirmation
    ------------------------------------------------------------------
    PRINT 'Incremental load completed – updated changed rows and inserted new rows.';

END;