CREATE   PROCEDURE [Propelis].[Proc_BRAND_OWNER_CUST]
AS
BEGIN
    -- Step 1: Update existing records in target table
    UPDATE T
    SET
                T.[CUST_KEY]	                                        = S.[CUST_KEY],
                T.[Brand Owner Customer ID]	                            = S.[CUST_ID],
                T.[Brand Owner Customer Legacy ID]	                    = S.[LGCY_CUST_ID],
                T.[Brand Owner Customer Name]	                        = S.[CUST_NAME],
                T.[Brand Owner Cust Line 2 Description]	                = S.[CUST_LINE_2_DESC],
                T.[Brand Owner Cust Country Code]	                    = S.[CNTRY_CD],
                T.[Brand Owner Cust Plant ID]	                        = S.[PLNT_ID],
                T.[Brand Owner Cust Segment ID]	                        = S.[SEG_ID],
                T.[Brand Owner Cust Industry]	                        = S.[INDUS],
                T.[Brand Owner Cust Vendor ID]	                        = S.[VNDR_ID],
                T.[Brand Owner Cust Group Code]	                        = S.[CUST_GROUP_CD],
                T.[Brand Owner Cust Account Group Code]	                = S.[CUST_ACCT_GROUP_CD],
                T.[Brand Owner Cust Title]	                            = S.[TITLE],
                T.[Brand Owner Cust Search Term]	                    = S.[SEARCH_TERM],
                T.[Brand Owner Cust Street]	                            = S.[STR],
                T.[Brand Owner Cust City]	                            = S.[CITY_NAME],
                T.[Brand Owner Cust Zip Code]	                        = S.[ZIP_CD],
                T.[Brand Owner Cust State Code]	                        = S.[ST_CD],
                T.[Brand Owner Cust Region Code]	                    = S.[REGN_CD],
                T.[Brand Owner Cust Telephone Number 1]	                = S.[TEL_NUM_1_CD],
                T.[Brand Owner Cust Telephone Number 2]	                = S.[TEL_NUM_2_CD],
                T.[Brand Owner Cust Fax Number Code]	                = S.[FAX_NUM_CD],
                T.[Brand Owner Cust Tax Number 1 Code]	                = S.[TAX_NUM_1_CD],
                T.[Brand Owner Cust Tax Number 2 Code]	                = S.[TAX_NUM_2_CD],
                T.[Brand Owner Cust VAT Number Code]	                = S.[VAT_NUM_CD],
                T.[Brand Owner Cust Credit Limit]	                    = S.[CREDIT_LMT],
                T.[Brand Owner Cust Bonus Rate]	                        = S.[BONUS_RT],
                T.[Brand Owner Cust Express Station]	                = S.[EXPRESS_STATION],
                T.[Brand Owner Cust Transportation Zone]	            = S.[TRANSTN_ZONE],
                T.[Brand Owner Cust Printer Location Characteristics]	= S.[PRINTER_LOC_CHARS],
                T.[Brand Owner Cust Printer Region Characteristics]	    = S.[PRINTER_REGN_CHARS],
                T.[Brand Owner Cust Printer Site Characteristics]	    = S.[PRINTER_SITE_CHARS],
                T.[Brand Owner Cust Created Date]	                    = S.[CREATED_DATE],
                T.[Brand Owner Cust Created User ID]	                = S.[CREATED_USR_ID],
                T.[Brand Owner Cust Updated Date]	                    = S.[UPDTD_DATE],
                T.[Brand Owner Cust Updated User ID]	                 = S.[UPDTD_USR_ID],
                T.[Brand Owner Cust Payment Terms Code]	                 = S.[PYMT_TRMS_CD],
                T.[Brand Owner Cust Sales Distribution]	                 = S.[SALES_DISTR],
                T.[Brand Owner Cust Order Block For Sales Area]	         = S.[ORDER_BLK_FOR_SALES_AREA],
                T.[Brand Owner Cust Delivery Block For Sales Area]	     = S.[DLVRY_BLK_FOR_SALES_AREA],
                T.[ETL_SRC_SYS_CD]	                                     = S.[ETL_SRC_SYS_CD],
                T.[ETL_EFFECTV_BEGIN_DATE]	                             = S.[ETL_EFFECTV_BEGIN_DATE],
                T.[ETL_EFFECTV_END_DATE]	                             = S.[ETL_EFFECTV_END_DATE],
                T.[ETL_CURR_RCD_IND]	                                 = S.[ETL_CURR_RCD_IND],
                T.[ETL_CREATED_TS]	                                     = S.[ETL_CREATED_TS],
                T.[ETL_UPDTD_TS]	                                     = S.[ETL_UPDTD_TS],
                T.[Brand Owner Cust Corporate Group]	                 = S.[CORPORATE_GROUP],
                T.[Brand Owner Customer Classification]	                 = S.[CUST_CLSFTN],
                T.[Brand Owner Cust Classification Description]	         = S.[CUST_CLSFTN_DESC],
                T.[Brand Owner Cust Printer Location]	                 = S.[PRINTER_LOC],
                T.[Brand Owner Cust Printer Site]	                     = S.[PRINTER_SITE],
                T.[Brand Owner Cust Printer Region]	                     = S.[PRINTER_REGN],
                T.[Brand Owner Cust Specific Field Label 01]	         = S.[CUST_SPECIFIC_FLD_LBL_01],
                T.[Brand Owner Cust Specific Field Label 02]	         = S.[CUST_SPECIFIC_FLD_LBL_02],
                T.[Brand Owner Cust Specific Field Label 03]	         = S.[CUST_SPECIFIC_FLD_LBL_03],
                T.[Brand Owner Cust Specific Field Label 04]	         = S.[CUST_SPECIFIC_FLD_LBL_04],
                T.[Brand Owner Cust Specific Field Label 05]	         = S.[CUST_SPECIFIC_FLD_LBL_05],
                T.[Brand Owner Cust Specific Field Label 06]	         = S.[CUST_SPECIFIC_FLD_LBL_06],
                T.[Brand Owner Cust Specific Field Label 07]	         = S.[CUST_SPECIFIC_FLD_LBL_07],
                T.[Brand Owner Cust Specific Field Label 08]	         = S.[CUST_SPECIFIC_FLD_LBL_08],
                T.[Brand Owner Cust Specific Field Label 09]	         = S.[CUST_SPECIFIC_FLD_LBL_09],
                T.[Brand Owner Cust Specific Field Label 10]	         = S.[CUST_SPECIFIC_FLD_LBL_10],
                T.[Brand Owner Cust Specific Field Label 11]	         = S.[CUST_SPECIFIC_FLD_LBL_11],
                T.[Brand Owner Cust Specific Field Label 12]	         = S.[CUST_SPECIFIC_FLD_LBL_12],
                T.[Brand Owner Cust Specific Field Label 13]	         = S.[CUST_SPECIFIC_FLD_LBL_13],
                T.[Brand Owner Cust Specific Field Label 14]	         = S.[CUST_SPECIFIC_FLD_LBL_14],
                T.[Brand Owner Cust Specific Field Label 15]	         = S.[CUST_SPECIFIC_FLD_LBL_15],
                T.[Brand Owner Cust Specific Field Label 16]	         = S.[CUST_SPECIFIC_FLD_LBL_16],
                T.[Brand Owner Cust Specific Field Label 17]	         = S.[CUST_SPECIFIC_FLD_LBL_17],
                T.[Brand Owner Cust Specific Field Label 18]	         = S.[CUST_SPECIFIC_FLD_LBL_18],
                T.[Brand Owner Cust Specific Field Label 19]	         = S.[CUST_SPECIFIC_FLD_LBL_19],
                T.[Brand Owner Cust Specific Field Label 20]	         = S.[CUST_SPECIFIC_FLD_LBL_20],
                T.[Brand Owner Cust Condition Group 1]	                 = S.[CUST_COND_GROUP_1],
                T.[Brand Owner Cust Industry Code 1]	                 = S.[INDUS_CD_1],
                T.[Brand Owner Cust Industry Code 2]	                 = S.[INDUS_CD_2],
                T.[Brand Owner Cust Industry Description]	             = S.[INDUS_DESC],
                T.[Brand Owner Cust Industry Code 1 Description]	     = S.[INDUS_CD_1_DESC],
                T.[Brand Owner Cust Industry Code 2 Description]	     = S.[INDUS_CD_2_DESC],
                T.[Brand Owner Assignment to Hierarchy]	                 = S.[ASSIGN_TO_HIERCHY],
                T.[Brand Owner Cust Account Group Description]	         = S.[CUST_ACCT_GROUP_DESC],
                T.[Brand Owner Cust Region Description]	                 = S.[REGN_DESC],
                T.[Brand Owner Cust Country Description]	             = S.[CNTRY_DESC],
                T.[Brand Owner Cust Transportation Zone Description]	 = S.[TRANSTN_ZONE_DESC],
                T.[Brand Owner Cust Plant Description]	                 = S.[PLNT_DESC],
                T.[Brand Owner Cust Condition Group Description]	     = S.[CUST_COND_GROUP_DESC],
                T.[Brand Owner Cust Cental Branding Block]	             = S.[CENTRAL_BILLING_BLK],
                T.[Brand Owner Cust Cental Branding Block Description]	 = S.[CENTRAL_BILLING_BLK_DESC],
                T.[Brand Owner Cust Central Delivery Block]	             = S.[CENTRAL_DLVRY_BLK],
                T.[Brand Owner Cust Central Delivery Block Description]	 = S.[CENTRAL_DLVRY_BLK_DESC],
                T.[Brand Owner Cust Deletion IndicaOwnerr]	             = S.[DELETION_IND],
                T.[Brand Owner Cust Central Posting Block]	             = S.[CENTRAL_PSTNG_BLK],
                T.[Brand Owner Cust Tax Jurisdiction]	                 = S.[TAX_JRSDCTN],
                T.[Brand Owner Cust Central Sales Block]	             = S.[CENTRAL_SALES_BLK],
                T.[Brand Owner Cust Central Deletion Indicator]	         = S.[CENTRAL_DELETION_IND],
                T.[Brand Owner Cust Language Key]	                     = S.[LANG_KEY],
                T.[Brand Owner Cust Trading Partner]	                 = S.[TRADING_PRTNR],
                T.[Brand Owner Cust Trading Partner Description]	     = S.[TRADING_PRTNR_DESC],
                T.[Brand Owner Cust Annual Sales]	                     = S.[ANNUAL_SALES],
                T.[Brand Owner Cust Annual Sales Year]	                 = S.[ANNUAL_SALES_YR],
                T.[Brand Owner Cust Sales Currency]	                     = S.[SALES_CRNCY],
                T.[Brand Owner Cust Sales Currency Description]	         = S.[SALES_CRNCY_DESC],
                T.[Brand Owner Cust One Time Account Group]	             = S.[ONE_TM_CUST_ACCT_GROUP],
                T.[Brand Owner Cust One Time Account Group Description]  = S.[ONE_TM_CUST_ACCT_GROUP_DESC],
                T.[Brand Owner Cust One Time Indicator]	                 = S.[ONE_TM_CUST_IND],
                T.[Brand Owner Cust Industry Type]	                     = S.[INDUS_TYP],
                T.[Brand Owner Cust Business Type]	                     = S.[BIZ_TYP],
                T.[Brand Owner Cust DUNS Number]	                     = S.[DUNS_NUM],
                T.[Brand Owner Cust DUNS Plus 4]	                     = S.[DUNS_PLUS_4],
                T.[Brand Owner City Coordinates]	                     = S.[CITY_COORDINATES],
                T.[Brand Owner Cust Tax Number 4 Code]	                 = S.[TAX_NUM_4_CD],
                T.[Brand Owner Cust Attribute 3]	                     = S.[ATTRIB_3],
                T.[Brand Owner Cust Attribute 3 Description]   	         = S.[ATTRIB_3_DESC],
                T.[Brand Owner Cust E-Mail Address]	                     = S.[E_MAIL_ADDR],
                T.[Brand Owner Cust Mobile Number]	                     = S.[MOBILE_NUM],
                T.[Brand Owner Cust Search Term 2]	                     = S.[SEARCH_TERM_2],
                T.[Brand Owner Cust Street 2]	                         = S.[STR_2],
                T.[Brand Owner Cust Street 3]	                         = S.[STR_3],
                T.[Brand Owner Cust Street 4]	                         = S.[STR_4],
                T.[Brand Owner Cust Street 5]	                         = S.[STR_5],
                T.[Brand Owner Cust PO Box]	                             = S.[PO_BOX],
                T.[Brand Owner Cust PO Box Postal Code]	                 = S.[PO_BOX_POSTAL_CD],
                T.[Brand Owner Cust PO Box City]	                     = S.[PO_BOX_CITY],
                T.[Brand Owner Cust Region For PO Box]	                 = S.[REGN_FOR_PO_BOX],
                T.[Brand Owner Cust PO Box Country]	                     = S.[PO_BOX_CNTRY],
                T.[Brand Owner Cust Transport Zone]	                     = S.[TRNSPRT_ZONE],
                T.[Brand Owner Cust Address Notes]	                     = S.[ADDR_NOTES],
                T.[Brand Owner Cust Tax Number 3 Code]	                 = S.[TAX_NUM_3],
                T.[Brand Owner Cust Tax Number 5 Code]	                 = S.[TAX_NUM_5],
                T.[Brand Owner Cust Industry Code 3]	                 = S.[INDUS_CD_3],
                T.[Brand Owner Cust Industry Code 3 Description]	     = S.[INDUS_CD_3_DESC],
                T.[Brand Owner Cust Industry Code 4]	                 = S.[INDUS_CD_4],
                T.[Brand Owner Cust Industry Code 4 Description]	     = S.[INDUS_CD_4_DESC],
                T.[Brand Owner Cust Industry Code 5]	                 = S.[INDUS_CD_5],
                T.[Brand Owner Cust Industry Code 5 Description]	     = S.[INDUS_CD_5_DESC],
                T.[Brand Owner Cust Central Order Block For Customer]	 = S.[CENTRAL_ORDER_BLK_FOR_CUST],
                T.[Brand Owner Cust Payment Block]	                     = S.[PYMT_BLK]

    FROM [GLOBAL_EDW].[Propelis].[BRAND_OWNER_CUST] AS T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D] AS S
        ON T.[CUST_KEY] = S.[CUST_KEY];

    -- Step 2: Insert new records from mirror to target table
    INSERT INTO [GLOBAL_EDW].[Propelis].[BRAND_OWNER_CUST] (
                 [CUST_KEY],
                 [Brand Owner Customer ID],
                 [Brand Owner Customer Legacy ID],
                 [Brand Owner Customer Name],
                 [Brand Owner Cust Line 2 Description],
                 [Brand Owner Cust Country Code],
                 [Brand Owner Cust Plant ID],
                 [Brand Owner Cust Segment ID],
                 [Brand Owner Cust Industry],
                 [Brand Owner Cust Vendor ID],
                 [Brand Owner Cust Group Code],
                 [Brand Owner Cust Account Group Code],
                 [Brand Owner Cust Title],
                 [Brand Owner Cust Search Term],
                 [Brand Owner Cust Street],
                 [Brand Owner Cust City],
                 [Brand Owner Cust Zip Code],
                 [Brand Owner Cust State Code],
                 [Brand Owner Cust Region Code],
                 [Brand Owner Cust Telephone Number 1],
                 [Brand Owner Cust Telephone Number 2],
                 [Brand Owner Cust Fax Number Code],
                 [Brand Owner Cust Tax Number 1 Code],
                 [Brand Owner Cust Tax Number 2 Code],
                 [Brand Owner Cust VAT Number Code],
                 [Brand Owner Cust Credit Limit],
                 [Brand Owner Cust Bonus Rate],
                 [Brand Owner Cust Express Station],
                 [Brand Owner Cust Transportation Zone],
                 [Brand Owner Cust Printer Location Characteristics],
                 [Brand Owner Cust Printer Region Characteristics],
                 [Brand Owner Cust Printer Site Characteristics],
                 [Brand Owner Cust Created Date],
                 [Brand Owner Cust Created User ID],
                 [Brand Owner Cust Updated Date],
                 [Brand Owner Cust Updated User ID],
                 [Brand Owner Cust Payment Terms Code],
                 [Brand Owner Cust Sales Distribution],
                 [Brand Owner Cust Order Block For Sales Area],
                 [Brand Owner Cust Delivery Block For Sales Area],
                 [ETL_SRC_SYS_CD],
                 [ETL_EFFECTV_BEGIN_DATE],
                 [ETL_EFFECTV_END_DATE],
                 [ETL_CURR_RCD_IND],
                 [ETL_CREATED_TS],
                 [ETL_UPDTD_TS],
                 [Brand Owner Cust Corporate Group],
                 [Brand Owner Customer Classification],
                 [Brand Owner Cust Classification Description],
                 [Brand Owner Cust Printer Location],
                 [Brand Owner Cust Printer Site],
                 [Brand Owner Cust Printer Region],
                 [Brand Owner Cust Specific Field Label 01],
                 [Brand Owner Cust Specific Field Label 02],
                 [Brand Owner Cust Specific Field Label 03],
                 [Brand Owner Cust Specific Field Label 04],
                 [Brand Owner Cust Specific Field Label 05],
                 [Brand Owner Cust Specific Field Label 06],
                 [Brand Owner Cust Specific Field Label 07],
                 [Brand Owner Cust Specific Field Label 08],
                 [Brand Owner Cust Specific Field Label 09],
                 [Brand Owner Cust Specific Field Label 10],
                 [Brand Owner Cust Specific Field Label 11],
                 [Brand Owner Cust Specific Field Label 12],
                 [Brand Owner Cust Specific Field Label 13],
                 [Brand Owner Cust Specific Field Label 14],
                 [Brand Owner Cust Specific Field Label 15],
                 [Brand Owner Cust Specific Field Label 16],
                 [Brand Owner Cust Specific Field Label 17],
                 [Brand Owner Cust Specific Field Label 18],
                 [Brand Owner Cust Specific Field Label 19],
                 [Brand Owner Cust Specific Field Label 20],
                 [Brand Owner Cust Condition Group 1],
                 [Brand Owner Cust Industry Code 1],
                 [Brand Owner Cust Industry Code 2],
                 [Brand Owner Cust Industry Description],
                 [Brand Owner Cust Industry Code 1 Description],
                 [Brand Owner Cust Industry Code 2 Description],
                 [Brand Owner Assignment to Hierarchy],
                 [Brand Owner Cust Account Group Description],
                 [Brand Owner Cust Region Description],
                 [Brand Owner Cust Country Description],
                 [Brand Owner Cust Transportation Zone Description],
                 [Brand Owner Cust Plant Description],
                 [Brand Owner Cust Condition Group Description],
                 [Brand Owner Cust Cental Branding Block],
                 [Brand Owner Cust Cental Branding Block Description],
                 [Brand Owner Cust Central Delivery Block],
                 [Brand Owner Cust Central Delivery Block Description],
                 [Brand Owner Cust Deletion IndicaOwnerr],
                 [Brand Owner Cust Central Posting Block],
                 [Brand Owner Cust Tax Jurisdiction],
                 [Brand Owner Cust Central Sales Block],
                 [Brand Owner Cust Central Deletion Indicator],
                 [Brand Owner Cust Language Key],
                 [Brand Owner Cust Trading Partner],
                 [Brand Owner Cust Trading Partner Description],
                 [Brand Owner Cust Annual Sales],
                 [Brand Owner Cust Annual Sales Year],
                 [Brand Owner Cust Sales Currency],
                 [Brand Owner Cust Sales Currency Description],
                 [Brand Owner Cust One Time Account Group],
                 [Brand Owner Cust One Time Account Group Description],
                 [Brand Owner Cust One Time Indicator],
                 [Brand Owner Cust Industry Type],
                 [Brand Owner Cust Business Type],
                 [Brand Owner Cust DUNS Number],
                 [Brand Owner Cust DUNS Plus 4],
                 [Brand Owner City Coordinates],
                 [Brand Owner Cust Tax Number 4 Code],
                 [Brand Owner Cust Attribute 3],
                 [Brand Owner Cust Attribute 3 Description],
                 [Brand Owner Cust E-Mail Address],
                 [Brand Owner Cust Mobile Number],
                 [Brand Owner Cust Search Term 2],
                 [Brand Owner Cust Street 2],
                 [Brand Owner Cust Street 3],
                 [Brand Owner Cust Street 4],
                 [Brand Owner Cust Street 5],
                 [Brand Owner Cust PO Box],
                 [Brand Owner Cust PO Box Postal Code],
                 [Brand Owner Cust PO Box City],
                 [Brand Owner Cust Region For PO Box],
                 [Brand Owner Cust PO Box Country],
                 [Brand Owner Cust Transport Zone],
                 [Brand Owner Cust Address Notes],
                 [Brand Owner Cust Tax Number 3 Code],
                 [Brand Owner Cust Tax Number 5 Code],
                 [Brand Owner Cust Industry Code 3],
                 [Brand Owner Cust Industry Code 3 Description],
                 [Brand Owner Cust Industry Code 4],
                 [Brand Owner Cust Industry Code 4 Description],
                 [Brand Owner Cust Industry Code 5],
                 [Brand Owner Cust Industry Code 5 Description],
                 [Brand Owner Cust Central Order Block For Customer],
                 [Brand Owner Cust Payment Block]

    )
    SELECT
         S.[CUST_KEY],
         S.[CUST_ID],
         S.[LGCY_CUST_ID],
         S.[CUST_NAME],
         S.[CUST_LINE_2_DESC],
         S.[CNTRY_CD],
         S.[PLNT_ID],
         S.[SEG_ID],
         S.[INDUS],
         S.[VNDR_ID],
         S.[CUST_GROUP_CD],
         S.[CUST_ACCT_GROUP_CD],
         S.[TITLE],
         S.[SEARCH_TERM],
         S.[STR],
         S.[CITY_NAME],
         S.[ZIP_CD],
         S.[ST_CD],
         S.[REGN_CD],
         S.[TEL_NUM_1_CD],
         S.[TEL_NUM_2_CD],
         S.[FAX_NUM_CD],
         S.[TAX_NUM_1_CD],
         S.[TAX_NUM_2_CD],
         S.[VAT_NUM_CD],
         S.[CREDIT_LMT],
         S.[BONUS_RT],
         S.[EXPRESS_STATION],
         S.[TRANSTN_ZONE],
         S.[PRINTER_LOC_CHARS],
         S.[PRINTER_REGN_CHARS],
         S.[PRINTER_SITE_CHARS],
         S.[CREATED_DATE],
         S.[CREATED_USR_ID],
         S.[UPDTD_DATE],
         S.[UPDTD_USR_ID],
         S.[PYMT_TRMS_CD],
         S.[SALES_DISTR],
         S.[ORDER_BLK_FOR_SALES_AREA],
         S.[DLVRY_BLK_FOR_SALES_AREA],
         S.[ETL_SRC_SYS_CD],
         S.[ETL_EFFECTV_BEGIN_DATE],
         S.[ETL_EFFECTV_END_DATE],
         S.[ETL_CURR_RCD_IND],
         S.[ETL_CREATED_TS],
         S.[ETL_UPDTD_TS],
         S.[CORPORATE_GROUP],
         S.[CUST_CLSFTN],
         S.[CUST_CLSFTN_DESC],
         S.[PRINTER_LOC],
         S.[PRINTER_SITE],
         S.[PRINTER_REGN],
         S.[CUST_SPECIFIC_FLD_LBL_01],
         S.[CUST_SPECIFIC_FLD_LBL_02],
         S.[CUST_SPECIFIC_FLD_LBL_03],
         S.[CUST_SPECIFIC_FLD_LBL_04],
         S.[CUST_SPECIFIC_FLD_LBL_05],
         S.[CUST_SPECIFIC_FLD_LBL_06],
         S.[CUST_SPECIFIC_FLD_LBL_07],
         S.[CUST_SPECIFIC_FLD_LBL_08],
         S.[CUST_SPECIFIC_FLD_LBL_09],
         S.[CUST_SPECIFIC_FLD_LBL_10],
         S.[CUST_SPECIFIC_FLD_LBL_11],
         S.[CUST_SPECIFIC_FLD_LBL_12],
         S.[CUST_SPECIFIC_FLD_LBL_13],
         S.[CUST_SPECIFIC_FLD_LBL_14],
         S.[CUST_SPECIFIC_FLD_LBL_15],
         S.[CUST_SPECIFIC_FLD_LBL_16],
         S.[CUST_SPECIFIC_FLD_LBL_17],
         S.[CUST_SPECIFIC_FLD_LBL_18],
         S.[CUST_SPECIFIC_FLD_LBL_19],
         S.[CUST_SPECIFIC_FLD_LBL_20],
         S.[CUST_COND_GROUP_1],
         S.[INDUS_CD_1],
         S.[INDUS_CD_2],
         S.[INDUS_DESC],
         S.[INDUS_CD_1_DESC],
         S.[INDUS_CD_2_DESC],
         S.[ASSIGN_TO_HIERCHY],
         S.[CUST_ACCT_GROUP_DESC],
         S.[REGN_DESC],
         S.[CNTRY_DESC],
         S.[TRANSTN_ZONE_DESC],
         S.[PLNT_DESC],
         S.[CUST_COND_GROUP_DESC],
         S.[CENTRAL_BILLING_BLK],
         S.[CENTRAL_BILLING_BLK_DESC],
         S.[CENTRAL_DLVRY_BLK],
         S.[CENTRAL_DLVRY_BLK_DESC],
         S.[DELETION_IND],
         S.[CENTRAL_PSTNG_BLK],
         S.[TAX_JRSDCTN],
         S.[CENTRAL_SALES_BLK],
         S.[CENTRAL_DELETION_IND],
         S.[LANG_KEY],
         S.[TRADING_PRTNR],
         S.[TRADING_PRTNR_DESC],
         S.[ANNUAL_SALES],
         S.[ANNUAL_SALES_YR],
         S.[SALES_CRNCY],
         S.[SALES_CRNCY_DESC],
         S.[ONE_TM_CUST_ACCT_GROUP],
         S.[ONE_TM_CUST_ACCT_GROUP_DESC],
         S.[ONE_TM_CUST_IND],
         S.[INDUS_TYP],
         S.[BIZ_TYP],
         S.[DUNS_NUM],
         S.[DUNS_PLUS_4],
         S.[CITY_COORDINATES],
         S.[TAX_NUM_4_CD],
         S.[ATTRIB_3],
         S.[ATTRIB_3_DESC],
         S.[E_MAIL_ADDR],
         S.[MOBILE_NUM],
         S.[SEARCH_TERM_2],
         S.[STR_2],
         S.[STR_3],
         S.[STR_4],
         S.[STR_5],
         S.[PO_BOX],
         S.[PO_BOX_POSTAL_CD],
         S.[PO_BOX_CITY],
         S.[REGN_FOR_PO_BOX],
         S.[PO_BOX_CNTRY],
         S.[TRNSPRT_ZONE],
         S.[ADDR_NOTES],
         S.[TAX_NUM_3],
         S.[TAX_NUM_5],
         S.[INDUS_CD_3],
         S.[INDUS_CD_3_DESC],
         S.[INDUS_CD_4],
         S.[INDUS_CD_4_DESC],
         S.[INDUS_CD_5],
         S.[INDUS_CD_5_DESC],
         S.[CENTRAL_ORDER_BLK_FOR_CUST],
         S.[PYMT_BLK]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[BRAND_OWNER_CUST] AS T
        ON T.[CUST_KEY] = S.[CUST_KEY]
    WHERE T.[CUST_KEY] IS NULL;

END