CREATE    PROCEDURE [Propelis].[Proc_PAYER_CUST]
AS
BEGIN
    -- Step 1: Update existing records in target table
    UPDATE T
    SET
                T.[CUST_KEY]	         = S.[CUST_KEY],
                T.[Payer Customer ID]	         = S.[CUST_ID],
                T.[Payer Legacy Customer ID]	         = S.[LGCY_CUST_ID],
                T.[Payer Customer Name]	         = S.[CUST_NAME],
                T.[Payer Cust Line 2 Description]	         = S.[CUST_LINE_2_DESC],
                T.[Payer Cust Country Code]	         = S.[CNTRY_CD],
                T.[Payer Cust Plant ID]	         = S.[PLNT_ID],
                T.[Payer Cust Segment ID]	         = S.[SEG_ID],
                T.[Payer Cust Industry]	         = S.[INDUS],
                T.[Payer Cust Vendor ID]	         = S.[VNDR_ID],
                T.[Payer Cust Customer Group Code]	         = S.[CUST_GROUP_CD],
                T.[Payer Cust Account Group Code]	         = S.[CUST_ACCT_GROUP_CD],
                T.[Payer Cust Title]	         = S.[TITLE],
                T.[Payer Cust Search Term]	         = S.[SEARCH_TERM],
                T.[Payer Cust Street]	         = S.[STR],
                T.[Payer Cust City]	         = S.[CITY_NAME],
                T.[Payer Cust Zip Code]	         = S.[ZIP_CD],
                T.[Payer Cust State Code]	         = S.[ST_CD],
                T.[Payer Cust Region Code]	         = S.[REGN_CD],
                T.[Payer Cust Telephone Number 1]	         = S.[TEL_NUM_1_CD],
                T.[Payer Cust Telephone Number 2]	         = S.[TEL_NUM_2_CD],
                T.[Payer Cust Fax Number Code]	         = S.[FAX_NUM_CD],
                T.[Payer Cust Tax Number 1 Code]	         = S.[TAX_NUM_1_CD],
                T.[Payer Cust Tax Number 2 Code]	         = S.[TAX_NUM_2_CD],
                T.[Payer Cust VAT Number Code]	         = S.[VAT_NUM_CD],
                T.[Payer Cust Credit Limit]	         = S.[CREDIT_LMT],
                T.[Payer Cust Bonus Rate]	         = S.[BONUS_RT],
                T.[Payer Cust Express Station]	         = S.[EXPRESS_STATION],
                T.[Payer Cust Transportation Zone]	         = S.[TRANSTN_ZONE],
                T.[Payer Cust Printer Location Characteristics]	         = S.[PRINTER_LOC_CHARS],
                T.[Payer Cust Printer Region Characteristics]	         = S.[PRINTER_REGN_CHARS],
                T.[Payer Cust Printer Site Characteristics]	         = S.[PRINTER_SITE_CHARS],
                T.[Payer Cust Customer Created Date]	         = S.[CREATED_DATE],
                T.[Payer Cust Created User ID]	         = S.[CREATED_USR_ID],
                T.[Payer Cust Customer Updated Date]	         = S.[UPDTD_DATE],
                T.[Payer Cust Updated User ID]	         = S.[UPDTD_USR_ID],
                T.[Payer Cust Payment Terms Code]	         = S.[PYMT_TRMS_CD],
                T.[Payer Cust Sales Distribution]	         = S.[SALES_DISTR],
                T.[Payer Cust Order Block For Sales Area]	         = S.[ORDER_BLK_FOR_SALES_AREA],
                T.[Payer Cust Delivery Block For Sales Area]	         = S.[DLVRY_BLK_FOR_SALES_AREA],
                T.[ETL_SRC_SYS_CD]	         = S.[ETL_SRC_SYS_CD],
                T.[ETL_EFFECTV_BEGIN_DATE]	         = S.[ETL_EFFECTV_BEGIN_DATE],
                T.[ETL_EFFECTV_END_DATE]	         = S.[ETL_EFFECTV_END_DATE],
                T.[ETL_CURR_RCD_IND]	         = S.[ETL_CURR_RCD_IND],
                T.[ETL_CREATED_TS]	         = S.[ETL_CREATED_TS],
                T.[ETL_UPDTD_TS]	         = S.[ETL_UPDTD_TS],
                T.[Payer Cust Corporate Group]	         = S.[CORPORATE_GROUP],
                T.[Payer Cust Classification]	         = S.[CUST_CLSFTN],
                T.[Payer Cust Classification Description]	         = S.[CUST_CLSFTN_DESC],
                T.[Payer Cust Printer Location]	         = S.[PRINTER_LOC],
                T.[Payer Cust Printer Site]	         = S.[PRINTER_SITE],
                T.[Payer Cust Printer Region]	         = S.[PRINTER_REGN],
                T.[Payer Cust Specific Field Label 01]	         = S.[CUST_SPECIFIC_FLD_LBL_01],
                T.[Payer Cust Specific Field Label 02]	         = S.[CUST_SPECIFIC_FLD_LBL_02],
                T.[Payer Cust Specific Field Label 03]	         = S.[CUST_SPECIFIC_FLD_LBL_03],
                T.[Payer Cust Specific Field Label 04]	         = S.[CUST_SPECIFIC_FLD_LBL_04],
                T.[Payer Cust Specific Field Label 05]	         = S.[CUST_SPECIFIC_FLD_LBL_05],
                T.[Payer Cust Specific Field Label 06]	         = S.[CUST_SPECIFIC_FLD_LBL_06],
                T.[Payer Cust Specific Field Label 07]	         = S.[CUST_SPECIFIC_FLD_LBL_07],
                T.[Payer Cust Specific Field Label 08]	         = S.[CUST_SPECIFIC_FLD_LBL_08],
                T.[Payer Cust Specific Field Label 09]	         = S.[CUST_SPECIFIC_FLD_LBL_09],
                T.[Payer Cust Specific Field Label 10]	         = S.[CUST_SPECIFIC_FLD_LBL_10],
                T.[Payer Cust Specific Field Label 11]	         = S.[CUST_SPECIFIC_FLD_LBL_11],
                T.[Payer Cust Specific Field Label 12]	         = S.[CUST_SPECIFIC_FLD_LBL_12],
                T.[Payer Cust Specific Field Label 13]	         = S.[CUST_SPECIFIC_FLD_LBL_13],
                T.[Payer Cust Specific Field Label 14]	         = S.[CUST_SPECIFIC_FLD_LBL_14],
                T.[Payer Cust Specific Field Label 15]	         = S.[CUST_SPECIFIC_FLD_LBL_15],
                T.[Payer Cust Specific Field Label 16]	         = S.[CUST_SPECIFIC_FLD_LBL_16],
                T.[Payer Cust Specific Field Label 17]	         = S.[CUST_SPECIFIC_FLD_LBL_17],
                T.[Payer Cust Specific Field Label 18]	         = S.[CUST_SPECIFIC_FLD_LBL_18],
                T.[Payer Cust Specific Field Label 19]	         = S.[CUST_SPECIFIC_FLD_LBL_19],
                T.[Payer Cust Specific Field Label 20]	         = S.[CUST_SPECIFIC_FLD_LBL_20],
                T.[Payer Cust Condition Group 1]	         = S.[CUST_COND_GROUP_1],
                T.[Payer Cust Industry Code 1]	         = S.[INDUS_CD_1],
                T.[Payer Cust Industry Code 2]	         = S.[INDUS_CD_2],
                T.[Payer Cust Industry Description]	         = S.[INDUS_DESC],
                T.[Payer Cust Industry Code 1 Description]	         = S.[INDUS_CD_1_DESC],
                T.[Payer Cust Industry Code 2 Description]	         = S.[INDUS_CD_2_DESC],
                T.[Payer Cust Assignment to Hierarchy]	         = S.[ASSIGN_TO_HIERCHY],
                T.[Payer Cust Account Group Description]	         = S.[CUST_ACCT_GROUP_DESC],
                T.[Payer Cust Region Description]	         = S.[REGN_DESC],
                T.[Payer Cust Country Description]	         = S.[CNTRY_DESC],
                T.[Payer Cust Transportation Zone Description]	         = S.[TRANSTN_ZONE_DESC],
                T.[Payer Cust Plant Description]	         = S.[PLNT_DESC],
                T.[Payer Cust Condition Group Description]	         = S.[CUST_COND_GROUP_DESC],
                T.[Payer Cust Cental Billing Block]	         = S.[CENTRAL_BILLING_BLK],
                T.[Payer Cust Cental Billing Block Description]	         = S.[CENTRAL_BILLING_BLK_DESC],
                T.[Payer Cust Central Delivery Block]	         = S.[CENTRAL_DLVRY_BLK],
                T.[Payer Cust Central Delivery Block Description]	         = S.[CENTRAL_DLVRY_BLK_DESC],
                T.[Payer Cust Deletion Indicator]	         = S.[DELETION_IND],
                T.[Payer Cust Central Posting Block]	         = S.[CENTRAL_PSTNG_BLK],
                T.[Payer Cust Tax Jurisdiction]	         = S.[TAX_JRSDCTN],
                T.[Payer Cust Central Sales Block]	         = S.[CENTRAL_SALES_BLK],
                T.[Payer Cust Central Deletion Indicator]	         = S.[CENTRAL_DELETION_IND],
                T.[Payer Cust Language Key]	         = S.[LANG_KEY],
                T.[Payer Cust Trading Partner]	         = S.[TRADING_PRTNR],
                T.[Payer Cust Trading Partner Description]	         = S.[TRADING_PRTNR_DESC],
                T.[Payer Cust Annual Sales]	         = S.[ANNUAL_SALES],
                T.[Payer Cust Annual Sales Year]	         = S.[ANNUAL_SALES_YR],
                T.[Payer Cust Sales Currency]	         = S.[SALES_CRNCY],
                T.[Payer Cust Sales Currency Description]	         = S.[SALES_CRNCY_DESC],
                T.[Payer Cust One Time Account Group]	         = S.[ONE_TM_CUST_ACCT_GROUP],
                T.[Payer Cust One Time Account Group Description]	         = S.[ONE_TM_CUST_ACCT_GROUP_DESC],
                T.[Payer Cust One Time Indicator]	         = S.[ONE_TM_CUST_IND],
                T.[Payer Cust Industry Type]	         = S.[INDUS_TYP],
                T.[Payer Cust Business Type]	         = S.[BIZ_TYP],
                T.[Payer Cust DUNS Number]	         = S.[DUNS_NUM],
                T.[Payer Cust DUNS Plus 4]	         = S.[DUNS_PLUS_4],
                T.[Payer Cust City Coordinates]	         = S.[CITY_COORDINATES],
                T.[Payer Cust Tax Number 4 Code]	         = S.[TAX_NUM_4_CD],
                T.[Payer Cust Attribute 3]	         = S.[ATTRIB_3],
                T.[Payer Cust Attribute 3 Description]	         = S.[ATTRIB_3_DESC],
                T.[Payer Cust E-Mail Address]	         = S.[E_MAIL_ADDR],
                T.[Payer Cust Mobile Number]	         = S.[MOBILE_NUM],
                T.[Payer Cust Search Term 2]	         = S.[SEARCH_TERM_2],
                T.[Payer Cust Street 2]	         = S.[STR_2],
                T.[Payer Cust Street 3]	         = S.[STR_3],
                T.[Payer Cust Street 4]	         = S.[STR_4],
                T.[Payer Cust Street 5]	         = S.[STR_5],
                T.[Payer Cust PO Box]	         = S.[PO_BOX],
                T.[Payer Cust PO Box Postal Code]	         = S.[PO_BOX_POSTAL_CD],
                T.[Payer Cust PO Box City]	         = S.[PO_BOX_CITY],
                T.[Payer Cust Region For PO Box]	         = S.[REGN_FOR_PO_BOX],
                T.[Payer Cust PO Box Country]	         = S.[PO_BOX_CNTRY],
                T.[Payer Cust Transport Zone]	         = S.[TRNSPRT_ZONE],
                T.[Payer Cust Address Notes]	         = S.[ADDR_NOTES],
                T.[Payer Cust Tax Number 3 Code]	         = S.[TAX_NUM_3],
                T.[Payer Cust Tax Number 5 Code]	         = S.[TAX_NUM_5],
                T.[Payer Cust Industry Code 3]	         = S.[INDUS_CD_3],
                T.[Payer Cust Industry Code 3 Description]	         = S.[INDUS_CD_3_DESC],
                T.[Payer Cust Industry Code 4]	         = S.[INDUS_CD_4],
                T.[Payer Cust Industry Code 4 Description]	         = S.[INDUS_CD_4_DESC],
                T.[Payer Cust Industry Code 5]	         = S.[INDUS_CD_5],
                T.[Payer Cust Industry Code 5 Description]	         = S.[INDUS_CD_5_DESC],
                T.[Payer Cust Central Order Block For Customer]	         = S.[CENTRAL_ORDER_BLK_FOR_CUST],
                T.[Payer Cust Payment Block]	         = S.[PYMT_BLK]
	

	


    FROM [GLOBAL_EDW].[Propelis].[PAYER_CUST] AS T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D] AS S
        ON T.[CUST_KEY] = S.[CUST_KEY];

    -- Step 2: Insert new records from mirror to target table
    INSERT INTO [GLOBAL_EDW].[Propelis].[PAYER_CUST] (
                 [CUST_KEY],
                  [Payer Customer ID],
                  [Payer Legacy Customer ID],
                  [Payer Customer Name],
                  [Payer Cust Line 2 Description],
                  [Payer Cust Country Code],
                  [Payer Cust Plant ID],
                  [Payer Cust Segment ID],
                  [Payer Cust Industry],
                  [Payer Cust Vendor ID],
                  [Payer Cust Customer Group Code],
                  [Payer Cust Account Group Code],
                  [Payer Cust Title],
                  [Payer Cust Search Term],
                  [Payer Cust Street],
                  [Payer Cust City],
                  [Payer Cust Zip Code],
                  [Payer Cust State Code],
                  [Payer Cust Region Code],
                  [Payer Cust Telephone Number 1],
                  [Payer Cust Telephone Number 2],
                  [Payer Cust Fax Number Code],
                  [Payer Cust Tax Number 1 Code],
                  [Payer Cust Tax Number 2 Code],
                  [Payer Cust VAT Number Code],
                  [Payer Cust Credit Limit],
                  [Payer Cust Bonus Rate],
                  [Payer Cust Express Station],
                  [Payer Cust Transportation Zone],
                  [Payer Cust Printer Location Characteristics],
                  [Payer Cust Printer Region Characteristics],
                  [Payer Cust Printer Site Characteristics],
                  [Payer Cust Customer Created Date],
                  [Payer Cust Created User ID],
                  [Payer Cust Customer Updated Date],
                  [Payer Cust Updated User ID],
                  [Payer Cust Payment Terms Code],
                  [Payer Cust Sales Distribution],
                  [Payer Cust Order Block For Sales Area],
                  [Payer Cust Delivery Block For Sales Area],
                  [ETL_SRC_SYS_CD],
                  [ETL_EFFECTV_BEGIN_DATE],
                  [ETL_EFFECTV_END_DATE],
                  [ETL_CURR_RCD_IND],
                  [ETL_CREATED_TS],
                  [ETL_UPDTD_TS],
                  [Payer Cust Corporate Group],
                  [Payer Cust Classification],
                  [Payer Cust Classification Description],
                  [Payer Cust Printer Location],
                  [Payer Cust Printer Site],
                  [Payer Cust Printer Region],
                  [Payer Cust Specific Field Label 01],
                  [Payer Cust Specific Field Label 02],
                  [Payer Cust Specific Field Label 03],
                  [Payer Cust Specific Field Label 04],
                  [Payer Cust Specific Field Label 05],
                  [Payer Cust Specific Field Label 06],
                  [Payer Cust Specific Field Label 07],
                  [Payer Cust Specific Field Label 08],
                  [Payer Cust Specific Field Label 09],
                  [Payer Cust Specific Field Label 10],
                  [Payer Cust Specific Field Label 11],
                  [Payer Cust Specific Field Label 12],
                  [Payer Cust Specific Field Label 13],
                  [Payer Cust Specific Field Label 14],
                  [Payer Cust Specific Field Label 15],
                  [Payer Cust Specific Field Label 16],
                  [Payer Cust Specific Field Label 17],
                  [Payer Cust Specific Field Label 18],
                  [Payer Cust Specific Field Label 19],
                  [Payer Cust Specific Field Label 20],
                  [Payer Cust Condition Group 1],
                  [Payer Cust Industry Code 1],
                  [Payer Cust Industry Code 2],
                  [Payer Cust Industry Description],
                  [Payer Cust Industry Code 1 Description],
                  [Payer Cust Industry Code 2 Description],
                  [Payer Cust Assignment to Hierarchy],
                  [Payer Cust Account Group Description],
                  [Payer Cust Region Description],
                  [Payer Cust Country Description],
                  [Payer Cust Transportation Zone Description],
                  [Payer Cust Plant Description],
                  [Payer Cust Condition Group Description],
                  [Payer Cust Cental Billing Block],
                  [Payer Cust Cental Billing Block Description],
                  [Payer Cust Central Delivery Block],
                  [Payer Cust Central Delivery Block Description],
                  [Payer Cust Deletion Indicator],
                  [Payer Cust Central Posting Block],
                  [Payer Cust Tax Jurisdiction],
                  [Payer Cust Central Sales Block],
                  [Payer Cust Central Deletion Indicator],
                  [Payer Cust Language Key],
                  [Payer Cust Trading Partner],
                  [Payer Cust Trading Partner Description],
                  [Payer Cust Annual Sales],
                  [Payer Cust Annual Sales Year],
                  [Payer Cust Sales Currency],
                  [Payer Cust Sales Currency Description],
                  [Payer Cust One Time Account Group],
                  [Payer Cust One Time Account Group Description],
                  [Payer Cust One Time Indicator],
                  [Payer Cust Industry Type],
                  [Payer Cust Business Type],
                  [Payer Cust DUNS Number],
                  [Payer Cust DUNS Plus 4],
                  [Payer Cust City Coordinates],
                  [Payer Cust Tax Number 4 Code],
                  [Payer Cust Attribute 3],
                  [Payer Cust Attribute 3 Description],
                  [Payer Cust E-Mail Address],
                  [Payer Cust Mobile Number],
                  [Payer Cust Search Term 2],
                  [Payer Cust Street 2],
                  [Payer Cust Street 3],
                  [Payer Cust Street 4],
                  [Payer Cust Street 5],
                  [Payer Cust PO Box],
                  [Payer Cust PO Box Postal Code],
                  [Payer Cust PO Box City],
                  [Payer Cust Region For PO Box],
                  [Payer Cust PO Box Country],
                  [Payer Cust Transport Zone],
                  [Payer Cust Address Notes],
                  [Payer Cust Tax Number 3 Code],
                  [Payer Cust Tax Number 5 Code],
                  [Payer Cust Industry Code 3],
                  [Payer Cust Industry Code 3 Description],
                  [Payer Cust Industry Code 4],
                  [Payer Cust Industry Code 4 Description],
                  [Payer Cust Industry Code 5],
                  [Payer Cust Industry Code 5 Description],
                  [Payer Cust Central Order Block For Customer],
                  [Payer Cust Payment Block]


    )
    SELECT
         S.[CUST_KEY],
         S.[CUST_ID],
         S.[LGCY_CUST_ID],
         S.[CUST_NAME],
         S.[CUST_LINE_2_DESC],
         S.[CNTRY_CD],
         S.[PLNT_ID],
         S.[SEG_ID],
         S.[INDUS],
         S.[VNDR_ID],
         S.[CUST_GROUP_CD],
         S.[CUST_ACCT_GROUP_CD],
         S.[TITLE],
         S.[SEARCH_TERM],
         S.[STR],
         S.[CITY_NAME],
         S.[ZIP_CD],
         S.[ST_CD],
         S.[REGN_CD],
         S.[TEL_NUM_1_CD],
         S.[TEL_NUM_2_CD],
         S.[FAX_NUM_CD],
         S.[TAX_NUM_1_CD],
         S.[TAX_NUM_2_CD],
         S.[VAT_NUM_CD],
         S.[CREDIT_LMT],
         S.[BONUS_RT],
         S.[EXPRESS_STATION],
         S.[TRANSTN_ZONE],
         S.[PRINTER_LOC_CHARS],
         S.[PRINTER_REGN_CHARS],
         S.[PRINTER_SITE_CHARS],
         S.[CREATED_DATE],
         S.[CREATED_USR_ID],
         S.[UPDTD_DATE],
         S.[UPDTD_USR_ID],
         S.[PYMT_TRMS_CD],
         S.[SALES_DISTR],
         S.[ORDER_BLK_FOR_SALES_AREA],
         S.[DLVRY_BLK_FOR_SALES_AREA],
         S.[ETL_SRC_SYS_CD],
         S.[ETL_EFFECTV_BEGIN_DATE],
         S.[ETL_EFFECTV_END_DATE],
         S.[ETL_CURR_RCD_IND],
         S.[ETL_CREATED_TS],
         S.[ETL_UPDTD_TS],
         S.[CORPORATE_GROUP],
         S.[CUST_CLSFTN],
         S.[CUST_CLSFTN_DESC],
         S.[PRINTER_LOC],
         S.[PRINTER_SITE],
         S.[PRINTER_REGN],
         S.[CUST_SPECIFIC_FLD_LBL_01],
         S.[CUST_SPECIFIC_FLD_LBL_02],
         S.[CUST_SPECIFIC_FLD_LBL_03],
         S.[CUST_SPECIFIC_FLD_LBL_04],
         S.[CUST_SPECIFIC_FLD_LBL_05],
         S.[CUST_SPECIFIC_FLD_LBL_06],
         S.[CUST_SPECIFIC_FLD_LBL_07],
         S.[CUST_SPECIFIC_FLD_LBL_08],
         S.[CUST_SPECIFIC_FLD_LBL_09],
         S.[CUST_SPECIFIC_FLD_LBL_10],
         S.[CUST_SPECIFIC_FLD_LBL_11],
         S.[CUST_SPECIFIC_FLD_LBL_12],
         S.[CUST_SPECIFIC_FLD_LBL_13],
         S.[CUST_SPECIFIC_FLD_LBL_14],
         S.[CUST_SPECIFIC_FLD_LBL_15],
         S.[CUST_SPECIFIC_FLD_LBL_16],
         S.[CUST_SPECIFIC_FLD_LBL_17],
         S.[CUST_SPECIFIC_FLD_LBL_18],
         S.[CUST_SPECIFIC_FLD_LBL_19],
         S.[CUST_SPECIFIC_FLD_LBL_20],
         S.[CUST_COND_GROUP_1],
         S.[INDUS_CD_1],
         S.[INDUS_CD_2],
         S.[INDUS_DESC],
         S.[INDUS_CD_1_DESC],
         S.[INDUS_CD_2_DESC],
         S.[ASSIGN_TO_HIERCHY],
         S.[CUST_ACCT_GROUP_DESC],
         S.[REGN_DESC],
         S.[CNTRY_DESC],
         S.[TRANSTN_ZONE_DESC],
         S.[PLNT_DESC],
         S.[CUST_COND_GROUP_DESC],
         S.[CENTRAL_BILLING_BLK],
         S.[CENTRAL_BILLING_BLK_DESC],
         S.[CENTRAL_DLVRY_BLK],
         S.[CENTRAL_DLVRY_BLK_DESC],
         S.[DELETION_IND],
         S.[CENTRAL_PSTNG_BLK],
         S.[TAX_JRSDCTN],
         S.[CENTRAL_SALES_BLK],
         S.[CENTRAL_DELETION_IND],
         S.[LANG_KEY],
         S.[TRADING_PRTNR],
         S.[TRADING_PRTNR_DESC],
         S.[ANNUAL_SALES],
         S.[ANNUAL_SALES_YR],
         S.[SALES_CRNCY],
         S.[SALES_CRNCY_DESC],
         S.[ONE_TM_CUST_ACCT_GROUP],
         S.[ONE_TM_CUST_ACCT_GROUP_DESC],
         S.[ONE_TM_CUST_IND],
         S.[INDUS_TYP],
         S.[BIZ_TYP],
         S.[DUNS_NUM],
         S.[DUNS_PLUS_4],
         S.[CITY_COORDINATES],
         S.[TAX_NUM_4_CD],
         S.[ATTRIB_3],
         S.[ATTRIB_3_DESC],
         S.[E_MAIL_ADDR],
         S.[MOBILE_NUM],
         S.[SEARCH_TERM_2],
         S.[STR_2],
         S.[STR_3],
         S.[STR_4],
         S.[STR_5],
         S.[PO_BOX],
         S.[PO_BOX_POSTAL_CD],
         S.[PO_BOX_CITY],
         S.[REGN_FOR_PO_BOX],
         S.[PO_BOX_CNTRY],
         S.[TRNSPRT_ZONE],
         S.[ADDR_NOTES],
         S.[TAX_NUM_3],
         S.[TAX_NUM_5],
         S.[INDUS_CD_3],
         S.[INDUS_CD_3_DESC],
         S.[INDUS_CD_4],
         S.[INDUS_CD_4_DESC],
         S.[INDUS_CD_5],
         S.[INDUS_CD_5_DESC],
         S.[CENTRAL_ORDER_BLK_FOR_CUST],
         S.[PYMT_BLK]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[PAYER_CUST] AS T
        ON T.[CUST_KEY] = S.[CUST_KEY]
    WHERE T.[CUST_KEY] IS NULL;

END