CREATE     PROCEDURE [Propelis].[Proc_POSTING_DATE]
AS
BEGIN
    -- 1. UPDATE existing rows
    UPDATE T
    SET
        T.[Posting Date]                       = S.[THE_DATE],
        T.[Posting Fiscal Year]                = S.[FISCAL_YR],
        T.[FISCAL PER NUM]                     = S.[FISCAL_PER_NUM],
        T.[Posting Fiscal Period Code]         = S.[FISCAL_PER_CD],
        T.[Posting Fiscal Quarter Number]      = S.[FISCAL_QTR_NUM],
        T.[Posting Fiscal Quarter Code]        = S.[FISCAL_QTR_CD],
        T.[Posting Calendar Year]              = S.[CLNDR_YR],
        T.[Posting Calendar Month Number]      = S.[CLNDR_MNTH_NUM],
        T.[Posting Calendar Month Code]        = S.[CLNDR_MNTH_CD],
        T.[Posting Calendar Month Desc]        = S.[CLNDR_MNTH_DESC],
        T.[CLNDR QTR NUM]                      = S.[CLNDR_QTR_NUM],
        T.[Posting Calendar Quarter Code]      = S.[CLNDR_QTR_CD],
        T.[Posting Calendar Weekday Number]    = S.[CLNDR_WEEKDAY_NUM],
        T.[Posting Calendar Weekday Name]      = S.[CLNDR_WEEKDAY_NAME],
        T.[Posting Calendar Day in Month]      = S.[CLNDR_DAY_IN_MNTH],
        T.[Posting Calendar Day in Year]       = S.[CLNDR_DAY_IN_YR],
        T.[Posting Calendar Week]              = S.[CLNDR_WK],
        T.[Posting Calendar Month in Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Posting Calendar Days in Month]     = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL SRC SYS CD]                     = S.[ETL_SRC_SYS_CD],
        T.[ETL CREATED TS]                     = S.[ETL_CREATED_TS],
        T.[ETL UPDTD TS]                       = S.[ETL_UPDTD_TS],
        T.[Posting Current Day Flag]           = S.[CURR_DAY_FLG],
        T.[Posting Current Day Minus 1 Flag]   = S.[CURR_DAY_MINUS_1_FLG],
        T.[Posting Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Posting Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Posting Current Month Flag]         = S.[CURR_MNTH_FLG],
        T.[Posting Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Posting Current Month Minus 12 Flag]= S.[CURR_MNTH_MINUS_12_FLG],
        T.[Posting Current Quarter Flag]       = S.[CURR_QTR_FLG],
        T.[Posting Current Quarter Minus 1 Flag]= S.[CURR_QTR_MINUS_1_FLG],
        T.[Posting Current Quarter Minus 4 Flag]= S.[CURR_QTR_MINUS_4_FLG],
        T.[Posting Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Posting Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Posting Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Posting Current Fiscal Year Flag]   = S.[CURR_FISCAL_YR_FLG],
        T.[Posting Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Posting Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Posting Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Posting Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Posting Day in Fiscal Year]         = S.[DAY_IN_FISCAL_YR],
        T.[Posting Date Is Weekday]            = S.[IS_WEEKDAY],
        T.[Posting Fiscal Week]                = S.[FISCAL_WK],
        T.[Posting Current Fiscal Week Flag]   = S.[CURR_FISCAL_WK_FLG],
        T.[Posting Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Posting Fiscal Weekday Number]      = S.[FISCAL_WEEKDAY_NUM],
        T.[Posting Fiscal Weekday Name]        = S.[FISCAL_WEEKDAY_NAME],
        T.[Posting Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Posting Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Posting Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Posting Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Posting Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Posting Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Posting Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[POSTING_DATE] AS T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] AS S
        ON T.[DATE_KEY] = S.[DATE_KEY];

    -- 2. INSERT new rows
    INSERT INTO [GLOBAL_EDW].[Propelis].[POSTING_DATE]
    (
        [DATE_KEY],
        [Posting Date],
        [Posting Fiscal Year],
        [FISCAL PER NUM],
        [Posting Fiscal Period Code],
        [Posting Fiscal Quarter Number],
        [Posting Fiscal Quarter Code],
        [Posting Calendar Year],
        [Posting Calendar Month Number],
        [Posting Calendar Month Code],
        [Posting Calendar Month Desc],
        [CLNDR QTR NUM],
        [Posting Calendar Quarter Code],
        [Posting Calendar Weekday Number],
        [Posting Calendar Weekday Name],
        [Posting Calendar Day in Month],
        [Posting Calendar Day in Year],
        [Posting Calendar Week],
        [Posting Calendar Month in Quarter Number],
        [Posting Calendar Days in Month],
        [ETL SRC SYS CD],
        [ETL CREATED TS],
        [ETL UPDTD TS],
        [Posting Current Day Flag],
        [Posting Current Day Minus 1 Flag],
        [Posting Current Calendar Week Flag],
        [Posting Current Calendar Week Minus 1 Flag],
        [Posting Current Month Flag],
        [Posting Current Month Minus 1 Flag],
        [Posting Current Month Minus 12 Flag],
        [Posting Current Quarter Flag],
        [Posting Current Quarter Minus 1 Flag],
        [Posting Current Quarter Minus 4 Flag],
        [Posting Current Calendar Year Flag],
        [Posting Current Calendar Year Minus 1 Flag],
        [Posting Current Calendar Year Minus 2 Flag],
        [Posting Current Fiscal Year Flag],
        [Posting Current Fiscal Year Minus 1 Flag],
        [Posting Current Fiscal Year Minus 2 Flag],
        [Posting Current Calendar Year Plus 1 Flag],
        [Posting Current Fiscal Year Plus 1 Flag],
        [Posting Day in Fiscal Year],
        [Posting Date Is Weekday],
        [Posting Fiscal Week],
        [Posting Current Fiscal Week Flag],
        [Posting Current Fiscal Week Minus 1 Flag],
        [Posting Fiscal Weekday Number],
        [Posting Fiscal Weekday Name],
        [Posting Current Month Minus 2 Flag],
        [Posting Current Fiscal Week Minus 2 Flag],
        [Posting Current Fiscal Week Minus 6 Flag],
        [Posting Current Fiscal Week Minus 3 Flag],
        [Posting Current Fiscal Week Minus 4 Flag],
        [Posting Current Fiscal Week Minus 5 Flag],
        [Posting Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[POSTING_DATE] AS T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;

END;