CREATE   PROCEDURE [Propelis].[Proc_Basic_Finish_Date]
AS
BEGIN  
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Basic Finish Date] = S.[THE_DATE],
        T.[Basic Finish Fiscal Year] = S.[FISCAL_YR],
        T.[Basic Finish Fiscal Period Number] = S.[FISCAL_PER_NUM],
        T.[Basic Finish Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Basic Finish Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Basic Finish Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Basic Finish Calendar Year] = S.[CLNDR_YR],
        T.[Basic Finish Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Basic Finish Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Basic Finish Calendar Month Description] = S.[CLNDR_MNTH_DESC],
        T.[Basic Finish Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[Basic Finish Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Basic Finish Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Basic Finish Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Basic Finish Calendar Day In Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Basic Finish Calendar Day In Year] = S.[CLNDR_DAY_IN_YR],
        T.[Basic Finish Calendar Week] = S.[CLNDR_WK],
        T.[Basic Finish Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Basic Finish Calendar Days In Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Basic Finish Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Basic Finish Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Basic Finish Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Basic Finish Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Basic Finish Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Basic Finish Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Basic Finish Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Basic Finish Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Basic Finish Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Basic Finish Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Basic Finish Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Basic Finish Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Basic Finish Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Basic Finish Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Basic Finish Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Basic Finish Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Basic Finish Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[CURR_FISCAL_YR_PLUS_1_FLG] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Basic Finish Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Basic Finish Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Basic Finish Fiscal Week] = S.[FISCAL_WK],
        T.[Basic Finish Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Basic Finish Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Basic Finish Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Basic Finish Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Basic Finish Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Basic Finish Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Basic Finish Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Basic Finish Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Basic Finish Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Basic Finish Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Basic Finish Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[Basic_Finish_Date] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];
 
    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[Basic_Finish_Date] (
        [DATE_KEY],
        [Basic Finish Date],
        [Basic Finish Fiscal Year],
        [Basic Finish Fiscal Period Number],
        [Basic Finish Fiscal Period Code],
        [Basic Finish Fiscal Quarter Number],
        [Basic Finish Fiscal Quarter Code],
        [Basic Finish Calendar Year],
        [Basic Finish Calendar Month Number],
        [Basic Finish Calendar Month Code],
        [Basic Finish Calendar Month Description],
        [Basic Finish Calendar Quarter Number],
        [Basic Finish Calendar Quarter Code],
        [Basic Finish Calendar Weekday Number],
        [Basic Finish Calendar Weekday Name],
        [Basic Finish Calendar Day In Month],
        [Basic Finish Calendar Day In Year],
        [Basic Finish Calendar Week],
        [Basic Finish Calendar Month In Quarter Number],
        [Basic Finish Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Basic Finish Current Day Flag],
        [Basic Finish Current Day Minus 1 Flag],
        [Basic Finish Current Calendar Week Flag],
        [Basic Finish Current Calendar Week Minus 1 Flag],
        [Basic Finish Current Month Flag],
        [Basic Finish Current Month Minus 1 Flag],
        [Basic Finish Current Month Minus 12 Flag],
        [Basic Finish Current Quarter Flag],
        [Basic Finish Current Quarter Minus 1 Flag],
        [Basic Finish Current Quarter Minus 4 Flag],
        [Basic Finish Current Calendar Year Flag],
        [Basic Finish Current Calendar Year Minus 1 Flag],
        [Basic Finish Current Calendar Year Minus 2 Flag],
        [Basic Finish Current Fiscal Year Flag],
        [Basic Finish Current Fiscal Year Minus 1 Flag],
        [Basic Finish Current Fiscal Year Minus 2 Flag],
        [Basic Finish Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Basic Finish Day In Fiscal Year],
        [Basic Finish Date Is Weekday],
        [Basic Finish Fiscal Week],
        [Basic Finish Current Fiscal Week Flag],
        [Basic Finish Current Fiscal Week Minus 1 Flag],
        [Basic Finish Fiscal Weekday Number],
        [Basic Finish Fiscal Weekday Name],
        [Basic Finish Current Month Minus 2 Flag],
        [Basic Finish Current Fiscal Week Minus 2 Flag],
        [Basic Finish Current Fiscal Week Minus 6 Flag],
        [Basic Finish Current Fiscal Week Minus 3 Flag],
        [Basic Finish Current Fiscal Week Minus 4 Flag],
        [Basic Finish Current Fiscal Week Minus 5 Flag],
        [Basic Finish Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[Basic_Finish_Date] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
 
END