-- Auto Generated (Do not modify) AD6A79103301052FF14C6CDC32BAF821A594E8CAA4487E51B54966B82DF9C003
CREATE   view [Propelis].[V_ACTUAL_RELEASE_DATE]
(		
        [DATE_KEY],
        [Actual Release Date],
        [Actual Release Fiscal Year],
        [Actual Release Fiscal Period Number],
        [Actual Release Fiscal Period Code],
        [Actual Release Fiscal Quarter Number],
        [Actual Release Fiscal Quarter Code],
        [Actual Release Calendar Year],
        [Actual Release Calendar Month Number],
        [Actual Release Calendar Month Code],
        [Actual Release Calendar Month Description],
        [Actual Release Calendar Quarter Number],
        [Actual Release Calendar Quarter Code],
        [Actual Release Calendar Weekday Number],
        [Actual Release Calendar Weekday Name],
        [Actual Release Calendar Day In Month],
        [Actual Release Calendar Day In Year],
        [Actual Release Calendar Week],
        [Actual Release Calendar Month In Quarter Number],
        [Actual Release Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Actual Release Current Day Flag],
        [Actual Release Current Day Minus 1 Flag],
        [Actual Release Current Calendar Week Flag],
        [Actual Release Current Calendar Week Minus 1 Flag],
        [Actual Release Current Month Flag],
        [Actual Release Current Month Minus 1 Flag],
        [Actual Release Current Month Minus 12 Flag],
        [Actual Release Current Quarter Flag],
        [Actual Release Current Quarter Minus 1 Flag],
        [Actual Release Current Quarter Minus 4 Flag],
        [Actual Release Current Calendar Year Flag],
        [Actual Release Current Calendar Year Minus 1 Flag],
        [Actual Release Current Calendar Year Minus 2 Flag],
        [Actual Release Current Fiscal Year Flag],
        [Actual Release Current Fiscal Year Minus 1 Flag],
        [Actual Release Current Fiscal Year Minus 2 Flag],
        [Actual Release Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Actual Release Day In Fiscal Year],
        [Actual Release Date Is Weekday],
        [Actual Release Fiscal Week],
        [Actual Release Current Fiscal Week Flag],
        [Actual Release Current Fiscal Week Minus 1 Flag],
        [Actual Release Fiscal Weekday Number],
        [Actual Release Fiscal Weekday Name],
        [Actual Release Current Month Minus 2 Flag],
        [Actual Release Current Fiscal Week Minus 2 Flag],
        [Actual Release Current Fiscal Week Minus 6 Flag],
        [Actual Release Current Fiscal Week Minus 3 Flag],
        [Actual Release Current Fiscal Week Minus 4 Flag],
        [Actual Release Current Fiscal Week Minus 5 Flag],
        [Actual Release Current Fiscal Week Minus 7 Flag]
)AS
SELECT
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];