-- Auto Generated (Do not modify) 62C545CBC780F5B7B9DBD5AB1B08B4D15C09005F2745CA23E59B5FD86284530B
CREATE   view [Propelis].[V_ACTUAL_FINISH_EXEC_DATE]
(
        [DATE_KEY]                                           ,
        [Actual Finish Exec Date]                                  ,
        [Actual Finish Exec Fiscal Year]                           ,
        [Actual Finish Exec Fiscal Period Number]                  ,
        [Actual Finish Exec Fiscal Period Code]                    ,
        [Actual Finish Exec Fiscal Quarter Number]                 ,
        [Actual Finish Exec Fiscal Quarter Code]                   ,
        [Actual Finish Exec Calendar Year]                         ,
        [Actual Finish Exec Calendar Month Number]                 ,
        [Actual Finish Exec Calendar Month Code]                   ,
        [Actual Finish Exec Calendar Month Description]            ,
        [Actual Finish Exec Calendar Quarter Number]               ,
        [Actual Finish Exec Calendar Quarter Code]                 ,
        [Actual Finish Exec Calendar Weekday Number]               ,
        [Actual Finish Exec Calendar Weekday Name]                 ,
        [Actual Finish Exec Calendar Day In Month]                 ,
        [Actual Finish Exec Calendar Day In Year]                  ,
        [Actual Finish Exec Calendar Week]                         ,
        [Actual Finish Exec Calendar Month In Quarter Number]      ,
        [Actual Finish Exec Calendar Days In Month]                ,
        [ETL_SRC_SYS_CD]                                     ,
        [ETL_CREATED_TS]                                     ,
        [ETL_UPDTD_TS]                                       ,
        [Actual Finish Exec Current Day Flag]                      ,
        [Actual Finish Exec Current Day Minus 1 Flag]              ,
        [Actual Finish Exec Current Calendar Week Flag]            ,
        [Actual Finish Exec Current Calendar Week Minus 1 Flag]    ,
        [Actual Finish Exec Current Month Flag]                    ,
        [Actual Finish Exec Current Month Minus 1 Flag]            ,
        [Actual Finish Exec Current Month Minus 12 Flag]           ,
        [Actual Finish Exec Current Quarter Flag]                  ,
        [Actual Finish Exec Current Quarter Minus 1 Flag]          ,
        [Actual Finish Exec Current Quarter Minus 4 Flag]          ,
        [Actual Finish Exec Current Calendar Year Flag]            ,
        [Actual Finish Exec Current Calendar Year Minus 1 Flag]    ,
        [Actual Finish Exec Current Calendar Year Minus 2 Flag]    ,
        [Actual Finish Exec Current Fiscal Year Flag]              ,
        [Actual Finish Exec Current Fiscal Year Minus 1 Flag]      ,
        [Actual Finish Exec Current Fiscal Year Minus 2 Flag]      ,
        [Actual Finish Exec Current Calendar Year Plus 1 Flag]     ,
        [Actual Finish Exec Current Calendar Year Plus 2 Flag]     ,
        [Actual Finish Exec Day In Fiscal Year]                    ,
        [Actual Finish Exec Date Is Weekday]                       ,
        [Actual Finish Exec Fiscal Week]                           ,
        [Actual Finish Exec Current Fiscal Week Flag]              ,
        [Actual Finish Exec Current Fiscal Week Minus 1 Flag]      ,
        [Actual Finish Exec Fiscal Weekday Number]                 ,
        [Actual Finish Exec Fiscal Weekday Name]                   ,
        [Actual Finish Exec Current Month Minus 2 Flag]            ,
        [Actual Finish Exec Current Fiscal Week Minus 2 Flag]      ,
        [Actual Finish Exec Current Fiscal Week Minus 6 Flag]      ,
        [Actual Finish Exec Current Fiscal Week Minus 3 Flag]      ,
        [Actual Finish Exec Current Fiscal Week Minus 4 Flag]      ,
        [Actual Finish Exec Current Fiscal Week Minus 5 Flag]      ,
        [Actual Finish Exec Current Fiscal Week Minus 7 Flag]
)AS
SELECT
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];