-- Auto Generated (Do not modify) 580B7E03EE2F712D2220EA07E24E4350E8A67C42D1C480724B1F918C5FB8B931
CREATE   view [Propelis].[V_ACTUAL_FINISH_DATE]
(		
        [DATE_KEY],
        [Actual Finish Date],
        [Actual Finish Fiscal Year],
        [Actual Finish Fiscal Period Number],
        [Actual Finish Fiscal Period Code],
        [Actual Finish Fiscal Quarter Number],
        [Actual Finish Fiscal Quarter Code],
        [Actual Finish Calendar Year],
        [Actual Finish Calendar Month Number],
        [Actual Finish Calendar Month Code],
        [Actual Finish Calendar Month Description],
        [Actual Finish Calendar Quarter Number],
        [Actual Finish Calendar Quarter Code],
        [Actual Finish Calendar Weekday Number],
        [Actual Finish Calendar Weekday Name],
        [Actual Finish Calendar Day In Month],
        [Actual Finish Calendar Day In Year],
        [Actual Finish Calendar Week],
        [Actual Finish Calendar Month In Quarter Number],
        [Actual Finish Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Actual Finish Current Day Flag],
        [Actual Finish Current Day Minus 1 Flag],
        [Actual Finish Current Calendar Week Flag],
        [Actual Finish Current Calendar Week Minus 1 Flag],
        [Actual Finish Current Month Flag],
        [Actual Finish Current Month Minus 1 Flag],
        [Actual Finish Current Month Minus 12 Flag],
        [Actual Finish Current Quarter Flag],
        [Actual Finish Current Quarter Minus 1 Flag],
        [Actual Finish Current Quarter Minus 4 Flag],
        [Actual Finish Current Calendar Year Flag],
        [Actual Finish Current Calendar Year Minus 1 Flag],
        [Actual Finish Current Calendar Year Minus 2 Flag],
        [Actual Finish Current Fiscal Year Flag],
        [Actual Finish Current Fiscal Year Minus 1 Flag],
        [Actual Finish Current Fiscal Year Minus 2 Flag],
        [Actual Finish Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Actual Finish Day In Fiscal Year],
        [Actual Finish Date Is Weekday],
        [Actual Finish Fiscal Week],
        [Actual Finish Current Fiscal Week Flag],
        [Actual Finish Current Fiscal Week Minus 1 Flag],
        [Actual Finish Fiscal Weekday Number],
        [Actual Finish Fiscal Weekday Name],
        [Actual Finish Current Month Minus 2 Flag],
        [Actual Finish Current Fiscal Week Minus 2 Flag],
        [Actual Finish Current Fiscal Week Minus 6 Flag],
        [Actual Finish Current Fiscal Week Minus 3 Flag],
        [Actual Finish Current Fiscal Week Minus 4 Flag],
        [Actual Finish Current Fiscal Week Minus 5 Flag],
        [Actual Finish Current Fiscal Week Minus 7 Flag]
)AS
SELECT
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];