-- Auto Generated (Do not modify) CE850E78B192FFB5EA18668ACD7A18D6A43841865517E8505ACC28375A4DC2BF
CREATE   view [Propelis].[V_ACTUAL_START_DATE]
(		
        [DATE_KEY],
        [Actual Start Date],
        [Actual Start Fiscal Year],
        [Actual Start Fiscal Period Number],
        [Actual Start Fiscal Period Code],
        [Actual Start Fiscal Quarter Number],
        [Actual Start Fiscal Quarter Code],
        [Actual Start Calendar Year],
        [Actual Start Calendar Month Number],
        [Actual Start Calendar Month Code],
        [Actual Start Calendar Month Description],
        [Actual Start Calendar Quarter Number],
        [Actual Start Calendar Quarter Code],
        [Actual Start Calendar Weekday Number],
        [Actual Start Calendar Weekday Name],
        [Actual Start Calendar Day In Month],
        [Actual Start Calendar Day In Year],
        [Actual Start Calendar Week],
        [Actual Start Calendar Month In Quarter Number],
        [Actual Start Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Actual Start Current Day Flag],
        [Actual Start Current Day Minus 1 Flag],
        [Actual Start Current Calendar Week Flag],
        [Actual Start Current Calendar Week Minus 1 Flag],
        [Actual Start Current Month Flag],
        [Actual Start Current Month Minus 1 Flag],
        [Actual Start Current Month Minus 12 Flag],
        [Actual Start Current Quarter Flag],
        [Actual Start Current Quarter Minus 1 Flag],
        [Actual Start Current Quarter Minus 4 Flag],
        [Actual Start Current Calendar Year Flag],
        [Actual Start Current Calendar Year Minus 1 Flag],
        [Actual Start Current Calendar Year Minus 2 Flag],
        [Actual Start Current Fiscal Year Flag],
        [Actual Start Current Fiscal Year Minus 1 Flag],
        [Actual Start Current Fiscal Year Minus 2 Flag],
        [Actual Start Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Actual Start Day In Fiscal Year],
        [Actual Start Date Is Weekday],
        [Actual Start Fiscal Week],
        [Actual Start Current Fiscal Week Flag],
        [Actual Start Current Fiscal Week Minus 1 Flag],
        [Actual Start Fiscal Weekday Number],
        [Actual Start Fiscal Weekday Name],
        [Actual Start Current Month Minus 2 Flag],
        [Actual Start Current Fiscal Week Minus 2 Flag],
        [Actual Start Current Fiscal Week Minus 6 Flag],
        [Actual Start Current Fiscal Week Minus 3 Flag],
        [Actual Start Current Fiscal Week Minus 4 Flag],
        [Actual Start Current Fiscal Week Minus 5 Flag],
        [Actual Start Current Fiscal Week Minus 7 Flag]
)AS
SELECT
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];