-- Auto Generated (Do not modify) 370DAE223741663DFCCB327E0BFC786F29132B7E228467A0BDD07308A495BB1E
CREATE VIEW [Propelis].[V_BASIC_START_DATE] (
        [DATE_KEY],
        [Basic Start Date],
        [Basic Start Fiscal Year],
        [Basic Start Fiscal Period Number],
        [Basic Start Fiscal Period Code],
        [Basic Start Fiscal Quarter Number],
        [Basic Start Fiscal Quarter Code],
        [Basic Start Calendar Year],
        [Basic Start Calendar Month Number],
        [Basic Start Calendar Month Code],
        [Basic Start Calendar Month Description],
        [Basic Start Calendar Quarter Number],
        [Basic Start Calendar Quarter Code],
        [Basic Start Calendar Weekday Number],
        [Basic Start Calendar Weekday Name],
        [Basic Start Calendar Day In Month],
        [Basic Start Calendar Day In Year],
        [Basic Start Calendar Week],
        [Basic Start Calendar Month In Quarter Number],
        [Basic Start Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Basic Start Current Day Flag],
        [Basic Start Current Day Minus 1 Flag],
        [Basic Start Current Calendar Week Flag],
        [Basic Start Current Calendar Week Minus 1 Flag],
        [Basic Start Current Month Flag],
        [Basic Start Current Month Minus 1 Flag],
        [Basic Start Current Month Minus 12 Flag],
        [Basic Start Current Quarter Flag],
        [Basic Start Current Quarter Minus 1 Flag],
        [Basic Start Current Quarter Minus 4 Flag],
        [Basic Start Current Calendar Year Flag],
        [Basic Start Current Calendar Year Minus 1 Flag],
        [Basic Start Current Calendar Year Minus 2 Flag],
        [Basic Start Current Fiscal Year Flag],
        [Basic Start Current Fiscal Year Minus 1 Flag],
        [Basic Start Current Fiscal Year Minus 2 Flag],
        [Basic Start Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Basic Start Day In Fiscal Year],
        [Basic Start Date Is Weekday],
        [Basic Start Fiscal Week],
        [Basic Start Current Fiscal Week Flag],
        [Basic Start Current Fiscal Week Minus 1 Flag],
        [Basic Start Fiscal Weekday Number],
        [Basic Start Fiscal Weekday Name],
        [Basic Start Current Month Minus 2 Flag],
        [Basic Start Current Fiscal Week Minus 2 Flag],
        [Basic Start Current Fiscal Week Minus 6 Flag],
        [Basic Start Current Fiscal Week Minus 3 Flag],
        [Basic Start Current Fiscal Week Minus 4 Flag],
        [Basic Start Current Fiscal Week Minus 5 Flag],
        [Basic Start Current Fiscal Week Minus 7 Flag]
    ) AS 
    SELECT
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D]