-- Auto Generated (Do not modify) 19A91CF60A3EC48C8A91F9068DC93E8266802AD6BD4B661C4ABF034476671CD9
CREATE   view [Propelis].[V_BASIC_FINISH_DATE]
(		
        [DATE_KEY],
        [Basic Finish Date],
        [Basic Finish Fiscal Year],
        [Basic Finish Fiscal Period Number],
        [Basic Finish Fiscal Period Code],
        [Basic Finish Fiscal Quarter Number],
        [Basic Finish Fiscal Quarter Code],
        [Basic Finish Calendar Year],
        [Basic Finish Calendar Month Number],
        [Basic Finish Calendar Month Code],
        [Basic Finish Calendar Month Description],
        [Basic Finish Calendar Quarter Number],
        [Basic Finish Calendar Quarter Code],
        [Basic Finish Calendar Weekday Number],
        [Basic Finish Calendar Weekday Name],
        [Basic Finish Calendar Day In Month],
        [Basic Finish Calendar Day In Year],
        [Basic Finish Calendar Week],
        [Basic Finish Calendar Month In Quarter Number],
        [Basic Finish Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Basic Finish Current Day Flag],
        [Basic Finish Current Day Minus 1 Flag],
        [Basic Finish Current Calendar Week Flag],
        [Basic Finish Current Calendar Week Minus 1 Flag],
        [Basic Finish Current Month Flag],
        [Basic Finish Current Month Minus 1 Flag],
        [Basic Finish Current Month Minus 12 Flag],
        [Basic Finish Current Quarter Flag],
        [Basic Finish Current Quarter Minus 1 Flag],
        [Basic Finish Current Quarter Minus 4 Flag],
        [Basic Finish Current Calendar Year Flag],
        [Basic Finish Current Calendar Year Minus 1 Flag],
        [Basic Finish Current Calendar Year Minus 2 Flag],
        [Basic Finish Current Fiscal Year Flag],
        [Basic Finish Current Fiscal Year Minus 1 Flag],
        [Basic Finish Current Fiscal Year Minus 2 Flag],
        [Basic Finish Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Basic Finish Day In Fiscal Year],
        [Basic Finish Date Is Weekday],
        [Basic Finish Fiscal Week],
        [Basic Finish Current Fiscal Week Flag],
        [Basic Finish Current Fiscal Week Minus 1 Flag],
        [Basic Finish Fiscal Weekday Number],
        [Basic Finish Fiscal Weekday Name],
        [Basic Finish Current Month Minus 2 Flag],
        [Basic Finish Current Fiscal Week Minus 2 Flag],
        [Basic Finish Current Fiscal Week Minus 6 Flag],
        [Basic Finish Current Fiscal Week Minus 3 Flag],
        [Basic Finish Current Fiscal Week Minus 4 Flag],
        [Basic Finish Current Fiscal Week Minus 5 Flag],
        [Basic Finish Current Fiscal Week Minus 7 Flag]
)AS
SELECT
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];