-- Auto Generated (Do not modify) BBB881A2CEEA87A093A667E52FB0C8133C8882DA9ED1F95B760452F1C96AD5F1
CREATE   view [Propelis].[V_BILL_TO_CUST] (
                 [CUST_KEY],
                [Bill To Customer ID],
                [Bill To Customer Legacy ID],
                [Bill To Customer Name],
                [Bill To Cust Line 2 Description],
                [Bill To Cust Country Code],
                [Bill To Cust Plant ID],
                [Bill To Cust Segment ID],
                [Bill To Cust Industry],
                [Bill To Cust Vendor ID],
                [Bill To Cust Group Code],
                [Bill To Cust Account Group Code],
                [Bill To Cust Title],
                [Bill To Cust Search Term],
                [Bill To Cust Street],
                [Bill To Cust City],
                [Bill To Cust Zip Code],
                [Bill To Cust State Code],
                [Bill To Cust Region Code],
                [Bill To Cust Telephone Number 1],
                [Bill To Cust Telephone Number 2],
                [Bill To Cust Fax Number Code],
                [Bill To Cust Tax Number 1 Code],
                [Bill To Cust Tax Number 2 Code],
                [Bill To Cust VAT Number Code],
                [Bill To Cust Credit Limit],
                [Bill To Cust Bonus Rate],
                [Bill To Cust Express Station],
                [Bill To Cust Transport Zone],
                [Bill To Cust Printer Location Characteristics],
                [Bill To Cust Printer Region Characteristics],
                [Bill To Cust Printer Site Characteristics],
                [Bill To Cust Created Date],
                [Bill To Cust Created User ID],
                [Bill To Cust Updated Date],
                [Bill To Cust Updated User ID],
                [Bill To Cust Payment Terms Code],
                [Bill To Cust Sales Distribution],
                [Bill To Cust Order Block For Sales Area],
                [Bill To Cust Delivery Block For Sales Area],
                [ETL_SRC_SYS_CD],
                [ETL_EFFECTV_BEGIN_DATE],
                [ETL_EFFECTV_END_DATE],
                [ETL_CURR_RCD_IND],
                [ETL_CREATED_TS],
                [ETL_UPDTD_TS],
                [Bill To Cust Corporate Group],
                [Bill To Cust Customer Classification],
                [Bill To Cust Classification Description],
                [Bill To Cust Printer Location],
                [Bill To Cust Printer Site],
                [Bill To Cust Printer Region],
                [Bill To Cust Specific Field Label 01],
                [Bill To Cust Specific Field Label 02],
                [Bill To Cust Specific Field Label 03],
                [Bill To Cust Specific Field Label 04],
                [Bill To Cust Specific Field Label 05],
                [Bill To Cust Specific Field Label 06],
                [Bill To Cust Specific Field Label 07],
                [Bill To Cust Specific Field Label 08],
                [Bill To Cust Specific Field Label 09],
                [Bill To Cust Specific Field Label 10],
                [Bill To Cust Specific Field Label 11],
                [Bill To Cust Specific Field Label 12],
                [Bill To Cust Specific Field Label 13],
                [Bill To Cust Specific Field Label 14],
                [Bill To Cust Specific Field Label 15],
                [Bill To Cust Specific Field Label 16],
                [Bill To Cust Specific Field Label 17],
                [Bill To Cust Specific Field Label 18],
                [Bill To Cust Specific Field Label 19],
                [Bill To Cust Specific Field Label 20],
                [Bill To Cust Condition Group 1],
                [Bill To Cust Industry Code 1],
                [Bill To Cust Industry Code 2],
                [Bill To Cust Industry Description],
                [Bill To Cust Industry Code 1 Description],
                [Bill To Cust Industry Code 2 Description],
                [Bill To Cust Assignment to Hierarchy],
                [Bill To Cust Account Group Description],
                [Bill To Cust Region Description],
                [Bill To Cust Country Description],
                [Bill To Cust Transportation Zone Description],
                [Bill To Cust Plant Description],
                [Bill To Cust Condition Group Description],
                [Bill To Cust Cental Billing Block],
                [Bill To Cust Cental Billing Block Description],
                [Bill To Cust Central Delivery Block],
                [Bill To Cust Central Delivery Block Description],
                [Bill To Cust Deletion Indicator],
                [Bill To Cust Central Posting Block],
                [Bill To Cust Tax Jurisdiction],
                [Bill To Cust Central Sales Block],
                [Bill To Cust Central Deletion Indicator],
                [Bill To Cust Language Key],
                [Bill To Cust Trading Partner],
                [Bill To Cust Trading Partner Description],
                [Bill To Cust Annual Sales],
                [Bill To Cust Annual Sales Year],
                [Bill To Cust Sales Currency],
                [Bill To Cust Sales Currency Description],
                [Bill To Cust One Time Account Group],
                [Bill To Cust One Time Account Group Description],
                [Bill To Cust One Time Indicator],
                [Bill To Cust Industry Type],
                [Bill To Cust Business Type],
                [Bill To Cust DUNS Number],
                [Bill To Cust DUNS Plus 4],
                [Bill To City Coordinates],
                [Bill To Cust Tax Number 4 Code],
                [Bill To Cust Attribute 3],
                [Bill To Cust Attribute 3 Description],
                [Bill To Cust E-Mail Address],
                [Bill To Cust Mobile Number],
                [Bill To Cust Search Term 2],
                [Bill To Cust Street 2],
                [Bill To Cust Street 3],
                [Bill To Cust Street 4],
                [Bill To Cust Street 5],
                [Bill To Cust PO Box],
                [Bill To Cust PO Box Postal Code],
                [Bill To Cust PO Box City],
                [Bill To Cust Region For PO Box],
                [Bill To Cust PO Box Country],
                [Bill To Cust Transportation Zone],
                [Bill To Cust Address Notes],
                [Bill To Cust Tax Number 3 Code],
                [Bill To Cust Tax Number 5 Code],
                [Bill To Cust Industry Code 3],
                [Bill To Cust Industry Code 3 Description],
                [Bill To Cust Industry Code 4],
                [Bill To Cust Industry Code 4 Description],
                [Bill To Cust Industry Code 5],
                [Bill To Cust Industry Code 5 Description],
                [Bill To Cust Central Order Block For Customer],
                [Bill To Cust Payment Block]
) AS
SELECT [CUST_KEY],
        [Customer ID],
        [Legacy Customer ID],
        [Customer Name],
        [Customer Line 2 Description],
        [Customer Country Code],
        [Customer Plant ID],
        [Customer Segment ID],
        [Customer Industry],
        [Customer Vendor ID],
        [Customer Group Code],
        [Customer Account Group Code],
        [Customer Title],
        [Customer Search Term],
        [Customer Street],
        [Customer City],
        [Customer Zip Code],
        [Customer State Code],
        [Customer Region Code],
        [Customer Telephone Number 1],
        [Customer Telephone Number 2],
        [Customer Fax Number Code],
        [Customer Tax Number 1 Code],
        [Customer Tax Number 2 Code],
        [Customer VAT Number Code],
        [Customer Credit Limit],
        [Customer Bonus Rate],
        [Customer Express Station],
        [Customer Transportation Zone],
        [Customer Printer Location Characteristics],
        [Customer Printer Region Characteristics],
        [Customer Printer Site Characteristics],
        [Customer Created Date],
        [Customer Created User ID],
        [Customer Updated Date],
        [Customer Updated User ID],
        [Customer Payment Terms Code],
        [Customer Sales Distribution],
        [Customer Order Block For Sales Area],
        [Customer Delivery Block For Sales Area],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Customer Corporate Group],
        [Customer Classification],
        [Customer Classification Description],
        [Customer Printer Location],
        [Customer Printer Site],
        [Customer Printer Region],
        [Customer Specific Field Label 01],
        [Customer Specific Field Label 02],
        [Customer Specific Field Label 03],
        [Customer Specific Field Label 04],
        [Customer Specific Field Label 05],
        [Customer Specific Field Label 06],
        [Customer Specific Field Label 07],
        [Customer Specific Field Label 08],
        [Customer Specific Field Label 09],
        [Customer Specific Field Label 10],
        [Customer Specific Field Label 11],
        [Customer Specific Field Label 12],
        [Customer Specific Field Label 13],
        [Customer Specific Field Label 14],
        [Customer Specific Field Label 15],
        [Customer Specific Field Label 16],
        [Customer Specific Field Label 17],
        [Customer Specific Field Label 18],
        [Customer Specific Field Label 19],
        [Customer Specific Field Label 20],
        [Customer Condition Group 1],
        [Customer Industry Code 1],
        [Customer Industry Code 2],
        [Customer Industry Description],
        [Customer Industry Code 1 Description],
        [Customer Industry Code 2 Description],
        [Customer Assignment to Hierarchy],
        [Customer Account Group Description],
        [Customer Region Description],
        [Customer Country Description],
        [Customer Transportation Zone Description],
        [Customer Plant Description],
        [Customer Condition Group Description],
        [Customer Cental Billing Block],
        [Customer Cental Billing Block Description],
        [Customer Central Delivery Block],
        [Customer Central Delivery Block Description],
        [Customer Deletion Indicator],
        [Customer Central Posting Block],
        [Customer Tax Jurisdiction],
        [Customer Central Sales Block],
        [Customer Central Deletion Indicator],
        [Customer Language Key],
        [Customer Trading Partner],
        [Customer Trading Partner Description],
        [Customer Annual Sales],
        [Customer Annual Sales Year],
        [Customer Sales Currency],
        [Customer Sales Currency Description],
        [Customer One Time Account Group],
        [Customer One Time Account Group Description],
        [Customer One Time Indicator],
        [Customer Industry Type],
        [Customer Business Type],
        [Customer DUNS Number],
        [Customer DUNS Plus 4],
        [Customer City Coordinates],
        [Customer Tax Number 4 Code],
        [Customer Attribute 3],
        [Customer Attribute 3 Description],
        [Customer E-Mail Address],
        [Customer Mobile Number],
        [Customer Search Term 2],
        [Customer Street 2],
        [Customer Street 3],
        [Customer Street 4],
        [Customer Street 5],
        [Customer PO Box],
        [Customer PO Box Postal Code],
        [Customer PO Box City],
        [Customer Region For PO Box],
        [Customer PO Box Country],
        [Customer Transport Zone],
        [Customer Address Notes],
        [Customer Tax Number 3 Code],
        [Customer Tax Number 5 Code],
        [Customer Industry Code 3],
        [Customer Industry Code 3 Description],
        [Customer Industry Code 4],
        [Customer Industry Code 4 Description],
        [Customer Industry Code 5],
        [Customer Industry Code 5 Description],
        [Customer Central Order Block For Customer],
        [Customer Payment Block]
        FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D];