-- Auto Generated (Do not modify) 11D4432239173296A6AE311B24ACEAAD6F819D97C09032DBF23B1175A3972D8A
CREATE   view [Propelis].[V_BRAND_OWNER_CUST] (
                 [CUST_KEY],
                 [Brand Owner Customer ID],
                 [Brand Owner Customer Legacy ID],
                 [Brand Owner Customer Name],
                 [Brand Owner Cust Line 2 Description],
                 [Brand Owner Cust Country Code],
                 [Brand Owner Cust Plant ID],
                 [Brand Owner Cust Segment ID],
                 [Brand Owner Cust Industry],
                 [Brand Owner Cust Vendor ID],
                 [Brand Owner Cust Group Code],
                 [Brand Owner Cust Account Group Code],
                 [Brand Owner Cust Title],
                 [Brand Owner Cust Search Term],
                 [Brand Owner Cust Street],
                 [Brand Owner Cust City],
                 [Brand Owner Cust Zip Code],
                 [Brand Owner Cust State Code],
                 [Brand Owner Cust Region Code],
                 [Brand Owner Cust Telephone Number 1],
                 [Brand Owner Cust Telephone Number 2],
                 [Brand Owner Cust Fax Number Code],
                 [Brand Owner Cust Tax Number 1 Code],
                 [Brand Owner Cust Tax Number 2 Code],
                 [Brand Owner Cust VAT Number Code],
                 [Brand Owner Cust Credit Limit],
                 [Brand Owner Cust Bonus Rate],
                 [Brand Owner Cust Express Station],
                 [Brand Owner Cust Transportation Zone],
                 [Brand Owner Cust Printer Location Characteristics],
                 [Brand Owner Cust Printer Region Characteristics],
                 [Brand Owner Cust Printer Site Characteristics],
                 [Brand Owner Cust Created Date],
                 [Brand Owner Cust Created User ID],
                 [Brand Owner Cust Updated Date],
                 [Brand Owner Cust Updated User ID],
                 [Brand Owner Cust Payment Terms Code],
                 [Brand Owner Cust Sales Distribution],
                 [Brand Owner Cust Order Block For Sales Area],
                 [Brand Owner Cust Delivery Block For Sales Area],
                 [ETL_SRC_SYS_CD],
                 [ETL_EFFECTV_BEGIN_DATE],
                 [ETL_EFFECTV_END_DATE],
                 [ETL_CURR_RCD_IND],
                 [ETL_CREATED_TS],
                 [ETL_UPDTD_TS],
                 [Brand Owner Cust Corporate Group],
                 [Brand Owner Customer Classification],
                 [Brand Owner Cust Classification Description],
                 [Brand Owner Cust Printer Location],
                 [Brand Owner Cust Printer Site],
                 [Brand Owner Cust Printer Region],
                 [Brand Owner Cust Specific Field Label 01],
                 [Brand Owner Cust Specific Field Label 02],
                 [Brand Owner Cust Specific Field Label 03],
                 [Brand Owner Cust Specific Field Label 04],
                 [Brand Owner Cust Specific Field Label 05],
                 [Brand Owner Cust Specific Field Label 06],
                 [Brand Owner Cust Specific Field Label 07],
                 [Brand Owner Cust Specific Field Label 08],
                 [Brand Owner Cust Specific Field Label 09],
                 [Brand Owner Cust Specific Field Label 10],
                 [Brand Owner Cust Specific Field Label 11],
                 [Brand Owner Cust Specific Field Label 12],
                 [Brand Owner Cust Specific Field Label 13],
                 [Brand Owner Cust Specific Field Label 14],
                 [Brand Owner Cust Specific Field Label 15],
                 [Brand Owner Cust Specific Field Label 16],
                 [Brand Owner Cust Specific Field Label 17],
                 [Brand Owner Cust Specific Field Label 18],
                 [Brand Owner Cust Specific Field Label 19],
                 [Brand Owner Cust Specific Field Label 20],
                 [Brand Owner Cust Condition Group 1],
                 [Brand Owner Cust Industry Code 1],
                 [Brand Owner Cust Industry Code 2],
                 [Brand Owner Cust Industry Description],
                 [Brand Owner Cust Industry Code 1 Description],
                 [Brand Owner Cust Industry Code 2 Description],
                 [Brand Owner Assignment to Hierarchy],
                 [Brand Owner Cust Account Group Description],
                 [Brand Owner Cust Region Description],
                 [Brand Owner Cust Country Description],
                 [Brand Owner Cust Transportation Zone Description],
                 [Brand Owner Cust Plant Description],
                 [Brand Owner Cust Condition Group Description],
                 [Brand Owner Cust Cental Branding Block],
                 [Brand Owner Cust Cental Branding Block Description],
                 [Brand Owner Cust Central Delivery Block],
                 [Brand Owner Cust Central Delivery Block Description],
                 [Brand Owner Cust Deletion IndicaOwnerr],
                 [Brand Owner Cust Central Posting Block],
                 [Brand Owner Cust Tax Jurisdiction],
                 [Brand Owner Cust Central Sales Block],
                 [Brand Owner Cust Central Deletion Indicator],
                 [Brand Owner Cust Language Key],
                 [Brand Owner Cust Trading Partner],
                 [Brand Owner Cust Trading Partner Description],
                 [Brand Owner Cust Annual Sales],
                 [Brand Owner Cust Annual Sales Year],
                 [Brand Owner Cust Sales Currency],
                 [Brand Owner Cust Sales Currency Description],
                 [Brand Owner Cust One Time Account Group],
                 [Brand Owner Cust One Time Account Group Description],
                 [Brand Owner Cust One Time Indicator],
                 [Brand Owner Cust Industry Type],
                 [Brand Owner Cust Business Type],
                 [Brand Owner Cust DUNS Number],
                 [Brand Owner Cust DUNS Plus 4],
                 [Brand Owner City Coordinates],
                 [Brand Owner Cust Tax Number 4 Code],
                 [Brand Owner Cust Attribute 3],
                 [Brand Owner Cust Attribute 3 Description],
                 [Brand Owner Cust E-Mail Address],
                 [Brand Owner Cust Mobile Number],
                 [Brand Owner Cust Search Term 2],
                 [Brand Owner Cust Street 2],
                 [Brand Owner Cust Street 3],
                 [Brand Owner Cust Street 4],
                 [Brand Owner Cust Street 5],
                 [Brand Owner Cust PO Box],
                 [Brand Owner Cust PO Box Postal Code],
                 [Brand Owner Cust PO Box City],
                 [Brand Owner Cust Region For PO Box],
                 [Brand Owner Cust PO Box Country],
                 [Brand Owner Cust Transport Zone],
                 [Brand Owner Cust Address Notes],
                 [Brand Owner Cust Tax Number 3 Code],
                 [Brand Owner Cust Tax Number 5 Code],
                 [Brand Owner Cust Industry Code 3],
                 [Brand Owner Cust Industry Code 3 Description],
                 [Brand Owner Cust Industry Code 4],
                 [Brand Owner Cust Industry Code 4 Description],
                 [Brand Owner Cust Industry Code 5],
                 [Brand Owner Cust Industry Code 5 Description],
                 [Brand Owner Cust Central Order Block For Customer],
                 [Brand Owner Cust Payment Block]
    ) AS 
    SELECT 
    [CUST_KEY],
        [Customer ID],
        [Legacy Customer ID],
        [Customer Name],
        [Customer Line 2 Description],
        [Customer Country Code],
        [Customer Plant ID],
        [Customer Segment ID],
        [Customer Industry],
        [Customer Vendor ID],
        [Customer Group Code],
        [Customer Account Group Code],
        [Customer Title],
        [Customer Search Term],
        [Customer Street],
        [Customer City],
        [Customer Zip Code],
        [Customer State Code],
        [Customer Region Code],
        [Customer Telephone Number 1],
        [Customer Telephone Number 2],
        [Customer Fax Number Code],
        [Customer Tax Number 1 Code],
        [Customer Tax Number 2 Code],
        [Customer VAT Number Code],
        [Customer Credit Limit],
        [Customer Bonus Rate],
        [Customer Express Station],
        [Customer Transportation Zone],
        [Customer Printer Location Characteristics],
        [Customer Printer Region Characteristics],
        [Customer Printer Site Characteristics],
        [Customer Created Date],
        [Customer Created User ID],
        [Customer Updated Date],
        [Customer Updated User ID],
        [Customer Payment Terms Code],
        [Customer Sales Distribution],
        [Customer Order Block For Sales Area],
        [Customer Delivery Block For Sales Area],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Customer Corporate Group],
        [Customer Classification],
        [Customer Classification Description],
        [Customer Printer Location],
        [Customer Printer Site],
        [Customer Printer Region],
        [Customer Specific Field Label 01],
        [Customer Specific Field Label 02],
        [Customer Specific Field Label 03],
        [Customer Specific Field Label 04],
        [Customer Specific Field Label 05],
        [Customer Specific Field Label 06],
        [Customer Specific Field Label 07],
        [Customer Specific Field Label 08],
        [Customer Specific Field Label 09],
        [Customer Specific Field Label 10],
        [Customer Specific Field Label 11],
        [Customer Specific Field Label 12],
        [Customer Specific Field Label 13],
        [Customer Specific Field Label 14],
        [Customer Specific Field Label 15],
        [Customer Specific Field Label 16],
        [Customer Specific Field Label 17],
        [Customer Specific Field Label 18],
        [Customer Specific Field Label 19],
        [Customer Specific Field Label 20],
        [Customer Condition Group 1],
        [Customer Industry Code 1],
        [Customer Industry Code 2],
        [Customer Industry Description],
        [Customer Industry Code 1 Description],
        [Customer Industry Code 2 Description],
        [Customer Assignment to Hierarchy],
        [Customer Account Group Description],
        [Customer Region Description],
        [Customer Country Description],
        [Customer Transportation Zone Description],
        [Customer Plant Description],
        [Customer Condition Group Description],
        [Customer Cental Billing Block],
        [Customer Cental Billing Block Description],
        [Customer Central Delivery Block],
        [Customer Central Delivery Block Description],
        [Customer Deletion Indicator],
        [Customer Central Posting Block],
        [Customer Tax Jurisdiction],
        [Customer Central Sales Block],
        [Customer Central Deletion Indicator],
        [Customer Language Key],
        [Customer Trading Partner],
        [Customer Trading Partner Description],
        [Customer Annual Sales],
        [Customer Annual Sales Year],
        [Customer Sales Currency],
        [Customer Sales Currency Description],
        [Customer One Time Account Group],
        [Customer One Time Account Group Description],
        [Customer One Time Indicator],
        [Customer Industry Type],
        [Customer Business Type],
        [Customer DUNS Number],
        [Customer DUNS Plus 4],
        [Customer City Coordinates],
        [Customer Tax Number 4 Code],
        [Customer Attribute 3],
        [Customer Attribute 3 Description],
        [Customer E-Mail Address],
        [Customer Mobile Number],
        [Customer Search Term 2],
        [Customer Street 2],
        [Customer Street 3],
        [Customer Street 4],
        [Customer Street 5],
        [Customer PO Box],
        [Customer PO Box Postal Code],
        [Customer PO Box City],
        [Customer Region For PO Box],
        [Customer PO Box Country],
        [Customer Transport Zone],
        [Customer Address Notes],
        [Customer Tax Number 3 Code],
        [Customer Tax Number 5 Code],
        [Customer Industry Code 3],
        [Customer Industry Code 3 Description],
        [Customer Industry Code 4],
        [Customer Industry Code 4 Description],
        [Customer Industry Code 5],
        [Customer Industry Code 5 Description],
        [Customer Central Order Block For Customer],
        [Customer Payment Block]
        FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D];