-- Auto Generated (Do not modify) 8814D1B2FD372B53C746A4BCA303EAC60C7473EA6539C25D1D3283D2B5B8E5A2
CREATE   view [Propelis].[V_CLOSE_DATE]
(		
		[DATE_KEY]                                           ,
        [Close Date]                                  ,
        [Close Fiscal Year]                           ,
        [Close Fiscal Period Number]                  ,
        [Close Fiscal Period Code]                    ,
        [Close Fiscal Quarter Number]                 ,
        [Close Fiscal Quarter Code]                   ,
        [Close Calendar Year]                         ,
        [Close Calendar Month Number]                 ,
        [Close Calendar Month Code]                   ,
        [Close Calendar Month Description]            ,
        [Close Calendar Quarter Number]               ,
        [Close Calendar Quarter Code]                 ,
        [Close Calendar Weekday Number]               ,
        [Close Calendar Weekday Name]                 ,
        [Close Calendar Day In Month]                 ,
        [Close Calendar Day In Year]                  ,
        [Close Calendar Week]                         ,
        [Close Calendar Month In Quarter Number]      ,
        [Close Calendar Days In Month]                ,
        [ETL_SRC_SYS_CD]                                     ,
        [ETL_CREATED_TS]                                     ,
        [ETL_UPDTD_TS]                                       ,
        [Close Current Day Flag]                      ,
        [Close Current Day Minus 1 Flag]              ,
        [Close Current Calendar Week Flag]            ,
        [Close Current Calendar Week Minus 1 Flag]    ,
        [Close Current Month Flag]                    ,
        [Close Current Month Minus 1 Flag]            ,
        [Close Current Month Minus 12 Flag]           ,
        [Close Current Quarter Flag]                  ,
        [Close Current Quarter Minus 1 Flag]          ,
        [Close Current Quarter Minus 4 Flag]          ,
        [Close Current Calendar Year Flag]            ,
        [Close Current Calendar Year Minus 1 Flag]    ,
        [Close Current Calendar Year Minus 2 Flag]    ,
        [Close Current Fiscal Year Flag]              ,
        [Close Current Fiscal Year Minus 1 Flag]      ,
        [Close Current Fiscal Year Minus 2 Flag]      ,
        [Close Current Calendar Year Plus 1 Flag]     ,
        [Close Current Calendar Year Plus 2 Flag]     ,
        [Close Day In Fiscal Year]                    ,
        [Close Date Is Weekday]                       ,
        [Close Fiscal Week]                           ,
        [Close Current Fiscal Week Flag]              ,
        [Close Current Fiscal Week Minus 1 Flag]      ,
        [Close Fiscal Weekday Number]                 ,
        [Close Fiscal Weekday Name]                   ,
        [Close Current Month Minus 2 Flag]            ,
        [Close Current Fiscal Week Minus 2 Flag]      ,
        [Close Current Fiscal Week Minus 6 Flag]      ,
        [Close Current Fiscal Week Minus 3 Flag]      ,
        [Close Current Fiscal Week Minus 4 Flag]      ,
        [Close Current Fiscal Week Minus 5 Flag]      ,
        [Close Current Fiscal Week Minus 7 Flag]
)AS
SELECT
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];