-- Auto Generated (Do not modify) 0E0A671B71F956FB33F5B7A36A53358BE3A28DCEC69F842D99ADBFBF63FCD1D5

create view [Propelis].[V_COMPANY](
	[CMPNY_KEY],
[Company],
[Company Legacy Code],
[Company Name],
[Company Line Of Business Code],
[Company Line Of Business Code Description],
[Company Currency Code],
[Company Language Type Code],
[Company Chart Of Accounts ID],
[Company Address Line 1],
[Company Address Line 2],
[Company City Name],
[Company Zip Code],
[Company Country Code],
[Company Telephone 1],
[Company Telephone 2],
[Company Fax Number],
[Company Tax Jurisdiction],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Company Fiscal Year Variant],
[Company Credit Control Area],
[Company Input Tax Cd],
[Company Output Tax Code],
[Company Currency Description],
[Company Chart Of Accounts Description],
[Company Country Description],
[Company Fiscal Year Variant Description],
[Company Credit Control Area Description]
) as
SELECT 
    [CMPNY_KEY],
[Company Code],
[Legacy Company Code],
[Company Name],
[Company Line Of Business],
[Company Line Of Business Description],
[Company Currency Code],
[Company Language Type Code],
[Company Chart Of Accounts ID],
[Company Address Line 1],
[Company Address Line 2],
[Company City Name],
[Company Zip Code],
[Company Country Code],
[Company Telephone 1],
[Company Telephone 2],
[Company Fax Number],
[Company Tax Jurisdiction],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Company Fiscal Year Variant],
[Company Credit Control Area],
[Company Input Tax Code],
[Company Output Tax Code],
[Company Currency Description],
[Company Chart Of Accounts Description],
[Company Country Description],
[Company Fiscal Year Variant Description],
[Company Credit Control Area Description]
  FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CMPNYCD_CUR_D];