-- Auto Generated (Do not modify) 6D67E6172DF0B103B48DF4B693471C24006748159A17380CF8A477EE61F9FDA8
CREATE   view [Propelis].[V_COMPANY_INFO] (
        [CMPNY_KEY],
        [Company Code],
        [Legacy Company Code],
        [Company Name],
        [Line Of Business],
        [Line Of Business Description],
        [Currency Code],
        [Language Type Code],
        [Chart Of Accounts ID],
        [Entity Address Line 1],
        [Entity Address Line 2],
        [Entity City Name],
        [Entity Zip Code],
        [Entity Country Code],
        [Entity Telephone1],
        [Entity Telephone 2],
        [Fax Number],
        [Tax Jurisdiction],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Fiscal Year Variant],
        [Credit Control Area],
        [Input Tax Code],
        [Output Tax Code],
        [Currency Description],
        [Chart Of Accounts Description],
        [Country Description],
        [Fiscal Year Variant Description],
        [Credit Control Area Description]
				
            )
as select 
        [CMPNY_KEY],
        [Company Code],
        [Legacy Company Code],
        [Company Name],
        [Company Line Of Business],
        [Company Line Of Business Description],
        [Company Currency Code],
        [Company Language Type Code],
        [Company Chart Of Accounts ID],
        [Company Address Line 1],
        [Company Address Line 2],
        [Company City Name],
        [Company Zip Code],
        [Company Country Code],
        [Company Telephone 1],
        [Company Telephone 2],
        [Company Fax Number],
        [Company Tax Jurisdiction],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Company Fiscal Year Variant],
        [Company Credit Control Area],
        [Company Input Tax Code],
        [Company Output Tax Code],
        [Company Currency Description],
        [Company Chart Of Accounts Description],
        [Company Country Description],
        [Company Fiscal Year Variant Description],
        [Company Credit Control Area Description]
   from  [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CMPNYCD_CUR_D];