-- Auto Generated (Do not modify) AA90F50537F75A6A08E9B6B85C0E5705D5B7514620E04B0580B6C7F40D45E743
CREATE VIEW [Propelis].[V_CREATED_ON_DATE] (
        [DATE_KEY],
        [Created On Date],
        [Created On Fiscal Year],
        [Created On Fiscal Period Number],
        [Created On Fiscal Period Code],
        [Created On Fiscal Quarter Number],
        [Created On Fiscal Quarter Code],
        [Created On Calendar Year],
        [Created On Calendar Month Number],
        [Created On Calendar Month Code],
        [Created On Calendar Month Description],
        [Created On Calendar Quarter Number],
        [Created On Calendar Quarter Code],
        [Created On Calendar Weekday Number],
        [Created On Calendar Weekday Name],
        [Created On Calendar Day In Month],
        [Created On Calendar Day In Year],
        [Created On Calendar Week],
        [Created On Calendar Month In Quarter Number],
        [Created On Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Created On Current Day Flag],
        [Created On Current Day Minus 1 Flag],
        [Created On Current Calendar Week Flag],
        [Created On Current Calendar Week Minus 1 Flag],
        [Created On Current Month Flag],
        [Created On Current Month Minus 1 Flag],
        [Created On Current Month Minus 12 Flag],
        [Created On Current Quarter Flag],
        [Created On Current Quarter Minus 1 Flag],
        [Created On Current Quarter Minus 4 Flag],
        [Created On Current Calendar Year Flag],
        [Created On Current Calendar Year Minus 1 Flag],
        [Created On Current Calendar Year Minus 2 Flag],
        [Created On Current Fiscal Year Flag],
        [Created On Current Fiscal Year Minus 1 Flag],
        [Created On Current Fiscal Year Minus 2 Flag],
        [Created On Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Created On Day In Fiscal Year],
        [Created On Date Is Weekday],
        [Created On Fiscal Week],
        [Created On Current Fiscal Week Flag],
        [Created On Current Fiscal Week Minus 1 Flag],
        [Created On Fiscal Weekday Number],
        [Created On Fiscal Weekday Name],
        [Created On Current Month Minus 2 Flag],
        [Created On Current Fiscal Week Minus 2 Flag],
        [Created On Current Fiscal Week Minus 6 Flag],
        [Created On Current Fiscal Week Minus 3 Flag],
        [Created On Current Fiscal Week Minus 4 Flag],
        [Created On Current Fiscal Week Minus 5 Flag],
        [Created On Current Fiscal Week Minus 7 Flag]
    ) AS
    SELECT
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D]