-- Auto Generated (Do not modify) A592A0A674E726658123020642AC6B7B9E2D02010B42357DB865F200D530E63C
CREATE   view [Propelis].[V_CYLINDER_OWNER_CUST] (
                 [CUST_KEY],
                 [Cylinder Owner Customer ID],
                 [Cylinder Owner Customer Legacy ID],
                 [Cylinder Owner Customer Name],
                 [Cylinder Owner Cust Line 2 Description],
                 [Cylinder Owner Cust Country Code],
                 [Cylinder Owner Cust Plant ID],
                 [Cylinder Owner Cust Segment ID],
                 [Cylinder Owner Cust Industry],
                 [Cylinder Owner Cust Vendor ID],
                 [Cylinder Owner Cust Group Code],
                 [Cylinder Owner Cust Account Group Code],
                 [Cylinder Owner Cust Title],
                 [Cylinder Owner Cust Search Term],
                 [Cylinder Owner Cust Street],
                 [Cylinder Owner Cust City],
                 [Cylinder Owner Cust Zip Code],
                 [Cylinder Owner Cust State Code],
                 [Cylinder Owner Cust Region Code],
                 [Cylinder Owner Cust Telephone Number 1],
                 [Cylinder Owner Cust Telephone Number 2],
                 [Cylinder Owner Cust Fax Number Code],
                 [Cylinder Owner Cust Tax Number 1 Code],
                 [Cylinder Owner Cust Tax Number 2 Code],
                 [Cylinder Owner Cust VAT Number Code],
                 [Cylinder Owner Cust Credit Limit],
                 [Cylinder Owner Cust Bonus Rate],
                 [Cylinder Owner Cust Express Station],
                 [Cylinder Owner Cust Transportation Zone],
                 [Cylinder Owner Cust Printer Location Characteristics],
                 [Cylinder Owner Cust Printer Region Characteristics],
                 [Cylinder Owner Cust Printer Site Characteristics],
                 [Cylinder Owner Cust Created Date],
                 [Cylinder Owner Cust Created User ID],
                 [Cylinder Owner Cust Updated Date],
                 [Cylinder Owner Cust Updated User ID],
                 [Cylinder Owner Cust Payment Terms Code],
                 [Cylinder Owner Cust Sales Distribution],
                 [Cylinder Owner Cust Order Block For Sales Area],
                 [Cylinder Owner Cust Delivery Block For Sales Area],
                 [ETL_SRC_SYS_CD],
                 [ETL_EFFECTV_BEGIN_DATE],
                 [ETL_EFFECTV_END_DATE],
                 [ETL_CURR_RCD_IND],
                 [ETL_CREATED_TS],
                 [ETL_UPDTD_TS],
                 [Cylinder Owner Cust Corporate Group],
                 [Cylinder Owner Cust Customer Classification],
                 [Cylinder Owner Cust Classification Description],
                 [Cylinder Owner Cust Printer Location],
                 [Cylinder Owner Cust Printer Site],
                 [Cylinder Owner Cust Printer Region],
                 [Cylinder Owner Cust Specific Field Label 01],
                 [Cylinder Owner Cust Specific Field Label 02],
                 [Cylinder Owner Cust Specific Field Label 03],
                 [Cylinder Owner Cust Specific Field Label 04],
                 [Cylinder Owner Cust Specific Field Label 05],
                 [Cylinder Owner Cust Specific Field Label 06],
                 [Cylinder Owner Cust Specific Field Label 07],
                 [Cylinder Owner Cust Specific Field Label 08],
                 [Cylinder Owner Cust Specific Field Label 09],
                 [Cylinder Owner Cust Specific Field Label 10],
                 [Cylinder Owner Cust Specific Field Label 11],
                 [Cylinder Owner Cust Specific Field Label 12],
                 [Cylinder Owner Cust Specific Field Label 13],
                 [Cylinder Owner Cust Specific Field Label 14],
                 [Cylinder Owner Cust Specific Field Label 15],
                 [Cylinder Owner Cust Specific Field Label 16],
                 [Cylinder Owner Cust Specific Field Label 17],
                 [Cylinder Owner Cust Specific Field Label 18],
                 [Cylinder Owner Cust Specific Field Label 19],
                 [Cylinder Owner Cust Specific Field Label 20],
                 [Cylinder Owner Cust Condition Group 1],
                 [Cylinder Owner Cust Industry Code 1],
                 [Cylinder Owner Cust Industry Code 2],
                 [Cylinder Owner Cust Industry Description],
                 [Cylinder Owner Cust Industry Code 1 Description],
                 [Cylinder Owner Cust Industry Code 2 Description],
                 [Cylinder Owner Cust Assignment to Hierarchy],
                 [Cylinder Owner Cust Account Group Description],
                 [Cylinder Owner Cust Region Description],
                 [Cylinder Owner Cust Country Description],
                 [Cylinder Owner Cust Transportation Zone Description],
                 [Cylinder Owner Cust Plant Description],
                 [Cylinder Owner Cust Condition Group Description],
                 [Cylinder Owner Cust Cental Cylindering Block],
                 [Cylinder Owner Cust Cental Cylindering Block Description],
                 [Cylinder Owner Cust Central Delivery Block],
                 [Cylinder Owner Cust Central Delivery Block Description],
                 [Cylinder Owner Cust Deletion Indicator],
                 [Cylinder Owner Cust Central Posting Block],
                 [Cylinder Owner Cust Tax Jurisdiction],
                 [Cylinder Owner Cust Central Sales Block],
                 [Cylinder Owner Cust Central Deletion Indicator],
                 [Cylinder Owner Cust Language Key],
                 [Cylinder Owner Cust Trading Partner],
                 [Cylinder Owner Cust Trading Partner Description],
                 [Cylinder Owner Cust Annual Sales],
                 [Cylinder Owner Cust Annual Sales Year],
                 [Cylinder Owner Cust Sales Currency],
                 [Cylinder Owner Cust Sales Currency Description],
                 [Cylinder Owner Cust One Time Account Group],
                 [Cylinder Owner Cust One Time Account Group Description],
                 [Cylinder Owner Cust One Time Indicator],
                 [Cylinder Owner Cust Industry Type],
                 [Cylinder Owner Cust Business Type],
                 [Cylinder Owner Cust DUNS Number],
                 [Cylinder Owner Cust DUNS Plus 4],
                 [Cylinder Owner City Coordinates],
                 [Cylinder Owner Cust Tax Number 4 Code],
                 [Cylinder Owner Cust Attribute 3],
                 [Cylinder Owner Cust Attribute 3 Description],
                 [Cylinder Owner Cust E-Mail Address],
                 [Cylinder Owner Cust Mobile Number],
                 [Cylinder Owner Cust Search Term 2],
                 [Cylinder Owner Cust Street 2],
                 [Cylinder Owner Cust Street 3],
                 [Cylinder Owner Cust Street 4],
                 [Cylinder Owner Cust Street 5],
                 [Cylinder Owner Cust PO Box],
                 [Cylinder Owner Cust PO Box Postal Code],
                 [Cylinder Owner Cust PO Box City],
                 [Cylinder Owner Cust Region For PO Box],
                 [Cylinder Owner Cust PO Box Country],
                 [Cylinder Owner Cust Transport Zone],
                 [Cylinder Owner Cust Address Notes],
                 [Cylinder Owner Cust Tax Number 3 Code],
                 [Cylinder Owner Cust Tax Number 5 Code],
                 [Cylinder Owner Cust Industry Code 3],
                 [Cylinder Owner Cust Industry Code 3 Description],
                 [Cylinder Owner Cust Industry Code 4],
                 [Cylinder Owner Cust Industry Code 4 Description],
                 [Cylinder Owner Cust Industry Code 5],
                 [Cylinder Owner Cust Industry Code 5 Description],
                 [Cylinder Owner Cust Central Order Block For Customer],
                 [Cylinder Owner Cust Payment Block]

    )
     AS 
    SELECT 
    [CUST_KEY],
        [Customer ID],
        [Legacy Customer ID],
        [Customer Name],
        [Customer Line 2 Description],
        [Customer Country Code],
        [Customer Plant ID],
        [Customer Segment ID],
        [Customer Industry],
        [Customer Vendor ID],
        [Customer Group Code],
        [Customer Account Group Code],
        [Customer Title],
        [Customer Search Term],
        [Customer Street],
        [Customer City],
        [Customer Zip Code],
        [Customer State Code],
        [Customer Region Code],
        [Customer Telephone Number 1],
        [Customer Telephone Number 2],
        [Customer Fax Number Code],
        [Customer Tax Number 1 Code],
        [Customer Tax Number 2 Code],
        [Customer VAT Number Code],
        [Customer Credit Limit],
        [Customer Bonus Rate],
        [Customer Express Station],
        [Customer Transportation Zone],
        [Customer Printer Location Characteristics],
        [Customer Printer Region Characteristics],
        [Customer Printer Site Characteristics],
        [Customer Created Date],
        [Customer Created User ID],
        [Customer Updated Date],
        [Customer Updated User ID],
        [Customer Payment Terms Code],
        [Customer Sales Distribution],
        [Customer Order Block For Sales Area],
        [Customer Delivery Block For Sales Area],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Customer Corporate Group],
        [Customer Classification],
        [Customer Classification Description],
        [Customer Printer Location],
        [Customer Printer Site],
        [Customer Printer Region],
        [Customer Specific Field Label 01],
        [Customer Specific Field Label 02],
        [Customer Specific Field Label 03],
        [Customer Specific Field Label 04],
        [Customer Specific Field Label 05],
        [Customer Specific Field Label 06],
        [Customer Specific Field Label 07],
        [Customer Specific Field Label 08],
        [Customer Specific Field Label 09],
        [Customer Specific Field Label 10],
        [Customer Specific Field Label 11],
        [Customer Specific Field Label 12],
        [Customer Specific Field Label 13],
        [Customer Specific Field Label 14],
        [Customer Specific Field Label 15],
        [Customer Specific Field Label 16],
        [Customer Specific Field Label 17],
        [Customer Specific Field Label 18],
        [Customer Specific Field Label 19],
        [Customer Specific Field Label 20],
        [Customer Condition Group 1],
        [Customer Industry Code 1],
        [Customer Industry Code 2],
        [Customer Industry Description],
        [Customer Industry Code 1 Description],
        [Customer Industry Code 2 Description],
        [Customer Assignment to Hierarchy],
        [Customer Account Group Description],
        [Customer Region Description],
        [Customer Country Description],
        [Customer Transportation Zone Description],
        [Customer Plant Description],
        [Customer Condition Group Description],
        [Customer Cental Billing Block],
        [Customer Cental Billing Block Description],
        [Customer Central Delivery Block],
        [Customer Central Delivery Block Description],
        [Customer Deletion Indicator],
        [Customer Central Posting Block],
        [Customer Tax Jurisdiction],
        [Customer Central Sales Block],
        [Customer Central Deletion Indicator],
        [Customer Language Key],
        [Customer Trading Partner],
        [Customer Trading Partner Description],
        [Customer Annual Sales],
        [Customer Annual Sales Year],
        [Customer Sales Currency],
        [Customer Sales Currency Description],
        [Customer One Time Account Group],
        [Customer One Time Account Group Description],
        [Customer One Time Indicator],
        [Customer Industry Type],
        [Customer Business Type],
        [Customer DUNS Number],
        [Customer DUNS Plus 4],
        [Customer City Coordinates],
        [Customer Tax Number 4 Code],
        [Customer Attribute 3],
        [Customer Attribute 3 Description],
        [Customer E-Mail Address],
        [Customer Mobile Number],
        [Customer Search Term 2],
        [Customer Street 2],
        [Customer Street 3],
        [Customer Street 4],
        [Customer Street 5],
        [Customer PO Box],
        [Customer PO Box Postal Code],
        [Customer PO Box City],
        [Customer Region For PO Box],
        [Customer PO Box Country],
        [Customer Transport Zone],
        [Customer Address Notes],
        [Customer Tax Number 3 Code],
        [Customer Tax Number 5 Code],
        [Customer Industry Code 3],
        [Customer Industry Code 3 Description],
        [Customer Industry Code 4],
        [Customer Industry Code 4 Description],
        [Customer Industry Code 5],
        [Customer Industry Code 5 Description],
        [Customer Central Order Block For Customer],
        [Customer Payment Block]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D];