-- Auto Generated (Do not modify) 3FDBBCA9EDD2BDD30557C9D9994103E32B9E34996B1931FCC0F392056A807A9B
CREATE   view [Propelis].[V_DOCUMENT_DATE](
    [DATE_KEY],
    [Entry Create Date],
    [Entry Create Fiscal Year],
    [Entry Create Fiscal Period Number],
    [Entry Create Fiscal Period Code],
    [Entry Create Fiscal Quarter Number],
    [Entry Create Fiscal Quarter Code],
    [Entry Create Calendar Year],
    [Entry Create Calendar Month Number],
    [Entry Create Calendar Month Code],
    [Entry Create Calendar Month Description],
    [Entry Create Calendar Quarter Number],
    [Entry Create Calendar Quarter Code],
    [Entry Create Calendar Weekday Number],
    [Entry Create Calendar Weekday Name],
    [Entry Create Calendar Day In Month],
    [Entry Create Calendar Day In Year],
    [Entry Create Calendar Week],
    [Entry Create Calendar Month In Quarter Number],
    [Entry Create Calendar Days In Month],
    [ETL_SRC_SYS_CD],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Entry Create Current Day Flag],
    [Entry Create Current Day Minus 1 Flag],
    [Entry Create Current Calendar Week Flag],
    [Entry Create Current Calendar Week Minus 1 Flag],
    [Entry Create Current Month Flag],
    [Entry Create Current Month Minus 1 Flag],
    [Entry Create Current Month Minus 12 Flag],
    [Entry Create Current Quarter Flag],
    [Entry Create Current Quarter Minus 1 Flag],
    [Entry Create Current Quarter Minus 4 Flag],
    [Entry Create Current Calendar Year Flag],
    [Entry Create Current Calendar Year Minus 1 Flag],
    [Entry Create Current Calendar Year Minus 2 Flag],
    [Entry Create Current Fiscal Year Flag],
    [Entry Create Current Fiscal Year Minus 1 Flag],
    [Entry Create Current Fiscal Year Minus 2 Flag],
    [Entry Create Current Calendar Year Plus 1 Flag],
    [CURR_FISCAL_YR_PLUS_1_FLG],
    [Entry Create Day In Fiscal Year],
    [Entry Create Date Is Weekday],
    [Entry Create Fiscal Week],
    [Entry Create Current Fiscal Week Flag],
    [Entry Create Current Fiscal Week Minus 1 Flag],
    [Entry Create Fiscal Weekday Number],
    [Entry Create Fiscal Weekday Name],
    [Entry Create Current Month Minus 2 Flag],
    [Entry Create Current Fiscal Week Minus 2 Flag],
    [Entry Create Current Fiscal Week Minus 6 Flag],
    [Entry Create Current Fiscal Week Minus 3 Flag],
    [Entry Create Current Fiscal Week Minus 4 Flag],
    [Entry Create Current Fiscal Week Minus 5 Flag],
    [Entry Create Current Fiscal Week Minus 7 Flag]
	
) AS
SELECT 
    [DATE_KEY],
    [Date],
    [Date Fiscal Year],
    [FISCAL_PER_NUM],
    [Date Fiscal Period Code],
    [Date Fiscal Quarter Number],
    [Date Fiscal Quarter Code],
    [Date Calendar Year],
    [Date Calendar Month Number],
    [Date Calendar Month Code],
    [Date Calendar Month Desc],
    [CLNDR_QTR_NUM],
    [Date Calendar Quarter Code],
    [Date Calendar Weekday Number],
    [Date Calendar Weekday Name],
    [Date Calendar Day in Month],
    [Date Calendar Day in Year],
    [Date Calendar Week],
    [Date Calendar Month in Quarter Number],
    [Date Calendar Days in Month],
    [ETL_SRC_SYS_CD],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Date Current Day Flag],
    [Date Current Day Minus 1 Flag],
    [Date Current Calendar Week Flag],
    [Date Current Calendar Week Minus 1 Flag],
    [Date Current Month Flag],
    [Date Current Month Minus 1 Flag],
    [Date Current Month Minus 12 Flag],
    [Date Current Quarter Flag],
    [Date Current Quarter Minus 1 Flag],
    [Date Current Quarter Minus 4 Flag],
    [Date Current Calendar Year Flag],
    [Date Current Calendar Year Minus 1 Flag],
    [Date Current Calendar Year Minus 2 Flag],
    [Date Current Fiscal Year Flag],
    [Date Current Fiscal Year Minus 1 Flag],
    [Date Current Fiscal Year Minus 2 Flag],
    [Date Current Calendar Year Plus 1 Flag],
    [Date Current Fiscal Year Plus 1 Flag],
    [Date Day in Fiscal Year],
    [Date Date Is Weekday],
    [Date Fiscal Week],
    [Date Current Fiscal Week Flag],
    [Date Current Fiscal Week Minus 1 Flag],
    [Date Fiscal Weekday Number],
    [Date Fiscal Weekday Name],
    [Date Current Month Minus 2 Flag],
    [Date Current Fiscal Week Minus 2 Flag],
    [Date Current Fiscal Week Minus 6 Flag],
    [Date Current Fiscal Week Minus 3 Flag],
    [Date Current Fiscal Week Minus 4 Flag],
    [Date Current Fiscal Week Minus 5 Flag],
    [Date Current Fiscal Week Minus 7 Flag]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];