-- Auto Generated (Do not modify) D0DB108F5013C817CF53BA2834E057420B716D645F217A2BE0C234E7ABECC256

create view [Propelis].[V_EMPLOYEE_RESPONSIBLE](
[PERSONEL_KEY],
[Personnel Number],
[Company Code],
[Plant ID],
[Cost Center ID],
[Success Factors ID],
[Employee First Name],
[Employee Last Name],
[Employee Full Name],
[Employee Status Indicator],
[Employment Start Date],
[Employment End Date],
[Employee Group ID],
[Employee Group Description],
[Employee Subgroup ID],
[Employee Subgroup Description],
[Employee Telephone 1],
[Employee Telephone 2],
[Email Address],
[Created Date],
[Created User ID],
[Updated Date],
[Updated User ID],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Company Description],
[Plant Description]
) as
SELECT 
   [PERSONEL_KEY],
[Personnel Number],
[Personnel Company Code],
[Personnel Plant ID],
[Personnel Cost Center ID],
[Personnel Success Factors ID],
[Personnel Employee First Name],
[Personnel Employee Last Name],
[Personnel Employee Full Name],
[Personnel Employee Status Indicator],
[Personnel Employment Start Date],
[Personnel Employment End Date],
[Personnel Employee Group ID],
[Personnel Employee Group Description],
[Personnel Employee SubGroup ID],
[Personnel Employee SubGroup Description],
[Personnel Employee Telephone 1],
[Personnel Employee Telephone 2],
[EMAIL_ADDR],
[Personnel Created Date],
[Personnel Created User ID],
[Personnel Updated Date],
[Personnel Updated User ID],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Personnel Company Description],
[Personnel Plant Description]
  FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PERSONL_CUR_D];