-- Auto Generated (Do not modify) 8D5331EDF087C47E3E8DDE9A0B804E219D1CBEC2BCEADAD20137D9AC77367710
CREATE VIEW [Propelis].[V_END_OF_MALFUNCTION_DATE] (
        [DATE_KEY],
        [End Of Malfunction Date],
        [End Of Malfunction Fiscal Year],
        [End Of Malfunction Fiscal Period Number],
        [End Of Malfunction Fiscal Period Code],
        [End Of Malfunction Fiscal Quarter Number],
        [End Of Malfunction Fiscal Quarter Code],
        [End Of Malfunction Calendar Year],
        [End Of Malfunction Calendar Month Number],
        [End Of Malfunction Calendar Month Code],
        [End Of Malfunction Calendar Month Description],
        [End Of Malfunction Calendar Quarter Number],
        [End Of Malfunction Calendar Quarter Code],
        [End Of Malfunction Calendar Weekday Number],
        [End Of Malfunction Calendar Weekday Name],
        [End Of Malfunction Calendar Day In Month],
        [End Of Malfunction Calendar Day In Year],
        [End Of Malfunction Calendar Week],
        [End Of Malfunction Calendar Month In Quarter Number],
        [End Of Malfunction Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [End Of Malfunction Current Day Flag],
        [End Of Malfunction Current Day Minus 1 Flag],
        [End Of Malfunction Current Calendar Week Flag],
        [End Of Malfunction Current Calendar Week Minus 1 Flag],
        [End Of Malfunction Current Month Flag],
        [End Of Malfunction Current Month Minus 1 Flag],
        [End Of Malfunction Current Month Minus 12 Flag],
        [End Of Malfunction Current Quarter Flag],
        [End Of Malfunction Current Quarter Minus 1 Flag],
        [End Of Malfunction Current Quarter Minus 4 Flag],
        [End Of Malfunction Current Calendar Year Flag],
        [End Of Malfunction Current Calendar Year Minus 1 Flag],
        [End Of Malfunction Current Calendar Year Minus 2 Flag],
        [End Of Malfunction Current Fiscal Year Flag],
        [End Of Malfunction Current Fiscal Year Minus 1 Flag],
        [End Of Malfunction Current Fiscal Year Minus 2 Flag],
        [End Of Malfunction Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [End Of Malfunction Day In Fiscal Year],
        [End Of Malfunction Date Is Weekday],
        [End Of Malfunction Fiscal Week],
        [End Of Malfunction Current Fiscal Week Flag],
        [End Of Malfunction Current Fiscal Week Minus 1 Flag],
        [End Of Malfunction Fiscal Weekday Number],
        [End Of Malfunction Fiscal Weekday Name],
        [End Of Malfunction Current Month Minus 2 Flag],
        [End Of Malfunction Current Fiscal Week Minus 2 Flag],
        [End Of Malfunction Current Fiscal Week Minus 6 Flag],
        [End Of Malfunction Current Fiscal Week Minus 3 Flag],
        [End Of Malfunction Current Fiscal Week Minus 4 Flag],
        [End Of Malfunction Current Fiscal Week Minus 5 Flag],
        [End Of Malfunction Current Fiscal Week Minus 7 Flag]
    ) AS 
    SELECT
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D]