-- Auto Generated (Do not modify) 9A25C6AC8605FA2F16EBAF9F6EEF644B1B0D61D3A3275410AB9F1A180F9E9CE3
CREATE   VIEW [Propelis].[V_FINISH_CONSTRAINT_DATE](
    [DATE_KEY],
    [Finish Constraint Date],
    [Finish Constraint Fiscal Year],
    [Finish Constraint Fiscal Period Number],
    [Finish Constraint Fiscal Period Code],
    [Finish Constraint Fiscal Quarter Number],
    [Finish Constraint Fiscal Quarter Code],
    [Finish Constraint Calendar Year],
    [Finish Constraint Calendar Month Number],
    [Finish Constraint Calendar Month Code],
    [Finish Constraint Calendar Month Description],
    [Finish Constraint Calendar Quarter Number],
    [Finish Constraint Calendar Quarter Code],
    [Finish Constraint Calendar Weekday Number],
    [Finish Constraint Calendar Weekday Name],
    [Finish Constraint Calendar Day In Month],
    [Finish Constraint Calendar Day In Year],
    [Finish Constraint Calendar Week],
    [Finish Constraint Calendar Month In Quarter Number],
    [Finish Constraint Calendar Days In Month],
    [ETL_SRC_SYS_CD],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Finish Constraint Current Day Flag],
    [Finish Constraint Current Day Minus 1 Flag],
    [Finish Constraint Current Calendar Week Flag],
    [Finish Constraint Current Calendar Week Minus 1 Flag],
    [Finish Constraint Current Month Flag],
    [Finish Constraint Current Month Minus 1 Flag],
    [Finish Constraint Current Month Minus 12 Flag],
    [Finish Constraint Current Quarter Flag],
    [Finish Constraint Current Quarter Minus 1 Flag],
    [Finish Constraint Current Quarter Minus 4 Flag],
    [Finish Constraint Current Calendar Year Flag],
    [Finish Constraint Current Calendar Year Minus 1 Flag],
    [Finish Constraint Current Calendar Year Minus 2 Flag],
    [Finish Constraint Current Fiscal Year Flag],
    [Finish Constraint Current Fiscal Year Minus 1 Flag],
    [Finish Constraint Current Fiscal Year Minus 2 Flag],
    [Finish Constraint Current Calendar Year Plus 1 Flag],
    [Finish Constraint Current Calendar Year Plus 2 Flag],
    [Finish Constraint Day In Fiscal Year],
    [Finish Constraint Date Is Weekday],
    [Finish Constraint Fiscal Week],
    [Finish Constraint Current Fiscal Week Flag],
    [Finish Constraint Current Fiscal Week Minus 1 Flag],
    [Finish Constraint Fiscal Weekday Number],
    [Finish Constraint Fiscal Weekday Name],
    [Finish Constraint Current Month Minus 2 Flag],
    [Finish Constraint Current Fiscal Week Minus 2 Flag],
    [Finish Constraint Current Fiscal Week Minus 6 Flag],
    [Finish Constraint Current Fiscal Week Minus 3 Flag],
    [Finish Constraint Current Fiscal Week Minus 4 Flag],
    [Finish Constraint Current Fiscal Week Minus 5 Flag],
    [Finish Constraint Current Fiscal Week Minus 7 Flag]
)AS
SELECT
    [DATE_KEY],
    [Date],
    [Date Fiscal Year],
    [FISCAL_PER_NUM],
    [Date Fiscal Period Code],
    [Date Fiscal Quarter Number],
    [Date Fiscal Quarter Code],
    [Date Calendar Year],
    [Date Calendar Month Number],
    [Date Calendar Month Code],
    [Date Calendar Month Desc],
    [CLNDR_QTR_NUM],
    [Date Calendar Quarter Code],
    [Date Calendar Weekday Number],
    [Date Calendar Weekday Name],
    [Date Calendar Day in Month],
    [Date Calendar Day in Year],
    [Date Calendar Week],
    [Date Calendar Month in Quarter Number],
    [Date Calendar Days in Month],
    [ETL_SRC_SYS_CD],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Date Current Day Flag],
    [Date Current Day Minus 1 Flag],
    [Date Current Calendar Week Flag],
    [Date Current Calendar Week Minus 1 Flag],
    [Date Current Month Flag],
    [Date Current Month Minus 1 Flag],
    [Date Current Month Minus 12 Flag],
    [Date Current Quarter Flag],
    [Date Current Quarter Minus 1 Flag],
    [Date Current Quarter Minus 4 Flag],
    [Date Current Calendar Year Flag],
    [Date Current Calendar Year Minus 1 Flag],
    [Date Current Calendar Year Minus 2 Flag],
    [Date Current Fiscal Year Flag],
    [Date Current Fiscal Year Minus 1 Flag],
    [Date Current Fiscal Year Minus 2 Flag],
    [Date Current Calendar Year Plus 1 Flag],
    [Date Current Fiscal Year Plus 1 Flag],
    [Date Day in Fiscal Year],
    [Date Date Is Weekday],
    [Date Fiscal Week],
    [Date Current Fiscal Week Flag],
    [Date Current Fiscal Week Minus 1 Flag],
    [Date Fiscal Weekday Number],
    [Date Fiscal Weekday Name],
    [Date Current Month Minus 2 Flag],
    [Date Current Fiscal Week Minus 2 Flag],
    [Date Current Fiscal Week Minus 6 Flag],
    [Date Current Fiscal Week Minus 3 Flag],
    [Date Current Fiscal Week Minus 4 Flag],
    [Date Current Fiscal Week Minus 5 Flag],
    [Date Current Fiscal Week Minus 7 Flag]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];