-- Auto Generated (Do not modify) 67EC77A5752E3444CD84AAA71EA3D7A64D4E6E9B455F66A50BDED93C182C51DE
CREATE   VIEW [Propelis].[V_FORWARDING_AGENT_VENDOR](
    [VNDR_KEY],
	[Forwarding Agent Vendor ID],
	[Forwarding Agent Vendor Name],
	[Forwarding Agent Vendor Description],
	[Forwarding Agent Vendor Account Group],
	[Forwarding Agent Vendor Title],
	[Forwarding Agent Vendor Search Term],
	[Forwarding Agent Vendor Street],
	[Forwarding Agent Vendor City Name],
	[Forwarding Agent Vendor Zip Code],
	[Forwarding Agent Vendor Country Code],
	[Forwarding Agent Vendor State],
	[Forwarding Agent Vendor Telephone Number 1 Code],
	[Forwarding Agent Vendor Fax Number Code],
	[Forwarding Agent Vendor Tax Number 1 Code],
	[Forwarding Agent Vendor Tax Number 2 Code],
	[Forwarding Agent Vendor VAT Number Code],
	[Forwarding Agent Vendor Express Station],
	[Forwarding Agent Vendor Transportation Zone],
	[Forwarding Agent Vendor Industry],
	[Forwarding Agent Vendor Created Date],
	[ETL_SRC_SYS_CD],
	[ETL_EFFECTV_BEGIN_DATE],
	[ETL_EFFECTV_END_DATE],
	[ETL_CURR_RCD_IND],
	[ETL_CREATED_TS],
	[ETL_UPDTD_TS],
	[Forwarding Agent Vendor Address Number],
	[Forwarding Agent Vendor Account Group Description],
	[Forwarding Agent Vendor Country Description],
	[Forwarding Agent Vendor Region Description],
	[Forwarding Agent Vendor Transportation Zone Description],
	[Forwarding Agent Vendor Industry Description],
	[Forwarding Agent Vendor Created By],
	[Forwarding Agent Vendor Central Deletion Indicator],
	[Forwarding Agent Vendor Central Posting Block],
	[Forwarding Agent Vendor Central Purchasing Block],
	[Forwarding Agent Vendor Language Key],
	[Forwarding Agent Vendor Customer ID],
	[Forwarding Agent Vendor One Time Account Indicator],
	[Forwarding Agent Vendor One Time Account Reference Group],
	[Forwarding Agent Vendor One Time Account Reference Group Desc],
	[Forwarding Agent Vendor Trading Partner],
	[Forwarding Agent Vendor Trading Partner Description],
	[Forwarding Agent Vendor VAT Indicator],
	[Forwarding Agent Vendor Industry Type],
	[Forwarding Agent Vendor Business Type],
	[Forwarding Agent Vendor Payment Block],
	[Forwarding Agent Vendor Tax Jurisdiction],
	[Forwarding Agent Vendor Tax Number 3 Code],
	[Forwarding Agent Vendor Tax Number Type],
	[Forwarding Agent Vendor Tax Type],
	[Forwarding Agent Vendor Level 1],
	[Forwarding Agent Vendor Level 2],
	[Forwarding Agent Vendor Level 3],
	[Forwarding Agent Vendor Level 4],
	[Forwarding Agent Vendor Addressable],
	[Forwarding Agent Tail Vendor],
	[Forwarding Agent Vendor Normalized],
	[Forwarding Agent Vendor Corporate Group],
	[Forwarding Agent Vendor Account No Alternate Payee],
	[Forwarding Agent Vendor Email Address]
)AS
SELECT 
    [VNDR_KEY],
    [Vendor ID],
    [Vendor Name],
    [Vendor Description],
    [Vendor Account Group],
    [Vendor Title],
    [Vendor Search Term],
    [Vendor Street],
    [Vendor City Name],
    [Vendor Zip Code],
    [Vendor Country Code],
    [Vendor State],
    [Vendor Telephone Number 1 Code],
    [Vendor Fax Number Code],
    [Vendor Tax Number 1 Code],
    [Vendor Tax Number 2 Code],
    [Vendor VAT Number Code],
    [Vendor Express Station],
    [Vendor Transportation Zone],
    [Vendor Industry],
    [Vendor Created Date],
    [ETL_SRC_SYS_CD],
    [ETL_EFFECTV_BEGIN_DATE],
    [ETL_EFFECTV_END_DATE],
    [ETL_CURR_RCD_IND],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Vendor Address Number],
    [Vendor Account Group Description],
    [Vendor Country Description],
    [Vendor Region Description],
    [Vendor Transportation Zone Description],
    [Vendor Industry Description],
    [Vendor Created By],
    [Vendor Central Deletion Indicator],
    [Vendor Central Posting Block],
    [Vendor Central Purchasing Block],
    [Vendor Language Key],
    [Vendor Customer ID],
    [Vendor One Time Account Indicator],
    [Vendor One Time Account Reference Group],
    [Vendor One Time Account Reference Group Desc],
    [Vendor Trading Partner],
    [Vendor Trading Partner Description],
    [Vendor VAT Indicator],
    [Vendor Industry Type],
    [Vendor Business Type],
    [Vendor Payment Block],
    [Vendor Tax Jurisdiction],
    [Vendor Tax Number 3 Code],
    [Vendor Tax Number Type],
    [Vendor Tax Type],
    [Vendor Level 1],
    [Vendor Level 2],
    [Vendor Level 3],
    [Vendor Level 4],
    [Vendor Addressable],
    [Tail Vendor],
    [Vendor Normalized],
    [Vendor Corporate Group],
    [Vendor Account No Alternate Payee],
    [Vendor Email Address]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_VENDOR_CUR_D];