-- Auto Generated (Do not modify) 882C179F3F843DCA8589518B5204A6448E8406EA0793BF2A98E6CA52F4150168
CREATE   view [Propelis].[V_INVOICE_CREATION_DATE]
(
    [DATE_KEY],
    [Invoice Creation Date],
    [Invoice Creation Fiscal Year],
    [Invoice Creation Fiscal Period],
    [Invoice Creation Fiscal Period Code],
    [Invoice Creation Fiscal Quarter],
    [Invoice Creation Fiscal Quarter Code],
    [Invoice Creation Calendar Year],
    [Invoice Creation Calendar Month Number],
    [Invoice Creation Calendar Month Code],
    [Invoice Creation Calendar Month Desc],
    [Invoice Creation Calendar Quarter],
    [Invoice Creation Calendar Quarter Code],
    [Invoice Creation Calendar Weekday Number],
    [Invoice Creation Calendar Weekday Name],
    [Invoice Creation Calendar Day in Month],
    [Invoice Creation Calendar Day in Year],
    [Invoice Creation Calendar Week],
    [Invoice Creation Calendar Month in Quarter Number],
    [Invoice Creation Calendar Days in Month],
    [ETL_SRC_SYS_CD],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Invoice Creation Current Day Flag],
    [Invoice Creation Current Day Minus 1 Flag],
    [Invoice Creation Current Calendar Week Flag],
    [Invoice Creation Current Calendar Week Minus 1 Flag],
    [Invoice Creation Current Month Flag],
    [Invoice Creation Current Month Minus 1 Flag],
    [Invoice Creation Current Month Minus 12 Flag],
    [Invoice Creation Current Quarter Flag],
    [Invoice Creation Current Quarter Minus 1 Flag],
    [Invoice Creation Current Quarter Minus 4 Flag],
    [Invoice Creation Current Calendar Year Flag],
    [Invoice Creation Current Calendar Year Minus 1 Flag],
    [Invoice Creation Current Calendar Year Minus 2 Flag],
    [Invoice Creation Current Fiscal Year Flag],
    [Invoice Creation Current Fiscal Year Minus 1 Flag],
    [Invoice Creation Current Fiscal Year Minus 2 Flag],
    [Invoice Creation Current Calendar Year Plus 1 Flag],
    [Invoice Creation Current Fiscal Year Plus 1 Flag],
    [Invoice Creation Day In Fiscal Year],
    [IS_WEEKDAY],
    [Invoice Creation Fiscal Week],
    [Invoice Creation Current Fiscal Week Flag],
    [Invoice Creation Current Fiscal Week Minus 1 Flag],
    [Invoice Creation Fiscal Weekday Number],
    [Invoice Creation Fiscal Weekday Name],
    [CURR_MNTH_MINUS_2_FLG],
    [Invoice Creation Current Fiscal Week Minus 2 Flag],
    [Invoice Creation Current Fiscal Week Minus 6 Flag],
    [Invoice Creation Current Fiscal Week Minus 3 Flag],
    [Invoice Creation Current Fiscal Week Minus 4 Flag],
    [Invoice Creation Current Fiscal Week Minus 5 Flag],
    [Invoice Creation Current Fiscal Week Minus 7 Flag]
)
as select 
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
   from  [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];