-- Auto Generated (Do not modify) 6542229FE662084DC061BAE04A0A7B9295D3378236A210C06739ECF5D07B388A
CREATE     view [Propelis].[V_LOCATION_PLANT](
[PLNT_KEY],
[Location Plant ID],
[Location Legacy Plant ID],
[Location Plant Name],
[Location Plant Company Code],
[Location Plant Sales Organization],
[Location Plant Purchasing Organization],
[Location Plant Valuation Area],
[Location Plant Customer Number],
[Location Plant Vendor Number],
[Location Plant Factory Calendar Key],
[Location Plant Line 1 Description],
[Location Plant Line 2 Description],
[Location Plant City Name],
[Location Plant Zip Code],
[Location Plant Country Code],
[Location Plant Country Name],
[Location Plant Tax Jurisdiction],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Location Plant Is P001],
[Location Plant Is P002],
[Location Plant Company Description],
[Location Plant Sales Organization Description],
[Location Plant Factory Calendar Description],
[Location Plant Purchasing Organization Description],
[Location Plant Tax Indicator],
[Location Plant Tax Indicator Description],
[Location Plant Shipping/Receiving Point],
[Location Plant Shipping/Receiving Point Description]

) AS
SELECT
   [PLNT_KEY],
[Plant ID],
[Legacy Plant ID],
[Plant Name],
[Plant Company Code],
[Plant Sales Organization],
[Plant Purchasing Organization],
[Plant Valuation Area],
[Plant Customer Number],
[Plant Vendor Number],
[Plant Factory Calendar Key],
[Plant Line 1 Description],
[Plant Line 2 Description],
[Plant City Name],
[Plant Zip Code],
[Plant Country Code],
[Plant Country Name],
[Plant Tax Jurisdiction],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Plant IS P001],
[Plant IS P002],
[Plant Company Description],
[Plant Sales Organization Description],
[Plant Factory Calendar Description],
[Plant Purchasing Organization Description],
[Plant Tax Indicator],
[Plant Tax Indicator Description],
[Plant Shipping/Receiving Point],
[Plant Shipping/Receiving Point Description]

FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PLANT_CUR_D];