-- Auto Generated (Do not modify) 6BFA80C3B6735942AE0D42D0CB972AFBE2807B344E6080212B3BDB0B5CA9CE8C
CREATE   view [Propelis].[V_MATRL_ENTERED]
(
    [MATRL_KEY],
    [Material Entered ID],
    [Material Entered Description],
    [Material Entered Legacy Material ID],
    [Material Entered Customer ID],
    [Material Entered Material Category],
    [Material Entered Material Type],
    [Material Entered Group],
    [Material Entered Base Unit Of Measure],
    [Material Entered Industry Sector],
    [Material Entered General Item Category Group],
    [Material Entered Unit],
    [Material Entered Gross Weight],
    [Material Entered Net Weight],
    [Material Entered Product Hierarchy],
    [Category of Material Entered Category],
    [Material Entered Brand],
    [Material Entered Sub Brand],
    [Material Entered Variant Obsolete],
    [Material Entered Variant],
    [Material Entered Name 1],
    [Material Entered Pack Size],
    [Material Entered Pack Type],
    [Material Entered Country Name],
    [Material Entered Print Method],
    [Material Entered Level 4 Product Category Code],
    [Material Entered Level 4 Product Category Description],
    [Material Entered Level 3 Sub Family Code],
    [Material Entered Level 3 Sub Family Description],
    [Material Entered Level 2 Family Code],
    [Material Entered Level 2 Family Description],
    [Material Entered Level 1 Class Code],
    [Material Entered Level 1 Class Description],
    [Material Entered Created Date],
    [Material Entered Created User ID],
    [Material Entered Updated Date],
    [Material Entered Updated User ID],
    [ETL_SRC_SYS_CD],
    [ETL_EFFECTV_BEGIN_DATE],
    [ETL_EFFECTV_END_DATE],
    [ETL_CURR_RCD_IND],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Material Entered Group Description],
    [Material Entered Group Description 2],
    [Category of Material Entered Category Description],
    [Material Entered Brand Description],
    [Material Entered Sub Brand Description],
    [Material Entered Print Method Description],
    [Material Entered Level 5 Product Category Code],
    [Material Entered Level 5 Product Category Code Description],
    [Material Entered Level 6 Product Category Code],
    [Material Entered Level 6 Product Category Code Description],
    [Material Client Level Deletion Indicator],
    [Material Entered PO UoM],
    [Material Entered Basic],
    [Material Entered Industry Standard Description],
    [Material Entered Laboratory/Design Office],
    [Material Entered Laboratory/Design Office Description],
    [Material Entered Purchasing Value Key],
    [Material Entered Storage Condition],
    [Material Entered Storage Condition Description],
    [Material Entered Temperature Conditions Indicator],
    [Material Entered Temperature Conditions Indicator Description],
    [Material Entered Transportation Group],
    [Material Entered Transportation Group Description],
    [Material Entered Hazardous Number],
    [Material Entered Source of Supply],
    [Material Entered Source of Supply Description],
    [Material Entered EAN/UPC Number],
    [Material Entered EAN Category],
    [Material Entered EAN Category Description],
    [Material Entered Length],
    [Material Entered Width],
    [Material Entered Height],
    [Material Entered UoD],
    [Material Entered External Group],
    [Material Entered External Group Description],
    [Material Entered Manufacturer Part Number],
    [Material Entered Dangerous Goods Indicator Profile],
    [Material Entered Dangerous Goods Ind Profile Desription],
    [Material Entered Country of Origin],
    [Material Entered Country of Origin Description],
    [Material Entered Quality Inspection Group],
    [Material Entered Quality Inspection Group Description],
    [Material Entered Material Category Description],
    [Material Entered Material Type Description],
    [Material Entered Product Hierarchy Description],
    [Material Entered Industry Sector Description],
    [Material Entered General Item Category Group Description],
    [MATRL_SALES_TEXT],
    [CHARACTERISTIC_22_VAL],
    [CLASS_INTERNL_NUM],
    [CLASS_NAME],
    [CLASS_TYP],
    [CLASS_TYP_DESC],
    [CLASS_STATUS],
    [CLASS_STATUS_DESC],
    [CHARACTERISTIC_1_INTERNL_NUM],
    [CHARACTERISTIC_1_NAME],
    [CHARACTERISTIC_1_DESC],
    [CHARACTERISTIC_1_VAL],
    [CHARACTERISTIC_1_VAL_DESC],
    [CHARACTERISTIC_2_INTERNL_NUM],
    [CHARACTERISTIC_2_NAME],
    [CHARACTERISTIC_2_DESC],
    [CHARACTERISTIC_2_VAL],
    [CHARACTERISTIC_2_VAL_DESC],
    [CHARACTERISTIC_3_INTERNL_NUM],
    [CHARACTERISTIC_3_NAME],
    [CHARACTERISTIC_3_DESC],
    [CHARACTERISTIC_3_VAL],
    [CHARACTERISTIC_3_VAL_DESC],
    [CHARACTERISTIC_4_INTERNL_NUM],
    [CHARACTERISTIC_4_NAME],
    [CHARACTERISTIC_4_DESC],
    [CHARACTERISTIC_4_VAL],
    [CHARACTERISTIC_4_VAL_DESC],
    [CHARACTERISTIC_5_INTERNL_NUM],
    [CHARACTERISTIC_5_NAME],
    [CHARACTERISTIC_5_DESC],
    [CHARACTERISTIC_5_VAL],
    [CHARACTERISTIC_5_VAL_DESC],
    [CHARACTERISTIC_6_INTERNL_NUM],
    [CHARACTERISTIC_6_NAME],
    [CHARACTERISTIC_6_DESC],
    [CHARACTERISTIC_6_VAL],
    [CHARACTERISTIC_6_VAL_DESC],
    [CHARACTERISTIC_7_INTERNL_NUM],
    [CHARACTERISTIC_7_NAME],
    [CHARACTERISTIC_7_DESC],
    [CHARACTERISTIC_7_VAL],
    [CHARACTERISTIC_7_VAL_DESC],
    [CHARACTERISTIC_8_INTERNL_NUM],
    [CHARACTERISTIC_8_NAME],
    [CHARACTERISTIC_8_DESC],
    [CHARACTERISTIC_8_VAL],
    [CHARACTERISTIC_8_VAL_DESC],
    [CHARACTERISTIC_9_INTERNL_NUM],
    [CHARACTERISTIC_9_NAME],
    [CHARACTERISTIC_9_DESC],
    [CHARACTERISTIC_9_VAL],
    [CHARACTERISTIC_9_VAL_DESC],
    [CHARACTERISTIC_10_INTERNL_NUM],
    [CHARACTERISTIC_10_NAME],
    [CHARACTERISTIC_10_DESC],
    [CHARACTERISTIC_10_VAL],
    [CHARACTERISTIC_10_VAL_DESC],
    [CHARACTERISTIC_11_INTERNL_NUM],
    [CHARACTERISTIC_11_NAME],
    [CHARACTERISTIC_11_DESC],
    [CHARACTERISTIC_11_VAL],
    [CHARACTERISTIC_11_VAL_DESC],
    [CHARACTERISTIC_12_INTERNL_NUM],
    [CHARACTERISTIC_12_NAME],
    [CHARACTERISTIC_12_DESC],
    [CHARACTERISTIC_12_VAL],
    [CHARACTERISTIC_12_VAL_DESC],
    [CHARACTERISTIC_13_INTERNL_NUM],
    [CHARACTERISTIC_13_NAME],
    [CHARACTERISTIC_13_DESC],
    [CHARACTERISTIC_13_VAL],
    [CHARACTERISTIC_13_VAL_DESC],
    [CHARACTERISTIC_14_INTERNL_NUM],
    [CHARACTERISTIC_14_NAME],
    [CHARACTERISTIC_14_DESC],
    [CHARACTERISTIC_14_VAL],
    [CHARACTERISTIC_14_VAL_DESC],
    [CHARACTERISTIC_15_INTERNL_NUM],
    [CHARACTERISTIC_15_NAME],
    [CHARACTERISTIC_15_DESC],
    [CHARACTERISTIC_15_VAL],
    [CHARACTERISTIC_15_VAL_DESC],
    [CHARACTERISTIC_16_INTERNL_NUM],
    [CHARACTERISTIC_16_NAME],
    [CHARACTERISTIC_16_DESC],
    [CHARACTERISTIC_16_VAL],
    [CHARACTERISTIC_16_VAL_DESC],
    [CHARACTERISTIC_17_INTERNL_NUM],
    [CHARACTERISTIC_17_NAME],
    [CHARACTERISTIC_17_DESC],
    [CHARACTERISTIC_17_VAL],
    [CHARACTERISTIC_17_VAL_DESC],
    [CHARACTERISTIC_18_INTERNL_NUM],
    [CHARACTERISTIC_18_NAME],
    [CHARACTERISTIC_18_DESC],
    [CHARACTERISTIC_18_VAL],
    [CHARACTERISTIC_18_VAL_DESC],
    [CHARACTERISTIC_19_INTERNL_NUM],
    [CHARACTERISTIC_19_NAME],
    [CHARACTERISTIC_19_DESC],
    [CHARACTERISTIC_19_VAL],
    [CHARACTERISTIC_19_VAL_DESC],
    [CHARACTERISTIC_20_INTERNL_NUM],
    [CHARACTERISTIC_20_NAME],
    [CHARACTERISTIC_20_DESC],
    [CHARACTERISTIC_20_VAL],
    [CHARACTERISTIC_20_VAL_DESC],
    [CHARACTERISTIC_21_INTERNL_NUM],
    [CHARACTERISTIC_21_NAME],
    [CHARACTERISTIC_21_DESC],
    [CHARACTERISTIC_21_VAL],
    [CHARACTERISTIC_21_VAL_DESC],
    [CHARACTERISTIC_22_INTERNL_NUM],
    [CHARACTERISTIC_22_NAME],
    [CHARACTERISTIC_22_DESC],
    [CHARACTERISTIC_22_VAL_DESC],
    [CHARACTERISTIC_23_INTERNL_NUM],
    [CHARACTERISTIC_23_NAME],
    [CHARACTERISTIC_23_DESC],
    [CHARACTERISTIC_23_VAL],
    [CHARACTERISTIC_23_VAL_DESC],
    [MATRL_DESC_ITALIAN],
    [MATRL_X_PLNT_STATUS],
    [MATRL_X_PLNT_DESC],
    [DIVISION],
        [DIVISION_DESC]
)
as select 
        [MATRL_KEY],
        [Material ID],
        [Material Description],
        [Legacy Material ID],
        [Material Customer ID],
        [Material Category],
        [Material Type],
        [Material Group],
        [Material Base Unit Of Measure],
        [Material Industry Sector],
        [Material General Item Category Group],
        [Material Unit],
        [Material Gross Weight],
        [Material Net Weight],
        [Material Product Hierarchy],
        [Category of Material],
        [Material Brand],
        [Material Sub Brand],
        [Material Variant Obsolete],
        [Material Variant],
        [Material Name 1],
        [Material Pack Size],
        [Material Pack Type],
        [Material Country Name],
        [Material Print Method],
        [Material Level 4 Product Category Code],
        [Material Level 4 Product Category Description],
        [Material Level 3 Sub Family Code],
        [Material Level 3 Sub Family Description],
        [Material Level 2 Family Code],
        [Material Level 2 Family Description],
        [Material Level 1 Class Code],
        [Material Level 1 Class Description],
        [Material Created Date],
        [Material Created User ID],
        [Material Updated Date],
        [Material Updated User ID],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Material Group Description],
        [Material Group Description 2],
        [Category of Material Description],
        [Material Brand Description],
        [Material Sub Brand Description],
        [Material Print Method Description],
        [Material Level 5 Product Category Code],
        [Material Level 5 Product Category Description],
        [Material Level 6 Product Category Code],
        [Material Level 6 Product Category Description],
        [Material Category Description],
        [Material Type Description],
        [Material Product Hierarchy Description],
        [Material Industry Sector Description],
        [Material General Item Category Group Description],
        [Material Client Level Deletion Indicator],
        [Material PO UoM],
        [Material Basic],
        [Material Industry Standard Description],
        [Material Laboratory/Design Office],
        [Material Laboratory/Design Office Description],
        [Material Purchasing Value Key],
        [Material Storage Condition],
        [Material Storage Condition Description],
        [Material Temperature Conditions Indicator],
        [Material Temperature Conditions Indicator Description],
        [Material Transportation Group],
        [Material Transportation Group Description],
        [Material Hazardous Number],
        [Material Source of Supply],
        [Material Source of Supply Description],
        [Material EAN/UPC Number],
        [Material EAN Category],
        [Material EAN Category Description],
        [Material Length],
        [Material Width],
        [Material Height],
        [Material UoD],
        [Material External Group],
        [Material External Group Description],
        [Material Manufacturer Part Number],
        [Material Dangerous Goods Indicator Profile],
        [Material Dangerous Goods Indicator Profile Desription],
        [Material Country of Origin],
        [Material Country of Origin Description],
        [Material Quality Inspection Group],
        [Material Quality Inspection Group Description],
        [MATRL_SALES_TEXT],
        [Class Internl Num],
        [Class Name],
        [Class Typ],
        [Class Typ Desc],
        [Class Status],
        [Class Status Desc],
        [Characteristic 1 Internl Num],    
        [Characteristic 1 Name],     
        [Characteristic 1 Desc],            
        [Characteristic 1 Val],           
        [Characteristic 1 Val Desc],         
        [Characteristic 2 Internl Num],      
        [Characteristic 2 Name],     
        [Characteristic 2 Desc],             
        [Characteristic 2 Val],              
        [Characteristic 2 Val Desc],         
        [Characteristic 3 Internl Num],      
        [Characteristic 3 Name],             
        [Characteristic 3 Desc],             
        [Characteristic 3 Val],              
        [Characteristic 3 Val Desc],         
        [Characteristic 4 Internl Num],      
        [Characteristic 4 Name],             
        [Characteristic 4 Desc],             
        [Characteristic 4 Val],              
        [Characteristic 4 Val Desc],         
        [Characteristic 5 Internl Num],      
        [Characteristic 5 Name],             
        [Characteristic 5 Desc],             
        [Characteristic 5 Val],              
        [Characteristic 5 Val Desc],         
        [Characteristic 6 Internl Num],      
        [Characteristic 6 Name],             
        [Characteristic 6 Desc],             
        [Characteristic 6 Val],              
        [Characteristic 6 Val Desc],         
        [Characteristic 7 Internl Num],      
        [Characteristic 7 Name],             
        [Characteristic 7 Desc],             
        [Characteristic 7 Val],              
        [Characteristic 7 Val Desc],         
        [Characteristic 8 Internl Num],      
        [Characteristic 8 Name],             
        [Characteristic 8 Desc],             
        [Characteristic 8 Val],              
        [Characteristic 8 Val Desc],         
        [Characteristic 9 Internl Num],      
        [Characteristic 9 Name],             
        [Characteristic 9 Desc],             
        [Characteristic 9 Val],              
        [Characteristic 9 Val Desc],         
        [Characteristic 10 Internl Num],     
        [Characteristic 10 Name],            
        [Characteristic 10 Desc],            
        [Characteristic 10 Val],             
        [Characteristic 10 Val Desc],        
        [Characteristic 11 Internl Num],     
        [Characteristic 11 Name],            
        [Characteristic 11 Desc],            
        [Characteristic 11 Val],             
        [Characteristic 11 Val Desc],        
        [Characteristic 12 Internl Num],     
        [Characteristic 12 Name],            
        [Characteristic 12 Desc],            
        [Characteristic 12 Val],             
        [Characteristic 12 Val Desc],        
        [Characteristic 13 Internl Num],     
        [Characteristic 13 Name],            
        [Characteristic 13 Desc],            
        [Characteristic 13 Val],             
        [Characteristic 13 Val Desc],        
        [Characteristic 14 Internl Num],     
        [Characteristic 14 Name],            
        [Characteristic 14 Desc],            
        [Characteristic 14 Val],             
        [Characteristic 14 Val Desc],        
        [Characteristic 15 Internl Num],     
        [Characteristic 15 Name],            
        [Characteristic 15 Desc],            
        [Characteristic 15 Val],             
        [Characteristic 15 Val Desc],        
        [Characteristic 16 Internl Num],     
        [Characteristic 16 Name],            
        [Characteristic 16 Desc],            
        [Characteristic 16 Val],             
        [Characteristic 16 Val Desc],        
        [Characteristic 17 Internl Num],     
        [Characteristic 17 Name],            
        [Characteristic 17 Desc],            
        [Characteristic 17 Val],             
        [Characteristic 17 Val Desc],        
        [Characteristic 18 Internl Num],     
        [Characteristic 18 Name],            
        [Characteristic 18 Desc],            
        [Characteristic 18 Val],             
        [Characteristic 18 Val Desc],        
        [Characteristic 19 Internl Num],     
        [Characteristic 19 Name],            
        [Characteristic 19 Desc],            
        [Characteristic 19 Val],             
        [Characteristic 19 Val Desc],        
        [Characteristic 20 Internl Num],     
        [Characteristic 20 Name],            
        [Characteristic 20 Desc],            
        [Characteristic 20 Val],             
        [Characteristic 20 Val Desc],        
        [Characteristic 21 Internl Num],     
        [Characteristic 21 Name],            
        [Characteristic 21 Desc],            
        [Characteristic 21 Val],             
        [Characteristic 21 Val Desc],        
        [Characteristic 22 Internl Num],     
        [Characteristic 22 Name],            
        [Characteristic 22 Desc],            
        [Characteristic 22 Val],             
        [Characteristic 22 Val Desc],        
        [Characteristic 23 Internl Num],     
        [Characteristic 23 Name],            
        [Characteristic 23 Desc], 
		[Characteristic 23 Val],             
        [Characteristic 23 Val Desc],
        [Material Description Italian],
        [Material Cross Plant Status],
        [Material Cross Plant Description],
        [DIVISION],
        [DIVISION_DESC]
   from  [GLOBAL_EDW].[dbo].[EDW_T_D_MST_MATERIAL_CUR_D];