-- Auto Generated (Do not modify) 3836CCCDCC360E1092E2D07A29AA493D31ABBC61C7E342441086DA1429DCB1C6

create view [Propelis].[V_OPERATION_LEVEL_WORK_CENTER](
	[WRK_CNTR_KEY],
[Operation Work Center ID],
[Operation Work Center Plant ID],
[Operation Work Center Object ID],
[Operation Work Center Object Type],
[Operation Work Center Category],
[Operation Work Center Location],
[Operation Work Center Person Responsible],
[Operation Work Center Standard Value Key],
[Operation Work Center Usage Code],
[Operation Work Center Capacity ID],
[Operation Work Center Supply Area],
[Operation Work Center Deletion Flag],
[Operation Work Center Locked Status],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Operation Work Center Description],
[Operation Work Center Category Description],
[Operation Work Center Person Responsible Name],
[Operation Work Center Control Key],
[Operation Work Center Storage Location Storage Resource],
[Operation Work Center User Name Term],
[Operation Work Center User Name GRND],
[Operation Work Center Changed On Date Term],
[Operation Work Center Changed On Date GRND],
[Operation Work Center Plant Description],
[Operation Work Center Object Type Description],
[Operation Work Center Location Description],
[Operation Work Center Standard Value Description],
[Operation Work Center Usage Description],
[Operation Work Center Supply Area Description],
[Operation Work Center Control Description],
[Operation Work Center Storage Location Description],
[Operation Work Center Changed On Date]
) as
SELECT 
    [WRK_CNTR_KEY],
[Work Center ID],
[Work Center Plant ID],
[Work Center Object ID],
[Work Center Object Type],
[Work Center Category],
[Work Center Location],
[Work Center Person Responsible],
[STD_VAL_KEY],
[Work Center Usage Code],
[Work Center Capacity ID],
[Work Center Supply Area],
[Work Center Deletion Flag],
[Work Center Locked Status],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Work Center Description],
[Work Center Category Description],
[Work Center Person Responsible Name],
[Work Center Control Key],
[Work Center Storage Location Storage Resource],
[Work Center User Name Term],
[Work Center User Name GRND],
[Work Center Changed On Date Term],
[Work Center Changed On Date GRND],
[Work Center Changed On Date],
[Work Center Plant Description],
[Work Center Object Type Description],
[Work Center Location Description],
[Work Center Standard Value Description],
[Work Center Usage Description],
[Work Center Supply Area Description],
[Work Center Control Description],
[Work Center Storage Location Description]
  FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_WORKCTR_CUR_D];