-- Auto Generated (Do not modify) B0AA4F9B1BEF29627E3D98F377FFDDDC8456257B9151B3F28C535BE19A241B5D
CREATE VIEW [Propelis].[V_OPERATING_PLANT] 
    (
        [PLNT_KEY],
        [Operating Plant ID],
        [Legacy Operating Plant ID],
        [Operating Plant Name],
        [Operating Plant Company Code],
        [Operating Plant Sales Organization],
        [Operating Plant Purchasing Organization],
        [Operating Plant Valuation Area],
        [Operating Plant Customer Number],
        [Operating Plant Vendor Number],
        [Operating Plant Factory Calendar Key],
        [Operating Plant Line 1 Description],
        [Operating Plant Line 2 Description],
        [Operating Plant City Name],
        [Operating Plant Zip Code],
        [Operating Plant Country Code],
        [Operating Plant Country Name],
        [Operating Plant Tax Jurisdiction],
        [ETL SRC SYS CD],
        [ETL EFFECTV BEGIN DATE],
        [ETL EFFECTV END DATE],
        [ETL CURR RCD IND],
        [ETL CREATED TS],
        [ETL UPDTD TS],
        [Operating Plant IS P001],
        [Operating Plant IS P002],
        [Operating Plant Company Description],
        [Operating Plant Sales Organization Description],
        [Operating Plant Factory Calendar Description],
        [Operating Plant Purchasing Organization Description],
        [Operating Plant Tax Indicator],
        [Operating Plant Tax Indicator Description],
        [Operating Plant Shipping Receiving Point],
        [Operating Plant Shipping Receiving Point Description]
    ) AS
    SELECT 
        [PLNT_KEY],
        [Plant ID],
        [Legacy Plant ID],
        [Plant Name],
        [Plant Company Code],
        [Plant Sales Organization],
        [Plant Purchasing Organization],
        [Plant Valuation Area],
        [Plant Customer Number],
        [Plant Vendor Number],
        [Plant Factory Calendar Key],
        [Plant Line 1 Description],
        [Plant Line 2 Description],
        [Plant City Name],
        [Plant Zip Code],
        [Plant Country Code],
        [Plant Country Name],
        [Plant Tax Jurisdiction],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Plant IS P001],
        [Plant IS P002],
        [Plant Company Description],
        [Plant Sales Organization Description],
        [Plant Factory Calendar Description],
        [Plant Purchasing Organization Description],
        [Plant Tax Indicator],
        [Plant Tax Indicator Description],
        [Plant Shipping/Receiving Point],
        [Plant Shipping/Receiving Point Description]
		
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PLANT_CUR_D]