-- Auto Generated (Do not modify) 0FA11A56CA2D4BF8F66109BF5DA1A91CB7FDBC6B8B62FD3084D8F91E6AC253CD
CREATE  view [Propelis].[V_PARTNER_COST_CENTER](
    [COST_CNTR_KEY],
[Partner Cost Center ID],
[Partner Cost Center Long Description],
[Partner Cost Center Controlling Area ID],
[Partner Cost Center Language Type Code],
[Partner Cost Center Category],
[Partner Cost Center Hierarchy Area],
[Partner Cost Center Company Code],
[Partner Cost Center Plant],
[Partner Cost Center Proft Center ID],
[Partner Cost Center Currency Code],
[Partner Cost Center Address Line 1],
[Partner Cost Center Address Line 2],
[Partner Cost Center Address Line 3],
[Partner Cost Center City Name],
[Partner Cost Center District Name],
[Partner Cost Center Postal Code],
[Partner Cost Center Country Code],
[Partner Cost Center Region Code],
[Partner Cost Center Person Responsible],
[Partner Cost Center Flag Actual Revenues],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Partner CC Actual Primary Postings Lock Indicator],
[Partner CC Plan Primary Costs Lock Indicator],
[Partner Cost Center Business Area],
[Partner CC Planning Revenues Lock Indicator],
[Partner Cost Center PO Box],
[Partner Cost Center Street],
[Partner Cost Center User Responsible],
[Partner Cost Center Description],
[Partner Cost Center Short Description],
[Partner Cost Center Controlling Area Description],
[Partner Cost Center Category Description],
[Partner Cost Center Company Description],
[Partner Cost Center Currency Description],
[Partner Cost Center Country Description],
[Partner Cost Center Business Area Description],
[Partner CC Actual Secondary Cost Lock Indicator],
[Partner CC Plan Secondary Cost Lock Indicator],
[Partner Cost Center Functional Area],
[Partner Cost Center Functional Area Description],
[Partner Cost Center Tax Jurisdiction],
[Partner Cost Center Function],
[Partner Cost Center Plant Description],
[Partner Cost Center Created On],
[Partner Cost Center Valid To Date],
[Partner Cost Center Valid From Date]

) AS
SELECT 
   [COST_CNTR_KEY],
[Cost Center ID],
[Cost Center Long Description],
[Cost Center Controlling Area ID],
[Cost Center Language Type Code],
[Cost Center Category],
[Cost Center Hierarchy Area],
[Cost Center Company Code],
[Cost Center Plant ID],
[Cost Center Profit Center ID],
[Cost Center Currency Code],
[Cost Center Address Line 1],
[Cost Center Address Line 2],
[Cost Center Address Line 3],
[Cost Center City Name],
[Cost Center District Name],
[Cost Center Postal Code],
[Cost Center Country Code],
[Cost Center Region Code],
[Cost Center Person Responsible],
[Cost Center Flag Actual Revenues],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Cost Center Actual Primary Postings Lock Indicator],
[Cost Center Plan Primary Costs Lock Indicator],
[Cost Center Business Area],
[Cost Center Planning Revenues Lock Indicator],
[Cost Center PO Box],
[Cost Center Street],
[Cost Center User Responsible],
[COST_CNTR_NAME],
[Cost Center Short Description],
[Cost Center Controlling Area Description],
[Cost Center Category Description],
[Cost Center Company Description],
[Cost Center Currency Description],
[Cost Center Country Description],
[Cost Center Business Area Description],
[Cost Center Actual Secondary Cost Lock Indicator],
[Cost Center Plan Secondary Cost Lock Indicator],
[Cost Center Functional Area],
[Cost Center Functional Area Description],
[Cost Center Tax Jurisdiction],
[FUNCTION_OF_COST_CNTR],
[Cost Center Plant Description],
[Cost Center Created On],
[Cost Center Valid To Date],
[Cost Center Valid From Date]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_COSCNTR_CUR_D];