-- Auto Generated (Do not modify) 51A8842E65C51AD71173A8B17537B9EE4FA6D2376EF4355D5B7BB87D1E154D1D
CREATE   view [Propelis].[V_PARENT_CUST]
(
    [CUST_KEY],
    [Parent Customer ID],
    [Parent Customer Legacy ID],
    [Parent Customer Name],
    [Parent Cust Line 2 Description],
    [Parent Cust Country Code],
    [Parent Cust Plant ID],
    [Parent Cust Segment ID],
    [Parent Cust Industry],
    [Parent Cust Vendor ID],
    [Parent Cust Group Code],
    [Parent Cust Account Group Code],
    [Parent Cust Title],
    [Parent Cust Search Term],
    [Parent Cust Street],
    [Parent Cust City],
    [Parent Cust Zip Code],
    [Parent Cust State Code],
    [Parent Cust Region Code],
    [Parent Cust Telephone Number 1],
    [Parent Cust Telephone Number 2],
    [Parent Cust Fax Number Code],
    [Parent Cust Tax Number 1 Code],
    [Parent Cust Tax Number 2 Code],
    [Parent Cust VAT Number Code],
    [Parent Cust Credit Limit],
    [Parent Cust Bonus Rate],
    [Parent Cust Express Station],
    [Parent Cust Transportation Zone],
    [Parent Cust Printer Location Characteristics],
    [Parent Cust Printer Region Characteristics],
    [Parent Cust Printer Site Characteristics],
    [Parent Cust Created Date],
    [Parent Cust Created User ID],
    [Parent Cust Updated Date],
    [Parent Cust Updated User ID],
    [Parent Cust Payment Terms Code],
    [Parent Cust Sales Distribution],
    [Parent Cust Order Block For Sales Area],
    [Parent Cust Delivery Block For Sales Area],
    [ETL_SRC_SYS_CD],
    [ETL_EFFECTV_BEGIN_DATE],
    [ETL_EFFECTV_END_DATE],
    [ETL_CURR_RCD_IND],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Parent Cust Corporate Group],
    [Parent Cust Customer Classification],
    [Parent Cust Classification Description],
    [Parent Cust Printer Location],
    [Parent Cust Printer Site],
    [Parent Cust Printer Region],
    [Parent Cust Specific Field Label 01],
    [Parent Cust Specific Field Label 02],
    [Parent Cust Specific Field Label 03],
    [Parent Cust Specific Field Label 04],
    [Parent Cust Specific Field Label 05],
    [Parent Cust Specific Field Label 06],
    [Parent Cust Specific Field Label 07],
    [Parent Cust Specific Field Label 08],
    [Parent Cust Specific Field Label 09],
    [Parent Cust Specific Field Label 10],
    [Parent Cust Specific Field Label 11],
    [Parent Cust Specific Field Label 12],
    [Parent Cust Specific Field Label 13],
    [Parent Cust Specific Field Label 14],
    [Parent Cust Specific Field Label 15],
    [Parent Cust Specific Field Label 16],
    [Parent Cust Specific Field Label 17],
    [Parent Cust Specific Field Label 18],
    [Parent Cust Specific Field Label 19],
    [Parent Cust Specific Field Label 20],
    [Parent Cust Condition Group 1],
    [Parent Cust Industry Code 1],
    [Parent Cust Industry Code 2],
    [Parent Cust Industry Description],
    [Parent Cust Industry Code 1 Description],
    [Parent Cust Industry Code 2 Description],
    [Parent Cust Assignment to Hierarchy],
    [Parent Cust Account Group Description],
    [Parent Cust Region Description],
    [Parent Cust Country Description],
    [Parent Cust Transportation Zone Description],
    [Parent Cust Plant Description],
    [Parent Cust Condition Group Description],
    [Parent Cust Cental Billing Block],
    [Parent Cust Cental Billing Block Description],
    [Parent Cust Central Delivery Block],
    [Parent Cust Central Delivery Block Description],
    [Parent Cust Deletion Indicator],
    [CENTRAL_PSTNG_BLK],
    [Parent Cust Tax Jurisdiction],
    [Parent Cust Central Sales Block],
    [Parent Cust Central Deletion Indicator],
    [Parent Cust Language Key],
    [Parent Cust Trading Partner],
    [Parent Cust Trading Partner Description],
    [Parent Cust Annual Sales],
    [Parent Cust Annual Sales Year],
    [Parent Cust Sales Currency],
    [Parent Cust Sales Currency Description],
    [Parent Cust One Time Account Group],
    [Parent Cust One Time Account Group Description],
    [Parent Cust One Time Customer Indicator],
    [Parent Cust Industry Type],
    [Parent Cust Business Type],
    [Parent Cust DUNS Number],
    [Parent Cust DUNS Plus 4],
    [Parent Cust City Coordinates],
    [Parent Cust Tax Number 4 Code],
    [Parent Cust Attribute 3],
    [Parent Cust Attribute 3 Description],
    [Parent Cust E Mail Address],
    [Parent Cust Mobile Number],
    [Parent Cust Search Term 2],
    [Parent Cust Street 2],
    [Parent Cust Street 3],
    [Parent Cust Street 4],
    [Parent Cust Street 5],
    [Parent Cust PO Box],
    [Parent Cust PO Box Postal Code],
    [Parent Cust PO Box City],
    [Parent Cust Region For PO Box],
    [Parent Cust PO Box Country],
    [Parent Cust Transport Zone],
               [ Parent  Cust  Address  Notes],
    [Parent Cust Tax Number 3 Code],
    [Parent Cust Tax Number 5 Code],
    [Parent Cust Industry Code 3],
    [Parent Cust Industry Code 3 Description],
    [Parent Cust Industry Code 4],
    [Parent Cust Industry Code 4 Description],
    [Parent Cust Industry Code 5],
    [Parent Cust Industry Code 5 Description],
    [Parent Cust Central Order Block For Customer],
    [Parent Cust Payment Block]
    ) AS 
    SELECT 
    [CUST_KEY],
        [Customer ID],
        [Legacy Customer ID],
        [Customer Name],
        [Customer Line 2 Description],
        [Customer Country Code],
        [Customer Plant ID],
        [Customer Segment ID],
        [Customer Industry],
        [Customer Vendor ID],
        [Customer Group Code],
        [Customer Account Group Code],
        [Customer Title],
        [Customer Search Term],
        [Customer Street],
        [Customer City],
        [Customer Zip Code],
        [Customer State Code],
        [Customer Region Code],
        [Customer Telephone Number 1],
        [Customer Telephone Number 2],
        [Customer Fax Number Code],
        [Customer Tax Number 1 Code],
        [Customer Tax Number 2 Code],
        [Customer VAT Number Code],
        [Customer Credit Limit],
        [Customer Bonus Rate],
        [Customer Express Station],
        [Customer Transportation Zone],
        [Customer Printer Location Characteristics],
        [Customer Printer Region Characteristics],
        [Customer Printer Site Characteristics],
        [Customer Created Date],
        [Customer Created User ID],
        [Customer Updated Date],
        [Customer Updated User ID],
        [Customer Payment Terms Code],
        [Customer Sales Distribution],
        [Customer Order Block For Sales Area],
        [Customer Delivery Block For Sales Area],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Customer Corporate Group],
        [Customer Classification],
        [Customer Classification Description],
        [Customer Printer Location],
        [Customer Printer Site],
        [Customer Printer Region],
        [Customer Specific Field Label 01],
        [Customer Specific Field Label 02],
        [Customer Specific Field Label 03],
        [Customer Specific Field Label 04],
        [Customer Specific Field Label 05],
        [Customer Specific Field Label 06],
        [Customer Specific Field Label 07],
        [Customer Specific Field Label 08],
        [Customer Specific Field Label 09],
        [Customer Specific Field Label 10],
        [Customer Specific Field Label 11],
        [Customer Specific Field Label 12],
        [Customer Specific Field Label 13],
        [Customer Specific Field Label 14],
        [Customer Specific Field Label 15],
        [Customer Specific Field Label 16],
        [Customer Specific Field Label 17],
        [Customer Specific Field Label 18],
        [Customer Specific Field Label 19],
        [Customer Specific Field Label 20],
        [Customer Condition Group 1],
        [Customer Industry Code 1],
        [Customer Industry Code 2],
        [Customer Industry Description],
        [Customer Industry Code 1 Description],
        [Customer Industry Code 2 Description],
        [Customer Assignment to Hierarchy],
        [Customer Account Group Description],
        [Customer Region Description],
        [Customer Country Description],
        [Customer Transportation Zone Description],
        [Customer Plant Description],
        [Customer Condition Group Description],
        [Customer Cental Billing Block],
        [Customer Cental Billing Block Description],
        [Customer Central Delivery Block],
        [Customer Central Delivery Block Description],
        [Customer Deletion Indicator],
        [Customer Central Posting Block],
        [Customer Tax Jurisdiction],
        [Customer Central Sales Block],
        [Customer Central Deletion Indicator],
        [Customer Language Key],
        [Customer Trading Partner],
        [Customer Trading Partner Description],
        [Customer Annual Sales],
        [Customer Annual Sales Year],
        [Customer Sales Currency],
        [Customer Sales Currency Description],
        [Customer One Time Account Group],
        [Customer One Time Account Group Description],
        [Customer One Time Indicator],
        [Customer Industry Type],
        [Customer Business Type],
        [Customer DUNS Number],
        [Customer DUNS Plus 4],
        [Customer City Coordinates],
        [Customer Tax Number 4 Code],
        [Customer Attribute 3],
        [Customer Attribute 3 Description],
        [Customer E-Mail Address],
        [Customer Mobile Number],
        [Customer Search Term 2],
        [Customer Street 2],
        [Customer Street 3],
        [Customer Street 4],
        [Customer Street 5],
        [Customer PO Box],
        [Customer PO Box Postal Code],
        [Customer PO Box City],
        [Customer Region For PO Box],
        [Customer PO Box Country],
        [Customer Transport Zone],
        [Customer Address Notes],
        [Customer Tax Number 3 Code],
        [Customer Tax Number 5 Code],
        [Customer Industry Code 3],
        [Customer Industry Code 3 Description],
        [Customer Industry Code 4],
        [Customer Industry Code 4 Description],
        [Customer Industry Code 5],
        [Customer Industry Code 5 Description],
        [Customer Central Order Block For Customer],
        [Customer Payment Block]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D];