-- Auto Generated (Do not modify) 797986A521508EF53BDFCE427459E6F7B989F31F624ACBAB8ED0C47E68877DE3
CREATE   view [Propelis].[V_PAYER_CUST] 
                ( [CUST_KEY],
                  [Payer Customer ID],
                  [Payer Legacy Customer ID],
                  [Payer Customer Name],
                  [Payer Cust Line 2 Description],
                  [Payer Cust Country Code],
                  [Payer Cust Plant ID],
                  [Payer Cust Segment ID],
                  [Payer Cust Industry],
                  [Payer Cust Vendor ID],
                  [Payer Cust Customer Group Code],
                  [Payer Cust Account Group Code],
                  [Payer Cust Title],
                  [Payer Cust Search Term],
                  [Payer Cust Street],
                  [Payer Cust City],
                  [Payer Cust Zip Code],
                  [Payer Cust State Code],
                  [Payer Cust Region Code],
                  [Payer Cust Telephone Number 1],
                  [Payer Cust Telephone Number 2],
                  [Payer Cust Fax Number Code],
                  [Payer Cust Tax Number 1 Code],
                  [Payer Cust Tax Number 2 Code],
                  [Payer Cust VAT Number Code],
                  [Payer Cust Credit Limit],
                  [Payer Cust Bonus Rate],
                  [Payer Cust Express Station],
                  [Payer Cust Transportation Zone],
                  [Payer Cust Printer Location Characteristics],
                  [Payer Cust Printer Region Characteristics],
                  [Payer Cust Printer Site Characteristics],
                  [Payer Cust Customer Created Date],
                  [Payer Cust Created User ID],
                  [Payer Cust Customer Updated Date],
                  [Payer Cust Updated User ID],
                  [Payer Cust Payment Terms Code],
                  [Payer Cust Sales Distribution],
                  [Payer Cust Order Block For Sales Area],
                  [Payer Cust Delivery Block For Sales Area],
                  [ETL_SRC_SYS_CD],
                  [ETL_EFFECTV_BEGIN_DATE],
                  [ETL_EFFECTV_END_DATE],
                  [ETL_CURR_RCD_IND],
                  [ETL_CREATED_TS],
                  [ETL_UPDTD_TS],
                  [Payer Cust Corporate Group],
                  [Payer Cust Classification],
                  [Payer Cust Classification Description],
                  [Payer Cust Printer Location],
                  [Payer Cust Printer Site],
                  [Payer Cust Printer Region],
                  [Payer Cust Specific Field Label 01],
                  [Payer Cust Specific Field Label 02],
                  [Payer Cust Specific Field Label 03],
                  [Payer Cust Specific Field Label 04],
                  [Payer Cust Specific Field Label 05],
                  [Payer Cust Specific Field Label 06],
                  [Payer Cust Specific Field Label 07],
                  [Payer Cust Specific Field Label 08],
                  [Payer Cust Specific Field Label 09],
                  [Payer Cust Specific Field Label 10],
                  [Payer Cust Specific Field Label 11],
                  [Payer Cust Specific Field Label 12],
                  [Payer Cust Specific Field Label 13],
                  [Payer Cust Specific Field Label 14],
                  [Payer Cust Specific Field Label 15],
                  [Payer Cust Specific Field Label 16],
                  [Payer Cust Specific Field Label 17],
                  [Payer Cust Specific Field Label 18],
                  [Payer Cust Specific Field Label 19],
                  [Payer Cust Specific Field Label 20],
                  [Payer Cust Condition Group 1],
                  [Payer Cust Industry Code 1],
                  [Payer Cust Industry Code 2],
                  [Payer Cust Industry Description],
                  [Payer Cust Industry Code 1 Description],
                  [Payer Cust Industry Code 2 Description],
                  [Payer Cust Assignment to Hierarchy],
                  [Payer Cust Account Group Description],
                  [Payer Cust Region Description],
                  [Payer Cust Country Description],
                  [Payer Cust Transportation Zone Description],
                  [Payer Cust Plant Description],
                  [Payer Cust Condition Group Description],
                  [Payer Cust Cental Billing Block],
                  [Payer Cust Cental Billing Block Description],
                  [Payer Cust Central Delivery Block],
                  [Payer Cust Central Delivery Block Description],
                  [Payer Cust Deletion Indicator],
                  [Payer Cust Central Posting Block],
                  [Payer Cust Tax Jurisdiction],
                  [Payer Cust Central Sales Block],
                  [Payer Cust Central Deletion Indicator],
                  [Payer Cust Language Key],
                  [Payer Cust Trading Partner],
                  [Payer Cust Trading Partner Description],
                  [Payer Cust Annual Sales],
                  [Payer Cust Annual Sales Year],
                  [Payer Cust Sales Currency],
                  [Payer Cust Sales Currency Description],
                  [Payer Cust One Time Account Group],
                  [Payer Cust One Time Account Group Description],
                  [Payer Cust One Time Indicator],
                  [Payer Cust Industry Type],
                  [Payer Cust Business Type],
                  [Payer Cust DUNS Number],
                  [Payer Cust DUNS Plus 4],
                  [Payer Cust City Coordinates],
                  [Payer Cust Tax Number 4 Code],
                  [Payer Cust Attribute 3],
                  [Payer Cust Attribute 3 Description],
                  [Payer Cust E-Mail Address],
                  [Payer Cust Mobile Number],
                  [Payer Cust Search Term 2],
                  [Payer Cust Street 2],
                  [Payer Cust Street 3],
                  [Payer Cust Street 4],
                  [Payer Cust Street 5],
                  [Payer Cust PO Box],
                  [Payer Cust PO Box Postal Code],
                  [Payer Cust PO Box City],
                  [Payer Cust Region For PO Box],
                  [Payer Cust PO Box Country],
                  [Payer Cust Transport Zone],
                  [Payer Cust Address Notes],
                  [Payer Cust Tax Number 3 Code],
                  [Payer Cust Tax Number 5 Code],
                  [Payer Cust Industry Code 3],
                  [Payer Cust Industry Code 3 Description],
                  [Payer Cust Industry Code 4],
                  [Payer Cust Industry Code 4 Description],
                  [Payer Cust Industry Code 5],
                  [Payer Cust Industry Code 5 Description],
                  [Payer Cust Central Order Block For Customer],
                  [Payer Cust Payment Block]
)
AS 
SELECT 
[CUST_KEY],
        [Customer ID],
        [Legacy Customer ID],
        [Customer Name],
        [Customer Line 2 Description],
        [Customer Country Code],
        [Customer Plant ID],
        [Customer Segment ID],
        [Customer Industry],
        [Customer Vendor ID],
        [Customer Group Code],
        [Customer Account Group Code],
        [Customer Title],
        [Customer Search Term],
        [Customer Street],
        [Customer City],
        [Customer Zip Code],
        [Customer State Code],
        [Customer Region Code],
        [Customer Telephone Number 1],
        [Customer Telephone Number 2],
        [Customer Fax Number Code],
        [Customer Tax Number 1 Code],
        [Customer Tax Number 2 Code],
        [Customer VAT Number Code],
        [Customer Credit Limit],
        [Customer Bonus Rate],
        [Customer Express Station],
        [Customer Transportation Zone],
        [Customer Printer Location Characteristics],
        [Customer Printer Region Characteristics],
        [Customer Printer Site Characteristics],
        [Customer Created Date],
        [Customer Created User ID],
        [Customer Updated Date],
        [Customer Updated User ID],
        [Customer Payment Terms Code],
        [Customer Sales Distribution],
        [Customer Order Block For Sales Area],
        [Customer Delivery Block For Sales Area],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Customer Corporate Group],
        [Customer Classification],
        [Customer Classification Description],
        [Customer Printer Location],
        [Customer Printer Site],
        [Customer Printer Region],
        [Customer Specific Field Label 01],
        [Customer Specific Field Label 02],
        [Customer Specific Field Label 03],
        [Customer Specific Field Label 04],
        [Customer Specific Field Label 05],
        [Customer Specific Field Label 06],
        [Customer Specific Field Label 07],
        [Customer Specific Field Label 08],
        [Customer Specific Field Label 09],
        [Customer Specific Field Label 10],
        [Customer Specific Field Label 11],
        [Customer Specific Field Label 12],
        [Customer Specific Field Label 13],
        [Customer Specific Field Label 14],
        [Customer Specific Field Label 15],
        [Customer Specific Field Label 16],
        [Customer Specific Field Label 17],
        [Customer Specific Field Label 18],
        [Customer Specific Field Label 19],
        [Customer Specific Field Label 20],
        [Customer Condition Group 1],
        [Customer Industry Code 1],
        [Customer Industry Code 2],
        [Customer Industry Description],
        [Customer Industry Code 1 Description],
        [Customer Industry Code 2 Description],
        [Customer Assignment to Hierarchy],
        [Customer Account Group Description],
        [Customer Region Description],
        [Customer Country Description],
        [Customer Transportation Zone Description],
        [Customer Plant Description],
        [Customer Condition Group Description],
        [Customer Cental Billing Block],
        [Customer Cental Billing Block Description],
        [Customer Central Delivery Block],
        [Customer Central Delivery Block Description],
        [Customer Deletion Indicator],
        [Customer Central Posting Block],
        [Customer Tax Jurisdiction],
        [Customer Central Sales Block],
        [Customer Central Deletion Indicator],
        [Customer Language Key],
        [Customer Trading Partner],
        [Customer Trading Partner Description],
        [Customer Annual Sales],
        [Customer Annual Sales Year],
        [Customer Sales Currency],
        [Customer Sales Currency Description],
        [Customer One Time Account Group],
        [Customer One Time Account Group Description],
        [Customer One Time Indicator],
        [Customer Industry Type],
        [Customer Business Type],
        [Customer DUNS Number],
        [Customer DUNS Plus 4],
        [Customer City Coordinates],
        [Customer Tax Number 4 Code],
        [Customer Attribute 3],
        [Customer Attribute 3 Description],
        [Customer E-Mail Address],
        [Customer Mobile Number],
        [Customer Search Term 2],
        [Customer Street 2],
        [Customer Street 3],
        [Customer Street 4],
        [Customer Street 5],
        [Customer PO Box],
        [Customer PO Box Postal Code],
        [Customer PO Box City],
        [Customer Region For PO Box],
        [Customer PO Box Country],
        [Customer Transport Zone],
        [Customer Address Notes],
        [Customer Tax Number 3 Code],
        [Customer Tax Number 5 Code],
        [Customer Industry Code 3],
        [Customer Industry Code 3 Description],
        [Customer Industry Code 4],
        [Customer Industry Code 4 Description],
        [Customer Industry Code 5],
        [Customer Industry Code 5 Description],
        [Customer Central Order Block For Customer],
        [Customer Payment Block]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D];