-- Auto Generated (Do not modify) 2C030FF3F7519B6DFC3D01B249BA3BD817EE88B669A249373A3C5A1A7D239B0A

create view [Propelis].[V_PARTNER_COMPANY](
	[CMPNY_KEY],
[Partner Company],
[Partner Legacy Company Code],
[Partner Company Name],
[Partner Company Line Of Business Code],
[Partner Company Line Of Business Code Description],
[Partner Company Currency Code],
[Partner Company Language Type Code],
[Partner Company Chart Of Accounts ID],
[Partner Company Address Line 1],
[Partner Company Address Line 2],
[Partner Company City Name],
[Partner Company Zip Code],
[Partner Company Country Code],
[Partner Company Telephone 1],
[Partner Company Telephone 2],
[Partner Company Fax Number],
[Partner Company Tax Jurisdiction],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Partner Company Fiscal Year Variant],
[Partner Company Credit Control Area],
[Partner Company Input Tax Cd],
[Partner Company Output Tax Code],
[Partner Company Currency Description],
[Partner Company Chart Of Accounts Description],
[Partner Company Country Description],
[Partner Company Fiscal Year Variant Description],
[Partner Company Credit Control Area Description]
) as
SELECT 
    [CMPNY_KEY],
[Company Code],
[Legacy Company Code],
[Company Name],
[Company Line Of Business],
[Company Line Of Business Description],
[Company Currency Code],
[Company Language Type Code],
[Company Chart Of Accounts ID],
[Company Address Line 1],
[Company Address Line 2],
[Company City Name],
[Company Zip Code],
[Company Country Code],
[Company Telephone 1],
[Company Telephone 2],
[Company Fax Number],
[Company Tax Jurisdiction],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Company Fiscal Year Variant],
[Company Credit Control Area],
[Company Input Tax Code],
[Company Output Tax Code],
[Company Currency Description],
[Company Chart Of Accounts Description],
[Company Country Description],
[Company Fiscal Year Variant Description],
[Company Credit Control Area Description]
  FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CMPNYCD_CUR_D];