-- Auto Generated (Do not modify) 41C4ADB7A40B071153B7C86C584C63A3CE0C51DF479020250A3AF84EA5EDAE89
CREATE   view [Propelis].[V_PERSON_RESPNSBLE_COST_CNTR]
    (
        [COST_CNTR_KEY],
[Person Resp Cost Center ID],
[Person Resp Cost Center Long Description],
[Person Resp CC Controlling Area ID],
[Person Resp Cost Center Language Type Code],
[Person Resp Cost Center Category],
[Person Resp Cost Center Hierarchy Area],
[Person Resp Cost Center Company Code],
[Person Resp Cost Center Plant ID],
[Person Resp Cost Center Profit Center ID],
[Person Resp Cost Center Currency Code],
[Person Resp Cost Center Adress Line 1],
[Person Resp Cost Center Line 2],
[Person Resp Cost Center Adress Line 3],
[Person Resp Cost Center City Name],
[Person Resp Cost Center District Name],
[Person Resp Cost Center Postal Code],
[Person Resp Cost Center Country Code],
[Person Resp Cost Center Region Code],
[Person Resp Cost Center Person Responsible],
[Person Resp Cost Center Flag Actual Revenues],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Person Resp CC Actual Primary Postings Lock Indicator],
[Person Resp CC Plan Primary Costs Lock Indicator],
[Person Resp Cost Center Business Area],
[Person Resp CC Planning Revenues Lock Indicator],
[Person Resp Cost Center PO Box],
[Person Resp Cost Center Street],
[Person Resp Cost Center User Respnsble],
[COST_CNTR_NAME],
[Person Resp Cost Center Short Description],
[Person Resp CC Controlling Area Description],
[Person Resp Cost Center Category Description],
[Person Resp Cost Center Company Description],
[Person Resp Cost Center Currency Description],
[Person Resp Cost Center Country Description],
[Person Resp Cost Center Business Area Description],
[Person Resp CC Actual Secondary Cost Lock Indicator],
[Person Resp CC Plan Secondary Cost Lock Indicator],
[Person Resp Cost Center Functional Area],
[Person Resp Cost Center Functional Area Description],
[Person Resp Cost Center Tax Jurisdiction],
[Person Resp Cost Center Function],
[Person Resp Cost Center Plant Description],
[Person Resp Cost Center Created On],
[VALID_TO_DATE],
[VALID_FROM_DATE]
    )
as select 
        [COST_CNTR_KEY],
[Cost Center ID],
[Cost Center Long Description],
[Cost Center Controlling Area ID],
[Cost Center Language Type Code],
[Cost Center Category],
[Cost Center Hierarchy Area],
[Cost Center Company Code],
[Cost Center Plant ID],
[Cost Center Profit Center ID],
[Cost Center Currency Code],
[Cost Center Address Line 1],
[Cost Center Address Line 2],
[Cost Center Address Line 3],
[Cost Center City Name],
[Cost Center District Name],
[Cost Center Postal Code],
[Cost Center Country Code],
[Cost Center Region Code],
[Cost Center Person Responsible],
[Cost Center Flag Actual Revenues],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Cost Center Actual Primary Postings Lock Indicator],
[Cost Center Plan Primary Costs Lock Indicator],
[Cost Center Business Area],
[Cost Center Planning Revenues Lock Indicator],
[Cost Center PO Box],
[Cost Center Street],
[Cost Center User Responsible],
[COST_CNTR_NAME],
[Cost Center Short Description],
[Cost Center Controlling Area Description],
[Cost Center Category Description],
[Cost Center Company Description],
[Cost Center Currency Description],
[Cost Center Country Description],
[Cost Center Business Area Description],
[Cost Center Actual Secondary Cost Lock Indicator],
[Cost Center Plan Secondary Cost Lock Indicator],
[Cost Center Functional Area],
[Cost Center Functional Area Description],
[Cost Center Tax Jurisdiction],
[FUNCTION_OF_COST_CNTR],
[Cost Center Plant Description],
[Cost Center Created On],
[Cost Center Valid To Date],
[Cost Center Valid From Date]

   from  [GLOBAL_EDW].[dbo].[EDW_T_D_MST_COSCNTR_CUR_D];