-- Auto Generated (Do not modify) 6BAD638BB80E747616738205D78C0FC3F6891F6056D13116D2A0B9C2EC7AA2AF
create view [Propelis].[V_PERSONNEL_NUMBER](
[PERSONEL_KEY],
[Personnel Number],
[Personnel Company Code],
[Personnel Plant],
[Personnel Cost Center ID],
[Personnel Success Factors ID],
[Personnel Employee First Name],
[Personnel Employee Last Name],
[Personnel Employee Full Name],
[Personnel Employee Status Indicator],
[Personnel Employee Start Date],
[Personnel Employee End Date],
[Personnel Employee Group ID],
[Personnel Employee Group Description],
[Personnel Employee Subgroup ID],
[Personnel Employee Subgroup Description],
[Personnel Employee Telephone 1],
[Personnel Employee Telephone 2],
[Personnel Employee Email Address],
[Personnel Created Date],
[Personnel Created User ID],
[Personnel Updated Date],
[Personnel Updated User ID],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Personnel Company Description],
[Plant Description]

) as
SELECT 
    [PERSONEL_KEY],
[Personnel Number],
[Personnel Company Code],
[Personnel Plant ID],
[Personnel Cost Center ID],
[Personnel Success Factors ID],
[Personnel Employee First Name],
[Personnel Employee Last Name],
[Personnel Employee Full Name],
[Personnel Employee Status Indicator],
[Personnel Employment Start Date],
[Personnel Employment End Date],
[Personnel Employee Group ID],
[Personnel Employee Group Description],
[Personnel Employee SubGroup ID],
[Personnel Employee SubGroup Description],
[Personnel Employee Telephone 1],
[Personnel Employee Telephone 2],
[EMAIL_ADDR],
[Personnel Created Date],
[Personnel Created User ID],
[Personnel Updated Date],
[Personnel Updated User ID],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Personnel Company Description],
[Personnel Plant Description]

  FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PERSONL_CUR_D];