-- Auto Generated (Do not modify) 2C84A5B763C70F03D26A86F25F86451FB1740389A7DF9FBA5FBAF102A69EB8C9
CREATE   view [Propelis].[V_Planned_Release_Date]
(		
        [DATE_KEY],
        [Planned Release Date],
        [Planned Release Fiscal Year],
        [Planned Release Fiscal Period Number],
        [Planned Release Fiscal Period Code],
        [Planned Release Fiscal Quarter Number],
        [Planned Release Fiscal Quarter Code],
        [Planned Release Calendar Year],
        [Planned Release Calendar Month Number],
        [Planned Release Calendar Month Code],
        [Planned Release Calendar Month Description],
        [Planned Release Calendar Quarter Number],
        [Planned Release Calendar Quarter Code],
        [Planned Release Calendar Weekday Number],
        [Planned Release Calendar Weekday Name],
        [Planned Release Calendar Day In Month],
        [Planned Release Calendar Day In Year],
        [Planned Release Calendar Week],
        [Planned Release Calendar Month In Quarter Number],
        [Planned Release Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Planned Release Current Day Flag],
        [Planned Release Current Day Minus 1 Flag],
        [Planned Release Current Calendar Week Flag],
        [Planned Release Current Calendar Week Minus 1 Flag],
        [Planned Release Current Month Flag],
        [Planned Release Current Month Minus 1 Flag],
        [Planned Release Current Month Minus 12 Flag],
        [Planned Release Current Quarter Flag],
        [Planned Release Current Quarter Minus 1 Flag],
        [Planned Release Current Quarter Minus 4 Flag],
        [Planned Release Current Calendar Year Flag],
        [Planned Release Current Calendar Year Minus 1 Flag],
        [Planned Release Current Calendar Year Minus 2 Flag],
        [Planned Release Current Fiscal Year Flag],
        [Planned Release Current Fiscal Year Minus 1 Flag],
        [Planned Release Current Fiscal Year Minus 2 Flag],
        [Planned Release Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Planned Release Day In Fiscal Year],
        [Planned Release Date Is Weekday],
        [Planned Release Fiscal Week],
        [Planned Release Current Fiscal Week Flag],
        [Planned Release Current Fiscal Week Minus 1 Flag],
        [Planned Release Fiscal Weekday Number],
        [Planned Release Fiscal Weekday Name],
        [Planned Release Current Month Minus 2 Flag],
        [Planned Release Current Fiscal Week Minus 2 Flag],
        [Planned Release Current Fiscal Week Minus 6 Flag],
        [Planned Release Current Fiscal Week Minus 3 Flag],
        [Planned Release Current Fiscal Week Minus 4 Flag],
        [Planned Release Current Fiscal Week Minus 5 Flag],
        [Planned Release Current Fiscal Week Minus 7 Flag]
)AS
SELECT
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];