-- Auto Generated (Do not modify) F51795EFF4B5354E5AD076175E789F2946F6D5F7D78A3DBD28ECD2F8421E3848
CREATE     view [Propelis].[V_PLANT](
[PLNT_KEY],
[Plant ID],
[Legacy Plant ID],
[Plant Name],
[Plant Company Code],
[Plant Sales Organization],
[Plant Purchasing Organization],
[Plant Valuation Area],
[Plant Customer Number],
[Plant Vendor Number],
[Plant Factory Calendar Key],
[Plant Line 1 Description],
[Plant Line 2 Description],
[Plant City Name],
[Plant Zip Code],
[Plant Country Code],
[Plant Country Name],
[Plant Tax Jurisdiction],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Plant Is P001],
[Plant Is P002],
[Plant Company Description],
[Plant Sales Organization Description],
[Plant Factory Calendar Description],
[Plant Purchasing Organization Description],
[Plant Tax Indicator],
[Plant Tax Indicator Description],
[Plant Shipping/Receiving Point],
[Plant Shipping/Receiving Point Description]

) AS
SELECT
   [PLNT_KEY],
[Plant ID],
[Legacy Plant ID],
[Plant Name],
[Plant Company Code],
[Plant Sales Organization],
[Plant Purchasing Organization],
[Plant Valuation Area],
[Plant Customer Number],
[Plant Vendor Number],
[Plant Factory Calendar Key],
[Plant Line 1 Description],
[Plant Line 2 Description],
[Plant City Name],
[Plant Zip Code],
[Plant Country Code],
[Plant Country Name],
[Plant Tax Jurisdiction],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Plant IS P001],
[Plant IS P002],
[Plant Company Description],
[Plant Sales Organization Description],
[Plant Factory Calendar Description],
[Plant Purchasing Organization Description],
[Plant Tax Indicator],
[Plant Tax Indicator Description],
[Plant Shipping/Receiving Point],
[Plant Shipping/Receiving Point Description]

FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PLANT_CUR_D];