-- Auto Generated (Do not modify) 664E782FC63500FA6E0E9456B6CDD70711471B8E34066BD5096F18FBA8BB6834
CREATE VIEW [Propelis].[V_PLANNING_PLANT] 
    (
        [PLNT_KEY],
        [Planning Plant ID],
        [Legacy Planning Plant ID],
        [Planning Plant Name],
        [Planning Plant Company Code],
        [Planning Plant Sales Organization],
        [Planning Plant Purchasing Organization],
        [Planning Plant Valuation Area],
        [Planning Plant Customer Number],
        [Planning Plant Vendor Number],
        [Planning Plant Factory Calendar Key],
        [Planning Plant Line 1 Description],
        [Planning Plant Line 2 Description],
        [Planning Plant City Name],
        [Planning Plant Zip Code],
        [Planning Plant Country Code],
        [Planning Plant Country Name],
        [Planning Plant Tax Jurisdiction],
        [ETL SRC SYS CD],
        [ETL EFFECTV BEGIN DATE],
        [ETL EFFECTV END DATE],
        [ETL CURR RCD IND],
        [ETL CREATED TS],
        [ETL UPDTD TS],
        [Planning Plant IS P001],
        [Planning Plant IS P002],
        [Planning Plant Company Description],
        [Planning Plant Sales Organization Description],
        [Planning Plant Factory Calendar Description],
        [Planning Plant Purchasing Organization Description],
        [Planning Plant Tax Indicator],
        [Planning Plant Tax Indicator Description],
        [Planning Plant Shipping Receiving Point],
        [Planning Plant Shipping Receiving Point Description]
    ) AS 
    SELECT 
            [PLNT_KEY],
        [Plant ID],
        [Legacy Plant ID],
        [Plant Name],
        [Plant Company Code],
        [Plant Sales Organization],
        [Plant Purchasing Organization],
        [Plant Valuation Area],
        [Plant Customer Number],
        [Plant Vendor Number],
        [Plant Factory Calendar Key],
        [Plant Line 1 Description],
        [Plant Line 2 Description],
        [Plant City Name],
        [Plant Zip Code],
        [Plant Country Code],
        [Plant Country Name],
        [Plant Tax Jurisdiction],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Plant IS P001],
        [Plant IS P002],
        [Plant Company Description],
        [Plant Sales Organization Description],
        [Plant Factory Calendar Description],
        [Plant Purchasing Organization Description],
        [Plant Tax Indicator],
        [Plant Tax Indicator Description],
        [Plant Shipping/Receiving Point],
        [Plant Shipping/Receiving Point Description]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PLANT_CUR_D]