-- Auto Generated (Do not modify) 2D1C43DC3B1B74D8C4E63737ED91B8CF257F76D09671B3CF0CEC43A5D2C76237
CREATE   view [Propelis].[V_POSTING_DATE](
    [DATE_KEY],
    [Posting Date],
    [Posting Fiscal Year],
    [FISCAL PER NUM],
    [Posting Fiscal Period Code],
    [Posting Fiscal Quarter Number],
    [Posting Fiscal Quarter Code],
    [Posting Calendar Year],
    [Posting Calendar Month Number],
    [Posting Calendar Month Code],
    [Posting Calendar Month Desc],
    [CLNDR QTR NUM],
    [Posting Calendar Quarter Code],
    [Posting Calendar Weekday Number],
    [Posting Calendar Weekday Name],
    [Posting Calendar Day in Month],
    [Posting Calendar Day in Year],
    [Posting Calendar Week],
    [Posting Calendar Month in Quarter Number],
    [Posting Calendar Days in Month],
    [ETL SRC SYS CD],
    [ETL CREATED TS],
    [ETL UPDTD TS],
    [Posting Current Day Flag],
    [Posting Current Day Minus 1 Flag],
    [Posting Current Calendar Week Flag],
    [Posting Current Calendar Week Minus 1 Flag],
    [Posting Current Month Flag],
    [Posting Current Month Minus 1 Flag],
    [Posting Current Month Minus 12 Flag],
    [Posting Current Quarter Flag],
    [Posting Current Quarter Minus 1 Flag],
    [Posting Current Quarter Minus 4 Flag],
    [Posting Current Calendar Year Flag],
    [Posting Current Calendar Year Minus 1 Flag],
    [Posting Current Calendar Year Minus 2 Flag],
    [Posting Current Fiscal Year Flag],
    [Posting Current Fiscal Year Minus 1 Flag],
    [Posting Current Fiscal Year Minus 2 Flag],
    [Posting Current Calendar Year Plus 1 Flag],
    [Posting Current Fiscal Year Plus 1 Flag],
    [Posting Day in Fiscal Year],
    [Posting Date Is Weekday],
    [Posting Fiscal Week],
    [Posting Current Fiscal Week Flag],
    [Posting Current Fiscal Week Minus 1 Flag],
    [Posting Fiscal Weekday Number],
    [Posting Fiscal Weekday Name],
    [Posting Current Month Minus 2 Flag],
    [Posting Current Fiscal Week Minus 2 Flag],
    [Posting Current Fiscal Week Minus 6 Flag],
    [Posting Current Fiscal Week Minus 3 Flag],
    [Posting Current Fiscal Week Minus 4 Flag],
    [Posting Current Fiscal Week Minus 5 Flag],
    [Posting Current Fiscal Week Minus 7 Flag]
) AS
SELECT 
    [DATE_KEY],
    [Date],
    [Date Fiscal Year],
    [FISCAL_PER_NUM],
    [Date Fiscal Period Code],
    [Date Fiscal Quarter Number],
    [Date Fiscal Quarter Code],
    [Date Calendar Year],
    [Date Calendar Month Number],
    [Date Calendar Month Code],
    [Date Calendar Month Desc],
    [CLNDR_QTR_NUM],
    [Date Calendar Quarter Code],
    [Date Calendar Weekday Number],
    [Date Calendar Weekday Name],
    [Date Calendar Day in Month],
    [Date Calendar Day in Year],
    [Date Calendar Week],
    [Date Calendar Month in Quarter Number],
    [Date Calendar Days in Month],
    [ETL_SRC_SYS_CD],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Date Current Day Flag],
    [Date Current Day Minus 1 Flag],
    [Date Current Calendar Week Flag],
    [Date Current Calendar Week Minus 1 Flag],
    [Date Current Month Flag],
    [Date Current Month Minus 1 Flag],
    [Date Current Month Minus 12 Flag],
    [Date Current Quarter Flag],
    [Date Current Quarter Minus 1 Flag],
    [Date Current Quarter Minus 4 Flag],
    [Date Current Calendar Year Flag],
    [Date Current Calendar Year Minus 1 Flag],
    [Date Current Calendar Year Minus 2 Flag],
    [Date Current Fiscal Year Flag],
    [Date Current Fiscal Year Minus 1 Flag],
    [Date Current Fiscal Year Minus 2 Flag],
    [Date Current Calendar Year Plus 1 Flag],
    [Date Current Fiscal Year Plus 1 Flag],
    [Date Day in Fiscal Year],
    [Date Date Is Weekday],
    [Date Fiscal Week],
    [Date Current Fiscal Week Flag],
    [Date Current Fiscal Week Minus 1 Flag],
    [Date Fiscal Weekday Number],
    [Date Fiscal Weekday Name],
    [Date Current Month Minus 2 Flag],
    [Date Current Fiscal Week Minus 2 Flag],
    [Date Current Fiscal Week Minus 6 Flag],
    [Date Current Fiscal Week Minus 3 Flag],
    [Date Current Fiscal Week Minus 4 Flag],
    [Date Current Fiscal Week Minus 5 Flag],
    [Date Current Fiscal Week Minus 7 Flag]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];