-- Auto Generated (Do not modify) B78D8565E9381EF6293951F981E01B94F6CBA0A525AB1F082D05523A0F24CAF1
CREATE     view [Propelis].[V_PRODUCING_PLANT](
[PLNT_KEY],
[Producing Plant ID],
[Producing Legacy Plant ID],
[Producing Plant Name],
[Producing Plant Company Code],
[Producing Plant Sales Organization],
[Producing Plant Purchasing Organization],
[Producing Plant Valuation Area],
[Producing Plant Customer Number],
[Producing Plant Vendor Number],
[Producing Plant Factory Calendar Key],
[Producing Plant Line 1 Description],
[Producing Plant Line 2 Description],
[Producing Plant City Name],
[Producing Plant Zip Code],
[Producing Plant Country Code],
[Producing Plant Country Name],
[Producing Plant Tax Jurisdiction],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Producing Plant Is P001],
[Producing Plant Is P002],
[Producing Plant Company Description],
[Producing Plant Sales Organization Description],
[Producing Plant Factory Calendar Description],
[Producing Plant Purchasing Organization Description],
[Producing Plant Tax Indicator],
[Producing Plant Tax Indicator Description],
[Producing Plant Shipping/Receiving Point],
[Producing Plant Shipping/Receiving Point Description]

) AS
SELECT
   [PLNT_KEY],
[Plant ID],
[Legacy Plant ID],
[Plant Name],
[Plant Company Code],
[Plant Sales Organization],
[Plant Purchasing Organization],
[Plant Valuation Area],
[Plant Customer Number],
[Plant Vendor Number],
[Plant Factory Calendar Key],
[Plant Line 1 Description],
[Plant Line 2 Description],
[Plant City Name],
[Plant Zip Code],
[Plant Country Code],
[Plant Country Name],
[Plant Tax Jurisdiction],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Plant IS P001],
[Plant IS P002],
[Plant Company Description],
[Plant Sales Organization Description],
[Plant Factory Calendar Description],
[Plant Purchasing Organization Description],
[Plant Tax Indicator],
[Plant Tax Indicator Description],
[Plant Shipping/Receiving Point],
[Plant Shipping/Receiving Point Description]

FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PLANT_CUR_D];