-- Auto Generated (Do not modify) 11B9F02C7AF5406719A4CC7A64517B9E165991A33E47310410ABA5D87457FDAB
CREATE     view [Propelis].[V_RESP_COST_CENTER_HORIZONTAL](
[COST_CNTR_KEY],
[Resp Cost Center Controlling Area ID HH],
[Resp Cost Center ID Leaf level HH],
[Resp Cost Center Level 0 ID HH],
[Resp Cost Center Level 0 Description HH],
[Resp Cost Center Level 1 ID HH],
[Resp Cost Center Level 1 Description HH],
[Resp Cost Center Level 2 ID HH],
[Resp Cost Center Level 2 Description HH],
[Resp Cost Center Level 3 ID HH],
[Resp Cost Center Level 3 Description HH],
[Resp Cost Center Level 4 ID HH],
[Resp Cost Center Level 4 Description HH],
[Resp Cost Center Level 5 ID HH],
[Resp Cost Center Level 5 Description HH],
[Resp Cost Center Level 6 ID HH],
[Resp Cost Center Level 6 Description HH],
[Resp Cost Center Level 7 ID HH],
[Resp Cost Center Level 7 Description HH],
[Resp Cost Center Level 8 ID HH],
[Resp Cost Center Level 8 Description HH]
) AS
SELECT
[COST_CNTR_KEY],
[CONTROLLING_AREA_ID],
[Cost Center ID Leaf level HH],
[LVL_0_ID],
[LVL_0_DESC],
[Cost Center Level 1 ID HH],
[Cost Center Level 1 Description HH],
[Cost Center Level 2 ID HH],
[Cost Center Level 2 Description HH],
[Cost Center Level 3 ID HH],
[Cost Center Level 3 Description HH],
[Cost Center Level 4 ID HH],
[Cost Center Level 4 Description HH],
[Cost Center Level 5 ID HH],
[Cost Center Level 5 Description HH],
[Cost Center Level 6 ID HH],
[Cost Center Level 6 Description HH],
[Cost Center Level 7 ID HH],
[Cost Center Level 7 Description HH],
[Cost Center Level 8 ID HH],
[Cost Center Level 8 Description HH]

FROM [GLOBAL_EDW].[dbo].[EDW_T_D_HY_COSTCHZ_CUR_D];