-- Auto Generated (Do not modify) EA52A2783DAAB32ED7C7ADCAC6EA5D11C46F48F21FB193D253700759B13283B9
CREATE view [Propelis].[V_RESP_COST_CENTER](
    [COST_CNTR_KEY],
[Resp Cost Center ID],
[Resp Cost Center Long Description],
[Resp Cost Center Controlling Area ID],
[Resp Cost Center Language Type Code],
[Resp Cost Center Category],
[Resp Cost Center Hierarchy Area],
[Resp Cost Center Company Code],
[Resp Cost Center Plant],
[Resp Cost Center Proft Center ID],
[Resp Cost Center Currency Code],
[Resp Cost Center Address Line 1],
[Resp Cost Center Address Line 2],
[Resp Cost Center Address Line 3],
[Resp Cost Center City Name],
[Resp Cost Center District Name],
[Resp Cost Center Postal Code],
[Resp Cost Center Country Code],
[Resp Cost Center Region Code],
[Resp Cost Center Person Responsible],
[Resp Cost Center Flag Actual Revenues],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Resp Cost Center Actual Primary Postings Lock Indicator],
[Resp Cost Center Plan Primary Costs Lock Indicator],
[Resp Cost Center Business Area],
[Resp Cost Center Planning Revenues Lock Indicator],
[Resp Cost Center PO Box],
[Resp Cost Center Street],
[Resp Cost Center User Responsible],
[Resp Cost Center Description],
[Resp Cost Center Short Description],
[Resp Cost Center Controlling Area Description],
[Resp Cost Center Category Description],
[Resp Cost Center Company Description],
[Resp Cost Center Currency Description],
[Resp Cost Center Country Description],
[Resp Cost Center Business Area Description],
[Resp Cost Center Actual Secondary Cost Lock Indicator],
[Resp Cost Center Plan Secondary Cost Lock Indicator],
[Resp Cost Center Functional Area],
[Resp Cost Center Functional Area Description],
[Resp Cost Center Tax Jurisdiction],
[Resp Cost Center Function],
[Resp Cost Center Plant Description],
[Resp Cost Center Created On],
[Resp Cost Center Valid To Date],
[Resp Cost Center Valid From Date]
) AS
SELECT 
   [COST_CNTR_KEY],
[Cost Center ID],
[Cost Center Long Description],
[Cost Center Controlling Area ID],
[Cost Center Language Type Code],
[Cost Center Category],
[Cost Center Hierarchy Area],
[Cost Center Company Code],
[Cost Center Plant ID],
[Cost Center Profit Center ID],
[Cost Center Currency Code],
[Cost Center Address Line 1],
[Cost Center Address Line 2],
[Cost Center Address Line 3],
[Cost Center City Name],
[Cost Center District Name],
[Cost Center Postal Code],
[Cost Center Country Code],
[Cost Center Region Code],
[Cost Center Person Responsible],
[Cost Center Flag Actual Revenues],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Cost Center Actual Primary Postings Lock Indicator],
[Cost Center Plan Primary Costs Lock Indicator],
[Cost Center Business Area],
[Cost Center Planning Revenues Lock Indicator],
[Cost Center PO Box],
[Cost Center Street],
[Cost Center User Responsible],
[COST_CNTR_NAME],
[Cost Center Short Description],
[Cost Center Controlling Area Description],
[Cost Center Category Description],
[Cost Center Company Description],
[Cost Center Currency Description],
[Cost Center Country Description],
[Cost Center Business Area Description],
[Cost Center Actual Secondary Cost Lock Indicator],
[Cost Center Plan Secondary Cost Lock Indicator],
[Cost Center Functional Area],
[Cost Center Functional Area Description],
[Cost Center Tax Jurisdiction],
[FUNCTION_OF_COST_CNTR],
[Cost Center Plant Description],
[Cost Center Created On],
[Cost Center Valid To Date],
[Cost Center Valid From Date]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_COSCNTR_CUR_D];