-- Auto Generated (Do not modify) 78DE50B07414CBAFCF61EC5E103D947C7EB74FAD15943F77B7F66CEC1342EC37
CREATE   view [Propelis].[V_REQD_DELVRY_DATE]
(
    [DATE_KEY],
    [Required Delivery Date],
    [Required Delivery Fiscal Year],
    [Required Delivery Fiscal Period],
    [Required Fiscal Period Code],
    [Required Fiscal Quarter],
    [Required Fiscal Quarter Code],
    [Required Calendar Year],
    [Required Calendar Month Number],
    [Required Calendar Month Code],
    [Required Calendar Month Desc],
    [Required Calendar Quarter],
    [Required Calendar Quarter Code],
    [Required Calendar Weekday Number],
    [Required Calendar Weekday Name],
    [Required Calendar Day],
    [Required Calendar Day in Year],
    [Required Calendar Week],
    [Required Calendar Month in Quarter Number],
    [Required Calendar Days in Month],
    [ETL_SRC_SYS_CD],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [CURR_DAY_FLG],
    [Required Current Day Minus 1 Flag],
    [Required Current Calendar Week Flag],
    [Required Current Calendar Week Minus 1 Flag],
    [Required Current Month Flag],
    [Required Current Month Minus 1 Flag],
    [Required Current Month Minus 12 Flag],
    [Required Current Quarter Flag],
    [Required Current Quarter Minus 1 Flag],
    [Required Current Quarter Minus 4 Flag],
    [Required Current Calendar Year Flag],
    [Required Current Calendar Year Minus 1 Flag],
    [Required Current Calendar Year Minus 2 Flag],
    [Required Current Fiscal Year Flag],
    [Required Current Fiscal Year Minus 1 Flag],
    [Required Current Fiscal Year Minus 2 Flag],
    [Required Current Calendar Year Plus 1 Flag],
    [Required Current Fiscal Year Plus 1 Flag],
    [Required Day In Fiscal Year],
    [Required Date Is Weekday],
    [Required Fiscal Week],
    [Required Current Fiscal Week Flag],
    [Required Current Fiscal Week Minus 1 Flag],
    [Required Fiscal Weekday Number],
    [Required Fiscal Weekday Name],
    [Required Current Month Minus 2 Flag],
    [Required Current Fiscal Week Minus 2 Flag],
    [Required Current Fiscal Week Minus 6 Flag],
    [Required Current Fiscal Week Minus 3 Flag],
    [Required Current Fiscal Week Minus 4 Flag],
    [Required Current Fiscal Week Minus 5 Flag],
    [Required Current Fiscal Week Minus 7 Flag]
)

as select 
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
   from  [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];