-- Auto Generated (Do not modify) 3B39989292888EAF668CD41F8FACBBBB8A592E9988160E92440AE64F052C8400
CREATE VIEW [Propelis].[V_RELEASE_DATE] (
                [DATE_KEY],
        [Release Date],
        [Release Fiscal Year],
        [Release Fiscal Period Number],
        [Release Fiscal Period Code],
        [Release Fiscal Quarter Number],
        [Release Fiscal Quarter Code],
        [Release Calendar Year],
        [Release Calendar Month Number],
        [Release Calendar Month Code],
        [Release Calendar Month Description],
        [Release Calendar Quarter Number],
        [Release Calendar Quarter Code],
        [Release Calendar Weekday Number],
        [Release Calendar Weekday Name],
        [Release Calendar Day In Month],
        [Release Calendar Day In Year],
        [Release Calendar Week],
        [Release Calendar Month In Quarter Number],
        [Release Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Release Current Day Flag],
        [Release Current Day Minus 1 Flag],
        [Release Current Calendar Week Flag],
        [Release Current Calendar Week Minus 1 Flag],
        [Release Current Month Flag],
        [Release Current Month Minus 1 Flag],
        [Release Current Month Minus 12 Flag],
        [Release Current Quarter Flag],
        [Release Current Quarter Minus 1 Flag],
        [Release Current Quarter Minus 4 Flag],
        [Release Current Calendar Year Flag],
        [Release Current Calendar Year Minus 1 Flag],
        [Release Current Calendar Year Minus 2 Flag],
        [Release Current Fiscal Year Flag],
        [Release Current Fiscal Year Minus 1 Flag],
        [Release Current Fiscal Year Minus 2 Flag],
        [Release Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Release Day In Fiscal Year],
        [Release Date Is Weekday],
        [Release Fiscal Week],
        [Release Current Fiscal Week Flag],
        [Release Current Fiscal Week Minus 1 Flag],
        [Release Fiscal Weekday Number],
        [Release Fiscal Weekday Name],
        [Release Current Month Minus 2 Flag],
        [Release Current Fiscal Week Minus 2 Flag],
        [Release Current Fiscal Week Minus 6 Flag],
        [Release Current Fiscal Week Minus 3 Flag],
        [Release Current Fiscal Week Minus 4 Flag],
        [Release Current Fiscal Week Minus 5 Flag],
        [Release Current Fiscal Week Minus 7 Flag]
    ) AS 
    SELECT
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D]