-- Auto Generated (Do not modify) 9890FC61247D5F85F738E2CC1DE48374DD34955C64A21618EA84964360DB6FE4

create view [Propelis].[V_SALES_EMPLOYEE](
[PERSONEL_KEY],
[Sales Employee Number],
[Sales Employee Company Code],
[Sales Employee Plant],
[Sales Employee Cost Center ID],
[Sales Employee Success Factors ID],
[Sales Employee First Name],
[Sales Employee Last Name],
[Sales Employee Full Name],
[Sales Employee Status Indicator],
[Sales Employee Start Date],
[Sales Employee End Date],
[Sales Employee Group ID],
[Sales Employee Group Description],
[Sales Employee Subgroup ID],
[Sales Employee Subgroup Description],
[Sales Employee Telephone 1],
[Sales Employee Telephone 2],
[Sales Employee Email Address],
[Sales Employee Created Date],
[Sales Employee Created User ID],
[Sales Employee Updated Date],
[Sales Employee Updated User ID],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Sales Employee Company Description],
[Sales Employee Plant Description]
) as
SELECT 
   [PERSONEL_KEY],
[Personnel Number],
[Personnel Company Code],
[Personnel Plant ID],
[Personnel Cost Center ID],
[Personnel Success Factors ID],
[Personnel Employee First Name],
[Personnel Employee Last Name],
[Personnel Employee Full Name],
[Personnel Employee Status Indicator],
[Personnel Employment Start Date],
[Personnel Employment End Date],
[Personnel Employee Group ID],
[Personnel Employee Group Description],
[Personnel Employee SubGroup ID],
[Personnel Employee SubGroup Description],
[Personnel Employee Telephone 1],
[Personnel Employee Telephone 2],
[EMAIL_ADDR],
[Personnel Created Date],
[Personnel Created User ID],
[Personnel Updated Date],
[Personnel Updated User ID],
[ETL_SRC_SYS_CD],
[ETL_EFFECTV_BEGIN_DATE],
[ETL_EFFECTV_END_DATE],
[ETL_CURR_RCD_IND],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Personnel Company Description],
[Personnel Plant Description]
  FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PERSONL_CUR_D];