-- Auto Generated (Do not modify) 670B49F206D8E510C3E35A9182EB06AD7628C9A767DC2F48A511EF4773D5E593
CREATE   view [Propelis].[V_SALES_PERSON_PERSONEL] (
                [PERSONEL_KEY],
                [Personnel Number],
                [Company Code],
                [Plant ID],
                [Cost Center ID],
                [Success Factors ID],
                [Employee First Name],
                [Employee Last Name],
                [Employee Full Name],
                [Employee Status lndicator],
                [Employment Start Date],
                [Employment End Date],
                [Employee Group Id],
                [Employee Group Description],
                [Employee Subgroup ID],
                [Employee Subgroup Description],
                [Employee Telephone 1],
                [Employee Telephone 2],
                [Email Address],
                [Created Date],
                [Created User ID],
                [Updated Date],
                [Updated User ID],
                [ETL_SRC_SYS_CD],
                [ETL_EFFECTV_BEGIN_DATE],
                [ETL_EFFECTV_END_DATE],
                [ETL_CURR_RCD_IND],
                [ETL_CREATED_TS],
                [ETL_UPDTD_TS],
                [Company Description],
                [Plant Description]	
            )
as select 
        [PERSONEL_KEY],
        [Personnel Number],
        [Personnel Company Code],
        [Personnel Plant ID],
        [Personnel Cost Center ID],
        [Personnel Success Factors ID],
        [Personnel Employee First Name],
        [Personnel Employee Last Name],
        [Personnel Employee Full Name],
        [Personnel Employee Status Indicator],
        [Personnel Employment Start Date],
        [Personnel Employment End Date],
        [Personnel Employee Group ID],
        [Personnel Employee Group Description],
        [Personnel Employee SubGroup ID],
        [Personnel Employee SubGroup Description],
        [Personnel Employee Telephone 1],
        [Personnel Employee Telephone 2],
        [EMAIL_ADDR],
        [Personnel Created Date],
        [Personnel Created User ID],
        [Personnel Updated Date],
        [Personnel Updated User ID],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Personnel Company Description],
        [Personnel Plant Description]
   from  [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PERSONL_CUR_D];