-- Auto Generated (Do not modify) 0E5E20E915BD8D0FDAA160C3689FD7AB75738218B5382B3D245475085B53432D
CREATE   view [Propelis].[V_SCHLD_FINISH_DATE]
(		
        [DATE_KEY],
        [Schld Finish Date],
        [Schld Finish Fiscal Year],
        [Schld Finish Fiscal Period Number],
        [Schld Finish Fiscal Period Code],
        [Schld Finish Fiscal Quarter Number],
        [Schld Finish Fiscal Quarter Code],
        [Schld Finish Calendar Year],
        [Schld Finish Calendar Month Number],
        [Schld Finish Calendar Month Code],
        [Schld Finish Calendar Month Description],
        [Schld Finish Calendar Quarter Number],
        [Schld Finish Calendar Quarter Code],
        [Schld Finish Calendar Weekday Number],
        [Schld Finish Calendar Weekday Name],
        [Schld Finish Calendar Day In Month],
        [Schld Finish Calendar Day In Year],
        [Schld Finish Calendar Week],
        [Schld Finish Calendar Month In Quarter Number],
        [Schld Finish Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Schld Finish Current Day Flag],
        [Schld Finish Current Day Minus 1 Flag],
        [Schld Finish Current Calendar Week Flag],
        [Schld Finish Current Calendar Week Minus 1 Flag],
        [Schld Finish Current Month Flag],
        [Schld Finish Current Month Minus 1 Flag],
        [Schld Finish Current Month Minus 12 Flag],
        [Schld Finish Current Quarter Flag],
        [Schld Finish Current Quarter Minus 1 Flag],
        [Schld Finish Current Quarter Minus 4 Flag],
        [Schld Finish Current Calendar Year Flag],
        [Schld Finish Current Calendar Year Minus 1 Flag],
        [Schld Finish Current Calendar Year Minus 2 Flag],
        [Schld Finish Current Fiscal Year Flag],
        [Schld Finish Current Fiscal Year Minus 1 Flag],
        [Schld Finish Current Fiscal Year Minus 2 Flag],
        [Schld Finish Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Schld Finish Day In Fiscal Year],
        [Schld Finish Date Is Weekday],
        [Schld Finish Fiscal Week],
        [Schld Finish Current Fiscal Week Flag],
        [Schld Finish Current Fiscal Week Minus 1 Flag],
        [Schld Finish Fiscal Weekday Number],
        [Schld Finish Fiscal Weekday Name],
        [Schld Finish Current Month Minus 2 Flag],
        [Schld Finish Current Fiscal Week Minus 2 Flag],
        [Schld Finish Current Fiscal Week Minus 6 Flag],
        [Schld Finish Current Fiscal Week Minus 3 Flag],
        [Schld Finish Current Fiscal Week Minus 4 Flag],
        [Schld Finish Current Fiscal Week Minus 5 Flag],
        [Schld Finish Current Fiscal Week Minus 7 Flag]
)AS
SELECT
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];