-- Auto Generated (Do not modify) D278582601894987A19C65884DA67F870BD3B9D2518C60FD9CAF18B679981CB2
CREATE   view [Propelis].[V_SCHLD_RELEASE_DATE]
(		
		[DATE_KEY],
        [Schld Release Date],
        [Schld Release Fiscal Year],
        [Schld Release Fiscal Period Number],
        [Schld Release Fiscal Period Code],
        [Schld Release Fiscal Quarter Number],
        [Schld Release Fiscal Quarter Code],
        [Schld Release Calendar Year],
        [Schld Release Calendar Month Number],
        [Schld Release Calendar Month Code],
        [Schld Release Calendar Month Description],
        [Schld Release Calendar Quarter Number],
        [Schld Release Calendar Quarter Code],
        [Schld Release Calendar Weekday Number],
        [Schld Release Calendar Weekday Name],
        [Schld Release Calendar Day In Month],
        [Schld Release Calendar Day In Year],
        [Schld Release Calendar Week],
        [Schld Release Calendar Month In Quarter Number],
        [Schld Release Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Schld Release Current Day Flag],
        [Schld Release Current Day Minus 1 Flag],
        [Schld Release Current Calendar Week Flag],
        [Schld Release Current Calendar Week Minus 1 Flag],
        [Schld Release Current Month Flag],
        [Schld Release Current Month Minus 1 Flag],
        [Schld Release Current Month Minus 12 Flag],
        [Schld Release Current Quarter Flag],
        [Schld Release Current Quarter Minus 1 Flag],
        [Schld Release Current Quarter Minus 4 Flag],
        [Schld Release Current Calendar Year Flag],
        [Schld Release Current Calendar Year Minus 1 Flag],
        [Schld Release Current Calendar Year Minus 2 Flag],
        [Schld Release Current Fiscal Year Flag],
        [Schld Release Current Fiscal Year Minus 1 Flag],
        [Schld Release Current Fiscal Year Minus 2 Flag],
        [Schld Release Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Schld Release Day In Fiscal Year],
        [Schld Release Date Is Weekday],
        [Schld Release Fiscal Week],
        [Schld Release Current Fiscal Week Flag],
        [Schld Release Current Fiscal Week Minus 1 Flag],
        [Schld Release Fiscal Weekday Number],
        [Schld Release Fiscal Weekday Name],
        [Schld Release Current Month Minus 2 Flag],
        [Schld Release Current Fiscal Week Minus 2 Flag],
        [Schld Release Current Fiscal Week Minus 6 Flag],
        [Schld Release Current Fiscal Week Minus 3 Flag],
        [Schld Release Current Fiscal Week Minus 4 Flag],
        [Schld Release Current Fiscal Week Minus 5 Flag],
        [Schld Release Current Fiscal Week Minus 7 Flag]
)AS
SELECT
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];