-- Auto Generated (Do not modify) B7BCFF301427B9FDDE8805E1704A915E8076A11888A196425120B182C2B588CE
CREATE   VIEW [Propelis].[V_SERV_ORDER_INVOICE_CREATED_DATE](
    [DATE_KEY],
    [THE_DATE],
    [Service Order Created Fiscal Year],
    [FISCAL_PER_NUM],
    [Service Order Created Fiscal Period Code],
    [Service Order Created Fiscal Quarter Number],
    [Service Order Created Fiscal Quarter Code],
    [Service Order Created Calendar Year],
    [Service Order Created Calendar Month Number],
    [Service Order Created Calendar Month Code],
    [Service Order Created Calendar Month Desc],
    [CLNDR_QTR_NUM],
    [Service Order Created Calendar Quarter Code],
    [Service Order Created Calendar Weekday Number],
    [Service Order Created Calendar Weekday Name],
    [Service Order Created Calendar Day in Month],
    [Service Order Created Calendar Day in Year],
    [Service Order Created Calendar Week],
    [Service Order Created Calendar Month in Quarter Number],
    [Service Order Created Calendar Days in Month],
    [ETL_SRC_SYS_CD],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Service Order Created Current Day Flag],
    [Service Order Created Current Day Minus 1 Flag],
    [Service Order Created Current Calendar Week Flag],
    [Service Order Created Current Calendar Week Minus 1 Flag],
    [Service Order Created Current Month Flag],
    [Service Order Created Current Month Minus 1 Flag],
    [Service Order Created Current Month Minus 12 Flag],
    [Service Order Created Current Quarter Flag],
    [Service Order Created Current Quarter Minus 1 Flag],
    [Service Order Created Current Quarter Minus 4 Flag],
    [Service Order Created Current Calendar Year Flag],
    [Service Order Created Current Calendar Year Minus 1 Flag],
    [Service Order Created Current Calendar Year Minus 2 Flag],
    [Service Order Created Current Fiscal Year Flag],
    [Service Order Created Current Fiscal Year Minus 1 Flag],
    [Service Order Created Current Fiscal Year Minus 2 Flag],
    [Service Order Created Current Calendar Year Plus 1 Flag],
    [Service Order Created Current Fiscal Year Plus 1 Flag],
    [Service Order Created Day in Fiscal Year],
    [Service Order Created Date Is Weekday],
    [Service Order Fiscal Week],
    [Service Order Current Fiscal Week Flag],
    [Service Order Current Fiscal Week Minus 1 Flag],
    [Service Order Fiscal Weekday Number],
    [Service Order Fiscal Weekday Name],
    [CURR_MNTH_MINUS_2_FLG],
    [Service Order Current Fiscal Week Minus 2 Flag],
    [Service Order Current Fiscal Week Minus 6 Flag],
    [Service Order Current Fiscal Week Minus 3 Flag],
    [Service Order Current Fiscal Week Minus 4 Flag],
    [Service Order Current Fiscal Week Minus 5 Flag],
    [Service Order Current Fiscal Week Minus 7 Flag]
)AS
SELECT
    [DATE_KEY],
    [Date],
    [Date Fiscal Year],
    [FISCAL_PER_NUM],
    [Date Fiscal Period Code],
    [Date Fiscal Quarter Number],
    [Date Fiscal Quarter Code],
    [Date Calendar Year],
    [Date Calendar Month Number],
    [Date Calendar Month Code],
    [Date Calendar Month Desc],
    [CLNDR_QTR_NUM],
    [Date Calendar Quarter Code],
    [Date Calendar Weekday Number],
    [Date Calendar Weekday Name],
    [Date Calendar Day in Month],
    [Date Calendar Day in Year],
    [Date Calendar Week],
    [Date Calendar Month in Quarter Number],
    [Date Calendar Days in Month],
    [ETL_SRC_SYS_CD],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Date Current Day Flag],
    [Date Current Day Minus 1 Flag],
    [Date Current Calendar Week Flag],
    [Date Current Calendar Week Minus 1 Flag],
    [Date Current Month Flag],
    [Date Current Month Minus 1 Flag],
    [Date Current Month Minus 12 Flag],
    [Date Current Quarter Flag],
    [Date Current Quarter Minus 1 Flag],
    [Date Current Quarter Minus 4 Flag],
    [Date Current Calendar Year Flag],
    [Date Current Calendar Year Minus 1 Flag],
    [Date Current Calendar Year Minus 2 Flag],
    [Date Current Fiscal Year Flag],
    [Date Current Fiscal Year Minus 1 Flag],
    [Date Current Fiscal Year Minus 2 Flag],
    [Date Current Calendar Year Plus 1 Flag],
    [Date Current Fiscal Year Plus 1 Flag],
    [Date Day in Fiscal Year],
    [Date Date Is Weekday],
    [Date Fiscal Week],
    [Date Current Fiscal Week Flag],
    [Date Current Fiscal Week Minus 1 Flag],
    [Date Fiscal Weekday Number],
    [Date Fiscal Weekday Name],
    [Date Current Month Minus 2 Flag],
    [Date Current Fiscal Week Minus 2 Flag],
    [Date Current Fiscal Week Minus 6 Flag],
    [Date Current Fiscal Week Minus 3 Flag],
    [Date Current Fiscal Week Minus 4 Flag],
    [Date Current Fiscal Week Minus 5 Flag],
    [Date Current Fiscal Week Minus 7 Flag]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];