-- Auto Generated (Do not modify) 9602CFAA55770EB9BFD7E5F47A41562A2FA57E23D3491256D9CBAE8EA4FB8EC1
CREATE   view [Propelis].[V_SOLD_TO_CUST] (
                 [CUST_KEY],
                 [Sold To Customer ID],
                 [Sold To Customer Legacy ID],
                 [Sold To Customer Name],
                 [Sold To Cust Line 2 Description],
                 [Sold To Cust Country Code],
                 [Sold To Cust Plant ID],
                 [Sold To Cust Segment ID],
                 [Sold To Cust Industry],
                 [Sold To Cust Vendor ID],
                 [Sold To Cust Group Code],
                 [Sold To Cust Account Group Code],
                 [Sold To Cust Title],
                 [Sold To Cust Search Term],
                 [Sold To Cust Street],
                 [Sold To Cust City Name],
                 [Sold To Cust Zip Code],
                 [Sold To Cust State Code],
                 [Sold To Cust Region Code],
                 [Sold To Cust Telephone Number 1 Code],
                 [Sold To Cust Telephone Number 2 Code],
                 [Sold To Cust Fax Number Code],
                 [Sold To Cust Tax Number 1 Code],
                 [Sold To Cust Tax Number 2 Code],
                 [Sold To Cust VAT Number Code],
                 [Sold To Cust Credit Limit],
                 [Sold To Cust Bonus Rate],
                 [Sold To Cust Express Station],
                 [Sold To Cust Transportation Zone],
                 [Sold To Cust Printer Location Characteristics],
                 [Sold To Cust Printer Region Characteristics],
                 [Sold To Cust Printer Site Characteristics],
                 [Sold To Cust Created Date],
                 [Sold To Cust Created User ID],
                 [Sold To Cust Updated Date],
                 [Sold To Cust Updated User ID],
                 [Sold To Cust Payment Terms Code],
                 [Sold To Cust Sales Distribution],
                 [Sold To Cust Order Block For Sales Area],
                 [Sold To Cust Delivery Block For Sales Area],
                 [ETL_SRC_SYS_CD],
                 [ETL_EFFECTV_BEGIN_DATE],
                 [ETL_EFFECTV_END_DATE],
                 [ETL_CURR_RCD_IND],
                 [ETL_CREATED_TS],
                 [ETL_UPDTD_TS],
                 [Sold To Cust Corporate Group],
                 [Sold To Cust Classification],
                 [Sold To Cust Classification Description],
                 [Sold To Cust Printer Location],
                 [Sold To Cust Printer Site],
                 [Sold To Cust Printer Region],
                 [Sold To Cust Specific Field Label 01],
                 [Sold To Cust Specific Field Label 02],
                 [Sold To Cust Specific Field Label 03],
                 [Sold To Cust Specific Field Label 04],
                 [Sold To Cust Specific Field Label 05],
                 [Sold To Cust Specific Field Label 06],
                 [Sold To Cust Specific Field Label 07],
                 [Sold To Cust Specific Field Label 08],
                 [Sold To Cust Specific Field Label 09],
                 [Sold To Cust Specific Field Label 10],
                 [Sold To Cust Specific Field Label 11],
                 [Sold To Cust Specific Field Label 12],
                 [Sold To Cust Specific Field Label 13],
                 [Sold To Cust Specific Field Label 14],
                 [Sold To Cust Specific Field Label 15],
                 [Sold To Cust Specific Field Label 16],
                 [Sold To Cust Specific Field Label 17],
                 [Sold To Cust Specific Field Label 18],
                 [Sold To Cust Specific Field Label 19],
                 [Sold To Cust Specific Field Label 20],
                 [Sold To Cust Condition Group 1],
                 [Sold To Cust Industry Code 1],
                 [Sold To Cust Industry Code 2],
                 [Sold To Cust Industry Description],
                 [Sold To Cust Industry Code 1 Description],
                 [Sold To Cust Industry Code 2 Description],
                 [Sold To Cust Assignment to Hierarchy],
                 [Sold To Cust Account Group Description],
                 [Sold To Cust Region Description],
                 [Sold To Cust Country Description],
                 [Sold To Cust Transportation Zone Description],
                 [Sold To Cust Plant Description],
                 [Sold To Cust Condition Group Description],
                 [Sold To Cust Central Billing Block],
                 [Sold To Cust Central Billing Block Description],
                 [Sold To Cust Central Delivery Block],
                 [Sold To Cust Central Delivery Block Description],
                 [Sold To Cust Deletion Indicator],
                 [Sold To Cust Central Posting Block],
                 [Sold To Cust Tax Jurisdiction],
                 [Sold To Cust Central Sales Block],
                 [Sold To Cust Central Deletion Indicator],
                 [Sold To Cust Language Key],
                 [Sold To Cust Trading Partner],
                 [Sold To Cust Trading Partner Description],
                 [Sold To Cust Annual Sales],
                 [Sold To Cust Annual Sales Year],
                 [Sold To Cust Sales Currency],
                 [Sold To Cust Sales Currency Description],
                 [Sold To Cust One Time Account Group],
                 [Sold To Cust One Time Account Group Description],
                 [Sold To Cust One Time Cust Indicator],
                 [Sold To Cust Industry Type],
                 [Sold To Cust Business Type],
                 [Sold To Cust DUNS Number],
                 [Sold To Cust DUNS Plus 4],
                 [Sold To Cust City Coordinates],
                 [Sold To Cust Tax Number 4 Code],
                 [Sold To Cust Attribute 3],
                 [Sold To Cust Attribute 3 Description],
                 [Sold To Cust E-Mail Address],
                 [Sold To Cust Mobile Number],
                 [Sold To Cust Search Term 2],
                 [Sold To Cust Street 2],
                 [Sold To Cust Street 3],
                 [Sold To Cust Street 4],
                 [Sold To Cust Street 5],
                 [Sold To Cust PO Box],
                 [Sold To Cust PO Box Postal Code],
                 [Sold To Cust PO Box City],
                 [Sold To Cust Region For PO Box],
                 [Sold To Cust PO Box Country],
                 [Sold To Cust Transport Zone],
                 [Sold To Cust Address Notes],
                 [Sold To Cust Tax Number 3 Code],
                 [Sold To Cust Tax Number 5 Code],
                 [Sold To Cust Industry Code 3],
                 [Sold To Cust Industry Code 3 Description],
                 [Sold To Cust Industry Code 4],
                 [Sold To Cust Industry Code 4 Description],
                 [Sold To Cust Industry Code 5],
                 [Sold To Cust Industry Code 5 Description],
                 [Sold To Cust Central Order Block For Customer],
                 [Sold To Cust Payment Block]
    ) AS 
    SELECT 
    [CUST_KEY],
        [Customer ID],
        [Legacy Customer ID],
        [Customer Name],
        [Customer Line 2 Description],
        [Customer Country Code],
        [Customer Plant ID],
        [Customer Segment ID],
        [Customer Industry],
        [Customer Vendor ID],
        [Customer Group Code],
        [Customer Account Group Code],
        [Customer Title],
        [Customer Search Term],
        [Customer Street],
        [Customer City],
        [Customer Zip Code],
        [Customer State Code],
        [Customer Region Code],
        [Customer Telephone Number 1],
        [Customer Telephone Number 2],
        [Customer Fax Number Code],
        [Customer Tax Number 1 Code],
        [Customer Tax Number 2 Code],
        [Customer VAT Number Code],
        [Customer Credit Limit],
        [Customer Bonus Rate],
        [Customer Express Station],
        [Customer Transportation Zone],
        [Customer Printer Location Characteristics],
        [Customer Printer Region Characteristics],
        [Customer Printer Site Characteristics],
        [Customer Created Date],
        [Customer Created User ID],
        [Customer Updated Date],
        [Customer Updated User ID],
        [Customer Payment Terms Code],
        [Customer Sales Distribution],
        [Customer Order Block For Sales Area],
        [Customer Delivery Block For Sales Area],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Customer Corporate Group],
        [Customer Classification],
        [Customer Classification Description],
        [Customer Printer Location],
        [Customer Printer Site],
        [Customer Printer Region],
        [Customer Specific Field Label 01],
        [Customer Specific Field Label 02],
        [Customer Specific Field Label 03],
        [Customer Specific Field Label 04],
        [Customer Specific Field Label 05],
        [Customer Specific Field Label 06],
        [Customer Specific Field Label 07],
        [Customer Specific Field Label 08],
        [Customer Specific Field Label 09],
        [Customer Specific Field Label 10],
        [Customer Specific Field Label 11],
        [Customer Specific Field Label 12],
        [Customer Specific Field Label 13],
        [Customer Specific Field Label 14],
        [Customer Specific Field Label 15],
        [Customer Specific Field Label 16],
        [Customer Specific Field Label 17],
        [Customer Specific Field Label 18],
        [Customer Specific Field Label 19],
        [Customer Specific Field Label 20],
        [Customer Condition Group 1],
        [Customer Industry Code 1],
        [Customer Industry Code 2],
        [Customer Industry Description],
        [Customer Industry Code 1 Description],
        [Customer Industry Code 2 Description],
        [Customer Assignment to Hierarchy],
        [Customer Account Group Description],
        [Customer Region Description],
        [Customer Country Description],
        [Customer Transportation Zone Description],
        [Customer Plant Description],
        [Customer Condition Group Description],
        [Customer Cental Billing Block],
        [Customer Cental Billing Block Description],
        [Customer Central Delivery Block],
        [Customer Central Delivery Block Description],
        [Customer Deletion Indicator],
        [Customer Central Posting Block],
        [Customer Tax Jurisdiction],
        [Customer Central Sales Block],
        [Customer Central Deletion Indicator],
        [Customer Language Key],
        [Customer Trading Partner],
        [Customer Trading Partner Description],
        [Customer Annual Sales],
        [Customer Annual Sales Year],
        [Customer Sales Currency],
        [Customer Sales Currency Description],
        [Customer One Time Account Group],
        [Customer One Time Account Group Description],
        [Customer One Time Indicator],
        [Customer Industry Type],
        [Customer Business Type],
        [Customer DUNS Number],
        [Customer DUNS Plus 4],
        [Customer City Coordinates],
        [Customer Tax Number 4 Code],
        [Customer Attribute 3],
        [Customer Attribute 3 Description],
        [Customer E-Mail Address],
        [Customer Mobile Number],
        [Customer Search Term 2],
        [Customer Street 2],
        [Customer Street 3],
        [Customer Street 4],
        [Customer Street 5],
        [Customer PO Box],
        [Customer PO Box Postal Code],
        [Customer PO Box City],
        [Customer Region For PO Box],
        [Customer PO Box Country],
        [Customer Transport Zone],
        [Customer Address Notes],
        [Customer Tax Number 3 Code],
        [Customer Tax Number 5 Code],
        [Customer Industry Code 3],
        [Customer Industry Code 3 Description],
        [Customer Industry Code 4],
        [Customer Industry Code 4 Description],
        [Customer Industry Code 5],
        [Customer Industry Code 5 Description],
        [Customer Central Order Block For Customer],
        [Customer Payment Block]
        FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D];