-- Auto Generated (Do not modify) 33211AA35954DADCA54010AAD77C7AF1A8908E1E67ECCF505E165CF318A57A2B
CREATE   view [Propelis].[V_SO_PARENT_CUST]
    (
        [CUST_KEY],
        [SO Parent Customer ID],
        [SO Parent Legacy Customer ID],
        [SO Parent Customer Name],
        [SO Parent Cust Line 2 Description],
        [SO Parent Cust Country Code],
        [SO Parent Cust Plant ID],
        [SO Parent Cust Segment ID],
        [SO Parent Cust Industry],
        [SO Parent Cust Vendor ID],
        [SO Parent Cust Group Code],
        [SO Parent Cust Account Group Code],
        [SO Parent Cust Title],
        [SO Parent Cust Search Term],
        [SO Parent Cust Street],
        [SO Parent Cust City],
        [SO Parent Cust Zip Code],
        [SO Parent Cust State Code],
        [SO Parent Cust Region Code],
        [SO Parent Cust Telephone Number 1],
        [SO Parent Cust Telephone Number 2],
        [SO Parent Cust Fax Number Code],
        [SO Parent Cust Tax Number 1 Code],
        [SO Parent Cust Tax Number 2 Code],
        [SO Parent Cust VAT Number Code],
        [SO Parent Cust Credit Limit],
        [SO Parent Cust Bonus Rate],
        [SO Parent Cust Express Station],
        [SO Parent Cust Transportation Zone],
        [SO Parent Cust Printer Location Characteristics],
        [SO Parent Cust Printer Region Characteristics],
        [SO Parent Cust Printer Site Characteristics],
        [SO Parent Cust Created Date],
        [SO Parent Cust Created User ID],
        [SO Parent Cust Updated Date],
        [SO Parent Cust Updated User ID],
        [SO Parent Cust Payment Terms Code],
        [SO Parent Cust Sales Distribution],
        [SO Parent Cust Order Block For Sales Area],
        [SO Parent Cust Delivery Block For Sales Area],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [SO Parent Cust Corporate Group],
        [SO Parent Cust Customer Classification],
        [SO Parent Cust Classification Description],
        [SO Parent Cust Printer Location],
        [SO Parent Cust Printer Site],
        [SO Parent Cust Printer Region],
        [SO Parent Cust Specific Field Label 01],
        [SO Parent Cust Specific Field Label 02],
        [SO Parent Cust Specific Field Label 03],
        [SO Parent Cust Specific Field Label 04],
        [SO Parent Cust Specific Field Label 05],
        [SO Parent Cust Specific Field Label 06],
        [SO Parent Cust Specific Field Label 07],
        [SO Parent Cust Specific Field Label 08],
        [SO Parent Cust Specific Field Label 09],
        [SO Parent Cust Specific Field Label 10],
        [SO Parent Cust Specific Field Label 11],
        [SO Parent Cust Specific Field Label 12],
        [SO Parent Cust Specific Field Label 13],
        [SO Parent Cust Specific Field Label 14],
        [SO Parent Cust Specific Field Label 15],
        [SO Parent Cust Specific Field Label 16],
        [SO Parent Cust Specific Field Label 17],
        [SO Parent Cust Specific Field Label 18],
        [SO Parent Cust Specific Field Label 19],
        [SO Parent Cust Specific Field Label 20],
        [SO Parent Cust Condition Group 1],
        [SO Parent Cust Industry Code 1],
        [SO Parent Cust Industry Code 2],
        [SO Parent Cust Industry Description],
        [SO Parent Cust Industry Code 1 Description],
        [SO Parent Cust Industry Code 2 Description],
        [SO Parent Cust Assignment to Hierarchy],
        [SO Parent Cust Account Group Description],
        [SO Parent Cust Region Description],
        [SO Parent Cust Country Description],
        [SO Parent Cust Transportation Zone Description],
        [SO Parent Cust Plant Description],
        [SO Parent Cust Condition Group Description],
        [SO Parent Cust Cental Billing Block],
        [SO Parent Cust Cental Billing Block Description],
        [SO Parent Cust Central Delivery Block],
        [SO Parent Cust Central Delivery Block Description],
        [SO Parent Cust Deletion Indicator],
        [SO Parent Cust Central Posting Block],
        [SO Parent Cust Tax Jurisdiction],
        [SO Parent Cust Central Sales Block],
        [SO Parent Cust Central Deletion Indicator],
        [SO Parent Cust Language Key],
        [SO Parent Cust Trading Partner],
        [SO Parent Cust Trading Partner Description],
        [SO Parent Cust Annual Sales],
        [SO Parent Cust Annual Sales Year],
        [SO Parent Cust Sales Currency],
        [SO Parent Cust Sales Currency Description],
        [SO Parent Cust One Time Account Group],
        [SO Parent Cust One Time Account Group Description],
        [SO Parent Cust One Time Indicator],
        [SO Parent Cust Industry Type],
        [SO Parent Cust Business Type],
        [SO Parent Cust DUNS Number],
        [SO Parent Cust DUNS Plus 4],
        [SO Parent Cust City Coordinates],
        [SO Parent Cust Tax Number 4 Code],
        [SO Parent Cust Attribute 3],
        [SO Parent Cust Attribute 3 Description],
        [SO Parent Cust E-Mail Address],
        [SO Parent Cust Mobile Number],
        [SO Parent Cust Search Term 2],
        [SO Parent Cust Street 2],
        [SO Parent Cust Street 3],
        [SO Parent Cust Street 4],
        [SO Parent Cust Street 5],
        [SO Parent Cust PO Box],
        [SO Parent Cust PO Box Postal Code],
        [SO Parent Cust PO Box City],
        [SO Parent Cust Region For PO Box],
        [SO Parent Cust PO Box Country],
        [SO Parent Cust Transport Zone],
        [SO Parent Cust Address Notes],
        [SO Parent Cust Tax Number 3 Code],
        [SO Parent Cust Tax Number 5 Code],
        [SO Parent Cust Industry Code 3],
        [SO Parent Cust Industry Code 3 Description],
        [SO Parent Cust Industry Code 4],
        [SO Parent Cust Industry Code 4 Description],
        [SO Parent Cust Industry Code 5],
        [SO Parent Cust Industry Code 5 Description],
        [SO Parent Cust Central Order Block For Customer],
        [SO Parent Cust Payment Block]
    )
     AS 
    SELECT 
    [CUST_KEY],
        [Customer ID],
        [Legacy Customer ID],
        [Customer Name],
        [Customer Line 2 Description],
        [Customer Country Code],
        [Customer Plant ID],
        [Customer Segment ID],
        [Customer Industry],
        [Customer Vendor ID],
        [Customer Group Code],
        [Customer Account Group Code],
        [Customer Title],
        [Customer Search Term],
        [Customer Street],
        [Customer City],
        [Customer Zip Code],
        [Customer State Code],
        [Customer Region Code],
        [Customer Telephone Number 1],
        [Customer Telephone Number 2],
        [Customer Fax Number Code],
        [Customer Tax Number 1 Code],
        [Customer Tax Number 2 Code],
        [Customer VAT Number Code],
        [Customer Credit Limit],
        [Customer Bonus Rate],
        [Customer Express Station],
        [Customer Transportation Zone],
        [Customer Printer Location Characteristics],
        [Customer Printer Region Characteristics],
        [Customer Printer Site Characteristics],
        [Customer Created Date],
        [Customer Created User ID],
        [Customer Updated Date],
        [Customer Updated User ID],
        [Customer Payment Terms Code],
        [Customer Sales Distribution],
        [Customer Order Block For Sales Area],
        [Customer Delivery Block For Sales Area],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Customer Corporate Group],
        [Customer Classification],
        [Customer Classification Description],
        [Customer Printer Location],
        [Customer Printer Site],
        [Customer Printer Region],
        [Customer Specific Field Label 01],
        [Customer Specific Field Label 02],
        [Customer Specific Field Label 03],
        [Customer Specific Field Label 04],
        [Customer Specific Field Label 05],
        [Customer Specific Field Label 06],
        [Customer Specific Field Label 07],
        [Customer Specific Field Label 08],
        [Customer Specific Field Label 09],
        [Customer Specific Field Label 10],
        [Customer Specific Field Label 11],
        [Customer Specific Field Label 12],
        [Customer Specific Field Label 13],
        [Customer Specific Field Label 14],
        [Customer Specific Field Label 15],
        [Customer Specific Field Label 16],
        [Customer Specific Field Label 17],
        [Customer Specific Field Label 18],
        [Customer Specific Field Label 19],
        [Customer Specific Field Label 20],
        [Customer Condition Group 1],
        [Customer Industry Code 1],
        [Customer Industry Code 2],
        [Customer Industry Description],
        [Customer Industry Code 1 Description],
        [Customer Industry Code 2 Description],
        [Customer Assignment to Hierarchy],
        [Customer Account Group Description],
        [Customer Region Description],
        [Customer Country Description],
        [Customer Transportation Zone Description],
        [Customer Plant Description],
        [Customer Condition Group Description],
        [Customer Cental Billing Block],
        [Customer Cental Billing Block Description],
        [Customer Central Delivery Block],
        [Customer Central Delivery Block Description],
        [Customer Deletion Indicator],
        [Customer Central Posting Block],
        [Customer Tax Jurisdiction],
        [Customer Central Sales Block],
        [Customer Central Deletion Indicator],
        [Customer Language Key],
        [Customer Trading Partner],
        [Customer Trading Partner Description],
        [Customer Annual Sales],
        [Customer Annual Sales Year],
        [Customer Sales Currency],
        [Customer Sales Currency Description],
        [Customer One Time Account Group],
        [Customer One Time Account Group Description],
        [Customer One Time Indicator],
        [Customer Industry Type],
        [Customer Business Type],
        [Customer DUNS Number],
        [Customer DUNS Plus 4],
        [Customer City Coordinates],
        [Customer Tax Number 4 Code],
        [Customer Attribute 3],
        [Customer Attribute 3 Description],
        [Customer E-Mail Address],
        [Customer Mobile Number],
        [Customer Search Term 2],
        [Customer Street 2],
        [Customer Street 3],
        [Customer Street 4],
        [Customer Street 5],
        [Customer PO Box],
        [Customer PO Box Postal Code],
        [Customer PO Box City],
        [Customer Region For PO Box],
        [Customer PO Box Country],
        [Customer Transport Zone],
        [Customer Address Notes],
        [Customer Tax Number 3 Code],
        [Customer Tax Number 5 Code],
        [Customer Industry Code 3],
        [Customer Industry Code 3 Description],
        [Customer Industry Code 4],
        [Customer Industry Code 4 Description],
        [Customer Industry Code 5],
        [Customer Industry Code 5 Description],
        [Customer Central Order Block For Customer],
        [Customer Payment Block]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D];