-- Auto Generated (Do not modify) 843E3893E36109F6A506FB89E3B08121B93767467FC592EDDD3ED37A515A27B7
CREATE VIEW [Propelis].[V_START_OF_MALFUNCTION_DATE] (
        [DATE_KEY],
        [Start Of Malfunction Date],
        [Start Of Malfunction Fiscal Year],
        [Start Of Malfunction Fiscal Period Number],
        [Start Of Malfunction Fiscal Period Code],
        [Start Of Malfunction Fiscal Quarter Number],
        [Start Of Malfunction Fiscal Quarter Code],
        [Start Of Malfunction Calendar Year],
        [Start Of Malfunction Calendar Month Number],
        [Start Of Malfunction Calendar Month Code],
        [Start Of Malfunction Calendar Month Description],
        [Start Of Malfunction Calendar Quarter Number],
        [Start Of Malfunction Calendar Quarter Code],
        [Start Of Malfunction Calendar Weekday Number],
        [Start Of Malfunction Calendar Weekday Name],
        [Start Of Malfunction Calendar Day In Month],
        [Start Of Malfunction Calendar Day In Year],
        [Start Of Malfunction Calendar Week],
        [Start Of Malfunction Calendar Month In Quarter Number],
        [Start Of Malfunction Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Start Of Malfunction Current Day Flag],
        [Start Of Malfunction Current Day Minus 1 Flag],
        [Start Of Malfunction Current Calendar Week Flag],
        [Start Of Malfunction Current Calendar Week Minus 1 Flag],
        [Start Of Malfunction Current Month Flag],
        [Start Of Malfunction Current Month Minus 1 Flag],
        [Start Of Malfunction Current Month Minus 12 Flag],
        [Start Of Malfunction Current Quarter Flag],
        [Start Of Malfunction Current Quarter Minus 1 Flag],
        [Start Of Malfunction Current Quarter Minus 4 Flag],
        [Start Of Malfunction Current Calendar Year Flag],
        [Start Of Malfunction Current Calendar Year Minus 1 Flag],
        [Start Of Malfunction Current Calendar Year Minus 2 Flag],
        [Start Of Malfunction Current Fiscal Year Flag],
        [Start Of Malfunction Current Fiscal Year Minus 1 Flag],
        [Start Of Malfunction Current Fiscal Year Minus 2 Flag],
        [Start Of Malfunction Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Start Of Malfunction Day In Fiscal Year],
        [Start Of Malfunction Date Is Weekday],
        [Start Of Malfunction Fiscal Week],
        [Start Of Malfunction Current Fiscal Week Flag],
        [Start Of Malfunction Current Fiscal Week Minus 1 Flag],
        [Start Of Malfunction Fiscal Weekday Number],
        [Start Of Malfunction Fiscal Weekday Name],
        [Start Of Malfunction Current Month Minus 2 Flag],
        [Start Of Malfunction Current Fiscal Week Minus 2 Flag],
        [Start Of Malfunction Current Fiscal Week Minus 6 Flag],
        [Start Of Malfunction Current Fiscal Week Minus 3 Flag],
        [Start Of Malfunction Current Fiscal Week Minus 4 Flag],
        [Start Of Malfunction Current Fiscal Week Minus 5 Flag],
        [Start Of Malfunction Current Fiscal Week Minus 7 Flag]
    ) AS 
    SELECT
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D]