-- Auto Generated (Do not modify) 95CB184D28FA2C61A638CAAFD7FF5604F2A098F9FCE8A762075FE7FC046C45CD
CREATE   VIEW [Propelis].[V_START_CONSTRAINT_DATE](
    [DATE_KEY]                                           ,
        [Start Constraint Date]                                  ,
        [Start Constraint Fiscal Year]                           ,
        [Start Constraint Fiscal Period Number]                  ,
        [Start Constraint Fiscal Period Code]                    ,
        [Start Constraint Fiscal Quarter Number]                 ,
        [Start Constraint Fiscal Quarter Code]                   ,
        [Start Constraint Calendar Year]                         ,
        [Start Constraint Calendar Month Number]                 ,
        [Start Constraint Calendar Month Code]                   ,
        [Start Constraint Calendar Month Description]            ,
        [Start Constraint Calendar Quarter Number]               ,
        [Start Constraint Calendar Quarter Code]                 ,
        [Start Constraint Calendar Weekday Number]               ,
        [Start Constraint Calendar Weekday Name]                 ,
        [Start Constraint Calendar Day In Month]                 ,
        [Start Constraint Calendar Day In Year]                  ,
        [Start Constraint Calendar Week]                         ,
        [Start Constraint Calendar Month In Quarter Number]      ,
        [Start Constraint Calendar Days In Month]                ,
        [ETL_SRC_SYS_CD]                                     ,
        [ETL_CREATED_TS]                                     ,
        [ETL_UPDTD_TS]                                       ,
        [Start Constraint Current Day Flag]                      ,
        [Start Constraint Current Day Minus 1 Flag]              ,
        [Start Constraint Current Calendar Week Flag]            ,
        [Start Constraint Current Calendar Week Minus 1 Flag]    ,
        [Start Constraint Current Month Flag]                    ,
        [Start Constraint Current Month Minus 1 Flag]            ,
        [Start Constraint Current Month Minus 12 Flag]           ,
        [Start Constraint Current Quarter Flag]                  ,
        [Start Constraint Current Quarter Minus 1 Flag]          ,
        [Start Constraint Current Quarter Minus 4 Flag]          ,
        [Start Constraint Current Calendar Year Flag]            ,
        [Start Constraint Current Calendar Year Minus 1 Flag]    ,
        [Start Constraint Current Calendar Year Minus 2 Flag]    ,
        [Start Constraint Current Fiscal Year Flag]              ,
        [Start Constraint Current Fiscal Year Minus 1 Flag]      ,
        [Start Constraint Current Fiscal Year Minus 2 Flag]      ,
        [Start Constraint Current Calendar Year Plus 1 Flag]     ,
        [Start Constraint Current Calendar Year Plus 2 Flag]                          ,
        [Start Constraint Day In Fiscal Year]                    ,
        [Start Constraint Date Is Weekday]                       ,
        [Start Constraint Fiscal Week]                           ,
        [Start Constraint Current Fiscal Week Flag]              ,
        [Start Constraint Current Fiscal Week Minus 1 Flag]      ,
        [Start Constraint Fiscal Weekday Number]                 ,
        [Start Constraint Fiscal Weekday Name]                   ,
        [Start Constraint Current Month Minus 2 Flag]            ,
        [Start Constraint Current Fiscal Week Minus 2 Flag]      ,
        [Start Constraint Current Fiscal Week Minus 6 Flag]      ,
        [Start Constraint Current Fiscal Week Minus 3 Flag]      ,
        [Start Constraint Current Fiscal Week Minus 4 Flag]      ,
        [Start Constraint Current Fiscal Week Minus 5 Flag]      ,
        [Start Constraint Current Fiscal Week Minus 7 Flag]
)AS
SELECT
    [DATE_KEY],
    [Date],
    [Date Fiscal Year],
    [FISCAL_PER_NUM],
    [Date Fiscal Period Code],
    [Date Fiscal Quarter Number],
    [Date Fiscal Quarter Code],
    [Date Calendar Year],
    [Date Calendar Month Number],
    [Date Calendar Month Code],
    [Date Calendar Month Desc],
    [CLNDR_QTR_NUM],
    [Date Calendar Quarter Code],
    [Date Calendar Weekday Number],
    [Date Calendar Weekday Name],
    [Date Calendar Day in Month],
    [Date Calendar Day in Year],
    [Date Calendar Week],
    [Date Calendar Month in Quarter Number],
    [Date Calendar Days in Month],
    [ETL_SRC_SYS_CD],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Date Current Day Flag],
    [Date Current Day Minus 1 Flag],
    [Date Current Calendar Week Flag],
    [Date Current Calendar Week Minus 1 Flag],
    [Date Current Month Flag],
    [Date Current Month Minus 1 Flag],
    [Date Current Month Minus 12 Flag],
    [Date Current Quarter Flag],
    [Date Current Quarter Minus 1 Flag],
    [Date Current Quarter Minus 4 Flag],
    [Date Current Calendar Year Flag],
    [Date Current Calendar Year Minus 1 Flag],
    [Date Current Calendar Year Minus 2 Flag],
    [Date Current Fiscal Year Flag],
    [Date Current Fiscal Year Minus 1 Flag],
    [Date Current Fiscal Year Minus 2 Flag],
    [Date Current Calendar Year Plus 1 Flag],
    [Date Current Fiscal Year Plus 1 Flag],
    [Date Day in Fiscal Year],
    [Date Date Is Weekday],
    [Date Fiscal Week],
    [Date Current Fiscal Week Flag],
    [Date Current Fiscal Week Minus 1 Flag],
    [Date Fiscal Weekday Number],
    [Date Fiscal Weekday Name],
    [Date Current Month Minus 2 Flag],
    [Date Current Fiscal Week Minus 2 Flag],
    [Date Current Fiscal Week Minus 6 Flag],
    [Date Current Fiscal Week Minus 3 Flag],
    [Date Current Fiscal Week Minus 4 Flag],
    [Date Current Fiscal Week Minus 5 Flag],
    [Date Current Fiscal Week Minus 7 Flag]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];