-- Auto Generated (Do not modify) A5F8AA37AF104255665EC270FC52DD9F04F42E91E0BF3E81AE92D120510298E8
CREATE   view [Propelis].[V_SUPPLIER_CUST] (
                 [CUST_KEY],
                 [Supplier Customer ID],
                 [Supplier Legacy Customer ID],
                 [Supplier Customer Name],
                 [Supplier Cust Line 2 Description],
                 [Supplier Cust Country Code],
                 [Supplier Cust Plant ID],
                 [Supplier Cust Segment ID],
                 [Supplier Cust Industry],
                 [Supplier Cust Vendor ID],
                 [Supplier Cust Customer Group Code],
                 [Supplier Cust Account Group Code],
                 [Supplier Cust Title],
                 [Supplier Cust Search Term],
                 [Supplier Cust Street],
                 [Supplier Cust City],
                 [Supplier Cust Zip Code],
                 [Supplier Cust State Code],
                 [Supplier Cust Region Code],
                 [Supplier Cust Telephone Number 1],
                 [Supplier Cust Telephone Number 2],
                 [Supplier Cust Fax Number Code],
                 [Supplier Cust Tax Number 1 Code],
                 [Supplier Cust Tax Number 2 Code],
                 [Supplier Cust VAT Number Code],
                 [Supplier Cust Credit Limit],
                 [Supplier Cust Bonus Rate],
                 [Supplier Cust Express Station],
                 [Supplier Cust Transportation Zone],
                 [Supplier Cust Printer Location Characteristics],
                 [Supplier Cust Printer Region Characteristics],
                 [Supplier Cust Printer Site Characteristics],
                 [Supplier Cust Customer Created Date],
                 [Supplier Cust Created User ID],
                 [Supplier Cust Customer Updated Date],
                 [Supplier Cust Updated User ID],
                 [Supplier Cust Payment Terms Code],
                 [Supplier Cust Sales Distribution],
                 [Supplier Cust Order Block For Sales Area],
                 [Supplier Cust Delivery Block For Sales Area],
                 [ETL_SRC_SYS_CD],
                 [ETL_EFFECTV_BEGIN_DATE],
                 [ETL_EFFECTV_END_DATE],
                 [ETL_CURR_RCD_IND],
                 [ETL_CREATED_TS],
                 [ETL_UPDTD_TS],
                 [Supplier Cust Corporate Group],
                 [Supplier Cust Classification],
                 [Supplier Cust Classification Description],
                 [Supplier Cust Printer Location],
                 [Supplier Cust Printer Site],
                 [Supplier Cust Printer Region],
                 [Supplier Cust Specific Field Label 01],
                 [Supplier Cust Specific Field Label 02],
                 [Supplier Cust Specific Field Label 03],
                 [Supplier Cust Specific Field Label 04],
                 [Supplier Cust Specific Field Label 05],
                 [Supplier Cust Specific Field Label 06],
                 [Supplier Cust Specific Field Label 07],
                 [Supplier Cust Specific Field Label 08],
                 [Supplier Cust Specific Field Label 09],
                 [Supplier Cust Specific Field Label 10],
                 [Supplier Cust Specific Field Label 11],
                 [Supplier Cust Specific Field Label 12],
                 [Supplier Cust Specific Field Label 13],
                 [Supplier Cust Specific Field Label 14],
                 [Supplier Cust Specific Field Label 15],
                 [Supplier Cust Specific Field Label 16],
                 [Supplier Cust Specific Field Label 17],
                 [Supplier Cust Specific Field Label 18],
                 [Supplier Cust Specific Field Label 19],
                 [Supplier Cust Specific Field Label 20],
                 [Supplier Cust Condition Group 1],
                 [Supplier Cust Industry Code 1],
                 [Supplier Cust Industry Code 2],
                 [Supplier Cust Industry Description],
                 [Supplier Cust Industry Code 1 Description],
                 [Supplier Cust Industry Code 2 Description],
                 [Supplier Cust Assignment to Hierarchy],
                 [Supplier Cust Account Group Description],
                 [Supplier Cust Region Description],
                 [Supplier Cust Country Description],
                 [Supplier Cust Transportation Zone Description],
                 [Supplier Cust Plant Description],
                 [Supplier Cust Condition Group Description],
                 [Supplier Cust Cental Billing Block],
                 [Supplier Cust Cental Billing Block Description],
                 [Supplier Cust Central Delivery Block],
                 [Supplier Cust Central Delivery Block Description],
                 [Supplier Cust Deletion Indicator],
                 [Supplier Cust Central Posting Block],
                 [Supplier Cust Tax Jurisdiction],
                 [Supplier Cust Central Sales Block],
                 [Supplier Cust Central Deletion Indicator],
                 [Supplier Cust Language Key],
                 [Supplier Cust Trading Partner],
                 [Supplier Cust Trading Partner Description],
                 [Supplier Cust Annual Sales],
                 [Supplier Cust Annual Sales Year],
                 [Supplier Cust Sales Currency],
                 [Supplier Cust Sales Currency Description],
                 [Supplier Cust One Time Account Group],
                 [Supplier Cust One Time Account Group Description],
                 [Supplier Cust One Time Indicator],
                 [Supplier Cust Industry Type],
                 [Supplier Cust Business Type],
                 [Supplier Cust DUNS Number],
                 [Supplier Cust DUNS Plus 4],
                 [Supplier Cust City Coordinates],
                 [Supplier Cust Tax Number 4 Code],
                 [Supplier Cust Attribute 3],
                 [Supplier Cust Attribute 3 Description],
                 [Supplier Cust E-Mail Address],
                 [Supplier Cust Mobile Number],
                 [Supplier Cust Search Term 2],
                 [Supplier Cust Street 2],
                 [Supplier Cust Street 3],
                 [Supplier Cust Street 4],
                 [Supplier Cust Street 5],
                 [Supplier Cust PO Box],
                 [Supplier Cust PO Box Postal Code],
                 [Supplier Cust PO Box City],
                 [Supplier Cust Region For PO Box],
                 [Supplier Cust PO Box Country],
                 [Supplier Cust Transport Zone],
                 [Supplier Cust Address Notes],
                 [Supplier Cust Tax Number 3 Code],
                 [Supplier Cust Tax Number 5 Code],
                 [Supplier Cust Industry Code 3],
                 [Supplier Cust Industry Code 3 Description],
                 [Supplier Cust Industry Code 4],
                 [Supplier Cust Industry Code 4 Description],
                 [Supplier Cust Industry Code 5],
                 [Supplier Cust Industry Code 5 Description],
                 [Supplier Cust Central Order Block For Customer],
                 [Supplier Cust Payment Block]


    )
     AS 
    SELECT 
    [CUST_KEY],
        [Customer ID],
        [Legacy Customer ID],
        [Customer Name],
        [Customer Line 2 Description],
        [Customer Country Code],
        [Customer Plant ID],
        [Customer Segment ID],
        [Customer Industry],
        [Customer Vendor ID],
        [Customer Group Code],
        [Customer Account Group Code],
        [Customer Title],
        [Customer Search Term],
        [Customer Street],
        [Customer City],
        [Customer Zip Code],
        [Customer State Code],
        [Customer Region Code],
        [Customer Telephone Number 1],
        [Customer Telephone Number 2],
        [Customer Fax Number Code],
        [Customer Tax Number 1 Code],
        [Customer Tax Number 2 Code],
        [Customer VAT Number Code],
        [Customer Credit Limit],
        [Customer Bonus Rate],
        [Customer Express Station],
        [Customer Transportation Zone],
        [Customer Printer Location Characteristics],
        [Customer Printer Region Characteristics],
        [Customer Printer Site Characteristics],
        [Customer Created Date],
        [Customer Created User ID],
        [Customer Updated Date],
        [Customer Updated User ID],
        [Customer Payment Terms Code],
        [Customer Sales Distribution],
        [Customer Order Block For Sales Area],
        [Customer Delivery Block For Sales Area],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Customer Corporate Group],
        [Customer Classification],
        [Customer Classification Description],
        [Customer Printer Location],
        [Customer Printer Site],
        [Customer Printer Region],
        [Customer Specific Field Label 01],
        [Customer Specific Field Label 02],
        [Customer Specific Field Label 03],
        [Customer Specific Field Label 04],
        [Customer Specific Field Label 05],
        [Customer Specific Field Label 06],
        [Customer Specific Field Label 07],
        [Customer Specific Field Label 08],
        [Customer Specific Field Label 09],
        [Customer Specific Field Label 10],
        [Customer Specific Field Label 11],
        [Customer Specific Field Label 12],
        [Customer Specific Field Label 13],
        [Customer Specific Field Label 14],
        [Customer Specific Field Label 15],
        [Customer Specific Field Label 16],
        [Customer Specific Field Label 17],
        [Customer Specific Field Label 18],
        [Customer Specific Field Label 19],
        [Customer Specific Field Label 20],
        [Customer Condition Group 1],
        [Customer Industry Code 1],
        [Customer Industry Code 2],
        [Customer Industry Description],
        [Customer Industry Code 1 Description],
        [Customer Industry Code 2 Description],
        [Customer Assignment to Hierarchy],
        [Customer Account Group Description],
        [Customer Region Description],
        [Customer Country Description],
        [Customer Transportation Zone Description],
        [Customer Plant Description],
        [Customer Condition Group Description],
        [Customer Cental Billing Block],
        [Customer Cental Billing Block Description],
        [Customer Central Delivery Block],
        [Customer Central Delivery Block Description],
        [Customer Deletion Indicator],
        [Customer Central Posting Block],
        [Customer Tax Jurisdiction],
        [Customer Central Sales Block],
        [Customer Central Deletion Indicator],
        [Customer Language Key],
        [Customer Trading Partner],
        [Customer Trading Partner Description],
        [Customer Annual Sales],
        [Customer Annual Sales Year],
        [Customer Sales Currency],
        [Customer Sales Currency Description],
        [Customer One Time Account Group],
        [Customer One Time Account Group Description],
        [Customer One Time Indicator],
        [Customer Industry Type],
        [Customer Business Type],
        [Customer DUNS Number],
        [Customer DUNS Plus 4],
        [Customer City Coordinates],
        [Customer Tax Number 4 Code],
        [Customer Attribute 3],
        [Customer Attribute 3 Description],
        [Customer E-Mail Address],
        [Customer Mobile Number],
        [Customer Search Term 2],
        [Customer Street 2],
        [Customer Street 3],
        [Customer Street 4],
        [Customer Street 5],
        [Customer PO Box],
        [Customer PO Box Postal Code],
        [Customer PO Box City],
        [Customer Region For PO Box],
        [Customer PO Box Country],
        [Customer Transport Zone],
        [Customer Address Notes],
        [Customer Tax Number 3 Code],
        [Customer Tax Number 5 Code],
        [Customer Industry Code 3],
        [Customer Industry Code 3 Description],
        [Customer Industry Code 4],
        [Customer Industry Code 4 Description],
        [Customer Industry Code 5],
        [Customer Industry Code 5 Description],
        [Customer Central Order Block For Customer],
        [Customer Payment Block]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTOMR_CUR_D];