-- Auto Generated (Do not modify) F1B04525824B2679129C86C6E68D348B99EB6BF11A05B717A71DB71068F5E796
CREATE  view [Propelis].[V_TECH_COMPLETION_DATE](
    [DATE_KEY],
[Tech Completion Date],
[Tech Completion Fiscal Year],
[Tech Completion Fiscal Period Number],
[Tech Completion Fiscal Period Code],
[Tech Completion Fiscal Quarter Number],
[Tech Completion Fiscal Quarter Code],
[Tech Completion Calendar Year],
[Tech Completion Calendar Month Number],
[Tech Completion Calendar Month Code],
[Tech Completion Calendar Month Description],
[Tech Completion Calendar Quarter Number],
[Tech Completion Calendar Quarter Code],
[Tech Completion Calendar Weekday Number],
[Tech Completion Calendar Weekday Name],
[Tech Completion Calendar Day In Month],
[Tech Completion Calendar Day In Year],
[Tech Completion Calendar Week],
[Tech Completion Calendar Month In Quarter Number],
[Tech Completion Calendar Days In Month],
[ETL_SRC_SYS_CD],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Tech Completion Current Day Flag],
[Tech Completion Current Day Minus 1 Flag],
[Tech Completion Current Calendar Week Flag],
[Tech Completion Current Calendar Week Minus 1 Flag],
[Tech Completion Current Month Flag],
[Tech Completion Current Month Minus 1 Flag],
[Tech Completion Current Month Minus 12 Flag],
[Tech Completion Current Quarter Flag],
[Tech Completion Current Quarter Minus 1 Flag],
[Tech Completion Current Quarter Minus 4 Flag],
[Tech Completion Current Calendar Year Flag],
[Tech Completion Current Calendar Year Minus 1 Flag],
[Tech Completion Current Calendar Year Minus 2 Flag],
[Tech Completion Current Fiscal Year Flag],
[Tech Completion Current Fiscal Year Minus 1 Flag],
[Tech Completion Current Fiscal Year Minus 2 Flag],
[Tech Completion Current Calendar Year Plus 1 Flag],
[Tech Completion Current Fiscal Year Plus 1 Flag],
[Tech Completion Day In Fiscal Year],
[Tech Completion Date Is Weekday],
[Tech Completion Fiscal Week],
[Tech Completion Current Fiscal Week Flag],
[Tech Completion Current Fiscal Week Minus 1 Flag],
[Tech Completion Fiscal Weekday Number],
[Tech Completion Fiscal Weekday Name],
[Tech Completion Current Month Minus 2 Flag],
[Tech Completion Current Fiscal Week Minus 2 Flag],
[Tech Completion Current Fiscal Week Minus 6 Flag],
[Tech Completion Current Fiscal Week Minus 3 Flag],
[Tech Completion Current Fiscal Week Minus 4 Flag],
[Tech Completion Current Fiscal Week Minus 5 Flag],
[Tech Completion Current Fiscal Week Minus 7 Flag]

) AS
SELECT 
    [DATE_KEY],
    [Date],
    [Date Fiscal Year],
    [FISCAL_PER_NUM],
    [Date Fiscal Period Code],
    [Date Fiscal Quarter Number],
    [Date Fiscal Quarter Code],
    [Date Calendar Year],
    [Date Calendar Month Number],
    [Date Calendar Month Code],
    [Date Calendar Month Desc],
    [CLNDR_QTR_NUM],
    [Date Calendar Quarter Code],
    [Date Calendar Weekday Number],
    [Date Calendar Weekday Name],
    [Date Calendar Day in Month],
    [Date Calendar Day in Year],
    [Date Calendar Week],
    [Date Calendar Month in Quarter Number],
    [Date Calendar Days in Month],
    [ETL_SRC_SYS_CD],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Date Current Day Flag],
    [Date Current Day Minus 1 Flag],
    [Date Current Calendar Week Flag],
    [Date Current Calendar Week Minus 1 Flag],
    [Date Current Month Flag],
    [Date Current Month Minus 1 Flag],
    [Date Current Month Minus 12 Flag],
    [Date Current Quarter Flag],
    [Date Current Quarter Minus 1 Flag],
    [Date Current Quarter Minus 4 Flag],
    [Date Current Calendar Year Flag],
    [Date Current Calendar Year Minus 1 Flag],
    [Date Current Calendar Year Minus 2 Flag],
    [Date Current Fiscal Year Flag],
    [Date Current Fiscal Year Minus 1 Flag],
    [Date Current Fiscal Year Minus 2 Flag],
    [Date Current Calendar Year Plus 1 Flag],
    [Date Current Fiscal Year Plus 1 Flag],
    [Date Day in Fiscal Year],
    [Date Date Is Weekday],
    [Date Fiscal Week],
    [Date Current Fiscal Week Flag],
    [Date Current Fiscal Week Minus 1 Flag],
    [Date Fiscal Weekday Number],
    [Date Fiscal Weekday Name],
    [Date Current Month Minus 2 Flag],
    [Date Current Fiscal Week Minus 2 Flag],
    [Date Current Fiscal Week Minus 6 Flag],
    [Date Current Fiscal Week Minus 3 Flag],
    [Date Current Fiscal Week Minus 4 Flag],
    [Date Current Fiscal Week Minus 5 Flag],
    [Date Current Fiscal Week Minus 7 Flag]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];