-- Auto Generated (Do not modify) FF3A5E1A3A1C8260B871CAB4F3F2B0BC70871205E12983D4CF699AFE301B1823
CREATE   VIEW [Propelis].[V_UNITIZATION_AGENT_VENDOR](
    [VNDR_KEY],
    [Unitization Agent Vendor ID],
    [Unitization Agent Vendor Name],
    [Unitization Agent Vendor Description],
    [Unitization Agent Vendor Account Group],
    [Unitization Agent Vendor Title],
    [Unitization Agent Vendor Search Term],
    [Unitization Agent Vendor Street],
    [Unitization Agent Vendor City Name],
    [Unitization Agent Vendor Zip Code],
    [Unitization Agent Vendor Country Code],
    [Unitization Agent Vendor State],
    [Unitization Agent Vendor Telephone Number 1 Code],
    [Unitization Agent Vendor Fax Number Code],
    [Unitization Agent Vendor Tax Number 1 Code],
    [Unitization Agent Vendor Tax Number 2 Code],
    [Unitization Agent Vendor VAT Number Code],
    [Unitization Agent Vendor Express Station],
    [Unitization Agent Vendor Transportation Zone],
    [Unitization Agent Vendor Industry],
    [Unitization Agent Vendor Created Date],
    [ETL_SRC_SYS_CD],
    [ETL_EFFECTV_BEGIN_DATE],
    [ETL_EFFECTV_END_DATE],
    [ETL_CURR_RCD_IND],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Unitization Agent Vendor Address Number],
    [Unitization Agent Vendor Account Group Description],
    [Unitization Agent Vendor Country Description],
    [Unitization Agent Vendor Region Description],
    [Unitization Agent Vendor Transportation Zone Description],
    [Unitization Agent Vendor Industry Description],
    [Unitization Agent Vendor Created By],
    [Unitization Agent Vendor Central Deletion Indicator],
    [Unitization Agent Vendor Central Posting Block],
    [Unitization Agent Vendor Central Purchasing Block],
    [Unitization Agent Vendor Language Key],
    [Unitization Agent Vendor Customer ID],
    [Unitization Agent Vendor One Time Account Indicator],
    [Unitization Agent Vendor One Time Account Reference Group],
    [Unitization Agent Vendor One Time Account Reference Group Desc],
    [Unitization Agent Vendor Trading Partner],
    [Unitization Agent Vendor Trading Partner Description],
    [Unitization Agent Vendor VAT Indicator],
    [Unitization Agent Vendor Industry Type],
    [Unitization Agent Vendor Business Type],
    [Unitization Agent Vendor Payment Block],
    [Unitization Agent Vendor Tax Jurisdiction],
    [Unitization Agent Vendor Tax Number 3 Code],
    [Unitization Agent Vendor Tax Number Type],
    [Unitization Agent Vendor Tax Type],
    [Unitization Agent Vendor Level 1],
    [Unitization Agent Vendor Level 2],
    [Unitization Agent Vendor Level 3],
    [Unitization Agent Vendor Level 4],
    [Unitization Agent Vendor Addressable],
    [Unitization Agent Tail Vendor],
    [Unitization Agent Vendor Normalized],
    [Unitization Agent Vendor Corporate Group],
    [Unitization Agent Vendor Account No Alternate Payee],
    [Unitization Agent Vendor Email Address]
)AS
SELECT 
    [VNDR_KEY],
    [Vendor ID],
    [Vendor Name],
    [Vendor Description],
    [Vendor Account Group],
    [Vendor Title],
    [Vendor Search Term],
    [Vendor Street],
    [Vendor City Name],
    [Vendor Zip Code],
    [Vendor Country Code],
    [Vendor State],
    [Vendor Telephone Number 1 Code],
    [Vendor Fax Number Code],
    [Vendor Tax Number 1 Code],
    [Vendor Tax Number 2 Code],
    [Vendor VAT Number Code],
    [Vendor Express Station],
    [Vendor Transportation Zone],
    [Vendor Industry],
    [Vendor Created Date],
    [ETL_SRC_SYS_CD],
    [ETL_EFFECTV_BEGIN_DATE],
    [ETL_EFFECTV_END_DATE],
    [ETL_CURR_RCD_IND],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Vendor Address Number],
    [Vendor Account Group Description],
    [Vendor Country Description],
    [Vendor Region Description],
    [Vendor Transportation Zone Description],
    [Vendor Industry Description],
    [Vendor Created By],
    [Vendor Central Deletion Indicator],
    [Vendor Central Posting Block],
    [Vendor Central Purchasing Block],
    [Vendor Language Key],
    [Vendor Customer ID],
    [Vendor One Time Account Indicator],
    [Vendor One Time Account Reference Group],
    [Vendor One Time Account Reference Group Desc],
    [Vendor Trading Partner],
    [Vendor Trading Partner Description],
    [Vendor VAT Indicator],
    [Vendor Industry Type],
    [Vendor Business Type],
    [Vendor Payment Block],
    [Vendor Tax Jurisdiction],
    [Vendor Tax Number 3 Code],
    [Vendor Tax Number Type],
    [Vendor Tax Type],
    [Vendor Level 1],
    [Vendor Level 2],
    [Vendor Level 3],
    [Vendor Level 4],
    [Vendor Addressable],
    [Tail Vendor],
    [Vendor Normalized],
    [Vendor Corporate Group],
    [Vendor Account No Alternate Payee],
    [Vendor Email Address]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_VENDOR_CUR_D];