CREATE TABLE [dbo].[AWS_SERVICE_ORDERS_EDW] (

	[UUID] varchar(255) NULL, 
	[SERVICE_ORDER] varchar(255) NULL, 
	[WHITE_PAPER_LOGGING] varchar(255) NULL, 
	[TOTAL_SAVING] decimal(13,3) NULL, 
	[DATE_STAMP] datetime2(0) NULL
);