CREATE TABLE [dbo].[EDW_T_D_FI_ASSETHR_CUR_D] (

	[ASSET_KEY] int NOT NULL, 
	[Asset Company Code] varchar(max) NULL, 
	[Main Asset Number] varchar(max) NULL, 
	[Asset Subnumber] varchar(max) NULL, 
	[Asset Class] varchar(max) NULL, 
	[Asset Class Description] varchar(max) NULL, 
	[Asset Description] varchar(max) NULL, 
	[Asset Quantity] decimal(13,3) NULL, 
	[Asset Base UOM] varchar(max) NULL, 
	[Asset Capitalization Date] date NULL, 
	[Asset First Acquistion Fiscal Year] int NULL, 
	[Asset First Acquistion Fiscal Period] int NULL, 
	[Asset Deactivation Date] date NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Name Of Person Who Created The Asset] varchar(max) NULL, 
	[Date On Which Asset Record was Created] date NULL, 
	[Asset Value Date Of The First Posting] date NULL, 
	[Asset Inventory Number] varchar(max) NULL, 
	[Additional Asset Description] varchar(max) NULL, 
	[Asset Serial Number] varchar(max) NULL, 
	[Asset Cost Center] varchar(max) NULL, 
	[Asset Plant] varchar(max) NULL
);