CREATE TABLE [dbo].[EDW_T_D_PRS_WBSELEM_CUR_D-BACK-UP] (

	[WBS_ELEMNT_KEY] int NOT NULL, 
	[WBS Project Definition Internal] bigint NULL, 
	[WBS Project Definition] varchar(max) NULL, 
	[WBS Project Object Number] varchar(max) NULL, 
	[WBS Element Internal] bigint NULL, 
	[WBS Element] varchar(max) NULL, 
	[WBS Element Object Number] varchar(max) NULL, 
	[WBS Element Description] varchar(max) NULL, 
	[WBS Project Type] varchar(max) NULL, 
	[WBS Project Priority] varchar(max) NULL, 
	[WBS Project Short Description] varchar(max) NULL, 
	[WBS Project Personnel Responsible] varchar(max) NULL, 
	[WBS Project Short ID] varchar(max) NULL, 
	[WBS Application Number] int NULL, 
	[WBS Responsible Cost Center] varchar(max) NULL, 
	[WBS Request Cost Center] varchar(max) NULL, 
	[WBS Request Company Code] varchar(max) NULL, 
	[WBS Basic Start Date] date NULL, 
	[WBS Basic Finish Date] date NULL, 
	[WBS Forecast Start Date] date NULL, 
	[WBS Forecast Finish Date] date NULL, 
	[WBS Actual Start Date] date NULL, 
	[WBS Actual Finish Date] date NULL, 
	[WBS Basic Duration] int NULL, 
	[WBS Basic UOM] varchar(max) NULL, 
	[WBS Forecast Duration] int NULL, 
	[WBS Forecast UOM] varchar(max) NULL, 
	[WBS Actual Duration] int NULL, 
	[WBS Actual UOM] varchar(max) NULL, 
	[WBS Basic Earlist Start Date] date NULL, 
	[WBS Basic Earlist Finish Date] date NULL, 
	[WBS Basic Latest Start Date] date NULL, 
	[WBS Basic Latest Finish Date] date NULL, 
	[WBS Forecast Earliest Start Date] date NULL, 
	[WBS Forecast Earliest Finish Date] date NULL, 
	[WBS Forecast Latest Start Date] date NULL, 
	[WBS Forecast Latest Finish Date] date NULL, 
	[WBS Tentative Actual Start Date] date NULL, 
	[WBS Tentative Actual Finish Date] date NULL, 
	[WBS Calendar] varchar(max) NULL, 
	[WBS Controlling Area] varchar(max) NULL, 
	[WBS Company Code] varchar(max) NULL, 
	[WBS Business Area] varchar(max) NULL, 
	[WBS Functional Area] varchar(max) NULL, 
	[WBS Profit Center] varchar(max) NULL, 
	[WBS Object Class] varchar(max) NULL, 
	[WBS Currency] varchar(max) NULL, 
	[WBS Tax Jurisdiction] varchar(max) NULL, 
	[WBS Sub Project] varchar(max) NULL, 
	[WBS Plant] varchar(max) NULL, 
	[WBS Location] varchar(max) NULL, 
	[WBS Equipment] varchar(max) NULL, 
	[WBS Functional Location] varchar(max) NULL, 
	[WBS Change Number] varchar(max) NULL, 
	[WBS Reference Element] varchar(max) NULL, 
	[WBS Element Created By] varchar(max) NULL, 
	[WBS Created On] date NULL, 
	[WBS Changed By] varchar(max) NULL, 
	[WBS Changed On] date NULL, 
	[WBS Level in Project Hierarchy] int NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[WBS Responsible Person Name] varchar(max) NULL, 
	[WBS Appropriate Project Number] int NULL, 
	[WBS Language Key] varchar(max) NULL, 
	[WBS Project Type Description] varchar(max) NULL, 
	[WBS Project Priority Description] varchar(max) NULL, 
	[WBS Factory Calendar Description] varchar(max) NULL, 
	[WBS Controlling Area Description] varchar(max) NULL, 
	[WBS Company Description] varchar(max) NULL, 
	[WBS Business Area Description] varchar(max) NULL, 
	[WBS Object Class Description] varchar(max) NULL, 
	[WBS Currency Description] varchar(max) NULL, 
	[WBS Plant Description] varchar(max) NULL, 
	[WBS POC Weight] decimal(8,0) NULL, 
	[WBS Progress Version] varchar(max) NULL, 
	[WBS Plan Measurement Method] varchar(max) NULL, 
	[WBS Plan Reference Object] varchar(max) NULL, 
	[WBS Actual Measurement Method] varchar(max) NULL, 
	[WBS Actual Reference Object] varchar(max) NULL, 
	[WBS System Status] varchar(max) NULL, 
	[WBS User Status] varchar(max) NULL, 
	[WBS Project Description] varchar(max) NULL, 
	[WBS Project Responsible Person Number] varchar(max) NULL, 
	[WBS Project Responsible Person Name] varchar(max) NULL, 
	[WBS Project Company Code] varchar(max) NULL, 
	[WBS Project Company Description] varchar(max) NULL, 
	[WBS Project Profit Center] varchar(max) NULL, 
	[WBS Project Plant ID] varchar(max) NULL, 
	[WBS Project Plant Description] varchar(max) NULL, 
	[WBS Project Functional Area] varchar(max) NULL, 
	[WBS Project Customer Number] varchar(max) NULL, 
	[WBS Project Customer Name] varchar(max) NULL, 
	[WBS Project Controlling Area] varchar(max) NULL, 
	[WBS Project Controlling Area Description] varchar(max) NULL, 
	[WBS Project Location] varchar(max) NULL, 
	[WBS Project Currency] varchar(max) NULL, 
	[WBS Project Business Area] varchar(max) NULL, 
	[WBS Project Business Area Description] varchar(max) NULL, 
	[WBS Project Factory Calendar] varchar(max) NULL, 
	[WBS Project Factory Calendar Description] varchar(max) NULL, 
	[WBS Project Time Unit] varchar(max) NULL, 
	[WBS Project Forecast Start Date] date NULL, 
	[WBS Project Forecast Finish Date] date NULL, 
	[WBS Project Created By] varchar(max) NULL, 
	[WBS Project Created Date] date NULL, 
	[WBS Project Changed By] varchar(max) NULL, 
	[WBS Project Changed On] date NULL, 
	[WBS Project System Status] varchar(max) NULL, 
	[WBS Project User Status] varchar(max) NULL, 
	[WBS Project Start Date] date NULL, 
	[WBS Project Finish Date] date NULL, 
	[WBS Project Last Basic Scheduling Date] date NULL, 
	[WBS Last Forecast Scheduling Date] date NULL
);