CREATE TABLE [dbo].[EDW_T_F_SAL_SALSPLN_CUR_D] (

	[CMPNY_KEY] int NOT NULL, 
	[SEG_KEY] int NOT NULL, 
	[CUST_KEY] int NOT NULL, 
	[SALES_PLAN_DATE_KEY] int NOT NULL, 
	[SALES_PLAN_AMT] decimal(18,3) NULL, 
	[SALES_PLAN_DISCNT] decimal(18,3) NULL, 
	[SALES_PLAN_NET_AMT] decimal(18,3) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);