CREATE TABLE [dbo].[EDW_T_D_MST_COSTELM_CUR_D] (

	[COST_ELEMNT_KEY] int NOT NULL, 
	[COST_ELEMNT_ID] varchar(10) NULL, 
	[CHART_OF_ACCTS] varchar(4) NULL, 
	[COST_ELEMNT_NAME] varchar(20) NULL, 
	[COST_ELEMNT_DESC] varchar(40) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[CHART_OF_ACCTS_DESC] varchar(50) NULL
);