CREATE TABLE [dbo].[EDW_T_D_MST_VENDOR_CUR_D-BACK-UP] (

	[VNDR_KEY] int NOT NULL, 
	[Vendor ID] varchar(max) NULL, 
	[Vendor Name] varchar(max) NULL, 
	[Vendor Description] varchar(max) NULL, 
	[Vendor Account Group] varchar(max) NULL, 
	[Vendor Title] varchar(max) NULL, 
	[Vendor Search Term] varchar(max) NULL, 
	[Vendor Street] varchar(max) NULL, 
	[Vendor City Name] varchar(max) NULL, 
	[Vendor Zip Code] varchar(max) NULL, 
	[Vendor Country Code] varchar(max) NULL, 
	[Vendor State] varchar(max) NULL, 
	[Vendor Telephone Number 1 Code] varchar(max) NULL, 
	[Vendor Fax Number Code] varchar(max) NULL, 
	[Vendor Tax Number 1 Code] varchar(max) NULL, 
	[Vendor Tax Number 2 Code] varchar(max) NULL, 
	[Vendor VAT Number Code] varchar(max) NULL, 
	[Vendor Express Station] varchar(max) NULL, 
	[Vendor Transportation Zone] varchar(max) NULL, 
	[Vendor Industry] varchar(max) NULL, 
	[Vendor Created Date] date NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Vendor Address Number] varchar(max) NULL, 
	[Vendor Account Group Description] varchar(max) NULL, 
	[Vendor Country Description] varchar(max) NULL, 
	[Vendor Region Description] varchar(max) NULL, 
	[Vendor Transportation Zone Description] varchar(max) NULL, 
	[Vendor Industry Description] varchar(max) NULL, 
	[Vendor Created By] varchar(max) NULL, 
	[Vendor Central Deletion Indicator] varchar(max) NULL, 
	[Vendor Central Posting Block] varchar(max) NULL, 
	[Vendor Central Purchasing Block] varchar(max) NULL, 
	[Vendor Language Key] varchar(max) NULL, 
	[Vendor Customer ID] varchar(max) NULL, 
	[Vendor One Time Account Indicator] varchar(max) NULL, 
	[Vendor One Time Account Reference Group] varchar(max) NULL, 
	[Vendor One Time Account Reference Group Desc] varchar(max) NULL, 
	[Vendor Trading Partner] varchar(max) NULL, 
	[Vendor Trading Partner Description] varchar(max) NULL, 
	[Vendor VAT Indicator] varchar(max) NULL, 
	[Vendor Industry Type] varchar(max) NULL, 
	[Vendor Business Type] varchar(max) NULL, 
	[Vendor Payment Block] varchar(max) NULL, 
	[Vendor Tax Jurisdiction] varchar(max) NULL, 
	[Vendor Tax Number 3 Code] varchar(max) NULL, 
	[Vendor Tax Number Type] varchar(max) NULL, 
	[Vendor Tax Type] varchar(max) NULL, 
	[Vendor Level 1] varchar(max) NULL, 
	[Vendor Level 2] varchar(max) NULL, 
	[Vendor Level 3] varchar(max) NULL, 
	[Vendor Level 4] varchar(max) NULL, 
	[Vendor Addressable] varchar(max) NULL, 
	[Tail Vendor] varchar(max) NULL, 
	[Vendor Normalized] varchar(max) NULL, 
	[Vendor Corporate Group] varchar(max) NULL, 
	[Vendor Account No Alternate Payee] varchar(max) NULL, 
	[Vendor Email Address] varchar(max) NULL
);