CREATE TABLE [dbo].[EDW_T_D_MST_EQUIPMT_CUR_D] (

	[EQUIP_KEY] int NOT NULL, 
	[EQUIP] varchar(18) NULL, 
	[EQUIP_DESC] varchar(40) NULL, 
	[EQUIP_CTGRY] varchar(1) NULL, 
	[WGHT_OF_OBJ] decimal(13,3) NULL, 
	[UNIT_OF_WGHT] varchar(3) NULL, 
	[WARRANTY_END_DATE] date NULL, 
	[NOTE] varchar(30) NULL, 
	[OBJ_NUM] varchar(22) NULL, 
	[MATRL] varchar(18) NULL, 
	[SERIAL_NUM] varchar(18) NULL, 
	[SIZE] varchar(18) NULL, 
	[DATE_LAST_GOODS_MOVMNT] date NULL, 
	[AUTH_GROUP_ORIGIN] varchar(1) NULL, 
	[EQUIP_DATA_EXISTS] varchar(1) NULL, 
	[SERIALIZATION_DATA] varchar(1) NULL, 
	[EQSI_EXISTS] varchar(1) NULL, 
	[STK_CHK] varchar(1) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[STK_TYP_OF_GOODS_MOVEMNT] varchar(2) NULL, 
	[PLNT] varchar(4) NULL, 
	[STOR_LOC] varchar(4) NULL, 
	[SPCL_STK_IND] varchar(1) NULL, 
	[SYS_STATUS] varchar(250) NULL
);