CREATE TABLE [dbo].[EDW_T_D_MST_PLNTMAT_CUR_D] (

	[PLNT_MATRL_KEY] int NOT NULL, 
	[Plant Material Material ID] varchar(max) NULL, 
	[Plant Material Plant ID] varchar(max) NULL, 
	[Plant Material Maintenance Status] varchar(max) NULL, 
	[Plant Material Purchasing Group] varchar(max) NULL, 
	[Plant Material MRP Type] varchar(max) NULL, 
	[Plant Material MRP Controller] varchar(max) NULL, 
	[Plant Material Procurement Type] varchar(max) NULL, 
	[Plant Material Export Import Group] varchar(max) NULL, 
	[Plant Material Profit Center ID] varchar(max) NULL, 
	[Plant Material Production Storage Location] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Plant Material Planned Delivery Time in Days] int NULL, 
	[Plant Material Goods Receipt Processing Time in Days] int NULL, 
	[Plant Material Lot Size] varchar(max) NULL, 
	[Plant Material Production Supervisor] varchar(max) NULL, 
	[Plant Material Commodity Code] varchar(max) NULL, 
	[Plant Material Storage Location for External Procurement] varchar(max) NULL, 
	[Plant Material Production Scheduling Profile] varchar(max) NULL, 
	[Plant Material Maximum Storage Period] decimal(5,0) NULL, 
	[Plant Material Time Unit] varchar(max) NULL, 
	[Plant Material Availability Check] varchar(max) NULL, 
	[Plant Material Costing Lot Size] decimal(13,3) NULL, 
	[Plant Material Planning Strategy Group] varchar(max) NULL, 
	[Plant Material Special Procurement Type] varchar(max) NULL, 
	[Plant Material Plant Description] varchar(max) NULL, 
	[Plant Material Purchasing Group Description] varchar(max) NULL, 
	[Plant Material MRP Type Description] varchar(max) NULL, 
	[Plant Material MRP Controller Description] varchar(max) NULL, 
	[Plant Material Procurement Type Description] varchar(max) NULL, 
	[Plant Material Export Import Group Description] varchar(max) NULL, 
	[Plant Material Production Storage Location Description] varchar(max) NULL, 
	[Plant Material Lot Size Description] varchar(max) NULL, 
	[Plant Material Production Supervisor Description] varchar(max) NULL, 
	[Plant Material Commodity Description] varchar(max) NULL, 
	[Plant Material Storage Location for External Procurement Description] varchar(max) NULL, 
	[Plant Material Production Scheduling Profile Description] varchar(max) NULL, 
	[Plant Material Availability Check Description] varchar(max) NULL, 
	[Plant Material Planning Strategy Group Description] varchar(max) NULL, 
	[Plant Material Special Procurement Type Description] varchar(max) NULL, 
	[Plant Material Re Order Point] decimal(13,3) NULL, 
	[Plant Material In House Production Time] decimal(3,0) NULL, 
	[SCHLG_MRGN_KEY] varchar(max) NULL, 
	[Plant Material PPC Planning Calendar] varchar(max) NULL, 
	[Plant Material Valuation Category] varchar(max) NULL, 
	[Plant Material Valuation Category Description] varchar(max) NULL, 
	[Plant Specific Material Status] varchar(max) NULL, 
	[Plant Specific Material Status Description] varchar(max) NULL, 
	[Plant Material ABC Indicator] varchar(max) NULL, 
	[Plant Material ABC Indicator Description] varchar(max) NULL, 
	[Plant Material Critical Part Indicator] varchar(max) NULL, 
	[Plant Material UOI] varchar(max) NULL, 
	[Plant Material Assembly Scrap In Pct] decimal(5,2) NULL, 
	[Plant Material Safety Stock] decimal(13,3) NULL, 
	[Plant Material Max Stock Level] decimal(13,3) NULL, 
	[Plant Material PO Qty Rounding] decimal(13,3) NULL, 
	[Plant Material Individual Collective Req Indicator] varchar(max) NULL, 
	[Plant Material Overdelivery Tolerance Limit] decimal(3,1) NULL, 
	[Plant Material Underdelivery Tolerance Limit] decimal(3,1) NULL, 
	[Plant Material Replenishment Lead Time In Days] decimal(3,0) NULL, 
	[Plant Material Country Of Origin] varchar(max) NULL, 
	[Plant Material Country Of Origin Description] varchar(max) NULL, 
	[Plant Material Individual Collective Requirement Description] varchar(max) NULL, 
	[Plant Material Costing Special Procurement Type] varchar(max) NULL, 
	[Plant Material Costing Special Procurement Type Description] varchar(max) NULL, 
	[Plant Material Do Not Cost] varchar(max) NULL, 
	[Plant Material Level Deletion Flag] varchar(max) NULL, 
	[Plant Material Replacement Part] varchar(max) NULL, 
	[Plant Material Replacement Part Description] varchar(max) NULL, 
	[Plant Material Freight Group] varchar(max) NULL, 
	[Plant Material Freight Group Description] varchar(max) NULL, 
	[Plant Material Serial Number Profile] varchar(max) NULL, 
	[Plant Material Serial Number Profile Description] varchar(max) NULL, 
	[Plant Material Distribution Profile Of Material In Plant] varchar(max) NULL, 
	[Plant Material Distribution Profile Of Material In Plant Description] varchar(max) NULL
);