CREATE TABLE [dbo].[EDW_T_F_SAL_INVSTSO_CUR_D] (

	[MATRL_KEY] int NOT NULL, 
	[PLNT_KEY] int NOT NULL, 
	[STOR_LOC_KEY] int NOT NULL, 
	[BATCH_NUM] varchar(10) NOT NULL, 
	[SPCL_STK_IND] varchar(1) NOT NULL, 
	[SALES_ORDER_KEY] int NOT NULL, 
	[SALES_ORDER_ITM_NUM] varchar(10) NOT NULL, 
	[CMPNY_KEY] int NULL, 
	[SEG_KEY] int NULL, 
	[SALES_AREA_KEY] int NULL, 
	[CUST_KEY] int NULL, 
	[YR] int NULL, 
	[PER] int NULL, 
	[QTY_UNRSTRD] decimal(13,3) NULL, 
	[QTY_IN_QUAL_INSPTN] decimal(13,3) NULL, 
	[QTY_BLCKD] decimal(13,3) NULL, 
	[QTY_UNRSTRD_USE_STK] decimal(13,3) NULL, 
	[QTY_IN_QUAL_INSPTN_PREV_PER] decimal(13,3) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);