CREATE TABLE [dbo].[EDW_T_D_HR_PERSBAR_CUR_D] (

	[PERSONEL_SUB_AREA_KEY] int NOT NULL, 
	[PERSONEL_SUB_AREA_DESC] varchar(50) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[PERSONEL_AREA] varchar(4) NULL, 
	[PERSONEL_SUB_AREA] varchar(4) NULL
);