CREATE TABLE [dbo].[EDW_T_D_MST_GENLDGR_CUR_D] (

	[GL_KEY] int NOT NULL, 
	[General Ledger Short Description] varchar(max) NULL, 
	[General Ledger Search Matchcode] varchar(max) NULL, 
	[General Ledger Group Account Number] varchar(max) NULL, 
	[General Ledger P L Statement Account Type] varchar(max) NULL, 
	[General Ledger Functional Area Description] varchar(max) NULL, 
	[General Ledger Functional Area] varchar(max) NULL, 
	[General Ledger Account Group Description] varchar(max) NULL, 
	[General Ledger Chart Of Accounts Description] varchar(max) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[General Ledger Account Blocked For Posting] varchar(max) NULL, 
	[General Ledger Account Blocked For Creation] varchar(max) NULL, 
	[General Ledger Account Marked For Deletion] varchar(max) NULL, 
	[General Ledger Account Group] varchar(max) NULL, 
	[General Ledger Account Created By] varchar(max) NULL, 
	[General Ledger Account Created Date] varchar(max) NULL, 
	[General Ledger Account Is Balance Sheet] varchar(max) NULL, 
	[General Ledger Description] varchar(max) NULL, 
	[Chart Of General Ledger Account] varchar(max) NULL, 
	[General Ledger Account] varchar(max) NULL, 
	[GL_CD] varchar(max) NULL
);