CREATE TABLE [dbo].[EDW_T_D_MST_CUSULPT_CUR_D] (

	[CUST_UNLOADING_PNT_KEY] int NOT NULL, 
	[CUST_CD] varchar(10) NULL, 
	[UNLOADING_PNT] varchar(25) NULL, 
	[SEQAL_NUM_FOR_UNLOADING_POINTS] int NULL, 
	[CUSTOMERS_FACTORY_CLNDR] varchar(2) NULL, 
	[TAX_CLSFTN_DESC] varchar(3) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);