CREATE TABLE [dbo].[EDW_T_D_MST_PERSONL_CUR_D] (

	[PERSONEL_KEY] int NOT NULL, 
	[Personnel Number] varchar(max) NULL, 
	[Personnel Company Code] varchar(max) NULL, 
	[Personnel Plant ID] varchar(max) NULL, 
	[Personnel Cost Center ID] varchar(max) NULL, 
	[Personnel Success Factors ID] varchar(max) NULL, 
	[Personnel Employee First Name] varchar(max) NULL, 
	[Personnel Employee Last Name] varchar(max) NULL, 
	[Personnel Employee Full Name] varchar(max) NULL, 
	[Personnel Employee Status Indicator] varchar(max) NULL, 
	[Personnel Employment Start Date] date NULL, 
	[Personnel Employment End Date] date NULL, 
	[Personnel Employee Group ID] varchar(max) NULL, 
	[Personnel Employee Group Description] varchar(max) NULL, 
	[Personnel Employee SubGroup ID] varchar(max) NULL, 
	[Personnel Employee SubGroup Description] varchar(max) NULL, 
	[Personnel Employee Telephone 1] varchar(max) NULL, 
	[Personnel Employee Telephone 2] varchar(max) NULL, 
	[EMAIL_ADDR] varchar(max) NULL, 
	[Personnel Created Date] date NULL, 
	[Personnel Created User ID] varchar(max) NULL, 
	[Personnel Updated Date] date NULL, 
	[Personnel Updated User ID] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Personnel Company Description] varchar(max) NULL, 
	[Personnel Plant Description] varchar(max) NULL
);