CREATE TABLE [dbo].[EDW_T_D_MST_ACTTYPE_CUR_D] (

	[ACTIVITY_TYP_KEY] int NOT NULL, 
	[ACTIVITY_TYP_ID] varchar(6) NULL, 
	[ACTIVITY_TYP_DESC] varchar(40) NULL, 
	[ACTIVITY_TYP_DESC_2] varchar(40) NULL, 
	[CONTROLLING_AREA] varchar(3) NULL, 
	[ACTIVITY_UNIT] varchar(4) NULL, 
	[ACTIVITY_TYP_CTGRY] varchar(1) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[CONTROLLING_AREA_DESC] varchar(25) NULL, 
	[ACTIVITY_TYP_CTGRY_DESC] varchar(60) NULL
);