CREATE TABLE [dbo].[EDW_T_D_MST_CUSCRED_CUR_D] (

	[CUST_CREDIT_KEY] int NOT NULL, 
	[Customer Credit Number] varchar(max) NULL, 
	[Customer Credit Control Area] varchar(max) NULL, 
	[Customer Credit Limit] varchar(max) NULL, 
	[Customer Credit Total Receivables] varchar(max) NULL, 
	[Customer Credit Account] varchar(max) NULL, 
	[Customer Credit Group Description] varchar(max) NULL, 
	[Customer Credit Currency Description] varchar(max) NULL, 
	[Current Record Indicator of Customer Credit] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Cust Sales Area Credit Control Area Description] varchar(max) NULL, 
	[Customer Credit Rep Group Description] varchar(max) NULL, 
	[Customer Credit Risk Category Description] varchar(max) NULL, 
	[Customer Credit Recommended Credit Limit] varchar(max) NULL, 
	[Customer Credit Changed By] varchar(max) NULL, 
	[Customer Credit Changed On] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[Customer Credit Group] varchar(max) NULL, 
	[Customer Credit Last Payment Amount] varchar(max) NULL, 
	[Customer Credit Last Payment Date] varchar(max) NULL, 
	[Customer Credit Currency] varchar(max) NULL, 
	[Customer Credit Payment Index] varchar(max) NULL, 
	[Customer Credit Rating] varchar(max) NULL, 
	[Customer Credit Rep Group] varchar(max) NULL, 
	[Customer Credit Exceeded On Date] varchar(max) NULL, 
	[Customer Credit Blocked] varchar(max) NULL, 
	[Customer Credit Risk Category] varchar(max) NULL, 
	[Customer Credit Info Number] varchar(max) NULL, 
	[Customer Credit Last External Review Date] varchar(max) NULL
);