CREATE TABLE [dbo].[EDW_T_D_MST_DISPCTGY_CUR_D] (

	[DISPUTE_TYP_CTGRY_KEY] int NOT NULL, 
	[DISPUTE_TYP] varchar(4) NULL, 
	[DISPUTE_CTGRY] varchar(4) NULL, 
	[DISPUTE_CTGRY_DESC] varchar(60) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);