CREATE TABLE [dbo].[EDW_T_F_SAL_PRDDLIM_CUR_D] (

	[DATE_KEY] int NOT NULL, 
	[PLNT_KEY] int NOT NULL, 
	[SEG_KEY] int NOT NULL, 
	[BRAND_OWNER_CUST_KEY] int NOT NULL, 
	[MATRL_KEY] int NOT NULL, 
	[G_CYLINDER_TYP] varchar(50) NOT NULL, 
	[QTY] decimal(18,2) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);