CREATE TABLE [dbo].[EDW_T_D_MST_WORKCTR_CUR_D] (

	[WRK_CNTR_KEY] int NOT NULL, 
	[Work Center ID] varchar(8) NULL, 
	[Work Center Plant ID] varchar(4) NULL, 
	[Work Center Object ID] int NULL, 
	[Work Center Object Type] varchar(2) NULL, 
	[Work Center Category] varchar(4) NULL, 
	[Work Center Location] varchar(10) NULL, 
	[Work Center Person Responsible] varchar(3) NULL, 
	[STD_VAL_KEY] varchar(4) NULL, 
	[Work Center Usage Code] varchar(3) NULL, 
	[Work Center Capacity ID] int NULL, 
	[Work Center Supply Area] varchar(10) NULL, 
	[Work Center Deletion Flag] varchar(1) NULL, 
	[Work Center Locked Status] varchar(1) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Work Center Description] varchar(40) NULL, 
	[Work Center Category Description] varchar(20) NULL, 
	[Work Center Person Responsible Name] varchar(40) NULL, 
	[Work Center Control Key] varchar(4) NULL, 
	[Work Center Storage Location Storage Resource] varchar(4) NULL, 
	[Work Center User Name Term] varchar(12) NULL, 
	[Work Center User Name GRND] varchar(12) NULL, 
	[Work Center Changed On Date Term] date NULL, 
	[Work Center Changed On Date GRND] date NULL, 
	[Work Center Changed On Date] date NULL, 
	[Work Center Plant Description] varchar(30) NULL, 
	[Work Center Object Type Description] varchar(60) NULL, 
	[Work Center Location Description] varchar(40) NULL, 
	[Work Center Standard Value Description] varchar(30) NULL, 
	[Work Center Usage Description] varchar(30) NULL, 
	[Work Center Supply Area Description] varchar(40) NULL, 
	[Work Center Control Description] varchar(40) NULL, 
	[Work Center Storage Location Description] varchar(40) NULL
);