CREATE TABLE [dbo].[EDW_T_D_MST_MATSALS_CUR_D] (

	[MATRL_SALES_KEY] int NOT NULL, 
	[Material Sales ID] varchar(max) NULL, 
	[Material Sales Organization] varchar(max) NULL, 
	[Material Sales Distribution Channel] varchar(max) NULL, 
	[Material Sales Statistics Group] varchar(max) NULL, 
	[Material Sales Item Category Group] varchar(max) NULL, 
	[Material Sales Account Assignment Group] varchar(max) NULL, 
	[Material Sales Delivering Plant] varchar(max) NULL, 
	[Material Sales Pricing Group] varchar(max) NULL, 
	[Material Sales Commission Group] varchar(max) NULL, 
	[Material Sales Group 1] varchar(max) NULL, 
	[Material Sales Group 2] varchar(max) NULL, 
	[Material Sales Group 3] varchar(max) NULL, 
	[Material Sales Group 4] varchar(max) NULL, 
	[Material Sales Group 5] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Material Sales Organization Description] varchar(max) NULL, 
	[Material Sales Distribution Channel Description] varchar(max) NULL, 
	[Material Sales Statistics Group Description] varchar(max) NULL, 
	[Material Sales Item Category Group Description] varchar(max) NULL, 
	[Material Sales Account Assignment Group Description] varchar(max) NULL, 
	[Material Sales Pricing Group Description] varchar(max) NULL, 
	[Material Sales Commission Group Description] varchar(max) NULL, 
	[Material Sales Group 1 Description] varchar(max) NULL, 
	[Material Sales Group 2 Description] varchar(max) NULL, 
	[Material Sales Group 3 Description] varchar(max) NULL, 
	[Material Sales Group 4 Description] varchar(max) NULL, 
	[Material Sales Group 5 Description] varchar(max) NULL, 
	[Material Sales Product Hierarchy] varchar(max) NULL, 
	[Material Sales Product Hierarchy Description] varchar(max) NULL, 
	[Material Sales Level6 Product Category Code] varchar(max) NULL, 
	[Material Sales Level6 Product Category Description] varchar(max) NULL, 
	[Material Sales Level5 Product Category Code] varchar(max) NULL, 
	[Material Sales Level5 Product Category Code Description] varchar(max) NULL, 
	[Material Sales Level4 Product Category Code] varchar(max) NULL, 
	[Material Sales Level4 Product Category Code Description] varchar(max) NULL, 
	[Material Sales Level3 Sub Family Code] varchar(max) NULL, 
	[Material Sales Level3 Sub Family Description] varchar(max) NULL, 
	[Material Sales Level2 Family Code] varchar(max) NULL, 
	[Material Sales Level2 Family Code Description] varchar(max) NULL, 
	[Material Sales Level1 Class Code] varchar(max) NULL, 
	[Material Sales Level1 Class Description] varchar(max) NULL, 
	[Material Sales Text] varchar(max) NULL, 
	[SALES_UNIT] varchar(max) NULL, 
	[CASH_DISCNT_IND] varchar(max) NULL, 
	[DISTRBN_CHAIN_SPECIFIC_MATRL_ST] varchar(max) NULL, 
	[DISTR_CHAIN_SPECIFIC_MATRL_STAT] varchar(max) NULL, 
	[PRICING_REF_MATRL] varchar(max) NULL
);