CREATE TABLE [dbo].[EDW_T_F_FI_CUSTCNT_CUR_D] (

	[CUST_CONTACT_GUID] varchar(32) NOT NULL, 
	[MAIN_CUST_CONTACT_KEY] int NULL, 
	[BIZ_PRTNR_KEY] int NULL, 
	[COLLECTION_SEG_KEY] int NULL, 
	[COLLECTION_SPECIALIST_KEY] int NULL, 
	[CUST_CONTACT_DATE_KEY] int NULL, 
	[CREATED_ON_DATE_KEY] int NULL, 
	[LAST_CHANGED_ON_DATE_KEY] int NULL, 
	[NUM_OF_DISPUTE_CASES] int NULL, 
	[NUM_OF_PROMISE_TO_PAY] int NULL, 
	[NUM_OF_RESUBMISSIONS] int NULL, 
	[NUM_OF_NOTES] int NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);