CREATE TABLE [dbo].[EDW_T_D_HY_GLACTHZ_CUR_D] (

	[General Ledger ID Hierarchy Group] varchar(max) NULL, 
	[GL_CD] varchar(max) NULL, 
	[CHART_OF_ACCTS] varchar(max) NULL, 
	[FUNCTNL_AREA] varchar(max) NULL, 
	[General Ledger Leaf Level HH] int NULL, 
	[General Ledger Level 0 ID HH] varchar(max) NULL, 
	[General Ledger Level 0 Description HH] varchar(max) NULL, 
	[General Ledger Level 1 ID HH] varchar(max) NULL, 
	[General Ledger Level 1 Description HH] varchar(max) NULL, 
	[General Ledger Level 2 ID HH] varchar(max) NULL, 
	[General Ledger Level 2 Description HH] varchar(max) NULL, 
	[General Ledger Level 3 ID HH] varchar(max) NULL, 
	[General Ledger Level 3 Description HH] varchar(max) NULL, 
	[General Ledger Level 4 ID HH] varchar(max) NULL, 
	[General Ledger Level 4 Description HH] varchar(max) NULL, 
	[General Ledger Level 5 ID HH] varchar(max) NULL, 
	[General Ledger Level 5 Description HH] varchar(max) NULL, 
	[General Ledger Level 6 ID HH] varchar(max) NULL, 
	[General Ledger Level 6 Description HH] varchar(max) NULL, 
	[General Ledger Level 1 NODEID] varchar(max) NULL, 
	[General Ledger Level 1 IOBJNM] varchar(max) NULL, 
	[General Ledger Level 1 NODENAME] varchar(max) NULL, 
	[General Ledger Level 2 NODEID] varchar(max) NULL, 
	[General Ledger Level 2 IOBJNM] varchar(max) NULL, 
	[General Ledger Level 2 NODENAME] varchar(max) NULL, 
	[General Ledger Level 3 NODEID] varchar(max) NULL, 
	[General Ledger Level 3 IOBJNM] varchar(max) NULL, 
	[General Ledger Level 3 NODENAME] varchar(max) NULL, 
	[General Ledger Level 4 NODEID] varchar(max) NULL, 
	[General Ledger Level 4 IOBJNM] varchar(max) NULL, 
	[General Ledger Level 4 NODENAME] varchar(max) NULL, 
	[General Ledger Level 5 NODEID] varchar(max) NULL, 
	[General Ledger Level 5 IOBJNM] varchar(max) NULL, 
	[General Ledger Level 5 NODENAME] varchar(max) NULL, 
	[General Ledger Level 6 NODEID] varchar(max) NULL, 
	[General Ledger Level 6 IOBJNM] varchar(max) NULL, 
	[General Ledger Level 6 NODENAME] varchar(max) NULL, 
	[Functional_GL_Key] varchar(8000) NULL, 
	[GLACTHZ_KEY] varchar(max) NULL
);