CREATE TABLE [dbo].[EDW_T_D_PP_PURORDL_CUR_D] (

	[PURCHS_ORDER_ITM_KEY] int NOT NULL, 
	[Purchase Order ID] varchar(max) NULL, 
	[Purchase Order Item ID] varchar(max) NULL, 
	[PO Company Code] varchar(max) NULL, 
	[PO Purchasing Document Category] varchar(max) NULL, 
	[PO Purchasing Document Type] varchar(max) NULL, 
	[PO Status] varchar(max) NULL, 
	[PO Statistical Date] datetime2(0) NULL, 
	[PO Delivery Date] datetime2(0) NULL, 
	[PO Created On] datetime2(0) NULL, 
	[PO Created By] varchar(max) NULL, 
	[PO Vendor] varchar(max) NULL, 
	[PO Purchasing Organization] varchar(max) NULL, 
	[PO Purchasing Group] varchar(max) NULL, 
	[PO Currency] varchar(max) NULL, 
	[PO Exchange Rate] decimal(9,5) NULL, 
	[PO Invoicing Party] varchar(max) NULL, 
	[PO Document Date] datetime2(0) NULL, 
	[PO Terms Of Payment] varchar(max) NULL, 
	[PO Incoterms] varchar(max) NULL, 
	[PO Deletion Indicator] varchar(max) NULL, 
	[PO Short Text] varchar(max) NULL, 
	[PO Material] varchar(max) NULL, 
	[PO Material 2] varchar(max) NULL, 
	[PO Material Group] varchar(max) NULL, 
	[PO Plant] varchar(max) NULL, 
	[PO Storage Location] varchar(max) NULL, 
	[PO Target Quantity] decimal(13,3) NULL, 
	[PO Quantity] decimal(13,3) NULL, 
	[PO Unit] varchar(max) NULL, 
	[PO Net Order Price] decimal(11,2) NULL, 
	[PO Net Order Value] decimal(13,2) NULL, 
	[PO Is PO Open] varchar(max) NULL, 
	[PO Quantity Open Goods Receipt Total] decimal(13,3) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[PO Account Assignment Category] varchar(max) NULL, 
	[PO Account Assignment Category Description] varchar(max) NULL, 
	[PO Number of Principal Purchase Agreement] varchar(max) NULL, 
	[PO Deletion Indicator in Purchasing Document] varchar(max) NULL, 
	[PO Delivery Completed Indicator] varchar(max) NULL, 
	[PO Final Invoice Indicator] varchar(max) NULL, 
	[PO Goods Receipt Non Valuated] varchar(max) NULL, 
	[PO Indicator GR Based Invoice Verification] varchar(max) NULL, 
	[PO Incoterms Part 1] varchar(max) NULL, 
	[PO Incoterms Part 2] varchar(max) NULL, 
	[PO Indicator Update Info Record] varchar(max) NULL, 
	[PO Period Indicator for Shelf Life Expiration Date] varchar(max) NULL, 
	[PO Item Category in Purchasing Document] varchar(max) NULL, 
	[PO Requisition Number] varchar(max) NULL, 
	[PO Revision Level] varchar(max) NULL, 
	[PO Shipping Instructions] varchar(max) NULL, 
	[PO Stock Type] varchar(max) NULL, 
	[PO Tax On Sales Purchases Code] varchar(max) NULL, 
	[PO Material Number Used by Vendor] varchar(max) NULL, 
	[PO Goods Receipt Processing Time in Days] int NULL, 
	[PO Minimum Remaining Shelf Life] int NULL, 
	[PO Overdelivery Tolerance Limit] int NULL, 
	[PO Planned Delivery Time in Days] int NULL, 
	[PO Underdelivery Tolerance Limit] decimal(3,1) NULL, 
	[PO Purchasing Document Processing State] varchar(max) NULL, 
	[PO International Article Number EAN UPC] varchar(max) NULL, 
	[PO Goods Receipt Indicator] varchar(max) NULL, 
	[PO Invoice Receipt Indicator] varchar(max) NULL, 
	[PO Order Price Unit Purchasing] varchar(max) NULL, 
	[PO Base Unit Of Measure] varchar(max) NULL, 
	[PO Name Of Requisitioner Requester] varchar(max) NULL, 
	[PO Change Document Responsible Person] varchar(max) NULL, 
	[PO Change Document Creation Date] date NULL, 
	[PO Item Category Description] varchar(max) NULL, 
	[PO Purchasing Document Category Description] varchar(max) NULL, 
	[PO Purchasing Document Type Description] varchar(max) NULL, 
	[PO Purchasing Organization Description] varchar(max) NULL, 
	[PO Purchasing Group Description] varchar(max) NULL, 
	[PO Currency Description] varchar(max) NULL, 
	[PO Terms of Payment Description] varchar(max) NULL, 
	[PO Incoterms Description] varchar(max) NULL, 
	[PO Material Group Description] varchar(max) NULL, 
	[PO Plant Description] varchar(max) NULL, 
	[PO Storage Location Description] varchar(max) NULL, 
	[PO Incoterms Part 1 Description] varchar(max) NULL, 
	[PO Indicator Update Info Record Description] varchar(max) NULL, 
	[PO Shipping Instructions Description] varchar(max) NULL, 
	[PO Stock Type Description] varchar(max) NULL, 
	[PO Tax On Sales Purchases Code Description] varchar(max) NULL, 
	[PO First Name Of Requester] varchar(max) NULL, 
	[PO Last Name Of Requester] varchar(max) NULL, 
	[PO First Name Of Change Document Responsible] varchar(max) NULL, 
	[PO Last Name Of Change Document Responsible] varchar(max) NULL, 
	[PO Item Category In Purchasing Order] varchar(max) NULL, 
	[PO Incompletion Indicator] varchar(max) NULL, 
	[PO STO Supplying Plant] varchar(max) NULL, 
	[PO Principle Purchase Agreement Item Number] varchar(max) NULL, 
	[PO Price Unit] int NULL, 
	[PO Is ZARI Output Type] varchar(max) NULL, 
	[PO ZARI Status] varchar(max) NULL, 
	[PO ZARI Status Description] varchar(max) NULL, 
	[PO Validity Period Start Date] date NULL, 
	[PO Validity Period End Date] date NULL, 
	[PO Delivery Address Name 1] varchar(max) NULL, 
	[PO Delivery Address Name 2] varchar(max) NULL, 
	[PO Delivery Address House Number] varchar(max) NULL, 
	[PO Delivery Address Street] varchar(max) NULL, 
	[PO Delivery Address District] varchar(max) NULL, 
	[PO Delivery Address Postal Code] varchar(max) NULL, 
	[PO Delivery Address City] varchar(max) NULL, 
	[PO Delivery Address Country] varchar(max) NULL, 
	[PO Delivery Address Region] varchar(max) NULL, 
	[PO Order Acknowledgment Number] varchar(max) NULL
);