CREATE TABLE [dbo].[EDW_T_F_FI_ACCTPAY_CUR_D] (

	[CMPNY_KEY] int NOT NULL, 
	[FISCAL_YR] int NOT NULL, 
	[DOCMT_HDR_NUM] varchar(10) NOT NULL, 
	[LDGR_PSTNG_ITM_NUM] varchar(6) NOT NULL, 
	[LDGR_CD] varchar(2) NOT NULL, 
	[VNDR_KEY] int NULL, 
	[DOCMT_LINE_ITM_NUM] int NULL, 
	[CLEARING_DOCMT_NUM] varchar(10) NULL, 
	[CLEARING_DATE_KEY] int NULL, 
	[ASSIGN_NUM] varchar(18) NULL, 
	[SPCL_GL_TRNSCTN_TYP] varchar(1) NULL, 
	[SPCL_GL_IND] varchar(1) NULL, 
	[DOCMT_DATE_KEY] int NULL, 
	[PSTNG_DATE_KEY] int NULL, 
	[DOCMT_CRNCY_KEY] int NULL, 
	[CMPNY_CRNCY_KEY] int NULL, 
	[GROUP_CRNCY_KEY] int NULL, 
	[PSTNG_PER] int NULL, 
	[DOCMT_TYP] varchar(2) NULL, 
	[REF_NUM] varchar(16) NULL, 
	[INVC_REF_NUM] varchar(10) NULL, 
	[RSN_CD] varchar(3) NULL, 
	[RSN_CD_DESC] varchar(40) NULL, 
	[CMPNY_CRNCY_AMT] decimal(23,2) NULL, 
	[DOCMT_CRNCY_AMT] decimal(23,2) NULL, 
	[GROUP_CRNCY_AMT] decimal(23,2) NULL, 
	[PSTNG_KEY] varchar(2) NULL, 
	[DEBIT_CREDIT_IND] varchar(1) NULL, 
	[GL_KEY] int NULL, 
	[BSLINE_DUE_DATE_KEY] int NULL, 
	[PYMT_TRMS] varchar(4) NULL, 
	[CASH_DISCOUNTS_DAY_1] decimal(3,0) NULL, 
	[CASH_DISCOUNTS_DAY_2] decimal(3,0) NULL, 
	[NET_PAYMENTS_TERM_PER] decimal(3,0) NULL, 
	[REF_KEY_FOR_LINE_ITM] varchar(20) NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[SEG_KEY] int NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[SPCL_GL_IND_DESC] varchar(30) NULL, 
	[LDGR_CD_DESC] varchar(40) NULL, 
	[DOCMT_TYP_DESC] varchar(30) NULL, 
	[PSTNG_DESC] varchar(20) NULL, 
	[TRMS_OF_PYMT_DESC] varchar(50) NULL, 
	[TAX_CD_ON_PURCHS] varchar(2) NULL, 
	[SPCL_GL_ACCTS_ASSIGN_NUM] varchar(18) NULL, 
	[ENTERED_BY] varchar(12) NULL
);