CREATE TABLE [dbo].[EDW_T_D_MST_COLLSEG_CUR_D] (

	[COLLECTION_SEG_KEY] int NOT NULL, 
	[COLLECTION_SEG] varchar(10) NULL, 
	[COLLECTION_SEG_WAS_RELSD] varchar(1) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);