CREATE TABLE [dbo].[EDW_T_F_SAL_TMCONFN_CUR_D] (

	[CONTROLLING_AREA] varchar(4) NOT NULL, 
	[DOCMT_NUM] varchar(10) NOT NULL, 
	[PSTNG_ROW] int NOT NULL, 
	[FISCAL_YR] int NULL, 
	[VRSN_HDR] varchar(3) NULL, 
	[BIZ_TRNSCTN_HDR] varchar(4) NULL, 
	[DOCMT_DATE_KEY] int NULL, 
	[PSTNG_DATE_KEY] int NULL, 
	[DOCMT_TYP] varchar(2) NULL, 
	[USR_NAME] varchar(12) NULL, 
	[PER] int NULL, 
	[PLNT_KEY] int NULL, 
	[COST_CNTR_KEY] int NULL, 
	[ACTIVITY_TYP_KEY] int NULL, 
	[VAL_TYP] varchar(2) NULL, 
	[VRSN] varchar(3) NULL, 
	[BIZ_TRNSCTN] varchar(4) NULL, 
	[PERSONEL_NUM_KEY] int NULL, 
	[ACTIVITY_UOM] varchar(3) NULL, 
	[ACTIVITY_QTY] date NULL, 
	[ACTUAL_WRK_UOM] varchar(3) NULL, 
	[ACTUAL_WRK] date NULL, 
	[ACTUAL_WRK_IN_HRS] date NULL, 
	[ACTUAL_WRK_IN_HRS_UOM] varchar(3) NULL, 
	[OBJ_NUM] varchar(22) NULL, 
	[DESC] varchar(50) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[PROFT_CNTR_KEY] int NULL
);