CREATE TABLE [dbo].[EDW_T_D_HR_JOBSBFN_CUR_D] (

	[JOB_SUB_FUNCTION_KEY] int NOT NULL, 
	[JOB_SUB_FUNCTION] varchar(4) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[JOB_SUB_FUNCTION_DESC] varchar(50) NULL, 
	[JOB_FUNCTION] varchar(2) NULL, 
	[JOB_FUNCTION_DESC] varchar(50) NULL
);