CREATE TABLE [dbo].[EDW_T_D_MST_PRTHRCY_CUR_D] (

	[PRDT_HIERCHY_CD] varchar(18) NOT NULL, 
	[PRDT_HIERCHY_DESC] varchar(40) NULL, 
	[LEVEL6_PRDT_CTGRY_CD] varchar(18) NULL, 
	[LEVEL6_PRDT_CTGRY_DESC] varchar(40) NULL, 
	[LEVEL5_PRDT_CTGRY_CD] varchar(18) NULL, 
	[LEVEL5_PRDT_CTGRY_DESC] varchar(40) NULL, 
	[LEVEL4_PRDT_CTGRY_CD] varchar(18) NULL, 
	[LEVEL4_PRDT_CTGRY_DESC] varchar(40) NULL, 
	[LEVEL3_SUB_FAMILY_CD] varchar(18) NULL, 
	[LEVEL3_SUB_FAMILY_DESC] varchar(40) NULL, 
	[LEVEL2_FAMILY_CD] varchar(18) NULL, 
	[LEVEL2_FAMILY_DESC] varchar(40) NULL, 
	[LEVEL1_CLASS_CD] varchar(18) NULL, 
	[LEVEL1_CLASS_DESC] varchar(40) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);