CREATE TABLE [dbo].[EDW_T_F_CO_COPABGT_CUR_D] (

	[CRNCY_TYP] varchar(2) NOT NULL, 
	[CRNCY_TYP_DESC] varchar(30) NULL, 
	[RCD_TYP] varchar(1) NOT NULL, 
	[VRSN] varchar(3) NOT NULL, 
	[PROFT_SEG] bigint NOT NULL, 
	[SUBNUMBER] int NOT NULL, 
	[DOCMT_NUM] varchar(10) NOT NULL, 
	[FISCAL_YR_PER_BLK] int NOT NULL, 
	[CREATED_ON_DATE] date NULL, 
	[CREATED_BY] varchar(12) NULL, 
	[FISCAL_YR] int NULL, 
	[SOLDTO_CUST_KEY] int NULL, 
	[MATRL_KEY] int NULL, 
	[FOREIGN_CRNCY_KEY] int NULL, 
	[CRNCY_KEY] int NULL, 
	[CUST_CMPNY_KEY] int NULL, 
	[CONTROLLING_AREA] varchar(4) NULL, 
	[CONTROLLING_AREA_DESC] varchar(25) NULL, 
	[PLNT_KEY] int NULL, 
	[SALES_AREA_KEY] int NULL, 
	[CUST_SALES_AREA_KEY] int NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[TM_CREATED] decimal(16,0) NULL, 
	[INDUS_KEY] varchar(4) NULL, 
	[INDUS_DESC] varchar(20) NULL, 
	[SALES_DISTR] varchar(6) NULL, 
	[SALES_DISTR_DESC] varchar(20) NULL, 
	[CUST_GROUP] varchar(2) NULL, 
	[CUST_GROUP_DESC] varchar(20) NULL, 
	[CNTRY_KEY] varchar(3) NULL, 
	[CUST_GROUP_2] varchar(3) NULL, 
	[CUST_GROUP_2_DESC] varchar(20) NULL, 
	[MATRL_GROUP] varchar(9) NULL, 
	[MATRL_GROUP_DESC] varchar(20) NULL, 
	[POSTAL_CD] varchar(10) NULL, 
	[REGN] varchar(3) NULL, 
	[SALES_OFFC] varchar(4) NULL, 
	[SALES_OFFC_DESC] varchar(20) NULL, 
	[SALES_GROUP] varchar(3) NULL, 
	[SALES_GROUP_DESC] varchar(20) NULL, 
	[CUST_ACCT_ASSIGN_GROUP] varchar(2) NULL, 
	[CUST_ACCT_ASSIGN_GROUP_DESC] varchar(20) NULL, 
	[CITY_COORDINATES] varchar(10) NULL, 
	[COMM_GROUP] varchar(2) NULL, 
	[COMM_GROUP_DESC] varchar(20) NULL, 
	[PRDT_HIERCHY_CD] varchar(18) NULL, 
	[INDUS_CD_1] varchar(10) NULL, 
	[INDUS_CD_1_DESC] varchar(20) NULL, 
	[INDUS_CD_2] varchar(10) NULL, 
	[INDUS_CD_2_DESC] varchar(20) NULL, 
	[ACCTNG_CLERK] varchar(2) NULL, 
	[ACCTNG_CLERK_DESC] varchar(30) NULL, 
	[SUB_BRAND] int NULL, 
	[BASE_UOM] varchar(3) NULL, 
	[SALES_QTY] decimal(15,3) NULL, 
	[REVNU_AMT] decimal(18,2) NULL, 
	[LABOR_COST_AMT] decimal(18,2) NULL, 
	[MATRL_COST_AMT] decimal(18,2) NULL, 
	[OVERHEAD_COST_AMT] decimal(18,2) NULL, 
	[OUTSIDE_PURCHASES_AMT] decimal(18,2) NULL, 
	[MATRL_SALES_KEY] int NULL, 
	[CMPNY_KEY] int NULL, 
	[SALES_ORGZTN] varchar(4) NULL, 
	[SALES_ORG_DESC] varchar(20) NULL, 
	[DISTRBN_CHNL] varchar(2) NULL, 
	[DISTRBN_CHNL_DESC] varchar(20) NULL, 
	[DIVISION] varchar(2) NULL, 
	[DIVISION_DESC] varchar(20) NULL, 
	[BRAND] int NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[BASE_UOM_DESC] varchar(30) NULL, 
	[GENERAL_AND_ADMIN_AMT] decimal(18,2) NULL, 
	[SELLING_EXPENSE_AMT] decimal(18,2) NULL, 
	[MCHINE_COSTS_AMT] decimal(18,2) NULL, 
	[SEG_KEY] int NULL
);