CREATE TABLE [dbo].[EDW_T_D_MST_BUPARTG_CUR_D] (

	[BIZ_PRTNR_RTG_KEY] int NOT NULL, 
	[BIZ_PRTNR_NUM] varchar(10) NULL, 
	[TM_STAMP_FOR_RATINGS_OBSOLET] varchar(14) NULL, 
	[DIFFERENTIATION_CRITERION] varchar(10) NULL, 
	[RTG_VALID_TO_DATE] date NULL, 
	[RTG_PROC] varchar(10) NULL, 
	[RTG_PROC_DESC] varchar(60) NULL, 
	[RTG_VALID_FROM_DATE] date NULL, 
	[RTG_ALLOWED] varchar(1) NULL, 
	[RTG] varchar(10) NULL, 
	[RTG_DESC] varchar(60) NULL, 
	[TREND] varchar(2) NULL, 
	[TREND_DESC] varchar(60) NULL, 
	[RTG_ENTERED_ON_DATE] date NULL, 
	[STD_PROC] varchar(1) NULL, 
	[TEXT_FOR_RATINGS] varchar(60) NULL, 
	[UKM_DNB_PAYDEX_SCORE] varchar(2) NULL, 
	[UKM_DELINQUENCY_CLASS] varchar(1) NULL, 
	[UKM_FAILURE_CLASS] varchar(1) NULL, 
	[UKM_DNB_RTG] varchar(5) NULL, 
	[UKM_BAD_DEBT_IND] varchar(1) NULL, 
	[UKM_QUICK_RTO] varchar(5) NULL, 
	[UKM_CURR_RTO] varchar(5) NULL, 
	[UKM_DNB_RAM_SCORE] varchar(5) NULL, 
	[UKM_YEARS_IN_BIZ] varchar(3) NULL, 
	[UKM_DNB_RECOMMENDED_CREDIT_LMT] varchar(20) NULL, 
	[COFACE_ID] varchar(60) NULL, 
	[DNB_DUNS_ID] varchar(60) NULL, 
	[ID_TYP] varchar(6) NULL, 
	[ID_TYP_DESC] varchar(40) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);