CREATE TABLE [dbo].[EDW_T_D_MST_CRDTSEG_CUR_D] (

	[CREDIT_SEG_KEY] int NOT NULL, 
	[CREDIT_SEG] varchar(10) NULL, 
	[NAME_OF_CREDIT_SEG] varchar(50) NULL, 
	[CREDIT_SEG_CRNCY] varchar(5) NULL, 
	[CHK_CREDIT_LMT_VALIDITY] varchar(1) NULL, 
	[EXCHG_RT_TYP] varchar(4) NULL, 
	[MAIN_CREDIT_SEG_IND] varchar(1) NULL, 
	[ADDITIVE_CONTRIBUTION_TO_MAIN_C] varchar(1) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);