CREATE TABLE [dbo].[EDW_T_D_MST_PROFCTR_CUR_D] (

	[PROFT_CNTR_KEY] int NOT NULL, 
	[PROFT_CNTR_ID] varchar(10) NULL, 
	[PROFT_CNTR_DESC] varchar(40) NULL, 
	[LGCY_PROFT_CNTR_CD] varchar(10) NULL, 
	[LGCY_PROFT_CNTR_DESC] varchar(60) NULL, 
	[CONTROLLING_AREA_ID] varchar(4) NULL, 
	[USR_RESPNSBLE_ID] varchar(12) NULL, 
	[PERSON_RESPNSBLE] varchar(20) NULL, 
	[LANG_TYP_CD] varchar(1) NULL, 
	[SEG_ID] varchar(10) NULL, 
	[ADRESS_LINE_1] varchar(35) NULL, 
	[ADRESS_LINE_2] varchar(35) NULL, 
	[CITY_NAME] varchar(35) NULL, 
	[DISTR_NAME] varchar(35) NULL, 
	[POSTAL_CD] varchar(10) NULL, 
	[CNTRY_CD] varchar(3) NULL, 
	[REGN_CD] varchar(3) NULL, 
	[CREATED_DATE] date NULL, 
	[CREATED_USR_ID] varchar(12) NULL, 
	[UPDTD_DATE] date NULL, 
	[UPDTD_USR_ID] varchar(12) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[CMPNY_CD] varchar(4) NULL, 
	[PROFT_CNTR_LONG_DESC] varchar(20) NULL, 
	[PROFT_CNTR_SHORT_DESC] varchar(20) NULL, 
	[LOCK_IND] varchar(1) NULL, 
	[NAME_1] varchar(35) NULL, 
	[PROFT_CNTR_AREA] varchar(12) NULL, 
	[GENERIC_MAST_RCD_STATUS] varchar(1) NULL, 
	[STATUS_DESC] varchar(60) NULL, 
	[CONTROLLING_AREA_DESC] varchar(25) NULL, 
	[CNTRY_DESC] varchar(15) NULL, 
	[CMPNY_DESC] varchar(25) NULL, 
	[TAX_JRSDCTN] varchar(15) NULL, 
	[VALID_TO_DATE] date NULL, 
	[VALID_FROM_DATE] date NULL
);