CREATE TABLE [dbo].[EDW_T_F_PP_SPNDANL2_CUR_D] (

	[CMPNY_KEY] int NOT NULL, 
	[DOCMT_NUM] varchar(10) NOT NULL, 
	[DOCMT_ITM_NUM] varchar(3) NOT NULL, 
	[YR] varchar(4) NOT NULL, 
	[DOCMT_TYP] varchar(2) NULL, 
	[DOCMT_DATE_KEY] int NULL, 
	[PSTNG_DATE_KEY] int NULL, 
	[VNDR_KEY] int NULL, 
	[COST_CNTR_KEY] int NULL, 
	[GL_KEY] int NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[SEG_KEY] int NULL, 
	[PLNT_KEY] int NULL, 
	[PURCHS_ORDER_ITM_KEY] int NULL, 
	[PSTNG_KEY] varchar(2) NULL, 
	[ACCT_TYP] varchar(1) NULL, 
	[DEBIT_CREDIT_IND] varchar(1) NULL, 
	[CMPNY_CRNCY_AMT] decimal(18,3) NULL, 
	[DOCMT_CRNCY_AMT] decimal(18,3) NULL, 
	[GROUP_CRNCY_AMT] decimal(18,3) NULL, 
	[QTY] decimal(18,3) NULL, 
	[BASE_UOM] varchar(3) NULL, 
	[REF_DOCMT_NUM] varchar(16) NULL, 
	[DOCMT_HDR_TEXT] varchar(25) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[MATRL_KEY] int NULL, 
	[DOCMT_TYP_DESC] varchar(20) NULL, 
	[PSTNG_KEY_DESC] varchar(20) NULL, 
	[ACCT_TYP_DESC] varchar(60) NULL, 
	[TAX_ON_SALES_PURCHASES_CD] varchar(2) NULL, 
	[DOCMT_CRNCY_KEY] int NULL, 
	[CMPNY_CRNCY_KEY] int NULL, 
	[GROUP_CRNCY_KEY] int NULL, 
	[CUST_KEY] int NULL, 
	[ASSET_NUM] varchar(12) NULL, 
	[SALES_ORDER_KEY] int NULL, 
	[PER] int NULL, 
	[USR_NAME] varchar(12) NULL, 
	[ASSIGN_NUM] varchar(18) NULL, 
	[ITM_TEXT] varchar(50) NULL, 
	[CLEARING_DATE_KEY] int NULL, 
	[PYMT_MTHD] varchar(1) NULL, 
	[PYMT_MTHD_DESC] varchar(30) NULL, 
	[CHK_NUM] varchar(13) NULL, 
	[PYMT_BLK] varchar(1) NULL, 
	[PYMT_BLK_DESC] varchar(30) NULL, 
	[DOCMT_CRNCY_CASH_DISCNT_AMT] decimal(18,3) NULL, 
	[CMPNY_CRNCY_CASH_DISCNT_AMT] decimal(18,3) NULL, 
	[GROUP_CRNCY_CASH_DISCNT_AMT] decimal(18,3) NULL, 
	[CASH_DISCNT_PRCNTG_1] decimal(18,3) NULL, 
	[CASH_DISCNT_PRCNTG_2] decimal(18,3) NULL, 
	[BSLINE_DATE_FOR_DUE_DATE_CALCUL] datetime2(0) NULL, 
	[CASH_DISCNT_DAYS_1] decimal(18,3) NULL, 
	[CASH_DISCNT_DAYS_2] decimal(18,3) NULL, 
	[NET_PYMT_TRMS_PER] decimal(18,3) NULL, 
	[PYMT_TRMS] varchar(4) NULL, 
	[PYMT_TRMS_DESC] varchar(50) NULL, 
	[CLEARING_DOCMT_NUM] varchar(10) NULL, 
	[VNDR_CMPNY_KEY] int NULL, 
	[SPCL_GL_IND] varchar(1) NULL, 
	[SPCL_GL_IND_DESC] varchar(30) NULL
);