CREATE TABLE [dbo].[EDW_T_D_SAL_DCHAREN_CUR_D] (

	[DOCMT_CHARS_ENCOWAY_JS_HDR_KEY] int NOT NULL, 
	[OBJ_NUM] varchar(50) NULL, 
	[CLASS_TYP] varchar(3) NULL, 
	[CLASS_NUM] varchar(18) NULL, 
	[CLASS_STATUS] varchar(1) NULL, 
	[G_PRINTER_ID] varchar(30) NULL, 
	[G_BRANDOWNER] varchar(30) NULL, 
	[G_TD_DESC] varchar(30) NULL, 
	[G_SU_WIDTH] varchar(30) NULL, 
	[G_SU_HEIGHT] varchar(30) NULL, 
	[G_ITM_NO] varchar(30) NULL, 
	[G_JOBTYPE] varchar(30) NULL, 
	[G_CNTRY_ID] varchar(30) NULL, 
	[G_IS_SECURITY] varchar(30) NULL, 
	[G_ROTO_TECHNOLOGY] varchar(30) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[G_SUPPLIED_FILES_MIN_DATE] date NULL, 
	[G_SUPPLIED_FILES_MAX_DATE] date NULL
);