CREATE TABLE [dbo].[EDW_T_D_MST_CMPNYDT_CUR_D] (

	[CMPNY_CD] varchar(max) NOT NULL, 
	[Company Factory Calendar ID] varchar(max) NOT NULL, 
	[DATE_KEY] int NOT NULL, 
	[Company Holiday Calendar ID] varchar(max) NULL, 
	[Company Date] date NULL, 
	[Company Fiscal Year] int NULL, 
	[Company Fiscal Period Number] int NULL, 
	[Company Fiscal Period Code] varchar(max) NULL, 
	[Company Fiscal Quarter Number] int NULL, 
	[Company Fiscal Quarter Code] varchar(max) NULL, 
	[Company Calendar Year] int NULL, 
	[Company Calendar Month Number] int NULL, 
	[Company Calendar Month Code] varchar(max) NULL, 
	[Company Calendar Month Description] varchar(max) NULL, 
	[Company Calendar Quarter Number] int NULL, 
	[Company Calendar Quarter Code] varchar(max) NULL, 
	[Company Calendar Weekday Number] int NULL, 
	[Company Calendar Weekday Name] varchar(max) NULL, 
	[Company Calendar Day In Month] int NULL, 
	[Company Calendar Day In Year] int NULL, 
	[Company Calendar Week] int NULL, 
	[Company Calendar Month In Quarter Number] int NULL, 
	[Company Calendar Days in Month] int NULL, 
	[Company Current Day Flag] int NULL, 
	[Company Current Day Minus 1 Flag] int NULL, 
	[Company Current Calendar Week Flag] int NULL, 
	[Company Current Calendar Week Minus 1 Flag] int NULL, 
	[Company Current Month Flag] int NULL, 
	[Company Current Month Minus 1 Flag] int NULL, 
	[Company Current Month Minus 12 Flag] int NULL, 
	[Company Current Quarter Flag] int NULL, 
	[Company Current Quarter Minus 1 Flag] int NULL, 
	[Company Current Quarter Minus 4 Flag] int NULL, 
	[Company Current Calendar Year Flag] int NULL, 
	[Company Current Calendar Year Minus 1 Flag] int NULL, 
	[Company Current Calendar Year Minus 2 Flag] int NULL, 
	[Company Current Fiscal Year Flag] int NULL, 
	[Company Current Fiscal Year Minus 1 Flag] int NULL, 
	[Company Current Fiscal Year Minus 2 Flag] int NULL, 
	[Company Current Calendar Year Plus 1 Flag] int NULL, 
	[Company Current Fiscal Year Plus 1 Flag] int NULL, 
	[Company Day in Fiscal Year] int NULL, 
	[Company Date Is Weekday] int NULL, 
	[Company Fiscal Week] int NULL, 
	[Company Current Fiscal Week Flag] int NULL, 
	[Company Current Fiscal Week Minus 1 Flag] int NULL, 
	[Company Fiscal Weekday Number] int NULL, 
	[Company Fiscal Weekday Name] varchar(max) NULL, 
	[CURR_MNTH_MINUS_2_FLG] int NULL, 
	[Company Is Factory Working Day] int NULL, 
	[Company Is Factory Public Holiday] int NULL, 
	[Company Is Working Day] int NULL, 
	[Company Business Day Number] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);