CREATE TABLE [dbo].[EDW_T_D_FI_MELTGRP_CUR_D] (

	[ACCT_ID] varchar(50) NOT NULL, 
	[MELT_ADJ_OPER_CF_VAL] varchar(100) NULL, 
	[MELT_ADJEBITDA_BU_VAL] varchar(100) NULL, 
	[MELT_ADJEBITDA_CORP_VAL] varchar(100) NULL, 
	[MELT_CAPEX_VAL] varchar(100) NULL, 
	[MELT_DII_VAL] varchar(100) NULL, 
	[MELT_DII_NUMERATOR_VAL] varchar(100) NULL, 
	[MELT_DII_DPO_DENOMINATOR_VAL] varchar(100) NULL, 
	[MELT_DPO_VAL] varchar(100) NULL, 
	[MELT_DPO_NUMERATOR_VAL] varchar(100) NULL, 
	[MELT_DSO_VAL] varchar(100) NULL, 
	[MELT_DSO_NUMERATOR_VAL] varchar(100) NULL, 
	[MELT_END_CASH_BALANCE_VAL] varchar(100) NULL, 
	[MELT_GP_VAL] varchar(100) NULL, 
	[MELT_LEVERAGE_RATIO_VAL] varchar(100) NULL, 
	[MELT_LT_DEBT_VAL] varchar(100) NULL, 
	[MELT_NIA_VAL] varchar(100) NULL, 
	[MELT_REVENUE_VAL] varchar(100) NULL, 
	[MELT_TOTAL_LABOR_COST_VAL] varchar(100) NULL
);