CREATE TABLE [dbo].[EDW_T_F_PP_SPNDANL_CUR_D] (

	[CMPNY_KEY] int NOT NULL, 
	[DOCMT_NUM] varchar(10) NOT NULL, 
	[DOCMT_ITM_NUM] varchar(3) NOT NULL, 
	[YR] varchar(4) NOT NULL, 
	[DOCMT_TYP] varchar(2) NULL, 
	[DOCMT_DATE_KEY] int NULL, 
	[PSTNG_DATE_KEY] int NULL, 
	[VNDR_KEY] int NULL, 
	[COST_CNTR_KEY] int NULL, 
	[GL_KEY] int NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[SEG_KEY] int NULL, 
	[PLNT_KEY] int NULL, 
	[PURCHS_ORDER_ITM_KEY] int NULL, 
	[PSTNG_KEY] varchar(2) NULL, 
	[ACCT_TYP] varchar(1) NULL, 
	[DEBIT_CREDIT_IND] varchar(1) NULL, 
	[CMPNY_CRNCY_AMT] decimal(13,2) NULL, 
	[DOCMT_CRNCY_AMT] decimal(13,2) NULL, 
	[GROUP_CRNCY_AMT] decimal(13,2) NULL, 
	[QTY] decimal(13,3) NULL, 
	[BASE_UOM] varchar(3) NULL, 
	[REF_DOCMT_NUM] varchar(16) NULL, 
	[DOCMT_HDR_TEXT] varchar(25) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[MATRL_KEY] int NULL, 
	[DOCMT_TYP_DESC] varchar(20) NULL, 
	[PSTNG_KEY_DESC] varchar(20) NULL, 
	[ACCT_TYP_DESC] varchar(60) NULL, 
	[TAX_ON_SALES_PURCHASES_CD] varchar(2) NULL, 
	[DOCMT_CRNCY_KEY] int NULL, 
	[CMPNY_CRNCY_KEY] int NULL, 
	[GROUP_CRNCY_KEY] int NULL, 
	[CUST_KEY] int NULL, 
	[ASSET_NUM] varchar(12) NULL, 
	[SALES_ORDER_KEY] int NULL, 
	[PER] int NULL
);