CREATE TABLE [dbo].[EDW_T_D_PRD_SERVORD_CUR_D] (

	[SERVC_ORDER_KEY] int NOT NULL, 
	[Service Order] varchar(12) NULL, 
	[Service Order Operation Task List ID] varchar(50) NULL, 
	[Service Order Order Type] varchar(10) NULL, 
	[Service Order Category] varchar(10) NULL, 
	[Service Order Company Code] varchar(10) NULL, 
	[Service Order Plant] varchar(50) NULL, 
	[Service Order Location Plant] varchar(50) NULL, 
	[Service Order Maintenance Plant] varchar(50) NULL, 
	[Service Order Document Currency] varchar(10) NULL, 
	[Service Order Maintenance Work Center] varchar(50) NULL, 
	[Service Order Functional Area] varchar(50) NULL, 
	[Service Order Object Class] varchar(50) NULL, 
	[Service Order Estimated Total Costs] decimal(18,2) NULL, 
	[Service Order Description] varchar(255) NULL, 
	[Service Order Is Created] varchar(1) NULL, 
	[Service Order Is Released] varchar(1) NULL, 
	[Service Order Is Completed] varchar(1) NULL, 
	[Service Order Is Closed] varchar(1) NULL, 
	[Service Order Release Date] date NULL, 
	[Service Order Tech Completion Date] date NULL, 
	[Service Order Close Date] date NULL, 
	[Service Order Deletion Flag] varchar(1) NULL, 
	[Service Order Object Number] varchar(50) NULL, 
	[Service Order Responsible Cost Center] varchar(50) NULL, 
	[Service Order Profit Center] varchar(50) NULL, 
	[Service Order Basic Start Date] date NULL, 
	[Service Order Basic Finish Date] date NULL, 
	[Service Order Scheduled Release Date] date NULL, 
	[Service Order Scheduled Finish Date] date NULL, 
	[Service Order Scheduled Start Date] date NULL, 
	[Service Order Actual Start Date] date NULL, 
	[Service Order Actual Finish Date] date NULL, 
	[Service Order Actual Release Date] date NULL, 
	[Service Order Planned Release Date] date NULL, 
	[Service Order Reservation] varchar(50) NULL, 
	[Service Order Total Scrap] decimal(18,2) NULL, 
	[Service Order Target Quantity] decimal(18,2) NULL, 
	[Service Order Task List Type] varchar(10) NULL, 
	[Service Order Capacity Requirements ID] varchar(10) NULL, 
	[Service Order Equipment] varchar(50) NULL, 
	[Service Order Location Account Assignment] varchar(50) NULL, 
	[Service Order Planning Plant] varchar(50) NULL, 
	[Service Order Work Center] varchar(50) NULL, 
	[Service Order Object List] varchar(100) NULL, 
	[Service Order Maintenance Activity Type] varchar(50) NULL, 
	[Service Order Notification] varchar(50) NULL, 
	[Service Order Cost Center] varchar(50) NULL, 
	[Service Order Functional Location] varchar(50) NULL, 
	[Service Order Sales Order] varchar(50) NULL, 
	[Service Order Sales Order Item Number] varchar(50) NULL, 
	[Service Order Count Of Rounds] int NULL, 
	[Service Order Count Of Rework Internal] int NULL, 
	[Service Order HUB Production Deadline Date] date NULL, 
	[Service Order HUB Approval Loop Deadline Date] date NULL, 
	[Service Order HUB Change Request Deadline Date] date NULL, 
	[Service Order HUB Finish Date Deadline Date] date NULL, 
	[Service Order HUB Number Of Loops] int NULL, 
	[Service Order HUB Webstatus] varchar(50) NULL, 
	[Service Order HUB First Time In Prep For Production] datetime2(0) NULL, 
	[Service Order HUB Last Time In Prep For Production] datetime2(0) NULL, 
	[Service Order HUB First Time In Production] datetime2(0) NULL, 
	[Service Order HUB Last Time In Production] datetime2(0) NULL, 
	[Service Order HUB First Time In Out For Approval] datetime2(0) NULL, 
	[Service Order HUB Last Time In Out For Approval] datetime2(0) NULL, 
	[Service Order HUB First Time In Approval Loop] datetime2(0) NULL, 
	[Service Order HUB Last Time In Approval Loop] datetime2(0) NULL, 
	[Service Order HUB First Time In Change Request] datetime2(0) NULL, 
	[Service Order HUB Last Time In Change Request] datetime2(0) NULL, 
	[Service Order HUB First Time In Approved] datetime2(0) NULL, 
	[Service Order HUB Last Time In Approved] datetime2(0) NULL, 
	[Service Order HUB First Time In Final Production] datetime2(0) NULL, 
	[Service Order HUB Last Time In Final Production] datetime2(0) NULL, 
	[Service Order HUB First Time In Production Completed] datetime2(0) NULL, 
	[Service Order HUB Last Time In Production Completed] datetime2(0) NULL, 
	[Service Order HUB First Time In On Hold] datetime2(0) NULL, 
	[Service Order HUB Last Time In On Hold] datetime2(0) NULL, 
	[Service Order HUB First Time In Archived] datetime2(0) NULL, 
	[Service Order HUB Last Time In Archived] datetime2(0) NULL, 
	[ETL_SRC_SYS_CD] varchar(50) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Service Order HUB Webstatus Description] varchar(255) NULL, 
	[Service Order Done Date] date NULL, 
	[Service Order Invoice Create Date] date NULL, 
	[Service Order Job Status] varchar(255) NULL, 
	[Service Order System Status] varchar(255) NULL, 
	[Service Order Last Changed By] varchar(255) NULL, 
	[Service Order Change Date] date NULL, 
	[Service Order Entered By] varchar(255) NULL, 
	[Service Order Additional Device Data] varchar(255) NULL, 
	[Service Order Assembly] varchar(255) NULL, 
	[Service Order ILOA Individual] varchar(255) NULL, 
	[Service Order Priority] varchar(50) NULL, 
	[Service Order Priority Type] varchar(50) NULL, 
	[Service Order Reason Code] varchar(255) NULL, 
	[Service Order Reason for Change] varchar(255) NULL, 
	[Service Order Description of Change] varchar(255) NULL, 
	[Service Order Error Caught By] varchar(255) NULL, 
	[Service Order Error Description] varchar(255) NULL, 
	[Service Order Error Origin] varchar(255) NULL, 
	[Service Order Error Severity] varchar(255) NULL, 
	[Service Order Error Type] varchar(255) NULL, 
	[Service Order Requested By] varchar(255) NULL, 
	[Service Order Controlling Area] varchar(10) NULL, 
	[Service Order Equity Type] varchar(10) NULL, 
	[Service Order WBS Element] int NULL, 
	[Service Order Type Description] varchar(255) NULL, 
	[Service Order Category Description] varchar(255) NULL, 
	[Service Order Company Description] varchar(255) NULL, 
	[Service Order Plant Description] varchar(255) NULL, 
	[Service Order Location Plant Description] varchar(255) NULL, 
	[Service Order Maintenance Plant Description] varchar(255) NULL, 
	[Service Order Document Currency Description] varchar(255) NULL, 
	[Service Order Object Class Description] varchar(255) NULL, 
	[Service Order Task List Type Description] varchar(255) NULL, 
	[Service Order Planning Plant Description] varchar(255) NULL, 
	[Service Order Work Center Description] varchar(255) NULL, 
	[Service Order Maintenance Activity Type Description] varchar(255) NULL, 
	[Service Order Active Date] date NULL, 
	[Service Order On Hold Date] date NULL, 
	[Service Order Intercompany Date] date NULL, 
	[Service Order Out For Appproval Date] date NULL, 
	[Service Order Closed Date] date NULL, 
	[Service Order Post Approval Production Date] date NULL, 
	[Service Order Active Artwork Date] date NULL, 
	[Service Order Active Prepress Date] date NULL, 
	[Service Order Priority Type Description] varchar(255) NULL, 
	[Service Order Controlling Area Description] varchar(255) NULL, 
	[Service Order Equity Type Description] varchar(255) NULL, 
	[Service Order Created On Date] date NULL, 
	[Service Order Production Complete Date] date NULL, 
	[Service Order Waiting on Client PO Date] date NULL, 
	[Service Order Billing In Progress Date] date NULL, 
	[Service Order Released To Invoicing Date] date NULL, 
	[Service Order Accountng Indicator Customer] varchar(50) NULL, 
	[Service Order Accountng Indicator Customer Description] varchar(255) NULL
);