CREATE TABLE [dbo].[EDW_T_R_MST_SGK_STNDRD_TXT_CATG_CUR_D] (

	[OPERATION_DESCRIPTION] varchar(255) NULL, 
	[STANDARD_TEXT_KEY] varchar(255) NULL, 
	[FY2023_SS_TASKS] varchar(255) NULL, 
	[SSP_PREFERRED_TASK] varchar(255) NULL, 
	[CSR_TASKS] varchar(255) NULL, 
	[ALL_TASKS] varchar(255) NULL, 
	[ACTIVITY_GROUP] varchar(255) NULL, 
	[ACTIVITY_WITH_STATUS] varchar(255) NULL, 
	[AUTOMATION_GROUPS] varchar(255) NULL
);