CREATE TABLE [dbo].[EDW_T_F_FI_BPCPYROL_CUR_D_BK_07092023] (

	[EMPL_ID] varchar(50) NOT NULL, 
	[EMPL_NAME] varchar(100) NULL, 
	[ACCT_ID] varchar(50) NOT NULL, 
	[ACCT_NAME] varchar(100) NULL, 
	[COST_CNTR_ID] varchar(50) NOT NULL, 
	[COST_CNTR_NAME] varchar(100) NULL, 
	[PROFT_CNTR_ID] varchar(50) NOT NULL, 
	[PROFT_CNTR_NAME] varchar(100) NULL, 
	[PAY_ELEMNT] varchar(50) NOT NULL, 
	[FISCAL_YR] int NOT NULL, 
	[PER] int NOT NULL, 
	[AMT] decimal(20,3) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[PAY_START_DATE_KEY] int NOT NULL, 
	[PAY_END_DATE_KEY] int NOT NULL, 
	[CHK_DATE_KEY] int NOT NULL
);