CREATE TABLE [dbo].[EDW_T_D_MST_CMPNYCD_CUR_D] (

	[CMPNY_KEY] int NOT NULL, 
	[Company Code] varchar(4) NULL, 
	[Legacy Company Code] varchar(10) NULL, 
	[Company Name] varchar(60) NULL, 
	[Company Line Of Business] varchar(20) NULL, 
	[Company Line Of Business Description] varchar(255) NULL, 
	[Company Currency Code] varchar(5) NULL, 
	[Company Language Type Code] varchar(1) NULL, 
	[Company Chart Of Accounts ID] varchar(4) NULL, 
	[Company Address Line 1] varchar(60) NULL, 
	[Company Address Line 2] varchar(60) NULL, 
	[Company City Name] varchar(40) NULL, 
	[Company Zip Code] varchar(10) NULL, 
	[Company Country Code] varchar(3) NULL, 
	[Company Telephone 1] varchar(30) NULL, 
	[Company Telephone 2] varchar(30) NULL, 
	[Company Fax Number] varchar(30) NULL, 
	[Company Tax Jurisdiction] varchar(15) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Company Fiscal Year Variant] varchar(2) NULL, 
	[Company Credit Control Area] varchar(4) NULL, 
	[Company Input Tax Code] varchar(2) NULL, 
	[Company Output Tax Code] varchar(2) NULL, 
	[Company Currency Description] varchar(15) NULL, 
	[Company Chart Of Accounts Description] varchar(50) NULL, 
	[Company Country Description] varchar(15) NULL, 
	[Company Fiscal Year Variant Description] varchar(30) NULL, 
	[Company Credit Control Area Description] varchar(35) NULL
);