CREATE TABLE [dbo].[EDW_T_D_MST_WORKCTR_CUR_D] (

	[WRK_CNTR_KEY] int NOT NULL, 
	[WRK_CNTR_ID] varchar(8) NULL, 
	[PLNT_ID] varchar(4) NULL, 
	[OBJ_ID] int NULL, 
	[OBJ_TYP] varchar(2) NULL, 
	[WRK_CNTR_CTGRY] varchar(4) NULL, 
	[WRK_CNTR_LOC] varchar(10) NULL, 
	[PERSON_RESPNSBLE] varchar(3) NULL, 
	[STD_VAL_KEY] varchar(4) NULL, 
	[USAGE_CD] varchar(3) NULL, 
	[CAPACITY_ID] int NULL, 
	[SUPLY_AREA] varchar(10) NULL, 
	[DELETION_FLG] varchar(1) NULL, 
	[LOCKED_STATUS] varchar(1) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[WRK_CNTR_DESC] varchar(40) NULL, 
	[WRK_CNTR_CTGRY_DESC] varchar(20) NULL, 
	[PERSON_RESPNSBLE_NAME] varchar(40) NULL, 
	[CTRL_KEY] varchar(4) NULL, 
	[STOR_LOC_STOR_RESOURCE] varchar(4) NULL, 
	[USR_NAME_TERM] varchar(12) NULL, 
	[USR_NAME_GRND] varchar(12) NULL, 
	[CHANGED_ON_DATE_TERM] date NULL, 
	[CHANGED_ON_DATE_GRND] date NULL, 
	[CHANGED_ON_DATE] date NULL, 
	[PLNT_DESC] varchar(30) NULL, 
	[OBJ_TYP_DESC] varchar(60) NULL, 
	[WRK_CNTR_LOC_DESC] varchar(40) NULL, 
	[STD_VAL_DESC] varchar(30) NULL, 
	[USAGE_DESC] varchar(30) NULL, 
	[SUPLY_AREA_DESC] varchar(40) NULL, 
	[CTRL_DESC] varchar(40) NULL, 
	[STOR_LOC_DESC] varchar(40) NULL
);