CREATE TABLE [dbo].[EDW_T_F_HR_HEADCN2_CUR_D] (

	[CMPNY_KEY] int NOT NULL, 
	[BIZ_SEG_KEY] int NOT NULL, 
	[LINE_OF_BIZ_KEY] int NOT NULL, 
	[PROFT_CNTR_KEY] int NOT NULL, 
	[COST_CNTR_KEY] int NOT NULL, 
	[LOC_REGN_KEY] int NOT NULL, 
	[LOC_PLNT_KEY] int NOT NULL, 
	[JOB_CLSFTN_KEY] int NOT NULL, 
	[JOB_SUB_FUNCTION_KEY] int NOT NULL, 
	[EMPL_CLASS_KEY] int NOT NULL, 
	[EMPLNT_MODE_KEY] int NOT NULL, 
	[DATA_EXTRACTION_DATE_KEY] int NOT NULL, 
	[NO_OF_EMPLOYEES] int NULL, 
	[SUM_OF_STD_HRS] decimal(10,2) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);