CREATE TABLE [dbo].[EDW_T_D_MST_CSTCACT_CUR_D] (

	[COST_CNTR_ACTIVITY_COSTS_KEY] int NOT NULL, 
	[COST_CNTR_ID] varchar(10) NULL, 
	[ACTIVITY_TYP] varchar(6) NULL, 
	[YR] int NULL, 
	[PER] int NULL, 
	[CMPNY_CRNCY_COST_AMT] decimal(18,3) NULL, 
	[GROUP_CRNCY_COST_AMT] decimal(18,3) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[COST_CNTR_DESC] varchar(40) NULL, 
	[ACTIVITY_TYP_CTGRY_DESC] varchar(60) NULL, 
	[PRICE_IND_DESC] varchar(50) NULL, 
	[PRICE_IND] varchar(3) NULL
);