CREATE TABLE [dbo].[EDW_T_F_CO_CCCSTRN_CUR_D] (

	[LDGR] varchar(2) NULL, 
	[OBJ_NUM] varchar(22) NULL, 
	[YR] int NULL, 
	[VAL_TYP] varchar(2) NULL, 
	[VRSN] varchar(3) NULL, 
	[COST_CNTR_KEY] int NOT NULL, 
	[CO_SUBKEY] varchar(14) NULL, 
	[BIZ_TRNSCTN] varchar(4) NULL, 
	[TRADING_PRTNR] varchar(6) NULL, 
	[TRADING_PRTNR_BIZ_AREA] varchar(4) NULL, 
	[DEBIT_CREDIT_IND] varchar(1) NULL, 
	[DOCMT_CRNCY_KEY] int NOT NULL, 
	[CMPNY_KEY] int NOT NULL, 
	[SEG_KEY] int NULL, 
	[COST_ELEMNT_KEY] int NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[CMPNY_CRNCY_KEY] int NULL, 
	[GROUP_CRNCY_KEY] int NULL, 
	[DOCMT_CRNCY_AMT] decimal(15,2) NULL, 
	[CMPNY_CRNCY_AMT] decimal(15,2) NULL, 
	[GROUP_CRNCY_AMT] decimal(15,2) NULL, 
	[PER] int NULL, 
	[PRTNR_OBJ_TYP] varchar(2) NULL, 
	[PRTNR_OBJ_TYP_DESC] varchar(30) NULL, 
	[TOTAL_QTY] decimal(15,3) NULL, 
	[FIXED_QTY] decimal(15,3) NULL, 
	[VAL_TYP_DESC] varchar(30) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[FUNCTNL_AREA_KEY] int NULL, 
	[CONTROLLING_AREA] varchar(4) NOT NULL, 
	[DOCMT_NUM] varchar(10) NOT NULL, 
	[PSTNG_ROW] varchar(3) NOT NULL, 
	[PLNT_KEY] int NULL, 
	[CONTROLLING_AREA_DESC] varchar(25) NULL, 
	[LDGR_DESC] varchar(40) NULL, 
	[BIZ_TRNSCTN_DESC] varchar(30) NULL, 
	[TRADING_PRTNR_DESC] varchar(30) NULL, 
	[TRADING_PRTNR_BIZ_AREA_DESC] varchar(30) NULL, 
	[PRTNR_OBJ] varchar(22) NULL, 
	[SRC_OBJ] varchar(22) NULL, 
	[PSTNG_DATE_KEY] int NULL, 
	[DOCMT_ITM_NUM] int NULL, 
	[TOTAL_QTY_ENTERED] decimal(15,3) NULL, 
	[UOM] varchar(3) NULL, 
	[PSTD_UOM] varchar(3) NULL, 
	[CONTROLLING_AREA_COST_ELEMNT_KE] int NULL, 
	[MATRL_KEY] int NULL
);