CREATE TABLE [dbo].[EDW_T_D_MST_PLANT_CUR_D] (

	[PLNT_KEY] int NOT NULL, 
	[Plant ID] varchar(max) NULL, 
	[Legacy Plant ID] varchar(max) NULL, 
	[Plant Name] varchar(max) NULL, 
	[Plant Company Code] varchar(max) NULL, 
	[Plant Sales Organization] varchar(max) NULL, 
	[Plant Purchasing Organization] varchar(max) NULL, 
	[Plant Valuation Area] varchar(max) NULL, 
	[Plant Customer Number] varchar(max) NULL, 
	[Plant Vendor Number] varchar(max) NULL, 
	[Plant Factory Calendar Key] varchar(max) NULL, 
	[Plant Line 1 Description] varchar(max) NULL, 
	[Plant Line 2 Description] varchar(max) NULL, 
	[Plant City Name] varchar(max) NULL, 
	[Plant Zip Code] varchar(max) NULL, 
	[Plant Country Code] varchar(max) NULL, 
	[Plant Country Name] varchar(max) NULL, 
	[Plant Tax Jurisdiction] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Plant IS P001] varchar(max) NULL, 
	[Plant IS P002] varchar(max) NULL, 
	[Plant Company Description] varchar(max) NULL, 
	[Plant Sales Organization Description] varchar(max) NULL, 
	[Plant Factory Calendar Description] varchar(max) NULL, 
	[Plant Purchasing Organization Description] varchar(max) NULL, 
	[Plant Tax Indicator] varchar(max) NULL, 
	[Plant Tax Indicator Description] varchar(max) NULL, 
	[Plant Shipping/Receiving Point] varchar(max) NULL, 
	[Plant Shipping/Receiving Point Description] varchar(max) NULL
);