CREATE TABLE [dbo].[EDW_T_D_MST_GENLDGR_CUR_D] (

	[GL_KEY] int NOT NULL, 
	[GL_CD] varchar(10) NULL, 
	[CHART_OF_ACCTS] varchar(5) NULL, 
	[GL_DESC] varchar(60) NULL, 
	[IS_BAL_SHEET_ACCT] varchar(1) NULL, 
	[CREATED_DATE] varchar(8) NULL, 
	[CREATED_BY] varchar(12) NULL, 
	[ACCT_GROUP] varchar(4) NULL, 
	[MRKD_FOR_DELETION] varchar(1) NULL, 
	[BLCKD_FOR_CREATION] varchar(1) NULL, 
	[BLCKD_FOR_PSTNG] varchar(1) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[CHART_OF_ACCTS_DESC] varchar(50) NULL, 
	[ACCT_GROUP_DESC] varchar(30) NULL, 
	[FUNCTNL_AREA] varchar(16) NULL, 
	[FUNCTNL_AREA_DESC] varchar(25) NULL, 
	[P_L_STMT_ACCT_TYP] varchar(2) NULL, 
	[GROUP_ACCT_NUM] varchar(10) NULL, 
	[SEARCH_MATCHCODE] varchar(25) NULL, 
	[GL_SHORT_DESC] varchar(20) NULL
);