CREATE TABLE [dbo].[EDW_T_D_MST_EXCHGRT_CUR_D] (

	[EXCHG_RT_TYP] varchar(4) NOT NULL, 
	[EXCHG_RT_TYP_DESC] varchar(40) NULL, 
	[FROM_CRNCY] varchar(5) NOT NULL, 
	[TO_CRNCY] varchar(5) NOT NULL, 
	[VALID_FROM_DATE] date NOT NULL, 
	[EXCHG_RT] decimal(20,10) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);