CREATE TABLE [dbo].[EDW_T_D_SAL_SALORDH_CUR_D] (

	[SALES_ORDER_KEY] int NOT NULL, 
	[Sales Order ID] varchar(max) NULL, 
	[Sales Order Company Code] varchar(max) NULL, 
	[Sales Order Segment ID] varchar(max) NULL, 
	[Sales Order Type ID] varchar(max) NULL, 
	[Sales Order Requested Delivery Date] date NULL, 
	[Sales Order Category Code] varchar(max) NULL, 
	[Sales Order Document Number] varchar(max) NULL, 
	[Sales Order Document Version] varchar(max) NULL, 
	[Sales Order Document Date] date NULL, 
	[Sales Order Purchase Order Type] varchar(max) NULL, 
	[Sales Order Note Description] varchar(max) NULL, 
	[Sales Order Receive Date] date NULL, 
	[Sales Order Currency] varchar(max) NULL, 
	[Sales Order Delivery Block] varchar(max) NULL, 
	[Sales Order Sales Organization] varchar(max) NULL, 
	[Sales Order Pricing Procedure In Pricing] varchar(max) NULL, 
	[Sales Order Distribution Channel] varchar(max) NULL, 
	[Sales Order Division] varchar(max) NULL, 
	[Sales Order Sales Group] varchar(max) NULL, 
	[Sales Order Sales Office] varchar(max) NULL, 
	[Sales Order Internal Customer Reference Number] varchar(max) NULL, 
	[Sales Order Name Of Order] varchar(max) NULL, 
	[Sales Order Document Overall Processing Status] varchar(max) NULL, 
	[Sales Order Document Overall Rejection Status] varchar(max) NULL, 
	[Sales Order Delivery Status] varchar(max) NULL, 
	[Sales Order Credit Status] varchar(max) NULL, 
	[Sales Order Billing Status] varchar(max) NULL, 
	[Sales Order Posting Status] varchar(max) NULL, 
	[Sales Order Rejection Status] varchar(max) NULL, 
	[Sales Order Total Goods Movement Status] varchar(max) NULL, 
	[Sales Order Reason] varchar(max) NULL, 
	[Sales Order Reference Document] varchar(max) NULL, 
	[Sales Order Contract Number] varchar(max) NULL, 
	[Sales Order Lot Location] varchar(max) NULL, 
	[Sales Order Counselor] varchar(max) NULL, 
	[Sales Order Websphere Order Number] varchar(max) NULL, 
	[Sales Order Processed Flag] varchar(max) NULL, 
	[Sales Order Websphere Create Name] varchar(max) NULL, 
	[Sales Order Delivery Days] decimal(3,0) NULL, 
	[Sales Order Previous Sales Order Number] varchar(max) NULL, 
	[Sales Order Remake Number] varchar(max) NULL, 
	[Sales Order Created Date] date NULL, 
	[Sales Order Created User ID] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Sales Order Reference Number] varchar(max) NULL, 
	[Sales Order Type Description] varchar(max) NULL, 
	[Sales Order Purchase Order Number] varchar(max) NULL, 
	[Sales Order Bill Stat Order Status] varchar(max) NULL, 
	[Sales Order Document Overall Processing Status Description] varchar(max) NULL, 
	[Sales Order Document Overall Rejection Status Description] varchar(max) NULL, 
	[Sales Order Delivery Status Description] varchar(max) NULL, 
	[Sales Order Credit Status Description] varchar(max) NULL, 
	[Sales Order Billing Status Description] varchar(max) NULL, 
	[Sales Order Posting Status Description] varchar(max) NULL, 
	[Sales Order Rejection Status Description] varchar(max) NULL, 
	[Sales Order Total Goods Movement Status Description] varchar(max) NULL, 
	[Sales Order Reason Description] varchar(max) NULL, 
	[Sales Order Bill Stat Order Status Description] varchar(max) NULL, 
	[Sales Order Payment Terms] varchar(max) NULL, 
	[Sales Order Payment Terms Description] varchar(max) NULL, 
	[Sales Order Quotation Valid From Date] date NULL, 
	[Sales Order Quotation Valid To Date] date NULL, 
	[Sales Order Warranty Date] date NULL, 
	[Sales Order Preceding Document Category] varchar(max) NULL, 
	[Sales Order Version] varchar(max) NULL, 
	[Sales Order Reference Status] varchar(max) NULL, 
	[Sales Order Total Reference Status] varchar(max) NULL, 
	[Sales Order Billing Block] varchar(max) NULL, 
	[Sales Order Is Arrangement] varchar(max) NULL, 
	[Sales Order Is Approval] varchar(max) NULL, 
	[Sales Order Is Delivery] varchar(max) NULL, 
	[Sales Order Is Fixed Det] varchar(max) NULL, 
	[Sales Order Invoice Create Date] date NULL, 
	[Sales Order Sold To Customer] varchar(max) NULL, 
	[Sales Order Bill To Customer] varchar(max) NULL, 
	[Sales Order Ship To Customer] varchar(max) NULL, 
	[Sales Order Changed On Date] date NULL, 
	[Sales Order Document Currency Net Value] decimal(15,3) NULL, 
	[Sales Order Customer Group 2] varchar(max) NULL, 
	[Sales Order Billing Date] date NULL, 
	[Sales Order Entry Time] int NULL, 
	[Sales Order Usage Indicator] varchar(max) NULL, 
	[SO Status of Static Credit Limit Check] varchar(max) NULL, 
	[Sales Order Company Code To Be Billed] varchar(max) NULL, 
	[Sales Order Long Description] varchar(max) NULL, 
	[Sales Order Company Description] varchar(max) NULL, 
	[Sales Order Category Code Description] varchar(max) NULL, 
	[Sales Order Purchase Order Type Description] varchar(max) NULL, 
	[Sales Order Currency Description] varchar(max) NULL, 
	[Sales Order Delivery Block Description] varchar(max) NULL, 
	[Sales Order Sales Organization Description] varchar(max) NULL, 
	[Sales Order Distribution Channel Description] varchar(max) NULL, 
	[Sales Order Division Description] varchar(max) NULL, 
	[Sales Order Sales Group Description] varchar(max) NULL, 
	[Sales Order Sales Office Description] varchar(max) NULL, 
	[Sales Order Preceding Document Category Description] varchar(max) NULL, 
	[Sales Order Reference Status Description] varchar(max) NULL, 
	[Sales Order Total Reference Status Description] varchar(max) NULL, 
	[Sales Order Billing Block Description] varchar(max) NULL, 
	[Sales Order Customer Group 2 Description] varchar(max) NULL, 
	[Sales Order Usage Indicator Description] varchar(max) NULL, 
	[Sales Order Static Credit Limit Check Description] varchar(max) NULL, 
	[Sales Order Company To Be Billed Description] varchar(max) NULL, 
	[Sales Order Sold To Purchase Order Number] varchar(max) NULL, 
	[Sales Order Sold To Purchase Order Date] date NULL, 
	[Sales Order Ship To Purchase Order Number] varchar(max) NULL, 
	[Sales Order Ship To Purchase Order Date] date NULL, 
	[Sales Order Customer Condition Group 1] varchar(max) NULL, 
	[Sales Order Customer Condition Group 1 Description] varchar(max) NULL, 
	[Sales Order Last Customer Contact Date] date NULL, 
	[Sales Order User Status] varchar(max) NULL, 
	[Sales Order Encoway ID] varchar(max) NULL, 
	[Sales Order Encoway Version] varchar(max) NULL, 
	[Sales Order Encoway Description] varchar(max) NULL, 
	[Sales Order Overall Blocked Status] varchar(max) NULL, 
	[Sales Order Overall Blocked Status Description] varchar(max) NULL, 
	[ADB Field 1 - Addl Field 1] varchar(max) NULL, 
	[ADB Field 2 - Addl Field 2] varchar(max) NULL, 
	[ADB Field 3 - Addl Field 3] varchar(max) NULL, 
	[ADB Field 4 - Addl Field 4] varchar(max) NULL, 
	[ADB Field 5 - Addl Field 5] varchar(max) NULL, 
	[ADB Field 6 - Addl Field 6] varchar(max) NULL, 
	[ADB Field 7 - Addl Field 7] varchar(max) NULL, 
	[ADB Field 8 - Addl Field 8] varchar(max) NULL, 
	[ADB Field 9 - Addl Field 9] varchar(max) NULL, 
	[Sales Order Number] varchar(max) NULL, 
	[Sales Order Delay Status] varchar(max) NULL, 
	[Sales Order Delay Status Description] varchar(max) NULL, 
	[Sales Order Payment Method] varchar(max) NULL, 
	[Sales Order Payment Method Description] varchar(max) NULL, 
	[VALID_FROM_DATE] date NULL, 
	[VALID_TO_DATE] date NULL, 
	[Sales Order Collective Number] varchar(max) NULL, 
	[Sales Order Sales Employee ID] varchar(max) NULL, 
	[Sales Order Terms Discount Percentage] varchar(max) NULL, 
	[Sales Order Customer Group 6] varchar(max) NULL, 
	[Sales Order Customer Group 7] varchar(max) NULL, 
	[Sales Order Customer Group 8] varchar(max) NULL, 
	[Sales Order Customer Group 9] varchar(max) NULL, 
	[Sales Order Customer Group 10] varchar(max) NULL, 
	[Sales Order Transaction Group] varchar(max) NULL, 
	[Sales Order Transaction Group Description] varchar(max) NULL, 
	[Sales Order Customer Group 6 Description] varchar(max) NULL, 
	[Sales Order Customer Group 7 Description] varchar(max) NULL, 
	[Sales Order Customer Group 8 Description] varchar(max) NULL, 
	[Sales Order Customer Group 9 Description] varchar(max) NULL, 
	[Sales Order Customer Group 10 Description] varchar(max) NULL
);