CREATE TABLE [dbo].[EDW_T_D_FI_MELTGRP_CUR_D] (

	[ACCT_ID] varchar(max) NULL, 
	[MELT_ADJ_OPER_CF_VAL] int NULL, 
	[MELT_ADJEBITDA_BU_VAL] int NULL, 
	[MELT_ADJEBITDA_CORP_VAL] int NULL, 
	[MELT_CAPEX_VAL] int NULL, 
	[MELT_DII_VAL] int NULL, 
	[MELT_TOTAL_LABOR_COST_VAL] int NULL, 
	[MELT_END_CASH_BALANCE_VAL] int NULL, 
	[MELT_GP_VAL] int NULL, 
	[MELT_LEVERAGE_RATIO_VAL] int NULL, 
	[MELT_LT_DEBT_VAL] int NULL, 
	[MELT_NIA_VAL] int NULL, 
	[MELT_REVENUE_VAL] int NULL, 
	[MELT_DII_NUMERATOR_VAL] int NULL, 
	[MELT_DII_DPO_DENOMINATOR_VAL] int NULL, 
	[MELT_DPO_VAL] int NULL, 
	[MELT_DPO_NUMERATOR_VAL] int NULL, 
	[MELT_DSO_VAL] int NULL, 
	[MELT_DSO_NUMERATOR_VAL] int NULL
);