CREATE TABLE [dbo].[EDW_T_D_MST_CACSELM_CUR_D] (

	[CONTROLLING_AREA_COST_ELEMNT_KE] int NULL, 
	[Controlling Area] varchar(max) NULL, 
	[Cost Element] varchar(max) NULL, 
	[Valid To Date] date NULL, 
	[Valid From Date] date NULL, 
	[Cost Element Category] varchar(max) NULL, 
	[Cost Element Category Description] varchar(max) NULL, 
	[Created On] date NULL, 
	[Entered By] varchar(max) NULL, 
	[Cost Element Attributes] varchar(max) NULL, 
	[Planning Access Indicator] varchar(max) NULL, 
	[Planning Location Indicator] varchar(max) NULL, 
	[Planning User Indicators] varchar(max) NULL, 
	[Cost Center] varchar(max) NULL, 
	[Order Number] varchar(max) NULL, 
	[Recording Consumption Quantities Indicator] varchar(max) NULL, 
	[Unit Of Measurement] varchar(max) NULL, 
	[Cost Element Deactivated Indicator] varchar(max) NULL, 
	[Cost Element Is Flagged For Deletion Indicator] varchar(max) NULL, 
	[Recovery Indicator] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);