CREATE TABLE [dbo].[EDW_T_D_MST_DATE_CUR_D] (

	[DATE_KEY] int NOT NULL, 
	[Date] date NULL, 
	[Date Fiscal Year] int NULL, 
	[FISCAL_PER_NUM] int NULL, 
	[Date Fiscal Period Code] varchar(max) NULL, 
	[Date Fiscal Quarter Number] int NULL, 
	[Date Fiscal Quarter Code] varchar(max) NULL, 
	[Date Calendar Year] int NULL, 
	[Date Calendar Month Number] int NULL, 
	[Date Calendar Month Code] varchar(max) NULL, 
	[Date Calendar Month Desc] varchar(max) NULL, 
	[CLNDR_QTR_NUM] int NULL, 
	[Date Calendar Quarter Code] varchar(max) NULL, 
	[Date Calendar Weekday Number] int NULL, 
	[Date Calendar Weekday Name] varchar(max) NULL, 
	[Date Calendar Day in Month] int NULL, 
	[Date Calendar Day in Year] int NULL, 
	[Date Calendar Week] int NULL, 
	[Date Calendar Month in Quarter Number] int NULL, 
	[Date Calendar Days in Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Date Current Day Flag] int NULL, 
	[Date Current Day Minus 1 Flag] int NULL, 
	[Date Current Calendar Week Flag] int NULL, 
	[Date Current Calendar Week Minus 1 Flag] int NULL, 
	[Date Current Month Flag] int NULL, 
	[Date Current Month Minus 1 Flag] int NULL, 
	[Date Current Month Minus 12 Flag] int NULL, 
	[Date Current Quarter Flag] int NULL, 
	[Date Current Quarter Minus 1 Flag] int NULL, 
	[Date Current Quarter Minus 4 Flag] int NULL, 
	[Date Current Calendar Year Flag] int NULL, 
	[Date Current Calendar Year Minus 1 Flag] int NULL, 
	[Date Current Calendar Year Minus 2 Flag] int NULL, 
	[Date Current Fiscal Year Flag] int NULL, 
	[Date Current Fiscal Year Minus 1 Flag] int NULL, 
	[Date Current Fiscal Year Minus 2 Flag] int NULL, 
	[Date Current Calendar Year Plus 1 Flag] int NULL, 
	[Date Current Fiscal Year Plus 1 Flag] int NULL, 
	[Date Day in Fiscal Year] int NULL, 
	[Date Date Is Weekday] int NULL, 
	[Date Fiscal Week] int NULL, 
	[Date Current Fiscal Week Flag] int NULL, 
	[Date Current Fiscal Week Minus 1 Flag] int NULL, 
	[Date Fiscal Weekday Number] int NULL, 
	[Date Fiscal Weekday Name] varchar(max) NULL, 
	[Date Current Month Minus 2 Flag] int NULL, 
	[Date Current Fiscal Week Minus 2 Flag] int NULL, 
	[Date Current Fiscal Week Minus 6 Flag] int NULL, 
	[Date Current Fiscal Week Minus 3 Flag] int NULL, 
	[Date Current Fiscal Week Minus 4 Flag] int NULL, 
	[Date Current Fiscal Week Minus 5 Flag] int NULL, 
	[Date Current Fiscal Week Minus 7 Flag] int NULL, 
	[MST_DATE_KEY] varchar(max) NULL
);