CREATE TABLE [dbo].[EDW_T_D_FI_ASSETHR_CUR_D] (

	[ASSET_KEY] int NOT NULL, 
	[CMPNY_CD] varchar(4) NULL, 
	[MAIN_ASSET_NUM] varchar(12) NULL, 
	[ASSET_SUBNUMBER] varchar(4) NULL, 
	[ASSET_CLASS] varchar(8) NULL, 
	[ASSET_CLASS_DESC] varchar(50) NULL, 
	[ASSET_DESC] varchar(50) NULL, 
	[QTY] decimal(13,3) NULL, 
	[BASE_UOM] varchar(5) NULL, 
	[ASSET_CAPITALIZATION_DATE] date NULL, 
	[FIRST_ACQUISTN_FISCAL_YR] int NULL, 
	[FIRST_ACQUISTN_FISCAL_PER] int NULL, 
	[DEACTIVATION_DATE] date NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[NAME_OF_PERSON_WHO_CREATED_THE] varchar(12) NULL, 
	[DATE_ON_WHICH_RCD_WAS_CREATED] date NULL, 
	[ASSET_VAL_DATE_OF_THE_FIRST_PST] date NULL, 
	[INVTRY_NUM] varchar(25) NULL, 
	[ADDITIONAL_ASSET_DESC] varchar(50) NULL, 
	[SERIAL_NUM] varchar(18) NULL, 
	[COST_CNTR] varchar(10) NULL, 
	[PLNT] varchar(4) NULL
);


GO
ALTER TABLE [dbo].[EDW_T_D_FI_ASSETHR_CUR_D] ADD CONSTRAINT PK_EDW_T_D_FI_ASSETHR_CUR_D primary key NONCLUSTERED ([ASSET_KEY]);