CREATE TABLE [dbo].[EDW_T_D_MST_DOCCHAR_CUR_D] (

	[DOCMT_CHARS_KEY] int NOT NULL, 
	[DOCMT_TYP] varchar(3) NULL, 
	[DOCMT_NUM] varchar(25) NULL, 
	[DOCMT_VRSN] varchar(2) NULL, 
	[DOCMT_DESC] varchar(40) NULL, 
	[DOCMT_DESC_2] varchar(40) NULL, 
	[CLASS_TYP] varchar(3) NULL, 
	[CLASS] varchar(18) NULL, 
	[CLASS_STATUS] varchar(1) NULL, 
	[CHARACTERISTIC_INTERNL_NUM] varchar(30) NULL, 
	[CHARACTERISTIC_NAME] varchar(30) NULL, 
	[CHARACTERISTIC_DESC] varchar(30) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[DOCMT_TYP_DESC] varchar(20) NULL, 
	[CLASS_TYP_DESC] varchar(40) NULL, 
	[CLASS_STATUS_DESC] varchar(40) NULL
);