CREATE TABLE [dbo].[EDW_T_D_SAL_VARCONF_CUR_D] (

	[VARIANT_CONFIG_KEY] int NOT NULL, 
	[SALES_ORDER_ID] varchar(10) NULL, 
	[SALES_ORDER_ITM_ID] varchar(10) NULL, 
	[CONFIG_ID] decimal(18,0) NULL, 
	[IN_RECNO_CD] varchar(22) NULL, 
	[SYMBL_ID] decimal(12,0) NULL, 
	[CHARACTERISTIC_NAME] varchar(60) NULL, 
	[CHARACTERISTIC_VAL] varchar(30) NULL, 
	[CHARACTERISTIC_FROM_VAL] float NULL, 
	[CHARACTERISTIC_TO_VAL] float NULL, 
	[CHARACTERISTIC_INTERNL_NUM] varchar(30) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[CHARACTERISTIC_DESC] varchar(60) NULL
);