CREATE TABLE [dbo].[GL_HIER_SRC] (

	[GRP_NAME] varchar(40) NULL, 
	[NODEID] varchar(6) NULL, 
	[IOBJNM] varchar(10) NULL, 
	[NODENAME] varchar(60) NULL, 
	[LINK] varchar(4) NULL, 
	[PARENTID] varchar(8) NULL, 
	[LANGU] varchar(5) NULL, 
	[TXTSH] varchar(50) NULL, 
	[TXTMD] varchar(50) NULL, 
	[TXTLG] varchar(50) NULL, 
	[INTERVL] varchar(7) NULL, 
	[SIGNCH] varchar(6) NULL, 
	[CHRT_ACCTS] varchar(10) NULL, 
	[FUNC_AREA] varchar(9) NULL, 
	[FIGLGGLAC] varchar(14) NULL, 
	[TO_CHRT_ACCTS] varchar(13) NULL, 
	[TO_FUNC_AREA] varchar(12) NULL, 
	[TO_FIGLGGLAC] varchar(12) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);