CREATE TABLE [dbo].[SALES_SNAP_DAILY_DATA_EXT] (

	[BUKRS_VF] varchar(4) NULL, 
	[BSTNK] varchar(20) NULL, 
	[AUFNR] varchar(12) NULL, 
	[ERDAT] varchar(8) NULL, 
	[AEDAT] varchar(8) NULL, 
	[FKSAA] varchar(1) NULL, 
	[WERKS] varchar(4) NULL, 
	[NETPR] decimal(11,2) NULL, 
	[WAERK] varchar(5) NULL, 
	[PAOBJNR] varchar(10) NULL, 
	[KUNNR] varchar(10) NULL, 
	[VBELN] varchar(10) NULL, 
	[AUDAT] varchar(8) NULL, 
	[MANDT] varchar(3) NULL, 
	[MATNR] varchar(18) NULL, 
	[POSNR] varchar(6) NULL, 
	[KWMENG] decimal(15,3) NULL, 
	[ABGRU] varchar(2) NULL, 
	[VKORG] varchar(4) NULL, 
	[VTWEG] varchar(2) NULL, 
	[SPART] varchar(2) NULL, 
	[PRCTR] varchar(10) NULL, 
	[ZZMARKET_CODE] varchar(3) NULL, 
	[INCOME] decimal(11,2) NULL, 
	[BACKLOG] decimal(11,2) NULL, 
	[DCMNT_CRNCY_INCOME_AMT] decimal(18,3) NULL, 
	[DCMNT_CRNCY_BACKLOG_AMT] decimal(18,3) NULL, 
	[CMPNY_CRNCY_INCOME_AMT] decimal(18,3) NULL, 
	[CMPNY_CRNCY_BACKLOG_AMT] decimal(18,3) NULL, 
	[GRP_CRNCY_INCOME_AMT] decimal(18,3) NULL, 
	[GRP_CRNCY_BACKLOG_AMT] decimal(18,3) NULL
);