CREATE TABLE [dbo].[SAU_T_D_SAL_INVOICE_CUR_D] (

	[INVC_KEY] int NOT NULL, 
	[SALES_ORDER_INVC_ID] varchar(12) NULL, 
	[CMPNY_CD] varchar(4) NULL, 
	[BILLING_TYP_CD] varchar(4) NULL, 
	[BILLING_CTGRY] varchar(1) NULL, 
	[SD_DOCMT_CTGRY] varchar(1) NULL, 
	[SALES_ORGZTN] varchar(4) NULL, 
	[DISTRBN_CHNL] varchar(2) NULL, 
	[DIVISON] varchar(2) NULL, 
	[PRICING_PROC] varchar(6) NULL, 
	[DOCMT_COND_NUM] varchar(10) NULL, 
	[SHIPG_COND] varchar(2) NULL, 
	[PRICE_GROUP] varchar(2) NULL, 
	[CUST_GROUP] varchar(2) NULL, 
	[PRICE_LIST] varchar(2) NULL, 
	[PYMT_REF] varchar(30) NULL, 
	[PYMT_TRMS] varchar(4) NULL, 
	[INCOTERMS] varchar(3) NULL, 
	[INCOTERMS2] varchar(28) NULL, 
	[EXCHG_RT] decimal(9,5) NULL, 
	[NET_VAL] decimal(15,3) NULL, 
	[STATISTICAL_CRNCY] varchar(5) NULL, 
	[INVC_LIST_TYP] varchar(4) NULL, 
	[REF] varchar(16) NULL, 
	[INVC_DATE] date NULL, 
	[CREATED_DATE] date NULL, 
	[CREATED_USR_ID] varchar(12) NULL, 
	[UPDTD_DATE] date NULL, 
	[UPDTD_USR_ID] varchar(12) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL
);