CREATE TABLE [dbo].[SAU_T_D_SAL_PRDORDH_CUR_D] (

	[PROD_ORDER_KEY] int NOT NULL, 
	[PROD_ORDER_NUM] varchar(12) NULL, 
	[CMPNY_CD] varchar(4) NULL, 
	[PROD_PLNT_ID] varchar(4) NULL, 
	[PLNG_PLNT_ID] varchar(4) NULL, 
	[MATRL_ID] varchar(18) NULL, 
	[PROFT_CNTR_ID] varchar(10) NULL, 
	[SALES_ORDER_ID] varchar(10) NULL, 
	[SALES_ORDER_ITM_NUM] varchar(6) NULL, 
	[TASK_LIST_TYP] varchar(1) NULL, 
	[PROD_ORDER_CREATE_DATE] date NULL, 
	[PROD_ORDER_CLS_DATE] date NULL, 
	[PROJ_ID] varchar(8) NULL, 
	[MRP_CNTRLR_CD] varchar(3) NULL, 
	[PROD_ORDER_TYP] varchar(4) NULL, 
	[PROD_CTGRY] varchar(2) NULL, 
	[RESRVTN_NUM] varchar(10) NULL, 
	[SCHLD_START_DATE] date NULL, 
	[SCHLD_FINISH_DATE] date NULL, 
	[ACTUAL_START_DATE] date NULL, 
	[ACTUAL_FINISH_DATE] date NULL, 
	[PLND_RELS_DATE] date NULL, 
	[ACTUAL_RELS_DATE] date NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[CREATION_TS] datetime2(0) NULL
);