CREATE TABLE [dbo].[TEST_BPC_PROFIT_CENTER] (

	[EMPL_NAME] varchar(100) NULL, 
	[EMPL_ID] varchar(50) NOT NULL, 
	[PAY_START_DATE_KEY] int NOT NULL, 
	[PAY_END_DATE_KEY] int NOT NULL, 
	[CHK_DATE_KEY] int NOT NULL, 
	[ACCT_ID] varchar(50) NOT NULL, 
	[ACCT_NAME] varchar(100) NULL, 
	[COST_CNTR_ID] varchar(50) NOT NULL, 
	[COST_CNTR_NAME] varchar(100) NULL, 
	[PROFT_CNTR_ID] varchar(50) NOT NULL, 
	[PROFT_CNTR_NAME] varchar(100) NULL, 
	[PAY_ELEMNT] varchar(50) NOT NULL, 
	[FISCAL_YR] int NOT NULL, 
	[PER] int NOT NULL, 
	[AMT] decimal(20,3) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[PROFT_CNTR_KEY] int NOT NULL, 
	[PROFT_CNTR_ID_1] varchar(50) NOT NULL
);