CREATE TABLE [Propelis].[BRAND_OWNER_CUST] (

	[CUST_KEY] int NOT NULL, 
	[Brand Owner Customer ID] varchar(max) NULL, 
	[Brand Owner Customer Legacy ID] varchar(max) NULL, 
	[Brand Owner Customer Name] varchar(max) NULL, 
	[Brand Owner Cust Line 2 Description] varchar(max) NULL, 
	[Brand Owner Cust Country Code] varchar(max) NULL, 
	[Brand Owner Cust Plant ID] varchar(max) NULL, 
	[Brand Owner Cust Segment ID] varchar(max) NULL, 
	[Brand Owner Cust Industry] varchar(max) NULL, 
	[Brand Owner Cust Vendor ID] varchar(max) NULL, 
	[Brand Owner Cust Group Code] varchar(max) NULL, 
	[Brand Owner Cust Account Group Code] varchar(max) NULL, 
	[Brand Owner Cust Title] varchar(max) NULL, 
	[Brand Owner Cust Search Term] varchar(max) NULL, 
	[Brand Owner Cust Street] varchar(max) NULL, 
	[Brand Owner Cust City] varchar(max) NULL, 
	[Brand Owner Cust Zip Code] varchar(max) NULL, 
	[Brand Owner Cust State Code] varchar(max) NULL, 
	[Brand Owner Cust Region Code] varchar(max) NULL, 
	[Brand Owner Cust Telephone Number 1] varchar(max) NULL, 
	[Brand Owner Cust Telephone Number 2] varchar(max) NULL, 
	[Brand Owner Cust Fax Number Code] varchar(max) NULL, 
	[Brand Owner Cust Tax Number 1 Code] varchar(max) NULL, 
	[Brand Owner Cust Tax Number 2 Code] varchar(max) NULL, 
	[Brand Owner Cust VAT Number Code] varchar(max) NULL, 
	[Brand Owner Cust Credit Limit] decimal(15,3) NULL, 
	[Brand Owner Cust Bonus Rate] decimal(9,3) NULL, 
	[Brand Owner Cust Express Station] varchar(max) NULL, 
	[Brand Owner Cust Transportation Zone] varchar(max) NULL, 
	[Brand Owner Cust Printer Location Characteristics] varchar(max) NULL, 
	[Brand Owner Cust Printer Region Characteristics] varchar(max) NULL, 
	[Brand Owner Cust Printer Site Characteristics] varchar(max) NULL, 
	[Brand Owner Cust Created Date] date NULL, 
	[Brand Owner Cust Created User ID] varchar(max) NULL, 
	[Brand Owner Cust Updated Date] date NULL, 
	[Brand Owner Cust Updated User ID] varchar(max) NULL, 
	[Brand Owner Cust Payment Terms Code] varchar(max) NULL, 
	[Brand Owner Cust Sales Distribution] varchar(max) NULL, 
	[Brand Owner Cust Order Block For Sales Area] varchar(max) NULL, 
	[Brand Owner Cust Delivery Block For Sales Area] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Brand Owner Cust Corporate Group] varchar(max) NULL, 
	[Brand Owner Customer Classification] varchar(max) NULL, 
	[Brand Owner Cust Classification Description] varchar(max) NULL, 
	[Brand Owner Cust Printer Location] varchar(max) NULL, 
	[Brand Owner Cust Printer Site] varchar(max) NULL, 
	[Brand Owner Cust Printer Region] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 01] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 02] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 03] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 04] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 05] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 06] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 07] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 08] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 09] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 10] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 11] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 12] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 13] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 14] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 15] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 16] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 17] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 18] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 19] varchar(max) NULL, 
	[Brand Owner Cust Specific Field Label 20] varchar(max) NULL, 
	[Brand Owner Cust Condition Group 1] varchar(max) NULL, 
	[Brand Owner Cust Industry Code 1] varchar(max) NULL, 
	[Brand Owner Cust Industry Code 2] varchar(max) NULL, 
	[Brand Owner Cust Industry Description] varchar(max) NULL, 
	[Brand Owner Cust Industry Code 1 Description] varchar(max) NULL, 
	[Brand Owner Cust Industry Code 2 Description] varchar(max) NULL, 
	[Brand Owner Assignment to Hierarchy] int NULL, 
	[Brand Owner Cust Account Group Description] varchar(max) NULL, 
	[Brand Owner Cust Region Description] varchar(max) NULL, 
	[Brand Owner Cust Country Description] varchar(max) NULL, 
	[Brand Owner Cust Transportation Zone Description] varchar(max) NULL, 
	[Brand Owner Cust Plant Description] varchar(max) NULL, 
	[Brand Owner Cust Condition Group Description] varchar(max) NULL, 
	[Brand Owner Cust Cental Branding Block] varchar(max) NULL, 
	[Brand Owner Cust Cental Branding Block Description] varchar(max) NULL, 
	[Brand Owner Cust Central Delivery Block] varchar(max) NULL, 
	[Brand Owner Cust Central Delivery Block Description] varchar(max) NULL, 
	[Brand Owner Cust Deletion IndicaOwnerr] varchar(max) NULL, 
	[Brand Owner Cust Central Posting Block] varchar(max) NULL, 
	[Brand Owner Cust Tax Jurisdiction] varchar(max) NULL, 
	[Brand Owner Cust Central Sales Block] varchar(max) NULL, 
	[Brand Owner Cust Central Deletion Indicator] varchar(max) NULL, 
	[Brand Owner Cust Language Key] varchar(max) NULL, 
	[Brand Owner Cust Trading Partner] varchar(max) NULL, 
	[Brand Owner Cust Trading Partner Description] varchar(max) NULL, 
	[Brand Owner Cust Annual Sales] decimal(8,2) NULL, 
	[Brand Owner Cust Annual Sales Year] int NULL, 
	[Brand Owner Cust Sales Currency] varchar(max) NULL, 
	[Brand Owner Cust Sales Currency Description] varchar(max) NULL, 
	[Brand Owner Cust One Time Account Group] varchar(max) NULL, 
	[Brand Owner Cust One Time Account Group Description] varchar(max) NULL, 
	[Brand Owner Cust One Time Indicator] varchar(max) NULL, 
	[Brand Owner Cust Industry Type] varchar(max) NULL, 
	[Brand Owner Cust Business Type] varchar(max) NULL, 
	[Brand Owner Cust DUNS Number] varchar(max) NULL, 
	[Brand Owner Cust DUNS Plus 4] varchar(max) NULL, 
	[Brand Owner City Coordinates] varchar(max) NULL, 
	[Brand Owner Cust Tax Number 4 Code] varchar(max) NULL, 
	[Brand Owner Cust Attribute 3] varchar(max) NULL, 
	[Brand Owner Cust Attribute 3 Description] varchar(max) NULL, 
	[Brand Owner Cust E-Mail Address] varchar(max) NULL, 
	[Brand Owner Cust Mobile Number] varchar(max) NULL, 
	[Brand Owner Cust Search Term 2] varchar(max) NULL, 
	[Brand Owner Cust Street 2] varchar(max) NULL, 
	[Brand Owner Cust Street 3] varchar(max) NULL, 
	[Brand Owner Cust Street 4] varchar(max) NULL, 
	[Brand Owner Cust Street 5] varchar(max) NULL, 
	[Brand Owner Cust PO Box] varchar(max) NULL, 
	[Brand Owner Cust PO Box Postal Code] varchar(max) NULL, 
	[Brand Owner Cust PO Box City] varchar(max) NULL, 
	[Brand Owner Cust Region For PO Box] varchar(max) NULL, 
	[Brand Owner Cust PO Box Country] varchar(max) NULL, 
	[Brand Owner Cust Transport Zone] varchar(max) NULL, 
	[Brand Owner Cust Address Notes] varchar(max) NULL, 
	[Brand Owner Cust Tax Number 3 Code] varchar(max) NULL, 
	[Brand Owner Cust Tax Number 5 Code] varchar(max) NULL, 
	[Brand Owner Cust Industry Code 3] varchar(max) NULL, 
	[Brand Owner Cust Industry Code 3 Description] varchar(max) NULL, 
	[Brand Owner Cust Industry Code 4] varchar(max) NULL, 
	[Brand Owner Cust Industry Code 4 Description] varchar(max) NULL, 
	[Brand Owner Cust Industry Code 5] varchar(max) NULL, 
	[Brand Owner Cust Industry Code 5 Description] varchar(max) NULL, 
	[Brand Owner Cust Central Order Block For Customer] varchar(max) NULL, 
	[Brand Owner Cust Payment Block] varchar(max) NULL
);