CREATE TABLE [Propelis].[EDW_T_FACT_PRD_SERVCST_CUR_D] (

	[SERVC_ORDER_KEY] int NULL, 
	[PRODUCING_PLNT_KEY] int NULL, 
	[Document Number] int NOT NULL, 
	[Period] int NULL, 
	[DOCMT_CRNCY_KEY] int NULL, 
	[CMPNY_CRNCY_KEY] int NULL, 
	[GROUP_CRNCY_KEY] int NULL, 
	[Document Currency Value] decimal(18,3) NULL, 
	[Company Currency Value] decimal(18,3) NULL, 
	[Group Currency Value] decimal(18,3) NULL, 
	[Quantity Total] decimal(18,3) NULL, 
	[UoM] varchar(max) NULL, 
	[Fiscal Year] int NULL, 
	[Value Type] varchar(max) NULL, 
	[COST_ELEMNT_KEY] int NULL, 
	[Transaction Type] varchar(max) NULL, 
	[Partner Object] varchar(max) NULL, 
	[MATRL_KEY] int NULL, 
	[CMPNY_KEY] int NULL, 
	[PRTNR_CMPNY_KEY] int NULL, 
	[Order Type] varchar(max) NULL, 
	[Order Category] varchar(max) NULL, 
	[MAINTENANCE_WRK_CNTR_KEY] int NULL, 
	[Object Class] varchar(max) NULL, 
	[RESPNSBLE_COST_CNTR_KEY] int NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[LOC_PLNT_KEY] int NULL, 
	[Type Of Cost] varchar(max) NULL, 
	[PERSONEL_NUM_KEY] int NULL, 
	[FUNCTNL_AREA_KEY] int NULL, 
	[Debit/Credit Indicator] varchar(max) NULL, 
	[Reference Document Number] varchar(max) NULL, 
	[Controlling Area] varchar(max) NULL, 
	[PLNT_KEY] int NULL, 
	[PSTNG_DATE_KEY] int NULL, 
	[Value Type Description] varchar(max) NULL, 
	[Transaction Type Description] varchar(max) NULL, 
	[Controlling Area Description] varchar(max) NULL, 
	[Is Internal  Posting] varchar(max) NULL, 
	[ACTIVITY_TYP_KEY] varchar(max) NULL, 
	[Posting Row] int NOT NULL, 
	[Is INTER Company Posting] varchar(max) NULL, 
	[Is INTRA Company Posting] varchar(max) NULL, 
	[PRTNR_COST_CNTR_KEY] int NULL, 
	[TCHNCL_COMPLETION_DATE_KEY] int NULL, 
	[DOCMT_DATE_KEY] int NULL, 
	[CREATION_DATE_KEY] int NULL, 
	[Posting Creation Date Timestamp] datetime2(0) NULL, 
	[PERSONNEL_PLANT_REGION_PLANT] varchar(max) NULL, 
	[PLANT_REGION_PLANT] varchar(max) NULL, 
	[LOCATION_PLANT_REGION_PLANT] varchar(max) NULL, 
	[PRODUCING_PLANT_REGION_PLANT] varchar(max) NULL
);