CREATE TABLE [Propelis].[EDW_T_FACT_SAL_TMCONFN_CUR_D] (

	[Controlling Area] varchar(max) NOT NULL, 
	[Document Number] varchar(max) NOT NULL, 
	[Posting Row] int NOT NULL, 
	[Fiscal Year] int NULL, 
	[Version Header] varchar(max) NULL, 
	[Business Transaction Header] varchar(max) NULL, 
	[DOCMT_DATE_KEY] int NULL, 
	[PSTNG_DATE_KEY] int NULL, 
	[Document Type] varchar(max) NULL, 
	[User Name] varchar(max) NULL, 
	[Period] int NULL, 
	[PLNT_KEY] int NULL, 
	[COST_CNTR_KEY] int NULL, 
	[ACTIVITY_TYP_KEY] int NULL, 
	[Value Type] varchar(max) NULL, 
	[Version] varchar(max) NULL, 
	[Business Transaction] varchar(max) NULL, 
	[PERSONEL_NUM_KEY] int NULL, 
	[Activity UOM] varchar(max) NULL, 
	[ACTIVITY_QTY] decimal(38,10) NULL, 
	[Actual Work UOM] varchar(max) NULL, 
	[ACTUAL_WRK] decimal(38,10) NULL, 
	[ACTUAL_WRK_IN_HRS] decimal(38,10) NULL, 
	[Actual Work in Hours UOM] varchar(max) NULL, 
	[Object Number] varchar(max) NULL, 
	[Description] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[PROFT_CNTR_KEY] int NULL, 
	[PLANT_REGION_PLANT] varchar(max) NULL, 
	[PERSONNEL_PLANT_REGION_PLANT] varchar(max) NULL
);