CREATE TABLE [Propelis].[MATRL_ENTERED] (

	[MATRL_KEY] int NOT NULL, 
	[Material Entered ID] varchar(max) NULL, 
	[Material Entered Description] varchar(max) NULL, 
	[Material Entered Legacy Material ID] varchar(max) NULL, 
	[Material Entered Customer ID] varchar(max) NULL, 
	[Material Entered Material Category] varchar(max) NULL, 
	[Material Entered Material Type] varchar(max) NULL, 
	[Material Entered Group] varchar(max) NULL, 
	[Material Entered Base Unit Of Measure] varchar(max) NULL, 
	[Material Entered Industry Sector] varchar(max) NULL, 
	[Material Entered General Item Category Group] varchar(max) NULL, 
	[Material Entered Unit] varchar(max) NULL, 
	[Material Entered Gross Weight] decimal(13,3) NULL, 
	[Material Entered Net Weight] decimal(13,3) NULL, 
	[Material Entered Product Hierarchy] varchar(max) NULL, 
	[Category of Material Entered Category] varchar(max) NULL, 
	[Material Entered Brand] varchar(max) NULL, 
	[Material Entered Sub Brand] varchar(max) NULL, 
	[Material Entered Variant Obsolete] varchar(max) NULL, 
	[Material Entered Variant] varchar(max) NULL, 
	[Material Entered Name 1] varchar(max) NULL, 
	[Material Entered Pack Size] varchar(max) NULL, 
	[Material Entered Pack Type] varchar(max) NULL, 
	[Material Entered Country Name] varchar(max) NULL, 
	[Material Entered Print Method] varchar(max) NULL, 
	[Material Entered Level 4 Product Category Code] varchar(max) NULL, 
	[Material Entered Level 4 Product Category Description] varchar(max) NULL, 
	[Material Entered Level 3 Sub Family Code] varchar(max) NULL, 
	[Material Entered Level 3 Sub Family Description] varchar(max) NULL, 
	[Material Entered Level 2 Family Code] varchar(max) NULL, 
	[Material Entered Level 2 Family Description] varchar(max) NULL, 
	[Material Entered Level 1 Class Code] varchar(max) NULL, 
	[Material Entered Level 1 Class Description] varchar(max) NULL, 
	[Material Entered Created Date] date NULL, 
	[Material Entered Created User ID] varchar(max) NULL, 
	[Material Entered Updated Date] date NULL, 
	[Material Entered Updated User ID] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(1) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Material Entered Group Description] varchar(max) NULL, 
	[Material Entered Group Description 2] varchar(max) NULL, 
	[Category of Material Entered Category Description] varchar(max) NULL, 
	[Material Entered Brand Description] varchar(max) NULL, 
	[Material Entered Sub Brand Description] varchar(max) NULL, 
	[Material Entered Print Method Description] varchar(max) NULL, 
	[Material Entered Level 5 Product Category Code] varchar(max) NULL, 
	[Material Entered Level 5 Product Category Code Description] varchar(max) NULL, 
	[Material Entered Level 6 Product Category Code] varchar(max) NULL, 
	[Material Entered Level 6 Product Category Code Description] varchar(max) NULL, 
	[Material Client Level Deletion Indicator] varchar(max) NULL, 
	[Material Entered PO UoM] varchar(max) NULL, 
	[Material Entered Basic] varchar(max) NULL, 
	[Material Entered Industry Standard Description] varchar(max) NULL, 
	[Material Entered Laboratory/Design Office] varchar(max) NULL, 
	[Material Entered Laboratory/Design Office Description] varchar(max) NULL, 
	[Material Entered Purchasing Value Key] varchar(max) NULL, 
	[Material Entered Storage Condition] varchar(max) NULL, 
	[Material Entered Storage Condition Description] varchar(max) NULL, 
	[Material Entered Temperature Conditions Indicator] varchar(max) NULL, 
	[Material Entered Temperature Conditions Indicator Description] varchar(max) NULL, 
	[Material Entered Transportation Group] varchar(max) NULL, 
	[Material Entered Transportation Group Description] varchar(max) NULL, 
	[Material Entered Hazardous Number] varchar(max) NULL, 
	[Material Entered Source of Supply] varchar(max) NULL, 
	[Material Entered Source of Supply Description] varchar(max) NULL, 
	[Material Entered EAN/UPC Number] varchar(max) NULL, 
	[Material Entered EAN Category] varchar(max) NULL, 
	[Material Entered EAN Category Description] varchar(max) NULL, 
	[Material Entered Length] decimal(13,3) NULL, 
	[Material Entered Width] decimal(13,3) NULL, 
	[Material Entered Height] decimal(13,3) NULL, 
	[Material Entered UoD] varchar(max) NULL, 
	[Material Entered External Group] varchar(max) NULL, 
	[Material Entered External Group Description] varchar(max) NULL, 
	[Material Entered Manufacturer Part Number] varchar(max) NULL, 
	[Material Entered Dangerous Goods Indicator Profile] varchar(max) NULL, 
	[Material Entered Dangerous Goods Ind Profile Desription] varchar(max) NULL, 
	[Material Entered Country of Origin] varchar(max) NULL, 
	[Material Entered Country of Origin Description] varchar(max) NULL, 
	[Material Entered Quality Inspection Group] varchar(max) NULL, 
	[Material Entered Quality Inspection Group Description] varchar(max) NULL, 
	[Material Entered Material Category Description] varchar(max) NULL, 
	[Material Entered Material Type Description] varchar(max) NULL, 
	[Material Entered Product Hierarchy Description] varchar(max) NULL, 
	[Material Entered Industry Sector Description] varchar(max) NULL, 
	[Material Entered General Item Category Group Description] varchar(max) NULL, 
	[MATRL_SALES_TEXT] varchar(max) NULL, 
	[CHARACTERISTIC_22_VAL] varchar(max) NULL, 
	[CLASS_INTERNL_NUM] int NULL, 
	[CLASS_NAME] varchar(max) NULL, 
	[CLASS_TYP] varchar(max) NULL, 
	[CLASS_TYP_DESC] varchar(max) NULL, 
	[CLASS_STATUS] varchar(max) NULL, 
	[CLASS_STATUS_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_1_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_1_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_1_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_1_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_1_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_2_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_2_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_2_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_2_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_2_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_3_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_3_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_3_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_3_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_3_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_4_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_4_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_4_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_4_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_4_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_5_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_5_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_5_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_5_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_5_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_6_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_6_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_6_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_6_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_6_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_7_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_7_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_7_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_7_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_7_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_8_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_8_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_8_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_8_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_8_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_9_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_9_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_9_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_9_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_9_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_10_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_10_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_10_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_10_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_10_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_11_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_11_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_11_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_11_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_11_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_12_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_12_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_12_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_12_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_12_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_13_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_13_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_13_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_13_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_13_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_14_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_14_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_14_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_14_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_14_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_15_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_15_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_15_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_15_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_15_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_16_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_16_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_16_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_16_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_16_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_17_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_17_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_17_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_17_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_17_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_18_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_18_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_18_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_18_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_18_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_19_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_19_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_19_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_19_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_19_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_20_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_20_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_20_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_20_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_20_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_21_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_21_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_21_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_21_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_21_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_22_INTERNL_NUM] int NULL, 
	[CHARACTERISTIC_22_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_22_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_22_VAL_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_23_INTERNL_NUM] varchar(max) NULL, 
	[CHARACTERISTIC_23_NAME] varchar(max) NULL, 
	[CHARACTERISTIC_23_DESC] varchar(max) NULL, 
	[CHARACTERISTIC_23_VAL] varchar(max) NULL, 
	[CHARACTERISTIC_23_VAL_DESC] varchar(max) NULL, 
	[MATRL_DESC_ITALIAN] varchar(max) NULL, 
	[MATRL_X_PLNT_STATUS] varchar(max) NULL, 
	[MATRL_X_PLNT_DESC] varchar(max) NULL
);