CREATE TABLE [Propelis].[PARENT_CUST] (

	[CUST_KEY] int NOT NULL, 
	[Parent Customer ID] varchar(max) NULL, 
	[Parent Customer Legacy ID] varchar(max) NULL, 
	[Parent Customer Name] varchar(max) NULL, 
	[Parent Cust Line 2 Description] varchar(max) NULL, 
	[Parent Cust Country Code] varchar(max) NULL, 
	[Parent Cust Plant ID] varchar(max) NULL, 
	[Parent Cust Segment ID] varchar(max) NULL, 
	[Parent Cust Industry] varchar(max) NULL, 
	[Parent Cust Vendor ID] varchar(max) NULL, 
	[Parent Cust Group Code] varchar(max) NULL, 
	[Parent Cust Account Group Code] varchar(max) NULL, 
	[Parent Cust Title] varchar(max) NULL, 
	[Parent Cust Search Term] varchar(max) NULL, 
	[Parent Cust Street] varchar(max) NULL, 
	[Parent Cust City] varchar(max) NULL, 
	[Parent Cust Zip Code] varchar(max) NULL, 
	[Parent Cust State Code] varchar(max) NULL, 
	[Parent Cust Region Code] varchar(max) NULL, 
	[Parent Cust Telephone Number 1] varchar(max) NULL, 
	[Parent Cust Telephone Number 2] varchar(max) NULL, 
	[Parent Cust Fax Number Code] varchar(max) NULL, 
	[Parent Cust Tax Number 1 Code] varchar(max) NULL, 
	[Parent Cust Tax Number 2 Code] varchar(max) NULL, 
	[Parent Cust VAT Number Code] varchar(max) NULL, 
	[Parent Cust Credit Limit] decimal(15,3) NULL, 
	[Parent Cust Bonus Rate] decimal(9,3) NULL, 
	[Parent Cust Express Station] varchar(max) NULL, 
	[Parent Cust Transportation Zone] varchar(max) NULL, 
	[Parent Cust Printer Location Characteristics] varchar(max) NULL, 
	[Parent Cust Printer Region Characteristics] varchar(max) NULL, 
	[Parent Cust Printer Site Characteristics] varchar(max) NULL, 
	[Parent Cust Created Date] date NULL, 
	[Parent Cust Created User ID] varchar(max) NULL, 
	[Parent Cust Updated Date] date NULL, 
	[Parent Cust Updated User ID] varchar(max) NULL, 
	[Parent Cust Payment Terms Code] varchar(max) NULL, 
	[Parent Cust Sales Distribution] varchar(max) NULL, 
	[Parent Cust Order Block For Sales Area] varchar(max) NULL, 
	[Parent Cust Delivery Block For Sales Area] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Parent Cust Corporate Group] varchar(max) NULL, 
	[Parent Cust Customer Classification] varchar(max) NULL, 
	[Parent Cust Classification Description] varchar(max) NULL, 
	[Parent Cust Printer Location] varchar(max) NULL, 
	[Parent Cust Printer Site] varchar(max) NULL, 
	[Parent Cust Printer Region] varchar(max) NULL, 
	[Parent Cust Specific Field Label 01] varchar(max) NULL, 
	[Parent Cust Specific Field Label 02] varchar(max) NULL, 
	[Parent Cust Specific Field Label 03] varchar(max) NULL, 
	[Parent Cust Specific Field Label 04] varchar(max) NULL, 
	[Parent Cust Specific Field Label 05] varchar(max) NULL, 
	[Parent Cust Specific Field Label 06] varchar(max) NULL, 
	[Parent Cust Specific Field Label 07] varchar(max) NULL, 
	[Parent Cust Specific Field Label 08] varchar(max) NULL, 
	[Parent Cust Specific Field Label 09] varchar(max) NULL, 
	[Parent Cust Specific Field Label 10] varchar(max) NULL, 
	[Parent Cust Specific Field Label 11] varchar(max) NULL, 
	[Parent Cust Specific Field Label 12] varchar(max) NULL, 
	[Parent Cust Specific Field Label 13] varchar(max) NULL, 
	[Parent Cust Specific Field Label 14] varchar(max) NULL, 
	[Parent Cust Specific Field Label 15] varchar(max) NULL, 
	[Parent Cust Specific Field Label 16] varchar(max) NULL, 
	[Parent Cust Specific Field Label 17] varchar(max) NULL, 
	[Parent Cust Specific Field Label 18] varchar(max) NULL, 
	[Parent Cust Specific Field Label 19] varchar(max) NULL, 
	[Parent Cust Specific Field Label 20] varchar(max) NULL, 
	[Parent Cust Condition Group 1] varchar(max) NULL, 
	[Parent Cust Industry Code 1] varchar(max) NULL, 
	[Parent Cust Industry Code 2] varchar(max) NULL, 
	[Parent Cust Industry Description] varchar(max) NULL, 
	[Parent Cust Industry Code 1 Description] varchar(max) NULL, 
	[Parent Cust Industry Code 2 Description] varchar(max) NULL, 
	[Parent Cust Assignment to Hierarchy] int NULL, 
	[Parent Cust Account Group Description] varchar(max) NULL, 
	[Parent Cust Region Description] varchar(max) NULL, 
	[Parent Cust Country Description] varchar(max) NULL, 
	[Parent Cust Transportation Zone Description] varchar(max) NULL, 
	[Parent Cust Plant Description] varchar(max) NULL, 
	[Parent Cust Condition Group Description] varchar(max) NULL, 
	[Parent Cust Cental Billing Block] varchar(max) NULL, 
	[Parent Cust Cental Billing Block Description] varchar(max) NULL, 
	[Parent Cust Central Delivery Block] varchar(max) NULL, 
	[Parent Cust Central Delivery Block Description] varchar(max) NULL, 
	[Parent Cust Deletion Indicator] varchar(max) NULL, 
	[CENTRAL_PSTNG_BLK] varchar(max) NULL, 
	[Parent Cust Tax Jurisdiction] varchar(max) NULL, 
	[Parent Cust Central Sales Block] varchar(max) NULL, 
	[Parent Cust Central Deletion Indicator] varchar(max) NULL, 
	[Parent Cust Language Key] varchar(max) NULL, 
	[Parent Cust Trading Partner] varchar(max) NULL, 
	[Parent Cust Trading Partner Description] varchar(max) NULL, 
	[Parent Cust Annual Sales] decimal(8,2) NULL, 
	[Parent Cust Annual Sales Year] int NULL, 
	[Parent Cust Sales Currency] varchar(max) NULL, 
	[Parent Cust Sales Currency Description] varchar(max) NULL, 
	[Parent Cust One Time Account Group] varchar(max) NULL, 
	[Parent Cust One Time Account Group Description] varchar(max) NULL, 
	[Parent Cust One Time Customer Indicator] varchar(max) NULL, 
	[Parent Cust Industry Type] varchar(max) NULL, 
	[Parent Cust Business Type] varchar(max) NULL, 
	[Parent Cust DUNS Number] varchar(max) NULL, 
	[Parent Cust DUNS Plus 4] varchar(max) NULL, 
	[Parent Cust City Coordinates] varchar(max) NULL, 
	[Parent Cust Tax Number 4 Code] varchar(max) NULL, 
	[Parent Cust Attribute 3] varchar(max) NULL, 
	[Parent Cust Attribute 3 Description] varchar(max) NULL, 
	[Parent Cust E Mail Address] varchar(max) NULL, 
	[Parent Cust Mobile Number] varchar(max) NULL, 
	[Parent Cust Search Term 2] varchar(max) NULL, 
	[Parent Cust Street 2] varchar(max) NULL, 
	[Parent Cust Street 3] varchar(max) NULL, 
	[Parent Cust Street 4] varchar(max) NULL, 
	[Parent Cust Street 5] varchar(max) NULL, 
	[Parent Cust PO Box] varchar(max) NULL, 
	[Parent Cust PO Box Postal Code] varchar(max) NULL, 
	[Parent Cust PO Box City] varchar(max) NULL, 
	[Parent Cust Region For PO Box] varchar(max) NULL, 
	[Parent Cust PO Box Country] varchar(max) NULL, 
	[Parent Cust Transport Zone] varchar(max) NULL, 
	[Parent Cust Address Notes] varchar(max) NULL, 
	[Parent Cust Tax Number 3 Code] varchar(max) NULL, 
	[Parent Cust Tax Number 5 Code] varchar(max) NULL, 
	[Parent Cust Industry Code 3] varchar(max) NULL, 
	[Parent Cust Industry Code 3 Description] varchar(max) NULL, 
	[Parent Cust Industry Code 4] varchar(max) NULL, 
	[Parent Cust Industry Code 4 Description] varchar(max) NULL, 
	[Parent Cust Industry Code 5] varchar(max) NULL, 
	[Parent Cust Industry Code 5 Description] varchar(max) NULL, 
	[Parent Cust Central Order Block For Customer] varchar(max) NULL, 
	[Parent Cust Payment Block] varchar(max) NULL
);