CREATE TABLE [Propelis].[PAYER_CUST] (

	[CUST_KEY] int NOT NULL, 
	[Payer Customer ID] varchar(max) NULL, 
	[Payer Legacy Customer ID] varchar(max) NULL, 
	[Payer Customer Name] varchar(max) NULL, 
	[Payer Cust Line 2 Description] varchar(max) NULL, 
	[Payer Cust Country Code] varchar(max) NULL, 
	[Payer Cust Plant ID] varchar(max) NULL, 
	[Payer Cust Segment ID] varchar(max) NULL, 
	[Payer Cust Industry] varchar(max) NULL, 
	[Payer Cust Vendor ID] varchar(max) NULL, 
	[Payer Cust Customer Group Code] varchar(max) NULL, 
	[Payer Cust Account Group Code] varchar(max) NULL, 
	[Payer Cust Title] varchar(max) NULL, 
	[Payer Cust Search Term] varchar(max) NULL, 
	[Payer Cust Street] varchar(max) NULL, 
	[Payer Cust City] varchar(max) NULL, 
	[Payer Cust Zip Code] varchar(max) NULL, 
	[Payer Cust State Code] varchar(max) NULL, 
	[Payer Cust Region Code] varchar(max) NULL, 
	[Payer Cust Telephone Number 1] varchar(max) NULL, 
	[Payer Cust Telephone Number 2] varchar(max) NULL, 
	[Payer Cust Fax Number Code] varchar(max) NULL, 
	[Payer Cust Tax Number 1 Code] varchar(max) NULL, 
	[Payer Cust Tax Number 2 Code] varchar(max) NULL, 
	[Payer Cust VAT Number Code] varchar(max) NULL, 
	[Payer Cust Credit Limit] decimal(15,3) NULL, 
	[Payer Cust Bonus Rate] decimal(9,3) NULL, 
	[Payer Cust Express Station] varchar(max) NULL, 
	[Payer Cust Transportation Zone] varchar(max) NULL, 
	[Payer Cust Printer Location Characteristics] varchar(max) NULL, 
	[Payer Cust Printer Region Characteristics] varchar(max) NULL, 
	[Payer Cust Printer Site Characteristics] varchar(max) NULL, 
	[Payer Cust Customer Created Date] date NULL, 
	[Payer Cust Created User ID] varchar(max) NULL, 
	[Payer Cust Customer Updated Date] date NULL, 
	[Payer Cust Updated User ID] varchar(max) NULL, 
	[Payer Cust Payment Terms Code] varchar(max) NULL, 
	[Payer Cust Sales Distribution] varchar(max) NULL, 
	[Payer Cust Order Block For Sales Area] varchar(max) NULL, 
	[Payer Cust Delivery Block For Sales Area] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Payer Cust Corporate Group] varchar(max) NULL, 
	[Payer Cust Classification] varchar(max) NULL, 
	[Payer Cust Classification Description] varchar(max) NULL, 
	[Payer Cust Printer Location] varchar(max) NULL, 
	[Payer Cust Printer Site] varchar(max) NULL, 
	[Payer Cust Printer Region] varchar(max) NULL, 
	[Payer Cust Specific Field Label 01] varchar(max) NULL, 
	[Payer Cust Specific Field Label 02] varchar(max) NULL, 
	[Payer Cust Specific Field Label 03] varchar(max) NULL, 
	[Payer Cust Specific Field Label 04] varchar(max) NULL, 
	[Payer Cust Specific Field Label 05] varchar(max) NULL, 
	[Payer Cust Specific Field Label 06] varchar(max) NULL, 
	[Payer Cust Specific Field Label 07] varchar(max) NULL, 
	[Payer Cust Specific Field Label 08] varchar(max) NULL, 
	[Payer Cust Specific Field Label 09] varchar(max) NULL, 
	[Payer Cust Specific Field Label 10] varchar(max) NULL, 
	[Payer Cust Specific Field Label 11] varchar(max) NULL, 
	[Payer Cust Specific Field Label 12] varchar(max) NULL, 
	[Payer Cust Specific Field Label 13] varchar(max) NULL, 
	[Payer Cust Specific Field Label 14] varchar(max) NULL, 
	[Payer Cust Specific Field Label 15] varchar(max) NULL, 
	[Payer Cust Specific Field Label 16] varchar(max) NULL, 
	[Payer Cust Specific Field Label 17] varchar(max) NULL, 
	[Payer Cust Specific Field Label 18] varchar(max) NULL, 
	[Payer Cust Specific Field Label 19] varchar(max) NULL, 
	[Payer Cust Specific Field Label 20] varchar(max) NULL, 
	[Payer Cust Condition Group 1] varchar(max) NULL, 
	[Payer Cust Industry Code 1] varchar(max) NULL, 
	[Payer Cust Industry Code 2] varchar(max) NULL, 
	[Payer Cust Industry Description] varchar(max) NULL, 
	[Payer Cust Industry Code 1 Description] varchar(max) NULL, 
	[Payer Cust Industry Code 2 Description] varchar(max) NULL, 
	[Payer Cust Assignment to Hierarchy] int NULL, 
	[Payer Cust Account Group Description] varchar(max) NULL, 
	[Payer Cust Region Description] varchar(max) NULL, 
	[Payer Cust Country Description] varchar(max) NULL, 
	[Payer Cust Transportation Zone Description] varchar(max) NULL, 
	[Payer Cust Plant Description] varchar(max) NULL, 
	[Payer Cust Condition Group Description] varchar(max) NULL, 
	[Payer Cust Central Delivery Block] varchar(max) NULL, 
	[Payer Cust Central Delivery Block Description] varchar(max) NULL, 
	[Payer Cust Deletion Indicator] varchar(max) NULL, 
	[Payer Cust Central Posting Block] varchar(max) NULL, 
	[Payer Cust Tax Jurisdiction] varchar(max) NULL, 
	[Payer Cust Central Sales Block] varchar(max) NULL, 
	[Payer Cust Central Deletion Indicator] varchar(max) NULL, 
	[Payer Cust Language Key] varchar(max) NULL, 
	[Payer Cust Trading Partner] varchar(max) NULL, 
	[Payer Cust Trading Partner Description] varchar(max) NULL, 
	[Payer Cust Annual Sales] decimal(8,2) NULL, 
	[Payer Cust Annual Sales Year] int NULL, 
	[Payer Cust Sales Currency] varchar(max) NULL, 
	[Payer Cust Sales Currency Description] varchar(max) NULL, 
	[Payer Cust One Time Account Group] varchar(max) NULL, 
	[Payer Cust One Time Account Group Description] varchar(max) NULL, 
	[Payer Cust Industry Type] varchar(max) NULL, 
	[Payer Cust Business Type] varchar(max) NULL, 
	[Payer Cust DUNS Number] varchar(max) NULL, 
	[Payer Cust DUNS Plus 4] varchar(max) NULL, 
	[Payer Cust Cental Billing Block] varchar(max) NULL, 
	[Payer Cust Cental Billing Block Description] varchar(max) NULL, 
	[Payer Cust One Time Indicator] varchar(max) NULL, 
	[Payer Cust City Coordinates] varchar(max) NULL, 
	[Payer Cust Tax Number 4 Code] varchar(max) NULL, 
	[Payer Cust Attribute 3] varchar(max) NULL, 
	[Payer Cust Attribute 3 Description] varchar(max) NULL, 
	[Payer Cust Mobile Number] varchar(max) NULL, 
	[Payer Cust E-Mail Address] varchar(max) NULL, 
	[Payer Cust Search Term 2] varchar(max) NULL, 
	[Payer Cust Street 2] varchar(max) NULL, 
	[Payer Cust Street 3] varchar(max) NULL, 
	[Payer Cust Street 4] varchar(max) NULL, 
	[Payer Cust Street 5] varchar(max) NULL, 
	[Payer Cust PO Box] varchar(max) NULL, 
	[Payer Cust PO Box Postal Code] varchar(max) NULL, 
	[Payer Cust PO Box City] varchar(max) NULL, 
	[Payer Cust Region For PO Box] varchar(max) NULL, 
	[Payer Cust PO Box Country] varchar(max) NULL, 
	[Payer Cust Transport Zone] varchar(max) NULL, 
	[Payer Cust Address Notes] varchar(max) NULL, 
	[Payer Cust Tax Number 3 Code] varchar(max) NULL, 
	[Payer Cust Tax Number 5 Code] varchar(max) NULL, 
	[Payer Cust Industry Code 3] varchar(max) NULL, 
	[Payer Cust Industry Code 3 Description] varchar(max) NULL, 
	[Payer Cust Industry Code 4] varchar(max) NULL, 
	[Payer Cust Industry Code 4 Description] varchar(max) NULL, 
	[Payer Cust Industry Code 5] varchar(max) NULL, 
	[Payer Cust Industry Code 5 Description] varchar(max) NULL, 
	[Payer Cust Central Order Block For Customer] varchar(max) NULL, 
	[Payer Cust Payment Block] varchar(max) NULL
);