CREATE TABLE [Propelis].[PERSON_RESPNSBLE_COST_CNTR] (

	[COST_CNTR_KEY] int NOT NULL, 
	[Person Resp Cost Center ID] varchar(max) NULL, 
	[Person Resp CC Controlling Area ID] varchar(max) NULL, 
	[Person Resp Cost Center Language Type Code] varchar(max) NULL, 
	[Person Resp Cost Center Category] varchar(max) NULL, 
	[Person Resp Cost Center Hierarchy Area] varchar(max) NULL, 
	[Person Resp Cost Center Company Code] varchar(max) NULL, 
	[Person Resp Cost Center Plant ID] varchar(max) NULL, 
	[Person Resp Cost Center Profit Center ID] varchar(max) NULL, 
	[Person Resp Cost Center Currency Code] varchar(max) NULL, 
	[Person Resp Cost Center Adress Line 1] varchar(max) NULL, 
	[Person Resp Cost Center Line 2] varchar(max) NULL, 
	[Person Resp Cost Center Adress Line 3] varchar(max) NULL, 
	[Person Resp Cost Center City Name] varchar(max) NULL, 
	[Person Resp Cost Center District Name] varchar(max) NULL, 
	[Person Resp Cost Center Postal Code] varchar(max) NULL, 
	[Person Resp Cost Center Country Code] varchar(max) NULL, 
	[Person Resp Cost Center Region Code] varchar(max) NULL, 
	[Person Resp Cost Center Person Responsible] varchar(max) NULL, 
	[Person Resp Cost Center Flag Actual Revenues] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[COST_CNTR_NAME] varchar(max) NULL, 
	[Person Resp CC Actual Primary Postings Lock Indicator] varchar(max) NULL, 
	[Person Resp CC Plan Primary Costs Lock Indicator] varchar(max) NULL, 
	[Person Resp Cost Center Business Area] varchar(max) NULL, 
	[Person Resp CC Planning Revenues Lock Indicator] varchar(max) NULL, 
	[Person Resp Cost Center PO Box] varchar(max) NULL, 
	[Person Resp Cost Center Street] varchar(max) NULL, 
	[Person Resp Cost Center User Respnsble] varchar(max) NULL, 
	[Person Resp Cost Center Short Description] varchar(max) NULL, 
	[Person Resp CC Controlling Area Description] varchar(max) NULL, 
	[Person Resp Cost Center Category Description] varchar(max) NULL, 
	[Person Resp Cost Center Company Description] varchar(max) NULL, 
	[Person Resp Cost Center Currency Description] varchar(max) NULL, 
	[Person Resp Cost Center Country Description] varchar(max) NULL, 
	[Person Resp Cost Center Business Area Description] varchar(max) NULL, 
	[Person Resp CC Actual Secondary Cost Lock Indicator] varchar(max) NULL, 
	[Person Resp CC Plan Secondary Cost Lock Indicator] varchar(max) NULL, 
	[Person Resp Cost Center Functional Area] varchar(max) NULL, 
	[Person Resp Cost Center Functional Area Description] varchar(max) NULL, 
	[Person Resp Cost Center Tax Jurisdiction] varchar(max) NULL, 
	[Person Resp Cost Center Function] varchar(max) NULL, 
	[Person Resp Cost Center Plant Description] varchar(max) NULL, 
	[Person Resp Cost Center Created On] date NULL, 
	[Person Resp Cost Center Long Description] varchar(max) NULL, 
	[VALID_TO_DATE] date NULL, 
	[VALID_FROM_DATE] date NULL
);