CREATE TABLE [Propelis].[PLANNING_PLANT] (

	[PLNT_KEY] int NOT NULL, 
	[Planning Plant ID] varchar(max) NULL, 
	[Legacy Planning Plant ID] varchar(max) NULL, 
	[Planning Plant Name] varchar(max) NULL, 
	[Planning Plant Company Code] varchar(max) NULL, 
	[Planning Plant Sales Organization] varchar(max) NULL, 
	[Planning Plant Purchasing Organization] varchar(max) NULL, 
	[Planning Plant Valuation Area] varchar(max) NULL, 
	[Planning Plant Customer Number] varchar(max) NULL, 
	[Planning Plant Vendor Number] varchar(max) NULL, 
	[Planning Plant Factory Calendar Key] varchar(max) NULL, 
	[Planning Plant Line 1 Description] varchar(max) NULL, 
	[Planning Plant Line 2 Description] varchar(max) NULL, 
	[Planning Plant City Name] varchar(max) NULL, 
	[Planning Plant Zip Code] varchar(max) NULL, 
	[Planning Plant Country Code] varchar(max) NULL, 
	[Planning Plant Country Name] varchar(max) NULL, 
	[Planning Plant Tax Jurisdiction] varchar(max) NULL, 
	[ETL SRC SYS CD] varchar(max) NULL, 
	[ETL EFFECTV BEGIN DATE] date NULL, 
	[ETL EFFECTV END DATE] date NULL, 
	[ETL CURR RCD IND] varchar(max) NULL, 
	[ETL CREATED TS] datetime2(0) NULL, 
	[ETL UPDTD TS] datetime2(0) NULL, 
	[Planning Plant IS P001] varchar(max) NULL, 
	[Planning Plant IS P002] varchar(max) NULL, 
	[Planning Plant Company Description] varchar(max) NULL, 
	[Planning Plant Sales Organization Description] varchar(max) NULL, 
	[Planning Plant Factory Calendar Description] varchar(max) NULL, 
	[Planning Plant Purchasing Organization Description] varchar(max) NULL, 
	[Planning Plant Tax Indicator] varchar(max) NULL, 
	[Planning Plant Tax Indicator Description] varchar(max) NULL, 
	[Planning Plant Shipping Receiving Point] varchar(max) NULL, 
	[Planning Plant Shipping Receiving Point Description] varchar(max) NULL
);