CREATE TABLE [Propelis].[RESP_COST_CENTER] (

	[COST_CNTR_KEY] int NOT NULL, 
	[Resp Cost Center ID] varchar(max) NULL, 
	[Resp Cost Center Long Description] varchar(max) NULL, 
	[Resp Cost Center Controlling Area ID] varchar(max) NULL, 
	[Resp Cost Center Language Type Code] varchar(max) NULL, 
	[Resp Cost Center Category] varchar(max) NULL, 
	[Resp Cost Center Hierarchy Area] varchar(max) NULL, 
	[Resp Cost Center Company Code] varchar(max) NULL, 
	[Resp Cost Center Plant] varchar(max) NULL, 
	[Resp Cost Center Proft Center ID] varchar(max) NULL, 
	[Resp Cost Center Currency Code] varchar(max) NULL, 
	[Resp Cost Center Address Line 1] varchar(max) NULL, 
	[Resp Cost Center Address Line 2] varchar(max) NULL, 
	[Resp Cost Center Address Line 3] varchar(max) NULL, 
	[Resp Cost Center City Name] varchar(max) NULL, 
	[Resp Cost Center District Name] varchar(max) NULL, 
	[Resp Cost Center Postal Code] varchar(max) NULL, 
	[Resp Cost Center Country Code] varchar(max) NULL, 
	[Resp Cost Center Region Code] varchar(max) NULL, 
	[Resp Cost Center Person Responsible] varchar(max) NULL, 
	[Resp Cost Center Flag Actual Revenues] varchar(max) NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Resp Cost Center Actual Primary Postings Lock Indicator] varchar(max) NULL, 
	[Resp Cost Center Plan Primary Costs Lock Indicator] varchar(max) NULL, 
	[Resp Cost Center Business Area] varchar(max) NULL, 
	[Resp Cost Center Planning Revenues Lock Indicator] varchar(max) NULL, 
	[Resp Cost Center PO Box] varchar(max) NULL, 
	[Resp Cost Center Street] varchar(max) NULL, 
	[Resp Cost Center User Responsible] varchar(max) NULL, 
	[Resp Cost Center Description] varchar(max) NULL, 
	[Resp Cost Center Short Description] varchar(max) NULL, 
	[Resp Cost Center Controlling Area Description] varchar(max) NULL, 
	[Resp Cost Center Category Description] varchar(max) NULL, 
	[Resp Cost Center Company Description] varchar(max) NULL, 
	[Resp Cost Center Currency Description] varchar(max) NULL, 
	[Resp Cost Center Country Description] varchar(max) NULL, 
	[Resp Cost Center Business Area Description] varchar(max) NULL, 
	[Resp Cost Center Actual Secondary Cost Lock Indicator] varchar(max) NULL, 
	[Resp Cost Center Plan Secondary Cost Lock Indicator] varchar(max) NULL, 
	[Resp Cost Center Functional Area] varchar(max) NULL, 
	[Resp Cost Center Functional Area Description] varchar(max) NULL, 
	[Resp Cost Center Tax Jurisdiction] varchar(max) NULL, 
	[Resp Cost Center Function] varchar(max) NULL, 
	[Resp Cost Center Plant Description] varchar(max) NULL, 
	[Resp Cost Center Created On] date NULL, 
	[Resp Cost Center Valid To Date] date NULL, 
	[Resp Cost Center Valid From Date] date NULL
);