CREATE TABLE [Propelis].[Schld_Start_Date] (

	[DATE_KEY] int NOT NULL, 
	[Schld Start Date] date NULL, 
	[Schld Start Fiscal Year] int NULL, 
	[Schld Start Fiscal Period Number] int NULL, 
	[Schld Start Fiscal Period Code] varchar(max) NULL, 
	[Schld Start Fiscal Quarter Number] int NULL, 
	[Schld Start Fiscal Quarter Code] varchar(max) NULL, 
	[Schld Start Calendar Year] int NULL, 
	[Schld Start Calendar Month Number] int NULL, 
	[Schld Start Calendar Month Code] varchar(max) NULL, 
	[Schld Start Calendar Month Description] varchar(max) NULL, 
	[Schld Start Calendar Quarter Number] int NULL, 
	[Schld Start Calendar Quarter Code] varchar(max) NULL, 
	[Schld Start Calendar Weekday Number] int NULL, 
	[Schld Start Calendar Weekday Name] varchar(max) NULL, 
	[Schld Start Calendar Day In Month] int NULL, 
	[Schld Start Calendar Day In Year] int NULL, 
	[Schld Start Calendar Week] int NULL, 
	[Schld Start Calendar Month In Quarter Number] int NULL, 
	[Schld Start Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Schld Start Current Day Flag] int NULL, 
	[Schld Start Current Day Minus 1 Flag] int NULL, 
	[Schld Start Current Calendar Week Flag] int NULL, 
	[Schld Start Current Calendar Week Minus 1 Flag] int NULL, 
	[Schld Start Current Month Flag] int NULL, 
	[Schld Start Current Month Minus 1 Flag] int NULL, 
	[Schld Start Current Month Minus 12 Flag] int NULL, 
	[Schld Start Current Quarter Flag] int NULL, 
	[Schld Start Current Quarter Minus 1 Flag] int NULL, 
	[Schld Start Current Quarter Minus 4 Flag] int NULL, 
	[Schld Start Current Calendar Year Flag] int NULL, 
	[Schld Start Current Calendar Year Minus 1 Flag] int NULL, 
	[Schld Start Current Calendar Year Minus 2 Flag] int NULL, 
	[Schld Start Current Fiscal Year Flag] int NULL, 
	[Schld Start Current Fiscal Year Minus 1 Flag] int NULL, 
	[Schld Start Current Fiscal Year Minus 2 Flag] int NULL, 
	[Schld Start Current Calendar Year Plus 1 Flag] int NULL, 
	[CURR_FISCAL_YR_PLUS_1_FLG] int NULL, 
	[Schld Start Day In Fiscal Year] int NULL, 
	[Schld Start Date Is Weekday] int NULL, 
	[Schld Start Fiscal Week] int NULL, 
	[Schld Start Current Fiscal Week Flag] int NULL, 
	[Schld Start Current Fiscal Week Minus 1 Flag] int NULL, 
	[Schld Start Fiscal Weekday Number] int NULL, 
	[Schld Start Fiscal Weekday Name] varchar(max) NULL, 
	[Schld Start Current Month Minus 2 Flag] int NULL, 
	[Schld Start Current Fiscal Week Minus 2 Flag] int NULL, 
	[Schld Start Current Fiscal Week Minus 6 Flag] int NULL, 
	[Schld Start Current Fiscal Week Minus 3 Flag] int NULL, 
	[Schld Start Current Fiscal Week Minus 4 Flag] int NULL, 
	[Schld Start Current Fiscal Week Minus 5 Flag] int NULL, 
	[Schld Start Current Fiscal Week Minus 7 Flag] int NULL
);