CREATE TABLE [Propelis].[START_CONSTRAINT_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Start Constraint Date] date NULL, 
	[Start Constraint Fiscal Year] int NULL, 
	[Start Constraint Fiscal Period Number] int NULL, 
	[Start Constraint Fiscal Period Code] varchar(max) NULL, 
	[Start Constraint Fiscal Quarter Number] int NULL, 
	[Start Constraint Fiscal Quarter Code] varchar(max) NULL, 
	[Start Constraint Calendar Year] int NULL, 
	[Start Constraint Calendar Month Number] int NULL, 
	[Start Constraint Calendar Month Code] varchar(max) NULL, 
	[Start Constraint Calendar Month Description] varchar(max) NULL, 
	[Start Constraint Calendar Quarter Number] int NULL, 
	[Start Constraint Calendar Quarter Code] varchar(max) NULL, 
	[Start Constraint Calendar Weekday Number] int NULL, 
	[Start Constraint Calendar Weekday Name] varchar(max) NULL, 
	[Start Constraint Calendar Day In Month] int NULL, 
	[Start Constraint Calendar Day In Year] int NULL, 
	[Start Constraint Calendar Week] int NULL, 
	[Start Constraint Calendar Month In Quarter Number] int NULL, 
	[Start Constraint Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Start Constraint Current Day Flag] int NULL, 
	[Start Constraint Current Day Minus 1 Flag] int NULL, 
	[Start Constraint Current Calendar Week Flag] int NULL, 
	[Start Constraint Current Calendar Week Minus 1 Flag] int NULL, 
	[Start Constraint Current Month Flag] int NULL, 
	[Start Constraint Current Month Minus 1 Flag] int NULL, 
	[Start Constraint Current Month Minus 12 Flag] int NULL, 
	[Start Constraint Current Quarter Flag] int NULL, 
	[Start Constraint Current Quarter Minus 1 Flag] int NULL, 
	[Start Constraint Current Quarter Minus 4 Flag] int NULL, 
	[Start Constraint Current Calendar Year Flag] int NULL, 
	[Start Constraint Current Calendar Year Minus 1 Flag] int NULL, 
	[Start Constraint Current Calendar Year Minus 2 Flag] int NULL, 
	[Start Constraint Current Fiscal Year Flag] int NULL, 
	[Start Constraint Current Fiscal Year Minus 1 Flag] int NULL, 
	[Start Constraint Current Fiscal Year Minus 2 Flag] int NULL, 
	[Start Constraint Current Calendar Year Plus 1 Flag] int NULL, 
	[Start Constraint Current Fiscal Year Plus 1 Flag] int NULL, 
	[Start Constraint Day In Fiscal Year] int NULL, 
	[Start Constraint Date Is Weekday] int NULL, 
	[Start Constraint Fiscal Week] int NULL, 
	[Start Constraint Current Fiscal Week Flag] int NULL, 
	[Start Constraint Current Fiscal Week Minus 1 Flag] int NULL, 
	[Start Constraint Fiscal Weekday Number] int NULL, 
	[Start Constraint Fiscal Weekday Name] varchar(max) NULL, 
	[Start Constraint Current Month Minus 2 Flag] int NULL, 
	[Start Constraint Current Fiscal Week Minus 2 Flag] int NULL, 
	[Start Constraint Current Fiscal Week Minus 6 Flag] int NULL, 
	[Start Constraint Current Fiscal Week Minus 3 Flag] int NULL, 
	[Start Constraint Current Fiscal Week Minus 4 Flag] int NULL, 
	[Start Constraint Current Fiscal Week Minus 5 Flag] int NULL, 
	[Start Constraint Current Fiscal Week Minus 7 Flag] int NULL
);