CREATE TABLE [Propelis].[TECH_COMPLETION_DATE] (

	[DATE_KEY] int NOT NULL, 
	[Tech Completion Date] date NULL, 
	[Tech Completion Fiscal Year] int NULL, 
	[Tech Completion Fiscal Period Number] int NULL, 
	[Tech Completion Fiscal Period Code] varchar(10) NULL, 
	[Tech Completion Fiscal Quarter Number] int NULL, 
	[Tech Completion Fiscal Quarter Code] varchar(10) NULL, 
	[Tech Completion Calendar Year] int NULL, 
	[Tech Completion Calendar Month Number] int NULL, 
	[Tech Completion Calendar Month Code] varchar(10) NULL, 
	[Tech Completion Calendar Month Description] varchar(10) NULL, 
	[Tech Completion Calendar Quarter Number] int NULL, 
	[Tech Completion Calendar Quarter Code] varchar(10) NULL, 
	[Tech Completion Calendar Weekday Number] int NULL, 
	[Tech Completion Calendar Weekday Name] varchar(10) NULL, 
	[Tech Completion Calendar Day In Month] int NULL, 
	[Tech Completion Calendar Day In Year] int NULL, 
	[Tech Completion Calendar Week] int NULL, 
	[Tech Completion Calendar Month In Quarter Number] int NULL, 
	[Tech Completion Calendar Days In Month] int NULL, 
	[ETL_SRC_SYS_CD] varchar(10) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Tech Completion Current Day Flag] int NULL, 
	[Tech Completion Current Day Minus 1 Flag] int NULL, 
	[Tech Completion Current Calendar Week Flag] int NULL, 
	[Tech Completion Current Calendar Week Minus 1 Flag] int NULL, 
	[Tech Completion Current Month Flag] int NULL, 
	[Tech Completion Current Month Minus 1 Flag] int NULL, 
	[Tech Completion Current Month Minus 12 Flag] int NULL, 
	[Tech Completion Current Quarter Flag] int NULL, 
	[Tech Completion Current Quarter Minus 1 Flag] int NULL, 
	[Tech Completion Current Quarter Minus 4 Flag] int NULL, 
	[Tech Completion Current Calendar Year Flag] int NULL, 
	[Tech Completion Current Calendar Year Minus 1 Flag] int NULL, 
	[Tech Completion Current Calendar Year Minus 2 Flag] int NULL, 
	[Tech Completion Current Fiscal Year Flag] int NULL, 
	[Tech Completion Current Fiscal Year Minus 1 Flag] int NULL, 
	[Tech Completion Current Fiscal Year Minus 2 Flag] int NULL, 
	[Tech Completion Current Calendar Year Plus 1 Flag] int NULL, 
	[Tech Completion Current Fiscal Year Plus 1 Flag] int NULL, 
	[Tech Completion Day In Fiscal Year] int NULL, 
	[Tech Completion Date Is Weekday] int NULL, 
	[Tech Completion Fiscal Week] int NULL, 
	[Tech Completion Current Fiscal Week Flag] int NULL, 
	[Tech Completion Current Fiscal Week Minus 1 Flag] int NULL, 
	[Tech Completion Fiscal Weekday Number] int NULL, 
	[Tech Completion Fiscal Weekday Name] varchar(10) NULL, 
	[Tech Completion Current Month Minus 2 Flag] int NULL, 
	[Tech Completion Current Fiscal Week Minus 2 Flag] int NULL, 
	[Tech Completion Current Fiscal Week Minus 6 Flag] int NULL, 
	[Tech Completion Current Fiscal Week Minus 3 Flag] int NULL, 
	[Tech Completion Current Fiscal Week Minus 4 Flag] int NULL, 
	[Tech Completion Current Fiscal Week Minus 5 Flag] int NULL, 
	[Tech Completion Current Fiscal Week Minus 7 Flag] int NULL
);