CREATE TABLE [Propelis].[UNITIZATION_AGENT_VENDOR] (

	[VNDR_KEY] int NOT NULL, 
	[Unitization Agent Vendor ID] varchar(max) NULL, 
	[Unitization Agent Vendor Name] varchar(max) NULL, 
	[Unitization Agent Vendor Description] varchar(max) NULL, 
	[Unitization Agent Vendor Account Group] varchar(max) NULL, 
	[Unitization Agent Vendor Title] varchar(max) NULL, 
	[Unitization Agent Vendor Search Term] varchar(max) NULL, 
	[Unitization Agent Vendor Street] varchar(max) NULL, 
	[Unitization Agent Vendor City Name] varchar(max) NULL, 
	[Unitization Agent Vendor Zip Code] varchar(max) NULL, 
	[Unitization Agent Vendor Country Code] varchar(max) NULL, 
	[Unitization Agent Vendor State] varchar(max) NULL, 
	[Unitization Agent Vendor Telephone Number 1 Code] varchar(max) NULL, 
	[Unitization Agent Vendor Fax Number Code] varchar(max) NULL, 
	[Unitization Agent Vendor Tax Number 1 Code] varchar(max) NULL, 
	[Unitization Agent Vendor Tax Number 2 Code] varchar(max) NULL, 
	[Unitization Agent Vendor VAT Number Code] varchar(max) NULL, 
	[Unitization Agent Vendor Express Station] varchar(max) NULL, 
	[Unitization Agent Vendor Transportation Zone] varchar(max) NULL, 
	[Unitization Agent Vendor Industry] varchar(max) NULL, 
	[Unitization Agent Vendor Created Date] date NULL, 
	[ETL_SRC_SYS_CD] varchar(max) NULL, 
	[ETL_EFFECTV_BEGIN_DATE] date NULL, 
	[ETL_EFFECTV_END_DATE] date NULL, 
	[ETL_CURR_RCD_IND] varchar(max) NULL, 
	[ETL_CREATED_TS] datetime2(0) NULL, 
	[ETL_UPDTD_TS] datetime2(0) NULL, 
	[Unitization Agent Vendor Address Number] varchar(max) NULL, 
	[Unitization Agent Vendor Account Group Description] varchar(max) NULL, 
	[Unitization Agent Vendor Country Description] varchar(max) NULL, 
	[Unitization Agent Vendor Region Description] varchar(max) NULL, 
	[Unitization Agent Vendor Transportation Zone Description] varchar(max) NULL, 
	[Unitization Agent Vendor Industry Description] varchar(max) NULL, 
	[Unitization Agent Vendor Created By] varchar(max) NULL, 
	[Unitization Agent Vendor Central Deletion Indicator] varchar(max) NULL, 
	[Unitization Agent Vendor Central Posting Block] varchar(max) NULL, 
	[Unitization Agent Vendor Central Purchasing Block] varchar(max) NULL, 
	[Unitization Agent Vendor Language Key] varchar(max) NULL, 
	[Unitization Agent Vendor Customer ID] varchar(max) NULL, 
	[Unitization Agent Vendor One Time Account Indicator] varchar(max) NULL, 
	[Unitization Agent Vendor One Time Account Reference Group] varchar(max) NULL, 
	[Unitization Agent Vendor One Time Account Reference Group Desc] varchar(max) NULL, 
	[Unitization Agent Vendor Trading Partner] varchar(max) NULL, 
	[Unitization Agent Vendor Trading Partner Description] varchar(max) NULL, 
	[Unitization Agent Vendor VAT Indicator] varchar(max) NULL, 
	[Unitization Agent Vendor Industry Type] varchar(max) NULL, 
	[Unitization Agent Vendor Business Type] varchar(max) NULL, 
	[Unitization Agent Vendor Payment Block] varchar(max) NULL, 
	[Unitization Agent Vendor Tax Jurisdiction] varchar(max) NULL, 
	[Unitization Agent Vendor Tax Number 3 Code] varchar(max) NULL, 
	[Unitization Agent Vendor Tax Number Type] varchar(max) NULL, 
	[Unitization Agent Vendor Tax Type] varchar(max) NULL, 
	[Unitization Agent Vendor Level 1] varchar(max) NULL, 
	[Unitization Agent Vendor Level 2] varchar(max) NULL, 
	[Unitization Agent Vendor Level 3] varchar(max) NULL, 
	[Unitization Agent Vendor Level 4] varchar(max) NULL, 
	[Unitization Agent Vendor Addressable] varchar(max) NULL, 
	[Unitization Agent Tail Vendor] varchar(max) NULL, 
	[Unitization Agent Vendor Normalized] varchar(max) NULL, 
	[Unitization Agent Vendor Corporate Group] varchar(max) NULL, 
	[Unitization Agent Vendor Account No Alternate Payee] varchar(max) NULL, 
	[Unitization Agent Vendor Email Address] varchar(max) NULL
);