
CREATE TABLE [GLOBAL_EDW].[Propelis].[FORWARDING_AGENT_VENDOR]
(
    [VNDR_KEY] INT NOT NULL,
    [Forwarding Agent Vendor ID] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Name] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Description] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Account Group] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Title] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Search Term] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Street] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor City Name] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Zip Code] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Country Code] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor State] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Telephone Number 1 Code] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Fax Number Code] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Tax Number 1 Code] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Tax Number 2 Code] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor VAT Number Code] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Express Station] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Transportation Zone] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Industry] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Created Date] DATE NULL,
    [ETL_SRC_SYS_CD] VARCHAR(MAX) NULL,
    [ETL_EFFECTV_BEGIN_DATE] DATE NULL,
    [ETL_EFFECTV_END_DATE] DATE NULL,
    [ETL_CURR_RCD_IND] VARCHAR(MAX) NULL,
    [ETL_CREATED_TS] DATETIME2(0) NULL,
    [ETL_UPDTD_TS] DATETIME2(0) NULL,
    [Forwarding Agent Vendor Address Number] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Account Group Description] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Country Description] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Region Description] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Transportation Zone Description] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Industry Description] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Created By] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Central Deletion Indicator] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Central Posting Block] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Central Purchasing Block] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Language Key] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Customer ID] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor One Time Account Indicator] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor One Time Account Reference Group] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor One Time Account Reference Group Desc] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Trading Partner] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Trading Partner Description] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor VAT Indicator] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Industry Type] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Business Type] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Payment Block] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Tax Jurisdiction] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Tax Number 3 Code] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Tax Number Type] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Tax Type] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Level 1] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Level 2] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Level 3] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Level 4] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Addressable] VARCHAR(MAX) NULL,
    [Forwarding Agent Tail Vendor] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Normalized] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Corporate Group] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Account No Alternate Payee] VARCHAR(MAX) NULL,
    [Forwarding Agent Vendor Email Address] VARCHAR(MAX) NULL
)
GO
