table 'Fact General Ledger'
	lineageTag: 2d48d025-470a-4a9e-9e1a-4ab0717215ac
	sourceLineageTag: [Propelis].[EDW_V_FACT_FI_GENLDGR_CUR_D]

	measure 'Company Currency Amount' = sum('Fact General Ledger'[CMPNY_CRNCY_AMT])
		lineageTag: a08b4660-ba1c-4b09-8b28-f147e6866ea5

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Company Currency Tax Amount' = sum('Fact General Ledger'[CMPNY_CRNCY_TAX_AMT])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 641dd056-e379-4b5b-be8a-62be710d58b1

		changedProperty = Name

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Document Currency Amount' = ```
			sum('Fact General Ledger'[DOCMT_CRNCY_AMT])
			
			```
		lineageTag: 70085eaf-435f-445e-a123-362f8d985d3e

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'GL Document Currency Tax Amount' = ```
			sum('Fact General Ledger'[DOCMT_CRNCY_TAX_AMT])
			
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 85a11d84-af8f-464c-b2fd-b360d0fb5ae3

		changedProperty = Name

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'GL Amount for Updating in GL' = ```
			sum('Fact General Ledger'[AMT_FOR_UPDATING_IN_GL])
			
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 7bba84e9-1041-41de-a743-b955fb1df9ec

		changedProperty = Name

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'GL Quantity' = ```
			sum('Fact General Ledger'[QTY])
			
			```
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 41e67333-2924-428e-a5ad-d5ebefeafc46

		changedProperty = Name

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Group Currency Amount' = ```
			sum('Fact General Ledger'[GROUP_CRNCY_AMT])
			
			```
		lineageTag: 67f00526-a626-4b35-afe6-33197c918aed

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Transaction Currency Amount' = ```
			sum('Fact General Ledger'[TRNSCTN_CRNCY_AMT])
			
			```
		lineageTag: 540afe40-e87b-4b31-abea-0c459a954620

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CMPNY_KEY
		dataType: int64
		formatString: 0
		lineageTag: 59d5eaa7-6550-4d63-a733-726e0da7d421
		sourceLineageTag: CMPNY_KEY
		summarizeBy: none
		sourceColumn: CMPNY_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: 1b2f2c6e-5fb6-454f-bdcf-3d35087c731e
		sourceLineageTag: GL Fiscal Year
		summarizeBy: sum
		sourceColumn: GL Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'GL Document Number'
		dataType: string
		lineageTag: 5e41d2bc-9271-459a-9e90-aadacaf3ed49
		sourceLineageTag: GL Document Number
		summarizeBy: none
		sourceColumn: GL Document Number

		annotation SummarizationSetBy = Automatic

	column 'GL Ledger'
		dataType: string
		lineageTag: b1aa8852-ab74-4a71-b550-9054461e60bf
		sourceLineageTag: GL Ledger
		summarizeBy: none
		sourceColumn: GL Ledger

		annotation SummarizationSetBy = Automatic

	column 'GL Document Line Item'
		dataType: int64
		formatString: 0
		lineageTag: adcc95dd-746b-4bfa-adb6-656007cb6dd1
		sourceLineageTag: GL Document Line Item
		summarizeBy: sum
		sourceColumn: GL Document Line Item

		annotation SummarizationSetBy = Automatic

	column 'GL Controlling Area'
		dataType: string
		lineageTag: d71afe02-bfe8-4e75-9e18-9e93ed429525
		sourceLineageTag: GL Controlling Area
		summarizeBy: none
		sourceColumn: GL Controlling Area

		annotation SummarizationSetBy = Automatic

	column COSTEVZ_COST_ELEMNT_KEY
		dataType: int64
		formatString: 0
		lineageTag: c09443d4-e7b7-4e6e-b6d4-769c5ef72947
		sourceLineageTag: COSTEVZ_COST_ELEMNT_KEY
		summarizeBy: none
		sourceColumn: COSTEVZ_COST_ELEMNT_KEY

		annotation SummarizationSetBy = Automatic

	column ICGLGRP_GL_CD
		dataType: int64
		formatString: 0
		lineageTag: 25c0742c-31d1-4de2-8b18-3418b1a6080f
		sourceLineageTag: ICGLGRP_GL_CD
		summarizeBy: sum
		sourceColumn: ICGLGRP_GL_CD

		annotation SummarizationSetBy = Automatic

	column PRTNR_PRFT_CNTR_H_HIER_KEY
		dataType: int64
		formatString: 0
		lineageTag: 36fbe4b4-9201-429e-b4bf-7457c7c0b434
		sourceLineageTag: PRTNR_PRFT_CNTR_H_HIER_KEY
		summarizeBy: none
		sourceColumn: PRTNR_PRFT_CNTR_H_HIER_KEY

		annotation SummarizationSetBy = Automatic

	column COSTCHZ_COST_CNTR_KEY
		dataType: int64
		formatString: 0
		lineageTag: 7603b4de-7484-449b-ab4f-e963426a073f
		sourceLineageTag: COSTCHZ_COST_CNTR_KEY
		summarizeBy: none
		sourceColumn: COSTCHZ_COST_CNTR_KEY

		annotation SummarizationSetBy = Automatic

	column COSTCVZ_COST_CNTR_KEY
		dataType: int64
		formatString: 0
		lineageTag: dae29819-fb91-4ccc-afa9-414dd953c870
		sourceLineageTag: COSTCVZ_COST_CNTR_KEY
		summarizeBy: none
		sourceColumn: COSTCVZ_COST_CNTR_KEY

		annotation SummarizationSetBy = Automatic

	column PROFCHZ_PROFT_CNTR_KEY
		dataType: int64
		formatString: 0
		lineageTag: a2b30be9-1283-4707-9804-2a1281ec58dc
		sourceLineageTag: PROFCHZ_PROFT_CNTR_KEY
		summarizeBy: none
		sourceColumn: PROFCHZ_PROFT_CNTR_KEY

		annotation SummarizationSetBy = Automatic

	column PROFCVZ_PROFT_CNTR_KEY
		dataType: int64
		formatString: 0
		lineageTag: 57f366af-dd8f-45e3-9630-8c1531184598
		sourceLineageTag: PROFCVZ_PROFT_CNTR_KEY
		summarizeBy: none
		sourceColumn: PROFCVZ_PROFT_CNTR_KEY

		annotation SummarizationSetBy = Automatic

	column COSTEHZ_COST_ELEMNT_KEY
		dataType: int64
		formatString: 0
		lineageTag: 511865d9-2c6e-411a-b1c8-71a35bdc7b72
		sourceLineageTag: COSTEHZ_COST_ELEMNT_KEY
		summarizeBy: none
		sourceColumn: COSTEHZ_COST_ELEMNT_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Asset Transaction Type'
		dataType: string
		lineageTag: 6efa4a8a-82e7-47ec-836b-4ced294a12b7
		sourceLineageTag: GL Asset Transaction Type
		summarizeBy: none
		sourceColumn: GL Asset Transaction Type

		annotation SummarizationSetBy = Automatic

	column 'GL Asset Transaction Type Description'
		dataType: string
		lineageTag: eb317ee0-34d8-47d1-8ea9-4776f4725e22
		sourceLineageTag: GL Asset Transaction Type Description
		summarizeBy: none
		sourceColumn: GL Asset Transaction Type Description

		annotation SummarizationSetBy = Automatic

	column 'GL Document Line Item In BSEG'
		dataType: int64
		formatString: 0
		lineageTag: 79933940-b653-406d-a37f-e53bb4859711
		sourceLineageTag: GL Document Line Item In BSEG
		summarizeBy: sum
		sourceColumn: GL Document Line Item In BSEG

		annotation SummarizationSetBy = Automatic

	column PRFT_CNTR_TRD_PRTNR_GRP_ID
		dataType: string
		lineageTag: b5ded6c7-6f4d-4a59-ac9c-9b1650ea0d5b
		sourceLineageTag: PRFT_CNTR_TRD_PRTNR_GRP_ID
		summarizeBy: none
		sourceColumn: PRFT_CNTR_TRD_PRTNR_GRP_ID

		annotation SummarizationSetBy = Automatic

	column PRTNR_PRFT_CNTR_TRD_PRTNR_GRP_ID
		dataType: string
		lineageTag: ca5135ea-1092-4ead-aaeb-29c47ee8fe2c
		sourceLineageTag: PRTNR_PRFT_CNTR_TRD_PRTNR_GRP_ID
		summarizeBy: none
		sourceColumn: PRTNR_PRFT_CNTR_TRD_PRTNR_GRP_ID

		annotation SummarizationSetBy = Automatic

	column PRTNR_PRFT_CNTR_V_HIER_KEY
		dataType: int64
		formatString: 0
		lineageTag: 83f3953a-c542-4c05-80ee-99655543d8a5
		sourceLineageTag: PRTNR_PRFT_CNTR_V_HIER_KEY
		summarizeBy: none
		sourceColumn: PRTNR_PRFT_CNTR_V_HIER_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Base UoM Description'
		dataType: string
		lineageTag: d06aa9ae-90c4-4af9-8e75-d782619ac74f
		sourceLineageTag: GL Base UoM Description
		summarizeBy: none
		sourceColumn: GL Base UoM Description

		annotation SummarizationSetBy = Automatic

	column DOCMT_CRNCY_KEY
		dataType: int64
		formatString: 0
		lineageTag: b531c407-6ee7-4ace-9fa8-ab904c599e13
		sourceLineageTag: DOCMT_CRNCY_KEY
		summarizeBy: none
		sourceColumn: DOCMT_CRNCY_KEY

		annotation SummarizationSetBy = Automatic

	column DOCMT_CRNCY_AMT
		dataType: double
		lineageTag: 3f6fd424-5e2e-49b3-9801-bfae87776d33
		sourceLineageTag: DOCMT_CRNCY_AMT
		summarizeBy: sum
		sourceColumn: DOCMT_CRNCY_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GL_CMPNY_KEY
		dataType: int64
		formatString: 0
		lineageTag: 6d5a9d81-deea-4796-8164-696b65b1b545
		sourceLineageTag: GL_CMPNY_KEY
		summarizeBy: none
		sourceColumn: GL_CMPNY_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Transaction Code'
		dataType: string
		lineageTag: bc49cba5-20ad-4f89-8742-cfe7f77d4c31
		sourceLineageTag: GL Transaction Code
		summarizeBy: none
		sourceColumn: GL Transaction Code

		annotation SummarizationSetBy = Automatic

	column ASSET_KEY
		dataType: int64
		formatString: 0
		lineageTag: 7a169078-c82f-4725-a3ef-1c9be43513b8
		sourceLineageTag: ASSET_KEY
		summarizeBy: none
		sourceColumn: ASSET_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Tax Type Description'
		dataType: string
		lineageTag: 586e3d9c-ff34-4a87-9d2b-349196605dc3
		sourceLineageTag: GL Tax Type Description
		summarizeBy: none
		sourceColumn: GL Tax Type Description

		annotation SummarizationSetBy = Automatic

	column 'GL Account Type Description'
		dataType: string
		lineageTag: 8763bbb8-8ca4-4b33-9fd6-4c9c127dcdda
		sourceLineageTag: GL Account Type Description
		summarizeBy: none
		sourceColumn: GL Account Type Description

		annotation SummarizationSetBy = Automatic

	column 'GL Posting Key Description'
		dataType: string
		lineageTag: 30ac858a-7ec7-4965-8981-e423b9a627a2
		sourceLineageTag: GL Posting Key Description
		summarizeBy: none
		sourceColumn: GL Posting Key Description

		annotation SummarizationSetBy = Automatic

	column 'GL Document Type Description'
		dataType: string
		lineageTag: 7188904b-d77b-42d1-bdd6-4315c8612089
		sourceLineageTag: GL Document Type Description
		summarizeBy: none
		sourceColumn: GL Document Type Description

		annotation SummarizationSetBy = Automatic

	column 'GL Document Status Description'
		dataType: string
		lineageTag: 9717034f-6d4a-49a3-b181-b10f5e52189a
		sourceLineageTag: GL Document Status Description
		summarizeBy: none
		sourceColumn: GL Document Status Description

		annotation SummarizationSetBy = Automatic

	column 'GL Timestamp'
		dataType: int64
		formatString: 0
		lineageTag: b16ba3ff-27cd-4f8c-94b3-bdd915fdaa57
		sourceLineageTag: GL Timestamp
		summarizeBy: sum
		sourceColumn: GL Timestamp

		annotation SummarizationSetBy = Automatic

	column 'GL Ledger Description'
		dataType: string
		lineageTag: 7144b668-ba28-4495-a996-e32863c4719a
		sourceLineageTag: GL Ledger Description
		summarizeBy: none
		sourceColumn: GL Ledger Description

		annotation SummarizationSetBy = Automatic

	column 'GL Controlling Area Description'
		dataType: string
		lineageTag: da9c9a55-5842-4c6a-a2d2-667675783593
		sourceLineageTag: GL Controlling Area Description
		summarizeBy: none
		sourceColumn: GL Controlling Area Description

		annotation SummarizationSetBy = Automatic

	column 'GL Item Category Description'
		dataType: string
		lineageTag: 84aec0ec-f06c-4ad7-a139-9033efecf892
		sourceLineageTag: GL Item Category Description
		summarizeBy: none
		sourceColumn: GL Item Category Description

		annotation SummarizationSetBy = Automatic

	column 'GL Reason Code Description'
		dataType: string
		lineageTag: 5a72da63-5827-4c0f-b491-04e095adc788
		sourceLineageTag: GL Reason Code Description
		summarizeBy: none
		sourceColumn: GL Reason Code Description

		annotation SummarizationSetBy = Automatic

	column 'GL Special GI Indicator Description'
		dataType: string
		lineageTag: c3f5e361-b714-4d38-8256-bf27096ae309
		sourceLineageTag: GL Special GI Indicator Description
		summarizeBy: none
		sourceColumn: GL Special GI Indicator Description

		annotation SummarizationSetBy = Automatic

	column 'GL Transaction Type Description'
		dataType: string
		lineageTag: db05deed-3bea-4aa2-8b2e-666d6c547d20
		sourceLineageTag: GL Transaction Type Description
		summarizeBy: none
		sourceColumn: GL Transaction Type Description

		annotation SummarizationSetBy = Automatic

	column ETL_SRC_SYS_CD
		dataType: string
		lineageTag: d5dd8aeb-cb1e-4adf-aea7-9d6851f78aee
		sourceLineageTag: ETL_SRC_SYS_CD
		summarizeBy: none
		sourceColumn: ETL_SRC_SYS_CD

		annotation SummarizationSetBy = Automatic

	column ETL_CREATED_TS
		dataType: dateTime
		formatString: General Date
		lineageTag: e75e9d30-048a-4b2a-af80-b919669e5bc8
		sourceLineageTag: ETL_CREATED_TS
		summarizeBy: none
		sourceColumn: ETL_CREATED_TS

		annotation SummarizationSetBy = Automatic

	column ETL_UPDTD_TS
		dataType: dateTime
		formatString: General Date
		lineageTag: 805e4c10-9bda-416b-870b-03f160efb177
		sourceLineageTag: ETL_UPDTD_TS
		summarizeBy: none
		sourceColumn: ETL_UPDTD_TS

		annotation SummarizationSetBy = Automatic

	column 'GL Assignment Number for Special Accounts'
		dataType: string
		lineageTag: f3ab4e1c-d346-47f2-99ae-cd017b736690
		sourceLineageTag: GL Assignment Number for Special Accounts
		summarizeBy: none
		sourceColumn: GL Assignment Number for Special Accounts

		annotation SummarizationSetBy = Automatic

	column CMPNY_CRNCY_TAX_AMT
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d3c1b8a1-43ab-4aec-8560-1e538a731da9
		sourceLineageTag: CMPNY_CRNCY_TAX_AMT
		summarizeBy: sum
		sourceColumn: CMPNY_CRNCY_TAX_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column DOCMT_CRNCY_TAX_AMT
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 563e221f-a479-4d1f-9c4c-5c21cc297418
		sourceLineageTag: DOCMT_CRNCY_TAX_AMT
		summarizeBy: sum
		sourceColumn: DOCMT_CRNCY_TAX_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'GL Purchase Order Item ID'
		dataType: int64
		formatString: 0
		lineageTag: fff46a29-65cf-4b80-9683-3e640fe376ae
		sourceLineageTag: GL Purchase Order Item ID
		summarizeBy: count
		sourceColumn: GL Purchase Order Item ID

		annotation SummarizationSetBy = Automatic

	column PURCHS_ORDER_ITM_KEY
		dataType: int64
		formatString: 0
		lineageTag: 8af93174-7a5c-49b7-8031-d674ef436740
		sourceLineageTag: PURCHS_ORDER_ITM_KEY
		summarizeBy: none
		sourceColumn: PURCHS_ORDER_ITM_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Sales Order Item ID'
		dataType: int64
		formatString: 0
		lineageTag: 59533ba9-0d59-4dfe-8465-1a14ac6006c4
		sourceLineageTag: GL Sales Order Item ID
		summarizeBy: count
		sourceColumn: GL Sales Order Item ID

		annotation SummarizationSetBy = Automatic

	column SALES_ORDER_KEY
		dataType: int64
		formatString: 0
		lineageTag: d860da8c-f41d-4dd7-acbc-44bb1e4283d5
		sourceLineageTag: SALES_ORDER_KEY
		summarizeBy: none
		sourceColumn: SALES_ORDER_KEY

		annotation SummarizationSetBy = Automatic

	column LCL_CRNCY_3_KEY
		dataType: int64
		formatString: 0
		lineageTag: a429aa7c-83a1-4455-a700-6493faf510a2
		sourceLineageTag: LCL_CRNCY_3_KEY
		summarizeBy: sum
		sourceColumn: LCL_CRNCY_3_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Parked Document User Name'
		dataType: string
		lineageTag: fddf3b9f-b5e9-493e-9023-a2304dcff699
		sourceLineageTag: GL Parked Document User Name
		summarizeBy: none
		sourceColumn: GL Parked Document User Name

		annotation SummarizationSetBy = Automatic

	column 'GL Document Status'
		dataType: string
		lineageTag: e6667410-e052-4e38-a1dc-23402a406db5
		sourceLineageTag: GL Document Status
		summarizeBy: none
		sourceColumn: GL Document Status

		annotation SummarizationSetBy = Automatic

	column 'GL Reference Document Number'
		dataType: string
		lineageTag: 93f252d7-29c9-483c-8d0b-0fbfa5f26ef8
		sourceLineageTag: GL Reference Document Number
		summarizeBy: none
		sourceColumn: GL Reference Document Number

		annotation SummarizationSetBy = Automatic

	column 'GL Reference Key'
		dataType: string
		lineageTag: f1b79399-83d7-4ae0-aaaa-014360388709
		sourceLineageTag: GL Reference Key
		summarizeBy: none
		sourceColumn: GL Reference Key

		annotation SummarizationSetBy = Automatic

	column 'GL Reference Transaction'
		dataType: string
		lineageTag: 3a89de2d-173f-48b3-89f2-374f72a711ea
		sourceLineageTag: GL Reference Transaction
		summarizeBy: none
		sourceColumn: GL Reference Transaction

		annotation SummarizationSetBy = Automatic

	column BILLING_DOCMT_KEY
		dataType: int64
		formatString: 0
		lineageTag: 3d4edfaa-7a09-4d6d-89b3-0e61b86236db
		sourceLineageTag: BILLING_DOCMT_KEY
		summarizeBy: none
		sourceColumn: BILLING_DOCMT_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Order Number'
		dataType: string
		lineageTag: 8b944d3b-03a7-4498-ad75-a78085b64b78
		sourceLineageTag: GL Order Number
		summarizeBy: none
		sourceColumn: GL Order Number

		annotation SummarizationSetBy = Automatic

	column DOCMT_DATE_KEY
		dataType: int64
		formatString: 0
		lineageTag: 4db9640e-d133-4e5d-a262-ec86a314bdd3
		sourceLineageTag: DOCMT_DATE_KEY
		summarizeBy: none
		sourceColumn: DOCMT_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Document Creation Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: d5cd43e0-1d85-4a6b-a65c-8f842b6ac2f6
		sourceLineageTag: GL Document Creation Date
		summarizeBy: none
		sourceColumn: GL Document Creation Date

		annotation SummarizationSetBy = Automatic

	column 'GL Document Creation Time'
		dataType: int64
		formatString: 0
		lineageTag: f1dc2bf1-0312-4c49-aa7e-81c3b54ce4ba
		sourceLineageTag: GL Document Creation Time
		summarizeBy: sum
		sourceColumn: GL Document Creation Time

		annotation SummarizationSetBy = Automatic

	column 'GL Document Creation User Name'
		dataType: string
		lineageTag: 4290b103-05aa-43e1-b0dd-78939e8dd52e
		sourceLineageTag: GL Document Creation User Name
		summarizeBy: none
		sourceColumn: GL Document Creation User Name

		annotation SummarizationSetBy = Automatic

	column PSTNG_DATE_KEY
		dataType: int64
		formatString: 0
		lineageTag: 891704da-5df8-456b-9bb5-f6281bed16ed
		sourceLineageTag: PSTNG_DATE_KEY
		summarizeBy: none
		sourceColumn: PSTNG_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Business Transaction'
		dataType: string
		lineageTag: 5d7f6892-1b03-46cb-851a-62fd95f91670
		sourceLineageTag: GL Business Transaction
		summarizeBy: none
		sourceColumn: GL Business Transaction

		annotation SummarizationSetBy = Automatic

	column GL_KEY
		dataType: int64
		formatString: 0
		lineageTag: 9c2cede7-53c6-4af9-9800-a593c694c815
		sourceLineageTag: GL_KEY
		summarizeBy: none
		sourceColumn: GL_KEY

		annotation SummarizationSetBy = Automatic

	column MATRL_KEY
		dataType: int64
		formatString: 0
		lineageTag: 426de4ec-bd74-48ad-a8bf-e05219258e52
		sourceLineageTag: MATRL_KEY
		summarizeBy: none
		sourceColumn: MATRL_KEY

		annotation SummarizationSetBy = Automatic

	column PRTNR_PROFT_CNTR_KEY
		dataType: int64
		formatString: 0
		lineageTag: 80865aa1-ddc0-4458-a2c6-bd5ec4fe8c1e
		sourceLineageTag: PRTNR_PROFT_CNTR_KEY
		summarizeBy: none
		sourceColumn: PRTNR_PROFT_CNTR_KEY

		annotation SummarizationSetBy = Automatic

	column PRTNR_SEG_KEY
		dataType: int64
		formatString: 0
		lineageTag: e8d4b165-6704-453f-aad0-39d855889850
		sourceLineageTag: PRTNR_SEG_KEY
		summarizeBy: none
		sourceColumn: PRTNR_SEG_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Document Type'
		dataType: string
		lineageTag: 7a72961b-275b-4f7c-a023-1df052b028dc
		sourceLineageTag: GL Document Type
		summarizeBy: none
		sourceColumn: GL Document Type

		annotation SummarizationSetBy = Automatic

	column 'GL Ledger in GL Accounting'
		dataType: string
		lineageTag: 40878779-1f3b-4fc2-b957-65f342e38b74
		sourceLineageTag: GL Ledger in GL Accounting
		summarizeBy: none
		sourceColumn: GL Ledger in GL Accounting

		annotation SummarizationSetBy = Automatic

	column 'GL Clearing Document Number'
		dataType: string
		lineageTag: ba27c03d-7403-4218-94c8-4d9f0320ed5f
		sourceLineageTag: GL Clearing Document Number
		summarizeBy: none
		sourceColumn: GL Clearing Document Number

		annotation SummarizationSetBy = Automatic

	column PROFT_CNTR_KEY
		dataType: int64
		formatString: 0
		lineageTag: 7b9d4221-2633-4443-bed4-f713872bcddc
		sourceLineageTag: PROFT_CNTR_KEY
		summarizeBy: none
		sourceColumn: PROFT_CNTR_KEY

		annotation SummarizationSetBy = Automatic

	column SEG_KEY
		dataType: int64
		formatString: 0
		lineageTag: 2ca1ae72-c948-4934-a08b-136f4b2a54b3
		sourceLineageTag: SEG_KEY
		summarizeBy: none
		sourceColumn: SEG_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Debit/Credit Indicator'
		dataType: string
		lineageTag: 856a5153-5dd1-4a27-aa9b-37ce39966e08
		sourceLineageTag: GL Debit/Credit Indicator
		summarizeBy: none
		sourceColumn: GL Debit/Credit Indicator

		annotation SummarizationSetBy = Automatic

	column 'GL Posting Key'
		dataType: string
		lineageTag: 6d026308-b2cb-464c-89da-e2cee46b6e80
		sourceLineageTag: GL Posting Key
		summarizeBy: none
		sourceColumn: GL Posting Key

		annotation SummarizationSetBy = Automatic

	column 'GL Invoice Document Number'
		dataType: string
		lineageTag: dbec3dd2-1e24-448e-bdfa-44d98c2babf5
		sourceLineageTag: GL Invoice Document Number
		summarizeBy: none
		sourceColumn: GL Invoice Document Number

		annotation SummarizationSetBy = Automatic

	column COST_CNTR_KEY
		dataType: int64
		formatString: 0
		lineageTag: 78e18134-ead3-46fd-8d2f-dd11d80a916f
		sourceLineageTag: COST_CNTR_KEY
		summarizeBy: none
		sourceColumn: COST_CNTR_KEY

		annotation SummarizationSetBy = Automatic

	column COST_ELEMNT_KEY
		dataType: int64
		formatString: 0
		lineageTag: ee4dcb64-65d5-4a8b-9d73-fc2a417934d1
		sourceLineageTag: COST_ELEMNT_KEY
		summarizeBy: none
		sourceColumn: COST_ELEMNT_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Reference Key for Line Item'
		dataType: string
		lineageTag: a7847bb6-2e1c-4311-8e10-f58f9343199a
		sourceLineageTag: GL Reference Key for Line Item
		summarizeBy: none
		sourceColumn: GL Reference Key for Line Item

		annotation SummarizationSetBy = Automatic

	column 'GL Payment Reference'
		dataType: string
		lineageTag: 7ae5794d-590e-48a2-a96a-8f90d235dc7b
		sourceLineageTag: GL Payment Reference
		summarizeBy: none
		sourceColumn: GL Payment Reference

		annotation SummarizationSetBy = Automatic

	column PLNT_KEY
		dataType: int64
		formatString: 0
		lineageTag: 124a26e4-dab1-446f-9cf5-d0557c5ac3d7
		sourceLineageTag: PLNT_KEY
		summarizeBy: none
		sourceColumn: PLNT_KEY

		annotation SummarizationSetBy = Automatic

	column CLEARING_DATE_KEY
		dataType: int64
		formatString: 0
		lineageTag: f2c7b5cc-6773-468d-b00d-d2559931b582
		sourceLineageTag: CLEARING_DATE_KEY
		summarizeBy: none
		sourceColumn: CLEARING_DATE_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Tax On Sales Or Purchases'
		dataType: string
		lineageTag: 12744536-5113-4502-9210-5fea4bb1edf7
		sourceLineageTag: GL Tax On Sales Or Purchases
		summarizeBy: none
		sourceColumn: GL Tax On Sales Or Purchases

		annotation SummarizationSetBy = Automatic

	column 'GL Tax Type'
		dataType: string
		lineageTag: 7a48c53b-9b99-4b03-9cc5-11fcfdeb48d3
		sourceLineageTag: GL Tax Type
		summarizeBy: none
		sourceColumn: GL Tax Type

		annotation SummarizationSetBy = Automatic

	column TRADING_PRTNR_CMPNY_KEY
		dataType: int64
		formatString: 0
		lineageTag: 36af9d6d-5ba6-4d89-ae6c-6a9300b8ebd1
		sourceLineageTag: TRADING_PRTNR_CMPNY_KEY
		summarizeBy: none
		sourceColumn: TRADING_PRTNR_CMPNY_KEY

		annotation SummarizationSetBy = Automatic

	column WBS_ELEMNT_KEY
		dataType: int64
		formatString: 0
		lineageTag: 6ac2e743-2268-4ae2-b484-f1fffd698ce6
		sourceLineageTag: WBS_ELEMNT_KEY
		summarizeBy: none
		sourceColumn: WBS_ELEMNT_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Account Type'
		dataType: string
		lineageTag: 0f191a82-6cd2-47a7-af3e-e3126fbf50f7
		sourceLineageTag: GL Account Type
		summarizeBy: none
		sourceColumn: GL Account Type

		annotation SummarizationSetBy = Automatic

	column PRTNR_FUNCTNL_AREA_KEY
		dataType: int64
		formatString: 0
		lineageTag: 653963a9-a4c0-4cf8-8e98-780e07bbfb97
		sourceLineageTag: PRTNR_FUNCTNL_AREA_KEY
		summarizeBy: sum
		sourceColumn: PRTNR_FUNCTNL_AREA_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Quantity UOM'
		dataType: string
		lineageTag: 012c6e87-971f-468a-a80d-193510c972e6
		sourceLineageTag: GL Quantity UOM
		summarizeBy: none
		sourceColumn: GL Quantity UOM

		annotation SummarizationSetBy = Automatic

	column FUNCTNL_AREA_KEY
		dataType: int64
		formatString: 0
		lineageTag: 019f1964-ab05-40ba-89ab-765e965b48af
		sourceLineageTag: FUNCTNL_AREA_KEY
		summarizeBy: none
		sourceColumn: FUNCTNL_AREA_KEY

		annotation SummarizationSetBy = Automatic

	column AMT_FOR_UPDATING_IN_GL
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ed80d775-9b33-4ecd-8e63-4910ed4ef7e8
		sourceLineageTag: AMT_FOR_UPDATING_IN_GL
		summarizeBy: sum
		sourceColumn: AMT_FOR_UPDATING_IN_GL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column 'GL Update Currency'
		dataType: string
		lineageTag: 21be8233-3797-4922-a37b-b33a3ff90b15
		sourceLineageTag: GL Update Currency
		summarizeBy: none
		sourceColumn: GL Update Currency

		annotation SummarizationSetBy = Automatic

	column 'GL Is Open Item Management'
		dataType: string
		lineageTag: f2c3f72c-e749-4274-9da5-5ae5ce95824e
		sourceLineageTag: GL Is Open Item Management
		summarizeBy: none
		sourceColumn: GL Is Open Item Management

		annotation SummarizationSetBy = Automatic

	column 'GL Tax Jurisdiction'
		dataType: string
		lineageTag: 1eff4b6a-b62a-4715-8fcc-b51b5a77c680
		sourceLineageTag: GL Tax Jurisdiction
		summarizeBy: none
		sourceColumn: GL Tax Jurisdiction

		annotation SummarizationSetBy = Automatic

	column 'GL Special GL Indicator'
		dataType: string
		lineageTag: d6ba9e8b-d223-4080-96e2-9f66530c3997
		sourceLineageTag: GL Special GL Indicator
		summarizeBy: none
		sourceColumn: GL Special GL Indicator

		annotation SummarizationSetBy = Automatic

	column 'GL Transaction Type'
		dataType: string
		lineageTag: b3143d65-9786-48cd-9f00-bd9295a51cc6
		sourceLineageTag: GL Transaction Type
		summarizeBy: none
		sourceColumn: GL Transaction Type

		annotation SummarizationSetBy = Automatic

	column 'GL Value Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 83dea929-b7a2-41a1-b066-ee700176ceea
		sourceLineageTag: GL Value Date
		summarizeBy: none
		sourceColumn: GL Value Date

		annotation SummarizationSetBy = Automatic

	column 'GL Assignment Number'
		dataType: string
		lineageTag: 89809d22-7f2d-4bea-a754-53fbc5ed5b51
		sourceLineageTag: GL Assignment Number
		summarizeBy: none
		sourceColumn: GL Assignment Number

		annotation SummarizationSetBy = Automatic

	column 'GL Item Text'
		dataType: string
		lineageTag: 634d7705-9ce9-4414-ab06-10e3be36c5c8
		sourceLineageTag: GL Item Text
		summarizeBy: none
		sourceColumn: GL Item Text

		annotation SummarizationSetBy = Automatic

	column QTY
		dataType: decimal
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: ac781e83-4491-445d-945a-08fc816ec771
		sourceLineageTag: QTY
		summarizeBy: sum
		sourceColumn: QTY

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column VNDR_KEY
		dataType: int64
		formatString: 0
		lineageTag: d266c9fc-6919-4178-81e2-2e764ae4f75e
		sourceLineageTag: VNDR_KEY
		summarizeBy: none
		sourceColumn: VNDR_KEY

		annotation SummarizationSetBy = Automatic

	column 'GL Reason Code for Payments'
		dataType: string
		lineageTag: d8057785-911c-4d53-b76f-f8a31e96bc23
		sourceLineageTag: GL Reason Code for Payments
		summarizeBy: none
		sourceColumn: GL Reason Code for Payments

		annotation SummarizationSetBy = Automatic

	column 'GL Reference Date for Settlement'
		dataType: dateTime
		formatString: General Date
		lineageTag: 3103b09d-6fff-4877-96e5-aab966ccccd3
		sourceLineageTag: GL Reference Date for Settlement
		summarizeBy: none
		sourceColumn: GL Reference Date for Settlement

		annotation SummarizationSetBy = Automatic

	column 'GL Business Partner Reference Key'
		dataType: string
		lineageTag: 76fe4c65-6d75-42a2-a8aa-b1067fccf6dc
		sourceLineageTag: GL Business Partner Reference Key
		summarizeBy: none
		sourceColumn: GL Business Partner Reference Key

		annotation SummarizationSetBy = Automatic

	column 'GL Business Partner Reference Key 2'
		dataType: string
		lineageTag: 8a8f5043-f10e-4bab-9a34-1c55c68aaef7
		sourceLineageTag: GL Business Partner Reference Key 2
		summarizeBy: none
		sourceColumn: GL Business Partner Reference Key 2

		annotation SummarizationSetBy = Automatic

	column 'GL Special GL Transaction Type'
		dataType: string
		lineageTag: 839f3623-f5d2-4027-8910-0de4fc73c6f5
		sourceLineageTag: GL Special GL Transaction Type
		summarizeBy: none
		sourceColumn: GL Special GL Transaction Type

		annotation SummarizationSetBy = Automatic

	column 'GL Item Category'
		dataType: string
		lineageTag: 0b2624d8-0f72-4bf4-851e-8452b27ec308
		sourceLineageTag: GL Item Category
		summarizeBy: none
		sourceColumn: GL Item Category

		annotation SummarizationSetBy = Automatic

	column 'GL Fiscal Period'
		dataType: int64
		formatString: 0
		lineageTag: 8f426155-e3f4-41dc-bae8-faa381d5639c
		sourceLineageTag: GL Fiscal Period
		summarizeBy: sum
		sourceColumn: GL Fiscal Period

		annotation SummarizationSetBy = Automatic

	column 'GL Document Line Item ID'
		dataType: string
		lineageTag: 50dbffa5-fd1c-45e6-9ee7-eae5ce041c8c
		sourceLineageTag: GL Document Line Item ID
		summarizeBy: none
		sourceColumn: GL Document Line Item ID

		annotation SummarizationSetBy = Automatic

	column 'GL Clearing Fiscal Year'
		dataType: int64
		formatString: 0
		lineageTag: a0cba4e6-ff04-4bd5-be63-3f882ed64f52
		sourceLineageTag: GL Clearing Fiscal Year
		summarizeBy: sum
		sourceColumn: GL Clearing Fiscal Year

		annotation SummarizationSetBy = Automatic

	column 'GL Clearing Item'
		dataType: int64
		formatString: 0
		lineageTag: 510b3156-64d5-4bbc-a07c-05bdfb3353f3
		sourceLineageTag: GL Clearing Item
		summarizeBy: sum
		sourceColumn: GL Clearing Item

		annotation SummarizationSetBy = Automatic

	column CUST_KEY
		dataType: int64
		formatString: 0
		lineageTag: 5481f1aa-bf99-412a-8e03-255ca23e9587
		sourceLineageTag: CUST_KEY
		summarizeBy: none
		sourceColumn: CUST_KEY

		annotation SummarizationSetBy = Automatic

	column TRNSCTN_CRNCY_AMT
		dataType: double
		lineageTag: 32a5800c-0529-42a1-91eb-eaa5d80f1a0d
		sourceLineageTag: TRNSCTN_CRNCY_AMT
		summarizeBy: sum
		sourceColumn: TRNSCTN_CRNCY_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CMPNY_CRNCY_AMT
		dataType: double
		lineageTag: babb0463-6aa1-4539-b612-1a20a6503ad3
		sourceLineageTag: CMPNY_CRNCY_AMT
		summarizeBy: sum
		sourceColumn: CMPNY_CRNCY_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column GROUP_CRNCY_AMT
		dataType: double
		lineageTag: 94ff1306-61cd-4c28-a54f-3b8b126c403e
		sourceLineageTag: GROUP_CRNCY_AMT
		summarizeBy: sum
		sourceColumn: GROUP_CRNCY_AMT

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column TRNSCTN_CRNCY_KEY
		dataType: int64
		formatString: 0
		lineageTag: e48ead16-e92f-4fe0-935a-efd1319d97b3
		sourceLineageTag: TRNSCTN_CRNCY_KEY
		summarizeBy: none
		sourceColumn: TRNSCTN_CRNCY_KEY

		annotation SummarizationSetBy = Automatic

	column CMPNY_CRNCY_KEY
		dataType: int64
		formatString: 0
		lineageTag: 94bcea6c-727a-4c9c-8022-93d01d254b56
		sourceLineageTag: CMPNY_CRNCY_KEY
		summarizeBy: none
		sourceColumn: CMPNY_CRNCY_KEY

		annotation SummarizationSetBy = Automatic

	column GROUP_CRNCY_KEY
		dataType: int64
		formatString: 0
		lineageTag: 704a7594-a853-4822-aa9a-45af2d276d60
		sourceLineageTag: GROUP_CRNCY_KEY
		summarizeBy: none
		sourceColumn: GROUP_CRNCY_KEY

		annotation SummarizationSetBy = Automatic

	partition 'Fact General Ledger' = entity
		mode: directLake
		source
			entityName: EDW_V_FACT_FI_GENLDGR_CUR_D
			schemaName: Propelis
			expressionSource: 'DirectLake - GLOBAL_EDW'

	changedProperty = Name

