CREATE   PROCEDURE [Propelis].[Proc_EDW_T_FACT_SAL_SALORDD_CUR_D]
AS 
BEGIN 
 UPDATE T 
    SET 
T.[Sales Order ID]=S.[Sales Order ID],
T.[Sales Order Item ID]=S.[Sales Order Item ID],
T.[DOCMT_DATE_KEY]=S.[DOCMT_DATE_KEY],
T.[REQD_DLVRY_DATE_KEY]=S.[REQD_DLVRY_DATE_KEY],
T.[PLNT_KEY]=S.[PLNT_KEY],
T.[SOLDTO_CUST_KEY]=S.[SOLDTO_CUST_KEY],
T.[BILLTO_CUST_KEY]=S.[BILLTO_CUST_KEY],
T.[PAYER_CUST_KEY]=S.[PAYER_CUST_KEY],
T.[SHIPTO_CUST_KEY]=S.[SHIPTO_CUST_KEY],
T.[BRAND_OWNER_CUST_KEY]=S.[BRAND_OWNER_CUST_KEY],
T.[CUST_CONTACT_KEY]=S.[CUST_CONTACT_KEY],
T.[SALES_PERSON_PERSONEL_KEY]=S.[SALES_PERSON_PERSONEL_KEY],
T.[PERSON_RESPNSBLE_PERSONEL_KEY]=S.[PERSON_RESPNSBLE_PERSONEL_KEY],
T.[MATRL_KEY]=S.[MATRL_KEY],
T.[PROFT_CNTR_KEY]=S.[PROFT_CNTR_KEY],
T.[CUST_CMPNY_KEY]=S.[CUST_CMPNY_KEY],
T.[CUST_SALES_AREA_KEY]=S.[CUST_SALES_AREA_KEY],
T.[SEG_KEY]=S.[SEG_KEY],
T.[SALES_AREA_KEY]=S.[SALES_AREA_KEY],
T.[DOCMT_CRNCY_KEY]=S.[DOCMT_CRNCY_KEY],
T.[CMPNY_CRNCY_KEY]=S.[CMPNY_CRNCY_KEY],
T.[GROUP_CRNCY_KEY]=S.[GROUP_CRNCY_KEY],
T.[SALES_ORDER_QTY]=S.[SALES_ORDER_QTY],
T.[SO Unit Of Measure]=S.[SO Unit Of Measure],
T.[DOCMT_CRNCY_NET_PRICE]=S.[DOCMT_CRNCY_NET_PRICE],
T.[DOCMT_CRNCY_NET_VAL_AMT]=S.[DOCMT_CRNCY_NET_VAL_AMT],
T.[DOCMT_CRNCY_TAX_AMT]=S.[DOCMT_CRNCY_TAX_AMT],
T.[CMPNY_CRNCY_NET_VAL_AMT]=S.[CMPNY_CRNCY_NET_VAL_AMT],
T.[GROUP_CRNCY_NET_VAL_AMT]=S.[GROUP_CRNCY_NET_VAL_AMT],
T.[SO Shipping Point]=S.[SO Shipping Point],
T.[SO Reason For Rejection]=S.[SO Reason For Rejection],
T.[SO Overall Status]=S.[SO Overall Status],
T.[SO Delivery Status]=S.[SO Delivery Status],
T.[SO Order Related Bill Status]=S.[SO Order Related Bill Status],
T.[Sales Order Header Encoway Id]=S.[Sales Order Header Encoway Id],
T.[SO Encoway Version]=S.[SO Encoway Version],
T.[SO Encoway Part]=S.[SO Encoway Part],
T.[SO Encoway Description]=S.[SO Encoway Description],
T.[SO Encoway Number]=S.[SO Encoway Number],
T.[SO Material Description]=S.[SO Material Description],
T.[SO Delivery Group]=S.[SO Delivery Group],
T.[QTY_NETTED]=S.[QTY_NETTED],
T.[SO Reason For Rejection Description]=S.[SO Reason For Rejection Description],
T.[SO Shipping Condition]=S.[SO Shipping Condition],
T.[SO Inco Terms]=S.[SO Inco Terms],
T.[SO Inco Terms Description]=S.[SO Inco Terms Description],
T.[SO Inco Terms 2]=S.[SO Inco Terms 2],
T.[SO Billing Date]=S.[SO Billing Date],
T.[ETL_CREATED_TS]=S.[ETL_CREATED_TS],
T.[ETL_UPDTD_TS]=S.[ETL_UPDTD_TS],
T.[CYLINDER_OWNER_CUST_KEY]=S.[CYLINDER_OWNER_CUST_KEY],
T.[SO Usage]=S.[SO Usage],
T.[SO Higher-Level Item]=S.[SO Higher-Level Item],
T.[SO Alternative to Item]=S.[SO Alternative to Item],
T.[MATRL_ENTERED_KEY]=S.[MATRL_ENTERED_KEY],
T.[SO Reference Document]=S.[SO Reference Document],
T.[SO Reference Item]=S.[SO Reference Item],
T.[SO Reference Status]=S.[SO Reference Status],
T.[SO Total Reference Status]=S.[SO Total Reference Status],
T.[SO Billing Block]=S.[SO Billing Block],
T.[PERSON_RESPNSBLE_COST_CNTR_KEY]=S.[PERSON_RESPNSBLE_COST_CNTR_KEY],
T.[PARNT_CUST_KEY]=S.[PARNT_CUST_KEY],
T.[CREATION_DATE_KEY]=S.[CREATION_DATE_KEY],
T.[SO Creation Timestamp]=S.[SO Creation Timestamp],
T.[SO Delivery Status Indicator]=S.[SO Delivery Status Indicator],
T.[SO Sales UoM]=S.[SO Sales UoM],
T.[SALES_TRGT_QTY]=S.[SALES_TRGT_QTY],
T.[SO Target Quantity UoM]=S.[SO Target Quantity UoM],
T.[DLVRD_QTY]=S.[DLVRD_QTY],
T.[SO Is Sales Schedule Line Created]=S.[SO Is Sales Schedule Line Created],
T.[DOCMT_CHARS_ENCOWAY_JS_HDR_KEY]=S.[DOCMT_CHARS_ENCOWAY_JS_HDR_KEY],
T.[EMPL_RESPNSBLE_2_KEY]=S.[EMPL_RESPNSBLE_2_KEY],
T.[SO BOM Item Number]=S.[SO BOM Item Number],
T.[CUST_MATRL_INFO_RCD_KEY]=S.[CUST_MATRL_INFO_RCD_KEY],
T.[SO Changed On Date]=S.[SO Changed On Date],
T.[SO Relevant For Billing]=S.[SO Relevant For Billing],
T.[SO Item Is Relevant For Delivery]=S.[SO Item Is Relevant For Delivery],
T.[WBS_ELEMNT_KEY]=S.[WBS_ELEMNT_KEY],
T.[AGENCY_CUST_KEY]=S.[AGENCY_CUST_KEY],
T.[PRINTER_CUST_KEY]=S.[PRINTER_CUST_KEY],
T.[SUPLR_CUST_KEY]=S.[SUPLR_CUST_KEY],
T.[SO Billing Status Of Delivery]=S.[SO Billing Status Of Delivery],
T.[SO Approval]=S.[SO Approval],
T.[SO Arrangement]=S.[SO Arrangement],
T.[SO Delivery]=S.[SO Delivery],
T.[SO Fixed DET]=S.[SO Fixed DET],
T.[RSLTS_ANALYSIS_KEY]=S.[RSLTS_ANALYSIS_KEY],
T.[SO Purchase Order Item Number]=S.[SO Purchase Order Item Number],
T.[SO Line Item System Status]=S.[SO Line Item System Status],
T.[SO Overall Status Description]=S.[SO Overall Status Description],
T.[Delivery Status Description]=S.[Delivery Status Description],
T.[SO Order Related Bill Status Description]=S.[SO Order Related Bill Status Description],
T.[SO Shipping Condition Description]=S.[SO Shipping Condition Description],
T.[SO Usage Description]=S.[SO Usage Description],
T.[SO Reference Status Description]=S.[SO Reference Status Description],
T.[SO Total Reference Status Description]=S.[SO Total Reference Status Description],
T.[SO Billing Block Description]=S.[SO Billing Block Description],
T.[SO Delivery Status Indicator Description]=S.[SO Delivery Status Indicator Description],
T.[SO Relevant For Billing Description]=S.[SO Relevant For Billing Description],
T.[SO Billing Status Of Delivery Description]=S.[SO Billing Status Of Delivery Description],
T.[SO Results Analysis Description]=S.[SO Results Analysis Description],
T.[SO Internal Customer Reference Number]=S.[SO Internal Customer Reference Number],
T.[Product Hierarchy]=S.[Product Hierarchy],
T.[SO Sold To Purchase Order Number]=S.[SO Sold To Purchase Order Number],
T.[SO Sold To Purchase Order Date]=S.[SO Sold To Purchase Order Date],
T.[SO Ship To Purchase Order Number]=S.[SO Ship To Purchase Order Number],
T.[SO Ship To Purchase Order Date]=S.[SO Ship To Purchase Order Date],
T.[SO Customer Condition Group 1]=S.[SO Customer Condition Group 1],
T.[SO Customer Condition Group 1 Description]=S.[SO Customer Condition Group 1 Description],
T.[SO Customer Material Number]=S.[SO Customer Material Number],
T.[EMPL_RESPNSBLE_KEY]=S.[EMPL_RESPNSBLE_KEY],
T.[CUST_POJECT_MGR_KEY]=S.[CUST_POJECT_MGR_KEY],
T.[SO Item Category]=S.[SO Item Category],
T.[SO Item Category Description]=S.[SO Item Category Description],
T.[SHIP_TO_ADDR_KEY]=S.[SHIP_TO_ADDR_KEY],
T.[SO Delivery Priority Code]=S.[SO Delivery Priority Code],
T.[SO Delivery Priority Description]=S.[SO Delivery Priority Description],
T.[CREATED_BY]=S.[CREATED_BY],
T.[UNITIZATION_AGENT_VNDR_KEY]=S.[UNITIZATION_AGENT_VNDR_KEY],
T.[SO Designable E Services Flag]=S.[SO Designable E Services Flag],
T.[SO Agreed Delivery Time]=S.[SO Agreed Delivery Time],
T.[SO Deceased Name]=S.[SO Deceased Name],
T.[SO Customer Purchase Order Type]=S.[SO Customer Purchase Order Type],
T.[SO Customer Purchase Order Type Description]=S.[SO Customer Purchase Order Type Description],
T.[ORDER_KEY]=S.[ORDER_KEY],
T.[SO Price Group]=S.[SO Price Group],
T.[SO Price Group Description]=S.[SO Price Group Description],
T.[CMLT_CONFIRMED_QTY_IN_BASE_UNIT]=S.[CMLT_CONFIRMED_QTY_IN_BASE_UNIT],
T.[SO Base Unit Of Measure]=S.[SO Base Unit Of Measure],
T.[COMPANY_INFO_CMPNY_CD_KEY]=S.[COMPANY_INFO_CMPNY_CD_KEY],
T.[SAL_SALORDH_INVOICE_CREATION_DATE_KEY]=S.[SAL_SALORDH_INVOICE_CREATION_DATE_KEY],
T.[SAL_SALORDH_CREATED_DATE_KEY]=S.[SAL_SALORDH_CREATED_DATE_KEY],
T.[PLANT_REGION_PLANT_ID]=S.[PLANT_REGION_PLANT_ID],
T.[RESPNSBLE_COST_CNTR_V_HEIR_COST_CNTR_KEY]=S.[RESPNSBLE_COST_CNTR_V_HEIR_COST_CNTR_KEY],
T.[PERSON_RESPNSBLE_COST_CNTR_H_HEIR_KEY]=S.[PERSON_RESPNSBLE_COST_CNTR_H_HEIR_KEY],
T.[FORWARDING_AGENT_VENDOR_KEY]=S.[FORWARDING_AGENT_VENDOR_KEY],
T.[ORDER_FOR_CUSTOMER_ADDR_KEY]=S.[ORDER_FOR_CUSTOMER_ADDR_KEY],
T.[SO_PARENT_CUST_KEY]=S.[SO_PARENT_CUST_KEY],
T.[MST_PRTHRCY_PRDT_HIERCHY_CD]=S.[MST_PRTHRCY_PRDT_HIERCHY_CD],
T.[SOIPTNR_KEY]=S.[SOIPTNR_KEY],
T.[V_D_SAL_PRDVCON_KEY]=S.[V_D_SAL_PRDVCON_KEY]

FROM 
        [GLOBAL_EDW].[Propelis].[EDW_T_FACT_SAL_SALORDD_CUR_D] T
    INNER JOIN 
        [GLOBAL_EDW].[Propelis].[TEMP_EDW_T_FACT_SAL_SALORDD_CUR_D] S
    ON 
        	T.[SALES_ORDER_KEY]=S.[SALES_ORDER_KEY] AND     
		T.[SALES_ORDER_ID]=S.[SALES_ORDER_ID] AND
		T.[SALES_ORDER_ITM_ID]=S.[SALES_ORDER_ITM_ID] AND
		T.[CMPNY_KEY]=S.[CMPNY_KEY] AND
		T.[ETL_SRC_SYS_CD]=S.[ETL_SRC_SYS_CD] ;


INSERT INTO [GLOBAL_EDW].[Propelis].[TEMP_EDW_T_FACT_SAL_SALORDD_CUR_D] 
( [SO Changed On Date],
			[SO Relevant For Billing],
			[SO Item Is Relevant For Delivery],
			[WBS_ELEMNT_KEY],
			[AGENCY_CUST_KEY],
			[PRINTER_CUST_KEY],
			[SUPLR_CUST_KEY],
			[SO Billing Status Of Delivery],
			[SO Approval],
			[SO Arrangement],
			[SO Delivery],
			[SO Fixed DET],
			[RSLTS_ANALYSIS_KEY],
			[SO Purchase Order Item Number],
			[SO Line Item System Status],
			[SO Overall Status Description],
			[Delivery Status Description],
			[SO Order Related Bill Status Description],
			[SO Shipping Condition Description],
			[SO Usage Description],
			[SO Reference Status Description],
			[SO Total Reference Status Description],
			[SO Billing Block Description],
			[SO Delivery Status Indicator Description],
			[SO Relevant For Billing Description],
			[SO Billing Status Of Delivery Description],
			[SO Results Analysis Description],
			[SO Internal Customer Reference Number],
			[Product Hierarchy],
			[SO Sold To Purchase Order Number],
			[SO Sold To Purchase Order Date],
			[SO Ship To Purchase Order Number],
			[SO Ship To Purchase Order Date],
			[SO Customer Condition Group 1],
			[SO Customer Condition Group 1 Description],
			[SO Customer Material Number],
			[EMPL_RESPNSBLE_KEY],
			[CUST_POJECT_MGR_KEY],
			[SO Item Category],
			[SO Item Category Description],
			[SHIP_TO_ADDR_KEY],
			[SO Delivery Priority Code],
			[SO Delivery Priority Description],
			[CREATED_BY],
			[UNITIZATION_AGENT_VNDR_KEY],
			[SO Designable E Services Flag],
			[SO Agreed Delivery Time],
			[SO Deceased Name],
			[SO Customer Purchase Order Type],
			[SO Customer Purchase Order Type Description],
			[ORDER_KEY],
			[SO Price Group],
			[SO Price Group Description],
			[CMLT_CONFIRMED_QTY_IN_BASE_UNIT],
			[SO Base Unit Of Measure],
			[COMPANY_INFO_CMPNY_CD_KEY],
			[SAL_SALORDH_INVOICE_CREATION_DATE_KEY],
			[SAL_SALORDH_CREATED_DATE_KEY],
			[PLANT_REGION_PLANT_ID],
			[RESPNSBLE_COST_CNTR_V_HEIR_COST_CNTR_KEY],
			[PERSON_RESPNSBLE_COST_CNTR_H_HEIR_KEY],
			[FORWARDING_AGENT_VENDOR_KEY],
			[ORDER_FOR_CUSTOMER_ADDR_KEY],
			[SO_PARENT_CUST_KEY],
			[SALES_ORDER_ID],
			[SALES_ORDER_ITM_ID],
			[MST_PRTHRCY_PRDT_HIERCHY_CD],
			[SOIPTNR_KEY],
			[V_D_SAL_PRDVCON_KEY],
			[SALES_ORDER_KEY],
			[Sales Order ID],
			[Sales Order Item ID],
			[DOCMT_DATE_KEY],
			[REQD_DLVRY_DATE_KEY],
			[CMPNY_KEY],
			[PLNT_KEY],
			[SOLDTO_CUST_KEY],
			[BILLTO_CUST_KEY],
			[PAYER_CUST_KEY],
			[SHIPTO_CUST_KEY],
			[BRAND_OWNER_CUST_KEY],
			[CUST_CONTACT_KEY],
			[SALES_PERSON_PERSONEL_KEY],
			[PERSON_RESPNSBLE_PERSONEL_KEY],
			[MATRL_KEY],
			[PROFT_CNTR_KEY],
			[CUST_CMPNY_KEY],
			[CUST_SALES_AREA_KEY],
			[SEG_KEY],
			[SALES_AREA_KEY],
			[DOCMT_CRNCY_KEY],
			[CMPNY_CRNCY_KEY],
			[GROUP_CRNCY_KEY],
			[SALES_ORDER_QTY],
			[SO Unit Of Measure],
			[DOCMT_CRNCY_NET_PRICE],
			[DOCMT_CRNCY_NET_VAL_AMT],
			[DOCMT_CRNCY_TAX_AMT],
			[CMPNY_CRNCY_NET_VAL_AMT],
			[GROUP_CRNCY_NET_VAL_AMT],
			[SO Shipping Point],
			[SO Reason For Rejection],
			[SO Overall Status],
			[SO Delivery Status],
			[SO Order Related Bill Status],
			[Sales Order Header Encoway Id],
			[SO Encoway Version],
			[SO Encoway Part],
			[SO Encoway Description],
			[SO Encoway Number],
			[SO Material Description],
			[SO Delivery Group],
			[QTY_NETTED],
			[SO Reason For Rejection Description],
			[SO Shipping Condition],
			[SO Inco Terms],
			[SO Inco Terms Description],
			[SO Inco Terms 2],
			[SO Billing Date],
			[ETL_SRC_SYS_CD],
			[ETL_CREATED_TS],
			[ETL_UPDTD_TS],
			[CYLINDER_OWNER_CUST_KEY],
			[SO Usage],
			[SO Higher-Level Item],
			[SO Alternative to Item],
			[MATRL_ENTERED_KEY],
			[SO Reference Document],
			[SO Reference Item],
			[SO Reference Status],
			[SO Total Reference Status],
			[SO Billing Block],
			[PERSON_RESPNSBLE_COST_CNTR_KEY],
			[PARNT_CUST_KEY],
			[CREATION_DATE_KEY],
			[SO Creation Timestamp],
			[SO Delivery Status Indicator],
			[SO Sales UoM],
			[SALES_TRGT_QTY],
			[SO Target Quantity UoM],
			[DLVRD_QTY],
			[SO Is Sales Schedule Line Created],
			[DOCMT_CHARS_ENCOWAY_JS_HDR_KEY],
			[EMPL_RESPNSBLE_2_KEY],
			[SO BOM Item Number],
			[CUST_MATRL_INFO_RCD_KEY] 
        )
        SELECT 
            S.[SO Changed On Date],
			S.[SO Relevant For Billing],
			S.[SO Item Is Relevant For Delivery],
			S.[WBS_ELEMNT_KEY],
			S.[AGENCY_CUST_KEY],
			S.[PRINTER_CUST_KEY],
			S.[SUPLR_CUST_KEY],
			S.[SO Billing Status Of Delivery],
			S.[SO Approval],
			S.[SO Arrangement],
			S.[SO Delivery],
			S.[SO Fixed DET],
			S.[RSLTS_ANALYSIS_KEY],
			S.[SO Purchase Order Item Number],
			S.[SO Line Item System Status],
			S.[SO Overall Status Description],
			S.[Delivery Status Description],
			S.[SO Order Related Bill Status Description],
			S.[SO Shipping Condition Description],
			S.[SO Usage Description],
			S.[SO Reference Status Description],
			S.[SO Total Reference Status Description],
			S.[SO Billing Block Description],
			S.[SO Delivery Status Indicator Description],
			S.[SO Relevant For Billing Description],
			S.[SO Billing Status Of Delivery Description],
			S.[SO Results Analysis Description],
			S.[SO Internal Customer Reference Number],
			S.[Product Hierarchy],
			S.[SO Sold To Purchase Order Number],
			S.[SO Sold To Purchase Order Date],
			S.[SO Ship To Purchase Order Number],
			S.[SO Ship To Purchase Order Date],
			S.[SO Customer Condition Group 1],
			S.[SO Customer Condition Group 1 Description],
			S.[SO Customer Material Number],
			S.[EMPL_RESPNSBLE_KEY],
			S.[CUST_POJECT_MGR_KEY],
			S.[SO Item Category],
			S.[SO Item Category Description],
			S.[SHIP_TO_ADDR_KEY],
			S.[SO Delivery Priority Code],
			S.[SO Delivery Priority Description],
			S.[CREATED_BY],
			S.[UNITIZATION_AGENT_VNDR_KEY],
			S.[SO Designable E Services Flag],
			S.[SO Agreed Delivery Time],
			S.[SO Deceased Name],
			S.[SO Customer Purchase Order Type],
			S.[SO Customer Purchase Order Type Description],
			S.[ORDER_KEY],
			S.[SO Price Group],
			S.[SO Price Group Description],
			S.[CMLT_CONFIRMED_QTY_IN_BASE_UNIT],
			S.[SO Base Unit Of Measure],
			S.[COMPANY_INFO_CMPNY_CD_KEY],
			S.[SAL_SALORDH_INVOICE_CREATION_DATE_KEY],
			S.[SAL_SALORDH_CREATED_DATE_KEY],
			S.[PLANT_REGION_PLANT_ID],
			S.[RESPNSBLE_COST_CNTR_V_HEIR_COST_CNTR_KEY],
			S.[PERSON_RESPNSBLE_COST_CNTR_H_HEIR_KEY],
			S.[FORWARDING_AGENT_VENDOR_KEY],
			S.[ORDER_FOR_CUSTOMER_ADDR_KEY],
			S.[SO_PARENT_CUST_KEY],
			S.[SALES_ORDER_ID],
			S.[SALES_ORDER_ITM_ID],
			S.[MST_PRTHRCY_PRDT_HIERCHY_CD],
			S.[SOIPTNR_KEY],
			S.[V_D_SAL_PRDVCON_KEY],
			S.[SALES_ORDER_KEY],
			S.[Sales Order ID],
			S.[Sales Order Item ID],
			S.[DOCMT_DATE_KEY],
			S.[REQD_DLVRY_DATE_KEY],
			S.[CMPNY_KEY],
			S.[PLNT_KEY],
			S.[SOLDTO_CUST_KEY],
			S.[BILLTO_CUST_KEY],
			S.[PAYER_CUST_KEY],
			S.[SHIPTO_CUST_KEY],
			S.[BRAND_OWNER_CUST_KEY],
			S.[CUST_CONTACT_KEY],
			S.[SALES_PERSON_PERSONEL_KEY],
			S.[PERSON_RESPNSBLE_PERSONEL_KEY],
			S.[MATRL_KEY],
			S.[PROFT_CNTR_KEY],
			S.[CUST_CMPNY_KEY],
			S.[CUST_SALES_AREA_KEY],
			S.[SEG_KEY],
			S.[SALES_AREA_KEY],
			S.[DOCMT_CRNCY_KEY],
			S.[CMPNY_CRNCY_KEY],
			S.[GROUP_CRNCY_KEY],
			S.[SALES_ORDER_QTY],
			S.[SO Unit Of Measure],
			S.[DOCMT_CRNCY_NET_PRICE],
			S.[DOCMT_CRNCY_NET_VAL_AMT],
			S.[DOCMT_CRNCY_TAX_AMT],
			S.[CMPNY_CRNCY_NET_VAL_AMT],
			S.[GROUP_CRNCY_NET_VAL_AMT],
			S.[SO Shipping Point],
			S.[SO Reason For Rejection],
			S.[SO Overall Status],
			S.[SO Delivery Status],
			S.[SO Order Related Bill Status],
			S.[Sales Order Header Encoway Id],
			S.[SO Encoway Version],
			S.[SO Encoway Part],
			S.[SO Encoway Description],
			S.[SO Encoway Number],
			S.[SO Material Description],
			S.[SO Delivery Group],
			S.[QTY_NETTED],
			S.[SO Reason For Rejection Description],
			S.[SO Shipping Condition],
			S.[SO Inco Terms],
			S.[SO Inco Terms Description],
			S.[SO Inco Terms 2],
			S.[SO Billing Date],
			S.[ETL_SRC_SYS_CD],
			S.[ETL_CREATED_TS],
			S.[ETL_UPDTD_TS],
			S.[CYLINDER_OWNER_CUST_KEY],
			S.[SO Usage],
			S.[SO Higher-Level Item],
			S.[SO Alternative to Item],
			S.[MATRL_ENTERED_KEY],
			S.[SO Reference Document],
			S.[SO Reference Item],
			S.[SO Reference Status],
			S.[SO Total Reference Status],
			S.[SO Billing Block],
			S.[PERSON_RESPNSBLE_COST_CNTR_KEY],
			S.[PARNT_CUST_KEY],
			S.[CREATION_DATE_KEY],
			S.[SO Creation Timestamp],
			S.[SO Delivery Status Indicator],
			S.[SO Sales UoM],
			S.[SALES_TRGT_QTY],
			S.[SO Target Quantity UoM],
			S.[DLVRD_QTY],
			S.[SO Is Sales Schedule Line Created],
			S.[DOCMT_CHARS_ENCOWAY_JS_HDR_KEY],
			S.[EMPL_RESPNSBLE_2_KEY],
			S.[SO BOM Item Number],
			S.[CUST_MATRL_INFO_RCD_KEY]


    FROM 
        [GLOBAL_EDW].[Propelis].[EDW_T_FACT_SAL_SALORDD_CUR_D] T
    LEFT JOIN 
        [GLOBAL_EDW].[Propelis].[TEMP_EDW_T_FACT_SAL_SALORDD_CUR_D] S
    ON 
        	T.[SALES_ORDER_KEY]=S.[SALES_ORDER_KEY] AND     
		T.[SALES_ORDER_ID]=S.[SALES_ORDER_ID] AND
		T.[SALES_ORDER_ITM_ID]=S.[SALES_ORDER_ITM_ID] AND
		T.[CMPNY_KEY]=S.[CMPNY_KEY] AND
		T.[ETL_SRC_SYS_CD]=S.[ETL_SRC_SYS_CD] 
    WHERE 
        T.[SALES_ORDER_KEY] IS NULL;
    END;