CREATE     PROCEDURE [Propelis].[Proc_SCHL_ITM_DATE] 
AS
BEGIN  
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Schedule Item Date] = S.[THE_DATE],
        T.[Schedule Item Fiscal Year] = S.[FISCAL_YR],
        T.[Schedule Item Fiscal Period] = S.[FISCAL_PER_NUM],
        T.[Schedule Item Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Schedule Item Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Schedule Item Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Schedule Item Calendar Year] = S.[CLNDR_YR],
        T.[Schedule Item Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Schedule Item Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Schedule Item Calendar Month Desc] = S.[CLNDR_MNTH_DESC],
        T.[Schedule Item Calendar Quarter] = S.[CLNDR_QTR_NUM],
        T.[Schedule Item Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Schedule Item Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Schedule Item Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Schdl Item Calendar Day in Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Schedule Item Calendar Day in Year] = S.[CLNDR_DAY_IN_YR],
        T.[Schedule Item Calendar Week] = S.[CLNDR_WK],
        T.[Schedule Item Calendar Month in Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Schedule Item Calendar Days in Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Schld Item Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Schld Item Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Schld Item Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Schld Item Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Schld Item Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Schld Item Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Schld Item Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Schld Item Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Schld Item Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Schld Item Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Schld Item Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Schld Item Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Schld Item Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Schld Item Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Schld Item Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Schld Item Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Schld Item Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Schld Item Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Schedule Item Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Schld Item Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Schedule Item Fiscal Week] = S.[FISCAL_WK],
        T.[Schld Item Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Schld Item Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Schedule Item Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Schedule Item Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Schld Item Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Schld Item Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Schld Item Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Schld Item Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Schld Item Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Schld Item Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Schld Item Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[SCHL_ITM_DATE] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];
 
    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[SCHL_ITM_DATE] (
        [DATE_KEY],
        [Schedule Item Date],
        [Schedule Item Fiscal Year],
        [Schedule Item Fiscal Period],
        [Schedule Item Fiscal Period Code],
        [Schedule Item Fiscal Quarter Number],
        [Schedule Item Fiscal Quarter Code],
        [Schedule Item Calendar Year],
        [Schedule Item Calendar Month Number],
        [Schedule Item Calendar Month Code],
        [Schedule Item Calendar Month Desc],
        [Schedule Item Calendar Quarter],
        [Schedule Item Calendar Quarter Code],
        [Schedule Item Calendar Weekday Number],
        [Schedule Item Calendar Weekday Name],
        [Schdl Item Calendar Day in Month],
        [Schedule Item Calendar Day in Year],
        [Schedule Item Calendar Week],
        [Schedule Item Calendar Month in Quarter Number],
        [Schedule Item Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Schld Item Current Day Flag],
        [Schld Item Current Day Minus 1 Flag],
        [Schld Item Current Calendar Week Flag],
        [Schld Item Current Calendar Week Minus 1 Flag],
        [Schld Item Current Month Flag],
        [Schld Item Current Month Minus 1 Flag],
        [Schld Item Current Month Minus 12 Flag],
        [Schld Item Current Quarter Flag],
        [Schld Item Current Quarter Minus 1 Flag],
        [Schld Item Current Quarter Minus 4 Flag],
        [Schld Item Current Calendar Year Flag],
        [Schld Item Current Calendar Year Minus 1 Flag],
        [Schld Item Current Calendar Year Minus 2 Flag],
        [Schld Item Current Fiscal Year Flag],
        [Schld Item Current Fiscal Year Minus 1 Flag],
        [Schld Item Current Fiscal Year Minus 2 Flag],
        [Schld Item Current Calendar Year Plus 1 Flag],
        [Schld Item Current Fiscal Year Plus 1 Flag],
        [Schedule Item Day In Fiscal Year],
        [Schld Item Date Is Weekday],
        [Schedule Item Fiscal Week],
        [Schld Item Current Fiscal Week Flag],
        [Schld Item Current Fiscal Week Minus 1 Flag],
        [Schedule Item Fiscal Weekday Number],
        [Schedule Item Fiscal Weekday Name],
        [Schld Item Current Month Minus 2 Flag],
        [Schld Item Current Fiscal Week Minus 2 Flag],
        [Schld Item Current Fiscal Week Minus 6 Flag],
        [Schld Item Current Fiscal Week Minus 3 Flag],
        [Schld Item Current Fiscal Week Minus 4 Flag],
        [Schld Item Current Fiscal Week Minus 5 Flag],
        [Schld Item Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[SCHL_ITM_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
END