CREATE     PROCEDURE [Propelis].[Proc_LAST_DUNNING_NOTICE_DATE]
AS
BEGIN  
    -- ============================================
    -- Step 1: Update existing records
    -- ============================================
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Last Dunning Notice Date] = S.[THE_DATE],
        T.[Last Dunning Notice Fiscal Year] = S.[FISCAL_YR],
        T.[Last Dunning Notice Fiscal Period Number] = S.[FISCAL_PER_NUM],
        T.[Last Dunning Notice Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Last Dunning Notice Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Last Dunning Notice Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Last Dunning Notice Calendar Year] = S.[CLNDR_YR],
        T.[Last Dunning Notice Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Last Dunning Notice Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Last Dunning Notice Calendar Month Description] = S.[CLNDR_MNTH_DESC],
        T.[Last Dunning Notice Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[Last Dunning Notice Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Last Dunning Notice Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Last Dunning Notice Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Last Dunning Notice Calendar Day In Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Last Dunning Notice Calendar Day In Year] = S.[CLNDR_DAY_IN_YR],
        T.[Last Dunning Notice Calendar Week] = S.[CLNDR_WK],
        T.[Last Dunning Notice Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Last Dunning Notice Calendar Days In Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Last Dunning Notice Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Last Dunning Notice Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Last Dunning Notice Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Last Dunning Notice Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Last Dunning Notice Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Last Dunning Notice Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Last Dunning Notice Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Last Dunning Notice Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Last Dunning Notice Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Last Dunning Notice Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Last Dunning Notice Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Last Dunning Notice Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Last Dunning Notice Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Last Dunning Notice Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Last Dunning Notice Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Last Dunning Notice Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Last Dunning Notice Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Last Dunning Notice Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Last Dunning Notice Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Last Dunning Notice Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Last Dunning Notice Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Last Dunning Notice Fiscal Week] = S.[FISCAL_WK],
        T.[Last Dunning Notice Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Last Dunning Notice Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Last Dunning Notice Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Last Dunning Notice Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Last Dunning Notice Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Last Dunning Notice Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Last Dunning Notice Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Last Dunning Notice Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Last Dunning Notice Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Last Dunning Notice Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[LAST_DUNNING_NOTICE_DATE] AS T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] AS S
        ON T.[DATE_KEY] = S.[DATE_KEY];

    -- ============================================
    -- Step 2: Insert new records
    -- ============================================
    INSERT INTO [GLOBAL_EDW].[Propelis].[LAST_DUNNING_NOTICE_DATE] (
        [DATE_KEY],
        [Last Dunning Notice Date],
        [Last Dunning Notice Fiscal Year],
        [Last Dunning Notice Fiscal Period Number],
        [Last Dunning Notice Fiscal Period Code],
        [Last Dunning Notice Fiscal Quarter Number],
        [Last Dunning Notice Fiscal Quarter Code],
        [Last Dunning Notice Calendar Year],
        [Last Dunning Notice Calendar Month Number],
        [Last Dunning Notice Calendar Month Code],
        [Last Dunning Notice Calendar Month Description],
        [Last Dunning Notice Calendar Quarter Number],
        [Last Dunning Notice Calendar Quarter Code],
        [Last Dunning Notice Calendar Weekday Number],
        [Last Dunning Notice Calendar Weekday Name],
        [Last Dunning Notice Calendar Day In Month],
        [Last Dunning Notice Calendar Day In Year],
        [Last Dunning Notice Calendar Week],
        [Last Dunning Notice Calendar Month In Quarter Number],
        [Last Dunning Notice Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Last Dunning Notice Current Day Flag],
        [Last Dunning Notice Current Day Minus 1 Flag],
        [Last Dunning Notice Current Calendar Week Flag],
        [Last Dunning Notice Current Calendar Week Minus 1 Flag],
        [Last Dunning Notice Current Month Flag],
        [Last Dunning Notice Current Month Minus 1 Flag],
        [Last Dunning Notice Current Month Minus 2 Flag],
        [Last Dunning Notice Current Month Minus 12 Flag],
        [Last Dunning Notice Current Quarter Flag],
        [Last Dunning Notice Current Quarter Minus 1 Flag],
        [Last Dunning Notice Current Quarter Minus 4 Flag],
        [Last Dunning Notice Current Calendar Year Flag],
        [Last Dunning Notice Current Calendar Year Minus 1 Flag],
        [Last Dunning Notice Current Calendar Year Minus 2 Flag],
        [Last Dunning Notice Current Calendar Year Plus 1 Flag],
        [Last Dunning Notice Current Fiscal Year Flag],
        [Last Dunning Notice Current Fiscal Year Minus 1 Flag],
        [Last Dunning Notice Current Fiscal Year Minus 2 Flag],
        [Last Dunning Notice Current Fiscal Year Plus 1 Flag],
        [Last Dunning Notice Day In Fiscal Year],
        [Last Dunning Notice Date Is Weekday],
        [Last Dunning Notice Fiscal Week],
        [Last Dunning Notice Fiscal Weekday Number],
        [Last Dunning Notice Fiscal Weekday Name],
        [Last Dunning Notice Current Fiscal Week Flag],
        [Last Dunning Notice Current Fiscal Week Minus 1 Flag],
        [Last Dunning Notice Current Fiscal Week Minus 2 Flag],
        [Last Dunning Notice Current Fiscal Week Minus 3 Flag],
        [Last Dunning Notice Current Fiscal Week Minus 4 Flag],
        [Last Dunning Notice Current Fiscal Week Minus 5 Flag],
        [Last Dunning Notice Current Fiscal Week Minus 6 Flag],
        [Last Dunning Notice Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[LAST_DUNNING_NOTICE_DATE] AS T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
END;