CREATE   PROCEDURE [Propelis].[Proc_MATRL_AVAILABILITY_DATE] 
AS
BEGIN  
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Matrl Avail Date] = S.[THE_DATE],
        T.[Matrl Avail Fiscal Year] = S.[FISCAL_YR],
        T.[Matrl Avail Fiscal Period] = S.[FISCAL_PER_NUM],
        T.[Matrl Avail Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Matrl Avail Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Matrl Avail Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Matrl Avail Calendar Year] = S.[CLNDR_YR],
        T.[Matrl Avail Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Matrl Avail Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Matrl Avail Calendar Month Desc] = S.[CLNDR_MNTH_DESC],
        T.[Matrl Avail Calendar Quarter] = S.[CLNDR_QTR_NUM],
        T.[Matrl Avail Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Matrl Avail Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Matrl Avail Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Matrl Avail Calendar Day in Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Matrl Avail Calendar Day in Year] = S.[CLNDR_DAY_IN_YR],
        T.[Matrl Avail Calendar Week] = S.[CLNDR_WK],
        T.[Matrl Avail Calendar Month in Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Matrl Avail Calendar Days in Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Matrl Avail Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Matrl Avail Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Matrl Avail Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Matrl Avail Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Matrl Avail Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Matrl Avail Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Matrl Avail Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Matrl Avail Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Matrl Avail Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Matrl Avail Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Matrl Avail Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Matrl Avail Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Matrl Avail Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Matrl Avail Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Matrl Avail Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Matrl Avail Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Matrl Avail Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Matrl Avail Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Matrl Avail Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Matrl Avail Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Matrl Avail Fiscal Week] = S.[FISCAL_WK],
        T.[Matrl Avail Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Matrl Avail Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Matrl Avail Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Matrl Avail Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Matrl Avail Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Matrl Avail Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Matrl Avail Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Matrl Avail Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Matrl Avail Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Matrl Avail Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Matrl Avail Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[MATRL_AVAILABILITY_DATE] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];
 
    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[MATRL_AVAILABILITY_DATE] (
        [DATE_KEY],
        [Matrl Avail Date],
        [Matrl Avail Fiscal Year],
        [Matrl Avail Fiscal Period],
        [Matrl Avail Fiscal Period Code],
        [Matrl Avail Fiscal Quarter Number],
        [Matrl Avail Fiscal Quarter Code],
        [Matrl Avail Calendar Year],
        [Matrl Avail Calendar Month Number],
        [Matrl Avail Calendar Month Code],
        [Matrl Avail Calendar Month Desc],
        [Matrl Avail Calendar Quarter],
        [Matrl Avail Calendar Quarter Code],
        [Matrl Avail Calendar Weekday Number],
        [Matrl Avail Calendar Weekday Name],
        [Matrl Avail Calendar Day in Month],
        [Matrl Avail Calendar Day in Year],
        [Matrl Avail Calendar Week],
        [Matrl Avail Calendar Month in Quarter Number],
        [Matrl Avail Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Matrl Avail Current Day Flag],
        [Matrl Avail Current Day Minus 1 Flag],
        [Matrl Avail Current Calendar Week Flag],
        [Matrl Avail Current Calendar Week Minus 1 Flag],
        [Matrl Avail Current Month Flag],
        [Matrl Avail Current Month Minus 1 Flag],
        [Matrl Avail Current Month Minus 12 Flag],
        [Matrl Avail Current Quarter Flag],
        [Matrl Avail Current Quarter Minus 1 Flag],
        [Matrl Avail Current Quarter Minus 4 Flag],
        [Matrl Avail Current Calendar Year Flag],
        [Matrl Avail Current Calendar Year Minus 1 Flag],
        [Matrl Avail Current Calendar Year Minus 2 Flag],
        [Matrl Avail Current Fiscal Year Flag],
        [Matrl Avail Current Fiscal Year Minus 1 Flag],
        [Matrl Avail Current Fiscal Year Minus 2 Flag],
        [Matrl Avail Current Calendar Year Plus 1 Flag],
        [Matrl Avail Current Fiscal Year Plus 1 Flag],
        [Matrl Avail Day In Fiscal Year],
        [Matrl Avail Date Is Weekday],
        [Matrl Avail Fiscal Week],
        [Matrl Avail Current Fiscal Week Flag],
        [Matrl Avail Current Fiscal Week Minus 1 Flag],
        [Matrl Avail Fiscal Weekday Number],
        [Matrl Avail Fiscal Weekday Name],
        [Matrl Avail Current Month Minus 2 Flag],
        [Matrl Avail Current Fiscal Week Minus 2 Flag],
        [Matrl Avail Current Fiscal Week Minus 6 Flag],
        [Matrl Avail Current Fiscal Week Minus 3 Flag],
        [Matrl Avail Current Fiscal Week Minus 4 Flag],
        [Matrl Avail Current Fiscal Week Minus 5 Flag],
        [Matrl Avail Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[MATRL_AVAILABILITY_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
END