CREATE     PROCEDURE [Propelis].[Proc_SERVICE_ORDER_CREATE_DATE]
AS
BEGIN
    -- Update existing records
    UPDATE T
    SET 
        T.[THE DATE] = S.[THE_DATE],
        T.[Service Order Created Fiscal Year] = S.[FISCAL_YR],
        T.[FISCAL PER NUM] = S.[FISCAL_PER_NUM],
        T.[Service Order Created Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Service Order Created Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Service Order Created Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Service Order Created Calendar Year] = S.[CLNDR_YR],
        T.[Service Order Created Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Service Order Created Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Service Order Created Calendar Month Desc] = S.[CLNDR_MNTH_DESC],
        T.[CLNDR QTR NUM] = S.[CLNDR_QTR_NUM],
        T.[Service Order Created Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Service Order Created Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Service Order Created Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Service Order Created Calendar Day in Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Service Order Created Calendar Day in Year] = S.[CLNDR_DAY_IN_YR],
        T.[Service Order Created Calendar Week] = S.[CLNDR_WK],
        T.[Service Order Created Calendar Month in Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Service Order Created Calendar Days in Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL SRC SYS CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL CREATED TS] = S.[ETL_CREATED_TS],
        T.[ETL UPDTD TS] = S.[ETL_UPDTD_TS],
        T.[Service Order Created Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Service Order Created Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Service Order Created Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Service Order Created Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Service Order Created Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Service Order Created Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Service Order Created Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Service Order Created Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Service Order Created Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Service Order Created Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Service Order Created Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Service Order Created Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Service Order Created Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Service Order Created Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Service Order Created Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Service Order Created Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Service Order Created Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Service Order Created Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Service Order Created Day in Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Service Order Created Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Service Order Fiscal Week] = S.[FISCAL_WK],
        T.[Service Order Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Service Order Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Service Order Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Service Order Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[CURR MNTH MINUS 2 FLG] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Service Order Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Service Order Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Service Order Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Service Order Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Service Order Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Service Order Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[SERVICE_ORDER_CREATE_DATE] AS T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D]  AS S
        ON T.[DATE KEY] = S.[DATE_KEY];

    -- Insert new records
    INSERT INTO [GLOBAL_EDW].[Propelis].[SERVICE_ORDER_CREATE_DATE] 
    (
        [DATE KEY],
        [THE DATE],
        [Service Order Created Fiscal Year],
        [FISCAL PER NUM],
        [Service Order Created Fiscal Period Code],
        [Service Order Created Fiscal Quarter Number],
        [Service Order Created Fiscal Quarter Code],
        [Service Order Created Calendar Year],
        [Service Order Created Calendar Month Number],
        [Service Order Created Calendar Month Code],
        [Service Order Created Calendar Month Desc],
        [CLNDR QTR NUM],
        [Service Order Created Calendar Quarter Code],
        [Service Order Created Calendar Weekday Number],
        [Service Order Created Calendar Weekday Name],
        [Service Order Created Calendar Day in Month],
        [Service Order Created Calendar Day in Year],
        [Service Order Created Calendar Week],
        [Service Order Created Calendar Month in Quarter Number],
        [Service Order Created Calendar Days in Month],
        [ETL SRC SYS CD],
        [ETL CREATED TS],
        [ETL UPDTD TS],
        [Service Order Created Current Day Flag],
        [Service Order Created Current Day Minus 1 Flag],
        [Service Order Created Current Calendar Week Flag],
        [Service Order Created Current Calendar Week Minus 1 Flag],
        [Service Order Created Current Month Flag],
        [Service Order Created Current Month Minus 1 Flag],
        [Service Order Created Current Month Minus 12 Flag],
        [Service Order Created Current Quarter Flag],
        [Service Order Created Current Quarter Minus 1 Flag],
        [Service Order Created Current Quarter Minus 4 Flag],
        [Service Order Created Current Calendar Year Flag],
        [Service Order Created Current Calendar Year Minus 1 Flag],
        [Service Order Created Current Calendar Year Minus 2 Flag],
        [Service Order Created Current Fiscal Year Flag],
        [Service Order Created Current Fiscal Year Minus 1 Flag],
        [Service Order Created Current Fiscal Year Minus 2 Flag],
        [Service Order Created Current Calendar Year Plus 1 Flag],
        [Service Order Created Current Fiscal Year Plus 1 Flag],
        [Service Order Created Day in Fiscal Year],
        [Service Order Created Date Is Weekday],
        [Service Order Fiscal Week],
        [Service Order Current Fiscal Week Flag],
        [Service Order Current Fiscal Week Minus 1 Flag],
        [Service Order Fiscal Weekday Number],
        [Service Order Fiscal Weekday Name],
        [CURR MNTH MINUS 2 FLG],
        [Service Order Current Fiscal Week Minus 2 Flag],
        [Service Order Current Fiscal Week Minus 6 Flag],
        [Service Order Current Fiscal Week Minus 3 Flag],
        [Service Order Current Fiscal Week Minus 4 Flag],
        [Service Order Current Fiscal Week Minus 5 Flag],
        [Service Order Current Fiscal Week Minus 7 Flag]
    )
    SELECT 
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D]  AS S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[SERVICE_ORDER_CREATE_DATE] AS T
        ON T.[DATE KEY] = S.[DATE_KEY]
    WHERE T.[DATE KEY] IS NULL;
END;