CREATE PROCEDURE [Propelis].[Proc_INTER_COMP_PROFIT_CNTR]
AS
BEGIN

UPDATE T 
SET
T.[PROFT_CNTR_KEY]  = S.[PROFT_CNTR_KEY],
T.[Inter Comp Profit Center ID]  = S.[Profit Center ID],
T.[Inter Comp Profit Center Tax Jurisdiction]  = S.[Profit Center Tax Jurisdiction],
T.[Inter Comp Profit Center Valid To Date]  = S.[Profit Center Valid To Date],
T.[Inter Comp Profit Center Valid From Date]  = S.[Profit Center Valid From Date],
T.[Inter Comp Profit Center Area]  = S.[Profit Center Area],
T.[Inter Comp Profit Center Generic Mastdf Record Status]  = S.[Profit Center Generic Master Record Status],
T.[Inter Comp Profit Center Status Description]  = S.[Profit Center Status Description],
T.[Inter Comp Profit Center Controlling Area Description]  = S.[Profit Center Controlling Area Description],
T.[Inter Comp Profit Center Country Description]  = S.[Profit Center Country Description],
T.[Inter Comp Profit Center Company Description]  = S.[Profit Center Company Description],
T.[ETL_UPDTD_TS]  = S.[ETL_UPDTD_TS],
T.[Inter Comp Profit Center Company Code]  = S.[Profit Center Company Code],
T.[Inter Comp Profit Center Long Description]  = S.[Profit Center Long Description],
T.[Inter Comp Profit Center Short Description]  = S.[Profit Center Short Description],
T.[Inter Comp Profit Center Lock Indicator]  = S.[Profit Center Lock Indicator],
T.[Inter Comp Profit Center Name 1]  = S.[Profit Center Name 1],
T.[Inter Comp Profit Center Updated User ID]  = S.[Profit Center Updated User ID],
T.[ETL_SRC_SYS_CD]  = S.[ETL_SRC_SYS_CD],
T.[ETL_EFFECTV_BEGIN_DATE]  = S.[ETL_EFFECTV_BEGIN_DATE],
T.[ETL_EFFECTV_END_DATE]  = S.[ETL_EFFECTV_END_DATE],
T.[ETL_CURR_RCD_IND]  = S.[ETL_CURR_RCD_IND],
T.[ETL_CREATED_TS]  = S.[ETL_CREATED_TS],
T.[Inter Comp Profit Center Postal Code]  = S.[Profit Center Postal Code],
T.[Inter Comp Profit Center Country Code]  = S.[Profit Center Country Code],
T.[Inter Comp Profit Center Region Code]  = S.[Profit Center Region Code],
T.[Inter Comp Profit Center Created Date]  = S.[Profit Center Created Date],
T.[Inter Comp Profit Center Created User ID]  = S.[Profit Center Created User ID],
T.[Inter Comp Profit Center Updated Date]  = S.[Profit Center Updated Date],
T.[Inter Comp Profit Center Language Type Code]  = S.[Profit Center Language Type Code],
T.[Inter Comp Profit Center Segment ID]  = S.[Profit Center Segment ID],
T.[Inter Comp Profit Center Address Line 1]  = S.[Profit Center Address Line 1],
T.[Inter Comp Profit Center Address Line 2]  = S.[Profit Center Address Line 2],
T.[Inter Comp Profit Center City Name]  = S.[Profit Center City Name],
T.[Inter Comp Profit Center Distrtict Name]  = S.[Profit Center District Name],
T.[Inter Comp Profit Center Description]  = S.[Profit Center Description],
T.[Legacy Profit Center Code]  = S.[Legacy Profit Center Code],
T.[Legacy Profit Center Description]  = S.[Legacy Profit Center Description],
T.[Inter Comp Profit Center Controlling Area ID]  = S.[Profit Center Controlling Area ID],
T.[Inter Comp Profit Center User Responsible ID]  = S.[Profit Center User Responsible ID],
T.[Inter Comp Profit Center Person Responsible]  = S.[Profit Center Person Responsible]

FROM [GLOBAL_EDW].[Propelis].[INTER_COMP_PROFIT_CNTR] T
INNER JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PROFCTR_CUR_D] S
ON T.[PROFT_CNTR_KEY] = S.[PROFT_CNTR_KEY];

INSERT INTO [GLOBAL_EDW].[Propelis].[INTER_COMP_PROFIT_CNTR]  (
[PROFT_CNTR_KEY] ,
[Inter Comp Profit Center ID] ,
[Inter Comp Profit Center Tax Jurisdiction] ,
[Inter Comp Profit Center Valid To Date] ,
[Inter Comp Profit Center Valid From Date] ,
[Inter Comp Profit Center Area] ,
[Inter Comp Profit Center Generic Mastdf Record Status] ,
[Inter Comp Profit Center Status Description] ,
[Inter Comp Profit Center Controlling Area Description] ,
[Inter Comp Profit Center Country Description] ,
[Inter Comp Profit Center Company Description] ,
[ETL_UPDTD_TS] ,
[Inter Comp Profit Center Company Code] ,
[Inter Comp Profit Center Long Description] ,
[Inter Comp Profit Center Short Description] ,
[Inter Comp Profit Center Lock Indicator] ,
[Inter Comp Profit Center Name 1] ,
[Inter Comp Profit Center Updated User ID] ,
[ETL_SRC_SYS_CD] ,
[ETL_EFFECTV_BEGIN_DATE] ,
[ETL_EFFECTV_END_DATE] ,
[ETL_CURR_RCD_IND] ,
[ETL_CREATED_TS] ,
[Inter Comp Profit Center Postal Code] ,
[Inter Comp Profit Center Country Code] ,
[Inter Comp Profit Center Region Code] ,
[Inter Comp Profit Center Created Date] ,
[Inter Comp Profit Center Created User ID] ,
[Inter Comp Profit Center Updated Date] ,
[Inter Comp Profit Center Language Type Code] ,
[Inter Comp Profit Center Segment ID] ,
[Inter Comp Profit Center Address Line 1] ,
[Inter Comp Profit Center Address Line 2] ,
[Inter Comp Profit Center City Name] ,
[Inter Comp Profit Center Distrtict Name] ,
[Inter Comp Profit Center Description] ,
[Legacy Profit Center Code] ,
[Legacy Profit Center Description] ,
[Inter Comp Profit Center Controlling Area ID] ,
[Inter Comp Profit Center User Responsible ID] ,
[Inter Comp Profit Center Person Responsible] 
)
SELECT
S.[PROFT_CNTR_KEY],
S.[Profit Center ID],
S.[Profit Center Tax Jurisdiction],
S.[Profit Center Valid To Date],
S.[Profit Center Valid From Date],
S.[Profit Center Area],
S.[Profit Center Generic Master Record Status],
S.[Profit Center Status Description],
S.[Profit Center Controlling Area Description],
S.[Profit Center Country Description],
S.[Profit Center Company Description],
S.[ETL_UPDTD_TS],
S.[Profit Center Company Code],
S.[Profit Center Long Description],
S.[Profit Center Short Description],
S.[Profit Center Lock Indicator],
S.[Profit Center Name 1],
S.[Profit Center Updated User ID],
S.[ETL_SRC_SYS_CD],
S.[ETL_EFFECTV_BEGIN_DATE],
S.[ETL_EFFECTV_END_DATE],
S.[ETL_CURR_RCD_IND],
S.[ETL_CREATED_TS],
S.[Profit Center Postal Code],
S.[Profit Center Country Code],
S.[Profit Center Region Code],
S.[Profit Center Created Date],
S.[Profit Center Created User ID],
S.[Profit Center Updated Date],
S.[Profit Center Language Type Code],
S.[Profit Center Segment ID],
S.[Profit Center Address Line 1],
S.[Profit Center Address Line 2],
S.[Profit Center City Name],
S.[Profit Center District Name],
S.[Profit Center Description],
S.[Legacy Profit Center Code],
S.[Legacy Profit Center Description],
S.[Profit Center Controlling Area ID],
S.[Profit Center User Responsible ID],
S.[Profit Center Person Responsible]
FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PROFCTR_CUR_D]  S
LEFT JOIN [GLOBAL_EDW].[Propelis].[INTER_COMP_PROFIT_CNTR]   AS T
ON T.[PROFT_CNTR_KEY] = S.[PROFT_CNTR_KEY]
WHERE T.[PROFT_CNTR_KEY] IS NULL;
END;