CREATE     PROCEDURE [Propelis].[Proc_UNITIZATION_AGENT_VENDOR]
AS
BEGIN
    -- Step 1: Update existing records in target table from mirror
    UPDATE T
    SET
        T.[Unitization Agent Vendor ID]                        = S.[VNDR_ID],
        T.[Unitization Agent Vendor Name]                      = S.[VNDR_NAME],
        T.[Unitization Agent Vendor Description]               = S.[VNDR_DESC],
        T.[Unitization Agent Vendor Account Group]             = S.[VNDR_ACCT_GROUP],
        T.[Unitization Agent Vendor Title]                     = S.[TITLE],
        T.[Unitization Agent Vendor Search Term]               = S.[SEARCH_TERM],
        T.[Unitization Agent Vendor Street]                    = S.[STR],
        T.[Unitization Agent Vendor City Name]                 = S.[CITY_NAME],
        T.[Unitization Agent Vendor Zip Code]                  = S.[ZIP_CD],
        T.[Unitization Agent Vendor Country Code]              = S.[CNTRY_CD],
        T.[Unitization Agent Vendor State]                     = S.[ST],
        T.[Unitization Agent Vendor Telephone Number 1 Code]   = S.[TEL_NUM_1_CD],
        T.[Unitization Agent Vendor Fax Number Code]           = S.[FAX_NUM_CD],
        T.[Unitization Agent Vendor Tax Number 1 Code]         = S.[TAX_NUM_1_CD],
        T.[Unitization Agent Vendor Tax Number 2 Code]         = S.[TAX_NUM_2_CD],
        T.[Unitization Agent Vendor VAT Number Code]           = S.[VAT_NUM_CD],
        T.[Unitization Agent Vendor Express Station]           = S.[EXPRESS_STATION],
        T.[Unitization Agent Vendor Transportation Zone]       = S.[TRANSTN_ZONE],
        T.[Unitization Agent Vendor Industry]                  = S.[INDUS],
        T.[Unitization Agent Vendor Created Date]              = S.[CREATED_DATE],
        T.[ETL_SRC_SYS_CD]                                    = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE]                            = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE]                              = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND]                                  = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS]                                    = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS]                                      = S.[ETL_UPDTD_TS],
        T.[Unitization Agent Vendor Address Number]            = S.[ADDR_NUM],
        T.[Unitization Agent Vendor Account Group Description] = S.[VNDR_ACCT_GROUP_DESC],
        T.[Unitization Agent Vendor Country Description]       = S.[CNTRY_DESC],
        T.[Unitization Agent Vendor Region Description]        = S.[REGN_DESC],
        T.[Unitization Agent Vendor Transportation Zone Description] = S.[TRANSTN_ZONE_DESC],
        T.[Unitization Agent Vendor Industry Description]      = S.[INDUS_DESC],
        T.[Unitization Agent Vendor Created By]                = S.[CREATED_BY],
        T.[Unitization Agent Vendor Central Deletion Indicator] = S.[CENTRAL_DELETION_IND],
        T.[Unitization Agent Vendor Central Posting Block]     = S.[CENTRAL_PSTNG_BLK],
        T.[Unitization Agent Vendor Central Purchasing Block]  = S.[CENTRAL_PURNG_BLK],
        T.[Unitization Agent Vendor Language Key]              = S.[LANG_KEY],
        T.[Unitization Agent Vendor Customer ID]               = S.[CUST_ID],
        T.[Unitization Agent Vendor One Time Account Indicator]= S.[ONE_TM_ACCT_IND],
        T.[Unitization Agent Vendor One Time Account Reference Group] = S.[ONE_TM_ACCT_REF_ACCT__GROUP],
        T.[Unitization Agent Vendor One Time Account Reference Group Desc] = S.[ONE_TM_ACC_REF_ACCT_GROUP_DESC],
        T.[Unitization Agent Vendor Trading Partner]           = S.[TRADING_PRTNR],
        T.[Unitization Agent Vendor Trading Partner Description]= S.[TRADING_PRTNR_DESC],
        T.[Unitization Agent Vendor VAT Indicator]             = S.[VAT_IND],
        T.[Unitization Agent Vendor Industry Type]             = S.[INDUS_TYP],
        T.[Unitization Agent Vendor Business Type]             = S.[BIZ_TYP],
        T.[Unitization Agent Vendor Payment Block]             = S.[PYMT_BLK],
        T.[Unitization Agent Vendor Tax Jurisdiction]          = S.[TAX_JRSDCTN],
        T.[Unitization Agent Vendor Tax Number 3 Code]        = S.[TAX_NUM_3_CD],
        T.[Unitization Agent Vendor Tax Number Type]          = S.[TAX_NUM_TYP],
        T.[Unitization Agent Vendor Tax Type]                 = S.[TAX_TYP],
        T.[Unitization Agent Vendor Level 1]                  = S.[LVL_1],
        T.[Unitization Agent Vendor Level 2]                  = S.[LVL_2],
        T.[Unitization Agent Vendor Level 3]                  = S.[LVL_3],
        T.[Unitization Agent Vendor Level 4]                  = S.[LVL_4],
        T.[Unitization Agent Vendor Addressable]              = S.[ADDRESSABLE],
        T.[Unitization Agent Tail Vendor]                     = S.[TAIL_VNDR],
        T.[Unitization Agent Vendor Normalized]               = S.[NORMALIZED_VNDR],
        T.[Unitization Agent Vendor Corporate Group]          = S.[CORPORATE_GROUP],
        T.[Unitization Agent Vendor Account No Alternate Payee]= S.[ACCT_NO_ALT_PYE],
        T.[Unitization Agent Vendor Email Address]            = S.[E_MAIL_ADDR]
    FROM [GLOBAL_EDW].[Propelis].[UNITIZATION_AGENT_VENDOR] AS T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_VENDOR_CUR_D] AS S
        ON T.[VNDR_KEY] = S.[VNDR_KEY];

    -- Step 2: Insert new records from mirror into target table
    INSERT INTO [GLOBAL_EDW].[Propelis].[UNITIZATION_AGENT_VENDOR] (
        [VNDR_KEY],
        [Unitization Agent Vendor ID],
        [Unitization Agent Vendor Name],
        [Unitization Agent Vendor Description],
        [Unitization Agent Vendor Account Group],
        [Unitization Agent Vendor Title],
        [Unitization Agent Vendor Search Term],
        [Unitization Agent Vendor Street],
        [Unitization Agent Vendor City Name],
        [Unitization Agent Vendor Zip Code],
        [Unitization Agent Vendor Country Code],
        [Unitization Agent Vendor State],
        [Unitization Agent Vendor Telephone Number 1 Code],
        [Unitization Agent Vendor Fax Number Code],
        [Unitization Agent Vendor Tax Number 1 Code],
        [Unitization Agent Vendor Tax Number 2 Code],
        [Unitization Agent Vendor VAT Number Code],
        [Unitization Agent Vendor Express Station],
        [Unitization Agent Vendor Transportation Zone],
        [Unitization Agent Vendor Industry],
        [Unitization Agent Vendor Created Date],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Unitization Agent Vendor Address Number],
        [Unitization Agent Vendor Account Group Description],
        [Unitization Agent Vendor Country Description],
        [Unitization Agent Vendor Region Description],
        [Unitization Agent Vendor Transportation Zone Description],
        [Unitization Agent Vendor Industry Description],
        [Unitization Agent Vendor Created By],
        [Unitization Agent Vendor Central Deletion Indicator],
        [Unitization Agent Vendor Central Posting Block],
        [Unitization Agent Vendor Central Purchasing Block],
        [Unitization Agent Vendor Language Key],
        [Unitization Agent Vendor Customer ID],
        [Unitization Agent Vendor One Time Account Indicator],
        [Unitization Agent Vendor One Time Account Reference Group],
        [Unitization Agent Vendor One Time Account Reference Group Desc],
        [Unitization Agent Vendor Trading Partner],
        [Unitization Agent Vendor Trading Partner Description],
        [Unitization Agent Vendor VAT Indicator],
        [Unitization Agent Vendor Industry Type],
        [Unitization Agent Vendor Business Type],
        [Unitization Agent Vendor Payment Block],
        [Unitization Agent Vendor Tax Jurisdiction],
        [Unitization Agent Vendor Tax Number 3 Code],
        [Unitization Agent Vendor Tax Number Type],
        [Unitization Agent Vendor Tax Type],
        [Unitization Agent Vendor Level 1],
        [Unitization Agent Vendor Level 2],
        [Unitization Agent Vendor Level 3],
        [Unitization Agent Vendor Level 4],
        [Unitization Agent Vendor Addressable],
        [Unitization Agent Tail Vendor],
        [Unitization Agent Vendor Normalized],
        [Unitization Agent Vendor Corporate Group],
        [Unitization Agent Vendor Account No Alternate Payee],
        [Unitization Agent Vendor Email Address]
    )
    SELECT
        S.[VNDR_KEY],
        S.[VNDR_ID],
        S.[VNDR_NAME],
        S.[VNDR_DESC],
        S.[VNDR_ACCT_GROUP],
        S.[TITLE],
        S.[SEARCH_TERM],
        S.[STR],
        S.[CITY_NAME],
        S.[ZIP_CD],
        S.[CNTRY_CD],
        S.[ST],
        S.[TEL_NUM_1_CD],
        S.[FAX_NUM_CD],
        S.[TAX_NUM_1_CD],
        S.[TAX_NUM_2_CD],
        S.[VAT_NUM_CD],
        S.[EXPRESS_STATION],
        S.[TRANSTN_ZONE],
        S.[INDUS],
        S.[CREATED_DATE],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[ADDR_NUM],
        S.[VNDR_ACCT_GROUP_DESC],
        S.[CNTRY_DESC],
        S.[REGN_DESC],
        S.[TRANSTN_ZONE_DESC],
        S.[INDUS_DESC],
        S.[CREATED_BY],
        S.[CENTRAL_DELETION_IND],
        S.[CENTRAL_PSTNG_BLK],
        S.[CENTRAL_PURNG_BLK],
        S.[LANG_KEY],
        S.[CUST_ID],
        S.[ONE_TM_ACCT_IND],
        S.[ONE_TM_ACCT_REF_ACCT__GROUP],
        S.[ONE_TM_ACC_REF_ACCT_GROUP_DESC],
        S.[TRADING_PRTNR],
        S.[TRADING_PRTNR_DESC],
        S.[VAT_IND],
        S.[INDUS_TYP],
        S.[BIZ_TYP],
        S.[PYMT_BLK],
        S.[TAX_JRSDCTN],
        S.[TAX_NUM_3_CD],
        S.[TAX_NUM_TYP],
        S.[TAX_TYP],
        S.[LVL_1],
        S.[LVL_2],
        S.[LVL_3],
        S.[LVL_4],
        S.[ADDRESSABLE],
        S.[TAIL_VNDR],
        S.[NORMALIZED_VNDR],
        S.[CORPORATE_GROUP],
        S.[ACCT_NO_ALT_PYE],
        S.[E_MAIL_ADDR]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_VENDOR_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[UNITIZATION_AGENT_VENDOR] AS T
        ON T.[VNDR_KEY] = S.[VNDR_KEY]
    WHERE T.[VNDR_KEY] IS NULL;

END