CREATE     PROCEDURE [Propelis].[Proc_START_OF_MALFUNCTION_DATE]
AS
BEGIN  
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Start Of Malfunction Date] = S.[THE_DATE],
        T.[Start Of Malfunction Fiscal Year] = S.[FISCAL_YR],
        T.[Start Of Malfunction Fiscal Period Number] = S.[FISCAL_PER_NUM],
        T.[Start Of Malfunction Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Start Of Malfunction Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Start Of Malfunction Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Start Of Malfunction Calendar Year] = S.[CLNDR_YR],
        T.[Start Of Malfunction Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Start Of Malfunction Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Start Of Malfunction Calendar Month Description] = S.[CLNDR_MNTH_DESC],
        T.[Start Of Malfunction Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[Start Of Malfunction Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Start Of Malfunction Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Start Of Malfunction Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Start Of Malfunction Calendar Day In Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Start Of Malfunction Calendar Day In Year] = S.[CLNDR_DAY_IN_YR],
        T.[Start Of Malfunction Calendar Week] = S.[CLNDR_WK],
        T.[Start Of Malfunction Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Start Of Malfunction Calendar Days In Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Start Of Malfunction Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Start Of Malfunction Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Start Of Malfunction Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Start Of Malfunction Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Start Of Malfunction Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Start Of Malfunction Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Start Of Malfunction Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Start Of Malfunction Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Start Of Malfunction Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Start Of Malfunction Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Start Of Malfunction Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Start Of Malfunction Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Start Of Malfunction Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Start Of Malfunction Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Start Of Malfunction Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Start Of Malfunction Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Start Of Malfunction Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[CURR_FISCAL_YR_PLUS_1_FLG] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Start Of Malfunction Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Start Of Malfunction Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Start Of Malfunction Fiscal Week] = S.[FISCAL_WK],
        T.[Start Of Malfunction Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Start Of Malfunction Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Start Of Malfunction Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Start Of Malfunction Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Start Of Malfunction Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Start Of Malfunction Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Start Of Malfunction Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Start Of Malfunction Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Start Of Malfunction Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Start Of Malfunction Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Start Of Malfunction Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[START_OF_MALFUNCTION_DATE] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];
 
    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[START_OF_MALFUNCTION_DATE] (
        [DATE_KEY],
        [Start Of Malfunction Date],
        [Start Of Malfunction Fiscal Year],
        [Start Of Malfunction Fiscal Period Number],
        [Start Of Malfunction Fiscal Period Code],
        [Start Of Malfunction Fiscal Quarter Number],
        [Start Of Malfunction Fiscal Quarter Code],
        [Start Of Malfunction Calendar Year],
        [Start Of Malfunction Calendar Month Number],
        [Start Of Malfunction Calendar Month Code],
        [Start Of Malfunction Calendar Month Description],
        [Start Of Malfunction Calendar Quarter Number],
        [Start Of Malfunction Calendar Quarter Code],
        [Start Of Malfunction Calendar Weekday Number],
        [Start Of Malfunction Calendar Weekday Name],
        [Start Of Malfunction Calendar Day In Month],
        [Start Of Malfunction Calendar Day In Year],
        [Start Of Malfunction Calendar Week],
        [Start Of Malfunction Calendar Month In Quarter Number],
        [Start Of Malfunction Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Start Of Malfunction Current Day Flag],
        [Start Of Malfunction Current Day Minus 1 Flag],
        [Start Of Malfunction Current Calendar Week Flag],
        [Start Of Malfunction Current Calendar Week Minus 1 Flag],
        [Start Of Malfunction Current Month Flag],
        [Start Of Malfunction Current Month Minus 1 Flag],
        [Start Of Malfunction Current Month Minus 12 Flag],
        [Start Of Malfunction Current Quarter Flag],
        [Start Of Malfunction Current Quarter Minus 1 Flag],
        [Start Of Malfunction Current Quarter Minus 4 Flag],
        [Start Of Malfunction Current Calendar Year Flag],
        [Start Of Malfunction Current Calendar Year Minus 1 Flag],
        [Start Of Malfunction Current Calendar Year Minus 2 Flag],
        [Start Of Malfunction Current Fiscal Year Flag],
        [Start Of Malfunction Current Fiscal Year Minus 1 Flag],
        [Start Of Malfunction Current Fiscal Year Minus 2 Flag],
        [Start Of Malfunction Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Start Of Malfunction Day In Fiscal Year],
        [Start Of Malfunction Date Is Weekday],
        [Start Of Malfunction Fiscal Week],
        [Start Of Malfunction Current Fiscal Week Flag],
        [Start Of Malfunction Current Fiscal Week Minus 1 Flag],
        [Start Of Malfunction Fiscal Weekday Number],
        [Start Of Malfunction Fiscal Weekday Name],
        [Start Of Malfunction Current Month Minus 2 Flag],
        [Start Of Malfunction Current Fiscal Week Minus 2 Flag],
        [Start Of Malfunction Current Fiscal Week Minus 6 Flag],
        [Start Of Malfunction Current Fiscal Week Minus 3 Flag],
        [Start Of Malfunction Current Fiscal Week Minus 4 Flag],
        [Start Of Malfunction Current Fiscal Week Minus 5 Flag],
        [Start Of Malfunction Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[START_OF_MALFUNCTION_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
 
END