CREATE   PROCEDURE [Propelis].[Proc_PA_COMPLETION_DATE]
AS
BEGIN
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[PA Completion Date] = S.[THE_DATE],
        T.[PA Completion Fiscal Year] = S.[FISCAL_YR],
        T.[PA Completion Fiscal Period Number] = S.[FISCAL_PER_NUM],
        T.[PA Completion Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[PA Completion Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[PA Completion Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[PA Completion Calendar Year] = S.[CLNDR_YR],
        T.[PA Completion Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[PA Completion Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[PA Completion Calendar Month Description] = S.[CLNDR_MNTH_DESC],
        T.[PA Completion Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[PA Completion Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[PA Completion Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[PA Completion Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[PA Completion Calendar Day In Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[PA Completion Calendar Day In Year] = S.[CLNDR_DAY_IN_YR],
        T.[PA Completion Calendar Week] = S.[CLNDR_WK],
        T.[PA Completion Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[PA Completion Calendar Days In Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[PA Completion Current Day Flag] = S.[CURR_DAY_FLG],
        T.[PA Completion Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[PA Completion Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[PA Completion Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[PA Completion Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[PA Completion Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[PA Completion Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[PA Completion Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[PA Completion Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[PA Completion Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[PA Completion Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[PA Completion Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[PA Completion Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[PA Completion Current Fiscal Yr Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[PA Completion Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[PA Completion Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[PA Completion Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[PA Completion Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[PA Completion Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[PA Completion Is Weekday] = S.[IS_WEEKDAY],
        T.[PA Completion Fiscal Week] = S.[FISCAL_WK],
        T.[PA Completion Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[PA Completion Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[PA Completion Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[PA Completion Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[PA Completion Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[PA Completion Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[PA Completion Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[PA Completion Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[PA Completion Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[PA Completion Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[PA Completion Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[PA_COMPLETION_DATE] T
    INNER JOIN [GLOBAL_EDW_MIRROR_OLD].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];

    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[PA_COMPLETION_DATE] (
        [DATE_KEY],
        [PA Completion Date],
        [PA Completion Fiscal Year],
        [PA Completion Fiscal Period Number],
        [PA Completion Fiscal Period Code],
        [PA Completion Fiscal Quarter Number],
        [PA Completion Fiscal Quarter Code],
        [PA Completion Calendar Year],
        [PA Completion Calendar Month Number],
        [PA Completion Calendar Month Code],
        [PA Completion Calendar Month Description],
        [PA Completion Calendar Quarter Number],
        [PA Completion Calendar Quarter Code],
        [PA Completion Calendar Weekday Number],
        [PA Completion Calendar Weekday Name],
        [PA Completion Calendar Day In Month],
        [PA Completion Calendar Day In Year],
        [PA Completion Calendar Week],
        [PA Completion Calendar Month In Quarter Number],
        [PA Completion Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [PA Completion Current Day Flag],
        [PA Completion Current Day Minus 1 Flag],
        [PA Completion Current Calendar Week Flag],
        [PA Completion Current Calendar Week Minus 1 Flag],
        [PA Completion Current Month Flag],
        [PA Completion Current Month Minus 1 Flag],
        [PA Completion Current Month Minus 12 Flag],
        [PA Completion Current Quarter Flag],
        [PA Completion Current Quarter Minus 1 Flag],
        [PA Completion Current Quarter Minus 4 Flag],
        [PA Completion Current Calendar Year Flag],
        [PA Completion Current Calendar Year Minus 1 Flag],
        [PA Completion Current Calendar Year Minus 2 Flag],
        [PA Completion Current Fiscal Yr Flag],
        [PA Completion Current Fiscal Year Minus 1 Flag],
        [PA Completion Current Fiscal Year Minus 2 Flag],
        [PA Completion Current Calendar Year Plus 1 Flag],
        [PA Completion Current Fiscal Year Plus 1 Flag],
        [PA Completion Day In Fiscal Year],
        [PA Completion Is Weekday],
        [PA Completion Fiscal Week],
        [PA Completion Current Fiscal Week Flag],
        [PA Completion Current Fiscal Week Minus 1 Flag],
        [PA Completion Fiscal Weekday Number],
        [PA Completion Fiscal Weekday Name],
        [PA Completion Current Month Minus 2 Flag],
        [PA Completion Current Fiscal Week Minus 2 Flag],
        [PA Completion Current Fiscal Week Minus 3 Flag],
        [PA Completion Current Fiscal Week Minus 4 Flag],
        [PA Completion Current Fiscal Week Minus 5 Flag],
        [PA Completion Current Fiscal Week Minus 6 Flag],
        [PA Completion Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR_OLD].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[PA_COMPLETION_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
END;