CREATE     PROCEDURE [Propelis].[Proc_SALES_ORDER_HEADER_CREATE_DATE]
AS
BEGIN
	UPDATE T
	SET
	T.[DATE_KEY] = S.[DATE_KEY],
	T.[Sales Order Header Creation Date] = S.[THE_DATE],
	T.[Sales Order Header Creation Fiscal Year] = S.[FISCAL_YR],
	T.[Sales Order Header Creation Fiscal Period] = S.[FISCAL_PER_NUM],
	T.[Sales Order Header Creation Fiscal Period Code] = S.[FISCAL_PER_CD],
	T.[Sales Order Header Creation Calendar Quarter] = S.[FISCAL_QTR_NUM],
	T.[Sales Order Header Creation Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
	T.[Sales Order Header Creation Calendar Year] = S.[CLNDR_YR],
	T.[Sales Order Header Creation Calendar Month Number] = S.[CLNDR_MNTH_NUM],
	T.[Sales Order Header Creation Calendar Month Code] = S.[CLNDR_MNTH_CD],
	T.[Sales Order Header Creation Calendar Month Desc] = S.[CLNDR_MNTH_DESC],
	T.[CLNDR_QTR_NUM] = S.[CLNDR_QTR_NUM],
	T.[Sales Order Header Creation Calendar Quarter Code] = S.[CLNDR_QTR_CD],
	T.[Sales Order Header Creation Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
	T.[Sales Order Header Creation Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
	T.[Sales Order Header Creation Calendar Day in Month] = S.[CLNDR_DAY_IN_MNTH],
	T.[Sales Order Header Creation Calendar Day in Year] = S.[CLNDR_DAY_IN_YR],
	T.[Sales Order Header Creation Calendar Week] = S.[CLNDR_WK],
	T.[Sales Order Header Creation Calendar Month in Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
	T.[Sales Order Header Creation Calendar Days in Month] = S.[CLNDR_DAYS_IN_MNTH],
	T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
	T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
	T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
	T.[Sales Order Header Creation Current Day Flag] = S.[CURR_DAY_FLG],
	T.[Sales Order Header Creation Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
	T.[Sales Order Header Creation Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
	T.[Sales Order Header Creation Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
	T.[Sales Order Header Creation Current Month Flag] = S.[CURR_MNTH_FLG],
	T.[Sales Order Header Creation Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
	T.[Sales Order Header Creation Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
	T.[Sales Order Header Creation Current Quarter Flag] = S.[CURR_QTR_FLG],
	T.[Sales Order Header Creation Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
	T.[Sales Order Header Creation Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
	T.[Sales Order Header Creation Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
	T.[Sales Order Header Creation Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
	T.[Sales Order Header Creation Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
	T.[Sales Order Header Creation Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
	T.[Sales Order Header Creation Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
	T.[Sales Order Header Creation Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
	T.[Sales Order Header Creation Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
	T.[Sales Order Header Creation Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
	T.[Sales Order Header Creation Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
	T.[IS_WEEKDAY] = S.[IS_WEEKDAY],
	T.[FISCAL_WK] = S.[FISCAL_WK],
	T.[Sales Order Header Creation Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
	T.[Sales Order Header Creation Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
	T.[Sales Order Header Creation Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
	T.[Sales Order Header Creation Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
	T.[CURR_MNTH_MINUS_2_FLG] = S.[CURR_MNTH_MINUS_2_FLG],
	T.[Sales Order Header Creation Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
	T.[Sales Order Header Creation Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
	T.[Sales Order Header Creation Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
	T.[Sales Order Header Creation Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
	T.[Sales Order Header Creation Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
	T.[Sales Order Header Creation Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]

FROM [GLOBAL_EDW].[Propelis].[SALES_ORDER_HEADER_CREATE_DATE] T
INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    ON T.[DATE_KEY] = S.[DATE_KEY]; 

-- Step 2: Insert new records from [GLOBAL_EDW_MIRROR] to [GLOBAL_EDW] where DATE_KEY does not exist

    INSERT INTO [GLOBAL_EDW].[Propelis].[SALES_ORDER_HEADER_CREATE_DATE] 
	(
		T.[DATE_KEY],															 
		T.[Sales Order Header Creation Date],                                    
		T.[Sales Order Header Creation Fiscal Year],                             
		T.[Sales Order Header Creation Fiscal Period],                           
		T.[Sales Order Header Creation Fiscal Period Code],                      
		T.[Sales Order Header Creation Calendar Quarter],                        
		T.[Sales Order Header Creation Fiscal Quarter Code],                     
		T.[Sales Order Header Creation Calendar Year],                           
		T.[Sales Order Header Creation Calendar Month Number],                   
		T.[Sales Order Header Creation Calendar Month Code],                     
		T.[Sales Order Header Creation Calendar Month Desc],                     
		T.[CLNDR_QTR_NUM],                                                       
		T.[Sales Order Header Creation Calendar Quarter Code],                   
		T.[Sales Order Header Creation Calendar Weekday Number],                 
		T.[Sales Order Header Creation Calendar Weekday Name],                   
		T.[Sales Order Header Creation Calendar Day in Month],                   
		T.[Sales Order Header Creation Calendar Day in Year],                    
		T.[Sales Order Header Creation Calendar Week],                           
		T.[Sales Order Header Creation Calendar Month in Quarter Number],        
		T.[Sales Order Header Creation Calendar Days in Month],                  
		T.[ETL_SRC_SYS_CD],                                                      
		T.[ETL_CREATED_TS],                                                      
		T.[ETL_UPDTD_TS],                                                        
		T.[Sales Order Header Creation Current Day Flag],                        
		T.[Sales Order Header Creation Current Day Minus 1 Flag],                
		T.[Sales Order Header Creation Current Calendar Week Flag],              
		T.[Sales Order Header Creation Current Calendar Week Minus 1 Flag],      
		T.[Sales Order Header Creation Current Month Flag],                      
		T.[Sales Order Header Creation Current Month Minus 1 Flag],              
		T.[Sales Order Header Creation Current Month Minus 12 Flag],             
		T.[Sales Order Header Creation Current Quarter Flag],                    
		T.[Sales Order Header Creation Current Quarter Minus 1 Flag],            
		T.[Sales Order Header Creation Current Quarter Minus 4 Flag],            
		T.[Sales Order Header Creation Current Calendar Year Flag],              
		T.[Sales Order Header Creation Current Calendar Year Minus 1 Flag],      
		T.[Sales Order Header Creation Current Calendar Year Minus 2 Flag],      
		T.[Sales Order Header Creation Current Fiscal Year Flag],                
		T.[Sales Order Header Creation Current Fiscal Year Minus 1 Flag],        
		T.[Sales Order Header Creation Current Fiscal Year Minus 2 Flag],        
		T.[Sales Order Header Creation Current Calendar Year Plus 1 Flag],       
		T.[Sales Order Header Creation Current Fiscal Year Plus 1 Flag],         
		T.[Sales Order Header Creation Day In Fiscal Year],                      
		T.[IS_WEEKDAY],                                                          
		T.[FISCAL_WK],                                                           
		T.[Sales Order Header Creation Current Fiscal Week Flag],                
		T.[Sales Order Header Creation Current Fiscal Week Minus 1 Flag],        
		T.[Sales Order Header Creation Fiscal Weekday Number],                   
		T.[Sales Order Header Creation Fiscal Weekday Name],                     
		T.[CURR_MNTH_MINUS_2_FLG],                                               
		T.[Sales Order Header Creation Current Fiscal Week Minus 2 Flag],        
		T.[Sales Order Header Creation Current Fiscal Week Minus 6 Flag],        
		T.[Sales Order Header Creation Current Fiscal Week Minus 3 Flag],        
		T.[Sales Order Header Creation Current Fiscal Week Minus 4 Flag],        
		T.[Sales Order Header Creation Current Fiscal Week Minus 5 Flag],        
		T.[Sales Order Header Creation Current Fiscal Week Minus 7 Flag]
	)
SELECT 

S.[DATE_KEY],
S.[THE_DATE],
S.[FISCAL_YR],
S.[FISCAL_PER_NUM],
S.[FISCAL_PER_CD],
S.[FISCAL_QTR_NUM],
S.[FISCAL_QTR_CD],
S.[CLNDR_YR],
S.[CLNDR_MNTH_NUM],
S.[CLNDR_MNTH_CD],
S.[CLNDR_MNTH_DESC],
S.[CLNDR_QTR_NUM],
S.[CLNDR_QTR_CD],
S.[CLNDR_WEEKDAY_NUM],
S.[CLNDR_WEEKDAY_NAME],
S.[CLNDR_DAY_IN_MNTH],
S.[CLNDR_DAY_IN_YR],
S.[CLNDR_WK],
S.[CLNDR_MNTH_IN_QTR_NUM],
S.[CLNDR_DAYS_IN_MNTH],
S.[ETL_SRC_SYS_CD],
S.[ETL_CREATED_TS],
S.[ETL_UPDTD_TS],
S.[CURR_DAY_FLG],
S.[CURR_DAY_MINUS_1_FLG],
S.[CURR_CLNDR_WK_FLG],
S.[CURR_CLNDR_WK_MINUS_1_FLG],
S.[CURR_MNTH_FLG],
S.[CURR_MNTH_MINUS_1_FLG],
S.[CURR_MNTH_MINUS_12_FLG],
S.[CURR_QTR_FLG],
S.[CURR_QTR_MINUS_1_FLG],
S.[CURR_QTR_MINUS_4_FLG],
S.[CURR_CLNDR_YR_FLG],
S.[CURR_CLNDR_YR_MINUS_1_FLG],
S.[CURR_CLNDR_YR_MINUS_2_FLG],
S.[CURR_FISCAL_YR_FLG],
S.[CURR_FISCAL_YR_MINUS_1_FLG],
S.[CURR_FISCAL_YR_MINUS_2_FLG],
S.[CURR_CLNDR_YR_PLUS_1_FLG],
S.[CURR_FISCAL_YR_PLUS_1_FLG],
S.[DAY_IN_FISCAL_YR],
S.[IS_WEEKDAY],
S.[FISCAL_WK],
S.[CURR_FISCAL_WK_FLG],
S.[CURR_FISCAL_WK_MINUS_1_FLG],
S.[FISCAL_WEEKDAY_NUM],
S.[FISCAL_WEEKDAY_NAME],
S.[CURR_MNTH_MINUS_2_FLG],
S.[CURR_FISCAL_WK_MINUS_2_FLG],
S.[CURR_FISCAL_WK_MINUS_6_FLG],
S.[CURR_FISCAL_WK_MINUS_3_FLG],
S.[CURR_FISCAL_WK_MINUS_4_FLG],
S.[CURR_FISCAL_WK_MINUS_5_FLG],
S.[CURR_FISCAL_WK_MINUS_7_FLG]



FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[SALES_ORDER_HEADER_CREATE_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;

END