CREATE    PROCEDURE [Propelis].[Proc_PROFIT_CENTER]
AS
BEGIN
    
    UPDATE T
    SET
      T.[PROFT_CNTR_KEY]	= S.[PROFT_CNTR_KEY],
      T.[Profit Center ID]	= S.[PROFT_CNTR_ID],
      T.[Profit Center Description]	= S.[PROFT_CNTR_DESC],
      T.[Legacy Profit Center Code]	= S.[LGCY_PROFT_CNTR_CD],
      T.[Legacy Profit Center Description]	= S.[LGCY_PROFT_CNTR_DESC],
      T.[Profit Center Controlling Area ID]	= S.[CONTROLLING_AREA_ID],
      T.[Profit Center User Responsible ID]	= S.[USR_RESPNSBLE_ID],
      T.[Profit Center Person Responsible]	= S.[PERSON_RESPNSBLE],
      T.[Profit Center Language Type Code]	= S.[LANG_TYP_CD],
      T.[Profit Center Segment ID]	= S.[SEG_ID],
      T.[Profit Center Address Line 1]	= S.[ADRESS_LINE_1],
      T.[Profit Center Address Line 2]	= S.[ADRESS_LINE_2],
      T.[Profit Center City Name]	= S.[CITY_NAME],
      T.[Profit Center District Name]	= S.[DISTR_NAME],
      T.[Profit Center Postal Code]	= S.[POSTAL_CD],
      T.[Profit Center Country Code]	= S.[CNTRY_CD],
      T.[Profit Center Region Code]	= S.[REGN_CD],
      T.[Profit Center Created Date]	= S.[CREATED_DATE],
      T.[Profit Center Created User ID]	= S.[CREATED_USR_ID],
      T.[Profit Center Updated Date]	= S.[UPDTD_DATE],
      T.[Profit Center Updated User ID]	= S.[UPDTD_USR_ID],
      T.[ETL_SRC_SYS_CD]	= S.[ETL_SRC_SYS_CD],
      T.[ETL_EFFECTV_BEGIN_DATE]	= S.[ETL_EFFECTV_BEGIN_DATE],
      T.[ETL_EFFECTV_END_DATE]	= S.[ETL_EFFECTV_END_DATE],
      T.[ETL_CURR_RCD_IND]	= S.[ETL_CURR_RCD_IND],
      T.[ETL_CREATED_TS]	= S.[ETL_CREATED_TS],
      T.[ETL_UPDTD_TS]	= S.[ETL_UPDTD_TS],
      T.[Profit Center Company Code]	= S.[CMPNY_CD],
      T.[Profit Center Long Description]	= S.[PROFT_CNTR_LONG_DESC],
      T.[Profit Center Short Description]	= S.[PROFT_CNTR_SHORT_DESC],
      T.[Profit Center Lock Indicator]	= S.[LOCK_IND],
      T.[Profit Center Name 1]	= S.[NAME_1],
      T.[Profit Center Area]	= S.[PROFT_CNTR_AREA],
      T.[Profit Center General Master Record Status]	= S.[GENERIC_MAST_RCD_STATUS],
      T.[Profit Center Status Description]	= S.[STATUS_DESC],
      T.[Profit Center Controlling Area Desc]	= S.[CONTROLLING_AREA_DESC],
      T.[Profit Center Country Description]	= S.[CNTRY_DESC],
      T.[Profit Center Company Description]	= S.[CMPNY_DESC],
      T.[Profit Center Tax Jurisdiction]	= S.[TAX_JRSDCTN],
      T.[Profit Center Valid To Date]	= S.[VALID_TO_DATE],
      T.[Profit Center Valid From Date]	= S.[VALID_FROM_DATE]

    FROM [GLOBAL_EDW].[Propelis].[PROFIT_CENTER] AS T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_PROFCTR_CUR_D] AS S
        ON T.[PROFT_CNTR_KEY] = S.[PROFT_CNTR_KEY];

    
    INSERT INTO [GLOBAL_EDW].[Propelis].[PROFIT_CENTER] (
       [PROFT_CNTR_KEY],
       [Profit Center ID],
       [Profit Center Description],
       [Legacy Profit Center Code],
       [Legacy Profit Center Description],
       [Profit Center Controlling Area ID],
       [Profit Center User Responsible ID],
       [Profit Center Person Responsible],
       [Profit Center Language Type Code],
       [Profit Center Segment ID],
       [Profit Center Address Line 1],
       [Profit Center Address Line 2],
       [Profit Center City Name],
       [Profit Center District Name],
       [Profit Center Postal Code],
       [Profit Center Country Code],
       [Profit Center Region Code],
       [Profit Center Created Date],
       [Profit Center Created User ID],
       [Profit Center Updated Date],
       [Profit Center Updated User ID],
       [ETL_SRC_SYS_CD],
       [ETL_EFFECTV_BEGIN_DATE],
       [ETL_EFFECTV_END_DATE],
       [ETL_CURR_RCD_IND],
       [ETL_CREATED_TS],
       [ETL_UPDTD_TS],
       [Profit Center Company Code],
       [Profit Center Long Description],
       [Profit Center Short Description],
       [Profit Center Lock Indicator],
       [Profit Center Name 1],
       [Profit Center Area],
       [Profit Center General Master Record Status],
       [Profit Center Status Description],
       [Profit Center Controlling Area Desc],
       [Profit Center Country Description],
       [Profit Center Company Description],
       [Profit Center Tax Jurisdiction],
       [Profit Center Valid To Date],
       [Profit Center Valid From Date]

    )
    SELECT
        S.[PROFT_CNTR_KEY],
        S.[PROFT_CNTR_ID],
        S.[PROFT_CNTR_DESC],
        S.[LGCY_PROFT_CNTR_CD],
        S.[LGCY_PROFT_CNTR_DESC],
        S.[CONTROLLING_AREA_ID],
        S.[USR_RESPNSBLE_ID],
        S.[PERSON_RESPNSBLE],
        S.[LANG_TYP_CD],
        S.[SEG_ID],
        S.[ADRESS_LINE_1],
        S.[ADRESS_LINE_2],
        S.[CITY_NAME],
        S.[DISTR_NAME],
        S.[POSTAL_CD],
        S.[CNTRY_CD],
        S.[REGN_CD],
        S.[CREATED_DATE],
        S.[CREATED_USR_ID],
        S.[UPDTD_DATE],
        S.[UPDTD_USR_ID],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CMPNY_CD],
        S.[PROFT_CNTR_LONG_DESC],
        S.[PROFT_CNTR_SHORT_DESC],
        S.[LOCK_IND],
        S.[NAME_1],
        S.[PROFT_CNTR_AREA],
        S.[GENERIC_MAST_RCD_STATUS],
        S.[STATUS_DESC],
        S.[CONTROLLING_AREA_DESC],
        S.[CNTRY_DESC],
        S.[CMPNY_DESC],
        S.[TAX_JRSDCTN],
        S.[VALID_TO_DATE],
        S.[VALID_FROM_DATE]

    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_PROFCTR_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[PROFIT_CENTER] AS T
        ON T.[PROFT_CNTR_KEY] = S.[PROFT_CNTR_KEY]
    WHERE T.[PROFT_CNTR_KEY] IS NULL;

END