CREATE        PROCEDURE [Propelis].[Proc_SOLD_TO_CUST]
AS
BEGIN
    -- Step 1: Update existing records in target table
    UPDATE T
    SET
                T.[CUST_KEY]	         = S.[CUST_KEY],
                T.[Sold To Customer ID]	         = S.[CUST_ID],
                T.[Sold To Customer Legacy ID]	         = S.[LGCY_CUST_ID],
                T.[Sold To Customer Name]	         = S.[CUST_NAME],
                T.[Sold To Cust Line 2 Description]	         = S.[CUST_LINE_2_DESC],
                T.[Sold To Cust Country Code]	         = S.[CNTRY_CD],
                T.[Sold To Cust Plant ID]	         = S.[PLNT_ID],
                T.[Sold To Cust Segment ID]	         = S.[SEG_ID],
                T.[Sold To Cust Industry]	         = S.[INDUS],
                T.[Sold To Cust Vendor ID]	         = S.[VNDR_ID],
                T.[Sold To Cust Group Code]	         = S.[CUST_GROUP_CD],
                T.[Sold To Cust Account Group Code]	         = S.[CUST_ACCT_GROUP_CD],
                T.[Sold To Cust Title]	         = S.[TITLE],
                T.[Sold To Cust Search Term]	         = S.[SEARCH_TERM],
                T.[Sold To Cust Street]	         = S.[STR],
                T.[Sold To Cust City Name]	         = S.[CITY_NAME],
                T.[Sold To Cust Zip Code]	         = S.[ZIP_CD],
                T.[Sold To Cust State Code]	         = S.[ST_CD],
                T.[Sold To Cust Region Code]	         = S.[REGN_CD],
                T.[Sold To Cust Telephone Number 1 Code]	         = S.[TEL_NUM_1_CD],
                T.[Sold To Cust Telephone Number 2 Code]	         = S.[TEL_NUM_2_CD],
                T.[Sold To Cust Fax Number Code]	         = S.[FAX_NUM_CD],
                T.[Sold To Cust Tax Number 1 Code]	         = S.[TAX_NUM_1_CD],
                T.[Sold To Cust Tax Number 2 Code]	         = S.[TAX_NUM_2_CD],
                T.[Sold To Cust VAT Number Code]	         = S.[VAT_NUM_CD],
                T.[Sold To Cust Credit Limit]	         = S.[CREDIT_LMT],
                T.[Sold To Cust Bonus Rate]	         = S.[BONUS_RT],
                T.[Sold To Cust Express Station]	         = S.[EXPRESS_STATION],
                T.[Sold To Cust Transportation Zone]	         = S.[TRANSTN_ZONE],
                T.[Sold To Cust Printer Location Characteristics]	         = S.[PRINTER_LOC_CHARS],
                T.[Sold To Cust Printer Region Characteristics]	         = S.[PRINTER_REGN_CHARS],
                T.[Sold To Cust Printer Site Characteristics]	         = S.[PRINTER_SITE_CHARS],
                T.[Sold To Cust Created Date]	         = S.[CREATED_DATE],
                T.[Sold To Cust Created User ID]	         = S.[CREATED_USR_ID],
                T.[Sold To Cust Updated Date]	         = S.[UPDTD_DATE],
                T.[Sold To Cust Updated User ID]	         = S.[UPDTD_USR_ID],
                T.[Sold To Cust Payment Terms Code]	         = S.[PYMT_TRMS_CD],
                T.[Sold To Cust Sales Distribution]	         = S.[SALES_DISTR],
                T.[Sold To Cust Order Block For Sales Area]	         = S.[ORDER_BLK_FOR_SALES_AREA],
                T.[Sold To Cust Delivery Block For Sales Area]	         = S.[DLVRY_BLK_FOR_SALES_AREA],
                T.[ETL_SRC_SYS_CD]	         = S.[ETL_SRC_SYS_CD],
                T.[ETL_EFFECTV_BEGIN_DATE]	         = S.[ETL_EFFECTV_BEGIN_DATE],
                T.[ETL_EFFECTV_END_DATE]	         = S.[ETL_EFFECTV_END_DATE],
                T.[ETL_CURR_RCD_IND]	         = S.[ETL_CURR_RCD_IND],
                T.[ETL_CREATED_TS]	         = S.[ETL_CREATED_TS],
                T.[ETL_UPDTD_TS]	         = S.[ETL_UPDTD_TS],
                T.[Sold To Cust Corporate Group]	         = S.[CORPORATE_GROUP],
                T.[Sold To Cust Classification]	         = S.[CUST_CLSFTN],
                T.[Sold To Cust Classification Description]	         = S.[CUST_CLSFTN_DESC],
                T.[Sold To Cust Printer Location]	         = S.[PRINTER_LOC],
                T.[Sold To Cust Printer Site]	         = S.[PRINTER_SITE],
                T.[Sold To Cust Printer Region]	         = S.[PRINTER_REGN],
                T.[Sold To Cust Specific Field Label 01]	         = S.[CUST_SPECIFIC_FLD_LBL_01],
                T.[Sold To Cust Specific Field Label 02]	         = S.[CUST_SPECIFIC_FLD_LBL_02],
                T.[Sold To Cust Specific Field Label 03]	         = S.[CUST_SPECIFIC_FLD_LBL_03],
                T.[Sold To Cust Specific Field Label 04]	         = S.[CUST_SPECIFIC_FLD_LBL_04],
                T.[Sold To Cust Specific Field Label 05]	         = S.[CUST_SPECIFIC_FLD_LBL_05],
                T.[Sold To Cust Specific Field Label 06]	         = S.[CUST_SPECIFIC_FLD_LBL_06],
                T.[Sold To Cust Specific Field Label 07]	         = S.[CUST_SPECIFIC_FLD_LBL_07],
                T.[Sold To Cust Specific Field Label 08]	         = S.[CUST_SPECIFIC_FLD_LBL_08],
                T.[Sold To Cust Specific Field Label 09]	         = S.[CUST_SPECIFIC_FLD_LBL_09],
                T.[Sold To Cust Specific Field Label 10]	         = S.[CUST_SPECIFIC_FLD_LBL_10],
                T.[Sold To Cust Specific Field Label 11]	         = S.[CUST_SPECIFIC_FLD_LBL_11],
                T.[Sold To Cust Specific Field Label 12]	         = S.[CUST_SPECIFIC_FLD_LBL_12],
                T.[Sold To Cust Specific Field Label 13]	         = S.[CUST_SPECIFIC_FLD_LBL_13],
                T.[Sold To Cust Specific Field Label 14]	         = S.[CUST_SPECIFIC_FLD_LBL_14],
                T.[Sold To Cust Specific Field Label 15]	         = S.[CUST_SPECIFIC_FLD_LBL_15],
                T.[Sold To Cust Specific Field Label 16]	         = S.[CUST_SPECIFIC_FLD_LBL_16],
                T.[Sold To Cust Specific Field Label 17]	         = S.[CUST_SPECIFIC_FLD_LBL_17],
                T.[Sold To Cust Specific Field Label 18]	         = S.[CUST_SPECIFIC_FLD_LBL_18],
                T.[Sold To Cust Specific Field Label 19]	         = S.[CUST_SPECIFIC_FLD_LBL_19],
                T.[Sold To Cust Specific Field Label 20]	         = S.[CUST_SPECIFIC_FLD_LBL_20],
                T.[Sold To Cust Condition Group 1]	         = S.[CUST_COND_GROUP_1],
                T.[Sold To Cust Industry Code 1]	         = S.[INDUS_CD_1],
                T.[Sold To Cust Industry Code 2]	         = S.[INDUS_CD_2],
                T.[Sold To Cust Industry Description]	         = S.[INDUS_DESC],
                T.[Sold To Cust Industry Code 1 Description]	         = S.[INDUS_CD_1_DESC],
                T.[Sold To Cust Industry Code 2 Description]	         = S.[INDUS_CD_2_DESC],
                T.[Sold To Cust Assignment to Hierarchy]	         = S.[ASSIGN_TO_HIERCHY],
                T.[Sold To Cust Account Group Description]	         = S.[CUST_ACCT_GROUP_DESC],
                T.[Sold To Cust Region Description]	         = S.[REGN_DESC],
                T.[Sold To Cust Country Description]	         = S.[CNTRY_DESC],
                T.[Sold To Cust Transportation Zone Description]	         = S.[TRANSTN_ZONE_DESC],
                T.[Sold To Cust Plant Description]	         = S.[PLNT_DESC],
                T.[Sold To Cust Condition Group Description]	         = S.[CUST_COND_GROUP_DESC],
                T.[Sold To Cust Central Billing Block]	         = S.[CENTRAL_BILLING_BLK],
                T.[Sold To Cust Central Billing Block Description]	         = S.[CENTRAL_BILLING_BLK_DESC],
                T.[Sold To Cust Central Delivery Block]	         = S.[CENTRAL_DLVRY_BLK],
                T.[Sold To Cust Central Delivery Block Description]	         = S.[CENTRAL_DLVRY_BLK_DESC],
                T.[Sold To Cust Deletion Indicator]	         = S.[DELETION_IND],
                T.[Sold To Cust Central Posting Block]	         = S.[CENTRAL_PSTNG_BLK],
                T.[Sold To Cust Tax Jurisdiction]	         = S.[TAX_JRSDCTN],
                T.[Sold To Cust Central Sales Block]	         = S.[CENTRAL_SALES_BLK],
                T.[Sold To Cust Central Deletion Indicator]	         = S.[CENTRAL_DELETION_IND],
                T.[Sold To Cust Language Key]	         = S.[LANG_KEY],
                T.[Sold To Cust Trading Partner]	         = S.[TRADING_PRTNR],
                T.[Sold To Cust Trading Partner Description]	         = S.[TRADING_PRTNR_DESC],
                T.[Sold To Cust Annual Sales]	         = S.[ANNUAL_SALES],
                T.[Sold To Cust Annual Sales Year]	         = S.[ANNUAL_SALES_YR],
                T.[Sold To Cust Sales Currency]	         = S.[SALES_CRNCY],
                T.[Sold To Cust Sales Currency Description]	         = S.[SALES_CRNCY_DESC],
                T.[Sold To Cust One Time Account Group]	         = S.[ONE_TM_CUST_ACCT_GROUP],
                T.[Sold To Cust One Time Account Group Description]	         = S.[ONE_TM_CUST_ACCT_GROUP_DESC],
                T.[Sold To Cust One Time Cust Indicator]	         = S.[ONE_TM_CUST_IND],
                T.[Sold To Cust Industry Type]	         = S.[INDUS_TYP],
                T.[Sold To Cust Business Type]	         = S.[BIZ_TYP],
                T.[Sold To Cust DUNS Number]	         = S.[DUNS_NUM],
                T.[Sold To Cust DUNS Plus 4]	         = S.[DUNS_PLUS_4],
                T.[Sold To Cust City Coordinates]	         = S.[CITY_COORDINATES],
                T.[Sold To Cust Tax Number 4 Code]	         = S.[TAX_NUM_4_CD],
                T.[Sold To Cust Attribute 3]	         = S.[ATTRIB_3],
                T.[Sold To Cust Attribute 3 Description]	         = S.[ATTRIB_3_DESC],
                T.[Sold To Cust E-Mail Address]	         = S.[E_MAIL_ADDR],
                T.[Sold To Cust Mobile Number]	         = S.[MOBILE_NUM],
                T.[Sold To Cust Search Term 2]	         = S.[SEARCH_TERM_2],
                T.[Sold To Cust Street 2]	         = S.[STR_2],
                T.[Sold To Cust Street 3]	         = S.[STR_3],
                T.[Sold To Cust Street 4]	         = S.[STR_4],
                T.[Sold To Cust Street 5]	         = S.[STR_5],
                T.[Sold To Cust PO Box]	         = S.[PO_BOX],
                T.[Sold To Cust PO Box Postal Code]	         = S.[PO_BOX_POSTAL_CD],
                T.[Sold To Cust PO Box City]	         = S.[PO_BOX_CITY],
                T.[Sold To Cust Region For PO Box]	         = S.[REGN_FOR_PO_BOX],
                T.[Sold To Cust PO Box Country]	         = S.[PO_BOX_CNTRY],
                T.[Sold To Cust Transport Zone]	         = S.[TRNSPRT_ZONE],
                T.[Sold To Cust Address Notes]	         = S.[ADDR_NOTES],
                T.[Sold To Cust Tax Number 3 Code]	         = S.[TAX_NUM_3],
                T.[Sold To Cust Tax Number 5 Code]	         = S.[TAX_NUM_5],
                T.[Sold To Cust Industry Code 3]	         = S.[INDUS_CD_3],
                T.[Sold To Cust Industry Code 3 Description]	         = S.[INDUS_CD_3_DESC],
                T.[Sold To Cust Industry Code 4]	         = S.[INDUS_CD_4],
                T.[Sold To Cust Industry Code 4 Description]	         = S.[INDUS_CD_4_DESC],
                T.[Sold To Cust Industry Code 5]	         = S.[INDUS_CD_5],
                T.[Sold To Cust Industry Code 5 Description]	         = S.[INDUS_CD_5_DESC],
                T.[Sold To Cust Central Order Block For Customer]	         = S.[CENTRAL_ORDER_BLK_FOR_CUST],
                T.[Sold To Cust Payment Block]	         = S.[PYMT_BLK]


    FROM [GLOBAL_EDW].[Propelis].[SOLD_TO_CUST] AS T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CUSTOMR_CUR_D] AS S
        ON T.[CUST_KEY] = S.[CUST_KEY];

    -- Step 2: Insert new records from mirror to target table
    INSERT INTO [GLOBAL_EDW].[Propelis].[SOLD_TO_CUST] (
                 [CUST_KEY],
                 [Sold To Customer ID],
                 [Sold To Customer Legacy ID],
                 [Sold To Customer Name],
                 [Sold To Cust Line 2 Description],
                 [Sold To Cust Country Code],
                 [Sold To Cust Plant ID],
                 [Sold To Cust Segment ID],
                 [Sold To Cust Industry],
                 [Sold To Cust Vendor ID],
                 [Sold To Cust Group Code],
                 [Sold To Cust Account Group Code],
                 [Sold To Cust Title],
                 [Sold To Cust Search Term],
                 [Sold To Cust Street],
                 [Sold To Cust City Name],
                 [Sold To Cust Zip Code],
                 [Sold To Cust State Code],
                 [Sold To Cust Region Code],
                 [Sold To Cust Telephone Number 1 Code],
                 [Sold To Cust Telephone Number 2 Code],
                 [Sold To Cust Fax Number Code],
                 [Sold To Cust Tax Number 1 Code],
                 [Sold To Cust Tax Number 2 Code],
                 [Sold To Cust VAT Number Code],
                 [Sold To Cust Credit Limit],
                 [Sold To Cust Bonus Rate],
                 [Sold To Cust Express Station],
                 [Sold To Cust Transportation Zone],
                 [Sold To Cust Printer Location Characteristics],
                 [Sold To Cust Printer Region Characteristics],
                 [Sold To Cust Printer Site Characteristics],
                 [Sold To Cust Created Date],
                 [Sold To Cust Created User ID],
                 [Sold To Cust Updated Date],
                 [Sold To Cust Updated User ID],
                 [Sold To Cust Payment Terms Code],
                 [Sold To Cust Sales Distribution],
                 [Sold To Cust Order Block For Sales Area],
                 [Sold To Cust Delivery Block For Sales Area],
                 [ETL_SRC_SYS_CD],
                 [ETL_EFFECTV_BEGIN_DATE],
                 [ETL_EFFECTV_END_DATE],
                 [ETL_CURR_RCD_IND],
                 [ETL_CREATED_TS],
                 [ETL_UPDTD_TS],
                 [Sold To Cust Corporate Group],
                 [Sold To Cust Classification],
                 [Sold To Cust Classification Description],
                 [Sold To Cust Printer Location],
                 [Sold To Cust Printer Site],
                 [Sold To Cust Printer Region],
                 [Sold To Cust Specific Field Label 01],
                 [Sold To Cust Specific Field Label 02],
                 [Sold To Cust Specific Field Label 03],
                 [Sold To Cust Specific Field Label 04],
                 [Sold To Cust Specific Field Label 05],
                 [Sold To Cust Specific Field Label 06],
                 [Sold To Cust Specific Field Label 07],
                 [Sold To Cust Specific Field Label 08],
                 [Sold To Cust Specific Field Label 09],
                 [Sold To Cust Specific Field Label 10],
                 [Sold To Cust Specific Field Label 11],
                 [Sold To Cust Specific Field Label 12],
                 [Sold To Cust Specific Field Label 13],
                 [Sold To Cust Specific Field Label 14],
                 [Sold To Cust Specific Field Label 15],
                 [Sold To Cust Specific Field Label 16],
                 [Sold To Cust Specific Field Label 17],
                 [Sold To Cust Specific Field Label 18],
                 [Sold To Cust Specific Field Label 19],
                 [Sold To Cust Specific Field Label 20],
                 [Sold To Cust Condition Group 1],
                 [Sold To Cust Industry Code 1],
                 [Sold To Cust Industry Code 2],
                 [Sold To Cust Industry Description],
                 [Sold To Cust Industry Code 1 Description],
                 [Sold To Cust Industry Code 2 Description],
                 [Sold To Cust Assignment to Hierarchy],
                 [Sold To Cust Account Group Description],
                 [Sold To Cust Region Description],
                 [Sold To Cust Country Description],
                 [Sold To Cust Transportation Zone Description],
                 [Sold To Cust Plant Description],
                 [Sold To Cust Condition Group Description],
                 [Sold To Cust Central Billing Block],
                 [Sold To Cust Central Billing Block Description],
                 [Sold To Cust Central Delivery Block],
                 [Sold To Cust Central Delivery Block Description],
                 [Sold To Cust Deletion Indicator],
                 [Sold To Cust Central Posting Block],
                 [Sold To Cust Tax Jurisdiction],
                 [Sold To Cust Central Sales Block],
                 [Sold To Cust Central Deletion Indicator],
                 [Sold To Cust Language Key],
                 [Sold To Cust Trading Partner],
                 [Sold To Cust Trading Partner Description],
                 [Sold To Cust Annual Sales],
                 [Sold To Cust Annual Sales Year],
                 [Sold To Cust Sales Currency],
                 [Sold To Cust Sales Currency Description],
                 [Sold To Cust One Time Account Group],
                 [Sold To Cust One Time Account Group Description],
                 [Sold To Cust One Time Cust Indicator],
                 [Sold To Cust Industry Type],
                 [Sold To Cust Business Type],
                 [Sold To Cust DUNS Number],
                 [Sold To Cust DUNS Plus 4],
                 [Sold To Cust City Coordinates],
                 [Sold To Cust Tax Number 4 Code],
                 [Sold To Cust Attribute 3],
                 [Sold To Cust Attribute 3 Description],
                 [Sold To Cust E-Mail Address],
                 [Sold To Cust Mobile Number],
                 [Sold To Cust Search Term 2],
                 [Sold To Cust Street 2],
                 [Sold To Cust Street 3],
                 [Sold To Cust Street 4],
                 [Sold To Cust Street 5],
                 [Sold To Cust PO Box],
                 [Sold To Cust PO Box Postal Code],
                 [Sold To Cust PO Box City],
                 [Sold To Cust Region For PO Box],
                 [Sold To Cust PO Box Country],
                 [Sold To Cust Transport Zone],
                 [Sold To Cust Address Notes],
                 [Sold To Cust Tax Number 3 Code],
                 [Sold To Cust Tax Number 5 Code],
                 [Sold To Cust Industry Code 3],
                 [Sold To Cust Industry Code 3 Description],
                 [Sold To Cust Industry Code 4],
                 [Sold To Cust Industry Code 4 Description],
                 [Sold To Cust Industry Code 5],
                 [Sold To Cust Industry Code 5 Description],
                 [Sold To Cust Central Order Block For Customer],
                 [Sold To Cust Payment Block]

    )
    SELECT
         S.[CUST_KEY],
         S.[CUST_ID],
         S.[LGCY_CUST_ID],
         S.[CUST_NAME],
         S.[CUST_LINE_2_DESC],
         S.[CNTRY_CD],
         S.[PLNT_ID],
         S.[SEG_ID],
         S.[INDUS],
         S.[VNDR_ID],
         S.[CUST_GROUP_CD],
         S.[CUST_ACCT_GROUP_CD],
         S.[TITLE],
         S.[SEARCH_TERM],
         S.[STR],
         S.[CITY_NAME],
         S.[ZIP_CD],
         S.[ST_CD],
         S.[REGN_CD],
         S.[TEL_NUM_1_CD],
         S.[TEL_NUM_2_CD],
         S.[FAX_NUM_CD],
         S.[TAX_NUM_1_CD],
         S.[TAX_NUM_2_CD],
         S.[VAT_NUM_CD],
         S.[CREDIT_LMT],
         S.[BONUS_RT],
         S.[EXPRESS_STATION],
         S.[TRANSTN_ZONE],
         S.[PRINTER_LOC_CHARS],
         S.[PRINTER_REGN_CHARS],
         S.[PRINTER_SITE_CHARS],
         S.[CREATED_DATE],
         S.[CREATED_USR_ID],
         S.[UPDTD_DATE],
         S.[UPDTD_USR_ID],
         S.[PYMT_TRMS_CD],
         S.[SALES_DISTR],
         S.[ORDER_BLK_FOR_SALES_AREA],
         S.[DLVRY_BLK_FOR_SALES_AREA],
         S.[ETL_SRC_SYS_CD],
         S.[ETL_EFFECTV_BEGIN_DATE],
         S.[ETL_EFFECTV_END_DATE],
         S.[ETL_CURR_RCD_IND],
         S.[ETL_CREATED_TS],
         S.[ETL_UPDTD_TS],
         S.[CORPORATE_GROUP],
         S.[CUST_CLSFTN],
         S.[CUST_CLSFTN_DESC],
         S.[PRINTER_LOC],
         S.[PRINTER_SITE],
         S.[PRINTER_REGN],
         S.[CUST_SPECIFIC_FLD_LBL_01],
         S.[CUST_SPECIFIC_FLD_LBL_02],
         S.[CUST_SPECIFIC_FLD_LBL_03],
         S.[CUST_SPECIFIC_FLD_LBL_04],
         S.[CUST_SPECIFIC_FLD_LBL_05],
         S.[CUST_SPECIFIC_FLD_LBL_06],
         S.[CUST_SPECIFIC_FLD_LBL_07],
         S.[CUST_SPECIFIC_FLD_LBL_08],
         S.[CUST_SPECIFIC_FLD_LBL_09],
         S.[CUST_SPECIFIC_FLD_LBL_10],
         S.[CUST_SPECIFIC_FLD_LBL_11],
         S.[CUST_SPECIFIC_FLD_LBL_12],
         S.[CUST_SPECIFIC_FLD_LBL_13],
         S.[CUST_SPECIFIC_FLD_LBL_14],
         S.[CUST_SPECIFIC_FLD_LBL_15],
         S.[CUST_SPECIFIC_FLD_LBL_16],
         S.[CUST_SPECIFIC_FLD_LBL_17],
         S.[CUST_SPECIFIC_FLD_LBL_18],
         S.[CUST_SPECIFIC_FLD_LBL_19],
         S.[CUST_SPECIFIC_FLD_LBL_20],
         S.[CUST_COND_GROUP_1],
         S.[INDUS_CD_1],
         S.[INDUS_CD_2],
         S.[INDUS_DESC],
         S.[INDUS_CD_1_DESC],
         S.[INDUS_CD_2_DESC],
         S.[ASSIGN_TO_HIERCHY],
         S.[CUST_ACCT_GROUP_DESC],
         S.[REGN_DESC],
         S.[CNTRY_DESC],
         S.[TRANSTN_ZONE_DESC],
         S.[PLNT_DESC],
         S.[CUST_COND_GROUP_DESC],
         S.[CENTRAL_BILLING_BLK],
         S.[CENTRAL_BILLING_BLK_DESC],
         S.[CENTRAL_DLVRY_BLK],
         S.[CENTRAL_DLVRY_BLK_DESC],
         S.[DELETION_IND],
         S.[CENTRAL_PSTNG_BLK],
         S.[TAX_JRSDCTN],
         S.[CENTRAL_SALES_BLK],
         S.[CENTRAL_DELETION_IND],
         S.[LANG_KEY],
         S.[TRADING_PRTNR],
         S.[TRADING_PRTNR_DESC],
         S.[ANNUAL_SALES],
         S.[ANNUAL_SALES_YR],
         S.[SALES_CRNCY],
         S.[SALES_CRNCY_DESC],
         S.[ONE_TM_CUST_ACCT_GROUP],
         S.[ONE_TM_CUST_ACCT_GROUP_DESC],
         S.[ONE_TM_CUST_IND],
         S.[INDUS_TYP],
         S.[BIZ_TYP],
         S.[DUNS_NUM],
         S.[DUNS_PLUS_4],
         S.[CITY_COORDINATES],
         S.[TAX_NUM_4_CD],
         S.[ATTRIB_3],
         S.[ATTRIB_3_DESC],
         S.[E_MAIL_ADDR],
         S.[MOBILE_NUM],
         S.[SEARCH_TERM_2],
         S.[STR_2],
         S.[STR_3],
         S.[STR_4],
         S.[STR_5],
         S.[PO_BOX],
         S.[PO_BOX_POSTAL_CD],
         S.[PO_BOX_CITY],
         S.[REGN_FOR_PO_BOX],
         S.[PO_BOX_CNTRY],
         S.[TRNSPRT_ZONE],
         S.[ADDR_NOTES],
         S.[TAX_NUM_3],
         S.[TAX_NUM_5],
         S.[INDUS_CD_3],
         S.[INDUS_CD_3_DESC],
         S.[INDUS_CD_4],
         S.[INDUS_CD_4_DESC],
         S.[INDUS_CD_5],
         S.[INDUS_CD_5_DESC],
         S.[CENTRAL_ORDER_BLK_FOR_CUST],
         S.[PYMT_BLK]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CUSTOMR_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[SOLD_TO_CUST] AS T
        ON T.[CUST_KEY] = S.[CUST_KEY]
    WHERE T.[CUST_KEY] IS NULL;

END