CREATE       PROCEDURE [Propelis].[Proc_CUST_HIERARCHY1]
AS
BEGIN  
    -- Update existing records
    UPDATE T SET
        T.[CUST_KEY] = S.[CUST_KEY],                                                                                   
        T.[Customer Hierarchy1 ID] = S.[CUST_ID],
        T.[Customer Hierarchy1 Legacy Customer ID] = S.[LGCY_CUST_ID],
        T.[Customer Hierarchy1 Name] = S.[CUST_NAME],
        T.[Customer Hierarchy1 Line 2 Description] = S.[CUST_LINE_2_DESC],
        T.[Customer Hierarchy1 Country Code] = S.[CNTRY_CD],
        T.[Customer Hierarchy1 Plant ID] = S.[PLNT_ID],
        T.[Customer Hierarchy1 Segment ID] = S.[SEG_ID],
        T.[Customer Hierarchy1 Industry] = S.[INDUS],
        T.[Customer Hierarchy1 Vendor ID] = S.[VNDR_ID],
        T.[Customer Hierarchy1 Customer Group Code] = S.[CUST_GROUP_CD],
        T.[Customer Hierarchy1 Account Group Code] = S.[CUST_ACCT_GROUP_CD],
        T.[Customer Hierarchy1 Title] = S.[TITLE],
        T.[Customer Hierarchy1 Search Term] = S.[SEARCH_TERM],
        T.[Customer Hierarchy1 Street] = S.[STR],
        T.[Customer Hierarchy1 City] = S.[CITY_NAME],
        T.[Customer Hierarchy1 Zip Code] = S.[ZIP_CD],
        T.[Customer Hierarchy1 State Code] = S.[ST_CD],
        T.[Customer Hierarchy1 Region Code] = S.[REGN_CD],
        T.[Customer Hierarchy1 Telephone Number 1] = S.[TEL_NUM_1_CD],
        T.[Customer Hierarchy1 Telephone Number 2] = S.[TEL_NUM_2_CD],
        T.[Customer Hierarchy1 Fax Number Code] = S.[FAX_NUM_CD],
        T.[Customer Hierarchy1 Tax Number 1 Code] = S.[TAX_NUM_1_CD],
        T.[Customer Hierarchy1 Tax Number 2 Code] = S.[TAX_NUM_2_CD],
        T.[Customer Hierarchy1 VAT Number Code] = S.[VAT_NUM_CD],
        T.[Customer Hierarchy1 Credit Limit] = S.[CREDIT_LMT],                                         
        T.[Customer Hierarchy1 Bonus Rate] = S.[BONUS_RT],
        T.[Customer Hierarchy1 Express Station] = S.[EXPRESS_STATION],
        T.[Customer Hierarchy1 Transportation Zone] = S.[TRANSTN_ZONE],
        T.[Customer Hierarchy1 Printer Location Characteristics] = S.[PRINTER_LOC_CHARS],
        T.[Customer Hierarchy1 Printer Region Characteristics] = S.[PRINTER_REGN_CHARS],
        T.[Customer Hierarchy1 Printer Site Characteristics] = S.[PRINTER_SITE_CHARS],
        T.[Customer Hierarchy1 Customer Created Date] = S.[CREATED_DATE],
        T.[Customer Hierarchy1 Created User ID] = S.[CREATED_USR_ID],
        T.[Customer Hierarchy1 Customer Updated Date] = S.[UPDTD_DATE],
        T.[Customer Hierarchy1 Updated User ID] = S.[UPDTD_USR_ID],
        T.[Customer Hierarchy1 Payment Terms Code] = S.[PYMT_TRMS_CD],
        T.[Customer Hierarchy1 Sales Distribution] = S.[SALES_DISTR],
        T.[Customer Hierarchy1 Order Block For Sales Area] = S.[ORDER_BLK_FOR_SALES_AREA],
        T.[Customer Hierarchy1 Delivery Block For Sales Area] = S.[DLVRY_BLK_FOR_SALES_AREA],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE] = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE] = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND] = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Customer Hierarchy1 Corporate Group] = S.[CORPORATE_GROUP],
        T.[Customer Hierarchy1 Classification] = S.[CUST_CLSFTN],
        T.[Customer Hierarchy1 Classification Description] = S.[CUST_CLSFTN_DESC],
        T.[Customer Hierarchy1 Printer Location] = S.[PRINTER_LOC],
        T.[Customer Hierarchy1 Printer Site] = S.[PRINTER_SITE],
        T.[Customer Hierarchy1 Printer Region] = S.[PRINTER_REGN],
        T.[Customer Hierarchy1 Specific Field Label 01] = S.[CUST_SPECIFIC_FLD_LBL_01],
        T.[Customer Hierarchy1 Specific Field Label 02] = S.[CUST_SPECIFIC_FLD_LBL_02],
        T.[Customer Hierarchy1 Specific Field Label 03] = S.[CUST_SPECIFIC_FLD_LBL_03],
        T.[Customer Hierarchy1 Specific Field Label 04] = S.[CUST_SPECIFIC_FLD_LBL_04],
        T.[Customer Hierarchy1 Specific Field Label 05] = S.[CUST_SPECIFIC_FLD_LBL_05],
        T.[Customer Hierarchy1 Specific Field Label 06] = S.[CUST_SPECIFIC_FLD_LBL_06],
        T.[Customer Hierarchy1 Specific Field Label 07] = S.[CUST_SPECIFIC_FLD_LBL_07],
        T.[Customer Hierarchy1 Specific Field Label 08] = S.[CUST_SPECIFIC_FLD_LBL_08],
        T.[Customer Hierarchy1 Specific Field Label 09] = S.[CUST_SPECIFIC_FLD_LBL_09],
        T.[Customer Hierarchy1 Specific Field Label 10] = S.[CUST_SPECIFIC_FLD_LBL_10],
        T.[Customer Hierarchy1 Specific Field Label 11] = S.[CUST_SPECIFIC_FLD_LBL_11],
        T.[Customer Hierarchy1 Specific Field Label 12] = S.[CUST_SPECIFIC_FLD_LBL_12],
        T.[Customer Hierarchy1 Specific Field Label 13] = S.[CUST_SPECIFIC_FLD_LBL_13],
        T.[Customer Hierarchy1 Specific Field Label 14] = S.[CUST_SPECIFIC_FLD_LBL_14],
        T.[Customer Hierarchy1 Specific Field Label 15] = S.[CUST_SPECIFIC_FLD_LBL_15],
        T.[Customer Hierarchy1 Specific Field Label 16] = S.[CUST_SPECIFIC_FLD_LBL_16],
        T.[Customer Hierarchy1 Specific Field Label 17] = S.[CUST_SPECIFIC_FLD_LBL_17],
        T.[Customer Hierarchy1 Specific Field Label 18] = S.[CUST_SPECIFIC_FLD_LBL_18],
        T.[Customer Hierarchy1 Specific Field Label 19] = S.[CUST_SPECIFIC_FLD_LBL_19],
        T.[Customer Hierarchy1 Specific Field Label 20] = S.[CUST_SPECIFIC_FLD_LBL_20],
        T.[Customer Hierarchy1 Condition Group 1] = S.[CUST_COND_GROUP_1],
        T.[Customer Hierarchy1 Industry Code 1] = S.[INDUS_CD_1],
        T.[Customer Hierarchy1 Industry Code 2] = S.[INDUS_CD_2],
        T.[Customer Hierarchy1 Industry Description] = S.[INDUS_DESC],
        T.[Customer Hierarchy1 Industry Code 1 Description] = S.[INDUS_CD_1_DESC],
        T.[Customer Hierarchy1 Industry Code 2 Description] = S.[INDUS_CD_2_DESC],
        T.[Customer Hierarchy1 Assignment to Hierarchy] = S.[ASSIGN_TO_HIERCHY],
        T.[Customer Hierarchy1 Account Group Description] = S.[CUST_ACCT_GROUP_DESC],
        T.[Customer Hierarchy1 Region Description] = S.[REGN_DESC],
        T.[Customer Hierarchy1 Country Description] = S.[CNTRY_DESC],
        T.[Customer Hierarchy1 Transportation Zone Description] = S.[TRANSTN_ZONE_DESC],
        T.[Customer Hierarchy1 Plant Description] = S.[PLNT_DESC],
        T.[Customer Hierarchy1 Condition Group Description] = S.[CUST_COND_GROUP_DESC],
        T.[Customer Hierarchy1 Cental Billing Block] = S.[CENTRAL_BILLING_BLK],
        T.[Customer Hierarchy1 Cental Billing Block Description] = S.[CENTRAL_BILLING_BLK_DESC],
        T.[Customer Hierarchy1 Central Delivery Block] = S.[CENTRAL_DLVRY_BLK],
        T.[Customer Hierarchy1 Central Delivery Block Description] = S.[CENTRAL_DLVRY_BLK_DESC],
        T.[Customer Hierarchy1 Deletion Indicator] = S.[DELETION_IND],
        T.[Customer Hierarchy1 Central Posting Block] = S.[CENTRAL_PSTNG_BLK],
        T.[Customer Hierarchy1 Tax Jurisdiction] = S.[TAX_JRSDCTN],
        T.[Customer Hierarchy1 Central Sales Block] = S.[CENTRAL_SALES_BLK],
        T.[Customer Hierarchy1 Central Deletion Indicator] = S.[CENTRAL_DELETION_IND],
        T.[Customer Hierarchy1 Language Key] = S.[LANG_KEY],
        T.[Customer Hierarchy1 Trading Partner] = S.[TRADING_PRTNR],
        T.[Customer Hierarchy1 Trading Partner Description] = S.[TRADING_PRTNR_DESC],
        T.[Customer Hierarchy1 Annual Sales] = S.[ANNUAL_SALES],
        T.[Customer Hierarchy1 Annual Sales Year] = S.[ANNUAL_SALES_YR],
        T.[Customer Hierarchy1 Sales Currency] = S.[SALES_CRNCY],
        T.[Customer Hierarchy1 Sales Currency Description] = S.[SALES_CRNCY_DESC],
        T.[Customer Hierarchy1 One Time Account Group] = S.[ONE_TM_CUST_ACCT_GROUP],
        T.[Customer Hierarchy1 One Time Account Group Description] = S.[ONE_TM_CUST_ACCT_GROUP_DESC],
        T.[Customer Hierarchy1 One Time Indicator] = S.[ONE_TM_CUST_IND],
        T.[Customer Hierarchy1 Industry Type] = S.[INDUS_TYP],
        T.[Customer Hierarchy1 Business Type] = S.[BIZ_TYP],
        T.[Customer Hierarchy1 DUNS Number] = S.[DUNS_NUM],
        T.[Customer Hierarchy1 DUNS Plus 4] = S.[DUNS_PLUS_4],
        T.[CITY_COORDINATES] = S.[CITY_COORDINATES],
        T.[TAX_NUM_4_CD] = S.[TAX_NUM_4_CD],
        T.[ATTRIB_3] = S.[ATTRIB_3],
        T.[ATTRIB_3_DESC] = S.[ATTRIB_3_DESC],
        T.[E_MAIL_ADDR] = S.[E_MAIL_ADDR],
        T.[MOBILE_NUM] = S.[MOBILE_NUM],
        T.[SEARCH_TERM_2] = S.[SEARCH_TERM_2],
        T.[STR_2] = S.[STR_2],
        T.[STR_3] = S.[STR_3],
        T.[STR_4] = S.[STR_4],
        T.[STR_5] = S.[STR_5],
        T.[PO_BOX] = S.[PO_BOX],
        T.[PO_BOX_POSTAL_CD] = S.[PO_BOX_POSTAL_CD],
        T.[PO_BOX_CITY] = S.[PO_BOX_CITY],
        T.[REGN_FOR_PO_BOX] = S.[REGN_FOR_PO_BOX],
        T.[PO_BOX_CNTRY] = S.[PO_BOX_CNTRY],
        T.[TRNSPRT_ZONE] = S.[TRNSPRT_ZONE],
        T.[ADDR_NOTES] = S.[ADDR_NOTES],
        T.[TAX_NUM_3] = S.[TAX_NUM_3],
        T.[TAX_NUM_5] = S.[TAX_NUM_5],
        T.[INDUS_CD_3] = S.[INDUS_CD_3],
        T.[INDUS_CD_3_DESC] = S.[INDUS_CD_3_DESC],
        T.[INDUS_CD_4] = S.[INDUS_CD_4],
        T.[INDUS_CD_4_DESC] = S.[INDUS_CD_4_DESC],
        T.[INDUS_CD_5] = S.[INDUS_CD_5],
        T.[INDUS_CD_5_DESC] = S.[INDUS_CD_5_DESC],
        T.[CENTRAL_ORDER_BLK_FOR_CUST] = S.[CENTRAL_ORDER_BLK_FOR_CUST],
        T.[PYMT_BLK] = S.[PYMT_BLK]  
	
    FROM [GLOBAL_EDW].[Propelis].[CUST_HIERARCHY1] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CUSTOMR_CUR_D] S
        ON T.[CUST_KEY] = S.[CUST_KEY];
 
        -- Insert new records
    INSERT INTO [GLOBAL_EDW].[Propelis].[CUST_HIERARCHY1] (
        [CUST_KEY],
        [Customer Hierarchy1 ID],
        [Customer Hierarchy1 Legacy Customer ID],
        [Customer Hierarchy1 Name],
        [Customer Hierarchy1 Line 2 Description],
        [Customer Hierarchy1 Country Code],
        [Customer Hierarchy1 Plant ID],
        [Customer Hierarchy1 Segment ID],
        [Customer Hierarchy1 Industry],
        [Customer Hierarchy1 Vendor ID],
        [Customer Hierarchy1 Customer Group Code],
        [Customer Hierarchy1 Account Group Code],
        [Customer Hierarchy1 Title],
        [Customer Hierarchy1 Search Term],
        [Customer Hierarchy1 Street],
        [Customer Hierarchy1 City],
        [Customer Hierarchy1 Zip Code],
        [Customer Hierarchy1 State Code],
        [Customer Hierarchy1 Region Code],
        [Customer Hierarchy1 Telephone Number 1],
        [Customer Hierarchy1 Telephone Number 2],
        [Customer Hierarchy1 Fax Number Code],
        [Customer Hierarchy1 Tax Number 1 Code],
        [Customer Hierarchy1 Tax Number 2 Code],
        [Customer Hierarchy1 VAT Number Code],
        [Customer Hierarchy1 Credit Limit],
        [Customer Hierarchy1 Bonus Rate],
        [Customer Hierarchy1 Express Station],
        [Customer Hierarchy1 Transportation Zone],
        [Customer Hierarchy1 Printer Location Characteristics],
        [Customer Hierarchy1 Printer Region Characteristics],
        [Customer Hierarchy1 Printer Site Characteristics],
        [Customer Hierarchy1 Customer Created Date],
        [Customer Hierarchy1 Created User ID],
        [Customer Hierarchy1 Customer Updated Date],
        [Customer Hierarchy1 Updated User ID],
        [Customer Hierarchy1 Payment Terms Code],
        [Customer Hierarchy1 Sales Distribution],
        [Customer Hierarchy1 Order Block For Sales Area],
        [Customer Hierarchy1 Delivery Block For Sales Area],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Customer Hierarchy1 Corporate Group],
        [Customer Hierarchy1 Classification],
        [Customer Hierarchy1 Classification Description],
        [Customer Hierarchy1 Printer Location],
        [Customer Hierarchy1 Printer Site],
        [Customer Hierarchy1 Printer Region],
        [Customer Hierarchy1 Specific Field Label 01],
        [Customer Hierarchy1 Specific Field Label 02],
        [Customer Hierarchy1 Specific Field Label 03],
        [Customer Hierarchy1 Specific Field Label 04],
        [Customer Hierarchy1 Specific Field Label 05],
        [Customer Hierarchy1 Specific Field Label 06],
        [Customer Hierarchy1 Specific Field Label 07],
        [Customer Hierarchy1 Specific Field Label 08],
        [Customer Hierarchy1 Specific Field Label 09],
        [Customer Hierarchy1 Specific Field Label 10],
        [Customer Hierarchy1 Specific Field Label 11],
        [Customer Hierarchy1 Specific Field Label 12],
        [Customer Hierarchy1 Specific Field Label 13],
        [Customer Hierarchy1 Specific Field Label 14],
        [Customer Hierarchy1 Specific Field Label 15],
        [Customer Hierarchy1 Specific Field Label 16],
        [Customer Hierarchy1 Specific Field Label 17],
        [Customer Hierarchy1 Specific Field Label 18],
        [Customer Hierarchy1 Specific Field Label 19],
        [Customer Hierarchy1 Specific Field Label 20],
        [Customer Hierarchy1 Condition Group 1],
        [Customer Hierarchy1 Industry Code 1],
        [Customer Hierarchy1 Industry Code 2],
        [Customer Hierarchy1 Industry Description],
        [Customer Hierarchy1 Industry Code 1 Description],
        [Customer Hierarchy1 Industry Code 2 Description],
        [Customer Hierarchy1 Assignment to Hierarchy],
        [Customer Hierarchy1 Account Group Description],
        [Customer Hierarchy1 Region Description],
        [Customer Hierarchy1 Country Description],
        [Customer Hierarchy1 Transportation Zone Description],
        [Customer Hierarchy1 Plant Description],
        [Customer Hierarchy1 Condition Group Description],
        [Customer Hierarchy1 Cental Billing Block],
        [Customer Hierarchy1 Cental Billing Block Description],
        [Customer Hierarchy1 Central Delivery Block],
        [Customer Hierarchy1 Central Delivery Block Description],
        [Customer Hierarchy1 Deletion Indicator],
        [Customer Hierarchy1 Central Posting Block],
        [Customer Hierarchy1 Tax Jurisdiction],
        [Customer Hierarchy1 Central Sales Block],
        [Customer Hierarchy1 Central Deletion Indicator],
        [Customer Hierarchy1 Language Key],
        [Customer Hierarchy1 Trading Partner],
        [Customer Hierarchy1 Trading Partner Description],
        [Customer Hierarchy1 Annual Sales],
        [Customer Hierarchy1 Annual Sales Year],
        [Customer Hierarchy1 Sales Currency],
        [Customer Hierarchy1 Sales Currency Description],
        [Customer Hierarchy1 One Time Account Group],
        [Customer Hierarchy1 One Time Account Group Description],
        [Customer Hierarchy1 One Time Indicator],
        [Customer Hierarchy1 Industry Type],
        [Customer Hierarchy1 Business Type],
        [Customer Hierarchy1 DUNS Number],
        [Customer Hierarchy1 DUNS Plus 4],
        [CITY_COORDINATES],
        [TAX_NUM_4_CD],
        [ATTRIB_3],
        [ATTRIB_3_DESC],
        [E_MAIL_ADDR],
        [MOBILE_NUM],
        [SEARCH_TERM_2],
        [STR_2],
        [STR_3],
        [STR_4],
        [STR_5],
        [PO_BOX],
        [PO_BOX_POSTAL_CD],
        [PO_BOX_CITY],
        [REGN_FOR_PO_BOX],
        [PO_BOX_CNTRY],
        [TRNSPRT_ZONE],
        [ADDR_NOTES],
        [TAX_NUM_3],
        [TAX_NUM_5],
        [INDUS_CD_3],
        [INDUS_CD_3_DESC],
        [INDUS_CD_4],
        [INDUS_CD_4_DESC],
        [INDUS_CD_5],
        [INDUS_CD_5_DESC],
        [CENTRAL_ORDER_BLK_FOR_CUST],
        [PYMT_BLK]

    )
    SELECT
        S.[CUST_KEY],
        S.[CUST_ID],
        S.[LGCY_CUST_ID],
        S.[CUST_NAME],
        S.[CUST_LINE_2_DESC],
        S.[CNTRY_CD],
        S.[PLNT_ID],
        S.[SEG_ID],
        S.[INDUS],
        S.[VNDR_ID],
        S.[CUST_GROUP_CD],
        S.[CUST_ACCT_GROUP_CD],
        S.[TITLE],
        S.[SEARCH_TERM],
        S.[STR],
        S.[CITY_NAME],
        S.[ZIP_CD],
        S.[ST_CD],
        S.[REGN_CD],
        S.[TEL_NUM_1_CD],
        S.[TEL_NUM_2_CD],
        S.[FAX_NUM_CD],
        S.[TAX_NUM_1_CD],
        S.[TAX_NUM_2_CD],
        S.[VAT_NUM_CD],
        S.[CREDIT_LMT],
        S.[BONUS_RT],
        S.[EXPRESS_STATION],
        S.[TRANSTN_ZONE],
        S.[PRINTER_LOC_CHARS],
        S.[PRINTER_REGN_CHARS],
        S.[PRINTER_SITE_CHARS],
        S.[CREATED_DATE],
        S.[CREATED_USR_ID],
        S.[UPDTD_DATE],
        S.[UPDTD_USR_ID],
        S.[PYMT_TRMS_CD],
        S.[SALES_DISTR],
        S.[ORDER_BLK_FOR_SALES_AREA],
        S.[DLVRY_BLK_FOR_SALES_AREA],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CORPORATE_GROUP],
        S.[CUST_CLSFTN],
        S.[CUST_CLSFTN_DESC],
        S.[PRINTER_LOC],
        S.[PRINTER_SITE],
        S.[PRINTER_REGN],
        S.[CUST_SPECIFIC_FLD_LBL_01],
        S.[CUST_SPECIFIC_FLD_LBL_02],
        S.[CUST_SPECIFIC_FLD_LBL_03],
        S.[CUST_SPECIFIC_FLD_LBL_04],
        S.[CUST_SPECIFIC_FLD_LBL_05],
        S.[CUST_SPECIFIC_FLD_LBL_06],
        S.[CUST_SPECIFIC_FLD_LBL_07],
        S.[CUST_SPECIFIC_FLD_LBL_08],
        S.[CUST_SPECIFIC_FLD_LBL_09],
        S.[CUST_SPECIFIC_FLD_LBL_10],
        S.[CUST_SPECIFIC_FLD_LBL_11],
        S.[CUST_SPECIFIC_FLD_LBL_12],
        S.[CUST_SPECIFIC_FLD_LBL_13],
        S.[CUST_SPECIFIC_FLD_LBL_14],
        S.[CUST_SPECIFIC_FLD_LBL_15],
        S.[CUST_SPECIFIC_FLD_LBL_16],
        S.[CUST_SPECIFIC_FLD_LBL_17],
        S.[CUST_SPECIFIC_FLD_LBL_18],
        S.[CUST_SPECIFIC_FLD_LBL_19],
        S.[CUST_SPECIFIC_FLD_LBL_20],
        S.[CUST_COND_GROUP_1],
        S.[INDUS_CD_1],
        S.[INDUS_CD_2],
        S.[INDUS_DESC],
        S.[INDUS_CD_1_DESC],
        S.[INDUS_CD_2_DESC],
        S.[ASSIGN_TO_HIERCHY],
        S.[CUST_ACCT_GROUP_DESC],
        S.[REGN_DESC],
        S.[CNTRY_DESC],
        S.[TRANSTN_ZONE_DESC],
        S.[PLNT_DESC],
        S.[CUST_COND_GROUP_DESC],
        S.[CENTRAL_BILLING_BLK],
        S.[CENTRAL_BILLING_BLK_DESC],
        S.[CENTRAL_DLVRY_BLK],
        S.[CENTRAL_DLVRY_BLK_DESC],
        S.[DELETION_IND],
        S.[CENTRAL_PSTNG_BLK],
        S.[TAX_JRSDCTN],
        S.[CENTRAL_SALES_BLK],
        S.[CENTRAL_DELETION_IND],
        S.[LANG_KEY],
        S.[TRADING_PRTNR],
        S.[TRADING_PRTNR_DESC],
        S.[ANNUAL_SALES],
        S.[ANNUAL_SALES_YR],
        S.[SALES_CRNCY],
        S.[SALES_CRNCY_DESC],
        S.[ONE_TM_CUST_ACCT_GROUP],
        S.[ONE_TM_CUST_ACCT_GROUP_DESC],
        S.[ONE_TM_CUST_IND],
        S.[INDUS_TYP],
        S.[BIZ_TYP],
        S.[DUNS_NUM],
        S.[DUNS_PLUS_4],
        S.[CITY_COORDINATES],
        S.[TAX_NUM_4_CD],
        S.[ATTRIB_3],
        S.[ATTRIB_3_DESC],
        S.[E_MAIL_ADDR],
        S.[MOBILE_NUM],
        S.[SEARCH_TERM_2],
        S.[STR_2],
        S.[STR_3],
        S.[STR_4],
        S.[STR_5],
        S.[PO_BOX],
        S.[PO_BOX_POSTAL_CD],
        S.[PO_BOX_CITY],
        S.[REGN_FOR_PO_BOX],
        S.[PO_BOX_CNTRY],
        S.[TRNSPRT_ZONE],
        S.[ADDR_NOTES],
        S.[TAX_NUM_3],
        S.[TAX_NUM_5],
        S.[INDUS_CD_3],
        S.[INDUS_CD_3_DESC],
        S.[INDUS_CD_4],
        S.[INDUS_CD_4_DESC],
        S.[INDUS_CD_5],
        S.[INDUS_CD_5_DESC],
        S.[CENTRAL_ORDER_BLK_FOR_CUST],
        S.[PYMT_BLK]
    
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CUSTOMR_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[CUST_HIERARCHY1] T
        ON T.[CUST_KEY] = S.[CUST_KEY]
    WHERE T.[CUST_KEY] IS NULL;
END