CREATE  PROCEDURE [Propelis].[Proc_EDW_T_FACT_FI_BPCDTAU_CUR_D]
AS
BEGIN
    -- Step 1: Clear existing data from the target table
	
    TRUNCATE TABLE [GLOBAL_EDW].[Propelis].[EDW_T_FACT_FI_BPCDTAU_CUR_D];
	
	-- Step 2: Insert refreshed data from mirror table with joins
 
    INSERT INTO [GLOBAL_EDW].[Propelis].[EDW_T_FACT_FI_BPCDTAU_CUR_D]
    (
	    [ACCT_KEY],
	    [Audit Trail],
	    [Currency],
	    [Custom1],
	    [ENTITY_KEY],
	    [Flow],
	    [FUNCTNL_AREA_KEY],
	    [INTER_CMPNY_PROFT_CNTR_KEY],
	    [INTER_CMPNY_KEY],
	    [PROFT_CNTR_KEY],
	    [Project],
	    [Scope],
	    [Version],
	    [Fiscal Year],
	    [Period],
	    [Signdata Amount],
	    [ETL_SRC_SYS_CD],
	    [ETL_CREATED_TS],
	    [ETL_UPDTD_TS],
	    [ACCT ID],
	    [ENTITY ID],
	    [Functional Area ID],
	    [Inter Company Profit Center ID],
	    [Profit Center ID],
	    [Inter Company ID],
	    [Signdata Amt - Current],
	    
	--Below columns are added for the Alias tables	
		
	    [PROFCHZ_PROFT_CNTR_KEY],
	    [PROFCVZ_PROFT_CNTR_KEY],
	    [INTER_COMPANY_PC_HH_PROFT_CNTR_KEY],
	    [INTER_COMP_PC_VH_PROFT_CNTR_KEY],
	    [MST_DATE_KEY],
	    [Functional_GL_Key]
)	
SELECT
        FACT.[ACCT_KEY],
        FACT.[AUDIT_TRAIL],
        FACT.[CRNCY],
        FACT.[CUSTOM1],
        FACT.[ENTTY_KEY],
        FACT.[FLOW],
        FACT.[FUNCTNL_AREA_KEY],
        FACT.[INTER_CMPNY_PROFT_CNTR_KEY],
        FACT.[INTER_CMPNY_KEY],
        FACT.[PROFT_CNTR_KEY],
        FACT.[PROJ],
        FACT.[SCOPE],
        FACT.[VRSN],
        FACT.[FISCAL_YR],
        FACT.[PER],
        FACT.[SIGNDATA_AMT],
        FACT.[ETL_SRC_SYS_CD],
        FACT.[ETL_CREATED_TS],
        FACT.[ETL_UPDTD_TS],
        FACT.[ACCT_ID],
        FACT.[ENTTY_ID],
        FACT.[FUNCTNL_AREA_ID],
        FACT.[INTER_CMPNY_PROFT_CNTR_ID],
        FACT.[PROFT_CNTR_ID],
        FACT.[INTER_CMPNY_ID],
        FACT.[SIGNDATA_AMT_CURR],

        MST_PROFCTR.PROFT_CNTR_KEY AS PROFCHZ_PROFT_CNTR_KEY,
        MST_PROFCTR.PROFT_CNTR_KEY AS PROFCVZ_PROFT_CNTR_KEY,
        COM_PRO_CNT.PROFT_CNTR_KEY AS INTER_COMPANY_PC_HH_PROFT_CNTR_KEY,
        COM_PRO_CNT.PROFT_CNTR_KEY AS INTER_COMP_PC_VH_PROFT_CNTR_KEY,

        CONCAT(FACT.[FISCAL_YR], '-', FACT.[PER]) AS MST_DATE_KEY,
        CONCAT(FACT.ACCT_ID, '-', FACT.FUNCTNL_AREA_ID) AS Functional_GL_Key

FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_F_FI_BPCDTAU_CUR_D] AS FACT

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_GENLDGR_CUR_D] AS MST_GENLDGR
    ON FACT.ACCT_KEY = MST_GENLDGR.GL_KEY

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_FUNCTAR_CUR_D] AS MST_FUNCTAR
    ON FACT.FUNCTNL_AREA_KEY = MST_FUNCTAR.FUNCTNL_AREA_KEY

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_HY_ENTYHZ_CUR_D] AS HY_ENTYHZ
    ON FACT.ENTTY_ID = HY_ENTYHZ.[Entity ID]

LEFT JOIN [GLOBAL_EDW].[Propelis].[Entity_Company] AS ENT_COM
    ON FACT.ENTTY_KEY = ENT_COM.CMPNY_KEY

LEFT JOIN [GLOBAL_EDW].[Propelis].[INTER_COMPANY] AS ENTR_COM
    ON FACT.INTER_CMPNY_KEY = ENTR_COM.CMPNY_KEY

LEFT JOIN [GLOBAL_EDW].[Propelis].[INTER_COMP_PROFIT_CNTR] AS COM_PRO_CNT
    ON FACT.INTER_CMPNY_PROFT_CNTR_KEY = COM_PRO_CNT.PROFT_CNTR_KEY

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PROFCTR_CUR_D] AS MST_PROFCTR
    ON FACT.PROFT_CNTR_KEY = MST_PROFCTR.PROFT_CNTR_KEY

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_FI_MELTGRP_CUR_D] AS MELTGRP_CUR
    ON FACT.ACCT_ID = MELTGRP_CUR.ACCT_ID

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_FI_MELTGRP_CUR_D] AS MELTGRP
    ON FACT.ACCT_ID = MELTGRP.ACCT_ID

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D] AS MST_DATE
    ON CONCAT(FACT.[FISCAL_YR], '-', FACT.[PER]) = MST_DATE.[MST_DATE_KEY]

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_HY_GLACTHZ_CUR_D] AS GLACTHZ
    ON CONCAT(FACT.ACCT_ID, '-', FACT.FUNCTNL_AREA_ID) = GLACTHZ.[Functional_GL_Key];
END