CREATE   PROCEDURE [Propelis].[Proc_INVOICE_CREATION_DATE]
AS
BEGIN

    ----------------------------------------------------------
    -- UPDATE EXISTING RECORDS
    ----------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY]                                       =S.[DATE_KEY],
        T.[Invoice Creation Date]                          = S.[THE_DATE],
        T.[Invoice Creation Fiscal Year]                   = S.[FISCAL_YR],
        T.[Invoice Creation Fiscal Period]                 = S.[FISCAL_PER_NUM],
        T.[Invoice Creation Fiscal Period Code]            = S.[FISCAL_PER_CD],
        T.[Invoice Creation Fiscal Quarter]                = S.[FISCAL_QTR_NUM],
        T.[Invoice Creation Fiscal Quarter Code]           = S.[FISCAL_QTR_CD],
        T.[Invoice Creation Calendar Year]                 = S.[CLNDR_YR],
        T.[Invoice Creation Calendar Month Number]         = S.[CLNDR_MNTH_NUM],
        T.[Invoice Creation Calendar Month Code]           = S.[CLNDR_MNTH_CD],
        T.[Invoice Creation Calendar Month Desc]           = S.[CLNDR_MNTH_DESC],
        T.[Invoice Creation Calendar Quarter]              = S.[CLNDR_QTR_NUM],
        T.[Invoice Creation Calendar Quarter Code]         = S.[CLNDR_QTR_CD],
        T.[Invoice Creation Calendar Weekday Number]       = S.[CLNDR_WEEKDAY_NUM],
        T.[Invoice Creation Calendar Weekday Name]         = S.[CLNDR_WEEKDAY_NAME],
        T.[Invoice Creation Calendar Day in Month]         = S.[CLNDR_DAY_IN_MNTH],
        T.[Invoice Creation Calendar Day in Year]          = S.[CLNDR_DAY_IN_YR],
        T.[Invoice Creation Calendar Week]                 = S.[CLNDR_WK],
        T.[Invoice Creation Calendar Month in Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Invoice Creation Calendar Days in Month]        = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD]                                 = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS]                                 = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS]                                   = S.[ETL_UPDTD_TS],
        T.[Invoice Creation Current Day Flag]              = S.[CURR_DAY_FLG],
        T.[Invoice Creation Current Day Minus 1 Flag]      = S.[CURR_DAY_MINUS_1_FLG],
        T.[Invoice Creation Current Calendar Week Flag]    = S.[CURR_CLNDR_WK_FLG],
        T.[Invoice Creation Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Invoice Creation Current Month Flag]            = S.[CURR_MNTH_FLG],
        T.[Invoice Creation Current Month Minus 1 Flag]    = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Invoice Creation Current Month Minus 12 Flag]   = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Invoice Creation Current Quarter Flag]          = S.[CURR_QTR_FLG],
        T.[Invoice Creation Current Quarter Minus 1 Flag]  = S.[CURR_QTR_MINUS_1_FLG],
        T.[Invoice Creation Current Quarter Minus 4 Flag]  = S.[CURR_QTR_MINUS_4_FLG],
        T.[Invoice Creation Current Calendar Year Flag]    = S.[CURR_CLNDR_YR_FLG],
        T.[Invoice Creation Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Invoice Creation Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Invoice Creation Current Fiscal Year Flag]      = S.[CURR_FISCAL_YR_FLG],
        T.[Invoice Creation Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Invoice Creation Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Invoice Creation Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Invoice Creation Current Fiscal Year Plus 1 Flag]  = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Invoice Creation Day In Fiscal Year]            = S.[DAY_IN_FISCAL_YR],
        T.[IS_WEEKDAY]                                     = S.[IS_WEEKDAY],
        T.[Invoice Creation Fiscal Week]                   = S.[FISCAL_WK],
        T.[Invoice Creation Current Fiscal Week Flag]      = S.[CURR_FISCAL_WK_FLG],
        T.[Invoice Creation Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Invoice Creation Fiscal Weekday Number]         = S.[FISCAL_WEEKDAY_NUM],
        T.[Invoice Creation Fiscal Weekday Name]           = S.[FISCAL_WEEKDAY_NAME],
        T.[CURR_MNTH_MINUS_2_FLG]                          = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Invoice Creation Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Invoice Creation Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Invoice Creation Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Invoice Creation Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Invoice Creation Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Invoice Creation Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[INVOICE_CREATION_DATE] AS T
    INNER JOIN  [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] AS S
        ON T.[DATE_KEY] = S.[DATE_KEY];


    ----------------------------------------------------------
    -- INSERT NEW RECORDS
    ----------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[INVOICE_CREATION_DATE]
    (
        [DATE_KEY],
        [Invoice Creation Date],
        [Invoice Creation Fiscal Year],
        [Invoice Creation Fiscal Period],
        [Invoice Creation Fiscal Period Code],
        [Invoice Creation Fiscal Quarter],
        [Invoice Creation Fiscal Quarter Code],
        [Invoice Creation Calendar Year],
        [Invoice Creation Calendar Month Number],
        [Invoice Creation Calendar Month Code],
        [Invoice Creation Calendar Month Desc],
        [Invoice Creation Calendar Quarter],
        [Invoice Creation Calendar Quarter Code],
        [Invoice Creation Calendar Weekday Number],
        [Invoice Creation Calendar Weekday Name],
        [Invoice Creation Calendar Day in Month],
        [Invoice Creation Calendar Day in Year],
        [Invoice Creation Calendar Week],
        [Invoice Creation Calendar Month in Quarter Number],
        [Invoice Creation Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Invoice Creation Current Day Flag],
        [Invoice Creation Current Day Minus 1 Flag],
        [Invoice Creation Current Calendar Week Flag],
        [Invoice Creation Current Calendar Week Minus 1 Flag],
        [Invoice Creation Current Month Flag],
        [Invoice Creation Current Month Minus 1 Flag],
        [Invoice Creation Current Month Minus 12 Flag],
        [Invoice Creation Current Quarter Flag],
        [Invoice Creation Current Quarter Minus 1 Flag],
        [Invoice Creation Current Quarter Minus 4 Flag],
        [Invoice Creation Current Calendar Year Flag],
        [Invoice Creation Current Calendar Year Minus 1 Flag],
        [Invoice Creation Current Calendar Year Minus 2 Flag],
        [Invoice Creation Current Fiscal Year Flag],
        [Invoice Creation Current Fiscal Year Minus 1 Flag],
        [Invoice Creation Current Fiscal Year Minus 2 Flag],
        [Invoice Creation Current Calendar Year Plus 1 Flag],
        [Invoice Creation Current Fiscal Year Plus 1 Flag],
        [Invoice Creation Day In Fiscal Year],
        [IS_WEEKDAY],
        [Invoice Creation Fiscal Week],
        [Invoice Creation Current Fiscal Week Flag],
        [Invoice Creation Current Fiscal Week Minus 1 Flag],
        [Invoice Creation Fiscal Weekday Number],
        [Invoice Creation Fiscal Weekday Name],
        [CURR_MNTH_MINUS_2_FLG],
        [Invoice Creation Current Fiscal Week Minus 2 Flag],
        [Invoice Creation Current Fiscal Week Minus 6 Flag],
        [Invoice Creation Current Fiscal Week Minus 3 Flag],
        [Invoice Creation Current Fiscal Week Minus 4 Flag],
        [Invoice Creation Current Fiscal Week Minus 5 Flag],
        [Invoice Creation Current Fiscal Week Minus 7 Flag]
    )
    SELECT 
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM  [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[INVOICE_CREATION_DATE] AS T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;

END;