CREATE   PROCEDURE [Propelis].[Proc_OCCURRENCE_DATE]
AS
BEGIN

    ----------------------------------------------------------------------
    -- Step 1: Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[Occurrence Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Occurrence Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Occurrence Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Occurrence Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG],
        T.[Occurrence Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Occurrence Fiscal Weekday Number]            = S.[FISCAL_WEEKDAY_NUM],
        T.[Occurrence Fiscal Weekday Name]              = S.[FISCAL_WEEKDAY_NAME],
        T.[Occurrence Current Month Minus 2 Flag]       = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Occurrence Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Occurrence Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Occurrence Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Occurrence Current Fiscal Year Plus 1 Flag]  = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Occurrence Day In Fiscal Year]               = S.[DAY_IN_FISCAL_YR],
        T.[Occurrence Is Weekday]                       = S.[IS_WEEKDAY],
        T.[Occurrence Fiscal Week]                      = S.[FISCAL_WK],
        T.[Occurrence Current Fiscal Week Flag]         = S.[CURR_FISCAL_WK_FLG],
        T.[Occurrence Current Calendar Year Flag]       = S.[CURR_CLNDR_YR_FLG],
        T.[Occurrence Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Occurrence Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Occurrence Current Fiscal Year Flag]         = S.[CURR_FISCAL_YR_FLG],
        T.[Occurrence Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Occurrence Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Occurrence Current Month Flag]               = S.[CURR_MNTH_FLG],
        T.[Occurrence Current Month Minus 1 Flag]       = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Occurrence Current Month Minus 12 Flag]      = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Occurrence Current Quarter Flag]             = S.[CURR_QTR_FLG],
        T.[Occurrence Current Quarter Minus 1 Flag]     = S.[CURR_QTR_MINUS_1_FLG],
        T.[Occurrence Current Quarter Minus 4 Flag]     = S.[CURR_QTR_MINUS_4_FLG],
        T.[ETL_CREATED_TS]                              = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS]                                = S.[ETL_UPDTD_TS],
        T.[Occurrence Current Day Flag]                 = S.[CURR_DAY_FLG],
        T.[Occurrence Current Day Minus 1 Flag]         = S.[CURR_DAY_MINUS_1_FLG],
        T.[Occurrence Current Calendar Week Flag]       = S.[CURR_CLNDR_WK_FLG],
        T.[Occurrence Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Occurrence Calendar Day In Month]            = S.[CLNDR_DAY_IN_MNTH],
        T.[Occurrence Calendar Day In Year]             = S.[CLNDR_DAY_IN_YR],
        T.[Occurrence Calendar Week]                    = S.[CLNDR_WK],
        T.[Occurrence Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Occurrence Calendar Days In Month]           = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD]                              = S.[ETL_SRC_SYS_CD],
        T.[Occurrence Calendar Month Code]              = S.[CLNDR_MNTH_CD],
        T.[Occurrence Calendar Month Description]       = S.[CLNDR_MNTH_DESC],
        T.[Occurrence Calendar Quarter Number]          = S.[CLNDR_QTR_NUM],
        T.[Occurrence Calendar Quarter Code]            = S.[CLNDR_QTR_CD],
        T.[Occurrence Calendar Weekday Number]          = S.[CLNDR_WEEKDAY_NUM],
        T.[Occurrence Calendar Weekday Name]            = S.[CLNDR_WEEKDAY_NAME],
        T.[Occurrence Fiscal Period Number]             = S.[FISCAL_PER_NUM],
        T.[Occurrence Fiscal Period Code]               = S.[FISCAL_PER_CD],
        T.[Occurrence Fiscal Quarter Number]            = S.[FISCAL_QTR_NUM],
        T.[Occurrence Fiscal Quarter Code]              = S.[FISCAL_QTR_CD],
        T.[Occurrence Calendar Year]                    = S.[CLNDR_YR],
        T.[Occurrence Calendar Month Number]            = S.[CLNDR_MNTH_NUM],
        T.[Occurrence Date]                             = S.[THE_DATE],
        T.[Occurrence Fiscal Year]                      = S.[FISCAL_YR]
    FROM [GLOBAL_EDW].[Propelis].[OCCURRENCE_DATE] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];

    ----------------------------------------------------------------------
    -- Step 2: Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[OCCURRENCE_DATE]
    (
        [Occurrence Current Fiscal Week Minus 3 Flag],
        [Occurrence Current Fiscal Week Minus 4 Flag],
        [Occurrence Current Fiscal Week Minus 5 Flag],
        [Occurrence Current Fiscal Week Minus 7 Flag],
        [Occurrence Current Fiscal Week Minus 1 Flag],
        [Occurrence Fiscal Weekday Number],
        [Occurrence Fiscal Weekday Name],
        [Occurrence Current Month Minus 2 Flag],
        [Occurrence Current Fiscal Week Minus 2 Flag],
        [Occurrence Current Fiscal Week Minus 6 Flag],
        [Occurrence Current Calendar Year Plus 1 Flag],
        [Occurrence Current Fiscal Year Plus 1 Flag],
        [Occurrence Day In Fiscal Year],
        [Occurrence Is Weekday],
        [Occurrence Fiscal Week],
        [Occurrence Current Fiscal Week Flag],
        [Occurrence Current Calendar Year Flag],
        [Occurrence Current Calendar Year Minus 1 Flag],
        [Occurrence Current Calendar Year Minus 2 Flag],
        [Occurrence Current Fiscal Year Flag],
        [Occurrence Current Fiscal Year Minus 1 Flag],
        [Occurrence Current Fiscal Year Minus 2 Flag],
        [Occurrence Current Month Flag],
        [Occurrence Current Month Minus 1 Flag],
        [Occurrence Current Month Minus 12 Flag],
        [Occurrence Current Quarter Flag],
        [Occurrence Current Quarter Minus 1 Flag],
        [Occurrence Current Quarter Minus 4 Flag],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Occurrence Current Day Flag],
        [Occurrence Current Day Minus 1 Flag],
        [Occurrence Current Calendar Week Flag],
        [Occurrence Current Calendar Week Minus 1 Flag],
        [Occurrence Calendar Day In Month],
        [Occurrence Calendar Day In Year],
        [Occurrence Calendar Week],
        [Occurrence Calendar Month In Quarter Number],
        [Occurrence Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [Occurrence Calendar Month Code],
        [Occurrence Calendar Month Description],
        [Occurrence Calendar Quarter Number],
        [Occurrence Calendar Quarter Code],
        [Occurrence Calendar Weekday Number],
        [Occurrence Calendar Weekday Name],
        [Occurrence Fiscal Period Number],
        [Occurrence Fiscal Period Code],
        [Occurrence Fiscal Quarter Number],
        [Occurrence Fiscal Quarter Code],
        [Occurrence Calendar Year],
        [Occurrence Calendar Month Number],
        [DATE_KEY],
        [Occurrence Date],
        [Occurrence Fiscal Year]
    )
    SELECT
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[OCCURRENCE_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;

END