CREATE     PROCEDURE [Propelis].[Proc_TEMP_EDW_T_FACT_PRD_TMCONFS_CUR_D]
AS
BEGIN
        -- Step 1: Truncate the temp table (truncate is faster than delete)
        TRUNCATE TABLE [GLOBAL_EDW].[Propelis].[TEMP_EDW_T_FACT_PRD_TMCONFS_CUR_D];

        -- Step 2: Insert data
        INSERT INTO [GLOBAL_EDW].[Propelis].[TEMP_EDW_T_FACT_PRD_TMCONFS_CUR_D]
		        ([SEG_CD_KEY]  ,
		        [Operation Task List ID] ,
		        [Operation Counter ID] ,
		        [Operation Activity ID] ,
		        [Operation Confirmation ID] ,
		        [Operation Sequence ID] ,
		        [PROFT_CNTR_KEY]  ,
		        [SALES_ORDER_KEY]  ,
		        [Sales Order Item Number]  ,
		        [CMPNY_KEY] ,
		        [WRK_CNTR_KEY]  ,
		        [COST_CNTR_KEY]  ,
		        [OPERATION_STD_TEXT] ,
		        [Operation Short Text] ,
		        [PSTNG_DATE_KEY]  ,
		        [PLNG_PLNT_KEY]  ,
		        [Entry Create Date] ,
		        [Person Who Entererd] ,
		        [Operation Confirm Counter] ,
		        [Actual Work] ,
		        [Actual Work UOM] ,
		        [Accounting Indicator] ,
		        [Remaining Work] ,
		        [Remaining Work UOM] ,
		        [Actual Work in Hours] ,
		        [Remaining Work in Hours] ,
		        [Work In Hours UOM] ,
		        [ACTIVITY_TYP_KEY]  ,
		        [Operation Confirm Text] ,
		        [Reason for Variance] ,
		        [Confirm  Counter  Of  Cancelled  Confirmation]  ,
		        [SOLD_TO_CUST_KEY]  ,
		        [PERSONEL_NUM_KEY]  ,
		        [ETL_SRC_SYS_CD] ,
		        [ETL_CREATED_TS] ,
		        [ETL_UPDTD_TS] ,
		        [SERVC_ORDER_KEY] ,
		        [SALES_AREA_KEY] ,
		        [OPERATING_PLNT_KEY]  ,
		        [SERVC_ORDER_CREATE_DATE_KEY]  ,
		        [Account Indicator] ,
		        [PARNT_CUST_KEY]  ,
		        [Reason for Variance Description] ,
		        [Partial Final Confirm] ,
		        [TCHNCL_COMPLETION_DATE_KEY]  ,
		        [SALES_ORDER_ID] ,
		        [Accounting Indicator Description]
				
				--Below columns are added for the Alias tables
				,SERV_ORDER_INVOICE_CREATED_DATE_KEY
				,OPERATING_PLANT_REGION_PLANT
				,PLANNING_PLANT_REGION_PLANT
				,PERSONNEL_PLANT_REGION_PLANT
				,PARENT_CUST_KEY
				,PAYER_CUST_KEY 
				,SHIP_TO_CUST_KEY
				,BRAND_OWNER_CUST_KEY
				,CUST_CONTACT_KEY
				,PERSON_RESP_PERSONNEL_KEY
				,CYLINDER_OWNER_CUST_KEY
				,AGENCY_CUST_KEY
				,PRINTER_CUST_KEY
				,SUPPLIER_CUST_KEY
				,EMPLOYEE_RESP_PERSONEL_KEY
				,EMPLOYEE_RESP_2_PERSONEL_KEY
				,FORWARDING_AGENT_VENDOR_KEY
				,UNITIZATION_AGENT_VENDOR_KEY
				,ORDER_FOR_CUSTOMER_ADDR_KEY
				,SO_PARENT_CUST_KEY
				,BILL_TO_CUST_KEY 
				,CUSTOMER_PROJECT_MANAGER_CUST_CONTACT_KEY
				,SALES_PERSON_PERSONEL_KEY
				,SOIPTNR_KEY
				,PRDT_VARIANT_CONFIG_KEY)
	
    -- Your entire SELECT query goes here:
    SELECT
    Fact.[SEG_CD_KEY]  ,
	Fact.[OPERATION_TASK_LIST_ID] ,
	Fact.[OPERATION_COUNTER_ID] ,
	Fact.[OPERATION_ACTIVITY_ID] ,
	Fact.[OPERATION_CONFIRM_ID] ,
	Fact.[OPERATION_SEQ_ID] ,
	Fact.[PROFT_CNTR_KEY]  ,
	Fact.[SALES_ORDER_KEY]  ,
	Fact.[SALES_ORDER_ITM_NBR]  ,
	Fact.[CMPNY_KEY] ,
	Fact.[WRK_CNTR_KEY]  ,
	Fact.[COST_CNTR_KEY]  ,
	Fact.[OPERATION_STD_TEXT] ,
	Fact.[OPERATION_SHORT_TEXT] ,
	Fact.[PSTNG_DATE_KEY]  ,
	Fact.[PLNG_PLNT_KEY]  ,
	Fact.[ENTRY_CREATE_DATE] ,
	Fact.[PERSON_WHO_ENTERERD] ,
	Fact.[OPERATION_CONFIRM_COUNTER] ,
	Fact.[ACTUAL_WRK] ,
	Fact.[ACTUAL_WRK_UOM] ,
	Fact.[ACCTNG_IND] ,
	Fact.[REMG_WRK] ,
	Fact.[REMG_WRK_UOM] ,
	Fact.[ACTUAL_WRK_IN_HRS] ,
	Fact.[REMG_WRK_IN_HRS] ,
	Fact.[WRK_IN_HRS_UOM] ,
	Fact.[ACTIVITY_TYP_KEY]  ,
	Fact.[OPERATION_CONFIRM_TEXT] ,
	Fact.[RSN_FOR_VRNC] ,
	Fact.[CONFIRM_COUNTER_OF_CANCELLED_CO]  ,
	Fact.[SOLD_TO_CUST_KEY]  ,
	Fact.[PERSONEL_NUM_KEY]  ,
	Fact.[ETL_SRC_SYS_CD] ,
	Fact.[ETL_CREATED_TS] ,
	Fact.[ETL_UPDTD_TS] ,
	Fact.[SERVC_ORDER_KEY] ,
	Fact.[SALES_AREA_KEY] ,
	Fact.[OPERATING_PLNT_KEY]  ,
	Fact.[SERVC_ORDER_CREATE_DATE_KEY]  ,
	Fact.[ACCT_IND] ,
	Fact.[PARNT_CUST_KEY]  ,
	Fact.[RSN_FOR_VRNC_DESC] ,
	Fact.[PARTIAL_FINAL_CONFIRM] ,
	Fact.[TCHNCL_COMPLETION_DATE_KEY]  ,
	Fact.[SALES_ORDER_ID] ,
	Fact.[ACCTNG_IND_DESC]

	--Below columns are added for the Alias tables
	,CASE WHEN CONVERT(VARCHAR, GLOBAL_EDW.dbo.EDW_T_D_PRD_SERVORD_CUR_D.[Service Order Invoice Create Date], 112) = '19000101' 
												OR GLOBAL_EDW.dbo.EDW_T_D_PRD_SERVORD_CUR_D.[Service Order Invoice Create Date] IS NULL 
												THEN '-1'
										ELSE CONVERT(VARCHAR, GLOBAL_EDW.dbo.EDW_T_D_PRD_SERVORD_CUR_D.[Service Order Invoice Create Date], 112)
									END AS SERV_ORDER_INVOICE_CREATED_DATE_KEY
	,OPERATING_PLANT.[Plant ID] AS OPERATING_PLANT_REGION_PLANT
	,PLANNING_PLANT.[Plant ID] AS PLANNING_PLANT_REGION_PLANT
	,substring(GLOBAL_EDW.dbo.EDW_T_D_MST_PERSONL_CUR_D.[Personnel Cost Center ID],4,4) AS PERSONNEL_PLANT_REGION_PLANT
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.PARENT_CUST_KEY AS PARENT_CUST_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.PAYER_CUST_KEY AS PAYER_CUST_KEY 
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.SHIP_TO_CUST_KEY AS SHIP_TO_CUST_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.BRAND_OWNER_CUST_KEY AS BRAND_OWNER_CUST_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.CUST_CONTACT_KEY AS CUST_CONTACT_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.PERSON_RESPNSBLE_KEY AS PERSON_RESP_PERSONNEL_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.CYLINDER_OWNER_CUST_KEY AS CYLINDER_OWNER_CUST_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.AGENCY_CUST_KEY AS AGENCY_CUST_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.PRINTER_CUST_KEY AS PRINTER_CUST_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.SUPPLIER_CUST_KEY AS SUPPLIER_CUST_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.EMPL_RESPNSBLE_KEY AS EMPLOYEE_RESP_PERSONEL_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.EMPL_RESPNSBLE_2_KEY AS EMPLOYEE_RESP_2_PERSONEL_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.FORWARDING_AGENT_VNDR_KEY AS FORWARDING_AGENT_VENDOR_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.UNITIZATION_AGENT_VNDR_KEY AS UNITIZATION_AGENT_VENDOR_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.ORDER_FOR_CUST_KEY AS ORDER_FOR_CUSTOMER_ADDR_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.SO_PARENT_CUST_KEY AS SO_PARENT_CUST_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.BILL_TO_CUST_KEY  AS BILL_TO_CUST_KEY 
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.CUST_PROJ_MGR_KEY AS CUSTOMER_PROJECT_MANAGER_CUST_CONTACT_KEY
	,GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.SALES_PERSON_PERSONNEL_KEY AS SALES_PERSON_PERSONEL_KEY
	,CONCAT(Fact.SALES_ORDER_ID, '-', Fact.SALES_ORDER_ITM_NBR) AS SOIPTNR_KEY
	,EDW_T_D_SAL_PRDVCON_CUR_D.PRDT_VARIANT_CONFIG_KEY AS PRDT_VARIANT_CONFIG_KEY
        FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_F_PRD_TMCONFS_CUR_D] AS Fact
		
        left join GLOBAL_EDW.dbo.EDW_T_D_PRD_SERVORD_CUR_D
    
		ON Fact.SERVC_ORDER_KEY=GLOBAL_EDW.dbo.EDW_T_D_PRD_SERVORD_CUR_D.SERVC_ORDER_KEY
            
    left join GLOBAL_EDW.dbo.EDW_T_D_SAL_SALAREA_CUR_D
    
		ON Fact.SALES_AREA_KEY=GLOBAL_EDW.dbo.EDW_T_D_SAL_SALAREA_CUR_D.SALES_AREA_KEY
            
    left join GLOBAL_EDW.dbo.EDW_T_D_MST_SEGMENT_CUR_D
    
		ON Fact.SEG_CD_KEY=GLOBAL_EDW.dbo.EDW_T_D_MST_SEGMENT_CUR_D.SEG_KEY
            
    left join GLOBAL_EDW.dbo.EDW_T_D_MST_PROFCTR_CUR_D
    
		ON Fact.PROFT_CNTR_KEY=GLOBAL_EDW.dbo.EDW_T_D_MST_PROFCTR_CUR_D.PROFT_CNTR_KEY
            
    left join GLOBAL_EDW.dbo.EDW_T_D_SAL_SALORDH_CUR_D
    
		ON Fact.SALES_ORDER_KEY=GLOBAL_EDW.dbo.EDW_T_D_SAL_SALORDH_CUR_D.SALES_ORDER_KEY
            
    left join GLOBAL_EDW.dbo.EDW_T_D_MST_CMPNYCD_CUR_D
    
		ON Fact.CMPNY_KEY=GLOBAL_EDW.dbo.EDW_T_D_MST_CMPNYCD_CUR_D.CMPNY_KEY
            
    left join GLOBAL_EDW.dbo.EDW_T_D_MST_WORKCTR_CUR_D
    
		ON Fact.WRK_CNTR_KEY=GLOBAL_EDW.dbo.EDW_T_D_MST_WORKCTR_CUR_D.WRK_CNTR_KEY
            
    left join GLOBAL_EDW.dbo.EDW_T_D_MST_COSCNTR_CUR_D
    
		ON Fact.COST_CNTR_KEY=GLOBAL_EDW.dbo.EDW_T_D_MST_COSCNTR_CUR_D.COST_CNTR_KEY
            
    left join GLOBAL_EDW.dbo.EDW_T_D_MST_ACTTYPE_CUR_D
    
		ON Fact.ACTIVITY_TYP_KEY=GLOBAL_EDW.dbo.EDW_T_D_MST_ACTTYPE_CUR_D.ACTIVITY_TYP_KEY
            
    left join GLOBAL_EDW.dbo.EDW_T_D_MST_PERSONL_CUR_D
    
		ON Fact.PERSONEL_NUM_KEY=GLOBAL_EDW.dbo.EDW_T_D_MST_PERSONL_CUR_D.PERSONEL_KEY           
    
	left join GLOBAL_EDW.dbo.EDW_T_R_MST_SGK_STNDRD_TXT_CATG_CUR_D
    
		ON Fact.OPERATION_STD_TEXT=GLOBAL_EDW.dbo.EDW_T_R_MST_SGK_STNDRD_TXT_CATG_CUR_D.STANDARD_TEXT_KEY           
               
    left join GLOBAL_EDW.dbo.EDW_T_D_SAL_PRDVCON_CUR_D
    
		ON Fact.SALES_ORDER_ID = GLOBAL_EDW.dbo.EDW_T_D_SAL_PRDVCON_CUR_D.SALES_ORDER_ID  
		AND Fact.SALES_ORDER_ITM_NBR=GLOBAL_EDW.dbo.EDW_T_D_SAL_PRDVCON_CUR_D.SALES_ORDER_ITM_ID 
		AND GLOBAL_EDW.dbo.EDW_T_D_SAL_PRDVCON_CUR_D.ETL_CURR_RCD_IND='Y'
            
    left join GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D
    
		ON Fact.SALES_ORDER_ITM_NBR = GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.SALES_ORDER_ITM_ID 
		AND Fact.SALES_ORDER_ID = GLOBAL_EDW.dbo.EDW_T_B_SAL_SOIPTNR_CUR_D.SALES_ORDER_ID     
	

	left join GLOBAL_EDW.dbo.EDW_T_D_MST_DATE_CUR_D AS POSTING_DATE
    
		ON Fact.PSTNG_DATE_KEY=POSTING_DATE.DATE_KEY

	left join GLOBAL_EDW.dbo.EDW_T_D_MST_PLANT_CUR_D AS PLANNING_PLANT
    
		ON Fact.PLNG_PLNT_KEY=PLANNING_PLANT.PLNT_KEY

	left join GLOBAL_EDW.dbo.EDW_T_D_MST_PLANT_CUR_D AS OPERATING_PLANT
    
		ON Fact.OPERATING_PLNT_KEY=OPERATING_PLANT.PLNT_KEY

	left join GLOBAL_EDW.dbo.EDW_T_D_MST_DATE_CUR_D AS SERVICE_ORDER_CREATE_DATE
    
		ON Fact.SERVC_ORDER_CREATE_DATE_KEY=SERVICE_ORDER_CREATE_DATE.DATE_KEY

	left join GLOBAL_EDW.dbo.EDW_T_D_MST_DATE_CUR_D AS TECH_COMPLETION_DATE
    
		ON Fact.TCHNCL_COMPLETION_DATE_KEY=TECH_COMPLETION_DATE.DATE_KEY
        ;
    -- Step 3: Return success message
    PRINT 'Succeeded';
END