CREATE       PROCEDURE [Propelis].[Proc_SPECIAL_STOCK_PARTNER]
AS
BEGIN  
    -- Update existing records
    UPDATE T SET
        T.[CUST_KEY] = S.[CUST_KEY],                                                                                   
        T.[Special Stock Partner ID] = S.[CUST_ID],
        T.[Special Stock Partner Legacy Customer ID] = S.[LGCY_CUST_ID],
        T.[Special Stock Partner Name] = S.[CUST_NAME],
        T.[Special Stock Partner Line 2 Description] = S.[CUST_LINE_2_DESC],
        T.[Special Stock Partner Country Code] = S.[CNTRY_CD],
        T.[Special Stock Partner Plant ID] = S.[PLNT_ID],
        T.[Special Stock Partner Segment ID] = S.[SEG_ID],
        T.[Special Stock Partner Industry] = S.[INDUS],
        T.[Special Stock Partner Vendor ID] = S.[VNDR_ID],
        T.[Special Stock Partner Customer Group Code] = S.[CUST_GROUP_CD],
        T.[Special Stock Partner Account Group Code] = S.[CUST_ACCT_GROUP_CD],
        T.[Special Stock Partner Title] = S.[TITLE],
        T.[Special Stock Partner Search Term] = S.[SEARCH_TERM],
        T.[Special Stock Partner Street] = S.[STR],
        T.[Special Stock Partner City] = S.[CITY_NAME],
        T.[Special Stock Partner Zip Code] = S.[ZIP_CD],
        T.[Special Stock Partner State Code] = S.[ST_CD],
        T.[Special Stock Partner Region Code] = S.[REGN_CD],
        T.[Special Stock Partner Telephone Number 1] = S.[TEL_NUM_1_CD],
        T.[Special Stock Partner Telephone Number 2] = S.[TEL_NUM_2_CD],
        T.[Special Stock Partner Fax Number Code] = S.[FAX_NUM_CD],
        T.[Special Stock Partner Tax Number 1 Code] = S.[TAX_NUM_1_CD],
        T.[Special Stock Partner Tax Number 2 Code] = S.[TAX_NUM_2_CD],
        T.[Special Stock Partner VAT Number Code] = S.[VAT_NUM_CD],
        T.[Special Stock Partner Credit Limit] = S.[CREDIT_LMT],                                         
        T.[Special Stock Partner Bonus Rate] = S.[BONUS_RT],
        T.[Special Stock Partner Express Station] = S.[EXPRESS_STATION],
        T.[Special Stock Partner Transportation Zone] = S.[TRANSTN_ZONE],
        T.[Special Stock Partner Printer Location Characteristics] = S.[PRINTER_LOC_CHARS],
        T.[Special Stock Partner Printer Region Characteristics] = S.[PRINTER_REGN_CHARS],
        T.[Special Stock Partner Printer Site Characteristics] = S.[PRINTER_SITE_CHARS],
        T.[Special Stock Partner Customer Created Date] = S.[CREATED_DATE],
        T.[Special Stock Partner Created User ID] = S.[CREATED_USR_ID],
        T.[Special Stock Partner Customer Updated Date] = S.[UPDTD_DATE],
        T.[Special Stock Partner Updated User ID] = S.[UPDTD_USR_ID],
        T.[Special Stock Partner Payment Terms Code] = S.[PYMT_TRMS_CD],
        T.[Special Stock Partner Sales Distribution] = S.[SALES_DISTR],
        T.[Special Stock Partner Order Block For Sales Area] = S.[ORDER_BLK_FOR_SALES_AREA],
        T.[Special Stock Partner Delivery Block For Sales Area] = S.[DLVRY_BLK_FOR_SALES_AREA],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE] = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE] = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND] = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Special Stock Partner Corporate Group] = S.[CORPORATE_GROUP],
        T.[Special Stock Partner Classification] = S.[CUST_CLSFTN],
        T.[Special Stock Partner Classification Description] = S.[CUST_CLSFTN_DESC],
        T.[Special Stock Partner Printer Location] = S.[PRINTER_LOC],
        T.[Special Stock Partner Printer Site] = S.[PRINTER_SITE],
        T.[Special Stock Partner Printer Region] = S.[PRINTER_REGN],
        T.[Special Stock Partner Specific Field Label 01] = S.[CUST_SPECIFIC_FLD_LBL_01],
        T.[Special Stock Partner Specific Field Label 02] = S.[CUST_SPECIFIC_FLD_LBL_02],
        T.[Special Stock Partner Specific Field Label 03] = S.[CUST_SPECIFIC_FLD_LBL_03],
        T.[Special Stock Partner Specific Field Label 04] = S.[CUST_SPECIFIC_FLD_LBL_04],
        T.[Special Stock Partner Specific Field Label 05] = S.[CUST_SPECIFIC_FLD_LBL_05],
        T.[Special Stock Partner Specific Field Label 06] = S.[CUST_SPECIFIC_FLD_LBL_06],
        T.[Special Stock Partner Specific Field Label 07] = S.[CUST_SPECIFIC_FLD_LBL_07],
        T.[Special Stock Partner Specific Field Label 08] = S.[CUST_SPECIFIC_FLD_LBL_08],
        T.[Special Stock Partner Specific Field Label 09] = S.[CUST_SPECIFIC_FLD_LBL_09],
        T.[Special Stock Partner Specific Field Label 10] = S.[CUST_SPECIFIC_FLD_LBL_10],
        T.[Special Stock Partner Specific Field Label 11] = S.[CUST_SPECIFIC_FLD_LBL_11],
        T.[Special Stock Partner Specific Field Label 12] = S.[CUST_SPECIFIC_FLD_LBL_12],
        T.[Special Stock Partner Specific Field Label 13] = S.[CUST_SPECIFIC_FLD_LBL_13],
        T.[Special Stock Partner Specific Field Label 14] = S.[CUST_SPECIFIC_FLD_LBL_14],
        T.[Special Stock Partner Specific Field Label 15] = S.[CUST_SPECIFIC_FLD_LBL_15],
        T.[Special Stock Partner Specific Field Label 16] = S.[CUST_SPECIFIC_FLD_LBL_16],
        T.[Special Stock Partner Specific Field Label 17] = S.[CUST_SPECIFIC_FLD_LBL_17],
        T.[Special Stock Partner Specific Field Label 18] = S.[CUST_SPECIFIC_FLD_LBL_18],
        T.[Special Stock Partner Specific Field Label 19] = S.[CUST_SPECIFIC_FLD_LBL_19],
        T.[Special Stock Partner Specific Field Label 20] = S.[CUST_SPECIFIC_FLD_LBL_20],
        T.[Special Stock Partner Condition Group 1] = S.[CUST_COND_GROUP_1],
        T.[Special Stock Partner Industry Code 1] = S.[INDUS_CD_1],
        T.[Special Stock Partner Industry Code 2] = S.[INDUS_CD_2],
        T.[Special Stock Partner Industry Description] = S.[INDUS_DESC],
        T.[Special Stock Partner Industry Code 1 Description] = S.[INDUS_CD_1_DESC],
        T.[Special Stock Partner Industry Code 2 Description] = S.[INDUS_CD_2_DESC],
        T.[Special Stock Partner Assignment to Hierarchy] = S.[ASSIGN_TO_HIERCHY],
        T.[Special Stock Partner Account Group Description] = S.[CUST_ACCT_GROUP_DESC],
        T.[Special Stock Partner Region Description] = S.[REGN_DESC],
        T.[Special Stock Partner Country Description] = S.[CNTRY_DESC],
        T.[Special Stock Partner Transportation Zone Description] = S.[TRANSTN_ZONE_DESC],
        T.[Special Stock Partner Plant Description] = S.[PLNT_DESC],
        T.[Special Stock Partner Condition Group Description] = S.[CUST_COND_GROUP_DESC],
        T.[Special Stock Partner Cental Billing Block] = S.[CENTRAL_BILLING_BLK],
        T.[Special Stock Partner Cental Billing Block Description] = S.[CENTRAL_BILLING_BLK_DESC],
        T.[Special Stock Partner Central Delivery Block] = S.[CENTRAL_DLVRY_BLK],
        T.[Special Stock Partner Central Delivery Block Description] = S.[CENTRAL_DLVRY_BLK_DESC],
        T.[Special Stock Partner Deletion Indicator] = S.[DELETION_IND],
        T.[Special Stock Partner Central Posting Block] = S.[CENTRAL_PSTNG_BLK],
        T.[Special Stock Partner Tax Jurisdiction] = S.[TAX_JRSDCTN],
        T.[Special Stock Partner Central Sales Block] = S.[CENTRAL_SALES_BLK],
        T.[Special Stock Partner Central Deletion Indicator] = S.[CENTRAL_DELETION_IND],
        T.[Special Stock Partner Language Key] = S.[LANG_KEY],
        T.[Special Stock Partner Trading Partner] = S.[TRADING_PRTNR],
        T.[Special Stock Partner Trading Partner Description] = S.[TRADING_PRTNR_DESC],
        T.[Special Stock Partner Annual Sales] = S.[ANNUAL_SALES],
        T.[Special Stock Partner Annual Sales Year] = S.[ANNUAL_SALES_YR],
        T.[Special Stock Partner Sales Currency] = S.[SALES_CRNCY],
        T.[Special Stock Partner Sales Currency Description] = S.[SALES_CRNCY_DESC],
        T.[Special Stock Partner One Time Account Group] = S.[ONE_TM_CUST_ACCT_GROUP],
        T.[Special Stock Partner One Time Account Group Description] = S.[ONE_TM_CUST_ACCT_GROUP_DESC],
        T.[Special Stock Partner One Time Indicator] = S.[ONE_TM_CUST_IND],
        T.[Special Stock Partner Industry Type] = S.[INDUS_TYP],
        T.[Special Stock Partner Business Type] = S.[BIZ_TYP],
        T.[Special Stock Partner DUNS Number] = S.[DUNS_NUM],
        T.[Special Stock Partner DUNS Plus 4] = S.[DUNS_PLUS_4],
        T.[CITY_COORDINATES] = S.[CITY_COORDINATES],
        T.[TAX_NUM_4_CD] = S.[TAX_NUM_4_CD],
        T.[ATTRIB_3] = S.[ATTRIB_3],
        T.[ATTRIB_3_DESC] = S.[ATTRIB_3_DESC],
        T.[E_MAIL_ADDR] = S.[E_MAIL_ADDR],
        T.[MOBILE_NUM] = S.[MOBILE_NUM],
        T.[SEARCH_TERM_2] = S.[SEARCH_TERM_2],
        T.[STR_2] = S.[STR_2],
        T.[STR_3] = S.[STR_3],
        T.[STR_4] = S.[STR_4],
        T.[STR_5] = S.[STR_5],
        T.[PO_BOX] = S.[PO_BOX],
        T.[PO_BOX_POSTAL_CD] = S.[PO_BOX_POSTAL_CD],
        T.[PO_BOX_CITY] = S.[PO_BOX_CITY],
        T.[REGN_FOR_PO_BOX] = S.[REGN_FOR_PO_BOX],
        T.[PO_BOX_CNTRY] = S.[PO_BOX_CNTRY],
        T.[TRNSPRT_ZONE] = S.[TRNSPRT_ZONE],
        T.[ADDR_NOTES] = S.[ADDR_NOTES],
        T.[TAX_NUM_3] = S.[TAX_NUM_3],
        T.[TAX_NUM_5] = S.[TAX_NUM_5],
        T.[INDUS_CD_3] = S.[INDUS_CD_3],
        T.[INDUS_CD_3_DESC] = S.[INDUS_CD_3_DESC],
        T.[INDUS_CD_4] = S.[INDUS_CD_4],
        T.[INDUS_CD_4_DESC] = S.[INDUS_CD_4_DESC],
        T.[INDUS_CD_5] = S.[INDUS_CD_5],
        T.[INDUS_CD_5_DESC] = S.[INDUS_CD_5_DESC],
        T.[CENTRAL_ORDER_BLK_FOR_CUST] = S.[CENTRAL_ORDER_BLK_FOR_CUST],
        T.[PYMT_BLK] = S.[PYMT_BLK]  
	
    FROM [GLOBAL_EDW].[Propelis].[SPECIAL_STOCK_PARTNER] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CUSTOMR_CUR_D] S
        ON T.[CUST_KEY] = S.[CUST_KEY];
 
        -- Insert new records
    INSERT INTO [GLOBAL_EDW].[Propelis].[SPECIAL_STOCK_PARTNER] (
        [CUST_KEY],
        [Special Stock Partner ID],
        [Special Stock Partner Legacy Customer ID],
        [Special Stock Partner Name],
        [Special Stock Partner Line 2 Description],
        [Special Stock Partner Country Code],
        [Special Stock Partner Plant ID],
        [Special Stock Partner Segment ID],
        [Special Stock Partner Industry],
        [Special Stock Partner Vendor ID],
        [Special Stock Partner Customer Group Code],
        [Special Stock Partner Account Group Code],
        [Special Stock Partner Title],
        [Special Stock Partner Search Term],
        [Special Stock Partner Street],
        [Special Stock Partner City],
        [Special Stock Partner Zip Code],
        [Special Stock Partner State Code],
        [Special Stock Partner Region Code],
        [Special Stock Partner Telephone Number 1],
        [Special Stock Partner Telephone Number 2],
        [Special Stock Partner Fax Number Code],
        [Special Stock Partner Tax Number 1 Code],
        [Special Stock Partner Tax Number 2 Code],
        [Special Stock Partner VAT Number Code],
        [Special Stock Partner Credit Limit],
        [Special Stock Partner Bonus Rate],
        [Special Stock Partner Express Station],
        [Special Stock Partner Transportation Zone],
        [Special Stock Partner Printer Location Characteristics],
        [Special Stock Partner Printer Region Characteristics],
        [Special Stock Partner Printer Site Characteristics],
        [Special Stock Partner Customer Created Date],
        [Special Stock Partner Created User ID],
        [Special Stock Partner Customer Updated Date],
        [Special Stock Partner Updated User ID],
        [Special Stock Partner Payment Terms Code],
        [Special Stock Partner Sales Distribution],
        [Special Stock Partner Order Block For Sales Area],
        [Special Stock Partner Delivery Block For Sales Area],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Special Stock Partner Corporate Group],
        [Special Stock Partner Classification],
        [Special Stock Partner Classification Description],
        [Special Stock Partner Printer Location],
        [Special Stock Partner Printer Site],
        [Special Stock Partner Printer Region],
        [Special Stock Partner Specific Field Label 01],
        [Special Stock Partner Specific Field Label 02],
        [Special Stock Partner Specific Field Label 03],
        [Special Stock Partner Specific Field Label 04],
        [Special Stock Partner Specific Field Label 05],
        [Special Stock Partner Specific Field Label 06],
        [Special Stock Partner Specific Field Label 07],
        [Special Stock Partner Specific Field Label 08],
        [Special Stock Partner Specific Field Label 09],
        [Special Stock Partner Specific Field Label 10],
        [Special Stock Partner Specific Field Label 11],
        [Special Stock Partner Specific Field Label 12],
        [Special Stock Partner Specific Field Label 13],
        [Special Stock Partner Specific Field Label 14],
        [Special Stock Partner Specific Field Label 15],
        [Special Stock Partner Specific Field Label 16],
        [Special Stock Partner Specific Field Label 17],
        [Special Stock Partner Specific Field Label 18],
        [Special Stock Partner Specific Field Label 19],
        [Special Stock Partner Specific Field Label 20],
        [Special Stock Partner Condition Group 1],
        [Special Stock Partner Industry Code 1],
        [Special Stock Partner Industry Code 2],
        [Special Stock Partner Industry Description],
        [Special Stock Partner Industry Code 1 Description],
        [Special Stock Partner Industry Code 2 Description],
        [Special Stock Partner Assignment to Hierarchy],
        [Special Stock Partner Account Group Description],
        [Special Stock Partner Region Description],
        [Special Stock Partner Country Description],
        [Special Stock Partner Transportation Zone Description],
        [Special Stock Partner Plant Description],
        [Special Stock Partner Condition Group Description],
        [Special Stock Partner Cental Billing Block],
        [Special Stock Partner Cental Billing Block Description],
        [Special Stock Partner Central Delivery Block],
        [Special Stock Partner Central Delivery Block Description],
        [Special Stock Partner Deletion Indicator],
        [Special Stock Partner Central Posting Block],
        [Special Stock Partner Tax Jurisdiction],
        [Special Stock Partner Central Sales Block],
        [Special Stock Partner Central Deletion Indicator],
        [Special Stock Partner Language Key],
        [Special Stock Partner Trading Partner],
        [Special Stock Partner Trading Partner Description],
        [Special Stock Partner Annual Sales],
        [Special Stock Partner Annual Sales Year],
        [Special Stock Partner Sales Currency],
        [Special Stock Partner Sales Currency Description],
        [Special Stock Partner One Time Account Group],
        [Special Stock Partner One Time Account Group Description],
        [Special Stock Partner One Time Indicator],
        [Special Stock Partner Industry Type],
        [Special Stock Partner Business Type],
        [Special Stock Partner DUNS Number],
        [Special Stock Partner DUNS Plus 4],
        [CITY_COORDINATES],
        [TAX_NUM_4_CD],
        [ATTRIB_3],
        [ATTRIB_3_DESC],
        [E_MAIL_ADDR],
        [MOBILE_NUM],
        [SEARCH_TERM_2],
        [STR_2],
        [STR_3],
        [STR_4],
        [STR_5],
        [PO_BOX],
        [PO_BOX_POSTAL_CD],
        [PO_BOX_CITY],
        [REGN_FOR_PO_BOX],
        [PO_BOX_CNTRY],
        [TRNSPRT_ZONE],
        [ADDR_NOTES],
        [TAX_NUM_3],
        [TAX_NUM_5],
        [INDUS_CD_3],
        [INDUS_CD_3_DESC],
        [INDUS_CD_4],
        [INDUS_CD_4_DESC],
        [INDUS_CD_5],
        [INDUS_CD_5_DESC],
        [CENTRAL_ORDER_BLK_FOR_CUST],
        [PYMT_BLK]

    )
    SELECT
        S.[CUST_KEY],
        S.[CUST_ID],
        S.[LGCY_CUST_ID],
        S.[CUST_NAME],
        S.[CUST_LINE_2_DESC],
        S.[CNTRY_CD],
        S.[PLNT_ID],
        S.[SEG_ID],
        S.[INDUS],
        S.[VNDR_ID],
        S.[CUST_GROUP_CD],
        S.[CUST_ACCT_GROUP_CD],
        S.[TITLE],
        S.[SEARCH_TERM],
        S.[STR],
        S.[CITY_NAME],
        S.[ZIP_CD],
        S.[ST_CD],
        S.[REGN_CD],
        S.[TEL_NUM_1_CD],
        S.[TEL_NUM_2_CD],
        S.[FAX_NUM_CD],
        S.[TAX_NUM_1_CD],
        S.[TAX_NUM_2_CD],
        S.[VAT_NUM_CD],
        S.[CREDIT_LMT],
        S.[BONUS_RT],
        S.[EXPRESS_STATION],
        S.[TRANSTN_ZONE],
        S.[PRINTER_LOC_CHARS],
        S.[PRINTER_REGN_CHARS],
        S.[PRINTER_SITE_CHARS],
        S.[CREATED_DATE],
        S.[CREATED_USR_ID],
        S.[UPDTD_DATE],
        S.[UPDTD_USR_ID],
        S.[PYMT_TRMS_CD],
        S.[SALES_DISTR],
        S.[ORDER_BLK_FOR_SALES_AREA],
        S.[DLVRY_BLK_FOR_SALES_AREA],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CORPORATE_GROUP],
        S.[CUST_CLSFTN],
        S.[CUST_CLSFTN_DESC],
        S.[PRINTER_LOC],
        S.[PRINTER_SITE],
        S.[PRINTER_REGN],
        S.[CUST_SPECIFIC_FLD_LBL_01],
        S.[CUST_SPECIFIC_FLD_LBL_02],
        S.[CUST_SPECIFIC_FLD_LBL_03],
        S.[CUST_SPECIFIC_FLD_LBL_04],
        S.[CUST_SPECIFIC_FLD_LBL_05],
        S.[CUST_SPECIFIC_FLD_LBL_06],
        S.[CUST_SPECIFIC_FLD_LBL_07],
        S.[CUST_SPECIFIC_FLD_LBL_08],
        S.[CUST_SPECIFIC_FLD_LBL_09],
        S.[CUST_SPECIFIC_FLD_LBL_10],
        S.[CUST_SPECIFIC_FLD_LBL_11],
        S.[CUST_SPECIFIC_FLD_LBL_12],
        S.[CUST_SPECIFIC_FLD_LBL_13],
        S.[CUST_SPECIFIC_FLD_LBL_14],
        S.[CUST_SPECIFIC_FLD_LBL_15],
        S.[CUST_SPECIFIC_FLD_LBL_16],
        S.[CUST_SPECIFIC_FLD_LBL_17],
        S.[CUST_SPECIFIC_FLD_LBL_18],
        S.[CUST_SPECIFIC_FLD_LBL_19],
        S.[CUST_SPECIFIC_FLD_LBL_20],
        S.[CUST_COND_GROUP_1],
        S.[INDUS_CD_1],
        S.[INDUS_CD_2],
        S.[INDUS_DESC],
        S.[INDUS_CD_1_DESC],
        S.[INDUS_CD_2_DESC],
        S.[ASSIGN_TO_HIERCHY],
        S.[CUST_ACCT_GROUP_DESC],
        S.[REGN_DESC],
        S.[CNTRY_DESC],
        S.[TRANSTN_ZONE_DESC],
        S.[PLNT_DESC],
        S.[CUST_COND_GROUP_DESC],
        S.[CENTRAL_BILLING_BLK],
        S.[CENTRAL_BILLING_BLK_DESC],
        S.[CENTRAL_DLVRY_BLK],
        S.[CENTRAL_DLVRY_BLK_DESC],
        S.[DELETION_IND],
        S.[CENTRAL_PSTNG_BLK],
        S.[TAX_JRSDCTN],
        S.[CENTRAL_SALES_BLK],
        S.[CENTRAL_DELETION_IND],
        S.[LANG_KEY],
        S.[TRADING_PRTNR],
        S.[TRADING_PRTNR_DESC],
        S.[ANNUAL_SALES],
        S.[ANNUAL_SALES_YR],
        S.[SALES_CRNCY],
        S.[SALES_CRNCY_DESC],
        S.[ONE_TM_CUST_ACCT_GROUP],
        S.[ONE_TM_CUST_ACCT_GROUP_DESC],
        S.[ONE_TM_CUST_IND],
        S.[INDUS_TYP],
        S.[BIZ_TYP],
        S.[DUNS_NUM],
        S.[DUNS_PLUS_4],
        S.[CITY_COORDINATES],
        S.[TAX_NUM_4_CD],
        S.[ATTRIB_3],
        S.[ATTRIB_3_DESC],
        S.[E_MAIL_ADDR],
        S.[MOBILE_NUM],
        S.[SEARCH_TERM_2],
        S.[STR_2],
        S.[STR_3],
        S.[STR_4],
        S.[STR_5],
        S.[PO_BOX],
        S.[PO_BOX_POSTAL_CD],
        S.[PO_BOX_CITY],
        S.[REGN_FOR_PO_BOX],
        S.[PO_BOX_CNTRY],
        S.[TRNSPRT_ZONE],
        S.[ADDR_NOTES],
        S.[TAX_NUM_3],
        S.[TAX_NUM_5],
        S.[INDUS_CD_3],
        S.[INDUS_CD_3_DESC],
        S.[INDUS_CD_4],
        S.[INDUS_CD_4_DESC],
        S.[INDUS_CD_5],
        S.[INDUS_CD_5_DESC],
        S.[CENTRAL_ORDER_BLK_FOR_CUST],
        S.[PYMT_BLK]
    
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CUSTOMR_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[SPECIAL_STOCK_PARTNER] T
        ON T.[CUST_KEY] = S.[CUST_KEY]
    WHERE T.[CUST_KEY] IS NULL;
END