CREATE   PROCEDURE [Propelis].[Proc_GOODS_ISSUED_DATE]
AS
BEGIN
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Goods Issued Date] = S.[THE_DATE],
        T.[Goods Issued Fiscal Year] = S.[FISCAL_YR],
        T.[Goods Issued Fiscal Period] = S.[FISCAL_PER_NUM],
        T.[Goods Issued Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Goods Issued Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Goods Issued Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Goods Issued Calendar Year] = S.[CLNDR_YR],
        T.[Goods Issued Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Goods Issued Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Goods Issued Calendar Month Desc] = S.[CLNDR_MNTH_DESC],
        T.[Goods Issued Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[Goods Issued Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Goods Issued Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Goods Issued Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Goods Issued Calendar Day in Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Goods Issued Calendar Day in Year] = S.[CLNDR_DAY_IN_YR],
        T.[Goods Issued Calendar Week] = S.[CLNDR_WK],
        T.[Goods Issued Calendar Month in Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Goods Issued Calendar Days in Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Goods Issued Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Goods Issued Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Goods Issued Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Goods Issued Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Goods Issued Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Goods Issued Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Goods Issued Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Goods Issued Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Goods Issued Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Goods Issued Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Goods Issued Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Goods Issued Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Goods Issued Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Goods Issued Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Goods Issued Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Goods Issued Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Goods Issued Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Goods Issued Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Goods Issued Day in Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Goods Issued Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Goods Issued Fiscal Week] = S.[FISCAL_WK],
        T.[Goods Issued Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Goods Issued Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Goods Issued Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Goods Issued Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Goods Issued Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Goods Issued Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Goods Issued Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Goods Issued Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Goods Issued Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Goods Issued Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Goods Issued Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[GOODS_ISSUED_DATE] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];

    
    INSERT INTO [GLOBAL_EDW].[Propelis].[GOODS_ISSUED_DATE]
    (
        [DATE_KEY],
        [Goods Issued Date],
        [Goods Issued Fiscal Year],
        [Goods Issued Fiscal Period],
        [Goods Issued Fiscal Period Code],
        [Goods Issued Fiscal Quarter Number],
        [Goods Issued Fiscal Quarter Code],
        [Goods Issued Calendar Year],
        [Goods Issued Calendar Month Number],
        [Goods Issued Calendar Month Code],
        [Goods Issued Calendar Month Desc],
        [Goods Issued Calendar Quarter Number],
        [Goods Issued Calendar Quarter Code],
        [Goods Issued Calendar Weekday Number],
        [Goods Issued Calendar Weekday Name],
        [Goods Issued Calendar Day in Month],
        [Goods Issued Calendar Day in Year],
        [Goods Issued Calendar Week],
        [Goods Issued Calendar Month in Quarter Number],
        [Goods Issued Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Goods Issued Current Day Flag],
        [Goods Issued Current Day Minus 1 Flag],
        [Goods Issued Current Calendar Week Flag],
        [Goods Issued Current Calendar Week Minus 1 Flag],
        [Goods Issued Current Month Flag],
        [Goods Issued Current Month Minus 1 Flag],
        [Goods Issued Current Month Minus 12 Flag],
        [Goods Issued Current Quarter Flag],
        [Goods Issued Current Quarter Minus 1 Flag],
        [Goods Issued Current Quarter Minus 4 Flag],
        [Goods Issued Current Calendar Year Flag],
        [Goods Issued Current Calendar Year Minus 1 Flag],
        [Goods Issued Current Calendar Year Minus 2 Flag],
        [Goods Issued Current Fiscal Year Flag],
        [Goods Issued Current Fiscal Year Minus 1 Flag],
        [Goods Issued Current Fiscal Year Minus 2 Flag],
        [Goods Issued Current Calendar Year Plus 1 Flag],
        [Goods Issued Current Fiscal Year Plus 1 Flag],
        [Goods Issued Day in Fiscal Year],
        [Goods Issued Date Is Weekday],
        [Goods Issued Fiscal Week],
        [Goods Issued Current Fiscal Week Flag],
        [Goods Issued Current Fiscal Week Minus 1 Flag],
        [Goods Issued Fiscal Weekday Number],
        [Goods Issued Fiscal Weekday Name],
        [Goods Issued Current Month Minus 2 Flag],
        [Goods Issued Current Fiscal Week Minus 2 Flag],
        [Goods Issued Current Fiscal Week Minus 6 Flag],
        [Goods Issued Current Fiscal Week Minus 3 Flag],
        [Goods Issued Current Fiscal Week Minus 4 Flag],
        [Goods Issued Current Fiscal Week Minus 5 Flag],
        [Goods Issued Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[GOODS_ISSUED_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
END