CREATE   PROCEDURE [Propelis].[Proc_EDW_T_FACT_PRD_QCDBDAT_CUR_D]
AS
BEGIN
 
   -- Step 1: Clear existing data from the target table
   
TRUNCATE TABLE [GLOBAL_EDW].[Propelis].[EDW_T_FACT_PRD_QCDBDAT_CUR_D];

   -- Step 2: Insert refreshed data from mirror table with joins

INSERT INTO [GLOBAL_EDW].[Propelis].[EDW_T_FACT_PRD_QCDBDAT_CUR_D](
	[QC Service Order ID],
	[QC Job Category],
	[QC Revision ID],
	[QC Revision No],
	[QC Job ID],
	[QC Unique Identifier],
	[QC Task],
	[SERVC_ORDER_KEY],
	[SOLDTO_PARTY_KEY],
	[QC Checklist Activity Type],
	[QC PA User],
	[QC User ID],
	[QC Does Stage Have Error],
	[QC Error Comment],
	[CUST_BRAND_HIERCHY_KEY],
	[SCHAWK_PLNT_KEY],
	[PA_PLNT_KEY],
	[QC_PLNT_KEY],
	[DATE_COMPLETION_PA_KEY],
	[DATE_COMPLETION_QC_KEY],
	[PARNT_KEY],
	[CREATED_ON_TS],
	[CREATED_ON_DATE_KEY],
	[ETL_SRC_SYS_CD],
	[ETL_CREATED_TS],
	[ETL_UPDTD_TS],
	[QC Instructions],
	
	[OPERREG_PLANT]
)

SELECT 
    FACT.[SERVC_ORDER_ID],
	FACT.[JOB_CTGRY],
	FACT.[REVISION_ID],
	FACT.[REVISION_NO],
	FACT.[QC_JOB_ID],
	FACT.[UNQ_IDENTIFIER],
	FACT.[TASK],
	FACT.[SERVC_ORDER_KEY],
	FACT.[SOLDTO_PARTY_KEY],
	FACT.[CHECKLIST_ACTIVITY_TYP],
	FACT.[PA_USR],
	FACT.[QC_USR_ID],
	FACT.[DOES_STAGE_HAVE_ERR],
	FACT.[ERR_COMMENT],
	FACT.[CUST_BRAND_HIERCHY_KEY],
	FACT.[SCHAWK_PLNT_KEY],
	FACT.[PA_PLNT_KEY],
	FACT.[QC_PLNT_KEY],
	FACT.[DATE_COMPLETION_PA_KEY],
	FACT.[DATE_COMPLETION_QC_KEY],
	FACT.[PARNT_KEY],
	FACT.[CREATED_ON_TS],
	FACT.[CREATED_ON_DATE_KEY],
	FACT.[ETL_SRC_SYS_CD],
	FACT.[ETL_CREATED_TS],
	FACT.[ETL_UPDTD_TS],
	FACT.[INSTRUCTIONS],
	
	SHK_PNT.[Schawk Plant ID] AS OPERREG_PLANT
	 
FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_F_PRD_QCDBDAT_CUR_D] AS FACT

LEFT JOIN [GLOBAL_EDW].[Propelis].[PARENT_CUST] AS P_CUST
  ON FACT.PARNT_KEY = P_CUST.CUST_KEY
  
LEFT JOIN [GLOBAL_EDW].[Propelis].[QC_PLANT] AS QC_PNT
  ON FACT.QC_PLNT_KEY = QC_PNT.PLNT_KEY

LEFT JOIN [GLOBAL_EDW].[Propelis].[EDW_T_D_MST_CUSTBRD_CUR_D] AS MST_CUSTBRD
  ON FACT.CUST_BRAND_HIERCHY_KEY = MST_CUSTBRD.CUST_BRAND_HIERCHY_KEY
  
LEFT JOIN [GLOBAL_EDW].[Propelis].[PA_COMPLETION_DATE] AS PA_Com_DT
  ON FACT.DATE_COMPLETION_PA_KEY =PA_Com_DT.DATE_KEY

LEFT JOIN [GLOBAL_EDW].[Propelis].[Schawk_PLANT] AS SHK_PNT
  ON FACT.SCHAWK_PLNT_KEY = SHK_PNT.PLNT_KEY
 
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_PRD_SERVORD_CUR_D] AS PRD_SERVORD
  ON FACT.SERVC_ORDER_KEY = PRD_SERVORD.SERVC_ORDER_KEY
  
LEFT JOIN [GLOBAL_EDW].[Propelis].[SOLD_TO_PARTY] AS ST_PRTY
  ON FACT.SOLDTO_PARTY_KEY = ST_PRTY.CUST_KEY
  
LEFT JOIN [GLOBAL_EDW].[Propelis].[PA_PLANT] AS PA_Plant
  ON FACT.PA_PLNT_KEY = PA_Plant.PLNT_KEY 
  
LEFT JOIN [GLOBAL_EDW].[Propelis].[QC_COMPLETION_DATE] AS QC_COM_DT
  ON FACT.DATE_COMPLETION_QC_KEY = QC_COM_DT.DATE_KEY;
  
END