CREATE   PROCEDURE [Propelis].[Proc_GOODS_ISSUE_DATE]
AS
BEGIN  
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Goods Issue Date] = S.[THE_DATE],
        T.[Goods Issue Fiscal Year] = S.[FISCAL_YR],
        T.[Goods Issue Fiscal Period] = S.[FISCAL_PER_NUM],
        T.[Goods Issue Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Goods Issue Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Goods Issue Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Goods Issue Calendar Year] = S.[CLNDR_YR],
        T.[Goods Issue Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Goods Issue Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Goods Issue Calendar Month Desc] = S.[CLNDR_MNTH_DESC],
        T.[Goods Issue Calendar Quarter] = S.[CLNDR_QTR_NUM],
        T.[Goods Issue Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Goods Issue Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Goods Issue Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Goods Issue Calendar Day in Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Goods Issue Calendar Day in Year] = S.[CLNDR_DAY_IN_YR],
        T.[Goods Issue Calendar Week] = S.[CLNDR_WK],
        T.[Goods Issue Calendar Month in Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Goods Issue Calendar Days in Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Goods Issue Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Goods Issue Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Goods Issue Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Goods Issue Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Goods Issue Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Goods Issue Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Goods Issue Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Goods Issue Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Goods Issue Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Goods Issue Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Goods Issue Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Goods Issue Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Goods Issue Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Goods Issue Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Goods Issue Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Goods Issue Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Goods Issue Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Goods Issue Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Goods Issue Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Goods Issue Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Goods Issue Fiscal Week] = S.[FISCAL_WK],
        T.[Goods Issue Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Goods Issue Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Goods Issue Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Goods Issue Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Goods Issue Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Goods Issue Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Goods Issue Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Goods Issue Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Goods Issue Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Goods Issue Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Goods Issue Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[GOODS_ISSUE_DATE] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];

    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[GOODS_ISSUE_DATE] (
        [DATE_KEY],
        [Goods Issue Date],
        [Goods Issue Fiscal Year],
        [Goods Issue Fiscal Period],
        [Goods Issue Fiscal Period Code],
        [Goods Issue Fiscal Quarter Number],
        [Goods Issue Fiscal Quarter Code],
        [Goods Issue Calendar Year],
        [Goods Issue Calendar Month Number],
        [Goods Issue Calendar Month Code],
        [Goods Issue Calendar Month Desc],
        [Goods Issue Calendar Quarter],
        [Goods Issue Calendar Quarter Code],
        [Goods Issue Calendar Weekday Number],
        [Goods Issue Calendar Weekday Name],
        [Goods Issue Calendar Day in Month],
        [Goods Issue Calendar Day in Year],
        [Goods Issue Calendar Week],
        [Goods Issue Calendar Month in Quarter Number],
        [Goods Issue Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Goods Issue Current Day Flag],
        [Goods Issue Current Day Minus 1 Flag],
        [Goods Issue Current Calendar Week Flag],
        [Goods Issue Current Calendar Week Minus 1 Flag],
        [Goods Issue Current Month Flag],
        [Goods Issue Current Month Minus 1 Flag],
        [Goods Issue Current Month Minus 12 Flag],
        [Goods Issue Current Quarter Flag],
        [Goods Issue Current Quarter Minus 1 Flag],
        [Goods Issue Current Quarter Minus 4 Flag],
        [Goods Issue Current Calendar Year Flag],
        [Goods Issue Current Calendar Year Minus 1 Flag],
        [Goods Issue Current Calendar Year Minus 2 Flag],
        [Goods Issue Current Fiscal Year Flag],
        [Goods Issue Current Fiscal Year Minus 1 Flag],
        [Goods Issue Current Fiscal Year Minus 2 Flag],
        [Goods Issue Current Calendar Year Plus 1 Flag],
        [Goods Issue Current Fiscal Year Plus 1 Flag],
        [Goods Issue Day In Fiscal Year],
        [Goods Issue Date Is Weekday],
        [Goods Issue Fiscal Week],
        [Goods Issue Current Fiscal Week Flag],
        [Goods Issue Current Fiscal Week Minus 1 Flag],
        [Goods Issue Fiscal Weekday Number],
        [Goods Issue Fiscal Weekday Name],
        [Goods Issue Current Month Minus 2 Flag],
        [Goods Issue Current Fiscal Week Minus 2 Flag],
        [Goods Issue Current Fiscal Week Minus 6 Flag],
        [Goods Issue Current Fiscal Week Minus 3 Flag],
        [Goods Issue Current Fiscal Week Minus 4 Flag],
        [Goods Issue Current Fiscal Week Minus 5 Flag],
        [Goods Issue Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[GOODS_ISSUE_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
END