CREATE      PROCEDURE [Propelis].[Proc_SHIP_TO_CUST]
AS
BEGIN
    -- Step 1: Update existing records in target table
    UPDATE T
    SET
                T.[CUST_KEY]	= S.[CUST_KEY],
                T.[Ship To Customer ID]	= S.[CUST_ID],
                T.[Ship To Legacy Customer ID]	= S.[LGCY_CUST_ID],
                T.[Ship To Customer Name]	= S.[CUST_NAME],
                T.[Ship To Cust Line 2 Description]	= S.[CUST_LINE_2_DESC],
                T.[Ship To Cust Country Code]	= S.[CNTRY_CD],
                T.[Ship To Cust Plant ID]	= S.[PLNT_ID],
                T.[Ship To Cust Segment ID]	= S.[SEG_ID],
                T.[Ship To Cust Industry]	= S.[INDUS],
                T.[Ship To Cust Vendor ID]	= S.[VNDR_ID],
                T.[Ship To Cust Group Code]	= S.[CUST_GROUP_CD],
                T.[Ship To Cust Account Group Code]	= S.[CUST_ACCT_GROUP_CD],
                T.[Ship To Cust Title]	= S.[TITLE],
                T.[Ship To Cust Search Term]	= S.[SEARCH_TERM],
                T.[Ship To Cust Street]	= S.[STR],
                T.[Ship To Cust City]	= S.[CITY_NAME],
                T.[Ship To Cust Zip Code]	= S.[ZIP_CD],
                T.[Ship To Cust State Code]	= S.[ST_CD],
                T.[Ship To Cust Region Code]	= S.[REGN_CD],
                T.[Ship To Cust Telephone Number 1]	= S.[TEL_NUM_1_CD],
                T.[Ship To Cust Telephone Number 2]	= S.[TEL_NUM_2_CD],
                T.[Ship To Cust Fax Number Code]	= S.[FAX_NUM_CD],
                T.[Ship To Cust Tax Number 1 Code]	= S.[TAX_NUM_1_CD],
                T.[Ship To Cust Tax Number 2 Code]	= S.[TAX_NUM_2_CD],
                T.[Ship To Cust VAT Number Code]	= S.[VAT_NUM_CD],
                T.[Ship To Cust Credit Limit]	= S.[CREDIT_LMT],
                T.[Ship To Cust Bonus Rate]	= S.[BONUS_RT],
                T.[Ship To Cust Express Station]	= S.[EXPRESS_STATION],
                T.[Ship To Cust Transportation Zone]	= S.[TRANSTN_ZONE],
                T.[Ship To Cust Printer Location Characteristics]	= S.[PRINTER_LOC_CHARS],
                T.[Ship To Cust Printer Region Characteristics]	= S.[PRINTER_REGN_CHARS],
                T.[Ship To Cust Printer Site Characteristics]	= S.[PRINTER_SITE_CHARS],
                T.[Ship To Cust Created Date]	= S.[CREATED_DATE],
                T.[Ship To Cust Created Usser ID]	= S.[CREATED_USR_ID],
                T.[Ship To Cust Updated Date]	= S.[UPDTD_DATE],
                T.[Ship To Cust Updated User ID]	= S.[UPDTD_USR_ID],
                T.[Ship To Cust Payment Terms Code]	= S.[PYMT_TRMS_CD],
                T.[Ship To Cust Sales Distribution]	= S.[SALES_DISTR],
                T.[Ship To Cust Order Block For Sales Area]	= S.[ORDER_BLK_FOR_SALES_AREA],
                T.[Ship To Cust Delivery Block For Sales Area]	= S.[DLVRY_BLK_FOR_SALES_AREA],
                T.[ETL_SRC_SYS_CD]	= S.[ETL_SRC_SYS_CD],
                T.[ETL_EFFECTV_BEGIN_DATE]	= S.[ETL_EFFECTV_BEGIN_DATE],
                T.[ETL_EFFECTV_END_DATE]	= S.[ETL_EFFECTV_END_DATE],
                T.[ETL_CURR_RCD_IND]	= S.[ETL_CURR_RCD_IND],
                T.[ETL_CREATED_TS]	= S.[ETL_CREATED_TS],
                T.[ETL_UPDTD_TS]	= S.[ETL_UPDTD_TS],
                T.[Ship To Cust Corporate Group]	= S.[CORPORATE_GROUP],
                T.[Ship To Cust Customer Classification]	= S.[CUST_CLSFTN],
                T.[Ship To Customer Customer Classification Description]	= S.[CUST_CLSFTN_DESC],
                T.[Ship To Cust Printer Location]	= S.[PRINTER_LOC],
                T.[Ship To Cust Printer Site]	= S.[PRINTER_SITE],
                T.[Ship To Cust Printer Region]	= S.[PRINTER_REGN],
                T.[Ship To Cust Specific Field Label 01]	= S.[CUST_SPECIFIC_FLD_LBL_01],
                T.[Ship To Cust Specific Field Label 02]	= S.[CUST_SPECIFIC_FLD_LBL_02],
                T.[Ship To Cust Specific Field Label 03]	= S.[CUST_SPECIFIC_FLD_LBL_03],
                T.[Ship To Cust Specific Field Label 04]	= S.[CUST_SPECIFIC_FLD_LBL_04],
                T.[Ship To Cust Specific Field Label 05]	= S.[CUST_SPECIFIC_FLD_LBL_05],
                T.[Ship To Cust Specific Field Label 06]	= S.[CUST_SPECIFIC_FLD_LBL_06],
                T.[Ship To Cust Specific Field Label 07]	= S.[CUST_SPECIFIC_FLD_LBL_07],
                T.[Ship To Cust Specific Field Label 08]	= S.[CUST_SPECIFIC_FLD_LBL_08],
                T.[Ship To Cust Specific Field Label 09]	= S.[CUST_SPECIFIC_FLD_LBL_09],
                T.[Ship To Cust Specific Field Label 10]	= S.[CUST_SPECIFIC_FLD_LBL_10],
                T.[Ship To Cust Specific Field Label 11]	= S.[CUST_SPECIFIC_FLD_LBL_11],
                T.[Ship To Cust Specific Field Label 12]	= S.[CUST_SPECIFIC_FLD_LBL_12],
                T.[Ship To Cust Specific Field Label 13]	= S.[CUST_SPECIFIC_FLD_LBL_13],
                T.[Ship To Cust Specific Field Label 14]	= S.[CUST_SPECIFIC_FLD_LBL_14],
                T.[Ship To Cust Specific Field Label 15]	= S.[CUST_SPECIFIC_FLD_LBL_15],
                T.[Ship To Cust Specific Field Label 16]	= S.[CUST_SPECIFIC_FLD_LBL_16],
                T.[Ship To Cust Specific Field Label 17]	= S.[CUST_SPECIFIC_FLD_LBL_17],
                T.[Ship To Cust Specific Field Label 18]	= S.[CUST_SPECIFIC_FLD_LBL_18],
                T.[Ship To Cust Specific Field Label 19]	= S.[CUST_SPECIFIC_FLD_LBL_19],
                T.[Ship To Cust Specific Field Label 20]	= S.[CUST_SPECIFIC_FLD_LBL_20],
                T.[Ship To Cust Condition Group 1]	= S.[CUST_COND_GROUP_1],
                T.[Ship To Cust Industry Code 1]	= S.[INDUS_CD_1],
                T.[Ship To Cust Industry Code 2]	= S.[INDUS_CD_2],
                T.[Ship To Cust Industry Description]	= S.[INDUS_DESC],
                T.[Ship To Cust Industry Code 1 Description]	= S.[INDUS_CD_1_DESC],
                T.[Ship To Cust Industry Code 2 Description]	= S.[INDUS_CD_2_DESC],
                T.[Ship To Cust Assignment to Hierarchy]	= S.[ASSIGN_TO_HIERCHY],
                T.[Ship To Cust Account Group Description]	= S.[CUST_ACCT_GROUP_DESC],
                T.[Ship To Cust Region Description]	= S.[REGN_DESC],
                T.[Ship To Cust Country Description]	= S.[CNTRY_DESC],
                T.[Ship To Cust Transportation Zone Description]	= S.[TRANSTN_ZONE_DESC],
                T.[Ship To Cust Plant Description]	= S.[PLNT_DESC],
                T.[Ship To Cust Condition Group Description]	= S.[CUST_COND_GROUP_DESC],
                T.[Ship To Cust Cental Billing Block]	= S.[CENTRAL_BILLING_BLK],
                T.[Ship To Cust Cental Billing Block Description]	= S.[CENTRAL_BILLING_BLK_DESC],
                T.[Ship To Cust Central Delivery Block]	= S.[CENTRAL_DLVRY_BLK],
                T.[Ship To Cust Central Delivery Block Description]	= S.[CENTRAL_DLVRY_BLK_DESC],
                T.[Ship To Cust Deletion Indicator]	= S.[DELETION_IND],
                T.[Ship To Cust Central Posting Block]	= S.[CENTRAL_PSTNG_BLK],
                T.[Ship To Cust Tax Jurisdiction]	= S.[TAX_JRSDCTN],
                T.[Ship To Cust Central Sales Block]	= S.[CENTRAL_SALES_BLK],
                T.[Ship To Cust Central Deletion Indicator]	= S.[CENTRAL_DELETION_IND],
                T.[Ship To Cust Language Key]	= S.[LANG_KEY],
                T.[Ship To Cust Trading Partner]	= S.[TRADING_PRTNR],
                T.[Ship To Cust Trading Partner Description]	= S.[TRADING_PRTNR_DESC],
                T.[Ship To Cust Annual Sales]	= S.[ANNUAL_SALES],
                T.[Ship To Cust Annual Sales Year]	= S.[ANNUAL_SALES_YR],
                T.[Ship To Cust Sales Currency]	= S.[SALES_CRNCY],
                T.[Ship To Cust Sales Currency Description]	= S.[SALES_CRNCY_DESC],
                T.[Ship To Cust One Time Account Group]	= S.[ONE_TM_CUST_ACCT_GROUP],
                T.[Ship To Cust One Time Account Group Description]	= S.[ONE_TM_CUST_ACCT_GROUP_DESC],
                T.[Ship To Cust One Time Indicator]	= S.[ONE_TM_CUST_IND],
                T.[Ship To Cust Industry Type]	= S.[INDUS_TYP],
                T.[Ship To Cust Business Type]	= S.[BIZ_TYP],
                T.[Ship To Cust DUNS Number]	= S.[DUNS_NUM],
                T.[Ship To Cust DUNS Plus 4]	= S.[DUNS_PLUS_4],
                T.[Ship To City Coordinates]	= S.[CITY_COORDINATES],
                T.[Ship To Cust Tax Number 4 Code]	= S.[TAX_NUM_4_CD],
                T.[Ship To Cust Attribute 3]	= S.[ATTRIB_3],
                T.[Ship To Cust Attribute 3 Description]	= S.[ATTRIB_3_DESC],
                T.[Ship To Cust E-Mail Address]	= S.[E_MAIL_ADDR],
                T.[Ship To Cust Mobile Number]	= S.[MOBILE_NUM],
                T.[Ship To Cust Search Term 2]	= S.[SEARCH_TERM_2],
                T.[Ship To Cust Street 2]	= S.[STR_2],
                T.[Ship To Cust Street 3]	= S.[STR_3],
                T.[Ship To Cust Street 4]	= S.[STR_4],
                T.[Ship To Cust Street 5]	= S.[STR_5],
                T.[Ship To Cust PO Box]	= S.[PO_BOX],
                T.[Ship To Cust PO Box Postal Code]	= S.[PO_BOX_POSTAL_CD],
                T.[Ship To Cust PO Box City]	= S.[PO_BOX_CITY],
                T.[Ship To Cust Region For PO Box]	= S.[REGN_FOR_PO_BOX],
                T.[Ship To Cust PO Box Country]	= S.[PO_BOX_CNTRY],
                T.[Ship To Cust Transport Zone]	= S.[TRNSPRT_ZONE],
                T.[Ship To Cust Address Notes]	= S.[ADDR_NOTES],
                T.[Ship To Cust Tax Number 3 Code]	= S.[TAX_NUM_3],
                T.[Ship To Cust Tax Number 5 Code]	= S.[TAX_NUM_5],
                T.[Ship To Cust Industry Code 3]	= S.[INDUS_CD_3],
                T.[Ship To Cust Industry Code 3 Description]	= S.[INDUS_CD_3_DESC],
                T.[Ship To Cust Industry Code 4]	= S.[INDUS_CD_4],
                T.[Ship To Cust Industry Code 4 Description]	= S.[INDUS_CD_4_DESC],
                T.[Ship To Cust Industry Code 5]	= S.[INDUS_CD_5],
                T.[Ship To Cust Industry Code 5 Description]	= S.[INDUS_CD_5_DESC],
                T.[Ship To Cust Central Order Block For Customer]	= S.[CENTRAL_ORDER_BLK_FOR_CUST],
                T.[Ship To Cust Payment Block]	= S.[PYMT_BLK]

    FROM [GLOBAL_EDW].[Propelis].[SHIP_TO_CUST] AS T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CUSTOMR_CUR_D] AS S
        ON T.[CUST_KEY] = S.[CUST_KEY];

    -- Step 2: Insert new records from mirror to target table
    INSERT INTO [GLOBAL_EDW].[Propelis].[SHIP_TO_CUST] (
                 [CUST_KEY],
                 [Ship To Customer ID],
                 [Ship To Legacy Customer ID],
                 [Ship To Customer Name],
                 [Ship To Cust Line 2 Description],
                 [Ship To Cust Country Code],
                 [Ship To Cust Plant ID],
                 [Ship To Cust Segment ID],
                 [Ship To Cust Industry],
                 [Ship To Cust Vendor ID],
                 [Ship To Cust Group Code],
                 [Ship To Cust Account Group Code],
                 [Ship To Cust Title],
                 [Ship To Cust Search Term],
                 [Ship To Cust Street],
                 [Ship To Cust City],
                 [Ship To Cust Zip Code],
                 [Ship To Cust State Code],
                 [Ship To Cust Region Code],
                 [Ship To Cust Telephone Number 1],
                 [Ship To Cust Telephone Number 2],
                 [Ship To Cust Fax Number Code],
                 [Ship To Cust Tax Number 1 Code],
                 [Ship To Cust Tax Number 2 Code],
                 [Ship To Cust VAT Number Code],
                 [Ship To Cust Credit Limit],
                 [Ship To Cust Bonus Rate],
                 [Ship To Cust Express Station],
                 [Ship To Cust Transportation Zone],
                 [Ship To Cust Printer Location Characteristics],
                 [Ship To Cust Printer Region Characteristics],
                 [Ship To Cust Printer Site Characteristics],
                 [Ship To Cust Created Date],
                 [Ship To Cust Created Usser ID],
                 [Ship To Cust Updated Date],
                 [Ship To Cust Updated User ID],
                 [Ship To Cust Payment Terms Code],
                 [Ship To Cust Sales Distribution],
                 [Ship To Cust Order Block For Sales Area],
                 [Ship To Cust Delivery Block For Sales Area],
                 [ETL_SRC_SYS_CD],
                 [ETL_EFFECTV_BEGIN_DATE],
                 [ETL_EFFECTV_END_DATE],
                 [ETL_CURR_RCD_IND],
                 [ETL_CREATED_TS],
                 [ETL_UPDTD_TS],
                 [Ship To Cust Corporate Group],
                 [Ship To Cust Customer Classification],
                 [Ship To Customer Customer Classification Description],
                 [Ship To Cust Printer Location],
                 [Ship To Cust Printer Site],
                 [Ship To Cust Printer Region],
                 [Ship To Cust Specific Field Label 01],
                 [Ship To Cust Specific Field Label 02],
                 [Ship To Cust Specific Field Label 03],
                 [Ship To Cust Specific Field Label 04],
                 [Ship To Cust Specific Field Label 05],
                 [Ship To Cust Specific Field Label 06],
                 [Ship To Cust Specific Field Label 07],
                 [Ship To Cust Specific Field Label 08],
                 [Ship To Cust Specific Field Label 09],
                 [Ship To Cust Specific Field Label 10],
                 [Ship To Cust Specific Field Label 11],
                 [Ship To Cust Specific Field Label 12],
                 [Ship To Cust Specific Field Label 13],
                 [Ship To Cust Specific Field Label 14],
                 [Ship To Cust Specific Field Label 15],
                 [Ship To Cust Specific Field Label 16],
                 [Ship To Cust Specific Field Label 17],
                 [Ship To Cust Specific Field Label 18],
                 [Ship To Cust Specific Field Label 19],
                 [Ship To Cust Specific Field Label 20],
                 [Ship To Cust Condition Group 1],
                 [Ship To Cust Industry Code 1],
                 [Ship To Cust Industry Code 2],
                 [Ship To Cust Industry Description],
                 [Ship To Cust Industry Code 1 Description],
                 [Ship To Cust Industry Code 2 Description],
                 [Ship To Cust Assignment to Hierarchy],
                 [Ship To Cust Account Group Description],
                 [Ship To Cust Region Description],
                 [Ship To Cust Country Description],
                 [Ship To Cust Transportation Zone Description],
                 [Ship To Cust Plant Description],
                 [Ship To Cust Condition Group Description],
                 [Ship To Cust Cental Billing Block],
                 [Ship To Cust Cental Billing Block Description],
                 [Ship To Cust Central Delivery Block],
                 [Ship To Cust Central Delivery Block Description],
                 [Ship To Cust Deletion Indicator],
                 [Ship To Cust Central Posting Block],
                 [Ship To Cust Tax Jurisdiction],
                 [Ship To Cust Central Sales Block],
                 [Ship To Cust Central Deletion Indicator],
                 [Ship To Cust Language Key],
                 [Ship To Cust Trading Partner],
                 [Ship To Cust Trading Partner Description],
                 [Ship To Cust Annual Sales],
                 [Ship To Cust Annual Sales Year],
                 [Ship To Cust Sales Currency],
                 [Ship To Cust Sales Currency Description],
                 [Ship To Cust One Time Account Group],
                 [Ship To Cust One Time Account Group Description],
                 [Ship To Cust One Time Indicator],
                 [Ship To Cust Industry Type],
                 [Ship To Cust Business Type],
                 [Ship To Cust DUNS Number],
                 [Ship To Cust DUNS Plus 4],
                 [Ship To City Coordinates],
                 [Ship To Cust Tax Number 4 Code],
                 [Ship To Cust Attribute 3],
                 [Ship To Cust Attribute 3 Description],
                 [Ship To Cust E-Mail Address],
                 [Ship To Cust Mobile Number],
                 [Ship To Cust Search Term 2],
                 [Ship To Cust Street 2],
                 [Ship To Cust Street 3],
                 [Ship To Cust Street 4],
                 [Ship To Cust Street 5],
                 [Ship To Cust PO Box],
                 [Ship To Cust PO Box Postal Code],
                 [Ship To Cust PO Box City],
                 [Ship To Cust Region For PO Box],
                 [Ship To Cust PO Box Country],
                 [Ship To Cust Transport Zone],
                 [Ship To Cust Address Notes],
                 [Ship To Cust Tax Number 3 Code],
                 [Ship To Cust Tax Number 5 Code],
                 [Ship To Cust Industry Code 3],
                 [Ship To Cust Industry Code 3 Description],
                 [Ship To Cust Industry Code 4],
                 [Ship To Cust Industry Code 4 Description],
                 [Ship To Cust Industry Code 5],
                 [Ship To Cust Industry Code 5 Description],
                 [Ship To Cust Central Order Block For Customer],
                 [Ship To Cust Payment Block]

    )
    SELECT
         S.[CUST_KEY],
         S.[CUST_ID],
         S.[LGCY_CUST_ID],
         S.[CUST_NAME],
         S.[CUST_LINE_2_DESC],
         S.[CNTRY_CD],
         S.[PLNT_ID],
         S.[SEG_ID],
         S.[INDUS],
         S.[VNDR_ID],
         S.[CUST_GROUP_CD],
         S.[CUST_ACCT_GROUP_CD],
         S.[TITLE],
         S.[SEARCH_TERM],
         S.[STR],
         S.[CITY_NAME],
         S.[ZIP_CD],
         S.[ST_CD],
         S.[REGN_CD],
         S.[TEL_NUM_1_CD],
         S.[TEL_NUM_2_CD],
         S.[FAX_NUM_CD],
         S.[TAX_NUM_1_CD],
         S.[TAX_NUM_2_CD],
         S.[VAT_NUM_CD],
         S.[CREDIT_LMT],
         S.[BONUS_RT],
         S.[EXPRESS_STATION],
         S.[TRANSTN_ZONE],
         S.[PRINTER_LOC_CHARS],
         S.[PRINTER_REGN_CHARS],
         S.[PRINTER_SITE_CHARS],
         S.[CREATED_DATE],
         S.[CREATED_USR_ID],
         S.[UPDTD_DATE],
         S.[UPDTD_USR_ID],
         S.[PYMT_TRMS_CD],
         S.[SALES_DISTR],
         S.[ORDER_BLK_FOR_SALES_AREA],
         S.[DLVRY_BLK_FOR_SALES_AREA],
         S.[ETL_SRC_SYS_CD],
         S.[ETL_EFFECTV_BEGIN_DATE],
         S.[ETL_EFFECTV_END_DATE],
         S.[ETL_CURR_RCD_IND],
         S.[ETL_CREATED_TS],
         S.[ETL_UPDTD_TS],
         S.[CORPORATE_GROUP],
         S.[CUST_CLSFTN],
         S.[CUST_CLSFTN_DESC],
         S.[PRINTER_LOC],
         S.[PRINTER_SITE],
         S.[PRINTER_REGN],
         S.[CUST_SPECIFIC_FLD_LBL_01],
         S.[CUST_SPECIFIC_FLD_LBL_02],
         S.[CUST_SPECIFIC_FLD_LBL_03],
         S.[CUST_SPECIFIC_FLD_LBL_04],
         S.[CUST_SPECIFIC_FLD_LBL_05],
         S.[CUST_SPECIFIC_FLD_LBL_06],
         S.[CUST_SPECIFIC_FLD_LBL_07],
         S.[CUST_SPECIFIC_FLD_LBL_08],
         S.[CUST_SPECIFIC_FLD_LBL_09],
         S.[CUST_SPECIFIC_FLD_LBL_10],
         S.[CUST_SPECIFIC_FLD_LBL_11],
         S.[CUST_SPECIFIC_FLD_LBL_12],
         S.[CUST_SPECIFIC_FLD_LBL_13],
         S.[CUST_SPECIFIC_FLD_LBL_14],
         S.[CUST_SPECIFIC_FLD_LBL_15],
         S.[CUST_SPECIFIC_FLD_LBL_16],
         S.[CUST_SPECIFIC_FLD_LBL_17],
         S.[CUST_SPECIFIC_FLD_LBL_18],
         S.[CUST_SPECIFIC_FLD_LBL_19],
         S.[CUST_SPECIFIC_FLD_LBL_20],
         S.[CUST_COND_GROUP_1],
         S.[INDUS_CD_1],
         S.[INDUS_CD_2],
         S.[INDUS_DESC],
         S.[INDUS_CD_1_DESC],
         S.[INDUS_CD_2_DESC],
         S.[ASSIGN_TO_HIERCHY],
         S.[CUST_ACCT_GROUP_DESC],
         S.[REGN_DESC],
         S.[CNTRY_DESC],
         S.[TRANSTN_ZONE_DESC],
         S.[PLNT_DESC],
         S.[CUST_COND_GROUP_DESC],
         S.[CENTRAL_BILLING_BLK],
         S.[CENTRAL_BILLING_BLK_DESC],
         S.[CENTRAL_DLVRY_BLK],
         S.[CENTRAL_DLVRY_BLK_DESC],
         S.[DELETION_IND],
         S.[CENTRAL_PSTNG_BLK],
         S.[TAX_JRSDCTN],
         S.[CENTRAL_SALES_BLK],
         S.[CENTRAL_DELETION_IND],
         S.[LANG_KEY],
         S.[TRADING_PRTNR],
         S.[TRADING_PRTNR_DESC],
         S.[ANNUAL_SALES],
         S.[ANNUAL_SALES_YR],
         S.[SALES_CRNCY],
         S.[SALES_CRNCY_DESC],
         S.[ONE_TM_CUST_ACCT_GROUP],
         S.[ONE_TM_CUST_ACCT_GROUP_DESC],
         S.[ONE_TM_CUST_IND],
         S.[INDUS_TYP],
         S.[BIZ_TYP],
         S.[DUNS_NUM],
         S.[DUNS_PLUS_4],
         S.[CITY_COORDINATES],
         S.[TAX_NUM_4_CD],
         S.[ATTRIB_3],
         S.[ATTRIB_3_DESC],
         S.[E_MAIL_ADDR],
         S.[MOBILE_NUM],
         S.[SEARCH_TERM_2],
         S.[STR_2],
         S.[STR_3],
         S.[STR_4],
         S.[STR_5],
         S.[PO_BOX],
         S.[PO_BOX_POSTAL_CD],
         S.[PO_BOX_CITY],
         S.[REGN_FOR_PO_BOX],
         S.[PO_BOX_CNTRY],
         S.[TRNSPRT_ZONE],
         S.[ADDR_NOTES],
         S.[TAX_NUM_3],
         S.[TAX_NUM_5],
         S.[INDUS_CD_3],
         S.[INDUS_CD_3_DESC],
         S.[INDUS_CD_4],
         S.[INDUS_CD_4_DESC],
         S.[INDUS_CD_5],
         S.[INDUS_CD_5_DESC],
         S.[CENTRAL_ORDER_BLK_FOR_CUST],
         S.[PYMT_BLK]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CUSTOMR_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[SHIP_TO_CUST] AS T
        ON T.[CUST_KEY] = S.[CUST_KEY]
    WHERE T.[CUST_KEY] IS NULL;

END