CREATE   PROCEDURE [Propelis].[Proc_LOADING_DATE] 
AS
BEGIN  
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Loading Date] = S.[THE_DATE],
        T.[Loading Fiscal Year] = S.[FISCAL_YR],
        T.[Loading Fiscal Period] = S.[FISCAL_PER_NUM],
        T.[Loading Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Loading Fiscal Quarter] = S.[FISCAL_QTR_NUM],
        T.[Loading Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Loading Calendar Year] = S.[CLNDR_YR],
        T.[Loading Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Loading Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Loading Calendar Month Desc] = S.[CLNDR_MNTH_DESC],
        T.[Loading Calendar Quarter] = S.[CLNDR_QTR_NUM],
        T.[Loading Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Loading Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Loading Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Loading Calendar Day in Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Loading Calendar Day in Year] = S.[CLNDR_DAY_IN_YR],
        T.[Loading Calendar Week] = S.[CLNDR_WK],
        T.[Loading Calendar Month in Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Loading Calendar Days in Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Loading Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Loading Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Loading Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Loading Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Loading Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Loading Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Loading Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Loading Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Loading Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Loading Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Loading Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Loading Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Loading Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Loading Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Loading Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Loading Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Loading Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Loading Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Loading Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Loading Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Loading Day Fiscal Week] = S.[FISCAL_WK],
        T.[Loading Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Loading Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Loading Day Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Loading Day Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Loading Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Loading Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Loading Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Loading Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Loading Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Loading Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Loading Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[LOADING_DATE] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];
 
    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[LOADING_DATE] (
        [DATE_KEY],
        [Loading Date],
        [Loading Fiscal Year],
        [Loading Fiscal Period],
        [Loading Fiscal Period Code],
        [Loading Fiscal Quarter],
        [Loading Fiscal Quarter Code],
        [Loading Calendar Year],
        [Loading Calendar Month Number],
        [Loading Calendar Month Code],
        [Loading Calendar Month Desc],
        [Loading Calendar Quarter],
        [Loading Calendar Quarter Code],
        [Loading Calendar Weekday Number],
        [Loading Calendar Weekday Name],
        [Loading Calendar Day in Month],
        [Loading Calendar Day in Year],
        [Loading Calendar Week],
        [Loading Calendar Month in Quarter Number],
        [Loading Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Loading Current Day Flag],
        [Loading Current Day Minus 1 Flag],
        [Loading Current Calendar Week Flag],
        [Loading Current Calendar Week Minus 1 Flag],
        [Loading Current Month Flag],
        [Loading Current Month Minus 1 Flag],
        [Loading Current Month Minus 12 Flag],
        [Loading Current Quarter Flag],
        [Loading Current Quarter Minus 1 Flag],
        [Loading Current Quarter Minus 4 Flag],
        [Loading Current Calendar Year Flag],
        [Loading Current Calendar Year Minus 1 Flag],
        [Loading Current Calendar Year Minus 2 Flag],
        [Loading Current Fiscal Year Flag],
        [Loading Current Fiscal Year Minus 1 Flag],
        [Loading Current Fiscal Year Minus 2 Flag],
        [Loading Current Calendar Year Plus 1 Flag],
        [Loading Current Fiscal Year Plus 1 Flag],
        [Loading Day In Fiscal Year],
        [Loading Date Is Weekday],
        [Loading Day Fiscal Week],
        [Loading Current Fiscal Week Flag],
        [Loading Current Fiscal Week Minus 1 Flag],
        [Loading Day Fiscal Weekday Number],
        [Loading Day Fiscal Weekday Name],
        [Loading Current Month Minus 2 Flag],
        [Loading Current Fiscal Week Minus 2 Flag],
        [Loading Current Fiscal Week Minus 6 Flag],
        [Loading Current Fiscal Week Minus 3 Flag],
        [Loading Current Fiscal Week Minus 4 Flag],
        [Loading Current Fiscal Week Minus 5 Flag],
        [Loading Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[LOADING_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
END