CREATE   PROCEDURE [Propelis].[Proc_START_DATE]
AS
BEGIN  
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Start Date] = S.[THE_DATE],
        T.[Start Fiscal Year] = S.[FISCAL_YR],
        T.[Start Fiscal Period Number] = S.[FISCAL_PER_NUM],
        T.[Start Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Start Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Start Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Start Calendar Year] = S.[CLNDR_YR],
        T.[Start Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Start Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Start Calendar Month Description] = S.[CLNDR_MNTH_DESC],
        T.[Start Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[Start Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Start Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Start Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Start Calendar Day In Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Start Calendar Day In Year] = S.[CLNDR_DAY_IN_YR],
        T.[Start Calendar Week] = S.[CLNDR_WK],
        T.[Start Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Start Calendar Days In Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Start Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Start Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Start Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Start Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Start Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Start Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Start Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Start Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Start Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Start Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Start Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Start Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Start Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Start Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Start Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Start Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Start Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Start Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Start Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Start Is Weekday] = S.[IS_WEEKDAY],
        T.[Start Fiscal Week] = S.[FISCAL_WK],
        T.[Start Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Start Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Start Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Start Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Start Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Start Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Start Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Start Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Start Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Start Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Start Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[START_DATE] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];

    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[START_DATE] (
        [DATE_KEY],
        [Start Date],
        [Start Fiscal Year],
        [Start Fiscal Period Number],
        [Start Fiscal Period Code],
        [Start Fiscal Quarter Number],
        [Start Fiscal Quarter Code],
        [Start Calendar Year],
        [Start Calendar Month Number],
        [Start Calendar Month Code],
        [Start Calendar Month Description],
        [Start Calendar Quarter Number],
        [Start Calendar Quarter Code],
        [Start Calendar Weekday Number],
        [Start Calendar Weekday Name],
        [Start Calendar Day In Month],
        [Start Calendar Day In Year],
        [Start Calendar Week],
        [Start Calendar Month In Quarter Number],
        [Start Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Start Current Day Flag],
        [Start Current Day Minus 1 Flag],
        [Start Current Calendar Week Flag],
        [Start Current Calendar Week Minus 1 Flag],
        [Start Current Month Flag],
        [Start Current Month Minus 1 Flag],
        [Start Current Month Minus 12 Flag],
        [Start Current Quarter Flag],
        [Start Current Quarter Minus 1 Flag],
        [Start Current Quarter Minus 4 Flag],
        [Start Current Calendar Year Flag],
        [Start Current Calendar Year Minus 1 Flag],
        [Start Current Calendar Year Minus 2 Flag],
        [Start Current Fiscal Year Flag],
        [Start Current Fiscal Year Minus 1 Flag],
        [Start Current Fiscal Year Minus 2 Flag],
        [Start Current Calendar Year Plus 1 Flag],
        [Start Current Fiscal Year Plus 1 Flag],
        [Start Day In Fiscal Year],
        [Start Is Weekday],
        [Start Fiscal Week],
        [Start Current Fiscal Week Flag],
        [Start Current Fiscal Week Minus 1 Flag],
        [Start Fiscal Weekday Number],
        [Start Fiscal Weekday Name],
        [Start Current Month Minus 2 Flag],
        [Start Current Fiscal Week Minus 2 Flag],
        [Start Current Fiscal Week Minus 6 Flag],
        [Start Current Fiscal Week Minus 3 Flag],
        [Start Current Fiscal Week Minus 4 Flag],
        [Start Current Fiscal Week Minus 5 Flag],
        [Start Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[START_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
END