CREATE     PROCEDURE [Propelis].[Proc_EDW_T_FACT_SAL_INVITEM_CUR_D]
AS
BEGIN

    -- Step 1: Clear existing data from the target table
	
	TRUNCATE TABLE [GLOBAL_EDW].[Propelis].[EDW_T_FACT_SAL_INVITEM_CUR_D];
	
	-- Step 2: Insert refreshed data from mirror table with joins
	
    INSERT INTO [GLOBAL_EDW].[Propelis].[EDW_T_FACT_SAL_INVITEM_CUR_D](
        [INVC_KEY],
        [Invoice ID],
        [Invoice Item ID],
        [CMPNY_KEY],
        [INVC_DATE_KEY],
        [PLNT_KEY],
        [SOLDTO_CUST_KEY],
        [BILLTO_CUST_KEY],
        [PAYER_CUST_KEY],
        [SHIPTO_CUST_KEY],
        [BRANDOWNER_CUST_KEY],
        [CUST_CONTACT_KEY],
        [SALES_PERSON_PERSONEL_KEY],
        [PERSON_RESPNSBLE_PERSONEL_KEY],
        [MATRL_KEY],
        [SEG_KEY],
        [CUST_CMPNY_KEY],
        [CUST_SALES_AREA_KEY],
        [SALES_ORDER_KEY],
        [SALES_ORDER_ID],
        [SALES_ORDER_ITM_ID],
        [DOCMT_CRNCY_KEY],
        [CMPNY_CRNCY_KEY],
        [GROUP_CRNCY_KEY],
        [Invoice Payment Required Date],
        [DOCMT_CRNCY_INVC_AMT],
        [CMPNY_CRNCY_INVC_AMT],
        [GROUP_CRNCY_INVC_AMT],
        [INVOICED_QTY],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [PRDT_VARIANT_CONFIG_KEY],
        [PROFT_CNTR_KEY],
        [CYLINDER_OWNER_CUST_KEY],
        [PARNT_CUST_KEY],
        [Sales UoM],
        [Short Text For Sales Order Item],
        [SUBTOTAL_4_PRICING_COND],
        [DOCMT_CRNCY_TAX_AMT],
        [AGENCY_CUST_KEY],
        [PRINTER_CUST_KEY],
        [SUPLR_CUST_KEY],
        [Sales Document Item Category],
        [Usage Indicator],
        [SUBTOTAL_2_PRICING_COND],
        [SUBTOTAL_5_PRICING_COND],
        [Reference Document],
        [Reference Document Item],
        [Usage Indicator Description],
        [SPCL_STK_PRTNR_KEY],
        [CUST_HIERCHY_1_KEY],
        [Originating Document],
        [Originating Item],
        [PARNT_INVC_KEY],
        [Parent Invoice Item ID],
        [CREATED_DATE_KEY],
        [SUBTOTAL_1_PRICING_COND],
        [SUBTOTAL_3_PRICING_COND],
        [SUBTOTAL_6_PRICING_COND],
        [RBTE_BASIS_1],
        [ITM_CREDIT_PRICE],
	    
		--Below columns are added for the Alias tables
	    
	    [OPERATING_PLANT_REGION_PLANT],
	    [SALES_ORDER_CREATION_DATE_DATE_KEY],
	    [CUSTOMR_CUST_ID],
	    [PROFCHZ_PROFT_CNTR_KEY],
	    [PROFCVZ_PROFT_CNTR_KEY],
	    [PRDVCON_KEY]	
	
    )
	SELECT 
        FACT.[INVC_KEY],
        FACT.[INVC_ID],
        FACT.[INVC_ITM_ID],
        FACT.[CMPNY_KEY],
        FACT.[INVC_DATE_KEY],
        FACT.[PLNT_KEY],
        FACT.[SOLDTO_CUST_KEY],
        FACT.[BILLTO_CUST_KEY],
        FACT.[PAYER_CUST_KEY],
        FACT.[SHIPTO_CUST_KEY],
        FACT.[BRANDOWNER_CUST_KEY],
        FACT.[CUST_CONTACT_KEY],
        FACT.[SALES_PERSON_PERSONEL_KEY],
        FACT.[PERSON_RESPNSBLE_PERSONEL_KEY],
        FACT.[MATRL_KEY],
        FACT.[SEG_KEY],
        FACT.[CUST_CMPNY_KEY],
        FACT.[CUST_SALES_AREA_KEY],
        FACT.[SALES_ORDER_KEY],
        FACT.[SALES_ORDER_ID],
        FACT.[SALES_ORDER_ITM_ID],
        FACT.[DOCMT_CRNCY_KEY],
        FACT.[CMPNY_CRNCY_KEY],
        FACT.[GROUP_CRNCY_KEY],
        FACT.[INVC_PYMT_REQUIRED_DATE],
        FACT.[DOCMT_CRNCY_INVC_AMT],
        FACT.[CMPNY_CRNCY_INVC_AMT],
        FACT.[GROUP_CRNCY_INVC_AMT],
        FACT.[INVOICED_QTY],
        FACT.[ETL_SRC_SYS_CD],
        FACT.[ETL_CREATED_TS],
        FACT.[ETL_UPDTD_TS],
        FACT.[PRDT_VARIANT_CONFIG_KEY],
        FACT.[PROFT_CNTR_KEY],
        FACT.[CYLINDER_OWNER_CUST_KEY],
        FACT.[PARNT_CUST_KEY],
        FACT.[SALES_UOM],
        FACT.[SHORT_TEXT_FOR_SALES_ORDER_ITM],
        FACT.[SUBTOTAL_4_PRICING_COND],
        FACT.[DOCMT_CRNCY_TAX_AMT],
        FACT.[AGENCY_CUST_KEY],
        FACT.[PRINTER_CUST_KEY],
        FACT.[SUPLR_CUST_KEY],
        FACT.[SALES_DOCMT_ITM_CTGRY],
        FACT.[USAGE_IND],
        FACT.[SUBTOTAL_2_PRICING_COND],
        FACT.[SUBTOTAL_5_PRICING_COND],
        FACT.[REF_DOCMT],
        FACT.[REF_DOCMT_ITM],
        FACT.[USAGE_IND_DESC],
        FACT.[SPCL_STK_PRTNR_KEY],
        FACT.[CUST_HIERCHY_1_KEY],
        FACT.[ORIGINATING_DOCMT],
        FACT.[ORIGINATING_ITM],
        FACT.[PARNT_INVC_KEY],
        FACT.[PARNT_INVC_ITM_ID],
        FACT.[CREATED_DATE_KEY],
        FACT.[SUBTOTAL_1_PRICING_COND],
        FACT.[SUBTOTAL_3_PRICING_COND],
        FACT.[SUBTOTAL_6_PRICING_COND],
        FACT.[RBTE_BASIS_1],
        FACT.[ITM_CREDIT_PRICE],
		
		--Below columns are added for the Alias tables
	    
	    PLANT.[Plant ID] AS OPERATING_PLANT_REGION_PLANT,
	    SALORDH.[Sales Order Created Date] AS SALES_ORDER_CREATION_DATE_DATE_KEY,
	    CUSTCMP.[Customer ID] AS CUSTOMR_CUST_ID,
	    PROFCTR.PROFT_CNTR_KEY AS PROFCHZ_PROFT_CNTR_KEY,
	    PROFCTR.PROFT_CNTR_KEY AS PROFCVZ_PROFT_CNTR_KEY,
	    CONCAT(FACT.SALES_ORDER_ID, '-', FACT.SALES_ORDER_ITM_ID) AS PRDVCON_KEY
	
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_F_SAL_INVITEM_CUR_D] AS FACT
    
    LEFT JOIN [GLOBAL_EDW].[Propelis].[BILL_TO_CUST] AS BI_T_CUST
        ON FACT.BILLTO_CUST_KEY = BI_T_CUST.CUST_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[PAYER_CUST] AS PAY_CUST
        ON FACT.PAYER_CUST_KEY = PAY_CUST.CUST_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[SHIP_TO_CUST] AS SH_T_CUST
        ON FACT.SHIPTO_CUST_KEY = SH_T_CUST.CUST_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[SOLD_TO_CUST] AS SLD_T_CUST
        ON FACT.SOLDTO_CUST_KEY = SLD_T_CUST.CUST_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[DOCUMENT_CURRENCY] AS  DOC_CURNCY
        ON FACT.DOCMT_CRNCY_KEY = 	DOC_CURNCY.CRNCY_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[CYLINDER_OWNER_CUST] AS CY_OWN_CUST
        ON FACT.CYLINDER_OWNER_CUST_KEY = CY_OWN_CUST.CUST_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[PARENT_CUST] AS PAR_CUST
        ON FACT.PARNT_CUST_KEY = PAR_CUST.CUST_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[GROUP_CURRENCY] AS GRP_CURNCY
        ON FACT.GROUP_CRNCY_KEY = GRP_CURNCY.CRNCY_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[AGENCY_CUST] AS AGN_CUST
        ON FACT.AGENCY_CUST_KEY = AGN_CUST.CUST_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[SUPPLIER_CUST] AS SUP_CUST
        ON FACT.SUPLR_CUST_KEY = SUP_CUST.CUST_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[CUST_HIERARCHY1] AS CUST_HIE1
        ON FACT.CUST_HIERCHY_1_KEY = CUST_HIE1.CUST_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[SPECIAL_STOCK_PARTNER] AS SPE_ST_PNTR
        ON FACT.SPCL_STK_PRTNR_KEY = SPE_ST_PNTR.CUST_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[PRINTER_CUST] AS PRI_CUST
        ON FACT.PRINTER_CUST_KEY = PRI_CUST.CUST_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[INVOICE_CREATION_DATE] AS INV_CRT_DT
        ON FACT.CREATED_DATE_KEY = INV_CRT_DT.DATE_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[INVOICE_DATE] AS INV_DT
        ON FACT.INVC_DATE_KEY = INV_DT.DATE_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[INVOICE] AS INV
        ON FACT.INVC_KEY = INV.INVC_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[Propelis].[PARENT_INVOICE] AS PRNT_INV
        ON FACT.PARNT_INVC_KEY = PRNT_INV.INVC_KEY
    
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CMPNYCD_CUR_D] AS CMPNYCD
        ON FACT.CMPNY_KEY = CMPNYCD.CMPNY_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PLANT_CUR_D] AS PLANT
        ON FACT.PLNT_KEY = PLANT.PLNT_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_SALORDH_CUR_D] AS SALORDH
        ON FACT.SALES_ORDER_KEY = SALORDH.SALES_ORDER_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTCNT_CUR_D] AS CUSTCNT
        ON FACT.CUST_CONTACT_KEY = CUSTCNT.CUST_CONTACT_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTSAL_CUR_D] AS CUSTSAL
        ON FACT.CUST_SALES_AREA_KEY = CUSTSAL.CUST_SALES_AREA_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PROFCTR_CUR_D] AS PROFCTR
        ON FACT.PROFT_CNTR_KEY = PROFCTR.PROFT_CNTR_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTCMP_CUR_D] AS CUSTCMP
        ON FACT.CUST_CMPNY_KEY = CUSTCMP.CUST_CMPNY_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_SEGMENT_CUR_D] AS SEGMENT
        ON FACT.SEG_KEY = SEGMENT.SEG_KEY
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_PRDVCON_CUR_D] AS PRDVCON
	    ON CONCAT(FACT.SALES_ORDER_ID, '-', FACT.SALES_ORDER_ITM_ID) = PRDVCON.PRDVCON_KEY
    	
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_MATERIAL_CUR_D] AS MATERIAL
        ON FACT.MATRL_KEY = MATERIAL.MATRL_KEY;
END