CREATE   PROCEDURE [Propelis].[Proc_EDW_T_FACT_PRD_SERVCST_CUR_D]
AS 
BEGIN

    -- Step 1: Clear existing data from the target table
	
	TRUNCATE TABLE [GLOBAL_EDW].[Propelis].[EDW_T_FACT_PRD_SERVCST_CUR_D];
	
	-- Step 2: Insert refreshed data from mirror table with joins
	
	INSERT INTO [GLOBAL_EDW].[Propelis].[EDW_T_FACT_PRD_SERVCST_CUR_D](
	    [SERVC_ORDER_KEY],
        [PRODUCING_PLNT_KEY],
        [Document Number],
        [Period],
        [DOCMT_CRNCY_KEY],
        [CMPNY_CRNCY_KEY],
        [GROUP_CRNCY_KEY],
        [DOCMT_CRNCY_VAL],
        [CMPNY_CRNCY_VAL],
        [GROUP_CRNCY_VAL],
        [QTY_TOTAL],
        [UoM],
        [Fiscal Year],
        [Value Type],
        [COST_ELEMNT_KEY],
        [TRNSCTN_TYP],
        [Partner Object],
        [MATRL_KEY],
        [CMPNY_KEY],
        [PRTNR_CMPNY_KEY],
        [Order Type],
        [Order Category],
        [MAINTENANCE_WRK_CNTR_KEY],
        [Object Class],
        [RESPNSBLE_COST_CNTR_KEY],
        [PROFT_CNTR_KEY],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [LOC_PLNT_KEY],
        [Type Of Cost],
        [PERSONEL_NUM_KEY],
        [FUNCTNL_AREA_KEY],
        [Debit Credit Indicator],
        [Reference Document Number],
        [Controlling Area],
        [PLNT_KEY],
        [PSTNG_DATE_KEY],
        [Value Type Description],
        [Transaction Type Description],
        [Controlling Area Description],
        [Is Internal  Posting],
        [ACTIVITY_TYP_KEY],
        [Posting Row],
        [Is INTER Company Posting],
        [Is INTRA Company Posting],
        [PRTNR_COST_CNTR_KEY],
        [TCHNCL_COMPLETION_DATE_KEY],
        [DOCMT_DATE_KEY],
        [CREATION_DATE_KEY],
        [Posting Creation Date Timestamp],
		
	--Below columns are added for the Alias tables
		
        [PERSONNEL_PLANT_REGION_PLANT],
        [PLANT_REGION_PLANT],
        [LOCATION_PLANT_REGION_PLANT],
        [PRODUCING_PLANT_REGION_PLANT],
        [COSTEHZ_COST_ELEMNT_KEY],
        [COSTEVZ_COST_ELEMNT_KEY],
        [PROFCHZ_PROFT_CNTR_KEY],
        [PROFCVZ_PROFT_CNTR_KEY],
        [WORKCHZ_WRK_CNTR_KEY],
        [WORKCVZ_WRK_CNTR_KEY],
        [Resp_Cost_Center_Horizontal_COST_CNTR_KEY],
        [Resp_Cost_Center_Vertical_COST_CNTR_KEY],
        [Partner_Cost_Center_Horizontal_COST_CNTR_KEY],
        [Partner_Cost_Center_Vertical_COST_CNTR_KEY]
		
		
	--[Service Order Sales Order] COLUMN DETAILS NOT FOUND
	)
	SELECT 
	    FACT.[SERVC_ORDER_KEY],
        FACT.[PRODUCING_PLNT_KEY],
        FACT.[DOCMT_NUM],
        FACT.[PER],
        FACT.[DOCMT_CRNCY_KEY],
        FACT.[CMPNY_CRNCY_KEY],
        FACT.[GROUP_CRNCY_KEY],
        FACT.[DOCMT_CRNCY_VAL],
        FACT.[CMPNY_CRNCY_VAL],
        FACT.[GROUP_CRNCY_VAL],
        FACT.[QTY_TOTAL],
        FACT.[UOM],
        FACT.[FISCAL_YR],
        FACT.[VAL_TYP],
        FACT.[COST_ELEMNT_KEY],
        FACT.[TRNSCTN_TYP],
        FACT.[PRTNR_OBJ],
        FACT.[MATRL_KEY],
        FACT.[CMPNY_KEY],
        FACT.[PRTNR_CMPNY_KEY],
        FACT.[ORDER_TYP],
        FACT.[ORDER_CTGRY],
        FACT.[MAINTENANCE_WRK_CNTR_KEY],
        FACT.[OBJ_CLASS],
        FACT.[RESPNSBLE_COST_CNTR_KEY],
        FACT.[PROFT_CNTR_KEY],
        FACT.[ETL_SRC_SYS_CD],
        FACT.[ETL_CREATED_TS],
        FACT.[ETL_UPDTD_TS],
        FACT.[LOC_PLNT_KEY],
        FACT.[TYP_OF_COST],
        FACT.[PERSONEL_NUM_KEY],
        FACT.[FUNCTNL_AREA_KEY],
        FACT.[DEBIT_CREDIT_IND],
        FACT.[REF_DOCMT_NUM],
        FACT.[CONTROLLING_AREA],
        FACT.[PLNT_KEY],
        FACT.[PSTNG_DATE_KEY],
        FACT.[VAL_TYP_DESC],
        FACT.[TRNSCTN_TYP_DESC],
        FACT.[CONTROLLING_AREA_DESC],
        FACT.[IS_INTERNL_PSTNG],
        FACT.[ACTIVITY_TYP_KEY],
        FACT.[PSTNG_ROW],
        FACT.[IS_INTER_CMPNY_PSTNG],
        FACT.[IS_INTRA_CMPNY_PSTNG],
        FACT.[PRTNR_COST_CNTR_KEY],
        FACT.[TCHNCL_COMPLETION_DATE_KEY],
        FACT.[DOCMT_DATE_KEY],
        FACT.[CREATION_DATE_KEY],
        FACT.[CREATION_DATE_TS],
		
	--Below columns are added for the Alias tables
		
		substring(PSNL_NUM.[Personnel Cost Center ID],4,4) AS PERSONNEL_PLANT_REGION_PLANT,
		PNT.[Plant ID] AS PLANT_REGION_PLANT,
		LOC_PNT.[Location Plant ID] AS LOCATION_PLANT_REGION_PLANT,
		PRDU_PNT.[Producing Plant ID] AS PRODUCING_PLANT_REGION_PLANT,
		COSTELM.COST_ELEMNT_KEY AS COSTEHZ_COST_ELEMNT_KEY,
		COSTELM.COST_ELEMNT_KEY AS COSTEVZ_COST_ELEMNT_KEY,
		PROFCTR.PROFT_CNTR_KEY AS PROFCHZ_PROFT_CNTR_KEY,
		PROFCTR.PROFT_CNTR_KEY AS PROFCVZ_PROFT_CNTR_KEY,
		WORKCTR.WRK_CNTR_KEY AS WORKCHZ_WRK_CNTR_KEY,
		WORKCTR.WRK_CNTR_KEY AS WORKCVZ_WRK_CNTR_KEY,
		RP_CT_CNTR.COST_CNTR_KEY AS Resp_Cost_Center_Horizontal_COST_CNTR_KEY,
		RP_CT_CNTR.COST_CNTR_KEY AS Resp_Cost_Center_Vertical_COST_CNTR_KEY,
		PNTR_CT_CNTR.COST_CNTR_KEY AS Partner_Cost_Center_Horizontal_COST_CNTR_KEY,
		PNTR_CT_CNTR.COST_CNTR_KEY AS Partner_Cost_Center_Vertical_COST_CNTR_KEY
		
	FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_F_PRD_SERVCST_CUR_D] AS FACT
	
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_MATERIAL_CUR_D] AS MATERIAL
	    ON FACT.MATRL_KEY = MATERIAL.MATRL_KEY

    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_PRD_SERVORD_CUR_D] AS SERVORD
	    ON FACT.SERVC_ORDER_KEY = SERVORD.SERVC_ORDER_KEY
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_COSTELM_CUR_D] AS COSTELM
	    ON FACT.COST_ELEMNT_KEY = COSTELM.COST_ELEMNT_KEY
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PROFCTR_CUR_D] AS PROFCTR
	    ON FACT.PROFT_CNTR_KEY = PROFCTR.PROFT_CNTR_KEY
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_FUNCTAR_CUR_D] AS FUNCTAR
	    ON FACT.FUNCTNL_AREA_KEY = FUNCTAR.FUNCTNL_AREA_KEY
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_WORKCTR_CUR_D] AS WORKCTR
	    ON FACT.MAINTENANCE_WRK_CNTR_KEY = WORKCTR.WRK_CNTR_KEY
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D] AS DT
	    ON FACT.PSTNG_DATE_KEY = DT.DATE_KEY
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_ACTTYPE_CUR_D] AS ACTTYPE
	    ON FACT.ACTIVITY_TYP_KEY = ACTTYPE.ACTIVITY_TYP_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[DOCUMENT_CURRENCY] AS DOC_CURNCY
	    ON FACT.DOCMT_CRNCY_KEY = DOC_CURNCY.CRNCY_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[COMPANY_CURRENCY] AS COM_CURNCY
	    ON FACT.CMPNY_CRNCY_KEY = COM_CURNCY.CRNCY_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[GROUP_CURRENCY] AS GRP_CURNCY
	    ON FACT.GROUP_CRNCY_KEY = GRP_CURNCY.CRNCY_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[COMPANY] AS CMP
	    ON FACT.CMPNY_KEY = CMP.CMPNY_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[PARTNER_COMPANY] AS PNTR_CMP
	    ON FACT.PRTNR_CMPNY_KEY = PNTR_CMP.CMPNY_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[PRODUCING_PLANT] AS PRDU_PNT
	    ON FACT.PRODUCING_PLNT_KEY = PRDU_PNT.PLNT_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[RESP_COST_CENTER] AS RP_CT_CNTR
	    ON FACT.RESPNSBLE_COST_CNTR_KEY = RP_CT_CNTR.COST_CNTR_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[LOCATION_PLANT] AS LOC_PNT
	    ON FACT.LOC_PLNT_KEY = LOC_PNT.PLNT_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[PLANT] AS PNT
	    ON FACT.PLNT_KEY = PNT.PLNT_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[PERSONNEL_NUMBER] AS PSNL_NUM
	    ON FACT.PERSONEL_NUM_KEY = PSNL_NUM.PERSONEL_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[PARTNER_COST_CENTER] AS PNTR_CT_CNTR
	    ON FACT.PRTNR_COST_CNTR_KEY = PNTR_CT_CNTR.COST_CNTR_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[TECH_COMPLETION_DATE] AS TE_COM_DT
	    ON FACT.TCHNCL_COMPLETION_DATE_KEY = TE_COM_DT.DATE_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[DOCUMENT_DATE] AS DOC_DT
	    ON FACT.DOCMT_DATE_KEY = DOC_DT.DATE_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[CREATION_DATE] AS CRT_DT
	    ON FACT.CREATION_DATE_KEY = CRT_DT.DATE_KEY;
END