CREATE     PROCEDURE [Propelis].[Proc_PERSON_RESPNSBLE_COST_CNTR]
AS
BEGIN
    ------------------------------------------------------------------
    -- Step 1: Update existing records
    ------------------------------------------------------------------
    UPDATE T
    SET
        T.[Person Resp Cost Center ID]                     = S.[COST_CNTR_ID],
        T.[Person Resp CC Controlling Area ID]             = S.[CONTROLLING_AREA_ID],
        T.[Person Resp Cost Center Language Type Code]     = S.[LANG_TYP_CD],
        T.[Person Resp Cost Center Category]               = S.[COST_CNTR_CTGRY],
        T.[Person Resp Cost Center Hierarchy Area]         = S.[HIERCHY_AREA],
        T.[Person Resp Cost Center Company Code]           = S.[CMPNY_CD],
        T.[Person Resp Cost Center Plant ID]               = S.[PLNT_ID],
        T.[Person Resp Cost Center Profit Center ID]       = S.[PROFT_CNTR_ID],
        T.[Person Resp Cost Center Currency Code]          = S.[CRNCY_CD],
        T.[Person Resp Cost Center Adress Line 1]          = S.[ADRESS_LINE_1],
        T.[Person Resp Cost Center Line 2]                 = S.[ADRESS_LINE_2],
        T.[Person Resp Cost Center Adress Line 3]          = S.[ADRESS_LINE_3],
        T.[Person Resp Cost Center City Name]              = S.[CITY_NAME],
        T.[Person Resp Cost Center District Name]          = S.[DISTR_NAME],
        T.[Person Resp Cost Center Postal Code]            = S.[POSTAL_CD],
        T.[Person Resp Cost Center Country Code]           = S.[CNTRY_CD],
        T.[Person Resp Cost Center Region Code]            = S.[REGN_CD],
        T.[Person Resp Cost Center Person Responsible]     = S.[PERSON_RESPNSBLE],
        T.[Person Resp Cost Center Flag Actual Revenues]   = S.[FLG_ACTUAL_REVENUES],
        T.[ETL_SRC_SYS_CD]                                 = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE]                         = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE]                           = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND]                               = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS]                                 = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS]                                   = S.[ETL_UPDTD_TS],
        T.[COST_CNTR_NAME]                                 = S.[COST_CNTR_NAME],
        T.[Person Resp CC Actual Primary Postings Lock Indicator] = S.[ACTUAL_PRIMARY_POSTINGS_LOCK_IN],
        T.[Person Resp CC Plan Primary Costs Lock Indicator]       = S.[PLAN_PRIMARY_COSTS_LOCK_IND],
        T.[Person Resp Cost Center Business Area]                = S.[BIZ_AREA],
        T.[Person Resp CC Planning Revenues Lock Indicator]       = S.[PLNG_REVENUES_LOCK_IND],
        T.[Person Resp Cost Center PO Box]                       = S.[PO_BOX],
        T.[Person Resp Cost Center Street]                       = S.[STR],
        T.[Person Resp Cost Center User Respnsble]               = S.[USR_RESPNSBLE],
        T.[Person Resp Cost Center Short Description]            = S.[COST_CNTR_SHORT_DESC],
        T.[Person Resp CC Controlling Area Description]          = S.[CONTROLLING_AREA_DESC],
        T.[Person Resp Cost Center Category Description]         = S.[COST_CNTR_CTGRY_DESC],
        T.[Person Resp Cost Center Company Description]          = S.[CMPNY_DESC],
        T.[Person Resp Cost Center Currency Description]         = S.[CRNCY_DESC],
        T.[Person Resp Cost Center Country Description]          = S.[CNTRY_DESC],
        T.[Person Resp Cost Center Business Area Description]    = S.[BIZ_AREA_DESC],
        T.[Person Resp CC Actual Secondary Cost Lock Indicator]  = S.[ACTUAL_SECONDARY_COST_LOCK_IND],
        T.[Person Resp CC Plan Secondary Cost Lock Indicator]    = S.[PLAN_SECONDARY_COST_LOCK_IND],
        T.[Person Resp Cost Center Functional Area]              = S.[FUNCTNL_AREA],
        T.[Person Resp Cost Center Functional Area Description]  = S.[FUNCTNL_AREA_DESC],
        T.[Person Resp Cost Center Tax Jurisdiction]             = S.[TAX_JRSDCTN],
        T.[Person Resp Cost Center Function]                     = S.[FUNCTION_OF_COST_CNTR],
        T.[Person Resp Cost Center Plant Description]            = S.[PLNT_DESC],
        T.[Person Resp Cost Center Created On]                   = S.[CREATED_ON],
        T.[Person Resp Cost Center Long Description]             = S.[COST_CNTR_LONG_DESC],
        T.[VALID_TO_DATE]                                        = S.[VALID_TO_DATE],
        T.[VALID_FROM_DATE]                                      = S.[VALID_FROM_DATE]
    FROM [GLOBAL_EDW].[Propelis].[PERSON_RESPNSBLE_COST_CNTR] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_COSCNTR_CUR_D] S
        ON T.[COST_CNTR_KEY] = S.[COST_CNTR_KEY];

    ------------------------------------------------------------------
    -- Step 2: Insert new records
    ------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[PERSON_RESPNSBLE_COST_CNTR]
    (
        [COST_CNTR_KEY],
        [Person Resp Cost Center ID],
        [Person Resp CC Controlling Area ID],
        [Person Resp Cost Center Language Type Code],
        [Person Resp Cost Center Category],
        [Person Resp Cost Center Hierarchy Area],
        [Person Resp Cost Center Company Code],
        [Person Resp Cost Center Plant ID],
        [Person Resp Cost Center Profit Center ID],
        [Person Resp Cost Center Currency Code],
        [Person Resp Cost Center Adress Line 1],
        [Person Resp Cost Center Line 2],
        [Person Resp Cost Center Adress Line 3],
        [Person Resp Cost Center City Name],
        [Person Resp Cost Center District Name],
        [Person Resp Cost Center Postal Code],
        [Person Resp Cost Center Country Code],
        [Person Resp Cost Center Region Code],
        [Person Resp Cost Center Person Responsible],
        [Person Resp Cost Center Flag Actual Revenues],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [COST_CNTR_NAME],
        [Person Resp CC Actual Primary Postings Lock Indicator],
        [Person Resp CC Plan Primary Costs Lock Indicator],
        [Person Resp Cost Center Business Area],
        [Person Resp CC Planning Revenues Lock Indicator],
        [Person Resp Cost Center PO Box],
        [Person Resp Cost Center Street],
        [Person Resp Cost Center User Respnsble],
        [Person Resp Cost Center Short Description],
        [Person Resp CC Controlling Area Description],
        [Person Resp Cost Center Category Description],
        [Person Resp Cost Center Company Description],
        [Person Resp Cost Center Currency Description],
        [Person Resp Cost Center Country Description],
        [Person Resp Cost Center Business Area Description],
        [Person Resp CC Actual Secondary Cost Lock Indicator],
        [Person Resp CC Plan Secondary Cost Lock Indicator],
        [Person Resp Cost Center Functional Area],
        [Person Resp Cost Center Functional Area Description],
        [Person Resp Cost Center Tax Jurisdiction],
        [Person Resp Cost Center Function],
        [Person Resp Cost Center Plant Description],
        [Person Resp Cost Center Created On],
        [Person Resp Cost Center Long Description],
        [VALID_TO_DATE],
        [VALID_FROM_DATE]
    )
    SELECT
        S.[COST_CNTR_KEY],
        S.[COST_CNTR_ID],
        S.[CONTROLLING_AREA_ID],
        S.[LANG_TYP_CD],
        S.[COST_CNTR_CTGRY],
        S.[HIERCHY_AREA],
        S.[CMPNY_CD],
        S.[PLNT_ID],
        S.[PROFT_CNTR_ID],
        S.[CRNCY_CD],
        S.[ADRESS_LINE_1],
        S.[ADRESS_LINE_2],
        S.[ADRESS_LINE_3],
        S.[CITY_NAME],
        S.[DISTR_NAME],
        S.[POSTAL_CD],
        S.[CNTRY_CD],
        S.[REGN_CD],
        S.[PERSON_RESPNSBLE],
        S.[FLG_ACTUAL_REVENUES],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[COST_CNTR_NAME],
        S.[ACTUAL_PRIMARY_POSTINGS_LOCK_IN],
        S.[PLAN_PRIMARY_COSTS_LOCK_IND],
        S.[BIZ_AREA],
        S.[PLNG_REVENUES_LOCK_IND],
        S.[PO_BOX],
        S.[STR],
        S.[USR_RESPNSBLE],
        S.[COST_CNTR_SHORT_DESC],
        S.[CONTROLLING_AREA_DESC],
        S.[COST_CNTR_CTGRY_DESC],
        S.[CMPNY_DESC],
        S.[CRNCY_DESC],
        S.[CNTRY_DESC],
        S.[BIZ_AREA_DESC],
        S.[ACTUAL_SECONDARY_COST_LOCK_IND],
        S.[PLAN_SECONDARY_COST_LOCK_IND],
        S.[FUNCTNL_AREA],
        S.[FUNCTNL_AREA_DESC],
        S.[TAX_JRSDCTN],
        S.[FUNCTION_OF_COST_CNTR],
        S.[PLNT_DESC],
        S.[CREATED_ON],
        S.[COST_CNTR_LONG_DESC],
        S.[VALID_TO_DATE],
        S.[VALID_FROM_DATE]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_COSCNTR_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[PERSON_RESPNSBLE_COST_CNTR] T
        ON T.[COST_CNTR_KEY] = S.[COST_CNTR_KEY]
    WHERE T.[COST_CNTR_KEY] IS NULL;
END