CREATE   PROCEDURE [Propelis].[Proc_CREATED_ON_DATE]
AS
BEGIN  
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Created On Date] = S.[THE_DATE],
        T.[Created On Fiscal Year] = S.[FISCAL_YR],
        T.[Created On Fiscal Period Number] = S.[FISCAL_PER_NUM],
        T.[Created On Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Created On Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Created On Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Created On Calendar Year] = S.[CLNDR_YR],
        T.[Created On Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Created On Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Created On Calendar Month Description] = S.[CLNDR_MNTH_DESC],
        T.[Created On Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[Created On Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Created On Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Created On Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Created On Calendar Day In Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Created On Calendar Day In Year] = S.[CLNDR_DAY_IN_YR],
        T.[Created On Calendar Week] = S.[CLNDR_WK],
        T.[Created On Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Created On Calendar Days In Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Created On Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Created On Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Created On Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Created On Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Created On Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Created On Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Created On Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Created On Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Created On Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Created On Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Created On Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Created On Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Created On Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Created On Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Created On Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Created On Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Created On Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[CURR_FISCAL_YR_PLUS_1_FLG] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Created On Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Created On Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Created On Fiscal Week] = S.[FISCAL_WK],
        T.[Created On Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Created On Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Created On Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Created On Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Created On Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Created On Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Created On Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Created On Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Created On Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Created On Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Created On Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[CREATED_ON_DATE] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];
 
    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[CREATED_ON_DATE] (
        [DATE_KEY],
        [Created On Date],
        [Created On Fiscal Year],
        [Created On Fiscal Period Number],
        [Created On Fiscal Period Code],
        [Created On Fiscal Quarter Number],
        [Created On Fiscal Quarter Code],
        [Created On Calendar Year],
        [Created On Calendar Month Number],
        [Created On Calendar Month Code],
        [Created On Calendar Month Description],
        [Created On Calendar Quarter Number],
        [Created On Calendar Quarter Code],
        [Created On Calendar Weekday Number],
        [Created On Calendar Weekday Name],
        [Created On Calendar Day In Month],
        [Created On Calendar Day In Year],
        [Created On Calendar Week],
        [Created On Calendar Month In Quarter Number],
        [Created On Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Created On Current Day Flag],
        [Created On Current Day Minus 1 Flag],
        [Created On Current Calendar Week Flag],
        [Created On Current Calendar Week Minus 1 Flag],
        [Created On Current Month Flag],
        [Created On Current Month Minus 1 Flag],
        [Created On Current Month Minus 12 Flag],
        [Created On Current Quarter Flag],
        [Created On Current Quarter Minus 1 Flag],
        [Created On Current Quarter Minus 4 Flag],
        [Created On Current Calendar Year Flag],
        [Created On Current Calendar Year Minus 1 Flag],
        [Created On Current Calendar Year Minus 2 Flag],
        [Created On Current Fiscal Year Flag],
        [Created On Current Fiscal Year Minus 1 Flag],
        [Created On Current Fiscal Year Minus 2 Flag],
        [Created On Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Created On Day In Fiscal Year],
        [Created On Date Is Weekday],
        [Created On Fiscal Week],
        [Created On Current Fiscal Week Flag],
        [Created On Current Fiscal Week Minus 1 Flag],
        [Created On Fiscal Weekday Number],
        [Created On Fiscal Weekday Name],
        [Created On Current Month Minus 2 Flag],
        [Created On Current Fiscal Week Minus 2 Flag],
        [Created On Current Fiscal Week Minus 6 Flag],
        [Created On Current Fiscal Week Minus 3 Flag],
        [Created On Current Fiscal Week Minus 4 Flag],
        [Created On Current Fiscal Week Minus 5 Flag],
        [Created On Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[CREATED_ON_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
 
END