CREATE       PROCEDURE [Propelis].[Proc_CLOSE_DATE] 
AS
BEGIN  
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY]                                                         = S.[DATE_KEY]                   ,
        T.[Close Date]                                   = S.[THE_DATE]                   ,
        T.[Close Fiscal Year]                            = S.[FISCAL_YR]                  ,
        T.[Close Fiscal Period Number]                   = S.[FISCAL_PER_NUM]             ,
        T.[Close Fiscal Period Code]                     = S.[FISCAL_PER_CD]              ,
        T.[Close Fiscal Quarter Number]                  = S.[FISCAL_QTR_NUM]             ,
        T.[Close Fiscal Quarter Code]                    = S.[FISCAL_QTR_CD]              ,
        T.[Close Calendar Year]                          = S.[CLNDR_YR]                   ,
        T.[Close Calendar Month Number]                  = S.[CLNDR_MNTH_NUM]             ,
        T.[Close Calendar Month Code]                    = S.[CLNDR_MNTH_CD]              ,
        T.[Close Calendar Month Description]             = S.[CLNDR_MNTH_DESC]            ,
        T.[Close Calendar Quarter Number]                = S.[CLNDR_QTR_NUM]              ,
        T.[Close Calendar Quarter Code]                  = S.[CLNDR_QTR_CD]               ,
        T.[Close Calendar Weekday Number]                = S.[CLNDR_WEEKDAY_NUM]          ,
        T.[Close Calendar Weekday Name]                  = S.[CLNDR_WEEKDAY_NAME]         ,
        T.[Close Calendar Day In Month]                  = S.[CLNDR_DAY_IN_MNTH]          ,
        T.[Close Calendar Day In Year]                   = S.[CLNDR_DAY_IN_YR]            ,
        T.[Close Calendar Week]                          = S.[CLNDR_WK]                   ,
        T.[Close Calendar Month In Quarter Number]       = S.[CLNDR_MNTH_IN_QTR_NUM]      ,
        T.[Close Calendar Days In Month]                 = S.[CLNDR_DAYS_IN_MNTH]         ,
        T.[ETL_SRC_SYS_CD]                                                   = S.[ETL_SRC_SYS_CD]             ,
        T.[ETL_CREATED_TS]                                                   = S.[ETL_CREATED_TS]             ,
        T.[ETL_UPDTD_TS]                                                     = S.[ETL_UPDTD_TS]               ,
        T.[Close Current Day Flag]                       = S.[CURR_DAY_FLG]               ,
        T.[Close Current Day Minus 1 Flag]               = S.[CURR_DAY_MINUS_1_FLG]       ,
        T.[Close Current Calendar Week Flag]             = S.[CURR_CLNDR_WK_FLG]          ,
        T.[Close Current Calendar Week Minus 1 Flag]     = S.[CURR_CLNDR_WK_MINUS_1_FLG]  ,
        T.[Close Current Month Flag]                     = S.[CURR_MNTH_FLG]              ,
        T.[Close Current Month Minus 1 Flag]             = S.[CURR_MNTH_MINUS_1_FLG]      ,
        T.[Close Current Month Minus 12 Flag]            = S.[CURR_MNTH_MINUS_12_FLG]     ,
        T.[Close Current Quarter Flag]                   = S.[CURR_QTR_FLG]               ,
        T.[Close Current Quarter Minus 1 Flag]           = S.[CURR_QTR_MINUS_1_FLG]       ,
        T.[Close Current Quarter Minus 4 Flag]           = S.[CURR_QTR_MINUS_4_FLG]       ,
        T.[Close Current Calendar Year Flag]             = S.[CURR_CLNDR_YR_FLG]          ,
        T.[Close Current Calendar Year Minus 1 Flag]     = S.[CURR_CLNDR_YR_MINUS_1_FLG]  ,
        T.[Close Current Calendar Year Minus 2 Flag]     = S.[CURR_CLNDR_YR_MINUS_2_FLG]  ,
        T.[Close Current Fiscal Year Flag]               = S.[CURR_FISCAL_YR_FLG]         ,
        T.[Close Current Fiscal Year Minus 1 Flag]       = S.[CURR_FISCAL_YR_MINUS_1_FLG] ,
        T.[Close Current Fiscal Year Minus 2 Flag]       = S.[CURR_FISCAL_YR_MINUS_2_FLG] ,
        T.[Close Current Calendar Year Plus 1 Flag]      = S.[CURR_CLNDR_YR_PLUS_1_FLG]   ,
        T.[Close Current Calendar Year Plus 2 Flag]      = S.[CURR_FISCAL_YR_PLUS_1_FLG]  ,
        T.[Close Day In Fiscal Year]                     = S.[DAY_IN_FISCAL_YR]           ,
        T.[Close Date Is Weekday]                        = S.[IS_WEEKDAY]                 ,
        T.[Close Fiscal Week]                            = S.[FISCAL_WK]                  ,
        T.[Close Current Fiscal Week Flag]               = S.[CURR_FISCAL_WK_FLG]         ,
        T.[Close Current Fiscal Week Minus 1 Flag]       = S.[CURR_FISCAL_WK_MINUS_1_FLG] ,
        T.[Close Fiscal Weekday Number]                  = S.[FISCAL_WEEKDAY_NUM]         ,
        T.[Close Fiscal Weekday Name]                    = S.[FISCAL_WEEKDAY_NAME]        ,
        T.[Close Current Month Minus 2 Flag]             = S.[CURR_MNTH_MINUS_2_FLG]      ,
        T.[Close Current Fiscal Week Minus 2 Flag]       = S.[CURR_FISCAL_WK_MINUS_2_FLG] ,
        T.[Close Current Fiscal Week Minus 6 Flag]       = S.[CURR_FISCAL_WK_MINUS_6_FLG] ,
        T.[Close Current Fiscal Week Minus 3 Flag]       = S.[CURR_FISCAL_WK_MINUS_3_FLG] ,
        T.[Close Current Fiscal Week Minus 4 Flag]       = S.[CURR_FISCAL_WK_MINUS_4_FLG] ,
        T.[Close Current Fiscal Week Minus 5 Flag]       = S.[CURR_FISCAL_WK_MINUS_5_FLG] ,
        T.[Close Current Fiscal Week Minus 7 Flag]       = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[CLOSE_DATE] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];
 
    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[CLOSE_DATE] (
        [DATE_KEY]                                           ,
        [Close Date]                                  ,
        [Close Fiscal Year]                           ,
        [Close Fiscal Period Number]                  ,
        [Close Fiscal Period Code]                    ,
        [Close Fiscal Quarter Number]                 ,
        [Close Fiscal Quarter Code]                   ,
        [Close Calendar Year]                         ,
        [Close Calendar Month Number]                 ,
        [Close Calendar Month Code]                   ,
        [Close Calendar Month Description]            ,
        [Close Calendar Quarter Number]               ,
        [Close Calendar Quarter Code]                 ,
        [Close Calendar Weekday Number]               ,
        [Close Calendar Weekday Name]                 ,
        [Close Calendar Day In Month]                 ,
        [Close Calendar Day In Year]                  ,
        [Close Calendar Week]                         ,
        [Close Calendar Month In Quarter Number]      ,
        [Close Calendar Days In Month]                ,
        [ETL_SRC_SYS_CD]                                     ,
        [ETL_CREATED_TS]                                     ,
        [ETL_UPDTD_TS]                                       ,
        [Close Current Day Flag]                      ,
        [Close Current Day Minus 1 Flag]              ,
        [Close Current Calendar Week Flag]            ,
        [Close Current Calendar Week Minus 1 Flag]    ,
        [Close Current Month Flag]                    ,
        [Close Current Month Minus 1 Flag]            ,
        [Close Current Month Minus 12 Flag]           ,
        [Close Current Quarter Flag]                  ,
        [Close Current Quarter Minus 1 Flag]          ,
        [Close Current Quarter Minus 4 Flag]          ,
        [Close Current Calendar Year Flag]            ,
        [Close Current Calendar Year Minus 1 Flag]    ,
        [Close Current Calendar Year Minus 2 Flag]    ,
        [Close Current Fiscal Year Flag]              ,
        [Close Current Fiscal Year Minus 1 Flag]      ,
        [Close Current Fiscal Year Minus 2 Flag]      ,
        [Close Current Calendar Year Plus 1 Flag]     ,
        [Close Current Calendar Year Plus 2 Flag]     ,
        [Close Day In Fiscal Year]                    ,
        [Close Date Is Weekday]                       ,
        [Close Fiscal Week]                           ,
        [Close Current Fiscal Week Flag]              ,
        [Close Current Fiscal Week Minus 1 Flag]      ,
        [Close Fiscal Weekday Number]                 ,
        [Close Fiscal Weekday Name]                   ,
        [Close Current Month Minus 2 Flag]            ,
        [Close Current Fiscal Week Minus 2 Flag]      ,
        [Close Current Fiscal Week Minus 6 Flag]      ,
        [Close Current Fiscal Week Minus 3 Flag]      ,
        [Close Current Fiscal Week Minus 4 Flag]      ,
        [Close Current Fiscal Week Minus 5 Flag]      ,
        [Close Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY]                        ,
        S.[THE_DATE]                        ,
        S.[FISCAL_YR]                       ,
        S.[FISCAL_PER_NUM]                  ,
        S.[FISCAL_PER_CD]                   ,
        S.[FISCAL_QTR_NUM]                  ,
        S.[FISCAL_QTR_CD]                   ,
        S.[CLNDR_YR]                        ,
        S.[CLNDR_MNTH_NUM]                  ,
        S.[CLNDR_MNTH_CD]                   ,
        S.[CLNDR_MNTH_DESC]                 ,
        S.[CLNDR_QTR_NUM]                   ,
        S.[CLNDR_QTR_CD]                    ,
        S.[CLNDR_WEEKDAY_NUM]               ,
        S.[CLNDR_WEEKDAY_NAME]              ,
        S.[CLNDR_DAY_IN_MNTH]               ,
        S.[CLNDR_DAY_IN_YR]                 ,
        S.[CLNDR_WK]                        ,
        S.[CLNDR_MNTH_IN_QTR_NUM]           ,
        S.[CLNDR_DAYS_IN_MNTH]              ,
        S.[ETL_SRC_SYS_CD]                  ,
        S.[ETL_CREATED_TS]                  ,
        S.[ETL_UPDTD_TS]                    ,
        S.[CURR_DAY_FLG]                    ,
        S.[CURR_DAY_MINUS_1_FLG]            ,
        S.[CURR_CLNDR_WK_FLG]               ,
        S.[CURR_CLNDR_WK_MINUS_1_FLG]       ,
        S.[CURR_MNTH_FLG]                   ,
        S.[CURR_MNTH_MINUS_1_FLG]           ,
        S.[CURR_MNTH_MINUS_12_FLG]          ,
        S.[CURR_QTR_FLG]                    ,
        S.[CURR_QTR_MINUS_1_FLG]            ,
        S.[CURR_QTR_MINUS_4_FLG]            ,
        S.[CURR_CLNDR_YR_FLG]               ,
        S.[CURR_CLNDR_YR_MINUS_1_FLG]       ,
        S.[CURR_CLNDR_YR_MINUS_2_FLG]       ,
        S.[CURR_FISCAL_YR_FLG]              ,
        S.[CURR_FISCAL_YR_MINUS_1_FLG]      ,
        S.[CURR_FISCAL_YR_MINUS_2_FLG]      ,
        S.[CURR_CLNDR_YR_PLUS_1_FLG]        ,
        S.[CURR_FISCAL_YR_PLUS_1_FLG]       ,
        S.[DAY_IN_FISCAL_YR]                ,
        S.[IS_WEEKDAY]                      ,
        S.[FISCAL_WK]                       ,
        S.[CURR_FISCAL_WK_FLG]              ,
        S.[CURR_FISCAL_WK_MINUS_1_FLG]      ,
        S.[FISCAL_WEEKDAY_NUM]              ,
        S.[FISCAL_WEEKDAY_NAME]             ,
        S.[CURR_MNTH_MINUS_2_FLG]           ,
        S.[CURR_FISCAL_WK_MINUS_2_FLG]      ,
        S.[CURR_FISCAL_WK_MINUS_6_FLG]      ,
        S.[CURR_FISCAL_WK_MINUS_3_FLG]      ,
        S.[CURR_FISCAL_WK_MINUS_4_FLG]      ,
        S.[CURR_FISCAL_WK_MINUS_5_FLG]      ,
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[CLOSE_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
 
END