CREATE     PROCEDURE Propelis.Proc_PARTNER_COST_CENTER
AS
BEGIN

    ------------------------------------------------------------------
    -- Step 1: Load source data into a temp table with a hash key
    ------------------------------------------------------------------
    IF OBJECT_ID('tempdb..#SourceData') IS NOT NULL
        DROP TABLE #SourceData;

    SELECT 
        S.[COST_CNTR_KEY],
        S.[COST_CNTR_ID],
        S.[COST_CNTR_LONG_DESC],
        S.[CONTROLLING_AREA_ID],
        S.[LANG_TYP_CD],
        S.[COST_CNTR_CTGRY],
        S.[HIERCHY_AREA],
        S.[CMPNY_CD],
        S.[PLNT_ID],
        S.[PROFT_CNTR_ID],
        S.[CRNCY_CD],
        S.[ADRESS_LINE_1],
        S.[ADRESS_LINE_2],
        S.[ADRESS_LINE_3],
        S.[CITY_NAME],
        S.[DISTR_NAME],
        S.[POSTAL_CD],
        S.[CNTRY_CD],
        S.[REGN_CD],
        S.[PERSON_RESPNSBLE],
        S.[FLG_ACTUAL_REVENUES],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[ACTUAL_PRIMARY_POSTINGS_LOCK_IN],
        S.[PLAN_PRIMARY_COSTS_LOCK_IND],
        S.[BIZ_AREA],
        S.[PLNG_REVENUES_LOCK_IND],
        S.[PO_BOX],
        S.[STR],
        S.[USR_RESPNSBLE],
        S.[COST_CNTR_NAME],
        S.[COST_CNTR_SHORT_DESC],
        S.[CONTROLLING_AREA_DESC],
        S.[COST_CNTR_CTGRY_DESC],
        S.[CMPNY_DESC],
        S.[CRNCY_DESC],
        S.[CNTRY_DESC],
        S.[BIZ_AREA_DESC],
        S.[ACTUAL_SECONDARY_COST_LOCK_IND],
        S.[PLAN_SECONDARY_COST_LOCK_IND],
        S.[FUNCTNL_AREA],
        S.[FUNCTNL_AREA_DESC],
        S.[TAX_JRSDCTN],
        S.[FUNCTION_OF_COST_CNTR],
        S.[PLNT_DESC],
        S.[CREATED_ON],
        S.[VALID_TO_DATE],
        S.[VALID_FROM_DATE],

        HASHBYTES('SHA2_256', 
            CONCAT(
                 ISNULL(S.[COST_CNTR_KEY], ''), '|',
                 ISNULL(S.[COST_CNTR_ID], ''), '|',
                 ISNULL(S.[COST_CNTR_LONG_DESC], ''), '|',
                 ISNULL(S.[CONTROLLING_AREA_ID], ''), '|',
                 ISNULL(S.[LANG_TYP_CD], ''), '|',
                 ISNULL(S.[COST_CNTR_CTGRY], ''), '|',
                 ISNULL(S.[HIERCHY_AREA], ''), '|',
                 ISNULL(S.[CMPNY_CD], ''), '|',
                 ISNULL(S.[PLNT_ID], ''), '|',
                 ISNULL(S.[PROFT_CNTR_ID], ''), '|',
                 ISNULL(S.[CRNCY_CD], ''), '|',
                 ISNULL(S.[ADRESS_LINE_1], ''), '|',
                 ISNULL(S.[ADRESS_LINE_2], ''), '|',
                 ISNULL(S.[ADRESS_LINE_3], ''), '|',
                 ISNULL(S.[CITY_NAME], ''), '|',
                 ISNULL(S.[DISTR_NAME], ''), '|',
                 ISNULL(S.[POSTAL_CD], ''), '|',
                 ISNULL(S.[CNTRY_CD], ''), '|',
                 ISNULL(S.[REGN_CD], ''), '|',
                 ISNULL(S.[PERSON_RESPNSBLE], ''), '|',
                 ISNULL(S.[FLG_ACTUAL_REVENUES], ''), '|',
                 ISNULL(S.[ETL_SRC_SYS_CD], ''), '|',
                 ISNULL(S.[ETL_EFFECTV_BEGIN_DATE], ''), '|',
                 ISNULL(S.[ETL_EFFECTV_END_DATE], ''), '|',
                 ISNULL(S.[ETL_CURR_RCD_IND], ''), '|',
                 ISNULL(S.[ETL_CREATED_TS], ''), '|',
                 ISNULL(S.[ETL_UPDTD_TS], ''), '|',
                 ISNULL(S.[ACTUAL_PRIMARY_POSTINGS_LOCK_IN], ''), '|',
                 ISNULL(S.[PLAN_PRIMARY_COSTS_LOCK_IND], ''), '|',
                 ISNULL(S.[BIZ_AREA], ''), '|',
                 ISNULL(S.[PLNG_REVENUES_LOCK_IND], ''), '|',
                 ISNULL(S.[PO_BOX], ''), '|',
                 ISNULL(S.[STR], ''), '|',
                 ISNULL(S.[USR_RESPNSBLE], ''), '|',
                 ISNULL(S.[COST_CNTR_NAME], ''), '|',
                 ISNULL(S.[COST_CNTR_SHORT_DESC], ''), '|',
                 ISNULL(S.[CONTROLLING_AREA_DESC], ''), '|',
                 ISNULL(S.[COST_CNTR_CTGRY_DESC], ''), '|',
                 ISNULL(S.[CMPNY_DESC], ''), '|',
                 ISNULL(S.[CRNCY_DESC], ''), '|',
                 ISNULL(S.[CNTRY_DESC], ''), '|',
                 ISNULL(S.[BIZ_AREA_DESC], ''), '|',
                 ISNULL(S.[ACTUAL_SECONDARY_COST_LOCK_IND], ''), '|',
                 ISNULL(S.[PLAN_SECONDARY_COST_LOCK_IND], ''), '|',
                 ISNULL(S.[FUNCTNL_AREA], ''), '|',
                 ISNULL(S.[FUNCTNL_AREA_DESC], ''), '|',
                 ISNULL(S.[TAX_JRSDCTN], ''), '|',
                 ISNULL(S.[FUNCTION_OF_COST_CNTR], ''), '|',
                 ISNULL(S.[PLNT_DESC], ''), '|',
                 ISNULL(S.[CREATED_ON], ''), '|',
                 ISNULL(S.[VALID_TO_DATE], ''), '|',
                 ISNULL(S.[VALID_FROM_DATE], ''), '|'

            )
        ) AS HashKey
    INTO #SourceData
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_COSCNTR_CUR_D] AS S;

    -- Step 2: Update changed rows in target (hash mismatch)
    UPDATE T
    SET 
        [COST_CNTR_KEY]	                                = S.[COST_CNTR_KEY],
        [Partner Cost Center ID]	                        = S.[COST_CNTR_ID],
        [Partner Cost Center Long Description]	            = S.[COST_CNTR_LONG_DESC],
        [Partner Cost Center Controlling Area ID]	        = S.[CONTROLLING_AREA_ID],
        [Partner Cost Center Language Type Code]	        = S.[LANG_TYP_CD],
        [Partner Cost Center Category]	                    = S.[COST_CNTR_CTGRY],
        [Partner Cost Center Hierarchy Area]	            = S.[HIERCHY_AREA],
        [Partner Cost Center Company Code]	                = S.[CMPNY_CD],
        [Partner Cost Center Plant]	                    = S.[PLNT_ID],
        [Partner Cost Center Proft Center ID]	            = S.[PROFT_CNTR_ID],
        [Partner Cost Center Currency Code]	            = S.[CRNCY_CD],
        [Partner Cost Center Address Line 1]	            = S.[ADRESS_LINE_1],
        [Partner Cost Center Address Line 2]	            = S.[ADRESS_LINE_2],
        [Partner Cost Center Address Line 3]	            = S.[ADRESS_LINE_3],
        [Partner Cost Center City Name]	                = S.[CITY_NAME],
        [Partner Cost Center District Name]	            = S.[DISTR_NAME],
        [Partner Cost Center Postal Code]	                = S.[POSTAL_CD],
        [Partner Cost Center Country Code]	                = S.[CNTRY_CD],
        [Partner Cost Center Region Code]	                = S.[REGN_CD],
        [Partner Cost Center Person Responsible]	        = S.[PERSON_RESPNSBLE],
        [Partner Cost Center Flag Actual Revenues]	        = S.[FLG_ACTUAL_REVENUES],
        [ETL_SRC_SYS_CD]	                            = S.[ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE]	                    = S.[ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE]	                        = S.[ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND]	                            = S.[ETL_CURR_RCD_IND],
        [ETL_CREATED_TS]	                            = S.[ETL_CREATED_TS],
        [ETL_UPDTD_TS]	                                = S.[ETL_UPDTD_TS],
        [Partner CC Actual Primary Postings Lock Indicator]	    = S.[ACTUAL_PRIMARY_POSTINGS_LOCK_IN],
        [Partner CC Plan Primary Costs Lock Indicator]	        = S.[PLAN_PRIMARY_COSTS_LOCK_IND],
        [Partner Cost Center Business Area]	            = S.[BIZ_AREA],
        [Partner CC Planning Revenues Lock Indicator]	            = S.[PLNG_REVENUES_LOCK_IND],
        [Partner Cost Center PO Box]	                    = S.[PO_BOX],
        [Partner Cost Center Street]	                    = S.[STR],
        [Partner Cost Center User Responsible]	            = S.[USR_RESPNSBLE],
        [Partner Cost Center Description]	                = S.[COST_CNTR_NAME],
        [Partner Cost Center Short Description]	        = S.[COST_CNTR_SHORT_DESC],
        [Partner Cost Center Controlling Area Description]	= S.[CONTROLLING_AREA_DESC],
        [Partner Cost Center Category Description]	        = S.[COST_CNTR_CTGRY_DESC],
        [Partner Cost Center Company Description]	        = S.[CMPNY_DESC],
        [Partner Cost Center Currency Description]	        = S.[CRNCY_DESC],
        [Partner Cost Center Country Description]	        = S.[CNTRY_DESC],
        [Partner Cost Center Business Area Description]	= S.[BIZ_AREA_DESC],
        [Partner CC Actual Secondary Cost Lock Indicator]	        = S.[ACTUAL_SECONDARY_COST_LOCK_IND],
        [Partner CC Plan Secondary Cost Lock Indicator]	        = S.[PLAN_SECONDARY_COST_LOCK_IND],
        [Partner Cost Center Functional Area]	            = S.[FUNCTNL_AREA],
        [Partner Cost Center Functional Area Description]	= S.[FUNCTNL_AREA_DESC],
        [Partner Cost Center Tax Jurisdiction]	            = S.[TAX_JRSDCTN],
        [Partner Cost Center Function]	                    = S.[FUNCTION_OF_COST_CNTR],
        [Partner Cost Center Plant Description]	        = S.[PLNT_DESC],
        [Partner Cost Center Created On]	                = S.[CREATED_ON],
        [Partner Cost Center Valid To Date]	            = S.[VALID_TO_DATE],
        [Partner Cost Center Valid From Date]	            = S.[VALID_FROM_DATE]

    FROM [GLOBAL_EDW].[Propelis].[PARTNER_COST_CENTER] AS T
    INNER JOIN #SourceData AS S
        ON T.[COST_CNTR_KEY] = S.[COST_CNTR_KEY]
    WHERE HASHBYTES('SHA2_256', 
            CONCAT(
				ISNULL(T.[COST_CNTR_KEY], ''), '|',
                ISNULL(T.[Partner Cost Center ID], ''), '|',
                ISNULL(T.[Partner Cost Center Long Description], ''), '|',
                ISNULL(T.[Partner Cost Center Controlling Area ID], ''), '|',
                ISNULL(T.[Partner Cost Center Language Type Code], ''), '|',
                ISNULL(T.[Partner Cost Center Category], ''), '|',
                ISNULL(T.[Partner Cost Center Hierarchy Area], ''), '|',
                ISNULL(T.[Partner Cost Center Company Code], ''), '|',
                ISNULL(T.[Partner Cost Center Plant], ''), '|',
                ISNULL(T.[Partner Cost Center Proft Center ID], ''), '|',
                ISNULL(T.[Partner Cost Center Currency Code], ''), '|',
                ISNULL(T.[Partner Cost Center Address Line 1], ''), '|',
                ISNULL(T.[Partner Cost Center Address Line 2], ''), '|',
                ISNULL(T.[Partner Cost Center Address Line 3], ''), '|',
                ISNULL(T.[Partner Cost Center City Name], ''), '|',
                ISNULL(T.[Partner Cost Center District Name], ''), '|',
                ISNULL(T.[Partner Cost Center Postal Code], ''), '|',
                ISNULL(T.[Partner Cost Center Country Code], ''), '|',
                ISNULL(T.[Partner Cost Center Region Code], ''), '|',
                ISNULL(T.[Partner Cost Center Person Responsible], ''), '|',
                ISNULL(T.[Partner Cost Center Flag Actual Revenues], ''), '|',
                ISNULL(T.[ETL_SRC_SYS_CD], ''), '|',
                ISNULL(T.[ETL_EFFECTV_BEGIN_DATE], ''), '|',
                ISNULL(T.[ETL_EFFECTV_END_DATE], ''), '|',
                ISNULL(T.[ETL_CURR_RCD_IND], ''), '|',
                ISNULL(T.[ETL_CREATED_TS], ''), '|',
                ISNULL(T.[ETL_UPDTD_TS], ''), '|',
                ISNULL(T.[Partner CC Actual Primary Postings Lock Indicator], ''), '|',
                ISNULL(T.[Partner CC Plan Primary Costs Lock Indicator], ''), '|',
                ISNULL(T.[Partner Cost Center Business Area], ''), '|',
                ISNULL(T.[Partner CC Planning Revenues Lock Indicator], ''), '|',
                ISNULL(T.[Partner Cost Center PO Box], ''), '|',
                ISNULL(T.[Partner Cost Center Street], ''), '|',
                ISNULL(T.[Partner Cost Center User Responsible], ''), '|',
                ISNULL(T.[Partner Cost Center Description], ''), '|',
                ISNULL(T.[Partner Cost Center Short Description], ''), '|',
                ISNULL(T.[Partner Cost Center Controlling Area Description], ''), '|',
                ISNULL(T.[Partner Cost Center Category Description], ''), '|',
                ISNULL(T.[Partner Cost Center Company Description], ''), '|',
                ISNULL(T.[Partner Cost Center Currency Description], ''), '|',
                ISNULL(T.[Partner Cost Center Country Description], ''), '|',
                ISNULL(T.[Partner Cost Center Business Area Description], ''), '|',
                ISNULL(T.[Partner CC Actual Secondary Cost Lock Indicator], ''), '|',
                ISNULL(T.[Partner CC Plan Secondary Cost Lock Indicator], ''), '|',
                ISNULL(T.[Partner Cost Center Functional Area], ''), '|',
                ISNULL(T.[Partner Cost Center Functional Area Description], ''), '|',
                ISNULL(T.[Partner Cost Center Tax Jurisdiction], ''), '|',
                ISNULL(T.[Partner Cost Center Function], ''), '|',
                ISNULL(T.[Partner Cost Center Plant Description], ''), '|',
                ISNULL(T.[Partner Cost Center Created On], ''), '|',
                ISNULL(T.[Partner Cost Center Valid To Date], ''), '|',
                ISNULL(T.[Partner Cost Center Valid From Date], ''), '|'

            )
        ) <> S.HashKey;

    -- Step 3: Insert only new rows not already in target
	
    INSERT INTO [GLOBAL_EDW].[Propelis].[PARTNER_COST_CENTER]
    (
        [COST_CNTR_KEY],
        [Partner Cost Center ID],
        [Partner Cost Center Long Description],
        [Partner Cost Center Controlling Area ID],
        [Partner Cost Center Language Type Code],
        [Partner Cost Center Category],
        [Partner Cost Center Hierarchy Area],
        [Partner Cost Center Company Code],
        [Partner Cost Center Plant],
        [Partner Cost Center Proft Center ID],
        [Partner Cost Center Currency Code],
        [Partner Cost Center Address Line 1],
        [Partner Cost Center Address Line 2],
        [Partner Cost Center Address Line 3],
        [Partner Cost Center City Name],
        [Partner Cost Center District Name],
        [Partner Cost Center Postal Code],
        [Partner Cost Center Country Code],
        [Partner Cost Center Region Code],
        [Partner Cost Center Person Responsible],
        [Partner Cost Center Flag Actual Revenues],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Partner CC Actual Primary Postings Lock Indicator],
        [Partner CC Plan Primary Costs Lock Indicator],
        [Partner Cost Center Business Area],
        [Partner CC Planning Revenues Lock Indicator],
        [Partner Cost Center PO Box],
        [Partner Cost Center Street],
        [Partner Cost Center User Responsible],
        [Partner Cost Center Description],
        [Partner Cost Center Short Description],
        [Partner Cost Center Controlling Area Description],
        [Partner Cost Center Category Description],
        [Partner Cost Center Company Description],
        [Partner Cost Center Currency Description],
        [Partner Cost Center Country Description],
        [Partner Cost Center Business Area Description],
        [Partner CC Actual Secondary Cost Lock Indicator],
        [Partner CC Plan Secondary Cost Lock Indicator],
        [Partner Cost Center Functional Area],
        [Partner Cost Center Functional Area Description],
        [Partner Cost Center Tax Jurisdiction],
        [Partner Cost Center Function],
        [Partner Cost Center Plant Description],
        [Partner Cost Center Created On],
        [Partner Cost Center Valid To Date],
        [Partner Cost Center Valid From Date]

    )
    SELECT 
         S.[COST_CNTR_KEY],
        S.[COST_CNTR_ID],
        S.[COST_CNTR_LONG_DESC],
        S.[CONTROLLING_AREA_ID],
        S.[LANG_TYP_CD],
        S.[COST_CNTR_CTGRY],
        S.[HIERCHY_AREA],
        S.[CMPNY_CD],
        S.[PLNT_ID],
        S.[PROFT_CNTR_ID],
        S.[CRNCY_CD],
        S.[ADRESS_LINE_1],
        S.[ADRESS_LINE_2],
        S.[ADRESS_LINE_3],
        S.[CITY_NAME],
        S.[DISTR_NAME],
        S.[POSTAL_CD],
        S.[CNTRY_CD],
        S.[REGN_CD],
        S.[PERSON_RESPNSBLE],
        S.[FLG_ACTUAL_REVENUES],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[ACTUAL_PRIMARY_POSTINGS_LOCK_IN],
        S.[PLAN_PRIMARY_COSTS_LOCK_IND],
        S.[BIZ_AREA],
        S.[PLNG_REVENUES_LOCK_IND],
        S.[PO_BOX],
        S.[STR],
        S.[USR_RESPNSBLE],
        S.[COST_CNTR_NAME],
        S.[COST_CNTR_SHORT_DESC],
        S.[CONTROLLING_AREA_DESC],
        S.[COST_CNTR_CTGRY_DESC],
        S.[CMPNY_DESC],
        S.[CRNCY_DESC],
        S.[CNTRY_DESC],
        S.[BIZ_AREA_DESC],
        S.[ACTUAL_SECONDARY_COST_LOCK_IND],
        S.[PLAN_SECONDARY_COST_LOCK_IND],
        S.[FUNCTNL_AREA],
        S.[FUNCTNL_AREA_DESC],
        S.[TAX_JRSDCTN],
        S.[FUNCTION_OF_COST_CNTR],
        S.[PLNT_DESC],
        S.[CREATED_ON],
        S.[VALID_TO_DATE],
        S.[VALID_FROM_DATE]
      
    FROM #SourceData AS S
    WHERE NOT EXISTS (
        SELECT 1
        FROM [GLOBAL_EDW].[Propelis].[PARTNER_COST_CENTER] AS T
        WHERE T.[COST_CNTR_KEY] = S.[COST_CNTR_KEY]
    );

END;