CREATE     PROCEDURE [Propelis].[Proc_SALES_ORDER_CREATION_DATE] 
AS
BEGIN  

    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Sales Order Creation Date] = S.[THE_DATE],
        T.[Sales Order Creation Fiscal Year] = S.[FISCAL_YR],
        T.[Sales Order Creation Fiscal Period] = S.[FISCAL_PER_NUM],
        T.[Sales Order Creation Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Sales Order Creation Fiscal Quarter] = S.[FISCAL_QTR_NUM],
        T.[Sales Order Creation Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Sales Order Creation Calendar Year] = S.[CLNDR_YR],
        T.[Sales Order Creation Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Sales Order Creation Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Sales Order Creation Calendar Month Desc] = S.[CLNDR_MNTH_DESC],
        T.[Sales Order Creation Calendar Quarter] = S.[CLNDR_QTR_NUM],
        T.[Sales Order Creation Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Sales Order Creation Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Sales Order Creation Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Sales Order Creation Calendar Day] = S.[CLNDR_DAY_IN_MNTH],
        T.[Sales Order Creation Calendar Day in Year] = S.[CLNDR_DAY_IN_YR],
        T.[Sales Order Creation Calendar Week] = S.[CLNDR_WK],
        T.[Sales Order Creation Calendar Month in Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Sales Order Creation Calendar Days in Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Sales Order Creation Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Sales Order Creation Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Sales Order Creation Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Sales Order Creation Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Sales Order Creation Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Sales Order Creation Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Sales Order Creation Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Sales Order Creation Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Sales Order Creation Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Sales Order Creation Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Sales Order Creation Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Sales Order Creation Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Sales Order Creation Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Sales Order Creation Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Sales Order Creation Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Sales Order Creation Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Sales Order Creation Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Sales Order Creation Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Sales Order Creation Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Sales Order Creation Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Sales Order Creation Fiscal Week] = S.[FISCAL_WK],
        T.[Sales Order Creation Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Sales Order Creation Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Sales Order Creation Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Sales Order Creation Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Sales Order Creation Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Sales Order Creation Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Sales Order Creation Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Sales Order Creation Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Sales Order Creation Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Sales Order Creation Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Sales Order Creation Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[SALES_ORDER_CREATION_DATE] T
    INNER JOIN[GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];


    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[SALES_ORDER_CREATION_DATE] (
        [DATE_KEY],
        [Sales Order Creation Date],
        [Sales Order Creation Fiscal Year],
        [Sales Order Creation Fiscal Period],
        [Sales Order Creation Fiscal Period Code],
        [Sales Order Creation Fiscal Quarter],
        [Sales Order Creation Fiscal Quarter Code],
        [Sales Order Creation Calendar Year],
        [Sales Order Creation Calendar Month Number],
        [Sales Order Creation Calendar Month Code],
        [Sales Order Creation Calendar Month Desc],
        [Sales Order Creation Calendar Quarter],
        [Sales Order Creation Calendar Quarter Code],
        [Sales Order Creation Calendar Weekday Number],
        [Sales Order Creation Calendar Weekday Name],
        [Sales Order Creation Calendar Day],
        [Sales Order Creation Calendar Day in Year],
        [Sales Order Creation Calendar Week],
        [Sales Order Creation Calendar Month in Quarter Number],
        [Sales Order Creation Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Sales Order Creation Current Day Flag],
        [Sales Order Creation Current Day Minus 1 Flag],
        [Sales Order Creation Current Calendar Week Flag],
        [Sales Order Creation Current Calendar Week Minus 1 Flag],
        [Sales Order Creation Current Month Flag],
        [Sales Order Creation Current Month Minus 1 Flag],
        [Sales Order Creation Current Month Minus 12 Flag],
        [Sales Order Creation Current Quarter Flag],
        [Sales Order Creation Current Quarter Minus 1 Flag],
        [Sales Order Creation Current Quarter Minus 4 Flag],
        [Sales Order Creation Current Calendar Year Flag],
        [Sales Order Creation Current Calendar Year Minus 1 Flag],
        [Sales Order Creation Current Calendar Year Minus 2 Flag],
        [Sales Order Creation Current Fiscal Year Flag],
        [Sales Order Creation Current Fiscal Year Minus 1 Flag],
        [Sales Order Creation Current Fiscal Year Minus 2 Flag],
        [Sales Order Creation Current Calendar Year Plus 1 Flag],
        [Sales Order Creation Current Fiscal Year Plus 1 Flag],
        [Sales Order Creation Day In Fiscal Year],
        [Sales Order Creation Date Is Weekday],
        [Sales Order Creation Fiscal Week],
        [Sales Order Creation Current Fiscal Week Flag],
        [Sales Order Creation Current Fiscal Week Minus 1 Flag],
        [Sales Order Creation Fiscal Weekday Number],
        [Sales Order Creation Fiscal Weekday Name],
        [Sales Order Creation Current Month Minus 2 Flag],
        [Sales Order Creation Current Fiscal Week Minus 2 Flag],
        [Sales Order Creation Current Fiscal Week Minus 6 Flag],
        [Sales Order Creation Current Fiscal Week Minus 3 Flag],
        [Sales Order Creation Current Fiscal Week Minus 4 Flag],
        [Sales Order Creation Current Fiscal Week Minus 5 Flag],
        [Sales Order Creation Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[SALES_ORDER_CREATION_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
END