CREATE   PROCEDURE [Propelis].[Proc_PARTNER_PROFIT_CENTER]
AS
BEGIN
    -- ==============================================
    -- STEP 1: UPDATE existing records in target
    -- ==============================================
    UPDATE T
    SET
        T.[Partner Profit Center ID] = S.[PROFT_CNTR_ID],
        T.[Partner Profit Center Description] = S.[PROFT_CNTR_DESC],
        T.[Legacy Partner Profit Center Code] = S.[LGCY_PROFT_CNTR_CD],
        T.[Legacy Partner Profit Center Description] = S.[LGCY_PROFT_CNTR_DESC],
        T.[Partner Profit Center Controlling Area ID] = S.[CONTROLLING_AREA_ID],
        T.[Partner Profit Center User Responsible ID] = S.[USR_RESPNSBLE_ID],
        T.[Partner Profit Center Person Responsible] = S.[PERSON_RESPNSBLE],
        T.[Partner Profit Center Language Type Code] = S.[LANG_TYP_CD],
        T.[Partner Profit Center Segment ID] = S.[SEG_ID],
        T.[Partner Profit Center Adress Line 1] = S.[ADRESS_LINE_1],
        T.[Partner Profit Center Address Line 2] = S.[ADRESS_LINE_2],
        T.[Partner Profit Center City Name] = S.[CITY_NAME],
        T.[Partner Profit Center District Name] = S.[DISTR_NAME],
        T.[Partner Profit Center Postal Code] = S.[POSTAL_CD],
        T.[Partner Profit Center Country Code] = S.[CNTRY_CD],
        T.[Partner Profit Center Region Code] = S.[REGN_CD],
        T.[Partner Profit Center Created Date] = S.[CREATED_DATE],
        T.[Partner Profit Center Created User ID] = S.[CREATED_USR_ID],
        T.[Partner Profit Center Updated Date] = S.[UPDTD_DATE],
        T.[Partner Profit Center Updated User ID] = S.[UPDTD_USR_ID],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE] = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE] = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND] = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Partner Profit Center Company Code] = S.[CMPNY_CD],
        T.[Partner Profit Center Long Description] = S.[PROFT_CNTR_LONG_DESC],
        T.[Partner Profit Center Short Description] = S.[PROFT_CNTR_SHORT_DESC],
        T.[Partner Profit Center Lock Indicator] = S.[LOCK_IND],
        T.[Profit Center Name 1] = S.[NAME_1],
        T.[Partner Profit Center Area] = S.[PROFT_CNTR_AREA],
        T.[Partner Profit Center General Master Record Status] = S.[GENERIC_MAST_RCD_STATUS],
        T.[Partner Profit Center Status Description] = S.[STATUS_DESC],
        T.[Partner Profit Center Controlling Area Desc] = S.[CONTROLLING_AREA_DESC],
        T.[Partner Profit Center Country Description] = S.[CNTRY_DESC],
        T.[Partner Profit Center Company Description] = S.[CMPNY_DESC],
        T.[Partner Profit Center Tax Jurisdiction] = S.[TAX_JRSDCTN],
        T.[Partner Profit Center Valid To Date] = S.[VALID_TO_DATE],
        T.[Partner Profit Center Valid From Date] = S.[VALID_FROM_DATE]
    FROM [GLOBAL_EDW].[Propelis].[PARTNER_PROFIT_CENTER] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_PROFCTR_CUR_D] S
        ON T.[PROFT_CNTR_KEY] = S.[PROFT_CNTR_KEY];

    -- ==============================================
    -- STEP 2: INSERT new records into target
    -- ==============================================
    INSERT INTO [GLOBAL_EDW].[Propelis].[PARTNER_PROFIT_CENTER] (
        [PROFT_CNTR_KEY],
        [Partner Profit Center ID],
        [Partner Profit Center Description],
        [Legacy Partner Profit Center Code],
        [Legacy Partner Profit Center Description],
        [Partner Profit Center Controlling Area ID],
        [Partner Profit Center User Responsible ID],
        [Partner Profit Center Person Responsible],
        [Partner Profit Center Language Type Code],
        [Partner Profit Center Segment ID],
        [Partner Profit Center Adress Line 1],
        [Partner Profit Center Address Line 2],
        [Partner Profit Center City Name],
        [Partner Profit Center District Name],
        [Partner Profit Center Postal Code],
        [Partner Profit Center Country Code],
        [Partner Profit Center Region Code],
        [Partner Profit Center Created Date],
        [Partner Profit Center Created User ID],
        [Partner Profit Center Updated Date],
        [Partner Profit Center Updated User ID],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Partner Profit Center Company Code],
        [Partner Profit Center Long Description],
        [Partner Profit Center Short Description],
        [Partner Profit Center Lock Indicator],
        [Profit Center Name 1],
        [Partner Profit Center Area],
        [Partner Profit Center General Master Record Status],
        [Partner Profit Center Status Description],
        [Partner Profit Center Controlling Area Desc],
        [Partner Profit Center Country Description],
        [Partner Profit Center Company Description],
        [Partner Profit Center Tax Jurisdiction],
        [Partner Profit Center Valid To Date],
        [Partner Profit Center Valid From Date]
    )
    SELECT
        S.[PROFT_CNTR_KEY],
        S.[PROFT_CNTR_ID],
        S.[PROFT_CNTR_DESC],
        S.[LGCY_PROFT_CNTR_CD],
        S.[LGCY_PROFT_CNTR_DESC],
        S.[CONTROLLING_AREA_ID],
        S.[USR_RESPNSBLE_ID],
        S.[PERSON_RESPNSBLE],
        S.[LANG_TYP_CD],
        S.[SEG_ID],
        S.[ADRESS_LINE_1],
        S.[ADRESS_LINE_2],
        S.[CITY_NAME],
        S.[DISTR_NAME],
        S.[POSTAL_CD],
        S.[CNTRY_CD],
        S.[REGN_CD],
        S.[CREATED_DATE],
        S.[CREATED_USR_ID],
        S.[UPDTD_DATE],
        S.[UPDTD_USR_ID],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CMPNY_CD],
        S.[PROFT_CNTR_LONG_DESC],
        S.[PROFT_CNTR_SHORT_DESC],
        S.[LOCK_IND],
        S.[NAME_1],
        S.[PROFT_CNTR_AREA],
        S.[GENERIC_MAST_RCD_STATUS],
        S.[STATUS_DESC],
        S.[CONTROLLING_AREA_DESC],
        S.[CNTRY_DESC],
        S.[CMPNY_DESC],
        S.[TAX_JRSDCTN],
        S.[VALID_TO_DATE],
        S.[VALID_FROM_DATE]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_PROFCTR_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[PARTNER_PROFIT_CENTER] T
        ON T.[PROFT_CNTR_KEY] = S.[PROFT_CNTR_KEY]
    WHERE T.[PROFT_CNTR_KEY] IS NULL;
END