CREATE   PROCEDURE [Propelis].[Proc_CREATE_DATE] 
AS
BEGIN  
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Create Date] = S.[THE_DATE],
        T.[Create Fiscal Year] = S.[FISCAL_YR],
        T.[Create Fiscal Period Number] = S.[FISCAL_PER_NUM],
        T.[Create Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Create Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Create Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Create Calendar Year] = S.[CLNDR_YR],
        T.[Create Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Create Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Create Calendar Month Description] = S.[CLNDR_MNTH_DESC],
        T.[Create Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[Create Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Create Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Create Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Create Calendar Day In Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Create Calendar Day In Year] = S.[CLNDR_DAY_IN_YR],
        T.[Create Calendar Week] = S.[CLNDR_WK],
        T.[Create Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Create Calendar Days In Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Create Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Create Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Create Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Create Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Create Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Create Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Create Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Create Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Create Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Create Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Create Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Create Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Create Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Create Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Create Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Create Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Create Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Create Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Create Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Create Is Weekday] = S.[IS_WEEKDAY],
        T.[Create Fiscal Week] = S.[FISCAL_WK],
        T.[Create Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Create Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Create Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Create Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Create Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Create Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Create Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Create Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Create Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Create Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Create Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[CREATE_DATE] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];

    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[CREATE_DATE] (
        [DATE_KEY],
        [Create Date],
        [Create Fiscal Year],
        [Create Fiscal Period Number],
        [Create Fiscal Period Code],
        [Create Fiscal Quarter Number],
        [Create Fiscal Quarter Code],
        [Create Calendar Year],
        [Create Calendar Month Number],
        [Create Calendar Month Code],
        [Create Calendar Month Description],
        [Create Calendar Quarter Number],
        [Create Calendar Quarter Code],
        [Create Calendar Weekday Number],
        [Create Calendar Weekday Name],
        [Create Calendar Day In Month],
        [Create Calendar Day In Year],
        [Create Calendar Week],
        [Create Calendar Month In Quarter Number],
        [Create Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Create Current Day Flag],
        [Create Current Day Minus 1 Flag],
        [Create Current Calendar Week Flag],
        [Create Current Calendar Week Minus 1 Flag],
        [Create Current Month Flag],
        [Create Current Month Minus 1 Flag],
        [Create Current Month Minus 12 Flag],
        [Create Current Quarter Flag],
        [Create Current Quarter Minus 1 Flag],
        [Create Current Quarter Minus 4 Flag],
        [Create Current Calendar Year Flag],
        [Create Current Calendar Year Minus 1 Flag],
        [Create Current Calendar Year Minus 2 Flag],
        [Create Current Fiscal Year Flag],
        [Create Current Fiscal Year Minus 1 Flag],
        [Create Current Fiscal Year Minus 2 Flag],
        [Create Current Calendar Year Plus 1 Flag],
        [Create Current Fiscal Year Plus 1 Flag],
        [Create Day In Fiscal Year],
        [Create Is Weekday],
        [Create Fiscal Week],
        [Create Current Fiscal Week Flag],
        [Create Current Fiscal Week Minus 1 Flag],
        [Create Fiscal Weekday Number],
        [Create Fiscal Weekday Name],
        [Create Current Month Minus 2 Flag],
        [Create Current Fiscal Week Minus 2 Flag],
        [Create Current Fiscal Week Minus 6 Flag],
        [Create Current Fiscal Week Minus 3 Flag],
        [Create Current Fiscal Week Minus 4 Flag],
        [Create Current Fiscal Week Minus 5 Flag],
        [Create Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[CREATE_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
END