CREATE   PROCEDURE [Propelis].[Proc_EDW_T_D_FI_MELTGRP_CUR_D] 
AS
BEGIN

    -- Update existing records
    UPDATE T
    SET 
		T.[ACCT_ID] = S.[ACCT_ID],
		T.[MELT_ADJ_OPER_CF_VAL] = S.[MELT_ADJ_OPER_CF_VAL],
		T.[MELT_ADJEBITDA_BU_VAL] = S.[MELT_ADJEBITDA_BU_VAL],
		T.[MELT_ADJEBITDA_CORP_VAL] = S.[MELT_ADJEBITDA_CORP_VAL],
		T.[MELT_CAPEX_VAL] = S.[MELT_CAPEX_VAL],
		T.[MELT_DII_VAL] = S.[MELT_DII_VAL],
		T.[MELT_TOTAL_LABOR_COST_VAL] = S.[MELT_TOTAL_LABOR_COST_VAL],
		T.[MELT_END_CASH_BALANCE_VAL] = S.[MELT_END_CASH_BALANCE_VAL],
		T.[MELT_GP_VAL] = S.[MELT_GP_VAL],
		T.[MELT_LEVERAGE_RATIO_VAL] = S.[MELT_LEVERAGE_RATIO_VAL],
		T.[MELT_LT_DEBT_VAL] = S.[MELT_LT_DEBT_VAL],
		T.[MELT_NIA_VAL] = S.[MELT_NIA_VAL],
		T.[MELT_REVENUE_VAL] = S.[MELT_REVENUE_VAL],
		T.[MELT_DII_NUMERATOR_VAL] = S.[MELT_DII_NUMERATOR_VAL],
		T.[MELT_DII_DPO_DENOMINATOR_VAL] = S.[MELT_DII_DPO_DENOMINATOR_VAL],
		T.[MELT_DPO_VAL] = S.[MELT_DPO_VAL],
		T.[MELT_DPO_NUMERATOR_VAL] = S.[MELT_DPO_NUMERATOR_VAL],
		T.[MELT_DSO_VAL] = S.[MELT_DSO_VAL],
		T.[MELT_DSO_NUMERATOR_VAL] = S.[MELT_DSO_NUMERATOR_VAL]

   FROM [GLOBAL_EDW].[dbo].[EDW_T_D_FI_MELTGRP_CUR_D] T
   INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_FI_MELTGRP_CUR_D] S 
   ON T.[ACCT_ID] = S.[ACCT_ID];
   
   -- Insert new records
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_FI_MELTGRP_CUR_D]
    (
		[ACCT_ID],
		[MELT_ADJ_OPER_CF_VAL],
		[MELT_ADJEBITDA_BU_VAL],
		[MELT_ADJEBITDA_CORP_VAL],
		[MELT_CAPEX_VAL],
		[MELT_DII_VAL],
		[MELT_TOTAL_LABOR_COST_VAL],
		[MELT_END_CASH_BALANCE_VAL],
		[MELT_GP_VAL],
		[MELT_LEVERAGE_RATIO_VAL],
		[MELT_LT_DEBT_VAL],
		[MELT_NIA_VAL],
		[MELT_REVENUE_VAL],
		[MELT_DII_NUMERATOR_VAL],
		[MELT_DII_DPO_DENOMINATOR_VAL],
		[MELT_DPO_VAL],
		[MELT_DPO_NUMERATOR_VAL],
		[MELT_DSO_VAL],
		[MELT_DSO_NUMERATOR_VAL]
	)
	
	SELECT
	
		S.[ACCT_ID],
		S.[MELT_ADJ_OPER_CF_VAL],
		S.[MELT_ADJEBITDA_BU_VAL],
		S.[MELT_ADJEBITDA_CORP_VAL],
		S.[MELT_CAPEX_VAL],
		S.[MELT_DII_VAL],
		S.[MELT_TOTAL_LABOR_COST_VAL],
		S.[MELT_END_CASH_BALANCE_VAL],
		S.[MELT_GP_VAL],
		S.[MELT_LEVERAGE_RATIO_VAL],
		S.[MELT_LT_DEBT_VAL],
		S.[MELT_NIA_VAL],
		S.[MELT_REVENUE_VAL],
		S.[MELT_DII_NUMERATOR_VAL],
		S.[MELT_DII_DPO_DENOMINATOR_VAL],
		S.[MELT_DPO_VAL],
		S.[MELT_DPO_NUMERATOR_VAL],
		S.[MELT_DSO_VAL],
		S.[MELT_DSO_NUMERATOR_VAL]

	 FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_FI_MELTGRP_CUR_D] S 
 LEFT JOIN  [GLOBAL_EDW].[dbo].[EDW_T_D_FI_MELTGRP_CUR_D] T
 ON T.[ACCT_ID] = S.[ACCT_ID]
 WHERE T.[ACCT_ID] IS NULL;
 END;