CREATE     PROCEDURE [Propelis].[Proc_MATRL_ENTERED]
AS
BEGIN
    -- Update existing records
    UPDATE T
    SET
    T.[Material Entered ID] = S.[MATRL_ID],
    T.[Material Entered Description] = S.[MATRL_DESC],
    T.[Material Entered Legacy Material ID] = S.[LGCY_MATRL_ID],
    T.[Material Entered Customer ID] = S.[CUST_ID],
    T.[Material Entered Material Category] = S.[MATRL_CTGRY],
    T.[Material Entered Material Type] = S.[MATRL_TYP],
    T.[Material Entered Group] = S.[MATRL_GROUP],
    T.[Material Entered Base Unit Of Measure] = S.[BASE_UNIT_OF_MEASUR],
    T.[Material Entered Industry Sector] = S.[INDUS_SECTOR],
    T.[Material Entered General Item Category Group] = S.[GENERAL_ITM_CTGRY_GROUP],
    T.[Material Entered Unit] = S.[UNIT],
    T.[Material Entered Gross Weight] = S.[GROSS_WGHT],
    T.[Material Entered Net Weight] = S.[NET_WGHT],
    T.[Material Entered Product Hierarchy] = S.[PRDT_HIERCHY],
    T.[Category of Material Entered Category] = S.[CTGRY],
    T.[Material Entered Brand] = S.[BRAND],
    T.[Material Entered Sub Brand] = S.[SUB_BRAND],
    T.[Material Entered Variant Obsolete] = S.[VARIANT_OBSOLET],
    T.[Material Entered Variant] = S.[VARIANT],
    T.[Material Entered Name 1] = S.[NAME_1],
    T.[Material Entered Pack Size] = S.[PACK_SIZE],
    T.[Material Entered Pack Type] = S.[PACK_TYP],
    T.[Material Entered Country Name] = S.[CNTRY_NAME],
    T.[Material Entered Print Method] = S.[PRNT_MTHD],
    T.[Material Entered Level 4 Product Category Code] = S.[LEVEL4_PRDT_CTGRY_CD],
    T.[Material Entered Level 4 Product Category Description] = S.[LEVEL4_PRDT_CTGRY_DESC],
    T.[Material Entered Level 3 Sub Family Code] = S.[LEVEL3_SUB_FAMILY_CD],
    T.[Material Entered Level 3 Sub Family Description] = S.[LEVEL3_SUB_FAMILY_DESC],
    T.[Material Entered Level 2 Family Code] = S.[LEVEL2_FAMILY_CD],
    T.[Material Entered Level 2 Family Description] = S.[LEVEL2_FAMILY_DESC],
    T.[Material Entered Level 1 Class Code] = S.[LEVEL1_CLASS_CD],
    T.[Material Entered Level 1 Class Description] = S.[LEVEL1_CLASS_DESC],
    T.[Material Entered Created Date] = S.[CREATED_DATE],
    T.[Material Entered Created User ID] = S.[CREATED_USR_ID],
    T.[Material Entered Updated Date] = S.[UPDTD_DATE],
    T.[Material Entered Updated User ID] = S.[UPDTD_USR_ID],
    T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
    T.[ETL_EFFECTV_BEGIN_DATE] = S.[ETL_EFFECTV_BEGIN_DATE],
    T.[ETL_EFFECTV_END_DATE] = S.[ETL_EFFECTV_END_DATE],
    T.[ETL_CURR_RCD_IND] = S.[ETL_CURR_RCD_IND],
    T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
    T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
    T.[Material Entered Group Description] = S.[MATRL_GROUP_DESC],
    T.[Material Entered Group Description 2] = S.[MATRL_GROUP_DESC_2],
    T.[Category of Material Entered Category Description] = S.[CTGRY_DESC],
    T.[Material Entered Brand Description] = S.[BRAND_DESC],
    T.[Material Entered Sub Brand Description] = S.[SUB_BRAND_DESC],
    T.[Material Entered Print Method Description] = S.[PRNT_MTHD_DESC],
    T.[Material Entered Level 5 Product Category Code] = S.[LEVEL5_PRDT_CTGRY_CD],
    T.[Material Entered Level 5 Product Category Code Description] = S.[LEVEL5_PRDT_CTGRY_DESC],
    T.[Material Entered Level 6 Product Category Code] = S.[LEVEL6_PRDT_CTGRY_CD],
    T.[Material Entered Level 6 Product Category Code Description] = S.[LEVEL6_PRDT_CTGRY_DESC],
    T.[Material Client Level Deletion Indicator] = S.[CLNT_LVL_DELETION_IND],
    T.[Material Entered PO UoM] = S.[PO_UOM],
    T.[Material Entered Basic] = S.[BASIC_MATRL],
    T.[Material Entered Industry Standard Description] = S.[INDUS_STD_DESC],
    T.[Material Entered Laboratory/Design Office] = S.[LABORATORY_DESIGN_OFFC],
    T.[Material Entered Laboratory/Design Office Description] = S.[LABORATORY_DESIGN_OFFC_DESC],
    T.[Material Entered Purchasing Value Key] = S.[PURNG_VAL_KEY],
    T.[Material Entered Storage Condition] = S.[STOR_COND],
    T.[Material Entered Storage Condition Description] = S.[STOR_COND_DESC],
    T.[Material Entered Temperature Conditions Indicator] = S.[TEMPERATURE_CONDITIONS_IND],
    T.[Material Entered Temperature Conditions Indicator Description] = S.[TEMPERATURE_CONDITIONS_IND_DESC],
    T.[Material Entered Transportation Group] = S.[TRANSTN_GROUP],
    T.[Material Entered Transportation Group Description] = S.[TRANSTN_GROUP_DESC],
    T.[Material Entered Hazardous Number] = S.[HAZARDOUS_MATRL_NUM],
    T.[Material Entered Source of Supply] = S.[SRC_OF_SUPLY],
    T.[Material Entered Source of Supply Description] = S.[SRC_OF_SUPLY_DESC],
    T.[Material Entered EAN/UPC Number] = S.[EAN_UPC_NO],
    T.[Material Entered EAN Category] = S.[EAN_CTGRY],
    T.[Material Entered EAN Category Description] = S.[EAN_CTGRY_DESC],
    T.[Material Entered Length] = S.[LNGTH],
    T.[Material Entered Width] = S.[WIDTH],
    T.[Material Entered Height] = S.[HGHT],
    T.[Material Entered UoD] = S.[UOD],
    T.[Material Entered External Group] = S.[EXTNL_MATRL_GROUP],
    T.[Material Entered External Group Description] = S.[EXTNL_MATRL_GROUP_DESC],
    T.[Material Entered Manufacturer Part Number] = S.[MANUFACTURER_PART_NUM],
    T.[Material Entered Dangerous Goods Indicator Profile] = S.[DANGEROUS_GOODS_IND_PROFILE],
    T.[Material Entered Dangerous Goods Ind Profile Desription] = S.[DANGEROUS_GOODS_IND_PROFILE_DES],
    T.[Material Entered Country of Origin] = S.[CNTRY_OF_ORIGIN],
    T.[Material Entered Country of Origin Description] = S.[CNTRY_OF_ORIGION_DESC],
    T.[Material Entered Quality Inspection Group] = S.[QUAL_INSPTN_GROUP],
    T.[Material Entered Quality Inspection Group Description] = S.[QUAL_INSPTN_GROUP_DESC],
    T.[Material Entered Material Category Description] = S.[MATRL_CTGRY_DESC],
    T.[Material Entered Material Type Description] = S.[MATRL_TYP_DESC],
    T.[Material Entered Product Hierarchy Description] = S.[PRDT_HIERCHY_DESC],
    T.[Material Entered Industry Sector Description] = S.[INDUS_SECTOR_DESC],
    T.[Material Entered General Item Category Group Description] = S.[GEN_ITM_CTGRY_GRP_DESC],
    T.[MATRL_SALES_TEXT] = S.[MATRL_SALES_TEXT],
    T.[CLASS_INTERNL_NUM] = S.[CLASS_INTERNL_NUM],
    T.[CLASS_NAME] = S.[CLASS_NAME],
    T.[CLASS_TYP] = S.[CLASS_TYP],
    T.[CLASS_TYP_DESC] = S.[CLASS_TYP_DESC],
    T.[CLASS_STATUS] = S.[CLASS_STATUS],
    T.[CLASS_STATUS_DESC] = S.[CLASS_STATUS_DESC],
    T.[CHARACTERISTIC_1_INTERNL_NUM] = S.[CHARACTERISTIC_1_INTERNL_NUM],
    T.[CHARACTERISTIC_1_NAME] = S.[CHARACTERISTIC_1_NAME],
    T.[CHARACTERISTIC_1_DESC] = S.[CHARACTERISTIC_1_DESC],
    T.[CHARACTERISTIC_1_VAL] = S.[CHARACTERISTIC_1_VAL],
    T.[CHARACTERISTIC_1_VAL_DESC] = S.[CHARACTERISTIC_1_VAL_DESC],
    T.[CHARACTERISTIC_2_INTERNL_NUM] = S.[CHARACTERISTIC_2_INTERNL_NUM],
    T.[CHARACTERISTIC_2_NAME] = S.[CHARACTERISTIC_2_NAME],
    T.[CHARACTERISTIC_2_DESC] = S.[CHARACTERISTIC_2_DESC],
    T.[CHARACTERISTIC_2_VAL] = S.[CHARACTERISTIC_2_VAL],
    T.[CHARACTERISTIC_2_VAL_DESC] = S.[CHARACTERISTIC_2_VAL_DESC],
    T.[CHARACTERISTIC_3_INTERNL_NUM] = S.[CHARACTERISTIC_3_INTERNL_NUM],
    T.[CHARACTERISTIC_3_NAME] = S.[CHARACTERISTIC_3_NAME],
    T.[CHARACTERISTIC_3_DESC] = S.[CHARACTERISTIC_3_DESC],
    T.[CHARACTERISTIC_3_VAL] = S.[CHARACTERISTIC_3_VAL],
    T.[CHARACTERISTIC_3_VAL_DESC] = S.[CHARACTERISTIC_3_VAL_DESC],
    T.[CHARACTERISTIC_4_INTERNL_NUM] = S.[CHARACTERISTIC_4_INTERNL_NUM],
    T.[CHARACTERISTIC_4_NAME] = S.[CHARACTERISTIC_4_NAME],
    T.[CHARACTERISTIC_4_DESC] = S.[CHARACTERISTIC_4_DESC],
    T.[CHARACTERISTIC_4_VAL] = S.[CHARACTERISTIC_4_VAL],
    T.[CHARACTERISTIC_4_VAL_DESC] = S.[CHARACTERISTIC_4_VAL_DESC],
    T.[CHARACTERISTIC_5_INTERNL_NUM] = S.[CHARACTERISTIC_5_INTERNL_NUM],
    T.[CHARACTERISTIC_5_NAME] = S.[CHARACTERISTIC_5_NAME],
    T.[CHARACTERISTIC_5_DESC] = S.[CHARACTERISTIC_5_DESC],
    T.[CHARACTERISTIC_5_VAL] = S.[CHARACTERISTIC_5_VAL],
    T.[CHARACTERISTIC_5_VAL_DESC] = S.[CHARACTERISTIC_5_VAL_DESC],
    T.[CHARACTERISTIC_6_INTERNL_NUM] = S.[CHARACTERISTIC_6_INTERNL_NUM],
    T.[CHARACTERISTIC_6_NAME] = S.[CHARACTERISTIC_6_NAME],
    T.[CHARACTERISTIC_6_DESC] = S.[CHARACTERISTIC_6_DESC],
    T.[CHARACTERISTIC_6_VAL] = S.[CHARACTERISTIC_6_VAL],
    T.[CHARACTERISTIC_6_VAL_DESC] = S.[CHARACTERISTIC_6_VAL_DESC],
    T.[CHARACTERISTIC_7_INTERNL_NUM] = S.[CHARACTERISTIC_7_INTERNL_NUM],
    T.[CHARACTERISTIC_7_NAME] = S.[CHARACTERISTIC_7_NAME],
    T.[CHARACTERISTIC_7_DESC] = S.[CHARACTERISTIC_7_DESC],
    T.[CHARACTERISTIC_7_VAL] = S.[CHARACTERISTIC_7_VAL],
    T.[CHARACTERISTIC_7_VAL_DESC] = S.[CHARACTERISTIC_7_VAL_DESC],
    T.[CHARACTERISTIC_8_INTERNL_NUM] = S.[CHARACTERISTIC_8_INTERNL_NUM],
    T.[CHARACTERISTIC_8_NAME] = S.[CHARACTERISTIC_8_NAME],
    T.[CHARACTERISTIC_8_DESC] = S.[CHARACTERISTIC_8_DESC],
    T.[CHARACTERISTIC_8_VAL] = S.[CHARACTERISTIC_8_VAL],
    T.[CHARACTERISTIC_8_VAL_DESC] = S.[CHARACTERISTIC_8_VAL_DESC],
    T.[CHARACTERISTIC_9_INTERNL_NUM] = S.[CHARACTERISTIC_9_INTERNL_NUM],
    T.[CHARACTERISTIC_9_NAME] = S.[CHARACTERISTIC_9_NAME],
    T.[CHARACTERISTIC_9_DESC] = S.[CHARACTERISTIC_9_DESC],
    T.[CHARACTERISTIC_9_VAL] = S.[CHARACTERISTIC_9_VAL],
    T.[CHARACTERISTIC_9_VAL_DESC] = S.[CHARACTERISTIC_9_VAL_DESC],
    T.[CHARACTERISTIC_10_INTERNL_NUM] = S.[CHARACTERISTIC_10_INTERNL_NUM],
    T.[CHARACTERISTIC_10_NAME] = S.[CHARACTERISTIC_10_NAME],
    T.[CHARACTERISTIC_10_DESC] = S.[CHARACTERISTIC_10_DESC],
    T.[CHARACTERISTIC_10_VAL] = S.[CHARACTERISTIC_10_VAL],
    T.[CHARACTERISTIC_10_VAL_DESC] = S.[CHARACTERISTIC_10_VAL_DESC],
    T.[CHARACTERISTIC_11_INTERNL_NUM] = S.[CHARACTERISTIC_11_INTERNL_NUM],
    T.[CHARACTERISTIC_11_NAME] = S.[CHARACTERISTIC_11_NAME],
    T.[CHARACTERISTIC_11_DESC] = S.[CHARACTERISTIC_11_DESC],
    T.[CHARACTERISTIC_11_VAL] = S.[CHARACTERISTIC_11_VAL],
    T.[CHARACTERISTIC_11_VAL_DESC] = S.[CHARACTERISTIC_11_VAL_DESC],
    T.[CHARACTERISTIC_12_INTERNL_NUM] = S.[CHARACTERISTIC_12_INTERNL_NUM],
    T.[CHARACTERISTIC_12_NAME] = S.[CHARACTERISTIC_12_NAME],
    T.[CHARACTERISTIC_12_DESC] = S.[CHARACTERISTIC_12_DESC],
    T.[CHARACTERISTIC_12_VAL] = S.[CHARACTERISTIC_12_VAL],
    T.[CHARACTERISTIC_12_VAL_DESC] = S.[CHARACTERISTIC_12_VAL_DESC],
    T.[CHARACTERISTIC_13_INTERNL_NUM] = S.[CHARACTERISTIC_13_INTERNL_NUM],
    T.[CHARACTERISTIC_13_NAME] = S.[CHARACTERISTIC_13_NAME],
    T.[CHARACTERISTIC_13_DESC] = S.[CHARACTERISTIC_13_DESC],
    T.[CHARACTERISTIC_13_VAL] = S.[CHARACTERISTIC_13_VAL],
    T.[CHARACTERISTIC_13_VAL_DESC] = S.[CHARACTERISTIC_13_VAL_DESC],
    T.[CHARACTERISTIC_14_INTERNL_NUM] = S.[CHARACTERISTIC_14_INTERNL_NUM],
    T.[CHARACTERISTIC_14_NAME] = S.[CHARACTERISTIC_14_NAME],
    T.[CHARACTERISTIC_14_DESC] = S.[CHARACTERISTIC_14_DESC],
    T.[CHARACTERISTIC_14_VAL] = S.[CHARACTERISTIC_14_VAL],
    T.[CHARACTERISTIC_14_VAL_DESC] = S.[CHARACTERISTIC_14_VAL_DESC],
    T.[CHARACTERISTIC_15_INTERNL_NUM] = S.[CHARACTERISTIC_15_INTERNL_NUM],
    T.[CHARACTERISTIC_15_NAME] = S.[CHARACTERISTIC_15_NAME],
    T.[CHARACTERISTIC_15_DESC] = S.[CHARACTERISTIC_15_DESC],
    T.[CHARACTERISTIC_15_VAL] = S.[CHARACTERISTIC_15_VAL],
    T.[CHARACTERISTIC_15_VAL_DESC] = S.[CHARACTERISTIC_15_VAL_DESC],
    T.[CHARACTERISTIC_16_INTERNL_NUM] = S.[CHARACTERISTIC_16_INTERNL_NUM],
    T.[CHARACTERISTIC_16_NAME] = S.[CHARACTERISTIC_16_NAME],
    T.[CHARACTERISTIC_16_DESC] = S.[CHARACTERISTIC_16_DESC],
    T.[CHARACTERISTIC_16_VAL] = S.[CHARACTERISTIC_16_VAL],
    T.[CHARACTERISTIC_16_VAL_DESC] = S.[CHARACTERISTIC_16_VAL_DESC],
    T.[CHARACTERISTIC_17_INTERNL_NUM] = S.[CHARACTERISTIC_17_INTERNL_NUM],
    T.[CHARACTERISTIC_17_NAME] = S.[CHARACTERISTIC_17_NAME],
    T.[CHARACTERISTIC_17_DESC] = S.[CHARACTERISTIC_17_DESC],
    T.[CHARACTERISTIC_17_VAL] = S.[CHARACTERISTIC_17_VAL],
    T.[CHARACTERISTIC_17_VAL_DESC] = S.[CHARACTERISTIC_17_VAL_DESC],
    T.[CHARACTERISTIC_18_INTERNL_NUM] = S.[CHARACTERISTIC_18_INTERNL_NUM],
    T.[CHARACTERISTIC_18_NAME] = S.[CHARACTERISTIC_18_NAME],
    T.[CHARACTERISTIC_18_DESC] = S.[CHARACTERISTIC_18_DESC],
    T.[CHARACTERISTIC_18_VAL] = S.[CHARACTERISTIC_18_VAL],
    T.[CHARACTERISTIC_18_VAL_DESC] = S.[CHARACTERISTIC_18_VAL_DESC],
    T.[CHARACTERISTIC_19_INTERNL_NUM] = S.[CHARACTERISTIC_19_INTERNL_NUM],
    T.[CHARACTERISTIC_19_NAME] = S.[CHARACTERISTIC_19_NAME],
    T.[CHARACTERISTIC_19_DESC] = S.[CHARACTERISTIC_19_DESC],
    T.[CHARACTERISTIC_19_VAL] = S.[CHARACTERISTIC_19_VAL],
    T.[CHARACTERISTIC_19_VAL_DESC] = S.[CHARACTERISTIC_19_VAL_DESC],
    T.[CHARACTERISTIC_20_INTERNL_NUM] = S.[CHARACTERISTIC_20_INTERNL_NUM],
    T.[CHARACTERISTIC_20_NAME] = S.[CHARACTERISTIC_20_NAME],
    T.[CHARACTERISTIC_20_DESC] = S.[CHARACTERISTIC_20_DESC],
    T.[CHARACTERISTIC_20_VAL] = S.[CHARACTERISTIC_20_VAL],
    T.[CHARACTERISTIC_20_VAL_DESC] = S.[CHARACTERISTIC_20_VAL_DESC],
    T.[CHARACTERISTIC_21_INTERNL_NUM] = S.[CHARACTERISTIC_21_INTERNL_NUM],
    T.[CHARACTERISTIC_21_NAME] = S.[CHARACTERISTIC_21_NAME],
    T.[CHARACTERISTIC_21_DESC] = S.[CHARACTERISTIC_21_DESC],
	T.[CHARACTERISTIC_21_VAL] = S.[CHARACTERISTIC_21_VAL],
    T.[CHARACTERISTIC_21_VAL_DESC] = S.[CHARACTERISTIC_21_VAL_DESC],
	T.[CHARACTERISTIC_22_INTERNL_NUM] = S.[CHARACTERISTIC_22_INTERNL_NUM],
    T.[CHARACTERISTIC_22_NAME] = S.[CHARACTERISTIC_22_NAME],
    T.[CHARACTERISTIC_22_DESC] = S.[CHARACTERISTIC_22_DESC],
	T.[CHARACTERISTIC_22_VAL_DESC] = S.[CHARACTERISTIC_22_VAL_DESC],
    T.[CHARACTERISTIC_23_INTERNL_NUM] = S.[CHARACTERISTIC_23_INTERNL_NUM],
	T.[CHARACTERISTIC_23_NAME] = S.[CHARACTERISTIC_23_NAME],
    T.[CHARACTERISTIC_23_DESC] = S.[CHARACTERISTIC_23_DESC],
	T.[CHARACTERISTIC_23_VAL] = S.[CHARACTERISTIC_23_VAL],
    T.[CHARACTERISTIC_23_VAL_DESC] = S.[CHARACTERISTIC_23_VAL_DESC],
    T.[MATRL_DESC_ITALIAN] = S.[MATRL_DESC_ITALIAN],
	T.[MATRL_X_PLNT_STATUS] = S.[MATRL_X_PLNT_STATUS],
    T.[MATRL_X_PLNT_DESC] = S.[MATRL_X_PLNT_DESC]
	
    FROM [GLOBAL_EDW].[Propelis].[MATRL_ENTERED] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_MATERIAL_CUR_D] S
        ON T.[MATRL_KEY] = S.[MATRL_KEY];

    -- Insert new records
  INSERT INTO [GLOBAL_EDW].[Propelis].[MATRL_ENTERED]
(
    [MATRL_KEY],
    [Material Entered ID],
    [Material Entered Description],
    [Material Entered Legacy Material ID],
    [Material Entered Customer ID],
    [Material Entered Material Category],
    [Material Entered Material Type],
    [Material Entered Group],
    [Material Entered Base Unit Of Measure],
    [Material Entered Industry Sector],
    [Material Entered General Item Category Group],
    [Material Entered Unit],
    [Material Entered Gross Weight],
    [Material Entered Net Weight],
    [Material Entered Product Hierarchy],
    [Category of Material Entered Category],
    [Material Entered Brand],
    [Material Entered Sub Brand],
    [Material Entered Variant Obsolete],
    [Material Entered Variant],
    [Material Entered Name 1],
    [Material Entered Pack Size],
    [Material Entered Pack Type],
    [Material Entered Country Name],
    [Material Entered Print Method],
    [Material Entered Level 4 Product Category Code],
    [Material Entered Level 4 Product Category Description],
    [Material Entered Level 3 Sub Family Code],
    [Material Entered Level 3 Sub Family Description],
    [Material Entered Level 2 Family Code],
    [Material Entered Level 2 Family Description],
    [Material Entered Level 1 Class Code],
    [Material Entered Level 1 Class Description],
    [Material Entered Created Date],
    [Material Entered Created User ID],
    [Material Entered Updated Date],
    [Material Entered Updated User ID],
    [ETL_SRC_SYS_CD],
    [ETL_EFFECTV_BEGIN_DATE],
    [ETL_EFFECTV_END_DATE],
    [ETL_CURR_RCD_IND],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Material Entered Group Description],
    [Material Entered Group Description 2],
    [Category of Material Entered Category Description],
    [Material Entered Brand Description],
    [Material Entered Sub Brand Description],
    [Material Entered Print Method Description],
    [Material Entered Level 5 Product Category Code],
    [Material Entered Level 5 Product Category Code Description],
    [Material Entered Level 6 Product Category Code],
    [Material Entered Level 6 Product Category Code Description],
    [Material Client Level Deletion Indicator],
    [Material Entered PO UoM],
    [Material Entered Basic],
    [Material Entered Industry Standard Description],
    [Material Entered Laboratory/Design Office],
    [Material Entered Laboratory/Design Office Description],
    [Material Entered Purchasing Value Key],
    [Material Entered Storage Condition],
    [Material Entered Storage Condition Description],
    [Material Entered Temperature Conditions Indicator],
    [Material Entered Temperature Conditions Indicator Description],
    [Material Entered Transportation Group],
    [Material Entered Transportation Group Description],
    [Material Entered Hazardous Number],
    [Material Entered Source of Supply],
    [Material Entered Source of Supply Description],
    [Material Entered EAN/UPC Number],
    [Material Entered EAN Category],
    [Material Entered EAN Category Description],
    [Material Entered Length],
    [Material Entered Width],
    [Material Entered Height],
    [Material Entered UoD],
    [Material Entered External Group],
    [Material Entered External Group Description],
    [Material Entered Manufacturer Part Number],
    [Material Entered Dangerous Goods Indicator Profile],
    [Material Entered Dangerous Goods Ind Profile Desription],
    [Material Entered Country of Origin],
    [Material Entered Country of Origin Description],
    [Material Entered Quality Inspection Group],
    [Material Entered Quality Inspection Group Description],
    [Material Entered Material Category Description],
    [Material Entered Material Type Description],
    [Material Entered Product Hierarchy Description],
    [Material Entered Industry Sector Description],
    [Material Entered General Item Category Group Description],
    [MATRL_SALES_TEXT],
    [CHARACTERISTIC_22_VAL],
    [CLASS_INTERNL_NUM],
    [CLASS_NAME],
    [CLASS_TYP],
    [CLASS_TYP_DESC],
    [CLASS_STATUS],
    [CLASS_STATUS_DESC],
    [CHARACTERISTIC_1_INTERNL_NUM],
    [CHARACTERISTIC_1_NAME],
    [CHARACTERISTIC_1_DESC],
    [CHARACTERISTIC_1_VAL],
    [CHARACTERISTIC_1_VAL_DESC],
    [CHARACTERISTIC_2_INTERNL_NUM],
    [CHARACTERISTIC_2_NAME],
    [CHARACTERISTIC_2_DESC],
    [CHARACTERISTIC_2_VAL],
    [CHARACTERISTIC_2_VAL_DESC],
    [CHARACTERISTIC_3_INTERNL_NUM],
    [CHARACTERISTIC_3_NAME],
    [CHARACTERISTIC_3_DESC],
    [CHARACTERISTIC_3_VAL],
    [CHARACTERISTIC_3_VAL_DESC],
    [CHARACTERISTIC_4_INTERNL_NUM],
    [CHARACTERISTIC_4_NAME],
    [CHARACTERISTIC_4_DESC],
    [CHARACTERISTIC_4_VAL],
    [CHARACTERISTIC_4_VAL_DESC],
    [CHARACTERISTIC_5_INTERNL_NUM],
    [CHARACTERISTIC_5_NAME],
    [CHARACTERISTIC_5_DESC],
    [CHARACTERISTIC_5_VAL],
    [CHARACTERISTIC_5_VAL_DESC],
    [CHARACTERISTIC_6_INTERNL_NUM],
    [CHARACTERISTIC_6_NAME],
    [CHARACTERISTIC_6_DESC],
    [CHARACTERISTIC_6_VAL],
    [CHARACTERISTIC_6_VAL_DESC],
    [CHARACTERISTIC_7_INTERNL_NUM],
    [CHARACTERISTIC_7_NAME],
    [CHARACTERISTIC_7_DESC],
    [CHARACTERISTIC_7_VAL],
    [CHARACTERISTIC_7_VAL_DESC],
    [CHARACTERISTIC_8_INTERNL_NUM],
    [CHARACTERISTIC_8_NAME],
    [CHARACTERISTIC_8_DESC],
    [CHARACTERISTIC_8_VAL],
    [CHARACTERISTIC_8_VAL_DESC],
    [CHARACTERISTIC_9_INTERNL_NUM],
    [CHARACTERISTIC_9_NAME],
    [CHARACTERISTIC_9_DESC],
    [CHARACTERISTIC_9_VAL],
    [CHARACTERISTIC_9_VAL_DESC],
    [CHARACTERISTIC_10_INTERNL_NUM],
    [CHARACTERISTIC_10_NAME],
    [CHARACTERISTIC_10_DESC],
    [CHARACTERISTIC_10_VAL],
    [CHARACTERISTIC_10_VAL_DESC],
    [CHARACTERISTIC_11_INTERNL_NUM],
    [CHARACTERISTIC_11_NAME],
    [CHARACTERISTIC_11_DESC],
    [CHARACTERISTIC_11_VAL],
    [CHARACTERISTIC_11_VAL_DESC],
    [CHARACTERISTIC_12_INTERNL_NUM],
    [CHARACTERISTIC_12_NAME],
    [CHARACTERISTIC_12_DESC],
    [CHARACTERISTIC_12_VAL],
    [CHARACTERISTIC_12_VAL_DESC],
    [CHARACTERISTIC_13_INTERNL_NUM],
    [CHARACTERISTIC_13_NAME],
    [CHARACTERISTIC_13_DESC],
    [CHARACTERISTIC_13_VAL],
    [CHARACTERISTIC_13_VAL_DESC],
    [CHARACTERISTIC_14_INTERNL_NUM],
    [CHARACTERISTIC_14_NAME],
    [CHARACTERISTIC_14_DESC],
    [CHARACTERISTIC_14_VAL],
    [CHARACTERISTIC_14_VAL_DESC],
    [CHARACTERISTIC_15_INTERNL_NUM],
    [CHARACTERISTIC_15_NAME],
    [CHARACTERISTIC_15_DESC],
    [CHARACTERISTIC_15_VAL],
    [CHARACTERISTIC_15_VAL_DESC],
    [CHARACTERISTIC_16_INTERNL_NUM],
    [CHARACTERISTIC_16_NAME],
    [CHARACTERISTIC_16_DESC],
    [CHARACTERISTIC_16_VAL],
    [CHARACTERISTIC_16_VAL_DESC],
    [CHARACTERISTIC_17_INTERNL_NUM],
    [CHARACTERISTIC_17_NAME],
    [CHARACTERISTIC_17_DESC],
    [CHARACTERISTIC_17_VAL],
    [CHARACTERISTIC_17_VAL_DESC],
    [CHARACTERISTIC_18_INTERNL_NUM],
    [CHARACTERISTIC_18_NAME],
    [CHARACTERISTIC_18_DESC],
    [CHARACTERISTIC_18_VAL],
    [CHARACTERISTIC_18_VAL_DESC],
    [CHARACTERISTIC_19_INTERNL_NUM],
    [CHARACTERISTIC_19_NAME],
    [CHARACTERISTIC_19_DESC],
    [CHARACTERISTIC_19_VAL],
    [CHARACTERISTIC_19_VAL_DESC],
    [CHARACTERISTIC_20_INTERNL_NUM],
    [CHARACTERISTIC_20_NAME],
    [CHARACTERISTIC_20_DESC],
    [CHARACTERISTIC_20_VAL],
    [CHARACTERISTIC_20_VAL_DESC],
    [CHARACTERISTIC_21_INTERNL_NUM],
    [CHARACTERISTIC_21_NAME],
    [CHARACTERISTIC_21_DESC],
    [CHARACTERISTIC_21_VAL],
    [CHARACTERISTIC_21_VAL_DESC],
    [CHARACTERISTIC_22_INTERNL_NUM],
    [CHARACTERISTIC_22_NAME],
    [CHARACTERISTIC_22_DESC],
    [CHARACTERISTIC_22_VAL_DESC],
    [CHARACTERISTIC_23_INTERNL_NUM],
    [CHARACTERISTIC_23_NAME],
    [CHARACTERISTIC_23_DESC],
    [CHARACTERISTIC_23_VAL],
    [CHARACTERISTIC_23_VAL_DESC],
    [MATRL_DESC_ITALIAN],
    [MATRL_X_PLNT_STATUS],
    [MATRL_X_PLNT_DESC]

)

 SELECT
    S.[MATRL_KEY],
    S.[MATRL_ID],
    S.[MATRL_DESC],
    S.[LGCY_MATRL_ID],
    S.[CUST_ID],
    S.[MATRL_CTGRY],
    S.[MATRL_TYP],
    S.[MATRL_GROUP],
    S.[BASE_UNIT_OF_MEASUR],
    S.[INDUS_SECTOR],
    S.[GENERAL_ITM_CTGRY_GROUP],
    S.[UNIT],
    S.[GROSS_WGHT],
    S.[NET_WGHT],
    S.[PRDT_HIERCHY],
    S.[CTGRY],
    S.[BRAND],
    S.[SUB_BRAND],
    S.[VARIANT_OBSOLET],
    S.[VARIANT],
    S.[NAME_1],
    S.[PACK_SIZE],
    S.[PACK_TYP],
    S.[CNTRY_NAME],
    S.[PRNT_MTHD],
    S.[LEVEL4_PRDT_CTGRY_CD],
    S.[LEVEL4_PRDT_CTGRY_DESC],
    S.[LEVEL3_SUB_FAMILY_CD],
    S.[LEVEL3_SUB_FAMILY_DESC],
    S.[LEVEL2_FAMILY_CD],
    S.[LEVEL2_FAMILY_DESC],
    S.[LEVEL1_CLASS_CD],
    S.[LEVEL1_CLASS_DESC],
    S.[CREATED_DATE],
    S.[CREATED_USR_ID],
    S.[UPDTD_DATE],
    S.[UPDTD_USR_ID],
    S.[ETL_SRC_SYS_CD],
    S.[ETL_EFFECTV_BEGIN_DATE],
    S.[ETL_EFFECTV_END_DATE],
    S.[ETL_CURR_RCD_IND],
    S.[ETL_CREATED_TS],
    S.[ETL_UPDTD_TS],
    S.[MATRL_GROUP_DESC],
    S.[MATRL_GROUP_DESC_2],
    S.[CTGRY_DESC],
    S.[BRAND_DESC],
    S.[SUB_BRAND_DESC],
    S.[PRNT_MTHD_DESC],
    S.[LEVEL5_PRDT_CTGRY_CD],
    S.[LEVEL5_PRDT_CTGRY_DESC],
    S.[LEVEL6_PRDT_CTGRY_CD],
    S.[LEVEL6_PRDT_CTGRY_DESC],
    S.[CLNT_LVL_DELETION_IND],
    S.[PO_UOM],
    S.[BASIC_MATRL],
    S.[INDUS_STD_DESC],
    S.[LABORATORY_DESIGN_OFFC],
    S.[LABORATORY_DESIGN_OFFC_DESC],
    S.[PURNG_VAL_KEY],
    S.[STOR_COND],
    S.[STOR_COND_DESC],
    S.[TEMPERATURE_CONDITIONS_IND],
    S.[TEMPERATURE_CONDITIONS_IND_DESC],
    S.[TRANSTN_GROUP],
    S.[TRANSTN_GROUP_DESC],
    S.[HAZARDOUS_MATRL_NUM],
    S.[SRC_OF_SUPLY],
    S.[SRC_OF_SUPLY_DESC],
    S.[EAN_UPC_NO],
    S.[EAN_CTGRY],
    S.[EAN_CTGRY_DESC],
    S.[LNGTH],
    S.[WIDTH],
    S.[HGHT],
    S.[UOD],
    S.[EXTNL_MATRL_GROUP],
    S.[EXTNL_MATRL_GROUP_DESC],
    S.[MANUFACTURER_PART_NUM],
    S.[DANGEROUS_GOODS_IND_PROFILE],
    S.[DANGEROUS_GOODS_IND_PROFILE_DES],
    S.[CNTRY_OF_ORIGIN],
    S.[CNTRY_OF_ORIGION_DESC],
    S.[QUAL_INSPTN_GROUP],
    S.[QUAL_INSPTN_GROUP_DESC],
    S.[MATRL_CTGRY_DESC],
    S.[MATRL_TYP_DESC],
    S.[PRDT_HIERCHY_DESC],
    S.[INDUS_SECTOR_DESC],
    S.[GEN_ITM_CTGRY_GRP_DESC],
    S.[MATRL_SALES_TEXT],
    S.[CHARACTERISTIC_22_VAL],
    S.[CLASS_INTERNL_NUM],
    S.[CLASS_NAME],
    S.[CLASS_TYP],
    S.[CLASS_TYP_DESC],
    S.[CLASS_STATUS],
    S.[CLASS_STATUS_DESC],
    S.[CHARACTERISTIC_1_INTERNL_NUM],
    S.[CHARACTERISTIC_1_NAME],
    S.[CHARACTERISTIC_1_DESC],
    S.[CHARACTERISTIC_1_VAL],
    S.[CHARACTERISTIC_1_VAL_DESC],
    S.[CHARACTERISTIC_2_INTERNL_NUM],
    S.[CHARACTERISTIC_2_NAME],
    S.[CHARACTERISTIC_2_DESC],
    S.[CHARACTERISTIC_2_VAL],
    S.[CHARACTERISTIC_2_VAL_DESC],
    S.[CHARACTERISTIC_3_INTERNL_NUM],
    S.[CHARACTERISTIC_3_NAME],
    S.[CHARACTERISTIC_3_DESC],
    S.[CHARACTERISTIC_3_VAL],
    S.[CHARACTERISTIC_3_VAL_DESC],
    S.[CHARACTERISTIC_4_INTERNL_NUM],
    S.[CHARACTERISTIC_4_NAME],
    S.[CHARACTERISTIC_4_DESC],
    S.[CHARACTERISTIC_4_VAL],
    S.[CHARACTERISTIC_4_VAL_DESC],
    S.[CHARACTERISTIC_5_INTERNL_NUM],
    S.[CHARACTERISTIC_5_NAME],
    S.[CHARACTERISTIC_5_DESC],
    S.[CHARACTERISTIC_5_VAL],
    S.[CHARACTERISTIC_5_VAL_DESC],
    S.[CHARACTERISTIC_6_INTERNL_NUM],
    S.[CHARACTERISTIC_6_NAME],
    S.[CHARACTERISTIC_6_DESC],
    S.[CHARACTERISTIC_6_VAL],
    S.[CHARACTERISTIC_6_VAL_DESC],
    S.[CHARACTERISTIC_7_INTERNL_NUM],
    S.[CHARACTERISTIC_7_NAME],
    S.[CHARACTERISTIC_7_DESC],
    S.[CHARACTERISTIC_7_VAL],
    S.[CHARACTERISTIC_7_VAL_DESC],
    S.[CHARACTERISTIC_8_INTERNL_NUM],
    S.[CHARACTERISTIC_8_NAME],
    S.[CHARACTERISTIC_8_DESC],
    S.[CHARACTERISTIC_8_VAL],
    S.[CHARACTERISTIC_8_VAL_DESC],
    S.[CHARACTERISTIC_9_INTERNL_NUM],
    S.[CHARACTERISTIC_9_NAME],
    S.[CHARACTERISTIC_9_DESC],
    S.[CHARACTERISTIC_9_VAL],
    S.[CHARACTERISTIC_9_VAL_DESC],
    S.[CHARACTERISTIC_10_INTERNL_NUM],
    S.[CHARACTERISTIC_10_NAME],
    S.[CHARACTERISTIC_10_DESC],
    S.[CHARACTERISTIC_10_VAL],
    S.[CHARACTERISTIC_10_VAL_DESC],
    S.[CHARACTERISTIC_11_INTERNL_NUM],
    S.[CHARACTERISTIC_11_NAME],
    S.[CHARACTERISTIC_11_DESC],
    S.[CHARACTERISTIC_11_VAL],
    S.[CHARACTERISTIC_11_VAL_DESC],
    S.[CHARACTERISTIC_12_INTERNL_NUM],
    S.[CHARACTERISTIC_12_NAME],
    S.[CHARACTERISTIC_12_DESC],
    S.[CHARACTERISTIC_12_VAL],
    S.[CHARACTERISTIC_12_VAL_DESC],
    S.[CHARACTERISTIC_13_INTERNL_NUM],
    S.[CHARACTERISTIC_13_NAME],
    S.[CHARACTERISTIC_13_DESC],
    S.[CHARACTERISTIC_13_VAL],
    S.[CHARACTERISTIC_13_VAL_DESC],
    S.[CHARACTERISTIC_14_INTERNL_NUM],
    S.[CHARACTERISTIC_14_NAME],
    S.[CHARACTERISTIC_14_DESC],
    S.[CHARACTERISTIC_14_VAL],
    S.[CHARACTERISTIC_14_VAL_DESC],
    S.[CHARACTERISTIC_15_INTERNL_NUM],
    S.[CHARACTERISTIC_15_NAME],
    S.[CHARACTERISTIC_15_DESC],
    S.[CHARACTERISTIC_15_VAL],
    S.[CHARACTERISTIC_15_VAL_DESC],
    S.[CHARACTERISTIC_16_INTERNL_NUM],
    S.[CHARACTERISTIC_16_NAME],
    S.[CHARACTERISTIC_16_DESC],
    S.[CHARACTERISTIC_16_VAL],
    S.[CHARACTERISTIC_16_VAL_DESC],
    S.[CHARACTERISTIC_17_INTERNL_NUM],
    S.[CHARACTERISTIC_17_NAME],
    S.[CHARACTERISTIC_17_DESC],
    S.[CHARACTERISTIC_17_VAL],
    S.[CHARACTERISTIC_17_VAL_DESC],
    S.[CHARACTERISTIC_18_INTERNL_NUM],
    S.[CHARACTERISTIC_18_NAME],
    S.[CHARACTERISTIC_18_DESC],
    S.[CHARACTERISTIC_18_VAL],
    S.[CHARACTERISTIC_18_VAL_DESC],
    S.[CHARACTERISTIC_19_INTERNL_NUM],
    S.[CHARACTERISTIC_19_NAME],
    S.[CHARACTERISTIC_19_DESC],
    S.[CHARACTERISTIC_19_VAL],
    S.[CHARACTERISTIC_19_VAL_DESC],
    S.[CHARACTERISTIC_20_INTERNL_NUM],
    S.[CHARACTERISTIC_20_NAME],
    S.[CHARACTERISTIC_20_DESC],
    S.[CHARACTERISTIC_20_VAL],
    S.[CHARACTERISTIC_20_VAL_DESC],
    S.[CHARACTERISTIC_21_INTERNL_NUM],
    S.[CHARACTERISTIC_21_NAME],
    S.[CHARACTERISTIC_21_DESC],
    S.[CHARACTERISTIC_21_VAL],
    S.[CHARACTERISTIC_21_VAL_DESC],
    S.[CHARACTERISTIC_22_INTERNL_NUM],
    S.[CHARACTERISTIC_22_NAME],
    S.[CHARACTERISTIC_22_DESC],
    S.[CHARACTERISTIC_22_VAL_DESC],
    S.[CHARACTERISTIC_23_INTERNL_NUM],
    S.[CHARACTERISTIC_23_NAME],
    S.[CHARACTERISTIC_23_DESC],
    S.[CHARACTERISTIC_23_VAL],
    S.[CHARACTERISTIC_23_VAL_DESC],
    S.[MATRL_DESC_ITALIAN],
    S.[MATRL_X_PLNT_STATUS],
    S.[MATRL_X_PLNT_DESC]   
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_MATERIAL_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[MATRL_ENTERED] T
        ON T.[MATRL_KEY] = S.[MATRL_KEY]
    WHERE T.[MATRL_KEY] IS NULL;
END