CREATE   PROCEDURE [Propelis].[Proc_BASELINE_DUE_DATE] 
AS
BEGIN  
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Baseline Due Date] = S.[THE_DATE],
        T.[Baseline Due Fiscal Year] = S.[FISCAL_YR],
        T.[Baseline Due Fiscal Period Number] = S.[FISCAL_PER_NUM],
        T.[Baseline Due Fiscal Period] = S.[FISCAL_PER_CD],
        T.[Baseline Due Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Baseline Due Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Baseline Due Calendar Year] = S.[CLNDR_YR],
        T.[Baseline Due Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Baseline Due Calendar Month] = S.[CLNDR_MNTH_CD],
        T.[Baseline Due Calendar Month Description] = S.[CLNDR_MNTH_DESC],
        T.[Baseline Due Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[Baseline Due Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Baseline Due Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Baseline Due Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Baseline Due Calendar Day In Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Baseline Due Calendar Day In Year] = S.[CLNDR_DAY_IN_YR],
        T.[Baseline Due Calendar Week] = S.[CLNDR_WK],
        T.[Baseline Due Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Baseline Due Calendar Days In Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Baseline Due Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Baseline Due Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Baseline Due Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Baseline Due Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Baseline Due Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Baseline Due Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Baseline Due Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Baseline Due Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Baseline Due Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Baseline Due Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Baseline Due Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Baseline Due Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Baseline Due Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Baseline Due Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Baseline Due Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Baseline Due Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Baseline Due Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Baseline Due Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Baseline Due Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Baseline Due Day in Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Baseline Due Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Clearing Fiscal Week] = S.[FISCAL_WK],
        T.[Baseline Due Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Baseline Due Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Baseline Due Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Baseline Due Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Baseline Due Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Baseline Due Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Baseline Due Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Baseline Due Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG],
        T.[Baseline Due Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Baseline Due Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME]
    FROM [GLOBAL_EDW].[Propelis].[BASELINE_DUE_DATE] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];

    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[BASELINE_DUE_DATE] (
        [DATE_KEY],
        [Baseline Due Date],
        [Baseline Due Fiscal Year],
        [Baseline Due Fiscal Period Number],
        [Baseline Due Fiscal Period],
        [Baseline Due Fiscal Quarter Number],
        [Baseline Due Fiscal Quarter Code],
        [Baseline Due Calendar Year],
        [Baseline Due Calendar Month Number],
        [Baseline Due Calendar Month],
        [Baseline Due Calendar Month Description],
        [Baseline Due Calendar Quarter Number],
        [Baseline Due Calendar Quarter Code],
        [Baseline Due Calendar Weekday Number],
        [Baseline Due Calendar Weekday Name],
        [Baseline Due Calendar Day In Month],
        [Baseline Due Calendar Day In Year],
        [Baseline Due Calendar Week],
        [Baseline Due Calendar Month In Quarter Number],
        [Baseline Due Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Baseline Due Current Day Flag],
        [Baseline Due Current Day Minus 1 Flag],
        [Baseline Due Current Calendar Week Flag],
        [Baseline Due Current Calendar Week Minus 1 Flag],
        [Baseline Due Current Month Flag],
        [Baseline Due Current Month Minus 1 Flag],
        [Baseline Due Current Month Minus 2 Flag],
        [Baseline Due Current Month Minus 12 Flag],
        [Baseline Due Current Quarter Flag],
        [Baseline Due Current Quarter Minus 1 Flag],
        [Baseline Due Current Quarter Minus 4 Flag],
        [Baseline Due Current Calendar Year Flag],
        [Baseline Due Current Calendar Year Minus 1 Flag],
        [Baseline Due Current Calendar Year Minus 2 Flag],
        [Baseline Due Current Calendar Year Plus 1 Flag],
        [Baseline Due Current Fiscal Year Flag],
        [Baseline Due Current Fiscal Year Minus 1 Flag],
        [Baseline Due Current Fiscal Year Minus 2 Flag],
        [Baseline Due Current Fiscal Year Plus 1 Flag],
        [Baseline Due Day in Fiscal Year],
        [Baseline Due Date Is Weekday],
        [Clearing Fiscal Week],
        [Baseline Due Current Fiscal Week Flag],
        [Baseline Due Current Fiscal Week Minus 1 Flag],
        [Baseline Due Current Fiscal Week Minus 2 Flag],
        [Baseline Due Current Fiscal Week Minus 3 Flag],
        [Baseline Due Current Fiscal Week Minus 4 Flag],
        [Baseline Due Current Fiscal Week Minus 5 Flag],
        [Baseline Due Current Fiscal Week Minus 6 Flag],
        [Baseline Due Current Fiscal Week Minus 7 Flag],
        [Baseline Due Fiscal Weekday Number],
        [Baseline Due Fiscal Weekday Name]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[BASELINE_DUE_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;

END