CREATE       PROCEDURE [Propelis].[Proc_PARENT_INVOICE]
AS
BEGIN

    ----------------------------------------------------------------------
    -- Update existing records in target table
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[Parent Invoice Sales Order Invoice ID] = S.[SALES_ORDER_INVC_ID],
        T.[Parent Invoice Company Code] = S.[CMPNY_CD],
        T.[Parent Invoice Billing Type Code] = S.[BILLING_TYP_CD],
        T.[Parent Invoice Billing Category] = S.[BILLING_CTGRY],
        T.[Parent Invoice SD Document Category] = S.[SD_DOCMT_CTGRY],
        T.[Parent Invoice Sales Organization] = S.[SALES_ORGZTN],
        T.[Parent Invoice Distribution Channel] = S.[DISTRBN_CHNL],
        T.[Parent Invoice Divison] = S.[DIVISON],
        T.[Parent Invoice Parent Invoice Pricing Procedure in Pricing] = S.[PRICING_PROC],
        T.[Parent Invoice Document Condition Number] = S.[DOCMT_COND_NUM],
        T.[Parent Invoice Shipping Condition] = S.[SHIPG_COND],
        T.[Parent Invoice Price Group] = S.[PRICE_GROUP],
        T.[Parent Invoice Customer Group] = S.[CUST_GROUP],
        T.[Parent Invoice Price List] = S.[PRICE_LIST],
        T.[Parent Invoice Payment Reference] = S.[PYMT_REF],
        T.[Parent Invoice Payment Terms] = S.[PYMT_TRMS],
        T.[Parent Invoice Incoterms] = S.[INCOTERMS],
        T.[Parent Invoice Incoterms 2] = S.[INCOTERMS2],
        T.[Parent Invoice Exchange Rate] = S.[EXCHG_RT],
        T.[Parent Invoice Net Value] = S.[NET_VAL],
        T.[Parent Invoice Statistical Currency] = S.[STATISTICAL_CRNCY],
        T.[Parent Invoice List Type] = S.[INVC_LIST_TYP],
        T.[Parent Invoice Reference] = S.[REF],
        T.[Parent Invoice Parent Invoice Date] = S.[INVC_DATE],
        T.[Parent Invoice Created Date] = S.[CREATED_DATE],
        T.[Parent Invoice Created User ID] = S.[CREATED_USR_ID],
        T.[Parent Invoice Updated Date] = S.[UPDTD_DATE],
        T.[Parent Invoice Updated User ID] = S.[UPDTD_USR_ID],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE] = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE] = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND] = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Parent Invoice Billing Document Cancelled Indicator] = S.[BILLING_DOCMT_CANCELLED_IND],
        T.[Parent Invoice Creation Date] = S.[CREATION_DATE],
        T.[Parent Invoice Changed On Date] = S.[CHANGED_ON_DATE],
        T.[Parent Invoice Customer Purchase Order Number] = S.[CUST_PURCHS_ORDER_NUM],
        T.[Parent Invoice Accounting Transfer Status] = S.[ACCTNG_TRSFR_STATUS],
        T.[Parent Invoice Currency Key of Credit Control Area] = S.[CRNCY_KEY_OF_CREDIT_CTRL_AREA],
        T.[Parent Invoice Accounting Document Number] = S.[ACCTNG_DOCMT_NUM],
        T.[Parent Invoice SD Document Currency] = S.[SD_DOCMT_CRNCY_DESC],
        T.[Parent Invoice Company Description] = S.[CMPNY_DESC],
        T.[Parent Invoice Billing Type Description] = S.[BILLING_TYP_DESC],
        T.[Parent Invoice Billing Category Description] = S.[BILLING_CTGRY_DESC],
        T.[Parent Invoice SD Document Category Description] = S.[SD_DOCMT_CTGRY_DESC],
        T.[Parent Invoice Sales Organization Description] = S.[SALES_ORGZTN_DESC],
        T.[Parent Invoice Distribution Channel Description] = S.[DISTRBN_CHNL_DESC],
        T.[Parent Invoice Division Description] = S.[DIVISION_DESC],
        T.[Parent Invoice Shipping Condition Description] = S.[SHIPG_COND_DESC],
        T.[Parent Invoice Price Group Description] = S.[PRICE_GROUP_DESC],
        T.[Parent Invoice Customer Group Description] = S.[CUST_GROUP_DESC],
        T.[Parent Invoice Price List Description] = S.[PRICE_LIST_DESC],
        T.[Parent Invoice Payment Terms Description] = S.[PYMT_TRMS_DESC],
        T.[Parent Invoice Incoterms Description] = S.[INCO_TRMS_DESC],
        T.[Parent Invoice Statistical Currency Description] = S.[STATISTICAL_CRNCY_DESC],
        T.[Parent Invoice List Type Description] = S.[INVC_LIST_TYP_DESC],
        T.[Parent Invoice Accounting Transfer Status Description] = S.[ACCTNG_TRSFR_STATUS_DESC],
        T.[Parent Invoice SD Document Currency Description] = S.[SD_DOCMT_CRNCY_DESC],
        T.[Parent Invoice Cancelled Document Number] = S.[CANCELLED_DOCMT_NUM],
        T.[Parent Invoice Terms Discount Percentage] = S.[TRMS_DISCNT_PRCNTG],
        T.[Parent Invoice Customer Group 6] = S.[CUST_GROUP_6],
        T.[Parent Invoice Customer Group 7] = S.[CUST_GROUP_7],
        T.[Parent Invoice Customer Group 8] = S.[CUST_GROUP_8],
        T.[Parent Invoice Customer Group 9] = S.[CUST_GROUP_9],
        T.[Parent Invoice Customer Group 10] = S.[CUST_GROUP_10],
        T.[Parent Invoice Customer Group 6 Description] = S.[CUST_GROUP_6_DESC],
        T.[Parent Invoice Customer Group 7 Description] = S.[CUST_GROUP_7_DESC],
        T.[Parent Invoice Customer Group 8 Description] = S.[CUST_GROUP_8_DESC],
        T.[Parent Invoice Customer Group 9 Description] = S.[CUST_GROUP_9_DESC],
        T.[Parent Invoice Customer Group 10 Description] = S.[CUST_GROUP_10_DESC]
    FROM [GLOBAL_EDW].[Propelis].[PARENT_INVOICE] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_SAL_INVOICE_CUR_D] S
        ON T.[INVC_KEY] = S.[INVC_KEY];

    ----------------------------------------------------------------------
    -- Insert new records into target table
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[PARENT_INVOICE] (
        [INVC_KEY],
        [Parent Invoice Sales Order Invoice ID],
        [Parent Invoice Company Code],
        [Parent Invoice Billing Type Code],
        [Parent Invoice Billing Category],
        [Parent Invoice SD Document Category],
        [Parent Invoice Sales Organization],
        [Parent Invoice Distribution Channel],
        [Parent Invoice Divison],
        [Parent Invoice Parent Invoice Pricing Procedure in Pricing],
        [Parent Invoice Document Condition Number],
        [Parent Invoice Shipping Condition],
        [Parent Invoice Price Group],
        [Parent Invoice Customer Group],
        [Parent Invoice Price List],
        [Parent Invoice Payment Reference],
        [Parent Invoice Payment Terms],
        [Parent Invoice Incoterms],
        [Parent Invoice Incoterms 2],
        [Parent Invoice Exchange Rate],
        [Parent Invoice Net Value],
        [Parent Invoice Statistical Currency],
        [Parent Invoice List Type],
        [Parent Invoice Reference],
        [Parent Invoice Parent Invoice Date],
        [Parent Invoice Created Date],
        [Parent Invoice Created User ID],
        [Parent Invoice Updated Date],
        [Parent Invoice Updated User ID],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Parent Invoice Billing Document Cancelled Indicator],
        [Parent Invoice Creation Date],
        [Parent Invoice Changed On Date],
        [Parent Invoice Customer Purchase Order Number],
        [Parent Invoice Accounting Transfer Status],
        [Parent Invoice Currency Key of Credit Control Area],
        [Parent Invoice Accounting Document Number],
        [Parent Invoice SD Document Currency],
        [Parent Invoice Company Description],
        [Parent Invoice Billing Type Description],
        [Parent Invoice Billing Category Description],
        [Parent Invoice SD Document Category Description],
        [Parent Invoice Sales Organization Description],
        [Parent Invoice Distribution Channel Description],
        [Parent Invoice Division Description],
        [Parent Invoice Shipping Condition Description],
        [Parent Invoice Price Group Description],
        [Parent Invoice Customer Group Description],
        [Parent Invoice Price List Description],
        [Parent Invoice Payment Terms Description],
        [Parent Invoice Incoterms Description],
        [Parent Invoice Statistical Currency Description],
        [Parent Invoice List Type Description],
        [Parent Invoice Accounting Transfer Status Description],
        [Parent Invoice SD Document Currency Description],
        [Parent Invoice Cancelled Document Number],
        [Parent Invoice Terms Discount Percentage],
        [Parent Invoice Customer Group 6],
        [Parent Invoice Customer Group 7],
        [Parent Invoice Customer Group 8],
        [Parent Invoice Customer Group 9],
        [Parent Invoice Customer Group 10],
        [Parent Invoice Customer Group 6 Description],
        [Parent Invoice Customer Group 7 Description],
        [Parent Invoice Customer Group 8 Description],
        [Parent Invoice Customer Group 9 Description],
        [Parent Invoice Customer Group 10 Description]
    )
    SELECT
    S.[INVC_KEY],
    S.[SALES_ORDER_INVC_ID],
    S.[CMPNY_CD],
    S.[BILLING_TYP_CD],
    S.[BILLING_CTGRY],
    S.[SD_DOCMT_CTGRY],
    S.[SALES_ORGZTN],
    S.[DISTRBN_CHNL],
    S.[DIVISON],
    S.[PRICING_PROC],
    S.[DOCMT_COND_NUM],
    S.[SHIPG_COND],
    S.[PRICE_GROUP],
    S.[CUST_GROUP],
    S.[PRICE_LIST],
    S.[PYMT_REF],
    S.[PYMT_TRMS],
    S.[INCOTERMS],
    S.[INCOTERMS2],
    S.[EXCHG_RT],
    S.[NET_VAL],
    S.[STATISTICAL_CRNCY],
    S.[INVC_LIST_TYP],
    S.[REF],
    S.[INVC_DATE],
    S.[CREATED_DATE],
    S.[CREATED_USR_ID],
    S.[UPDTD_DATE],
    S.[UPDTD_USR_ID],
    S.[ETL_SRC_SYS_CD],
    S.[ETL_EFFECTV_BEGIN_DATE],
    S.[ETL_EFFECTV_END_DATE],
    S.[ETL_CURR_RCD_IND],
    S.[ETL_CREATED_TS],
    S.[ETL_UPDTD_TS],
    S.[BILLING_DOCMT_CANCELLED_IND],
    S.[CREATION_DATE],
    S.[CHANGED_ON_DATE],
    S.[CUST_PURCHS_ORDER_NUM],
    S.[ACCTNG_TRSFR_STATUS],
    S.[CRNCY_KEY_OF_CREDIT_CTRL_AREA],
    S.[ACCTNG_DOCMT_NUM],
    S.[SD_DOCMT_CRNCY],
    S.[CMPNY_DESC],
    S.[BILLING_TYP_DESC],
    S.[BILLING_CTGRY_DESC],
    S.[SD_DOCMT_CTGRY_DESC],
    S.[SALES_ORGZTN_DESC],
    S.[DISTRBN_CHNL_DESC],
    S.[DIVISION_DESC],
    S.[SHIPG_COND_DESC],
    S.[PRICE_GROUP_DESC],
    S.[CUST_GROUP_DESC],
    S.[PRICE_LIST_DESC],
    S.[PYMT_TRMS_DESC],
    S.[INCO_TRMS_DESC],
    S.[STATISTICAL_CRNCY_DESC],
    S.[INVC_LIST_TYP_DESC],
    S.[ACCTNG_TRSFR_STATUS_DESC],
    S.[SD_DOCMT_CRNCY_DESC],
    S.[CANCELLED_DOCMT_NUM],
    S.[TRMS_DISCNT_PRCNTG],
    S.[CUST_GROUP_6],
    S.[CUST_GROUP_7],
    S.[CUST_GROUP_8],
    S.[CUST_GROUP_9],
    S.[CUST_GROUP_10],
    S.[CUST_GROUP_6_DESC],
    S.[CUST_GROUP_7_DESC],
    S.[CUST_GROUP_8_DESC],
    S.[CUST_GROUP_9_DESC],
    S.[CUST_GROUP_10_DESC]
   
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_SAL_INVOICE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[PARENT_INVOICE] T
        ON T.[INVC_KEY] = S.[INVC_KEY]
    WHERE T.[INVC_KEY] IS NULL;
END