CREATE  PROCEDURE [Propelis].[Proc_EDW_T_FACT_HR_CATSDB_CUR_D]
AS
BEGIN

-- Step 1: Clear existing data from the target table
	
    TRUNCATE TABLE [GLOBAL_EDW].[Propelis].[EDW_T_FACT_HR_CATSDB_CUR_D];
	
	-- Step 2: Insert refreshed data from mirror table with joins
INSERT INTO [GLOBAL_EDW].[Propelis].[EDW_T_FACT_HR_CATSDB_CUR_D]
(
	[PERSONEL_NUM_KEY],
	[WRK_DATE_KEY],
	[Counter],
	[COST_CNTR_KEY],
	[ACTIVITY_TYP_KEY],
	[SERVC_ORDER_KEY],
	[Operation Task List],
	[Operation Counter],
	[RECVNG_FUNCTNL_AREA_KEY],
	[SENDING_FUNCTNL_AREA_KEY],
	[Attendance Or Absence Type],
	[Controlling Area],
	[Display UOM],
	[WRK_CNTR_KEY],
	[Order Category],
	[Processing Status],
	[Document Number],
	[HRS],
	[Start Time],
	[End Time],
	[CATS_AMT],
	[CATS_QTY],
	[Change Text],
	[Created Date],
	[Created Time],
	[Changed Date],
	[Change Time],
	[Comment],
	[Header Comment],
	[Short Text],
	[Long Text],
	[ETL_SRC_SYS_CD],
	[ETL_CREATED_TS],
	[ETL_UPDTD_TS],
	[PLNT_KEY],
	[Controlling Area Description],
	[Order Category Description],
	[Processing Status Description],
	[Network Number],
	[UOM],
	[Created On],
	[Time Of Entry],
	[User Who Created Data Record],
	[Date Of Last Change],
	[Time of Last Change],
	[Name Of Person Who Changed Object],
	[Name Of Person Who Apprvd Data],
	[Date Of Approval],
	[Logical System],
	[Reference Counter for Record to be Changed],
	[Partial Confirmation Indicator],
	[Receiver Order],
	[Project Description],
	[WBS Number],
	[WBS Description],
	[WBS_ELEMNT_KEY],
	
	--Added Alias Key List
	[SGK_OPERREG_PLANT],
	[COSTCVZ_COST_CNTR_KEY],
	[COSTCHZ_COST_CNTR_KEY],
	[WORKCHZ_WRK_CNTR_KEY],
	[WORKCVZ_WRK_CNTR_KEY]
	)
SELECT 
		FACT.[PERSONEL_NUM_KEY],
		FACT.[WRK_DATE_KEY],
		FACT.[COUNTER],
		FACT.[COST_CNTR_KEY],
		FACT.[ACTIVITY_TYP_KEY],
		FACT.[SERVC_ORDER_KEY],
		FACT.[OPERATION_TASK_LIST],
		FACT.[OPERATION_COUNTER],
		FACT.[RECVNG_FUNCTNL_AREA_KEY],
		FACT.[SENDING_FUNCTNL_AREA_KEY],
		FACT.[ATTENDANCE_OR_ABSNE_TYP],
		FACT.[CONTROLLING_AREA],
		FACT.[DISPLAY_UOM],
		FACT.[WRK_CNTR_KEY],
		FACT.[ORDER_CTGRY],
		FACT.[PRCSNG_STATUS],
		FACT.[DOCMT_NUM],
		FACT.[HRS],
		FACT.[START_TM],
		FACT.[END_TM],
		FACT.[CATS_AMT],
		FACT.[CATS_QTY],
		FACT.[CHG_TEXT],
		FACT.[CREATED_DATE],
		FACT.[CREATED_TM],
		FACT.[CHANGED_DATE],
		FACT.[CHG_TM],
		FACT.[COMMENT],
		FACT.[HDR_COMMENT],
		FACT.[SHORT_TEXT],
		FACT.[LONG_TEXT],
		FACT.[ETL_SRC_SYS_CD],
		FACT.[ETL_CREATED_TS],
		FACT.[ETL_UPDTD_TS],
		FACT.[PLNT_KEY],
		FACT.[CONTROLLING_AREA_DESC],
		FACT.[ORDER_CTGRY_DESC],
		FACT.[PRCSNG_STATUS_DESC],
		FACT.[NTWRK_NUM],
		FACT.[UOM],
		FACT.[CREATED_ON],
		FACT.[TM_OF_ENTRY],
		FACT.[USR_WHO_CREATED_DATA_RCD],
		FACT.[DATE_OF_LAST_CHG],
		FACT.[TM_OF_LAST_CHG],
		FACT.[NAME_OF_PERSON_WHO_CHANGED_OBJ],
		FACT.[NAME_OF_PERSON_WHO_APPRVD_DATA],
		FACT.[DATE_OF_APPROVAL],
		FACT.[LGCL_SYS],
		FACT.[REF_COUNTER_FOR_RCD_TO_BE_CHANG],
		FACT.[PARTIAL_CONFIRM_IND],
		FACT.[RECEIVER_ORDER],
		FACT.[PROJ_DESC],
		FACT.[WBS_NUM],
		FACT.[WBS_DESC],
		FACT.[WBS_ELEMNT_KEY],
		--Added Alias Key List
		SUBSTRING(PERSONL.[Personnel Cost Center ID],4,4) AS SGK_OPERREG_PLANT,
		COSCNTR.COST_CNTR_KEY AS COSTCVZ_COST_CNTR_KEY,
		COSCNTR.COST_CNTR_KEY AS COSTCHZ_COST_CNTR_KEY,
		WORKCTR.WRK_CNTR_KEY AS WORKCHZ_WRK_CNTR_KEY,
		WORKCTR.WRK_CNTR_KEY AS WORKCVZ_WRK_CNTR_KEY
		
FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_F_HR_CATSDB_CUR_D] AS FACT
	
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D] AS MST_DATE
		ON FACT.[WRK_DATE_KEY] = MST_DATE.[DATE_KEY] 
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_COSCNTR_CUR_D] AS COSCNTR
		ON FACT.[COST_CNTR_KEY] = COSCNTR.[COST_CNTR_KEY] 
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PERSONL_CUR_D] AS PERSONL
		ON FACT.[PERSONEL_NUM_KEY] = PERSONL.[PERSONEL_KEY]
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PLANT_CUR_D] AS PLANT
		ON FACT.[PLNT_KEY] = PLANT.[PLNT_KEY] 
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_ACTTYPE_CUR_D] AS ACTTYPE
		ON FACT.[ACTIVITY_TYP_KEY] = ACTTYPE.[ACTIVITY_TYP_KEY]
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_PRD_SERVORD_CUR_D] AS SERVORD
		ON FACT.[SERVC_ORDER_KEY] = SERVORD.[SERVC_ORDER_KEY] 
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_WORKCTR_CUR_D] AS WORKCTR
		ON FACT.[WRK_CNTR_KEY] = WORKCTR.[WRK_CNTR_KEY]
	LEFT JOIN [GLOBAL_EDW].[Propelis].[RECEIVING_FUNCTIONAL_AREA] AS RECEIVING
		ON FACT.[RECVNG_FUNCTNL_AREA_KEY] = RECEIVING.[FUNCTNL_AREA_KEY]
	LEFT JOIN [GLOBAL_EDW].[Propelis].[SENDING_FUNCTIONAL_AREA] AS SENDING
		ON FACT.[SENDING_FUNCTNL_AREA_KEY] = SENDING.[FUNCTNL_AREA_KEY];

END;