CREATE   PROCEDURE [Propelis].[Proc_BASIC_START_DATE]
AS
BEGIN  
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Basic Start Date] = S.[THE_DATE],
        T.[Basic Start Fiscal Year] = S.[FISCAL_YR],
        T.[Basic Start Fiscal Period Number] = S.[FISCAL_PER_NUM],
        T.[Basic Start Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Basic Start Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Basic Start Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Basic Start Calendar Year] = S.[CLNDR_YR],
        T.[Basic Start Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Basic Start Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Basic Start Calendar Month Description] = S.[CLNDR_MNTH_DESC],
        T.[Basic Start Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[Basic Start Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Basic Start Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Basic Start Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Basic Start Calendar Day In Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Basic Start Calendar Day In Year] = S.[CLNDR_DAY_IN_YR],
        T.[Basic Start Calendar Week] = S.[CLNDR_WK],
        T.[Basic Start Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Basic Start Calendar Days In Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Basic Start Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Basic Start Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Basic Start Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Basic Start Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Basic Start Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Basic Start Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Basic Start Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Basic Start Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Basic Start Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Basic Start Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Basic Start Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Basic Start Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Basic Start Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Basic Start Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Basic Start Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Basic Start Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Basic Start Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[CURR_FISCAL_YR_PLUS_1_FLG] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Basic Start Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Basic Start Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Basic Start Fiscal Week] = S.[FISCAL_WK],
        T.[Basic Start Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Basic Start Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Basic Start Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Basic Start Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Basic Start Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Basic Start Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Basic Start Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Basic Start Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Basic Start Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Basic Start Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Basic Start Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[BASIC_START_DATE] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];
 
    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[BASIC_START_DATE] (
        [DATE_KEY],
        [Basic Start Date],
        [Basic Start Fiscal Year],
        [Basic Start Fiscal Period Number],
        [Basic Start Fiscal Period Code],
        [Basic Start Fiscal Quarter Number],
        [Basic Start Fiscal Quarter Code],
        [Basic Start Calendar Year],
        [Basic Start Calendar Month Number],
        [Basic Start Calendar Month Code],
        [Basic Start Calendar Month Description],
        [Basic Start Calendar Quarter Number],
        [Basic Start Calendar Quarter Code],
        [Basic Start Calendar Weekday Number],
        [Basic Start Calendar Weekday Name],
        [Basic Start Calendar Day In Month],
        [Basic Start Calendar Day In Year],
        [Basic Start Calendar Week],
        [Basic Start Calendar Month In Quarter Number],
        [Basic Start Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Basic Start Current Day Flag],
        [Basic Start Current Day Minus 1 Flag],
        [Basic Start Current Calendar Week Flag],
        [Basic Start Current Calendar Week Minus 1 Flag],
        [Basic Start Current Month Flag],
        [Basic Start Current Month Minus 1 Flag],
        [Basic Start Current Month Minus 12 Flag],
        [Basic Start Current Quarter Flag],
        [Basic Start Current Quarter Minus 1 Flag],
        [Basic Start Current Quarter Minus 4 Flag],
        [Basic Start Current Calendar Year Flag],
        [Basic Start Current Calendar Year Minus 1 Flag],
        [Basic Start Current Calendar Year Minus 2 Flag],
        [Basic Start Current Fiscal Year Flag],
        [Basic Start Current Fiscal Year Minus 1 Flag],
        [Basic Start Current Fiscal Year Minus 2 Flag],
        [Basic Start Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Basic Start Day In Fiscal Year],
        [Basic Start Date Is Weekday],
        [Basic Start Fiscal Week],
        [Basic Start Current Fiscal Week Flag],
        [Basic Start Current Fiscal Week Minus 1 Flag],
        [Basic Start Fiscal Weekday Number],
        [Basic Start Fiscal Weekday Name],
        [Basic Start Current Month Minus 2 Flag],
        [Basic Start Current Fiscal Week Minus 2 Flag],
        [Basic Start Current Fiscal Week Minus 6 Flag],
        [Basic Start Current Fiscal Week Minus 3 Flag],
        [Basic Start Current Fiscal Week Minus 4 Flag],
        [Basic Start Current Fiscal Week Minus 5 Flag],
        [Basic Start Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[BASIC_START_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
 
END