CREATE   PROCEDURE [Propelis].[Proc_INVOICE_DATE] 
AS
BEGIN  

    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Invoice Posting Date] = S.[THE_DATE],
        T.[Invoice Posting Fiscal Year] = S.[FISCAL_YR],
        T.[Invoice Posting Fiscal Period] = S.[FISCAL_PER_NUM],
        T.[Invoice Posting Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Invoice Posting Fiscal Quarter] = S.[FISCAL_QTR_NUM],
        T.[Invoice Posting Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Invoice Posting Calendar Year] = S.[CLNDR_YR],
        T.[Invoice Posting Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Invoice Posting Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Invoice Posting Calendar Month Desc] = S.[CLNDR_MNTH_DESC],
        T.[Invoice Posting Calendar Quarter] = S.[CLNDR_QTR_NUM],
        T.[Invoice Posting Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Invoice Posting Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Invoice Posting Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Invoice Posting Calendar Day] = S.[CLNDR_DAY_IN_MNTH],
        T.[Invoice Posting Calendar Day in Year] = S.[CLNDR_DAY_IN_YR],
        T.[Invoice Posting Calendar Week] = S.[CLNDR_WK],
        T.[Invoice Posting Calendar Month in Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Invoice Posting Calendar Days in Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Invoice Posting Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Invoice Posting Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Invoice Posting Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Invoice Posting Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Invoice Posting Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Invoice Posting Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Invoice Posting Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Invoice Posting Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Invoice Posting Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Invoice Posting Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Invoice Posting Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Invoice Posting Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Invoice Posting Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Invoice Posting Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Invoice Posting Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Invoice Posting Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Invoice Posting Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Invoice Posting Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Invoice Posting Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Invoice Posting Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Invoice Posting Fiscal Week] = S.[FISCAL_WK],
        T.[Invoice Posting Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Invoice Posting Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Invoice Posting Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Invoice Posting Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Invoice Posting Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Invoice Posting Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Invoice Posting Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Invoice Posting Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Invoice Posting Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Invoice Posting Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Invoice Posting Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[INVOICE_DATE] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];


    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[INVOICE_DATE] (
        [DATE_KEY],
        [Invoice Posting Date],
        [Invoice Posting Fiscal Year],
        [Invoice Posting Fiscal Period],
        [Invoice Posting Fiscal Period Code],
        [Invoice Posting Fiscal Quarter],
        [Invoice Posting Fiscal Quarter Code],
        [Invoice Posting Calendar Year],
        [Invoice Posting Calendar Month Number],
        [Invoice Posting Calendar Month Code],
        [Invoice Posting Calendar Month Desc],
        [Invoice Posting Calendar Quarter],
        [Invoice Posting Calendar Quarter Code],
        [Invoice Posting Calendar Weekday Number],
        [Invoice Posting Calendar Weekday Name],
        [Invoice Posting Calendar Day],
        [Invoice Posting Calendar Day in Year],
        [Invoice Posting Calendar Week],
        [Invoice Posting Calendar Month in Quarter Number],
        [Invoice Posting Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Invoice Posting Current Day Flag],
        [Invoice Posting Current Day Minus 1 Flag],
        [Invoice Posting Current Calendar Week Flag],
        [Invoice Posting Current Calendar Week Minus 1 Flag],
        [Invoice Posting Current Month Flag],
        [Invoice Posting Current Month Minus 1 Flag],
        [Invoice Posting Current Month Minus 12 Flag],
        [Invoice Posting Current Quarter Flag],
        [Invoice Posting Current Quarter Minus 1 Flag],
        [Invoice Posting Current Quarter Minus 4 Flag],
        [Invoice Posting Current Calendar Year Flag],
        [Invoice Posting Current Calendar Year Minus 1 Flag],
        [Invoice Posting Current Calendar Year Minus 2 Flag],
        [Invoice Posting Current Fiscal Year Flag],
        [Invoice Posting Current Fiscal Year Minus 1 Flag],
        [Invoice Posting Current Fiscal Year Minus 2 Flag],
        [Invoice Posting Current Calendar Year Plus 1 Flag],
        [Invoice Posting Current Fiscal Year Plus 1 Flag],
        [Invoice Posting Day In Fiscal Year],
        [Invoice Posting Date Is Weekday],
        [Invoice Posting Fiscal Week],
        [Invoice Posting Current Fiscal Week Flag],
        [Invoice Posting Current Fiscal Week Minus 1 Flag],
        [Invoice Posting Fiscal Weekday Number],
        [Invoice Posting Fiscal Weekday Name],
        [Invoice Posting Current Month Minus 2 Flag],
        [Invoice Posting Current Fiscal Week Minus 2 Flag],
        [Invoice Posting Current Fiscal Week Minus 6 Flag],
        [Invoice Posting Current Fiscal Week Minus 3 Flag],
        [Invoice Posting Current Fiscal Week Minus 4 Flag],
        [Invoice Posting Current Fiscal Week Minus 5 Flag],
        [Invoice Posting Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[INVOICE_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;

END;