CREATE     PROCEDURE [Propelis].[Proc_ACTUAL_RELEASE_DATE]
AS
BEGIN  
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Actual Release Date] = S.[THE_DATE],
        T.[Actual Release Fiscal Year] = S.[FISCAL_YR],
        T.[Actual Release Fiscal Period Number] = S.[FISCAL_PER_NUM],
        T.[Actual Release Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Actual Release Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Actual Release Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Actual Release Calendar Year] = S.[CLNDR_YR],
        T.[Actual Release Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Actual Release Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Actual Release Calendar Month Description] = S.[CLNDR_MNTH_DESC],
        T.[Actual Release Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[Actual Release Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Actual Release Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Actual Release Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Actual Release Calendar Day In Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Actual Release Calendar Day In Year] = S.[CLNDR_DAY_IN_YR],
        T.[Actual Release Calendar Week] = S.[CLNDR_WK],
        T.[Actual Release Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Actual Release Calendar Days In Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Actual Release Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Actual Release Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Actual Release Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Actual Release Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Actual Release Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Actual Release Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Actual Release Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Actual Release Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Actual Release Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Actual Release Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Actual Release Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Actual Release Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Actual Release Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Actual Release Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Actual Release Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Actual Release Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Actual Release Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[CURR_FISCAL_YR_PLUS_1_FLG] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Actual Release Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Actual Release Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Actual Release Fiscal Week] = S.[FISCAL_WK],
        T.[Actual Release Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Actual Release Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Actual Release Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Actual Release Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Actual Release Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Actual Release Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Actual Release Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Actual Release Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Actual Release Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Actual Release Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Actual Release Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[ACTUAL_RELEASE_DATE] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];
 
    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[ACTUAL_RELEASE_DATE] (
        [DATE_KEY],
        [Actual Release Date],
        [Actual Release Fiscal Year],
        [Actual Release Fiscal Period Number],
        [Actual Release Fiscal Period Code],
        [Actual Release Fiscal Quarter Number],
        [Actual Release Fiscal Quarter Code],
        [Actual Release Calendar Year],
        [Actual Release Calendar Month Number],
        [Actual Release Calendar Month Code],
        [Actual Release Calendar Month Description],
        [Actual Release Calendar Quarter Number],
        [Actual Release Calendar Quarter Code],
        [Actual Release Calendar Weekday Number],
        [Actual Release Calendar Weekday Name],
        [Actual Release Calendar Day In Month],
        [Actual Release Calendar Day In Year],
        [Actual Release Calendar Week],
        [Actual Release Calendar Month In Quarter Number],
        [Actual Release Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Actual Release Current Day Flag],
        [Actual Release Current Day Minus 1 Flag],
        [Actual Release Current Calendar Week Flag],
        [Actual Release Current Calendar Week Minus 1 Flag],
        [Actual Release Current Month Flag],
        [Actual Release Current Month Minus 1 Flag],
        [Actual Release Current Month Minus 12 Flag],
        [Actual Release Current Quarter Flag],
        [Actual Release Current Quarter Minus 1 Flag],
        [Actual Release Current Quarter Minus 4 Flag],
        [Actual Release Current Calendar Year Flag],
        [Actual Release Current Calendar Year Minus 1 Flag],
        [Actual Release Current Calendar Year Minus 2 Flag],
        [Actual Release Current Fiscal Year Flag],
        [Actual Release Current Fiscal Year Minus 1 Flag],
        [Actual Release Current Fiscal Year Minus 2 Flag],
        [Actual Release Current Calendar Year Plus 1 Flag],
        [CURR_FISCAL_YR_PLUS_1_FLG],
        [Actual Release Day In Fiscal Year],
        [Actual Release Date Is Weekday],
        [Actual Release Fiscal Week],
        [Actual Release Current Fiscal Week Flag],
        [Actual Release Current Fiscal Week Minus 1 Flag],
        [Actual Release Fiscal Weekday Number],
        [Actual Release Fiscal Weekday Name],
        [Actual Release Current Month Minus 2 Flag],
        [Actual Release Current Fiscal Week Minus 2 Flag],
        [Actual Release Current Fiscal Week Minus 6 Flag],
        [Actual Release Current Fiscal Week Minus 3 Flag],
        [Actual Release Current Fiscal Week Minus 4 Flag],
        [Actual Release Current Fiscal Week Minus 5 Flag],
        [Actual Release Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[ACTUAL_RELEASE_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
 
END