CREATE   PROCEDURE [Propelis].[Proc_DOCUMENT_DATE] 
AS
BEGIN  
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[Entry Create Date] = S.[THE_DATE],
        T.[Entry Create Fiscal Year] = S.[FISCAL_YR],
        T.[Entry Create Fiscal Period] = S.[FISCAL_PER_NUM],
        T.[Entry Create Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Entry Create Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Entry Create Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Entry Create Calendar Year] = S.[CLNDR_YR],
        T.[Entry Create Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Entry Create Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Entry Create Calendar Month Description] = S.[CLNDR_MNTH_DESC],
        T.[Entry Create Calendar Quarter] = S.[CLNDR_QTR_NUM],
        T.[Entry Create Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Entry Create Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Entry Create Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Entry Create Calendar Day in Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Entry Create Calendar Day in Year] = S.[CLNDR_DAY_IN_YR],
        T.[Entry Create Calendar Week] = S.[CLNDR_WK],
        T.[Entry Create Calendar Month in Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Entry Create Calendar Days in Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[Entry Create Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Entry Create Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Entry Create Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Entry Create Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Entry Create Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Entry Create Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Entry Create Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Entry Create Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Entry Create Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Entry Create Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Entry Create Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Entry Create Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Entry Create Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Entry Create Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Entry Create Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Entry Create Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Entry Create Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Entry Create Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Entry Create Day in Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[IS_WEEKDAY] = S.[IS_WEEKDAY],
        T.[Entry Create Fiscal Week] = S.[FISCAL_WK],
        T.[Entry Create Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Entry Create Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Entry Create Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Entry Create Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Entry Create Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Entry Create Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Entry Create Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Entry Create Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Entry Create Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Entry Create Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Entry Create Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[DOCUMENT_DATE] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];
 
    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[DOCUMENT_DATE] (
        [DATE_KEY],
        [Entry Create Date],
        [Entry Create Fiscal Year],
        [Entry Create Fiscal Period],
        [Entry Create Fiscal Period Code],
        [Entry Create Fiscal Quarter Number],
        [Entry Create Fiscal Quarter Code],
        [Entry Create Calendar Year],
        [Entry Create Calendar Month Number],
        [Entry Create Calendar Month Code],
        [Entry Create Calendar Month Description],
        [Entry Create Calendar Quarter],
        [Entry Create Calendar Quarter Code],
        [Entry Create Calendar Weekday Number],
        [Entry Create Calendar Weekday Name],
        [Entry Create Calendar Day in Month],
        [Entry Create Calendar Day in Year],
        [Entry Create Calendar Week],
        [Entry Create Calendar Month in Quarter Number],
        [Entry Create Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Entry Create Current Day Flag],
        [Entry Create Current Day Minus 1 Flag],
        [Entry Create Current Calendar Week Flag],
        [Entry Create Current Calendar Week Minus 1 Flag],
        [Entry Create Current Month Flag],
        [Entry Create Current Month Minus 1 Flag],
        [Entry Create Current Month Minus 12 Flag],
        [Entry Create Current Quarter Flag],
        [Entry Create Current Quarter Minus 1 Flag],
        [Entry Create Current Quarter Minus 4 Flag],
        [Entry Create Current Calendar Year Flag],
        [Entry Create Current Calendar Year Minus 1 Flag],
        [Entry Create Current Calendar Year Minus 2 Flag],
        [Entry Create Current Fiscal Year Flag],
        [Entry Create Current Fiscal Year Minus 1 Flag],
        [Entry Create Current Fiscal Year Minus 2 Flag],
        [Entry Create Current Calendar Year Plus 1 Flag],
        [Entry Create Current Fiscal Year Plus 1 Flag],
        [Entry Create Day in Fiscal Year],
        [IS_WEEKDAY],
        [Entry Create Fiscal Week],
        [Entry Create Current Fiscal Week Flag],
        [Entry Create Current Fiscal Week Minus 1 Flag],
        [Entry Create Fiscal Weekday Number],
        [Entry Create Fiscal Weekday Name],
        [Entry Create Current Month Minus 2 Flag],
        [Entry Create Current Fiscal Week Minus 2 Flag],
        [Entry Create Current Fiscal Week Minus 6 Flag],
        [Entry Create Current Fiscal Week Minus 3 Flag],
        [Entry Create Current Fiscal Week Minus 4 Flag],
        [Entry Create Current Fiscal Week Minus 5 Flag],
        [Entry Create Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[DOCUMENT_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
END