CREATE   PROCEDURE [Propelis].[Proc_TEMP_EDW_T_FACT_FI_BPCDTAU_CUR_D]
AS
BEGIN  

DELETE FROM [GLOBAL_EDW].[Propelis].[TEMP_EDW_T_FACT_PRD_SERVRES_CUR_D];

INSERT INTO [GLOBAL_EDW].[Propelis].[TEMP_EDW_T_FACT_FI_BPCDTAU_CUR_D]
(
[ACCT_KEY],
[Audit Trail],
[Currency],
[Custom1],
[ENTITY_KEY],
[Flow],
[FUNCTNL_AREA_KEY],
[INTER_CMPNY_PROFT_CNTR_KEY],
[INTER_CMPNY_KEY],
[PROFT_CNTR_KEY],
[Project],
[Scope],
[Version],
[Fiscal Year],
[FYP],
[Signdata Amount],
[ETL_SRC_SYS_CD],
[ETL_CREATED_TS],
[ETL_UPDTD_TS],
[Account ID],
[Entity ID],
[Functional Area ID],
[Inter Company Profit Center ID],
[Profit Center ID],
[Inter Company ID],
[Signdata Amt - Current]
)

SELECT 
Fact.[ACCT_KEY],
Fact.[AUDIT_TRAIL],
Fact.[CRNCY],
Fact.[CUSTOM1],
Fact.[ENTTY_KEY],
Fact.[FLOW],
Fact.[FUNCTNL_AREA_KEY],
Fact.[INTER_CMPNY_PROFT_CNTR_KEY],
Fact.[INTER_CMPNY_KEY],
Fact.[PROFT_CNTR_KEY],
Fact.[PROJ],
Fact.[SCOPE],
Fact.[VRSN],
Fact.[FISCAL_YR],
Fact.[PER],
Fact.[SIGNDATA_AMT],
Fact.[ETL_SRC_SYS_CD],
Fact.[ETL_CREATED_TS],
Fact.[ETL_UPDTD_TS],
Fact.[ACCT_ID],
Fact.[ENTTY_ID],
Fact.[FUNCTNL_AREA_ID],
Fact.[INTER_CMPNY_PROFT_CNTR_ID],
Fact.[PROFT_CNTR_ID],
Fact.[INTER_CMPNY_ID],
Fact.[SIGNDATA_AMT_CURR]
FROM [GLOBAL_EDW_02_MIRROR].[GLOBAL_EDW].[EDW_T_F_FI_BPCDTAU_CUR_D] Fact
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_GENLDGR_CUR_D] a 
ON Fact.[ACCT_KEY] = a.[GL_KEY]
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_FUNCTAR_CUR_D] b 
ON Fact.[FUNCTNL_AREA_KEY] = b.[FUNCTNL_AREA_KEY]
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D] c 
ON Fact.[FISCAL_YR] = c.[Date Fiscal Year]
AND Fact.[PER] = c.[FISCAL_PER_NUM]
AND c.[Date Calendar Month Number] = 1
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_HY_GLACTHZ_CUR_D] d 
ON Fact.[ACCT_ID] = ltrim(d.[GL_CD],0)
AND Fact.[FUNCTNL_AREA_ID] = d.[FUNCTNL_AREA]
LEFT JOIN [GLOBAL_EDW].[Propelis].[INTER_COMPANY] e 
ON Fact.[INTER_CMPNY_KEY] = e.[CMPNY_KEY]
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PROFCTR_CUR_D] f 
ON Fact.[PROFT_CNTR_KEY] = f.[PROFT_CNTR_KEY]
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_HY_PROFCHZ_CUR_D] g 
ON f.[PROFT_CNTR_KEY] = g.[PROFT_CNTR_KEY]
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_HY_PROFCVZ_CUR_D] h
ON f.[PROFT_CNTR_KEY] = h.[PROFT_CNTR_KEY]
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_HY_BPCGLHZ_CUR_D] i 
ON Fact.[ACCT_ID] = i.[BPC GL Account ID]
LEFT JOIN [GLOBAL_EDW].[Propelis].[INTER_COMP_PROFIT_CNTR] j 
ON Fact.[INTER_CMPNY_PROFT_CNTR_KEY] = j.[PROFT_CNTR_KEY]
LEFT JOIN [GLOBAL_EDW].[Propelis].[Inter_Comp_PC_VH] k 
ON j.[PROFT_CNTR_KEY] = k.[COST_CNTR_KEY]
LEFT JOIN [GLOBAL_EDW].[Propelis].[INTER_COMPANY_PC_HH] l 
ON j.[PROFT_CNTR_KEY] = l.[PROFT_CNTR_KEY]
LEFT JOIN [GLOBAL_EDW].[Propelis].[Entity_Company] m 
ON Fact.[ENTTY_KEY] = m.[CMPNY_KEY]
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_FI_MELTGRP_CUR_D] n 
ON Fact.[ACCT_ID] = n.[ACCT_ID]
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_HY_ENTYHZ_CUR_D] o 
ON Fact.[ENTTY_ID] = o.[Entity ID];

END;