CREATE     PROCEDURE [Propelis].[Proc_BILLING_DATE]
AS
BEGIN
    SET NOCOUNT ON;

    -- =================================================================
    -- Step 1: Update existing records that match on the DATE_KEY
    -- =================================================================
    UPDATE T
    SET
        T.[Billing Date] = S.[THE_DATE],
        T.[Billing Fiscal Year] = S.[FISCAL_YR],
        T.[Billing Fiscal Period] = S.[FISCAL_PER_NUM],
        T.[Billing Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[Billing Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[Billing Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[Billing Calendar Year] = S.[CLNDR_YR],
        T.[Billing Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[Billing Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[Billing Calendar Month Desc] = S.[CLNDR_MNTH_DESC],
        T.[Billing Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[Billing Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[Billing Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[Billing Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[Billing Calendar Day in Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[Billing Calendar Day in Year] = S.[CLNDR_DAY_IN_YR],
        T.[Billing Calendar week] = S.[CLNDR_WK], -- Corrected Casing
        T.[Billing Calendar Month in Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[Billing Calendar Days in Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_UPDTD_TS] = GETUTCDATE(),
        T.[Billing Current Day Flag] = S.[CURR_DAY_FLG],
        T.[Billing Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[Billing Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[Billing Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[Billing Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[Billing Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[Billing Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[Billing Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[Billing Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[Billing Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[Billing Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[Billing Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[Billing Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[Billing Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[Billing Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[Billing Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[Billing Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[Billing Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[Billing Day in Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[Billing Date Is Weekday] = S.[IS_WEEKDAY],
        T.[Billing Fiscal Week] = S.[FISCAL_WK],
        T.[Billing Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[Billing Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[Billing Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[Billing Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[Billing Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[Billing Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[Billing Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[Billing Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[Billing Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[Billing Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[Billing Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM
        [GLOBAL_EDW].[Propelis].[BILLING_DATE] T
    INNER JOIN
        [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] S ON T.[DATE_KEY] = S.[DATE_KEY];

    -- =================================================================
    -- Step 2: Insert new records that do not exist in the target
    -- =================================================================
    INSERT INTO [GLOBAL_EDW].[Propelis].[BILLING_DATE] (
        [DATE_KEY],
        [Billing Date],
        [Billing Fiscal Year],
        [Billing Fiscal Period],
        [Billing Fiscal Period Code],
        [Billing Fiscal Quarter Number],
        [Billing Fiscal Quarter Code],
        [Billing Calendar Year],
        [Billing Calendar Month Number],
        [Billing Calendar Month Code],
        [Billing Calendar Month Desc],
        [Billing Calendar Quarter Number],
        [Billing Calendar Quarter Code],
        [Billing Calendar Weekday Number],
        [Billing Calendar Weekday Name],
        [Billing Calendar Day in Month],
        [Billing Calendar Day in Year],
        [Billing Calendar week], -- Corrected Casing
        [Billing Calendar Month in Quarter Number],
        [Billing Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Billing Current Day Flag],
        [Billing Current Day Minus 1 Flag],
        [Billing Current Calendar Week Flag],
        [Billing Current Calendar Week Minus 1 Flag],
        [Billing Current Month Flag],
        [Billing Current Month Minus 1 Flag],
        [Billing Current Month Minus 12 Flag],
        [Billing Current Quarter Flag],
        [Billing Current Quarter Minus 1 Flag],
        [Billing Current Quarter Minus 4 Flag],
        [Billing Current Calendar Year Flag],
        [Billing Current Calendar Year Minus 1 Flag],
        [Billing Current Calendar Year Minus 2 Flag],
        [Billing Current Fiscal Year Flag],
        [Billing Current Fiscal Year Minus 1 Flag],
        [Billing Current Fiscal Year Minus 2 Flag],
        [Billing Current Calendar Year Plus 1 Flag],
        [Billing Current Fiscal Year Plus 1 Flag],
        [Billing Day in Fiscal Year],
        [Billing Date Is Weekday],
        [Billing Fiscal Week],
        [Billing Current Fiscal Week Flag],
        [Billing Current Fiscal Week Minus 1 Flag],
        [Billing Fiscal Weekday Number],
        [Billing Fiscal Weekday Name],
        [Billing Current Month Minus 2 Flag],
        [Billing Current Fiscal Week Minus 2 Flag],
        [Billing Current Fiscal Week Minus 6 Flag],
        [Billing Current Fiscal Week Minus 3 Flag],
        [Billing Current Fiscal Week Minus 4 Flag],
        [Billing Current Fiscal Week Minus 5 Flag],
        [Billing Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM
        [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN
        [GLOBAL_EDW].[Propelis].[BILLING_DATE] T ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE
        T.[DATE_KEY] IS NULL;

END;