CREATE     PROCEDURE [Propelis].[Proc_EDW_T_FACT_PRD_TMCONFS_CUR_D]
AS
BEGIN

    -- Step 1: Clear existing data from the target table
	
	TRUNCATE TABLE [GLOBAL_EDW].[Propelis].[EDW_T_FACT_PRD_TMCONFS_CUR_D];
	
	-- Step 2: Insert refreshed data from mirror table with joins
	
	INSERT INTO [GLOBAL_EDW].[Propelis].[EDW_T_FACT_PRD_TMCONFS_CUR_D](
	    [SEG_CD_KEY],
        [Operation Task List ID],
        [Operation Counter ID],
        [Operation Activity ID],
        [Operation Confirmation ID],
        [Operation Sequence ID],
        [PROFT_CNTR_KEY],
        [SALES_ORDER_KEY],
        [Sales Order Item Number],
        [CMPNY_KEY],
        [WRK_CNTR_KEY],
        [COST_CNTR_KEY],
        [OPERATION_STD_TEXT],
        [Operation Short Text],
        [PSTNG_DATE_KEY],
        [PLNG_PLNT_KEY],
        [Entry Create Date],
        [Person Who Entererd],
        [Operation Confirm Counter],
        [ACTUAL_WRK],
        [Actual Work UOM],
        [Accounting Indicator],
        [REMG_WRK],
        [Remaining Work UOM],
        [ACTUAL_WRK_IN_HRS],
        [REMG_WRK_IN_HRS],
        [Work In Hours UOM],
        [ACTIVITY_TYP_KEY],
        [Operation Confirm Text],
        [Reason for Variance],
        [Confirm  Counter  Of  Cancelled  Confirmation],
        [SOLD_TO_CUST_KEY],
        [PERSONEL_NUM_KEY],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [SERVC_ORDER_KEY],
        [SALES_AREA_KEY],
        [OPERATING_PLNT_KEY],
        [SERVC_ORDER_CREATE_DATE_KEY],
        [ACCT_IND],
        [PARNT_CUST_KEY],
        [Reason for Variance Description],
        [Partial Final Confirm],
        [TCHNCL_COMPLETION_DATE_KEY],
        [SALES_ORDER_ID],
        [Accounting Indicator Description],
		
		--Below columns are added for the Alias tables
		
        [SERV_ORDER_INVOICE_CREATED_DATE_KEY],
        [OPERATING_PLANT_REGION_PLANT],
        [PLANNING_PLANT_REGION_PLANT],
        [PERSONNEL_PLANT_REGION_PLANT],
        [PARENT_CUST_KEY],
        [PAYER_CUST_KEY],
        [SHIP_TO_CUST_KEY],
        [BRAND_OWNER_CUST_KEY],
        [CUST_CONTACT_KEY],
        [PERSON_RESP_PERSONNEL_KEY],
        [CYLINDER_OWNER_CUST_KEY],
        [AGENCY_CUST_KEY],
        [PRINTER_CUST_KEY],
        [SUPPLIER_CUST_KEY],
        [EMPLOYEE_RESP_PERSONEL_KEY],
        [EMPLOYEE_RESP_2_PERSONEL_KEY],
        [FORWARDING_AGENT_VENDOR_KEY],
        [UNITIZATION_AGENT_VENDOR_KEY],
        [ORDER_FOR_CUSTOMER_ADDR_KEY],
        [SO_PARENT_CUST_KEY],
        [BILL_TO_CUST_KEY],
        [CUSTOMER_PROJECT_MANAGER_CUST_CONTACT_KEY],
        [SALES_PERSON_PERSONEL_KEY],
        [SOLDTO_CUST_KEY],		
        [SOIPTNR_KEY],
		[PRDVCON_KEY],
        [PROFCHZ_PROFT_CNTR_KEY],
        [PROFCVZ_PROFT_CNTR_KEY],
        [WORKCHZ_WRK_CNTR_KEY],
        [WORKCVZ_WRK_CNTR_KEY],
        [COSTCHZ_COST_CNTR_KEY],
        [COSTCVZ_COST_CNTR_KEY]
    )
    SELECT
        FACT.[SEG_CD_KEY]  ,
	    FACT.[OPERATION_TASK_LIST_ID] ,
	    FACT.[OPERATION_COUNTER_ID] ,
	    FACT.[OPERATION_ACTIVITY_ID] ,
	    FACT.[OPERATION_CONFIRM_ID] ,
	    FACT.[OPERATION_SEQ_ID] ,
	    FACT.[PROFT_CNTR_KEY]  ,
	    FACT.[SALES_ORDER_KEY]  ,
	    FACT.[SALES_ORDER_ITM_NBR]  ,
	    FACT.[CMPNY_KEY] ,
	    FACT.[WRK_CNTR_KEY]  ,
	    FACT.[COST_CNTR_KEY]  ,
	    FACT.[OPERATION_STD_TEXT] ,
	    FACT.[OPERATION_SHORT_TEXT] ,
	    FACT.[PSTNG_DATE_KEY]  ,
	    FACT.[PLNG_PLNT_KEY]  ,
	    FACT.[ENTRY_CREATE_DATE] ,
	    FACT.[PERSON_WHO_ENTERERD] ,
	    FACT.[OPERATION_CONFIRM_COUNTER] ,
	    FACT.[ACTUAL_WRK] ,
	    FACT.[ACTUAL_WRK_UOM] ,
	    FACT.[ACCTNG_IND] ,
	    FACT.[REMG_WRK] ,
	    FACT.[REMG_WRK_UOM] ,
	    FACT.[ACTUAL_WRK_IN_HRS] ,
	    FACT.[REMG_WRK_IN_HRS] ,
	    FACT.[WRK_IN_HRS_UOM] ,
	    FACT.[ACTIVITY_TYP_KEY]  ,
	    FACT.[OPERATION_CONFIRM_TEXT] ,
	    FACT.[RSN_FOR_VRNC] ,
	    FACT.[CONFIRM_COUNTER_OF_CANCELLED_CO]  ,
	    FACT.[SOLD_TO_CUST_KEY]  ,
	    FACT.[PERSONEL_NUM_KEY]  ,
	    FACT.[ETL_SRC_SYS_CD] ,
	    FACT.[ETL_CREATED_TS] ,
	    FACT.[ETL_UPDTD_TS] ,
	    FACT.[SERVC_ORDER_KEY] ,
	    FACT.[SALES_AREA_KEY] ,
	    FACT.[OPERATING_PLNT_KEY]  ,
	    FACT.[SERVC_ORDER_CREATE_DATE_KEY]  ,
	    FACT.[ACCT_IND] ,
	    FACT.[PARNT_CUST_KEY]  ,
	    FACT.[RSN_FOR_VRNC_DESC] ,
	    FACT.[PARTIAL_FINAL_CONFIRM] ,
	    FACT.[TCHNCL_COMPLETION_DATE_KEY]  ,
	    FACT.[SALES_ORDER_ID] ,
	    FACT.[ACCTNG_IND_DESC],
	    
	    --Below columns are added for the Alias tables
		
	    CASE WHEN CONVERT(VARCHAR, SERVORD.[Service Order Invoice Create Date], 112) = '19000101' 
			OR SERVORD.[Service Order Invoice Create Date] IS NULL 
			THEN '-1'
			ELSE CONVERT(VARCHAR, SERVORD.[Service Order Invoice Create Date], 112)
			END AS SERV_ORDER_INVOICE_CREATED_DATE_KEY,
	    OPT_PLT.[Operating Plant ID] AS OPERATING_PLANT_REGION_PLANT,
	    PLNG_PLT.[Planning Plant ID] AS PLANNING_PLANT_REGION_PLANT,
	    substring(PERSONL.[Personnel Cost Center ID],4,4) AS PERSONNEL_PLANT_REGION_PLANT,
	    SOIPTNR.PARNT_CUST_KEY AS PARNT_CUST_KEY,
	    SOIPTNR.PAYER_CUST_KEY AS PAYER_CUST_KEY,
	    SOIPTNR.SHIP_TO_CUST_KEY AS SHIP_TO_CUST_KEY,
	    SOIPTNR.BRAND_OWNER_CUST_KEY AS BRAND_OWNER_CUST_KEY,
	    SOIPTNR.CUST_CONTACT_KEY AS CUST_CONTACT_KEY,
	    SOIPTNR.PERSON_RESPNSBLE_KEY AS PERSON_RESP_PERSONNEL_KEY,
	    SOIPTNR.CYLINDER_OWNER_CUST_KEY AS CYLINDER_OWNER_CUST_KEY,
	    SOIPTNR.AGENCY_CUST_KEY AS AGENCY_CUST_KEY,
	    SOIPTNR.PRINTER_CUST_KEY AS PRINTER_CUST_KEY,
	    SOIPTNR.SUPPLIER_CUST_KEY AS SUPPLIER_CUST_KEY,
	    SOIPTNR.EMPL_RESPNSBLE_KEY AS EMPLOYEE_RESP_PERSONEL_KEY,
	    SOIPTNR.EMPL_RESPNSBLE_2_KEY AS EMPLOYEE_RESP_2_PERSONEL_KEY,
	    SOIPTNR.FORWARDING_AGENT_VNDR_KEY AS FORWARDING_AGENT_VENDOR_KEY,
	    SOIPTNR.UNITIZATION_AGENT_VNDR_KEY AS UNITIZATION_AGENT_VENDOR_KEY,
	    SOIPTNR.ORDER_FOR_CUST_KEY AS ORDER_FOR_CUSTOMER_ADDR_KEY,
	    SOIPTNR.SO_PARNT_CUST_KEY AS SO_PARENT_CUST_KEY,
	    SOIPTNR.BILL_TO_CUST_KEY  AS BILL_TO_CUST_KEY, 
	    SOIPTNR.CUST_PROJ_MGR_KEY AS CUSTOMER_PROJECT_MANAGER_CUST_CONTACT_KEY,
	    SOIPTNR.SALES_PERSON_PERSONNEL_KEY AS SALES_PERSON_PERSONEL_KEY,
		SOIPTNR.SOLDTO_CUST_KEY AS SOLDTO_CUST_KEY,
	    CONCAT(FACT.SALES_ORDER_ID, '-', FACT.SALES_ORDER_ITM_NBR) AS SOIPTNR_KEY,
	    CONCAT(FACT.SALES_ORDER_ID, '-', FACT.SALES_ORDER_ITM_NBR) AS PRDVCON_KEY,
		PROFCTR.PROFT_CNTR_KEY AS PROFCHZ_PROFT_CNTR_KEY,
		PROFCTR.PROFT_CNTR_KEY AS PROFCVZ_PROFT_CNTR_KEY,
		WORKCTR.WRK_CNTR_KEY AS WORKCHZ_WRK_CNTR_KEY,
	    WORKCTR.WRK_CNTR_KEY AS WORKCVZ_WRK_CNTR_KEY,
		COSCNTR.COST_CNTR_KEY AS COSTCHZ_COST_CNTR_KEY,
		COSCNTR.COST_CNTR_KEY AS COSTCVZ_COST_CNTR_KEY
	   
	
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_F_PRD_TMCONFS_CUR_D] AS FACT

	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_PRD_SERVORD_CUR_D] AS SERVORD
        ON FACT.SERVC_ORDER_KEY = SERVORD.SERVC_ORDER_KEY

    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_SALAREA_CUR_D] AS	SALAREA
        ON FACT.SALES_AREA_KEY = SALAREA.SALES_AREA_KEY	
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_SEGMENT_CUR_D] AS SEGMENT
	    ON FACT.SEG_CD_KEY = SEGMENT.SEG_KEY
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PROFCTR_CUR_D] AS PROFCTR
	    ON FACT.PROFT_CNTR_KEY = PROFCTR.PROFT_CNTR_KEY
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_SALORDH_CUR_D] AS SALORDH
	    ON FACT.SALES_ORDER_KEY = SALORDH.SALES_ORDER_KEY
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CMPNYCD_CUR_D] AS CMPNYCD
	    ON FACT.CMPNY_KEY = CMPNYCD.CMPNY_KEY
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_WORKCTR_CUR_D] AS WORKCTR
	    ON FACT.WRK_CNTR_KEY = WORKCTR.WRK_CNTR_KEY
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_COSCNTR_CUR_D] AS COSCNTR
	    ON FACT.COST_CNTR_KEY = COSCNTR.COST_CNTR_KEY
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_ACTTYPE_CUR_D] AS ACTTYPE
	    ON FACT.ACTIVITY_TYP_KEY = ACTTYPE.ACTIVITY_TYP_KEY
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PERSONL_CUR_D] AS PERSONL
	    ON FACT.PERSONEL_NUM_KEY = PERSONL.PERSONEL_KEY
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_R_MST_SGK_STNDRD_TXT_CATG_CUR_D] AS SGK_STNDRD_TXT
	    ON FACT.OPERATION_STD_TEXT = SGK_STNDRD_TXT.STANDARD_TEXT_KEY
		
	LEFT JOIN (SELECT SALES_ORDER_ITM_ID,MAX(SALES_ORDER_ID) AS SALES_ORDER_ID FROM
	    [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_PRDVCON_CUR_D] GROUP BY SALES_ORDER_ITM_ID) AS PRDVCON
	    ON FACT.SALES_ORDER_ID = PRDVCON.SALES_ORDER_ID
		AND FACT.SALES_ORDER_ITM_NBR = PRDVCON.SALES_ORDER_ITM_ID
		
	LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_B_SAL_SOIPTNR_CUR_D]  AS SOIPTNR
	    ON CONCAT(FACT.SALES_ORDER_ID, '-', FACT.SALES_ORDER_ITM_NBR) = SOIPTNR.SOIPTNR_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[POSTING_DATE] AS PST_DT
	    ON FACT.PSTNG_DATE_KEY = PST_DT.DATE_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[PLANNING_PLANT] AS PLNG_PLT
	    ON FACT.PLNG_PLNT_KEY = PLNG_PLT.PLNT_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[OPERATING_PLANT] AS OPT_PLT
	    ON FACT.OPERATING_PLNT_KEY = OPT_PLT.PLNT_KEY
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[SERVICE_ORDER_CREATE_DATE] AS SEV_ORD_CT_DT
	    ON FACT.SERVC_ORDER_CREATE_DATE_KEY = SEV_ORD_CT_DT.[DATE KEY]
		
	LEFT JOIN [GLOBAL_EDW].[Propelis].[TECH_COMPLETION_DATE] AS TH_COM_DT
	    ON FACT.TCHNCL_COMPLETION_DATE_KEY = TH_COM_DT.DATE_KEY;
END