CREATE       PROCEDURE [Propelis].[Proc_EDW_V_D_SAL_PRDVCON_CUR_D]
AS
BEGIN
    
    UPDATE T
    SET
	
	T.[PRDT_VARIANT_CONFIG_KEY]  		 						=  S.[PRDT_VARIANT_CONFIG_KEY]  		 				  ,
	T.[SALES_ORDER_ID]                                          =  S.[SALES_ORDER_ID]                                     ,
	T.[SALES_ORDER_ITM_ID]                                      =  S.[SALES_ORDER_ITM_ID]                                 ,
	T.[ZLP BB Reference Job]                                    =  S.[ZLP BB Reference Job]                               ,
    T.[ZLP AV Reference Job Number]                             =  S.[ZLP AV Reference Job Number]                        ,
	T.[ZLP BB Adapt From]                                       =  S.[ZLP BB Adapt From]                                  ,
    T.[ZLP CAD F Previous Job Number]                           =  S.[ZLP CAD F Previous Job Number]                      ,
    T.[ZLP AG Reference Job]                                    =  S.[ZLP AG Reference Job]                               ,
    T.[ZLP BB Version]                                          =  S.[ZLP BB Version]                                     ,
    T.[ZLP AG Project]                                          =  S.[ZLP AG Project]                                     ,
    T.[G Separation ID]                                         =  S.[G Separation ID]                                    ,
    T.[G Emboss Rework]                                         =  S.[G Emboss Rework]                                    ,
    T.[G Chrome Thickness]                                      =  S.[G Chrome Thickness]                                 ,
    T.[G Emboss Double Height]                                  =  S.[G Emboss Double Height]                             ,
    T.[G SE Drawing Number]                                     =  S.[G SE Drawing Number]                                ,
    T.[G Incoming Cylinder Number]                              =  S.[G Incoming Cylinder Number]                         ,
    T.[G Leaving Cylinder Number]                               =  S.[G Leaving Cylinder Number]                          ,
    T.[G Bombage]                                               =  S.[G Bombage]                                          ,
    T.[G Copper Diameter]                                       =  S.[G Copper Diameter]                                  ,
    T.[G Copper Radius]                                         =  S.[G Copper Radius]                                    ,
    T.[G Lower Tolerance]                                       =  S.[G Lower Tolerance]                                  ,
    T.[G Upper Tolerance]                                       =  S.[G Upper Tolerance]                                  ,
    T.[G Copper Thickness]                                      =  S.[G Copper Thickness]                                 ,
    T.[G Extra Copper Work]                                     =  S.[G Extra Copper Work]                                ,
    T.[G Finishing]                                             =  S.[G Finishing]                                        ,
    T.[G Grinding Finishing]                                    =  S.[G Grinding Finishing]                               ,
    T.[G Emboss Hardening]                                      =  S.[G Emboss Hardening]                                 ,
    T.[G Coating]                                               =  S.[G Coating]                                          ,
    T.[G Emboss Bearings]                                       =  S.[G Emboss Bearings]                                  ,
    T.[G Inbnd Cylinder]                                        =  S.[G Inbnd Cylinder]                                   ,
    T.[G Finishing 2]                                           =  S.[G Finishing 2]                                      ,
    T.[G Emboss Mat Thickness]                                  =  S.[G Emboss Mat Thickness]                             ,
    T.[G Emboss Dehydrathe]                                     =  S.[G Emboss Dehydrathe]                                ,
    T.[G Grinding In Steel]                                     =  S.[G Grinding In Steel]                                ,
    T.[G Ctrl Classtatu]                                        =  S.[G Ctrl Classtatu]                                   ,
    T.[G Imaging Material]                                      =  S.[G Imaging Material]                                 ,
    T.[G Engraving Width]                                       =  S.[G Engraving Width]                                  ,
    T.[GT Nickel Type]                                          =  S.[GT Nickel Type]                                     ,
    T.[G Emboss Blasting]                                       =  S.[G Emboss Blasting]                                  ,
    T.[G DFF Work Guideline]                                    =  S.[G DFF Work Guideline]                               ,
    T.[GT 3D Coating]                                           =  S.[GT 3D Coating]                                      ,
    T.[Document Version]                                        =  S.[Document Version]                                   ,
    T.[Encoway Document Number]                                 =  S.[Encoway Document Number]                            ,
    T.[Encoway Document Version]                                =  S.[Encoway Document Version]                           ,
    T.[Document Number]                                         =  S.[Document Number]                                    ,
    T.[G Separation DESC]                                       =  S.[G Separation DESC]                                  ,
    T.[G Repro Source]                                          =  S.[G Repro Source]                                     ,
    T.[G Repro Class]                                           =  S.[G Repro Class]                                      ,
    T.[G Face Width]                                            =  S.[G Face Width]                                       ,
    T.[G Final Diameter]                                        =  S.[G Final Diameter]                                   ,
    T.[G Circumference Change]                                  =  S.[G Circumference Change]                             ,
    T.[G Number of Multiple Engravings]                         =  S.[G Number of Multiple Engravings]                    ,
    T.[G Cylinder Conditions]                                   =  S.[G Cylinder Conditions]                              ,
    T.[G Repro Rework]                                          =  S.[G Repro Rework]                                     ,
    T.[G Repro Team]                                            =  S.[G Repro Team]                                       ,
    T.[G ROTO Technology]                                       =  S.[G ROTO Technology]                                  ,
    T.[G Repro Composition]                                     =  S.[G Repro Composition]                                ,
    T.[G Brandowner]                                            =  S.[G Brandowner]                                       ,
    T.[G Cylinder Type]                                         =  S.[G Cylinder Type]                                    ,
    T.[G Axial Width]                                           =  S.[G Axial Width]                                      ,
    T.[G Business Unit]                                         =  S.[G Business Unit]                                    ,
    T.[G Position Number]                                       =  S.[G Position Number]                                  ,
    T.[Batch Class]                                             =  S.[Batch Class]                                        ,
    T.[G Original Diameter]                                     =  S.[G Original Diameter]                                ,
    T.[G Original Wall Thickness]                               =  S.[G Original Wall Thickness]                          ,
    T.[G Original Copper Layer]                                 =  S.[G Original Copper Layer]                            ,
    T.[G Original Steelbase Order]                              =  S.[G Original Steelbase Order]                         ,
    T.[G Original Engraving Surface]                            =  S.[G Original Engraving Surface]                       ,
    T.[G Original Cylinder Surface]                             =  S.[G Original Cylinder Surface]                        ,
    T.[G Original Threads]                                      =  S.[G Original Threads]                                 ,
    T.[G Printing Circumference]                                =  S.[G Printing Circumference]                           ,
    T.[G Engraving Type]                                        =  S.[G Engraving Type]                                   ,
    T.[ETL_SRC_SYS_CD]                                          =  S.[ETL_SRC_SYS_CD]                                     ,
    T.[ETL_EFFECTV_BEGIN_DATE]                                  =  S.[ETL_EFFECTV_BEGIN_DATE]                             ,
    T.[ETL_EFFECTV_END_DATE]                                    =  S.[ETL_EFFECTV_END_DATE]                               ,
    T.[ETL_CURR_RCD_IND]                                        =  S.[ETL_CURR_RCD_IND]                                   ,
    T.[ETL_CREATED_TS]                                          =  S.[ETL_CREATED_TS]                                     ,
    T.[ETL_UPDTD_TS]                                            =  S.[ETL_UPDTD_TS]                                       ,
    T.[ZLP BB Reference Job Description]                        =  S.[ZLP BB Reference Job Description]                   ,
    T.[ZLP AV Reference Job Number Description]                 =  S.[ZLP AV Reference Job Number Description]            ,
    T.[ZLP BB Adapt From Description]                           =  S.[ZLP BB Adapt From Description]                      ,
    T.[ZLP CAD F Previous Job Number Description]               =  S.[ZLP CAD F Previous Job Number Description]          ,
    T.[ZLP AG Reference Job Description]                        =  S.[ZLP AG Reference Job Description]                   ,
    T.[ZLP BB Version Description]                              =  S.[ZLP BB Version Description]                         ,
    T.[ZLP AG Project Description]                              =  S.[ZLP AG Project Description]                         ,
    T.[G Separation ID Description]                             =  S.[G Separation ID Description]                        ,
    T.[G Emboss Rework Description]                             =  S.[G Emboss Rework Description]                        ,
    T.[G Chrome Thickness Description]                          =  S.[G Chrome Thickness Description]                     ,
    T.[G Emboss Double Height Description]                      =  S.[G Emboss Double Height Description]                 ,
    T.[G SE Draw Number Description]                            =  S.[G SE Draw Number Description]                       ,
    T.[G Incoming Cylinder Number Description]                  =  S.[G Incoming Cylinder Number Description]             ,
    T.[G Leaving Cylinder Number Description]                   =  S.[G Leaving Cylinder Number Description]              ,
    T.[G Bombage Description]                                   =  S.[G Bombage Description]                              ,
    T.[G Copper Diameter Description]                           =  S.[G Copper Diameter Description]                      ,
    T.[G Copper Radius Description]                             =  S.[G Copper Radius Description]                        ,
    T.[G Lower Tolerance Description]                           =  S.[G Lower Tolerance Description]                      ,
    T.[G Upper Tolerance Description]                           =  S.[G Upper Tolerance Description]                      ,
    T.[G Copper Thickness Description]                          =  S.[G Copper Thickness Description]                     ,
    T.[G Extra Copper Work Description]                         =  S.[G Extra Copper Work Description]                    ,
    T.[G Finishing Description]                                 =  S.[G Finishing Description]                            ,
    T.[G Grinding Finishing Description]                        =  S.[G Grinding Finishing Description]                   ,
    T.[G Emboss Hardening Description]                          =  S.[G Emboss Hardening Description]                     ,
    T.[G Coating Description]                                   =  S.[G Coating Description]                              ,
    T.[G Emboss Bearings Description]                           =  S.[G Emboss Bearings Description]                      ,
    T.[G Inbnd Cylinder Description]                            =  S.[G Inbnd Cylinder Description]                       ,
    T.[G Finishing 2 Description]                               =  S.[G Finishing 2 Description]                          ,
    T.[G Emboss Mat Thickness Description]                      =  S.[G Emboss Mat Thickness Description]                 ,
    T.[G Emboss Dehydrathe Description]                         =  S.[G Emboss Dehydrathe Description]                    ,
    T.[G Grinding In Steel Description]                         =  S.[G Grinding In Steel Description]                    ,
    T.[G Ctrl Classtatu Description]                            =  S.[G Ctrl Classtatu Description]                       ,
    T.[G Imaging Material Description]                          =  S.[G Imaging Material Description]                     ,
    T.[G Engraving Width Description]                           =  S.[G Engraving Width Description]                      ,
    T.[GT Nickel Type Description]                              =  S.[GT Nickel Type Description]                         ,
    T.[G Emboss Blasting Description]                           =  S.[G Emboss Blasting Description]                      ,
    T.[G DFF Work Guideline Description]                        =  S.[G DFF Work Guideline Description]                   ,
    T.[GT 3D Coating Description]                               =  S.[GT 3D Coating Description]                          ,
    T.[Document Version Description]                            =  S.[Document Version Description]                       ,
    T.[Encoway Document Number Description]                     =  S.[Encoway Document Number Description]                ,
    T.[Encoway Document Version Description]                    =  S.[Encoway Document Version Description]               ,
    T.[Document Number Description]                             =  S.[Document Number Description]                        ,
    T.[G Separation DESC Description]                           =  S.[G Separation DESC Description]                      ,
    T.[G Repro Source Description]                              =  S.[G Repro Source Description]                         ,
    T.[G Repro Class Description]                               =  S.[G Repro Class Description]                          ,
    T.[G Face Width Description]                                =  S.[G Face Width Description]                           ,
    T.[G Final Diameter Description]                            =  S.[G Final Diameter Description]                       ,
    T.[G Circumference Change Description]                      =  S.[G Circumference Change Description]                 ,
    T.[G Number of Multiple Engravings Description]             =  S.[G Number of Multiple Engravings Description]        ,
    T.[G Cylinder Conditions Description]                       =  S.[G Cylinder Conditions Description]                  ,
    T.[G Repro Rework Description]                              =  S.[G Repro Rework Description]                         ,
    T.[G Repro Team Description]                                =  S.[G Repro Team Description]                           ,
    T.[G ROTO Technology Description]                           =  S.[G ROTO Technology Description]                      ,
	T.[G Repro Composition Description]                         =  S.[G Repro Composition Description]                    ,
	T.[G Brandowner Description]                                =  S.[G Brandowner Description]                           ,
	T.[G Cylinder Type Description]                             =  S.[G Cylinder Type Description]                        ,
	T.[G Axial Width Description]                               =  S.[G Axial Width Description]                          ,
	T.[G Business Unit Description]                             =  S.[G Business Unit Description]                        ,
	T.[G Position Number Description]                           =  S.[G Position Number Description]                      ,
	T.[Batch Class Description]                                 =  S.[Batch Class Description]                            ,
	T.[G Original Diameter Description]                         =  S.[G Original Diameter Description]                    ,
	T.[G Original Wall Thickness Description]                   =  S.[G Original Wall Thickness Description]              ,
	T.[G Original Copper Layer Description]                     =  S.[G Original Copper Layer Description]                ,
	T.[G Original Steelbase Order Description]                  =  S.[G Original Steelbase Order Description]             ,
	T.[G Original Engraving Surface Description]                =  S.[G Original Engraving Surface Description]           ,
	T.[G Original Cylinder Surface Description]                 =  S.[G Original Cylinder Surface Description]            ,
	T.[G Original Threads Description]                          =  S.[G Original Threads Description]                     ,
	T.[G Printing Circumference Description]                    =  S.[G Printing Circumference Description]               ,
	T.[G Engraving Type Description]                            =  S.[G Engraving Type Description]                       ,
	T.[ZLP Customer Specific Field Label 01]                    =  S.[ZLP Customer Specific Field Label 01]               ,
	T.[ZLP Customer Specific Field Label 02]                    =  S.[ZLP Customer Specific Field Label 02]               ,
	T.[ZLP Customer Specific Field Label 03]                    =  S.[ZLP Customer Specific Field Label 03]               ,
	T.[ZLP Customer Specific Field Label 04]                    =  S.[ZLP Customer Specific Field Label 04]               ,
	T.[ZLP Customer Specific Field Label 05]                    =  S.[ZLP Customer Specific Field Label 05]               ,
	T.[ZLP Customer Specific Field Label 06]                    =  S.[ZLP Customer Specific Field Label 06]               ,
	T.[ZLP Customer Specific Field Label 07]                    =  S.[ZLP Customer Specific Field Label 07]               ,
	T.[ZLP Customer Specific Field Label 08]                    =  S.[ZLP Customer Specific Field Label 08]               ,
	T.[ZLP Customer Specific Field Label 09]                    =  S.[ZLP Customer Specific Field Label 09]               ,
	T.[ZLP Customer Specific Field Label 10]                    =  S.[ZLP Customer Specific Field Label 10]               ,
	T.[ZLP Customer Specific Field Label 11]                    =  S.[ZLP Customer Specific Field Label 11]               ,
	T.[ZLP Customer Specific Field Label 12]                    =  S.[ZLP Customer Specific Field Label 12]               ,
	T.[ZLP Customer Specific Field Label 13]                    =  S.[ZLP Customer Specific Field Label 13]               ,
	T.[ZLP Customer Specific Field Label 14]                    =  S.[ZLP Customer Specific Field Label 14]               ,
	T.[ZLP Customer Specific Field Label 15]                    =  S.[ZLP Customer Specific Field Label 15]               ,
	T.[ZLP Customer Specific Field Label 16]                    =  S.[ZLP Customer Specific Field Label 16]               ,
	T.[ZLP Customer Specific Field Label 17]                    =  S.[ZLP Customer Specific Field Label 17]               ,
	T.[ZLP Customer Specific Field Label 18]                    =  S.[ZLP Customer Specific Field Label 18]               ,
	T.[ZLP Customer Specific Field Label 19]                    =  S.[ZLP Customer Specific Field Label 19]               ,
	T.[ZLP Customer Specific Field Label 20]                    =  S.[ZLP Customer Specific Field Label 20]               ,
	T.[ZLP Customer Specific Field Label 01 Description]        =  S.[ZLP Customer Specific Field Label 01 Description]   ,
	T.[ZLP Customer Specific Field Label 02 Description]        =  S.[ZLP Customer Specific Field Label 02 Description]   ,
	T.[ZLP Customer Specific Field Label 03 Description]        =  S.[ZLP Customer Specific Field Label 03 Description]   ,
	T.[ZLP Customer Specific Field Label 04 Description]        =  S.[ZLP Customer Specific Field Label 04 Description]   ,
	T.[ZLP Customer Specific Field Label 05 Description]        =  S.[ZLP Customer Specific Field Label 05 Description]   ,
	T.[ZLP Customer Specific Field Label 06 Description]        =  S.[ZLP Customer Specific Field Label 06 Description]   ,
	T.[ZLP Customer Specific Field Label 07 Description]        =  S.[ZLP Customer Specific Field Label 07 Description]   ,
	T.[ZLP Customer Specific Field Label 08 Description]        =  S.[ZLP Customer Specific Field Label 08 Description]   ,
	T.[ZLP Customer Specific Field Label 09 Description]        =  S.[ZLP Customer Specific Field Label 09 Description]   ,
	T.[ZLP Customer Specific Field Label 10 Description]        =  S.[ZLP Customer Specific Field Label 10 Description]   ,
	T.[ZLP Customer Specific Field Label 11 Description]        =  S.[ZLP Customer Specific Field Label 11 Description]   ,
	T.[ZLP Customer Specific Field Label 12 Description]        =  S.[ZLP Customer Specific Field Label 12 Description]   ,
	T.[ZLP Customer Specific Field Label 13 Description]        =  S.[ZLP Customer Specific Field Label 13 Description]   ,
	T.[ZLP Customer Specific Field Label 14 Description]        =  S.[ZLP Customer Specific Field Label 14 Description]   ,
	T.[ZLP Customer Specific Field Label 15 Description]        =  S.[ZLP Customer Specific Field Label 15 Description]   ,
	T.[ZLP Customer Specific Field Label 16 Description]        =  S.[ZLP Customer Specific Field Label 16 Description]   ,
	T.[ZLP Customer Specific Field Label 17 Description]        =  S.[ZLP Customer Specific Field Label 17 Description]   ,
	T.[ZLP Customer Specific Field Label 18 Description]        =  S.[ZLP Customer Specific Field Label 18 Description]   ,
	T.[ZLP Customer Specific Field Label 19 Description]        =  S.[ZLP Customer Specific Field Label 19 Description]   ,
	T.[ZLP Customer Specific Field Label 20 Description]        =  S.[ZLP Customer Specific Field Label 20 Description]   ,
	T.[GT Screen Circumference]                                 =  S.[GT Screen Circumference]                            ,
	T.[GT Screen Length]                                        =  S.[GT Screen Length]                                   ,
	T.[G Plate Length]                                          =  S.[G Plate Length]                                     ,
	T.[G Plate Width]                                           =  S.[G Plate Width]                                      ,
	T.[G Emboss Depth]                                          =  S.[G Emboss Depth]                                     ,
	T.[GT C Nickel Plating]                                     =  S.[GT C Nickel Plating]                                ,
	T.[G Emboss Steps]                                          =  S.[G Emboss Steps]                                     ,
	T.[GT Screen Circumference Description]                     =  S.[GT Screen Circumference Description]                ,
	T.[GT Screen Length Description]                            =  S.[GT Screen Length Description]                       ,
	T.[G Plate Length Description]                              =  S.[G Plate Length Description]                         ,
	T.[G Plate Width Description]                               =  S.[G Plate Width Description]                          ,
	T.[G Emboss Depth Description]                              =  S.[G Emboss Depth Description]                         ,
	T.[GT C Nickel Plating Description]                         =  S.[GT C Nickel Plating Description]                    ,
	T.[GT Wall Thickness Description]                           =  S.[GT Wall Thickness Description]                      ,
	T.[G Emboss Steps Description]                              =  S.[G Emboss Steps Description]                         ,
	T.[GT Wall Thickness]                                       =  S.[GT Wall Thickness]                                  ,
	T.[G Engraving Methode]                                     =  S.[G Engraving Methode]                                ,
	T.[G Laser Type]                                            =  S.[G Laser Type]                                       ,
	T.[G Engraving Methode Description]                         =  S.[G Engraving Methode Description]                    ,
	T.[G Laser Type Description]                                =  S.[G Laser Type Description]                           ,
	T.[G Estimated Cylinder Conditions]                         =  S.[G Estimated Cylinder Conditions]                    ,
	T.[G Estimated Circumference Change]                        =  S.[G Estimated Circumference Change]                   ,
	T.[G Emboss Method]                                         =  S.[G Emboss Method]                                    ,
	T.[G Emboss Material]                                       =  S.[G Emboss Material]                                  ,
	T.[GT Screen Type]                                          =  S.[GT Screen Type]                                     ,
	T.[G Estimated Cylinder Conditions Description]             =  S.[G Estimated Cylinder Conditions Description]        ,
	T.[G Estimated Circumference Change Description]            =  S.[G Estimated Circumference Change Description]       ,
	T.[G Emboss Method Description]                             =  S.[G Emboss Method Description]                        ,
	T.[G Emboss Material Description]                           =  S.[G Emboss Material Description]                      ,
	T.[GT Screen Type Description]                              =  S.[GT Screen Type Description]                         ,
	T.[ZLP ANZF VS]                                             =  S.[ZLP ANZF VS]                                        ,
	T.[ZLP ANZF VS Description]                                 =  S.[ZLP ANZF VS Description]                            ,
	T.[G Copper Hardness HV]                                    =  S.[G Copper Hardness HV]                               ,
	T.[G Copper Hardness HV Description]                        =  S.[G Copper Hardness HV Description]                   ,
	T.[ZLP BB Color Profile]                                    =  S.[ZLP BB Color Profile]                               ,
	T.[ZLP BB Color Profile Description]                        =  S.[ZLP BB Color Profile Description]                   ,
	T.[ZLP AG F Color 01]                                       =  S.[ZLP AG F Color 01]                                  ,
	T.[ZLP AG F Color 02]                                       =  S.[ZLP AG F Color 02]                                  ,
	T.[ZLP AG F Color 03]                                       =  S.[ZLP AG F Color 03]                                  ,
	T.[ZLP AG F Color 04]                                       =  S.[ZLP AG F Color 04]                                  ,
	T.[ZLP AG F Color 05]                                       =  S.[ZLP AG F Color 05]                                  ,
	T.[ZLP AG F Color 06]                                       =  S.[ZLP AG F Color 06]                                  ,
	T.[ZLP AG F Color 07]                                       =  S.[ZLP AG F Color 07]                                  ,
	T.[ZLP AG F Color 08]                                       =  S.[ZLP AG F Color 08]                                  ,
	T.[ZLP AG F Color 09]                                       =  S.[ZLP AG F Color 09]                                  ,
	T.[ZLP AG F Color 10]                                       =  S.[ZLP AG F Color 10]                                  ,
	T.[ZLP AG F Color 11]                                       =  S.[ZLP AG F Color 11]                                  ,
	T.[ZLP AG F Color 12]                                       =  S.[ZLP AG F Color 12]                                  ,
	T.[ZLP AG F Color 13]                                       =  S.[ZLP AG F Color 13]                                  ,
	T.[ZLP AG F Color 14]                                       =  S.[ZLP AG F Color 14]                                  ,
	T.[ZLP AG F Color 15]                                       =  S.[ZLP AG F Color 15]                                  ,
	T.[ZLP AG F Color 16]                                       =  S.[ZLP AG F Color 16]                                  ,
	T.[ZLP AG F Color 17]                                       =  S.[ZLP AG F Color 17]                                  ,
	T.[ZLP AG F Color 18]                                       =  S.[ZLP AG F Color 18]                                  ,
	T.[ZLP AG F Color 19]                                       =  S.[ZLP AG F Color 19]                                  ,
	T.[ZLP AG F Color 20]                                       =  S.[ZLP AG F Color 20]                                  ,
	T.[ZLP AG C Customer Color 01]                              =  S.[ZLP AG C Customer Color 01]                         ,
	T.[ZLP AG C Customer Color 02]                              =  S.[ZLP AG C Customer Color 02]                         ,
	T.[ZLP AG C Customer Color 03]                              =  S.[ZLP AG C Customer Color 03]                         ,
	T.[ZLP AG C Customer Color 04]                              =  S.[ZLP AG C Customer Color 04]                         ,
	T.[ZLP AG C Customer Color 05]                              =  S.[ZLP AG C Customer Color 05]                         ,
	T.[ZLP AG C Customer Color 06]                              =  S.[ZLP AG C Customer Color 06]                         ,
	T.[ZLP AG C Customer Color 07]                              =  S.[ZLP AG C Customer Color 07]                         ,
	T.[ZLP AG C Customer Color 08]                              =  S.[ZLP AG C Customer Color 08]                         ,
	T.[ZLP AG C Customer Color 09]                              =  S.[ZLP AG C Customer Color 09]                         ,
	T.[ZLP AG C Customer Color 10]                              =  S.[ZLP AG C Customer Color 10]                         ,
	T.[ZLP AG C Customer Color 11]                              =  S.[ZLP AG C Customer Color 11]                         ,
	T.[ZLP AG C Customer Color 12]                              =  S.[ZLP AG C Customer Color 12]                         ,
	T.[ZLP AG C Customer Color 13]                              =  S.[ZLP AG C Customer Color 13]                         ,
	T.[ZLP AG C Customer Color 14]                              =  S.[ZLP AG C Customer Color 14]                         ,
	T.[ZLP AG C Customer Color 15]                              =  S.[ZLP AG C Customer Color 15]                         ,
	T.[ZLP AG C Customer Color 16]                              =  S.[ZLP AG C Customer Color 16]                         ,
	T.[ZLP AG C Customer Color 17]                              =  S.[ZLP AG C Customer Color 17]                         ,
	T.[ZLP AG C Customer Color 18]                              =  S.[ZLP AG C Customer Color 18]                         ,
	T.[ZLP AG C Customer Color 19]                              =  S.[ZLP AG C Customer Color 19]                         ,
	T.[ZLP AG C Customer Color 20]                              =  S.[ZLP AG C Customer Color 20]                         ,
	T.[ZLP AG F Color 01 Description]                           =  S.[ZLP AG F Color 01 Description]                      ,
	T.[ZLP AG F Color 02 Description]                           =  S.[ZLP AG F Color 02 Description]                      ,
	T.[ZLP AG F Color 03 Description]                           =  S.[ZLP AG F Color 03 Description]                      ,
	T.[ZLP AG F Color 04 Description]                           =  S.[ZLP AG F Color 04 Description]                      ,
	T.[ZLP AG F Color 05 Description]                           =  S.[ZLP AG F Color 05 Description]                      ,
	T.[ZLP AG F Color 06 Description]                           =  S.[ZLP AG F Color 06 Description]                      ,
	T.[ZLP AG F Color 07 Description]                           =  S.[ZLP AG F Color 07 Description]                      ,
	T.[ZLP AG F Color 08 Description]                           =  S.[ZLP AG F Color 08 Description]                      ,
	T.[ZLP AG F Color 09 Description]                           =  S.[ZLP AG F Color 09 Description]                      ,
	T.[ZLP AG F Color 10 Description]                           =  S.[ZLP AG F Color 10 Description]                      ,
	T.[ZLP AG F Color 11 Description]                           =  S.[ZLP AG F Color 11 Description]                      ,
	T.[ZLP AG F Color 12 Description]                           =  S.[ZLP AG F Color 12 Description]                      ,
	T.[ZLP AG F Color 13 Description]                           =  S.[ZLP AG F Color 13 Description]                      ,
	T.[ZLP AG F Color 14 Description]                           =  S.[ZLP AG F Color 14 Description]                      ,
	T.[ZLP AG F Color 15 Description]                           =  S.[ZLP AG F Color 15 Description]                      ,
	T.[ZLP AG F Color 16 Description]                           =  S.[ZLP AG F Color 16 Description]                      ,
	T.[ZLP AG F Color 17 Description]                           =  S.[ZLP AG F Color 17 Description]                      ,
	T.[ZLP AG F Color 18 Description]                           =  S.[ZLP AG F Color 18 Description]                      ,
	T.[ZLP AG F Color 19 Description]                           =  S.[ZLP AG F Color 19 Description]                      ,
	T.[ZLP AG F Color 20 Description]                           =  S.[ZLP AG F Color 20 Description]                      ,
	T.[ZLP AG C Customer Color 01 Description]                  =  S.[ZLP AG C Customer Color 01 Description]             ,
	T.[ZLP AG C Customer Color 02 Description]                  =  S.[ZLP AG C Customer Color 02 Description]             ,
	T.[ZLP AG C Customer Color 03 Description]                  =  S.[ZLP AG C Customer Color 03 Description]             ,
	T.[ZLP AG C Customer Color 04 Description]                  =  S.[ZLP AG C Customer Color 04 Description]             ,
	T.[ZLP AG C Customer Color 05 Description]                  =  S.[ZLP AG C Customer Color 05 Description]             ,
	T.[ZLP AG C Customer Color 06 Description]                  =  S.[ZLP AG C Customer Color 06 Description]             ,
	T.[ZLP AG C Customer Color 07 Description]                  =  S.[ZLP AG C Customer Color 07 Description]             ,
	T.[ZLP AG C Customer Color 08 Description]                  =  S.[ZLP AG C Customer Color 08 Description]             ,
	T.[ZLP AG C Customer Color 09 Description]                  =  S.[ZLP AG C Customer Color 09 Description]             ,
	T.[ZLP AG C Customer Color 10 Description]                  =  S.[ZLP AG C Customer Color 10 Description]             ,
	T.[ZLP AG C Customer Color 11 Description]                  =  S.[ZLP AG C Customer Color 11 Description]             ,
	T.[ZLP AG C Customer Color 12 Description]                  =  S.[ZLP AG C Customer Color 12 Description]             ,
	T.[ZLP AG C Customer Color 13 Description]                  =  S.[ZLP AG C Customer Color 13 Description]             ,
	T.[ZLP AG C Customer Color 14 Description]                  =  S.[ZLP AG C Customer Color 14 Description]             ,
	T.[ZLP AG C Customer Color 15 Description]                  =  S.[ZLP AG C Customer Color 15 Description]             ,
	T.[ZLP AG C Customer Color 16 Description]                  =  S.[ZLP AG C Customer Color 16 Description]             ,
	T.[ZLP AG C Customer Color 17 Description]                  =  S.[ZLP AG C Customer Color 17 Description]             ,
	T.[ZLP AG C Customer Color 18 Description]                  =  S.[ZLP AG C Customer Color 18 Description]             ,
	T.[ZLP AG C Customer Color 19 Description]                  =  S.[ZLP AG C Customer Color 19 Description]             ,
	T.[ZLP AG C Customer Color 20 Description]                  =  S.[ZLP AG C Customer Color 20 Description]             ,
	T.[ZLP AG F Line Screen 1]                                  =  S.[ZLP AG F Line Screen 1]                             ,
	T.[ZLP AG F Line Screen 2]                                  =  S.[ZLP AG F Line Screen 2]                             ,
	T.[ZLP AG F Line Screen 3]                                  =  S.[ZLP AG F Line Screen 3]                             ,
	T.[ZLP AG F Line Screen 4]                                  =  S.[ZLP AG F Line Screen 4]                             ,
	T.[ZLP AG F Line Screen 5]                                  =  S.[ZLP AG F Line Screen 5]                             ,
	T.[ZLP AG F Line Screen 6]                                  =  S.[ZLP AG F Line Screen 6]                             ,
	T.[ZLP AG F Line Screen 7]                                  =  S.[ZLP AG F Line Screen 7]                             ,
	T.[ZLP AG F Line Screen 8]                                  =  S.[ZLP AG F Line Screen 8]                             ,
	T.[ZLP AG F Line Screen 9]                                  =  S.[ZLP AG F Line Screen 9]                             ,
	T.[ZLP AG F Line Screen 10]                                 =  S.[ZLP AG F Line Screen 10]                            ,
	T.[ZLP AG F Line Screen 11]                                 =  S.[ZLP AG F Line Screen 11]                            ,
	T.[ZLP AG F Line Screen 12]                                 =  S.[ZLP AG F Line Screen 12]                            ,
	T.[ZLP AG F Line Screen 13]                                 =  S.[ZLP AG F Line Screen 13]                            ,
	T.[ZLP AG F Line Screen 14]                                 =  S.[ZLP AG F Line Screen 14]                            ,
	T.[ZLP AG F Line Screen 15]                                 =  S.[ZLP AG F Line Screen 15]                            ,
	T.[ZLP AG F Line Screen 16]                                 =  S.[ZLP AG F Line Screen 16]                            ,
	T.[ZLP AG F Line Screen 17]                                 =  S.[ZLP AG F Line Screen 17]                            ,
	T.[ZLP AG F Line Screen 18]                                 =  S.[ZLP AG F Line Screen 18]                            ,
	T.[ZLP AG F Line Screen 19]                                 =  S.[ZLP AG F Line Screen 19]                            ,
	T.[ZLP AG F Line Screen 20]                                 =  S.[ZLP AG F Line Screen 20]                            ,
	T.[ZLP AG F Line Screen 1 Description]                      =  S.[ZLP AG F Line Screen 1 Description]                 ,
	T.[ZLP AG F Line Screen 2 Description]                      =  S.[ZLP AG F Line Screen 2 Description]                 ,
	T.[ZLP AG F Line Screen 3 Description]                      =  S.[ZLP AG F Line Screen 3 Description]                 ,
	T.[ZLP AG F Line Screen 4 Description]                      =  S.[ZLP AG F Line Screen 4 Description]                 ,
	T.[ZLP AG F Line Screen 5 Description]                      =  S.[ZLP AG F Line Screen 5 Description]                 ,
	T.[ZLP AG F Line Screen 6 Description]                      =  S.[ZLP AG F Line Screen 6 Description]                 ,
	T.[ZLP AG F Line Screen 7 Description]                      =  S.[ZLP AG F Line Screen 7 Description]                 ,
	T.[ZLP AG F Line Screen 8 Description]                      =  S.[ZLP AG F Line Screen 8 Description]                 ,
	T.[ZLP AG F Line Screen 9 Description]                      =  S.[ZLP AG F Line Screen 9 Description]                 ,
	T.[ZLP AG F Line Screen 10 Description]                     =  S.[ZLP AG F Line Screen 10 Description]                ,
	T.[ZLP AG F Line Screen 11 Description]                     =  S.[ZLP AG F Line Screen 11 Description]                ,
	T.[ZLP AG F Line Screen 12 Description]                     =  S.[ZLP AG F Line Screen 12 Description]                ,
	T.[ZLP AG F Line Screen 13 Description]                     =  S.[ZLP AG F Line Screen 13 Description]                ,
	T.[ZLP AG F Line Screen 14 Description]                     =  S.[ZLP AG F Line Screen 14 Description]                ,
	T.[ZLP AG F Line Screen 15 Description]                     =  S.[ZLP AG F Line Screen 15 Description]                ,
	T.[ZLP AG F Line Screen 16 Description]                     =  S.[ZLP AG F Line Screen 16 Description]                ,
	T.[ZLP AG F Line Screen 17 Description]                     =  S.[ZLP AG F Line Screen 17 Description]                ,
	T.[ZLP AG F Line Screen 18 Description]                     =  S.[ZLP AG F Line Screen 18 Description]                ,
	T.[ZLP AG F Line Screen 19 Description]                     =  S.[ZLP AG F Line Screen 19 Description]                ,
	T.[ZLP AG F Line Screen 20 Description]                     =  S.[ZLP AG F Line Screen 20 Description]                ,
	T.[ZLP Order Type]	                                        =  S.[ZLP Order Type]	                                  ,
	T.[ZLP Order Type Description]                              =  S.[ZLP Order Type Description]                         ,
    T.[PRDVCON_KEY]                                             =  CONCAT(S.[SALES_ORDER_ID],'-',S.[SALES_ORDER_ITM_ID])


FROM [GLOBAL_EDW].[Propelis].[EDW_V_D_SAL_PRDVCON_CUR_D] T
    INNER JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_PRDVCON_CUR_D] S
        ON T.[PRDT_VARIANT_CONFIG_KEY] = S.[PRDT_VARIANT_CONFIG_KEY];

    -- Step 2: Insert new records 
    INSERT INTO [GLOBAL_EDW].[Propelis].[EDW_V_D_SAL_PRDVCON_CUR_D] (
[PRDT_VARIANT_CONFIG_KEY]  								  ,
[SALES_ORDER_ID]                                          ,
[SALES_ORDER_ITM_ID]                                      ,
[ZLP BB Reference Job]                                    ,
[ZLP AV Reference Job Number]                             ,
[ZLP BB Adapt From]                                       ,
[ZLP CAD F Previous Job Number]                           ,
[ZLP AG Reference Job]                                    ,
[ZLP BB Version]                                          ,
[ZLP AG Project]                                          ,
[G Separation ID]                                         ,
[G Emboss Rework]                                         ,
[G Chrome Thickness]                                      ,
[G Emboss Double Height]                                  ,
[G SE Drawing Number]                                     ,
[G Incoming Cylinder Number]                              ,
[G Leaving Cylinder Number]                               ,
[G Bombage]                                               ,
[G Copper Diameter]                                       ,
[G Copper Radius]                                         ,
[G Lower Tolerance]                                       ,
[G Upper Tolerance]                                       ,
[G Copper Thickness]                                      ,
[G Extra Copper Work]                                     ,
[G Finishing]                                             ,
[G Grinding Finishing]                                    ,
[G Emboss Hardening]                                      ,
[G Coating]                                               ,
[G Emboss Bearings]                                       ,
[G Inbnd Cylinder]                                        ,
[G Finishing 2]                                           ,
[G Emboss Mat Thickness]                                  ,
[G Emboss Dehydrathe]                                     ,
[G Grinding In Steel]                                     ,
[G Ctrl Classtatu]                                        ,
[G Imaging Material]                                      ,
[G Engraving Width]                                       ,
[GT Nickel Type]                                          ,
[G Emboss Blasting]                                       ,
[G DFF Work Guideline]                                    ,
[GT 3D Coating]                                           ,
[Document Version]                                        ,
[Encoway Document Number]                                 ,
[Encoway Document Version]                                ,
[Document Number]                                         ,
[G Separation DESC]                                       ,
[G Repro Source]                                          ,
[G Repro Class]                                           ,
[G Face Width]                                            ,
[G Final Diameter]                                        ,
[G Circumference Change]                                  ,
[G Number of Multiple Engravings]                         ,
[G Cylinder Conditions]                                   ,
[G Repro Rework]                                          ,
[G Repro Team]                                            ,
[G ROTO Technology]                                       ,
[G Repro Composition]                                     ,
[G Brandowner]                                            ,
[G Cylinder Type]                                         ,
[G Axial Width]                                           ,
[G Business Unit]                                         ,
[G Position Number]                                       ,
[Batch Class]                                             ,
[G Original Diameter]                                     ,
[G Original Wall Thickness]                               ,
[G Original Copper Layer]                                 ,
[G Original Steelbase Order]                              ,
[G Original Engraving Surface]                            ,
[G Original Cylinder Surface]                             ,
[G Original Threads]                                      ,
[G Printing Circumference]                                ,
[G Engraving Type]                                        ,
[ETL_SRC_SYS_CD]                                          ,
[ETL_EFFECTV_BEGIN_DATE]                                  ,
[ETL_EFFECTV_END_DATE]                                    ,
[ETL_CURR_RCD_IND]                                        ,
[ETL_CREATED_TS]                                          ,
[ETL_UPDTD_TS]                                            ,
[ZLP BB Reference Job Description]                        ,
[ZLP AV Reference Job Number Description]                 ,
[ZLP BB Adapt From Description]                           ,
[ZLP CAD F Previous Job Number Description]               ,
[ZLP AG Reference Job Description]                        ,
[ZLP BB Version Description]                              ,
[ZLP AG Project Description]                              ,
[G Separation ID Description]                             ,
[G Emboss Rework Description]                             ,
[G Chrome Thickness Description]                         ,
[G Emboss Double Height Description]                      ,
[G SE Draw Number Description]                            ,
[G Incoming Cylinder Number Description]                  ,
[G Leaving Cylinder Number Description]                  ,
[G Bombage Description]                                   ,
[G Copper Diameter Description]                           ,
[G Copper Radius Description]                             ,
[G Lower Tolerance Description]                           ,
[G Upper Tolerance Description]                           ,
[G Copper Thickness Description]                         ,
[G Extra Copper Work Description]                         ,
[G Finishing Description]                                 ,
[G Grinding Finishing Description]                       ,
[G Emboss Hardening Description]                          ,
[G Coating Description]                                   ,
[G Emboss Bearings Description]                           ,
[G Inbnd Cylinder Description]                            ,
[G Finishing 2 Description]                               ,
[G Emboss Mat Thickness Description]                      ,
[G Emboss Dehydrathe Description]                         ,
[G Grinding In Steel Description]                         ,
[G Ctrl Classtatu Description]                            ,
[G Imaging Material Description]                          ,
[G Engraving Width Description]                           ,
[GT Nickel Type Description]                              ,
[G Emboss Blasting Description]                           ,
[G DFF Work Guideline Description]                        ,
[GT 3D Coating Description]                               ,
[Document Version Description]                            ,
[Encoway Document Number Description]                     ,
[Encoway Document Version Description]                    ,
[Document Number Description]                             ,
[G Separation DESC Description]                           ,
[G Repro Source Description]                              ,
[G Repro Class Description]                               ,
[G Face Width Description]                                ,
[G Final Diameter Description]                            ,
[G Circumference Change Description]                      ,
[G Number of Multiple Engravings Description]             ,
[G Cylinder Conditions Description]                       ,
[G Repro Rework Description]                              ,
[G Repro Team Description]                                ,
[G ROTO Technology Description]                           ,
[G Repro Composition Description]                         ,
[G Brandowner Description]                                ,
[G Cylinder Type Description]                             ,
[G Axial Width Description]                               ,
[G Business Unit Description]                             ,
[G Position Number Description]                           ,
[Batch Class Description]                                 ,
[G Original Diameter Description]                         ,
[G Original Wall Thickness Description]                   ,
[G Original Copper Layer Description]                     ,
[G Original Steelbase Order Description]                  ,
[G Original Engraving Surface Description]                ,
[G Original Cylinder Surface Description]                 ,
[G Original Threads Description]                          ,
[G Printing Circumference Description]                    ,
[G Engraving Type Description]                            ,
[ZLP Customer Specific Field Label 01]                    ,
[ZLP Customer Specific Field Label 02]                    ,
[ZLP Customer Specific Field Label 03]                    ,
[ZLP Customer Specific Field Label 04]                    ,
[ZLP Customer Specific Field Label 05]                    ,
[ZLP Customer Specific Field Label 06]                    ,
[ZLP Customer Specific Field Label 07]                    ,
[ZLP Customer Specific Field Label 08]                    ,
[ZLP Customer Specific Field Label 09]                    ,
[ZLP Customer Specific Field Label 10]                    ,
[ZLP Customer Specific Field Label 11]                    ,
[ZLP Customer Specific Field Label 12]                    ,
[ZLP Customer Specific Field Label 13]                    ,
[ZLP Customer Specific Field Label 14]                    ,
[ZLP Customer Specific Field Label 15]                    ,
[ZLP Customer Specific Field Label 16]                    ,
[ZLP Customer Specific Field Label 17]                    ,
[ZLP Customer Specific Field Label 18]                    ,
[ZLP Customer Specific Field Label 19]                    ,
[ZLP Customer Specific Field Label 20]                    ,
[ZLP Customer Specific Field Label 01 Description]        ,
[ZLP Customer Specific Field Label 02 Description]        ,
[ZLP Customer Specific Field Label 03 Description]        ,
[ZLP Customer Specific Field Label 04 Description]        ,
[ZLP Customer Specific Field Label 05 Description]        ,
[ZLP Customer Specific Field Label 06 Description]        ,
[ZLP Customer Specific Field Label 07 Description]        ,
[ZLP Customer Specific Field Label 08 Description]        ,
[ZLP Customer Specific Field Label 09 Description]        ,
[ZLP Customer Specific Field Label 10 Description]        ,
[ZLP Customer Specific Field Label 11 Description]        ,
[ZLP Customer Specific Field Label 12 Description]        ,
[ZLP Customer Specific Field Label 13 Description]        ,
[ZLP Customer Specific Field Label 14 Description]        ,
[ZLP Customer Specific Field Label 15 Description]        ,
[ZLP Customer Specific Field Label 16 Description]        ,
[ZLP Customer Specific Field Label 17 Description]        ,
[ZLP Customer Specific Field Label 18 Description]        ,
[ZLP Customer Specific Field Label 19 Description]        ,
[ZLP Customer Specific Field Label 20 Description]        ,
[GT Screen Circumference]                                 ,
[GT Screen Length]                                       ,
[G Plate Length]                                         ,
[G Plate Width]                                           ,
[G Emboss Depth]                                          ,
[GT C Nickel Plating]                                     ,
[G Emboss Steps]                                          ,
[GT Screen Circumference Description]                    ,
[GT Screen Length Description]                           ,
[G Plate Length Description]                              ,
[G Plate Width Description]                               ,
[G Emboss Depth Description]                              ,
[GT C Nickel Plating Description]                         ,
[GT Wall Thickness Description]                           ,
[G Emboss Steps Description]                              ,
[GT Wall Thickness]                                       ,
[G Engraving Methode]                                     ,
[G Laser Type]                                            ,
[G Engraving Methode Description]                         ,
[G Laser Type Description]                                ,
[G Estimated Cylinder Conditions]                         ,
[G Estimated Circumference Change]                        ,
[G Emboss Method]                                         ,
[G Emboss Material]                                       ,
[GT Screen Type]                                          ,
[G Estimated Cylinder Conditions Description]             ,
[G Estimated Circumference Change Description]            ,
[G Emboss Method Description]                             ,
[G Emboss Material Description]                           ,
[GT Screen Type Description]                              ,
[ZLP ANZF VS]                                           ,
[ZLP ANZF VS Description]                                ,
[G Copper Hardness HV]                                   ,
[G Copper Hardness HV Description]                        ,
[ZLP BB Color Profile]                                    ,
[ZLP BB Color Profile Description]                        ,
[ZLP AG F Color 01]                                       ,
[ZLP AG F Color 02]                                       ,
[ZLP AG F Color 03]                                       ,
[ZLP AG F Color 04]                                       ,
[ZLP AG F Color 05]                                       ,
[ZLP AG F Color 06]                                       ,
[ZLP AG F Color 07]                                       ,
[ZLP AG F Color 08]                                       ,
[ZLP AG F Color 09]                                       ,
[ZLP AG F Color 10]                                       ,
[ZLP AG F Color 11]                                       ,
[ZLP AG F Color 12]                                       ,
[ZLP AG F Color 13]                                       ,
[ZLP AG F Color 14]                                       ,
[ZLP AG F Color 15]                                       ,
[ZLP AG F Color 16]                                       ,
[ZLP AG F Color 17]                                       ,
[ZLP AG F Color 18]                                       ,
[ZLP AG F Color 19]                                       ,
[ZLP AG F Color 20]                                       ,
[ZLP AG C Customer Color 01]                              ,
[ZLP AG C Customer Color 02]                              ,
[ZLP AG C Customer Color 03]                              ,
[ZLP AG C Customer Color 04]                              ,
[ZLP AG C Customer Color 05]                              ,
[ZLP AG C Customer Color 06]                              ,
[ZLP AG C Customer Color 07]                              ,
[ZLP AG C Customer Color 08]                              ,
[ZLP AG C Customer Color 09]                              ,
[ZLP AG C Customer Color 10]                              ,
[ZLP AG C Customer Color 11]                              ,
[ZLP AG C Customer Color 12]                              ,
[ZLP AG C Customer Color 13]                              ,
[ZLP AG C Customer Color 14]                              ,
[ZLP AG C Customer Color 15]                              ,
[ZLP AG C Customer Color 16]                              ,
[ZLP AG C Customer Color 17]                              ,
[ZLP AG C Customer Color 18]                              ,
[ZLP AG C Customer Color 19]                              ,
[ZLP AG C Customer Color 20]                              ,
[ZLP AG F Color 01 Description]                           ,
[ZLP AG F Color 02 Description]                           ,
[ZLP AG F Color 03 Description]                           ,
[ZLP AG F Color 04 Description]                           ,
[ZLP AG F Color 05 Description]                           ,
[ZLP AG F Color 06 Description]                           ,
[ZLP AG F Color 07 Description]                           ,
[ZLP AG F Color 08 Description]                           ,
[ZLP AG F Color 09 Description]                           ,
[ZLP AG F Color 10 Description]                           ,
[ZLP AG F Color 11 Description]                           ,
[ZLP AG F Color 12 Description]                           ,
[ZLP AG F Color 13 Description]                           ,
[ZLP AG F Color 14 Description]                           ,
[ZLP AG F Color 15 Description]                           ,
[ZLP AG F Color 16 Description]                           ,
[ZLP AG F Color 17 Description]                           ,
[ZLP AG F Color 18 Description]                           ,
[ZLP AG F Color 19 Description]                           ,
[ZLP AG F Color 20 Description]                           ,
[ZLP AG C Customer Color 01 Description]                  ,
[ZLP AG C Customer Color 02 Description]                  ,
[ZLP AG C Customer Color 03 Description]                  ,
[ZLP AG C Customer Color 04 Description]                  ,
[ZLP AG C Customer Color 05 Description]                  ,
[ZLP AG C Customer Color 06 Description]                  ,
[ZLP AG C Customer Color 07 Description]                  ,
[ZLP AG C Customer Color 08 Description]                  ,
[ZLP AG C Customer Color 09 Description]                  ,
[ZLP AG C Customer Color 10 Description]                  ,
[ZLP AG C Customer Color 11 Description]                  ,
[ZLP AG C Customer Color 12 Description]                  ,
[ZLP AG C Customer Color 13 Description]                  ,
[ZLP AG C Customer Color 14 Description]                  ,
[ZLP AG C Customer Color 15 Description]                  ,
[ZLP AG C Customer Color 16 Description]                  ,
[ZLP AG C Customer Color 17 Description]                  ,
[ZLP AG C Customer Color 18 Description]                  ,
[ZLP AG C Customer Color 19 Description]                  ,
[ZLP AG C Customer Color 20 Description]                  ,
[ZLP AG F Line Screen 1]                                  ,
[ZLP AG F Line Screen 2]                                  ,
[ZLP AG F Line Screen 3]                                  ,
[ZLP AG F Line Screen 4]                                  ,
[ZLP AG F Line Screen 5]                                  ,
[ZLP AG F Line Screen 6]                                  ,
[ZLP AG F Line Screen 7]                                  ,
[ZLP AG F Line Screen 8]                                  ,
[ZLP AG F Line Screen 9]                                  ,
[ZLP AG F Line Screen 10]                                 ,
[ZLP AG F Line Screen 11]                                 ,
[ZLP AG F Line Screen 12]                                 ,
[ZLP AG F Line Screen 13]                                 ,
[ZLP AG F Line Screen 14]                                 ,
[ZLP AG F Line Screen 15]                                 ,
[ZLP AG F Line Screen 16]                                 ,
[ZLP AG F Line Screen 17]                                 ,
[ZLP AG F Line Screen 18]                                 ,
[ZLP AG F Line Screen 19]                                 ,
[ZLP AG F Line Screen 20]                                 ,
[ZLP AG F Line Screen 1 Description]                      ,
[ZLP AG F Line Screen 2 Description]                      ,
[ZLP AG F Line Screen 3 Description]                      ,
[ZLP AG F Line Screen 4 Description]                      ,
[ZLP AG F Line Screen 5 Description]                      ,
[ZLP AG F Line Screen 6 Description]                      ,
[ZLP AG F Line Screen 7 Description]                      ,
[ZLP AG F Line Screen 8 Description]                      ,
[ZLP AG F Line Screen 9 Description]                      ,
[ZLP AG F Line Screen 10 Description]                     ,
[ZLP AG F Line Screen 11 Description]                     ,
[ZLP AG F Line Screen 12 Description]                     ,
[ZLP AG F Line Screen 13 Description]                     ,
[ZLP AG F Line Screen 14 Description]                     ,
[ZLP AG F Line Screen 15 Description]                     ,
[ZLP AG F Line Screen 16 Description]                     ,
[ZLP AG F Line Screen 17 Description]                     ,
[ZLP AG F Line Screen 18 Description]                     ,
[ZLP AG F Line Screen 19 Description]                     ,
[ZLP AG F Line Screen 20 Description]                     ,
[ZLP Order Type]	                                      ,
[ZLP Order Type Description]                              ,
[PRDVCON_KEY]
)
SELECT

S.[PRDT_VARIANT_CONFIG_KEY]  		 				  ,
S.[SALES_ORDER_ID]                                     ,
S.[SALES_ORDER_ITM_ID]                                 ,
S.[ZLP BB Reference Job]                               ,
S.[ZLP AV Reference Job Number]                        ,
S.[ZLP BB Adapt From]                                  ,
S.[ZLP CAD F Previous Job Number]                      ,
S.[ZLP AG Reference Job]                               ,
S.[ZLP BB Version]                                     ,
S.[ZLP AG Project]                                     ,
S.[G Separation ID]                                    ,
S.[G Emboss Rework]                                    ,
S.[G Chrome Thickness]                                 ,
S.[G Emboss Double Height]                             ,
S.[G SE Drawing Number]                                ,
S.[G Incoming Cylinder Number]                         ,
S.[G Leaving Cylinder Number]                          ,
S.[G Bombage]                                          ,
S.[G Copper Diameter]                                  ,
S.[G Copper Radius]                                    ,
S.[G Lower Tolerance]                                  ,
S.[G Upper Tolerance]                                  ,
S.[G Copper Thickness]                                 ,
S.[G Extra Copper Work]                                ,
S.[G Finishing]                                        ,
S.[G Grinding Finishing]                               ,
S.[G Emboss Hardening]                                 ,
S.[G Coating]                                          ,
S.[G Emboss Bearings]                                  ,
S.[G Inbnd Cylinder]                                   ,
S.[G Finishing 2]                                      ,
S.[G Emboss Mat Thickness]                             ,
S.[G Emboss Dehydrathe]                                ,
S.[G Grinding In Steel]                                ,
S.[G Ctrl Classtatu]                                   ,
S.[G Imaging Material]                                 ,
S.[G Engraving Width]                                  ,
S.[GT Nickel Type]                                     ,
S.[G Emboss Blasting]                                  ,
S.[G DFF Work Guideline]                               ,
S.[GT 3D Coating]                                      ,
S.[Document Version]                                   ,
S.[Encoway Document Number]                            ,
S.[Encoway Document Version]                           ,
S.[Document Number]                                    ,
S.[G Separation DESC]                                  ,
S.[G Repro Source]                                     ,
S.[G Repro Class]                                      ,
S.[G Face Width]                                       ,
S.[G Final Diameter]                                   ,
S.[G Circumference Change]                             ,
S.[G Number of Multiple Engravings]                    ,
S.[G Cylinder Conditions]                              ,
S.[G Repro Rework]                                     ,
S.[G Repro Team]                                       ,
S.[G ROTO Technology]                                  ,
S.[G Repro Composition]                                ,
S.[G Brandowner]                                       ,
S.[G Cylinder Type]                                    ,
S.[G Axial Width]                                      ,
S.[G Business Unit]                                    ,
S.[G Position Number]                                  ,
S.[Batch Class]                                        ,
S.[G Original Diameter]                                ,
S.[G Original Wall Thickness]                          ,
S.[G Original Copper Layer]                            ,
S.[G Original Steelbase Order]                         ,
S.[G Original Engraving Surface]                       ,
S.[G Original Cylinder Surface]                        ,
S.[G Original Threads]                                 ,
S.[G Printing Circumference]                           ,
S.[G Engraving Type]                                   ,
S.[ETL_SRC_SYS_CD]                                     ,
S.[ETL_EFFECTV_BEGIN_DATE]                             ,
S.[ETL_EFFECTV_END_DATE]                               ,
S.[ETL_CURR_RCD_IND]                                   ,
S.[ETL_CREATED_TS]                                     ,
S.[ETL_UPDTD_TS]                                       ,
S.[ZLP BB Reference Job Description]                   ,
S.[ZLP AV Reference Job Number Description]            ,
S.[ZLP BB Adapt From Description]                      ,
S.[ZLP CAD F Previous Job Number Description]          ,
S.[ZLP AG Reference Job Description]                   ,
S.[ZLP BB Version Description]                         ,
S.[ZLP AG Project Description]                         ,
S.[G Separation ID Description]                        ,
S.[G Emboss Rework Description]                        ,
S.[G Chrome Thickness Description]                     ,
S.[G Emboss Double Height Description]                 ,
S.[G SE Draw Number Description]                       ,
S.[G Incoming Cylinder Number Description]             ,
S.[G Leaving Cylinder Number Description]              ,
S.[G Bombage Description]                              ,
S.[G Copper Diameter Description]                      ,
S.[G Copper Radius Description]                        ,
S.[G Lower Tolerance Description]                      ,
S.[G Upper Tolerance Description]                      ,
S.[G Copper Thickness Description]                     ,
S.[G Extra Copper Work Description]                    ,
S.[G Finishing Description]                            ,
S.[G Grinding Finishing Description]                   ,
S.[G Emboss Hardening Description]                     ,
S.[G Coating Description]                              ,
S.[G Emboss Bearings Description]                      ,
S.[G Inbnd Cylinder Description]                       ,
S.[G Finishing 2 Description]                          ,
S.[G Emboss Mat Thickness Description]                 ,
S.[G Emboss Dehydrathe Description]                    ,
S.[G Grinding In Steel Description]                    ,
S.[G Ctrl Classtatu Description]                       ,
S.[G Imaging Material Description]                     ,
S.[G Engraving Width Description]                      ,
S.[GT Nickel Type Description]                         ,
S.[G Emboss Blasting Description]                      ,
S.[G DFF Work Guideline Description]                   ,
S.[GT 3D Coating Description]                          ,
S.[Document Version Description]                       ,
S.[Encoway Document Number Description]                ,
S.[Encoway Document Version Description]               ,
S.[Document Number Description]                        ,
S.[G Separation DESC Description]                      ,
S.[G Repro Source Description]                         ,
S.[G Repro Class Description]                          ,
S.[G Face Width Description]                           ,
S.[G Final Diameter Description]                       ,
S.[G Circumference Change Description]                 ,
S.[G Number of Multiple Engravings Description]        ,
S.[G Cylinder Conditions Description]                  ,
S.[G Repro Rework Description]                         ,
S.[G Repro Team Description]                           ,
S.[G ROTO Technology Description]                      ,
S.[G Repro Composition Description]                    ,
S.[G Brandowner Description]                           ,
S.[G Cylinder Type Description]                        ,
S.[G Axial Width Description]                          ,
S.[G Business Unit Description]                        ,
S.[G Position Number Description]                      ,
S.[Batch Class Description]                            ,
S.[G Original Diameter Description]                    ,
S.[G Original Wall Thickness Description]              ,
S.[G Original Copper Layer Description]                ,
S.[G Original Steelbase Order Description]             ,
S.[G Original Engraving Surface Description]           ,
S.[G Original Cylinder Surface Description]            ,
S.[G Original Threads Description]                     ,
S.[G Printing Circumference Description]               ,
S.[G Engraving Type Description]                       ,
S.[ZLP Customer Specific Field Label 01]               ,
S.[ZLP Customer Specific Field Label 02]               ,
S.[ZLP Customer Specific Field Label 03]               ,
S.[ZLP Customer Specific Field Label 04]               ,
S.[ZLP Customer Specific Field Label 05]               ,
S.[ZLP Customer Specific Field Label 06]               ,
S.[ZLP Customer Specific Field Label 07]               ,
S.[ZLP Customer Specific Field Label 08]               ,
S.[ZLP Customer Specific Field Label 09]               ,
S.[ZLP Customer Specific Field Label 10]               ,
S.[ZLP Customer Specific Field Label 11]               ,
S.[ZLP Customer Specific Field Label 12]               ,
S.[ZLP Customer Specific Field Label 13]               ,
S.[ZLP Customer Specific Field Label 14]               ,
S.[ZLP Customer Specific Field Label 15]               ,
S.[ZLP Customer Specific Field Label 16]               ,
S.[ZLP Customer Specific Field Label 17]               ,
S.[ZLP Customer Specific Field Label 18]               ,
S.[ZLP Customer Specific Field Label 19]               ,
S.[ZLP Customer Specific Field Label 20]               ,
S.[ZLP Customer Specific Field Label 01 Description]   ,
S.[ZLP Customer Specific Field Label 02 Description]   ,
S.[ZLP Customer Specific Field Label 03 Description]   ,
S.[ZLP Customer Specific Field Label 04 Description]   ,
S.[ZLP Customer Specific Field Label 05 Description]   ,
S.[ZLP Customer Specific Field Label 06 Description]   ,
S.[ZLP Customer Specific Field Label 07 Description]   ,
S.[ZLP Customer Specific Field Label 08 Description]   ,
S.[ZLP Customer Specific Field Label 09 Description]   ,
S.[ZLP Customer Specific Field Label 10 Description]   ,
S.[ZLP Customer Specific Field Label 11 Description]   ,
S.[ZLP Customer Specific Field Label 12 Description]   ,
S.[ZLP Customer Specific Field Label 13 Description]   ,
S.[ZLP Customer Specific Field Label 14 Description]   ,
S.[ZLP Customer Specific Field Label 15 Description]   ,
S.[ZLP Customer Specific Field Label 16 Description]   ,
S.[ZLP Customer Specific Field Label 17 Description]   ,
S.[ZLP Customer Specific Field Label 18 Description]   ,
S.[ZLP Customer Specific Field Label 19 Description]   ,
S.[ZLP Customer Specific Field Label 20 Description]   ,
S.[GT Screen Circumference]                            ,
S.[GT Screen Length]                                   ,
S.[G Plate Length]                                     ,
S.[G Plate Width]                                      ,
S.[G Emboss Depth]                                     ,
S.[GT C Nickel Plating]                                ,
S.[G Emboss Steps]                                     ,
S.[GT Screen Circumference Description]                ,
S.[GT Screen Length Description]                       ,
S.[G Plate Length Description]                         ,
S.[G Plate Width Description]                          ,
S.[G Emboss Depth Description]                         ,
S.[GT C Nickel Plating Description]                    ,
S.[GT Wall Thickness Description]                      ,
S.[G Emboss Steps Description]                         ,
S.[GT Wall Thickness]                                  ,
S.[G Engraving Methode]                                ,
S.[G Laser Type]                                       ,
S.[G Engraving Methode Description]                    ,
S.[G Laser Type Description]                           ,
S.[G Estimated Cylinder Conditions]                    ,
S.[G Estimated Circumference Change]                   ,
S.[G Emboss Method]                                    ,
S.[G Emboss Material]                                  ,
S.[GT Screen Type]                                     ,
S.[G Estimated Cylinder Conditions Description]        ,
S.[G Estimated Circumference Change Description]       ,
S.[G Emboss Method Description]                        ,
S.[G Emboss Material Description]                      ,
S.[GT Screen Type Description]                         ,
S.[ZLP ANZF VS]                                        ,
S.[ZLP ANZF VS Description]                            ,
S.[G Copper Hardness HV]                               ,
S.[G Copper Hardness HV Description]                   ,
S.[ZLP BB Color Profile]                               ,
S.[ZLP BB Color Profile Description]                   ,
S.[ZLP AG F Color 01]                                  ,
S.[ZLP AG F Color 02]                                  ,
S.[ZLP AG F Color 03]                                  ,
S.[ZLP AG F Color 04]                                  ,
S.[ZLP AG F Color 05]                                  ,
S.[ZLP AG F Color 06]                                  ,
S.[ZLP AG F Color 07]                                  ,
S.[ZLP AG F Color 08]                                  ,
S.[ZLP AG F Color 09]                                  ,
S.[ZLP AG F Color 10]                                  ,
S.[ZLP AG F Color 11]                                  ,
S.[ZLP AG F Color 12]                                  ,
S.[ZLP AG F Color 13]                                  ,
S.[ZLP AG F Color 14]                                  ,
S.[ZLP AG F Color 15]                                  ,
S.[ZLP AG F Color 16]                                  ,
S.[ZLP AG F Color 17]                                  ,
S.[ZLP AG F Color 18]                                  ,
S.[ZLP AG F Color 19]                                  ,
S.[ZLP AG F Color 20]                                  ,
S.[ZLP AG C Customer Color 01]                         ,
S.[ZLP AG C Customer Color 02]                         ,
S.[ZLP AG C Customer Color 03]                         ,
S.[ZLP AG C Customer Color 04]                         ,
S.[ZLP AG C Customer Color 05]                         ,
S.[ZLP AG C Customer Color 06]                         ,
S.[ZLP AG C Customer Color 07]                         ,
S.[ZLP AG C Customer Color 08]                         ,
S.[ZLP AG C Customer Color 09]                         ,
S.[ZLP AG C Customer Color 10]                         ,
S.[ZLP AG C Customer Color 11]                         ,
S.[ZLP AG C Customer Color 12]                         ,
S.[ZLP AG C Customer Color 13]                         ,
S.[ZLP AG C Customer Color 14]                         ,
S.[ZLP AG C Customer Color 15]                         ,
S.[ZLP AG C Customer Color 16]                         ,
S.[ZLP AG C Customer Color 17]                         ,
S.[ZLP AG C Customer Color 18]                         ,
S.[ZLP AG C Customer Color 19]                         ,
S.[ZLP AG C Customer Color 20]                         ,
S.[ZLP AG F Color 01 Description]                      ,
S.[ZLP AG F Color 02 Description]                      ,
S.[ZLP AG F Color 03 Description]                      ,
S.[ZLP AG F Color 04 Description]                      ,
S.[ZLP AG F Color 05 Description]                      ,
S.[ZLP AG F Color 06 Description]                      ,
S.[ZLP AG F Color 07 Description]                      ,
S.[ZLP AG F Color 08 Description]                      ,
S.[ZLP AG F Color 09 Description]                      ,
S.[ZLP AG F Color 10 Description]                      ,
S.[ZLP AG F Color 11 Description]                      ,
S.[ZLP AG F Color 12 Description]                      ,
S.[ZLP AG F Color 13 Description]                      ,
S.[ZLP AG F Color 14 Description]                      ,
S.[ZLP AG F Color 15 Description]                      ,
S.[ZLP AG F Color 16 Description]                      ,
S.[ZLP AG F Color 17 Description]                      ,
S.[ZLP AG F Color 18 Description]                      ,
S.[ZLP AG F Color 19 Description]                      ,
S.[ZLP AG F Color 20 Description]                      ,
S.[ZLP AG C Customer Color 01 Description]             ,
S.[ZLP AG C Customer Color 02 Description]             ,
S.[ZLP AG C Customer Color 03 Description]             ,
S.[ZLP AG C Customer Color 04 Description]             ,
S.[ZLP AG C Customer Color 05 Description]             ,
S.[ZLP AG C Customer Color 06 Description]             ,
S.[ZLP AG C Customer Color 07 Description]             ,
S.[ZLP AG C Customer Color 08 Description]             ,
S.[ZLP AG C Customer Color 09 Description]             ,
S.[ZLP AG C Customer Color 10 Description]             ,
S.[ZLP AG C Customer Color 11 Description]             ,
S.[ZLP AG C Customer Color 12 Description]             ,
S.[ZLP AG C Customer Color 13 Description]             ,
S.[ZLP AG C Customer Color 14 Description]             ,
S.[ZLP AG C Customer Color 15 Description]             ,
S.[ZLP AG C Customer Color 16 Description]             ,
S.[ZLP AG C Customer Color 17 Description]             ,
S.[ZLP AG C Customer Color 18 Description]             ,
S.[ZLP AG C Customer Color 19 Description]             ,
S.[ZLP AG C Customer Color 20 Description]             ,
S.[ZLP AG F Line Screen 1]                             ,
S.[ZLP AG F Line Screen 2]                             ,
S.[ZLP AG F Line Screen 3]                             ,
S.[ZLP AG F Line Screen 4]                             ,
S.[ZLP AG F Line Screen 5]                             ,
S.[ZLP AG F Line Screen 6]                             ,
S.[ZLP AG F Line Screen 7]                             ,
S.[ZLP AG F Line Screen 8]                             ,
S.[ZLP AG F Line Screen 9]                             ,
S.[ZLP AG F Line Screen 10]                            ,
S.[ZLP AG F Line Screen 11]                            ,
S.[ZLP AG F Line Screen 12]                            ,
S.[ZLP AG F Line Screen 13]                            ,
S.[ZLP AG F Line Screen 14]                            ,
S.[ZLP AG F Line Screen 15]                            ,
S.[ZLP AG F Line Screen 16]                            ,
S.[ZLP AG F Line Screen 17]                            ,
S.[ZLP AG F Line Screen 18]                            ,
S.[ZLP AG F Line Screen 19]                            ,
S.[ZLP AG F Line Screen 20]                            ,
S.[ZLP AG F Line Screen 1 Description]                 ,
S.[ZLP AG F Line Screen 2 Description]                 ,
S.[ZLP AG F Line Screen 3 Description]                 ,
S.[ZLP AG F Line Screen 4 Description]                 ,
S.[ZLP AG F Line Screen 5 Description]                 ,
S.[ZLP AG F Line Screen 6 Description]                 ,
S.[ZLP AG F Line Screen 7 Description]                 ,
S.[ZLP AG F Line Screen 8 Description]                 ,
S.[ZLP AG F Line Screen 9 Description]                 ,
S.[ZLP AG F Line Screen 10 Description]                ,
S.[ZLP AG F Line Screen 11 Description]                ,
S.[ZLP AG F Line Screen 12 Description]                ,
S.[ZLP AG F Line Screen 13 Description]                ,
S.[ZLP AG F Line Screen 14 Description]                ,
S.[ZLP AG F Line Screen 15 Description]                ,
S.[ZLP AG F Line Screen 16 Description]                ,
S.[ZLP AG F Line Screen 17 Description]                ,
S.[ZLP AG F Line Screen 18 Description]                ,
S.[ZLP AG F Line Screen 19 Description]                ,
S.[ZLP AG F Line Screen 20 Description]                ,
S.[ZLP Order Type]	                                  ,
S.[ZLP Order Type Description]                        ,
CONCAT(S.[SALES_ORDER_ID],'-',S.[SALES_ORDER_ITM_ID])

FROM [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_PRDVCON_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[EDW_V_D_SAL_PRDVCON_CUR_D] T
        ON T.[PRDT_VARIANT_CONFIG_KEY] = S.[PRDT_VARIANT_CONFIG_KEY]
    WHERE T.[PRDT_VARIANT_CONFIG_KEY] IS NULL;

END