CREATE     PROCEDURE [Propelis].[Proc_PARENT_CUST]
AS
BEGIN
    -------------------------------------------------------------------
    -- Step 1: Update existing records
    -------------------------------------------------------------------
    UPDATE T
    SET
        T.[Parent Customer ID]                        = S.[CUST_ID],
        T.[Parent Customer Legacy ID]                 = S.[LGCY_CUST_ID],
        T.[Parent Customer Name]                      = S.[CUST_NAME],
        T.[Parent Cust Line 2 Description]            = S.[CUST_LINE_2_DESC],
        T.[Parent Cust Country Code]                  = S.[CNTRY_CD],
        T.[Parent Cust Plant ID]                      = S.[PLNT_ID],
        T.[Parent Cust Segment ID]                    = S.[SEG_ID],
        T.[Parent Cust Industry]                      = S.[INDUS],
        T.[Parent Cust Vendor ID]                     = S.[VNDR_ID],
        T.[Parent Cust Group Code]                    = S.[CUST_GROUP_CD],
        T.[Parent Cust Account Group Code]            = S.[CUST_ACCT_GROUP_CD],
        T.[Parent Cust Title]                         = S.[TITLE],
        T.[Parent Cust Search Term]                   = S.[SEARCH_TERM],
        T.[Parent Cust Street]                        = S.[STR],
        T.[Parent Cust City]                          = S.[CITY_NAME],
        T.[Parent Cust Zip Code]                      = S.[ZIP_CD],
        T.[Parent Cust State Code]                    = S.[ST_CD],
        T.[Parent Cust Region Code]                   = S.[REGN_CD],
        T.[Parent Cust Telephone Number 1]            = S.[TEL_NUM_1_CD],
        T.[Parent Cust Telephone Number 2]            = S.[TEL_NUM_2_CD],
        T.[Parent Cust Fax Number Code]               = S.[FAX_NUM_CD],
        T.[Parent Cust Tax Number 1 Code]             = S.[TAX_NUM_1_CD],
        T.[Parent Cust Tax Number 2 Code]             = S.[TAX_NUM_2_CD],
        T.[Parent Cust VAT Number Code]               = S.[VAT_NUM_CD],
        T.[Parent Cust Credit Limit]                  = S.[CREDIT_LMT],
        T.[Parent Cust Bonus Rate]                    = S.[BONUS_RT],
        T.[Parent Cust Express Station]               = S.[EXPRESS_STATION],
        T.[Parent Cust Transportation Zone]           = S.[TRANSTN_ZONE],
        T.[Parent Cust Printer Location Characteristics] = S.[PRINTER_LOC_CHARS],
        T.[Parent Cust Printer Region Characteristics]  = S.[PRINTER_REGN_CHARS],
        T.[Parent Cust Printer Site Characteristics]    = S.[PRINTER_SITE_CHARS],
        T.[Parent Cust Created Date]                  = S.[CREATED_DATE],
        T.[Parent Cust Created User ID]               = S.[CREATED_USR_ID],
        T.[Parent Cust Updated Date]                  = S.[UPDTD_DATE],
        T.[Parent Cust Updated User ID]               = S.[UPDTD_USR_ID],
        T.[Parent Cust Payment Terms Code]            = S.[PYMT_TRMS_CD],
        T.[Parent Cust Sales Distribution]            = S.[SALES_DISTR],
        T.[Parent Cust Order Block For Sales Area]    = S.[ORDER_BLK_FOR_SALES_AREA],
        T.[Parent Cust Delivery Block For Sales Area] = S.[DLVRY_BLK_FOR_SALES_AREA],
        T.[ETL_SRC_SYS_CD]                            = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE]                    = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE]                      = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND]                          = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS]                            = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS]                              = S.[ETL_UPDTD_TS],
        T.[Parent Cust Corporate Group]               = S.[CORPORATE_GROUP],
        T.[Parent Cust Customer Classification]       = S.[CUST_CLSFTN],
        T.[Parent Cust Classification Description]    = S.[CUST_CLSFTN_DESC],
        T.[Parent Cust Printer Location]              = S.[PRINTER_LOC],
        T.[Parent Cust Printer Site]                  = S.[PRINTER_SITE],
        T.[Parent Cust Printer Region]                = S.[PRINTER_REGN],
        T.[Parent Cust Specific Field Label 01]       = S.[CUST_SPECIFIC_FLD_LBL_01],
        T.[Parent Cust Specific Field Label 02]       = S.[CUST_SPECIFIC_FLD_LBL_02],
        T.[Parent Cust Specific Field Label 03]       = S.[CUST_SPECIFIC_FLD_LBL_03],
        T.[Parent Cust Specific Field Label 04]       = S.[CUST_SPECIFIC_FLD_LBL_04],
        T.[Parent Cust Specific Field Label 05]       = S.[CUST_SPECIFIC_FLD_LBL_05],
        T.[Parent Cust Specific Field Label 06]       = S.[CUST_SPECIFIC_FLD_LBL_06],
        T.[Parent Cust Specific Field Label 07]       = S.[CUST_SPECIFIC_FLD_LBL_07],
        T.[Parent Cust Specific Field Label 08]       = S.[CUST_SPECIFIC_FLD_LBL_08],
        T.[Parent Cust Specific Field Label 09]       = S.[CUST_SPECIFIC_FLD_LBL_09],
        T.[Parent Cust Specific Field Label 10]       = S.[CUST_SPECIFIC_FLD_LBL_10],
        T.[Parent Cust Specific Field Label 11]       = S.[CUST_SPECIFIC_FLD_LBL_11],
        T.[Parent Cust Specific Field Label 12]       = S.[CUST_SPECIFIC_FLD_LBL_12],
        T.[Parent Cust Specific Field Label 13]       = S.[CUST_SPECIFIC_FLD_LBL_13],
        T.[Parent Cust Specific Field Label 14]       = S.[CUST_SPECIFIC_FLD_LBL_14],
        T.[Parent Cust Specific Field Label 15]       = S.[CUST_SPECIFIC_FLD_LBL_15],
        T.[Parent Cust Specific Field Label 16]       = S.[CUST_SPECIFIC_FLD_LBL_16],
        T.[Parent Cust Specific Field Label 17]       = S.[CUST_SPECIFIC_FLD_LBL_17],
        T.[Parent Cust Specific Field Label 18]       = S.[CUST_SPECIFIC_FLD_LBL_18],
        T.[Parent Cust Specific Field Label 19]       = S.[CUST_SPECIFIC_FLD_LBL_19],
        T.[Parent Cust Specific Field Label 20]       = S.[CUST_SPECIFIC_FLD_LBL_20],
        T.[Parent Cust Condition Group 1]             = S.[CUST_COND_GROUP_1],
        T.[Parent Cust Industry Code 1]               = S.[INDUS_CD_1],
        T.[Parent Cust Industry Code 2]               = S.[INDUS_CD_2],
        T.[Parent Cust Industry Description]          = S.[INDUS_DESC],
        T.[Parent Cust Industry Code 1 Description]   = S.[INDUS_CD_1_DESC],
        T.[Parent Cust Industry Code 2 Description]   = S.[INDUS_CD_2_DESC],
        T.[Parent Cust Assignment to Hierarchy]       = S.[ASSIGN_TO_HIERCHY],
        T.[Parent Cust Account Group Description]     = S.[CUST_ACCT_GROUP_DESC],
        T.[Parent Cust Region Description]            = S.[REGN_DESC],
        T.[Parent Cust Country Description]           = S.[CNTRY_DESC],
        T.[Parent Cust Transportation Zone Description] = S.[TRANSTN_ZONE_DESC],
        T.[Parent Cust Plant Description]             = S.[PLNT_DESC],
        T.[Parent Cust Condition Group Description]   = S.[CUST_COND_GROUP_DESC],
        T.[Parent Cust Cental Billing Block]          = S.[CENTRAL_BILLING_BLK],
        T.[Parent Cust Cental Billing Block Description] = S.[CENTRAL_BILLING_BLK_DESC],
        T.[Parent Cust Central Delivery Block]        = S.[CENTRAL_DLVRY_BLK],
        T.[Parent Cust Central Delivery Block Description] = S.[CENTRAL_DLVRY_BLK_DESC],
        T.[Parent Cust Deletion Indicator]            = S.[DELETION_IND],
        T.[CENTRAL_PSTNG_BLK]                         = S.[CENTRAL_PSTNG_BLK],
        T.[Parent Cust Tax Jurisdiction]              = S.[TAX_JRSDCTN],
        T.[Parent Cust Central Sales Block]           = S.[CENTRAL_SALES_BLK],
        T.[Parent Cust Central Deletion Indicator]    = S.[CENTRAL_DELETION_IND],
        T.[Parent Cust Language Key]                  = S.[LANG_KEY],
        T.[Parent Cust Trading Partner]               = S.[TRADING_PRTNR],
        T.[Parent Cust Trading Partner Description]   = S.[TRADING_PRTNR_DESC],
        T.[Parent Cust Annual Sales]                  = S.[ANNUAL_SALES],
        T.[Parent Cust Annual Sales Year]             = S.[ANNUAL_SALES_YR],
        T.[Parent Cust Sales Currency]                = S.[SALES_CRNCY],
        T.[Parent Cust Sales Currency Description]    = S.[SALES_CRNCY_DESC],
        T.[Parent Cust One Time Account Group]        = S.[ONE_TM_CUST_ACCT_GROUP],
        T.[Parent Cust One Time Account Group Description] = S.[ONE_TM_CUST_ACCT_GROUP_DESC],
        T.[Parent Cust One Time Customer Indicator]   = S.[ONE_TM_CUST_IND],
        T.[Parent Cust Industry Type]                 = S.[INDUS_TYP],
        T.[Parent Cust Business Type]                 = S.[BIZ_TYP],
        T.[Parent Cust DUNS Number]                   = S.[DUNS_NUM],
        T.[Parent Cust DUNS Plus 4]                   = S.[DUNS_PLUS_4],
        T.[Parent Cust City Coordinates]              = S.[CITY_COORDINATES],
        T.[Parent Cust Tax Number 4 Code]             = S.[TAX_NUM_4_CD],
        T.[Parent Cust Attribute 3]                   = S.[ATTRIB_3],
        T.[Parent Cust Attribute 3 Description]       = S.[ATTRIB_3_DESC],
        T.[Parent Cust E Mail Address]                = S.[E_MAIL_ADDR],
        T.[Parent Cust Mobile Number]                 = S.[MOBILE_NUM],
        T.[Parent Cust Search Term 2]                 = S.[SEARCH_TERM_2],
        T.[Parent Cust Street 2]                      = S.[STR_2],
        T.[Parent Cust Street 3]                      = S.[STR_3],
        T.[Parent Cust Street 4]                      = S.[STR_4],
        T.[Parent Cust Street 5]                      = S.[STR_5],
        T.[Parent Cust PO Box]                        = S.[PO_BOX],
        T.[Parent Cust PO Box Postal Code]            = S.[PO_BOX_POSTAL_CD],
        T.[Parent Cust PO Box City]                   = S.[PO_BOX_CITY],
        T.[Parent Cust Region For PO Box]             = S.[REGN_FOR_PO_BOX],
        T.[Parent Cust PO Box Country]                = S.[PO_BOX_CNTRY],
        T.[Parent Cust Transport Zone]                = S.[TRNSPRT_ZONE],
        T.[Parent Cust Tax Number 3 Code]             = S.[TAX_NUM_3],
        T.[Parent Cust Tax Number 5 Code]             = S.[TAX_NUM_5],
        T.[Parent Cust Industry Code 3]               = S.[INDUS_CD_3],
        T.[Parent Cust Industry Code 3 Description]   = S.[INDUS_CD_3_DESC],
        T.[Parent Cust Industry Code 4]               = S.[INDUS_CD_4],
        T.[Parent Cust Industry Code 4 Description]   = S.[INDUS_CD_4_DESC],
        T.[Parent Cust Industry Code 5]               = S.[INDUS_CD_5],
        T.[Parent Cust Industry Code 5 Description]   = S.[INDUS_CD_5_DESC],
        T.[Parent Cust Central Order Block For Customer] = S.[CENTRAL_ORDER_BLK_FOR_CUST],
        T.[Parent Cust Payment Block]                 = S.[PYMT_BLK]
    FROM [GLOBAL_EDW].[Propelis].[PARENT_CUST] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CUSTOMR_CUR_D] S
        ON T.[CUST_KEY] = S.[CUST_KEY];

    -------------------------------------------------------------------
    -- Step 2: Insert new records
    -------------------------------------------------------------------
    -------------------------------------------------------------------
-- Step 2: Insert new records
-------------------------------------------------------------------
INSERT INTO [GLOBAL_EDW].[Propelis].[PARENT_CUST]
(
    [CUST_KEY],
    [Parent Customer ID],
    [Parent Customer Legacy ID],
    [Parent Customer Name],
    [Parent Cust Line 2 Description],
    [Parent Cust Country Code],
    [Parent Cust Plant ID],
    [Parent Cust Segment ID],
    [Parent Cust Industry],
    [Parent Cust Vendor ID],
    [Parent Cust Group Code],
    [Parent Cust Account Group Code],
    [Parent Cust Title],
    [Parent Cust Search Term],
    [Parent Cust Street],
    [Parent Cust City],
    [Parent Cust Zip Code],
    [Parent Cust State Code],
    [Parent Cust Region Code],
    [Parent Cust Telephone Number 1],
    [Parent Cust Telephone Number 2],
    [Parent Cust Fax Number Code],
    [Parent Cust Tax Number 1 Code],
    [Parent Cust Tax Number 2 Code],
    [Parent Cust VAT Number Code],
    [Parent Cust Credit Limit],
    [Parent Cust Bonus Rate],
    [Parent Cust Express Station],
    [Parent Cust Transportation Zone],
    [Parent Cust Printer Location Characteristics],
    [Parent Cust Printer Region Characteristics],
    [Parent Cust Printer Site Characteristics],
    [Parent Cust Created Date],
    [Parent Cust Created User ID],
    [Parent Cust Updated Date],
    [Parent Cust Updated User ID],
    [Parent Cust Payment Terms Code],
    [Parent Cust Sales Distribution],
    [Parent Cust Order Block For Sales Area],
    [Parent Cust Delivery Block For Sales Area],
    [ETL_SRC_SYS_CD],
    [ETL_EFFECTV_BEGIN_DATE],
    [ETL_EFFECTV_END_DATE],
    [ETL_CURR_RCD_IND],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [Parent Cust Corporate Group],
    [Parent Cust Customer Classification],
    [Parent Cust Classification Description],
    [Parent Cust Printer Location],
    [Parent Cust Printer Site],
    [Parent Cust Printer Region],
    [Parent Cust Specific Field Label 01],
    [Parent Cust Specific Field Label 02],
    [Parent Cust Specific Field Label 03],
    [Parent Cust Specific Field Label 04],
    [Parent Cust Specific Field Label 05],
    [Parent Cust Specific Field Label 06],
    [Parent Cust Specific Field Label 07],
    [Parent Cust Specific Field Label 08],
    [Parent Cust Specific Field Label 09],
    [Parent Cust Specific Field Label 10],
    [Parent Cust Specific Field Label 11],
    [Parent Cust Specific Field Label 12],
    [Parent Cust Specific Field Label 13],
    [Parent Cust Specific Field Label 14],
    [Parent Cust Specific Field Label 15],
    [Parent Cust Specific Field Label 16],
    [Parent Cust Specific Field Label 17],
    [Parent Cust Specific Field Label 18],
    [Parent Cust Specific Field Label 19],
    [Parent Cust Specific Field Label 20],
    [Parent Cust Condition Group 1],
    [Parent Cust Industry Code 1],
    [Parent Cust Industry Code 2],
    [Parent Cust Industry Description],
    [Parent Cust Industry Code 1 Description],
    [Parent Cust Industry Code 2 Description],
    [Parent Cust Assignment to Hierarchy],
    [Parent Cust Account Group Description],
    [Parent Cust Region Description],
    [Parent Cust Country Description],
    [Parent Cust Transportation Zone Description],
    [Parent Cust Plant Description],
    [Parent Cust Condition Group Description],
    [Parent Cust Cental Billing Block],
    [Parent Cust Cental Billing Block Description],
    [Parent Cust Central Delivery Block],
    [Parent Cust Central Delivery Block Description],
    [Parent Cust Deletion Indicator],
    [CENTRAL_PSTNG_BLK],
    [Parent Cust Tax Jurisdiction],
    [Parent Cust Central Sales Block],
    [Parent Cust Central Deletion Indicator],
    [Parent Cust Language Key],
    [Parent Cust Trading Partner],
    [Parent Cust Trading Partner Description],
    [Parent Cust Annual Sales],
    [Parent Cust Annual Sales Year],
    [Parent Cust Sales Currency],
    [Parent Cust Sales Currency Description],
    [Parent Cust One Time Account Group],
    [Parent Cust One Time Account Group Description],
    [Parent Cust One Time Customer Indicator],
    [Parent Cust Industry Type],
    [Parent Cust Business Type],
    [Parent Cust DUNS Number],
    [Parent Cust DUNS Plus 4],
    [Parent Cust City Coordinates],
    [Parent Cust Tax Number 4 Code],
    [Parent Cust Attribute 3],
    [Parent Cust Attribute 3 Description],
    [Parent Cust E Mail Address],
    [Parent Cust Mobile Number],
    [Parent Cust Search Term 2],
    [Parent Cust Street 2],
    [Parent Cust Street 3],
    [Parent Cust Street 4],
    [Parent Cust Street 5],
    [Parent Cust PO Box],
    [Parent Cust PO Box Postal Code],
    [Parent Cust PO Box City],
    [Parent Cust Region For PO Box],
    [Parent Cust PO Box Country],
    [Parent Cust Transport Zone],
    [Parent Cust Tax Number 3 Code],
    [Parent Cust Tax Number 5 Code],
    [Parent Cust Industry Code 3],
    [Parent Cust Industry Code 3 Description],
    [Parent Cust Industry Code 4],
    [Parent Cust Industry Code 4 Description],
    [Parent Cust Industry Code 5],
    [Parent Cust Industry Code 5 Description],
    [Parent Cust Central Order Block For Customer],
    [Parent Cust Payment Block]
)
SELECT
    S.[CUST_KEY],
    S.[CUST_ID],
    S.[LGCY_CUST_ID],
    S.[CUST_NAME],
    S.[CUST_LINE_2_DESC],
    S.[CNTRY_CD],
    S.[PLNT_ID],
    S.[SEG_ID],
    S.[INDUS],
    S.[VNDR_ID],
    S.[CUST_GROUP_CD],
    S.[CUST_ACCT_GROUP_CD],
    S.[TITLE],
    S.[SEARCH_TERM],
    S.[STR],
    S.[CITY_NAME],
    S.[ZIP_CD],
    S.[ST_CD],
    S.[REGN_CD],
    S.[TEL_NUM_1_CD],
    S.[TEL_NUM_2_CD],
    S.[FAX_NUM_CD],
    S.[TAX_NUM_1_CD],
    S.[TAX_NUM_2_CD],
    S.[VAT_NUM_CD],
    S.[CREDIT_LMT],
    S.[BONUS_RT],
    S.[EXPRESS_STATION],
    S.[TRANSTN_ZONE],
    S.[PRINTER_LOC_CHARS],
    S.[PRINTER_REGN_CHARS],
    S.[PRINTER_SITE_CHARS],
    S.[CREATED_DATE],
    S.[CREATED_USR_ID],
    S.[UPDTD_DATE],
    S.[UPDTD_USR_ID],
    S.[PYMT_TRMS_CD],
    S.[SALES_DISTR],
    S.[ORDER_BLK_FOR_SALES_AREA],
    S.[DLVRY_BLK_FOR_SALES_AREA],
    S.[ETL_SRC_SYS_CD],
    S.[ETL_EFFECTV_BEGIN_DATE],
    S.[ETL_EFFECTV_END_DATE],
    S.[ETL_CURR_RCD_IND],
    S.[ETL_CREATED_TS],
    S.[ETL_UPDTD_TS],
    S.[CORPORATE_GROUP],
    S.[CUST_CLSFTN],
    S.[CUST_CLSFTN_DESC],
    S.[PRINTER_LOC],
    S.[PRINTER_SITE],
    S.[PRINTER_REGN],
    S.[CUST_SPECIFIC_FLD_LBL_01],
    S.[CUST_SPECIFIC_FLD_LBL_02],
    S.[CUST_SPECIFIC_FLD_LBL_03],
    S.[CUST_SPECIFIC_FLD_LBL_04],
    S.[CUST_SPECIFIC_FLD_LBL_05],
    S.[CUST_SPECIFIC_FLD_LBL_06],
    S.[CUST_SPECIFIC_FLD_LBL_07],
    S.[CUST_SPECIFIC_FLD_LBL_08],
    S.[CUST_SPECIFIC_FLD_LBL_09],
    S.[CUST_SPECIFIC_FLD_LBL_10],
    S.[CUST_SPECIFIC_FLD_LBL_11],
    S.[CUST_SPECIFIC_FLD_LBL_12],
    S.[CUST_SPECIFIC_FLD_LBL_13],
    S.[CUST_SPECIFIC_FLD_LBL_14],
    S.[CUST_SPECIFIC_FLD_LBL_15],
    S.[CUST_SPECIFIC_FLD_LBL_16],
    S.[CUST_SPECIFIC_FLD_LBL_17],
    S.[CUST_SPECIFIC_FLD_LBL_18],
    S.[CUST_SPECIFIC_FLD_LBL_19],
    S.[CUST_SPECIFIC_FLD_LBL_20],
    S.[CUST_COND_GROUP_1],
    S.[INDUS_CD_1],
    S.[INDUS_CD_2],
    S.[INDUS_DESC],
    S.[INDUS_CD_1_DESC],
    S.[INDUS_CD_2_DESC],
    S.[ASSIGN_TO_HIERCHY],
    S.[CUST_ACCT_GROUP_DESC],
    S.[REGN_DESC],
    S.[CNTRY_DESC],
    S.[TRANSTN_ZONE_DESC],
    S.[PLNT_DESC],
    S.[CUST_COND_GROUP_DESC],
    S.[CENTRAL_BILLING_BLK],
    S.[CENTRAL_BILLING_BLK_DESC],
    S.[CENTRAL_DLVRY_BLK],
    S.[CENTRAL_DLVRY_BLK_DESC],
    S.[DELETION_IND],
    S.[CENTRAL_PSTNG_BLK],
    S.[TAX_JRSDCTN],
    S.[CENTRAL_SALES_BLK],
    S.[CENTRAL_DELETION_IND],
    S.[LANG_KEY],
    S.[TRADING_PRTNR],
    S.[TRADING_PRTNR_DESC],
    S.[ANNUAL_SALES],
    S.[ANNUAL_SALES_YR],
    S.[SALES_CRNCY],
    S.[SALES_CRNCY_DESC],
    S.[ONE_TM_CUST_ACCT_GROUP],
    S.[ONE_TM_CUST_ACCT_GROUP_DESC],
    S.[ONE_TM_CUST_IND],
    S.[INDUS_TYP],
    S.[BIZ_TYP],
    S.[DUNS_NUM],
    S.[DUNS_PLUS_4],
    S.[CITY_COORDINATES],
    S.[TAX_NUM_4_CD],
    S.[ATTRIB_3],
    S.[ATTRIB_3_DESC],
    S.[E_MAIL_ADDR],
    S.[MOBILE_NUM],
    S.[SEARCH_TERM_2],
    S.[STR_2],
    S.[STR_3],
    S.[STR_4],
    S.[STR_5],
    S.[PO_BOX],
    S.[PO_BOX_POSTAL_CD],
    S.[PO_BOX_CITY],
    S.[REGN_FOR_PO_BOX],
    S.[PO_BOX_CNTRY],
    S.[TRNSPRT_ZONE],
    S.[TAX_NUM_3],
    S.[TAX_NUM_5],
    S.[INDUS_CD_3],
    S.[INDUS_CD_3_DESC],
    S.[INDUS_CD_4],
    S.[INDUS_CD_4_DESC],
    S.[INDUS_CD_5],
    S.[INDUS_CD_5_DESC],
    S.[CENTRAL_ORDER_BLK_FOR_CUST],
    S.[PYMT_BLK]
FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_CUSTOMR_CUR_D] S
LEFT JOIN [GLOBAL_EDW].[Propelis].[PARENT_CUST] T
    ON T.[CUST_KEY] = S.[CUST_KEY]
WHERE T.[CUST_KEY] IS NULL;
END