CREATE  PROCEDURE [Propelis].[Proc_EDW_T_FACT_PRD_FFUDATA_CUR_D]
AS
BEGIN
 
    -- Step 1: Clear existing data from the target table
    TRUNCATE TABLE [GLOBAL_EDW].[Propelis].[EDW_T_FACT_PRD_FFUDATA_CUR_D];
	-- Step 2: Insert refreshed data from mirror table with joins

INSERT INTO [GLOBAL_EDW].[Propelis].[EDW_T_FACT_PRD_FFUDATA_CUR_D]
(
	[FFU Job ID],
	[FFU Account Indicator],
	[FFU Author],
	[FFU Auto Status],
	[FFU Brand],
	[FFU Category],
	[FFU Issue Category],
	[FFU Issue Sub Category],
	[FFU Query Type],
	[FFU Sales Employee Name],
	[FFU Site],
	[FFU SKU Description],
	[FFU Sold To Party Name],
	[FFU Status],
	[SERVC_ORDER_KEY],
	[SALES_ORDER_KEY],
	[SOLD_TO_PARTY_KEY],
	[CUST_BRAND_HIERCHY_KEY],
	[SKU_MATRL_KEY],
	[SITE_KEY],
	[SALES_EMPL_KEY],
	[ETL_SRC_SYS_CD],
	[ETL_CREATED_TS],
	[ETL_UPDTD_TS],
	[CREATE_DATE_KEY],
	[FFU Create Date Timestamp],
	[FFU Status Name],
	[FFU Additional Affected Service Orders],
	[FFU Issue Category 2],
	[FFU Issue Category 3],
	[FFU Issue Category 4],
	[FFU Issue Category 5],
	[FFU Issue Category 6],
	[FFU Issue Subcategory 2],
	[FFU Issue Subcategory 3],
	[FFU Issue Subcategory 4],
	[FFU Issue Subcategory 5],
	[FFU Issue Subcategory 6],
	[FFU CSR2],
	[FFU CSR],
	[FFU Variant],
	[FFU Proj Description],
	[FFU Project Name],
	[FFU Project Number],
	[FFU Last Status Change],
	[FFU Error Description],
	[FFU Resolution]
)

SELECT 
	FACT.[JOB_ID],
	FACT.[ACC_IND],
	FACT.[AUTHOR],
	FACT.[AUTO_STATUS],
	FACT.[BRAND],
	FACT.[CTGRY],
	FACT.[ISSUE_CTGRY],
	FACT.[ISSUE_SUBCATEGORY],
	FACT.[QUERY_TYP],
	FACT.[SALES_EMPL_NAME],
	FACT.[SITE],
	FACT.[SKU_DESC],
	FACT.[SOLD_TO_PARTY_NAME],
	FACT.[STATUS],
	FACT.[SERVC_ORDER_KEY],
	FACT.[SALES_ORDER_KEY],
	FACT.[SOLD_TO_PARTY_KEY],
	FACT.[CUST_BRAND_HIERCHY_KEY],
	FACT.[SKU_MATRL_KEY],
	FACT.[SITE_KEY],
	FACT.[SALES_EMPL_KEY],
	FACT.[ETL_SRC_SYS_CD],
	FACT.[ETL_CREATED_TS],
	FACT.[ETL_UPDTD_TS],
	FACT.[CREATE_DATE_KEY],
	FACT.[CREATE_DATE_TS],
	FACT.[STATUS_NAME],
	FACT.[ADDITIONAL_AFFECTED_SERVC_ORDER],
	FACT.[ISSUE_CTGRY_2],
	FACT.[ISSUE_CTGRY_3],
	FACT.[ISSUE_CTGRY_4],
	FACT.[ISSUE_CTGRY_5],
	FACT.[ISSUE_CTGRY_6],
	FACT.[ISSUE_SUBCATEGORY_2],
	FACT.[ISSUE_SUBCATEGORY_3],
	FACT.[ISSUE_SUBCATEGORY_4],
	FACT.[ISSUE_SUBCATEGORY_5],
	FACT.[ISSUE_SUBCATEGORY_6],
	FACT.[CSR2],
	FACT.[CSR],
	FACT.[VARIANT],
	FACT.[PROJ_DESC],
	FACT.[PROJ_NAME],
	FACT.[PROJ_NUM],
	FACT.[LAST_STATUS_CHG],
	FACT.[ERR_DESC],
	FACT.[RESOLUTION]
	
FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_F_PRD_FFUDATA_CUR_D] AS FACT

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PERSONL_CUR_D] AS PERSONL
    ON FACT.SALES_EMPL_KEY = PERSONL.PERSONEL_KEY
	
LEFT JOIN [GLOBAL_EDW].[Propelis].[SOLD_TO_PARTY] AS SO_T_PRT
    ON FACT.SOLD_TO_PARTY_KEY = SO_T_PRT.CUST_KEY
	
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_PRD_SERVORD_CUR_D] AS SERVORD
    ON FACT.SERVC_ORDER_KEY = SERVORD.SERVC_ORDER_KEY
	
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_SALORDH_CUR_D] AS SAL_SALORDH
    ON FACT.SALES_ORDER_KEY = SAL_SALORDH.SALES_ORDER_KEY
	  
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_MATERIAL_CUR_D] AS MST_MATERIAL
    ON FACT.SKU_MATRL_KEY = MST_MATERIAL.MATRL_KEY
	
LEFT JOIN [GLOBAL_EDW].[Propelis].[SITE] AS ST
    ON FACT.SITE_KEY = ST.PLNT_KEY
	
LEFT JOIN [GLOBAL_EDW].[Propelis].[CREATE_DATE] AS CRE_DT
    ON FACT.CREATE_DATE_KEY = CRE_DT.DATE_KEY
	
LEFT JOIN [GLOBAL_EDW].[Propelis].[EDW_T_D_MST_CUSTBRD_CUR_D] AS MST_CUSTBRD
   ON FACT.CUST_BRAND_HIERCHY_KEY = MST_CUSTBRD.CUST_BRAND_HIERCHY_KEY;
   
END