CREATE   PROCEDURE [Propelis].[Proc_Investigation_Start_Date]
AS
BEGIN
    -- Step 1: Update existing records
    UPDATE T
    SET

            T.[Investigation Start Date] = S.[THE_DATE],
            T.[Investigation Start Fiscal Year] = S.[FISCAL_YR],
            T.[Investigation Start Fiscal Period Number] = S.[FISCAL_PER_NUM],
            T.[Investigation Start Fiscal Period Code] = S.[FISCAL_PER_CD],
            T.[Investigation Start Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
            T.[Investigation Start Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
            T.[Investigation Start Calendar Year] = S.[CLNDR_YR],
            T.[Investigation Start Calendar Month Number] = S.[CLNDR_MNTH_NUM],
            T.[Investigation Start Calendar Month Code] = S.[CLNDR_MNTH_CD],
            T.[Investigation Start Calendar Month Description] = S.[CLNDR_MNTH_DESC],
            T.[Investigation Start Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
            T.[Investigation Start Calendar Quarter Code] = S.[CLNDR_QTR_CD],
            T.[Investigation Start Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
            T.[Investigation Start Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
            T.[Investigation Start Calendar Day In Month] = S.[CLNDR_DAY_IN_MNTH],
            T.[Investigation Start Calendar Day In Year] = S.[CLNDR_DAY_IN_YR],
            T.[Investigation Start Calendar Week] = S.[CLNDR_WK],
            T.[Investigation Start Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
            T.[Investigation Start Calendar Days In Month] = S.[CLNDR_DAYS_IN_MNTH],
            T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
            T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
            T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
            T.[Investigation Start Current Day Flag] = S.[CURR_DAY_FLG],
            T.[Investigation Start Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
            T.[Investigation Start Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
            T.[Investigation Start Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
            T.[Investigation Start Current Month Flag] = S.[CURR_MNTH_FLG],
            T.[Investigation Start Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
            T.[Investigation Start Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
            T.[Investigation Start Current Quarter Flag] = S.[CURR_QTR_FLG],
            T.[Investigation Start Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
            T.[Investigation Start Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
            T.[Investigation Start Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
            T.[Investigation Start Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
            T.[Investigation Start Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
            T.[Investigation Start Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
            T.[Investigation Start Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
            T.[Investigation Start Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
            T.[Investigation Start Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
            T.[Investigation Start Current Fiscal Year Plus 1 Flag] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
            T.[Investigation Start Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
            T.[Investigation Start Is Weekday] = S.[IS_WEEKDAY],
            T.[Investigation Start Fiscal Week] = S.[FISCAL_WK],
            T.[Investigation Start Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
            T.[Investigation Start Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
            T.[Investigation Start Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
            T.[Investigation Start Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
            T.[Investigation Start Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
            T.[Investigation Start Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
            T.[Investigation Start Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
            T.[Investigation Start Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
            T.[Investigation Start Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
            T.[Investigation Start Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
            T.[Investigation Start Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[Investigation_Start_Date] T
   INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] S
    ON T.[DATE_KEY] = S.[DATE_KEY];

INSERT INTO [GLOBAL_EDW].[Propelis].[Investigation_Start_Date]
    (
            [DATE_KEY],
            [Investigation Start Date],
            [Investigation Start Fiscal Year],
            [Investigation Start Fiscal Period Number],
            [Investigation Start Fiscal Period Code],
            [Investigation Start Fiscal Quarter Number],
            [Investigation Start Fiscal Quarter Code],
            [Investigation Start Calendar Year],
            [Investigation Start Calendar Month Number],
            [Investigation Start Calendar Month Code],
            [Investigation Start Calendar Month Description],
            [Investigation Start Calendar Quarter Number],
            [Investigation Start Calendar Quarter Code],
            [Investigation Start Calendar Weekday Number],
            [Investigation Start Calendar Weekday Name],
            [Investigation Start Calendar Day In Month],
            [Investigation Start Calendar Day In Year],
            [Investigation Start Calendar Week],
            [Investigation Start Calendar Month In Quarter Number],
            [Investigation Start Calendar Days In Month],
            [ETL_SRC_SYS_CD],
            [ETL_CREATED_TS],
            [ETL_UPDTD_TS],
            [Investigation Start Current Day Flag],
            [Investigation Start Current Day Minus 1 Flag],
            [Investigation Start Current Calendar Week Flag],
            [Investigation Start Current Calendar Week Minus 1 Flag],
            [Investigation Start Current Month Flag],
            [Investigation Start Current Month Minus 1 Flag],
            [Investigation Start Current Month Minus 12 Flag],
            [Investigation Start Current Quarter Flag],
            [Investigation Start Current Quarter Minus 1 Flag],
            [Investigation Start Current Quarter Minus 4 Flag],
            [Investigation Start Current Calendar Year Flag],
            [Investigation Start Current Calendar Year Minus 1 Flag],
            [Investigation Start Current Calendar Year Minus 2 Flag],
            [Investigation Start Current Fiscal Year Flag],
            [Investigation Start Current Fiscal Year Minus 1 Flag],
            [Investigation Start Current Fiscal Year Minus 2 Flag],
            [Investigation Start Current Calendar Year Plus 1 Flag],
            [Investigation Start Current Fiscal Year Plus 1 Flag],
            [Investigation Start Day In Fiscal Year],
            [Investigation Start Is Weekday],
            [Investigation Start Fiscal Week],
            [Investigation Start Current Fiscal Week Flag],
            [Investigation Start Current Fiscal Week Minus 1 Flag],
            [Investigation Start Fiscal Weekday Number],
            [Investigation Start Fiscal Weekday Name],
            [Investigation Start Current Month Minus 2 Flag],
            [Investigation Start Current Fiscal Week Minus 2 Flag],
            [Investigation Start Current Fiscal Week Minus 6 Flag],
            [Investigation Start Current Fiscal Week Minus 3 Flag],
            [Investigation Start Current Fiscal Week Minus 4 Flag],
            [Investigation Start Current Fiscal Week Minus 5 Flag],
            [Investigation Start Current Fiscal Week Minus 7 Flag]
        )
        SELECT 
            S.[DATE_KEY],
            S.[THE_DATE],
            S.[FISCAL_YR],
            S.[FISCAL_PER_NUM],
            S.[FISCAL_PER_CD],
            S.[FISCAL_QTR_NUM],
            S.[FISCAL_QTR_CD],
            S.[CLNDR_YR],
            S.[CLNDR_MNTH_NUM],
            S.[CLNDR_MNTH_CD],
            S.[CLNDR_MNTH_DESC],
            S.[CLNDR_QTR_NUM],
            S.[CLNDR_QTR_CD],
            S.[CLNDR_WEEKDAY_NUM],
            S.[CLNDR_WEEKDAY_NAME],
            S.[CLNDR_DAY_IN_MNTH],
            S.[CLNDR_DAY_IN_YR],
            S.[CLNDR_WK],
            S.[CLNDR_MNTH_IN_QTR_NUM],
            S.[CLNDR_DAYS_IN_MNTH],
            S.[ETL_SRC_SYS_CD],
            S.[ETL_CREATED_TS],
            S.[ETL_UPDTD_TS],
            S.[CURR_DAY_FLG],
            S.[CURR_DAY_MINUS_1_FLG],
            S.[CURR_CLNDR_WK_FLG],
            S.[CURR_CLNDR_WK_MINUS_1_FLG],
            S.[CURR_MNTH_FLG],
            S.[CURR_MNTH_MINUS_1_FLG],
            S.[CURR_MNTH_MINUS_12_FLG],
            S.[CURR_QTR_FLG],
            S.[CURR_QTR_MINUS_1_FLG],
            S.[CURR_QTR_MINUS_4_FLG],
            S.[CURR_CLNDR_YR_FLG],
            S.[CURR_CLNDR_YR_MINUS_1_FLG],
            S.[CURR_CLNDR_YR_MINUS_2_FLG],
            S.[CURR_FISCAL_YR_FLG],
            S.[CURR_FISCAL_YR_MINUS_1_FLG],
            S.[CURR_FISCAL_YR_MINUS_2_FLG],
            S.[CURR_CLNDR_YR_PLUS_1_FLG],
            S.[CURR_FISCAL_YR_PLUS_1_FLG],
            S.[DAY_IN_FISCAL_YR],
            S.[IS_WEEKDAY],
            S.[FISCAL_WK],
            S.[CURR_FISCAL_WK_FLG],
            S.[CURR_FISCAL_WK_MINUS_1_FLG],
            S.[FISCAL_WEEKDAY_NUM],
            S.[FISCAL_WEEKDAY_NAME],
            S.[CURR_MNTH_MINUS_2_FLG],
            S.[CURR_FISCAL_WK_MINUS_2_FLG],
            S.[CURR_FISCAL_WK_MINUS_6_FLG],
            S.[CURR_FISCAL_WK_MINUS_3_FLG],
            S.[CURR_FISCAL_WK_MINUS_4_FLG],
            S.[CURR_FISCAL_WK_MINUS_5_FLG],
            S.[CURR_FISCAL_WK_MINUS_7_FLG]
FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[Investigation_Start_Date] AS T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;

END;