CREATE     PROCEDURE [Propelis].[Proc_FORWARDING_AGENT_VENDOR]
AS
BEGIN
    -- Step 1: Update existing records in target table from mirror
    UPDATE T
    SET
        T.[Forwarding Agent Vendor ID]                        = S.[VNDR_ID],
        T.[Forwarding Agent Vendor Name]                      = S.[VNDR_NAME],
        T.[Forwarding Agent Vendor Description]               = S.[VNDR_DESC],
        T.[Forwarding Agent Vendor Account Group]             = S.[VNDR_ACCT_GROUP],
        T.[Forwarding Agent Vendor Title]                     = S.[TITLE],
        T.[Forwarding Agent Vendor Search Term]               = S.[SEARCH_TERM],
        T.[Forwarding Agent Vendor Street]                    = S.[STR],
        T.[Forwarding Agent Vendor City Name]                 = S.[CITY_NAME],
        T.[Forwarding Agent Vendor Zip Code]                  = S.[ZIP_CD],
        T.[Forwarding Agent Vendor Country Code]              = S.[CNTRY_CD],
        T.[Forwarding Agent Vendor State]                     = S.[ST],
        T.[Forwarding Agent Vendor Telephone Number 1 Code]   = S.[TEL_NUM_1_CD],
        T.[Forwarding Agent Vendor Fax Number Code]           = S.[FAX_NUM_CD],
        T.[Forwarding Agent Vendor Tax Number 1 Code]         = S.[TAX_NUM_1_CD],
        T.[Forwarding Agent Vendor Tax Number 2 Code]         = S.[TAX_NUM_2_CD],
        T.[Forwarding Agent Vendor VAT Number Code]           = S.[VAT_NUM_CD],
        T.[Forwarding Agent Vendor Express Station]           = S.[EXPRESS_STATION],
        T.[Forwarding Agent Vendor Transportation Zone]       = S.[TRANSTN_ZONE],
        T.[Forwarding Agent Vendor Industry]                  = S.[INDUS],
        T.[Forwarding Agent Vendor Created Date]              = S.[CREATED_DATE],
        T.[ETL_SRC_SYS_CD]                                    = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE]                            = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE]                              = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND]                                  = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS]                                    = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS]                                      = S.[ETL_UPDTD_TS],
        T.[Forwarding Agent Vendor Address Number]            = S.[ADDR_NUM],
        T.[Forwarding Agent Vendor Account Group Description] = S.[VNDR_ACCT_GROUP_DESC],
        T.[Forwarding Agent Vendor Country Description]       = S.[CNTRY_DESC],
        T.[Forwarding Agent Vendor Region Description]        = S.[REGN_DESC],
        T.[Forwarding Agent Vendor Transportation Zone Description] = S.[TRANSTN_ZONE_DESC],
        T.[Forwarding Agent Vendor Industry Description]      = S.[INDUS_DESC],
        T.[Forwarding Agent Vendor Created By]                = S.[CREATED_BY],
        T.[Forwarding Agent Vendor Central Deletion Indicator] = S.[CENTRAL_DELETION_IND],
        T.[Forwarding Agent Vendor Central Posting Block]     = S.[CENTRAL_PSTNG_BLK],
        T.[Forwarding Agent Vendor Central Purchasing Block]  = S.[CENTRAL_PURNG_BLK],
        T.[Forwarding Agent Vendor Language Key]              = S.[LANG_KEY],
        T.[Forwarding Agent Vendor Customer ID]               = S.[CUST_ID],
        T.[Forwarding Agent Vendor One Time Account Indicator]= S.[ONE_TM_ACCT_IND],
        T.[Forwarding Agent Vendor One Time Account Reference Group] = S.[ONE_TM_ACCT_REF_ACCT__GROUP],
        T.[Forwarding Agent Vendor One Time Account Reference Group Desc] = S.[ONE_TM_ACC_REF_ACCT_GROUP_DESC],
        T.[Forwarding Agent Vendor Trading Partner]           = S.[TRADING_PRTNR],
        T.[Forwarding Agent Vendor Trading Partner Description]= S.[TRADING_PRTNR_DESC],
        T.[Forwarding Agent Vendor VAT Indicator]             = S.[VAT_IND],
        T.[Forwarding Agent Vendor Industry Type]             = S.[INDUS_TYP],
        T.[Forwarding Agent Vendor Business Type]             = S.[BIZ_TYP],
        T.[Forwarding Agent Vendor Payment Block]             = S.[PYMT_BLK],
        T.[Forwarding Agent Vendor Tax Jurisdiction]          = S.[TAX_JRSDCTN],
        T.[Forwarding Agent Vendor Tax Number 3 Code]        = S.[TAX_NUM_3_CD],
        T.[Forwarding Agent Vendor Tax Number Type]          = S.[TAX_NUM_TYP],
        T.[Forwarding Agent Vendor Tax Type]                 = S.[TAX_TYP],
        T.[Forwarding Agent Vendor Level 1]                  = S.[LVL_1],
        T.[Forwarding Agent Vendor Level 2]                  = S.[LVL_2],
        T.[Forwarding Agent Vendor Level 3]                  = S.[LVL_3],
        T.[Forwarding Agent Vendor Level 4]                  = S.[LVL_4],
        T.[Forwarding Agent Vendor Addressable]              = S.[ADDRESSABLE],
        T.[Forwarding Agent Tail Vendor]                     = S.[TAIL_VNDR],
        T.[Forwarding Agent Vendor Normalized]               = S.[NORMALIZED_VNDR],
        T.[Forwarding Agent Vendor Corporate Group]          = S.[CORPORATE_GROUP],
        T.[Forwarding Agent Vendor Account No Alternate Payee]= S.[ACCT_NO_ALT_PYE],
        T.[Forwarding Agent Vendor Email Address]            = S.[E_MAIL_ADDR]
    FROM [GLOBAL_EDW].[Propelis].[FORWARDING_AGENT_VENDOR] AS T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_VENDOR_CUR_D] AS S
        ON T.[VNDR_KEY] = S.[VNDR_KEY];

    -- Step 2: Insert new records from mirror into target table
    INSERT INTO [GLOBAL_EDW].[Propelis].[FORWARDING_AGENT_VENDOR] (
        [VNDR_KEY],
        [Forwarding Agent Vendor ID],
        [Forwarding Agent Vendor Name],
        [Forwarding Agent Vendor Description],
        [Forwarding Agent Vendor Account Group],
        [Forwarding Agent Vendor Title],
        [Forwarding Agent Vendor Search Term],
        [Forwarding Agent Vendor Street],
        [Forwarding Agent Vendor City Name],
        [Forwarding Agent Vendor Zip Code],
        [Forwarding Agent Vendor Country Code],
        [Forwarding Agent Vendor State],
        [Forwarding Agent Vendor Telephone Number 1 Code],
        [Forwarding Agent Vendor Fax Number Code],
        [Forwarding Agent Vendor Tax Number 1 Code],
        [Forwarding Agent Vendor Tax Number 2 Code],
        [Forwarding Agent Vendor VAT Number Code],
        [Forwarding Agent Vendor Express Station],
        [Forwarding Agent Vendor Transportation Zone],
        [Forwarding Agent Vendor Industry],
        [Forwarding Agent Vendor Created Date],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Forwarding Agent Vendor Address Number],
        [Forwarding Agent Vendor Account Group Description],
        [Forwarding Agent Vendor Country Description],
        [Forwarding Agent Vendor Region Description],
        [Forwarding Agent Vendor Transportation Zone Description],
        [Forwarding Agent Vendor Industry Description],
        [Forwarding Agent Vendor Created By],
        [Forwarding Agent Vendor Central Deletion Indicator],
        [Forwarding Agent Vendor Central Posting Block],
        [Forwarding Agent Vendor Central Purchasing Block],
        [Forwarding Agent Vendor Language Key],
        [Forwarding Agent Vendor Customer ID],
        [Forwarding Agent Vendor One Time Account Indicator],
        [Forwarding Agent Vendor One Time Account Reference Group],
        [Forwarding Agent Vendor One Time Account Reference Group Desc],
        [Forwarding Agent Vendor Trading Partner],
        [Forwarding Agent Vendor Trading Partner Description],
        [Forwarding Agent Vendor VAT Indicator],
        [Forwarding Agent Vendor Industry Type],
        [Forwarding Agent Vendor Business Type],
        [Forwarding Agent Vendor Payment Block],
        [Forwarding Agent Vendor Tax Jurisdiction],
        [Forwarding Agent Vendor Tax Number 3 Code],
        [Forwarding Agent Vendor Tax Number Type],
        [Forwarding Agent Vendor Tax Type],
        [Forwarding Agent Vendor Level 1],
        [Forwarding Agent Vendor Level 2],
        [Forwarding Agent Vendor Level 3],
        [Forwarding Agent Vendor Level 4],
        [Forwarding Agent Vendor Addressable],
        [Forwarding Agent Tail Vendor],
        [Forwarding Agent Vendor Normalized],
        [Forwarding Agent Vendor Corporate Group],
        [Forwarding Agent Vendor Account No Alternate Payee],
        [Forwarding Agent Vendor Email Address]
    )
    SELECT
        S.[VNDR_KEY],
        S.[VNDR_ID],
        S.[VNDR_NAME],
        S.[VNDR_DESC],
        S.[VNDR_ACCT_GROUP],
        S.[TITLE],
        S.[SEARCH_TERM],
        S.[STR],
        S.[CITY_NAME],
        S.[ZIP_CD],
        S.[CNTRY_CD],
        S.[ST],
        S.[TEL_NUM_1_CD],
        S.[FAX_NUM_CD],
        S.[TAX_NUM_1_CD],
        S.[TAX_NUM_2_CD],
        S.[VAT_NUM_CD],
        S.[EXPRESS_STATION],
        S.[TRANSTN_ZONE],
        S.[INDUS],
        S.[CREATED_DATE],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[ADDR_NUM],
        S.[VNDR_ACCT_GROUP_DESC],
        S.[CNTRY_DESC],
        S.[REGN_DESC],
        S.[TRANSTN_ZONE_DESC],
        S.[INDUS_DESC],
        S.[CREATED_BY],
        S.[CENTRAL_DELETION_IND],
        S.[CENTRAL_PSTNG_BLK],
        S.[CENTRAL_PURNG_BLK],
        S.[LANG_KEY],
        S.[CUST_ID],
        S.[ONE_TM_ACCT_IND],
        S.[ONE_TM_ACCT_REF_ACCT__GROUP],
        S.[ONE_TM_ACC_REF_ACCT_GROUP_DESC],
        S.[TRADING_PRTNR],
        S.[TRADING_PRTNR_DESC],
        S.[VAT_IND],
        S.[INDUS_TYP],
        S.[BIZ_TYP],
        S.[PYMT_BLK],
        S.[TAX_JRSDCTN],
        S.[TAX_NUM_3_CD],
        S.[TAX_NUM_TYP],
        S.[TAX_TYP],
        S.[LVL_1],
        S.[LVL_2],
        S.[LVL_3],
        S.[LVL_4],
        S.[ADDRESSABLE],
        S.[TAIL_VNDR],
        S.[NORMALIZED_VNDR],
        S.[CORPORATE_GROUP],
        S.[ACCT_NO_ALT_PYE],
        S.[E_MAIL_ADDR]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_VENDOR_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[FORWARDING_AGENT_VENDOR] AS T
        ON T.[VNDR_KEY] = S.[VNDR_KEY]
    WHERE T.[VNDR_KEY] IS NULL;

END