CREATE     PROCEDURE [Propelis].[Proc_QC_COMPLETION_DATE] 
AS
BEGIN
    ----------------------------------------------------------------------
    -- Update existing records
    ----------------------------------------------------------------------
    UPDATE T
    SET
        T.[DATE_KEY] = S.[DATE_KEY],
        T.[QC Completion Date] = S.[THE_DATE],
        T.[QC Completion Fiscal Year] = S.[FISCAL_YR],
        T.[QC Completion Fiscal Period Number] = S.[FISCAL_PER_NUM],
        T.[QC Completion Fiscal Period Code] = S.[FISCAL_PER_CD],
        T.[QC Completion Fiscal Quarter Number] = S.[FISCAL_QTR_NUM],
        T.[QC Completion Fiscal Quarter Code] = S.[FISCAL_QTR_CD],
        T.[QC Completion Calendar Year] = S.[CLNDR_YR],
        T.[QC Completion Calendar Month Number] = S.[CLNDR_MNTH_NUM],
        T.[QC Completion Calendar Month Code] = S.[CLNDR_MNTH_CD],
        T.[QC Completion Calendar Month Description] = S.[CLNDR_MNTH_DESC],
        T.[QC Completion Calendar Quarter Number] = S.[CLNDR_QTR_NUM],
        T.[QC Completion Calendar Quarter Code] = S.[CLNDR_QTR_CD],
        T.[QC Completion Calendar Weekday Number] = S.[CLNDR_WEEKDAY_NUM],
        T.[QC Completion Calendar Weekday Name] = S.[CLNDR_WEEKDAY_NAME],
        T.[QC Completion Calendar Day In Month] = S.[CLNDR_DAY_IN_MNTH],
        T.[QC Completion Calendar Day In Year] = S.[CLNDR_DAY_IN_YR],
        T.[QC Completion Calendar Week] = S.[CLNDR_WK],
        T.[QC Completion Calendar Month In Quarter Number] = S.[CLNDR_MNTH_IN_QTR_NUM],
        T.[QC Completion Calendar Days In Month] = S.[CLNDR_DAYS_IN_MNTH],
        T.[ETL_SRC_SYS_CD] = S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS] = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS] = S.[ETL_UPDTD_TS],
        T.[QC Completion Current Day Flag] = S.[CURR_DAY_FLG],
        T.[QC Completion Current Day Minus 1 Flag] = S.[CURR_DAY_MINUS_1_FLG],
        T.[QC Completion Current Calendar Week Flag] = S.[CURR_CLNDR_WK_FLG],
        T.[QC Completion Current Calendar Week Minus 1 Flag] = S.[CURR_CLNDR_WK_MINUS_1_FLG],
        T.[QC Completion Current Month Flag] = S.[CURR_MNTH_FLG],
        T.[QC Completion Current Month Minus 1 Flag] = S.[CURR_MNTH_MINUS_1_FLG],
        T.[QC Completion Current Month Minus 12 Flag] = S.[CURR_MNTH_MINUS_12_FLG],
        T.[QC Completion Current Quarter Flag] = S.[CURR_QTR_FLG],
        T.[QC Completion Current Quarter Minus 1 Flag] = S.[CURR_QTR_MINUS_1_FLG],
        T.[QC Completion Current Quarter Minus 4 Flag] = S.[CURR_QTR_MINUS_4_FLG],
        T.[QC Completion Current Calendar Year Flag] = S.[CURR_CLNDR_YR_FLG],
        T.[QC Completion Current Calendar Year Minus 1 Flag] = S.[CURR_CLNDR_YR_MINUS_1_FLG],
        T.[QC Completion Current Calendar Year Minus 2 Flag] = S.[CURR_CLNDR_YR_MINUS_2_FLG],
        T.[QC Completion Current Fiscal Year Flag] = S.[CURR_FISCAL_YR_FLG],
        T.[QC Completion Current Fiscal Year Minus 1 Flag] = S.[CURR_FISCAL_YR_MINUS_1_FLG],
        T.[QC Completion Current Fiscal Year Minus 2 Flag] = S.[CURR_FISCAL_YR_MINUS_2_FLG],
        T.[QC Completion Current Calendar Year Plus 1 Flag] = S.[CURR_CLNDR_YR_PLUS_1_FLG],
        T.[QC Completion_FISCAL_YR_PLUS_1_FLG] = S.[CURR_FISCAL_YR_PLUS_1_FLG],
        T.[QC Completion Day In Fiscal Year] = S.[DAY_IN_FISCAL_YR],
        T.[QC Completion Date Is Weekday] = S.[IS_WEEKDAY],
        T.[QC Completion Fiscal Week] = S.[FISCAL_WK],
        T.[QC Completion Current Fiscal Week Flag] = S.[CURR_FISCAL_WK_FLG],
        T.[QC Completion Current Fiscal Week Minus 1 Flag] = S.[CURR_FISCAL_WK_MINUS_1_FLG],
        T.[QC Completion Fiscal Weekday Number] = S.[FISCAL_WEEKDAY_NUM],
        T.[QC Completion Fiscal Weekday Name] = S.[FISCAL_WEEKDAY_NAME],
        T.[QC Completion Current Month Minus 2 Flag] = S.[CURR_MNTH_MINUS_2_FLG],
        T.[QC Completion Current Fiscal Week Minus 2 Flag] = S.[CURR_FISCAL_WK_MINUS_2_FLG],
        T.[QC Completion Current Fiscal Week Minus 6 Flag] = S.[CURR_FISCAL_WK_MINUS_6_FLG],
        T.[QC Completion Current Fiscal Week Minus 3 Flag] = S.[CURR_FISCAL_WK_MINUS_3_FLG],
        T.[QC Completion Current Fiscal Week Minus 4 Flag] = S.[CURR_FISCAL_WK_MINUS_4_FLG],
        T.[QC Completion Current Fiscal Week Minus 5 Flag] = S.[CURR_FISCAL_WK_MINUS_5_FLG],
        T.[QC Completion Current Fiscal Week Minus 7 Flag] = S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW].[Propelis].[QC_COMPLETION_DATE] T
    INNER JOIN [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] S
        ON T.[DATE_KEY] = S.[DATE_KEY];

    ----------------------------------------------------------------------
    -- Insert new records
    ----------------------------------------------------------------------
    INSERT INTO [GLOBAL_EDW].[Propelis].[QC_COMPLETION_DATE] (
        [DATE_KEY],
        [QC Completion Date],
        [QC Completion Fiscal Year],
        [QC Completion Fiscal Period Number],
        [QC Completion Fiscal Period Code],
        [QC Completion Fiscal Quarter Number],
        [QC Completion Fiscal Quarter Code],
        [QC Completion Calendar Year],
        [QC Completion Calendar Month Number],
        [QC Completion Calendar Month Code],
        [QC Completion Calendar Month Description],
        [QC Completion Calendar Quarter Number],
        [QC Completion Calendar Quarter Code],
        [QC Completion Calendar Weekday Number],
        [QC Completion Calendar Weekday Name],
        [QC Completion Calendar Day In Month],
        [QC Completion Calendar Day In Year],
        [QC Completion Calendar Week],
        [QC Completion Calendar Month In Quarter Number],
        [QC Completion Calendar Days In Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [QC Completion Current Day Flag],
        [QC Completion Current Day Minus 1 Flag],
        [QC Completion Current Calendar Week Flag],
        [QC Completion Current Calendar Week Minus 1 Flag],
        [QC Completion Current Month Flag],
        [QC Completion Current Month Minus 1 Flag],
        [QC Completion Current Month Minus 12 Flag],
        [QC Completion Current Quarter Flag],
        [QC Completion Current Quarter Minus 1 Flag],
        [QC Completion Current Quarter Minus 4 Flag],
        [QC Completion Current Calendar Year Flag],
        [QC Completion Current Calendar Year Minus 1 Flag],
        [QC Completion Current Calendar Year Minus 2 Flag],
        [QC Completion Current Fiscal Year Flag],
        [QC Completion Current Fiscal Year Minus 1 Flag],
        [QC Completion Current Fiscal Year Minus 2 Flag],
        [QC Completion Current Calendar Year Plus 1 Flag],
        [QC Completion_FISCAL_YR_PLUS_1_FLG],
        [QC Completion Day In Fiscal Year],
        [QC Completion Date Is Weekday],
        [QC Completion Fiscal Week],
        [QC Completion Current Fiscal Week Flag],
        [QC Completion Current Fiscal Week Minus 1 Flag],
        [QC Completion Fiscal Weekday Number],
        [QC Completion Fiscal Weekday Name],
        [QC Completion Current Month Minus 2 Flag],
        [QC Completion Current Fiscal Week Minus 2 Flag],
        [QC Completion Current Fiscal Week Minus 6 Flag],
        [QC Completion Current Fiscal Week Minus 3 Flag],
        [QC Completion Current Fiscal Week Minus 4 Flag],
        [QC Completion Current Fiscal Week Minus 5 Flag],
        [QC Completion Current Fiscal Week Minus 7 Flag]
    )
    SELECT
        S.[DATE_KEY],
        S.[THE_DATE],
        S.[FISCAL_YR],
        S.[FISCAL_PER_NUM],
        S.[FISCAL_PER_CD],
        S.[FISCAL_QTR_NUM],
        S.[FISCAL_QTR_CD],
        S.[CLNDR_YR],
        S.[CLNDR_MNTH_NUM],
        S.[CLNDR_MNTH_CD],
        S.[CLNDR_MNTH_DESC],
        S.[CLNDR_QTR_NUM],
        S.[CLNDR_QTR_CD],
        S.[CLNDR_WEEKDAY_NUM],
        S.[CLNDR_WEEKDAY_NAME],
        S.[CLNDR_DAY_IN_MNTH],
        S.[CLNDR_DAY_IN_YR],
        S.[CLNDR_WK],
        S.[CLNDR_MNTH_IN_QTR_NUM],
        S.[CLNDR_DAYS_IN_MNTH],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[CURR_DAY_FLG],
        S.[CURR_DAY_MINUS_1_FLG],
        S.[CURR_CLNDR_WK_FLG],
        S.[CURR_CLNDR_WK_MINUS_1_FLG],
        S.[CURR_MNTH_FLG],
        S.[CURR_MNTH_MINUS_1_FLG],
        S.[CURR_MNTH_MINUS_12_FLG],
        S.[CURR_QTR_FLG],
        S.[CURR_QTR_MINUS_1_FLG],
        S.[CURR_QTR_MINUS_4_FLG],
        S.[CURR_CLNDR_YR_FLG],
        S.[CURR_CLNDR_YR_MINUS_1_FLG],
        S.[CURR_CLNDR_YR_MINUS_2_FLG],
        S.[CURR_FISCAL_YR_FLG],
        S.[CURR_FISCAL_YR_MINUS_1_FLG],
        S.[CURR_FISCAL_YR_MINUS_2_FLG],
        S.[CURR_CLNDR_YR_PLUS_1_FLG],
        S.[CURR_FISCAL_YR_PLUS_1_FLG],
        S.[DAY_IN_FISCAL_YR],
        S.[IS_WEEKDAY],
        S.[FISCAL_WK],
        S.[CURR_FISCAL_WK_FLG],
        S.[CURR_FISCAL_WK_MINUS_1_FLG],
        S.[FISCAL_WEEKDAY_NUM],
        S.[FISCAL_WEEKDAY_NAME],
        S.[CURR_MNTH_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_2_FLG],
        S.[CURR_FISCAL_WK_MINUS_6_FLG],
        S.[CURR_FISCAL_WK_MINUS_3_FLG],
        S.[CURR_FISCAL_WK_MINUS_4_FLG],
        S.[CURR_FISCAL_WK_MINUS_5_FLG],
        S.[CURR_FISCAL_WK_MINUS_7_FLG]
    FROM [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_D_MST_DATE_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[Propelis].[QC_COMPLETION_DATE] T
        ON T.[DATE_KEY] = S.[DATE_KEY]
    WHERE T.[DATE_KEY] IS NULL;
END