CREATE   PROCEDURE [Propelis].[Proc_EDW_T_FACT_PRD_ENCPDAT_CUR_D]
AS
BEGIN
 
   -- Step 1: Clear existing data from the target table
   
TRUNCATE TABLE [GLOBAL_EDW].[Propelis].[EDW_T_FACT_PRD_ENCPDAT_CUR_D];
 
   -- Step 2: Insert refreshed data from mirror table with joins
 
INSERT INTO [GLOBAL_EDW].[Propelis].[EDW_T_FACT_PRD_ENCPDAT_CUR_D](
    [ENCP Job ID],
    [ENCP Investigation Level],
    [ENCP Brand],
    [ENCP Category],
    [ENCP Client],
    [DISCOVERY_DATE_KEY],
    [ENCP Notification Number],
    [ENCP Estimated Cost of Poor Quality],
    [INVESTIGATION_START_DATE_KEY],
    [OCCURRENCE_DATE_KEY],
    [ENCP Other Impacted Service Orders],
    [ENCP Primary Error Category],
    [ENCP Primary Root Cause],
    [ENCP Repeat Incident],
    [ENCP Responsible Department],
    [ENCP Secondary Error Category],
    [ENCP Secondary Root Cause],
    [ENCP SGK Error],
    [ENCP SKU Description],
    [ENCP Sold To Party Name],
    [START_DATE_KEY],
    [ENCP Status],
    [SERVC_ORDER_KEY],
    [SALES_ORDER_KEY],
    [SOLD_TO_PARTY_KEY],
    [CUST_BRAND_HIERCHY_KEY],
    [SKU_MATRL_KEY],
    [ETL_SRC_SYS_CD],
    [ETL_CREATED_TS],
    [ETL_UPDTD_TS],
    [ENCP Potential Value of Claim $],
    [ENCP Settled Value of Claim $],
    [ENCP Describe Potential Impact Of The Error],
    [ENCP On Hold Reason]
)
 
SELECT
    FACT.[JOB_ID],
    FACT.[INVESTIGATION_LVL],
    FACT.[BRAND],
    FACT.[CTGRY],
    FACT.[CLNT],
    FACT.[DISCOVERY_DATE_KEY],
    FACT.[ENCP_NOTIFICATION_NO],
    FACT.[ESTD_COST_OF_POOR_QUAL],
    FACT.[INVESTIGATION_START_DATE_KEY],
    FACT.[OCCURRENCE_DATE_KEY],
    FACT.[OTHR_IMPACTED_SERVC_ORDERS],
    FACT.[PRIMARY_ERR_CTGRY],
    FACT.[PRIMARY_ROOT_CAUSE],
    FACT.[REPEAT_INCIDENT],
    FACT.[RESPNSBLE_DEPT],
    FACT.[SECONDARY_ERR_CTGRY],
    FACT.[SECONDARY_ROOT_CAUSE],
    FACT.[SGK_ERR],
    FACT.[SKU_DESC],
    FACT.[SOLD_TO_PARTY_NAME],
    FACT.[START_DATE_KEY],
    FACT.[STATUS],
    FACT.[SERVC_ORDER_KEY],
    FACT.[SALES_ORDER_KEY],
    FACT.[SOLD_TO_PARTY_KEY],
    FACT.[CUST_BRAND_HIERCHY_KEY],
    FACT.[SKU_MATRL_KEY],
    FACT.[ETL_SRC_SYS_CD],
    FACT.[ETL_CREATED_TS],
    FACT.[ETL_UPDTD_TS],
    FACT.[POTENTIAL_VAL_OF_CLAIM_$],
    FACT.[SETTLED_VAL_OF_CLAIM_$],
    FACT.[DESCRIBE_POTENTIAL_IMPACT_OF_TH],
    FACT.[ON_HOLD_RSN]
 
FROM  [GLOBAL_EDW_QA].[GLOBAL_EDW].[EDW_T_F_PRD_ENCPDAT_CUR_D] AS FACT
 
LEFT JOIN [GLOBAL_EDW].[Propelis].[START_DATE] AS SD
  ON FACT.START_DATE_KEY = SD.DATE_KEY
   
LEFT JOIN [GLOBAL_EDW].[Propelis].[SOLD_TO_PARTY] AS ST_PRTY
  ON FACT.SOLD_TO_PARTY_KEY = ST_PRTY.CUST_KEY
 
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_MATERIAL_CUR_D] AS MST_MATERIAL
  ON FACT.SKU_MATRL_KEY = MST_MATERIAL.MATRL_KEY
 
LEFT JOIN [GLOBAL_EDW].[Propelis].[EDW_T_D_MST_CUSTBRD_CUR_D] AS MST_CUSTBRD
  ON FACT.CUST_BRAND_HIERCHY_KEY = MST_CUSTBRD.CUST_BRAND_HIERCHY_KEY
 
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_SALORDH_CUR_D] AS SAL_SALORDH
  ON FACT.SALES_ORDER_KEY = SAL_SALORDH.SALES_ORDER_KEY
 
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_PRD_SERVORD_CUR_D] AS PRD_SERVORD
  ON FACT.SERVC_ORDER_KEY=PRD_SERVORD.SERVC_ORDER_KEY
 
LEFT JOIN [GLOBAL_EDW].[Propelis].[OCCURRENCE_DATE] AS OCRNC_DT
  ON FACT.OCCURRENCE_DATE_KEY = OCRNC_DT.DATE_KEY
 
LEFT JOIN [GLOBAL_EDW].[Propelis].[Investigation_Start_Date] AS IN_ST_DT
  ON FACT.INVESTIGATION_START_DATE_KEY = IN_ST_DT.DATE_KEY
 
LEFT JOIN [GLOBAL_EDW].[Propelis].[DISCOVERY_DATE] AS DV_DT
  ON FACT.DISCOVERY_DATE_KEY = DV_DT.DATE_KEY;
 
END