-- Auto Generated (Do not modify) D74EDF20EFFA82CFD9E1216A94F17A220D1F4BB7E6DB78805BE5B8DE1779A376
CREATE   view [V_SALES_ORDER_HEADER_CREATE_DATE] 
	(
		[DATE_KEY],															 
		[Sales Order Header Creation Date],                                    
		[Sales Order Header Creation Fiscal Year],                             
		[Sales Order Header Creation Fiscal Period],                           
		[Sales Order Header Creation Fiscal Period Code],                      
		[Sales Order Header Creation Calendar Quarter],                        
		[Sales Order Header Creation Fiscal Quarter Code],                     
		[Sales Order Header Creation Calendar Year],                           
		[Sales Order Header Creation Calendar Month Number],                   
		[Sales Order Header Creation Calendar Month Code],                     
		[Sales Order Header Creation Calendar Month Desc],                     
		[CLNDR_QTR_NUM],                                                       
		[Sales Order Header Creation Calendar Quarter Code],                   
		[Sales Order Header Creation Calendar Weekday Number],                 
		[Sales Order Header Creation Calendar Weekday Name],                   
		[Sales Order Header Creation Calendar Day in Month],                   
		[Sales Order Header Creation Calendar Day in Year],                    
		[Sales Order Header Creation Calendar Week],                           
		[Sales Order Header Creation Calendar Month in Quarter Number],        
		[Sales Order Header Creation Calendar Days in Month],                  
		[ETL_SRC_SYS_CD],                                                      
		[ETL_CREATED_TS],                                                      
		[ETL_UPDTD_TS],                                                        
		[Sales Order Header Creation Current Day Flag],                        
		[Sales Order Header Creation Current Day Minus 1 Flag],                
		[Sales Order Header Creation Current Calendar Week Flag],              
		[Sales Order Header Creation Current Calendar Week Minus 1 Flag],      
		[Sales Order Header Creation Current Month Flag],                      
		[Sales Order Header Creation Current Month Minus 1 Flag],              
		[Sales Order Header Creation Current Month Minus 12 Flag],             
		[Sales Order Header Creation Current Quarter Flag],                    
		[Sales Order Header Creation Current Quarter Minus 1 Flag],            
		[Sales Order Header Creation Current Quarter Minus 4 Flag],            
		[Sales Order Header Creation Current Calendar Year Flag],              
		[Sales Order Header Creation Current Calendar Year Minus 1 Flag],      
		[Sales Order Header Creation Current Calendar Year Minus 2 Flag],      
		[Sales Order Header Creation Current Fiscal Year Flag],                
		[Sales Order Header Creation Current Fiscal Year Minus 1 Flag],        
		[Sales Order Header Creation Current Fiscal Year Minus 2 Flag],        
		[Sales Order Header Creation Current Calendar Year Plus 1 Flag],       
		[Sales Order Header Creation Current Fiscal Year Plus 1 Flag],         
		[Sales Order Header Creation Day In Fiscal Year],                      
		[IS_WEEKDAY],                                                          
		[FISCAL_WK],                                                           
		[Sales Order Header Creation Current Fiscal Week Flag],                
		[Sales Order Header Creation Current Fiscal Week Minus 1 Flag],        
		[Sales Order Header Creation Fiscal Weekday Number],                   
		[Sales Order Header Creation Fiscal Weekday Name],                     
		[CURR_MNTH_MINUS_2_FLG],                                               
		[Sales Order Header Creation Current Fiscal Week Minus 2 Flag],        
		[Sales Order Header Creation Current Fiscal Week Minus 6 Flag],        
		[Sales Order Header Creation Current Fiscal Week Minus 3 Flag],        
		[Sales Order Header Creation Current Fiscal Week Minus 4 Flag],        
		[Sales Order Header Creation Current Fiscal Week Minus 5 Flag],        
		[Sales Order Header Creation Current Fiscal Week Minus 7 Flag]
)
as select 
        [DATE_KEY],
        [Date],
        [Date Fiscal Year],
        [FISCAL_PER_NUM],
        [Date Fiscal Period Code],
        [Date Fiscal Quarter Number],
        [Date Fiscal Quarter Code],
        [Date Calendar Year],
        [Date Calendar Month Number],
        [Date Calendar Month Code],
        [Date Calendar Month Desc],
        [CLNDR_QTR_NUM],
        [Date Calendar Quarter Code],
        [Date Calendar Weekday Number],
        [Date Calendar Weekday Name],
        [Date Calendar Day in Month],
        [Date Calendar Day in Year],
        [Date Calendar Week],
        [Date Calendar Month in Quarter Number],
        [Date Calendar Days in Month],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Date Current Day Flag],
        [Date Current Day Minus 1 Flag],
        [Date Current Calendar Week Flag],
        [Date Current Calendar Week Minus 1 Flag],
        [Date Current Month Flag],
        [Date Current Month Minus 1 Flag],
        [Date Current Month Minus 12 Flag],
        [Date Current Quarter Flag],
        [Date Current Quarter Minus 1 Flag],
        [Date Current Quarter Minus 4 Flag],
        [Date Current Calendar Year Flag],
        [Date Current Calendar Year Minus 1 Flag],
        [Date Current Calendar Year Minus 2 Flag],
        [Date Current Fiscal Year Flag],
        [Date Current Fiscal Year Minus 1 Flag],
        [Date Current Fiscal Year Minus 2 Flag],
        [Date Current Calendar Year Plus 1 Flag],
        [Date Current Fiscal Year Plus 1 Flag],
        [Date Day in Fiscal Year],
        [Date Date Is Weekday],
        [Date Fiscal Week],
        [Date Current Fiscal Week Flag],
        [Date Current Fiscal Week Minus 1 Flag],
        [Date Fiscal Weekday Number],
        [Date Fiscal Weekday Name],
        [Date Current Month Minus 2 Flag],
        [Date Current Fiscal Week Minus 2 Flag],
        [Date Current Fiscal Week Minus 6 Flag],
        [Date Current Fiscal Week Minus 3 Flag],
        [Date Current Fiscal Week Minus 4 Flag],
        [Date Current Fiscal Week Minus 5 Flag],
        [Date Current Fiscal Week Minus 7 Flag]
   from  [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D];