CREATE   PROCEDURE [dbo].[Proc_EDW_T_D_PM_ORDER_CUR_D]
AS
BEGIN
    -- Update existing records
    UPDATE T
    SET
        T.[Order Type]                   = S.[ORDER_TYP],
        T.[Order Category]               = S.[ORDER_CTGRY],
        T.[Order Company Code]           = S.[CMPNY_CD],
        T.[Production Plant ID]          = S.[PROD_PLNT_ID],
        T.[Planning Plant ID]            = S.[PLNG_PLNT_ID],
        T.[Material ID]                  = S.[MATRL_ID],
        T.[Order Profit Center ID]       = S.[PROFT_CNTR_ID],
        T.[Sales Order ID]               = S.[SALES_ORDER_ID],
        T.[Sales Order Item Number]      = S.[SALES_ORDER_ITM_NBR],
        T.[Task List Type]               = S.[TASK_LIST_TYP],
        T.[Order Create Date]            = S.[ORDER_CREATE_DATE],
        T.[Order Close Date]             = S.[ORDER_CLS_DATE],
        T.[Project ID]                   = S.[PROJ_ID],
        T.[MRP Controller Code]          = S.[MRP_CNTRLR_CD],
        T.[Reservation Number]           = S.[RESRVTN_NUM],
        T.[Scheduled Start Date]         = S.[SCHLD_START_DATE],
        T.[Scheduled Finish Date]        = S.[SCHLD_FINISH_DATE],
        T.[Actual Start Date]            = S.[ACTUAL_START_DATE],
        T.[Actual Finish Date]           = S.[ACTUAL_FINISH_DATE],
        T.[Planned Release Date]         = S.[PLND_RELS_DATE],
        T.[Actual Release Date]          = S.[ACTUAL_RELS_DATE],
        T.[ETL_SRC_SYS_CD]               = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE]       = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE]         = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND]             = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS]               = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS]                 = S.[ETL_UPDTD_TS],
        T.[Order Number]                 = S.[ORDER_NUM],
        T.[Entered By]                   = S.[ENTERED_BY],
        T.[Order Description]            = S.[ORDER_DESC],
        T.[WBS Element Internal]         = S.[WBS_ELEMNT_INTERNL],
        T.[Controlling Area]             = S.[CONTROLLING_AREA],
        T.[Responsible Cost Center]      = S.[RESPNSBLE_COST_CNTR],
        T.[Order Currency Code]          = S.[CRNCY_CD],
        T.[Release Date]                 = S.[RELS_DATE],
        T.[Technical Completion Date]    = S.[TCHNCL_COMPLETION_DATE],
        T.[Object Number]                = S.[OBJ_NUM],
        T.[Requested By]                 = S.[REQD_BY],
        T.[Reason Code]                  = S.[RSN_CD],
        T.[Error Severity]               = S.[ERR_SEVERITY],
        T.[Error Caught By]              = S.[ERR_CAUGHT_BY],
        T.[Error Origin]                 = S.[ERR_ORIGIN],
        T.[Error Type]                   = S.[ERR_TYP],
        T.[Error Description]            = S.[ERR_DESC],
        T.[Reason For Change]            = S.[RSN_FOR_CHG],
        T.[Description Of Change]        = S.[DESC_OF_CHG],
        T.[Main Work Center ID]          = S.[MAIN_WRK_CNTR_ID],
        T.[Costing Sheet]                = S.[COSTING_SHEET],
        T.[Order Changed By]             = S.[ORDER_CHANGED_BY],
        T.[Order Changed On]             = S.[ORDER_CHANGED_ON],
        T.[Business Area]                = S.[BIZ_AREA],
        T.[Functional Area]              = S.[FUNCTNL_AREA],
        T.[Object Class]                 = S.[OBJ_CLASS],
        T.[Tax Jurisdiction]             = S.[TAX_JRSDCTN],
        T.[Overhead Key]                 = S.[OVERHEAD_KEY],
        T.[Basic End Date]               = S.[BASIC_END_DATE],
        T.[Basic Start Date]             = S.[BASIC_START_DATE],
        T.[Scheduled Release Date]       = S.[SCHLD_RELS_DATE],
        T.[Plan Number Of Operation]     = S.[PLAN_NUM_OF_OPERATION],
        T.[Exact Break Times]            = S.[EXACT_BRK_TIMES],
        T.[Network Profile]              = S.[NTWRK_PROFILE],
        T.[Order Priority]               = S.[ORDER_PRIORITY],
        T.[Costing Variant Plan]         = S.[COSTING_VARIANT_PLAN],
        T.[Costing Variant Actual]       = S.[COSTING_VARIANT_ACTUAL],
        T.[Superior Network Number]      = S.[SUPERIOR_NTWRK_NUM],
        T.[Superior Activity]            = S.[SUPERIOR_ACTIVITY],
        T.[Responsible Planner Group]    = S.[RESPNSBLE_PLANNER_GROUP],
        T.[Change Number]                = S.[CHG_NUM],
        T.[Order Type Description]       = S.[ORDER_TYP_DESC],
        T.[Order Category Description]   = S.[ORDER_CTGRY_DESC],
        T.[Task List Type Description]   = S.[TASK_LIST_TYP_DESC],
        T.[MRP Controller Code Description] = S.[MRP_CNTRLR_CD_DESC],
        T.[Controlling Area Description] = S.[CONTROLLING_AREA_DESC],
        T.[Business Area Description]    = S.[BIZ_AREA_DESC],
        T.[Functional Area Description]  = S.[FUNCTNL_AREA_DESC],
        T.[Object Class Description]     = S.[OBJ_CLASS_DESC],
        T.[External Order Number]        = S.[EXTNL_ORDER_NUM],
        T.[Person Responsible]           = S.[PERSON_RESPNSBLE],
        T.[End Of Work Date]             = S.[END_OF_WRK_DATE],
        T.[Date Of Last Status Change]   = S.[DATE_OF_LAST_STATUS_CHG],
        T.[Status Reached So Far]        = S.[STATUS_REACHED_SO_FAR],
        T.[Is Created]                   = S.[IS_CREATED],
        T.[Is Released]                  = S.[IS_RELSD],
        T.[Is Completed]                 = S.[IS_COMPLETED],
        T.[Is Closed]                    = S.[IS_CLSD],
        T.[Deletion Indicator]           = S.[DELETION_IND]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_PM_ORDER_CUR_D] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_PM_ORDER_CUR_D] S
        ON T.[ORDER_KEY] = S.[ORDER_KEY];

    -- Insert new records
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_PM_ORDER_CUR_D] (
        [ORDER_KEY],
        [Order Type],
        [Order Category],
        [Order Company Code],
        [Production Plant ID],
        [Planning Plant ID],
        [Material ID],
        [Order Profit Center ID],
        [Sales Order ID],
        [Sales Order Item Number],
        [Task List Type],
        [Order Create Date],
        [Order Close Date],
        [Project ID],
        [MRP Controller Code],
        [Reservation Number],
        [Scheduled Start Date],
        [Scheduled Finish Date],
        [Actual Start Date],
        [Actual Finish Date],
        [Planned Release Date],
        [Actual Release Date],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Order Number],
        [Entered By],
        [Order Description],
        [WBS Element Internal],
        [Controlling Area],
        [Responsible Cost Center],
        [Order Currency Code],
        [Release Date],
        [Technical Completion Date],
        [Object Number],
        [Requested By],
        [Reason Code],
        [Error Severity],
        [Error Caught By],
        [Error Origin],
        [Error Type],
        [Error Description],
        [Reason For Change],
        [Description Of Change],
        [Main Work Center ID],
        [Costing Sheet],
        [Order Changed By],
        [Order Changed On],
        [Business Area],
        [Functional Area],
        [Object Class],
        [Tax Jurisdiction],
        [Overhead Key],
        [Basic End Date],
        [Basic Start Date],
        [Scheduled Release Date],
        [Plan Number Of Operation],
        [Exact Break Times],
        [Network Profile],
        [Order Priority],
        [Costing Variant Plan],
        [Costing Variant Actual],
        [Superior Network Number],
        [Superior Activity],
        [Responsible Planner Group],
        [Change Number],
        [Order Type Description],
        [Order Category Description],
        [Task List Type Description],
        [MRP Controller Code Description],
        [Controlling Area Description],
        [Business Area Description],
        [Functional Area Description],
        [Object Class Description],
        [External Order Number],
        [Person Responsible],
        [End Of Work Date],
        [Date Of Last Status Change],
        [Status Reached So Far],
        [Is Created],
        [Is Released],
        [Is Completed],
        [Is Closed],
        [Deletion Indicator]
    )
    SELECT
        S.[ORDER_KEY],
        S.[ORDER_TYP],
        S.[ORDER_CTGRY],
        S.[CMPNY_CD],
        S.[PROD_PLNT_ID],
        S.[PLNG_PLNT_ID],
        S.[MATRL_ID],
        S.[PROFT_CNTR_ID],
        S.[SALES_ORDER_ID],
        S.[SALES_ORDER_ITM_NBR],
        S.[TASK_LIST_TYP],
        S.[ORDER_CREATE_DATE],
        S.[ORDER_CLS_DATE],
        S.[PROJ_ID],
        S.[MRP_CNTRLR_CD],
        S.[RESRVTN_NUM],
        S.[SCHLD_START_DATE],
        S.[SCHLD_FINISH_DATE],
        S.[ACTUAL_START_DATE],
        S.[ACTUAL_FINISH_DATE],
        S.[PLND_RELS_DATE],
        S.[ACTUAL_RELS_DATE],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[ORDER_NUM],
        S.[ENTERED_BY],
        S.[ORDER_DESC],
        S.[WBS_ELEMNT_INTERNL],
        S.[CONTROLLING_AREA],
        S.[RESPNSBLE_COST_CNTR],
        S.[CRNCY_CD],
        S.[RELS_DATE],
        S.[TCHNCL_COMPLETION_DATE],
        S.[OBJ_NUM],
        S.[REQD_BY],
        S.[RSN_CD],
        S.[ERR_SEVERITY],
        S.[ERR_CAUGHT_BY],
        S.[ERR_ORIGIN],
        S.[ERR_TYP],
        S.[ERR_DESC],
        S.[RSN_FOR_CHG],
        S.[DESC_OF_CHG],
        S.[MAIN_WRK_CNTR_ID],
        S.[COSTING_SHEET],
        S.[ORDER_CHANGED_BY],
        S.[ORDER_CHANGED_ON],
        S.[BIZ_AREA],
        S.[FUNCTNL_AREA],
        S.[OBJ_CLASS],
        S.[TAX_JRSDCTN],
        S.[OVERHEAD_KEY],
        S.[BASIC_END_DATE],
        S.[BASIC_START_DATE],
        S.[SCHLD_RELS_DATE],
        S.[PLAN_NUM_OF_OPERATION],
        S.[EXACT_BRK_TIMES],
        S.[NTWRK_PROFILE],
        S.[ORDER_PRIORITY],
        S.[COSTING_VARIANT_PLAN],
        S.[COSTING_VARIANT_ACTUAL],
        S.[SUPERIOR_NTWRK_NUM],
        S.[SUPERIOR_ACTIVITY],
        S.[RESPNSBLE_PLANNER_GROUP],
        S.[CHG_NUM],
        S.[ORDER_TYP_DESC],
        S.[ORDER_CTGRY_DESC],
        S.[TASK_LIST_TYP_DESC],
        S.[MRP_CNTRLR_CD_DESC],
        S.[CONTROLLING_AREA_DESC],
        S.[BIZ_AREA_DESC],
        S.[FUNCTNL_AREA_DESC],
        S.[OBJ_CLASS_DESC],
        S.[EXTNL_ORDER_NUM],
        S.[PERSON_RESPNSBLE],
        S.[END_OF_WRK_DATE],
        S.[DATE_OF_LAST_STATUS_CHG],
        S.[STATUS_REACHED_SO_FAR],
        S.[IS_CREATED],
        S.[IS_RELSD],
        S.[IS_COMPLETED],
        S.[IS_CLSD],
        S.[DELETION_IND]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_PM_ORDER_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_PM_ORDER_CUR_D] T
        ON T.[ORDER_KEY] = S.[ORDER_KEY]
    WHERE T.[ORDER_KEY] IS NULL;
END