CREATE   PROCEDURE [dbo].[Proc_EDW_T_B_PRD_SVORDPTR_CUR_D]
AS
BEGIN
    UPDATE T
    SET
        T.[SERVC_ORDER]	= S.[SERVC_ORDER],
        T.[BILL_TO_CUST_KEY]	= S.[BILL_TO_CUST_KEY],
        T.[EMPL_RESPNSBLE_KEY]	= S.[EMPL_RESPNSBLE_KEY],
        T.[SHIP_TO_CUST_KEY]	= S.[SHIP_TO_CUST_KEY],
        T.[SOLD_TO_CUST_KEY]	= S.[SOLD_TO_CUST_KEY],
        T.[PRINTER_CUST_KEY]	= S.[PRINTER_CUST_KEY],
        T.[BRAND_OWNER_CUST_KEY]	= S.[BRAND_OWNER_CUST_KEY],
        T.[PERSON_RESPNSBLE_KEY]	= S.[PERSON_RESPNSBLE_KEY],
        T.[BRAND_OWNER_CONTACT_KEY]	= S.[BRAND_OWNER_CONTACT_KEY],
        T.[AGENCY_CUST_KEY]	= S.[AGENCY_CUST_KEY],
        T.[SUPLR_CONTACT_PERSON_KEY]	= S.[SUPLR_CONTACT_PERSON_KEY],
        T.[VNDR_KEY]	= S.[VNDR_KEY],
        T.[CUST_PROJ_MGR_KEY]	= S.[CUST_PROJ_MGR_KEY],
        T.[SALES_EMPL_KEY]	= S.[SALES_EMPL_KEY],
        T.[PAYER_CUST_KEY]	= S.[PAYER_CUST_KEY],
        T.[CONTACT_PERSON_KEY]	= S.[CONTACT_PERSON_KEY],
        T.[SUPLR_CUST_KEY]	= S.[SUPLR_CUST_KEY],
        T.[AGENCY_CONTACT_PERSON_KEY]	= S.[AGENCY_CONTACT_PERSON_KEY],
        T.[USR_RESPNSBLE]	= S.[USR_RESPNSBLE],
        T.[ATE_CONTACT_PERSON_1_KEY]	= S.[ATE_CONTACT_PERSON_1_KEY],
        T.[EMPL_RESPNSBLE_2_KEY]	= S.[EMPL_RESPNSBLE_2_KEY],
        T.[PRINTER_CONTACT_PERSON_KEY]	= S.[PRINTER_CONTACT_PERSON_KEY],
        T.[ETL_SRC_SYS_CD]	= S.[ETL_SRC_SYS_CD],
        T.[ETL_CREATED_TS]	= S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS]	= S.[ETL_UPDTD_TS]

 FROM [GLOBAL_EDW].[dbo].[EDW_T_B_PRD_SVORDPTR_CUR_D] AS T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_B_PRD_SVORDPTR_CUR_D] AS S
        ON T.[SERVC_ORDER] = S.[SERVC_ORDER];

    -- Step 2: Insert new records from mirror into target table
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_B_PRD_SVORDPTR_CUR_D] (
        [SERVC_ORDER],
        [BILL_TO_CUST_KEY],
        [EMPL_RESPNSBLE_KEY],
        [SHIP_TO_CUST_KEY],
        [SOLD_TO_CUST_KEY],
        [PRINTER_CUST_KEY],
        [BRAND_OWNER_CUST_KEY],
        [PERSON_RESPNSBLE_KEY],
        [BRAND_OWNER_CONTACT_KEY],
        [AGENCY_CUST_KEY],
        [SUPLR_CONTACT_PERSON_KEY],
        [VNDR_KEY],
        [CUST_PROJ_MGR_KEY],
        [SALES_EMPL_KEY],
        [PAYER_CUST_KEY],
        [CONTACT_PERSON_KEY],
        [SUPLR_CUST_KEY],
        [AGENCY_CONTACT_PERSON_KEY],
        [USR_RESPNSBLE],
        [ATE_CONTACT_PERSON_1_KEY],
        [EMPL_RESPNSBLE_2_KEY],
        [PRINTER_CONTACT_PERSON_KEY],
        [ETL_SRC_SYS_CD],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS]

)
    SELECT
       S.[SERVC_ORDER],
       S.[BILL_TO_CUST_KEY],
       S.[EMPL_RESPNSBLE_KEY],
       S.[SHIP_TO_CUST_KEY],
       S.[SOLD_TO_CUST_KEY],
       S.[PRINTER_CUST_KEY],
       S.[BRAND_OWNER_CUST_KEY],
       S.[PERSON_RESPNSBLE_KEY],
       S.[BRAND_OWNER_CONTACT_KEY],
       S.[AGENCY_CUST_KEY],
       S.[SUPLR_CONTACT_PERSON_KEY],
       S.[VNDR_KEY],
       S.[CUST_PROJ_MGR_KEY],
       S.[SALES_EMPL_KEY],
       S.[PAYER_CUST_KEY],
       S.[CONTACT_PERSON_KEY],
       S.[SUPLR_CUST_KEY],
       S.[AGENCY_CONTACT_PERSON_KEY],
       S.[USR_RESPNSBLE],
       S.[ATE_CONTACT_PERSON_1_KEY],
       S.[EMPL_RESPNSBLE_2_KEY],
       S.[PRINTER_CONTACT_PERSON_KEY],
       S.[ETL_SRC_SYS_CD],
       S.[ETL_CREATED_TS],
       S.[ETL_UPDTD_TS]
    
	FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_B_PRD_SVORDPTR_CUR_D] AS S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_B_PRD_SVORDPTR_CUR_D] AS T
        ON T.[SERVC_ORDER] = S.[SERVC_ORDER]
    WHERE T.[SERVC_ORDER] IS NULL;

END