CREATE   PROCEDURE [dbo].[Proc_EDW_T_D_MST_PLANT_CUR_D]
AS
BEGIN
    -- Update existing records
    UPDATE T
    SET
        T.[Plant ID]                             = S.[PLNT_ID],
        T.[Legacy Plant ID]                      = S.[LGCY_PLNT_ID],
        T.[Plant Name]                           = S.[PLNT_NAME],
        T.[Plant Company Code]                   = S.[CMPNY_CD],
        T.[Plant Sales Organization]             = S.[SALES_ORGZTN],
        T.[Plant Purchasing Organization]        = S.[PURNG_ORGZTN],
        T.[Plant Valuation Area]                 = S.[VALTN_AREA],
        T.[Plant Customer Number]                = S.[CUST_NUM_OF_PLNT],
        T.[Plant Vendor Number]                  = S.[VNDR_NUM_OF_PLNT],
        T.[Plant Factory Calendar Key]           = S.[FACTORY_CLNDR_KEY],
        T.[Plant Line 1 Description]             = S.[PLNT_LINE_1_DESC],
        T.[Plant Line 2 Description]             = S.[PLNT_LINE_2_DESC],
        T.[Plant City Name]                      = S.[PLNT_CITY_NAME],
        T.[Plant Zip Code]                       = S.[PLNT_ZIP_CD],
        T.[Plant Country Code]                   = S.[PLNT_CNTRY_CD],
        T.[Plant Country Name]                   = S.[PLNT_CNTRY_NAME],
        T.[Plant Tax Jurisdiction]               = S.[TAX_JRSDCTN],
        T.[ETL_SRC_SYS_CD]                       = S.[ETL_SRC_SYS_CD],
        T.[ETL_EFFECTV_BEGIN_DATE]               = S.[ETL_EFFECTV_BEGIN_DATE],
        T.[ETL_EFFECTV_END_DATE]                 = S.[ETL_EFFECTV_END_DATE],
        T.[ETL_CURR_RCD_IND]                     = S.[ETL_CURR_RCD_IND],
        T.[ETL_CREATED_TS]                       = S.[ETL_CREATED_TS],
        T.[ETL_UPDTD_TS]                         = S.[ETL_UPDTD_TS],
        T.[Plant IS P001]                        = S.[IS_P001],
        T.[Plant IS P002]                        = S.[IS_P002],
        T.[Plant Company Description]            = S.[CMPNY_DESC],
        T.[Plant Sales Organization Description] = S.[SALES_ORG_DESC],
        T.[Plant Factory Calendar Description]   = S.[FACTORY_CLNDR_DESC],
        T.[Plant Purchasing Organization Description] = S.[PURNG_ORGZTN_DESC],
        T.[Plant Tax Indicator]                  = S.[PLNT_TAX_IND],
        T.[Plant Tax Indicator Description]      = S.[PLNT_TAX_IND_DESC],
        T.[Plant Shipping/Receiving Point]       = S.[SHIPG_RECVNG_PNT],
        T.[Plant Shipping/Receiving Point Description] = S.[SHIPG_RECVNG_PNT_DESC]
    FROM [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PLANT_CUR_D] T
    INNER JOIN [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_PLANT_CUR_D] S
        ON T.[PLNT_KEY] = S.[PLNT_KEY];

    -- Insert new records
    INSERT INTO [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PLANT_CUR_D]
    (
        [PLNT_KEY],
        [Plant ID],
        [Legacy Plant ID],
        [Plant Name],
        [Plant Company Code],
        [Plant Sales Organization],
        [Plant Purchasing Organization],
        [Plant Valuation Area],
        [Plant Customer Number],
        [Plant Vendor Number],
        [Plant Factory Calendar Key],
        [Plant Line 1 Description],
        [Plant Line 2 Description],
        [Plant City Name],
        [Plant Zip Code],
        [Plant Country Code],
        [Plant Country Name],
        [Plant Tax Jurisdiction],
        [ETL_SRC_SYS_CD],
        [ETL_EFFECTV_BEGIN_DATE],
        [ETL_EFFECTV_END_DATE],
        [ETL_CURR_RCD_IND],
        [ETL_CREATED_TS],
        [ETL_UPDTD_TS],
        [Plant IS P001],
        [Plant IS P002],
        [Plant Company Description],
        [Plant Sales Organization Description],
        [Plant Factory Calendar Description],
        [Plant Purchasing Organization Description],
        [Plant Tax Indicator],
        [Plant Tax Indicator Description],
        [Plant Shipping/Receiving Point],
        [Plant Shipping/Receiving Point Description]
    )
    SELECT
        S.[PLNT_KEY],
        S.[PLNT_ID],
        S.[LGCY_PLNT_ID],
        S.[PLNT_NAME],
        S.[CMPNY_CD],
        S.[SALES_ORGZTN],
        S.[PURNG_ORGZTN],
        S.[VALTN_AREA],
        S.[CUST_NUM_OF_PLNT],
        S.[VNDR_NUM_OF_PLNT],
        S.[FACTORY_CLNDR_KEY],
        S.[PLNT_LINE_1_DESC],
        S.[PLNT_LINE_2_DESC],
        S.[PLNT_CITY_NAME],
        S.[PLNT_ZIP_CD],
        S.[PLNT_CNTRY_CD],
        S.[PLNT_CNTRY_NAME],
        S.[TAX_JRSDCTN],
        S.[ETL_SRC_SYS_CD],
        S.[ETL_EFFECTV_BEGIN_DATE],
        S.[ETL_EFFECTV_END_DATE],
        S.[ETL_CURR_RCD_IND],
        S.[ETL_CREATED_TS],
        S.[ETL_UPDTD_TS],
        S.[IS_P001],
        S.[IS_P002],
        S.[CMPNY_DESC],
        S.[SALES_ORG_DESC],
        S.[FACTORY_CLNDR_DESC],
        S.[PURNG_ORGZTN_DESC],
        S.[PLNT_TAX_IND],
        S.[PLNT_TAX_IND_DESC],
        S.[SHIPG_RECVNG_PNT],
        S.[SHIPG_RECVNG_PNT_DESC]
    FROM [GLOBAL_EDW_MIRROR].[dbo].[EDW_T_D_MST_PLANT_CUR_D] S
    LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_PLANT_CUR_D] T
        ON T.[PLNT_KEY] = S.[PLNT_KEY]
    WHERE T.[PLNT_KEY] IS NULL;
END