

SELECT *

FROM GLOBAL_EDW.[Propelis].[EDW_T_Fact_PRD_SERVOPR_CUR_D] AS Fact

LEFT JOIN [GLOBAL_EDW].[Propelis].[BASIC_FINISH_DATE] AS Actual_Finish_Date 
    ON Fact.[BASIC_FINISH_DATE_KEY] = Actual_Finish_Date.[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[ACTUAL_FINISH_EXEC_DATE] AS Actual_Finish_Exec_Date
    ON Fact.[ACTUAL_FINISH_DATE_KEY] = Actual_Finish_Exec_Date.[DATE_KEY] 
Tech_Completion_Date
LEFT JOIN [GLOBAL_EDW].[Propelis].[SERV_ORDER_INVOICE_CREATED_DATE] AS Serv_Order_Invoice_Created_Date
    ON Fact.[ACTUAL_RELS_DATE_KEY] = Serv_Order_Invoice_Created_Date.[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[START_CONSTRAINT_DATE] AS START_CONSTRAINT_DATE
    ON Fact.[START_CNSTRNT_DATE_KEY] = START_CONSTRAINT_DATE.[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[START_OF_MALFUNCTION_DATE] AS Start_Of_Malfunction_Date
    ON Fact.[START_OF_MALFUNCTION_DATE_KEY] = Start_Of_Malfunction_Date.[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[BASIC_FINISH_DATE] AS Basic_Finish_Date
    ON Fact.[BASIC_FINISH_DATE_KEY] = Basic_Finish_Date.[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[BASIC_START_DATE] AS Basic_Start_Date
    ON Fact.[BASIC_START_DATE_KEY] = Basic_Start_Date.[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[CLOSE_DATE] AS Close_Date
    ON Fact.[CLS_DATE_KEY] = Close_Date.[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[COMPANY] AS Company
    ON Fact.[CMPNY_CD_KEY] = Company.[CMPNY_CD] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[COMPANY] AS Company2
    ON Fact.[CMPNY_CD_KEY] = Company2.[CMPNY_CD] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[DOCUMENT_CURRENCY] 
    ON Fact.[DOCMT_CRNCY_KEY] = [GLOBAL_EDW].[Propelis].[DOCUMENT_CURRENCY].[CRNCY_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[END_OF_MALFUNCTION_DATE] 
    ON Fact.[END_OF_MALFUNCTION_DATE_KEY] = [GLOBAL_EDW].[Propelis].[END_OF_MALFUNCTION_DATE].[DATE_KEY] 
 

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_EQUIPMT_CUR_D] 
    ON Fact.[EQUIP_KEY] = [GLOBAL_EDW].[dbo].[EDW_T_D_MST_EQUIPMT_CUR_D].[EQUIP_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[EARLIEST_SCHLD_FINISH_EXEC_DATE] 
    ON Fact.[ERLST_SCHED_FINISH_EXCT_DATE_KE] = [GLOBAL_EDW].[Propelis].[EARLIEST_SCHLD_FINISH_EXEC_DATE].[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[EARLIEST_SCHLD_START_EXEC_DATE] 
    ON Fact.[ERLST_SCHLD_START_EXCT_DATE_KEY] = [GLOBAL_EDW].[Propelis].[EARLIEST_SCHLD_START_EXEC_DATE].[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[FINISH_CONSTRAINT_DATE] 
    ON Fact.[FINISH_CNSTRNT_DATE_KEY] = [GLOBAL_EDW].[Propelis].[FINISH_CONSTRAINT_DATE].[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_FUNCTAR_CUR_D] 
    ON Fact.[FUNCTNL_AREA_KEY] = [GLOBAL_EDW].[dbo].[EDW_T_D_MST_FUNCTAR_CUR_D].[FUNCTNL_AREA_KEY] 

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_FUNCLOC_CUR_D] 
    ON Fact.[FUNCTNL_LOC_KEY] = [GLOBAL_EDW].[dbo].[EDW_T_D_MST_FUNCLOC_CUR_D].[FUNCTNL_LOC_KEY]


LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D] AS EDW_T_D_MST_DATE_CUR_D_1
    ON Fact.[LATEST_SCHLD_START_EXCT_DATE_KE] = EDW_T_D_MST_DATE_CUR_D_1.[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[LOCATION_PLANT] 
    ON Fact.[LOC_PLNT_KEY] = [GLOBAL_EDW].[Propelis].[LOCATION_PLANT].[PLNT_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[MAINTENANCE_PLANT] 
    ON Fact.[MAINTENANCE_PLNT_KEY] = [GLOBAL_EDW].[Propelis].[MAINTENANCE_PLANT].[PLNT_KEY] 

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_NOTFICN_CUR_D] 
    ON Fact.[NOTIFICATION_KEY] = [GLOBAL_EDW].[dbo].[EDW_T_D_MST_NOTFICN_CUR_D].[NOTIFICATION_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[PLANNING_PLANT] AS PLANNING_PLANT
    ON Fact.[PLNG_PLNT_KEY] = PLANNING_PLANT.[PLNT_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[PLANT] 
    ON Fact.[PLNG_PLNT_KEY] = [GLOBAL_EDW].[Propelis].[PLANT].[PLNT_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[RELEASE_DATE]  
    ON Fact.[RELS_DATE_KEY] = [GLOBAL_EDW].[Propelis].[RELEASE_DATE].[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[RESP_COST_CENTER]  
    ON Fact.[RESPNSBLE_COST_CNTR_KEY] = [GLOBAL_EDW].[Propelis].[RESP_COST_CENTER].[COST_CNTR_KEY] -- No changes needed, join condition is valid
 
LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_SALORDH_CUR_D] 
    ON Fact.[SALES_ORDER_KEY] = [GLOBAL_EDW].[dbo].[EDW_T_D_SAL_SALORDH_CUR_D].[SALES_ORDER_KEY]

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D] AS EDW_T_D_MST_DATE_CUR_D_2
    ON Fact.[SCHLD_FINISH_DATE_KEY] = EDW_T_D_MST_DATE_CUR_D_2.[DATE_KEY]

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D] AS EDW_T_D_MST_DATE_CUR_D_3
    ON Fact.[SCHLD_RELS_DATE_KEY] = EDW_T_D_MST_DATE_CUR_D_3.[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[START_CONSTRAINT_DATE] AS START_CONSTRAINT_DATE_1
    ON Fact.[START_CNSTRNT_DATE_KEY] = START_CONSTRAINT_DATE_1.[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_PRD_SERVORD_CUR_D] 
    ON Fact.[SERVC_ORDER_KEY] = [GLOBAL_EDW].[dbo].[EDW_T_D_PRD_SERVORD_CUR_D].[SERVC_ORDER_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[CLOSE_DATE] 
    ON Fact.[CLS_DATE_KEY] = [GLOBAL_EDW].[Propelis].[CLOSE_DATE].[DATE_KEY] 
LEFT JOIN [GLOBAL_EDW].[Propelis].[START_OF_MALFUNCTION_DATE] 
    ON Fact.[START_OF_MALFUNCTION_DATE_KEY] = [GLOBAL_EDW].[Propelis].[START_OF_MALFUNCTION_DATE].[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[TECH_COMPLETION_DATE] 
    ON Fact.[TCHNCL_COMPLETION_DATE_KEY] = [GLOBAL_EDW].[Propelis].[TECH_COMPLETION_DATE].[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_WORKCTR_CUR_D] 
    ON Fact.[WRK_CNTR_KEY] = [GLOBAL_EDW].[dbo].[EDW_T_D_MST_WORKCTR_CUR_D].[WRK_CNTR_KEY] 

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_DATE_CUR_D] AS EDW_T_D_MST_DATE_CUR_D_4
    ON Fact.[PLND_RELS_DATE_KEY] = EDW_T_D_MST_DATE_CUR_D_4.[DATE_KEY] 

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_MATERIAL_CUR_D] 
    ON Fact.[SERVC_MATRL_KEY] = [GLOBAL_EDW].[dbo].[EDW_T_D_MST_MATERIAL_CUR_D].[MATRL_KEY] 

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_ACTTYPE_CUR_D] 
    ON Fact.[ACTIVITY_TYP_KEY] = [GLOBAL_EDW].[dbo].[EDW_T_D_MST_ACTTYPE_CUR_D].[ACTIVITY_TYP_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[PERSONNEL_NUMBER] AS PERSONNEL_NUMBER
    ON Fact.[PERSONEL_NUM_KEY] = PERSONNEL_NUMBER.[PERSONEL_KEY] 

LEFT JOIN [GLOBAL_EDW].[Propelis].[OPERATING_PLANT] -- Auto-Fix: Updated table name to match schema
    ON Fact.[OPER_PLANT_KEY] = [GLOBAL_EDW].[Propelis].[OPERATING_PLANT].[PLNT_KEY]
LEFT JOIN [GLOBAL_EDW].[Propelis].[CREATED_ON_DATE] -- Auto-Fix: Updated table name to match schema
    ON Fact.[CREATED_ON_DATE_KEY] = [GLOBAL_EDW].[Propelis].[CREATED_ON_DATE].[DATE_KEY] -- Auto-Fix: Ensured column names are case-sensitive and match schema
 

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTMINR_CUR_D] 
    ON Fact.[CUST_MATRL_INFO_RCD_KEY] = [GLOBAL_EDW].[dbo].[EDW_T_D_MST_CUSTMINR_CUR_D].[CUST_MATRL_INFO_RCD_KEY] 

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_V_D_SAL_PRDVCON_CUR_D]
    ON Fact.[SALES_ORDER_ID] = [GLOBAL_EDW].[dbo].[EDW_V_D_SAL_PRDVCON_CUR_D].[SALES_ORDER_ID] 
   AND Fact.[SALES_ORDER_ITM] = [GLOBAL_EDW].[dbo].[EDW_V_D_SAL_PRDVCON_CUR_D].[SALES_ORDER_ITM_ID] 
   AND [GLOBAL_EDW].[dbo].[EDW_V_D_SAL_PRDVCON_CUR_D].[ETL_CURR_RCD_IND] = 'Y'
 
LEFT JOIN [GLOBAL_EDW].[Propelis].[OPERATION_LEVEL_WORK_CENTER]  AS OPERATION_LEVEL_WORK_CENTER
    ON Fact.[OPERATION_LVL_WRK_CNTR_KEY] = OPERATION_LEVEL_WORK_CENTER.[WRK_CNTR_KEY]

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_B_SAL_SOIPTNR_CUR_D] 
    ON Fact.[EMPL_RESPNSBLE_KEY] = [GLOBAL_EDW].[dbo].[EDW_T_B_SAL_SOIPTNR_CUR_D].[EMPL_RESPNSBLE_KEY]

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_B_PRD_SVORDPTR_CUR_D] 
    ON Fact.[SERVC_ORDER] = [GLOBAL_EDW].[dbo].[EDW_T_B_PRD_SVORDPTR_CUR_D].[SERVC_ORDER] 
 
LEFT JOIN [GLOBAL_EDW].[Propelis].[SALES_EMPLOYEE] AS SALES_EMPLOYEE
    ON [GLOBAL_EDW].[dbo].[EDW_T_B_PRD_SVORDPTR_CUR_D].[SALES_EMPL_KEY] = SALES_EMPLOYEE.[PERSONEL_KEY]

LEFT JOIN [GLOBAL_EDW].[Propelis].[SHIP_TO_CUST] AS SHIP_TO_CUST
    ON Fact.[SHIP_TO_CUST_KEY] = SHIP_TO_CUST.[CUST_KEY]

LEFT JOIN [GLOBAL_EDW].[Propelis].[PRINTER_CUST] AS PRINTER_CUST
    ON Fact.[PRINTER_CUST_KEY] = PRINTER_CUST.[CUST_KEY]

LEFT JOIN [GLOBAL_EDW].[Propelis].[BRAND_OWNER_CUST] AS BRAND_OWNER_CUST
    ON Fact.[BRAND_OWNER_CUST_KEY] = BRAND_OWNER_CUST.[CUST_KEY]

LEFT JOIN [GLOBAL_EDW].[Propelis].[BILL_TO_CUST] AS BILL_TO_CUST
    ON Fact.[BILL_TO_CUST_KEY] = BILL_TO_CUST.[CUST_KEY]

LEFT JOIN [GLOBAL_EDW].[Propelis].[SOLD_TO_CUST] AS SOLD_TO_CUST
    ON Fact.[SOLD_TO_CUST_KEY] = SOLD_TO_CUST.[CUST_KEY]

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_B_SAL_SOIPTNR_CUR_D] AS EDW_T_B_SAL_SOIPTNR_CUR_D 
    ON Fact.[SERVC_ORDER] = EDW_T_B_SAL_SOIPTNR_CUR_D.[SALES_ORDER_ID] 
    AND Fact.[SALES_ORDER_ITM] = EDW_T_B_SAL_SOIPTNR_CUR_D.[SALES_ORDER_ITM_ID] 

LEFT JOIN [GLOBAL_EDW].[dbo].[EDW_T_R_MST_SGK_STNDRD_TXT_CATG_CUR_D]
		
		ON Fact.[TASK_TYPE_DESC] = [GLOBAL_EDW].[dbo].[EDW_T_R_MST_SGK_STNDRD_TXT_CATG_CUR_D].[STANDARD_TEXT_KEY]
		
--	Invalid column name 'COST_CNTR_KEY'. IS NOT PRESENT
-- JOIN [GLOBAL_EDW].[Propelis].[RESP_COST_CENTER_HORIZONTAL_HIERARCHY] AS RESP_COST_CENTER_HORIZONTAL_HIERARCHY
--     ON [GLOBAL_EDW].[Propelis].[RESP_COST_CENTER].[COST_CNTR_KEY] 
--         = RESP_COST_CENTER_HORIZONTAL_HIERARCHY.[COST_CNTR_KEY] 
	
JOIN  [GLOBAL_EDW].[Propelis].[RESP_COST_CENTER_VERTICAL_HIERARCHY] AS RESP_COST_CENTER_VERTICAL_HIERARCHY
        ON RESP_COST_CENTER_VERTICAL_HIERARCHY.[COST_CNTR_KEY]
		= [GLOBAL_EDW].[Propelis].[RESP_COST_CENTER].[COST_CNTR_KEY]

JOIN [GLOBAL_EDW].[Propelis].[COST_CENTER_VERTICAL_HIERARCHY] AS COST_CENTER_VERTICAL_HIERARCHY
    ON [GLOBAL_EDW].[Propelis].[COST_CENTER].[COST_CNTR_KEY] = COST_CENTER_VERTICAL_HIERARCHY.[COST_CNTR_KEY] 
 
JOIN [GLOBAL_EDW].[Propelis].[PLANT_REGION] AS PLANT_REGION
	
		ON [GLOBAL_EDW].[Propelis].[PLANT].[PLNT_ID] = PLANT_REGION.[PLANT]
	
JOIN [GLOBAL_EDW].[Propelis].[PERSONNEL_PLANT_REGION] AS ppr 
    ON SUBSTRING(pn.COST_CNTR_ID, 4, 4) = ppr.PLNT_ID 

JOIN [GLOBAL_EDW].[Propelis].[LOCATION_PLANT_REGION] AS LOCATION_PLANT_REGION
		
		ON [GLOBAL_EDW].[Propelis].[LOCATION_PLANT].[PLNT_ID] = LOCATION_PLANT_REGION.[PLANT] 
		
JOIN [GLOBAL_EDW].[Propelis].[PLANNING_PLANT_REGION] AS PLANNING_PLANT_REGION
		
		ON [[GLOBAL_EDW].[Propelis].[PLANNING_PLANT].[PLNT_ID] = PLANNING_PLANT_REGION.[PLANT]
		
JOIN [GLOBAL_EDW].[Propelis].[OPERATING_PLANT_REGION] AS OPERATING_PLANT_REGION
		
		ON [GLOBAL_EDW].[Propelis].[OPERATING_PLANT].[PLNT_ID] = OPERATING_PLANT_REGION.[PLANT]
	
JOIN [GLOBAL_EDW].[Propelis].[MAINTENANCE_PLANT_REGION] AS MAINTENANCE_PLANT_REGION
		
		ON [GLOBAL_EDW].[Propelis].[MAINTENANCE_PLANT].[PLNT_ID] = MAINTENANCE_PLANT_REGION.[PLANT]
	
JOIN  [GLOBAL_EDW].[Propelis].[PARENT_CUST] AS PARENT_CUST
		
		ON [GLOBAL_EDW].[dbo].[EDW_T_B_SAL_SOIPTNR_CUR_D].[PARENT_CUST_KEY] = PARENT_CUST.[CUST_KEY]
	
JOIN [GLOBAL_EDW].[Propelis].[SO_PARENT_CUST] AS SO_PARENT_CUST
	
		ON [GLOBAL_EDW].[dbo].[EDW_T_B_SAL_SOIPTNR_CUR_D].[SO_PARENT_CUST_KEY] = SO_PARENT_CUST.[CUST_KEY]